package achievement

var mangaMilestoneDefinitions = []Definition{
	{
		Key:            "chapter_counter",
		Name:           "Chapter Counter",
		Description:    "Read {threshold} total manga chapters",
		Category:       CategoryMangaMilestone,
		MaxTier:        5,
		TierThresholds: []int{100, 500, 1000, 5000, 10000},
		TierNames:      []string{"I", "II", "III", "IV", "V"},
		Triggers:       []EvalTrigger{TriggerCollectionRefresh},
	},
	{
		Key:            "manga_collector",
		Name:           "Manga Collector",
		Description:    "Have {threshold} manga in your list",
		Category:       CategoryMangaMilestone,
		MaxTier:        5,
		TierThresholds: []int{25, 100, 250, 500, 1000},
		TierNames:      []string{"I", "II", "III", "IV", "V"},
		Triggers:       []EvalTrigger{TriggerCollectionRefresh},
	},
	{
		Key:            "manga_completionist",
		Name:           "Manga Completionist",
		Description:    "Complete {threshold} manga series",
		Category:       CategoryMangaMilestone,
		MaxTier:        5,
		TierThresholds: []int{5, 15, 30, 50, 100},
		TierNames:      []string{"I", "II", "III", "IV", "V"},
		Triggers:       []EvalTrigger{TriggerCollectionRefresh},
	},
	{
		Key:            "page_turner",
		Name:           "Page Turner",
		Description:    "Read {threshold}+ chapters in a single day",
		Category:       CategoryMangaMilestone,
		MaxTier:        5,
		TierThresholds: []int{10, 25, 50, 100, 200},
		TierNames:      []string{"I", "II", "III", "IV", "V"},
		Triggers:       []EvalTrigger{TriggerChapterRead},
	},
	{
		Key:            "bookworm",
		Name:           "Bookworm",
		Description:    "Read manga for {threshold} total hours",
		Category:       CategoryMangaMilestone,
		MaxTier:        5,
		TierThresholds: []int{10, 50, 200, 500, 1000},
		TierNames:      []string{"I", "II", "III", "IV", "V"},
		Triggers:       []EvalTrigger{TriggerSessionUpdate},
	},
}
