package achievement

var dedicationDefinitions = []Definition{
	{
		Key:            "dedicated_fan",
		Name:           "Dedicated Fan",
		Description:    "Watch {threshold}+ episodes of a single series",
		Category:       CategoryDedication,
		MaxTier:        5,
		TierThresholds: []int{50, 100, 200, 500, 1000},
		TierNames:      []string{"I", "II", "III", "IV", "V"},
		Triggers:       []EvalTrigger{TriggerEpisodeProgress},
	},
	{
		Key:            "loyal_reader",
		Name:           "Loyal Reader",
		Description:    "Read {threshold}+ chapters of a single manga",
		Category:       CategoryDedication,
		MaxTier:        5,
		TierThresholds: []int{100, 250, 500, 1000, 2000},
		TierNames:      []string{"I", "II", "III", "IV", "V"},
		Triggers:       []EvalTrigger{TriggerChapterRead},
	},
	{
		Key:            "rewatch_king",
		Name:           "Rewatch King",
		Description:    "Rewatch a series {threshold} times",
		Category:       CategoryDedication,
		MaxTier:        5,
		TierThresholds: []int{1, 3, 5, 10, 25},
		TierNames:      []string{"I", "II", "III", "IV", "V"},
		Triggers:       []EvalTrigger{TriggerSeriesComplete},
	},
	{
		Key:            "series_devotee",
		Name:           "Series Devotee",
		Description:    "Complete all entries in a franchise {threshold} times",
		Category:       CategoryDedication,
		MaxTier:        3,
		TierThresholds: []int{1, 5, 15},
		TierNames:      []string{"I", "II", "III"},
		Triggers:       []EvalTrigger{TriggerSeriesComplete},
	},
	{
		Key:            "sequel_hunter",
		Name:           "Sequel Hunter",
		Description:    "Watch a sequel within a week of completing predecessor {threshold} times",
		Category:       CategoryDedication,
		MaxTier:        5,
		TierThresholds: []int{1, 5, 15, 30, 50},
		TierNames:      []string{"I", "II", "III", "IV", "V"},
		Triggers:       []EvalTrigger{TriggerEpisodeProgress},
	},
}
