package achievement

var genreExplorerDefinitions = []Definition{
	{
		Key:            "genre_explorer",
		Name:           "Genre Explorer",
		Description:    "Watch anime from {threshold}+ different genres",
		Category:       CategoryGenreExplorer,
		MaxTier:        5,
		TierThresholds: []int{5, 10, 15, 20, 30},
		TierNames:      []string{"I", "II", "III", "IV", "V"},
		Triggers:       []EvalTrigger{TriggerCollectionRefresh},
	},
	{
		Key:            "one_genre_wonder",
		Name:           "One Genre Wonder",
		Description:    "Watch {threshold}+ anime of the same genre",
		Category:       CategoryGenreExplorer,
		MaxTier:        5,
		TierThresholds: []int{10, 25, 50, 100, 200},
		TierNames:      []string{"I", "II", "III", "IV", "V"},
		Triggers:       []EvalTrigger{TriggerCollectionRefresh},
	},
	{
		Key:            "studio_hopper",
		Name:           "Studio Hopper",
		Description:    "Watch anime from {threshold}+ different studios",
		Category:       CategoryGenreExplorer,
		MaxTier:        5,
		TierThresholds: []int{5, 15, 30, 50, 100},
		TierNames:      []string{"I", "II", "III", "IV", "V"},
		Triggers:       []EvalTrigger{TriggerCollectionRefresh},
	},
	{
		Key:            "tag_explorer",
		Name:           "Tag Explorer",
		Description:    "Encounter {threshold}+ unique tags in watched anime",
		Category:       CategoryGenreExplorer,
		MaxTier:        5,
		TierThresholds: []int{25, 50, 100, 200, 500},
		TierNames:      []string{"I", "II", "III", "IV", "V"},
		Triggers:       []EvalTrigger{TriggerCollectionRefresh},
	},
	{
		Key:            "decade_hopper",
		Name:           "Decade Hopper",
		Description:    "Watch anime from {threshold}+ different decades",
		Category:       CategoryGenreExplorer,
		MaxTier:        5,
		TierThresholds: []int{2, 3, 4, 5, 7},
		TierNames:      []string{"I", "II", "III", "IV", "V"},
		Triggers:       []EvalTrigger{TriggerCollectionRefresh},
	},
}
