package achievement

var episodeMilestoneDefinitions = []Definition{
	{
		Key:            "episode_counter",
		Name:           "Episode Counter",
		Description:    "Watch {threshold} total episodes",
		Category:       CategoryEpisodeMilestone,
		MaxTier:        5,
		TierThresholds: []int{100, 500, 1000, 5000, 10000},
		TierNames:      []string{"I", "II", "III", "IV", "V"},
		Triggers:       []EvalTrigger{TriggerCollectionRefresh},
	},
	{
		Key:            "hours_invested",
		Name:           "Hours Invested",
		Description:    "Watch {threshold} total hours of anime",
		Category:       CategoryEpisodeMilestone,
		MaxTier:        5,
		TierThresholds: []int{24, 168, 720, 2160, 8760},
		TierNames:      []string{"I", "II", "III", "IV", "V"},
		Triggers:       []EvalTrigger{TriggerCollectionRefresh},
	},
	{
		Key:            "ten_thousand",
		Name:           "Ten Thousand",
		Description:    "Watch {threshold} minutes of anime",
		Category:       CategoryEpisodeMilestone,
		MaxTier:        3,
		TierThresholds: []int{10000, 100000, 1000000},
		TierNames:      []string{"I", "II", "III"},
		Triggers:       []EvalTrigger{TriggerCollectionRefresh},
	},
	{
		Key:            "anime_collector",
		Name:           "Anime Collector",
		Description:    "Have {threshold} anime in your list",
		Category:       CategoryEpisodeMilestone,
		MaxTier:        5,
		TierThresholds: []int{25, 100, 250, 500, 1000},
		TierNames:      []string{"I", "II", "III", "IV", "V"},
		Triggers:       []EvalTrigger{TriggerCollectionRefresh},
	},
	{
		Key:            "completed_collection",
		Name:           "Completed Collection",
		Description:    "Complete {threshold} anime series",
		Category:       CategoryEpisodeMilestone,
		MaxTier:        5,
		TierThresholds: []int{10, 25, 50, 100, 250},
		TierNames:      []string{"I", "II", "III", "IV", "V"},
		Triggers:       []EvalTrigger{TriggerCollectionRefresh},
	},
}
