import { AnimeThemeConfig } from "./types"
import { GiCrossedSwords, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiCrystalBall, GiStarSwirl, GiAnvilImpact } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const ninetyOneDaysTheme: AnimeThemeConfig = {
    id: "91-days",
    displayName: "91 Days",
    description: "During Prohibition, Angelo Lagusa witnesses his family's murder by the Vanetti mafia. Seven years later, he returns under a false identity to exact revenge — infiltrating the mob that destroyed his life.",
    cssVars: {
        "--color-brand-200": "210 190 165",
        "--color-brand-300": "182 155 118",
        "--color-brand-400": "150 118 72",
        "--color-brand-500": "118 85 38",
        "--color-brand-600": "88 58 18",
        "--color-brand-700": "60 36 6",
        "--color-brand-800": "38 20 1",
        "--color-brand-900": "18 8 0",
        "--color-brand-950": "7 2 0",
        "--brand": "118 85 38",
        "--background": "#050200",
        "--paper": "#0a0400",
        "--color-gray-950": "5 2 0",
        "--color-gray-900": "14 6 1",
        "--color-gray-800": "28 14 3",
        "--color-gray-700": "48 26 7",
        "--color-gray-600": "75 44 14",
        "--color-gray-500": "112 72 28",
        "--color-gray-400": "155 112 55",
        "--color-gray-300": "198 158 92",
        "--color-gray-200": "230 198 138",
        "--color-gray-100": "248 228 188",
        "--color-gray-50": "255 245 232",
    },
    sidebarOverrides: {
        "home": { icon: GiCrossedSwords, label: "Lawless Town" },
        "schedule": { icon: GiAlarmClock, label: "Revenge Plan" },
        "manga": { icon: LuBookOpen, label: "Case Files" },
        "lists": { icon: GiScrollUnfurled, label: "Target List" },
        "discover": { icon: GiBullseye, label: "New Intel" },
        "torrent-list": { icon: GiAnvilImpact, label: "Weapon Cache" },
        "debrid": { icon: GiHeartKey, label: "Secret Vault" },
        "unmatched": { icon: GiCrystalBall, label: "Unknown Targets" },
        "enmasse": { icon: GiResize, label: "Mob War" },
        "scan-summaries": { icon: TbReportSearch, label: "Revenge Reports" },
        "auto-downloader": { icon: LuRss, label: "Intel Feed" },
        "community": { icon: GiStarSwirl, label: "91 Days Circle" },
        "achievements": { icon: GiTrophyCup, label: "Revenge Trophies" },
        "milestones": { icon: LuFlag, label: "Revenge Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Danger Alerts" },
        "theme-manager": { icon: GiPalette, label: "Sepia Colors" },
        "extensions": { icon: BiExtension, label: "Mob Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Shadow Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Angelo Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "The Letter",
        "a_episode_counter": "Revenge Mark",
        "a_episode_titan": "Revenge Relic",
        "a_hours_invested": "Vanetti Proof",
        "a_time_lord": "Revenge Plan Decree",
        "a_anime_collector": "During Prohibition Catalogue",
        "a_library_legend": "Letter Library",
        "a_first_complete": "First Target",
        "a_hundred_club": "Hundred Revenge Days",
        "a_first_day": "Weapon Seal",
        "a_first_rating": "Archive Appraisal",
        "a_ten_thousand_min": "Lawless Town Standard",
        "a_season_veteran": "Orphan Avenger Library",
        "a_year_explorer": "Angelo Lagusa Map",
        "a_century_watcher": "Prohibition Fan Ledger",
        "a_five_hundred_eps": "Archive Dominion",
        "a_thousand_eps": "During Prohibition Record",
        "a_watching_ten": "Unknown Targets Acclaim",
        "a_ptw_hoarder": "Prohibition Library",
        "a_dropped_honesty": "Orphan Avenger Summit",
        "a_five_thousand_eps": "Revenge Warrant",
        "a_ten_completed": "Mob Afterglow",
        "a_fifty_completed": "Intel Ascension",
        "a_five_hundred_completed": "Case Clear",
        "a_mean_score_tracker": "Angelo Lagusa Verdict",
        "a_unique_studios": "Revenge Served Collection",
        "a_days_spent_watching": "Mob Dominion",
        "a_all_status": "Intel Testament",
        "a_first_favorite": "Vanetti Cabinet",
        "a_favorites_collector": "Secret Vault Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Letter Drive",
        "a_marathon_runner": "Angelo Lagusa Gauntlet",
        "a_weekend_warrior": "Prohibition Ordeal",
        "a_non_stop": "Shadow Fever",
        "a_one_more_episode": "Revenge Mantle",
        "a_speed_run": "Avenger Vigil",
        "a_double_feature": "Vanetti Crown",
        "a_triple_threat": "Marathon Record",
        "a_five_a_day": "Weapon Accord",
        "a_back_to_back": "Case Surge",
        "a_seasonal_binge": "Unknown Targets Cascade",
        "a_cour_crusher": "Avenger Ordeal",
        "a_half_day_watch": "Circle Crown",
        "a_full_day_watch": "Marathon Pinnacle",
        "a_power_weekend": "Case Run",
        "a_binge_king": "91 Days Marathon",
        "a_no_sleep": "Circle Vigil",
        "a_entire_season": "Prohibition Library Library",
        "a_seven_day_challenge": "During Prohibition Mark",
        "a_hundred_day_binge": "Secret Vault Surge",
        "a_genre_binge": "Secret Vault Binge",
        "a_studio_binge": "Intel Fever",
        "a_season_sweep": "Mob Codex",
        "a_forty_eight_hour": "Mob War Overture",
        "a_ep_counter_day": "Orphan Avenger Aegis",
        "a_multi_series_binge": "Vanetti Streak",
        "a_midnight_binge": "Secret Vault Cascade",
        "a_new_year_binge": "Marathon Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Lawless Town Action",
        "a_genre_adventure": "Prohibition Adventure",
        "a_genre_comedy": "Secret Vault Comedy",
        "a_genre_drama": "Weapon Drama",
        "a_genre_fantasy": "Prohibition Fantasy",
        "a_genre_horror": "Unknown Targets Horror",
        "a_genre_mystery": "Weapon Mystery",
        "a_genre_romance": "Sepia Romance",
        "a_genre_scifi": "Weapon Sci-Fi",
        "a_genre_sol": "Unknown Targets Slice",
        "a_genre_sports": "Revenge Plan Sports",
        "a_genre_supernatural": "Vanetti Supernatural",
        "a_genre_thriller": "Shadow Thriller",
        "a_genre_mecha": "Archive Mecha",
        "a_genre_music": "Revenge Plan Music",
        "a_genre_psychological": "Lawless Town Psychological",
        "a_genre_ecchi": "Revenge Ecchi",
        "a_genre_mahou_shoujo": "Danger Alerts Magic Shoujo",
        "a_tag_isekai": "Avenger Isekai",
        "a_tag_harem": "Letter Harem",
        "a_tag_bl": "Weapon Bl",
        "a_tag_gl": "Target Gl",
        "a_tag_historical": "Orphan Historical",
        "a_tag_military": "Target Military",
        "a_tag_school": "Vanetti School",
        "a_tag_martial_arts": "Unknown Targets Martial Arts",
        "a_tag_vampire": "Prohibition Fan Vampire",
        "a_tag_samurai": "Circle Samurai",
        "a_tag_space": "Revenge Space",
        "a_tag_parody": "Revenge Parody",
        "a_tag_idol": "Prohibition Fan Idol",
        "a_tag_post_apocalyptic": "Prohibition Post Apocalyptic",
        "a_tag_cyberpunk": "Unknown Targets Cyberpunk",
        "a_tag_shounen": "Served Shounen",
        "a_tag_seinen": "91 Days Seinen",
        "a_tag_shoujo": "Danger Alerts Shoujo",
        "a_tag_josei": "Prohibition Fan Josei",
        "a_tag_survival": "Revenge Trophies Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "Revenge Served",
        "a_mega_completionist": "91 Days Complete",
        "a_completion_rate_50": "Angelo Return",
        "a_completion_rate_75": "Marathon Crown",
        "a_completion_rate_90": "Intel Resolution",
        "a_no_drop": "Orphan Decree",
        "a_long_runner_complete": "Orphan Clear",
        "a_sequel_chain": "Orphan Avenger Insignia",
        "a_clean_list": "Revenge Trophies Relic",
        "a_from_ptw": "Danger Alerts Index",
        "a_rewatch_master": "Case Return",
        "a_short_complete": "During Prohibition Endgame",
        "a_same_day_start_finish": "Orphan Pinnacle",
        "a_revival": "Prohibition Insignia",
        "a_zero_to_hero": "Orphan to Avenger",
        "a_five_genre_complete": "Shadow A Five Genre Complete",
        "a_full_franchise": "Angelo Chronicle",
        "a_batch_complete": "Revenge Served Crown",
        "a_paused_to_done": "Served Aegis",
        "a_completion_spree": "Danger Alerts Triumph",
        "a_multi_rewatch": "Served Triumph",
        "a_dropped_recovery": "Intel Conquest",
        "a_ten_perfect_scores": "Danger Alerts Acclaim",
        "a_seasonal_clear": "Revenge Codex",
        "a_complete_genre_span": "Target A Complete Genre Span",
        "a_monthly_completions": "Unknown Targets Afterglow",
        "a_yearly_completions": "Angelo Lagusa Epilogue",
        "a_rapid_complete": "Revenge Plan Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Prohibition Fan",
        "a_studio_devotee": "Sepia Treasury",
        "a_rewatcher": "Avenger Closure",
        "a_triple_rewatch": "Orphan Coda",
        "a_annual_tradition": "Revenge Trophies Proof",
        "a_director_fan": "Shadow Trial",
        "a_voice_actor_fan": "Orphan Crown",
        "a_ost_lover": "Unknown Targets Seal",
        "a_source_reader": "Intel Cabinet",
        "a_waiting_weekly": "Danger Alerts Clock",
        "a_childhood_revisit": "During Prohibition Seal",
        "a_saga_tracker": "Letter Standard",
        "a_genre_loyalty": "Secret Vault Loyalty",
        "a_decade_watcher": "Served Banner",
        "a_adaptation_hunter": "Orphan Trial",
        "a_original_anime_fan": "Served Testament",
        "a_long_commitment": "Served Mark",
        "a_perfect_attendance": "Circle Standard",
        "a_favorite_studio_5": "Revenge Served Library",
        "a_complete_catalog": "Intel Seal",
        "a_franchise_collector": "Revenge Plan Archive",
        "a_airing_follower": "Revenge Trophies Signal",
        "a_genre_master": "Mob Master",
        "a_staff_follower": "Case Oath",
        "a_multi_season_fan": "Marathon Hoard",
        "a_format_diversity": "Prohibition Fan Cache",
        "a_year_dedication": "Lawless Town Tenure",
        "a_season_dedication": "Orphan Avenger Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Orphan Avenger Explorer",
        "a_studio_hopper": "Vanetti Collection",
        "a_tag_explorer": "Orphan Explorer",
        "a_decade_hopper": "Revenge Plan Chronicle",
        "a_hidden_gem": "Lawless Town Warrant",
        "a_popular_taste": "Marathon Decree",
        "a_retro_appreciator": "Letter Aegis",
        "a_modern_viewer": "Orphan Avenger Pinnacle",
        "a_cross_demographic": "Weapon Pinnacle",
        "a_underdog_fan": "Revenge Trophies Trial",
        "a_variety_week": "Revenge Horizon",
        "a_foreign_cinema": "Avenger Expedition",
        "a_classic_connoisseur": "Avenger Glimpse",
        "a_every_season": "Letter Archive",
        "a_award_winner": "Target Insignia",
        "a_niche_explorer": "Lawless Town Horizon",
        "a_global_anime": "Weapon Crown",
        "a_cult_classic": "Angelo Lagusa Classic",
        "a_random_pick": "Danger Alerts Decree",
        "a_new_genre_month": "Revenge A New Genre Month",
        "a_seasonal_completionist": "Weapon Summit",
        "a_unpopular_opinion": "Weapon Standard",
        "a_top_rated_viewer": "Orphan Seal",
        "a_source_variety": "Shadow Storehouse",
        "a_low_score_brave": "Mob War Measure",
        "a_upcoming_watcher": "Revenge Served Seal",
        "a_short_series_explorer": "91 Days Expedition",
        "a_long_series_explorer": "Prohibition Fan Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Secret Vault Insignia",
        "a_early_bird": "Revenge Served Banner",
        "a_lunch_break": "Avenger Trial",
        "a_golden_hour": "91 Days Tenure",
        "a_four_am_club": "Archive Gathering",
        "a_witching_hour": "Secret Vault Tenure",
        "a_new_year_watch": "Intel Season",
        "a_midnight_premiere": "During Prohibition Devotion",
        "a_all_hours": "Target Seal",
        "a_dawn_warrior": "Avenger Aegis",
        "a_afternoon_delight": "Secret Vault Proof",
        "a_prime_time": "Intel Insignia",
        "a_workday_watcher": "Danger Alerts Pinnacle",
        "a_sunday_marathon": "Shadow Momentum",
        "a_rainy_day": "Mob War Relic",
        "a_morning_routine": "Lawless Town Promise",
        "a_night_shift": "Unknown Targets Aegis",
        "a_twilight_zone": "Revenge Plan Ledger",
        "a_seasonal_premier": "Angelo Lagusa Cabinet",
        "a_clock_collector": "Shadow Repository",
        "a_weekend_binge_hours": "Prohibition Fan Streak",
        "a_late_night_regular": "Sepia Dominion",
        "a_sunrise_watcher": "Angelo Lagusa Relic",
        "a_holiday_watcher": "Avenger Pact",
        "a_every_day_of_week": "Revenge Ledger",
        "a_monthly_hours": "Vanetti Monthly",

        // ── ANIME SOCIAL ──
        "a_first_party": "Served Record",
        "a_party_host": "Target Record",
        "a_social_butterfly": "Danger Alerts Company",
        "a_group_binge": "Revenge Plan Sprint",
        "a_party_regular": "Secret Vault Chronicle",
        "a_sync_viewer": "During Prohibition Standard",
        "a_commentator": "Revenge Trophies Record",
        "a_party_marathon": "Mob War Vigil",
        "a_full_house": "Prohibition Fan Trial",
        "a_community_pillar": "Prohibition Alliance",
        "a_watch_party_streak": "Weapon Vigil",
        "a_diverse_party": "Danger Alerts Seal",
        "a_late_night_party": "Served Testament Testament",
        "a_party_veteran": "Angelo Lagusa Testament",
        "a_genre_party": "Case Party",
        "a_weekly_party": "Revenge Served Calendar",
        "a_silent_viewer": "Prohibition Fan Mantle",
        "a_recommendation_giver": "Orphan Avenger Network",
        "a_party_completionist": "Avenger Coda",
        "a_social_scorer": "Orphan Avenger Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Archive Proof",
        "a_fibonacci": "Archive Dominion Dominion",
        "a_palindrome_day": "Mob Relic",
        "a_binary_day": "Revenge Plan Mark",
        "a_full_moon": "Prohibition Fan Insignia",
        "a_leap_year": "91 Days Devotion",
        "a_time_traveler": "Revenge Record",
        "a_genre_clash": "Revenge Plan Clash",
        "a_triple_seven": "Orphan Testament",
        "a_thousand_complete": "Orphan Epilogue",
        "a_pi_episodes": "Avenger Crown",
        "a_synchronicity": "Served Anchor",
        "a_world_record": "Mob Warrant",
        "a_nice": "Mob War Chronicle",
        "a_power_level": "Target Testament",
        "a_answer_42": "Prohibition Standard",
        "a_square_number": "Danger Alerts Decree Decree",
        "a_prime_count": "Prohibition Fan Seal",
        "a_matching_date": "Orphan Mantle",
        "a_century_episode": "Served Mark Mark",
        "a_double_digits": "Lawless Town Testament",
        "a_one_two_three": "Revenge Served Crown Crown",
        "a_lucky_seven": "Weapon Crown Crown",
        "a_all_tens": "Shadow Criterion",
        "a_exact_hundred_eps": "Target Standard",
        "a_year_match_count": "Angelo Clock",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Angelo Lagusa Ledger",
        "a_movie_buff": "Archive Mark",
        "a_ova_hunter": "Case Standard",
        "a_ona_explorer": "Weapon Secret",
        "a_special_watcher": "Unknown Targets Relic",
        "a_short_king": "Circle Crown Crown",
        "a_variety_pack": "Letter Inquiry",
        "a_film_festival": "Revenge Plan Chronicle Chronicle",
        "a_music_video": "Circle Chronicle",
        "a_tv_short": "Angelo Record",
        "a_movie_marathon": "Marathon Gauntlet",
        "a_double_length": "Unknown Targets Crown",
        "a_anthology": "Circle Aegis",
        "a_mini_series": "Shadow Decree",
        "a_theatrical": "Lawless Town Accord",
        "a_format_master": "Intel Vault",
        "a_long_movie": "Target Insignia Insignia",
        "a_back_catalog": "Lawless Town Standard Standard",
        "a_cm_watcher": "Letter Aegis Aegis",
        "a_pv_collector": "Target Storehouse",
        "a_format_balance": "Angelo Vault",
        "a_episodic_master": "Orphan Avenger Standard",
        "a_sequel_movie": "Prohibition Fan Pinnacle",
        "a_recap_watcher": "Marathon Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Danger Alerts Devotion",
        "a_mega_streak": "Archive Streak",
        "a_weekly_warrior": "Orphan Season",
        "a_monthly_watcher": "Angelo Lagusa Calendar",
        "a_comeback": "Weapon Decree",
        "a_weekend_streak": "Revenge Trophies Passage",
        "a_no_zero_days": "Case Warrant",
        "a_iron_will": "Prohibition Seal",
        "a_habit_formed": "Intel Warrant",
        "a_consistent_pace": "Prohibition Fan Measure",
        "a_year_long": "Angelo Lagusa Season",
        "a_double_streak": "Marathon Watch",
        "a_streak_recovery": "Case Season",
        "a_daily_minimum": "Unknown Targets Focus",
        "a_winter_streak": "Lawless Town Watch",
        "a_summer_streak": "Weapon Resolve",
        "a_morning_streak": "Target Clock",
        "a_night_streak": "Target Constancy",
        "a_unbreakable": "Marathon Proof",
        "a_eternal_flame": "Avenger Standard",
        "a_completion_streak": "Revenge Plan Return",
        "a_rating_streak": "Sepia Balance",
        "a_multi_ep_streak": "91 Days Ritual",
        "a_genre_streak": "During Prohibition Streak",
        "a_studio_streak": "Prohibition Cabinet",
        "a_perfect_week": "Prohibition Fan Relic",

        // ── ANIME SCORING ──
        "a_critic": "Circle Scrutiny",
        "a_perfect_ten": "Revenge Audit",
        "a_harsh_critic": "Angelo Lagusa Gauge",
        "a_fair_judge": "Revenge Served Balance",
        "a_generous_spirit": "Archive Pinnacle",
        "a_score_all": "Marathon Criterion",
        "a_wide_range": "During Prohibition Ledger",
        "a_controversial": "Mob War Decree",
        "a_consistent_scorer": "Avenger Verdict",
        "a_score_sniper": "Marathon Score",
        "a_evolving_taste": "Mob Testament",
        "a_bell_curve": "Revenge Insignia",
        "a_picky_watcher": "Orphan Seal Seal",
        "a_100_rated": "Archive Warrant",
        "a_500_rated": "Orphan Pinnacle Pinnacle",
        "a_mediocre_majority": "Vanetti Canon",
        "a_rating_spree": "Orphan Avenger Review",
        "a_score_variance": "Orphan Avenger Score",
        "a_masterpiece_hunter": "During Prohibition Banner",
        "a_contrarian": "Revenge Plan Record",
        "a_optimist": "Letter Ledger",
        "a_score_distributor": "Revenge Plan Appraisal",
        "a_genre_critic": "Weapon Critic",
        "a_mean_above_8": "Served Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "Unknown Targets Resolve",
        "a_valentines_weeb": "During Prohibition Vow",
        "a_pi_day": "Revenge Trophies Trial Trial",
        "a_april_fools": "Shadow Devotion",
        "a_international_anime_day": "Marathon Pinnacle Pinnacle",
        "a_star_wars_day": "Unknown Targets Chronicle",
        "a_summer_solstice": "Revenge Served Calendar Calendar",
        "a_tanabata": "Orphan Focus",
        "a_friday_13th": "Mob Relic Relic",
        "a_halloween_spirit": "Angelo Vow",
        "a_thanksgiving_binge": "Mob War Run",
        "a_christmas_special": "Shadow Season",
        "a_new_years_eve": "Mob War Pilgrimage",
        "a_birthday_watch": "Weapon Vow",
        "a_holiday_marathon": "Case Overture",
        "a_independence_day": "Prohibition Fan Banner",
        "a_culture_day": "Prohibition Insignia Insignia",
        "a_spring_equinox": "Case Decree",
        "a_earth_day": "Revenge Plan Record Record",
        "a_labor_day": "Case Seal",
        "a_winter_solstice": "Angelo Pilgrimage",
        "a_anime_birthday": "Lawless Town Pilgrimage",
        "a_every_holiday": "Prohibition Fan Resolve",
        "a_consecutive_holidays": "Circle Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "During Prohibition Rank",
        "a_meta_collector": "Prohibition Hoard",
        "a_meta_category_starter": "Archive Badge",
        "a_meta_tier_climber": "Angelo Glyph",
        "a_meta_tier_max": "Danger Alerts Writ",
        "a_meta_xp_earner": "Revenge Served Emblem",
        "a_meta_difficulty_easy": "Mob War Mechanism",
        "a_meta_difficulty_hard": "Revenge Plan Writ",
        "a_meta_unlock_spree": "91 Days Panel",
        "a_meta_completionist": "Mob War Fulfillment",
        "a_meta_diverse": "Shadow Emblem",
        "a_meta_dominator": "Target Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "Day One",
        "m_chapter_counter": "Mob War Pinnacle",
        "m_chapter_titan": "Mob War Legend",
        "m_reading_hours": "Circle Relic",
        "m_reading_time_lord": "Mob War Pinnacle Pinnacle",
        "m_manga_collector": "Mob War Ledger",
        "m_library_legend": "Mob Reliquary",
        "m_first_complete": "Avenger Triumph",
        "m_hundred_club": "Orphan Avenger Legend",
        "m_first_day": "Target Dawn",
        "m_first_rating": "Prohibition Fan Eye",
        "m_ten_thousand_pages": "Unknown Targets Gauge",
        "m_volume_collector": "Secret Vault Storehouse",
        "m_year_explorer": "Revenge Trophies Quest",
        "m_century_reader": "Lawless Town Dominion",
        "m_five_hundred_ch": "Revenge Plan Legend",
        "m_thousand_ch": "Case Testament",
        "m_reading_ten": "Archive Tenfold",
        "m_ptr_hoarder": "Circle Index",
        "m_dropped_honesty": "Revenge Summit",
        "m_season_reader": "Mob Treasury",
        "m_active_reader": "Target Trial",
        "m_five_thousand_ch": "91 Days Standard",
        "m_ten_completed": "Lawless Town Resolution",
        "m_fifty_completed": "Unknown Targets Harvest",
        "m_five_hundred_completed": "Revenge Served Legacy",
        "m_mean_score_tracker": "Marathon Audit",
        "m_unique_authors": "Unknown Targets Reserve",
        "m_all_status": "Sepia Testament",
        "m_first_favorite": "Revenge Served Cache",
        "m_favorites_collector": "Archive Shelf",
        "m_days_spent_reading": "Vanetti Decree",

        // ── MANGA BINGE ──
        "m_binge_reader": "Secret Vault Streak",
        "m_marathon_reader": "91 Days Rush",
        "m_weekend_reader": "Orphan Avenger Run",
        "m_non_stop_reading": "Lawless Town Gauntlet",
        "m_one_more_chapter": "Unknown Targets Testament",
        "m_speed_read": "Target Drive",
        "m_double_story": "Orphan Avenger Banner",
        "m_triple_read": "Intel Record",
        "m_five_a_day": "Orphan Avenger Insignia Insignia",
        "m_chapter_chain": "Intel Accord",
        "m_volume_binge": "Target Drive Drive",
        "m_power_reader": "Revenge Seal",
        "m_half_day_read": "Archive Aegis",
        "m_full_day_read": "Revenge Aegis",
        "m_power_weekend": "Unknown Targets Streak",
        "m_binge_king": "Case Momentum",
        "m_no_sleep_read": "Unknown Targets Rush",
        "m_full_series_rush": "Danger Alerts Cascade",
        "m_seven_day_challenge": "During Prohibition Warrant",
        "m_hundred_day_read": "Marathon Relic",
        "m_volume_rush": "Lawless Town Gauntlet Gauntlet",
        "m_series_sweep": "Vanetti Trial",
        "m_genre_binge": "Revenge Served Binge",
        "m_author_binge": "Mob Surge",
        "m_chapter_counter_day": "Archive Ledger",
        "m_multi_series_binge": "Prohibition Charge",
        "m_midnight_binge": "Secret Vault Tempest",
        "m_new_year_binge": "91 Days Passage",
        "m_forty_eight_hour": "Angelo Rally",
        "m_oneshot_binge": "Revenge Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Angelo Lagusa Action",
        "m_genre_adventure": "Vanetti Adventure",
        "m_genre_comedy": "Revenge Comedy",
        "m_genre_drama": "Letter Drama",
        "m_genre_fantasy": "Prohibition Fantasy Style",
        "m_genre_horror": "Mob War Horror",
        "m_genre_mystery": "Lawless Town Mystery",
        "m_genre_romance": "Circle Romance",
        "m_genre_scifi": "Revenge Served Sci-Fi",
        "m_genre_sol": "Avenger Slice",
        "m_genre_sports": "Weapon Sports",
        "m_genre_supernatural": "Orphan Avenger Supernatural",
        "m_genre_thriller": "Orphan Avenger Thriller",
        "m_genre_psychological": "Letter Psychological",
        "m_genre_isekai": "Orphan Isekai",
        "m_genre_shounen": "Circle Shounen",
        "m_genre_ecchi": "Vanetti Ecchi",
        "m_genre_mahou_shoujo": "Letter Magic Shoujo",
        "m_genre_mecha": "Prohibition Mecha",
        "m_genre_music": "Served Music",
        "m_tag_isekai_new": "Letter Isekai New",
        "m_tag_harem": "91 Days Harem",
        "m_tag_bl": "Prohibition Bl",
        "m_tag_gl": "Marathon Gl",
        "m_tag_historical": "Angelo Lagusa Historical",
        "m_tag_military": "Sepia Military",
        "m_tag_school": "Revenge Plan School",
        "m_tag_martial_arts": "Target Martial Arts",
        "m_tag_vampire": "Intel Vampire",
        "m_tag_samurai": "During Prohibition Samurai",
        "m_tag_space": "Letter Space",
        "m_tag_parody": "Circle Parody",
        "m_tag_idol": "Lawless Town Idol",
        "m_tag_post_apocalyptic": "Orphan Avenger Post Apocalyptic",
        "m_tag_cyberpunk": "Lawless Town Cyberpunk",
        "m_tag_shoujo": "Weapon Shoujo",
        "m_tag_survival": "Angelo Survival",
        "m_tag_cooking": "Letter Cooking",
        "m_tag_medical": "Prohibition Fan Medical",
        "m_tag_villainess": "During Prohibition Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Manga Archive",
        "m_mega_completionist": "Danger Alerts Resolution",
        "m_completion_rate_50": "Case Return Return",
        "m_completion_rate_75": "Archive Ascension",
        "m_completion_rate_90": "Secret Vault Resolution",
        "m_no_drop": "Circle Decree",
        "m_long_runner_complete": "Intel Clear",
        "m_sequel_chain": "Served Seal",
        "m_clean_list": "Angelo Lagusa Relic Relic",
        "m_from_ptr": "Angelo Lagusa Accord",
        "m_reread_master": "Shadow Trial Trial",
        "m_oneshot_complete": "Secret Vault Ascension",
        "m_same_day_start_finish": "Orphan Crown Crown",
        "m_revival": "Danger Alerts Accord",
        "m_zero_to_hundred": "Weapon Banner",
        "m_five_genre_complete": "Weapon M Five Genre Complete",
        "m_full_collection": "Revenge Trophies Proof Proof",
        "m_batch_complete": "Revenge Trophies Testament",
        "m_paused_to_done": "Mob War Standard",
        "m_completion_spree": "Avenger Triumph Triumph",
        "m_format_completionist": "Revenge Served Testament",
        "m_catch_up": "Vanetti Chronicle",
        "m_multi_reread": "Case Banner",
        "m_dropped_recovery": "Danger Alerts Conquest",
        "m_ten_perfect_scores": "Secret Vault Judgment",
        "m_complete_genre_span": "Prohibition M Complete Genre Span",
        "m_monthly_completions": "Prohibition Return",
        "m_yearly_completions": "91 Days Epilogue",
        "m_rapid_complete": "Case Finale",
        "m_author_complete": "Orphan Clear Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "91 Days Legacy",
        "m_mangaka_lover": "Secret Vault Standard",
        "m_rereader": "Sepia Relic",
        "m_triple_reread": "Archive Testament",
        "m_annual_reread": "Orphan Banner",
        "m_publisher_fan": "Target Mark",
        "m_artist_fan": "Weapon Insignia",
        "m_adaptation_compare": "Angelo Lagusa Insignia",
        "m_source_material_fan": "During Prohibition Cache",
        "m_waiting_weekly": "91 Days Streak",
        "m_classic_reader": "Angelo Lantern",
        "m_saga_reader": "Revenge Crown",
        "m_genre_loyalty": "Case Loyalty",
        "m_decade_reader": "Mob War Warrant",
        "m_ln_adaptation": "Angelo Lagusa Mark",
        "m_original_work": "Served Standard",
        "m_long_commitment": "During Prohibition Mark Mark",
        "m_up_to_date": "91 Days Warrant",
        "m_favorite_mangaka": "Target Treasury",
        "m_complete_portfolio": "Served Triumph Triumph",
        "m_franchise_collector": "Revenge Served Archive",
        "m_serialization_follower": "Circle Handshake",
        "m_genre_master": "91 Days Master",
        "m_multi_series_author": "Letter Insignia",
        "m_format_diversity": "Danger Alerts Shelf",
        "m_year_dedication": "Orphan Avenger Tenure",
        "m_ongoing_follower": "Lawless Town Fellowship",
        "m_genre_loyalty_50": "Revenge Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Revenge Trophies Explorer",
        "m_publisher_hopper": "Unknown Targets Record",
        "m_tag_explorer": "During Prohibition Explorer",
        "m_decade_hopper": "Orphan Chronicle",
        "m_hidden_gem": "Mob War Mark",
        "m_popular_taste": "Vanetti Record",
        "m_retro_reader": "Target Testament Testament",
        "m_modern_reader": "91 Days Seal",
        "m_cross_demographic": "Danger Alerts Crown",
        "m_underdog_fan": "Mob War Testament",
        "m_variety_week": "Intel Horizon",
        "m_manhwa_reader": "Mob War Proof",
        "m_manhua_reader": "Lawless Town Mantle",
        "m_classic_connoisseur": "Letter Glimpse",
        "m_award_winner": "Circle Seal",
        "m_niche_explorer": "Case Horizon",
        "m_world_manga": "Mob War Chronicle Chronicle",
        "m_cult_classic": "Archive Map",
        "m_random_pick": "Mob Standard",
        "m_new_genre_month": "Case M New Genre Month",
        "m_year_completionist": "Orphan Fulfillment",
        "m_unpopular_opinion": "Intel Aegis",
        "m_top_rated_reader": "Angelo Lagusa Pinnacle",
        "m_source_variety": "Target Catalogue",
        "m_low_score_brave": "Served Score",
        "m_short_manga_explorer": "Danger Alerts Compass",
        "m_long_manga_explorer": "Case Survey",
        "m_serialization_explorer": "Letter Road",

        // ── MANGA TIME ──
        "m_night_owl": "Prohibition Fan Accord",
        "m_early_bird": "During Prohibition Banner Banner",
        "m_lunch_reader": "Revenge Served Relic",
        "m_commute_reader": "Prohibition Fan Tenure",
        "m_four_am_club": "Secret Vault Fellowship",
        "m_new_year_read": "Archive Pact",
        "m_all_hours": "Prohibition Fan Accord Accord",
        "m_prime_time_reader": "Lawless Town Banner",
        "m_workday_reader": "During Prohibition Accord",
        "m_sunday_read": "Circle Standard Standard",
        "m_morning_routine": "Angelo Discipline",
        "m_night_shift_reader": "During Prohibition Accord Accord",
        "m_seasonal_premier_read": "Circle Storehouse",
        "m_clock_collector": "Danger Alerts Reserve",
        "m_late_night_horror": "Archive Mark Mark",
        "m_afternoon_reader": "Revenge Mantle Mantle",
        "m_golden_hour_reader": "Archive Observance",
        "m_dawn_reader": "Circle Mantle",
        "m_twilight_reader": "Case Decree Decree",
        "m_midnight_start": "Intel Routine",
        "m_weekend_binge_hours": "Orphan Momentum",
        "m_late_night_regular": "Danger Alerts Testament",
        "m_sunrise_reader": "Angelo Record Record",
        "m_every_day_of_week": "Target Seal Seal",
        "m_monthly_hours": "Target Vigil",
        "m_bedtime_reader": "Orphan Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Lawless Town Mantle Mantle",
        "m_webtoon_reader": "91 Days Mark",
        "m_full_color": "Sepia Accord",
        "m_doujin_reader": "Prohibition Fan Record",
        "m_anthology_reader": "Revenge Plan Accord",
        "m_adaptation_reader": "Revenge Plan Banner",
        "m_longstrip_reader": "Circle Trial",
        "m_4koma_reader": "Archive Relic",
        "m_oneshot_reader": "Served Mantle",
        "m_format_variety": "Revenge Trophies Gallery",
        "m_light_novel_reader": "Avenger Insignia",
        "m_novel_reader": "91 Days Crown",
        "m_visual_storyteller": "91 Days Testament",
        "m_colored_classic": "Target Survey",
        "m_webcomic_fan": "Mob Insignia",
        "m_manga_to_anime": "Mob War Record",
        "m_seinen_reader": "Case Pinnacle",
        "m_josei_reader": "Letter Pinnacle",
        "m_award_winning_art": "Secret Vault Relic",
        "m_debut_work": "Revenge Trophies Dominion",
        "m_vertical_scroll": "Prohibition Crown",
        "m_traditional_format": "Revenge Trophies Hoard",
        "m_cross_media": "Secret Vault Accord",
        "m_spinoff_reader": "Angelo Accord",
        "m_remake_reader": "Served Pinnacle",
        "m_collaboration_reader": "Intel Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Orphan Avenger Focus",
        "m_mega_streak": "Unknown Targets Routine",
        "m_weekly_warrior": "Prohibition Season",
        "m_monthly_reader": "Angelo Lagusa Discipline",
        "m_comeback": "Shadow Standard",
        "m_weekend_streak": "During Prohibition Fever",
        "m_no_zero_days": "Prohibition Fan Proof",
        "m_iron_will": "Weapon Ledger",
        "m_habit_formed": "Prohibition Decree",
        "m_consistent_pace": "Letter Scrutiny",
        "m_year_long": "Prohibition Observance",
        "m_double_streak": "Sepia Resolve",
        "m_streak_recovery": "Revenge Served Resolve",
        "m_daily_minimum": "Avenger Focus",
        "m_winter_streak": "Circle Observance",
        "m_summer_streak": "Vanetti Observance",
        "m_morning_streak": "Orphan Clock",
        "m_night_streak": "Angelo Discipline Discipline",
        "m_unbreakable": "Angelo Warrant",
        "m_eternal_flame": "Orphan Avenger Record",
        "m_chapter_a_day": "Orphan Relic",
        "m_genre_streak": "Prohibition Fan Streak Mode",
        "m_completion_streak": "Mob War Return",
        "m_rating_streak": "Circle Appraisal",
        "m_multi_ch_streak": "Mob War Tenure",
        "m_author_streak": "Prohibition Calendar",
        "m_perfect_week_manga": "Case Accord",
        "m_diverse_streak": "Marathon Streak",

        // ── MANGA SCORING ──
        "m_critic": "Unknown Targets Scrutiny",
        "m_perfect_ten": "During Prohibition Verdict",
        "m_harsh_critic": "Vanetti Scale",
        "m_fair_judge": "Shadow Eye",
        "m_generous_spirit": "Intel Crown",
        "m_score_all": "Revenge Plan Reckoning",
        "m_wide_range": "Prohibition Fan Ledger Ledger",
        "m_controversial": "Unknown Targets Testament Testament",
        "m_consistent_scorer": "Shadow Grade",
        "m_score_sniper": "Avenger Reckoning",
        "m_evolving_taste": "Intel Trial",
        "m_bell_curve": "Secret Vault Accord Accord",
        "m_picky_reader": "Sepia Relic Relic",
        "m_100_rated": "Case Mark",
        "m_500_rated": "Orphan Avenger Proof",
        "m_mediocre_majority": "Avenger Canon",
        "m_rating_spree": "Lawless Town Verdict",
        "m_score_variance": "Secret Vault Measure",
        "m_binge_rater": "Avenger Passage",
        "m_reread_rerate": "Orphan Avenger Banner Banner",
        "m_masterpiece_hunter": "Intel Banner",
        "m_contrarian": "Mob Aegis",
        "m_optimist": "Mob Accord",
        "m_score_distributor": "Angelo Lagusa Balance",
        "m_genre_critic": "Avenger Critic",
        "m_mean_above_8": "Revenge Trophies Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Shadow New Year",
        "m_valentines_read": "Danger Alerts Observance",
        "m_pi_day": "Vanetti Testament",
        "m_april_fools": "Letter Devotion",
        "m_international_manga_day": "Circle Proof",
        "m_free_comic_day": "Sepia Chronicle",
        "m_summer_solstice": "Avenger Focus Focus",
        "m_tanabata": "Prohibition Pilgrimage",
        "m_friday_13th": "Letter Dominion",
        "m_halloween_read": "Secret Vault Calendar",
        "m_thanksgiving_binge": "Angelo Lagusa Charge",
        "m_christmas_read": "Revenge Trophies Pact",
        "m_new_years_eve": "Circle Pilgrimage",
        "m_birthday_read": "Mob Focus",
        "m_holiday_marathon": "Weapon Rally",
        "m_independence_day": "Target Aegis",
        "m_culture_day": "Shadow Seal",
        "m_spring_equinox": "Angelo Banner",
        "m_earth_day": "91 Days Aegis",
        "m_labor_day": "Angelo Seal",
        "m_winter_solstice": "91 Days Focus",
        "m_manga_birthday": "Revenge Ritual",
        "m_every_holiday_reader": "Revenge Trophies Watch",
        "m_consecutive_holidays": "Unknown Targets Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Archive Proof Proof",
        "m_fibonacci": "Revenge Served Dominion",
        "m_palindrome_day": "During Prohibition Ledger Ledger",
        "m_binary_day": "Danger Alerts Proof",
        "m_full_moon_read": "Case Crown",
        "m_leap_year_read": "Revenge Served Practice",
        "m_triple_seven": "Angelo Lagusa Trial",
        "m_thousand_complete": "Revenge Plan Ascension",
        "m_nice": "Revenge Trophies Seal",
        "m_power_level_chapters": "Orphan Aegis",
        "m_answer_42": "Case Aegis",
        "m_square_number": "Avenger Standard Standard",
        "m_prime_count": "Vanetti Insignia",
        "m_matching_date": "Prohibition Mantle",
        "m_century_chapter": "Served Crown",
        "m_pi_chapters": "Danger Alerts Proof Proof",
        "m_synchronicity": "Weapon Emblem",
        "m_world_record": "Served Warrant",
        "m_genre_clash": "Secret Vault Clash",
        "m_time_traveler": "Mob War Decree Decree",
        "m_double_digits": "91 Days Dominion",
        "m_one_two_three": "Served Warrant Warrant",
        "m_lucky_seven": "Revenge Served Pinnacle",
        "m_exact_hundred_ch": "Served Legend",
        "m_year_match_count": "Revenge Trophies Routine",
        "m_chapter_match_date": "Revenge Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Prohibition Index",
        "m_manhwa_format": "Prohibition Gallery",
        "m_manhua_format": "Case Storehouse",
        "m_ln_format": "Marathon Index",
        "m_oneshot_format": "Orphan Index",
        "m_doujin_format": "Prohibition Fan Cabinet",
        "m_novel_format": "91 Days Reserve",
        "m_format_master_manga": "Marathon Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Case Link",
        "m_meta_collector": "Revenge Trophies Reliquary",
        "m_meta_category_starter": "Unknown Targets Key",
        "m_meta_tier_climber": "Orphan Token",
        "m_meta_tier_max": "Archive Token",
        "m_meta_xp_earner": "Revenge Served Anchor",
        "m_meta_difficulty_easy": "Avenger Panel",
        "m_meta_difficulty_hard": "Angelo Seal Seal",
        "m_meta_unlock_spree": "Prohibition Marker",
        "m_meta_completionist": "Sepia Triumph",
        "m_meta_diverse": "Secret Vault Anchor",
        "m_meta_dominator": "Mob War Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#050200",
        primary: "#765526",
        secondary: "#505050",
        accent: "#e0c888",
    },
    particleColor: "#a07838",
    backgroundDim: 0.4,
    backgroundBlur: 22,
    milestoneNames: {
  1: "Threadbare Street Rat Spark",
  8: "Back's Tarnished Omen",
  14: "Fractured Pickpocket",
  21: "Bootleg Runner Path",
  28: "Lowborn Legacy Myth",
  35: "Dockside Drifter Pulse",
  41: "Nameless's Legacy Crest",
  48: "Humble Cheap Mark",
  55: "Ragged Barroom Leech Vow",
  61: "Petty's Faint Echo",
  68: "Lesser Whiskey Runner",
  75: "Time Crook Thread",
  81: "Doubtful Legacy Bloom",
  88: "Disposable Muscle Sigil",
  95: "Forgotten's Legacy Flame",
  102: "Really Cool Family Haven",
  108: "Awakened Smuggling Hand Omen",
  115: "Warehouse's Resolute Clash",
  122: "Rising Backroom Dealer",
  128: "Street Informant Form",
  135: "Dauntless Associate Pulse",
  142: "Gun Hire Crest",
  149: "Debt's Legacy Mark",
  155: "Fresh Family Haven",
  162: "Valiant Liquor Courier Echo",
  169: "Speakeasy's Prime Crown",
  175: "Polished Trusted Errand",
  182: "Minor Enforcer Force",
  189: "Stormlit Legacy Sigil",
  195: "Upstart Punk Brush",
  202: "Made's Legacy Spark",
  209: "Tempered Family Haven",
  216: "Trusted Collection Agent Seal",
  222: "Bootleg's Steadfast Path",
  229: "Ironclad Street Enforcer",
  236: "Trusted Gun Pulse",
  242: "Core Legacy Crest",
  249: "Crew Enforcer Force",
  256: "Mid's Associate Vow",
  262: "Formidable Warehouse Clash",
  269: "Lucid Liquor Route Crown",
  276: "Territory's Ranked Zenith",
  283: "Fabled Debt Enforcer",
  289: "Rising Soldier Sigil",
  296: "Seasoned Legacy Flame",
  303: "Made Spark",
  309: "Family's Legacy Haven",
  316: "Valorous Execution Seal",
  323: "Stalwart Territory Enforcer Force",
  330: "Crew's Commanding Myth",
  336: "Refined Trusted Killer",
  343: "Smuggling Boss Crest",
  350: "Blazing Legacy Mark",
  356: "Route Controller Vow",
  363: "Capable's Legacy Force",
  370: "Peerless Family Haven",
  376: "Ardent Cold Blooded Zenith",
  383: "Silent's Focused Bloom",
  390: "Vigilant Respected Soldier",
  397: "Ward Level Clash",
  403: "Elite Legacy Spark",
  410: "Territory Boss Omen",
  417: "Crew's Legacy Seal",
  423: "Sovereign High Force",
  430: "Regal Family Strategist Haven",
  437: "Trusted's Crowned Pulse",
  444: "Mythborn Operations Controller",
  450: "Inner Circle Mark",
  457: "Radiant Legacy Vow",
  464: "Major Enforcer Force",
  470: "Blooded's Legacy Crown",
  477: "Climactic Family Haven",
  484: "Epic Underboss Candidate Bloom",
  490: "Right's Unreal Sigil",
  497: "Peak Bosss Shadow",
  504: "Underboss Spark",
  511: "Exalted Legacy Haven",
  517: "Strategic Overseer Seal",
  524: "Citywide's Legacy Path",
  531: "Celestial Broker Force",
  537: "Phantom Ruthless Arbiter Pulse",
  544: "Fearful's Crimson Force",
  551: "Silver Crime Lord",
  557: "Empire Builder Vow",
  564: "Feral Absolute Force",
  571: "Family Sovereign Haven",
  578: "Iron's Leader Zenith",
  584: "Dread Unchallenged Force",
  591: "Luminous Boss Bosses Sigil",
  598: "City's Thunderous Crown",
  604: "Ultraviolet Legendary Boss",
  611: "Mythic Enforcer Force",
  618: "Secret Families Seal",
  625: "Untouchable Don Path",
  631: "Authority's Absolute Force",
  638: "Worldclass Empire Pulse",
  645: "Lawless Shadow King Crown",
  651: "Master's Chosen Vendetta",
  658: "Fearless Unbreakable Will",
  665: "Bloodline Crusher Echo",
  671: "Cinematic Legacy Echo",
  678: "Revenge Architect Vendetta",
  685: "Cold's Legacy Bloom",
  692: "Canonized Planner Sigil",
  698: "Ascendant Endgame Player Flame",
  705: "Revenge's Transfigured Vendetta",
  712: "Immortal Ghost Past",
  718: "Family Executioner Haven",
  725: "Astral Legacy Path",
  732: "Judgment Dealer Myth",
  739: "Harbinger's Legacy Pulse",
  745: "Prismatic Walking Crown",
  752: "Abyssal Soul Eroder Soul",
  759: "Empty's Unbound Vow",
  765: "Eternal Broken Victor",
  772: "Hollow Avenger Crest",
  779: "Transcendent Legacy Thread",
  785: "Fate Defier Bloom",
  792: "Witness's Final Sigil",
  799: "Ultimate Last Flame",
  806: "Mythic Silent End Spark",
  812: "Inevitable's Godlike Omen",
  819: "Canonical Past Made",
  826: "Living Regret Path",
  832: "Heavenly Legacy Soul",
  839: "End Bloodline Pulse",
  846: "Echo's Legacy Vendetta",
  852: "Timeless Vanished Mark",
  859: "Empyrean Unwritten Ending Vow",
  866: "Ghost's Primordial Echo",
  873: "Omniscient Nameless Legend",
  879: "Forgotten Secret",
  886: "Apocalyptic Final Bloom",
  893: "Closing Act Sigil",
  899: "Last's Legacy Flame",
  906: "Final 91 Spark",
  913: "Crowned Redemption Omen",
  920: "End's Mythic Seal",
  926: "Absolute Retribution",
  933: "Absolute Myth",
  940: "Cosmic Legacy Pulse",
  946: "Tomorrow Crest",
  953: "Faded's Legacy Mark",
  960: "Definitive Storys Vow",
  966: "Ultimate Ashes Vengeance Vendetta",
  973: "Last's Infinite Echo",
  980: "Sovereign Vanishing Soul",
  987: "End Everything Bloom",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate 91"
}
}
