import { AnimeThemeConfig } from "./types"
import { GiHeartKey, GiMusicalNotes, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiFlowerEmblem, GiStarSwirl, GiCrystalBall } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const aSilentVoiceTheme: AnimeThemeConfig = {
    id: "a-silent-voice",
    displayName: "A Silent Voice",
    description: "Shoya Ishida bullied deaf classmate Shoko Nishimiya in elementary school. Years later, plagued by guilt and isolation, he seeks her out to make amends — and discovers the true cost of connection.",
    cssVars: {
        "--color-brand-200": "185 210 240",
        "--color-brand-300": "128 170 222",
        "--color-brand-400": "75 128 200",
        "--color-brand-500": "35 90 172",
        "--color-brand-600": "15 60 135",
        "--color-brand-700": "5 36 98",
        "--color-brand-800": "2 18 62",
        "--color-brand-900": "0 8 36",
        "--color-brand-950": "0 2 16",
        "--brand": "35 90 172",
        "--background": "#000208",
        "--paper": "#010510",
        "--color-gray-950": "0 2 8",
        "--color-gray-900": "2 6 18",
        "--color-gray-800": "5 14 35",
        "--color-gray-700": "10 26 58",
        "--color-gray-600": "18 48 88",
        "--color-gray-500": "30 78 120",
        "--color-gray-400": "55 118 158",
        "--color-gray-300": "90 158 195",
        "--color-gray-200": "135 195 222",
        "--color-gray-100": "185 222 242",
        "--color-gray-50": "228 242 252",
    },
    sidebarOverrides: {
        "home": { icon: GiFlowerEmblem, label: "Shoko's World" },
        "schedule": { icon: GiAlarmClock, label: "Life Schedule" },
        "manga": { icon: LuBookOpen, label: "Story Archive" },
        "lists": { icon: GiScrollUnfurled, label: "Connection List" },
        "discover": { icon: GiBullseye, label: "New Bonds" },
        "torrent-list": { icon: GiMusicalNotes, label: "Koe no Katachi" },
        "debrid": { icon: GiHeartKey, label: "Silent Vault" },
        "unmatched": { icon: GiCrystalBall, label: "Unresolved" },
        "enmasse": { icon: GiResize, label: "Reconnect" },
        "scan-summaries": { icon: TbReportSearch, label: "Life Reports" },
        "auto-downloader": { icon: LuRss, label: "New Connections" },
        "community": { icon: GiStarSwirl, label: "Silent Circle" },
        "achievements": { icon: GiTrophyCup, label: "Redemption Trophies" },
        "milestones": { icon: LuFlag, label: "Healing Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Connection Alerts" },
        "theme-manager": { icon: GiPalette, label: "Silent Colors" },
        "extensions": { icon: BiExtension, label: "Life Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Heart Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Shoya Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Encounter",
        "a_episode_counter": "Archive Mark",
        "a_episode_titan": "Loyal Relic",
        "a_hours_invested": "Silent Voice Proof",
        "a_time_lord": "Story Archive Decree",
        "a_anime_collector": "Connection Alerts Catalogue",
        "a_library_legend": "Redemption Library",
        "a_first_complete": "Forgiveness Sought",
        "a_hundred_club": "Hundred Quiet Moments",
        "a_first_day": "Loyal Fan Seal",
        "a_first_rating": "Healing Appraisal",
        "a_ten_thousand_min": "Silent Voice Standard",
        "a_season_veteran": "Moments Library",
        "a_year_explorer": "Sought Map",
        "a_century_watcher": "Shoko Nishimiya Ledger",
        "a_five_hundred_eps": "Shoko Nishimiya Dominion",
        "a_thousand_eps": "Redemption Trophies Record",
        "a_watching_ten": "Reconnect Acclaim",
        "a_ptw_hoarder": "Archive Library",
        "a_dropped_honesty": "Loyal Summit",
        "a_five_thousand_eps": "Silent Warrant",
        "a_ten_completed": "Shoya Afterglow",
        "a_fifty_completed": "Connection Ascension",
        "a_five_hundred_completed": "Story Clear",
        "a_mean_score_tracker": "Forgiveness Sought Verdict",
        "a_unique_studios": "Story Archive Collection",
        "a_days_spent_watching": "Bully Dominion",
        "a_all_status": "Forgiveness Testament",
        "a_first_favorite": "Story Archive Cabinet",
        "a_favorites_collector": "Bully Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Forgiveness Drive",
        "a_marathon_runner": "Silent Voice Gauntlet",
        "a_weekend_warrior": "Silent Vault Ordeal",
        "a_non_stop": "Archive Fever",
        "a_one_more_episode": "Sought Mantle",
        "a_speed_run": "Voice Marathon Vigil",
        "a_double_feature": "Story Archive Crown",
        "a_triple_threat": "Shoya Record",
        "a_five_a_day": "Marathon Accord",
        "a_back_to_back": "Connection Surge",
        "a_seasonal_binge": "Shoya Ishida Cascade",
        "a_cour_crusher": "Bully Ordeal",
        "a_half_day_watch": "Silent Vault Crown",
        "a_full_day_watch": "Heart Pinnacle",
        "a_power_weekend": "Shoko's World Run",
        "a_binge_king": "Silent Voice Marathon",
        "a_no_sleep": "Forgiveness Sought Vigil",
        "a_entire_season": "Quiet Moments Library",
        "a_seven_day_challenge": "Story Archive Mark",
        "a_hundred_day_binge": "Silent Voice Surge",
        "a_genre_binge": "Quiet Binge",
        "a_studio_binge": "Silent Circle Fever",
        "a_season_sweep": "Koe Codex",
        "a_forty_eight_hour": "Silent Voice Overture",
        "a_ep_counter_day": "Shoya Aegis",
        "a_multi_series_binge": "Loyal Fan Streak",
        "a_midnight_binge": "Silent Cascade",
        "a_new_year_binge": "Friend Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Voice Marathon Action",
        "a_genre_adventure": "Bully Adventure",
        "a_genre_comedy": "Heart Comedy",
        "a_genre_drama": "Bully Friend Drama",
        "a_genre_fantasy": "Shoya Fantasy",
        "a_genre_horror": "Redemption Trophies Horror",
        "a_genre_mystery": "Silent Voice Marathon Mystery",
        "a_genre_romance": "Forgiveness Romance",
        "a_genre_scifi": "Forgiveness Sought Sci-Fi",
        "a_genre_sol": "Unresolved Slice",
        "a_genre_sports": "Story Sports",
        "a_genre_supernatural": "Unresolved Supernatural",
        "a_genre_thriller": "Marathon Thriller",
        "a_genre_mecha": "Katachi Mecha",
        "a_genre_music": "Bully Music",
        "a_genre_psychological": "Life Psychological",
        "a_genre_ecchi": "Archive Ecchi",
        "a_genre_mahou_shoujo": "Shoko Nishimiya Magic Shoujo",
        "a_tag_isekai": "Bully Isekai",
        "a_tag_harem": "Reconnect Harem",
        "a_tag_bl": "Loyal Fan Bl",
        "a_tag_gl": "Connection Alerts Gl",
        "a_tag_historical": "Silent Historical",
        "a_tag_military": "Forgiveness Sought Military",
        "a_tag_school": "Marathon School",
        "a_tag_martial_arts": "Redemption Martial Arts",
        "a_tag_vampire": "Connection Alerts Vampire",
        "a_tag_samurai": "Healing Samurai",
        "a_tag_space": "Moments Space",
        "a_tag_parody": "Shoya Ishida Parody",
        "a_tag_idol": "Shoya Idol",
        "a_tag_post_apocalyptic": "Connection Alerts Post Apocalyptic",
        "a_tag_cyberpunk": "Silent Voice Cyberpunk",
        "a_tag_shounen": "Shoya Ishida Shounen",
        "a_tag_seinen": "Sought Seinen",
        "a_tag_shoujo": "Marathon Shoujo",
        "a_tag_josei": "Bonds Josei",
        "a_tag_survival": "Bully Friend Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Story Complete",
        "a_mega_completionist": "Redemption Arc Done",
        "a_completion_rate_50": "Encounter Return",
        "a_completion_rate_75": "Story Archive Crown Crown",
        "a_completion_rate_90": "Story Resolution",
        "a_no_drop": "Silent Vault Decree",
        "a_long_runner_complete": "Loyal Clear",
        "a_sequel_chain": "A Silent Voice Insignia",
        "a_clean_list": "Silent Voice Marathon Relic",
        "a_from_ptw": "Encounter Index",
        "a_rewatch_master": "Shoko Nishimiya Return",
        "a_short_complete": "Loyal Fan Endgame",
        "a_same_day_start_finish": "Forgiveness Sought Pinnacle",
        "a_revival": "Silent Insignia",
        "a_zero_to_hero": "Bully to Friend",
        "a_five_genre_complete": "Loyal A Five Genre Complete",
        "a_full_franchise": "Moments Chronicle",
        "a_batch_complete": "Redemption Crown",
        "a_paused_to_done": "Bully Aegis",
        "a_completion_spree": "Voice Triumph",
        "a_multi_rewatch": "Redemption Trophies Triumph",
        "a_dropped_recovery": "Voice Marathon Conquest",
        "a_ten_perfect_scores": "A Silent Voice Acclaim",
        "a_seasonal_clear": "Bonds Codex",
        "a_complete_genre_span": "Shoko Nishimiya A Complete Genre",
        "a_monthly_completions": "Healing Afterglow",
        "a_yearly_completions": "A Silent Voice Epilogue",
        "a_rapid_complete": "Loyal Fan Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Fan",
        "a_studio_devotee": "Moments Treasury",
        "a_rewatcher": "Story Closure",
        "a_triple_rewatch": "Shoya Coda",
        "a_annual_tradition": "Redemption Proof",
        "a_director_fan": "Redemption Trial",
        "a_voice_actor_fan": "Bonds Crown",
        "a_ost_lover": "Silent Voice Marathon Seal",
        "a_source_reader": "Shoya Cabinet",
        "a_waiting_weekly": "Bully Clock",
        "a_childhood_revisit": "Encounter Seal",
        "a_saga_tracker": "Unresolved Standard",
        "a_genre_loyalty": "Connection Loyalty",
        "a_decade_watcher": "Silent Circle Banner",
        "a_adaptation_hunter": "Archive Trial",
        "a_original_anime_fan": "Quiet Testament",
        "a_long_commitment": "A Silent Voice Mark",
        "a_perfect_attendance": "Silent Vault Standard",
        "a_favorite_studio_5": "Bully Library",
        "a_complete_catalog": "Connections Seal",
        "a_franchise_collector": "Koe Archive",
        "a_airing_follower": "Marathon Signal",
        "a_genre_master": "Shoya Ishida Master",
        "a_staff_follower": "Encounter Oath",
        "a_multi_season_fan": "Loyal Hoard",
        "a_format_diversity": "Unresolved Cache",
        "a_year_dedication": "Redemption Trophies Tenure",
        "a_season_dedication": "Moments Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Forgiveness Sought Explorer",
        "a_studio_hopper": "Shoya Ishida Collection",
        "a_tag_explorer": "Marathon Explorer",
        "a_decade_hopper": "Unresolved Chronicle",
        "a_hidden_gem": "Quiet Moments Warrant",
        "a_popular_taste": "Quiet Moments Decree",
        "a_retro_appreciator": "Silent Voice Marathon Aegis",
        "a_modern_viewer": "Connection Pinnacle",
        "a_cross_demographic": "Archive Pinnacle",
        "a_underdog_fan": "Quiet Moments Trial",
        "a_variety_week": "Sought Horizon",
        "a_foreign_cinema": "Voice Marathon Expedition",
        "a_classic_connoisseur": "Friend Glimpse",
        "a_every_season": "Voice Archive",
        "a_award_winner": "Bully Friend Insignia",
        "a_niche_explorer": "Bonds Horizon",
        "a_global_anime": "Shoko Nishimiya Crown",
        "a_cult_classic": "Loyal Fan Map",
        "a_random_pick": "Silent Vault Decree Decree",
        "a_new_genre_month": "Bonds A New Genre Month",
        "a_seasonal_completionist": "Marathon Summit",
        "a_unpopular_opinion": "Silent Circle Standard",
        "a_top_rated_viewer": "A Silent Voice Seal",
        "a_source_variety": "Heart Storehouse",
        "a_low_score_brave": "Silent Circle Measure",
        "a_upcoming_watcher": "Shoko Nishimiya Seal",
        "a_short_series_explorer": "Archive Expedition",
        "a_long_series_explorer": "Connection Alerts Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Healing Insignia",
        "a_early_bird": "Loyal Banner",
        "a_lunch_break": "Bonds Trial",
        "a_golden_hour": "Redemption Tenure",
        "a_four_am_club": "Koe Gathering",
        "a_witching_hour": "Marathon Tenure",
        "a_new_year_watch": "Silent Circle Season",
        "a_midnight_premiere": "Voice Marathon Devotion",
        "a_all_hours": "Silent Circle Seal",
        "a_dawn_warrior": "Unresolved Aegis",
        "a_afternoon_delight": "Voice Marathon Proof",
        "a_prime_time": "Redemption Insignia",
        "a_workday_watcher": "Quiet Pinnacle",
        "a_sunday_marathon": "Katachi Momentum",
        "a_rainy_day": "Loyal Relic Relic",
        "a_morning_routine": "Bully Promise",
        "a_night_shift": "Connection Aegis",
        "a_twilight_zone": "Encounter Ledger",
        "a_seasonal_premier": "Silent Cabinet",
        "a_clock_collector": "Silent Circle Repository",
        "a_weekend_binge_hours": "Silent Voice Marathon Streak",
        "a_late_night_regular": "Katachi Dominion",
        "a_sunrise_watcher": "Moments Ledger",
        "a_holiday_watcher": "Life Pact",
        "a_every_day_of_week": "Loyal Ledger",
        "a_monthly_hours": "Healing Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "A Silent Voice Record",
        "a_party_host": "Moments Record",
        "a_social_butterfly": "Shoya Company",
        "a_group_binge": "Loyal Sprint",
        "a_party_regular": "Shoya Ishida Chronicle",
        "a_sync_viewer": "Sought Standard",
        "a_commentator": "Silent Voice Marathon Record",
        "a_party_marathon": "Silent Voice Vigil",
        "a_full_house": "Bonds Trial Trial",
        "a_community_pillar": "Shoko Nishimiya Alliance",
        "a_watch_party_streak": "Bully Friend Vigil",
        "a_diverse_party": "Sought Seal",
        "a_late_night_party": "Shoko's World Testament",
        "a_party_veteran": "Shoko Nishimiya Testament",
        "a_genre_party": "Shoya Ishida Party",
        "a_weekly_party": "Silent Circle Calendar",
        "a_silent_viewer": "A Silent Voice Mantle",
        "a_recommendation_giver": "Encounter Network",
        "a_party_completionist": "A Silent Voice Coda",
        "a_social_scorer": "Koe Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Shoko's World Proof",
        "a_fibonacci": "Redemption Trophies Dominion",
        "a_palindrome_day": "Life Relic",
        "a_binary_day": "Connection Mark",
        "a_full_moon": "Bully Friend Insignia Insignia",
        "a_leap_year": "Life Devotion",
        "a_time_traveler": "Unresolved Record",
        "a_genre_clash": "Encounter Clash",
        "a_triple_seven": "Reconnect Testament",
        "a_thousand_complete": "Silent Epilogue",
        "a_pi_episodes": "Silent Vault Crown Crown",
        "a_synchronicity": "Sought Anchor",
        "a_world_record": "Bully Friend Warrant",
        "a_nice": "Reconnect Chronicle",
        "a_power_level": "Sought Testament",
        "a_answer_42": "Shoya Ishida Standard",
        "a_square_number": "Connection Alerts Decree",
        "a_prime_count": "Reconnect Seal",
        "a_matching_date": "Encounter Mantle",
        "a_century_episode": "Connections Mark",
        "a_double_digits": "Encounter Testament",
        "a_one_two_three": "Bonds Crown Crown",
        "a_lucky_seven": "Shoko Nishimiya Decree",
        "a_all_tens": "Encounter Criterion",
        "a_exact_hundred_eps": "Silent Voice Legend",
        "a_year_match_count": "Katachi Clock",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Unresolved Ledger",
        "a_movie_buff": "Silent Voice Marathon Mark",
        "a_ova_hunter": "Voice Standard",
        "a_ona_explorer": "Reconnect Secret",
        "a_special_watcher": "Bonds Relic",
        "a_short_king": "Encounter Crown",
        "a_variety_pack": "Heart Inquiry",
        "a_film_festival": "Archive Chronicle",
        "a_music_video": "Reconnect Chronicle Chronicle",
        "a_tv_short": "Life Record",
        "a_movie_marathon": "Story Archive Gauntlet",
        "a_double_length": "Friend Crown",
        "a_anthology": "Loyal Aegis",
        "a_mini_series": "Shoko's World Decree",
        "a_theatrical": "Life Accord",
        "a_format_master": "Moments Vault",
        "a_long_movie": "Voice Marathon Insignia",
        "a_back_catalog": "Redemption Standard",
        "a_cm_watcher": "Connection Aegis Aegis",
        "a_pv_collector": "A Silent Voice Storehouse",
        "a_format_balance": "Connections Vault",
        "a_episodic_master": "Reconnect Standard",
        "a_sequel_movie": "Bully Pinnacle",
        "a_recap_watcher": "Redemption Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Redemption Devotion",
        "a_mega_streak": "Voice Marathon Streak",
        "a_weekly_warrior": "A Silent Voice Season",
        "a_monthly_watcher": "Silent Calendar",
        "a_comeback": "Life Decree",
        "a_weekend_streak": "Shoko Nishimiya Passage",
        "a_no_zero_days": "Voice Warrant",
        "a_iron_will": "Story Seal",
        "a_habit_formed": "Friend Warrant",
        "a_consistent_pace": "Story Measure",
        "a_year_long": "Silent Season",
        "a_double_streak": "Unresolved Watch",
        "a_streak_recovery": "A Silent Voice Season Season",
        "a_daily_minimum": "Voice Focus",
        "a_winter_streak": "Loyal Watch",
        "a_summer_streak": "Forgiveness Sought Resolve",
        "a_morning_streak": "Forgiveness Sought Clock",
        "a_night_streak": "Bully Friend Constancy",
        "a_unbreakable": "Connections Proof",
        "a_eternal_flame": "Shoko Nishimiya Standard",
        "a_completion_streak": "Bonds Return",
        "a_rating_streak": "Story Balance",
        "a_multi_ep_streak": "Marathon Ritual",
        "a_genre_streak": "Shoko's World Streak",
        "a_studio_streak": "Life Cabinet",
        "a_perfect_week": "Story Relic",

        // ── ANIME SCORING ──
        "a_critic": "Quiet Moments Scrutiny",
        "a_perfect_ten": "Shoya Ishida Audit",
        "a_harsh_critic": "Voice Gauge",
        "a_fair_judge": "Archive Balance",
        "a_generous_spirit": "Moments Pinnacle",
        "a_score_all": "Archive Criterion",
        "a_wide_range": "Reconnect Ledger",
        "a_controversial": "Connections Decree",
        "a_consistent_scorer": "Silent Voice Marathon Verdict",
        "a_score_sniper": "Shoya Score",
        "a_evolving_taste": "Encounter Testament Testament",
        "a_bell_curve": "Connection Alerts Insignia",
        "a_picky_watcher": "Loyal Seal",
        "a_100_rated": "Silent Circle Warrant",
        "a_500_rated": "Story Archive Pinnacle",
        "a_mediocre_majority": "Redemption Trophies Canon",
        "a_rating_spree": "Silent Vault Review",
        "a_score_variance": "Connection Alerts Score",
        "a_masterpiece_hunter": "Forgiveness Banner",
        "a_contrarian": "Redemption Trophies Record Record",
        "a_optimist": "Quiet Ledger",
        "a_score_distributor": "Moments Appraisal",
        "a_genre_critic": "Shoko Nishimiya Critic",
        "a_mean_above_8": "Sought Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "Voice Marathon Resolve",
        "a_valentines_weeb": "Silent Circle Vow",
        "a_pi_day": "Voice Marathon Trial",
        "a_april_fools": "Sought Devotion",
        "a_international_anime_day": "Shoya Ishida Pinnacle",
        "a_star_wars_day": "Voice Chronicle",
        "a_summer_solstice": "Story Archive Calendar",
        "a_tanabata": "Redemption Focus",
        "a_friday_13th": "Silent Relic",
        "a_halloween_spirit": "Shoya Ishida Vow",
        "a_thanksgiving_binge": "Archive Run",
        "a_christmas_special": "Connection Season",
        "a_new_years_eve": "Koe Pilgrimage",
        "a_birthday_watch": "Connection Alerts Vow",
        "a_holiday_marathon": "Silent Overture",
        "a_independence_day": "Forgiveness Sought Banner",
        "a_culture_day": "Redemption Trophies Insignia",
        "a_spring_equinox": "Loyal Fan Decree",
        "a_earth_day": "Reconnect Record",
        "a_labor_day": "Silent Circle Seal Seal",
        "a_winter_solstice": "Heart Pilgrimage",
        "a_anime_birthday": "Story Archive Pilgrimage",
        "a_every_holiday": "Story Archive Resolve",
        "a_consecutive_holidays": "Moments Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Quiet Moments Rank",
        "a_meta_collector": "Friend Hoard",
        "a_meta_category_starter": "Connection Badge",
        "a_meta_tier_climber": "Silent Voice Glyph",
        "a_meta_tier_max": "Forgiveness Sought Writ",
        "a_meta_xp_earner": "Shoya Emblem",
        "a_meta_difficulty_easy": "Silent Voice Marathon Mechanism",
        "a_meta_difficulty_hard": "Shoko Nishimiya Writ",
        "a_meta_unlock_spree": "Connection Alerts Panel",
        "a_meta_completionist": "Koe Fulfillment",
        "a_meta_diverse": "Life Emblem",
        "a_meta_dominator": "Loyal Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Manga Chapter",
        "m_chapter_counter": "Silent Voice Marathon Pinnacle",
        "m_chapter_titan": "Friend Relic",
        "m_reading_hours": "Forgiveness Relic",
        "m_reading_time_lord": "Archive Pinnacle Pinnacle",
        "m_manga_collector": "Encounter Ledger Ledger",
        "m_library_legend": "Shoko Nishimiya Reliquary",
        "m_first_complete": "Sought Triumph",
        "m_hundred_club": "Heart Network",
        "m_first_day": "Silent Voice Seal",
        "m_first_rating": "Forgiveness Eye",
        "m_ten_thousand_pages": "Katachi Gauge",
        "m_volume_collector": "Connection Alerts Storehouse",
        "m_year_explorer": "Bonds Quest",
        "m_century_reader": "Loyal Dominion",
        "m_five_hundred_ch": "Life Ledger",
        "m_thousand_ch": "Shoya Ishida Testament",
        "m_reading_ten": "Loyal Fan Appraisal",
        "m_ptr_hoarder": "Silent Vault Index",
        "m_dropped_honesty": "Encounter Summit",
        "m_season_reader": "Katachi Treasury",
        "m_active_reader": "Encounter Trial",
        "m_five_thousand_ch": "Story Archive Standard",
        "m_ten_completed": "Silent Voice Resolution",
        "m_fifty_completed": "Sought Harvest",
        "m_five_hundred_completed": "Redemption Legacy",
        "m_mean_score_tracker": "Reconnect Audit",
        "m_unique_authors": "Connection Reserve",
        "m_all_status": "Redemption Trophies Testament",
        "m_first_favorite": "Life Cache",
        "m_favorites_collector": "Marathon Shelf",
        "m_days_spent_reading": "Shoya Decree",

        // ── MANGA BINGE ──
        "m_binge_reader": "Shoya Streak",
        "m_marathon_reader": "Healing Rush",
        "m_weekend_reader": "Bonds Run",
        "m_non_stop_reading": "Story Archive Gauntlet Gauntlet",
        "m_one_more_chapter": "Story Testament",
        "m_speed_read": "Shoya Drive",
        "m_double_story": "Silent Voice Banner",
        "m_triple_read": "Archive Record",
        "m_five_a_day": "Quiet Moments Insignia",
        "m_chapter_chain": "Moments Accord",
        "m_volume_binge": "Quiet Moments Drive",
        "m_power_reader": "Bully Friend Seal",
        "m_half_day_read": "Silent Vault Aegis",
        "m_full_day_read": "Story Archive Aegis",
        "m_power_weekend": "Silent Streak",
        "m_binge_king": "Bonds Momentum",
        "m_no_sleep_read": "Forgiveness Rush",
        "m_full_series_rush": "Shoko's World Cascade",
        "m_seven_day_challenge": "Shoko Nishimiya Warrant",
        "m_hundred_day_read": "Reconnect Relic",
        "m_volume_rush": "Heart Gauntlet",
        "m_series_sweep": "Sought Trial",
        "m_genre_binge": "Healing Binge",
        "m_author_binge": "Shoko Nishimiya Surge",
        "m_chapter_counter_day": "Story Ledger",
        "m_multi_series_binge": "Life Charge",
        "m_midnight_binge": "Silent Circle Tempest",
        "m_new_year_binge": "Forgiveness Passage",
        "m_forty_eight_hour": "Archive Rally",
        "m_oneshot_binge": "Forgiveness Sought Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Silent Action",
        "m_genre_adventure": "Connections Adventure",
        "m_genre_comedy": "Life Comedy",
        "m_genre_drama": "Sought Drama",
        "m_genre_fantasy": "Forgiveness Sought Fantasy",
        "m_genre_horror": "Moments Horror",
        "m_genre_mystery": "Reconnect Mystery",
        "m_genre_romance": "Shoko Nishimiya Romance",
        "m_genre_scifi": "Silent Voice Marathon Sci-Fi",
        "m_genre_sol": "Story Slice",
        "m_genre_sports": "Moments Sports",
        "m_genre_supernatural": "Redemption Supernatural",
        "m_genre_thriller": "Bonds Thriller",
        "m_genre_psychological": "Koe Psychological",
        "m_genre_isekai": "Koe Isekai",
        "m_genre_shounen": "Quiet Shounen",
        "m_genre_ecchi": "Reconnect Ecchi",
        "m_genre_mahou_shoujo": "Connections Magic Shoujo",
        "m_genre_mecha": "Heart Mecha",
        "m_genre_music": "Marathon Music",
        "m_tag_isekai_new": "Shoko Nishimiya Isekai New",
        "m_tag_harem": "Shoko's World Harem",
        "m_tag_bl": "Connections Bl",
        "m_tag_gl": "Shoko's World Gl",
        "m_tag_historical": "Voice Historical",
        "m_tag_military": "Forgiveness Military",
        "m_tag_school": "Story School",
        "m_tag_martial_arts": "Shoko's World Martial Arts",
        "m_tag_vampire": "Heart Vampire",
        "m_tag_samurai": "Unresolved Samurai",
        "m_tag_space": "Bully Space",
        "m_tag_parody": "Bully Friend Parody",
        "m_tag_idol": "Forgiveness Sought Idol",
        "m_tag_post_apocalyptic": "Connections Post Apocalyptic",
        "m_tag_cyberpunk": "Healing Cyberpunk",
        "m_tag_shoujo": "Forgiveness Sought Shoujo",
        "m_tag_survival": "Bully Survival",
        "m_tag_cooking": "Voice Cooking",
        "m_tag_medical": "Katachi Medical",
        "m_tag_villainess": "Silent Voice Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Manga Archive",
        "m_mega_completionist": "Connections Resolution",
        "m_completion_rate_50": "Loyal Return",
        "m_completion_rate_75": "Story Ascension",
        "m_completion_rate_90": "Life Resolution",
        "m_no_drop": "Loyal Decree",
        "m_long_runner_complete": "Silent Circle Clear",
        "m_sequel_chain": "Healing Seal",
        "m_clean_list": "Moments Relic",
        "m_from_ptr": "Story Archive Accord",
        "m_reread_master": "Silent Trial",
        "m_oneshot_complete": "Katachi Ascension",
        "m_same_day_start_finish": "Forgiveness Sought Crown",
        "m_revival": "Koe Accord",
        "m_zero_to_hundred": "Life Banner",
        "m_five_genre_complete": "Katachi M Five Genre Complete",
        "m_full_collection": "Encounter Proof",
        "m_batch_complete": "Shoya Testament",
        "m_paused_to_done": "Bonds Standard",
        "m_completion_spree": "Katachi Triumph",
        "m_format_completionist": "Quiet Moments Testament",
        "m_catch_up": "Loyal Fan Chronicle",
        "m_multi_reread": "Archive Banner",
        "m_dropped_recovery": "Marathon Conquest",
        "m_ten_perfect_scores": "Silent Circle Judgment",
        "m_complete_genre_span": "Shoya M Complete Genre Span",
        "m_monthly_completions": "Connection Return",
        "m_yearly_completions": "Voice Marathon Epilogue",
        "m_rapid_complete": "Bully Finale",
        "m_author_complete": "Encounter Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Redemption Legacy Legacy",
        "m_mangaka_lover": "Sought Standard Standard",
        "m_rereader": "Silent Circle Relic",
        "m_triple_reread": "Marathon Testament",
        "m_annual_reread": "Moments Banner",
        "m_publisher_fan": "Loyal Fan Mark",
        "m_artist_fan": "Silent Circle Insignia",
        "m_adaptation_compare": "Silent Insignia Insignia",
        "m_source_material_fan": "Redemption Trophies Cache",
        "m_waiting_weekly": "Shoya Weekly",
        "m_classic_reader": "Redemption Trophies Lantern",
        "m_saga_reader": "Silent Crown",
        "m_genre_loyalty": "Loyal Fan Loyalty",
        "m_decade_reader": "Archive Warrant",
        "m_ln_adaptation": "Quiet Mark",
        "m_original_work": "Silent Voice Standard Standard",
        "m_long_commitment": "Forgiveness Mark",
        "m_up_to_date": "Bonds Warrant",
        "m_favorite_mangaka": "Sought Treasury",
        "m_complete_portfolio": "Healing Triumph",
        "m_franchise_collector": "Connections Archive",
        "m_serialization_follower": "Connections Handshake",
        "m_genre_master": "Koe Master",
        "m_multi_series_author": "Voice Marathon Insignia Insignia",
        "m_format_diversity": "Reconnect Shelf",
        "m_year_dedication": "Sought Tenure",
        "m_ongoing_follower": "Silent Fellowship",
        "m_genre_loyalty_50": "Bully Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Koe Explorer",
        "m_publisher_hopper": "Loyal Fan Record",
        "m_tag_explorer": "Voice Marathon Explorer",
        "m_decade_hopper": "Voice Chronicle Chronicle",
        "m_hidden_gem": "Silent Mark",
        "m_popular_taste": "Shoya Ishida Record",
        "m_retro_reader": "Quiet Testament Testament",
        "m_modern_reader": "Quiet Moments Seal",
        "m_cross_demographic": "Connections Crown",
        "m_underdog_fan": "Koe Testament",
        "m_variety_week": "Shoko's World Horizon",
        "m_manhwa_reader": "Healing Proof",
        "m_manhua_reader": "Story Archive Mantle",
        "m_classic_connoisseur": "Encounter Glimpse",
        "m_award_winner": "Bonds Seal",
        "m_niche_explorer": "Unresolved Horizon",
        "m_world_manga": "Life Chronicle",
        "m_cult_classic": "Voice Marathon Map",
        "m_random_pick": "Quiet Moments Testament Testament",
        "m_new_genre_month": "Quiet Moments M New Genre",
        "m_year_completionist": "Silent Voice Marathon Fulfillment",
        "m_unpopular_opinion": "Story Archive Aegis Aegis",
        "m_top_rated_reader": "Bonds Pinnacle",
        "m_source_variety": "Silent Voice Catalogue",
        "m_low_score_brave": "Loyal Fan Score",
        "m_short_manga_explorer": "Redemption Trophies Compass",
        "m_long_manga_explorer": "Connection Survey",
        "m_serialization_explorer": "Quiet Road",

        // ── MANGA TIME ──
        "m_night_owl": "Quiet Moments Accord",
        "m_early_bird": "Shoko Nishimiya Banner",
        "m_lunch_reader": "Moments Ledger Ledger",
        "m_commute_reader": "Shoko's World Tenure",
        "m_four_am_club": "Shoko's World Fellowship",
        "m_new_year_read": "Redemption Trophies Pact",
        "m_all_hours": "Silent Vault Accord",
        "m_prime_time_reader": "Redemption Banner",
        "m_workday_reader": "Story Accord",
        "m_sunday_read": "Encounter Standard",
        "m_morning_routine": "Heart Discipline",
        "m_night_shift_reader": "Silent Voice Marathon Accord",
        "m_seasonal_premier_read": "Quiet Moments Storehouse",
        "m_clock_collector": "Silent Circle Reserve",
        "m_late_night_horror": "Silent Mark Mark",
        "m_afternoon_reader": "Sought Mantle Mantle",
        "m_golden_hour_reader": "Marathon Observance",
        "m_dawn_reader": "Katachi Mantle",
        "m_twilight_reader": "Voice Marathon Crown",
        "m_midnight_start": "Bonds Routine",
        "m_weekend_binge_hours": "Life Momentum",
        "m_late_night_regular": "Shoya Ishida Testament Testament",
        "m_sunrise_reader": "Shoya Ishida Record Record",
        "m_every_day_of_week": "Forgiveness Sought Seal",
        "m_monthly_hours": "Shoko's World Vigil",
        "m_bedtime_reader": "Heart Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Life Mantle",
        "m_webtoon_reader": "Shoya Ishida Mark",
        "m_full_color": "Reconnect Accord",
        "m_doujin_reader": "Katachi Record",
        "m_anthology_reader": "Loyal Accord",
        "m_adaptation_reader": "Unresolved Banner",
        "m_longstrip_reader": "Loyal Chronicle",
        "m_4koma_reader": "Healing Relic",
        "m_oneshot_reader": "Loyal Mantle",
        "m_format_variety": "Friend Gallery",
        "m_light_novel_reader": "Redemption Insignia Insignia",
        "m_novel_reader": "Voice Crown",
        "m_visual_storyteller": "Unresolved Testament",
        "m_colored_classic": "Shoko Nishimiya Survey",
        "m_webcomic_fan": "Story Insignia",
        "m_manga_to_anime": "Bully Friend Record",
        "m_seinen_reader": "Heart Pinnacle Pinnacle",
        "m_josei_reader": "Bully Friend Pinnacle",
        "m_award_winning_art": "Unresolved Relic",
        "m_debut_work": "Sought Dominion",
        "m_vertical_scroll": "Reconnect Crown",
        "m_traditional_format": "Archive Hoard",
        "m_cross_media": "Unresolved Accord",
        "m_spinoff_reader": "Loyal Fan Accord",
        "m_remake_reader": "Healing Insignia Insignia",
        "m_collaboration_reader": "Shoko Nishimiya Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Quiet Moments Focus",
        "m_mega_streak": "Silent Voice Routine",
        "m_weekly_warrior": "Koe Season",
        "m_monthly_reader": "Shoko's World Discipline",
        "m_comeback": "Heart Standard",
        "m_weekend_streak": "Reconnect Fever",
        "m_no_zero_days": "Forgiveness Sought Proof",
        "m_iron_will": "Reconnect Ledger Ledger",
        "m_habit_formed": "Life Crown",
        "m_consistent_pace": "Shoya Scrutiny",
        "m_year_long": "Forgiveness Sought Observance",
        "m_double_streak": "Shoya Resolve",
        "m_streak_recovery": "Connections Resolve",
        "m_daily_minimum": "Story Focus",
        "m_winter_streak": "Friend Observance",
        "m_summer_streak": "Voice Marathon Observance",
        "m_morning_streak": "Shoya Ishida Clock",
        "m_night_streak": "Voice Marathon Discipline",
        "m_unbreakable": "Heart Warrant Warrant",
        "m_eternal_flame": "Healing Record",
        "m_chapter_a_day": "Quiet Moments Relic",
        "m_genre_streak": "Voice Marathon Streak Mode",
        "m_completion_streak": "Life Return",
        "m_rating_streak": "Heart Appraisal",
        "m_multi_ch_streak": "Connection Tenure",
        "m_author_streak": "Silent Voice Calendar",
        "m_perfect_week_manga": "Forgiveness Accord",
        "m_diverse_streak": "Silent Circle Streak",

        // ── MANGA SCORING ──
        "m_critic": "Quiet Scrutiny",
        "m_perfect_ten": "Encounter Verdict",
        "m_harsh_critic": "Forgiveness Scale",
        "m_fair_judge": "Marathon Eye",
        "m_generous_spirit": "Connection Crown",
        "m_score_all": "Silent Voice Reckoning",
        "m_wide_range": "Connections Crown Crown",
        "m_controversial": "Voice Standard Standard",
        "m_consistent_scorer": "Healing Grade",
        "m_score_sniper": "Loyal Fan Reckoning",
        "m_evolving_taste": "Sought Trial Trial",
        "m_bell_curve": "Story Archive Accord Accord",
        "m_picky_reader": "A Silent Voice Relic",
        "m_100_rated": "Marathon Mark",
        "m_500_rated": "Loyal Proof",
        "m_mediocre_majority": "Reconnect Canon",
        "m_rating_spree": "Unresolved Verdict",
        "m_score_variance": "Forgiveness Sought Measure",
        "m_binge_rater": "Redemption Trophies Passage",
        "m_reread_rerate": "Silent Circle Banner Banner",
        "m_masterpiece_hunter": "Bully Banner",
        "m_contrarian": "Marathon Aegis",
        "m_optimist": "Unresolved Accord Accord",
        "m_score_distributor": "Bully Balance",
        "m_genre_critic": "Connections Critic",
        "m_mean_above_8": "Shoya Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Redemption Season",
        "m_valentines_read": "Connections Observance",
        "m_pi_day": "Connections Testament",
        "m_april_fools": "Redemption Devotion Devotion",
        "m_international_manga_day": "Healing Proof Proof",
        "m_free_comic_day": "Unresolved Chronicle Chronicle",
        "m_summer_solstice": "Life Focus",
        "m_tanabata": "Encounter Pilgrimage",
        "m_friday_13th": "Connection Alerts Dominion",
        "m_halloween_read": "Reconnect Calendar",
        "m_thanksgiving_binge": "Shoko Nishimiya Charge",
        "m_christmas_read": "Katachi Pact",
        "m_new_years_eve": "Bonds Pilgrimage",
        "m_birthday_read": "Sought Focus",
        "m_holiday_marathon": "Koe Rally",
        "m_independence_day": "Voice Aegis",
        "m_culture_day": "Bully Seal",
        "m_spring_equinox": "Connection Alerts Banner",
        "m_earth_day": "Quiet Aegis",
        "m_labor_day": "Story Seal Seal",
        "m_winter_solstice": "Healing Focus",
        "m_manga_birthday": "Shoya Ritual",
        "m_every_holiday_reader": "Shoko's World Watch",
        "m_consecutive_holidays": "Sought Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Heart Proof",
        "m_fibonacci": "Heart Dominion",
        "m_palindrome_day": "Bonds Relic Relic",
        "m_binary_day": "Life Proof",
        "m_full_moon_read": "Shoko's World Crown",
        "m_leap_year_read": "Healing Practice",
        "m_triple_seven": "Encounter Chronicle",
        "m_thousand_complete": "Katachi Legend",
        "m_nice": "Archive Seal",
        "m_power_level_chapters": "Voice Marathon Aegis",
        "m_answer_42": "Unresolved Aegis Aegis",
        "m_square_number": "Koe Standard",
        "m_prime_count": "Reconnect Insignia",
        "m_matching_date": "Forgiveness Sought Mantle",
        "m_century_chapter": "Quiet Moments Crown",
        "m_pi_chapters": "Bully Proof",
        "m_synchronicity": "Marathon Emblem",
        "m_world_record": "Shoya Ishida Warrant",
        "m_genre_clash": "Silent Vault Clash",
        "m_time_traveler": "Voice Decree",
        "m_double_digits": "Life Dominion",
        "m_one_two_three": "Connections Warrant",
        "m_lucky_seven": "Silent Record",
        "m_exact_hundred_ch": "Shoya Legend",
        "m_year_match_count": "Reconnect Routine",
        "m_chapter_match_date": "Bully Friend Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Story Index",
        "m_manhwa_format": "Connections Gallery",
        "m_manhua_format": "Story Archive Storehouse",
        "m_ln_format": "Connections Index",
        "m_oneshot_format": "Silent Voice Marathon Index",
        "m_doujin_format": "Shoya Ishida Cabinet",
        "m_novel_format": "Healing Reserve",
        "m_format_master_manga": "Redemption Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Reconnect Link",
        "m_meta_collector": "Connection Reliquary",
        "m_meta_category_starter": "Silent Vault Standard Standard",
        "m_meta_tier_climber": "Encounter Token",
        "m_meta_tier_max": "Koe Token",
        "m_meta_xp_earner": "Encounter Anchor",
        "m_meta_difficulty_easy": "Story Archive Panel",
        "m_meta_difficulty_hard": "Katachi Seal",
        "m_meta_unlock_spree": "Redemption Trophies Marker",
        "m_meta_completionist": "Connections Triumph",
        "m_meta_diverse": "Voice Anchor",
        "m_meta_dominator": "Shoya Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#000208",
        primary: "#235aac",
        secondary: "#8888aa",
        accent: "#a8d8f0",
    },
    particleColor: "#4088d0",
    backgroundDim: 0.32,
    backgroundBlur: 25,
    milestoneNames: {
  1: "Threadbare Careless Child Spark",
  8: "Loud's Tarnished Omen",
  14: "Fractured Class Disturber",
  21: "Mocking Voice Crown",
  28: "Lowborn Legacy Myth",
  35: "Cruel Tease Pulse",
  41: "Social's Legacy Crest",
  48: "Humble Unaware Clash",
  55: "Ragged Small Tormentor Vow",
  61: "Attention's Faint Echo",
  68: "Lesser Broken Empathy",
  75: "Group Follower Zenith",
  81: "Doubtful Legacy Bloom",
  88: "Unthinking Harm Crown",
  95: "Empty's Legacy Flame",
  102: "Really Cool Awkward Clash",
  108: "Awakened Isolated Classmate Omen",
  115: "Growing's Resolute Seal",
  122: "Rising Quiet Observer",
  128: "Social Outcast Myth",
  135: "Dauntless Legacy Pulse",
  142: "Flicker Echo",
  149: "Guilt's Legacy Mark",
  155: "Fresh Avoidant Vow",
  162: "Valiant Lingering Shame Echo",
  169: "Silent's Prime Crown",
  175: "Polished Broken Bonds",
  182: "Self Doubt Soul",
  189: "Stormlit Legacy Clash",
  195: "Hurt Realization Flame",
  202: "Seeking's Legacy Crown",
  209: "Tempered Social Omen",
  216: "Trusted Guilt Carrier Seal",
  222: "Past's Steadfast Thread",
  229: "Ironclad Reluctant Apology",
  236: "Attempted Change Pulse",
  242: "Core Legacy Vow",
  249: "Reaching Out Mark",
  256: "Fearful's Legacy Vow",
  262: "Formidable Burden Soul",
  269: "Lucid Rejection Echo",
  276: "Hope's Ranked Zenith",
  283: "Fabled Trying Again",
  289: "Silent Regret Sigil",
  296: "Seasoned Legacy Flame",
  303: "Seeking Forgiveness Crown",
  309: "Bridge's Legacy Omen",
  316: "Valorous Awkward Vow",
  323: "Stalwart Emotional Soul",
  330: "Confronted's Commanding Secret",
  336: "Refined Shared Pain",
  343: "Small Progress Crest",
  350: "Blazing Legacy Mark",
  356: "Open Wound Vow",
  363: "Trying's Legacy Echo",
  370: "Peerless New Clash",
  376: "Ardent Repair Attempt Zenith",
  383: "Broken's Focused Bloom",
  390: "Vigilant Hesitant Friend",
  397: "Shared Silence Flame",
  403: "Elite True Spark",
  410: "Awakening Soul",
  417: "Trust's Legacy Seal",
  423: "Sovereign Past Thread",
  430: "Regal Growing Understanding Myth",
  437: "Repaired's Crowned Vow",
  444: "Mythborn Mutual Effort",
  450: "Quiet Acceptance Mark",
  457: "Radiant Legacy Vow",
  464: "Forgiveness Earned Echo",
  470: "Honesty's Emotional Soul",
  477: "Climactic Healed Zenith",
  484: "Epic Reconnected Lives Bloom",
  490: "Shared's Unreal Sigil",
  497: "Peak Better Self",
  504: "Responsible Heart Brush",
  511: "Exalted Legacy Omen",
  517: "Empathy Learner Seal",
  524: "Supportive's Legacy Vow",
  531: "Celestial Repaired Myth",
  537: "Phantom Understanding Voice Pulse",
  544: "Maturity's Crimson Soul",
  551: "Silver Quiet Strength",
  557: "Rebuilt Friendships Vow",
  564: "Feral Legacy Thread",
  571: "Steady Growth Crown",
  578: "Reliable's Legacy Zenith",
  584: "Dread Healing Bloom",
  591: "Luminous Forgiven Self Soul",
  598: "Peace's Thunderous Flame",
  604: "Ultraviolet Inner Peace",
  611: "Emotional Soul",
  618: "Secret True Seal",
  625: "Kind Presence Path",
  631: "Restored's Legacy Vow",
  638: "Worldclass Balanced Brush",
  645: "Lawless Gentle Understanding Crest",
  651: "Quiet's Chosen Mark",
  658: "Fearless Social Rebuilder",
  665: "Empathetic Soul Soul",
  671: "Cinematic Legacy Crown",
  678: "Harmonized Past Thread",
  685: "Complete's Legacy Bloom",
  692: "Canonized Healing Sigil",
  698: "Ascendant Resolved Spirit Soul",
  705: "Reconciliation's Transfigured Spark",
  712: "Immortal Peaceful",
  718: "Eclipsed Emotional Soul",
  725: "Astral Legacy Path",
  732: "Calm Myth",
  739: "Letting's Go Pulse",
  745: "Prismatic Regret Crest",
  752: "Abyssal Soft Echo",
  759: "Quiet's Unbound Vow",
  765: "Eternal Healing Complete",
  772: "Inner Silence Crown",
  779: "Transcendent Legacy Brush",
  785: "Past Released Thread",
  792: "Gentle's Legacy Thread",
  799: "Ultimate Peaceful Flame",
  806: "Mythic Harmonized Life Spark",
  812: "Unburdened's Godlike Omen",
  819: "Canonical Pure",
  826: "Shared Humanity Path",
  832: "Heavenly Emotional Soul",
  839: "Complete Healing Pulse",
  846: "Soft's Legacy Crest",
  852: "Timeless Quiet Mark",
  859: "Empyrean Balanced Life Vow",
  866: "Mutual's Primordial Echo",
  873: "Omniscient Gentle Connection",
  879: "Last Barrier Zenith",
  886: "Apocalyptic Legacy Vow",
  893: "Friend Vow",
  899: "Restored's Legacy Flame",
  906: "Final Guilt Spark",
  913: "Crowned Pain Omen",
  920: "Silence's Mythic Seal",
  926: "Absolute Past",
  933: "Pure Presence Myth",
  940: "Cosmic Legacy Pulse",
  946: "Freedom Soul",
  953: "Wholeness's Legacy Mark",
  960: "Definitive Serene Brush",
  966: "Ultimate Endless Understanding Echo",
  973: "Acceptance's Infinite Crown",
  980: "Sovereign Complete Self",
  987: "Peace Incarnate Bloom",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate Silent Voice"
}
}
