import { AnimeThemeConfig } from "./types"
import { GiStarSwirl, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiCrystalBall, GiFlowerEmblem, GiFireworkRocket } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const amagiBrilliantParkTheme: AnimeThemeConfig = {
    id: "amagi-brilliant-park",
    displayName: "Amagi Brilliant Park",
    description: "High school narcissist Seiya is coerced at gunpoint into managing a failing amusement park inhabited by magical beings from a fantasy realm. With 100 days to draw 250,000 visitors, he brings ruthless efficiency to the rescue.",
    cssVars: {
        "--color-brand-200": "255 215 160",
        "--color-brand-300": "252 175 88",
        "--color-brand-400": "238 128 28",
        "--color-brand-500": "210 85 0",
        "--color-brand-600": "165 52 0",
        "--color-brand-700": "118 25 0",
        "--color-brand-800": "74 8 0",
        "--color-brand-900": "38 2 0",
        "--color-brand-950": "15 0 0",
        "--brand": "210 85 0",
        "--background": "#060100",
        "--paper": "#0f0200",
        "--color-gray-950": "6 1 0",
        "--color-gray-900": "16 4 1",
        "--color-gray-800": "30 9 2",
        "--color-gray-700": "52 18 4",
        "--color-gray-600": "82 32 8",
        "--color-gray-500": "125 60 18",
        "--color-gray-400": "168 102 45",
        "--color-gray-300": "208 152 82",
        "--color-gray-200": "238 195 130",
        "--color-gray-100": "252 228 182",
        "--color-gray-50": "255 244 228",
    },
    sidebarOverrides: {
        "home": { icon: GiFlowerEmblem, label: "Amagi Park" },
        "schedule": { icon: GiAlarmClock, label: "Park Schedule" },
        "manga": { icon: LuBookOpen, label: "Park Manual" },
        "lists": { icon: GiScrollUnfurled, label: "Cast Registry" },
        "discover": { icon: GiBullseye, label: "New Visitors" },
        "torrent-list": { icon: GiFireworkRocket, label: "Magic Cache" },
        "debrid": { icon: GiHeartKey, label: "Park Vault" },
        "unmatched": { icon: GiCrystalBall, label: "Magic Anomalies" },
        "enmasse": { icon: GiResize, label: "Park Event" },
        "scan-summaries": { icon: TbReportSearch, label: "Visitor Reports" },
        "auto-downloader": { icon: LuRss, label: "Visitor Feed" },
        "community": { icon: GiStarSwirl, label: "Amagi Circle" },
        "achievements": { icon: GiTrophyCup, label: "Park Trophies" },
        "milestones": { icon: LuFlag, label: "Visitor Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Park Alerts" },
        "theme-manager": { icon: GiPalette, label: "Park Colors" },
        "extensions": { icon: BiExtension, label: "Park Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Magic Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Seiya Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "Park Manager",
        "a_episode_counter": "Magic Anomalies Mark",
        "a_episode_titan": "Amagi Marathon Relic",
        "a_hours_invested": "Manager Proof",
        "a_time_lord": "Park Manual Decree",
        "a_anime_collector": "Seiya Catalogue",
        "a_library_legend": "Park Alerts Library",
        "a_first_complete": "First Visitor Wave",
        "a_hundred_club": "100,000 Visitors",
        "a_first_day": "Amagi Seal",
        "a_first_rating": "Seiya Appraisal",
        "a_ten_thousand_min": "Park Saved Standard",
        "a_season_veteran": "Park Alerts Library Library",
        "a_year_explorer": "Narcissist Hero Map",
        "a_century_watcher": "Saved Ledger",
        "a_five_hundred_eps": "Park Dominion",
        "a_thousand_eps": "Amagi Circle Record",
        "a_watching_ten": "Seiya Acclaim",
        "a_ptw_hoarder": "Park Archive Library",
        "a_dropped_honesty": "Visitors Summit",
        "a_five_thousand_eps": "Park Warrant",
        "a_ten_completed": "Hero Afterglow",
        "a_fifty_completed": "Visitor Wave Ascension",
        "a_five_hundred_completed": "Opening Clear",
        "a_mean_score_tracker": "Visitor Verdict",
        "a_unique_studios": "Visitor Collection",
        "a_days_spent_watching": "Grand Opening Dominion",
        "a_all_status": "Visitor Testament",
        "a_first_favorite": "Regular Cabinet",
        "a_favorites_collector": "Hero Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Park Vault Drive",
        "a_marathon_runner": "Grand Opening Gauntlet",
        "a_weekend_warrior": "Regular Ordeal",
        "a_non_stop": "Park Fever",
        "a_one_more_episode": "Amagi Circle Mantle",
        "a_speed_run": "Park Vault Vigil",
        "a_double_feature": "Park Regular Crown",
        "a_triple_threat": "Seiya Record",
        "a_five_a_day": "Park Alerts Accord",
        "a_back_to_back": "Visitor Wave Surge",
        "a_seasonal_binge": "Park Regular Cascade",
        "a_cour_crusher": "Amagi Ordeal",
        "a_half_day_watch": "Park Regular Crown Crown",
        "a_full_day_watch": "Visitor Pinnacle",
        "a_power_weekend": "Amagi Brilliant Park Run",
        "a_binge_king": "Amagi Marathon",
        "a_no_sleep": "Visitor Vigil",
        "a_entire_season": "Park Trophies Vault",
        "a_seven_day_challenge": "Magic Anomalies Mark Mark",
        "a_hundred_day_binge": "Narcissist Surge",
        "a_genre_binge": "Amagi Circle Binge",
        "a_studio_binge": "Amagi Fever",
        "a_season_sweep": "Hero Codex",
        "a_forty_eight_hour": "Park Event Overture",
        "a_ep_counter_day": "Manager Aegis",
        "a_multi_series_binge": "Park Event Streak",
        "a_midnight_binge": "Opening Cascade",
        "a_new_year_binge": "Visitor Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Seiya Action",
        "a_genre_adventure": "Grand Opening Adventure",
        "a_genre_comedy": "Park Manager Comedy",
        "a_genre_drama": "Archive Drama",
        "a_genre_fantasy": "Marathon Fantasy",
        "a_genre_horror": "Magic Anomalies Horror",
        "a_genre_mystery": "Amagi Park Mystery",
        "a_genre_romance": "Visitor Wave Romance",
        "a_genre_scifi": "Amagi Circle Sci-Fi",
        "a_genre_sol": "Park Alerts Slice",
        "a_genre_sports": "Narcissist Sports",
        "a_genre_supernatural": "Park Supernatural",
        "a_genre_thriller": "Amagi Circle Thriller",
        "a_genre_mecha": "Visitor Mecha",
        "a_genre_music": "Park Music",
        "a_genre_psychological": "Park Trophies Psychological",
        "a_genre_ecchi": "Amagi Park Ecchi",
        "a_genre_mahou_shoujo": "Hero Magic Shoujo",
        "a_tag_isekai": "Amagi Brilliant Park Isekai",
        "a_tag_harem": "Marathon Harem",
        "a_tag_bl": "Magic Anomalies Bl",
        "a_tag_gl": "Wave Gl",
        "a_tag_historical": "Visitors Historical",
        "a_tag_military": "Grand Military",
        "a_tag_school": "Park Archive School",
        "a_tag_martial_arts": "Park Manual Martial Arts",
        "a_tag_vampire": "Amagi Marathon Vampire",
        "a_tag_samurai": "Magic Anomalies Samurai",
        "a_tag_space": "Park Regular Space",
        "a_tag_parody": "Grand Parody",
        "a_tag_idol": "Park Manual Idol",
        "a_tag_post_apocalyptic": "Park Vault Post Apocalyptic",
        "a_tag_cyberpunk": "Park Saved Cyberpunk",
        "a_tag_shounen": "Opening Shounen",
        "a_tag_seinen": "Magic Anomalies Seinen",
        "a_tag_shoujo": "Seiya Shoujo",
        "a_tag_josei": "Visitor Wave Josei",
        "a_tag_survival": "Visitor Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "250,000 Visitors",
        "a_mega_completionist": "Park Saved",
        "a_completion_rate_50": "Marathon Return",
        "a_completion_rate_75": "Park Trophies Crown",
        "a_completion_rate_90": "Archive Resolution",
        "a_no_drop": "Park Manual Decree Decree",
        "a_long_runner_complete": "Opening Clear Clear",
        "a_sequel_chain": "Park Vault Insignia",
        "a_clean_list": "Park Regular Relic",
        "a_from_ptw": "Archive Index",
        "a_rewatch_master": "Manager Return",
        "a_short_complete": "Opening Endgame",
        "a_same_day_start_finish": "Visitor Pinnacle Pinnacle",
        "a_revival": "Narcissist Hero Insignia",
        "a_zero_to_hero": "Narcissist to Hero",
        "a_five_genre_complete": "Grand A Five Genre Complete",
        "a_full_franchise": "Park Trophies Chronicle",
        "a_batch_complete": "Park Event Crown",
        "a_paused_to_done": "Manager Aegis Aegis",
        "a_completion_spree": "Visitor Wave Triumph",
        "a_multi_rewatch": "Park Triumph",
        "a_dropped_recovery": "High Conquest",
        "a_ten_perfect_scores": "Visitors Acclaim",
        "a_seasonal_clear": "Amagi Brilliant Park Codex",
        "a_complete_genre_span": "Park Vault A Complete Genre",
        "a_monthly_completions": "Opening Afterglow",
        "a_yearly_completions": "Grand Epilogue",
        "a_rapid_complete": "Park Archive Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Park Regular",
        "a_studio_devotee": "Archive Treasury",
        "a_rewatcher": "Regular Closure",
        "a_triple_rewatch": "Narcissist Coda",
        "a_annual_tradition": "High Proof",
        "a_director_fan": "High Trial",
        "a_voice_actor_fan": "Amagi Brilliant Park Crown",
        "a_ost_lover": "Visitor Wave Seal",
        "a_source_reader": "Regular Cabinet Cabinet",
        "a_waiting_weekly": "Visitor Wave Clock",
        "a_childhood_revisit": "Park Saved Seal",
        "a_saga_tracker": "Wave Standard",
        "a_genre_loyalty": "Park Regular Loyalty",
        "a_decade_watcher": "Narcissist Banner",
        "a_adaptation_hunter": "Park Trophies Trial",
        "a_original_anime_fan": "Wave Testament",
        "a_long_commitment": "Grand Mark",
        "a_perfect_attendance": "Grand Opening Standard",
        "a_favorite_studio_5": "Grand Library",
        "a_complete_catalog": "Narcissist Hero Seal",
        "a_franchise_collector": "Park Manual Archive",
        "a_airing_follower": "Archive Signal",
        "a_genre_master": "Park Manual Master",
        "a_staff_follower": "Park Saved Oath",
        "a_multi_season_fan": "Visitor Wave Hoard",
        "a_format_diversity": "Park Trophies Cache",
        "a_year_dedication": "Park Trophies Tenure",
        "a_season_dedication": "Saved Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Park Alerts Explorer",
        "a_studio_hopper": "Seiya Collection",
        "a_tag_explorer": "Park Vault Explorer",
        "a_decade_hopper": "Park Trophies Chronicle Chronicle",
        "a_hidden_gem": "Grand Opening Warrant",
        "a_popular_taste": "Opening Decree",
        "a_retro_appreciator": "Park Event Aegis",
        "a_modern_viewer": "Park Vault Pinnacle",
        "a_cross_demographic": "Cast Registry Pinnacle",
        "a_underdog_fan": "Manager Trial",
        "a_variety_week": "Park Trophies Horizon",
        "a_foreign_cinema": "Magic Anomalies Expedition",
        "a_classic_connoisseur": "Grand Glimpse",
        "a_every_season": "Park Manual Archive Archive",
        "a_award_winner": "Seiya Insignia",
        "a_niche_explorer": "Park Event Horizon",
        "a_global_anime": "Narcissist Hero Decree",
        "a_cult_classic": "Narcissist Hero Classic",
        "a_random_pick": "Amagi Marathon Decree",
        "a_new_genre_month": "Park Event A New Genre",
        "a_seasonal_completionist": "Visitors Seasonal",
        "a_unpopular_opinion": "Park Alerts Standard",
        "a_top_rated_viewer": "Park Saved Seal Seal",
        "a_source_variety": "Park Storehouse",
        "a_low_score_brave": "Amagi Marathon Measure",
        "a_upcoming_watcher": "Visitor Wave Seal Seal",
        "a_short_series_explorer": "Archive Expedition",
        "a_long_series_explorer": "Park Manual Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Park Vault Insignia Insignia",
        "a_early_bird": "Park Saved Banner",
        "a_lunch_break": "Park Event Trial",
        "a_golden_hour": "Manager Tenure",
        "a_four_am_club": "Park Manual Gathering",
        "a_witching_hour": "Magic Tenure",
        "a_new_year_watch": "Park Regular Season",
        "a_midnight_premiere": "Park Regular Devotion",
        "a_all_hours": "Grand Opening Seal",
        "a_dawn_warrior": "Park Manager Aegis",
        "a_afternoon_delight": "Magic Proof",
        "a_prime_time": "Cast Registry Insignia",
        "a_workday_watcher": "Visitors Pinnacle",
        "a_sunday_marathon": "Archive Momentum",
        "a_rainy_day": "Park Manual Relic",
        "a_morning_routine": "Amagi Park Promise",
        "a_night_shift": "Magic Aegis",
        "a_twilight_zone": "Amagi Marathon Ledger",
        "a_seasonal_premier": "Visitor Wave Cabinet",
        "a_clock_collector": "Visitor Repository",
        "a_weekend_binge_hours": "Park Event Streak Streak",
        "a_late_night_regular": "Narcissist Dominion",
        "a_sunrise_watcher": "Saved Relic",
        "a_holiday_watcher": "Park Event Pact",
        "a_every_day_of_week": "Opening Ledger",
        "a_monthly_hours": "Park Archive Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Park Vault Record",
        "a_party_host": "Cast Registry Record",
        "a_social_butterfly": "Park Regular Company",
        "a_group_binge": "Wave Sprint",
        "a_party_regular": "Marathon Chronicle",
        "a_sync_viewer": "Park Trophies Standard",
        "a_commentator": "Visitor Record",
        "a_party_marathon": "Cast Registry Vigil",
        "a_full_house": "Park Event Trial Trial",
        "a_community_pillar": "Magic Alliance",
        "a_watch_party_streak": "Cast Registry Vigil Vigil",
        "a_diverse_party": "Grand Opening Seal Seal",
        "a_late_night_party": "Park Alerts Testament",
        "a_party_veteran": "Park Alerts Testament Testament",
        "a_genre_party": "Amagi Circle Party",
        "a_weekly_party": "High Calendar",
        "a_silent_viewer": "Narcissist Hero Mantle",
        "a_recommendation_giver": "High Network",
        "a_party_completionist": "Visitor Wave Coda",
        "a_social_scorer": "Park Manual Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Marathon Proof",
        "a_fibonacci": "Visitor Wave Dominion",
        "a_palindrome_day": "Park Regular Relic Relic",
        "a_binary_day": "Archive Mark",
        "a_full_moon": "Visitors Insignia",
        "a_leap_year": "Saved Devotion",
        "a_time_traveler": "Seiya Record Record",
        "a_genre_clash": "Park Alerts Clash",
        "a_triple_seven": "Archive Testament",
        "a_thousand_complete": "Wave Epilogue",
        "a_pi_episodes": "Park Manual Crown",
        "a_synchronicity": "Narcissist Hero Anchor",
        "a_world_record": "Park Warrant Warrant",
        "a_nice": "Magic Chronicle",
        "a_power_level": "Park Trophies Accord",
        "a_answer_42": "Park Alerts Standard Standard",
        "a_square_number": "Cast Registry Relic",
        "a_prime_count": "Magic Anomalies Warrant",
        "a_matching_date": "Narcissist Hero Mantle Mantle",
        "a_century_episode": "Amagi Park Mark",
        "a_double_digits": "Archive Testament Testament",
        "a_one_two_three": "Narcissist Hero Decree Decree",
        "a_lucky_seven": "Amagi Marathon Crown",
        "a_all_tens": "Amagi Criterion",
        "a_exact_hundred_eps": "Archive Standard",
        "a_year_match_count": "Amagi Clock",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Saved Ledger Ledger",
        "a_movie_buff": "Grand Mark Mark",
        "a_ova_hunter": "Grand Standard",
        "a_ona_explorer": "Park Trophies Secret",
        "a_special_watcher": "Hero Relic",
        "a_short_king": "Hero Crown",
        "a_variety_pack": "Visitors Inquiry",
        "a_film_festival": "Manager Chronicle",
        "a_music_video": "Manager Chronicle Chronicle",
        "a_tv_short": "Cast Registry Record Record",
        "a_movie_marathon": "Grand Opening Gauntlet Gauntlet",
        "a_double_length": "Amagi Brilliant Park Crown Crown",
        "a_anthology": "High Aegis",
        "a_mini_series": "Amagi Marathon Decree Decree",
        "a_theatrical": "Magic Anomalies Accord",
        "a_format_master": "Grand Vault",
        "a_long_movie": "Visitor Insignia",
        "a_back_catalog": "Park Trophies Testament",
        "a_cm_watcher": "Park Event Aegis Aegis",
        "a_pv_collector": "Narcissist Storehouse",
        "a_format_balance": "Park Archive Vault",
        "a_episodic_master": "Grand Standard Standard",
        "a_sequel_movie": "Narcissist Hero Pinnacle",
        "a_recap_watcher": "Amagi Park Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Park Regular Daily",
        "a_mega_streak": "Archive Streak",
        "a_weekly_warrior": "Opening Season",
        "a_monthly_watcher": "Park Manager Calendar",
        "a_comeback": "Cast Registry Relic Relic",
        "a_weekend_streak": "Park Manager Passage",
        "a_no_zero_days": "Narcissist Warrant",
        "a_iron_will": "Regular Seal",
        "a_habit_formed": "Regular Warrant",
        "a_consistent_pace": "Park Manual Measure",
        "a_year_long": "Amagi Marathon Season",
        "a_double_streak": "Amagi Circle Watch",
        "a_streak_recovery": "Opening Season Season",
        "a_daily_minimum": "Park Vault Focus",
        "a_winter_streak": "Visitors Watch",
        "a_summer_streak": "Grand Opening Resolve",
        "a_morning_streak": "Park Clock",
        "a_night_streak": "Park Vault Constancy",
        "a_unbreakable": "Park Trophies Proof",
        "a_eternal_flame": "Archive Standard Standard",
        "a_completion_streak": "High Return",
        "a_rating_streak": "Park Regular Balance",
        "a_multi_ep_streak": "Grand Ritual",
        "a_genre_streak": "Amagi Brilliant Park Streak",
        "a_studio_streak": "Grand Opening Cabinet",
        "a_perfect_week": "Narcissist Hero Ledger",

        // ── ANIME SCORING ──
        "a_critic": "Magic Scrutiny",
        "a_perfect_ten": "Saved Audit",
        "a_harsh_critic": "Wave Gauge",
        "a_fair_judge": "Park Regular Balance Balance",
        "a_generous_spirit": "Narcissist Record",
        "a_score_all": "Park Saved Criterion",
        "a_wide_range": "Opening Ledger Ledger",
        "a_controversial": "Opening Decree Decree",
        "a_consistent_scorer": "Seiya Verdict",
        "a_score_sniper": "Park Archive Score",
        "a_evolving_taste": "Park Trophies Accord Accord",
        "a_bell_curve": "Cast Registry Insignia Insignia",
        "a_picky_watcher": "Park Archive Warrant",
        "a_100_rated": "Grand Banner",
        "a_500_rated": "Amagi Circle Pinnacle",
        "a_mediocre_majority": "Visitor Wave Canon",
        "a_rating_spree": "Park Archive Review",
        "a_score_variance": "Wave Score",
        "a_masterpiece_hunter": "Park Banner",
        "a_contrarian": "Visitors Record",
        "a_optimist": "Visitors Crown",
        "a_score_distributor": "Narcissist Hero Appraisal",
        "a_genre_critic": "Magic Anomalies Critic",
        "a_mean_above_8": "Park Trophies Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "Amagi Resolve",
        "a_valentines_weeb": "Opening Vow",
        "a_pi_day": "Manager Trial Trial",
        "a_april_fools": "Opening Devotion",
        "a_international_anime_day": "Visitors Pinnacle Pinnacle",
        "a_star_wars_day": "Park Event Chronicle",
        "a_summer_solstice": "Magic Calendar",
        "a_tanabata": "Amagi Circle Focus",
        "a_friday_13th": "Park Manual Relic Relic",
        "a_halloween_spirit": "Hero Vow",
        "a_thanksgiving_binge": "Hero Run",
        "a_christmas_special": "Hero Season",
        "a_new_years_eve": "Grand Opening Pilgrimage",
        "a_birthday_watch": "Amagi Brilliant Park Vow",
        "a_holiday_marathon": "Park Event Overture Overture",
        "a_independence_day": "Park Saved Banner Banner",
        "a_culture_day": "Visitor Wave Pinnacle",
        "a_spring_equinox": "Saved Decree",
        "a_earth_day": "Regular Mantle",
        "a_labor_day": "Amagi Seal Seal",
        "a_winter_solstice": "Amagi Pilgrimage",
        "a_anime_birthday": "Amagi Birthday",
        "a_every_holiday": "Park Resolve",
        "a_consecutive_holidays": "Park Regular Season Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Seiya Rank",
        "a_meta_collector": "Grand Opening Hoard",
        "a_meta_category_starter": "Park Vault Badge",
        "a_meta_tier_climber": "Park Trophies Glyph",
        "a_meta_tier_max": "Grand Writ",
        "a_meta_xp_earner": "High Emblem",
        "a_meta_difficulty_easy": "Amagi Brilliant Park Mechanism",
        "a_meta_difficulty_hard": "Park Archive Writ",
        "a_meta_unlock_spree": "Archive Panel",
        "a_meta_completionist": "Seiya Fulfillment",
        "a_meta_diverse": "High Emblem Emblem",
        "a_meta_dominator": "Visitor Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "Grand Opening",
        "m_chapter_counter": "Seiya Pinnacle",
        "m_chapter_titan": "Park Regular Legend",
        "m_reading_hours": "Saved Relic Relic",
        "m_reading_time_lord": "Park Saved Record",
        "m_manga_collector": "High Ledger",
        "m_library_legend": "High Reliquary",
        "m_first_complete": "Amagi Triumph",
        "m_hundred_club": "Magic Network",
        "m_first_day": "Narcissist Seal",
        "m_first_rating": "Park Event Eye",
        "m_ten_thousand_pages": "Archive Gauge",
        "m_volume_collector": "Amagi Storehouse",
        "m_year_explorer": "Park Saved Quest",
        "m_century_reader": "Amagi Dominion",
        "m_five_hundred_ch": "Amagi Marathon Legend",
        "m_thousand_ch": "Archive Legend",
        "m_reading_ten": "Amagi Circle Appraisal",
        "m_ptr_hoarder": "Grand Index",
        "m_dropped_honesty": "Visitors Honesty",
        "m_season_reader": "Amagi Park Treasury",
        "m_active_reader": "Amagi Brilliant Park Chronicle",
        "m_five_thousand_ch": "Park Alerts Legend",
        "m_ten_completed": "Park Alerts Resolution",
        "m_fifty_completed": "Hero Harvest",
        "m_five_hundred_completed": "Grand Legacy",
        "m_mean_score_tracker": "Amagi Marathon Audit",
        "m_unique_authors": "Park Trophies Reserve",
        "m_all_status": "Cast Registry Testament",
        "m_first_favorite": "Park Manager Cache",
        "m_favorites_collector": "Amagi Brilliant Park Shelf",
        "m_days_spent_reading": "Saved Decree Decree",

        // ── MANGA BINGE ──
        "m_binge_reader": "Magic Streak",
        "m_marathon_reader": "Marathon Rush",
        "m_weekend_reader": "Amagi Marathon Run",
        "m_non_stop_reading": "Visitor Wave Gauntlet",
        "m_one_more_chapter": "Park Archive Testament",
        "m_speed_read": "Visitors Drive",
        "m_double_story": "Grand Opening Banner",
        "m_triple_read": "Amagi Circle Record Record",
        "m_five_a_day": "Amagi Circle Insignia",
        "m_chapter_chain": "Grand Accord",
        "m_volume_binge": "Visitors Drive Drive",
        "m_power_reader": "Park Seal",
        "m_half_day_read": "Park Manager Aegis Aegis",
        "m_full_day_read": "Magic Aegis Aegis",
        "m_power_weekend": "Marathon Streak",
        "m_binge_king": "Magic Anomalies Momentum",
        "m_no_sleep_read": "Park Event Rush",
        "m_full_series_rush": "Amagi Marathon Cascade",
        "m_seven_day_challenge": "Grand Opening Warrant Warrant",
        "m_hundred_day_read": "Amagi Marathon Legend Relic",
        "m_volume_rush": "Visitor Wave Gauntlet Gauntlet",
        "m_series_sweep": "Marathon Trial",
        "m_genre_binge": "Visitors Binge",
        "m_author_binge": "Grand Opening Surge",
        "m_chapter_counter_day": "Park Regular Ledger",
        "m_multi_series_binge": "Amagi Circle Charge",
        "m_midnight_binge": "Amagi Park Tempest",
        "m_new_year_binge": "Park Event Passage",
        "m_forty_eight_hour": "Amagi Brilliant Park Rally",
        "m_oneshot_binge": "Archive Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Narcissist Action",
        "m_genre_adventure": "Park Regular Adventure",
        "m_genre_comedy": "Grand Opening Comedy",
        "m_genre_drama": "Amagi Brilliant Park Drama",
        "m_genre_fantasy": "Magic Anomalies Fantasy",
        "m_genre_horror": "Hero Horror",
        "m_genre_mystery": "Regular Mystery",
        "m_genre_romance": "Grand Romance",
        "m_genre_scifi": "Cast Registry Sci-Fi",
        "m_genre_sol": "Park Regular Slice",
        "m_genre_sports": "Opening Sports",
        "m_genre_supernatural": "Manager Supernatural",
        "m_genre_thriller": "Amagi Park Thriller",
        "m_genre_psychological": "Park Vault Psychological",
        "m_genre_isekai": "Park Vault Isekai",
        "m_genre_shounen": "Magic Shounen",
        "m_genre_ecchi": "Visitor Wave Ecchi",
        "m_genre_mahou_shoujo": "Amagi Park Magic Shoujo",
        "m_genre_mecha": "Magic Anomalies Mecha",
        "m_genre_music": "Narcissist Music",
        "m_tag_isekai_new": "Magic Anomalies Isekai New",
        "m_tag_harem": "Grand Harem",
        "m_tag_bl": "Grand Bl",
        "m_tag_gl": "Opening Gl",
        "m_tag_historical": "Park Manual Historical",
        "m_tag_military": "Amagi Military",
        "m_tag_school": "Regular School",
        "m_tag_martial_arts": "Grand Opening Martial Arts",
        "m_tag_vampire": "Park Vault Vampire",
        "m_tag_samurai": "Marathon Samurai",
        "m_tag_space": "Hero Space",
        "m_tag_parody": "Regular Parody",
        "m_tag_idol": "Narcissist Hero Idol",
        "m_tag_post_apocalyptic": "Wave Post Apocalyptic",
        "m_tag_cyberpunk": "Wave Cyberpunk",
        "m_tag_shoujo": "High Shoujo",
        "m_tag_survival": "Amagi Brilliant Park Survival",
        "m_tag_cooking": "Park Manual Cooking",
        "m_tag_medical": "Visitors Medical",
        "m_tag_villainess": "Visitors Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Park Archive",
        "m_mega_completionist": "Park Archive Resolution",
        "m_completion_rate_50": "Park Trophies Return",
        "m_completion_rate_75": "Narcissist Ascension",
        "m_completion_rate_90": "Park Archive Resolution Resolution",
        "m_no_drop": "Park Vault Relic",
        "m_long_runner_complete": "Amagi Marathon Clear",
        "m_sequel_chain": "Magic Anomalies Warrant Warrant",
        "m_clean_list": "Narcissist Hero Ledger Ledger",
        "m_from_ptr": "Wave Accord",
        "m_reread_master": "Park Trophies Trial Trial",
        "m_oneshot_complete": "Amagi Ascension",
        "m_same_day_start_finish": "Amagi Circle Decree",
        "m_revival": "Grand Accord Accord",
        "m_zero_to_hundred": "Narcissist Legend",
        "m_five_genre_complete": "Manager M Five Genre Complete",
        "m_full_collection": "Park Manager Proof",
        "m_batch_complete": "Narcissist Hero Testament",
        "m_paused_to_done": "Amagi Park Standard",
        "m_completion_spree": "Narcissist Triumph",
        "m_format_completionist": "Cast Registry Completion",
        "m_catch_up": "Amagi Brilliant Park Proof",
        "m_multi_reread": "Grand Opening Banner Banner",
        "m_dropped_recovery": "Marathon Conquest",
        "m_ten_perfect_scores": "Amagi Marathon Judgment",
        "m_complete_genre_span": "Regular M Complete Genre Span",
        "m_monthly_completions": "Manager Monthly",
        "m_yearly_completions": "Grand Yearlong",
        "m_rapid_complete": "Archive Finale",
        "m_author_complete": "Saved Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Amagi Park Legacy",
        "m_mangaka_lover": "Magic Anomalies Standard",
        "m_rereader": "Saved Return",
        "m_triple_reread": "Amagi Park Testament Testament",
        "m_annual_reread": "Park Banner Banner",
        "m_publisher_fan": "Wave Mark",
        "m_artist_fan": "Visitors Insignia Insignia",
        "m_adaptation_compare": "Visitor Insignia Insignia",
        "m_source_material_fan": "Park Trophies Cache Cache",
        "m_waiting_weekly": "Grand Streak",
        "m_classic_reader": "Visitors Lantern",
        "m_saga_reader": "Amagi Circle Decree Decree",
        "m_genre_loyalty": "Park Manager Loyalty",
        "m_decade_reader": "Grand Banner Banner",
        "m_ln_adaptation": "Archive Mark Mark",
        "m_original_work": "Park Archive Standard",
        "m_long_commitment": "Park Alerts Mark",
        "m_up_to_date": "Visitor Wave Warrant",
        "m_favorite_mangaka": "Magic Anomalies Treasury",
        "m_complete_portfolio": "Park Saved Triumph",
        "m_franchise_collector": "Saved Archive",
        "m_serialization_follower": "Park Event Handshake",
        "m_genre_master": "Amagi Marathon Master",
        "m_multi_series_author": "Narcissist Pinnacle",
        "m_format_diversity": "Opening Shelf",
        "m_year_dedication": "Park Event Tenure",
        "m_ongoing_follower": "Park Manager Fellowship",
        "m_genre_loyalty_50": "Magic Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Grand Opening Explorer",
        "m_publisher_hopper": "Visitors Record Record",
        "m_tag_explorer": "Grand Explorer",
        "m_decade_hopper": "Magic Chronicle Chronicle",
        "m_hidden_gem": "Park Archive Mark",
        "m_popular_taste": "Park Saved Mantle",
        "m_retro_reader": "Wave Testament Testament",
        "m_modern_reader": "Park Archive Warrant Warrant",
        "m_cross_demographic": "Amagi Marathon Crown Crown",
        "m_underdog_fan": "Manager Accord",
        "m_variety_week": "Marathon Horizon",
        "m_manhwa_reader": "Manager Proof Proof",
        "m_manhua_reader": "Visitors Mantle",
        "m_classic_connoisseur": "Archive Glimpse",
        "m_award_winner": "Archive Warrant",
        "m_niche_explorer": "Marathon Horizon Horizon",
        "m_world_manga": "Park Event Chronicle Chronicle",
        "m_cult_classic": "Amagi Circle Map",
        "m_random_pick": "Park Event Testament",
        "m_new_genre_month": "Park Manual M New Genre",
        "m_year_completionist": "Park Vault Fulfillment",
        "m_unpopular_opinion": "Marathon Aegis",
        "m_top_rated_reader": "Amagi Circle Pinnacle Pinnacle",
        "m_source_variety": "Visitor Catalogue",
        "m_low_score_brave": "Park Alerts Score",
        "m_short_manga_explorer": "Park Saved Compass",
        "m_long_manga_explorer": "Park Archive Survey",
        "m_serialization_explorer": "Park Manual Road",

        // ── MANGA TIME ──
        "m_night_owl": "Marathon Mark",
        "m_early_bird": "Park Archive Dominion",
        "m_lunch_reader": "Visitors Ledger",
        "m_commute_reader": "Manager Tenure Tenure",
        "m_four_am_club": "Manager Fellowship",
        "m_new_year_read": "Marathon Pact",
        "m_all_hours": "Marathon Mark Mark",
        "m_prime_time_reader": "Visitor Wave Banner",
        "m_workday_reader": "Park Archive Accord",
        "m_sunday_read": "Park Trophies Testament Testament",
        "m_morning_routine": "Park Saved Discipline",
        "m_night_shift_reader": "Wave Accord Accord",
        "m_seasonal_premier_read": "Regular Storehouse",
        "m_clock_collector": "Park Event Reserve",
        "m_late_night_horror": "Amagi Park Mark Mark",
        "m_afternoon_reader": "Amagi Circle Mantle Mantle",
        "m_golden_hour_reader": "Amagi Park Observance",
        "m_dawn_reader": "Cast Registry Mantle",
        "m_twilight_reader": "Park Manual Crown Crown",
        "m_midnight_start": "Park Regular Routine",
        "m_weekend_binge_hours": "Archive Momentum Momentum",
        "m_late_night_regular": "Magic Anomalies Testament",
        "m_sunrise_reader": "Grand Opening Mantle",
        "m_every_day_of_week": "Park Seal Seal",
        "m_monthly_hours": "Cast Registry Monthly",
        "m_bedtime_reader": "Wave Banner",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Cast Registry Mantle Mantle",
        "m_webtoon_reader": "Park Archive Mark Mark",
        "m_full_color": "Park Alerts Accord Accord",
        "m_doujin_reader": "Park Mantle",
        "m_anthology_reader": "Archive Accord",
        "m_adaptation_reader": "Narcissist Banner Banner",
        "m_longstrip_reader": "Hero Chronicle",
        "m_4koma_reader": "Amagi Brilliant Park Relic",
        "m_oneshot_reader": "Grand Opening Insignia",
        "m_format_variety": "Saved Gallery",
        "m_light_novel_reader": "Narcissist Pinnacle Pinnacle",
        "m_novel_reader": "Seiya Decree",
        "m_visual_storyteller": "Park Event Accord",
        "m_colored_classic": "Wave Survey",
        "m_webcomic_fan": "Seiya Insignia Insignia",
        "m_manga_to_anime": "Park Mantle Mantle",
        "m_seinen_reader": "Cast Registry Pinnacle Pinnacle",
        "m_josei_reader": "Park Vault Pinnacle Pinnacle",
        "m_award_winning_art": "Amagi Brilliant Park Relic Relic",
        "m_debut_work": "Narcissist Dominion Dominion",
        "m_vertical_scroll": "Amagi Relic",
        "m_traditional_format": "Regular Hoard",
        "m_cross_media": "Archive Accord Accord",
        "m_spinoff_reader": "Park Trophies Mark",
        "m_remake_reader": "Visitor Wave Pinnacle Pinnacle",
        "m_collaboration_reader": "Park Manager Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Narcissist Hero Focus",
        "m_mega_streak": "Amagi Marathon Routine",
        "m_weekly_warrior": "Amagi Brilliant Park Season",
        "m_monthly_reader": "Park Discipline",
        "m_comeback": "Marathon Testament",
        "m_weekend_streak": "Visitor Wave Fever",
        "m_no_zero_days": "Amagi Brilliant Park Aegis",
        "m_iron_will": "Amagi Marathon Ledger Ledger",
        "m_habit_formed": "Amagi Relic Relic",
        "m_consistent_pace": "Park Event Scrutiny",
        "m_year_long": "Grand Observance",
        "m_double_streak": "Grand Opening Resolve Resolve",
        "m_streak_recovery": "Regular Resolve",
        "m_daily_minimum": "Amagi Circle Daily",
        "m_winter_streak": "Amagi Park Observance Observance",
        "m_summer_streak": "Park Alerts Observance",
        "m_morning_streak": "Grand Opening Clock",
        "m_night_streak": "Narcissist Discipline",
        "m_unbreakable": "Regular Warrant Warrant",
        "m_eternal_flame": "Regular Mantle Mantle",
        "m_chapter_a_day": "Cast Registry Ledger",
        "m_genre_streak": "Magic Streak Mode",
        "m_completion_streak": "High Return Return",
        "m_rating_streak": "Seiya Appraisal Appraisal",
        "m_multi_ch_streak": "Park Manager Tenure",
        "m_author_streak": "Park Manager Calendar Calendar",
        "m_perfect_week_manga": "Amagi Park Accord",
        "m_diverse_streak": "Amagi Park Streak",

        // ── MANGA SCORING ──
        "m_critic": "Magic Scrutiny Scrutiny",
        "m_perfect_ten": "Amagi Circle Verdict",
        "m_harsh_critic": "Manager Scale",
        "m_fair_judge": "Park Manager Eye",
        "m_generous_spirit": "Archive Ledger",
        "m_score_all": "Narcissist Hero Reckoning",
        "m_wide_range": "Amagi Brilliant Park Ledger",
        "m_controversial": "Magic Anomalies Standard Standard",
        "m_consistent_scorer": "Regular Grade",
        "m_score_sniper": "Cast Registry Reckoning",
        "m_evolving_taste": "Magic Trial",
        "m_bell_curve": "Amagi Park Accord Accord",
        "m_picky_reader": "Amagi Crown",
        "m_100_rated": "High Standard",
        "m_500_rated": "High Proof Proof",
        "m_mediocre_majority": "Amagi Canon",
        "m_rating_spree": "Cast Registry Verdict",
        "m_score_variance": "Amagi Brilliant Park Measure",
        "m_binge_rater": "High Passage",
        "m_reread_rerate": "Park Alerts Dominion",
        "m_masterpiece_hunter": "Amagi Banner",
        "m_contrarian": "Opening Trial",
        "m_optimist": "Park Manager Mark",
        "m_score_distributor": "Park Manual Balance Balance",
        "m_genre_critic": "Archive Critic",
        "m_mean_above_8": "Amagi Park Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Saved Season",
        "m_valentines_read": "Park Archive Observance",
        "m_pi_day": "Park Manager Accord",
        "m_april_fools": "Park Manual Devotion",
        "m_international_manga_day": "Amagi Brilliant Park Aegis Aegis",
        "m_free_comic_day": "High Chronicle",
        "m_summer_solstice": "Amagi Circle Focus Focus",
        "m_tanabata": "Narcissist Pilgrimage",
        "m_friday_13th": "Park Alerts Seal",
        "m_halloween_read": "High Halloween",
        "m_thanksgiving_binge": "Cast Registry Charge",
        "m_christmas_read": "Manager Pact",
        "m_new_years_eve": "Narcissist New Year",
        "m_birthday_read": "Amagi Circle Birthday",
        "m_holiday_marathon": "Opening Rally",
        "m_independence_day": "Marathon Aegis Aegis",
        "m_culture_day": "Narcissist Seal Seal",
        "m_spring_equinox": "Park Alerts Dominion Dominion",
        "m_earth_day": "High Aegis Aegis",
        "m_labor_day": "Wave Warrant",
        "m_winter_solstice": "Park Vault Focus Focus",
        "m_manga_birthday": "Amagi Park Ritual",
        "m_every_holiday_reader": "Cast Registry Watch",
        "m_consecutive_holidays": "Cast Registry Watch Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Saved Aegis",
        "m_fibonacci": "Regular Dominion",
        "m_palindrome_day": "Amagi Marathon Relic Relic",
        "m_binary_day": "Saved Aegis Aegis",
        "m_full_moon_read": "Hero Crown Crown",
        "m_leap_year_read": "Park Trophies Practice",
        "m_triple_seven": "Park Manager Trial",
        "m_thousand_complete": "Grand Opening Ascension",
        "m_nice": "Grand Warrant",
        "m_power_level_chapters": "Amagi Marathon Trial",
        "m_answer_42": "Amagi Brilliant Park Trial",
        "m_square_number": "Park Archive Standard Standard",
        "m_prime_count": "Park Alerts Record",
        "m_matching_date": "Grand Opening Insignia Insignia",
        "m_century_chapter": "Visitor Decree",
        "m_pi_chapters": "Marathon Proof Proof",
        "m_synchronicity": "Park Manager Emblem",
        "m_world_record": "Park Saved Warrant",
        "m_genre_clash": "Cast Registry Clash",
        "m_time_traveler": "Park Ledger",
        "m_double_digits": "Regular Dominion Dominion",
        "m_one_two_three": "Visitor Wave Warrant Warrant",
        "m_lucky_seven": "Narcissist Record Record",
        "m_exact_hundred_ch": "Archive Legend Testament",
        "m_year_match_count": "Opening Routine",
        "m_chapter_match_date": "Grand Opening Record",

        // ── MANGA FORMATS ──
        "m_manga_format": "Archive Index Index",
        "m_manhwa_format": "Amagi Marathon Gallery",
        "m_manhua_format": "Visitor Wave Storehouse",
        "m_ln_format": "Amagi Park Index",
        "m_oneshot_format": "Amagi Park Index Index",
        "m_doujin_format": "Park Cabinet",
        "m_novel_format": "Magic Reserve",
        "m_format_master_manga": "Grand Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Park Alerts Link",
        "m_meta_collector": "Magic Reliquary",
        "m_meta_category_starter": "High Standard Standard",
        "m_meta_tier_climber": "Cast Registry Token",
        "m_meta_tier_max": "Seiya Token",
        "m_meta_xp_earner": "Amagi Circle Anchor",
        "m_meta_difficulty_easy": "Park Archive Panel",
        "m_meta_difficulty_hard": "Archive Node",
        "m_meta_unlock_spree": "Visitor Wave Marker",
        "m_meta_completionist": "Park Saved Completion",
        "m_meta_diverse": "Narcissist Hero Anchor Anchor",
        "m_meta_dominator": "Archive Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060100",
        primary: "#d25500",
        secondary: "#5050a0",
        accent: "#f8d070",
    },
    particleColor: "#e08020",
    backgroundDim: 0.25,
    backgroundBlur: 15,
    milestoneNames: {
  1: "Threadbare Unmotivated Student Spark",
  8: "Lazy's Tarnished Omen",
  14: "Fractured Reluctant Visitor",
  21: "Forced Manager Force",
  28: "Lowborn Legacy Myth",
  35: "Ticket Counter Pulse",
  41: "Broken's Witness Crest",
  48: "Humble Skeptical Mark",
  55: "Ragged Low Morale Vow",
  61: "Accidental's Faint Echo",
  68: "Lesser Budget Disaster",
  75: "Inexperienced Planner Zenith",
  81: "Doubtful Manager Crown",
  88: "Crisis Survivor Sigil",
  95: "Barely's Admin Flame",
  102: "Really Cool Amagi Spark",
  108: "Awakened Park Assistant Omen",
  115: "Ticket's Resolute Seal",
  122: "Rising Staff Organizer",
  128: "Basic Manager Myth",
  135: "Dauntless Event Pulse",
  142: "Ride Supervisor Crest",
  149: "Low's Planner Mark",
  155: "Fresh Visitor Vow",
  162: "Valiant Operations Learner Echo",
  169: "Budget's Prime Crown",
  175: "Polished Staff Mediator",
  182: "Problem Fixer Bloom",
  189: "Stormlit Legacy Sigil",
  195: "Early Leadership Flame",
  202: "Official's Legacy Spark",
  209: "Tempered Amagi Omen",
  216: "Trusted Contract Holder Pact",
  222: "Operational's Steadfast Path",
  229: "Ironclad Guest Experience",
  236: "Resource Coordinator Pulse",
  242: "Core Solver Crest",
  249: "Minor Decision Mark",
  256: "Designer's Event Vow",
  262: "Formidable Staff Echo",
  269: "Lucid Magic Contract Pact",
  276: "Amagi's Ranked Zenith",
  283: "Fabled Mid Level",
  289: "Crisis Handler Sigil",
  296: "Seasoned Legacy Flame",
  303: "Senior Manager Spark",
  309: "Operations's Legacy Omen",
  316: "Valorous Ride Seal",
  323: "Stalwart Entertainment Coordinator Path",
  330: "Revenue's Commanding Myth",
  336: "Refined Guest Satisfaction",
  343: "Amagi Representative Crest",
  350: "Blazing Legacy Mark",
  356: "Contract User Pact",
  363: "Park's Legacy Echo",
  370: "Peerless Recovery Crown",
  376: "Ardent Magic Officer Zenith",
  383: "Performance's Focused Form",
  390: "Vigilant High Tier",
  397: "Park Revival Flame",
  403: "Elite Legacy Spark",
  410: "Amagi Core Omen",
  417: "Contract's Legacy Pact",
  423: "Sovereign Park Path",
  430: "Regal Operations Master Myth",
  437: "Entertainment's Crowned Pulse",
  444: "Mythborn Revenue Stabilizer",
  450: "System Mark",
  457: "Radiant Legacy Vow",
  464: "Senior Executive Echo",
  470: "Park's Expert Crown",
  477: "Climactic Guest Zenith",
  484: "Epic Magical Operations Bloom",
  490: "Elite's Unreal Sigil",
  497: "Peak Amagi Savior",
  504: "Park Vice Spark",
  511: "Exalted Staff Omen",
  517: "Master Coordinator Seal",
  524: "Unrivaled Contract Pact",
  531: "Celestial Park Myth",
  537: "Phantom Entertainment Visionary Pulse",
  544: "Operational's Crimson Crest",
  551: "Silver Revenue Miracle",
  557: "Amagi Core Vow",
  564: "Feral System Echo",
  571: "Park Legend Crown",
  578: "Executive's Legacy Zenith",
  584: "Dread Magical Bloom",
  591: "Luminous Near Director Sigil",
  598: "Amagi's Thunderous Flame",
  604: "Ultraviolet Park Director",
  611: "Amagi Master Omen",
  618: "Secret Legacy Pact",
  625: "Entertainment Crown",
  631: "Operational's Legacy Myth",
  638: "Worldclass Revenue Pulse",
  645: "Lawless Park Rebuilder Crest",
  651: "Integrator's Chosen Mark",
  658: "Fearless Legendary Manager",
  665: "Amagi Core Echo",
  671: "Cinematic Infrastructure Crown",
  678: "Guest Happiness Zenith",
  685: "Park's Hero Bloom",
  692: "Canonized Executive Sigil",
  698: "Ascendant Near Mythic Flame",
  705: "Park's Transfigured Spark",
  712: "Immortal Breakthrough",
  718: "Amagi Restoration Seal",
  725: "Astral Singularity Path",
  732: "Contract Evolution Pact",
  739: "Revenue's Legacy Pulse",
  745: "Prismatic Park Crest",
  752: "Abyssal Operational Transcendence Mark",
  759: "Magical's Unbound Vow",
  765: "Eternal Amagi Renaissance",
  772: "Overhaul Entity Crown",
  779: "Transcendent Engine Zenith",
  785: "Park Apex Form",
  792: "Linked's Legacy Sigil",
  799: "Ultimate Legendary Flame",
  806: "Mythic Park God Spark",
  812: "Entertainment's Godlike Omen",
  819: "Canonical Perfection",
  826: "Amagi Engine Path",
  832: "Heavenly Core Myth",
  839: "Entertainment Pulse",
  846: "Park's Entity Crest",
  852: "Timeless Ultimate Pact",
  859: "Empyrean Joy Distribution Vow",
  866: "Amagi's Primordial Form",
  873: "Omniscient Park",
  879: "Infinite Operations Zenith",
  886: "Apocalyptic Singularity Bloom",
  893: "Amagi Core Sigil",
  899: "Legend's Legacy Flame",
  906: "Final Apex Spark",
  913: "Crowned Management Omen",
  920: "Park's Mythic Seal",
  926: "Absolute Director",
  933: "Entertainment God Myth",
  940: "Cosmic True Pulse",
  946: "Infinite Joy Crest",
  953: "Class's Entity Mark",
  960: "Definitive Operational Vow",
  966: "Ultimate Amagi Overmind Echo",
  973: "God's Infinite Crown",
  980: "Sovereign End Park",
  987: "Final Form",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate Brilliant Park"
}
}
