import { AnimeThemeConfig } from "./types"
import { GiFlowerEmblem, GiForestCamp, GiGhost, GiHeartKey, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiSunflower } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const anohanaTheme: AnimeThemeConfig = {
    id: "anohana",
    displayName: "AnoHana",
    description: "Five years after the accidental death of Meiko 'Menma' Honma, her ghost appears to her childhood friend Jintan — the only one who can see her. She has one unfinished wish, and fulfilling it might finally let her rest.",
    fontFamily: "'Noto Serif JP', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "200 225 240",
        "--color-brand-300": "158 200 228",
        "--color-brand-400": "112 170 210",
        "--color-brand-500": "68 138 190",
        "--color-brand-600": "40 108 160",
        "--color-brand-700": "20 78 130",
        "--color-brand-800": "8 50 98",
        "--color-brand-900": "3 26 62",
        "--color-brand-950": "1 12 34",
        "--brand": "68 138 190",
        "--background": "#010405",
        "--paper": "#040c12",
        "--color-gray-950": "1 4 5",
        "--color-gray-900": "4 10 14",
        "--color-gray-800": "8 18 25",
        "--color-gray-700": "14 30 42",
        "--color-gray-600": "22 48 64",
        "--color-gray-500": "36 74 96",
        "--color-gray-400": "64 112 140",
        "--color-gray-300": "100 152 178",
        "--color-gray-200": "140 188 208",
        "--color-gray-100": "178 214 228",
        "--color-gray-50": "220 238 244",
    },
    sidebarOverrides: {
        "home": { icon: GiForestCamp, label: "Chichibu" },
        "schedule": { icon: GiAlarmClock, label: "Summer Schedule" },
        "manga": { icon: LuBookOpen, label: "Menma's Files" },
        "lists": { icon: GiHeartKey, label: "Super Peace Busters" },
        "discover": { icon: GiBullseye, label: "Wish Search" },
        "torrent-list": { icon: GiGhost, label: "Ghost Cache" },
        "debrid": { icon: GiFlowerEmblem, label: "Memory Store" },
        "unmatched": { icon: GiSunflower, label: "Lost Friends" },
        "enmasse": { icon: GiResize, label: "Group Reunion" },
        "scan-summaries": { icon: TbReportSearch, label: "Grief Reports" },
        "auto-downloader": { icon: LuRss, label: "Memory Feed" },
        "community": { icon: GiGhost, label: "Super Peace Busters" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Ghost Calls" },
        "achievements": { icon: GiTrophy, label: "Memory Titles" },
        "milestones": { icon: LuFlag, label: "Wish Goals" },
        "theme-manager": { icon: GiPalette, label: "Summer Colors" },
        "extensions": { icon: BiExtension, label: "Memory Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Memory Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Menma's Wish" },
    },
    achievementNames: {
        "a_first_episode": "Menma Returns",
        "a_first_complete": "Wish Fulfilled",
        "a_hundred_club": "Hundred Tears",
        "a_time_lord": "Grief Veteran",
        "a_anime_collector": "Memory Collection",
        "a_library_legend": "Summer Archives",
        "a_binge_king": "Emotional Marathon",
        "a_no_sleep": "All-Night Grief",
        "a_marathon_runner": "Chichibu Walk",
        "a_speed_run": "Jintan's Run",
        "a_completionist": "All Episodes",
        "a_mega_completionist": "Okada Master",
        "a_loyal_fan": "Menma's Friend",
        "a_rewatcher": "Painful Revisit",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "None Here",
        "a_genre_adventure": "Summer Journey",
        "a_genre_comedy": "Group Teasing",
        "a_genre_drama": "Grief Story",
        "a_genre_fantasy": "Ghost World",
        "a_genre_horror": "Survivor's Guilt",
        "a_genre_romance": "Lost Love",
        "a_genre_scifi": "Ghost Science",
        "a_genre_supernatural": "Menma Ghost",
        "a_genre_psychological": "Grief Processing",
        "a_genre_mecha": "None Here",
        "a_critic": "Tear Judge",
        "a_perfect_ten": "Menma's Smile",
        "a_harsh_critic": "Anaru's Standard",
        "a_daily_streak": "Daily Memory",
        "a_mega_streak": "Endless Summer",
        "a_year_long": "Year of Grief",
        "a_iron_will": "Jintan's Strength",
        "a_hidden_gem": "Hidden Memory",
        "a_cult_classic": "Okada Classic",
        "a_classic_connoisseur": "2011 Fan",
        "a_new_years_resolution": "New Year Memory",
        "a_christmas_special": "Winter Memory",
        "a_meta_tier_max": "Wish Granted",
        "a_meta_completionist": "All Memories",
        "a_sequel_chain": "Live Action",
        "a_zero_to_hero": "Hikikomori to Healed",
        "a_night_owl": "Night Ghost",
        "a_early_bird": "Morning Memory",
        "m_first_chapter": "First Memory",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Emotional Marathon",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "AnoHana Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Memory Return",
        "m_genre_action": "None Here",
        "m_genre_adventure": "Summer Chapter",
        "m_genre_romance": "Heart Chapter",
        "m_genre_fantasy": "Ghost Chapter",
        "m_genre_horror": "Guilt Chapter",
        "m_genre_drama": "Grief Chapter",
        "m_genre_scifi": "Unusual Chapter",
        "m_genre_supernatural": "Menma Chapter",
        "m_genre_psychological": "Healing Depth",
        "m_critic": "Grief Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Summer Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Healing Resolve",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Bittersweet Classic",
        "m_mangaka_lover": "Okada Fan",
        "m_source_material_fan": "Anime Original",
        "m_meta_tier_max": "AnoHana Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Summer Art",
        "m_manga_to_anime": "Anime Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#010405",
        primary: "#448abe",
        secondary: "#286ca0",
        accent: "#f0e080",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/anohana.jpg",
    particleColor: "#80c8f0",
    backgroundDim: 0.3,
    backgroundBlur: 14,
    particleTypes: {
        fireflies: { label: "Fireflies", maxCount: 20, defaultEnabled: true, defaultIntensity: 55 },
        dandelions: { label: "Dandelion Seeds", maxCount: 15, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
        1: "Hikikomori",
        5: "Jintan",
        15: "Ghost Seen",
        30: "Peace Buster",
        50: "Wish Seeker",
        75: "Memory Keeper",
        100: "Wish Granted",
    },
}
