import { AnimeThemeConfig } from "./types"
import { GiFlame, GiDaemonSkull, GiCrossedSwords, GiMagicPortal, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiSwordClash } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const aoNoExorcistTheme: AnimeThemeConfig = {
    id: "ao-no-exorcist",
    displayName: "Ao no Exorcist",
    description: "Rin Okumura discovers he is the son of Satan himself — and after his guardian's death, vows to become an exorcist and defeat his own father. Training at True Cross Academy, he must hide his demonic flames.",
    fontFamily: "'Exo 2', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Exo+2:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "155 175 235",
        "--color-brand-300": "112 138 218",
        "--color-brand-400": "70 100 195",
        "--color-brand-500": "35 65 168",
        "--color-brand-600": "18 42 138",
        "--color-brand-700": "8 24 105",
        "--color-brand-800": "3 12 72",
        "--color-brand-900": "1 5 42",
        "--color-brand-950": "0 2 22",
        "--brand": "35 65 168",
        "--background": "#000105",
        "--paper": "#02040e",
        "--color-gray-950": "0 1 5",
        "--color-gray-900": "2 4 12",
        "--color-gray-800": "5 8 22",
        "--color-gray-700": "9 14 38",
        "--color-gray-600": "16 24 62",
        "--color-gray-500": "28 40 95",
        "--color-gray-400": "52 68 135",
        "--color-gray-300": "88 104 172",
        "--color-gray-200": "128 145 205",
        "--color-gray-100": "168 182 228",
        "--color-gray-50": "212 218 245",
    },
    sidebarOverrides: {
        "home": { icon: GiMagicPortal, label: "True Cross Academy" },
        "schedule": { icon: GiAlarmClock, label: "Exorcist Schedule" },
        "manga": { icon: LuBookOpen, label: "Exorcist Files" },
        "lists": { icon: GiCrossedSwords, label: "Cram School" },
        "discover": { icon: GiBullseye, label: "Demon Hunt" },
        "torrent-list": { icon: GiDaemonSkull, label: "Demon Cache" },
        "debrid": { icon: GiFlame, label: "Satan's Flame" },
        "unmatched": { icon: GiSwordClash, label: "Unknown Demons" },
        "enmasse": { icon: GiResize, label: "Order Deploy" },
        "scan-summaries": { icon: TbReportSearch, label: "Mission Reports" },
        "auto-downloader": { icon: LuRss, label: "True Cross Feed" },
        "community": { icon: GiMagicPortal, label: "True Cross Order" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Order Alerts" },
        "achievements": { icon: GiTrophy, label: "Exorcist Medals" },
        "milestones": { icon: LuFlag, label: "Exorcist Goals" },
        "theme-manager": { icon: GiPalette, label: "Blue Flame Colors" },
        "extensions": { icon: BiExtension, label: "Exorcist Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Order Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Rin's Settings" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "Satan's Son",
        "a_episode_counter": "Father's Death Mark",
        "a_episode_titan": "Order Return Relic",
        "a_hours_invested": "Blue Exorcist Expert Proof",
        "a_time_lord": "Order Veteran",
        "a_anime_collector": "Demon Collection",
        "a_library_legend": "True Cross Archives",
        "a_first_complete": "Exorcist Qualified",
        "a_hundred_club": "Hundred Exorcisms",
        "a_first_day": "Katou Master Seal",
        "a_first_rating": "Order Return Appraisal",
        "a_ten_thousand_min": "Katou Classic Standard",
        "a_season_veteran": "Katou Classic Library",
        "a_year_explorer": "Cross Academy Map",
        "a_century_watcher": "Rin's Comrade Ledger",
        "a_five_hundred_eps": "Order Alerts Dominion",
        "a_thousand_eps": "Unknown Demons Record",
        "a_watching_ten": "Ao No Exorcist Acclaim",
        "a_ptw_hoarder": "Exorcist Medals Library",
        "a_dropped_honesty": "Ao No Exorcist Summit",
        "a_five_thousand_eps": "Order Revisit Warrant",
        "a_ten_completed": "Order Judge Afterglow",
        "a_fifty_completed": "Cross Archives Ascension",
        "a_five_hundred_completed": "Ao No Exorcist Clear",
        "a_mean_score_tracker": "Rin's Identity Verdict",
        "a_unique_studios": "Unknown Demons Collection",
        "a_days_spent_watching": "Identity Depth Dominion",
        "a_all_status": "Yukio's Review Testament",
        "a_first_favorite": "Rin Okumura Cabinet",
        "a_favorites_collector": "Hidden Demon Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Demon Battle Drive",
        "a_marathon_runner": "Blue Flame Run",
        "a_weekend_warrior": "Order Return Ordeal",
        "a_non_stop": "Gehenna Journey Fever",
        "a_one_more_episode": "All Exorcisms Mantle",
        "a_speed_run": "Rin's Speed",
        "a_double_feature": "All Demons Crown",
        "a_triple_threat": "Shiemi's Care Record",
        "a_five_a_day": "Decade Fan Accord",
        "a_back_to_back": "Night Training Surge",
        "a_seasonal_binge": "Order Return Cascade",
        "a_cour_crusher": "Identity Depth Ordeal",
        "a_half_day_watch": "Father's Death Crown",
        "a_full_day_watch": "Satan's Son Pinnacle",
        "a_power_weekend": "Katou Master Run",
        "a_binge_king": "Exorcist Marathon",
        "a_no_sleep": "All-Night Training",
        "a_entire_season": "Demon Spawn Library",
        "a_seven_day_challenge": "Satan's Son Mark",
        "a_hundred_day_binge": "Katou Master Surge",
        "a_genre_binge": "Gehenna Science Binge",
        "a_studio_binge": "Father's Death Fever",
        "a_season_sweep": "Winter Exorcism Codex",
        "a_forty_eight_hour": "Rin's Speed Overture",
        "a_ep_counter_day": "Order Judge Aegis",
        "a_multi_series_binge": "Exorcist Medals Streak",
        "a_midnight_binge": "All Exorcisms Cascade",
        "a_new_year_binge": "Demon Power Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Demon Battle",
        "a_genre_adventure": "Gehenna Journey",
        "a_genre_comedy": "Kuro's Play",
        "a_genre_drama": "Father's Death",
        "a_genre_fantasy": "Two Worlds",
        "a_genre_horror": "Demon Spawn",
        "a_genre_mystery": "Night Exorcism Mystery",
        "a_genre_romance": "Shiemi's Care",
        "a_genre_scifi": "Gehenna Science",
        "a_genre_sol": "Order Revisit Slice",
        "a_genre_sports": "Rin's Speed Sports",
        "a_genre_supernatural": "Demon Power",
        "a_genre_thriller": "Cross Archives Thriller",
        "a_genre_mecha": "None Here",
        "a_genre_music": "Katou Classic Music",
        "a_genre_psychological": "Rin's Identity",
        "a_genre_ecchi": "Demon Battle Ecchi",
        "a_genre_mahou_shoujo": "Shiemi's Care Magic Shoujo",
        "a_tag_isekai": "Blue Run Isekai",
        "a_tag_harem": "Katou Fan Harem",
        "a_tag_bl": "Rin's Speed Bl",
        "a_tag_gl": "All Exorcisms Gl",
        "a_tag_historical": "Demon Son Historical",
        "a_tag_military": "Order Alerts Military",
        "a_tag_school": "Exorcist Medals School",
        "a_tag_martial_arts": "Satan's Son Martial Arts",
        "a_tag_vampire": "Shiemi's Care Vampire",
        "a_tag_samurai": "Unknown Demons Samurai",
        "a_tag_space": "All Night Space",
        "a_tag_parody": "Cram School Parody",
        "a_tag_idol": "Rin's Speed Idol",
        "a_tag_post_apocalyptic": "Daily Training Post Apocalyptic",
        "a_tag_cyberpunk": "Gehenna Journey Cyberpunk",
        "a_tag_shounen": "Daily Training Shounen",
        "a_tag_seinen": "Cross Order Seinen",
        "a_tag_shoujo": "Cross Order Shoujo",
        "a_tag_josei": "Order Judge Josei",
        "a_tag_survival": "Hidden Demon Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "All Exorcisms",
        "a_mega_completionist": "Katou Master",
        "a_completion_rate_50": "Shiemi's Care Return",
        "a_completion_rate_75": "Cross Archives Crown",
        "a_completion_rate_90": "Order Judge Resolution",
        "a_no_drop": "Night Exorcism Decree",
        "a_long_runner_complete": "Katou Master Clear",
        "a_sequel_chain": "Kyoto Arc",
        "a_clean_list": "Winter Exorcism Relic",
        "a_from_ptw": "Cram School Index",
        "a_rewatch_master": "Rin's Identity Return",
        "a_short_complete": "Morning Class Endgame",
        "a_same_day_start_finish": "Endless Battle Pinnacle",
        "a_revival": "Rin's Comrade Insignia",
        "a_zero_to_hero": "Demon Son to Exorcist",
        "a_five_genre_complete": "Morning Class A Five Genre",
        "a_full_franchise": "Exorcist Medals Chronicle",
        "a_batch_complete": "Order Return Crown",
        "a_paused_to_done": "Order Judge Aegis Aegis",
        "a_completion_spree": "Son Exorcist Triumph",
        "a_multi_rewatch": "Son Exorcist Triumph Triumph",
        "a_dropped_recovery": "Father's Death Conquest",
        "a_ten_perfect_scores": "Katou Master Acclaim",
        "a_seasonal_clear": "Identity Depth Codex",
        "a_complete_genre_span": "Demon Hunt A Complete Genre",
        "a_monthly_completions": "Rin's Identity Afterglow",
        "a_yearly_completions": "Yukio's Review Epilogue",
        "a_rapid_complete": "Satan's Son Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Rin's Comrade",
        "a_studio_devotee": "Night Exorcism Treasury",
        "a_rewatcher": "Order Revisit",
        "a_triple_rewatch": "Gehenna Science Coda",
        "a_annual_tradition": "Satan's Son Proof",
        "a_director_fan": "Winter Exorcism Trial",
        "a_voice_actor_fan": "Father's Death Crown Crown",
        "a_ost_lover": "Exorcist Medals Seal",
        "a_source_reader": "Cross Academy Cabinet",
        "a_waiting_weekly": "Night Exorcism Clock",
        "a_childhood_revisit": "Blue Classic Seal",
        "a_saga_tracker": "All Night Standard",
        "a_genre_loyalty": "Order Revisit Loyalty",
        "a_decade_watcher": "Decade Fan",
        "a_adaptation_hunter": "Cram School Trial",
        "a_original_anime_fan": "Kuro's Play Testament",
        "a_long_commitment": "Satan's Son Mark Mark",
        "a_perfect_attendance": "Ao No Exorcist Standard",
        "a_favorite_studio_5": "Daily Training Library",
        "a_complete_catalog": "Hidden Demon Seal",
        "a_franchise_collector": "Daily Training Archive",
        "a_airing_follower": "Blue Classic Signal",
        "a_genre_master": "Winter Exorcism Master",
        "a_staff_follower": "Daily Training Oath",
        "a_multi_season_fan": "Demon Son Hoard",
        "a_format_diversity": "Shiemi's Care Cache",
        "a_year_dedication": "Order Return Tenure",
        "a_season_dedication": "Order Alerts Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Gehenna Science Explorer",
        "a_studio_hopper": "Rin's Identity Collection",
        "a_tag_explorer": "Order Return Explorer",
        "a_decade_hopper": "Exorcist Medals Chronicle Chronicle",
        "a_hidden_gem": "Hidden Demon",
        "a_popular_taste": "Rin's Speed Decree",
        "a_retro_appreciator": "Hidden Demon Aegis",
        "a_modern_viewer": "Endless Battle Pinnacle Pinnacle",
        "a_cross_demographic": "Demon Battle Pinnacle",
        "a_underdog_fan": "Demon Hunt Trial",
        "a_variety_week": "Daily Training Horizon",
        "a_foreign_cinema": "All Exorcisms Expedition",
        "a_classic_connoisseur": "2009 Fan",
        "a_every_season": "Blue Classic Archive",
        "a_award_winner": "Katou Classic Insignia",
        "a_niche_explorer": "Cross Order Horizon",
        "a_global_anime": "Morning Class Crown",
        "a_cult_classic": "Katou Classic",
        "a_random_pick": "Rin's Speed Decree Decree",
        "a_new_genre_month": "Ao No Exorcist A New",
        "a_seasonal_completionist": "Rin's Comrade Summit",
        "a_unpopular_opinion": "Rin Okumura Standard",
        "a_top_rated_viewer": "Decade Fan Seal",
        "a_source_variety": "Identity Depth Storehouse",
        "a_low_score_brave": "Gehenna Journey Measure",
        "a_upcoming_watcher": "Decade Fan Seal Seal",
        "a_short_series_explorer": "All Exorcisms Expedition Expedition",
        "a_long_series_explorer": "All Demons Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Night Exorcism",
        "a_early_bird": "Morning Class",
        "a_lunch_break": "Blue Art Trial",
        "a_golden_hour": "Blue Exorcist Tenure",
        "a_four_am_club": "Son Exorcist Gathering",
        "a_witching_hour": "Cross Archives Tenure",
        "a_new_year_watch": "Order Return Season",
        "a_midnight_premiere": "Demon Power Devotion",
        "a_all_hours": "Rin's Comrade Seal",
        "a_dawn_warrior": "Rin's Speed Aegis",
        "a_afternoon_delight": "Blue Exorcist Expert Proof Proof",
        "a_prime_time": "Katou Classic Insignia Insignia",
        "a_workday_watcher": "Demon Battle Pinnacle Pinnacle",
        "a_sunday_marathon": "Katou Master Momentum",
        "a_rainy_day": "Cross Archives Relic",
        "a_morning_routine": "Demon Son Promise",
        "a_night_shift": "Shiemi's Care Aegis",
        "a_twilight_zone": "Demon Spawn Ledger",
        "a_seasonal_premier": "Night Exorcism Cabinet",
        "a_clock_collector": "Son Exorcist Repository",
        "a_weekend_binge_hours": "Cross Order Streak",
        "a_late_night_regular": "Yukio's Review Dominion",
        "a_sunrise_watcher": "Winter Exorcism Relic Relic",
        "a_holiday_watcher": "Decade Fan Pact",
        "a_every_day_of_week": "Night Training Ledger",
        "a_monthly_hours": "Rin's Speed Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Order Judge Record",
        "a_party_host": "Shiemi's Care Record Record",
        "a_social_butterfly": "Cross Academy Company",
        "a_group_binge": "Unknown Demons Sprint",
        "a_party_regular": "Demon Spawn Chronicle",
        "a_sync_viewer": "Son Exorcist Standard",
        "a_commentator": "Hidden Demon Record",
        "a_party_marathon": "Gehenna Science Vigil",
        "a_full_house": "Order Alerts Trial",
        "a_community_pillar": "Yukio's Review Alliance",
        "a_watch_party_streak": "Hidden Demon Vigil",
        "a_diverse_party": "Demon Son Seal",
        "a_late_night_party": "Yukio's Review Testament Testament",
        "a_party_veteran": "Order Alerts Testament",
        "a_genre_party": "All Exorcisms Party",
        "a_weekly_party": "Son Exorcist Calendar",
        "a_silent_viewer": "Kuro's Play Mantle",
        "a_recommendation_giver": "Cross Order Network",
        "a_party_completionist": "All Night Coda",
        "a_social_scorer": "Winter Exorcism Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "All Demons Proof",
        "a_fibonacci": "Order Return Dominion",
        "a_palindrome_day": "Order Return Relic Relic",
        "a_binary_day": "Order Revisit Mark",
        "a_full_moon": "Blue Classic Insignia",
        "a_leap_year": "Morning Class Devotion",
        "a_time_traveler": "Night Exorcism Record",
        "a_genre_clash": "Gehenna Science Clash",
        "a_triple_seven": "Order Return Testament",
        "a_thousand_complete": "Kuro's Play Epilogue",
        "a_pi_episodes": "Demon Battle Crown",
        "a_synchronicity": "Demon Hunt Anchor",
        "a_world_record": "Father's Death Warrant",
        "a_nice": "Katou Classic Chronicle",
        "a_power_level": "Kuro's Play Testament Testament",
        "a_answer_42": "Rin's Speed Standard",
        "a_square_number": "Gehenna Science Decree",
        "a_prime_count": "Katou Classic Seal",
        "a_matching_date": "Demon Hunt Mantle",
        "a_century_episode": "Demon Battle Mark",
        "a_double_digits": "Cross Archives Testament",
        "a_one_two_three": "Morning Class Crown Crown",
        "a_lucky_seven": "Satan's Son Crown",
        "a_all_tens": "Gehenna Journey Criterion",
        "a_exact_hundred_eps": "All Night Legend",
        "a_year_match_count": "Night Exorcism Yearlong",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Cross Order Ledger",
        "a_movie_buff": "Father's Death Mark Mark",
        "a_ova_hunter": "All Night Standard Standard",
        "a_ona_explorer": "Demon Hunt Secret",
        "a_special_watcher": "Cross Archives Relic Relic",
        "a_short_king": "Katou Fan Crown",
        "a_variety_pack": "Father's Death Inquiry",
        "a_film_festival": "Decade Fan Chronicle",
        "a_music_video": "Demon Son Chronicle",
        "a_tv_short": "Gehenna Science Record",
        "a_movie_marathon": "Gehenna Science Gauntlet",
        "a_double_length": "All Demons Crown Crown",
        "a_anthology": "Shiemi's Care Aegis Aegis",
        "a_mini_series": "Rin Okumura Decree",
        "a_theatrical": "Daily Training Accord",
        "a_format_master": "Son Exorcist Vault",
        "a_long_movie": "Rin's Comrade Insignia Insignia",
        "a_back_catalog": "Hidden Demon Standard",
        "a_cm_watcher": "Blue Run Aegis",
        "a_pv_collector": "Demon Hunt Storehouse",
        "a_format_balance": "Son Exorcist Vault Vault",
        "a_episodic_master": "Blue Run Standard",
        "a_sequel_movie": "Morning Class Pinnacle",
        "a_recap_watcher": "Blue Art Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Training",
        "a_mega_streak": "Endless Battle",
        "a_weekly_warrior": "Order Alerts Season",
        "a_monthly_watcher": "Demon Power Calendar",
        "a_comeback": "Cross Academy Decree",
        "a_weekend_streak": "Gehenna Journey Passage",
        "a_no_zero_days": "Order Revisit Warrant Warrant",
        "a_iron_will": "Rin's Vow",
        "a_habit_formed": "Night Training Banner",
        "a_consistent_pace": "All Demons Measure",
        "a_year_long": "Year in Order",
        "a_double_streak": "Winter Exorcism Watch",
        "a_streak_recovery": "Kuro's Play Season",
        "a_daily_minimum": "Demon Power Focus",
        "a_winter_streak": "All Exorcisms Watch",
        "a_summer_streak": "Cross Archives Resolve",
        "a_morning_streak": "Hidden Demon Clock",
        "a_night_streak": "Night Training Constancy",
        "a_unbreakable": "Katou Fan Proof",
        "a_eternal_flame": "Rin's Identity Standard",
        "a_completion_streak": "All Night Return",
        "a_rating_streak": "Order Return Balance",
        "a_multi_ep_streak": "Father's Death Ritual",
        "a_genre_streak": "Order Return Streak",
        "a_studio_streak": "Cross Academy Cabinet Cabinet",
        "a_perfect_week": "Demon Hunt Relic",

        // ── ANIME SCORING ──
        "a_critic": "Order Judge",
        "a_perfect_ten": "Blue Exorcist",
        "a_harsh_critic": "Yukio's Review",
        "a_fair_judge": "Yukio's Review Balance",
        "a_generous_spirit": "Demon Power Pinnacle",
        "a_score_all": "Blue Exorcist Expert Criterion",
        "a_wide_range": "Katou Classic Ledger",
        "a_controversial": "Hidden Demon Decree",
        "a_consistent_scorer": "Night Exorcism Verdict",
        "a_score_sniper": "Morning Class Score",
        "a_evolving_taste": "Winter Exorcism Testament",
        "a_bell_curve": "Ao No Exorcist Insignia",
        "a_picky_watcher": "Kuro's Play Warrant",
        "a_100_rated": "Son Exorcist Warrant",
        "a_500_rated": "Katou Fan Pinnacle",
        "a_mediocre_majority": "Demon Hunt Canon",
        "a_rating_spree": "Hidden Demon Review",
        "a_score_variance": "Gehenna Journey Score",
        "a_masterpiece_hunter": "Hidden Demon Banner",
        "a_contrarian": "Gehenna Science Record Record",
        "a_optimist": "Demon Son Ledger",
        "a_score_distributor": "Blue Art Appraisal",
        "a_genre_critic": "All Demons Critic",
        "a_mean_above_8": "Satan's Son Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Battle",
        "a_valentines_weeb": "Daily Training Vow",
        "a_pi_day": "Yukio's Review Trial",
        "a_april_fools": "Morning Class Devotion Devotion",
        "a_international_anime_day": "Rin's Comrade Record",
        "a_star_wars_day": "Katou Master Chronicle",
        "a_summer_solstice": "Order Revisit Calendar",
        "a_tanabata": "Endless Battle Focus",
        "a_friday_13th": "Blue Art Relic",
        "a_halloween_spirit": "Cross Order Vow",
        "a_thanksgiving_binge": "Demon Spawn Run",
        "a_christmas_special": "Winter Exorcism",
        "a_new_years_eve": "Satan's Son Pilgrimage",
        "a_birthday_watch": "Ao No Exorcist Vow",
        "a_holiday_marathon": "Unknown Demons Overture",
        "a_independence_day": "Rin's Identity Banner",
        "a_culture_day": "Exorcist Medals Insignia",
        "a_spring_equinox": "Unknown Demons Decree",
        "a_earth_day": "Father's Death Mantle",
        "a_labor_day": "Cross Order Seal",
        "a_winter_solstice": "Demon Battle Pilgrimage",
        "a_anime_birthday": "Father's Death Pilgrimage",
        "a_every_holiday": "Cram School Resolve",
        "a_consecutive_holidays": "Cross Archives Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Cross Academy Rank",
        "a_meta_collector": "Exorcist Medals Hoard",
        "a_meta_category_starter": "Demon Power Badge",
        "a_meta_tier_climber": "Exorcist Medals Glyph",
        "a_meta_tier_max": "True Exorcist",
        "a_meta_xp_earner": "Blue Art Emblem",
        "a_meta_difficulty_easy": "Yukio's Review Mechanism",
        "a_meta_difficulty_hard": "Decade Fan Writ",
        "a_meta_unlock_spree": "Order Alerts Panel",
        "a_meta_completionist": "All Demons",
        "a_meta_diverse": "Order Return Emblem",
        "a_meta_dominator": "Demon Spawn Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Class",
        "m_chapter_counter": "Son Exorcist Pinnacle",
        "m_chapter_titan": "Identity Depth Relic",
        "m_reading_hours": "Blue Art Relic Relic",
        "m_reading_time_lord": "Rin's Comrade Record Record",
        "m_manga_collector": "Order Alerts Ledger",
        "m_library_legend": "Exorcist Medals Reliquary",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "Daily Training Seal",
        "m_first_rating": "Blue Art Eye",
        "m_ten_thousand_pages": "Daily Training Gauge",
        "m_volume_collector": "Kuro's Play Storehouse",
        "m_year_explorer": "Rin's Speed Quest",
        "m_century_reader": "All Exorcisms Dominion",
        "m_five_hundred_ch": "Katou Classic Legend",
        "m_thousand_ch": "Winter Exorcism Legend",
        "m_reading_ten": "All Exorcisms Appraisal",
        "m_ptr_hoarder": "Winter Exorcism Index",
        "m_dropped_honesty": "Exorcist Medals Summit",
        "m_season_reader": "Hidden Demon Treasury",
        "m_active_reader": "Cross Archives Trial",
        "m_five_thousand_ch": "Gehenna Science Standard",
        "m_ten_completed": "Gehenna Science Resolution",
        "m_fifty_completed": "Winter Exorcism Harvest",
        "m_five_hundred_completed": "Night Training Legacy",
        "m_mean_score_tracker": "Night Exorcism Audit",
        "m_unique_authors": "Father's Death Reserve",
        "m_all_status": "Cross Archives Testament Testament",
        "m_first_favorite": "All Night Cache",
        "m_favorites_collector": "Cross Academy Shelf",
        "m_days_spent_reading": "Demon Battle Relic",

        // ── MANGA BINGE ──
        "m_binge_reader": "Ao No Exorcist Streak",
        "m_marathon_reader": "Yukio's Review Rush",
        "m_weekend_reader": "Blue Classic Run",
        "m_non_stop_reading": "All Night Gauntlet",
        "m_one_more_chapter": "Blue Art Testament Testament",
        "m_speed_read": "Order Revisit Drive",
        "m_double_story": "Unknown Demons Banner",
        "m_triple_read": "Rin's Identity Record",
        "m_five_a_day": "Demon Son Insignia",
        "m_chapter_chain": "Exorcist Medals Accord",
        "m_volume_binge": "Gehenna Journey Drive",
        "m_power_reader": "Katou Master Seal Seal",
        "m_half_day_read": "Cross Academy Aegis",
        "m_full_day_read": "Blue Run Aegis Aegis",
        "m_power_weekend": "Daily Training Streak",
        "m_binge_king": "Exorcist Marathon",
        "m_no_sleep_read": "All Exorcisms Rush",
        "m_full_series_rush": "Yukio's Review Cascade",
        "m_seven_day_challenge": "Endless Battle Warrant",
        "m_hundred_day_read": "Order Return Legend",
        "m_volume_rush": "Order Judge Gauntlet",
        "m_series_sweep": "Cram School Trial Trial",
        "m_genre_binge": "Blue Run Binge",
        "m_author_binge": "Blue Classic Surge",
        "m_chapter_counter_day": "Demon Spawn Ledger Ledger",
        "m_multi_series_binge": "Katou Classic Charge",
        "m_midnight_binge": "Winter Exorcism Tempest",
        "m_new_year_binge": "Father's Death Passage",
        "m_forty_eight_hour": "Night Exorcism Rally",
        "m_oneshot_binge": "Order Revisit Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Battle Chapter",
        "m_genre_adventure": "Gehenna Chapter",
        "m_genre_comedy": "Cross Academy Comedy",
        "m_genre_drama": "Father Chapter",
        "m_genre_fantasy": "Two World Chapter",
        "m_genre_horror": "Demon Chapter",
        "m_genre_mystery": "Gehenna Science Mystery",
        "m_genre_romance": "Heart Chapter",
        "m_genre_scifi": "Science Chapter",
        "m_genre_sol": "Son Exorcist Slice",
        "m_genre_sports": "Order Judge Sports",
        "m_genre_supernatural": "Flame Chapter",
        "m_genre_thriller": "Demon Hunt Thriller",
        "m_genre_psychological": "Identity Depth",
        "m_genre_isekai": "Order Alerts Isekai",
        "m_genre_shounen": "Blue Exorcist Shounen",
        "m_genre_ecchi": "All Demons Ecchi",
        "m_genre_mahou_shoujo": "Cross Academy Magic Shoujo",
        "m_genre_mecha": "Kuro's Play Mecha",
        "m_genre_music": "Cross Order Music",
        "m_tag_isekai_new": "Blue Art Isekai New",
        "m_tag_harem": "Blue Exorcist Expert Harem",
        "m_tag_bl": "Rin Okumura Bl",
        "m_tag_gl": "Winter Exorcism Gl",
        "m_tag_historical": "Katou Classic Historical",
        "m_tag_military": "Blue Exorcist Military",
        "m_tag_school": "Daily Training School",
        "m_tag_martial_arts": "Son Exorcist Martial Arts",
        "m_tag_vampire": "Order Judge Vampire",
        "m_tag_samurai": "Shiemi's Care Samurai",
        "m_tag_space": "Rin Okumura Space",
        "m_tag_parody": "Kuro's Play Parody",
        "m_tag_idol": "Rin Okumura Idol",
        "m_tag_post_apocalyptic": "Exorcist Medals Post Apocalyptic",
        "m_tag_cyberpunk": "Blue Exorcist Expert Cyberpunk",
        "m_tag_shoujo": "Decade Fan Shoujo",
        "m_tag_survival": "Cross Academy Survival",
        "m_tag_cooking": "Ao No Exorcist Cooking",
        "m_tag_medical": "Cross Archives Medical",
        "m_tag_villainess": "Blue Classic Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Blue Exorcist Expert",
        "m_completion_rate_50": "Rin Okumura Return",
        "m_completion_rate_75": "Demon Hunt Ascension",
        "m_completion_rate_90": "Rin's Identity Resolution",
        "m_no_drop": "All Night Decree",
        "m_long_runner_complete": "Demon Spawn Clear",
        "m_sequel_chain": "Cross Order Seal Seal",
        "m_clean_list": "Identity Depth Relic Relic",
        "m_from_ptr": "Decade Fan Watchlist",
        "m_reread_master": "Yukio's Review Trial Trial",
        "m_oneshot_complete": "Yukio's Review Ascension",
        "m_same_day_start_finish": "Satan's Son Crown Crown",
        "m_revival": "Demon Spawn Accord",
        "m_zero_to_hundred": "Gehenna Science Banner",
        "m_five_genre_complete": "Order Revisit M Five Genre",
        "m_full_collection": "Satan's Son Proof Proof",
        "m_batch_complete": "Night Exorcism Summit",
        "m_paused_to_done": "Rin's Identity Standard Standard",
        "m_completion_spree": "Katou Fan Triumph",
        "m_format_completionist": "Yukio's Review Completion",
        "m_catch_up": "Rin's Comrade Chronicle",
        "m_multi_reread": "All Night Banner",
        "m_dropped_recovery": "All Demons Conquest",
        "m_ten_perfect_scores": "Blue Classic Judgment",
        "m_complete_genre_span": "Order Alerts M Complete Genre",
        "m_monthly_completions": "Blue Run Return",
        "m_yearly_completions": "Order Alerts Epilogue",
        "m_rapid_complete": "Endless Battle Finale",
        "m_author_complete": "Daily Training Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Devoted Reader",
        "m_mangaka_lover": "Katou Fan",
        "m_rereader": "Order Return",
        "m_triple_reread": "Order Return Testament Testament",
        "m_annual_reread": "Gehenna Science Banner Banner",
        "m_publisher_fan": "Katou Fan Mark",
        "m_artist_fan": "Cross Order Insignia",
        "m_adaptation_compare": "Ao No Exorcist Insignia Insignia",
        "m_source_material_fan": "Manga First",
        "m_waiting_weekly": "Shiemi's Care Streak",
        "m_classic_reader": "Kuro's Play Lantern",
        "m_saga_reader": "Exorcist Medals Decree",
        "m_genre_loyalty": "All Demons Loyalty",
        "m_decade_reader": "Gehenna Journey Warrant",
        "m_ln_adaptation": "Gehenna Journey Mark",
        "m_original_work": "Order Judge Standard",
        "m_long_commitment": "All Demons Mark",
        "m_up_to_date": "Father's Death Warrant Warrant",
        "m_favorite_mangaka": "Rin's Speed Treasury",
        "m_complete_portfolio": "Katou Fan Triumph Triumph",
        "m_franchise_collector": "Rin's Comrade Archive",
        "m_serialization_follower": "Rin's Speed Handshake",
        "m_genre_master": "Identity Depth Master",
        "m_multi_series_author": "Exorcist Medals Insignia Insignia",
        "m_format_diversity": "Order Judge Shelf",
        "m_year_dedication": "All Exorcisms Tenure",
        "m_ongoing_follower": "Gehenna Journey Fellowship",
        "m_genre_loyalty_50": "Winter Exorcism Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Unknown Demons Explorer",
        "m_publisher_hopper": "Katou Fan Mantle",
        "m_tag_explorer": "Cram School Explorer",
        "m_decade_hopper": "Decade Fan Chronicle Chronicle",
        "m_hidden_gem": "Hidden Volume",
        "m_popular_taste": "Night Exorcism Record Record",
        "m_retro_reader": "Night Exorcism Accord",
        "m_modern_reader": "Katou Classic Seal Seal",
        "m_cross_demographic": "Demon Power Crown",
        "m_underdog_fan": "Night Exorcism Accord Accord",
        "m_variety_week": "Cross Order Horizon Horizon",
        "m_manhwa_reader": "Morning Class Proof",
        "m_manhua_reader": "Kuro's Play Mantle Mantle",
        "m_classic_connoisseur": "Night Training Glimpse",
        "m_award_winner": "All Exorcisms Warrant",
        "m_niche_explorer": "Ao No Exorcist Horizon",
        "m_world_manga": "Rin's Comrade Chronicle Chronicle",
        "m_cult_classic": "Blue Flame Classic",
        "m_random_pick": "Night Exorcism Standard",
        "m_new_genre_month": "Rin's Comrade M New Genre",
        "m_year_completionist": "Son Exorcist Fulfillment",
        "m_unpopular_opinion": "Father's Death Trial",
        "m_top_rated_reader": "Ao No Exorcist Record",
        "m_source_variety": "Kuro's Play Catalogue",
        "m_low_score_brave": "Son Exorcist Score",
        "m_short_manga_explorer": "Katou Classic Compass",
        "m_long_manga_explorer": "Gehenna Science Survey",
        "m_serialization_explorer": "Demon Hunt Road",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Rin Okumura Ledger",
        "m_commute_reader": "Cross Archives Tenure Tenure",
        "m_four_am_club": "Katou Fan Fellowship",
        "m_new_year_read": "Cross Order Pact",
        "m_all_hours": "Decade Fan Accord Accord",
        "m_prime_time_reader": "Order Judge Banner",
        "m_workday_reader": "Demon Spawn Accord Accord",
        "m_sunday_read": "Rin Okumura Standard Standard",
        "m_morning_routine": "Demon Spawn Discipline",
        "m_night_shift_reader": "Daily Training Accord Accord",
        "m_seasonal_premier_read": "Kuro's Play Seasonal",
        "m_clock_collector": "Demon Battle Reserve",
        "m_late_night_horror": "Order Revisit Mark Mark",
        "m_afternoon_reader": "All Exorcisms Mantle Mantle",
        "m_golden_hour_reader": "Order Return Observance",
        "m_dawn_reader": "Cram School Mantle",
        "m_twilight_reader": "Gehenna Journey Crown",
        "m_midnight_start": "Order Judge Routine",
        "m_weekend_binge_hours": "Blue Classic Momentum",
        "m_late_night_regular": "Rin Okumura Accord",
        "m_sunrise_reader": "Blue Exorcist Expert Mantle",
        "m_every_day_of_week": "Kuro's Play Warrant Warrant",
        "m_monthly_hours": "Unknown Demons Vigil",
        "m_bedtime_reader": "Son Exorcist Warrant Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Blue Art",
        "m_webtoon_reader": "Gehenna Journey Mark Mark",
        "m_full_color": "Cross Order Accord",
        "m_doujin_reader": "Rin's Identity Record Record",
        "m_anthology_reader": "Blue Classic Accord",
        "m_adaptation_reader": "Night Exorcism Banner",
        "m_longstrip_reader": "Order Return Trial",
        "m_4koma_reader": "Shiemi's Care Ledger",
        "m_oneshot_reader": "Order Alerts Mantle",
        "m_format_variety": "Katou Fan Gallery",
        "m_light_novel_reader": "Decade Fan Insignia",
        "m_novel_reader": "Son Exorcist Crown",
        "m_visual_storyteller": "All Exorcisms Testament",
        "m_colored_classic": "Hidden Demon Survey",
        "m_webcomic_fan": "Night Training Insignia",
        "m_manga_to_anime": "Manga Adapted",
        "m_seinen_reader": "All Demons Pinnacle",
        "m_josei_reader": "Blue Exorcist Expert Pinnacle",
        "m_award_winning_art": "Blue Exorcist Relic",
        "m_debut_work": "Blue Exorcist Dominion",
        "m_vertical_scroll": "Exorcist Medals Decree Decree",
        "m_traditional_format": "Ao No Exorcist Hoard",
        "m_cross_media": "Katou Classic Accord",
        "m_spinoff_reader": "Rin's Comrade Accord",
        "m_remake_reader": "Yukio's Review Pinnacle",
        "m_collaboration_reader": "Night Training Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Flame Streak",
        "m_weekly_warrior": "Demon Hunt Season",
        "m_monthly_reader": "Demon Son Discipline",
        "m_comeback": "Gehenna Science Standard Standard",
        "m_weekend_streak": "Blue Exorcist Expert Fever",
        "m_no_zero_days": "Morning Class Proof Proof",
        "m_iron_will": "Exorcist Resolve",
        "m_habit_formed": "Demon Power Crown Crown",
        "m_consistent_pace": "Satan's Son Scrutiny Scrutiny",
        "m_year_long": "Year Reading",
        "m_double_streak": "Order Alerts Resolve",
        "m_streak_recovery": "Identity Depth Resolve",
        "m_daily_minimum": "Demon Battle Focus",
        "m_winter_streak": "Order Return Observance Observance",
        "m_summer_streak": "Blue Exorcist Observance",
        "m_morning_streak": "Unknown Demons Clock",
        "m_night_streak": "Ao No Exorcist Discipline",
        "m_unbreakable": "Blue Exorcist Expert Warrant",
        "m_eternal_flame": "Cross Academy Record",
        "m_chapter_a_day": "Rin Okumura Ledger Ledger",
        "m_genre_streak": "Cram School Streak",
        "m_completion_streak": "Night Exorcism Return",
        "m_rating_streak": "Cram School Appraisal",
        "m_multi_ch_streak": "Demon Hunt Tenure",
        "m_author_streak": "Demon Battle Calendar",
        "m_perfect_week_manga": "Rin's Comrade Accord Accord",
        "m_diverse_streak": "All Night Streak",

        // ── MANGA SCORING ──
        "m_critic": "Exorcist Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_harsh_critic": "Decade Fan Scale",
        "m_fair_judge": "Blue Art Eye Eye",
        "m_generous_spirit": "Blue Classic Decree",
        "m_score_all": "Gehenna Journey Reckoning",
        "m_wide_range": "Demon Son Ledger Ledger",
        "m_controversial": "Blue Run Standard Standard",
        "m_consistent_scorer": "Rin's Identity Grade",
        "m_score_sniper": "Father's Death Reckoning",
        "m_evolving_taste": "Order Alerts Trial Trial",
        "m_bell_curve": "Demon Son Accord",
        "m_picky_reader": "All Night Ledger",
        "m_100_rated": "Demon Son Standard",
        "m_500_rated": "Daily Training Aegis",
        "m_mediocre_majority": "Order Alerts Canon",
        "m_rating_spree": "Unknown Demons Verdict",
        "m_score_variance": "Son Exorcist Measure",
        "m_binge_rater": "Demon Battle Passage",
        "m_reread_rerate": "Hidden Demon Banner Banner",
        "m_masterpiece_hunter": "Blue Run Banner",
        "m_contrarian": "Night Exorcism Aegis",
        "m_optimist": "Katou Classic Accord Accord",
        "m_score_distributor": "Demon Hunt Balance",
        "m_genre_critic": "Demon Battle Critic",
        "m_mean_above_8": "Son Exorcist Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "All Exorcisms Season",
        "m_valentines_read": "Cram School Observance",
        "m_pi_day": "Order Alerts Testament Testament",
        "m_april_fools": "Father's Death Devotion",
        "m_international_manga_day": "Decade Fan Aegis",
        "m_free_comic_day": "Blue Classic Chronicle",
        "m_summer_solstice": "Endless Battle Focus Focus",
        "m_tanabata": "Satan's Son Tanabata",
        "m_friday_13th": "Yukio's Review Dominion Dominion",
        "m_halloween_read": "Order Revisit Halloween",
        "m_thanksgiving_binge": "Rin's Comrade Charge",
        "m_christmas_read": "Demon Spawn Pact",
        "m_new_years_eve": "Endless Battle Pilgrimage",
        "m_birthday_read": "All Demons Focus",
        "m_holiday_marathon": "Rin's Speed Rally",
        "m_independence_day": "Night Exorcism Aegis Aegis",
        "m_culture_day": "Daily Training Seal Seal",
        "m_spring_equinox": "Order Revisit Dominion",
        "m_earth_day": "All Demons Trial",
        "m_labor_day": "Demon Spawn Seal",
        "m_winter_solstice": "Demon Power Focus Focus",
        "m_manga_birthday": "Satan's Son Ritual",
        "m_every_holiday_reader": "Identity Depth Watch",
        "m_consecutive_holidays": "Yukio's Review Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Katou Master Aegis",
        "m_fibonacci": "Cross Archives Dominion",
        "m_palindrome_day": "Order Alerts Relic",
        "m_binary_day": "Demon Power Proof",
        "m_full_moon_read": "Blue Exorcist Expert Crown",
        "m_leap_year_read": "All Night Practice",
        "m_triple_seven": "Blue Art Trial Trial",
        "m_thousand_complete": "Blue Art Ascension",
        "m_nice": "Exorcist Medals Seal Seal",
        "m_power_level_chapters": "Gehenna Science Aegis",
        "m_answer_42": "Blue Exorcist Expert Trial",
        "m_square_number": "Cross Academy Standard",
        "m_prime_count": "Blue Art Pinnacle",
        "m_matching_date": "Identity Depth Mantle",
        "m_century_chapter": "Katou Master Decree",
        "m_pi_chapters": "All Demons Proof Proof",
        "m_synchronicity": "Cram School Emblem",
        "m_world_record": "Morning Class Warrant",
        "m_genre_clash": "Order Judge Clash",
        "m_time_traveler": "Rin's Identity Decree",
        "m_double_digits": "Kuro's Play Dominion",
        "m_one_two_three": "Night Training Banner Banner",
        "m_lucky_seven": "Ao No Exorcist Record Record",
        "m_exact_hundred_ch": "Cross Archives Legend",
        "m_year_match_count": "Shiemi's Care Routine",
        "m_chapter_match_date": "Demon Power Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Kuro's Play Index",
        "m_manhwa_format": "Order Revisit Gallery",
        "m_manhua_format": "Order Return Storehouse",
        "m_ln_format": "Blue Art Index",
        "m_oneshot_format": "Order Alerts Index",
        "m_doujin_format": "Unknown Demons Cabinet",
        "m_novel_format": "Father's Death Reserve Reserve",
        "m_format_master_manga": "Unknown Demons Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Rin's Identity Link",
        "m_meta_collector": "Daily Training Reliquary",
        "m_meta_category_starter": "Katou Fan Standard",
        "m_meta_tier_climber": "Katou Classic Token",
        "m_meta_tier_max": "Blue Exorcist Complete",
        "m_meta_xp_earner": "Kuro's Play Anchor",
        "m_meta_difficulty_easy": "Blue Art Panel",
        "m_meta_difficulty_hard": "All Exorcisms Node",
        "m_meta_unlock_spree": "Kuro's Play Marker",
        "m_meta_completionist": "Full Library",
        "m_meta_diverse": "Order Alerts Anchor",
        "m_meta_dominator": "Exorcist Medals Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#000105",
        primary: "#2341a8",
        secondary: "#122a8a",
        accent: "#e05020",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/ao-no-exorcist.jpg",
    particleColor: "#3050d0",
    backgroundDim: 0.4,
    backgroundBlur: 20,
    particleTypes: {
        blue_flames: { label: "Blue Flames", maxCount: 15, defaultEnabled: true, defaultIntensity: 70 },
        demon_sparks: { label: "Demon Sparks", maxCount: 12, defaultEnabled: true, defaultIntensity: 55 },
    },
    milestoneNames: {
  1: "Threadbare Ordinary Student Spark",
  8: "Troubled's Tarnished Omen",
  14: "Fractured Unaware Twin",
  21: "Temple Helper Path",
  28: "Lowborn Legacy Myth",
  35: "Family Outsider Haven",
  41: "Hidden's Legacy Secret",
  48: "Humble Ignorant Mark",
  55: "Ragged Doubtful Believer Vow",
  61: "Broken's Faint Echo",
  68: "Lesser Outburst",
  75: "Lost Direction Zenith",
  81: "Doubtful Legacy Bloom",
  88: "Unstable Soul",
  95: "Pre's State Flame",
  102: "Really Cool Cross Spark",
  108: "Awakened Exorcist Trainee Omen",
  115: "Sword's Resolute Blade",
  122: "Rising Basic Spell",
  128: "Demon Initiate Crest",
  135: "Dauntless Member Pulse",
  142: "Low Rank Crest",
  149: "Control's Legacy Mark",
  155: "Fresh Ritual Vow",
  162: "Valiant Combat Apprentice Echo",
  169: "Sealed's Prime Force",
  175: "Polished Academy Student",
  182: "Minor Exorcist Bloom",
  189: "Stormlit Legacy Sigil",
  195: "Early Awakening Flame",
  202: "ExWire's Legacy Spark",
  209: "Tempered Sword Blade",
  216: "Trusted Demon Sight Crest",
  222: "Ritual's Steadfast Path",
  229: "Ironclad Training Exorcist",
  236: "Okumura Awareness Clash",
  242: "Core Power Force",
  249: "Field Exorcist Mark",
  256: "Low's Fighter Clash",
  262: "Formidable Demon Crest",
  269: "Lucid Seal User Crown",
  276: "Combat's Ranked Zenith",
  283: "Fabled Academy Operative",
  289: "Rising Exorcist Sigil",
  296: "Seasoned Power Force",
  303: "Cross Exorcist Spark",
  309: "Advanced's User Blade",
  316: "Valorous Demon Crest",
  323: "Stalwart Field Specialist Path",
  330: "Elite's Commanding Myth",
  336: "Refined Okumura Blood",
  343: "Flame User Crest",
  350: "Blazing Legacy Mark",
  356: "Ritual Expert Vow",
  363: "Mid's Exorcist Echo",
  370: "Peerless Demon Crest",
  376: "Ardent Advanced Field Zenith",
  383: "Sealed's Focused Bloom",
  390: "Vigilant Battle Exorcist",
  397: "Order Flame",
  403: "Elite Legacy Spark",
  410: "High Rank Omen",
  417: "Demon's Fighter Crest",
  423: "Sovereign Elite Path",
  430: "Regal Flame User Myth",
  437: "Combat's Crowned Pulse",
  444: "Mythborn Cross Agent",
  450: "Advanced Ritual Mark",
  457: "Radiant Legacy Vow",
  464: "Elite Sword Blade",
  470: "Demon's Eliminator Crest",
  477: "Climactic Specialist Zenith",
  484: "Epic Rising Knight Bloom",
  490: "Okumura's Unreal Force",
  497: "Peak Top Tier",
  504: "Knight Class Spark",
  511: "Exalted Slayer Crest",
  517: "Cross Elite Seal",
  524: "Flame's User Crest",
  531: "Celestial Field Myth",
  537: "Phantom High Level Pulse",
  544: "Veteran's Crimson Crest",
  551: "Silver Demon War",
  557: "Advanced Knight Vow",
  564: "Feral Core Echo",
  571: "Okumura Master Force",
  578: "Combat's Legacy Force",
  584: "Dread Demon Crest",
  591: "Luminous Elite Field Sigil",
  598: "Near's Thunderous Flame",
  604: "Ultraviolet Paladin Candidate",
  611: "Order Omen",
  618: "Secret Commander Crest",
  625: "Flame Sovereign Path",
  631: "Cross's Legacy Myth",
  638: "Worldclass Elite Pulse",
  645: "Lawless Rin Awakening Crest",
  651: "Battlefield's Chosen Clash",
  658: "Fearless Top Exorcist",
  665: "Demon Realm Crest",
  671: "Cinematic Order Crown",
  678: "Flame King Crown",
  685: "Elite's Slayer Crest",
  692: "Canonized Near Sigil",
  698: "Ascendant Mythic Exorcist Flame",
  705: "Demon's Transfigured Crest",
  712: "Immortal Flame",
  718: "Order Seal",
  725: "Astral Legacy Path",
  732: "Okumura Force",
  739: "Demon's Threat Crest",
  745: "Prismatic Knight Crest",
  752: "Abyssal Battlefield Apex Clash",
  759: "Exorcist's Unbound Vow",
  765: "Eternal Rin Awakening",
  772: "Order Crown",
  779: "Transcendent Legacy Zenith",
  785: "Demon's Breaker Crest",
  792: "Humanity's Apex Sigil",
  799: "Ultimate Near Flame",
  806: "Mythic Paladin Ascendant Spark",
  812: "Flame's Godlike Omen",
  819: "Canonical Demon King",
  826: "Order Path",
  832: "Heavenly Legacy Myth",
  839: "Exorcist Form",
  846: "Flame's Legacy Crest",
  852: "Timeless Demon Crest",
  859: "Empyrean Knight Apocalypse Vow",
  866: "Rin's Primordial Form",
  873: "Omniscient Myth",
  879: "Flame Sovereign Zenith",
  886: "Apocalyptic Absolute Bloom",
  893: "Legend Sigil",
  899: "Near's Exorcist Flame",
  906: "Final Apex Spark",
  913: "Crowned Demon Realm Crest",
  920: "Authority's Mythic Force",
  926: "Absolute Knight",
  933: "Demon King Crest",
  940: "Cosmic Legacy Pulse",
  946: "Breaker Entity Crest",
  953: "Infinite's Power Force",
  960: "Definitive Awakening Form",
  966: "Ultimate God Exorcism Echo",
  973: "End's Infinite Crest",
  980: "Sovereign Abyss Flame",
  987: "Final Bloom",
  993: "Legendary Unclean Sigil",
  1000: "Ultimate Blue Exorcist"
}
}
