import { AnimeThemeConfig } from "./types"
import { GiFlowerEmblem, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiCrystalBall, GiStarSwirl, GiSpellBook } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const ariaTheme: AnimeThemeConfig = {
    id: "aria",
    displayName: "Aria the Animation",
    description: "In a utopian future terraformed Mars called Aqua, Akari trains as an undine — a gondolier guide — in the Venice-like city of Neo-Venezia. The series is a quiet meditation on wonder, gratitude, and the beauty of everyday life.",
    cssVars: {
        "--color-brand-200": "175 220 252",
        "--color-brand-300": "112 185 248",
        "--color-brand-400": "58 145 238",
        "--color-brand-500": "18 108 215",
        "--color-brand-600": "5 72 172",
        "--color-brand-700": "1 44 128",
        "--color-brand-800": "0 20 80",
        "--color-brand-900": "0 8 40",
        "--color-brand-950": "0 2 18",
        "--brand": "18 108 215",
        "--background": "#000209",
        "--paper": "#000518",
        "--color-gray-950": "0 2 9",
        "--color-gray-900": "1 6 20",
        "--color-gray-800": "3 14 38",
        "--color-gray-700": "6 26 62",
        "--color-gray-600": "11 46 96",
        "--color-gray-500": "20 80 138",
        "--color-gray-400": "42 120 175",
        "--color-gray-300": "78 162 215",
        "--color-gray-200": "122 198 240",
        "--color-gray-100": "175 225 255",
        "--color-gray-50": "222 244 255",
    },
    sidebarOverrides: {
        "home": { icon: GiFlowerEmblem, label: "Neo-Venezia" },
        "schedule": { icon: GiAlarmClock, label: "Gondola Schedule" },
        "manga": { icon: LuBookOpen, label: "Wandering Log" },
        "lists": { icon: GiScrollUnfurled, label: "Undine Registry" },
        "discover": { icon: GiBullseye, label: "New Routes" },
        "torrent-list": { icon: GiCrystalBall, label: "Canal Cache" },
        "debrid": { icon: GiHeartKey, label: "Aria Cache" },
        "unmatched": { icon: GiStarSwirl, label: "Unexplored Canals" },
        "enmasse": { icon: GiResize, label: "Gondola Festival" },
        "scan-summaries": { icon: TbReportSearch, label: "Tour Reports" },
        "auto-downloader": { icon: LuRss, label: "Water Feed" },
        "community": { icon: GiSpellBook, label: "Undine Circle" },
        "achievements": { icon: GiTrophyCup, label: "Prima Trophies" },
        "milestones": { icon: LuFlag, label: "Undine Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Canal Alerts" },
        "theme-manager": { icon: GiPalette, label: "Water Colors" },
        "extensions": { icon: BiExtension, label: "Gondola Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Canal Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Akari Config" },
    },
    achievementNames: {
        "a_first_episode": "First Row",
        "a_first_complete": "First Tour Complete",
        "a_hundred_club": "Hundred Gondola Days",
        "a_binge_king": "Aria Marathon",
        "a_completionist": "Single Trainee",
        "a_mega_completionist": "Prima Undine",
        "a_loyal_fan": "Canal Regular",
        "a_zero_to_hero": "Trainee to Prima",
        "m_first_chapter": "First Stroke",
        "m_completionist": "Full Archive",
    },
    musicUrl: "",
    previewColors: {
        bg: "#000209",
        primary: "#126cd7",
        secondary: "#c8a040",
        accent: "#a8d8f8",
    },
    particleColor: "#4098e8",
    backgroundDim: 0.22,
    backgroundBlur: 18,
    milestoneNames: {
        1: "Earth Visitor",
        7: "Lost Tourist",
        14: "New Arrival",
        21: "City Observer",
        27: "Quiet Wanderer",
        34: "Canal Side Dreamer",
        41: "First Boat Ride",
        47: "Gentle Listener",
        54: "Water Admirer",
        61: "Neo-Venezia Explorer",
        68: "Floating City Visitor",
        74: "Emotionally Open Traveler",
        81: "Calm Observer",
        88: "Early Harmony Seeker",
        94: "Pre-Apprentice State",

        101: "Undine Apprentice",
        108: "Gondola Trainee",
        114: "Canal Learner",
        121: "Rowing Beginner",
        128: "Tour Guide Student",
        135: "Waterway Observer",
        141: "Basic Navigation User",
        148: "Customer Greeter",
        155: "Training Undine",
        161: "Emotion Listener",
        168: "Small Tour Helper",
        175: "Gentle Speaker",
        182: "Boat Control Learner",
        188: "Service Apprentice",
        195: "Early Undine Path",

        202: "Licensed Undine Candidate",
        208: "Gondola Operator",
        215: "Tour Guide Assistant",
        222: "Canal Specialist",
        228: "Client Communicator",
        235: "Neo-Venezia Resident",
        242: "Rowing Practitioner",
        249: "Emotional Guide Learner",
        255: "Service Adept",
        262: "Water Harmony Student",
        269: "Basic Undine",
        275: "City Path Learner",
        282: "Visitor Guide",
        289: "Calm Presence",
        296: "Developing Undine",

        302: "Full Undine",
        309: "Professional Gondolier",
        316: "Neo-Venezia Guide",
        322: "Canal Expert",
        329: "Client Experience Handler",
        336: "Seasoned Operator",
        342: "Emotionally Skilled Guide",
        349: "City Navigation Expert",
        356: "Senior Apprentice Undine",
        363: "Watercraft Mastery",
        369: "Service Specialist",
        376: "Tour Flow Coordinator",
        383: "Harmony Practitioner",
        389: "Advanced Guide",
        396: "Calm Communication Expert",

        403: "Senior Undine",
        409: "Elite Gondolier",
        416: "Neo-Venezia Ambassador",
        423: "Emotional Guide Expert",
        430: "Canal System Master",
        436: "Client Harmony Specialist",
        443: "Seasoned Tour Leader",
        450: "Water Path Virtuoso",
        456: "City Emotion Reader",
        463: "Undine Instructor",
        470: "Perfect Rowing Control",
        477: "Advanced Harmony Guide",
        483: "Experience Curator",
        490: "Calmness Embodied",
        497: "Near Prima Undine",

        503: "Prima Undine Candidate",
        510: "Neo-Venezia Elite Guide",
        517: "Emotion Flow Master",
        523: "Waterway Virtuoso",
        530: "Client Experience Legend",
        537: "Perfect Tour Coordinator",
        544: "Harmony System Expert",
        550: "City Spirit Listener",
        557: "Undine Leadership Core",
        564: "Calm Mastery State",
        570: "Advanced Prima Path",
        577: "Emotional Navigator",
        584: "Canal Harmony Keeper",
        591: "Seasoned Prima Candidate",
        597: "Near Legend Undine",

        604: "Prima Undine",
        611: "Neo-Venezia Icon",
        617: "Emotion Harmony Master",
        624: "City Water Guide",
        631: "Perfect Undine Form",
        637: "Client Emotion Artist",
        644: "Canal Spirit Reader",
        651: "Water Flow Sage",
        658: "Undine Legend",
        664: "Tour Experience Perfection",
        671: "Harmony Incarnate",
        678: "Neo-Venezia Voice",
        684: "Calmness Embodied",
        691: "Ultimate Guide",
        698: "Near Myth Undine",

        704: "Water Awakening",
        711: "City Spirit Bond",
        718: "Emotional Flow Mastery",
        725: "Neo-Venezia Resonance",
        731: "Perfect Calm State",
        738: "Canal Unity",
        745: "Harmony Expansion",
        751: "Undine Transcendence",
        758: "Water Memory Keeper",
        765: "City Emotion Merge",
        772: "Flow of Neo-Venezia",
        778: "Gentle World Connection",
        785: "Peace Embodiment",
        792: "Perfect Emotional Guide",
        798: "Near Eternal Undine",

        805: "Aqua Sage",
        812: "Neo-Venezia Spirit",
        818: "Emotion Flow Entity",
        825: "Perfect Guide State",
        832: "Water Harmony God Candidate",
        839: "City Soul Listener",
        845: "Undine Transcendent",
        852: "Calmness Absolute",
        859: "Waterway Deity",
        865: "Emotion Guide Incarnate",
        872: "Neo-Venezia Myth",
        879: "Harmony Eternal",
        886: "Ultimate Undine",
        892: "Perfect Serenity",
        899: "Legend Beyond Water",

        906: "Apex Undine",
        912: "Beyond Emotion Flow",
        919: "City Water Consciousness",
        926: "Final Guide Form",
        932: "Absolute Harmony",
        939: "Neo-Venezia Essence",
        946: "Infinite Calm Flow",
        953: "Perfect City Spirit",
        959: "Emotion Transcendence",
        966: "God of Water Guides",
        973: "End of Disturbance",
        979: "Abyss of Calm",
        986: "Final Reflection",
        993: "Nothing But Water",
        1000: "Aria"
        }
}
