import { AnimeThemeConfig } from "./types"
import { GiFist, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiCrystalBall, GiStarSwirl, GiAnvilImpact } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const ashitaNoJoeTheme: AnimeThemeConfig = {
    id: "ashita-no-joe",
    displayName: "Ashita no Joe",
    description: "Joe Yabuki is a delinquent from the slums whose raw talent for boxing catches trainer Danpei's eye. His meteoric rise through the boxing world burns with fierce passion — and foreshadows a tragic end.",
    cssVars: {
        "--color-brand-200": "240 200 168",
        "--color-brand-300": "220 155 110",
        "--color-brand-400": "195 105 58",
        "--color-brand-500": "162 65 22",
        "--color-brand-600": "125 38 8",
        "--color-brand-700": "88 18 2",
        "--color-brand-800": "55 8 0",
        "--color-brand-900": "28 3 0",
        "--color-brand-950": "12 1 0",
        "--brand": "162 65 22",
        "--background": "#050100",
        "--paper": "#0c0300",
        "--color-gray-950": "5 1 0",
        "--color-gray-900": "15 5 1",
        "--color-gray-800": "30 12 3",
        "--color-gray-700": "52 22 6",
        "--color-gray-600": "82 38 14",
        "--color-gray-500": "122 65 28",
        "--color-gray-400": "165 105 58",
        "--color-gray-300": "205 152 98",
        "--color-gray-200": "235 195 148",
        "--color-gray-100": "250 228 198",
        "--color-gray-50": "255 246 235",
    },
    sidebarOverrides: {
        "home": { icon: GiFist, label: "Doya Slums" },
        "schedule": { icon: GiAlarmClock, label: "Fight Schedule" },
        "manga": { icon: LuBookOpen, label: "Training Log" },
        "lists": { icon: GiScrollUnfurled, label: "Opponent List" },
        "discover": { icon: GiBullseye, label: "New Challengers" },
        "torrent-list": { icon: GiAnvilImpact, label: "Knockout Cache" },
        "debrid": { icon: GiHeartKey, label: "Ring Vault" },
        "unmatched": { icon: GiCrystalBall, label: "Unmatched Files" },
        "enmasse": { icon: GiResize, label: "Tournament Night" },
        "scan-summaries": { icon: TbReportSearch, label: "Fight Reports" },
        "auto-downloader": { icon: LuRss, label: "Ring Alerts" },
        "community": { icon: GiStarSwirl, label: "Doya Circle" },
        "achievements": { icon: GiTrophyCup, label: "Champion Belts" },
        "milestones": { icon: LuFlag, label: "Fight Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Corner Alerts" },
        "theme-manager": { icon: GiPalette, label: "Ash Colors" },
        "extensions": { icon: BiExtension, label: "Glove Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Corner Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Danpei Config" },
    },
    achievementNames: {
        "a_first_episode": "First Jab",
        "a_first_complete": "First Victory",
        "a_hundred_club": "Hundred Rounds",
        "a_binge_king": "Joe Marathon",
        "a_completionist": "Championship Contender",
        "a_mega_completionist": "Legend of the Ring",
        "a_loyal_fan": "Ringside Regular",
        "a_zero_to_hero": "Delinquent to Champion",
        "m_first_chapter": "First Bell",
        "m_completionist": "Full Fight Archive",
    },
    musicUrl: "",
    previewColors: {
        bg: "#050100",
        primary: "#a24116",
        secondary: "#505050",
        accent: "#e8c890",
    },
    particleColor: "#c06828",
    backgroundDim: 0.35,
    backgroundBlur: 20,
    milestoneNames: {
        1: "Street Brawler",
        5: "Reform School Fighter",
        15: "Danpei's Pupil",
        30: "Junior Champion",
        50: "Ranked Contender",
        75: "World Stage Bound",
        100: "Tomorrow's Champion",
    },
}
