import { AnimeThemeConfig } from "./types"
import { GiFist, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiCrystalBall, GiStarSwirl, GiAnvilImpact } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const bakiTheme: AnimeThemeConfig = {
    id: "baki",
    displayName: "Baki the Grappler",
    description: "Baki Hanma trains obsessively to defeat his father Yujiro — the strongest creature on earth. He fights legendary martial artists across styles and genres in the most extreme combat tournament imaginable.",
    cssVars: {
        "--color-brand-200": "240 175 175",
        "--color-brand-300": "222 120 120",
        "--color-brand-400": "198 68 68",
        "--color-brand-500": "168 25 25",
        "--color-brand-600": "130 8 8",
        "--color-brand-700": "92 2 2",
        "--color-brand-800": "58 0 0",
        "--color-brand-900": "28 0 0",
        "--color-brand-950": "12 0 0",
        "--brand": "168 25 25",
        "--background": "#060000",
        "--paper": "#0e0000",
        "--color-gray-950": "6 0 0",
        "--color-gray-900": "16 2 2",
        "--color-gray-800": "30 5 5",
        "--color-gray-700": "52 10 10",
        "--color-gray-600": "82 18 18",
        "--color-gray-500": "122 35 35",
        "--color-gray-400": "165 68 68",
        "--color-gray-300": "205 112 112",
        "--color-gray-200": "235 158 158",
        "--color-gray-100": "250 200 200",
        "--color-gray-50": "255 235 235",
    },
    sidebarOverrides: {
        "home": { icon: GiFist, label: "Underground Arena" },
        "schedule": { icon: GiAlarmClock, label: "Fight Schedule" },
        "manga": { icon: LuBookOpen, label: "Fighter Files" },
        "lists": { icon: GiScrollUnfurled, label: "Fighter Registry" },
        "discover": { icon: GiBullseye, label: "New Opponents" },
        "torrent-list": { icon: GiAnvilImpact, label: "Technique Cache" },
        "debrid": { icon: GiHeartKey, label: "Arena Vault" },
        "unmatched": { icon: GiCrystalBall, label: "Unknown Fighters" },
        "enmasse": { icon: GiResize, label: "World Tournament" },
        "scan-summaries": { icon: TbReportSearch, label: "Fight Reports" },
        "auto-downloader": { icon: LuRss, label: "Fighter Feed" },
        "community": { icon: GiStarSwirl, label: "Baki Circle" },
        "achievements": { icon: GiTrophyCup, label: "Combat Trophies" },
        "milestones": { icon: LuFlag, label: "Strength Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Fight Alerts" },
        "theme-manager": { icon: GiPalette, label: "Combat Colors" },
        "extensions": { icon: BiExtension, label: "Fighter Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Arena Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Baki Config" },
    },
    achievementNames: {
        "a_first_episode": "First Fight",
        "a_first_complete": "First Victory",
        "a_hundred_club": "Hundred Training Days",
        "a_binge_king": "Baki Marathon",
        "a_completionist": "Underground Champion",
        "a_mega_completionist": "Strongest Son",
        "a_loyal_fan": "Fighter Fan",
        "a_zero_to_hero": "Kid to Champion",
        "m_first_chapter": "First Punch",
        "m_completionist": "Full Fighting Archive",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060000",
        primary: "#a81919",
        secondary: "#505050",
        accent: "#f0a0a0",
    },
    particleColor: "#c03030",
    backgroundDim: 0.35,
    backgroundBlur: 18,
    milestoneNames: {
        1: "Underground Rookie",
        5: "Tournament Fighter",
        15: "Seasoned Warrior",
        30: "Champion Challenger",
        50: "World Class",
        75: "Yujiro's Equal",
        100: "Strongest Son",
    },
}
