import { AnimeThemeConfig } from "./types"
import { GiCrossedSwords, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiCrystalBall, GiStarSwirl, GiRoad } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const bananaFishTheme: AnimeThemeConfig = {
    id: "banana-fish",
    displayName: "Banana Fish",
    description: "Ash Lynx is a beautiful, deadly street gang leader in New York caught up in a conspiracy around a mysterious drug called Banana Fish. His meeting with Japanese photographer Eiji changes everything.",
    cssVars: {
        "--color-brand-200": "220 200 170",
        "--color-brand-300": "195 162 112",
        "--color-brand-400": "165 120 62",
        "--color-brand-500": "132 82 25",
        "--color-brand-600": "98 52 8",
        "--color-brand-700": "68 28 2",
        "--color-brand-800": "42 12 0",
        "--color-brand-900": "20 4 0",
        "--color-brand-950": "8 1 0",
        "--brand": "132 82 25",
        "--background": "#050200",
        "--paper": "#0c0400",
        "--color-gray-950": "5 2 0",
        "--color-gray-900": "14 6 1",
        "--color-gray-800": "28 14 3",
        "--color-gray-700": "48 25 6",
        "--color-gray-600": "75 42 12",
        "--color-gray-500": "115 72 25",
        "--color-gray-400": "158 112 52",
        "--color-gray-300": "200 158 90",
        "--color-gray-200": "232 198 138",
        "--color-gray-100": "250 228 188",
        "--color-gray-50": "255 245 232",
    },
    sidebarOverrides: {
        "home": { icon: GiRoad, label: "New York Streets" },
        "schedule": { icon: GiAlarmClock, label: "Street Schedule" },
        "manga": { icon: LuBookOpen, label: "Case Files" },
        "lists": { icon: GiScrollUnfurled, label: "Crew List" },
        "discover": { icon: GiBullseye, label: "New Leads" },
        "torrent-list": { icon: GiCrossedSwords, label: "Weapon Cache" },
        "debrid": { icon: GiHeartKey, label: "Street Vault" },
        "unmatched": { icon: GiCrystalBall, label: "Unsolved Cases" },
        "enmasse": { icon: GiResize, label: "Gang War" },
        "scan-summaries": { icon: TbReportSearch, label: "Case Reports" },
        "auto-downloader": { icon: LuRss, label: "Street Feed" },
        "community": { icon: GiStarSwirl, label: "Banana Fish Circle" },
        "achievements": { icon: GiTrophyCup, label: "Street Trophies" },
        "milestones": { icon: LuFlag, label: "Survival Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Danger Alerts" },
        "theme-manager": { icon: GiPalette, label: "Noir Colors" },
        "extensions": { icon: BiExtension, label: "Street Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Street Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Ash Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "New York Streets",
        "a_episode_counter": "Street Vault Mark",
        "a_episode_titan": "Leader Relic",
        "a_hours_invested": "Case Proof",
        "a_time_lord": "Unsolved Cases Decree",
        "a_anime_collector": "Danger Alerts Catalogue",
        "a_library_legend": "York Library",
        "a_first_complete": "First Lead",
        "a_hundred_club": "Hundred Street Days",
        "a_first_day": "Street Fan Seal",
        "a_first_rating": "Uncovered Appraisal",
        "a_ten_thousand_min": "Streets Standard",
        "a_season_veteran": "Archive Library",
        "a_year_explorer": "Banana Fish Circle Map",
        "a_century_watcher": "Banana Fish Marathon Ledger",
        "a_five_hundred_eps": "Eiji Dominion",
        "a_thousand_eps": "Noir Record",
        "a_watching_ten": "Danger Alerts Acclaim",
        "a_ptw_hoarder": "Banana Library",
        "a_dropped_honesty": "Case Summit",
        "a_five_thousand_eps": "Victim Warrant",
        "a_ten_completed": "Page Afterglow",
        "a_fifty_completed": "Banana Ascension",
        "a_five_hundred_completed": "Case Clear",
        "a_mean_score_tracker": "Conspiracy Uncovered Verdict",
        "a_unique_studios": "Street Vault Collection",
        "a_days_spent_watching": "Archive Dominion",
        "a_all_status": "Victim Leader Testament",
        "a_first_favorite": "Street Cabinet",
        "a_favorites_collector": "Unsolved Cases Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Banana Fish Marathon Drive",
        "a_marathon_runner": "Banana Fish Marathon Gauntlet",
        "a_weekend_warrior": "Page Ordeal",
        "a_non_stop": "Victim Leader Fever",
        "a_one_more_episode": "Gang War Mantle",
        "a_speed_run": "Survival Vigil",
        "a_double_feature": "Ash Crown",
        "a_triple_threat": "Gang War Record",
        "a_five_a_day": "Archive Accord",
        "a_back_to_back": "Fish Surge",
        "a_seasonal_binge": "Banana Fish Marathon Cascade",
        "a_cour_crusher": "Ash Lynx Ordeal",
        "a_half_day_watch": "Case Crown",
        "a_full_day_watch": "York Streets Pinnacle",
        "a_power_weekend": "Ash Run",
        "a_binge_king": "Banana Fish Marathon",
        "a_no_sleep": "Conspiracy Uncovered Vigil",
        "a_entire_season": "Conspiracy Library",
        "a_seven_day_challenge": "Fish Marathon Mark",
        "a_hundred_day_binge": "Streets Surge",
        "a_genre_binge": "Ash Binge",
        "a_studio_binge": "Weapon Fever",
        "a_season_sweep": "Gang War Codex",
        "a_forty_eight_hour": "Leads Overture",
        "a_ep_counter_day": "Lead Aegis",
        "a_multi_series_binge": "Crew Streak",
        "a_midnight_binge": "Weapon Cascade",
        "a_new_year_binge": "Victim Leader Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Eiji Action",
        "a_genre_adventure": "Archive Adventure",
        "a_genre_comedy": "Street Vault Comedy",
        "a_genre_drama": "Banana Drama",
        "a_genre_fantasy": "Street Vault Fantasy",
        "a_genre_horror": "Leader Horror",
        "a_genre_mystery": "Victim Leader Mystery",
        "a_genre_romance": "Crew Romance",
        "a_genre_scifi": "Case Sci-Fi",
        "a_genre_sol": "Survival Slice",
        "a_genre_sports": "Conspiracy Uncovered Sports",
        "a_genre_supernatural": "Leader Supernatural",
        "a_genre_thriller": "Victim Leader Thriller",
        "a_genre_mecha": "Fish Marathon Mecha",
        "a_genre_music": "Uncovered Music",
        "a_genre_psychological": "Case Psychological",
        "a_genre_ecchi": "Banana Ecchi",
        "a_genre_mahou_shoujo": "Archive Magic Shoujo",
        "a_tag_isekai": "His Isekai",
        "a_tag_harem": "Eiji Harem",
        "a_tag_bl": "Victim Bl",
        "a_tag_gl": "York Gl",
        "a_tag_historical": "Conspiracy Uncovered Historical",
        "a_tag_military": "Victim Military",
        "a_tag_school": "York Streets School",
        "a_tag_martial_arts": "Japanese Martial Arts",
        "a_tag_vampire": "Victim Vampire",
        "a_tag_samurai": "Gang War Samurai",
        "a_tag_space": "Conspiracy Space",
        "a_tag_parody": "Survival Parody",
        "a_tag_idol": "Fish Idol",
        "a_tag_post_apocalyptic": "Conspiracy Uncovered Post Apocalyptic",
        "a_tag_cyberpunk": "York Streets Cyberpunk",
        "a_tag_shounen": "Ash Shounen",
        "a_tag_seinen": "York Seinen",
        "a_tag_shoujo": "Uncovered Shoujo",
        "a_tag_josei": "Gang War Josei",
        "a_tag_survival": "Japanese Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "Conspiracy Uncovered",
        "a_mega_completionist": "Banana Fish Complete",
        "a_completion_rate_50": "Survival Return",
        "a_completion_rate_75": "His Crown",
        "a_completion_rate_90": "Banana Fish Marathon Resolution",
        "a_no_drop": "Ash Decree",
        "a_long_runner_complete": "Weapon Clear",
        "a_sequel_chain": "Streets Insignia",
        "a_clean_list": "Street Vault Relic",
        "a_from_ptw": "Streets Index",
        "a_rewatch_master": "Uncovered Return",
        "a_short_complete": "Leader Endgame",
        "a_same_day_start_finish": "Banana Fish Circle Pinnacle",
        "a_revival": "Street Vault Insignia",
        "a_zero_to_hero": "Victim to Leader",
        "a_five_genre_complete": "Danger Alerts A Five Genre",
        "a_full_franchise": "Weapon Chronicle",
        "a_batch_complete": "York Crown",
        "a_paused_to_done": "Leader Aegis",
        "a_completion_spree": "Victim Leader Triumph",
        "a_multi_rewatch": "Eiji Triumph",
        "a_dropped_recovery": "Street Fan Conquest",
        "a_ten_perfect_scores": "Banana Fish Acclaim",
        "a_seasonal_clear": "Conspiracy Codex",
        "a_complete_genre_span": "Lead A Complete Genre Span",
        "a_monthly_completions": "Street Afterglow",
        "a_yearly_completions": "Case Epilogue",
        "a_rapid_complete": "Street Vault Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Street Fan",
        "a_studio_devotee": "Ash Treasury",
        "a_rewatcher": "Fish Closure",
        "a_triple_rewatch": "Leads Coda",
        "a_annual_tradition": "Fish Marathon Proof",
        "a_director_fan": "Conspiracy Uncovered Trial",
        "a_voice_actor_fan": "Page Crown",
        "a_ost_lover": "Leads Seal",
        "a_source_reader": "Marathon Cabinet",
        "a_waiting_weekly": "Fish Marathon Clock",
        "a_childhood_revisit": "Fish Seal",
        "a_saga_tracker": "Fish Marathon Standard",
        "a_genre_loyalty": "His Loyalty",
        "a_decade_watcher": "Uncovered Banner",
        "a_adaptation_hunter": "Archive Trial",
        "a_original_anime_fan": "Marathon Testament",
        "a_long_commitment": "His Mark",
        "a_perfect_attendance": "Case Standard",
        "a_favorite_studio_5": "Street Vault Library",
        "a_complete_catalog": "Victim Seal",
        "a_franchise_collector": "Banana Fish Archive",
        "a_airing_follower": "Streets Signal",
        "a_genre_master": "Banana Fish Circle Master",
        "a_staff_follower": "Gang War Oath",
        "a_multi_season_fan": "Fish Hoard",
        "a_format_diversity": "Danger Alerts Cache",
        "a_year_dedication": "Leads Tenure",
        "a_season_dedication": "Victim Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Archive Explorer",
        "a_studio_hopper": "Case Collection",
        "a_tag_explorer": "Eiji Explorer",
        "a_decade_hopper": "Conspiracy Uncovered Chronicle",
        "a_hidden_gem": "Gang War Warrant",
        "a_popular_taste": "Marathon Decree",
        "a_retro_appreciator": "Survival Aegis",
        "a_modern_viewer": "Fish Marathon Pinnacle",
        "a_cross_demographic": "Street Pinnacle",
        "a_underdog_fan": "Conspiracy Trial",
        "a_variety_week": "Conspiracy Uncovered Horizon",
        "a_foreign_cinema": "Marathon Expedition",
        "a_classic_connoisseur": "Marathon Glimpse",
        "a_every_season": "Japanese Archive",
        "a_award_winner": "Page Insignia",
        "a_niche_explorer": "Street Trophies Horizon",
        "a_global_anime": "Victim Leader Crown",
        "a_cult_classic": "York Map",
        "a_random_pick": "Archive Decree",
        "a_new_genre_month": "Street Trophies A New Genre",
        "a_seasonal_completionist": "Banana Fish Marathon Summit",
        "a_unpopular_opinion": "Case Standard Standard",
        "a_top_rated_viewer": "Danger Alerts Seal",
        "a_source_variety": "Fish Marathon Storehouse",
        "a_low_score_brave": "Eiji Measure",
        "a_upcoming_watcher": "Fish Marathon Seal",
        "a_short_series_explorer": "Case Expedition",
        "a_long_series_explorer": "Victim Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Leader Insignia",
        "a_early_bird": "Fish Marathon Banner",
        "a_lunch_break": "His Trial",
        "a_golden_hour": "Danger Alerts Tenure",
        "a_four_am_club": "Victim Leader Gathering",
        "a_witching_hour": "His Tenure",
        "a_new_year_watch": "Marathon Season",
        "a_midnight_premiere": "Leader Devotion",
        "a_all_hours": "Noir Seal",
        "a_dawn_warrior": "Conspiracy Uncovered Aegis",
        "a_afternoon_delight": "Lead Proof",
        "a_prime_time": "Fish Insignia",
        "a_workday_watcher": "Uncovered Pinnacle",
        "a_sunday_marathon": "Archive Momentum",
        "a_rainy_day": "Banana Fish Relic",
        "a_morning_routine": "Banana Fish Marathon Promise",
        "a_night_shift": "Crew Aegis",
        "a_twilight_zone": "Marathon Ledger",
        "a_seasonal_premier": "York Streets Cabinet",
        "a_clock_collector": "Conspiracy Uncovered Repository",
        "a_weekend_binge_hours": "Fish Streak",
        "a_late_night_regular": "York Dominion",
        "a_sunrise_watcher": "Case Relic",
        "a_holiday_watcher": "Fish Pact",
        "a_every_day_of_week": "Streets Ledger",
        "a_monthly_hours": "Banana Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Case Record",
        "a_party_host": "Fish Record",
        "a_social_butterfly": "Fish Marathon Company",
        "a_group_binge": "Street Vault Sprint",
        "a_party_regular": "Case Chronicle",
        "a_sync_viewer": "Noir Standard",
        "a_commentator": "Banana Fish Marathon Record",
        "a_party_marathon": "Eiji Vigil",
        "a_full_house": "Banana Fish Marathon Trial",
        "a_community_pillar": "Fish Alliance",
        "a_watch_party_streak": "Fish Marathon Vigil",
        "a_diverse_party": "Unsolved Cases Seal",
        "a_late_night_party": "Street Trophies Testament",
        "a_party_veteran": "Banana Fish Testament",
        "a_genre_party": "Banana Fish Party",
        "a_weekly_party": "Street Trophies Calendar",
        "a_silent_viewer": "Victim Leader Mantle",
        "a_recommendation_giver": "York Streets Network",
        "a_party_completionist": "Eiji Coda",
        "a_social_scorer": "Ash Lynx Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Marathon Proof",
        "a_fibonacci": "Conspiracy Dominion",
        "a_palindrome_day": "Weapon Relic",
        "a_binary_day": "Uncovered Mark",
        "a_full_moon": "Banana Insignia",
        "a_leap_year": "Danger Alerts Devotion",
        "a_time_traveler": "Japanese Record",
        "a_genre_clash": "Street Trophies Clash",
        "a_triple_seven": "Street Trophies Testament Testament",
        "a_thousand_complete": "Conspiracy Uncovered Epilogue",
        "a_pi_episodes": "Street Crown",
        "a_synchronicity": "Fish Anchor",
        "a_world_record": "Streets Warrant",
        "a_nice": "Banana Fish Marathon Chronicle",
        "a_power_level": "Lead Testament",
        "a_answer_42": "Conspiracy Uncovered Standard",
        "a_square_number": "Conspiracy Uncovered Decree",
        "a_prime_count": "York Streets Seal",
        "a_matching_date": "Banana Fish Marathon Mantle",
        "a_century_episode": "Uncovered Mark Mark",
        "a_double_digits": "Lead Testament Testament",
        "a_one_two_three": "Fish Marathon Crown",
        "a_lucky_seven": "Conspiracy Uncovered Crown",
        "a_all_tens": "Banana Fish Marathon Criterion",
        "a_exact_hundred_eps": "Conspiracy Standard",
        "a_year_match_count": "Street Clock",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Fish Marathon Ledger",
        "a_movie_buff": "Streets Mark",
        "a_ova_hunter": "Noir Standard Standard",
        "a_ona_explorer": "His Secret",
        "a_special_watcher": "Fish Marathon Relic",
        "a_short_king": "Banana Fish Circle Crown",
        "a_variety_pack": "Street Trophies Inquiry",
        "a_film_festival": "Leads Chronicle",
        "a_music_video": "Fish Chronicle",
        "a_tv_short": "Leader Record",
        "a_movie_marathon": "Banana Gauntlet",
        "a_double_length": "Street Trophies Crown",
        "a_anthology": "Conspiracy Uncovered Aegis Aegis",
        "a_mini_series": "Street Fan Decree",
        "a_theatrical": "Survival Accord",
        "a_format_master": "Weapon Vault",
        "a_long_movie": "Japanese Insignia",
        "a_back_catalog": "Eiji Standard",
        "a_cm_watcher": "Page Aegis",
        "a_pv_collector": "York Streets Storehouse",
        "a_format_balance": "Unsolved Cases Vault",
        "a_episodic_master": "Banana Fish Circle Standard",
        "a_sequel_movie": "Gang War Pinnacle",
        "a_recap_watcher": "Marathon Testament Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Street Trophies Devotion",
        "a_mega_streak": "York Streets Streak",
        "a_weekly_warrior": "Street Fan Season",
        "a_monthly_watcher": "Street Vault Calendar",
        "a_comeback": "Lead Decree",
        "a_weekend_streak": "Fish Passage",
        "a_no_zero_days": "Survival Warrant",
        "a_iron_will": "Street Seal",
        "a_habit_formed": "Case Warrant",
        "a_consistent_pace": "His Measure",
        "a_year_long": "Street Fan Yearlong",
        "a_double_streak": "Uncovered Watch",
        "a_streak_recovery": "Victim Season",
        "a_daily_minimum": "Banana Fish Marathon Focus",
        "a_winter_streak": "Unsolved Cases Watch",
        "a_summer_streak": "York Streets Resolve",
        "a_morning_streak": "Weapon Clock",
        "a_night_streak": "Victim Leader Constancy",
        "a_unbreakable": "Street Proof",
        "a_eternal_flame": "Leads Standard",
        "a_completion_streak": "York Return",
        "a_rating_streak": "Conspiracy Balance",
        "a_multi_ep_streak": "Victim Ritual",
        "a_genre_streak": "Archive Streak",
        "a_studio_streak": "Fish Cabinet",
        "a_perfect_week": "Japanese Relic",

        // ── ANIME SCORING ──
        "a_critic": "Victim Leader Scrutiny",
        "a_perfect_ten": "Eiji Audit",
        "a_harsh_critic": "Eiji Gauge",
        "a_fair_judge": "York Balance",
        "a_generous_spirit": "Fish Pinnacle",
        "a_score_all": "Banana Fish Criterion",
        "a_wide_range": "Page Ledger",
        "a_controversial": "Conspiracy Decree",
        "a_consistent_scorer": "Ash Verdict",
        "a_score_sniper": "Gang War Score",
        "a_evolving_taste": "Crew Accord",
        "a_bell_curve": "York Streets Insignia",
        "a_picky_watcher": "Survival Seal",
        "a_100_rated": "Fish Warrant",
        "a_500_rated": "Weapon Pinnacle",
        "a_mediocre_majority": "Leader Canon",
        "a_rating_spree": "His Review",
        "a_score_variance": "Banana Fish Circle Score",
        "a_masterpiece_hunter": "Streets Banner",
        "a_contrarian": "Street Record",
        "a_optimist": "Page Ledger Ledger",
        "a_score_distributor": "Street Fan Appraisal",
        "a_genre_critic": "York Streets Critic",
        "a_mean_above_8": "Victim Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "Survival Resolve",
        "a_valentines_weeb": "Eiji Vow",
        "a_pi_day": "Eiji Trial",
        "a_april_fools": "Victim Leader Devotion",
        "a_international_anime_day": "Conspiracy Uncovered Pinnacle",
        "a_star_wars_day": "Leads Chronicle Chronicle",
        "a_summer_solstice": "Crew Calendar",
        "a_tanabata": "Survival Focus",
        "a_friday_13th": "Gang War Relic",
        "a_halloween_spirit": "His Vow",
        "a_thanksgiving_binge": "Ash Run Run",
        "a_christmas_special": "Street Season",
        "a_new_years_eve": "Ash Pilgrimage",
        "a_birthday_watch": "Street Fan Vow",
        "a_holiday_marathon": "Banana Fish Circle Overture",
        "a_independence_day": "Leader Banner",
        "a_culture_day": "Uncovered Insignia",
        "a_spring_equinox": "Danger Alerts Decree",
        "a_earth_day": "Banana Record",
        "a_labor_day": "Banana Fish Marathon Seal",
        "a_winter_solstice": "Crew Pilgrimage",
        "a_anime_birthday": "Street Fan Pilgrimage",
        "a_every_holiday": "Noir Resolve",
        "a_consecutive_holidays": "Marathon Season Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Banana Rank",
        "a_meta_collector": "Marathon Hoard",
        "a_meta_category_starter": "Street Badge",
        "a_meta_tier_climber": "Lead Glyph",
        "a_meta_tier_max": "Street Fan Writ",
        "a_meta_xp_earner": "Archive Emblem",
        "a_meta_difficulty_easy": "Ash Mechanism",
        "a_meta_difficulty_hard": "Marathon Writ",
        "a_meta_unlock_spree": "Crew Panel",
        "a_meta_completionist": "Uncovered Fulfillment",
        "a_meta_diverse": "Conspiracy Emblem",
        "a_meta_dominator": "Conspiracy Uncovered Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Page",
        "m_chapter_counter": "His Pinnacle",
        "m_chapter_titan": "His Relic",
        "m_reading_hours": "Ash Relic",
        "m_reading_time_lord": "Fish Marathon Pinnacle Pinnacle",
        "m_manga_collector": "Leads Ledger",
        "m_library_legend": "Ash Lynx Reliquary",
        "m_first_complete": "Archive Triumph",
        "m_hundred_club": "Fish Network",
        "m_first_day": "Ash Seal",
        "m_first_rating": "Banana Fish Marathon Eye",
        "m_ten_thousand_pages": "Unsolved Cases Gauge",
        "m_volume_collector": "Street Vault Storehouse",
        "m_year_explorer": "Street Fan Quest",
        "m_century_reader": "Street Vault Dominion",
        "m_five_hundred_ch": "Banana Fish Marathon Legend",
        "m_thousand_ch": "Banana Fish Marathon Testament",
        "m_reading_ten": "Ash Appraisal",
        "m_ptr_hoarder": "Fish Index",
        "m_dropped_honesty": "Danger Alerts Summit",
        "m_season_reader": "Leader Treasury",
        "m_active_reader": "Conspiracy Uncovered Trial Trial",
        "m_five_thousand_ch": "Street Vault Standard",
        "m_ten_completed": "His Resolution",
        "m_fifty_completed": "Case Harvest",
        "m_five_hundred_completed": "Victim Legacy",
        "m_mean_score_tracker": "Street Fan Audit",
        "m_unique_authors": "Victim Reserve",
        "m_all_status": "Street Testament",
        "m_first_favorite": "Gang War Cache",
        "m_favorites_collector": "Ash Shelf",
        "m_days_spent_reading": "Fish Marathon Decree",

        // ── MANGA BINGE ──
        "m_binge_reader": "Street Vault Streak",
        "m_marathon_reader": "Lead Rush",
        "m_weekend_reader": "Banana Run",
        "m_non_stop_reading": "Victim Leader Gauntlet",
        "m_one_more_chapter": "Victim Testament",
        "m_speed_read": "Lead Drive",
        "m_double_story": "Danger Alerts Banner",
        "m_triple_read": "Leads Record",
        "m_five_a_day": "Streets Insignia Insignia",
        "m_chapter_chain": "Conspiracy Uncovered Accord",
        "m_volume_binge": "Street Fan Drive",
        "m_power_reader": "Streets Seal",
        "m_half_day_read": "Street Trophies Aegis",
        "m_full_day_read": "Street Vault Aegis",
        "m_power_weekend": "Leads Streak",
        "m_binge_king": "Gang War Momentum",
        "m_no_sleep_read": "Leads Rush",
        "m_full_series_rush": "Conspiracy Uncovered Cascade",
        "m_seven_day_challenge": "Conspiracy Uncovered Warrant",
        "m_hundred_day_read": "Street Relic",
        "m_volume_rush": "Banana Fish Marathon Gauntlet Gauntlet",
        "m_series_sweep": "Uncovered Trial",
        "m_genre_binge": "Danger Alerts Binge",
        "m_author_binge": "Ash Surge",
        "m_chapter_counter_day": "Gang War Ledger",
        "m_multi_series_binge": "Page Charge",
        "m_midnight_binge": "Lead Tempest",
        "m_new_year_binge": "Streets Passage",
        "m_forty_eight_hour": "Street Fan Rally",
        "m_oneshot_binge": "Archive Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Banana Fish Marathon Action",
        "m_genre_adventure": "Gang War Adventure",
        "m_genre_comedy": "Unsolved Cases Comedy",
        "m_genre_drama": "Eiji Drama",
        "m_genre_fantasy": "Banana Fantasy",
        "m_genre_horror": "Conspiracy Uncovered Horror",
        "m_genre_mystery": "Street Trophies Mystery",
        "m_genre_romance": "Fish Marathon Romance",
        "m_genre_scifi": "Street Vault Sci-Fi",
        "m_genre_sol": "Conspiracy Uncovered Slice",
        "m_genre_sports": "Conspiracy Sports",
        "m_genre_supernatural": "Case Supernatural",
        "m_genre_thriller": "Japanese Thriller",
        "m_genre_psychological": "Eiji Psychological",
        "m_genre_isekai": "Survival Isekai",
        "m_genre_shounen": "Conspiracy Shounen",
        "m_genre_ecchi": "Uncovered Ecchi",
        "m_genre_mahou_shoujo": "Leads Magic Shoujo",
        "m_genre_mecha": "Banana Fish Marathon Mecha",
        "m_genre_music": "Lead Music",
        "m_tag_isekai_new": "Ash Isekai New",
        "m_tag_harem": "Street Fan Harem",
        "m_tag_bl": "Fish Marathon Bl",
        "m_tag_gl": "Conspiracy Gl",
        "m_tag_historical": "Street Fan Historical",
        "m_tag_military": "Conspiracy Uncovered Military",
        "m_tag_school": "Leads School",
        "m_tag_martial_arts": "Page Martial Arts",
        "m_tag_vampire": "Conspiracy Uncovered Vampire",
        "m_tag_samurai": "Crew Samurai",
        "m_tag_space": "Weapon Space",
        "m_tag_parody": "His Parody",
        "m_tag_idol": "Eiji Idol",
        "m_tag_post_apocalyptic": "York Streets Post Apocalyptic",
        "m_tag_cyberpunk": "Page Cyberpunk",
        "m_tag_shoujo": "His Shoujo",
        "m_tag_survival": "Leader Survival",
        "m_tag_cooking": "Crew Cooking",
        "m_tag_medical": "Street Vault Medical",
        "m_tag_villainess": "Uncovered Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Manga Archive",
        "m_mega_completionist": "Uncovered Resolution",
        "m_completion_rate_50": "Banana Fish Circle Return",
        "m_completion_rate_75": "Danger Alerts Ascension",
        "m_completion_rate_90": "His Resolution Resolution",
        "m_no_drop": "Streets Decree",
        "m_long_runner_complete": "Street Vault Clear",
        "m_sequel_chain": "Banana Seal",
        "m_clean_list": "Banana Fish Relic Relic",
        "m_from_ptr": "Marathon Accord",
        "m_reread_master": "Archive Trial Trial",
        "m_oneshot_complete": "Archive Ascension",
        "m_same_day_start_finish": "Streets Crown",
        "m_revival": "Danger Alerts Accord",
        "m_zero_to_hundred": "His Banner",
        "m_five_genre_complete": "Fish Marathon M Five Genre",
        "m_full_collection": "His Proof",
        "m_batch_complete": "Crew Testament",
        "m_paused_to_done": "Ash Lynx Standard",
        "m_completion_spree": "Case Triumph",
        "m_format_completionist": "Fish Testament",
        "m_catch_up": "Unsolved Cases Chronicle",
        "m_multi_reread": "Unsolved Cases Banner",
        "m_dropped_recovery": "Gang War Conquest",
        "m_ten_perfect_scores": "Uncovered Judgment",
        "m_complete_genre_span": "Page M Complete Genre Span",
        "m_monthly_completions": "Page Return",
        "m_yearly_completions": "Marathon Epilogue",
        "m_rapid_complete": "Street Finale",
        "m_author_complete": "Crew Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Fish Legacy",
        "m_mangaka_lover": "Gang War Standard",
        "m_rereader": "Ash Lynx Relic",
        "m_triple_reread": "Unsolved Cases Testament",
        "m_annual_reread": "Ash Banner",
        "m_publisher_fan": "Street Vault Mark Mark",
        "m_artist_fan": "Ash Lynx Insignia",
        "m_adaptation_compare": "Eiji Insignia",
        "m_source_material_fan": "Case Cache",
        "m_waiting_weekly": "Crew Weekly",
        "m_classic_reader": "Gang War Lantern",
        "m_saga_reader": "Leader Crown",
        "m_genre_loyalty": "Street Loyalty",
        "m_decade_reader": "Eiji Warrant",
        "m_ln_adaptation": "Page Mark",
        "m_original_work": "Marathon Standard",
        "m_long_commitment": "Street Trophies Mark",
        "m_up_to_date": "Street Fan Warrant",
        "m_favorite_mangaka": "Archive Treasury",
        "m_complete_portfolio": "Lead Triumph",
        "m_franchise_collector": "Fish Archive",
        "m_serialization_follower": "Eiji Handshake",
        "m_genre_master": "His Master",
        "m_multi_series_author": "Noir Insignia",
        "m_format_diversity": "Page Shelf",
        "m_year_dedication": "York Streets Tenure",
        "m_ongoing_follower": "York Streets Fellowship",
        "m_genre_loyalty_50": "Street Trophies Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Street Vault Explorer",
        "m_publisher_hopper": "Noir Record Record",
        "m_tag_explorer": "Banana Fish Circle Explorer",
        "m_decade_hopper": "Crew Chronicle",
        "m_hidden_gem": "Victim Mark",
        "m_popular_taste": "Case Record Record",
        "m_retro_reader": "Fish Testament Testament",
        "m_modern_reader": "His Seal",
        "m_cross_demographic": "Eiji Crown",
        "m_underdog_fan": "Street Fan Accord",
        "m_variety_week": "Victim Horizon",
        "m_manhwa_reader": "Leads Proof",
        "m_manhua_reader": "Ash Lynx Mantle",
        "m_classic_connoisseur": "Case Glimpse",
        "m_award_winner": "Fish Marathon Seal Seal",
        "m_niche_explorer": "Conspiracy Horizon",
        "m_world_manga": "Noir Chronicle",
        "m_cult_classic": "Street Vault Map",
        "m_random_pick": "Fish Marathon Standard Standard",
        "m_new_genre_month": "York M New Genre Month",
        "m_year_completionist": "Weapon Fulfillment",
        "m_unpopular_opinion": "Marathon Aegis",
        "m_top_rated_reader": "York Record",
        "m_source_variety": "His Catalogue",
        "m_low_score_brave": "Banana Score",
        "m_short_manga_explorer": "Fish Marathon Compass",
        "m_long_manga_explorer": "Ash Lynx Survey",
        "m_serialization_explorer": "Banana Fish Circle Road",

        // ── MANGA TIME ──
        "m_night_owl": "Street Vault Accord",
        "m_early_bird": "Leader Banner Banner",
        "m_lunch_reader": "Page Relic",
        "m_commute_reader": "Conspiracy Uncovered Tenure",
        "m_four_am_club": "Archive Fellowship",
        "m_new_year_read": "Leader Pact",
        "m_all_hours": "York Accord",
        "m_prime_time_reader": "Conspiracy Uncovered Banner",
        "m_workday_reader": "Archive Accord Accord",
        "m_sunday_read": "Street Testament Testament",
        "m_morning_routine": "Conspiracy Uncovered Discipline",
        "m_night_shift_reader": "Japanese Accord",
        "m_seasonal_premier_read": "Weapon Storehouse",
        "m_clock_collector": "Archive Reserve",
        "m_late_night_horror": "Victim Leader Mark",
        "m_afternoon_reader": "Uncovered Mantle",
        "m_golden_hour_reader": "Japanese Observance",
        "m_dawn_reader": "Archive Mantle",
        "m_twilight_reader": "Street Crown Crown",
        "m_midnight_start": "Weapon Routine",
        "m_weekend_binge_hours": "Danger Alerts Momentum",
        "m_late_night_regular": "Uncovered Testament",
        "m_sunrise_reader": "Marathon Record",
        "m_every_day_of_week": "Weapon Seal",
        "m_monthly_hours": "Gang War Vigil",
        "m_bedtime_reader": "Page Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Case Mantle",
        "m_webtoon_reader": "His Standard",
        "m_full_color": "Japanese Accord Accord",
        "m_doujin_reader": "Streets Record",
        "m_anthology_reader": "Street Vault Accord Accord",
        "m_adaptation_reader": "Banana Fish Marathon Banner",
        "m_longstrip_reader": "Fish Marathon Trial",
        "m_4koma_reader": "Leads Relic",
        "m_oneshot_reader": "His Mantle",
        "m_format_variety": "Japanese Gallery",
        "m_light_novel_reader": "Eiji Insignia Insignia",
        "m_novel_reader": "Conspiracy Uncovered Crown Crown",
        "m_visual_storyteller": "Street Vault Testament",
        "m_colored_classic": "Banana Fish Circle Survey",
        "m_webcomic_fan": "Page Insignia Insignia",
        "m_manga_to_anime": "Leader Record Record",
        "m_seinen_reader": "Ash Lynx Pinnacle",
        "m_josei_reader": "His Pinnacle Pinnacle",
        "m_award_winning_art": "Danger Alerts Relic",
        "m_debut_work": "Gang War Dominion",
        "m_vertical_scroll": "Street Vault Crown",
        "m_traditional_format": "Eiji Hoard",
        "m_cross_media": "Case Accord",
        "m_spinoff_reader": "His Mark Mark",
        "m_remake_reader": "Noir Insignia Insignia",
        "m_collaboration_reader": "Eiji Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Street Fan Focus",
        "m_mega_streak": "His Routine",
        "m_weekly_warrior": "Street Trophies Season",
        "m_monthly_reader": "Crew Discipline",
        "m_comeback": "Banana Fish Circle Standard Standard",
        "m_weekend_streak": "Marathon Fever",
        "m_no_zero_days": "Survival Proof",
        "m_iron_will": "Survival Ledger",
        "m_habit_formed": "Leader Crown Crown",
        "m_consistent_pace": "Fish Marathon Scrutiny",
        "m_year_long": "Danger Alerts Observance",
        "m_double_streak": "Archive Resolve",
        "m_streak_recovery": "York Streets Resolve Resolve",
        "m_daily_minimum": "Crew Focus",
        "m_winter_streak": "Victim Observance",
        "m_summer_streak": "Streets Observance",
        "m_morning_streak": "Page Clock",
        "m_night_streak": "York Streets Discipline",
        "m_unbreakable": "Banana Fish Marathon Warrant",
        "m_eternal_flame": "Conspiracy Uncovered Record",
        "m_chapter_a_day": "Fish Relic",
        "m_genre_streak": "Street Vault Streak Mode",
        "m_completion_streak": "Eiji Return",
        "m_rating_streak": "Street Vault Appraisal",
        "m_multi_ch_streak": "York Streets Tenure Tenure",
        "m_author_streak": "Ash Lynx Calendar",
        "m_perfect_week_manga": "Eiji Accord",
        "m_diverse_streak": "Leader Streak",

        // ── MANGA SCORING ──
        "m_critic": "Street Scrutiny",
        "m_perfect_ten": "Banana Verdict",
        "m_harsh_critic": "Lead Scale",
        "m_fair_judge": "Leads Eye",
        "m_generous_spirit": "Streets Crown Crown",
        "m_score_all": "Banana Fish Marathon Reckoning",
        "m_wide_range": "Marathon Ledger Ledger",
        "m_controversial": "York Testament",
        "m_consistent_scorer": "Ash Grade",
        "m_score_sniper": "Page Reckoning",
        "m_evolving_taste": "Street Fan Trial",
        "m_bell_curve": "Case Accord Accord",
        "m_picky_reader": "Conspiracy Uncovered Relic",
        "m_100_rated": "Banana Mark",
        "m_500_rated": "Banana Fish Circle Proof",
        "m_mediocre_majority": "Unsolved Cases Canon",
        "m_rating_spree": "Banana Fish Marathon Verdict",
        "m_score_variance": "Fish Marathon Measure",
        "m_binge_rater": "Ash Lynx Passage",
        "m_reread_rerate": "Unsolved Cases Banner Banner",
        "m_masterpiece_hunter": "Street Banner",
        "m_contrarian": "Case Aegis",
        "m_optimist": "Banana Fish Circle Mark",
        "m_score_distributor": "Street Balance",
        "m_genre_critic": "Conspiracy Uncovered Critic",
        "m_mean_above_8": "Leader Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Banana Season",
        "m_valentines_read": "Victim Valentine",
        "m_pi_day": "Leader Accord",
        "m_april_fools": "Weapon Devotion",
        "m_international_manga_day": "Conspiracy Proof",
        "m_free_comic_day": "Noir Chronicle Chronicle",
        "m_summer_solstice": "Streets Focus",
        "m_tanabata": "Noir Pilgrimage",
        "m_friday_13th": "Lead Dominion",
        "m_halloween_read": "Japanese Calendar",
        "m_thanksgiving_binge": "York Charge",
        "m_christmas_read": "Archive Pact",
        "m_new_years_eve": "Crew New Year",
        "m_birthday_read": "Street Vault Focus",
        "m_holiday_marathon": "Eiji Rally",
        "m_independence_day": "Unsolved Cases Aegis",
        "m_culture_day": "York Streets Seal Seal",
        "m_spring_equinox": "Banana Fish Marathon Banner Banner",
        "m_earth_day": "Victim Leader Aegis",
        "m_labor_day": "Marathon Seal",
        "m_winter_solstice": "Lead Focus",
        "m_manga_birthday": "Page Ritual",
        "m_every_holiday_reader": "Gang War Watch",
        "m_consecutive_holidays": "Danger Alerts Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Japanese Proof",
        "m_fibonacci": "Leader Dominion",
        "m_palindrome_day": "Noir Relic",
        "m_binary_day": "Weapon Proof",
        "m_full_moon_read": "Unsolved Cases Crown",
        "m_leap_year_read": "Conspiracy Uncovered Practice",
        "m_triple_seven": "Ash Lynx Trial",
        "m_thousand_complete": "Danger Alerts Legend",
        "m_nice": "Leads Seal Seal",
        "m_power_level_chapters": "Leader Aegis Aegis",
        "m_answer_42": "Danger Alerts Aegis",
        "m_square_number": "Gang War Standard Standard",
        "m_prime_count": "Leads Insignia",
        "m_matching_date": "Weapon Mantle",
        "m_century_chapter": "Ash Lynx Crown",
        "m_pi_chapters": "Survival Proof Proof",
        "m_synchronicity": "Lead Emblem",
        "m_world_record": "Japanese Warrant",
        "m_genre_clash": "Fish Marathon Clash",
        "m_time_traveler": "His Decree",
        "m_double_digits": "Lead Dominion Dominion",
        "m_one_two_three": "Noir Warrant",
        "m_lucky_seven": "Victim Leader Pinnacle",
        "m_exact_hundred_ch": "Archive Testament",
        "m_year_match_count": "Archive Routine",
        "m_chapter_match_date": "Street Vault Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Unsolved Cases Index",
        "m_manhwa_format": "Leads Gallery",
        "m_manhua_format": "Danger Alerts Storehouse",
        "m_ln_format": "Case Index",
        "m_oneshot_format": "Lead Index",
        "m_doujin_format": "Street Fan Cabinet",
        "m_novel_format": "Fish Marathon Reserve",
        "m_format_master_manga": "Ash Lynx Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Ash Lynx Link",
        "m_meta_collector": "Ash Lynx Reliquary Reliquary",
        "m_meta_category_starter": "Uncovered Standard",
        "m_meta_tier_climber": "Banana Fish Marathon Token",
        "m_meta_tier_max": "Street Trophies Token",
        "m_meta_xp_earner": "Street Anchor",
        "m_meta_difficulty_easy": "Leader Panel",
        "m_meta_difficulty_hard": "Banana Fish Circle Seal",
        "m_meta_unlock_spree": "Crew Marker",
        "m_meta_completionist": "Banana Fish Marathon Triumph",
        "m_meta_diverse": "York Streets Anchor",
        "m_meta_dominator": "Fish Marathon Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#050200",
        primary: "#845219",
        secondary: "#506080",
        accent: "#e8d0a0",
    },
    particleColor: "#a07030",
    backgroundDim: 0.38,
    backgroundBlur: 22,
    milestoneNames: {
  1: "Threadbare Ash Lynx Spark",
  8: "Dino's Tarnished Form",
  14: "Fractured Child Soldier",
  21: "Street Survival Path",
  28: "Lowborn Foundation Myth",
  35: "Eiji Okumura Pulse",
  41: "Trust's Emotional Soul",
  48: "Humble Banana Mark",
  55: "Ragged Gang Warfare Clash",
  61: "Police's Faint Clash",
  68: "Lesser Max Lobo",
  75: "Ash Tactical Zenith",
  81: "Doubtful Fragmentation Echo",
  88: "Dino Sigil",
  95: "Ash's Identity Form",
  102: "Really Cool Eiji Soul",
  108: "Awakened Banana Fish Secret",
  115: "Underground's Resolute Seal",
  122: "Rising Gang Alliances",
  128: "Emotional Soul",
  135: "Dauntless Manipulation Pulse",
  142: "Ash Control Clash",
  149: "Lab's Fragments Secret",
  155: "Fresh Protection Vow",
  162: "Valiant Psychological Collapse Echo",
  169: "Banana's Prime Crown",
  175: "Polished Political Corruption",
  182: "Eiji Kidnapping Bloom",
  189: "Stormlit Instinct Vow",
  195: "Found Family Vow",
  202: "Trauma's Events Echo",
  209: "Tempered Dino Omen",
  216: "Trusted Survivor Experiment Seal",
  222: "Violence's Steadfast Path",
  229: "Ironclad Dependence",
  236: "New York Clash",
  242: "Core Implication Crest",
  249: "Systemic Abuse Mark",
  256: "Ash's Emotional Soul",
  262: "Formidable Eiji Force",
  269: "Lucid Mafia Control Crown",
  276: "Experiment's Ranked Secret",
  283: "Fabled Ownership Collapse",
  289: "Escape Attempts Sigil",
  296: "Seasoned Legacy Flame",
  303: "Dino Control Spark",
  309: "Banana's Activation Omen",
  316: "Valorous Ash Seal",
  323: "Stalwart Eiji Rescue Vow",
  330: "Alliance's Commanding Form",
  336: "Refined Collapse Trigger",
  343: "Violence Control Crest",
  350: "Blazing Struggle Mark",
  356: "Experiments Secret",
  363: "Escape's Legacy Echo",
  370: "Peerless Eiji Crown",
  376: "Ardent Ash Mental Zenith",
  383: "Banana's Focused Bloom",
  390: "Vigilant Confrontation",
  397: "Emotional Vow",
  403: "Elite Clash Clash",
  410: "Ash Tactical Omen",
  417: "Banana's Collapse Seal",
  423: "Sovereign Freedom Path",
  430: "Regal Emotional Soul",
  437: "Battle's Crowned Clash",
  444: "Mythborn Destruction",
  450: "Ash Injury Mark",
  457: "Radiant Emotional Soul",
  464: "Exposure Secret",
  470: "End's Legacy Crown",
  477: "Climactic Ash Zenith",
  484: "Epic Collapse Criminal Bloom",
  490: "Aftermath's Unreal Sigil",
  497: "Peak Eiji Survival",
  504: "Ash Acceptance Spark",
  511: "Exalted Legacy Omen",
  517: "Systemic Corruption Seal",
  524: "Trauma's Emotional Soul",
  531: "Celestial Fragment Echo",
  537: "Phantom Justice Closure Pulse",
  544: "Survivor's Crimson Crest",
  551: "Silver Ash Lynx",
  557: "Eiji Carrying Soul",
  564: "Feral Legacy Echo",
  571: "Healing Secret",
  578: "Freedom's Legacy Zenith",
  584: "Dread New Echo",
  591: "Luminous Ash Symbolization Sigil",
  598: "Abuse's Thunderous Flame",
  604: "Ultraviolet Fragment",
  611: "Moving Indifference Omen",
  618: "Secret Finalized Seal",
  625: "Justice Failure Path",
  631: "Ash's Legacy Form",
  638: "Worldclass Eiji Echo",
  645: "Lawless Trauma Echo",
  651: "Human's Chosen Secret",
  658: "Fearless Echo",
  665: "Broken Hope Echo",
  671: "Cinematic Legacy Crown",
  678: "Ash Lynx Zenith",
  685: "Survivor's Legacy Bloom",
  692: "Canonized Violence Echo",
  698: "Ascendant Unspoken Goodbye Flame",
  705: "Banana's Transfigured Spark",
  712: "Immortal Human Cost",
  718: "Control Echo",
  725: "Astral Emotional Soul",
  732: "Lost Youth Myth",
  739: "Resolution's Truth Secret",
  745: "Prismatic Eiji Soul",
  752: "Abyssal Ash Symbol Mark",
  759: "World's Unbound Vow",
  765: "Eternal Fragment Continuation",
  772: "Tragedy Ending Crown",
  779: "Transcendent Echo Echo",
  785: "Banana Fish Echo",
  792: "Human's Truth Secret",
  799: "Ultimate Ash Flame",
  806: "Mythic Endless Scar Soul",
  812: "Freedom's Godlike Omen",
  819: "Canonical Love Reach",
  826: "Justice Victory Path",
  832: "Heavenly Legacy Myth",
  839: "Ash Eternal Echo",
  846: "Eiji's Legacy Crest",
  852: "Timeless Broken Mark",
  859: "Empyrean Trauma Cannot Vow",
  866: "Control's Primordial Echo",
  873: "Omniscient Human Cost",
  879: "Memory Echo",
  886: "Apocalyptic Legacy Bloom",
  893: "Fragment Soul",
  899: "Cannot's Legacy Flame",
  906: "Final Banana Echo",
  913: "Crowned Truth Secret",
  920: "Ash's Mythic Seal",
  926: "Absolute Built Broken",
  933: "Eiji Carrying Echo",
  940: "Cosmic Emotional Soul",
  946: "Collapse Lock Echo",
  953: "Closure's Legacy Mark",
  960: "Definitive Ash Form",
  966: "Ultimate Engineered Violence Echo",
  973: "Engineered's Infinite Crown",
  980: "Sovereign Engineered Violence",
  987: "Engineered Violence Bloom",
  993: "Legendary Too Sigil",
  1000: "Ultimate Ash Lynx"
}
}
