import { AnimeThemeConfig } from "./types"
import { GiCoffin, GiTopHat, GiRose, GiDeathSkull, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiCrown } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const blackButlerTheme: AnimeThemeConfig = {
    id: "black-butler",
    displayName: "Black Butler",
    description: "In Victorian England, twelve-year-old Ciel Phantomhive runs the family empire with his infallible butler Sebastian — who is not human, bound to Ciel by a Faustian contract sealed with a demon's mark.",
    fontFamily: "'Cinzel Decorative', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Cinzel+Decorative:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "190 185 210",
        "--color-brand-300": "152 145 190",
        "--color-brand-400": "112 105 168",
        "--color-brand-500": "75 68 145",
        "--color-brand-600": "52 45 118",
        "--color-brand-700": "33 28 90",
        "--color-brand-800": "18 15 62",
        "--color-brand-900": "8 7 36",
        "--color-brand-950": "4 3 20",
        "--brand": "75 68 145",
        "--background": "#010000",
        "--paper": "#060408",
        "--color-gray-950": "1 0 0",
        "--color-gray-900": "6 4 8",
        "--color-gray-800": "12 9 16",
        "--color-gray-700": "22 16 28",
        "--color-gray-600": "36 28 48",
        "--color-gray-500": "58 50 78",
        "--color-gray-400": "90 80 118",
        "--color-gray-300": "130 120 158",
        "--color-gray-200": "168 160 194",
        "--color-gray-100": "200 196 220",
        "--color-gray-50": "232 229 242",
    },
    sidebarOverrides: {
        "home": { icon: GiCoffin, label: "Phantomhive Manor" },
        "schedule": { icon: GiAlarmClock, label: "Master's Schedule" },
        "manga": { icon: LuBookOpen, label: "Phantomhive Files" },
        "lists": { icon: GiTopHat, label: "Servant Registry" },
        "discover": { icon: GiBullseye, label: "Case Scouting" },
        "torrent-list": { icon: GiDeathSkull, label: "Underworld Cache" },
        "debrid": { icon: GiCrown, label: "Queen's Store" },
        "unmatched": { icon: GiRose, label: "Unresolved Cases" },
        "enmasse": { icon: GiResize, label: "Butler Deploy" },
        "scan-summaries": { icon: TbReportSearch, label: "Case Reports" },
        "auto-downloader": { icon: LuRss, label: "Royal Feed" },
        "community": { icon: GiCoffin, label: "Phantomhive Network" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Royal Commands" },
        "achievements": { icon: GiTrophy, label: "Butler Awards" },
        "milestones": { icon: LuFlag, label: "Butler Goals" },
        "theme-manager": { icon: GiPalette, label: "Victorian Colors" },
        "extensions": { icon: BiExtension, label: "Butler Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Manor Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Contract Settings" },
    },
    achievementNames: {
        "a_first_episode": "Contract Sealed",
        "a_first_complete": "Queen's Dog",
        "a_hundred_club": "Hundred Cases",
        "a_time_lord": "Victorian Veteran",
        "a_anime_collector": "Manor Collection",
        "a_library_legend": "Phantomhive Archives",
        "a_binge_king": "Butler Marathon",
        "a_no_sleep": "All-Night Service",
        "a_marathon_runner": "Sebastian's Run",
        "a_speed_run": "Simply One Hell",
        "a_completionist": "All Cases",
        "a_mega_completionist": "Toboso Master",
        "a_loyal_fan": "Ciel's Subject",
        "a_rewatcher": "Manor Revisit",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Demon Battle",
        "a_genre_adventure": "Victorian Journey",
        "a_genre_comedy": "Servants' Failure",
        "a_genre_drama": "Ciel's Past",
        "a_genre_fantasy": "Demon World",
        "a_genre_horror": "Faustian Terror",
        "a_genre_romance": "Sebastian Intrigue",
        "a_genre_scifi": "Victorian Science",
        "a_genre_supernatural": "Demon Power",
        "a_genre_psychological": "Ciel's Revenge",
        "a_genre_mecha": "None Here",
        "a_critic": "Butler Judge",
        "a_perfect_ten": "Simply Perfect",
        "a_harsh_critic": "Sebastian's Standard",
        "a_daily_streak": "Daily Service",
        "a_mega_streak": "Endless Service",
        "a_year_long": "Victorian Year",
        "a_iron_will": "Ciel's Revenge",
        "a_hidden_gem": "Hidden Case",
        "a_cult_classic": "Toboso Classic",
        "a_classic_connoisseur": "2006 Fan",
        "a_new_years_resolution": "New Year Ball",
        "a_christmas_special": "Victorian Christmas",
        "a_meta_tier_max": "Phantomhive Head",
        "a_meta_completionist": "All Arcs",
        "a_sequel_chain": "Season 2",
        "a_zero_to_hero": "Victim to Earl",
        "a_night_owl": "Night Service",
        "a_early_bird": "Morning Butler",
        "m_first_chapter": "First Case",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Butler Marathon",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Black Butler Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Manor Return",
        "m_genre_action": "Demon Chapter",
        "m_genre_adventure": "Case Chapter",
        "m_genre_romance": "Sebastian Chapter",
        "m_genre_fantasy": "Dark Chapter",
        "m_genre_horror": "Horror Chapter",
        "m_genre_drama": "Past Chapter",
        "m_genre_scifi": "Victorian Chapter",
        "m_genre_supernatural": "Contract Chapter",
        "m_genre_psychological": "Revenge Depth",
        "m_critic": "Case Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Service Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Earl's Resolve",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Victorian Classic",
        "m_mangaka_lover": "Toboso Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Black Butler Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Victorian Art",
        "m_manga_to_anime": "Manga Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#010000",
        primary: "#4b4491",
        secondary: "#342d76",
        accent: "#e0c060",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/black-butler.jpg",
    particleColor: "#6058b0",
    backgroundDim: 0.42,
    backgroundBlur: 22,
    particleTypes: {
        roses: { label: "Black Roses", maxCount: 15, defaultEnabled: true, defaultIntensity: 55 },
        feathers: { label: "Demon Feathers", maxCount: 12, defaultEnabled: true, defaultIntensity: 50 },
    },
    milestoneNames: {
    1:    "Ciel Phantomhive Aristocratic Tragedy",
    8:    "Phantomhive Estate Collapse Event",
    15:   "Family Murder Incident Awakening",
    22:   "Pact With Demon Formation",
    29:   "Sebastian Michaelis Contract Binding",

    36:   "Vengeance Directive Establishment",
    43:   "Queen’s Watchdog Appointment",
    50:   "Demon Butler Integration Phase",
    57:   "London Criminal Underworld Exposure",
    64:   "Contract Seal Stabilization",

    71:   "Phantomhive Investigation Authority",
    78:   "Sebastian Absolute Servitude Display",
    85:   "Ciel Emotional Suppression Growth",
    92:   "Supernatural Case Investigations Begin",
    99:   "Dual Identity Formation",

    106:  "Aristocratic Power Manipulation",
    113:  "Demonic Efficiency Revelation",
    120:  "Undertaker Mystery Encounter",
    127:  "Shinigami Realm Awareness",
    134:  "Contract Bound Existence Pressure",

    141:  "Public Aristocracy vs Underground Crime",
    148:  "Sebastian Combat Capability Display",
    155:  "Ciel Strategic Mastery Growth",
    162:  "London Occult Activity Expansion",
    169:  "Emotional Isolation Deepening",

    176:  "Phantomhive Enemy Networks",
    183:  "Demon Servant Nature Hint",
    190:  "Revenge Path Reinforcement",
    197:  "Grim Reaper Bureau Exposure",
    204:  "Contract Obedience Absolute Rule",

    211:  "Circus Arc Psychological Collapse",
    218:  "Human Corruption Exposure",
    225:  "Sebastian Predator Nature Reveal",
    232:  "Ciel Trauma Reinforcement Cycle",
    239:  "Justice Through Manipulation",

    246:  "Luxury vs Horror Contrast Arc",
    253:  "Underground Ritual Investigations",
    260:  "Shinigami Intervention Events",
    267:  "Demon vs Reaper Conflict Layer",
    274:  "Contract Power Balance Stability",

    281:  "Ciel Emotional Fracture Signs",
    288:  "Sebastian Absolute Control Display",
    295:  "Human Morality Deconstruction",
    302:  "Aristocratic Reputation Expansion",
    309:  "Revenge Obsession Intensifies",

    316:  "Public Enemy Manipulation Arc",
    323:  "Demonic Servitude Questioning",
    330:  "Shinigami Record Revelation",
    337:  "Ciel Psychological Burden Peak",
    344:  "Contract Purpose Reflection",

    351:  "Black Butler Myth Formation",
    358:  "Supernatural London Integration",
    365:  "Sebastian Combat Perfection Display",
    372:  "Ciel Strategic Coldness Peak",
    379:  "World Hidden Layer Exposure",

    386:  "Phantomhive Political Influence",
    393:  "Demonic Identity Contrast",
    400:  "Turning Point of Contract Meaning",

    407:  "Ciel Revenge Fulfillment Pressure",
    414:  "Sebastian Loyalty Paradox",
    421:  "Shinigami Observation Expansion",
    428:  "Human Soul Value Questioning",
    435:  "Contract Binding Deepest Layer",

    442:  "Aristocracy Corruption Collapse",
    449:  "Demonic Consumption Implication",
    456:  "Ciel Emotional Detachment Peak",
    463:  "Sebastian True Nature Hint",
    470:  "Turning Point of Servitude Truth",

    477:  "Final Investigation Arc Setup",
    484:  "Ciel vs Fate Conflict",
    491:  "Demon Contract Instability Signs",
    498:  "Reaper Observation Peak",
    505:  "Truth of Phantomhive Bloodline",

    512:  "Sebastian Devouring Nature Risk",
    519:  "Ciel Identity Fracture Pressure",
    526:  "London Supernatural Convergence",
    533:  "Contract End Condition Awareness",
    540:  "Revenge Cycle Completion Threat",

    547:  "Final Aristocratic Operation",
    554:  "Shinigami Intervention Conflict",
    561:  "Demonic Power Exposure Peak",
    568:  "Ciel Emotional Collapse Risk",
    575:  "Sebastian Absolute Compliance Phase",

    582:  "Contract Fulfillment Crisis",
    589:  "Human Soul Ownership Question",
    596:  "Phantomhive Legacy Burden",
    603:  "Turning Point of Identity Loss",

    610:  "Endgame Investigation Arc",
    617:  "Sebastian Predatory Instinct Emergence",
    624:  "Ciel Revenge Finalization Attempt",
    631:  "Shinigami Judgment Awareness",
    638:  "Contract Final Clause Pressure",

    645:  "Demon vs Human Boundary Collapse",
    652:  "Aristocratic System Breakdown",
    659:  "Ciel Emotional Void Deepening",
    666:  "Sebastian True Form Echo",

    673:  "Black Butler Myth Completion",
    680:  "Contract Absolute Binding State",
    687:  "Reaper Observation Full Attention",
    694:  "Ciel Identity Locked State",

    701:  "Final Revenge Execution Path",
    708:  "Demonic Consumption Threat",
    715:  "Human Soul vs Contract Balance",
    722:  "Sebastian End Condition Approaching",
    729:  "Ciel Final Will Declaration",

    736:  "Contract Fate Convergence",
    743:  "London Supernatural Collapse Point",
    750:  "Identity vs Ownership Final Clash",
    757:  "Sebastian Absolute Obedience Peak",
    764:  "Ciel Emotional Finalization",

    771:  "Reaper Judgment Imminent",
    778:  "Demon Contract Finalization Risk",
    785:  "Phantomhive Legacy Completion",
    792:  "Humanity Within Contract Question",

    799:  "End of Aristocratic Order Cycle",
    806:  "Sebastian Eternal Servitude Concept",
    813:  "Ciel Fate Locked Path",
    820:  "Demonic Truth Exposure Complete",
    827:  "Contract Beyond Morality",

    834:  "Final Human-Demon Exchange",
    841:  "Soul Ownership Resolution",
    848:  "Shinigami Record Closure",
    855:  "Ciel Absolute Command State",
    862:  "Sebastian Predation Suppressed",

    869:  "Beyond Revenge Identity",
    876:  "Contract as Existence Law",
    883:  "Black Butler Eternal Role",
    890:  "Human Emotion Suppression Peak",
    897:  "Demonic Purpose Fulfilled",

    904:  "Absolute Contract Binding",
    911:  "Final Aristocratic Memory",
    918:  "Sebastian Timeless Servant",
    925:  "Ciel End Condition Awareness",
    932:  "London Mythological Integration",

    939:  "Identity Fully Contracted",
    946:  "Beyond Human Morality",
    953:  "Demon Butler Eternal Form",
    960:  "Revenge Cycle Transcendence",
    967:  "Contracted Existence Permanence",

    974:  "Absolute Servitude Reality",
    981:  "Ciel Final Aristocrat State",
    988:  "Sebastian Beyond Demon Form",
    995:  "Perfect Contract Existence",
    998:  "Absolute Black Butler State",
    1000:"A Boy Who Sold His Soul for Revenge Became the Master of a Demon Who Could Grant It, Only to Realize That Every Step Toward Justice Was Also a Step Deeper Into a Contract That Would Never Truly End"
}
}
