import { AnimeThemeConfig } from "./types"
import { GiPaintBrush, GiPalette, GiEasel, GiPencil, GiTrophy, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiInspiration, GiArtificialIntelligence, GiHeartKey, GiOpenBook } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const bluePeriodTheme: AnimeThemeConfig = {
    id: "blue-period",
    displayName: "Blue Period",
    description: "Yatora Yaguchi is an excellent student with an empty life — until a single blue painting cracks him open and ignites a consuming passion for art. His desperate pursuit of Tokyo University of the Arts is a visceral portrait of obsession and creative suffering.",
    fontFamily: "'Crimson Text', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Crimson+Text:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "168 196 255",
        "--color-brand-300": "118 158 248",
        "--color-brand-400": "70 118 232",
        "--color-brand-500": "32 80 208",
        "--color-brand-600": "12 52 168",
        "--color-brand-700": "4 30 126",
        "--color-brand-800": "0 14 80",
        "--color-brand-900": "0 6 42",
        "--color-brand-950": "0 2 14",
        "--brand": "32 80 208",
        "--background": "#000208",
        "--paper": "#000410",
        "--color-gray-950": "0 2 8",
        "--color-gray-900": "2 5 16",
        "--color-gray-800": "4 10 28",
        "--color-gray-700": "8 18 46",
        "--color-gray-600": "14 32 72",
        "--color-gray-500": "26 56 110",
        "--color-gray-400": "48 88 150",
        "--color-gray-300": "80 126 190",
        "--color-gray-200": "120 164 220",
        "--color-gray-100": "168 200 240",
        "--color-gray-50": "220 236 252",
    },
    sidebarOverrides: {
        "home": { icon: GiEasel, label: "Studio" },
        "schedule": { icon: GiAlarmClock, label: "Art Schedule" },
        "manga": { icon: LuBookOpen, label: "Artist's Journal" },
        "lists": { icon: GiFlowerEmblem, label: "Inspirations" },
        "discover": { icon: GiBullseye, label: "New Works" },
        "torrent-list": { icon: GiPaintBrush, label: "Canvas Cache" },
        "debrid": { icon: GiOpenBook, label: "Art Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Works" },
        "enmasse": { icon: GiResize, label: "Studio Ops" },
        "scan-summaries": { icon: TbReportSearch, label: "Art Reports" },
        "auto-downloader": { icon: LuRss, label: "Art News" },
        "community": { icon: GiInspiration, label: "Artist Circle" },
        "achievements": { icon: GiTrophy, label: "Art Trophies" },
        "milestones": { icon: LuFlag, label: "Creative Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Studio Alerts" },
        "theme-manager": { icon: GiPalette, label: "Blue Palette" },
        "extensions": { icon: BiExtension, label: "Art Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Canvas Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Yatora's Config" },
    },
    achievementNames: {
        "a_first_episode": "Blue Revelation",
        "a_first_complete": "Art Complete",
        "a_hundred_club": "Hundred Pieces",
        "a_time_lord": "Art Master",
        "a_anime_collector": "Art Archive",
        "a_library_legend": "Blue Library",
        "a_binge_king": "Art Marathon",
        "a_no_sleep": "All-Night Canvas",
        "a_marathon_runner": "Yatora's Run",
        "a_speed_run": "Brush Speed",
        "a_completionist": "Full Blue Period",
        "a_mega_completionist": "TUA Graduate",
        "a_loyal_fan": "Devoted Fan",
        "a_rewatcher": "Blue Again",
        "a_decade_watcher": "Decade Artist",
        "a_genre_action": "None Here",
        "a_genre_adventure": "Art Journey",
        "a_genre_comedy": "None Here",
        "a_genre_drama": "Blue Drama",
        "a_genre_fantasy": "None Here",
        "a_genre_horror": "None Here",
        "a_genre_romance": "None Here",
        "a_genre_scifi": "None Here",
        "a_genre_supernatural": "None Here",
        "a_genre_psychological": "Yatora's Mind",
        "a_genre_mecha": "None Here",
        "a_critic": "Art Critic",
        "a_perfect_ten": "Perfect Canvas",
        "a_harsh_critic": "TUA Standard",
        "a_daily_streak": "Daily Study",
        "a_mega_streak": "Blue Streak",
        "a_year_long": "Year of Art",
        "a_iron_will": "Artist's Will",
        "a_hidden_gem": "Hidden Color",
        "a_cult_classic": "Art Classic",
        "a_classic_connoisseur": "2020 Fan",
        "a_new_years_resolution": "New Year Canvas",
        "a_christmas_special": "Winter Blue",
        "a_meta_tier_max": "True Artist",
        "a_meta_completionist": "All Blue",
        "a_sequel_chain": "Blue Chain",
        "a_zero_to_hero": "Late Bloomer",
        "a_night_owl": "Night Canvas",
        "a_early_bird": "Dawn Brush",
        "m_first_chapter": "First Brushstroke",
        "m_first_complete": "Blue Arc",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Art Binge",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Art Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Blue Again",
        "m_genre_action": "None Here",
        "m_genre_adventure": "Journey Chapter",
        "m_genre_romance": "None Here",
        "m_genre_fantasy": "None Here",
        "m_genre_horror": "None Here",
        "m_genre_drama": "Drama Chapter",
        "m_genre_scifi": "None Here",
        "m_genre_supernatural": "None Here",
        "m_genre_psychological": "Mind Chapter",
        "m_critic": "Blue Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Blue Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Iron Brush",
        "m_hidden_gem": "Hidden Canvas",
        "m_cult_classic": "Classic Blue",
        "m_mangaka_lover": "Yamaguchi Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Blue Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "True Appreciator",
        "m_manga_to_anime": "Adapted Blue",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#000208",
        primary: "#2050d0",
        secondary: "#1030a0",
        accent: "#d8c8a8",
    },
    particleColor: "#4070e0",
    backgroundDim: 0.28,
    backgroundBlur: 18,
    particleTypes: {
        blue_sparks: { label: "Paint Particles", maxCount: 14, defaultEnabled: true, defaultIntensity: 50 },
        snow_particles: { label: "Canvas Dust", maxCount: 10, defaultEnabled: true, defaultIntensity: 35 },
    },
    milestoneNames: {
    1:    "Yatora Yaguchi High School Apathy Phase",
    8:    "Empty Success Through Surface Talent",
    15:   "Art Room Chance Observation",
    22:   "Shibuya Landscape Painting Spark",
    29:   "First Emotional Artistic Response",

    36:   "Art Club Entry Decision",
    43:   "Fundamental Drawing Skill Gap Realization",
    50:   "Copying vs Expression Conflict Begins",
    57:   "Observation Discipline Awakening",
    64:   "First Sketch Study Obsession",

    71:   "Art School Goal Formation",
    78:   "Peer Comparison Pressure Growth",
    85:   "Technical Skill Foundation Struggle",
    92:   "Self Doubt in Creativity",
    99:   "Art as Career Idea Takes Hold",

    106:  "Intensive Practice Schedule Begins",
    113:  "Color Theory Introduction Struggle",
    120:  "Perspective and Structure Learning",
    127:  "Yaguchi Identity Shift Begins",
    134:  "Art Competition Awareness",

    141:  "Tsubasa Yamaguchi Influence Exposure",
    148:  "Rival Art Student Recognition",
    155:  "Creative Burnout Early Signs",
    162:  "Technique vs Emotion Conflict",
    169:  "First Portfolio Attempt",

    176:  "Art School Entrance Exam Pressure",
    183:  "Failure and Reattempt Cycle",
    190:  "Art Critique Emotional Impact",
    197:  "Teacher Guidance Awakening",
    204:  "Personal Style Uncertainty",

    211:  "Acceptance into Art University Goal",
    218:  "Studio Practice Intensity Increase",
    225:  "Peer Competition Environment",
    232:  "Art as Identity Questioning",
    239:  "Emotional Vulnerability Through Art",

    246:  "Color Expression Breakthrough Attempts",
    253:  "Self Comparison to Masters",
    260:  "Creative Block Encounter",
    267:  "Relearning Basics Phase",
    274:  "Art as Communication Realization",

    281:  "Exam Preparation Mental Pressure",
    288:  "Late Night Practice Cycles",
    295:  "Emotional Expression Through Canvas",
    302:  "Skill vs Vision Gap Awareness",
    309:  "Support System Importance",

    316:  "Art School Entrance Exam Arc",
    323:  "Performance Under Evaluation Stress",
    330:  "Expression vs Accuracy Conflict",
    337:  "Failure Acceptance Growth",
    344:  "Art Identity Solidifying",

    351:  "Acceptance into Tokyo Art University",
    358:  "New Environment Shock Phase",
    365:  "High-Level Peer Exposure",
    372:  "Creative Insecurity Intensifies",
    379:  "Art Freedom vs Pressure",

    386:  "Specialized Studio Assignment",
    393:  "Advanced Technique Learning",
    400:  "Turning Point of Artistic Identity",

    407:  "Mentor Feedback Deep Impact",
    414:  "Personal Style Fragmentation",
    421:  "Artistic Voice Search Begins",
    428:  "Creative Frustration Peak",
    435:  "Comparison to Genius Students",

    442:  "Art Exhibition Preparation",
    449:  "Critique Panel Pressure",
    456:  "Emotional Art Expression Attempt",
    463:  "Technical Mastery vs Feeling",
    470:  "Turning Point of Expression",

    477:  "Public Exhibition Experience",
    484:  "Viewer Interpretation Shock",
    491:  "Art Communication Realization",
    498:  "Self Doubt After Exposure",
    505:  "Art Identity Reassessment",

    512:  "Creative Burnout Crisis",
    519:  "Return to Fundamentals",
    526:  "Relearning Observation Depth",
    533:  "Emotion as Artistic Core",
    540:  "Art Purpose Redefinition",

    547:  "Peer Rival Development",
    554:  "Technical Skill Refinement",
    561:  "Emotional Expression Clarity",
    568:  "Criticism Acceptance Growth",
    575:  "Art as Self Exploration",

    582:  "Second Major Project Arc",
    589:  "Complex Composition Challenges",
    596:  "Creative Confidence Rebuild",
    603:  "Artistic Voice Stabilization",

    610:  "University Competition Phase",
    617:  "Time Pressure Artistic Output",
    624:  "Concept vs Execution Balance",
    631:  "Peer Recognition Growth",
    638:  "Artistic Maturity Formation",

    645:  "Exhibition Success Attempt",
    652:  "Emotional Expression Climax",
    659:  "Creative Identity Strengthening",
    666:  "Skill and Emotion Harmony",

    673:  "Art Career Path Consideration",
    680:  "Long Term Creative Vision",
    687:  "Self Acceptance Through Art",
    694:  "Mentor Validation Moment",

    701:  "Final University Evaluation Arc",
    708:  "Artistic Philosophy Solidification",
    715:  "Creative Independence Growth",
    722:  "Identity Beyond Student Artist",
    729:  "Expression Without Fear",

    736:  "Art World Entry Preparation",
    743:  "Portfolio Finalization",
    750:  "Creative Confidence Peak",

    757:  "Professional Art Threshold",
    764:  "Art as Lifelong Discipline",
    771:  "Emotional Art Mastery",
    778:  "Style and Voice Fusion",

    785:  "Post-Education Transition",
    792:  "Art Identity Fully Formed",

    799:  "Creative Life Commitment",
    806:  "Art Beyond Evaluation",
    813:  "Expression as Existence",
    820:  "Independent Artist Emergence",

    827:  "Yaguchi Fully Realized Artist",
    834:  "Artistic Fear Dissolution",
    841:  "Creative Freedom Mastery",
    848:  "Self Expression Clarity",
    855:  "Art as Emotional Language",

    862:  "Beyond Academic Art System",
    869:  "Personal Vision Fully Defined",
    876:  "Art Without Comparison",
    883:  "Expression as Identity",

    890:  "Final Artistic Philosophy",
    897:  "Creative Self Acceptance",
    904:  "Artistic Life Continuation",

    911:  "Beyond Talent and Skill",
    918:  "Expression Without Fear of Judgment",
    925:  "Art as Pure Communication",
    932:  "Identity Fully Expressed",

    939:  "Creative Soul Stabilization",
    946:  "Art Beyond Structure",
    953:  "Final Expression Freedom",
    960:  "Art as Living Experience",

    967:  "Beyond Success or Failure",
    974:  "Absolute Artistic Clarity",
    981:  "Perfect Expression State",
    988:  "Beyond Technique and Emotion",
    995:  "Complete Creative Identity",
    998:  "Perfect Blue Period State",
    1000:"A Student Who Once Saw Art as Just Another Goal Discovered That True Creation Was Not About Talent or Approval, but About Struggling Through Doubt and Fear Until Expression Became the Only Way He Knew How to Exist"
}
}
