import { AnimeThemeConfig } from "./types"
import { GiRunningShoe, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiCrystalBall, GiStarSwirl, GiRoad } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const captainTsubasaTheme: AnimeThemeConfig = {
    id: "captain-tsubasa",
    displayName: "Captain Tsubasa",
    description: "Tsubasa Ozora's dream is to win the World Cup for Japan. With the ball as his best friend, he overcomes rivals across Japan and the world through tireless effort and breathtaking technique.",
    cssVars: {
        "--color-brand-200": "175 210 255",
        "--color-brand-300": "115 168 248",
        "--color-brand-400": "62 120 235",
        "--color-brand-500": "22 80 205",
        "--color-brand-600": "6 52 165",
        "--color-brand-700": "2 30 120",
        "--color-brand-800": "0 14 75",
        "--color-brand-900": "0 5 40",
        "--color-brand-950": "0 2 18",
        "--brand": "22 80 205",
        "--background": "#000208",
        "--paper": "#000410",
        "--color-gray-950": "0 2 8",
        "--color-gray-900": "2 6 18",
        "--color-gray-800": "4 14 35",
        "--color-gray-700": "8 26 58",
        "--color-gray-600": "14 46 90",
        "--color-gray-500": "24 75 130",
        "--color-gray-400": "45 115 168",
        "--color-gray-300": "80 155 205",
        "--color-gray-200": "125 192 232",
        "--color-gray-100": "178 220 248",
        "--color-gray-50": "225 242 255",
    },
    sidebarOverrides: {
        "home": { icon: GiRunningShoe, label: "Nankatsu Field" },
        "schedule": { icon: GiAlarmClock, label: "Match Schedule" },
        "manga": { icon: LuBookOpen, label: "Training Manual" },
        "lists": { icon: GiScrollUnfurled, label: "Team Roster" },
        "discover": { icon: GiBullseye, label: "New Rivals" },
        "torrent-list": { icon: GiRoad, label: "Ball Cache" },
        "debrid": { icon: GiHeartKey, label: "World Cup Vault" },
        "unmatched": { icon: GiCrystalBall, label: "Unmatched Files" },
        "enmasse": { icon: GiResize, label: "World Stage" },
        "scan-summaries": { icon: TbReportSearch, label: "Match Reports" },
        "auto-downloader": { icon: LuRss, label: "Scout Feed" },
        "community": { icon: GiStarSwirl, label: "Japan Circle" },
        "achievements": { icon: GiTrophyCup, label: "World Cup Trophies" },
        "milestones": { icon: LuFlag, label: "Dream Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Match Alerts" },
        "theme-manager": { icon: GiPalette, label: "Japan Colors" },
        "extensions": { icon: BiExtension, label: "Football Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "World Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Tsubasa Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Kick",
        "a_episode_counter": "Village Mark",
        "a_episode_titan": "World Relic",
        "a_hours_invested": "Cup Hero Proof",
        "a_time_lord": "Village Kid Decree",
        "a_anime_collector": "Tsubasa Ozora's Catalogue",
        "a_library_legend": "Faithful Library",
        "a_first_complete": "First Victory",
        "a_hundred_club": "Hundred Goals",
        "a_first_day": "World Cup Trophies Seal",
        "a_first_rating": "Victory Appraisal",
        "a_ten_thousand_min": "Cup Hero Standard",
        "a_season_veteran": "Dribble Library",
        "a_year_explorer": "Rivals Map",
        "a_century_watcher": "Captain Tsubasa Ledger",
        "a_five_hundred_eps": "Captain Tsubasa Dominion",
        "a_thousand_eps": "Tsubasa Marathon Record",
        "a_watching_ten": "Football Acclaim",
        "a_ptw_hoarder": "Village Library",
        "a_dropped_honesty": "World Summit",
        "a_five_thousand_eps": "Scout Warrant",
        "a_ten_completed": "Kick Afterglow",
        "a_fifty_completed": "National Ascension",
        "a_five_hundred_completed": "Hero Clear",
        "a_mean_score_tracker": "Training Manual Verdict",
        "a_unique_studios": "Village Kid Collection",
        "a_days_spent_watching": "Star Dominion",
        "a_all_status": "Technique Testament",
        "a_first_favorite": "Village Kid Cabinet",
        "a_favorites_collector": "Star Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Technique Drive",
        "a_marathon_runner": "Cup Hero Gauntlet",
        "a_weekend_warrior": "Kid World Ordeal",
        "a_non_stop": "Village Fever",
        "a_one_more_episode": "Rivals Mantle",
        "a_speed_run": "Nankatsu Field Vigil",
        "a_double_feature": "Village Kid Crown",
        "a_triple_threat": "Kick Record",
        "a_five_a_day": "Archive Accord",
        "a_back_to_back": "National Surge",
        "a_seasonal_binge": "World Cup Cascade",
        "a_cour_crusher": "Star Ordeal",
        "a_half_day_watch": "Kid World Crown",
        "a_full_day_watch": "Ball Pinnacle",
        "a_power_weekend": "Team Roster Run",
        "a_binge_king": "Tsubasa Marathon",
        "a_no_sleep": "Training Manual Vigil",
        "a_entire_season": "Match Alerts Library",
        "a_seven_day_challenge": "Village Kid Mark",
        "a_hundred_day_binge": "Cup Hero Surge",
        "a_genre_binge": "Japan Binge",
        "a_studio_binge": "Japan Circle Fever",
        "a_season_sweep": "National Champion Codex",
        "a_forty_eight_hour": "Cup Hero Overture",
        "a_ep_counter_day": "Kick Aegis",
        "a_multi_series_binge": "World Cup Trophies Streak",
        "a_midnight_binge": "Scout Cascade",
        "a_new_year_binge": "Dream Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Nankatsu Field Action",
        "a_genre_adventure": "Star Adventure",
        "a_genre_comedy": "Ball Comedy",
        "a_genre_drama": "World Star Drama",
        "a_genre_fantasy": "Kick Fantasy",
        "a_genre_horror": "Tsubasa Marathon Horror",
        "a_genre_mystery": "World Cup Vault Mystery",
        "a_genre_romance": "Technique Romance",
        "a_genre_scifi": "Training Manual Sci-Fi",
        "a_genre_sol": "Champion Slice",
        "a_genre_sports": "Hero Sports",
        "a_genre_supernatural": "Champion Supernatural",
        "a_genre_thriller": "Archive Thriller",
        "a_genre_mecha": "Tsubasa Mecha",
        "a_genre_music": "Star Music",
        "a_genre_psychological": "Football Faithful Psychological",
        "a_genre_ecchi": "Village Ecchi",
        "a_genre_mahou_shoujo": "Captain Tsubasa Magic Shoujo",
        "a_tag_isekai": "Star Isekai",
        "a_tag_harem": "Football Harem",
        "a_tag_bl": "World Cup Trophies Bl",
        "a_tag_gl": "Tsubasa Ozora's Gl",
        "a_tag_historical": "Scout Historical",
        "a_tag_military": "Training Manual Military",
        "a_tag_school": "Archive School",
        "a_tag_martial_arts": "Faithful Martial Arts",
        "a_tag_vampire": "Tsubasa Ozora's Vampire",
        "a_tag_samurai": "Victory Samurai",
        "a_tag_space": "Dribble Space",
        "a_tag_parody": "World Cup Parody",
        "a_tag_idol": "Kick Idol",
        "a_tag_post_apocalyptic": "Tsubasa Ozora's Post Apocalyptic",
        "a_tag_cyberpunk": "Cup Hero Cyberpunk",
        "a_tag_shounen": "World Cup Shounen",
        "a_tag_seinen": "Rivals Seinen",
        "a_tag_shoujo": "Archive Shoujo",
        "a_tag_josei": "Technique Archive Josei",
        "a_tag_survival": "World Star Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "National Champion",
        "a_mega_completionist": "World Cup Hero",
        "a_completion_rate_50": "Marathon Return",
        "a_completion_rate_75": "Village Kid Crown Crown",
        "a_completion_rate_90": "Hero Resolution",
        "a_no_drop": "Kid World Decree",
        "a_long_runner_complete": "World Clear",
        "a_sequel_chain": "World Cup Hero Insignia",
        "a_clean_list": "World Cup Vault Relic",
        "a_from_ptw": "Marathon Index",
        "a_rewatch_master": "Captain Tsubasa Return",
        "a_short_complete": "World Cup Trophies Endgame",
        "a_same_day_start_finish": "Training Manual Pinnacle",
        "a_revival": "Scout Insignia",
        "a_zero_to_hero": "Village Kid to World Star",
        "a_five_genre_complete": "World A Five Genre Complete",
        "a_full_franchise": "Dribble Chronicle",
        "a_batch_complete": "Faithful Crown",
        "a_paused_to_done": "Star Aegis",
        "a_completion_spree": "Match Triumph",
        "a_multi_rewatch": "Tsubasa Marathon Triumph",
        "a_dropped_recovery": "Nankatsu Field Conquest",
        "a_ten_perfect_scores": "World Cup Hero Acclaim",
        "a_seasonal_clear": "Technique Archive Codex",
        "a_complete_genre_span": "Captain Tsubasa A Complete Genre",
        "a_monthly_completions": "Victory Afterglow",
        "a_yearly_completions": "World Cup Hero Epilogue",
        "a_rapid_complete": "World Cup Trophies Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Football Faithful",
        "a_studio_devotee": "Dribble Treasury",
        "a_rewatcher": "Hero Closure",
        "a_triple_rewatch": "Kick Coda",
        "a_annual_tradition": "Faithful Proof",
        "a_director_fan": "Faithful Trial",
        "a_voice_actor_fan": "Technique Archive Crown",
        "a_ost_lover": "World Cup Vault Seal",
        "a_source_reader": "Kick Cabinet",
        "a_waiting_weekly": "Star Clock",
        "a_childhood_revisit": "Marathon Seal",
        "a_saga_tracker": "Champion Standard",
        "a_genre_loyalty": "National Loyalty",
        "a_decade_watcher": "Japan Circle Banner",
        "a_adaptation_hunter": "Village Trial",
        "a_original_anime_fan": "Japan Testament",
        "a_long_commitment": "World Cup Hero Mark",
        "a_perfect_attendance": "Kid World Standard",
        "a_favorite_studio_5": "Star Library",
        "a_complete_catalog": "Unmatched Seal",
        "a_franchise_collector": "National Champion Archive",
        "a_airing_follower": "Archive Signal",
        "a_genre_master": "World Cup Master",
        "a_staff_follower": "Marathon Oath",
        "a_multi_season_fan": "World Hoard",
        "a_format_diversity": "Champion Cache",
        "a_year_dedication": "Tsubasa Marathon Tenure",
        "a_season_dedication": "Dribble Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Training Manual Explorer",
        "a_studio_hopper": "World Cup Collection",
        "a_tag_explorer": "Archive Explorer",
        "a_decade_hopper": "Champion Chronicle",
        "a_hidden_gem": "Match Alerts Warrant",
        "a_popular_taste": "Match Alerts Decree",
        "a_retro_appreciator": "World Cup Vault Aegis",
        "a_modern_viewer": "National Pinnacle",
        "a_cross_demographic": "Village Pinnacle",
        "a_underdog_fan": "Match Alerts Trial",
        "a_variety_week": "Rivals Horizon",
        "a_foreign_cinema": "Nankatsu Field Expedition",
        "a_classic_connoisseur": "Dream Glimpse",
        "a_every_season": "Match Archive",
        "a_award_winner": "World Star Insignia",
        "a_niche_explorer": "Technique Archive Horizon",
        "a_global_anime": "Captain Tsubasa Crown",
        "a_cult_classic": "World Cup Trophies Map",
        "a_random_pick": "Kid World Decree Decree",
        "a_new_genre_month": "Technique Archive A New Genre",
        "a_seasonal_completionist": "Archive Summit",
        "a_unpopular_opinion": "Japan Circle Standard",
        "a_top_rated_viewer": "World Cup Hero Seal",
        "a_source_variety": "Ball Storehouse",
        "a_low_score_brave": "Japan Circle Measure",
        "a_upcoming_watcher": "Captain Tsubasa Seal",
        "a_short_series_explorer": "Village Expedition",
        "a_long_series_explorer": "Tsubasa Ozora's Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Victory Insignia",
        "a_early_bird": "World Banner",
        "a_lunch_break": "Technique Archive Trial",
        "a_golden_hour": "Faithful Tenure",
        "a_four_am_club": "National Champion Gathering",
        "a_witching_hour": "Archive Tenure",
        "a_new_year_watch": "Japan Circle Season",
        "a_midnight_premiere": "Nankatsu Field Devotion",
        "a_all_hours": "Japan Circle Seal",
        "a_dawn_warrior": "Champion Aegis",
        "a_afternoon_delight": "Nankatsu Field Proof",
        "a_prime_time": "Faithful Insignia",
        "a_workday_watcher": "Japan Pinnacle",
        "a_sunday_marathon": "Tsubasa Momentum",
        "a_rainy_day": "World Relic Relic",
        "a_morning_routine": "Star Promise",
        "a_night_shift": "National Aegis",
        "a_twilight_zone": "Marathon Ledger",
        "a_seasonal_premier": "Scout Cabinet",
        "a_clock_collector": "Japan Circle Repository",
        "a_weekend_binge_hours": "World Cup Vault Streak",
        "a_late_night_regular": "Tsubasa Dominion",
        "a_sunrise_watcher": "Dribble Ledger",
        "a_holiday_watcher": "Football Faithful Pact",
        "a_every_day_of_week": "World Ledger",
        "a_monthly_hours": "Victory Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "World Cup Hero Record",
        "a_party_host": "Dribble Record",
        "a_social_butterfly": "Kick Company",
        "a_group_binge": "World Sprint",
        "a_party_regular": "World Cup Chronicle",
        "a_sync_viewer": "Rivals Standard",
        "a_commentator": "World Cup Vault Record",
        "a_party_marathon": "Cup Hero Vigil",
        "a_full_house": "Technique Archive Trial Trial",
        "a_community_pillar": "Captain Tsubasa Alliance",
        "a_watch_party_streak": "World Star Vigil",
        "a_diverse_party": "Rivals Seal",
        "a_late_night_party": "Team Roster Testament",
        "a_party_veteran": "Captain Tsubasa Testament",
        "a_genre_party": "World Cup Party",
        "a_weekly_party": "Japan Circle Calendar",
        "a_silent_viewer": "World Cup Hero Mantle",
        "a_recommendation_giver": "Marathon Network",
        "a_party_completionist": "World Cup Hero Coda",
        "a_social_scorer": "National Champion Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Team Roster Proof",
        "a_fibonacci": "Tsubasa Marathon Dominion",
        "a_palindrome_day": "Football Faithful Relic",
        "a_binary_day": "National Mark",
        "a_full_moon": "World Star Insignia Insignia",
        "a_leap_year": "Football Faithful Devotion",
        "a_time_traveler": "Champion Record",
        "a_genre_clash": "Marathon Clash",
        "a_triple_seven": "Football Testament",
        "a_thousand_complete": "Scout Epilogue",
        "a_pi_episodes": "Kid World Crown Crown",
        "a_synchronicity": "Rivals Anchor",
        "a_world_record": "World Star Warrant",
        "a_nice": "Football Chronicle",
        "a_power_level": "Rivals Testament",
        "a_answer_42": "World Cup Standard",
        "a_square_number": "Tsubasa Ozora's Decree",
        "a_prime_count": "Football Seal",
        "a_matching_date": "Marathon Mantle",
        "a_century_episode": "Unmatched Mark",
        "a_double_digits": "Marathon Testament",
        "a_one_two_three": "Technique Archive Crown Crown",
        "a_lucky_seven": "Captain Tsubasa Decree",
        "a_all_tens": "Marathon Criterion",
        "a_exact_hundred_eps": "Cup Hero Legend",
        "a_year_match_count": "Tsubasa Clock",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Champion Ledger",
        "a_movie_buff": "World Cup Vault Mark",
        "a_ova_hunter": "Match Standard",
        "a_ona_explorer": "Football Secret",
        "a_special_watcher": "Technique Archive Relic",
        "a_short_king": "Marathon Crown",
        "a_variety_pack": "Ball Inquiry",
        "a_film_festival": "Village Chronicle",
        "a_music_video": "Football Chronicle Chronicle",
        "a_tv_short": "Football Faithful Record",
        "a_movie_marathon": "Village Kid Gauntlet",
        "a_double_length": "Dream Crown",
        "a_anthology": "World Aegis",
        "a_mini_series": "Team Roster Decree",
        "a_theatrical": "Football Faithful Accord",
        "a_format_master": "Dribble Vault",
        "a_long_movie": "Nankatsu Field Insignia",
        "a_back_catalog": "Faithful Standard",
        "a_cm_watcher": "National Aegis Aegis",
        "a_pv_collector": "World Cup Hero Storehouse",
        "a_format_balance": "Unmatched Vault",
        "a_episodic_master": "Football Standard",
        "a_sequel_movie": "Star Pinnacle",
        "a_recap_watcher": "Faithful Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Faithful Devotion",
        "a_mega_streak": "Nankatsu Field Streak",
        "a_weekly_warrior": "World Cup Hero Season",
        "a_monthly_watcher": "Scout Calendar",
        "a_comeback": "Football Faithful Decree",
        "a_weekend_streak": "Captain Tsubasa Passage",
        "a_no_zero_days": "Match Warrant",
        "a_iron_will": "Hero Seal",
        "a_habit_formed": "Dream Warrant",
        "a_consistent_pace": "Hero Measure",
        "a_year_long": "Scout Season",
        "a_double_streak": "Champion Watch",
        "a_streak_recovery": "World Cup Hero Season Season",
        "a_daily_minimum": "Match Focus",
        "a_winter_streak": "World Watch",
        "a_summer_streak": "Training Manual Resolve",
        "a_morning_streak": "Training Manual Clock",
        "a_night_streak": "World Star Constancy",
        "a_unbreakable": "Unmatched Proof",
        "a_eternal_flame": "Captain Tsubasa Standard",
        "a_completion_streak": "Technique Archive Return",
        "a_rating_streak": "Hero Balance",
        "a_multi_ep_streak": "Archive Ritual",
        "a_genre_streak": "Team Roster Streak",
        "a_studio_streak": "Football Faithful Cabinet",
        "a_perfect_week": "Hero Relic",

        // ── ANIME SCORING ──
        "a_critic": "Match Alerts Scrutiny",
        "a_perfect_ten": "World Cup Audit",
        "a_harsh_critic": "Match Gauge",
        "a_fair_judge": "Village Balance",
        "a_generous_spirit": "Dribble Pinnacle",
        "a_score_all": "Village Criterion",
        "a_wide_range": "Football Ledger",
        "a_controversial": "Unmatched Decree",
        "a_consistent_scorer": "World Cup Vault Verdict",
        "a_score_sniper": "Kick Score",
        "a_evolving_taste": "Marathon Testament Testament",
        "a_bell_curve": "Tsubasa Ozora's Insignia",
        "a_picky_watcher": "World Seal",
        "a_100_rated": "Japan Circle Warrant",
        "a_500_rated": "Village Kid Pinnacle",
        "a_mediocre_majority": "Tsubasa Marathon Canon",
        "a_rating_spree": "Kid World Review",
        "a_score_variance": "Tsubasa Ozora's Score",
        "a_masterpiece_hunter": "Technique Banner",
        "a_contrarian": "Tsubasa Marathon Record Record",
        "a_optimist": "Japan Ledger",
        "a_score_distributor": "Dribble Appraisal",
        "a_genre_critic": "Captain Tsubasa Critic",
        "a_mean_above_8": "Rivals Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "Nankatsu Field Resolve",
        "a_valentines_weeb": "Japan Circle Vow",
        "a_pi_day": "Nankatsu Field Trial",
        "a_april_fools": "Rivals Devotion",
        "a_international_anime_day": "World Cup Pinnacle",
        "a_star_wars_day": "Match Chronicle",
        "a_summer_solstice": "Village Kid Calendar",
        "a_tanabata": "Faithful Focus",
        "a_friday_13th": "Scout Relic",
        "a_halloween_spirit": "World Cup Vow",
        "a_thanksgiving_binge": "Village Run",
        "a_christmas_special": "National Season",
        "a_new_years_eve": "National Champion Pilgrimage",
        "a_birthday_watch": "Tsubasa Ozora's Vow",
        "a_holiday_marathon": "Scout Overture",
        "a_independence_day": "Training Manual Banner",
        "a_culture_day": "Tsubasa Marathon Insignia",
        "a_spring_equinox": "World Cup Trophies Decree",
        "a_earth_day": "Football Record",
        "a_labor_day": "Japan Circle Seal Seal",
        "a_winter_solstice": "Ball Pilgrimage",
        "a_anime_birthday": "Village Kid Pilgrimage",
        "a_every_holiday": "Village Kid Resolve",
        "a_consecutive_holidays": "Dribble Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Match Alerts Rank",
        "a_meta_collector": "Dream Hoard",
        "a_meta_category_starter": "National Badge",
        "a_meta_tier_climber": "Cup Hero Glyph",
        "a_meta_tier_max": "Training Manual Writ",
        "a_meta_xp_earner": "Kick Emblem",
        "a_meta_difficulty_easy": "World Cup Vault Mechanism",
        "a_meta_difficulty_hard": "Captain Tsubasa Writ",
        "a_meta_unlock_spree": "Tsubasa Ozora's Panel",
        "a_meta_completionist": "National Champion Fulfillment",
        "a_meta_diverse": "Football Faithful Emblem",
        "a_meta_dominator": "World Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Dribble",
        "m_chapter_counter": "World Cup Vault Pinnacle",
        "m_chapter_titan": "Dream Relic",
        "m_reading_hours": "Technique Relic",
        "m_reading_time_lord": "Village Pinnacle Pinnacle",
        "m_manga_collector": "Marathon Ledger Ledger",
        "m_library_legend": "Captain Tsubasa Reliquary",
        "m_first_complete": "Rivals Triumph",
        "m_hundred_club": "Ball Network",
        "m_first_day": "Cup Hero Seal",
        "m_first_rating": "Technique Eye",
        "m_ten_thousand_pages": "Tsubasa Gauge",
        "m_volume_collector": "Tsubasa Ozora's Storehouse",
        "m_year_explorer": "Technique Archive Quest",
        "m_century_reader": "World Dominion",
        "m_five_hundred_ch": "Football Faithful Ledger",
        "m_thousand_ch": "World Cup Testament",
        "m_reading_ten": "World Cup Trophies Appraisal",
        "m_ptr_hoarder": "Kid World Index",
        "m_dropped_honesty": "Marathon Summit",
        "m_season_reader": "Tsubasa Treasury",
        "m_active_reader": "Marathon Trial",
        "m_five_thousand_ch": "Village Kid Standard",
        "m_ten_completed": "Cup Hero Resolution",
        "m_fifty_completed": "Rivals Harvest",
        "m_five_hundred_completed": "Faithful Legacy",
        "m_mean_score_tracker": "Football Audit",
        "m_unique_authors": "National Reserve",
        "m_all_status": "Tsubasa Marathon Testament",
        "m_first_favorite": "Football Faithful Cache",
        "m_favorites_collector": "Archive Shelf",
        "m_days_spent_reading": "Kick Decree",

        // ── MANGA BINGE ──
        "m_binge_reader": "Kick Streak",
        "m_marathon_reader": "Victory Rush",
        "m_weekend_reader": "Technique Archive Run",
        "m_non_stop_reading": "Village Kid Gauntlet Gauntlet",
        "m_one_more_chapter": "Hero Testament",
        "m_speed_read": "Kick Drive",
        "m_double_story": "Cup Hero Banner",
        "m_triple_read": "Village Record",
        "m_five_a_day": "Match Alerts Insignia",
        "m_chapter_chain": "Dribble Accord",
        "m_volume_binge": "Match Alerts Drive",
        "m_power_reader": "World Star Seal",
        "m_half_day_read": "Kid World Aegis",
        "m_full_day_read": "Village Kid Aegis",
        "m_power_weekend": "Scout Streak",
        "m_binge_king": "Technique Archive Momentum",
        "m_no_sleep_read": "Technique Rush",
        "m_full_series_rush": "Team Roster Cascade",
        "m_seven_day_challenge": "Captain Tsubasa Warrant",
        "m_hundred_day_read": "Football Relic",
        "m_volume_rush": "Ball Gauntlet",
        "m_series_sweep": "Rivals Trial",
        "m_genre_binge": "Victory Binge",
        "m_author_binge": "Captain Tsubasa Surge",
        "m_chapter_counter_day": "Hero Ledger",
        "m_multi_series_binge": "Football Faithful Charge",
        "m_midnight_binge": "Japan Circle Tempest",
        "m_new_year_binge": "Technique Passage",
        "m_forty_eight_hour": "Village Rally",
        "m_oneshot_binge": "Training Manual Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Scout Action",
        "m_genre_adventure": "Unmatched Adventure",
        "m_genre_comedy": "Football Faithful Comedy",
        "m_genre_drama": "Rivals Drama",
        "m_genre_fantasy": "Training Manual Fantasy",
        "m_genre_horror": "Dribble Horror",
        "m_genre_mystery": "Football Mystery",
        "m_genre_romance": "Captain Tsubasa Romance",
        "m_genre_scifi": "World Cup Vault Sci-Fi",
        "m_genre_sol": "Hero Slice",
        "m_genre_sports": "Dribble Sports",
        "m_genre_supernatural": "Faithful Supernatural",
        "m_genre_thriller": "Technique Archive Thriller",
        "m_genre_psychological": "National Champion Psychological",
        "m_genre_isekai": "National Champion Isekai",
        "m_genre_shounen": "Japan Shounen",
        "m_genre_ecchi": "Football Ecchi",
        "m_genre_mahou_shoujo": "Unmatched Magic Shoujo",
        "m_genre_mecha": "Ball Mecha",
        "m_genre_music": "Archive Music",
        "m_tag_isekai_new": "Captain Tsubasa Isekai New",
        "m_tag_harem": "Team Roster Harem",
        "m_tag_bl": "Unmatched Bl",
        "m_tag_gl": "Team Roster Gl",
        "m_tag_historical": "Match Historical",
        "m_tag_military": "Technique Military",
        "m_tag_school": "Hero School",
        "m_tag_martial_arts": "Team Roster Martial Arts",
        "m_tag_vampire": "Ball Vampire",
        "m_tag_samurai": "Champion Samurai",
        "m_tag_space": "Star Space",
        "m_tag_parody": "World Star Parody",
        "m_tag_idol": "Training Manual Idol",
        "m_tag_post_apocalyptic": "Unmatched Post Apocalyptic",
        "m_tag_cyberpunk": "Victory Cyberpunk",
        "m_tag_shoujo": "Training Manual Shoujo",
        "m_tag_survival": "Star Survival",
        "m_tag_cooking": "Match Cooking",
        "m_tag_medical": "Tsubasa Medical",
        "m_tag_villainess": "Cup Hero Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Technique Archive",
        "m_mega_completionist": "Unmatched Resolution",
        "m_completion_rate_50": "World Return",
        "m_completion_rate_75": "Hero Ascension",
        "m_completion_rate_90": "Football Faithful Resolution",
        "m_no_drop": "World Decree",
        "m_long_runner_complete": "Japan Circle Clear",
        "m_sequel_chain": "Victory Seal",
        "m_clean_list": "Dribble Relic",
        "m_from_ptr": "Village Kid Accord",
        "m_reread_master": "Scout Trial",
        "m_oneshot_complete": "Tsubasa Ascension",
        "m_same_day_start_finish": "Training Manual Crown",
        "m_revival": "National Champion Accord",
        "m_zero_to_hundred": "Football Faithful Banner",
        "m_five_genre_complete": "Tsubasa M Five Genre Complete",
        "m_full_collection": "Marathon Proof",
        "m_batch_complete": "Kick Testament",
        "m_paused_to_done": "Technique Archive Standard",
        "m_completion_spree": "Tsubasa Triumph",
        "m_format_completionist": "Match Alerts Testament",
        "m_catch_up": "World Cup Trophies Chronicle",
        "m_multi_reread": "Village Banner",
        "m_dropped_recovery": "Archive Conquest",
        "m_ten_perfect_scores": "Japan Circle Judgment",
        "m_complete_genre_span": "Kick M Complete Genre Span",
        "m_monthly_completions": "National Return",
        "m_yearly_completions": "Nankatsu Field Epilogue",
        "m_rapid_complete": "Star Finale",
        "m_author_complete": "Marathon Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Faithful Legacy Legacy",
        "m_mangaka_lover": "Rivals Standard Standard",
        "m_rereader": "Japan Circle Relic",
        "m_triple_reread": "Archive Testament",
        "m_annual_reread": "Dribble Banner",
        "m_publisher_fan": "World Cup Trophies Mark",
        "m_artist_fan": "Japan Circle Insignia",
        "m_adaptation_compare": "Scout Insignia Insignia",
        "m_source_material_fan": "Tsubasa Marathon Cache",
        "m_waiting_weekly": "Kick Weekly",
        "m_classic_reader": "Tsubasa Marathon Lantern",
        "m_saga_reader": "Scout Crown",
        "m_genre_loyalty": "World Cup Trophies Loyalty",
        "m_decade_reader": "Village Warrant",
        "m_ln_adaptation": "Japan Mark",
        "m_original_work": "Cup Hero Standard Standard",
        "m_long_commitment": "Technique Mark",
        "m_up_to_date": "Technique Archive Warrant",
        "m_favorite_mangaka": "Rivals Treasury",
        "m_complete_portfolio": "Victory Triumph",
        "m_franchise_collector": "Unmatched Archive",
        "m_serialization_follower": "Unmatched Handshake",
        "m_genre_master": "National Champion Master",
        "m_multi_series_author": "Nankatsu Field Insignia Insignia",
        "m_format_diversity": "Football Shelf",
        "m_year_dedication": "Rivals Tenure",
        "m_ongoing_follower": "Scout Fellowship",
        "m_genre_loyalty_50": "Star Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "National Champion Explorer",
        "m_publisher_hopper": "World Cup Trophies Record",
        "m_tag_explorer": "Nankatsu Field Explorer",
        "m_decade_hopper": "Match Chronicle Chronicle",
        "m_hidden_gem": "Scout Mark",
        "m_popular_taste": "World Cup Record",
        "m_retro_reader": "Japan Testament Testament",
        "m_modern_reader": "Match Alerts Seal",
        "m_cross_demographic": "Unmatched Crown",
        "m_underdog_fan": "National Champion Testament",
        "m_variety_week": "Team Roster Horizon",
        "m_manhwa_reader": "Victory Proof",
        "m_manhua_reader": "Village Kid Mantle",
        "m_classic_connoisseur": "Marathon Glimpse",
        "m_award_winner": "Technique Archive Seal",
        "m_niche_explorer": "Champion Horizon",
        "m_world_manga": "Football Faithful Chronicle",
        "m_cult_classic": "Nankatsu Field Map",
        "m_random_pick": "Match Alerts Testament Testament",
        "m_new_genre_month": "Match Alerts M New Genre",
        "m_year_completionist": "World Cup Vault Fulfillment",
        "m_unpopular_opinion": "Village Kid Aegis Aegis",
        "m_top_rated_reader": "Technique Archive Pinnacle",
        "m_source_variety": "Cup Hero Catalogue",
        "m_low_score_brave": "World Cup Trophies Score",
        "m_short_manga_explorer": "Tsubasa Marathon Compass",
        "m_long_manga_explorer": "National Survey",
        "m_serialization_explorer": "Japan Road",

        // ── MANGA TIME ──
        "m_night_owl": "Match Alerts Accord",
        "m_early_bird": "Captain Tsubasa Banner",
        "m_lunch_reader": "Dribble Ledger Ledger",
        "m_commute_reader": "Team Roster Tenure",
        "m_four_am_club": "Team Roster Fellowship",
        "m_new_year_read": "Tsubasa Marathon Pact",
        "m_all_hours": "Kid World Accord",
        "m_prime_time_reader": "Faithful Banner",
        "m_workday_reader": "Hero Accord",
        "m_sunday_read": "Marathon Standard",
        "m_morning_routine": "Ball Discipline",
        "m_night_shift_reader": "World Cup Vault Accord",
        "m_seasonal_premier_read": "Match Alerts Storehouse",
        "m_clock_collector": "Japan Circle Reserve",
        "m_late_night_horror": "Scout Mark Mark",
        "m_afternoon_reader": "Rivals Mantle Mantle",
        "m_golden_hour_reader": "Archive Observance",
        "m_dawn_reader": "Tsubasa Mantle",
        "m_twilight_reader": "Nankatsu Field Crown",
        "m_midnight_start": "Technique Archive Routine",
        "m_weekend_binge_hours": "Football Faithful Momentum",
        "m_late_night_regular": "World Cup Testament Testament",
        "m_sunrise_reader": "World Cup Record Record",
        "m_every_day_of_week": "Training Manual Seal",
        "m_monthly_hours": "Team Roster Vigil",
        "m_bedtime_reader": "Ball Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Football Faithful Mantle",
        "m_webtoon_reader": "World Cup Mark",
        "m_full_color": "Football Accord",
        "m_doujin_reader": "Tsubasa Record",
        "m_anthology_reader": "World Accord",
        "m_adaptation_reader": "Champion Banner",
        "m_longstrip_reader": "World Chronicle",
        "m_4koma_reader": "Victory Relic",
        "m_oneshot_reader": "World Mantle",
        "m_format_variety": "Dream Gallery",
        "m_light_novel_reader": "Faithful Insignia Insignia",
        "m_novel_reader": "Match Crown",
        "m_visual_storyteller": "Champion Testament",
        "m_colored_classic": "Captain Tsubasa Survey",
        "m_webcomic_fan": "Hero Insignia",
        "m_manga_to_anime": "World Star Record",
        "m_seinen_reader": "Ball Pinnacle Pinnacle",
        "m_josei_reader": "World Star Pinnacle",
        "m_award_winning_art": "Champion Relic",
        "m_debut_work": "Rivals Dominion",
        "m_vertical_scroll": "Football Crown",
        "m_traditional_format": "Village Hoard",
        "m_cross_media": "Champion Accord",
        "m_spinoff_reader": "World Cup Trophies Accord",
        "m_remake_reader": "Victory Insignia Insignia",
        "m_collaboration_reader": "Captain Tsubasa Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Match Alerts Focus",
        "m_mega_streak": "Cup Hero Routine",
        "m_weekly_warrior": "National Champion Season",
        "m_monthly_reader": "Team Roster Discipline",
        "m_comeback": "Ball Standard",
        "m_weekend_streak": "Football Fever",
        "m_no_zero_days": "Training Manual Proof",
        "m_iron_will": "Football Ledger Ledger",
        "m_habit_formed": "Football Faithful Crown",
        "m_consistent_pace": "Kick Scrutiny",
        "m_year_long": "Training Manual Observance",
        "m_double_streak": "Kick Resolve",
        "m_streak_recovery": "Unmatched Resolve",
        "m_daily_minimum": "Hero Focus",
        "m_winter_streak": "Dream Observance",
        "m_summer_streak": "Nankatsu Field Observance",
        "m_morning_streak": "World Cup Clock",
        "m_night_streak": "Nankatsu Field Discipline",
        "m_unbreakable": "Ball Warrant Warrant",
        "m_eternal_flame": "Victory Record",
        "m_chapter_a_day": "Match Alerts Relic",
        "m_genre_streak": "Nankatsu Field Streak Mode",
        "m_completion_streak": "Football Faithful Return",
        "m_rating_streak": "Ball Appraisal",
        "m_multi_ch_streak": "National Tenure",
        "m_author_streak": "Cup Hero Calendar",
        "m_perfect_week_manga": "Technique Accord",
        "m_diverse_streak": "Japan Circle Streak",

        // ── MANGA SCORING ──
        "m_critic": "Japan Scrutiny",
        "m_perfect_ten": "Marathon Verdict",
        "m_harsh_critic": "Technique Scale",
        "m_fair_judge": "Archive Eye",
        "m_generous_spirit": "National Crown",
        "m_score_all": "Cup Hero Reckoning",
        "m_wide_range": "Unmatched Crown Crown",
        "m_controversial": "Match Standard Standard",
        "m_consistent_scorer": "Victory Grade",
        "m_score_sniper": "World Cup Trophies Reckoning",
        "m_evolving_taste": "Rivals Trial Trial",
        "m_bell_curve": "Village Kid Accord Accord",
        "m_picky_reader": "World Cup Hero Relic",
        "m_100_rated": "Archive Mark",
        "m_500_rated": "World Proof",
        "m_mediocre_majority": "Football Canon",
        "m_rating_spree": "Champion Verdict",
        "m_score_variance": "Training Manual Measure",
        "m_binge_rater": "Tsubasa Marathon Passage",
        "m_reread_rerate": "Japan Circle Banner Banner",
        "m_masterpiece_hunter": "Star Banner",
        "m_contrarian": "Archive Aegis",
        "m_optimist": "Champion Accord Accord",
        "m_score_distributor": "Star Balance",
        "m_genre_critic": "Unmatched Critic",
        "m_mean_above_8": "Kick Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Faithful Season",
        "m_valentines_read": "Unmatched Observance",
        "m_pi_day": "Unmatched Testament",
        "m_april_fools": "Faithful Devotion Devotion",
        "m_international_manga_day": "Victory Proof Proof",
        "m_free_comic_day": "Champion Chronicle Chronicle",
        "m_summer_solstice": "Football Faithful Focus",
        "m_tanabata": "Marathon Pilgrimage",
        "m_friday_13th": "Tsubasa Ozora's Dominion",
        "m_halloween_read": "Football Calendar",
        "m_thanksgiving_binge": "Captain Tsubasa Charge",
        "m_christmas_read": "Tsubasa Pact",
        "m_new_years_eve": "Technique Archive Pilgrimage",
        "m_birthday_read": "Rivals Focus",
        "m_holiday_marathon": "National Champion Rally",
        "m_independence_day": "Match Aegis",
        "m_culture_day": "Star Seal",
        "m_spring_equinox": "Tsubasa Ozora's Banner",
        "m_earth_day": "Japan Aegis",
        "m_labor_day": "Hero Seal Seal",
        "m_winter_solstice": "Victory Focus",
        "m_manga_birthday": "Kick Ritual",
        "m_every_holiday_reader": "Team Roster Watch",
        "m_consecutive_holidays": "Rivals Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Ball Proof",
        "m_fibonacci": "Ball Dominion",
        "m_palindrome_day": "Technique Archive Relic Relic",
        "m_binary_day": "Football Faithful Proof",
        "m_full_moon_read": "Team Roster Crown",
        "m_leap_year_read": "Victory Practice",
        "m_triple_seven": "Marathon Chronicle",
        "m_thousand_complete": "Tsubasa Legend",
        "m_nice": "Village Seal",
        "m_power_level_chapters": "Nankatsu Field Aegis",
        "m_answer_42": "Champion Aegis Aegis",
        "m_square_number": "National Champion Standard",
        "m_prime_count": "Football Insignia",
        "m_matching_date": "Training Manual Mantle",
        "m_century_chapter": "Match Alerts Crown",
        "m_pi_chapters": "Star Proof",
        "m_synchronicity": "Archive Emblem",
        "m_world_record": "World Cup Warrant",
        "m_genre_clash": "Kid World Clash",
        "m_time_traveler": "Match Decree",
        "m_double_digits": "Football Faithful Dominion",
        "m_one_two_three": "Unmatched Warrant",
        "m_lucky_seven": "Scout Record",
        "m_exact_hundred_ch": "Kick Legend",
        "m_year_match_count": "Football Routine",
        "m_chapter_match_date": "World Star Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Hero Index",
        "m_manhwa_format": "Unmatched Gallery",
        "m_manhua_format": "Village Kid Storehouse",
        "m_ln_format": "Unmatched Index",
        "m_oneshot_format": "World Cup Vault Index",
        "m_doujin_format": "World Cup Cabinet",
        "m_novel_format": "Victory Reserve",
        "m_format_master_manga": "Faithful Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Football Link",
        "m_meta_collector": "National Reliquary",
        "m_meta_category_starter": "Kid World Standard Standard",
        "m_meta_tier_climber": "Marathon Token",
        "m_meta_tier_max": "National Champion Token",
        "m_meta_xp_earner": "Marathon Anchor",
        "m_meta_difficulty_easy": "Village Kid Panel",
        "m_meta_difficulty_hard": "Tsubasa Seal",
        "m_meta_unlock_spree": "Tsubasa Marathon Marker",
        "m_meta_completionist": "Unmatched Triumph",
        "m_meta_diverse": "Match Anchor",
        "m_meta_dominator": "Kick Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#000208",
        primary: "#1650cd",
        secondary: "#cc2020",
        accent: "#f0f0f0",
    },
    particleColor: "#4088e0",
    backgroundDim: 0.3,
    backgroundBlur: 18,
    milestoneNames: {
  1: "Threadbare Tsubasa Ozora Spark",
  8: "Neighborhood's Tarnished Omen",
  14: "Fractured Dream Cup",
  21: "Nankatsu Elementary Path",
  28: "Lowborn Control Myth",
  35: "Genzo Wakabayashi Pulse",
  41: "Rivalry's Legacy Form",
  48: "Humble Team Mark",
  55: "Ragged Match Victory Vow",
  61: "Football's Faint Echo",
  68: "Lesser Training Discipline",
  75: "Drive Shot Zenith",
  81: "Doubtful Competition Haven",
  88: "Technical Skill Sigil",
  95: "Youth's Legacy Clash",
  102: "Really Cool Tsubasa Spark",
  108: "Awakened Offensive Play Brush",
  115: "Team's Resolute Soul",
  122: "Rising Regional Tournament",
  128: "Winning Streak Myth",
  135: "Dauntless Youth Pulse",
  142: "Rival Strikers Crest",
  149: "Special's Legacy Mark",
  155: "Fresh Football Vow",
  162: "Valiant Emotional Soul",
  169: "National's Prime Crown",
  175: "Polished Japan Youth",
  182: "Tactical Match Bloom",
  189: "Stormlit Expands Haven",
  195: "Team Japan Form",
  202: "International's Tournament Clash",
  209: "Tempered Global Clash",
  216: "Trusted Physical Endurance Seal",
  222: "Tsubasa's Steadfast Path",
  229: "Ironclad Skill Strength",
  236: "South American Pulse",
  242: "Core Rival Brush",
  249: "Level Competition Mark",
  256: "Advanced's Legacy Clash",
  262: "Formidable Team Echo",
  269: "Lucid International Youth Brush",
  276: "Global's Ranked Clash",
  283: "Fabled Tsubasa Elite",
  289: "Drive Shot Form",
  296: "Seasoned Legacy Flame",
  303: "Brazilian Football Spark",
  309: "Rival's Striker Omen",
  316: "Valorous Skill Seal",
  323: "Stalwart Team Japan Clash",
  330: "Drive's Commanding Soul",
  336: "Refined International",
  343: "Rivalry Class Crest",
  350: "Blazing Surge Mark",
  356: "Physical Exhaustion Force",
  363: "Dream's Solidifies Echo",
  370: "Peerless Semifinal Crown",
  376: "Ardent Team Unity Zenith",
  383: "Turning's Focused Bloom",
  390: "Vigilant Match Preparation",
  397: "Tsubasa Performance Form",
  403: "Elite Showdown Spark",
  410: "Team Coordination Omen",
  417: "National's Legacy Seal",
  423: "Sovereign Championship Path",
  430: "Regal Class Rival Myth",
  437: "Drive's Crowned Form",
  444: "Mythborn Tsubasa Injury",
  450: "Turning Athlete Soul",
  457: "Radiant Emotional Soul",
  464: "Career Opening Echo",
  470: "International's Scout Crown",
  477: "Climactic Club Haven",
  484: "Epic Global Stage Bloom",
  490: "Brazil's Unreal Haven",
  497: "Peak Rival Striker",
  504: "Tsubasa Skill Spark",
  511: "Exalted Legacy Omen",
  517: "World Football Seal",
  524: "European's Legacy Path",
  531: "Celestial Tactical Myth",
  537: "Phantom Match Intelligence Form",
  544: "Elite's Crimson Crest",
  551: "Silver Professional",
  557: "International League Vow",
  564: "Feral Strikers Echo",
  571: "Tsubasa Leadership Crown",
  578: "Drive's Legacy Zenith",
  584: "Dread Cup Bloom",
  591: "Luminous National Team Form",
  598: "Global's Thunderous Flame",
  604: "Ultraviolet Elite Defense",
  611: "Team Japan Omen",
  618: "Secret Legacy Brush",
  625: "Global Rival Clash",
  631: "Tsubasa's Stars Myth",
  638: "Worldclass Physical Pulse",
  645: "Lawless Knockout Intensity Crest",
  651: "Team's Chosen Mark",
  658: "Fearless Rivalry Evolution",
  665: "Tsubasa Injury Echo",
  671: "Cinematic Legacy Crown",
  678: "Tsubasa Gameplay Form",
  685: "Global's Recognition Bloom",
  692: "Canonized Football Sigil",
  698: "Ascendant Team Unity Flame",
  705: "World's Transfigured Spark",
  712: "Immortal Ultimate Rival",
  718: "Drive Shot Seal",
  725: "Astral Legacy Form",
  732: "National Hero Myth",
  739: "Football's Legacy Pulse",
  745: "Prismatic Tsubasa Form",
  752: "Abyssal Post Tournament Clash",
  759: "Global's Unbound Haven",
  765: "Eternal Football Legend",
  772: "International Star Crown",
  779: "Transcendent Limits Zenith",
  785: "Professional Mastery Bloom",
  792: "Tsubasa's Player Sigil",
  799: "Ultimate Global Flame",
  806: "Mythic Drive Shot Form",
  812: "Team's Godlike Omen",
  819: "Canonical National Football",
  826: "Legendary Career Path",
  832: "Heavenly Legacy Myth",
  839: "Football Soul",
  846: "Rival's Shift Crest",
  852: "Timeless Tsubasa Mark",
  859: "Empyrean Global Football Vow",
  866: "Competition's Primordial Echo",
  873: "Omniscient Football Intelligence",
  879: "Legend Soccer Zenith",
  886: "Apocalyptic Evolution Form",
  893: "Football Dream Sigil",
  899: "Tsubasa's Absolute Flame",
  906: "Final Team Spark",
  913: "Crowned Human Athletic Omen",
  920: "Football's Mythic Seal",
  926: "Absolute Legend Eras",
  933: "Absolute Myth",
  940: "Cosmic Legacy Echo",
  946: "Competition Crest",
  953: "Ultimate's Legend Mark",
  960: "Definitive Captain Vow",
  966: "Ultimate Kicked Ball Clash",
  973: "Kicked's Infinite Clash",
  980: "Sovereign Kicked Ball",
  987: "Kicked Ball Clash",
  993: "Legendary Streets Clash",
  1000: "Ultimate Captain Tsubasa"
}
}
