import { AnimeThemeConfig } from "./types"
import { GiCastle, GiCrystalBall, GiSteampunkGoggles, GiGemChain, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiAirplane } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const castleInTheSkyTheme: AnimeThemeConfig = {
    id: "castle-in-the-sky",
    displayName: "Castle in the Sky",
    description: "A boy and girl with a mysterious crystal flee sky pirates and military forces to find the legendary floating fortress of Laputa — Miyazaki's soaring adventure of wonder.",
    fontFamily: "'Libre Baskerville', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "175 225 255",
        "--color-brand-300": "115 198 250",
        "--color-brand-400": "62 170 240",
        "--color-brand-500": "20 142 225",
        "--color-brand-600": "12 114 188",
        "--color-brand-700": "8 88 148",
        "--color-brand-800": "4 62 108",
        "--color-brand-900": "2 36 65",
        "--color-brand-950": "1 20 38",
        "--brand": "20 142 225",
        "--background": "#010608",
        "--paper": "#040e14",
        "--color-gray-950": "1 6 8",
        "--color-gray-900": "4 12 18",
        "--color-gray-800": "8 22 34",
        "--color-gray-700": "14 38 58",
        "--color-gray-600": "24 60 90",
        "--color-gray-500": "40 90 130",
        "--color-gray-400": "72 128 165",
        "--color-gray-300": "115 168 200",
        "--color-gray-200": "160 202 222",
        "--color-gray-100": "198 225 238",
        "--color-gray-50": "232 244 250",
    },
    sidebarOverrides: {
        "home": { icon: GiCastle, label: "Laputa" },
        "schedule": { icon: GiAlarmClock, label: "Flight Schedule" },
        "manga": { icon: LuBookOpen, label: "Laputan Texts" },
        "lists": { icon: GiGemChain, label: "Crystal Registry" },
        "discover": { icon: GiBullseye, label: "Sky Survey" },
        "torrent-list": { icon: GiSteampunkGoggles, label: "Airship Cache" },
        "debrid": { icon: GiCrystalBall, label: "Aetherium" },
        "unmatched": { icon: GiAirplane, label: "Lost Vessels" },
        "enmasse": { icon: GiResize, label: "Pirate Fleet" },
        "scan-summaries": { icon: TbReportSearch, label: "Sky Charts" },
        "auto-downloader": { icon: LuRss, label: "Radio Signals" },
        "community": { icon: GiCastle, label: "Sky Pirates" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Laputa Alerts" },
        "achievements": { icon: GiTrophy, label: "Sky Medals" },
        "milestones": { icon: LuFlag, label: "Sky Goals" },
        "theme-manager": { icon: GiPalette, label: "Sky Colors" },
        "extensions": { icon: BiExtension, label: "Airship Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Laputa Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Navigation" },
    },
    achievementNames: {
        "a_first_episode": "First Flight",
        "a_first_complete": "Laputa Found",
        "a_hundred_club": "Hundred Flights",
        "a_time_lord": "Sky Veteran",
        "a_anime_collector": "Crystal Cache",
        "a_library_legend": "Laputan Archives",
        "a_binge_king": "Sky Marathon",
        "a_no_sleep": "All-Night Flight",
        "a_marathon_runner": "Cloud Marathon",
        "a_speed_run": "Tiger Moth Speed",
        "a_completionist": "Sky Complete",
        "a_mega_completionist": "Miyazaki Master",
        "a_loyal_fan": "Sheeta's Ally",
        "a_rewatcher": "Return to Laputa",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Air Battle",
        "a_genre_adventure": "Sky Adventure",
        "a_genre_comedy": "Dola's Crew",
        "a_genre_drama": "Crystal Mystery",
        "a_genre_fantasy": "Laputa Legend",
        "a_genre_horror": "Army Terror",
        "a_genre_romance": "Pazu & Sheeta",
        "a_genre_scifi": "Laputian Tech",
        "a_genre_supernatural": "Crystal Power",
        "a_genre_psychological": "Lost Kingdom",
        "a_genre_mecha": "Laputian Robots",
        "a_critic": "Sky Judge",
        "a_perfect_ten": "Perfect Flight",
        "a_harsh_critic": "Strict Captain",
        "a_daily_streak": "Daily Flight",
        "a_mega_streak": "Endless Sky",
        "a_year_long": "Year of Wonder",
        "a_iron_will": "Pazu's Resolve",
        "a_hidden_gem": "Hidden Castle",
        "a_cult_classic": "Miyazaki Classic",
        "a_classic_connoisseur": "86 Classic Fan",
        "a_new_years_resolution": "New Year Flight",
        "a_christmas_special": "Winter Sky",
        "a_meta_tier_max": "Laputan Prince",
        "a_meta_completionist": "Sky Complete",
        "a_sequel_chain": "Ghibli Sequel",
        "a_zero_to_hero": "Mine Boy to Hero",
        "a_night_owl": "Night Flight",
        "a_early_bird": "Dawn Flight",
        "m_first_chapter": "First Page",
        "m_first_complete": "Arc Complete",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Sky Marathon",
        "m_completionist": "Full Journey",
        "m_mega_completionist": "Ghibli Expert",
        "m_loyal_reader": "Crystal Reader",
        "m_rereader": "Sky Return",
        "m_genre_action": "Air Combat",
        "m_genre_adventure": "Sky Journey",
        "m_genre_romance": "Sky Romance",
        "m_genre_fantasy": "Laputa Chapter",
        "m_genre_horror": "Fallen Castle",
        "m_genre_drama": "Sky Drama",
        "m_genre_scifi": "Laputian Science",
        "m_genre_supernatural": "Crystal Chapter",
        "m_genre_psychological": "Deep Sky",
        "m_critic": "Ghibli Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Unbroken Flight",
        "m_year_long": "Year Reading",
        "m_iron_will": "Sky Dedication",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Classic Film",
        "m_mangaka_lover": "Miyazaki Fan",
        "m_source_material_fan": "Ghibli First",
        "m_meta_tier_max": "Sky Master",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Sky Art",
        "m_manga_to_anime": "Story Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#010608",
        primary: "#148ee1",
        secondary: "#0c72bc",
        accent: "#c8a430",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/castle-in-the-sky.jpg",
    particleColor: "#78c8f8",
    backgroundDim: 0.3,
    backgroundBlur: 18,
    particleTypes: {
        clouds: { label: "Clouds", maxCount: 15, defaultEnabled: true, defaultIntensity: 55 },
        crystal_sparks: { label: "Crystal Sparks", maxCount: 12, defaultEnabled: true, defaultIntensity: 50 },
    },
    milestoneNames: {
    1:    "Pazu Mining Town Apprentice Life",
    8:    "Sheeta Falling From the Sky Incident",
    15:   "Aether Crystal Awakening",
    22:   "Laputa Myth Discovery Begins",
    29:   "Airship Pirate Encounter",

    36:   "Dola Family Pursuit Conflict",
    43:   "Military Forces Tracking Sheeta",
    50:   "Floating Stone Gravity Activation",
    57:   "Pazu Protective Instinct Awakening",
    64:   "Escape From Mining Town",

    71:   "Airship Chase Through Storms",
    78:   "Sheeta Ancient Royal Line Reveal",
    85:   "Laputa Coordinates Fragment",
    92:   "Mechanical Robots First Encounter",
    99:   "Crystal Resonance Phenomenon",

    106:  "Military Power Escalation",
    113:  "Pirate Alliance Temporary Formation",
    120:  "Sky Navigation Survival Skills",
    127:  "Ancient Technology Activation Signs",
    134:  "Sheeta Emotional Memory Triggers",

    141:  "Laputa Search Intensifies",
    148:  "Airship Battle Skies",
    155:  "Gravity Crystal Control Growth",
    162:  "Pazu Courage Development",
    169:  "Pursuit Across Cloud Layers",

    176:  "Military Fortress Air Assault",
    183:  "Dola Family Tactical Shift",
    190:  "Ancient Robot Awakening",
    197:  "Laputa Ruins Signal Strength",
    204:  "Crystal Language Fragment Understanding",

    211:  "Sky Fortress Entry Approach",
    218:  "Environmental Hazard Navigation",
    225:  "Mechanical Guardian Encounters",
    232:  "Royal Heritage Confirmation",
    239:  "Military Greed Intensifies",

    246:  "Floating Island Final Coordinates",
    253:  "Airship Battle Chaos Peak",
    260:  "Sheeta Emotional Resolve Growth",
    267:  "Pazu Determination Strengthens",
    274:  "Ancient Defense System Activation",

    281:  "Laputa Outer Structure Discovery",
    288:  "Robotic Army Awakening",
    295:  "Crystal Core Resonance Spike",
    302:  "Military vs Nature Conflict",
    309:  "Dola Family Shift to Survival",

    316:  "Sky Castle Entry Sequence",
    323:  "Ancient Technology Overload",
    330:  "Pazu and Sheeta Unity Strength",
    337:  "Laputa Civilization Echoes",
    344:  "Military Breakdown in Sky",

    351:  "Core Chamber Approach",
    358:  "Robot Guardian Interaction",
    365:  "Lost Civilization Revelation",
    372:  "Crystal Control Instability",
    379:  "Sheeta Royal Command Awakening",

    386:  "Laputa Heart Chamber Entry",
    393:  "Power of the Crystal Revealed",
    400:  "Turning Point of Sky Kingdom",

    407:  "Military Overreach Collapse Begins",
    414:  "Laputa Defensive System Activation",
    421:  "Pazu Protective Resolution Peak",
    428:  "Sheeta Moral Choice Pressure",
    435:  "Ancient AI Guardian Response",

    442:  "Sky Fortress System Awakening",
    449:  "Destruction vs Preservation Conflict",
    456:  "Dola Family Escape Decision",
    463:  "Crystal Overload Crisis",
    470:  "Turning Point of Civilization Power",

    477:  "Laputa Core Instability Rising",
    484:  "Military Final Assault Failure",
    491:  "Robot Army Autonomous Response",
    498:  "Pazu and Sheeta Final Bond",
    505:  "Sky Collapse Risk Escalation",

    512:  "Final Chamber Revelation",
    519:  "Ancient Civilization Fate Exposure",
    526:  "Power Without Control Collapse",
    533:  "Nature vs Technology Balance",
    540:  "Crystal System Overload",

    547:  "Laputa Self-Defense Override",
    554:  "Military Disintegration in Sky",
    561:  "Sheeta Emotional Final Decision",
    568:  "Pazu Support Absolute Resolve",
    575:  "Sky Castle System Failure",

    582:  "Robotic Guardians Stand Down",
    589:  "Civilization Memory Echo",
    596:  "Laputa Energy Core Destabilization",
    603:  "Escape Route Formation",

    610:  "Final Descent Sequence Begins",
    617:  "Ancient Power Release Trigger",
    624:  "Sky Fortress Structural Collapse",
    631:  "Sheeta Command Word Activation",
    638:  "Balance of Destruction and Freedom",

    645:  "Laputa Disassembly in Sky",
    652:  "Military Defeat Complete",
    659:  "Robot Guardians Peaceful State",
    666:  "Crystal Power Dissipation",

    673:  "Sky Kingdom Separation",
    680:  "Pazu and Sheeta Survival Escape",
    687:  "Ancient Technology Return to Sky",
    694:  "Civilization Letting Go Moment",

    701:  "World Below Witnesses Falling City",
    708:  "Final Airship Escape Sequence",
    715:  "Laputa Myth Transformation",
    722:  "Memory of Lost Civilization",

    729:  "Nature Reclaims Balance",
    736:  "Military Ambition Erased",
    743:  "Sheeta Identity Acceptance",
    750:  "Pazu Dream Fulfillment",

    757:  "Sky Journey Completion",
    764:  "Ancient Power Resting",
    771:  "Human Greed Lesson End",
    778:  "Freedom of the Sky Restored",

    785:  "Aftermath of Floating Kingdom",
    792:  "Bond Between Two Survivors",

    799:  "Legend of Laputa Spreads",
    806:  "Sky Memory Preservation",
    813:  "Technology and Nature Balance Restored",
    820:  "Civilization Without Control Lesson",

    827:  "Sheeta Peaceful Identity",
    834:  "Pazu Future Dream Rekindled",
    841:  "Sky Castle Gone but Remembered",
    848:  "World Healing Begins",

    855:  "Beyond Military Greed",
    862:  "Ancient Magic Silence",
    869:  "Humanity Grounded in Earth",

    876:  "Final Sky Memory",
    883:  "Laputa Eternal Myth State",
    890:  "Pazu and Sheeta Hopeful Future",

    897:  "Balance Between Sky and Earth",
    904:  "Freedom Through Letting Go",

    911:  "Absolute Sky Journey Completion",
    918:  "Civilization Beyond Control",
    925:  "Memory of Floating World",

    932:  "Final Emotional Resolution",
    939:  "Sky Without Kingdom",
    946:  "Humanity Rooted in Ground",

    953:  "Beyond Power and Technology",
    960:  "Perfect Sky Harmony",

    967:  "Legend of Laputa Eternal",
    974:  "Freedom Without Possession",
    981:  "Perfect Balance Achieved",
    988:  "Beyond Sky and Earth Conflict",
    995:  "Absolute Laputa Myth",
    998:  "Perfect Castle in the Sky State",
    1000:"A Boy and a Girl Who Discovered a Floating Kingdom Learned That True Power Was Not in Controlling the Sky, but in Letting It Go—Allowing Ancient Wonders to Fade Back Into the Clouds So That Humanity Could Return to the Earth With New Understanding"
}
}
