import { AnimeThemeConfig } from "./types"
import { GiCrystalBall, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiStarSwirl, GiSpellBook, GiMusicalNotes } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const charlotteTheme: AnimeThemeConfig = {
    id: "charlotte",
    displayName: "Charlotte",
    description: "Some teenagers develop supernatural abilities during puberty. Yuu Otosaka abuses his for personal gain until he's caught and recruited into the student council that polices ability users — and learns of a darker truth.",
    cssVars: {
        "--color-brand-200": "195 215 255",
        "--color-brand-300": "140 175 248",
        "--color-brand-400": "85 132 235",
        "--color-brand-500": "42 92 215",
        "--color-brand-600": "16 60 172",
        "--color-brand-700": "4 34 128",
        "--color-brand-800": "1 16 80",
        "--color-brand-900": "0 5 40",
        "--color-brand-950": "0 1 18",
        "--brand": "42 92 215",
        "--background": "#000208",
        "--paper": "#000514",
        "--color-gray-950": "0 2 8",
        "--color-gray-900": "1 6 18",
        "--color-gray-800": "3 14 35",
        "--color-gray-700": "6 26 58",
        "--color-gray-600": "11 46 90",
        "--color-gray-500": "20 76 130",
        "--color-gray-400": "42 116 168",
        "--color-gray-300": "78 156 205",
        "--color-gray-200": "122 192 232",
        "--color-gray-100": "175 220 250",
        "--color-gray-50": "222 242 255",
    },
    sidebarOverrides: {
        "home": { icon: GiCrystalBall, label: "Student Council" },
        "schedule": { icon: GiAlarmClock, label: "Ability Schedule" },
        "manga": { icon: LuBookOpen, label: "Ability Files" },
        "lists": { icon: GiScrollUnfurled, label: "Ability Registry" },
        "discover": { icon: GiBullseye, label: "New Ability Users" },
        "torrent-list": { icon: GiMusicalNotes, label: "ZHIEND Cache" },
        "debrid": { icon: GiHeartKey, label: "Council Vault" },
        "unmatched": { icon: GiStarSwirl, label: "Unknown Abilities" },
        "enmasse": { icon: GiResize, label: "Ability Gathering" },
        "scan-summaries": { icon: TbReportSearch, label: "Ability Reports" },
        "auto-downloader": { icon: LuRss, label: "Ability Feed" },
        "community": { icon: GiSpellBook, label: "Charlotte Circle" },
        "achievements": { icon: GiTrophyCup, label: "Power Trophies" },
        "milestones": { icon: LuFlag, label: "Ability Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Ability Alerts" },
        "theme-manager": { icon: GiPalette, label: "Night Colors" },
        "extensions": { icon: BiExtension, label: "Power Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Council Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Yuu Config" },
    },
    achievementNames: {
        "a_first_episode": "Power Discovered",
        "a_first_complete": "First Mission Done",
        "a_hundred_club": "Hundred Ability Days",
        "a_binge_king": "Charlotte Marathon",
        "a_completionist": "All Abilities Collected",
        "a_mega_completionist": "Charlotte Complete",
        "a_loyal_fan": "Council Regular",
        "a_zero_to_hero": "Cheater to Hero",
        "m_first_chapter": "First Power",
        "m_completionist": "Full Ability Archive",
    },
    musicUrl: "",
    previewColors: {
        bg: "#000208",
        primary: "#2a5cd7",
        secondary: "#c84888",
        accent: "#a8c8f8",
    },
    particleColor: "#4880e0",
    backgroundDim: 0.3,
    backgroundBlur: 20,
    milestoneNames: {
    1:    "Yuu Otosaka Normal Student Life",
    8:    "Short-Term Possession Ability Awakening",
    15:   "Cheating Through Powers Phase",
    22:   "Hidden Ability Users Discovery",
    29:   "Nao Tomori Observation Initiation",

    36:   "Student Council Intervention",
    43:   "Ability Misuse Consequences",
    50:   "Controlled School Surveillance",
    57:   "Yuu Exposure and Capture",
    64:   "Ability User Registration Awareness",

    71:   "Student Council Recruitment",
    78:   "Forced Ethical Correction Phase",
    85:   "Ability Abuse Moral Shift",
    92:   "Trust Formation With Nao",
    99:   "Power Responsibility Realization",

    106:  "Transfer Ability Recognition",
    113:  "Brother Separation Trauma Hint",
    120:  "Ability Hunting Expansion",
    127:  "Group Ability User Encounters",
    134:  "Ethical Power Usage Training",

    141:  "Student Council Field Operations",
    148:  "Ability Abuse Victim Awareness",
    155:  "Protective Intervention Growth",
    162:  "Emotional Burden Increase",
    169:  "Yuu Moral Reformation",

    176:  "Shunsuke Time Leap Mystery",
    183:  "Ability Origin Investigation",
    190:  "International Ability Scope Reveal",
    197:  "Student Council Expansion",
    204:  "Early Collapse Risk Signs",

    211:  "Emotional Attachment Formation",
    218:  "Yusa Nishimori Possession Case",
    225:  "Multiple Personality Ability Complexity",
    232:  "Power Instability Growth",
    239:  "Council Strategy Development",

    246:  "Ability User Exploitation Cases",
    253:  "Protection vs Control Conflict",
    260:  "Yuu Emotional Duality Growth",
    267:  "Nao Trust Dependency Increase",
    274:  "Ethical Breaking Point Approach",

    281:  "Ability Suppression Experiments",
    288:  "Memory Manipulation Awareness",
    295:  "Brother Time Travel Revelation",
    302:  "Yuu Psychological Strain",
    309:  "Student Council Crisis Escalation",

    316:  "Global Ability Research Hint",
    323:  "Shocking Ability Side Effects",
    330:  "Yuu Responsibility Burden Peak",
    337:  "Nao Emotional Vulnerability",
    344:  "Group Stability Fracture",

    351:  "Collapse of Normal Life",
    358:  "Ability Abuse Catastrophe",
    365:  "Brother Illness Revelation",
    372:  "Time Travel Solution Concept",
    379:  "Emotional Desperation Growth",

    386:  "Plan for Ability Sealing",
    393:  "Yuu Leadership Emergence",
    400:  "Turning Point of Sacrifice",

    407:  "Global Ability Hunting Awareness",
    414:  "Zhiend Music Emotional Anchor",
    421:  "Memory Retention Instability",
    428:  "Yuu Emotional Collapse Risk",
    435:  "Nao Support Dependency Peak",

    442:  "Time Travel Mission Preparation",
    449:  "Brother Rescue Strategy Formation",
    456:  "Ability Drain Side Effect Exposure",
    463:  "Identity Fragmentation Begins",
    470:  "Sacrifice Path Becoming Clear",

    477:  "Ability Overuse Consequences",
    484:  "Yuu Physical and Mental Strain",
    491:  "Emotional Separation Risk",
    498:  "Student Council Final Mission Setup",
    505:  "Time Leap System Activation",

    512:  "World Line Change Attempt",
    519:  "Memory Loss Risk Intensifies",
    526:  "Brother Condition Critical",
    533:  "Yuu Isolation Phase",
    540:  "Emotional Breakdown Threshold",

    547:  "Time Travel Execution Begins",
    554:  "Ability Accumulation Strain",
    561:  "Reality Reconstruction Instability",
    568:  "Nao Emotional Collapse",
    575:  "Yuu Determination Peak",

    582:  "Global Ability Impact Revelation",
    589:  "Sacrifice Acceptance Phase",
    596:  "Memory Erosion Acceleration",
    603:  "Brother Rescue Near Completion",

    610:  "Final Time Jump Sequence",
    617:  "Identity Loss Warning",
    624:  "Emotional Anchor Breakdown",
    631:  "World Stability Risk",
    638:  "Yuu Final Decision Point",

    645:  "Ability Erasure Mechanism Trigger",
    652:  "Brother Recovery Outcome",
    659:  "Memory Void Expansion",
    666:  "Yuu Identity Collapse",

    673:  "Post-Ability World Formation",
    680:  "Student Council Dissolution",
    687:  "Lost Memories Consequence",
    694:  "Emotional Aftershock Phase",

    701:  "Yuu Rehabilitation Process",
    708:  "Fragmented Memory Life",
    715:  "Nao Distance Recovery",
    722:  "Normal Life Reconstruction",
    729:  "Emotional Relearning Stage",

    736:  "Residual Ability Echoes",
    743:  "Identity Stabilization Attempt",
    750:  "Brother Survival Outcome Confirmed",

    757:  "World Without Abilities Transition",
    764:  "Emotional Recovery Slow Growth",
    771:  "Student Council Legacy Memory",
    778:  "Zhiend Emotional Anchor Return",

    785:  "Yuu Psychological Healing Phase",
    792:  "Lost Bonds Reconstruction",

    799:  "Ability Era Closure Memory",
    806:  "Human Emotion Rebalancing",
    813:  "Nao Emotional Distance Healing",
    820:  "Yuu Identity Rebuilding",

    827:  "Beyond Ability Trauma",
    834:  "Memory Fragments Integration",
    841:  "Emotional Stability Return",
    848:  "Life Without Powers Acceptance",

    855:  "Final Emotional Clarity",
    862:  "Brother Bond Preservation",
    869:  "Student Council Memory Echo",
    876:  "Peace After Collapse",

    883:  "Absolute Emotional Recovery",
    890:  "Yuu Stable Identity Formed",
    897:  "Nao Relationship Restoration",

    904:  "Beyond Time and Ability",
    911:  "Human Fragile Continuation",
    918:  "Emotional Memory Harmony",
    925:  "Life After Sacrifice",

    932:  "Final World Stability",
    939:  "Identity Fully Rebuilt",
    946:  "Emotional Bonds Reforged",
    953:  "Beyond Loss and Memory",

    960:  "Absolute Emotional Resolution",
    967:  "Charlotte Era Closure",
    974:  "Perfect Memory Balance",
    981:  "Beyond Ability Concept",
    988:  "Absolute Human Fragility",
    995:  "Perfect Charlotte State",
    998:  "Ultimate Emotional Harmony",
    1000:"A Boy Who Once Used Abilities for Himself Learned Through Loss, Time, and Sacrifice That True Power Was Not Changing the World, but Choosing to Endure Its Pain for the Ones You Love—Even If It Meant Forgetting Everything That Made You Strong"
}
}
