import { AnimeThemeConfig } from "./types"
import { GiSpellBook, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiCrystalBall, GiStarSwirl, GiFlowerEmblem } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const chihayafuruTheme: AnimeThemeConfig = {
    id: "chihayafuru",
    displayName: "Chihayafuru",
    description: "Chihaya Ayase discovers karuta — competitive card-matching based on classical poetry — and falls in love with the game. She forms a high school team to reach the national championship and reunite with her childhood friend.",
    cssVars: {
        "--color-brand-200": "175 218 252",
        "--color-brand-300": "112 182 245",
        "--color-brand-400": "58 142 228",
        "--color-brand-500": "18 105 200",
        "--color-brand-600": "5 72 160",
        "--color-brand-700": "1 44 118",
        "--color-brand-800": "0 22 74",
        "--color-brand-900": "0 8 38",
        "--color-brand-950": "0 2 16",
        "--brand": "18 105 200",
        "--background": "#000208",
        "--paper": "#000510",
        "--color-gray-950": "0 2 8",
        "--color-gray-900": "1 6 18",
        "--color-gray-800": "3 14 35",
        "--color-gray-700": "6 26 58",
        "--color-gray-600": "11 46 90",
        "--color-gray-500": "20 76 130",
        "--color-gray-400": "42 116 168",
        "--color-gray-300": "78 156 205",
        "--color-gray-200": "122 192 232",
        "--color-gray-100": "175 220 248",
        "--color-gray-50": "222 242 255",
    },
    sidebarOverrides: {
        "home": { icon: GiFlowerEmblem, label: "Karuta Club" },
        "schedule": { icon: GiAlarmClock, label: "Tournament Schedule" },
        "manga": { icon: LuBookOpen, label: "Poem Archive" },
        "lists": { icon: GiScrollUnfurled, label: "Card Registry" },
        "discover": { icon: GiBullseye, label: "New Rivals" },
        "torrent-list": { icon: GiSpellBook, label: "Poem Cache" },
        "debrid": { icon: GiHeartKey, label: "Club Vault" },
        "unmatched": { icon: GiCrystalBall, label: "Unread Cards" },
        "enmasse": { icon: GiResize, label: "National Tournament" },
        "scan-summaries": { icon: TbReportSearch, label: "Match Reports" },
        "auto-downloader": { icon: LuRss, label: "Tournament Feed" },
        "community": { icon: GiStarSwirl, label: "Karuta Circle" },
        "achievements": { icon: GiTrophyCup, label: "Meijin Trophies" },
        "milestones": { icon: LuFlag, label: "Karuta Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Tournament Alerts" },
        "theme-manager": { icon: GiPalette, label: "Poem Colors" },
        "extensions": { icon: BiExtension, label: "Club Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Club Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Chihaya Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Card Taken",
        "a_episode_counter": "National Tournament Mark",
        "a_episode_titan": "Meijin Challenger Relic",
        "a_hours_invested": "Karuta Fan Proof",
        "a_time_lord": "Poems Decree",
        "a_anime_collector": "She Catalogue",
        "a_library_legend": "Card Taken Library",
        "a_first_complete": "First Tournament",
        "a_hundred_club": "Hundred Poems Memorized",
        "a_first_day": "Meijin Trophies Seal",
        "a_first_rating": "Karuta Appraisal",
        "a_ten_thousand_min": "Elite Standard",
        "a_season_veteran": "Contender Library",
        "a_year_explorer": "Chihaya Map",
        "a_century_watcher": "Beginner Ledger",
        "a_five_hundred_eps": "Memorized Dominion",
        "a_thousand_eps": "Tournament Alerts Record",
        "a_watching_ten": "National Contender Acclaim",
        "a_ptw_hoarder": "Elite Library",
        "a_dropped_honesty": "National Contender Summit",
        "a_five_thousand_eps": "Marathon Warrant",
        "a_ten_completed": "National Afterglow",
        "a_fifty_completed": "Karuta Ascension",
        "a_five_hundred_completed": "Card Taken Clear",
        "a_mean_score_tracker": "Poem Archive Verdict",
        "a_unique_studios": "Challenger Collection",
        "a_days_spent_watching": "Beginner Elite Dominion",
        "a_all_status": "Unread Cards Testament",
        "a_first_favorite": "Tournament Alerts Cabinet",
        "a_favorites_collector": "Tournament Alerts Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Taken Drive",
        "a_marathon_runner": "Challenger Gauntlet",
        "a_weekend_warrior": "Meijin Challenger Ordeal",
        "a_non_stop": "Taken Fever",
        "a_one_more_episode": "Archive Mantle",
        "a_speed_run": "Challenger Vigil",
        "a_double_feature": "Taken Crown",
        "a_triple_threat": "Vault Record",
        "a_five_a_day": "Elite Accord",
        "a_back_to_back": "National Contender Surge",
        "a_seasonal_binge": "Karuta Cascade",
        "a_cour_crusher": "Memorized Ordeal",
        "a_half_day_watch": "National Tournament Crown",
        "a_full_day_watch": "Karuta Fan Pinnacle",
        "a_power_weekend": "Contender Run",
        "a_binge_king": "Chihayafuru Marathon",
        "a_no_sleep": "Poem Archive Vigil",
        "a_entire_season": "Chihaya Ayase Library",
        "a_seven_day_challenge": "Karuta Fan Mark",
        "a_hundred_day_binge": "Meijin Trophies Surge",
        "a_genre_binge": "Tournament Alerts Binge",
        "a_studio_binge": "Meijin Fever",
        "a_season_sweep": "Meijin Challenger Codex",
        "a_forty_eight_hour": "Chihayafuru Marathon Overture",
        "a_ep_counter_day": "Karuta Circle Aegis",
        "a_multi_series_binge": "Elite Streak",
        "a_midnight_binge": "She Cascade",
        "a_new_year_binge": "Card Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Memorized Action",
        "a_genre_adventure": "Karuta Adventure",
        "a_genre_comedy": "National Comedy",
        "a_genre_drama": "Rivals Drama",
        "a_genre_fantasy": "Marathon Fantasy",
        "a_genre_horror": "Marathon Horror",
        "a_genre_mystery": "Karuta Circle Mystery",
        "a_genre_romance": "Karuta Circle Romance",
        "a_genre_scifi": "Meijin Challenger Sci-Fi",
        "a_genre_sol": "Card Registry Slice",
        "a_genre_sports": "Poem Archive Sports",
        "a_genre_supernatural": "Card Registry Supernatural",
        "a_genre_thriller": "Chihayafuru Thriller",
        "a_genre_mecha": "Memorized Mecha",
        "a_genre_music": "Contender Music",
        "a_genre_psychological": "Chihaya Ayase Psychological",
        "a_genre_ecchi": "Poems Memorized Ecchi",
        "a_genre_mahou_shoujo": "Vault Magic Shoujo",
        "a_tag_isekai": "Chihayafuru Marathon Isekai",
        "a_tag_harem": "Marathon Harem",
        "a_tag_bl": "Chihayafuru Marathon Bl",
        "a_tag_gl": "Unread Cards Gl",
        "a_tag_historical": "Poem Historical",
        "a_tag_military": "Match Military",
        "a_tag_school": "Contender School",
        "a_tag_martial_arts": "Karuta Fan Martial Arts",
        "a_tag_vampire": "Karuta Circle Vampire",
        "a_tag_samurai": "Poems Samurai",
        "a_tag_space": "National Space",
        "a_tag_parody": "Karuta Parody",
        "a_tag_idol": "Chihaya Idol",
        "a_tag_post_apocalyptic": "Chihaya Ayase Post Apocalyptic",
        "a_tag_cyberpunk": "Tournament Cyberpunk",
        "a_tag_shounen": "Chihaya Ayase Shounen",
        "a_tag_seinen": "National Contender Seinen",
        "a_tag_shoujo": "Card Taken Shoujo",
        "a_tag_josei": "Karuta Circle Josei",
        "a_tag_survival": "Poems Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "National Contender",
        "a_mega_completionist": "Meijin Challenger",
        "a_completion_rate_50": "Karuta Circle Return",
        "a_completion_rate_75": "Karuta Crown",
        "a_completion_rate_90": "Vault Resolution",
        "a_no_drop": "National Decree",
        "a_long_runner_complete": "Contender Clear",
        "a_sequel_chain": "Beginner Insignia",
        "a_clean_list": "Chihayafuru Relic",
        "a_from_ptw": "Chihayafuru Index",
        "a_rewatch_master": "Poem Archive Return",
        "a_short_complete": "Taken Endgame",
        "a_same_day_start_finish": "Card Registry Pinnacle",
        "a_revival": "Chihaya Ayase Insignia",
        "a_zero_to_hero": "Beginner to Elite",
        "a_five_genre_complete": "Taken A Five Genre Complete",
        "a_full_franchise": "Elite Chronicle",
        "a_batch_complete": "Karuta Crown Crown",
        "a_paused_to_done": "Vault Aegis",
        "a_completion_spree": "Karuta Fan Triumph",
        "a_multi_rewatch": "Meijin Triumph",
        "a_dropped_recovery": "National Tournament Conquest",
        "a_ten_perfect_scores": "Contender Acclaim",
        "a_seasonal_clear": "Match Codex",
        "a_complete_genre_span": "Beginner Elite A Complete Genre",
        "a_monthly_completions": "Chihayafuru Marathon Afterglow",
        "a_yearly_completions": "She Epilogue",
        "a_rapid_complete": "National Tournament Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Karuta Fan",
        "a_studio_devotee": "Vault Treasury",
        "a_rewatcher": "Card Taken Closure",
        "a_triple_rewatch": "Tournament Alerts Coda",
        "a_annual_tradition": "Meijin Proof",
        "a_director_fan": "Chihayafuru Trial",
        "a_voice_actor_fan": "Meijin Crown",
        "a_ost_lover": "Elite Seal",
        "a_source_reader": "Chihaya Cabinet",
        "a_waiting_weekly": "Vault Clock",
        "a_childhood_revisit": "Rivals Seal",
        "a_saga_tracker": "Vault Standard",
        "a_genre_loyalty": "Marathon Loyalty",
        "a_decade_watcher": "Vault Banner",
        "a_adaptation_hunter": "Meijin Challenger Trial",
        "a_original_anime_fan": "She Testament",
        "a_long_commitment": "Karuta Fan Mark Mark",
        "a_perfect_attendance": "Card Taken Standard",
        "a_favorite_studio_5": "Chihaya Ayase Library Library",
        "a_complete_catalog": "Tournament Alerts Seal",
        "a_franchise_collector": "Beginner Archive",
        "a_airing_follower": "National Contender Signal",
        "a_genre_master": "Karuta Master",
        "a_staff_follower": "Chihaya Ayase Oath",
        "a_multi_season_fan": "Poem Hoard",
        "a_format_diversity": "National Cache",
        "a_year_dedication": "Meijin Challenger Tenure",
        "a_season_dedication": "Memorized Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Challenger Explorer",
        "a_studio_hopper": "Chihaya Collection",
        "a_tag_explorer": "Chihayafuru Explorer",
        "a_decade_hopper": "Elite Chronicle Chronicle",
        "a_hidden_gem": "National Tournament Warrant",
        "a_popular_taste": "Chihayafuru Marathon Decree",
        "a_retro_appreciator": "Challenger Aegis",
        "a_modern_viewer": "Marathon Pinnacle",
        "a_cross_demographic": "Tournament Pinnacle",
        "a_underdog_fan": "Memorized Trial",
        "a_variety_week": "Beginner Horizon",
        "a_foreign_cinema": "Archive Expedition",
        "a_classic_connoisseur": "Contender Glimpse",
        "a_every_season": "Card Taken Archive",
        "a_award_winner": "Elite Insignia",
        "a_niche_explorer": "Rivals Horizon",
        "a_global_anime": "Poems Memorized Crown",
        "a_cult_classic": "Chihayafuru Marathon Map",
        "a_random_pick": "Chihaya Decree",
        "a_new_genre_month": "Rivals A New Genre Month",
        "a_seasonal_completionist": "Poem Summit",
        "a_unpopular_opinion": "Poems Standard",
        "a_top_rated_viewer": "Elite Seal Seal",
        "a_source_variety": "Beginner Elite Storehouse",
        "a_low_score_brave": "Tournament Measure",
        "a_upcoming_watcher": "Contender Seal",
        "a_short_series_explorer": "Unread Cards Expedition",
        "a_long_series_explorer": "Taken Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Chihaya Ayase Insignia Insignia",
        "a_early_bird": "Vault Banner Banner",
        "a_lunch_break": "Archive Trial",
        "a_golden_hour": "Match Tenure",
        "a_four_am_club": "Meijin Gathering",
        "a_witching_hour": "Karuta Tenure",
        "a_new_year_watch": "Karuta Season",
        "a_midnight_premiere": "Marathon Devotion",
        "a_all_hours": "Poem Seal",
        "a_dawn_warrior": "Poem Archive Aegis",
        "a_afternoon_delight": "Meijin Proof Proof",
        "a_prime_time": "Elite Insignia Insignia",
        "a_workday_watcher": "Tournament Pinnacle Pinnacle",
        "a_sunday_marathon": "Elite Momentum",
        "a_rainy_day": "Karuta Relic",
        "a_morning_routine": "Poem Promise",
        "a_night_shift": "National Aegis",
        "a_twilight_zone": "Chihaya Ayase Ledger",
        "a_seasonal_premier": "Vault Cabinet",
        "a_clock_collector": "Meijin Repository",
        "a_weekend_binge_hours": "Rivals Streak",
        "a_late_night_regular": "Archive Dominion",
        "a_sunrise_watcher": "Karuta Relic Relic",
        "a_holiday_watcher": "Elite Pact",
        "a_every_day_of_week": "Rivals Ledger",
        "a_monthly_hours": "Poem Archive Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "National Record",
        "a_party_host": "National Record Record",
        "a_social_butterfly": "Poem Archive Company",
        "a_group_binge": "Challenger Sprint",
        "a_party_regular": "Poem Chronicle",
        "a_sync_viewer": "National Tournament Standard",
        "a_commentator": "Poems Record",
        "a_party_marathon": "Tournament Alerts Vigil",
        "a_full_house": "Match Trial",
        "a_community_pillar": "Archive Alliance",
        "a_watch_party_streak": "Poems Vigil",
        "a_diverse_party": "Poem Seal Seal",
        "a_late_night_party": "Archive Testament",
        "a_party_veteran": "Memorized Testament",
        "a_genre_party": "Archive Party",
        "a_weekly_party": "Meijin Calendar",
        "a_silent_viewer": "Unread Cards Mantle",
        "a_recommendation_giver": "Rivals Network",
        "a_party_completionist": "Vault Coda",
        "a_social_scorer": "Meijin Challenger Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Poems Memorized Proof",
        "a_fibonacci": "Karuta Dominion",
        "a_palindrome_day": "Meijin Challenger Relic Relic",
        "a_binary_day": "Card Registry Mark",
        "a_full_moon": "Card Taken Insignia",
        "a_leap_year": "Poems Memorized Devotion",
        "a_time_traveler": "Vault Record Record",
        "a_genre_clash": "Challenger Clash",
        "a_triple_seven": "Chihayafuru Testament",
        "a_thousand_complete": "She Legend",
        "a_pi_episodes": "Tournament Crown",
        "a_synchronicity": "Match Anchor",
        "a_world_record": "National Tournament Warrant Warrant",
        "a_nice": "Contender Chronicle",
        "a_power_level": "Unread Cards Testament Testament",
        "a_answer_42": "Chihaya Standard",
        "a_square_number": "Tournament Alerts Decree",
        "a_prime_count": "Contender Seal Seal",
        "a_matching_date": "Memorized Mantle",
        "a_century_episode": "Taken Mark",
        "a_double_digits": "Meijin Challenger Testament",
        "a_one_two_three": "Poems Memorized Crown Crown",
        "a_lucky_seven": "Meijin Crown Crown",
        "a_all_tens": "Taken Criterion",
        "a_exact_hundred_eps": "National Standard",
        "a_year_match_count": "National Clock",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "National Contender Ledger",
        "a_movie_buff": "Meijin Mark",
        "a_ova_hunter": "Karuta Circle Standard",
        "a_ona_explorer": "Memorized Secret",
        "a_special_watcher": "National Ledger",
        "a_short_king": "Card Registry Crown",
        "a_variety_pack": "Meijin Inquiry",
        "a_film_festival": "Meijin Trophies Chronicle",
        "a_music_video": "Chihaya Ayase Chronicle",
        "a_tv_short": "Challenger Record",
        "a_movie_marathon": "Poems Gauntlet",
        "a_double_length": "Poem Decree",
        "a_anthology": "Karuta Circle Aegis Aegis",
        "a_mini_series": "Tournament Alerts Decree Decree",
        "a_theatrical": "Beginner Accord",
        "a_format_master": "Karuta Fan Vault",
        "a_long_movie": "Beginner Insignia Insignia",
        "a_back_catalog": "Challenger Standard",
        "a_cm_watcher": "Chihayafuru Marathon Aegis",
        "a_pv_collector": "Memorized Storehouse",
        "a_format_balance": "National Tournament Vault",
        "a_episodic_master": "Poem Archive Standard",
        "a_sequel_movie": "Chihaya Ayase Record",
        "a_recap_watcher": "Tournament Alerts Accord",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Karuta Fan Devotion",
        "a_mega_streak": "Vault Streak",
        "a_weekly_warrior": "Beginner Elite Season",
        "a_monthly_watcher": "Card Calendar",
        "a_comeback": "Chihayafuru Marathon Decree Decree",
        "a_weekend_streak": "Tournament Passage",
        "a_no_zero_days": "Card Registry Warrant",
        "a_iron_will": "Unread Cards Warrant",
        "a_habit_formed": "Card Warrant",
        "a_consistent_pace": "Taken Measure",
        "a_year_long": "Beginner Elite Yearlong",
        "a_double_streak": "Karuta Watch",
        "a_streak_recovery": "Unread Cards Season",
        "a_daily_minimum": "Card Focus",
        "a_winter_streak": "Unread Cards Watch",
        "a_summer_streak": "Chihayafuru Resolve",
        "a_morning_streak": "Challenger Clock",
        "a_night_streak": "National Contender Constancy",
        "a_unbreakable": "Marathon Proof",
        "a_eternal_flame": "Chihaya Standard Standard",
        "a_completion_streak": "Karuta Circle Return Return",
        "a_rating_streak": "Karuta Balance",
        "a_multi_ep_streak": "National Tournament Ritual",
        "a_genre_streak": "Karuta Streak",
        "a_studio_streak": "Chihayafuru Marathon Cabinet",
        "a_perfect_week": "Match Relic",

        // ── ANIME SCORING ──
        "a_critic": "Meijin Scrutiny",
        "a_perfect_ten": "Vault Audit",
        "a_harsh_critic": "National Contender Gauge",
        "a_fair_judge": "Unread Cards Balance",
        "a_generous_spirit": "Card Pinnacle",
        "a_score_all": "Karuta Fan Criterion",
        "a_wide_range": "Elite Ledger",
        "a_controversial": "Challenger Decree",
        "a_consistent_scorer": "Karuta Circle Verdict",
        "a_score_sniper": "Taken Score",
        "a_evolving_taste": "Karuta Testament",
        "a_bell_curve": "Rivals Insignia",
        "a_picky_watcher": "Archive Warrant",
        "a_100_rated": "Karuta Fan Warrant",
        "a_500_rated": "Card Pinnacle Pinnacle",
        "a_mediocre_majority": "Match Canon",
        "a_rating_spree": "Challenger Review",
        "a_score_variance": "Tournament Score",
        "a_masterpiece_hunter": "Tournament Alerts Banner",
        "a_contrarian": "Challenger Record Record",
        "a_optimist": "Poem Ledger",
        "a_score_distributor": "Archive Appraisal",
        "a_genre_critic": "Poems Memorized Critic",
        "a_mean_above_8": "Karuta Fan Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "Beginner Elite Resolve",
        "a_valentines_weeb": "Beginner Vow",
        "a_pi_day": "Unread Cards Trial",
        "a_april_fools": "Tournament Devotion",
        "a_international_anime_day": "Poems Memorized Pinnacle",
        "a_star_wars_day": "Archive Proof",
        "a_summer_solstice": "Card Registry Calendar",
        "a_tanabata": "Card Registry Focus",
        "a_friday_13th": "Unread Cards Relic",
        "a_halloween_spirit": "National Contender Vow",
        "a_thanksgiving_binge": "Poem Run",
        "a_christmas_special": "She Season",
        "a_new_years_eve": "Karuta Fan Pilgrimage",
        "a_birthday_watch": "National Contender Birthday",
        "a_holiday_marathon": "Tournament Alerts Overture",
        "a_independence_day": "Chihaya Banner",
        "a_culture_day": "Contender Insignia",
        "a_spring_equinox": "Poems Decree Decree",
        "a_earth_day": "Karuta Fan Mantle",
        "a_labor_day": "National Contender Seal",
        "a_winter_solstice": "Taken Pilgrimage",
        "a_anime_birthday": "Meijin Pilgrimage",
        "a_every_holiday": "Karuta Resolve",
        "a_consecutive_holidays": "Karuta Season Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Chihaya Rank",
        "a_meta_collector": "Contender Hoard",
        "a_meta_category_starter": "Card Badge",
        "a_meta_tier_climber": "Meijin Trophies Glyph",
        "a_meta_tier_max": "Contender Writ",
        "a_meta_xp_earner": "She Emblem",
        "a_meta_difficulty_easy": "She Mechanism",
        "a_meta_difficulty_hard": "Contender Writ Writ",
        "a_meta_unlock_spree": "Match Panel",
        "a_meta_completionist": "National Tournament Fulfillment",
        "a_meta_diverse": "Chihayafuru Emblem",
        "a_meta_dominator": "Beginner Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Poem",
        "m_chapter_counter": "Meijin Pinnacle",
        "m_chapter_titan": "Memorized Relic",
        "m_reading_hours": "She Relic",
        "m_reading_time_lord": "Poems Memorized Pinnacle Pinnacle",
        "m_manga_collector": "Match Ledger",
        "m_library_legend": "Contender Reliquary",
        "m_first_complete": "Meijin Triumph Triumph",
        "m_hundred_club": "Chihaya Ayase Network",
        "m_first_day": "Chihaya Ayase Seal",
        "m_first_rating": "Archive Eye",
        "m_ten_thousand_pages": "Beginner Gauge",
        "m_volume_collector": "Unread Cards Storehouse",
        "m_year_explorer": "Chihaya Quest",
        "m_century_reader": "Archive Dominion Dominion",
        "m_five_hundred_ch": "Contender Ledger",
        "m_thousand_ch": "Chihayafuru Legend",
        "m_reading_ten": "Archive Tenfold",
        "m_ptr_hoarder": "Meijin Challenger Index",
        "m_dropped_honesty": "Contender Summit",
        "m_season_reader": "Tournament Alerts Treasury",
        "m_active_reader": "Chihayafuru Trial Trial",
        "m_five_thousand_ch": "Challenger Legend",
        "m_ten_completed": "Tournament Alerts Resolution",
        "m_fifty_completed": "Chihayafuru Harvest",
        "m_five_hundred_completed": "Rivals Legacy",
        "m_mean_score_tracker": "Vault Audit Audit",
        "m_unique_authors": "National Tournament Reserve",
        "m_all_status": "Karuta Testament Testament",
        "m_first_favorite": "Karuta Circle Cache",
        "m_favorites_collector": "Poem Archive Shelf",
        "m_days_spent_reading": "Chihaya Decree Decree",

        // ── MANGA BINGE ──
        "m_binge_reader": "National Contender Streak",
        "m_marathon_reader": "Archive Rush",
        "m_weekend_reader": "National Contender Run",
        "m_non_stop_reading": "Vault Gauntlet",
        "m_one_more_chapter": "Tournament Alerts Accord Accord",
        "m_speed_read": "Marathon Drive",
        "m_double_story": "Challenger Banner",
        "m_triple_read": "Poem Archive Record",
        "m_five_a_day": "Chihayafuru Pinnacle",
        "m_chapter_chain": "Contender Accord",
        "m_volume_binge": "Tournament Drive",
        "m_power_reader": "Meijin Trophies Seal Seal",
        "m_half_day_read": "Chihayafuru Marathon Aegis Aegis",
        "m_full_day_read": "Poem Archive Aegis Aegis",
        "m_power_weekend": "Beginner Streak",
        "m_binge_king": "Card Taken Momentum",
        "m_no_sleep_read": "Archive Sleepless",
        "m_full_series_rush": "Unread Cards Cascade",
        "m_seven_day_challenge": "Card Warrant Warrant",
        "m_hundred_day_read": "Chihayafuru Legend Relic",
        "m_volume_rush": "National Gauntlet",
        "m_series_sweep": "Karuta Trial",
        "m_genre_binge": "Chihaya Binge",
        "m_author_binge": "Rivals Surge",
        "m_chapter_counter_day": "Chihaya Ayase Ledger Ledger",
        "m_multi_series_binge": "Elite Charge",
        "m_midnight_binge": "Chihayafuru Tempest",
        "m_new_year_binge": "Meijin Passage",
        "m_forty_eight_hour": "Karuta Circle Rally",
        "m_oneshot_binge": "Card Taken Sprint",

        // ── MANGA GENRES ──
        "m_genre_action": "Chihayafuru Action",
        "m_genre_adventure": "Meijin Challenger Adventure",
        "m_genre_comedy": "Chihaya Comedy",
        "m_genre_drama": "Beginner Drama",
        "m_genre_fantasy": "Taken Fantasy",
        "m_genre_horror": "Marathon Horror Pulse",
        "m_genre_mystery": "Tournament Alerts Mystery",
        "m_genre_romance": "Vault Romance",
        "m_genre_scifi": "Match Sci-Fi",
        "m_genre_sol": "Meijin Slice",
        "m_genre_sports": "National Sports",
        "m_genre_supernatural": "National Tournament Supernatural",
        "m_genre_thriller": "Memorized Thriller",
        "m_genre_psychological": "National Contender Psychological",
        "m_genre_isekai": "Beginner Elite Isekai",
        "m_genre_shounen": "Beginner Elite Shounen",
        "m_genre_ecchi": "Taken Ecchi",
        "m_genre_mahou_shoujo": "Poem Archive Magic Shoujo",
        "m_genre_mecha": "Archive Mecha",
        "m_genre_music": "Card Taken Music",
        "m_tag_isekai_new": "She Isekai New",
        "m_tag_harem": "National Tournament Harem",
        "m_tag_bl": "Challenger Bl",
        "m_tag_gl": "Meijin Challenger Gl",
        "m_tag_historical": "Elite Historical",
        "m_tag_military": "Memorized Military",
        "m_tag_school": "Chihaya Ayase School",
        "m_tag_martial_arts": "Karuta Fan Martial Arts Canon",
        "m_tag_vampire": "National Vampire",
        "m_tag_samurai": "National Samurai",
        "m_tag_space": "Poems Space",
        "m_tag_parody": "Unread Cards Parody",
        "m_tag_idol": "Tournament Alerts Idol",
        "m_tag_post_apocalyptic": "Meijin Trophies Post Apocalyptic",
        "m_tag_cyberpunk": "National Tournament Cyberpunk",
        "m_tag_shoujo": "Contender Shoujo",
        "m_tag_survival": "Chihaya Survival",
        "m_tag_cooking": "Card Taken Cooking",
        "m_tag_medical": "Karuta Medical",
        "m_tag_villainess": "Card Taken Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Poem Archive",
        "m_mega_completionist": "Tournament Alerts Completion",
        "m_completion_rate_50": "Poems Return",
        "m_completion_rate_75": "Match Ascension",
        "m_completion_rate_90": "Poem Archive Resolution",
        "m_no_drop": "National Decree Decree",
        "m_long_runner_complete": "Chihaya Ayase Clear",
        "m_sequel_chain": "Card Taken Seal",
        "m_clean_list": "Match Relic Relic",
        "m_from_ptr": "Elite Watchlist",
        "m_reread_master": "Unread Cards Trial Trial",
        "m_oneshot_complete": "She Ascension",
        "m_same_day_start_finish": "Contender Decree",
        "m_revival": "Poem Accord",
        "m_zero_to_hundred": "Poems Banner",
        "m_five_genre_complete": "Card Registry M Five Genre",
        "m_full_collection": "Karuta Fan Proof Proof",
        "m_batch_complete": "National Summit",
        "m_paused_to_done": "Poem Archive Standard Standard",
        "m_completion_spree": "Marathon Triumph",
        "m_format_completionist": "Unread Cards Completion",
        "m_catch_up": "Chihaya Ayase Chronicle Chronicle",
        "m_multi_reread": "Meijin Dominion",
        "m_dropped_recovery": "Poems Memorized Conquest",
        "m_ten_perfect_scores": "Card Taken Judgment",
        "m_complete_genre_span": "Match M Complete Genre Span",
        "m_monthly_completions": "Poem Archive Monthly",
        "m_yearly_completions": "Beginner Elite Epilogue",
        "m_rapid_complete": "Card Finale",
        "m_author_complete": "Beginner Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Elite Legacy",
        "m_mangaka_lover": "National Standard Standard",
        "m_rereader": "Archive Relic",
        "m_triple_reread": "Meijin Challenger Testament Testament",
        "m_annual_reread": "Challenger Banner Banner",
        "m_publisher_fan": "Card Mark",
        "m_artist_fan": "National Contender Insignia",
        "m_adaptation_compare": "Card Taken Insignia Insignia",
        "m_source_material_fan": "Poem Archive Cache",
        "m_waiting_weekly": "Karuta Circle Streak",
        "m_classic_reader": "Unread Cards Lantern",
        "m_saga_reader": "Contender Decree Decree",
        "m_genre_loyalty": "Taken Loyalty",
        "m_decade_reader": "Taken Warrant",
        "m_ln_adaptation": "Tournament Mark",
        "m_original_work": "Vault Standard Standard",
        "m_long_commitment": "Tournament Mark Mark",
        "m_up_to_date": "Karuta Fan Warrant Warrant",
        "m_favorite_mangaka": "Chihayafuru Marathon Treasury",
        "m_complete_portfolio": "Marathon Triumph Triumph",
        "m_franchise_collector": "Beginner Archive Archive",
        "m_serialization_follower": "Chihaya Handshake",
        "m_genre_master": "Match Master",
        "m_multi_series_author": "Meijin Trophies Insignia",
        "m_format_diversity": "Karuta Circle Shelf",
        "m_year_dedication": "Archive Tenure",
        "m_ongoing_follower": "Tournament Fellowship",
        "m_genre_loyalty_50": "Karuta Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Tournament Alerts Explorer",
        "m_publisher_hopper": "Tournament Alerts Record Record",
        "m_tag_explorer": "Meijin Challenger Explorer",
        "m_decade_hopper": "Meijin Trophies Chronicle Chronicle",
        "m_hidden_gem": "Chihaya Ayase Standard",
        "m_popular_taste": "Karuta Fan Mantle Mantle",
        "m_retro_reader": "Vault Accord",
        "m_modern_reader": "She Warrant",
        "m_cross_demographic": "Card Registry Crown Crown",
        "m_underdog_fan": "Vault Accord Accord",
        "m_variety_week": "National Contender Horizon",
        "m_manhwa_reader": "Taken Proof",
        "m_manhua_reader": "She Mantle",
        "m_classic_connoisseur": "Rivals Glimpse",
        "m_award_winner": "Archive Warrant Warrant",
        "m_niche_explorer": "Card Taken Horizon",
        "m_world_manga": "Poem Chronicle Chronicle",
        "m_cult_classic": "National Map",
        "m_random_pick": "Karuta Fan Testament",
        "m_new_genre_month": "Beginner M New Genre Month",
        "m_year_completionist": "Karuta Fan Fulfillment",
        "m_unpopular_opinion": "National Aegis Aegis",
        "m_top_rated_reader": "Marathon Pinnacle Pinnacle",
        "m_source_variety": "She Catalogue Catalogue",
        "m_low_score_brave": "National Tournament Score",
        "m_short_manga_explorer": "Contender Compass",
        "m_long_manga_explorer": "Tournament Alerts Survey",
        "m_serialization_explorer": "Match Road",

        // ── MANGA TIME ──
        "m_night_owl": "National Contender Accord",
        "m_early_bird": "Poem Archive Banner",
        "m_lunch_reader": "Unread Cards Relic Relic",
        "m_commute_reader": "Meijin Challenger Tenure Tenure",
        "m_four_am_club": "Marathon Fellowship",
        "m_new_year_read": "National Contender Pact",
        "m_all_hours": "Meijin Trophies Accord",
        "m_prime_time_reader": "Karuta Circle Banner",
        "m_workday_reader": "Chihaya Ayase Accord",
        "m_sunday_read": "Tournament Alerts Standard",
        "m_morning_routine": "Chihaya Ayase Discipline",
        "m_night_shift_reader": "Poem Accord Accord",
        "m_seasonal_premier_read": "Unread Cards Seasonal",
        "m_clock_collector": "Poems Memorized Reserve",
        "m_late_night_horror": "Marathon Mark",
        "m_afternoon_reader": "Archive Mantle Mantle",
        "m_golden_hour_reader": "Meijin Challenger Observance",
        "m_dawn_reader": "Chihayafuru Mantle",
        "m_twilight_reader": "Tournament Crown Crown",
        "m_midnight_start": "Vault Routine",
        "m_weekend_binge_hours": "Card Taken Momentum Momentum",
        "m_late_night_regular": "Card Mark Mark",
        "m_sunrise_reader": "Meijin Trophies Insignia Insignia",
        "m_every_day_of_week": "She Warrant Warrant",
        "m_monthly_hours": "Poems Monthly",
        "m_bedtime_reader": "Elite Banner",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Challenger Insignia",
        "m_webtoon_reader": "Poems Memorized Mark",
        "m_full_color": "Card Taken Accord",
        "m_doujin_reader": "Chihayafuru Marathon Record",
        "m_anthology_reader": "Card Taken Accord Accord",
        "m_adaptation_reader": "Meijin Dominion Dominion",
        "m_longstrip_reader": "Meijin Challenger Trial Trial",
        "m_4koma_reader": "Vault Ledger",
        "m_oneshot_reader": "Match Mantle",
        "m_format_variety": "Card Registry Gallery",
        "m_light_novel_reader": "Contender Insignia Insignia",
        "m_novel_reader": "Tournament Alerts Ledger",
        "m_visual_storyteller": "Archive Testament Testament",
        "m_colored_classic": "Challenger Survey",
        "m_webcomic_fan": "Rivals Insignia Insignia",
        "m_manga_to_anime": "Poem Archive Record Record",
        "m_seinen_reader": "Poem Record",
        "m_josei_reader": "Meijin Pinnacle Pinnacle",
        "m_award_winning_art": "Chihaya Ledger",
        "m_debut_work": "Memorized Dominion Dominion",
        "m_vertical_scroll": "National Tournament Crown Crown",
        "m_traditional_format": "Rivals Hoard",
        "m_cross_media": "Contender Accord Accord",
        "m_spinoff_reader": "Chihaya Ayase Accord Accord",
        "m_remake_reader": "Archive Pinnacle",
        "m_collaboration_reader": "Rivals Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Card Daily",
        "m_mega_streak": "Poems Routine",
        "m_weekly_warrior": "Beginner Elite Weekly",
        "m_monthly_reader": "Poem Discipline",
        "m_comeback": "Tournament Alerts Standard Standard",
        "m_weekend_streak": "Meijin Fever Fever",
        "m_no_zero_days": "Poems Memorized Proof Proof",
        "m_iron_will": "Card Taken Ledger",
        "m_habit_formed": "National Contender Decree",
        "m_consistent_pace": "National Tournament Scrutiny",
        "m_year_long": "Chihayafuru Observance",
        "m_double_streak": "Match Resolve",
        "m_streak_recovery": "Memorized Resolve",
        "m_daily_minimum": "Poems Memorized Focus",
        "m_winter_streak": "Karuta Observance",
        "m_summer_streak": "Beginner Elite Observance",
        "m_morning_streak": "Challenger Clock Clock",
        "m_night_streak": "National Contender Discipline",
        "m_unbreakable": "Meijin Trophies Banner",
        "m_eternal_flame": "Chihaya Record",
        "m_chapter_a_day": "Tournament Alerts Ledger Ledger",
        "m_genre_streak": "Meijin Challenger Streak",
        "m_completion_streak": "National Return",
        "m_rating_streak": "Chihayafuru Appraisal",
        "m_multi_ch_streak": "Match Tenure Tenure",
        "m_author_streak": "Taken Calendar",
        "m_perfect_week_manga": "Meijin Challenger Mark",
        "m_diverse_streak": "Vault Streak Streak",

        // ── MANGA SCORING ──
        "m_critic": "Poems Memorized Scrutiny",
        "m_perfect_ten": "Chihayafuru Marathon Verdict",
        "m_harsh_critic": "Elite Scale",
        "m_fair_judge": "Unread Cards Eye",
        "m_generous_spirit": "Card Crown",
        "m_score_all": "Poems Memorized Reckoning",
        "m_wide_range": "Poem Ledger Ledger",
        "m_controversial": "Poems Memorized Testament",
        "m_consistent_scorer": "Chihayafuru Marathon Grade",
        "m_score_sniper": "Karuta Fan Reckoning",
        "m_evolving_taste": "Match Trial Trial",
        "m_bell_curve": "Beginner Accord Accord",
        "m_picky_reader": "National Ledger Ledger",
        "m_100_rated": "Taken Mark Mark",
        "m_500_rated": "Taken Proof Proof",
        "m_mediocre_majority": "Beginner Elite Canon",
        "m_rating_spree": "Tournament Alerts Verdict",
        "m_score_variance": "Meijin Measure",
        "m_binge_rater": "Taken Passage Passage",
        "m_reread_rerate": "Tournament Alerts Banner Banner",
        "m_masterpiece_hunter": "Poem Archive Banner Banner",
        "m_contrarian": "Karuta Fan Trial",
        "m_optimist": "Elite Accord Accord",
        "m_score_distributor": "Memorized Balance",
        "m_genre_critic": "Taken Critic",
        "m_mean_above_8": "Karuta Fan Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Archive Season",
        "m_valentines_read": "Chihayafuru Valentine",
        "m_pi_day": "Beginner Elite Testament",
        "m_april_fools": "Meijin Devotion",
        "m_international_manga_day": "Meijin Trophies Aegis",
        "m_free_comic_day": "Rivals Chronicle Chronicle",
        "m_summer_solstice": "Card Registry Focus Focus",
        "m_tanabata": "National Tournament Pilgrimage",
        "m_friday_13th": "Unread Cards Dominion",
        "m_halloween_read": "Card Halloween",
        "m_thanksgiving_binge": "Poem Charge",
        "m_christmas_read": "Beginner Pact",
        "m_new_years_eve": "Card Registry Pilgrimage",
        "m_birthday_read": "Tournament Focus",
        "m_holiday_marathon": "Chihayafuru Marathon Rally",
        "m_independence_day": "Vault Aegis Aegis",
        "m_culture_day": "Karuta Warrant",
        "m_spring_equinox": "Card Registry Dominion",
        "m_earth_day": "Chihaya Aegis",
        "m_labor_day": "Beginner Seal",
        "m_winter_solstice": "National Contender Vigil",
        "m_manga_birthday": "Karuta Fan Ritual",
        "m_every_holiday_reader": "Match Watch",
        "m_consecutive_holidays": "She Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Meijin Trophies Aegis Aegis",
        "m_fibonacci": "Meijin Challenger Dominion",
        "m_palindrome_day": "Chihaya Ledger Ledger",
        "m_binary_day": "Card Registry Proof",
        "m_full_moon_read": "Elite Decree",
        "m_leap_year_read": "Karuta Circle Practice",
        "m_triple_seven": "Tournament Alerts Chronicle",
        "m_thousand_complete": "Archive Ascension",
        "m_nice": "Card Registry Dominion Dominion",
        "m_power_level_chapters": "Challenger Aegis Aegis",
        "m_answer_42": "Meijin Trial",
        "m_square_number": "Chihayafuru Marathon Standard",
        "m_prime_count": "Unread Cards Pinnacle",
        "m_matching_date": "Memorized Mantle Mantle",
        "m_century_chapter": "Elite Decree Decree",
        "m_pi_chapters": "Beginner Aegis",
        "m_synchronicity": "Karuta Emblem",
        "m_world_record": "Tournament Warrant",
        "m_genre_clash": "Karuta Circle Clash",
        "m_time_traveler": "Poem Archive Decree",
        "m_double_digits": "Challenger Seal",
        "m_one_two_three": "Card Registry Warrant Warrant",
        "m_lucky_seven": "Rivals Record",
        "m_exact_hundred_ch": "Karuta Legend",
        "m_year_match_count": "Karuta Circle Routine",
        "m_chapter_match_date": "Card Registry Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "She Index",
        "m_manhwa_format": "Card Registry Gallery Gallery",
        "m_manhua_format": "Chihayafuru Storehouse",
        "m_ln_format": "She Index Index",
        "m_oneshot_format": "Memorized Index",
        "m_doujin_format": "Tournament Alerts Cabinet Cabinet",
        "m_novel_format": "National Tournament Reserve Reserve",
        "m_format_master_manga": "Challenger Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Poem Archive Link",
        "m_meta_collector": "Poem Reliquary",
        "m_meta_category_starter": "Marathon Standard",
        "m_meta_tier_climber": "Contender Token",
        "m_meta_tier_max": "Elite Token",
        "m_meta_xp_earner": "Archive Anchor",
        "m_meta_difficulty_easy": "Unread Cards Panel",
        "m_meta_difficulty_hard": "Archive Node",
        "m_meta_unlock_spree": "Archive Marker",
        "m_meta_completionist": "Marathon Completion",
        "m_meta_diverse": "Match Anchor Anchor",
        "m_meta_dominator": "Meijin Trophies Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#000208",
        primary: "#1269c8",
        secondary: "#cc4488",
        accent: "#b8d8f8",
    },
    particleColor: "#4090d8",
    backgroundDim: 0.28,
    backgroundBlur: 20,
    milestoneNames: {
  1: "Threadbare Generic Rank Spark",
  8: "Generic's Tarnished Omen",
  14: "Fractured Generic Rank",
  21: "Generic Rank Path",
  28: "Lowborn Legacy Myth",
  35: "Generic Rank Pulse",
  41: "Generic's Legacy Crest",
  48: "Humble Generic Mark",
  55: "Ragged Generic Rank Vow",
  61: "Generic's Faint Echo",
  68: "Lesser Generic Rank",
  75: "Generic Rank Zenith",
  81: "Doubtful Legacy Bloom",
  88: "Generic Rank Sigil",
  95: "Generic's Legacy Flame",
  102: "Really Cool Generic Spark",
  108: "Awakened Generic Rank Omen",
  115: "Generic's Resolute Seal",
  122: "Rising Generic Rank",
  128: "Generic Rank Myth",
  135: "Dauntless Legacy Pulse",
  142: "Generic Rank Crest",
  149: "Generic's Legacy Mark",
  155: "Fresh Generic Vow",
  162: "Valiant Generic Rank Echo",
  169: "Generic's Prime Crown",
  175: "Polished Generic Rank",
  182: "Generic Rank Bloom",
  189: "Stormlit Legacy Sigil",
  195: "Generic Rank Flame",
  202: "Generic's Legacy Spark",
  209: "Tempered Generic Omen",
  216: "Trusted Generic Rank Seal",
  222: "Generic's Steadfast Path",
  229: "Ironclad Generic Rank",
  236: "Veteran Legacy Pulse",
  242: "Core Legacy Crest",
  249: "Generic Rank Mark",
  256: "Generic's Legacy Vow",
  262: "Formidable Generic Echo",
  269: "Lucid Generic Rank Crown",
  276: "Generic's Ranked Zenith",
  283: "Fabled Generic Rank",
  289: "Grand Legacy Sigil",
  296: "Seasoned Legacy Flame",
  303: "Generic Rank Spark",
  309: "Generic's Legacy Omen",
  316: "Valorous Generic Seal",
  323: "Stalwart Generic Rank Path",
  330: "Generic's Commanding Myth",
  336: "Refined Generic Rank",
  343: "Unbroken Legacy Crest",
  350: "Blazing Legacy Mark",
  356: "Generic Rank Vow",
  363: "Generic's Legacy Echo",
  370: "Peerless Generic Crown",
  376: "Ardent Generic Rank Zenith",
  383: "Generic's Focused Bloom",
  390: "Vigilant Generic Rank",
  397: "Dominant Legacy Flame",
  403: "Elite Legacy Spark",
  410: "Generic Rank Omen",
  417: "Generic's Legacy Seal",
  423: "Sovereign Generic Path",
  430: "Regal Generic Rank Myth",
  437: "Generic's Crowned Pulse",
  444: "Mythborn Generic Rank",
  450: "Limitless Legacy Mark",
  457: "Radiant Legacy Vow",
  464: "Generic Rank Echo",
  470: "Generic's Legacy Crown",
  477: "Climactic Generic Zenith",
  484: "Epic Generic Rank Bloom",
  490: "Generic's Unreal Sigil",
  497: "Peak Generic Rank",
  504: "Supreme Legacy Spark",
  511: "Exalted Legacy Omen",
  517: "Generic Rank Seal",
  524: "Generic's Legacy Path",
  531: "Celestial Generic Myth",
  537: "Phantom Generic Rank Pulse",
  544: "Generic's Crimson Crest",
  551: "Silver Generic Rank",
  557: "Golden Legacy Vow",
  564: "Feral Legacy Echo",
  571: "Generic Rank Crown",
  578: "Generic's Legacy Zenith",
  584: "Dread Generic Bloom",
  591: "Luminous Generic Rank Sigil",
  598: "Generic's Thunderous Flame",
  604: "Ultraviolet Generic Rank",
  611: "Unleashed Legacy Omen",
  618: "Secret Legacy Seal",
  625: "Final Generic Path",
  631: "Generic's Legacy Myth",
  638: "Worldclass Generic Pulse",
  645: "Lawless Generic Rank Crest",
  651: "Generic's Chosen Mark",
  658: "Fearless Generic Rank",
  665: "Overdrive Legacy Echo",
  671: "Cinematic Legacy Crown",
  678: "Impossible Generic Zenith",
  685: "Generic's Legacy Bloom",
  692: "Canonized Generic Sigil",
  698: "Ascendant Generic Rank Flame",
  705: "Generic's Transfigured Spark",
  712: "Immortal Generic Rank",
  718: "Eclipsed Legacy Seal",
  725: "Astral Legacy Path",
  732: "Sublime Generic Myth",
  739: "Generic's Legacy Pulse",
  745: "Prismatic Generic Crest",
  752: "Abyssal Generic Rank Mark",
  759: "Generic's Unbound Vow",
  765: "Eternal Generic Rank",
  772: "Cosmic Legacy Crown",
  779: "Transcendent Legacy Zenith",
  785: "Perfected Generic Bloom",
  792: "Generic's Legacy Sigil",
  799: "Ultimate Generic Flame",
  806: "Mythic Generic Rank Spark",
  812: "Generic's Godlike Omen",
  819: "Canonical Generic Rank",
  826: "Reality-Bent Legacy Path",
  832: "Heavenly Legacy Myth",
  839: "Absolute Generic Pulse",
  846: "Untouchable Generic Crest",
  852: "Timeless Generic Mark",
  859: "Empyrean Generic Rank Vow",
  866: "Generic's Primordial Echo",
  873: "Omniscient Generic Rank",
  879: "Unfathomed Legacy Zenith",
  886: "Apocalyptic Legacy Bloom",
  893: "Seraphic Generic Sigil",
  899: "Omega Generic Flame",
  906: "Final Generic Spark",
  913: "Crowned Generic Rank Omen",
  920: "Generic's Mythic Seal",
  926: "Absolute Generic Rank",
  933: "Eternal Legacy Myth",
  940: "Cosmic Legacy Pulse",
  946: "Transcendent Generic Crest",
  953: "Perfected Generic Mark",
  960: "Definitive Generic Vow",
  966: "Ultimate Generic Rank Echo",
  973: "Generic's Infinite Crown",
  980: "Sovereign Generic Rank",
  987: "Celestial Legacy Bloom",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate Generic Rank"
},
}
