import { AnimeThemeConfig } from "./types"
import { GiScrollUnfurled, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiSpellBook, GiHeartKey, GiCrystalBall, GiMagnifyingGlass } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const classroomOfTheEliteTheme: AnimeThemeConfig = {
    id: "classroom-of-the-elite",
    displayName: "Classroom of the Elite",
    description: "Tokyo Metropolitan Advanced Nurturing High School rewards ability with points. In Class D — the lowest — Kiyotaka Ayanokoji hides extraordinary intellect, manipulating events from the shadows.",
    cssVars: {
        "--color-brand-200": "185 195 225",
        "--color-brand-300": "130 148 200",
        "--color-brand-400": "80 100 175",
        "--color-brand-500": "42 62 148",
        "--color-brand-600": "24 38 115",
        "--color-brand-700": "12 22 82",
        "--color-brand-800": "5 11 52",
        "--color-brand-900": "2 5 28",
        "--color-brand-950": "0 1 12",
        "--brand": "42 62 148",
        "--background": "#000208",
        "--paper": "#01040e",
        "--color-gray-950": "0 2 8",
        "--color-gray-900": "2 5 18",
        "--color-gray-800": "5 12 36",
        "--color-gray-700": "10 22 60",
        "--color-gray-600": "18 40 90",
        "--color-gray-500": "30 68 122",
        "--color-gray-400": "55 105 162",
        "--color-gray-300": "90 148 198",
        "--color-gray-200": "135 188 225",
        "--color-gray-100": "185 218 242",
        "--color-gray-50": "225 240 252",
    },
    sidebarOverrides: {
        "home": { icon: GiSpellBook, label: "ANHS Campus" },
        "schedule": { icon: GiAlarmClock, label: "Exam Schedule" },
        "manga": { icon: LuBookOpen, label: "Strategy Archive" },
        "lists": { icon: GiScrollUnfurled, label: "Class Rankings" },
        "discover": { icon: GiBullseye, label: "Discover Elites" },
        "torrent-list": { icon: GiCrystalBall, label: "Point Cache" },
        "debrid": { icon: GiHeartKey, label: "Secret Vault" },
        "unmatched": { icon: GiMagnifyingGlass, label: "Hidden Players" },
        "enmasse": { icon: GiResize, label: "Class Operation" },
        "scan-summaries": { icon: TbReportSearch, label: "Exam Reports" },
        "auto-downloader": { icon: LuRss, label: "Point Alerts" },
        "community": { icon: GiPalette, label: "Class Circle" },
        "achievements": { icon: GiTrophyCup, label: "Academic Trophies" },
        "milestones": { icon: LuFlag, label: "Class Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Exam Alerts" },
        "theme-manager": { icon: GiPalette, label: "Class Colors" },
        "extensions": { icon: BiExtension, label: "Strategy Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Class Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Ayanokoji Config" },
    },
    achievementNames: {
        "a_first_episode": "First Day at ANHS",
        "a_first_complete": "Exam Passed",
        "a_hundred_club": "Hundred Points Earned",
        "a_binge_king": "COTE Marathon",
        "a_completionist": "All Exams Cleared",
        "a_mega_completionist": "Class A Achiever",
        "a_loyal_fan": "Loyal Student",
        "a_zero_to_hero": "Class D to Class A",
        "m_first_chapter": "First Study Session",
        "m_completionist": "Full Light Novel",
    },
    musicUrl: "",
    previewColors: {
        bg: "#000208",
        primary: "#2a3e94",
        secondary: "#1e3060",
        accent: "#c8a000",
    },
    particleColor: "#3a50c0",
    backgroundDim: 0.30,
    backgroundBlur: 20,
    milestoneNames: {
    1:    "Kiyotaka Ayanokōji Enrollment at Advanced Nurturing High",
    8:    "Class D Placement and System Introduction",
    15:   "Sudo Conflict Early Social Pressure",
    22:   "Class Hierarchy Awareness Begins",
    29:   "Horikita Strategic Personality Exposure",

    36:   "Class Competition System Explanation",
    43:   "Private Points Economy Understanding",
    50:   "Hidden Ability Observation Phase",
    57:   "Ayanokōji Passive Behavior Masking",
    64:   "Initial Class D Instability",

    71:   "Sports Festival Strategic Manipulation",
    78:   "Class Survival Pressure Increase",
    85:   "Horikita Leadership Development",
    92:   "Ayanokōji Subtle Influence Emergence",
    99:   "Social Structure Exploitation Awareness",

    106:  "Class Points Recovery Strategy",
    113:  "Rival Class Tactical Observation",
    120:  "Student Council Power Dynamics",
    127:  "Kushida Dual Personality Hint",
    134:  "Hidden Talent Detection Phase",

    141:  "Class Competition Escalation",
    148:  "Island Survival Exam Introduction",
    155:  "Psychological Pressure Experiment",
    162:  "Trust vs Utility Conflict",
    169:  "Strategic Alliance Formation",

    176:  "Ayanokōji Strategic Calculations Reveal",
    183:  "Class D Survival Instinct Growth",
    190:  "Kushida Manipulation Awareness",
    197:  "Inter-Class Betrayal Signs",
    204:  "System Exploitation Techniques",

    211:  "Cruise Ship Special Exam Arc",
    218:  "White Room Mystery Hints",
    225:  "Class Hierarchy Collapse Risk",
    232:  "Strategic Sacrifice Planning",
    239:  "Psychological Warfare Intensifies",

    246:  "Ayanokōji Competence Suspicion",
    253:  "Horikita Independence Growth",
    260:  "Rival Class Leader Introduction",
    267:  "Kushida Identity Exposure Risk",
    274:  "Strategic Isolation Techniques",

    281:  "Sports Festival Manipulation Peak",
    288:  "Class D Internal Fracture",
    295:  "Ayanokōji Direct Intervention Moment",
    302:  "Leadership Power Shift",
    309:  "Psychological Control Mastery",

    316:  "White Room Conditioning Flashback Hint",
    323:  "Ayanokōji Emotional Detachment Clarity",
    330:  "Elite Student Identification System",
    337:  "Strategic Rival Class Collapse",
    344:  "Class Unity Forced Stability",

    351:  "Uninhabited Island Survival Exam Peak",
    358:  "Group Strategy Exploitation",
    365:  "Ayanokōji Hidden Command Role",
    372:  "Trust Breakdown Manipulation",
    379:  "Resource Scarcity Pressure",

    386:  "Karuizawa Psychological Focus Arc",
    393:  "Emotional Leverage Strategy",
    400:  "Turning Point of Control Systems",

    407:  "Class War Escalation Phase",
    414:  "Ayanokōji Hidden Authority Growth",
    421:  "Student Alliance Instability",
    428:  "Kushida Exposure Risk Peak",
    435:  "Psychological Pressure Mastery",

    442:  "White Room Ideology Revelation",
    449:  "Ayanokōji Identity Fragmentation Hint",
    456:  "Horikita Emotional Development",
    463:  "Strategic Betrayal Execution",
    470:  "Class Hierarchy Breakdown Risk",

    477:  "Advanced Exam Tactical Complexity",
    484:  "Manipulation Network Expansion",
    491:  "Ayanokōji Strategic Apex Planning",
    498:  "Rival Class Leader Confrontation",
    505:  "System Exploitation Peak",

    512:  "School Survival Game Intensification",
    519:  "Psychological Isolation Strategy",
    526:  "Class Unity Artificial Stability",
    533:  "Karuizawa Emotional Dependency",
    540:  "Control vs Freedom Conflict",

    547:  "White Room Legacy Pressure",
    554:  "Ayanokōji Tactical Dominance",
    561:  "Inter-Class War Strategy Peak",
    568:  "Horikita Leadership Solidification",
    575:  "Emotional Tool Utilization Ethics",

    582:  "Final Exam Strategy Arc",
    589:  "Rival Manipulation Collapse",
    596:  "Ayanokōji Hidden Power Exposure",
    603:  "Class D Ascension Path",

    610:  "Ultimate Psychological Exam",
    617:  "White Room Philosophy Conflict",
    624:  "Ayanokōji Direct Intervention Peak",
    631:  "System Control Awareness",
    638:  "Emotional Suppression Absolute",

    645:  "Class Hierarchy Reversal Attempt",
    652:  "Strategic Endgame Planning",
    659:  "Kushida Final Exposure",
    666:  "Psychological Battlefield Collapse",

    673:  "Post-Exam Power Stabilization",
    680:  "Ayanokōji Identity Mask Strengthening",
    687:  "Horikita Independent Leader Status",
    694:  "Class Balance Restoration",

    701:  "School System Deep Structure Awareness",
    708:  "Manipulation Neutralization Phase",
    715:  "Karuizawa Emotional Stabilization",
    722:  "Strategic Trust Formation",

    729:  "Residual Rival Tension",
    736:  "Class D Reputation Growth",
    743:  "Ayanokōji Emotional Boundary Awareness",
    750:  "Elite School Survival Mastery",

    757:  "White Room Influence Echo",
    764:  "Psychological Control Stability",
    771:  "Horikita-Class Synergy Growth",
    778:  "System Exploit Neutralization",

    785:  "Long-Term Strategic Positioning",
    792:  "Class Stability Peak",

    799:  "Elite Manipulator Legend Formation",
    806:  "Ayanokōji Tactical Perfection",
    813:  "School System Balance Shift",
    820:  "Class Identity Stabilized",

    827:  "Beyond Emotional Manipulation",
    834:  "Perfect Strategic Execution",
    841:  "Horikita Full Leadership Maturity",
    848:  "Class D Elite Recognition",

    855:  "Absolute Psychological Mastery",
    862:  "Ayanokōji System Control Peak",
    869:  "School Hierarchy Understanding",
    876:  "Strategic Neutral State",

    883:  "Final Manipulation Resolution",
    890:  "Elite School Order Stabilized",
    897:  "Perfect Strategic Balance",

    904:  "Beyond Social Hierarchy",
    911:  "Absolute Tactical Clarity",
    918:  "Ayanokōji True Potential Hint",
    925:  "System Philosophy Integration",

    932:  "Final Identity Mask Stable",
    939:  "Absolute School Control Awareness",
    946:  "Psychological System Perfection",
    953:  "Beyond Human Competition",

    960:  "Absolute Strategic Existence",
    967:  "Legend of White Room Survivor",
    974:  "Perfect Manipulation Flow",
    981:  "Beyond Emotion and Logic",
    988:  "Absolute Elite Control",
    995:  "Perfect Classroom of the Elite State",
    998:  "Ultimate Psychological Harmony",
    1000:"A Boy Raised Without Freedom Learned That in a World Built on Hierarchies and Deception, True Control Is Not Dominating Others—but Remaining Unseen While Guiding Everything From the Shadows"
}
}
