import { AnimeThemeConfig } from "./types"
import { GiDragonHead, GiFist, GiLightningBow, GiFlame, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiStarFormation } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const dragonBallGtTheme: AnimeThemeConfig = {
    id: "dragon-ball-gt",
    displayName: "Dragon Ball GT",
    description: "When Black Star Dragon Balls scatter across the universe, Goku is turned into a child and must retrieve them before the Earth is destroyed — an unofficial but memorable final journey.",
    fontFamily: "'Bangers', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Bangers&display=swap",
    cssVars: {
        "--color-brand-200": "255 185 100",
        "--color-brand-300": "248 155 45",
        "--color-brand-400": "236 122 0",
        "--color-brand-500": "214 90 0",
        "--color-brand-600": "176 68 0",
        "--color-brand-700": "138 50 0",
        "--color-brand-800": "98 34 0",
        "--color-brand-900": "58 20 0",
        "--color-brand-950": "33 11 0",
        "--brand": "214 90 0",
        "--background": "#060300",
        "--paper": "#100800",
        "--color-gray-950": "6 3 0",
        "--color-gray-900": "14 8 2",
        "--color-gray-800": "26 16 5",
        "--color-gray-700": "44 28 10",
        "--color-gray-600": "68 46 18",
        "--color-gray-500": "108 76 38",
        "--color-gray-400": "152 118 78",
        "--color-gray-300": "192 160 118",
        "--color-gray-200": "218 192 158",
        "--color-gray-100": "234 216 192",
        "--color-gray-50": "246 238 228",
    },
    sidebarOverrides: {
        "home": { icon: GiDragonHead, label: "GT World" },
        "schedule": { icon: GiAlarmClock, label: "Space Journey" },
        "manga": { icon: LuBookOpen, label: "GT Records" },
        "lists": { icon: GiFist, label: "GT Roster" },
        "discover": { icon: GiBullseye, label: "Ball Hunt" },
        "torrent-list": { icon: GiFlame, label: "GT Cache" },
        "debrid": { icon: GiLightningBow, label: "Super Saiyan 4" },
        "unmatched": { icon: GiStarFormation, label: "Shadow Dragons" },
        "enmasse": { icon: GiResize, label: "Team Deploy" },
        "scan-summaries": { icon: TbReportSearch, label: "GT Reports" },
        "auto-downloader": { icon: LuRss, label: "Dragon Radar" },
        "community": { icon: GiDragonHead, label: "GT Fans" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Dragon Alerts" },
        "achievements": { icon: GiTrophy, label: "GT Medals" },
        "milestones": { icon: LuFlag, label: "Dragon GT Goals" },
        "theme-manager": { icon: GiPalette, label: "GT Colors" },
        "extensions": { icon: BiExtension, label: "Power Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "GT Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Power Settings" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "Child Goku",
        "a_episode_counter": "Goku's Will Mark",
        "a_episode_titan": "Decade Fan Relic",
        "a_hours_invested": "Black Star Dragon Proof",
        "a_time_lord": "GT Veteran",
        "a_anime_collector": "GT Cache",
        "a_library_legend": "GT Archives",
        "a_first_complete": "GT Complete",
        "a_hundred_club": "Hundred GT",
        "a_first_day": "Gt Records Seal",
        "a_first_rating": "Decade Fan Appraisal",
        "a_ten_thousand_min": "Galaxy Tour Standard",
        "a_season_veteran": "Galaxy Tour Library",
        "a_year_explorer": "Holiday Gt Map",
        "a_century_watcher": "Classic Gt Ledger",
        "a_five_hundred_eps": "All Night Dominion",
        "a_thousand_eps": "Baby Terror Record",
        "a_watching_ten": "Dragon Ball Gt Acclaim",
        "a_ptw_hoarder": "Space Journey Library",
        "a_dropped_honesty": "Dragon Ball Gt Summit",
        "a_five_thousand_eps": "Ball Super Warrant",
        "a_ten_completed": "Hidden Gt Afterglow",
        "a_fifty_completed": "Pan's Heart Ascension",
        "a_five_hundred_completed": "Dragon Ball Gt Clear",
        "a_mean_score_tracker": "Dragon Ball Verdict",
        "a_unique_studios": "Baby Terror Collection",
        "a_days_spent_watching": "Dragon Power Dominion",
        "a_all_status": "Super Saiyan Testament",
        "a_first_favorite": "Gt Charm Cabinet",
        "a_favorites_collector": "Gt Cleared Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Child Goku Drive",
        "a_marathon_runner": "Galaxy Tour",
        "a_weekend_warrior": "Decade Fan Ordeal",
        "a_non_stop": "Dragon Alerts Fever",
        "a_one_more_episode": "Gt Revisit Mantle",
        "a_speed_run": "Super Speed",
        "a_double_feature": "Daily Gt Crown",
        "a_triple_threat": "Gt Archives Record",
        "a_five_a_day": "Gt Judge Accord",
        "a_back_to_back": "Tuffle Tech Surge",
        "a_seasonal_binge": "Decade Fan Cascade",
        "a_cour_crusher": "Dragon Power Ordeal",
        "a_half_day_watch": "Goku's Will Crown",
        "a_full_day_watch": "Gt Medals Pinnacle",
        "a_power_weekend": "Gt Records Run",
        "a_binge_king": "GT Marathon",
        "a_no_sleep": "All-Night GT",
        "a_entire_season": "Gt Critic Library",
        "a_seven_day_challenge": "Gt Medals Mark",
        "a_hundred_day_binge": "Gt Records Surge",
        "a_genre_binge": "Goku's Burden Binge",
        "a_studio_binge": "Goku's Will Fever",
        "a_season_sweep": "Gt Collection Codex",
        "a_forty_eight_hour": "Dragon Gt Overture",
        "a_ep_counter_day": "Hidden Gt Aegis",
        "a_multi_series_binge": "Space Journey Streak",
        "a_midnight_binge": "Gt Revisit Cascade",
        "a_new_year_binge": "Gt Streak Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Super Saiyan 4",
        "a_genre_adventure": "Space Journey",
        "a_genre_comedy": "Kid Goku",
        "a_genre_drama": "Shadow Dragons",
        "a_genre_fantasy": "GT World",
        "a_genre_horror": "Baby Terror",
        "a_genre_mystery": "Gt Revisited Mystery",
        "a_genre_romance": "Pan's Heart",
        "a_genre_scifi": "Galactic Balls",
        "a_genre_sol": "Ball Super Slice",
        "a_genre_sports": "Dragon Gt Sports",
        "a_genre_supernatural": "Dragon Power",
        "a_genre_thriller": "Pan's Heart Thriller",
        "a_genre_mecha": "Tuffle Tech",
        "a_genre_music": "Galaxy Tour Music",
        "a_genre_psychological": "Goku's Burden",
        "a_genre_ecchi": "Child Goku Ecchi",
        "a_genre_mahou_shoujo": "Gt Archives Magic Shoujo",
        "a_tag_isekai": "Dragon Ball Super Isekai",
        "a_tag_harem": "Gt World Harem",
        "a_tag_bl": "Dragon Gt Bl",
        "a_tag_gl": "Gt Revisit Gl",
        "a_tag_historical": "Gt Fans Historical",
        "a_tag_military": "All Night Military",
        "a_tag_school": "Space Journey School",
        "a_tag_martial_arts": "Gt Medals Martial Arts",
        "a_tag_vampire": "Gt Archives Vampire",
        "a_tag_samurai": "Baby Terror Samurai",
        "a_tag_space": "Night Gt Space",
        "a_tag_parody": "Gt Roster Parody",
        "a_tag_idol": "Dragon Gt Idol",
        "a_tag_post_apocalyptic": "Dragon Radar Post Apocalyptic",
        "a_tag_cyberpunk": "Dragon Alerts Cyberpunk",
        "a_tag_shounen": "Dragon Radar Shounen",
        "a_tag_seinen": "Ball Hunt Seinen",
        "a_tag_shoujo": "Ball Hunt Shoujo",
        "a_tag_josei": "Hidden Gt Josei",
        "a_tag_survival": "Gt Cleared Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "GT Cleared",
        "a_mega_completionist": "GT Master",
        "a_completion_rate_50": "Gt Archives Return",
        "a_completion_rate_75": "Pan's Heart Crown",
        "a_completion_rate_90": "Hidden Gt Resolution",
        "a_no_drop": "Gt Revisited Decree",
        "a_long_runner_complete": "Gt Records Clear",
        "a_sequel_chain": "Dragon Ball Super",
        "a_clean_list": "Gt Collection Relic",
        "a_from_ptw": "Gt Roster Index",
        "a_rewatch_master": "Dragon Ball Return",
        "a_short_complete": "Super Speed Endgame",
        "a_same_day_start_finish": "Gt Supporter Pinnacle",
        "a_revival": "Classic Gt Insignia",
        "a_zero_to_hero": "Child to Legend",
        "a_five_genre_complete": "Super Speed A Five Genre",
        "a_full_franchise": "Space Journey Chronicle",
        "a_batch_complete": "Decade Fan Crown",
        "a_paused_to_done": "Hidden Gt Aegis Aegis",
        "a_completion_spree": "Gt Classic Triumph",
        "a_multi_rewatch": "Gt Classic Triumph Triumph",
        "a_dropped_recovery": "Goku's Will Conquest",
        "a_ten_perfect_scores": "Gt Records Acclaim",
        "a_seasonal_clear": "Dragon Power Codex",
        "a_complete_genre_span": "Kid Goku A Complete Genre",
        "a_monthly_completions": "Dragon Ball Afterglow",
        "a_yearly_completions": "Super Saiyan Epilogue",
        "a_rapid_complete": "Gt Medals Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "GT Supporter",
        "a_studio_devotee": "Gt Revisited Treasury",
        "a_rewatcher": "GT Revisited",
        "a_triple_rewatch": "Goku's Burden Coda",
        "a_annual_tradition": "Gt Medals Proof",
        "a_director_fan": "Gt Collection Trial",
        "a_voice_actor_fan": "Goku's Will Crown Crown",
        "a_ost_lover": "Space Journey Seal",
        "a_source_reader": "Holiday Gt Cabinet",
        "a_waiting_weekly": "Gt Revisited Clock",
        "a_childhood_revisit": "Endless Gt Seal",
        "a_saga_tracker": "Night Gt Standard",
        "a_genre_loyalty": "Ball Super Loyalty",
        "a_decade_watcher": "Decade Fan",
        "a_adaptation_hunter": "Gt Roster Trial",
        "a_original_anime_fan": "Gt Master Testament",
        "a_long_commitment": "Gt Medals Mark Mark",
        "a_perfect_attendance": "Dragon Ball Gt Standard",
        "a_favorite_studio_5": "Dragon Radar Library",
        "a_complete_catalog": "Gt Cleared Seal",
        "a_franchise_collector": "Dragon Radar Archive",
        "a_airing_follower": "Endless Gt Signal",
        "a_genre_master": "Gt Collection Master",
        "a_staff_follower": "Dragon Radar Oath",
        "a_multi_season_fan": "Gt Fans Hoard",
        "a_format_diversity": "Gt Archives Cache",
        "a_year_dedication": "Decade Fan Tenure",
        "a_season_dedication": "All Night Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Goku's Burden Explorer",
        "a_studio_hopper": "Dragon Ball Collection",
        "a_tag_explorer": "Decade Fan Explorer",
        "a_decade_hopper": "Space Journey Chronicle Chronicle",
        "a_hidden_gem": "GT Charm",
        "a_popular_taste": "Dragon Gt Decree",
        "a_retro_appreciator": "Gt Cleared Aegis",
        "a_modern_viewer": "Gt Supporter Pinnacle Pinnacle",
        "a_cross_demographic": "Child Goku Pinnacle",
        "a_underdog_fan": "Kid Goku Trial",
        "a_variety_week": "Dragon Radar Horizon",
        "a_foreign_cinema": "Gt Revisit Expedition",
        "a_classic_connoisseur": "97 Fan",
        "a_every_season": "Endless Gt Archive",
        "a_award_winner": "Galaxy Tour Insignia",
        "a_niche_explorer": "Ball Hunt Horizon",
        "a_global_anime": "Super Speed Crown",
        "a_cult_classic": "GT Classic",
        "a_random_pick": "Dragon Gt Decree Decree",
        "a_new_genre_month": "Dragon Ball Gt A New",
        "a_seasonal_completionist": "Classic Gt Summit",
        "a_unpopular_opinion": "Gt Charm Standard",
        "a_top_rated_viewer": "Gt Judge Seal",
        "a_source_variety": "Dragon Power Storehouse",
        "a_low_score_brave": "Dragon Alerts Measure",
        "a_upcoming_watcher": "Gt Judge Seal Seal",
        "a_short_series_explorer": "Gt Revisit Expedition Expedition",
        "a_long_series_explorer": "Daily Gt Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Night Training",
        "a_early_bird": "Dawn Training",
        "a_lunch_break": "Gt Art Trial",
        "a_golden_hour": "Gt Marathon Tenure",
        "a_four_am_club": "Gt Classic Gathering",
        "a_witching_hour": "Pan's Heart Tenure",
        "a_new_year_watch": "Decade Fan Season",
        "a_midnight_premiere": "Gt Streak Devotion",
        "a_all_hours": "Classic Gt Seal",
        "a_dawn_warrior": "Dragon Gt Aegis",
        "a_afternoon_delight": "Black Star Dragon Proof Proof",
        "a_prime_time": "Galaxy Tour Insignia Insignia",
        "a_workday_watcher": "Child Goku Pinnacle Pinnacle",
        "a_sunday_marathon": "Gt Records Momentum",
        "a_rainy_day": "Pan's Heart Relic",
        "a_morning_routine": "Gt Fans Promise",
        "a_night_shift": "Gt Archives Aegis",
        "a_twilight_zone": "Gt Critic Ledger",
        "a_seasonal_premier": "Gt Revisited Cabinet",
        "a_clock_collector": "Gt Classic Repository",
        "a_weekend_binge_hours": "Ball Hunt Streak",
        "a_late_night_regular": "Super Saiyan Dominion",
        "a_sunrise_watcher": "Gt Collection Relic Relic",
        "a_holiday_watcher": "Gt Judge Pact",
        "a_every_day_of_week": "Tuffle Tech Ledger",
        "a_monthly_hours": "Dragon Gt Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Hidden Gt Record",
        "a_party_host": "Gt Archives Record Record",
        "a_social_butterfly": "Holiday Gt Company",
        "a_group_binge": "Baby Terror Sprint",
        "a_party_regular": "Gt Critic Chronicle",
        "a_sync_viewer": "Gt Classic Standard",
        "a_commentator": "Gt Cleared Record",
        "a_party_marathon": "Goku's Burden Vigil",
        "a_full_house": "All Night Trial",
        "a_community_pillar": "Super Saiyan Alliance",
        "a_watch_party_streak": "Gt Cleared Vigil",
        "a_diverse_party": "Gt Fans Seal",
        "a_late_night_party": "Super Saiyan Testament Testament",
        "a_party_veteran": "All Night Testament",
        "a_genre_party": "Gt Revisit Party",
        "a_weekly_party": "Gt Classic Calendar",
        "a_silent_viewer": "Gt Master Mantle",
        "a_recommendation_giver": "Ball Hunt Network",
        "a_party_completionist": "Night Gt Coda",
        "a_social_scorer": "Gt Collection Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Daily Gt Proof",
        "a_fibonacci": "Decade Fan Dominion",
        "a_palindrome_day": "Decade Fan Relic Relic",
        "a_binary_day": "Ball Super Mark",
        "a_full_moon": "Endless Gt Insignia",
        "a_leap_year": "Super Speed Devotion",
        "a_time_traveler": "Gt Revisited Record",
        "a_genre_clash": "Goku's Burden Clash",
        "a_triple_seven": "Decade Fan Testament",
        "a_thousand_complete": "Gt Master Epilogue",
        "a_pi_episodes": "Child Goku Crown",
        "a_synchronicity": "Kid Goku Anchor",
        "a_world_record": "Goku's Will Warrant",
        "a_nice": "Galaxy Tour Chronicle",
        "a_power_level": "Gt Master Testament Testament",
        "a_answer_42": "Dragon Gt Standard",
        "a_square_number": "Goku's Burden Decree",
        "a_prime_count": "Galaxy Tour Seal",
        "a_matching_date": "Kid Goku Mantle",
        "a_century_episode": "Child Goku Mark",
        "a_double_digits": "Pan's Heart Testament",
        "a_one_two_three": "Super Speed Crown Crown",
        "a_lucky_seven": "Gt Medals Crown",
        "a_all_tens": "Dragon Alerts Criterion",
        "a_exact_hundred_eps": "Night Gt Legend",
        "a_year_match_count": "Gt Revisited Yearlong",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Ball Hunt Ledger",
        "a_movie_buff": "Goku's Will Mark Mark",
        "a_ova_hunter": "Night Gt Standard Standard",
        "a_ona_explorer": "Kid Goku Secret",
        "a_special_watcher": "Pan's Heart Relic Relic",
        "a_short_king": "Gt World Crown",
        "a_variety_pack": "Goku's Will Inquiry",
        "a_film_festival": "Gt Judge Chronicle",
        "a_music_video": "Gt Fans Chronicle",
        "a_tv_short": "Goku's Burden Record",
        "a_movie_marathon": "Goku's Burden Gauntlet",
        "a_double_length": "Daily Gt Crown Crown",
        "a_anthology": "Gt Archives Aegis Aegis",
        "a_mini_series": "Gt Charm Decree",
        "a_theatrical": "Dragon Radar Accord",
        "a_format_master": "Gt Classic Vault",
        "a_long_movie": "Classic Gt Insignia Insignia",
        "a_back_catalog": "Gt Cleared Standard",
        "a_cm_watcher": "Dragon Ball Super Aegis",
        "a_pv_collector": "Kid Goku Storehouse",
        "a_format_balance": "Gt Classic Vault Vault",
        "a_episodic_master": "Dragon Ball Super Standard",
        "a_sequel_movie": "Super Speed Pinnacle",
        "a_recap_watcher": "Gt Art Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily GT",
        "a_mega_streak": "Endless GT",
        "a_weekly_warrior": "All Night Season",
        "a_monthly_watcher": "Gt Streak Calendar",
        "a_comeback": "Holiday Gt Decree",
        "a_weekend_streak": "Dragon Alerts Passage",
        "a_no_zero_days": "Ball Super Warrant Warrant",
        "a_iron_will": "Goku's Will",
        "a_habit_formed": "Tuffle Tech Banner",
        "a_consistent_pace": "Daily Gt Measure",
        "a_year_long": "Year of GT",
        "a_double_streak": "Gt Collection Watch",
        "a_streak_recovery": "Gt Master Season",
        "a_daily_minimum": "Gt Streak Focus",
        "a_winter_streak": "Gt Revisit Watch",
        "a_summer_streak": "Pan's Heart Resolve",
        "a_morning_streak": "Gt Cleared Clock",
        "a_night_streak": "Tuffle Tech Constancy",
        "a_unbreakable": "Gt World Proof",
        "a_eternal_flame": "Dragon Ball Standard",
        "a_completion_streak": "Night Gt Return",
        "a_rating_streak": "Decade Fan Balance",
        "a_multi_ep_streak": "Goku's Will Ritual",
        "a_genre_streak": "Decade Fan Streak",
        "a_studio_streak": "Holiday Gt Cabinet Cabinet",
        "a_perfect_week": "Kid Goku Relic",

        // ── ANIME SCORING ──
        "a_critic": "GT Judge",
        "a_perfect_ten": "SSJ4 Perfection",
        "a_harsh_critic": "Critical Review",
        "a_fair_judge": "Super Saiyan Balance",
        "a_generous_spirit": "Gt Streak Pinnacle",
        "a_score_all": "Black Star Dragon Criterion",
        "a_wide_range": "Galaxy Tour Ledger",
        "a_controversial": "Gt Cleared Decree",
        "a_consistent_scorer": "Gt Revisited Verdict",
        "a_score_sniper": "Super Speed Score",
        "a_evolving_taste": "Gt Collection Testament",
        "a_bell_curve": "Dragon Ball Gt Insignia",
        "a_picky_watcher": "Gt Master Warrant",
        "a_100_rated": "Gt Classic Warrant",
        "a_500_rated": "Gt World Pinnacle",
        "a_mediocre_majority": "Kid Goku Canon",
        "a_rating_spree": "Gt Cleared Review",
        "a_score_variance": "Dragon Alerts Score",
        "a_masterpiece_hunter": "Gt Cleared Banner",
        "a_contrarian": "Goku's Burden Record Record",
        "a_optimist": "Gt Fans Ledger",
        "a_score_distributor": "Gt Art Appraisal",
        "a_genre_critic": "Daily Gt Critic",
        "a_mean_above_8": "Gt Medals Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year GT",
        "a_valentines_weeb": "Dragon Radar Vow",
        "a_pi_day": "Super Saiyan Trial",
        "a_april_fools": "Super Speed Devotion Devotion",
        "a_international_anime_day": "Classic Gt Record",
        "a_star_wars_day": "Gt Records Chronicle",
        "a_summer_solstice": "Ball Super Calendar",
        "a_tanabata": "Gt Supporter Focus",
        "a_friday_13th": "Gt Art Relic",
        "a_halloween_spirit": "Ball Hunt Vow",
        "a_thanksgiving_binge": "Gt Critic Run",
        "a_christmas_special": "Holiday GT",
        "a_new_years_eve": "Gt Medals Pilgrimage",
        "a_birthday_watch": "Dragon Ball Gt Vow",
        "a_holiday_marathon": "Baby Terror Overture",
        "a_independence_day": "Dragon Ball Banner",
        "a_culture_day": "Space Journey Insignia",
        "a_spring_equinox": "Baby Terror Decree",
        "a_earth_day": "Goku's Will Mantle",
        "a_labor_day": "Ball Hunt Seal",
        "a_winter_solstice": "Child Goku Pilgrimage",
        "a_anime_birthday": "Goku's Will Pilgrimage",
        "a_every_holiday": "Gt Roster Resolve",
        "a_consecutive_holidays": "Pan's Heart Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Holiday Gt Rank",
        "a_meta_collector": "Space Journey Hoard",
        "a_meta_category_starter": "Gt Streak Badge",
        "a_meta_tier_climber": "Space Journey Glyph",
        "a_meta_tier_max": "Super Saiyan 4",
        "a_meta_xp_earner": "Gt Art Emblem",
        "a_meta_difficulty_easy": "Super Saiyan Mechanism",
        "a_meta_difficulty_hard": "Gt Judge Writ",
        "a_meta_unlock_spree": "All Night Panel",
        "a_meta_completionist": "GT Collection",
        "a_meta_diverse": "Decade Fan Emblem",
        "a_meta_dominator": "Gt Critic Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Page",
        "m_chapter_counter": "Gt Classic Pinnacle",
        "m_chapter_titan": "Dragon Power Relic",
        "m_reading_hours": "Gt Art Relic Relic",
        "m_reading_time_lord": "Classic Gt Record Record",
        "m_manga_collector": "All Night Ledger",
        "m_library_legend": "Space Journey Reliquary",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "Dragon Radar Seal",
        "m_first_rating": "Gt Art Eye",
        "m_ten_thousand_pages": "Dragon Radar Gauge",
        "m_volume_collector": "Gt Master Storehouse",
        "m_year_explorer": "Dragon Gt Quest",
        "m_century_reader": "Gt Revisit Dominion",
        "m_five_hundred_ch": "Galaxy Tour Legend",
        "m_thousand_ch": "Gt Collection Legend",
        "m_reading_ten": "Gt Revisit Appraisal",
        "m_ptr_hoarder": "Gt Collection Index",
        "m_dropped_honesty": "Space Journey Summit",
        "m_season_reader": "Gt Cleared Treasury",
        "m_active_reader": "Pan's Heart Trial",
        "m_five_thousand_ch": "Goku's Burden Standard",
        "m_ten_completed": "Goku's Burden Resolution",
        "m_fifty_completed": "Gt Collection Harvest",
        "m_five_hundred_completed": "Tuffle Tech Legacy",
        "m_mean_score_tracker": "Gt Revisited Audit",
        "m_unique_authors": "Goku's Will Reserve",
        "m_all_status": "Pan's Heart Testament Testament",
        "m_first_favorite": "Night Gt Cache",
        "m_favorites_collector": "Holiday Gt Shelf",
        "m_days_spent_reading": "Child Goku Relic",

        // ── MANGA BINGE ──
        "m_binge_reader": "Dragon Ball Gt Streak",
        "m_marathon_reader": "Super Saiyan Rush",
        "m_weekend_reader": "Endless Gt Run",
        "m_non_stop_reading": "Night Gt Gauntlet",
        "m_one_more_chapter": "Gt Art Testament Testament",
        "m_speed_read": "Ball Super Drive",
        "m_double_story": "Baby Terror Banner",
        "m_triple_read": "Dragon Ball Record",
        "m_five_a_day": "Gt Fans Insignia",
        "m_chapter_chain": "Space Journey Accord",
        "m_volume_binge": "Dragon Alerts Drive",
        "m_power_reader": "Gt Records Seal Seal",
        "m_half_day_read": "Holiday Gt Aegis",
        "m_full_day_read": "Dragon Ball Super Aegis Aegis",
        "m_power_weekend": "Dragon Radar Streak",
        "m_binge_king": "GT Marathon",
        "m_no_sleep_read": "Gt Revisit Rush",
        "m_full_series_rush": "Super Saiyan Cascade",
        "m_seven_day_challenge": "Gt Supporter Warrant",
        "m_hundred_day_read": "Decade Fan Legend",
        "m_volume_rush": "Hidden Gt Gauntlet",
        "m_series_sweep": "Gt Roster Trial Trial",
        "m_genre_binge": "Dragon Ball Super Binge",
        "m_author_binge": "Endless Gt Surge",
        "m_chapter_counter_day": "Gt Critic Ledger Ledger",
        "m_multi_series_binge": "Galaxy Tour Charge",
        "m_midnight_binge": "Gt Collection Tempest",
        "m_new_year_binge": "Goku's Will Passage",
        "m_forty_eight_hour": "Gt Revisited Rally",
        "m_oneshot_binge": "Ball Super Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Chapter",
        "m_genre_adventure": "Space Chapter",
        "m_genre_comedy": "Holiday Gt Comedy",
        "m_genre_drama": "Drama Chapter",
        "m_genre_fantasy": "GT Chapter",
        "m_genre_horror": "Dark Chapter",
        "m_genre_mystery": "Goku's Burden Mystery",
        "m_genre_romance": "Heart Chapter",
        "m_genre_scifi": "Tech Chapter",
        "m_genre_sol": "Gt Classic Slice",
        "m_genre_sports": "Hidden Gt Sports",
        "m_genre_supernatural": "Power Chapter",
        "m_genre_thriller": "Kid Goku Thriller",
        "m_genre_psychological": "Deep Chapter",
        "m_genre_isekai": "All Night Isekai",
        "m_genre_shounen": "Gt Marathon Shounen",
        "m_genre_ecchi": "Daily Gt Ecchi",
        "m_genre_mahou_shoujo": "Holiday Gt Magic Shoujo",
        "m_genre_mecha": "Gt Master Mecha",
        "m_genre_music": "Ball Hunt Music",
        "m_tag_isekai_new": "Gt Art Isekai New",
        "m_tag_harem": "Black Star Dragon Harem",
        "m_tag_bl": "Gt Charm Bl",
        "m_tag_gl": "Gt Collection Gl",
        "m_tag_historical": "Galaxy Tour Historical",
        "m_tag_military": "Gt Marathon Military",
        "m_tag_school": "Dragon Radar School",
        "m_tag_martial_arts": "Gt Classic Martial Arts",
        "m_tag_vampire": "Hidden Gt Vampire",
        "m_tag_samurai": "Gt Archives Samurai",
        "m_tag_space": "Gt Charm Space",
        "m_tag_parody": "Gt Master Parody",
        "m_tag_idol": "Gt Charm Idol",
        "m_tag_post_apocalyptic": "Space Journey Post Apocalyptic",
        "m_tag_cyberpunk": "Black Star Dragon Cyberpunk",
        "m_tag_shoujo": "Gt Judge Shoujo",
        "m_tag_survival": "Holiday Gt Survival",
        "m_tag_cooking": "Dragon Ball Gt Cooking",
        "m_tag_medical": "Pan's Heart Medical",
        "m_tag_villainess": "Endless Gt Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full GT",
        "m_mega_completionist": "GT Master",
        "m_completion_rate_50": "Gt Charm Return",
        "m_completion_rate_75": "Kid Goku Ascension",
        "m_completion_rate_90": "Dragon Ball Resolution",
        "m_no_drop": "Night Gt Decree",
        "m_long_runner_complete": "Gt Critic Clear",
        "m_sequel_chain": "Ball Hunt Seal Seal",
        "m_clean_list": "Dragon Power Relic Relic",
        "m_from_ptr": "Gt Judge Watchlist",
        "m_reread_master": "Super Saiyan Trial Trial",
        "m_oneshot_complete": "Super Saiyan Ascension",
        "m_same_day_start_finish": "Gt Medals Crown Crown",
        "m_revival": "Gt Critic Accord",
        "m_zero_to_hundred": "Goku's Burden Banner",
        "m_five_genre_complete": "Ball Super M Five Genre",
        "m_full_collection": "Gt Medals Proof Proof",
        "m_batch_complete": "Gt Revisited Summit",
        "m_paused_to_done": "Dragon Ball Standard Standard",
        "m_completion_spree": "Gt World Triumph",
        "m_format_completionist": "Super Saiyan Completion",
        "m_catch_up": "Classic Gt Chronicle",
        "m_multi_reread": "Night Gt Banner",
        "m_dropped_recovery": "Daily Gt Conquest",
        "m_ten_perfect_scores": "Endless Gt Judgment",
        "m_complete_genre_span": "All Night M Complete Genre",
        "m_monthly_completions": "Dragon Ball Super Return",
        "m_yearly_completions": "All Night Epilogue",
        "m_rapid_complete": "Gt Supporter Finale",
        "m_author_complete": "Dragon Radar Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "GT Reader",
        "m_mangaka_lover": "Toriyama Adjacent",
        "m_rereader": "GT Revisit",
        "m_triple_reread": "Decade Fan Testament Testament",
        "m_annual_reread": "Goku's Burden Banner Banner",
        "m_publisher_fan": "Gt World Mark",
        "m_artist_fan": "Ball Hunt Insignia",
        "m_adaptation_compare": "Dragon Ball Gt Insignia Insignia",
        "m_source_material_fan": "Anime Original",
        "m_waiting_weekly": "Gt Archives Streak",
        "m_classic_reader": "Gt Master Lantern",
        "m_saga_reader": "Space Journey Decree",
        "m_genre_loyalty": "Daily Gt Loyalty",
        "m_decade_reader": "Dragon Alerts Warrant",
        "m_ln_adaptation": "Dragon Alerts Mark",
        "m_original_work": "Hidden Gt Standard",
        "m_long_commitment": "Daily Gt Mark",
        "m_up_to_date": "Goku's Will Warrant Warrant",
        "m_favorite_mangaka": "Dragon Gt Treasury",
        "m_complete_portfolio": "Gt World Triumph Triumph",
        "m_franchise_collector": "Classic Gt Archive",
        "m_serialization_follower": "Dragon Gt Handshake",
        "m_genre_master": "Dragon Power Master",
        "m_multi_series_author": "Space Journey Insignia Insignia",
        "m_format_diversity": "Hidden Gt Shelf",
        "m_year_dedication": "Gt Revisit Tenure",
        "m_ongoing_follower": "Dragon Alerts Fellowship",
        "m_genre_loyalty_50": "Gt Collection Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Baby Terror Explorer",
        "m_publisher_hopper": "Gt World Mantle",
        "m_tag_explorer": "Gt Roster Explorer",
        "m_decade_hopper": "Gt Judge Chronicle Chronicle",
        "m_hidden_gem": "Hidden GT",
        "m_popular_taste": "Gt Revisited Record Record",
        "m_retro_reader": "Gt Revisited Accord",
        "m_modern_reader": "Galaxy Tour Seal Seal",
        "m_cross_demographic": "Gt Streak Crown",
        "m_underdog_fan": "Gt Revisited Accord Accord",
        "m_variety_week": "Ball Hunt Horizon Horizon",
        "m_manhwa_reader": "Super Speed Proof",
        "m_manhua_reader": "Gt Master Mantle Mantle",
        "m_classic_connoisseur": "Tuffle Tech Glimpse",
        "m_award_winner": "Gt Revisit Warrant",
        "m_niche_explorer": "Dragon Ball Gt Horizon",
        "m_world_manga": "Classic Gt Chronicle Chronicle",
        "m_cult_classic": "Classic GT",
        "m_random_pick": "Gt Revisited Standard",
        "m_new_genre_month": "Classic Gt M New Genre",
        "m_year_completionist": "Gt Classic Fulfillment",
        "m_unpopular_opinion": "Goku's Will Trial",
        "m_top_rated_reader": "Dragon Ball Gt Record",
        "m_source_variety": "Gt Master Catalogue",
        "m_low_score_brave": "Gt Classic Score",
        "m_short_manga_explorer": "Galaxy Tour Compass",
        "m_long_manga_explorer": "Goku's Burden Survey",
        "m_serialization_explorer": "Kid Goku Road",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Gt Charm Ledger",
        "m_commute_reader": "Pan's Heart Tenure Tenure",
        "m_four_am_club": "Gt World Fellowship",
        "m_new_year_read": "Ball Hunt Pact",
        "m_all_hours": "Gt Judge Accord Accord",
        "m_prime_time_reader": "Hidden Gt Banner",
        "m_workday_reader": "Gt Critic Accord Accord",
        "m_sunday_read": "Gt Charm Standard Standard",
        "m_morning_routine": "Gt Critic Discipline",
        "m_night_shift_reader": "Dragon Radar Accord Accord",
        "m_seasonal_premier_read": "Gt Master Seasonal",
        "m_clock_collector": "Child Goku Reserve",
        "m_late_night_horror": "Ball Super Mark Mark",
        "m_afternoon_reader": "Gt Revisit Mantle Mantle",
        "m_golden_hour_reader": "Decade Fan Observance",
        "m_dawn_reader": "Gt Roster Mantle",
        "m_twilight_reader": "Dragon Alerts Crown",
        "m_midnight_start": "Hidden Gt Routine",
        "m_weekend_binge_hours": "Endless Gt Momentum",
        "m_late_night_regular": "Gt Charm Accord",
        "m_sunrise_reader": "Black Star Dragon Mantle",
        "m_every_day_of_week": "Gt Master Warrant Warrant",
        "m_monthly_hours": "Baby Terror Vigil",
        "m_bedtime_reader": "Gt Classic Warrant Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "GT Art",
        "m_webtoon_reader": "Dragon Alerts Mark Mark",
        "m_full_color": "Ball Hunt Accord",
        "m_doujin_reader": "Dragon Ball Record Record",
        "m_anthology_reader": "Endless Gt Accord",
        "m_adaptation_reader": "Gt Revisited Banner",
        "m_longstrip_reader": "Decade Fan Trial",
        "m_4koma_reader": "Gt Archives Ledger",
        "m_oneshot_reader": "All Night Mantle",
        "m_format_variety": "Gt World Gallery",
        "m_light_novel_reader": "Gt Judge Insignia",
        "m_novel_reader": "Gt Classic Crown",
        "m_visual_storyteller": "Gt Revisit Testament",
        "m_colored_classic": "Gt Cleared Survey",
        "m_webcomic_fan": "Tuffle Tech Insignia",
        "m_manga_to_anime": "Anime Only",
        "m_seinen_reader": "Daily Gt Pinnacle",
        "m_josei_reader": "Black Star Dragon Pinnacle",
        "m_award_winning_art": "Gt Marathon Relic",
        "m_debut_work": "Gt Marathon Dominion",
        "m_vertical_scroll": "Space Journey Decree Decree",
        "m_traditional_format": "Dragon Ball Gt Hoard",
        "m_cross_media": "Galaxy Tour Accord",
        "m_spinoff_reader": "Classic Gt Accord",
        "m_remake_reader": "Super Saiyan Pinnacle",
        "m_collaboration_reader": "Tuffle Tech Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "GT Streak",
        "m_weekly_warrior": "Kid Goku Season",
        "m_monthly_reader": "Gt Fans Discipline",
        "m_comeback": "Goku's Burden Standard Standard",
        "m_weekend_streak": "Black Star Dragon Fever",
        "m_no_zero_days": "Super Speed Proof Proof",
        "m_iron_will": "GT Dedication",
        "m_habit_formed": "Gt Streak Crown Crown",
        "m_consistent_pace": "Gt Medals Scrutiny Scrutiny",
        "m_year_long": "Year Reading",
        "m_double_streak": "All Night Resolve",
        "m_streak_recovery": "Dragon Power Resolve",
        "m_daily_minimum": "Child Goku Focus",
        "m_winter_streak": "Decade Fan Observance Observance",
        "m_summer_streak": "Gt Marathon Observance",
        "m_morning_streak": "Baby Terror Clock",
        "m_night_streak": "Dragon Ball Gt Discipline",
        "m_unbreakable": "Black Star Dragon Warrant",
        "m_eternal_flame": "Holiday Gt Record",
        "m_chapter_a_day": "Gt Charm Ledger Ledger",
        "m_genre_streak": "Gt Roster Streak",
        "m_completion_streak": "Gt Revisited Return",
        "m_rating_streak": "Gt Roster Appraisal",
        "m_multi_ch_streak": "Kid Goku Tenure",
        "m_author_streak": "Child Goku Calendar",
        "m_perfect_week_manga": "Classic Gt Accord Accord",
        "m_diverse_streak": "Night Gt Streak",

        // ── MANGA SCORING ──
        "m_critic": "GT Critic",
        "m_perfect_ten": "SSJ4 Volume",
        "m_harsh_critic": "Gt Judge Scale",
        "m_fair_judge": "Gt Art Eye Eye",
        "m_generous_spirit": "Endless Gt Decree",
        "m_score_all": "Dragon Alerts Reckoning",
        "m_wide_range": "Gt Fans Ledger Ledger",
        "m_controversial": "Dragon Ball Super Standard Standard",
        "m_consistent_scorer": "Dragon Ball Grade",
        "m_score_sniper": "Goku's Will Reckoning",
        "m_evolving_taste": "All Night Trial Trial",
        "m_bell_curve": "Gt Fans Accord",
        "m_picky_reader": "Night Gt Ledger",
        "m_100_rated": "Gt Fans Standard",
        "m_500_rated": "Dragon Radar Aegis",
        "m_mediocre_majority": "All Night Canon",
        "m_rating_spree": "Baby Terror Verdict",
        "m_score_variance": "Gt Classic Measure",
        "m_binge_rater": "Child Goku Passage",
        "m_reread_rerate": "Gt Cleared Banner Banner",
        "m_masterpiece_hunter": "Dragon Ball Super Banner",
        "m_contrarian": "Gt Revisited Aegis",
        "m_optimist": "Galaxy Tour Accord Accord",
        "m_score_distributor": "Kid Goku Balance",
        "m_genre_critic": "Child Goku Critic",
        "m_mean_above_8": "Gt Classic Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Gt Revisit Season",
        "m_valentines_read": "Gt Roster Observance",
        "m_pi_day": "All Night Testament Testament",
        "m_april_fools": "Goku's Will Devotion",
        "m_international_manga_day": "Gt Judge Aegis",
        "m_free_comic_day": "Endless Gt Chronicle",
        "m_summer_solstice": "Gt Supporter Focus Focus",
        "m_tanabata": "Gt Medals Tanabata",
        "m_friday_13th": "Super Saiyan Dominion Dominion",
        "m_halloween_read": "Ball Super Halloween",
        "m_thanksgiving_binge": "Classic Gt Charge",
        "m_christmas_read": "Gt Critic Pact",
        "m_new_years_eve": "Gt Supporter Pilgrimage",
        "m_birthday_read": "Daily Gt Focus",
        "m_holiday_marathon": "Dragon Gt Rally",
        "m_independence_day": "Gt Revisited Aegis Aegis",
        "m_culture_day": "Dragon Radar Seal Seal",
        "m_spring_equinox": "Ball Super Dominion",
        "m_earth_day": "Daily Gt Trial",
        "m_labor_day": "Gt Critic Seal",
        "m_winter_solstice": "Gt Streak Focus Focus",
        "m_manga_birthday": "Gt Medals Ritual",
        "m_every_holiday_reader": "Dragon Power Watch",
        "m_consecutive_holidays": "Super Saiyan Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Gt Records Aegis",
        "m_fibonacci": "Pan's Heart Dominion",
        "m_palindrome_day": "All Night Relic",
        "m_binary_day": "Gt Streak Proof",
        "m_full_moon_read": "Black Star Dragon Crown",
        "m_leap_year_read": "Night Gt Practice",
        "m_triple_seven": "Gt Art Trial Trial",
        "m_thousand_complete": "Gt Art Ascension",
        "m_nice": "Space Journey Seal Seal",
        "m_power_level_chapters": "Goku's Burden Aegis",
        "m_answer_42": "Black Star Dragon Trial",
        "m_square_number": "Holiday Gt Standard",
        "m_prime_count": "Gt Art Pinnacle",
        "m_matching_date": "Dragon Power Mantle",
        "m_century_chapter": "Gt Records Decree",
        "m_pi_chapters": "Daily Gt Proof Proof",
        "m_synchronicity": "Gt Roster Emblem",
        "m_world_record": "Super Speed Warrant",
        "m_genre_clash": "Hidden Gt Clash",
        "m_time_traveler": "Dragon Ball Decree",
        "m_double_digits": "Gt Master Dominion",
        "m_one_two_three": "Tuffle Tech Banner Banner",
        "m_lucky_seven": "Dragon Ball Gt Record Record",
        "m_exact_hundred_ch": "Pan's Heart Legend",
        "m_year_match_count": "Gt Archives Routine",
        "m_chapter_match_date": "Gt Streak Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Gt Master Index",
        "m_manhwa_format": "Ball Super Gallery",
        "m_manhua_format": "Decade Fan Storehouse",
        "m_ln_format": "Gt Art Index",
        "m_oneshot_format": "All Night Index",
        "m_doujin_format": "Baby Terror Cabinet",
        "m_novel_format": "Goku's Will Reserve Reserve",
        "m_format_master_manga": "Baby Terror Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Dragon Ball Link",
        "m_meta_collector": "Dragon Radar Reliquary",
        "m_meta_category_starter": "Gt World Standard",
        "m_meta_tier_climber": "Galaxy Tour Token",
        "m_meta_tier_max": "GT Legend",
        "m_meta_xp_earner": "Gt Master Anchor",
        "m_meta_difficulty_easy": "Gt Art Panel",
        "m_meta_difficulty_hard": "Gt Revisit Node",
        "m_meta_unlock_spree": "Gt Master Marker",
        "m_meta_completionist": "Full Library",
        "m_meta_diverse": "All Night Anchor",
        "m_meta_dominator": "Space Journey Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060300",
        primary: "#d65a00",
        secondary: "#8a3800",
        accent: "#d8c020",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/dragon-ball-gt.jpg",
    particleColor: "#e09000",
    backgroundDim: 0.35,
    backgroundBlur: 20,
    particleTypes: {
        power_aura: { label: "Power Aura", maxCount: 14, defaultEnabled: true, defaultIntensity: 65 },
        dragon_scales: { label: "Dragon Scales", maxCount: 10, defaultEnabled: true, defaultIntensity: 50 },
    },
    milestoneNames: {
  1: "Threadbare Goku Turned Spark",
  8: "Black's Tarnished Omen",
  14: "Fractured Space Adventure",
  21: "Pan Joins Path",
  28: "Lowborn Legacy Myth",
  35: "Baby Parasite Pulse",
  41: "Planetary's Threat Crest",
  48: "Humble Trunks Mark",
  55: "Ragged Vegeta Mind Vow",
  61: "Tuffle's Faint Vendetta",
  68: "Lesser Super Saiyan",
  75: "Goku Suppression Force",
  81: "Doubtful Forms Form",
  88: "Earth Infection Brush",
  95: "Resistance's Legacy Flame",
  102: "Really Cool Super Spark",
  108: "Awakened Goku Training Omen",
  115: "Pan's Resolute Soul",
  122: "Rising Vegeta Liberation",
  128: "Final Clash",
  135: "Dauntless Ape Pulse",
  142: "Super Saiyan Crest",
  149: "Super's Vegeta Mark",
  155: "Fresh Baby Vow",
  162: "Valiant Earth Restoration Brush",
  169: "Myuu's Prime Crown",
  175: "Polished Hell Fighter",
  182: "Android Fusion Bloom",
  189: "Stormlit 17 Sigil",
  195: "Hell Breach Flame",
  202: "Goku's 17 Spark",
  209: "Tempered Energy Omen",
  216: "Trusted Android Weakness Seal",
  222: "Fusion's Steadfast Path",
  229: "Ironclad Super Collapse",
  236: "Dragon Balls Pulse",
  242: "Core Emergence Crest",
  249: "Negative Energy Mark",
  256: "Earth's Destruction Brush",
  262: "Formidable Shadow Clash",
  269: "Lucid Nuova Shenron Crown",
  276: "Ice's Ranked Clash",
  283: "Fabled Fire Ice",
  289: "Pan Growth Sigil",
  296: "Seasoned Journey Flame",
  303: "Seven Shadow Spark",
  309: "Nature's Dragons Omen",
  316: "Valorous Oceanus Clash",
  323: "Stalwart Rage Escalation Force",
  330: "Earth's Commanding Brush",
  336: "Refined Saiyan Reflection",
  343: "Android 17 Crest",
  350: "Blazing Legacy Mark",
  356: "Dragon Gathering Vow",
  363: "Energy's Collapse Echo",
  370: "Peerless Syn Crown",
  376: "Ardent Omega Shenron Zenith",
  383: "Turning's Focused Bloom",
  390: "Vigilant Omega Shenron",
  397: "Super Saiyan Flame",
  403: "Elite Appearance Spark",
  410: "Omega Overwhelms Omen",
  417: "Hope's Legacy Seal",
  423: "Sovereign Universal Path",
  430: "Regal Dragon Resistance Myth",
  437: "Goku's Crowned Pulse",
  444: "Mythborn Spirit Bomb",
  450: "Energy Sacrifice Mark",
  457: "Radiant Collapse Vow",
  464: "Blow Preparation Echo",
  470: "Goku's Disappearance Crown",
  477: "Climactic Victory Zenith",
  484: "Epic Dragon Ball Bloom",
  490: "Shadow's Unreal Sigil",
  497: "Peak Earth Restoration",
  504: "Saiyan Reflection Echo",
  511: "Exalted Aftermath Clash",
  517: "Peace Restored Seal",
  524: "Pan's Guardian Thread",
  531: "Celestial Trunks Myth",
  537: "Phantom Vegeta Acceptance Echo",
  544: "Goku's Crimson Crest",
  551: "Silver Dragon Ball",
  557: "Dragon Balls Vow",
  564: "Feral Legacy Echo",
  571: "Saiyan Evolution Form",
  578: "Peaceful's Transition Zenith",
  584: "Dread Time Thread",
  591: "Luminous New Generation Sigil",
  598: "Earth's Thunderous Brush",
  604: "Ultraviolet Pan Training",
  611: "Threat Echoes Echo",
  618: "Secret Solidified Seal",
  625: "Goku Legend Path",
  631: "Universe's Memory Echo",
  638: "Worldclass Level Force",
  645: "Lawless Peaceful Planet Crest",
  651: "Residual's Chosen Mark",
  658: "Fearless Dragon Ball",
  665: "Legacy Echo",
  671: "Cinematic Fighters Clash",
  678: "Saiyan Bloodline Thread",
  685: "Universal's Legacy Force",
  692: "Canonized Training Sigil",
  698: "Ascendant Earth Peace Brush",
  705: "Myth's Transfigured Spark",
  712: "Immortal Goku Eternal",
  718: "Cosmic Restored Seal",
  725: "Astral GT Echo",
  732: "Saiyan's Theory Form",
  739: "Pan's Potential Pulse",
  745: "Prismatic Vegeta Crest",
  752: "Abyssal Quiet Universe Mark",
  759: "Dormant's Unbound Force",
  765: "Eternal Legend Dragon",
  772: "Goku Eternal Clash",
  779: "Transcendent Legend Zenith",
  785: "Shadow Dragon Bloom",
  792: "Mortal's Legacy Sigil",
  799: "Ultimate Saiyan Flame",
  806: "Mythic Cosmic Energy Spark",
  812: "Universe's Godlike Omen",
  819: "Canonical Saiyan Mastery",
  826: "Goku Myth Form",
  832: "Heavenly Legacy Myth",
  839: "Pan Echo",
  846: "Closure's Emotional Soul",
  852: "Timeless Era Mark",
  859: "Empyrean Peace Sacrifice Vow",
  866: "Dragon's Primordial Echo",
  873: "Omniscient Harmony",
  879: "Goku Legendary Zenith",
  886: "Apocalyptic Myth Bloom",
  893: "Resolution Soul",
  899: "Cosmic's Balance Flame",
  906: "Final Dragon Spark",
  913: "Crowned Transformation Form",
  920: "Saiyan's Mythic Seal",
  926: "Absolute Legend",
  933: "Power Force",
  940: "Cosmic Legacy Pulse",
  946: "Universe Crest",
  953: "Saiyan's Perfect Mark",
  960: "Definitive Ultimate Vow",
  966: "Ultimate Warrior Sought Vow",
  973: "Warrior's Infinite Vow",
  980: "Sovereign Warrior Sought",
  987: "Warrior Sought Vow",
  993: "Legendary Strength Vow",
  1000: "Ultimate Ultimate Dragon"
}
}
