import { AnimeThemeConfig } from "./types"
import { GiCookingPot, GiMeatCleaver, GiDungeonGate, GiSwordClash, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiMushroom, GiHeartKey, GiFireBowl } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const dungeonMeshiTheme: AnimeThemeConfig = {
    id: "dungeon-meshi",
    displayName: "Dungeon Meshi",
    description: "After his sister is devoured by a dragon deep in a dungeon, the adventurer Laios sets out to rescue her — with the ingenious plan to cook and eat the monsters they encounter along the way.",
    fontFamily: "'Noto Sans JP', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "248 222 148",
        "--color-brand-300": "238 195 88",
        "--color-brand-400": "218 162 30",
        "--color-brand-500": "188 130 0",
        "--color-brand-600": "150 100 0",
        "--color-brand-700": "110 70 0",
        "--color-brand-800": "72 44 0",
        "--color-brand-900": "40 22 0",
        "--color-brand-950": "18 8 0",
        "--brand": "188 130 0",
        "--background": "#050300",
        "--paper": "#120800",
        "--color-gray-950": "5 3 0",
        "--color-gray-900": "12 7 0",
        "--color-gray-800": "24 14 2",
        "--color-gray-700": "40 24 6",
        "--color-gray-600": "65 40 12",
        "--color-gray-500": "102 68 26",
        "--color-gray-400": "148 108 55",
        "--color-gray-300": "190 148 90",
        "--color-gray-200": "220 185 132",
        "--color-gray-100": "240 215 172",
        "--color-gray-50": "252 240 215",
    },
    sidebarOverrides: {
        "home": { icon: GiCookingPot, label: "Mess Hall" },
        "schedule": { icon: GiAlarmClock, label: "Dungeon Run" },
        "manga": { icon: LuBookOpen, label: "Recipes" },
        "lists": { icon: GiFlowerEmblem, label: "Monster Bestiary" },
        "discover": { icon: GiBullseye, label: "New Floors" },
        "torrent-list": { icon: GiMeatCleaver, label: "Supply Cache" },
        "debrid": { icon: GiDungeonGate, label: "Dungeon Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Party" },
        "enmasse": { icon: GiResize, label: "Dungeon Crew" },
        "scan-summaries": { icon: TbReportSearch, label: "Expedition Logs" },
        "auto-downloader": { icon: LuRss, label: "Monster Feed" },
        "community": { icon: GiMushroom, label: "Adventurer Guild" },
        "achievements": { icon: GiTrophy, label: "Dungeon Trophies" },
        "milestones": { icon: LuFlag, label: "Floor Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Guild Alerts" },
        "theme-manager": { icon: GiPalette, label: "Gold Palette" },
        "extensions": { icon: BiExtension, label: "Dungeon Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Party Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Laios's Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Bite",
        "a_episode_counter": "Adapted Feast Mark",
        "a_episode_titan": "Perfect Dish Relic",
        "a_hours_invested": "Dawn Prep Proof",
        "a_time_lord": "Dungeon Elder",
        "a_anime_collector": "Recipe Archive",
        "a_library_legend": "Monster Library",
        "a_first_complete": "Floor Cleared",
        "a_hundred_club": "Hundred Recipes",
        "a_first_day": "Dungeon Dive Seal",
        "a_first_rating": "Perfect Dish Appraisal",
        "a_ten_thousand_min": "Dungeon Drama Standard",
        "a_season_veteran": "Dungeon Drama Library",
        "a_year_explorer": "Meshi Expert Map",
        "a_century_watcher": "Dungeon Vault Ledger",
        "a_five_hundred_eps": "Gold Palette Dominion",
        "a_thousand_eps": "Endless Feast Record",
        "a_watching_ten": "Mess Hall Acclaim",
        "a_ptw_hoarder": "Monster Library Library",
        "a_dropped_honesty": "Mess Hall Summit",
        "a_five_thousand_eps": "Floor Cleared Warrant",
        "a_ten_completed": "Guild Alerts Afterglow",
        "a_fifty_completed": "Hidden Recipe Ascension",
        "a_five_hundred_completed": "Mess Hall Clear",
        "a_mean_score_tracker": "Recipe Archive Verdict",
        "a_unique_studios": "Endless Feast Collection",
        "a_days_spent_watching": "Expedition Logs Dominion",
        "a_all_status": "Feast Marathon Testament",
        "a_first_favorite": "Dungeon Run Cabinet",
        "a_favorites_collector": "Dungeon Mind Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Cursed Floor Drive",
        "a_marathon_runner": "Laios's Run",
        "a_weekend_warrior": "Perfect Dish Ordeal",
        "a_non_stop": "Loyal Companion Fever",
        "a_one_more_episode": "Dungeon Meshi Mantle",
        "a_speed_run": "Quick Cook",
        "a_double_feature": "All Floors Crown",
        "a_triple_threat": "Dungeon Elder Record",
        "a_five_a_day": "Daily Cook Accord",
        "a_back_to_back": "Laios's Chain Surge",
        "a_seasonal_binge": "Perfect Dish Cascade",
        "a_cour_crusher": "Expedition Logs Ordeal",
        "a_half_day_watch": "Adapted Feast Crown",
        "a_full_day_watch": "Decade Cook Pinnacle",
        "a_power_weekend": "Dungeon Dive Run",
        "a_binge_king": "Feast Marathon",
        "a_no_sleep": "All-Night Cook",
        "a_entire_season": "Dungeon Art Library",
        "a_seven_day_challenge": "Decade Cook Mark",
        "a_hundred_day_binge": "Dungeon Dive Surge",
        "a_genre_binge": "Fantasy Dungeon Binge",
        "a_studio_binge": "Adapted Feast Fever",
        "a_season_sweep": "Senshi Standard Codex",
        "a_forty_eight_hour": "Food Critic Overture",
        "a_ep_counter_day": "Guild Alerts Aegis",
        "a_multi_series_binge": "Monster Library Streak",
        "a_midnight_binge": "Dungeon Meshi Cascade",
        "a_new_year_binge": "Dungeon Crew Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Dungeon Fight",
        "a_genre_adventure": "Dungeon Dive",
        "a_genre_comedy": "Cooking Comedy",
        "a_genre_drama": "Dungeon Drama",
        "a_genre_fantasy": "Fantasy Dungeon",
        "a_genre_horror": "Cursed Floor",
        "a_genre_mystery": "Dungeon Streak Mystery",
        "a_genre_romance": "None Here",
        "a_genre_scifi": "None Here",
        "a_genre_sol": "Floor Cleared Slice",
        "a_genre_sports": "Food Critic Sports",
        "a_genre_supernatural": "Ancient Magic",
        "a_genre_thriller": "Hidden Recipe Thriller",
        "a_genre_mecha": "None Here",
        "a_genre_music": "Dungeon Drama Music",
        "a_genre_psychological": "Dungeon Mind",
        "a_genre_ecchi": "Cursed Floor Ecchi",
        "a_genre_mahou_shoujo": "Dungeon Elder Magic Shoujo",
        "a_tag_isekai": "Iron Chef Isekai",
        "a_tag_harem": "Lost Party Harem",
        "a_tag_bl": "Food Critic Bl",
        "a_tag_gl": "Dungeon Meshi Gl",
        "a_tag_historical": "All Night Historical",
        "a_tag_military": "Gold Palette Military",
        "a_tag_school": "Monster Library School",
        "a_tag_martial_arts": "Decade Cook Martial Arts",
        "a_tag_vampire": "Dungeon Elder Vampire",
        "a_tag_samurai": "Endless Feast Samurai",
        "a_tag_space": "Night Cook Space",
        "a_tag_parody": "Laios's Run Parody",
        "a_tag_idol": "Food Critic Idol",
        "a_tag_post_apocalyptic": "Cooking Comedy Post Apocalyptic",
        "a_tag_cyberpunk": "Loyal Companion Cyberpunk",
        "a_tag_shounen": "Cooking Comedy Shounen",
        "a_tag_seinen": "Master Cook Seinen",
        "a_tag_shoujo": "Master Cook Shoujo",
        "a_tag_josei": "Guild Alerts Josei",
        "a_tag_survival": "Dungeon Mind Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Feast",
        "a_mega_completionist": "Master Cook",
        "a_completion_rate_50": "Dungeon Elder Return",
        "a_completion_rate_75": "Hidden Recipe Crown",
        "a_completion_rate_90": "Guild Alerts Resolution",
        "a_no_drop": "Dungeon Streak Decree",
        "a_long_runner_complete": "Dungeon Dive Clear",
        "a_sequel_chain": "Laios's Chain",
        "a_clean_list": "Senshi Standard Relic",
        "a_from_ptw": "Laios's Run Index",
        "a_rewatch_master": "Recipe Archive Return",
        "a_short_complete": "Ancient Magic Endgame",
        "a_same_day_start_finish": "Raw Ingredient Pinnacle",
        "a_revival": "Dungeon Vault Insignia",
        "a_zero_to_hero": "Raw Ingredient",
        "a_five_genre_complete": "Ancient Magic A Five Genre",
        "a_full_franchise": "Monster Library Chronicle",
        "a_batch_complete": "Perfect Dish Crown",
        "a_paused_to_done": "Guild Alerts Aegis Aegis",
        "a_completion_spree": "Recipe Binge Triumph",
        "a_multi_rewatch": "Recipe Binge Triumph Triumph",
        "a_dropped_recovery": "Adapted Feast Conquest",
        "a_ten_perfect_scores": "Dungeon Dive Acclaim",
        "a_seasonal_clear": "Expedition Logs Codex",
        "a_complete_genre_span": "Quick Cook A Complete Genre",
        "a_monthly_completions": "Recipe Archive Afterglow",
        "a_yearly_completions": "Feast Marathon Epilogue",
        "a_rapid_complete": "Decade Cook Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Companion",
        "a_studio_devotee": "Dungeon Streak Treasury",
        "a_rewatcher": "Second Serving",
        "a_triple_rewatch": "Fantasy Dungeon Coda",
        "a_annual_tradition": "Decade Cook Proof",
        "a_director_fan": "Senshi Standard Trial",
        "a_voice_actor_fan": "Adapted Feast Crown Crown",
        "a_ost_lover": "Monster Library Seal",
        "a_source_reader": "Meshi Expert Cabinet",
        "a_waiting_weekly": "Dungeon Streak Clock",
        "a_childhood_revisit": "Dungeon Will Seal",
        "a_saga_tracker": "Night Cook Standard",
        "a_genre_loyalty": "Floor Cleared Loyalty",
        "a_decade_watcher": "Decade Cook",
        "a_adaptation_hunter": "Laios's Run Trial",
        "a_original_anime_fan": "Winter Meal Testament",
        "a_long_commitment": "Decade Cook Mark Mark",
        "a_perfect_attendance": "Mess Hall Standard",
        "a_favorite_studio_5": "Cooking Comedy Library",
        "a_complete_catalog": "Dungeon Mind Seal",
        "a_franchise_collector": "Cooking Comedy Archive",
        "a_airing_follower": "Dungeon Will Signal",
        "a_genre_master": "Senshi Standard Master",
        "a_staff_follower": "Cooking Comedy Oath",
        "a_multi_season_fan": "All Night Hoard",
        "a_format_diversity": "Dungeon Elder Cache",
        "a_year_dedication": "Perfect Dish Tenure",
        "a_season_dedication": "Gold Palette Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Fantasy Dungeon Explorer",
        "a_studio_hopper": "Recipe Archive Collection",
        "a_tag_explorer": "Perfect Dish Explorer",
        "a_decade_hopper": "Monster Library Chronicle Chronicle",
        "a_hidden_gem": "Hidden Recipe",
        "a_popular_taste": "Food Critic Decree",
        "a_retro_appreciator": "Dungeon Mind Aegis",
        "a_modern_viewer": "Raw Ingredient Pinnacle Pinnacle",
        "a_cross_demographic": "Cursed Floor Pinnacle",
        "a_underdog_fan": "Quick Cook Trial",
        "a_variety_week": "Cooking Comedy Horizon",
        "a_foreign_cinema": "Dungeon Meshi Expedition",
        "a_classic_connoisseur": "2024 Fan",
        "a_every_season": "Dungeon Will Archive",
        "a_award_winner": "Dungeon Drama Insignia",
        "a_niche_explorer": "Master Cook Horizon",
        "a_global_anime": "Ancient Magic Crown",
        "a_cult_classic": "Dungeon Classic",
        "a_random_pick": "Food Critic Decree Decree",
        "a_new_genre_month": "Mess Hall A New Genre",
        "a_seasonal_completionist": "Dungeon Vault Summit",
        "a_unpopular_opinion": "Dungeon Run Standard",
        "a_top_rated_viewer": "Daily Cook Seal",
        "a_source_variety": "Expedition Logs Storehouse",
        "a_low_score_brave": "Loyal Companion Measure",
        "a_upcoming_watcher": "Daily Cook Seal Seal",
        "a_short_series_explorer": "Dungeon Meshi Expedition Expedition",
        "a_long_series_explorer": "All Floors Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Night Cook",
        "a_early_bird": "Dawn Prep",
        "a_lunch_break": "Ryoko Fan Trial",
        "a_golden_hour": "Dungeon Fight Tenure",
        "a_four_am_club": "Recipe Binge Gathering",
        "a_witching_hour": "Hidden Recipe Tenure",
        "a_new_year_watch": "Perfect Dish Season",
        "a_midnight_premiere": "Dungeon Crew Devotion",
        "a_all_hours": "Dungeon Vault Seal",
        "a_dawn_warrior": "Food Critic Aegis",
        "a_afternoon_delight": "Dawn Prep Proof Proof",
        "a_prime_time": "Dungeon Drama Insignia Insignia",
        "a_workday_watcher": "Cursed Floor Pinnacle Pinnacle",
        "a_sunday_marathon": "Dungeon Dive Momentum",
        "a_rainy_day": "Hidden Recipe Relic",
        "a_morning_routine": "All Night Promise",
        "a_night_shift": "Dungeon Elder Aegis",
        "a_twilight_zone": "Dungeon Art Ledger",
        "a_seasonal_premier": "Dungeon Streak Cabinet",
        "a_clock_collector": "Recipe Binge Repository",
        "a_weekend_binge_hours": "Master Cook Streak",
        "a_late_night_regular": "Feast Marathon Dominion",
        "a_sunrise_watcher": "Senshi Standard Relic Relic",
        "a_holiday_watcher": "Daily Cook Pact",
        "a_every_day_of_week": "Laios's Chain Ledger",
        "a_monthly_hours": "Food Critic Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Guild Alerts Record",
        "a_party_host": "Dungeon Elder Record Record",
        "a_social_butterfly": "Meshi Expert Company",
        "a_group_binge": "Endless Feast Sprint",
        "a_party_regular": "Dungeon Art Chronicle",
        "a_sync_viewer": "Recipe Binge Standard",
        "a_commentator": "Dungeon Mind Record",
        "a_party_marathon": "Fantasy Dungeon Vigil",
        "a_full_house": "Gold Palette Trial",
        "a_community_pillar": "Feast Marathon Alliance",
        "a_watch_party_streak": "Dungeon Mind Vigil",
        "a_diverse_party": "All Night Seal",
        "a_late_night_party": "Feast Marathon Testament Testament",
        "a_party_veteran": "Gold Palette Testament",
        "a_genre_party": "Dungeon Meshi Party",
        "a_weekly_party": "Recipe Binge Calendar",
        "a_silent_viewer": "Winter Meal Mantle",
        "a_recommendation_giver": "Master Cook Network",
        "a_party_completionist": "Night Cook Coda",
        "a_social_scorer": "Senshi Standard Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "All Floors Proof",
        "a_fibonacci": "Perfect Dish Dominion",
        "a_palindrome_day": "Perfect Dish Relic Relic",
        "a_binary_day": "Floor Cleared Mark",
        "a_full_moon": "Dungeon Will Insignia",
        "a_leap_year": "Ancient Magic Devotion",
        "a_time_traveler": "Dungeon Streak Record",
        "a_genre_clash": "Fantasy Dungeon Clash",
        "a_triple_seven": "Perfect Dish Testament",
        "a_thousand_complete": "Winter Meal Epilogue",
        "a_pi_episodes": "Cursed Floor Crown",
        "a_synchronicity": "Quick Cook Anchor",
        "a_world_record": "Adapted Feast Warrant",
        "a_nice": "Dungeon Drama Chronicle",
        "a_power_level": "Winter Meal Testament Testament",
        "a_answer_42": "Food Critic Standard",
        "a_square_number": "Fantasy Dungeon Decree",
        "a_prime_count": "Dungeon Drama Seal",
        "a_matching_date": "Quick Cook Mantle",
        "a_century_episode": "Cursed Floor Mark",
        "a_double_digits": "Hidden Recipe Testament",
        "a_one_two_three": "Ancient Magic Crown Crown",
        "a_lucky_seven": "Decade Cook Crown",
        "a_all_tens": "Loyal Companion Criterion",
        "a_exact_hundred_eps": "Night Cook Legend",
        "a_year_match_count": "Dungeon Streak Yearlong",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Master Cook Ledger",
        "a_movie_buff": "Adapted Feast Mark Mark",
        "a_ova_hunter": "Night Cook Standard Standard",
        "a_ona_explorer": "Quick Cook Secret",
        "a_special_watcher": "Hidden Recipe Relic Relic",
        "a_short_king": "Lost Party Crown",
        "a_variety_pack": "Adapted Feast Inquiry",
        "a_film_festival": "Daily Cook Chronicle",
        "a_music_video": "All Night Chronicle",
        "a_tv_short": "Fantasy Dungeon Record",
        "a_movie_marathon": "Fantasy Dungeon Gauntlet",
        "a_double_length": "All Floors Crown Crown",
        "a_anthology": "Dungeon Elder Aegis Aegis",
        "a_mini_series": "Dungeon Run Decree",
        "a_theatrical": "Cooking Comedy Accord",
        "a_format_master": "Recipe Binge Vault",
        "a_long_movie": "Dungeon Vault Insignia Insignia",
        "a_back_catalog": "Dungeon Mind Standard",
        "a_cm_watcher": "Iron Chef Aegis",
        "a_pv_collector": "Quick Cook Storehouse",
        "a_format_balance": "Recipe Binge Vault Vault",
        "a_episodic_master": "Iron Chef Standard",
        "a_sequel_movie": "Ancient Magic Pinnacle",
        "a_recap_watcher": "Ryoko Fan Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Cook",
        "a_mega_streak": "Endless Feast",
        "a_weekly_warrior": "Gold Palette Season",
        "a_monthly_watcher": "Dungeon Crew Calendar",
        "a_comeback": "Meshi Expert Decree",
        "a_weekend_streak": "Loyal Companion Passage",
        "a_no_zero_days": "Floor Cleared Warrant Warrant",
        "a_iron_will": "Dungeon Will",
        "a_habit_formed": "Laios's Chain Banner",
        "a_consistent_pace": "All Floors Measure",
        "a_year_long": "Year of Feasts",
        "a_double_streak": "Senshi Standard Watch",
        "a_streak_recovery": "Winter Meal Season",
        "a_daily_minimum": "Dungeon Crew Focus",
        "a_winter_streak": "Dungeon Meshi Watch",
        "a_summer_streak": "Hidden Recipe Resolve",
        "a_morning_streak": "Dungeon Mind Clock",
        "a_night_streak": "Laios's Chain Constancy",
        "a_unbreakable": "Lost Party Proof",
        "a_eternal_flame": "Recipe Archive Standard",
        "a_completion_streak": "Night Cook Return",
        "a_rating_streak": "Perfect Dish Balance",
        "a_multi_ep_streak": "Adapted Feast Ritual",
        "a_genre_streak": "Perfect Dish Streak",
        "a_studio_streak": "Meshi Expert Cabinet Cabinet",
        "a_perfect_week": "Quick Cook Relic",

        // ── ANIME SCORING ──
        "a_critic": "Food Critic",
        "a_perfect_ten": "Perfect Dish",
        "a_harsh_critic": "Senshi Standard",
        "a_fair_judge": "Feast Marathon Balance",
        "a_generous_spirit": "Dungeon Crew Pinnacle",
        "a_score_all": "Dawn Prep Criterion",
        "a_wide_range": "Dungeon Drama Ledger",
        "a_controversial": "Dungeon Mind Decree",
        "a_consistent_scorer": "Dungeon Streak Verdict",
        "a_score_sniper": "Ancient Magic Score",
        "a_evolving_taste": "Senshi Standard Testament",
        "a_bell_curve": "Mess Hall Insignia",
        "a_picky_watcher": "Winter Meal Warrant",
        "a_100_rated": "Recipe Binge Warrant",
        "a_500_rated": "Lost Party Pinnacle",
        "a_mediocre_majority": "Quick Cook Canon",
        "a_rating_spree": "Dungeon Mind Review",
        "a_score_variance": "Loyal Companion Score",
        "a_masterpiece_hunter": "Dungeon Mind Banner",
        "a_contrarian": "Fantasy Dungeon Record Record",
        "a_optimist": "All Night Ledger",
        "a_score_distributor": "Ryoko Fan Appraisal",
        "a_genre_critic": "All Floors Critic",
        "a_mean_above_8": "Decade Cook Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Feast",
        "a_valentines_weeb": "Cooking Comedy Vow",
        "a_pi_day": "Feast Marathon Trial",
        "a_april_fools": "Ancient Magic Devotion Devotion",
        "a_international_anime_day": "Dungeon Vault Record",
        "a_star_wars_day": "Dungeon Dive Chronicle",
        "a_summer_solstice": "Floor Cleared Calendar",
        "a_tanabata": "Raw Ingredient Focus",
        "a_friday_13th": "Ryoko Fan Relic",
        "a_halloween_spirit": "Master Cook Vow",
        "a_thanksgiving_binge": "Dungeon Art Run",
        "a_christmas_special": "Winter Meal",
        "a_new_years_eve": "Decade Cook Pilgrimage",
        "a_birthday_watch": "Mess Hall Vow",
        "a_holiday_marathon": "Endless Feast Overture",
        "a_independence_day": "Recipe Archive Banner",
        "a_culture_day": "Monster Library Insignia",
        "a_spring_equinox": "Endless Feast Decree",
        "a_earth_day": "Adapted Feast Mantle",
        "a_labor_day": "Master Cook Seal",
        "a_winter_solstice": "Cursed Floor Pilgrimage",
        "a_anime_birthday": "Adapted Feast Pilgrimage",
        "a_every_holiday": "Laios's Run Resolve",
        "a_consecutive_holidays": "Hidden Recipe Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Meshi Expert Rank",
        "a_meta_collector": "Monster Library Hoard",
        "a_meta_category_starter": "Dungeon Crew Badge",
        "a_meta_tier_climber": "Monster Library Glyph",
        "a_meta_tier_max": "True Delver",
        "a_meta_xp_earner": "Ryoko Fan Emblem",
        "a_meta_difficulty_easy": "Feast Marathon Mechanism",
        "a_meta_difficulty_hard": "Daily Cook Writ",
        "a_meta_unlock_spree": "Gold Palette Panel",
        "a_meta_completionist": "All Floors",
        "a_meta_diverse": "Perfect Dish Emblem",
        "a_meta_dominator": "Dungeon Art Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Course",
        "m_chapter_counter": "Recipe Binge Pinnacle",
        "m_chapter_titan": "Expedition Logs Relic",
        "m_reading_hours": "Ryoko Fan Relic Relic",
        "m_reading_time_lord": "Dungeon Vault Record Record",
        "m_manga_collector": "Gold Palette Ledger",
        "m_library_legend": "Monster Library Reliquary",
        "m_first_complete": "Meal Complete",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "Cooking Comedy Seal",
        "m_first_rating": "Ryoko Fan Eye",
        "m_ten_thousand_pages": "Cooking Comedy Gauge",
        "m_volume_collector": "Winter Meal Storehouse",
        "m_year_explorer": "Food Critic Quest",
        "m_century_reader": "Dungeon Meshi Dominion",
        "m_five_hundred_ch": "Dungeon Drama Legend",
        "m_thousand_ch": "Senshi Standard Legend",
        "m_reading_ten": "Dungeon Meshi Appraisal",
        "m_ptr_hoarder": "Senshi Standard Index",
        "m_dropped_honesty": "Monster Library Summit",
        "m_season_reader": "Dungeon Mind Treasury",
        "m_active_reader": "Hidden Recipe Trial",
        "m_five_thousand_ch": "Fantasy Dungeon Standard",
        "m_ten_completed": "Fantasy Dungeon Resolution",
        "m_fifty_completed": "Senshi Standard Harvest",
        "m_five_hundred_completed": "Laios's Chain Legacy",
        "m_mean_score_tracker": "Dungeon Streak Audit",
        "m_unique_authors": "Adapted Feast Reserve",
        "m_all_status": "Hidden Recipe Testament Testament",
        "m_first_favorite": "Night Cook Cache",
        "m_favorites_collector": "Meshi Expert Shelf",
        "m_days_spent_reading": "Cursed Floor Relic",

        // ── MANGA BINGE ──
        "m_binge_reader": "Mess Hall Streak",
        "m_marathon_reader": "Feast Marathon Rush",
        "m_weekend_reader": "Dungeon Will Run",
        "m_non_stop_reading": "Night Cook Gauntlet",
        "m_one_more_chapter": "Ryoko Fan Testament Testament",
        "m_speed_read": "Floor Cleared Drive",
        "m_double_story": "Endless Feast Banner",
        "m_triple_read": "Recipe Archive Record",
        "m_five_a_day": "All Night Insignia",
        "m_chapter_chain": "Monster Library Accord",
        "m_volume_binge": "Loyal Companion Drive",
        "m_power_reader": "Dungeon Dive Seal Seal",
        "m_half_day_read": "Meshi Expert Aegis",
        "m_full_day_read": "Iron Chef Aegis Aegis",
        "m_power_weekend": "Cooking Comedy Streak",
        "m_binge_king": "Recipe Binge",
        "m_no_sleep_read": "Dungeon Meshi Rush",
        "m_full_series_rush": "Feast Marathon Cascade",
        "m_seven_day_challenge": "Raw Ingredient Warrant",
        "m_hundred_day_read": "Perfect Dish Legend",
        "m_volume_rush": "Guild Alerts Gauntlet",
        "m_series_sweep": "Laios's Run Trial Trial",
        "m_genre_binge": "Iron Chef Binge",
        "m_author_binge": "Dungeon Will Surge",
        "m_chapter_counter_day": "Dungeon Art Ledger Ledger",
        "m_multi_series_binge": "Dungeon Drama Charge",
        "m_midnight_binge": "Senshi Standard Tempest",
        "m_new_year_binge": "Adapted Feast Passage",
        "m_forty_eight_hour": "Dungeon Streak Rally",
        "m_oneshot_binge": "Floor Cleared Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Chapter",
        "m_genre_adventure": "Dungeon Chapter",
        "m_genre_comedy": "Meshi Expert Comedy",
        "m_genre_drama": "Drama Chapter",
        "m_genre_fantasy": "Fantasy Chapter",
        "m_genre_horror": "Cursed Chapter",
        "m_genre_mystery": "Fantasy Dungeon Mystery",
        "m_genre_romance": "None Here",
        "m_genre_scifi": "None Here",
        "m_genre_sol": "Recipe Binge Slice",
        "m_genre_sports": "Guild Alerts Sports",
        "m_genre_supernatural": "Magic Chapter",
        "m_genre_thriller": "Quick Cook Thriller",
        "m_genre_psychological": "Deep Chapter",
        "m_genre_isekai": "Gold Palette Isekai",
        "m_genre_shounen": "Dungeon Fight Shounen",
        "m_genre_ecchi": "All Floors Ecchi",
        "m_genre_mahou_shoujo": "Meshi Expert Magic Shoujo",
        "m_genre_mecha": "Winter Meal Mecha",
        "m_genre_music": "Master Cook Music",
        "m_tag_isekai_new": "Ryoko Fan Isekai New",
        "m_tag_harem": "Dawn Prep Harem",
        "m_tag_bl": "Dungeon Run Bl",
        "m_tag_gl": "Senshi Standard Gl",
        "m_tag_historical": "Dungeon Drama Historical",
        "m_tag_military": "Dungeon Fight Military",
        "m_tag_school": "Cooking Comedy School",
        "m_tag_martial_arts": "Recipe Binge Martial Arts",
        "m_tag_vampire": "Guild Alerts Vampire",
        "m_tag_samurai": "Dungeon Elder Samurai",
        "m_tag_space": "Dungeon Run Space",
        "m_tag_parody": "Winter Meal Parody",
        "m_tag_idol": "Dungeon Run Idol",
        "m_tag_post_apocalyptic": "Monster Library Post Apocalyptic",
        "m_tag_cyberpunk": "Dawn Prep Cyberpunk",
        "m_tag_shoujo": "Daily Cook Shoujo",
        "m_tag_survival": "Meshi Expert Survival",
        "m_tag_cooking": "Mess Hall Cooking",
        "m_tag_medical": "Hidden Recipe Medical",
        "m_tag_villainess": "Dungeon Will Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Meshi Expert",
        "m_completion_rate_50": "Dungeon Run Return",
        "m_completion_rate_75": "Quick Cook Ascension",
        "m_completion_rate_90": "Recipe Archive Resolution",
        "m_no_drop": "Night Cook Decree",
        "m_long_runner_complete": "Dungeon Art Clear",
        "m_sequel_chain": "Master Cook Seal Seal",
        "m_clean_list": "Expedition Logs Relic Relic",
        "m_from_ptr": "Daily Cook Watchlist",
        "m_reread_master": "Feast Marathon Trial Trial",
        "m_oneshot_complete": "Feast Marathon Ascension",
        "m_same_day_start_finish": "Decade Cook Crown Crown",
        "m_revival": "Dungeon Art Accord",
        "m_zero_to_hundred": "Fantasy Dungeon Banner",
        "m_five_genre_complete": "Floor Cleared M Five Genre",
        "m_full_collection": "Decade Cook Proof Proof",
        "m_batch_complete": "Dungeon Streak Summit",
        "m_paused_to_done": "Recipe Archive Standard Standard",
        "m_completion_spree": "Lost Party Triumph",
        "m_format_completionist": "Feast Marathon Completion",
        "m_catch_up": "Dungeon Vault Chronicle",
        "m_multi_reread": "Night Cook Banner",
        "m_dropped_recovery": "All Floors Conquest",
        "m_ten_perfect_scores": "Dungeon Will Judgment",
        "m_complete_genre_span": "Gold Palette M Complete Genre",
        "m_monthly_completions": "Iron Chef Return",
        "m_yearly_completions": "Gold Palette Epilogue",
        "m_rapid_complete": "Raw Ingredient Finale",
        "m_author_complete": "Cooking Comedy Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Devoted Reader",
        "m_mangaka_lover": "Ryoko Fan",
        "m_rereader": "Re-serve",
        "m_triple_reread": "Perfect Dish Testament Testament",
        "m_annual_reread": "Fantasy Dungeon Banner Banner",
        "m_publisher_fan": "Lost Party Mark",
        "m_artist_fan": "Master Cook Insignia",
        "m_adaptation_compare": "Mess Hall Insignia Insignia",
        "m_source_material_fan": "Manga First",
        "m_waiting_weekly": "Dungeon Elder Streak",
        "m_classic_reader": "Winter Meal Lantern",
        "m_saga_reader": "Monster Library Decree",
        "m_genre_loyalty": "All Floors Loyalty",
        "m_decade_reader": "Loyal Companion Warrant",
        "m_ln_adaptation": "Loyal Companion Mark",
        "m_original_work": "Guild Alerts Standard",
        "m_long_commitment": "All Floors Mark",
        "m_up_to_date": "Adapted Feast Warrant Warrant",
        "m_favorite_mangaka": "Food Critic Treasury",
        "m_complete_portfolio": "Lost Party Triumph Triumph",
        "m_franchise_collector": "Dungeon Vault Archive",
        "m_serialization_follower": "Food Critic Handshake",
        "m_genre_master": "Expedition Logs Master",
        "m_multi_series_author": "Monster Library Insignia Insignia",
        "m_format_diversity": "Guild Alerts Shelf",
        "m_year_dedication": "Dungeon Meshi Tenure",
        "m_ongoing_follower": "Loyal Companion Fellowship",
        "m_genre_loyalty_50": "Senshi Standard Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Endless Feast Explorer",
        "m_publisher_hopper": "Lost Party Mantle",
        "m_tag_explorer": "Laios's Run Explorer",
        "m_decade_hopper": "Daily Cook Chronicle Chronicle",
        "m_hidden_gem": "Hidden Recipe",
        "m_popular_taste": "Dungeon Streak Record Record",
        "m_retro_reader": "Dungeon Streak Accord",
        "m_modern_reader": "Dungeon Drama Seal Seal",
        "m_cross_demographic": "Dungeon Crew Crown",
        "m_underdog_fan": "Dungeon Streak Accord Accord",
        "m_variety_week": "Master Cook Horizon Horizon",
        "m_manhwa_reader": "Ancient Magic Proof",
        "m_manhua_reader": "Winter Meal Mantle Mantle",
        "m_classic_connoisseur": "Laios's Chain Glimpse",
        "m_award_winner": "Dungeon Meshi Warrant",
        "m_niche_explorer": "Mess Hall Horizon",
        "m_world_manga": "Dungeon Vault Chronicle Chronicle",
        "m_cult_classic": "Dungeon Classic",
        "m_random_pick": "Dungeon Streak Standard",
        "m_new_genre_month": "Dungeon Vault M New Genre",
        "m_year_completionist": "Recipe Binge Fulfillment",
        "m_unpopular_opinion": "Adapted Feast Trial",
        "m_top_rated_reader": "Mess Hall Record",
        "m_source_variety": "Winter Meal Catalogue",
        "m_low_score_brave": "Recipe Binge Score",
        "m_short_manga_explorer": "Dungeon Drama Compass",
        "m_long_manga_explorer": "Fantasy Dungeon Survey",
        "m_serialization_explorer": "Quick Cook Road",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Dungeon Run Ledger",
        "m_commute_reader": "Hidden Recipe Tenure Tenure",
        "m_four_am_club": "Lost Party Fellowship",
        "m_new_year_read": "Master Cook Pact",
        "m_all_hours": "Daily Cook Accord Accord",
        "m_prime_time_reader": "Guild Alerts Banner",
        "m_workday_reader": "Dungeon Art Accord Accord",
        "m_sunday_read": "Dungeon Run Standard Standard",
        "m_morning_routine": "Dungeon Art Discipline",
        "m_night_shift_reader": "Cooking Comedy Accord Accord",
        "m_seasonal_premier_read": "Winter Meal Seasonal",
        "m_clock_collector": "Cursed Floor Reserve",
        "m_late_night_horror": "Floor Cleared Mark Mark",
        "m_afternoon_reader": "Dungeon Meshi Mantle Mantle",
        "m_golden_hour_reader": "Perfect Dish Observance",
        "m_dawn_reader": "Laios's Run Mantle",
        "m_twilight_reader": "Loyal Companion Crown",
        "m_midnight_start": "Guild Alerts Routine",
        "m_weekend_binge_hours": "Dungeon Will Momentum",
        "m_late_night_regular": "Dungeon Run Accord",
        "m_sunrise_reader": "Dawn Prep Mantle",
        "m_every_day_of_week": "Winter Meal Warrant Warrant",
        "m_monthly_hours": "Endless Feast Vigil",
        "m_bedtime_reader": "Recipe Binge Warrant Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Dungeon Art",
        "m_webtoon_reader": "Loyal Companion Mark Mark",
        "m_full_color": "Master Cook Accord",
        "m_doujin_reader": "Recipe Archive Record Record",
        "m_anthology_reader": "Dungeon Will Accord",
        "m_adaptation_reader": "Dungeon Streak Banner",
        "m_longstrip_reader": "Perfect Dish Trial",
        "m_4koma_reader": "Dungeon Elder Ledger",
        "m_oneshot_reader": "Gold Palette Mantle",
        "m_format_variety": "Lost Party Gallery",
        "m_light_novel_reader": "Daily Cook Insignia",
        "m_novel_reader": "Recipe Binge Crown",
        "m_visual_storyteller": "Dungeon Meshi Testament",
        "m_colored_classic": "Dungeon Mind Survey",
        "m_webcomic_fan": "Laios's Chain Insignia",
        "m_manga_to_anime": "Adapted Feast",
        "m_seinen_reader": "All Floors Pinnacle",
        "m_josei_reader": "Dawn Prep Pinnacle",
        "m_award_winning_art": "Dungeon Fight Relic",
        "m_debut_work": "Dungeon Fight Dominion",
        "m_vertical_scroll": "Monster Library Decree Decree",
        "m_traditional_format": "Mess Hall Hoard",
        "m_cross_media": "Dungeon Drama Accord",
        "m_spinoff_reader": "Dungeon Vault Accord",
        "m_remake_reader": "Feast Marathon Pinnacle",
        "m_collaboration_reader": "Laios's Chain Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Dungeon Streak",
        "m_weekly_warrior": "Quick Cook Season",
        "m_monthly_reader": "All Night Discipline",
        "m_comeback": "Fantasy Dungeon Standard Standard",
        "m_weekend_streak": "Dawn Prep Fever",
        "m_no_zero_days": "Ancient Magic Proof Proof",
        "m_iron_will": "Iron Chef",
        "m_habit_formed": "Dungeon Crew Crown Crown",
        "m_consistent_pace": "Decade Cook Scrutiny Scrutiny",
        "m_year_long": "Year Reading",
        "m_double_streak": "Gold Palette Resolve",
        "m_streak_recovery": "Expedition Logs Resolve",
        "m_daily_minimum": "Cursed Floor Focus",
        "m_winter_streak": "Perfect Dish Observance Observance",
        "m_summer_streak": "Dungeon Fight Observance",
        "m_morning_streak": "Endless Feast Clock",
        "m_night_streak": "Mess Hall Discipline",
        "m_unbreakable": "Dawn Prep Warrant",
        "m_eternal_flame": "Meshi Expert Record",
        "m_chapter_a_day": "Dungeon Run Ledger Ledger",
        "m_genre_streak": "Laios's Run Streak",
        "m_completion_streak": "Dungeon Streak Return",
        "m_rating_streak": "Laios's Run Appraisal",
        "m_multi_ch_streak": "Quick Cook Tenure",
        "m_author_streak": "Cursed Floor Calendar",
        "m_perfect_week_manga": "Dungeon Vault Accord Accord",
        "m_diverse_streak": "Night Cook Streak",

        // ── MANGA SCORING ──
        "m_critic": "Senshi's Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_harsh_critic": "Daily Cook Scale",
        "m_fair_judge": "Ryoko Fan Eye Eye",
        "m_generous_spirit": "Dungeon Will Decree",
        "m_score_all": "Loyal Companion Reckoning",
        "m_wide_range": "All Night Ledger Ledger",
        "m_controversial": "Iron Chef Standard Standard",
        "m_consistent_scorer": "Recipe Archive Grade",
        "m_score_sniper": "Adapted Feast Reckoning",
        "m_evolving_taste": "Gold Palette Trial Trial",
        "m_bell_curve": "All Night Accord",
        "m_picky_reader": "Night Cook Ledger",
        "m_100_rated": "All Night Standard",
        "m_500_rated": "Cooking Comedy Aegis",
        "m_mediocre_majority": "Gold Palette Canon",
        "m_rating_spree": "Endless Feast Verdict",
        "m_score_variance": "Recipe Binge Measure",
        "m_binge_rater": "Cursed Floor Passage",
        "m_reread_rerate": "Dungeon Mind Banner Banner",
        "m_masterpiece_hunter": "Iron Chef Banner",
        "m_contrarian": "Dungeon Streak Aegis",
        "m_optimist": "Dungeon Drama Accord Accord",
        "m_score_distributor": "Quick Cook Balance",
        "m_genre_critic": "Cursed Floor Critic",
        "m_mean_above_8": "Recipe Binge Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Dungeon Meshi Season",
        "m_valentines_read": "Laios's Run Observance",
        "m_pi_day": "Gold Palette Testament Testament",
        "m_april_fools": "Adapted Feast Devotion",
        "m_international_manga_day": "Daily Cook Aegis",
        "m_free_comic_day": "Dungeon Will Chronicle",
        "m_summer_solstice": "Raw Ingredient Focus Focus",
        "m_tanabata": "Decade Cook Tanabata",
        "m_friday_13th": "Feast Marathon Dominion Dominion",
        "m_halloween_read": "Floor Cleared Halloween",
        "m_thanksgiving_binge": "Dungeon Vault Charge",
        "m_christmas_read": "Dungeon Art Pact",
        "m_new_years_eve": "Raw Ingredient Pilgrimage",
        "m_birthday_read": "All Floors Focus",
        "m_holiday_marathon": "Food Critic Rally",
        "m_independence_day": "Dungeon Streak Aegis Aegis",
        "m_culture_day": "Cooking Comedy Seal Seal",
        "m_spring_equinox": "Floor Cleared Dominion",
        "m_earth_day": "All Floors Trial",
        "m_labor_day": "Dungeon Art Seal",
        "m_winter_solstice": "Dungeon Crew Focus Focus",
        "m_manga_birthday": "Decade Cook Ritual",
        "m_every_holiday_reader": "Expedition Logs Watch",
        "m_consecutive_holidays": "Feast Marathon Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Dungeon Dive Aegis",
        "m_fibonacci": "Hidden Recipe Dominion",
        "m_palindrome_day": "Gold Palette Relic",
        "m_binary_day": "Dungeon Crew Proof",
        "m_full_moon_read": "Dawn Prep Crown",
        "m_leap_year_read": "Night Cook Practice",
        "m_triple_seven": "Ryoko Fan Trial Trial",
        "m_thousand_complete": "Ryoko Fan Ascension",
        "m_nice": "Monster Library Seal Seal",
        "m_power_level_chapters": "Fantasy Dungeon Aegis",
        "m_answer_42": "Dawn Prep Trial",
        "m_square_number": "Meshi Expert Standard",
        "m_prime_count": "Ryoko Fan Pinnacle",
        "m_matching_date": "Expedition Logs Mantle",
        "m_century_chapter": "Dungeon Dive Decree",
        "m_pi_chapters": "All Floors Proof Proof",
        "m_synchronicity": "Laios's Run Emblem",
        "m_world_record": "Ancient Magic Warrant",
        "m_genre_clash": "Guild Alerts Clash",
        "m_time_traveler": "Recipe Archive Decree",
        "m_double_digits": "Winter Meal Dominion",
        "m_one_two_three": "Laios's Chain Banner Banner",
        "m_lucky_seven": "Mess Hall Record Record",
        "m_exact_hundred_ch": "Hidden Recipe Legend",
        "m_year_match_count": "Dungeon Elder Routine",
        "m_chapter_match_date": "Dungeon Crew Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Winter Meal Index",
        "m_manhwa_format": "Floor Cleared Gallery",
        "m_manhua_format": "Perfect Dish Storehouse",
        "m_ln_format": "Ryoko Fan Index",
        "m_oneshot_format": "Gold Palette Index",
        "m_doujin_format": "Endless Feast Cabinet",
        "m_novel_format": "Adapted Feast Reserve Reserve",
        "m_format_master_manga": "Endless Feast Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Recipe Archive Link",
        "m_meta_collector": "Cooking Comedy Reliquary",
        "m_meta_category_starter": "Lost Party Standard",
        "m_meta_tier_climber": "Dungeon Drama Token",
        "m_meta_tier_max": "Meshi Complete",
        "m_meta_xp_earner": "Winter Meal Anchor",
        "m_meta_difficulty_easy": "Ryoko Fan Panel",
        "m_meta_difficulty_hard": "Dungeon Meshi Node",
        "m_meta_unlock_spree": "Winter Meal Marker",
        "m_meta_completionist": "Full Library",
        "m_meta_diverse": "Gold Palette Anchor",
        "m_meta_dominator": "Monster Library Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#050300",
        primary: "#bc8200",
        secondary: "#966400",
        accent: "#50c890",
    },
    particleColor: "#d8a830",
    backgroundDim: 0.28,
    backgroundBlur: 14,
    particleTypes: {
        golden_sparks: { label: "Cooking Sparks", maxCount: 16, defaultEnabled: true, defaultIntensity: 50 },
        ember_wisps: { label: "Embers", maxCount: 12, defaultEnabled: true, defaultIntensity: 40 },
    },
milestoneNames: {
  1: "Threadbare Generic Rank Spark",
  8: "Generic's Tarnished Omen",
  14: "Fractured Generic Rank",
  21: "Generic Rank Path",
  28: "Lowborn Legacy Myth",
  35: "Generic Rank Pulse",
  41: "Generic's Legacy Crest",
  48: "Humble Generic Mark",
  55: "Ragged Generic Rank Vow",
  61: "Generic's Faint Echo",
  68: "Lesser Generic Rank",
  75: "Generic Rank Zenith",
  81: "Doubtful Legacy Bloom",
  88: "Generic Rank Sigil",
  95: "Generic's Legacy Flame",
  102: "Really Cool Generic Spark",
  108: "Awakened Generic Rank Omen",
  115: "Generic's Resolute Seal",
  122: "Rising Generic Rank",
  128: "Generic Rank Myth",
  135: "Dauntless Legacy Pulse",
  142: "Generic Rank Crest",
  149: "Generic's Legacy Mark",
  155: "Fresh Generic Vow",
  162: "Valiant Generic Rank Echo",
  169: "Generic's Prime Crown",
  175: "Polished Generic Rank",
  182: "Generic Rank Bloom",
  189: "Stormlit Legacy Sigil",
  195: "Generic Rank Flame",
  202: "Generic's Legacy Spark",
  209: "Tempered Generic Omen",
  216: "Trusted Generic Rank Seal",
  222: "Generic's Steadfast Path",
  229: "Ironclad Generic Rank",
  236: "Veteran Legacy Pulse",
  242: "Core Legacy Crest",
  249: "Generic Rank Mark",
  256: "Generic's Legacy Vow",
  262: "Formidable Generic Echo",
  269: "Lucid Generic Rank Crown",
  276: "Generic's Ranked Zenith",
  283: "Fabled Generic Rank",
  289: "Grand Legacy Sigil",
  296: "Seasoned Legacy Flame",
  303: "Generic Rank Spark",
  309: "Generic's Legacy Omen",
  316: "Valorous Generic Seal",
  323: "Stalwart Generic Rank Path",
  330: "Generic's Commanding Myth",
  336: "Refined Generic Rank",
  343: "Unbroken Legacy Crest",
  350: "Blazing Legacy Mark",
  356: "Generic Rank Vow",
  363: "Generic's Legacy Echo",
  370: "Peerless Generic Crown",
  376: "Ardent Generic Rank Zenith",
  383: "Generic's Focused Bloom",
  390: "Vigilant Generic Rank",
  397: "Dominant Legacy Flame",
  403: "Elite Legacy Spark",
  410: "Generic Rank Omen",
  417: "Generic's Legacy Seal",
  423: "Sovereign Generic Path",
  430: "Regal Generic Rank Myth",
  437: "Generic's Crowned Pulse",
  444: "Mythborn Generic Rank",
  450: "Limitless Legacy Mark",
  457: "Radiant Legacy Vow",
  464: "Generic Rank Echo",
  470: "Generic's Legacy Crown",
  477: "Climactic Generic Zenith",
  484: "Epic Generic Rank Bloom",
  490: "Generic's Unreal Sigil",
  497: "Peak Generic Rank",
  504: "Supreme Legacy Spark",
  511: "Exalted Legacy Omen",
  517: "Generic Rank Seal",
  524: "Generic's Legacy Path",
  531: "Celestial Generic Myth",
  537: "Phantom Generic Rank Pulse",
  544: "Generic's Crimson Crest",
  551: "Silver Generic Rank",
  557: "Golden Legacy Vow",
  564: "Feral Legacy Echo",
  571: "Generic Rank Crown",
  578: "Generic's Legacy Zenith",
  584: "Dread Generic Bloom",
  591: "Luminous Generic Rank Sigil",
  598: "Generic's Thunderous Flame",
  604: "Ultraviolet Generic Rank",
  611: "Unleashed Legacy Omen",
  618: "Secret Legacy Seal",
  625: "Final Generic Path",
  631: "Generic's Legacy Myth",
  638: "Worldclass Generic Pulse",
  645: "Lawless Generic Rank Crest",
  651: "Generic's Chosen Mark",
  658: "Fearless Generic Rank",
  665: "Overdrive Legacy Echo",
  671: "Cinematic Legacy Crown",
  678: "Impossible Generic Zenith",
  685: "Generic's Legacy Bloom",
  692: "Canonized Generic Sigil",
  698: "Ascendant Generic Rank Flame",
  705: "Generic's Transfigured Spark",
  712: "Immortal Generic Rank",
  718: "Eclipsed Legacy Seal",
  725: "Astral Legacy Path",
  732: "Sublime Generic Myth",
  739: "Generic's Legacy Pulse",
  745: "Prismatic Generic Crest",
  752: "Abyssal Generic Rank Mark",
  759: "Generic's Unbound Vow",
  765: "Eternal Generic Rank",
  772: "Cosmic Legacy Crown",
  779: "Transcendent Legacy Zenith",
  785: "Perfected Generic Bloom",
  792: "Generic's Legacy Sigil",
  799: "Ultimate Generic Flame",
  806: "Mythic Generic Rank Spark",
  812: "Generic's Godlike Omen",
  819: "Canonical Generic Rank",
  826: "Reality-Bent Legacy Path",
  832: "Heavenly Legacy Myth",
  839: "Absolute Generic Pulse",
  846: "Untouchable Generic Crest",
  852: "Timeless Generic Mark",
  859: "Empyrean Generic Rank Vow",
  866: "Generic's Primordial Echo",
  873: "Omniscient Generic Rank",
  879: "Unfathomed Legacy Zenith",
  886: "Apocalyptic Legacy Bloom",
  893: "Seraphic Generic Sigil",
  899: "Omega Generic Flame",
  906: "Final Generic Spark",
  913: "Crowned Generic Rank Omen",
  920: "Generic's Mythic Seal",
  926: "Absolute Generic Rank",
  933: "Eternal Legacy Myth",
  940: "Cosmic Legacy Pulse",
  946: "Transcendent Generic Crest",
  953: "Perfected Generic Mark",
  960: "Definitive Generic Vow",
  966: "Ultimate Generic Rank Echo",
  973: "Generic's Infinite Crown",
  980: "Sovereign Generic Rank",
  987: "Celestial Legacy Bloom",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate Generic Rank"
},
}
