import { AnimeThemeConfig } from "./types"
import { GiCookingPot, GiMeatCleaver, GiDungeonGate, GiSwordClash, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiMushroom, GiHeartKey, GiFireBowl } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const dungeonMeshiTheme: AnimeThemeConfig = {
    id: "dungeon-meshi",
    displayName: "Dungeon Meshi",
    description: "After his sister is devoured by a dragon deep in a dungeon, the adventurer Laios sets out to rescue her — with the ingenious plan to cook and eat the monsters they encounter along the way.",
    fontFamily: "'Noto Sans JP', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "248 222 148",
        "--color-brand-300": "238 195 88",
        "--color-brand-400": "218 162 30",
        "--color-brand-500": "188 130 0",
        "--color-brand-600": "150 100 0",
        "--color-brand-700": "110 70 0",
        "--color-brand-800": "72 44 0",
        "--color-brand-900": "40 22 0",
        "--color-brand-950": "18 8 0",
        "--brand": "188 130 0",
        "--background": "#050300",
        "--paper": "#120800",
        "--color-gray-950": "5 3 0",
        "--color-gray-900": "12 7 0",
        "--color-gray-800": "24 14 2",
        "--color-gray-700": "40 24 6",
        "--color-gray-600": "65 40 12",
        "--color-gray-500": "102 68 26",
        "--color-gray-400": "148 108 55",
        "--color-gray-300": "190 148 90",
        "--color-gray-200": "220 185 132",
        "--color-gray-100": "240 215 172",
        "--color-gray-50": "252 240 215",
    },
    sidebarOverrides: {
        "home": { icon: GiCookingPot, label: "Mess Hall" },
        "schedule": { icon: GiAlarmClock, label: "Dungeon Run" },
        "manga": { icon: LuBookOpen, label: "Recipes" },
        "lists": { icon: GiFlowerEmblem, label: "Monster Bestiary" },
        "discover": { icon: GiBullseye, label: "New Floors" },
        "torrent-list": { icon: GiMeatCleaver, label: "Supply Cache" },
        "debrid": { icon: GiDungeonGate, label: "Dungeon Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Party" },
        "enmasse": { icon: GiResize, label: "Dungeon Crew" },
        "scan-summaries": { icon: TbReportSearch, label: "Expedition Logs" },
        "auto-downloader": { icon: LuRss, label: "Monster Feed" },
        "community": { icon: GiMushroom, label: "Adventurer Guild" },
        "achievements": { icon: GiTrophy, label: "Dungeon Trophies" },
        "milestones": { icon: LuFlag, label: "Floor Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Guild Alerts" },
        "theme-manager": { icon: GiPalette, label: "Gold Palette" },
        "extensions": { icon: BiExtension, label: "Dungeon Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Party Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Laios's Config" },
    },
    achievementNames: {
        "a_first_episode": "First Bite",
        "a_first_complete": "Floor Cleared",
        "a_hundred_club": "Hundred Recipes",
        "a_time_lord": "Dungeon Elder",
        "a_anime_collector": "Recipe Archive",
        "a_library_legend": "Monster Library",
        "a_binge_king": "Feast Marathon",
        "a_no_sleep": "All-Night Cook",
        "a_marathon_runner": "Laios's Run",
        "a_speed_run": "Quick Cook",
        "a_completionist": "Full Feast",
        "a_mega_completionist": "Master Cook",
        "a_loyal_fan": "Loyal Companion",
        "a_rewatcher": "Second Serving",
        "a_decade_watcher": "Decade Cook",
        "a_genre_action": "Dungeon Fight",
        "a_genre_adventure": "Dungeon Dive",
        "a_genre_comedy": "Cooking Comedy",
        "a_genre_drama": "Dungeon Drama",
        "a_genre_fantasy": "Fantasy Dungeon",
        "a_genre_horror": "Cursed Floor",
        "a_genre_romance": "None Here",
        "a_genre_scifi": "None Here",
        "a_genre_supernatural": "Ancient Magic",
        "a_genre_psychological": "Dungeon Mind",
        "a_genre_mecha": "None Here",
        "a_critic": "Food Critic",
        "a_perfect_ten": "Perfect Dish",
        "a_harsh_critic": "Senshi Standard",
        "a_daily_streak": "Daily Cook",
        "a_mega_streak": "Endless Feast",
        "a_year_long": "Year of Feasts",
        "a_iron_will": "Dungeon Will",
        "a_hidden_gem": "Hidden Recipe",
        "a_cult_classic": "Dungeon Classic",
        "a_classic_connoisseur": "2024 Fan",
        "a_new_years_resolution": "New Year Feast",
        "a_christmas_special": "Winter Meal",
        "a_meta_tier_max": "True Delver",
        "a_meta_completionist": "All Floors",
        "a_sequel_chain": "Laios's Chain",
        "a_zero_to_hero": "Raw Ingredient",
        "a_night_owl": "Night Cook",
        "a_early_bird": "Dawn Prep",
        "m_first_chapter": "First Course",
        "m_first_complete": "Meal Complete",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Recipe Binge",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Meshi Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Re-serve",
        "m_genre_action": "Action Chapter",
        "m_genre_adventure": "Dungeon Chapter",
        "m_genre_romance": "None Here",
        "m_genre_fantasy": "Fantasy Chapter",
        "m_genre_horror": "Cursed Chapter",
        "m_genre_drama": "Drama Chapter",
        "m_genre_scifi": "None Here",
        "m_genre_supernatural": "Magic Chapter",
        "m_genre_psychological": "Deep Chapter",
        "m_critic": "Senshi's Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Dungeon Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Iron Chef",
        "m_hidden_gem": "Hidden Recipe",
        "m_cult_classic": "Dungeon Classic",
        "m_mangaka_lover": "Ryoko Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Meshi Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Dungeon Art",
        "m_manga_to_anime": "Adapted Feast",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#050300",
        primary: "#bc8200",
        secondary: "#966400",
        accent: "#50c890",
    },
    particleColor: "#d8a830",
    backgroundDim: 0.28,
    backgroundBlur: 14,
    particleTypes: {
        golden_sparks: { label: "Cooking Sparks", maxCount: 16, defaultEnabled: true, defaultIntensity: 50 },
        ember_wisps: { label: "Embers", maxCount: 12, defaultEnabled: true, defaultIntensity: 40 },
    },
milestoneNames: {
    1: "Dragon Devours Falin",
    8: "Dungeon Re-entry Decision",
    15: "Food Crisis Begins",
    22: "Monster Cooking Plan",
    29: "Laios Leadership Shift",

    36: "Senshi Joins Party",
    43: "Dungeon Cooking Starts",
    50: "Slime Cuisine First Try",
    57: "Mushroom Identification",
    64: "Basic Survival Meals",

    71: "Monster Diet Expansion",
    78: "Trap Navigation Learned",
    85: "Party Synergy Forms",
    92: "Magic Ecosystem Study",
    99: "Deep Dungeon Awareness",

    106: "Underground Ecology Map",
    113: "Living Armor Encounter",
    120: "Food Poison Survival",
    127: "Chilchuck Expertise",
    134: "Party Role Stability",

    141: "Ancient Dungeon Clues",
    148: "Monster Recipe Mastery",
    155: "Gold-Rich Food Finds",
    162: "Corpse Revival Hint",
    169: "Falin Rescue Motivation",

    176: "Undead Cuisine Discovery",
    183: "Magic Plant Cooking",
    190: "Dungeon Economy Insight",
    197: "Elf Observer Arrival",
    204: "Marcille Anxiety Growth",

    211: "Dragon Ecology Study",
    218: "Trap Monster Adaptation",
    225: "Deep Floor Entry",
    232: "Horror Cuisine Acceptance",
    239: "Party Bond Strengthens",

    246: "Ancient Civilization Ruins",
    253: "Dungeon Core Mystery",
    260: "Senshi Past Revealed",
    267: "Monster Behavior Patterns",
    274: "Food Survival Optimization",

    281: "Shifting Floor Mechanics",
    288: "Living Dungeon Theory",
    295: "Gold Dungeon Revelation",
    302: "Falin Soul Clue",
    309: "Resurrection Method Hint",

    316: "Party Mental Strain",
    323: "Monster Fusion Dishes",
    330: "Deep Dungeon Descent",
    337: "Magic Instability Zone",
    344: "Laios Obsession Growth",

    351: "Ancient Curse Discovery",
    358: "Dungeon Ecosystem Balance",
    365: "Chimera Threat Emerges",
    372: "Falin Transformation Truth",
    379: "Rescue Plan Formation",

    386: "Dungeon Core Distortion",
    393: "Monster Intelligence Signs",
    400: "Turning Point Descent",

    407: "Golden Kingdom Echo",
    414: "Dungeon Heart Revelation",
    421: "Party Fatigue Peak",
    428: "Marcille Forbidden Magic",
    435: "Senshi Culinary Mastery",

    442: "Deep Monster Civilization",
    449: "Dungeon Consciousness Theory",
    456: "Falin Location Confirmed",
    463: "Chimera Encounter Approach",
    470: "Life-Or-Death Cooking",

    477: "Dungeon Collapse Risk",
    484: "Final Floor Entry",
    491: "Ancient Spell Activation",
    498: "Party Resolve Solidifies",
    505: "Rescue Operation Begins",

    512: "Chimera Falin Encounter",
    519: "Emotional Breakthrough",
    526: "Monster Identity Conflict",
    533: "Dungeon Core Exposure",
    540: "Magic System Breakdown",

    547: "Final Battle Cooking",
    554: "Party Full Coordination",
    561: "Falin Restoration Attempt",
    568: "Dungeon Collapse Imminent",
    575: "Core Confrontation",

    582: "Dungeon Heart Battle",
    589: "Falin Rescue Success",
    596: "Magic Stabilization",
    603: "Escape from Deep Dungeon",

    610: "Surface Return",
    617: "Party Recovery Phase",
    624: "Dungeon Knowledge Expansion",
    631: "Senshi Legacy Acknowledged",
    638: "Marcille Growth Acceptance",

    645: "Post-Dungeon Analysis",
    652: "Monster Cuisine Normalized",
    659: "Party Bond Deepens",
    666: "Falin Reintegration",

    673: "Dungeon Threat Contained",
    680: "Ancient Mystery Remains",
    687: "Ecology Understanding Complete",
    694: "Survival Philosophy Established",

    701: "New Dungeon Expeditions",
    708: "Cooking Innovation Peak",
    715: "Party Stability Achieved",
    722: "Monster World Accepted",
    729: "Dungeon Society Theory",

    736: "Peaceful Exploration Era",
    743: "Knowledge Expansion",
    750: "Balance Between Life and Dungeon",

    757: "Legend of Dungeon Meshi",
    764: "Senshi Culinary Myth",
    771: "Laios Monster Wisdom",
    778: "Marcille Magic Understanding",

    785: "Quiet Dungeon Stability",
    792: "Dormant Core Activity",

    799: "Legend of Delicious in Dungeon",
    806: "Monster Cooking Myth",
    813: "Dungeon Survivor Legend",
    820: "Falin Resurrection Story",

    827: "Beyond Survival",
    834: "Perfect Dungeon Harmony",
    841: "Monster Ecology Balance",
    848: "Party Unity Achieved",

    855: "Absolute Survival Mastery",
    862: "Laios Peak Understanding",
    869: "Senshi Culinary Perfection",
    876: "Marcille Magic Harmony",

    883: "Final Emotional Closure",
    890: "Dungeon Peace Established",
    897: "Life Through Monsters",

    904: "Beyond Dungeon Depth",
    911: "Perfect Survival System",
    918: "Party Legendary Status",
    925: "Dungeon Eternal Myth",

    932: "Final Identity Resolution",
    939: "Absolute Ecosystem Balance",
    946: "Dungeon Truth Revealed",
    953: "Beyond Life and Death",

    960: "Absolute Dungeon Existence",
    967: "Legend of Dungeon Meshi",
    974: "Perfect Survival Flow",
    981: "Beyond Hunger",
    988: "Absolute Dungeon State",
    995: "Perfect Monster Harmony",
    998: "Ultimate Culinary Survival",
    1000: "A Group of Adventurers Who Entered a Dungeon to Save a Friend Learned That Survival Was Not Just About Strength or Magic, but About Understanding the World So Deeply That Even Monsters Became Part of Life Itself"
},
}
