import { AnimeThemeConfig } from "./types"
import { GiSteampunkGoggles, GiFairyWings, GiParachute, GiLightningBow, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiWaves } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const eurekaSevenTheme: AnimeThemeConfig = {
    id: "eureka-seven",
    displayName: "Eureka Seven",
    description: "Teenage Renton Thurston joins the renegade group Gekkostate on the surfing robot LFO Nirvash to fight against the military, inspired by the mysterious pilot Eureka.",
    fontFamily: "'Raleway', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Raleway:wght@300;400;600&display=swap",
    cssVars: {
        "--color-brand-200": "160 225 245",
        "--color-brand-300": "100 200 235",
        "--color-brand-400": "45 172 220",
        "--color-brand-500": "5 145 200",
        "--color-brand-600": "3 115 165",
        "--color-brand-700": "2 86 130",
        "--color-brand-800": "1 58 95",
        "--color-brand-900": "0 34 58",
        "--color-brand-950": "0 18 32",
        "--brand": "5 145 200",
        "--background": "#000508",
        "--paper": "#000c12",
        "--color-gray-950": "0 5 8",
        "--color-gray-900": "0 10 16",
        "--color-gray-800": "2 18 28",
        "--color-gray-700": "4 30 46",
        "--color-gray-600": "8 48 72",
        "--color-gray-500": "16 74 108",
        "--color-gray-400": "40 110 148",
        "--color-gray-300": "80 150 182",
        "--color-gray-200": "120 188 210",
        "--color-gray-100": "162 212 228",
        "--color-gray-50": "206 235 244",
    },
    sidebarOverrides: {
        "home": { icon: GiSteampunkGoggles, label: "Gekkostate" },
        "schedule": { icon: GiAlarmClock, label: "Lift Schedule" },
        "manga": { icon: LuBookOpen, label: "Ray=Out Zine" },
        "lists": { icon: GiFairyWings, label: "LFO Registry" },
        "discover": { icon: GiBullseye, label: "Trapar Scouting" },
        "torrent-list": { icon: GiParachute, label: "Lift Cache" },
        "debrid": { icon: GiWaves, label: "Trapar Network" },
        "unmatched": { icon: GiLightningBow, label: "Unknown LFOs" },
        "enmasse": { icon: GiResize, label: "Gekkostate Deploy" },
        "scan-summaries": { icon: TbReportSearch, label: "Mission Reports" },
        "auto-downloader": { icon: LuRss, label: "Broadcast Feed" },
        "community": { icon: GiSteampunkGoggles, label: "Gekkostate Crew" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Trapar Alerts" },
        "achievements": { icon: GiTrophy, label: "Lifting Trophies" },
        "milestones": { icon: LuFlag, label: "Ref Board Goals" },
        "theme-manager": { icon: GiPalette, label: "Trapar Colors" },
        "extensions": { icon: BiExtension, label: "LFO Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Gekkostate Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Nirvash Settings" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "Lifting Off",
        "a_episode_counter": "Loves Eureka Mark",
        "a_episode_titan": "Ageha Squad Relic",
        "a_hours_invested": "Teenage Renton Thurston Proof",
        "a_time_lord": "Lift Veteran",
        "a_anime_collector": "LFO Cache",
        "a_library_legend": "Ray=Out Archive",
        "a_first_complete": "Compac Drive",
        "a_hundred_club": "Hundred Lifts",
        "a_first_day": "Lifting Off Seal",
        "a_first_rating": "Ageha Squad Appraisal",
        "a_ten_thousand_min": "Renton Grows Standard",
        "a_season_veteran": "Renton Grows Library",
        "a_year_explorer": "Lfo Registry Map",
        "a_century_watcher": "Compac Drive Ledger",
        "a_five_hundred_eps": "Lfo Nirvash Dominion",
        "a_thousand_eps": "Endless Lift Record",
        "a_watching_ten": "Renton Loves Eureka Acclaim",
        "a_ptw_hoarder": "Trapar Network Library",
        "a_dropped_honesty": "Renton Loves Eureka Summit",
        "a_five_thousand_eps": "Bones Master Warrant",
        "a_ten_completed": "Coming Age Afterglow",
        "a_fifty_completed": "Lift Resolve Ascension",
        "a_five_hundred_completed": "Renton Loves Eureka Clear",
        "a_mean_score_tracker": "Trapar Alerts Verdict",
        "a_unique_studios": "Endless Lift Collection",
        "a_days_spent_watching": "Classic Mecha Dominion",
        "a_all_status": "Eureka's Past Testament",
        "a_first_favorite": "Scub Coral Cabinet",
        "a_favorites_collector": "Sky Revisit Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Out Archive Drive",
        "a_marathon_runner": "Aerial Journey",
        "a_weekend_warrior": "Ageha Squad Ordeal",
        "a_non_stop": "Aerial Journey Fever",
        "a_one_more_episode": "Unknown Lfos Mantle",
        "a_speed_run": "Seven Swell",
        "a_double_feature": "Night Lift Crown",
        "a_triple_threat": "Renton Fails Record",
        "a_five_a_day": "All Night Accord",
        "a_back_to_back": "Renton Loves Surge",
        "a_seasonal_binge": "Ageha Squad Cascade",
        "a_cour_crusher": "Classic Mecha Ordeal",
        "a_half_day_watch": "Loves Eureka Crown",
        "a_full_day_watch": "Lift Judge Pinnacle",
        "a_power_weekend": "Lifting Off Run",
        "a_binge_king": "Lifting Marathon",
        "a_no_sleep": "All-Night Lift",
        "a_entire_season": "Sky Critic Library",
        "a_seven_day_challenge": "Lift Judge Mark",
        "a_hundred_day_binge": "Lifting Off Surge",
        "a_genre_binge": "Renton's Heart Binge",
        "a_studio_binge": "Loves Eureka Fever",
        "a_season_sweep": "Holland Strict Codex",
        "a_forty_eight_hour": "Daily Lift Overture",
        "a_ep_counter_day": "Coming Age Aegis",
        "a_multi_series_binge": "Trapar Network Streak",
        "a_midnight_binge": "Unknown Lfos Cascade",
        "a_new_year_binge": "Author Fan Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "LFO Battle",
        "a_genre_adventure": "Gekkostate Journey",
        "a_genre_comedy": "Renton Fails",
        "a_genre_drama": "Eureka's Past",
        "a_genre_fantasy": "Trapar World",
        "a_genre_horror": "Ageha Squad",
        "a_genre_mystery": "Eureka Expert Mystery",
        "a_genre_romance": "Renton Loves Eureka",
        "a_genre_scifi": "Scub Coral",
        "a_genre_sol": "Bones Master Slice",
        "a_genre_sports": "Daily Lift Sports",
        "a_genre_supernatural": "Compac Drive",
        "a_genre_thriller": "Lift Resolve Thriller",
        "a_genre_mecha": "Nirvash TypeZERO",
        "a_genre_music": "Renton Grows Music",
        "a_genre_psychological": "Renton Grows",
        "a_genre_ecchi": "Out Archive Ecchi",
        "a_genre_mahou_shoujo": "Renton Fails Magic Shoujo",
        "a_tag_isekai": "Sky Art Isekai",
        "a_tag_harem": "Ref Board Harem",
        "a_tag_bl": "Daily Lift Bl",
        "a_tag_gl": "Unknown Lfos Gl",
        "a_tag_historical": "Out Zine Historical",
        "a_tag_military": "Lfo Nirvash Military",
        "a_tag_school": "Trapar Network School",
        "a_tag_martial_arts": "Lift Judge Martial Arts",
        "a_tag_vampire": "Renton Fails Vampire",
        "a_tag_samurai": "Endless Lift Samurai",
        "a_tag_space": "Ao Sequel Space",
        "a_tag_parody": "Decade Fan Parody",
        "a_tag_idol": "Daily Lift Idol",
        "a_tag_post_apocalyptic": "Hidden Trapar Post Apocalyptic",
        "a_tag_cyberpunk": "Aerial Journey Cyberpunk",
        "a_tag_shounen": "Hidden Trapar Shounen",
        "a_tag_seinen": "Lfo Battle Seinen",
        "a_tag_shoujo": "Lfo Battle Shoujo",
        "a_tag_josei": "Coming Age Josei",
        "a_tag_survival": "Sky Revisit Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "Scub Coral",
        "a_mega_completionist": "BONES Master",
        "a_completion_rate_50": "Renton Fails Return",
        "a_completion_rate_75": "Lift Resolve Crown",
        "a_completion_rate_90": "Coming Age Resolution",
        "a_no_drop": "Eureka Expert Decree",
        "a_long_runner_complete": "Lifting Off Clear",
        "a_sequel_chain": "AO Sequel",
        "a_clean_list": "Holland Strict Relic",
        "a_from_ptw": "Decade Fan Index",
        "a_rewatch_master": "Trapar Alerts Return",
        "a_short_complete": "Moonlit Lift Endgame",
        "a_same_day_start_finish": "Bones Classic Pinnacle",
        "a_revival": "Compac Drive Insignia",
        "a_zero_to_hero": "Mechanic to Pilot",
        "a_five_genre_complete": "Moonlit Lift A Five Genre",
        "a_full_franchise": "Trapar Network Chronicle",
        "a_batch_complete": "Ageha Squad Crown",
        "a_paused_to_done": "Coming Age Aegis Aegis",
        "a_completion_spree": "Eureka Seven Triumph",
        "a_multi_rewatch": "Eureka Seven Triumph Triumph",
        "a_dropped_recovery": "Loves Eureka Conquest",
        "a_ten_perfect_scores": "Lifting Off Acclaim",
        "a_seasonal_clear": "Classic Mecha Codex",
        "a_complete_genre_span": "Dawn Lift A Complete Genre",
        "a_monthly_completions": "Trapar Alerts Afterglow",
        "a_yearly_completions": "Eureka's Past Epilogue",
        "a_rapid_complete": "Lift Judge Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Renton's Heart",
        "a_studio_devotee": "Eureka Expert Treasury",
        "a_rewatcher": "Sky Revisit",
        "a_triple_rewatch": "Renton's Heart Coda",
        "a_annual_tradition": "Lift Judge Proof",
        "a_director_fan": "Holland Strict Trial",
        "a_voice_actor_fan": "Loves Eureka Crown Crown",
        "a_ost_lover": "Trapar Network Seal",
        "a_source_reader": "Lfo Registry Cabinet",
        "a_waiting_weekly": "Eureka Expert Clock",
        "a_childhood_revisit": "Endless Sky Seal",
        "a_saga_tracker": "Ao Sequel Standard",
        "a_genre_loyalty": "Bones Master Loyalty",
        "a_decade_watcher": "Decade Fan",
        "a_adaptation_hunter": "Decade Fan Trial",
        "a_original_anime_fan": "Winter Sky Testament",
        "a_long_commitment": "Lift Judge Mark Mark",
        "a_perfect_attendance": "Renton Loves Eureka Standard",
        "a_favorite_studio_5": "Hidden Trapar Library",
        "a_complete_catalog": "Sky Revisit Seal",
        "a_franchise_collector": "Hidden Trapar Archive",
        "a_airing_follower": "Endless Sky Signal",
        "a_genre_master": "Holland Strict Master",
        "a_staff_follower": "Hidden Trapar Oath",
        "a_multi_season_fan": "Out Zine Hoard",
        "a_format_diversity": "Renton Fails Cache",
        "a_year_dedication": "Ageha Squad Tenure",
        "a_season_dedication": "Lfo Nirvash Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Renton's Heart Explorer",
        "a_studio_hopper": "Trapar Alerts Collection",
        "a_tag_explorer": "Ageha Squad Explorer",
        "a_decade_hopper": "Trapar Network Chronicle Chronicle",
        "a_hidden_gem": "Hidden Trapar",
        "a_popular_taste": "Daily Lift Decree",
        "a_retro_appreciator": "Sky Revisit Aegis",
        "a_modern_viewer": "Bones Classic Pinnacle Pinnacle",
        "a_cross_demographic": "Out Archive Pinnacle",
        "a_underdog_fan": "Dawn Lift Trial",
        "a_variety_week": "Hidden Trapar Horizon",
        "a_foreign_cinema": "Unknown Lfos Expedition",
        "a_classic_connoisseur": "2005 Fan",
        "a_every_season": "Endless Sky Archive",
        "a_award_winner": "Renton Grows Insignia",
        "a_niche_explorer": "Lfo Battle Horizon",
        "a_global_anime": "Moonlit Lift Crown",
        "a_cult_classic": "BONES Classic",
        "a_random_pick": "Daily Lift Decree Decree",
        "a_new_genre_month": "Renton Loves Eureka A New",
        "a_seasonal_completionist": "Compac Drive Summit",
        "a_unpopular_opinion": "Scub Coral Standard",
        "a_top_rated_viewer": "All Night Seal",
        "a_source_variety": "Classic Mecha Storehouse",
        "a_low_score_brave": "Aerial Journey Measure",
        "a_upcoming_watcher": "All Night Seal Seal",
        "a_short_series_explorer": "Unknown Lfos Expedition Expedition",
        "a_long_series_explorer": "Night Lift Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Moonlit Lift",
        "a_early_bird": "Dawn Lift",
        "a_lunch_break": "Ray Out Trial",
        "a_golden_hour": "Trapar World Tenure",
        "a_four_am_club": "Eureka Seven Gathering",
        "a_witching_hour": "Lift Resolve Tenure",
        "a_new_year_watch": "Ageha Squad Season",
        "a_midnight_premiere": "Author Fan Devotion",
        "a_all_hours": "Compac Drive Seal",
        "a_dawn_warrior": "Daily Lift Aegis",
        "a_afternoon_delight": "Teenage Renton Thurston Proof Proof",
        "a_prime_time": "Renton Grows Insignia Insignia",
        "a_workday_watcher": "Out Archive Pinnacle Pinnacle",
        "a_sunday_marathon": "Lifting Off Momentum",
        "a_rainy_day": "Lift Resolve Relic",
        "a_morning_routine": "Out Zine Promise",
        "a_night_shift": "Renton Fails Aegis",
        "a_twilight_zone": "Sky Critic Ledger",
        "a_seasonal_premier": "Eureka Expert Cabinet",
        "a_clock_collector": "Eureka Seven Repository",
        "a_weekend_binge_hours": "Lfo Battle Streak",
        "a_late_night_regular": "Eureka's Past Dominion",
        "a_sunrise_watcher": "Holland Strict Relic Relic",
        "a_holiday_watcher": "All Night Pact",
        "a_every_day_of_week": "Renton Loves Ledger",
        "a_monthly_hours": "Daily Lift Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Coming Age Record",
        "a_party_host": "Renton Fails Record Record",
        "a_social_butterfly": "Lfo Registry Company",
        "a_group_binge": "Endless Lift Sprint",
        "a_party_regular": "Sky Critic Chronicle",
        "a_sync_viewer": "Eureka Seven Standard",
        "a_commentator": "Sky Revisit Record",
        "a_party_marathon": "Renton's Heart Vigil",
        "a_full_house": "Lfo Nirvash Trial",
        "a_community_pillar": "Eureka's Past Alliance",
        "a_watch_party_streak": "Sky Revisit Vigil",
        "a_diverse_party": "Out Zine Seal",
        "a_late_night_party": "Eureka's Past Testament Testament",
        "a_party_veteran": "Lfo Nirvash Testament",
        "a_genre_party": "Unknown Lfos Party",
        "a_weekly_party": "Eureka Seven Calendar",
        "a_silent_viewer": "Winter Sky Mantle",
        "a_recommendation_giver": "Lfo Battle Network",
        "a_party_completionist": "Ao Sequel Coda",
        "a_social_scorer": "Holland Strict Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Night Lift Proof",
        "a_fibonacci": "Ageha Squad Dominion",
        "a_palindrome_day": "Ageha Squad Relic Relic",
        "a_binary_day": "Bones Master Mark",
        "a_full_moon": "Endless Sky Insignia",
        "a_leap_year": "Moonlit Lift Devotion",
        "a_time_traveler": "Eureka Expert Record",
        "a_genre_clash": "Renton's Heart Clash",
        "a_triple_seven": "Ageha Squad Testament",
        "a_thousand_complete": "Winter Sky Epilogue",
        "a_pi_episodes": "Out Archive Crown",
        "a_synchronicity": "Dawn Lift Anchor",
        "a_world_record": "Loves Eureka Warrant",
        "a_nice": "Renton Grows Chronicle",
        "a_power_level": "Winter Sky Testament Testament",
        "a_answer_42": "Daily Lift Standard",
        "a_square_number": "Renton's Heart Decree",
        "a_prime_count": "Renton Grows Seal",
        "a_matching_date": "Dawn Lift Mantle",
        "a_century_episode": "Out Archive Mark",
        "a_double_digits": "Lift Resolve Testament",
        "a_one_two_three": "Moonlit Lift Crown Crown",
        "a_lucky_seven": "Lift Judge Crown",
        "a_all_tens": "Aerial Journey Criterion",
        "a_exact_hundred_eps": "Ao Sequel Legend",
        "a_year_match_count": "Eureka Expert Yearlong",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Lfo Battle Ledger",
        "a_movie_buff": "Loves Eureka Mark Mark",
        "a_ova_hunter": "Ao Sequel Standard Standard",
        "a_ona_explorer": "Dawn Lift Secret",
        "a_special_watcher": "Lift Resolve Relic Relic",
        "a_short_king": "Ref Board Crown",
        "a_variety_pack": "Loves Eureka Inquiry",
        "a_film_festival": "All Night Chronicle",
        "a_music_video": "Out Zine Chronicle",
        "a_tv_short": "Renton's Heart Record",
        "a_movie_marathon": "Renton's Heart Gauntlet",
        "a_double_length": "Night Lift Crown Crown",
        "a_anthology": "Renton Fails Aegis Aegis",
        "a_mini_series": "Scub Coral Decree",
        "a_theatrical": "Hidden Trapar Accord",
        "a_format_master": "Eureka Seven Vault",
        "a_long_movie": "Compac Drive Insignia Insignia",
        "a_back_catalog": "Sky Revisit Standard",
        "a_cm_watcher": "Sky Art Aegis",
        "a_pv_collector": "Dawn Lift Storehouse",
        "a_format_balance": "Eureka Seven Vault Vault",
        "a_episodic_master": "Sky Art Standard",
        "a_sequel_movie": "Moonlit Lift Pinnacle",
        "a_recap_watcher": "Ray Out Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Lift",
        "a_mega_streak": "Endless Sky",
        "a_weekly_warrior": "Lfo Nirvash Season",
        "a_monthly_watcher": "Author Fan Calendar",
        "a_comeback": "Lfo Registry Decree",
        "a_weekend_streak": "Aerial Journey Passage",
        "a_no_zero_days": "Bones Master Warrant Warrant",
        "a_iron_will": "Renton's Growth",
        "a_habit_formed": "Renton Loves Banner",
        "a_consistent_pace": "Night Lift Measure",
        "a_year_long": "Year of Lifting",
        "a_double_streak": "Holland Strict Watch",
        "a_streak_recovery": "Winter Sky Season",
        "a_daily_minimum": "Author Fan Focus",
        "a_winter_streak": "Unknown Lfos Watch",
        "a_summer_streak": "Lift Resolve Resolve",
        "a_morning_streak": "Sky Revisit Clock",
        "a_night_streak": "Renton Loves Constancy",
        "a_unbreakable": "Ref Board Proof",
        "a_eternal_flame": "Trapar Alerts Standard",
        "a_completion_streak": "Ao Sequel Return",
        "a_rating_streak": "Ageha Squad Balance",
        "a_multi_ep_streak": "Loves Eureka Ritual",
        "a_genre_streak": "Ageha Squad Streak",
        "a_studio_streak": "Lfo Registry Cabinet Cabinet",
        "a_perfect_week": "Dawn Lift Relic",

        // ── ANIME SCORING ──
        "a_critic": "Lift Judge",
        "a_perfect_ten": "Seven Swell",
        "a_harsh_critic": "Holland Strict",
        "a_fair_judge": "Eureka's Past Balance",
        "a_generous_spirit": "Author Fan Pinnacle",
        "a_score_all": "Teenage Renton Thurston Criterion",
        "a_wide_range": "Renton Grows Ledger",
        "a_controversial": "Sky Revisit Decree",
        "a_consistent_scorer": "Eureka Expert Verdict",
        "a_score_sniper": "Moonlit Lift Score",
        "a_evolving_taste": "Holland Strict Testament",
        "a_bell_curve": "Renton Loves Eureka Insignia",
        "a_picky_watcher": "Winter Sky Warrant",
        "a_100_rated": "Eureka Seven Warrant",
        "a_500_rated": "Ref Board Pinnacle",
        "a_mediocre_majority": "Dawn Lift Canon",
        "a_rating_spree": "Sky Revisit Review",
        "a_score_variance": "Aerial Journey Score",
        "a_masterpiece_hunter": "Sky Revisit Banner",
        "a_contrarian": "Renton's Heart Record Record",
        "a_optimist": "Out Zine Ledger",
        "a_score_distributor": "Ray Out Appraisal",
        "a_genre_critic": "Night Lift Critic",
        "a_mean_above_8": "Lift Judge Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Lift",
        "a_valentines_weeb": "Hidden Trapar Vow",
        "a_pi_day": "Eureka's Past Trial",
        "a_april_fools": "Moonlit Lift Devotion Devotion",
        "a_international_anime_day": "Compac Drive Record",
        "a_star_wars_day": "Lifting Off Chronicle",
        "a_summer_solstice": "Bones Master Calendar",
        "a_tanabata": "Bones Classic Focus",
        "a_friday_13th": "Ray Out Relic",
        "a_halloween_spirit": "Lfo Battle Vow",
        "a_thanksgiving_binge": "Sky Critic Run",
        "a_christmas_special": "Winter Sky",
        "a_new_years_eve": "Lift Judge Pilgrimage",
        "a_birthday_watch": "Renton Loves Eureka Vow",
        "a_holiday_marathon": "Endless Lift Overture",
        "a_independence_day": "Trapar Alerts Banner",
        "a_culture_day": "Trapar Network Insignia",
        "a_spring_equinox": "Endless Lift Decree",
        "a_earth_day": "Loves Eureka Mantle",
        "a_labor_day": "Lfo Battle Seal",
        "a_winter_solstice": "Out Archive Pilgrimage",
        "a_anime_birthday": "Loves Eureka Pilgrimage",
        "a_every_holiday": "Decade Fan Resolve",
        "a_consecutive_holidays": "Lift Resolve Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Lfo Registry Rank",
        "a_meta_collector": "Trapar Network Hoard",
        "a_meta_category_starter": "Author Fan Badge",
        "a_meta_tier_climber": "Trapar Network Glyph",
        "a_meta_tier_max": "Nirvash Legend",
        "a_meta_xp_earner": "Ray Out Emblem",
        "a_meta_difficulty_easy": "Eureka's Past Mechanism",
        "a_meta_difficulty_hard": "All Night Writ",
        "a_meta_unlock_spree": "Lfo Nirvash Panel",
        "a_meta_completionist": "Complete Series",
        "a_meta_diverse": "Ageha Squad Emblem",
        "a_meta_dominator": "Sky Critic Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Lift",
        "m_chapter_counter": "Eureka Seven Pinnacle",
        "m_chapter_titan": "Classic Mecha Relic",
        "m_reading_hours": "Ray Out Relic Relic",
        "m_reading_time_lord": "Compac Drive Record Record",
        "m_manga_collector": "Lfo Nirvash Ledger",
        "m_library_legend": "Trapar Network Reliquary",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "Hidden Trapar Seal",
        "m_first_rating": "Ray Out Eye",
        "m_ten_thousand_pages": "Hidden Trapar Gauge",
        "m_volume_collector": "Winter Sky Storehouse",
        "m_year_explorer": "Daily Lift Quest",
        "m_century_reader": "Unknown Lfos Dominion",
        "m_five_hundred_ch": "Renton Grows Legend",
        "m_thousand_ch": "Holland Strict Legend",
        "m_reading_ten": "Unknown Lfos Appraisal",
        "m_ptr_hoarder": "Holland Strict Index",
        "m_dropped_honesty": "Trapar Network Summit",
        "m_season_reader": "Sky Revisit Treasury",
        "m_active_reader": "Lift Resolve Trial",
        "m_five_thousand_ch": "Renton's Heart Standard",
        "m_ten_completed": "Renton's Heart Resolution",
        "m_fifty_completed": "Holland Strict Harvest",
        "m_five_hundred_completed": "Renton Loves Legacy",
        "m_mean_score_tracker": "Eureka Expert Audit",
        "m_unique_authors": "Loves Eureka Reserve",
        "m_all_status": "Lift Resolve Testament Testament",
        "m_first_favorite": "Ao Sequel Cache",
        "m_favorites_collector": "Lfo Registry Shelf",
        "m_days_spent_reading": "Out Archive Relic",

        // ── MANGA BINGE ──
        "m_binge_reader": "Renton Loves Eureka Streak",
        "m_marathon_reader": "Eureka's Past Rush",
        "m_weekend_reader": "Endless Sky Run",
        "m_non_stop_reading": "Ao Sequel Gauntlet",
        "m_one_more_chapter": "Ray Out Testament Testament",
        "m_speed_read": "Bones Master Drive",
        "m_double_story": "Endless Lift Banner",
        "m_triple_read": "Trapar Alerts Record",
        "m_five_a_day": "Out Zine Insignia",
        "m_chapter_chain": "Trapar Network Accord",
        "m_volume_binge": "Aerial Journey Drive",
        "m_power_reader": "Lifting Off Seal Seal",
        "m_half_day_read": "Lfo Registry Aegis",
        "m_full_day_read": "Sky Art Aegis Aegis",
        "m_power_weekend": "Hidden Trapar Streak",
        "m_binge_king": "Lifting Marathon",
        "m_no_sleep_read": "Unknown Lfos Rush",
        "m_full_series_rush": "Eureka's Past Cascade",
        "m_seven_day_challenge": "Bones Classic Warrant",
        "m_hundred_day_read": "Ageha Squad Legend",
        "m_volume_rush": "Coming Age Gauntlet",
        "m_series_sweep": "Decade Fan Trial Trial",
        "m_genre_binge": "Sky Art Binge",
        "m_author_binge": "Endless Sky Surge",
        "m_chapter_counter_day": "Sky Critic Ledger Ledger",
        "m_multi_series_binge": "Renton Grows Charge",
        "m_midnight_binge": "Holland Strict Tempest",
        "m_new_year_binge": "Loves Eureka Passage",
        "m_forty_eight_hour": "Eureka Expert Rally",
        "m_oneshot_binge": "Bones Master Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Battle Chapter",
        "m_genre_adventure": "Sky Chapter",
        "m_genre_comedy": "Lfo Registry Comedy",
        "m_genre_drama": "Growth Chapter",
        "m_genre_fantasy": "Trapar Chapter",
        "m_genre_horror": "Dark Chapter",
        "m_genre_mystery": "Renton's Heart Mystery",
        "m_genre_romance": "Love Chapter",
        "m_genre_scifi": "Scub Chapter",
        "m_genre_sol": "Eureka Seven Slice",
        "m_genre_sports": "Coming Age Sports",
        "m_genre_supernatural": "Compac Chapter",
        "m_genre_thriller": "Dawn Lift Thriller",
        "m_genre_psychological": "Coming of Age",
        "m_genre_isekai": "Lfo Nirvash Isekai",
        "m_genre_shounen": "Trapar World Shounen",
        "m_genre_ecchi": "Night Lift Ecchi",
        "m_genre_mahou_shoujo": "Lfo Registry Magic Shoujo",
        "m_genre_mecha": "Winter Sky Mecha",
        "m_genre_music": "Lfo Battle Music",
        "m_tag_isekai_new": "Ray Out Isekai New",
        "m_tag_harem": "Teenage Renton Thurston Harem",
        "m_tag_bl": "Scub Coral Bl",
        "m_tag_gl": "Holland Strict Gl",
        "m_tag_historical": "Renton Grows Historical",
        "m_tag_military": "Trapar World Military",
        "m_tag_school": "Hidden Trapar School",
        "m_tag_martial_arts": "Eureka Seven Martial Arts",
        "m_tag_vampire": "Coming Age Vampire",
        "m_tag_samurai": "Renton Fails Samurai",
        "m_tag_space": "Scub Coral Space",
        "m_tag_parody": "Winter Sky Parody",
        "m_tag_idol": "Scub Coral Idol",
        "m_tag_post_apocalyptic": "Trapar Network Post Apocalyptic",
        "m_tag_cyberpunk": "Teenage Renton Thurston Cyberpunk",
        "m_tag_shoujo": "All Night Shoujo",
        "m_tag_survival": "Lfo Registry Survival",
        "m_tag_cooking": "Renton Loves Eureka Cooking",
        "m_tag_medical": "Lift Resolve Medical",
        "m_tag_villainess": "Endless Sky Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Journey",
        "m_mega_completionist": "Eureka Expert",
        "m_completion_rate_50": "Scub Coral Return",
        "m_completion_rate_75": "Dawn Lift Ascension",
        "m_completion_rate_90": "Trapar Alerts Resolution",
        "m_no_drop": "Ao Sequel Decree",
        "m_long_runner_complete": "Sky Critic Clear",
        "m_sequel_chain": "Lfo Battle Seal Seal",
        "m_clean_list": "Classic Mecha Relic Relic",
        "m_from_ptr": "All Night Watchlist",
        "m_reread_master": "Eureka's Past Trial Trial",
        "m_oneshot_complete": "Eureka's Past Ascension",
        "m_same_day_start_finish": "Lift Judge Crown Crown",
        "m_revival": "Sky Critic Accord",
        "m_zero_to_hundred": "Renton's Heart Banner",
        "m_five_genre_complete": "Bones Master M Five Genre",
        "m_full_collection": "Lift Judge Proof Proof",
        "m_batch_complete": "Eureka Expert Summit",
        "m_paused_to_done": "Trapar Alerts Standard Standard",
        "m_completion_spree": "Ref Board Triumph",
        "m_format_completionist": "Eureka's Past Completion",
        "m_catch_up": "Compac Drive Chronicle",
        "m_multi_reread": "Ao Sequel Banner",
        "m_dropped_recovery": "Night Lift Conquest",
        "m_ten_perfect_scores": "Endless Sky Judgment",
        "m_complete_genre_span": "Lfo Nirvash M Complete Genre",
        "m_monthly_completions": "Sky Art Return",
        "m_yearly_completions": "Lfo Nirvash Epilogue",
        "m_rapid_complete": "Bones Classic Finale",
        "m_author_complete": "Hidden Trapar Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Sky Reader",
        "m_mangaka_lover": "Author Fan",
        "m_rereader": "Sky Revisit",
        "m_triple_reread": "Ageha Squad Testament Testament",
        "m_annual_reread": "Renton's Heart Banner Banner",
        "m_publisher_fan": "Ref Board Mark",
        "m_artist_fan": "Lfo Battle Insignia",
        "m_adaptation_compare": "Renton Loves Eureka Insignia Insignia",
        "m_source_material_fan": "Manga Version",
        "m_waiting_weekly": "Renton Fails Streak",
        "m_classic_reader": "Winter Sky Lantern",
        "m_saga_reader": "Trapar Network Decree",
        "m_genre_loyalty": "Night Lift Loyalty",
        "m_decade_reader": "Aerial Journey Warrant",
        "m_ln_adaptation": "Aerial Journey Mark",
        "m_original_work": "Coming Age Standard",
        "m_long_commitment": "Night Lift Mark",
        "m_up_to_date": "Loves Eureka Warrant Warrant",
        "m_favorite_mangaka": "Daily Lift Treasury",
        "m_complete_portfolio": "Ref Board Triumph Triumph",
        "m_franchise_collector": "Compac Drive Archive",
        "m_serialization_follower": "Daily Lift Handshake",
        "m_genre_master": "Classic Mecha Master",
        "m_multi_series_author": "Trapar Network Insignia Insignia",
        "m_format_diversity": "Coming Age Shelf",
        "m_year_dedication": "Unknown Lfos Tenure",
        "m_ongoing_follower": "Aerial Journey Fellowship",
        "m_genre_loyalty_50": "Holland Strict Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Endless Lift Explorer",
        "m_publisher_hopper": "Ref Board Mantle",
        "m_tag_explorer": "Decade Fan Explorer",
        "m_decade_hopper": "All Night Chronicle Chronicle",
        "m_hidden_gem": "Hidden Volume",
        "m_popular_taste": "Eureka Expert Record Record",
        "m_retro_reader": "Eureka Expert Accord",
        "m_modern_reader": "Renton Grows Seal Seal",
        "m_cross_demographic": "Author Fan Crown",
        "m_underdog_fan": "Eureka Expert Accord Accord",
        "m_variety_week": "Lfo Battle Horizon Horizon",
        "m_manhwa_reader": "Moonlit Lift Proof",
        "m_manhua_reader": "Winter Sky Mantle Mantle",
        "m_classic_connoisseur": "Renton Loves Glimpse",
        "m_award_winner": "Unknown Lfos Warrant",
        "m_niche_explorer": "Renton Loves Eureka Horizon",
        "m_world_manga": "Compac Drive Chronicle Chronicle",
        "m_cult_classic": "Classic Mecha",
        "m_random_pick": "Eureka Expert Standard",
        "m_new_genre_month": "Compac Drive M New Genre",
        "m_year_completionist": "Eureka Seven Fulfillment",
        "m_unpopular_opinion": "Loves Eureka Trial",
        "m_top_rated_reader": "Renton Loves Eureka Record",
        "m_source_variety": "Winter Sky Catalogue",
        "m_low_score_brave": "Eureka Seven Score",
        "m_short_manga_explorer": "Renton Grows Compass",
        "m_long_manga_explorer": "Renton's Heart Survey",
        "m_serialization_explorer": "Dawn Lift Road",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Scub Coral Ledger",
        "m_commute_reader": "Lift Resolve Tenure Tenure",
        "m_four_am_club": "Ref Board Fellowship",
        "m_new_year_read": "Lfo Battle Pact",
        "m_all_hours": "All Night Accord Accord",
        "m_prime_time_reader": "Coming Age Banner",
        "m_workday_reader": "Sky Critic Accord Accord",
        "m_sunday_read": "Scub Coral Standard Standard",
        "m_morning_routine": "Sky Critic Discipline",
        "m_night_shift_reader": "Hidden Trapar Accord Accord",
        "m_seasonal_premier_read": "Winter Sky Seasonal",
        "m_clock_collector": "Out Archive Reserve",
        "m_late_night_horror": "Bones Master Mark Mark",
        "m_afternoon_reader": "Unknown Lfos Mantle Mantle",
        "m_golden_hour_reader": "Ageha Squad Observance",
        "m_dawn_reader": "Decade Fan Mantle",
        "m_twilight_reader": "Aerial Journey Crown",
        "m_midnight_start": "Coming Age Routine",
        "m_weekend_binge_hours": "Endless Sky Momentum",
        "m_late_night_regular": "Scub Coral Accord",
        "m_sunrise_reader": "Teenage Renton Thurston Mantle",
        "m_every_day_of_week": "Winter Sky Warrant Warrant",
        "m_monthly_hours": "Endless Lift Vigil",
        "m_bedtime_reader": "Eureka Seven Warrant Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Sky Art",
        "m_webtoon_reader": "Aerial Journey Mark Mark",
        "m_full_color": "Lfo Battle Accord",
        "m_doujin_reader": "Trapar Alerts Record Record",
        "m_anthology_reader": "Endless Sky Accord",
        "m_adaptation_reader": "Eureka Expert Banner",
        "m_longstrip_reader": "Ageha Squad Trial",
        "m_4koma_reader": "Renton Fails Ledger",
        "m_oneshot_reader": "Lfo Nirvash Mantle",
        "m_format_variety": "Ref Board Gallery",
        "m_light_novel_reader": "All Night Insignia",
        "m_novel_reader": "Eureka Seven Crown",
        "m_visual_storyteller": "Unknown Lfos Testament",
        "m_colored_classic": "Sky Revisit Survey",
        "m_webcomic_fan": "Renton Loves Insignia",
        "m_manga_to_anime": "Anime Adapted",
        "m_seinen_reader": "Night Lift Pinnacle",
        "m_josei_reader": "Teenage Renton Thurston Pinnacle",
        "m_award_winning_art": "Trapar World Relic",
        "m_debut_work": "Trapar World Dominion",
        "m_vertical_scroll": "Trapar Network Decree Decree",
        "m_traditional_format": "Renton Loves Eureka Hoard",
        "m_cross_media": "Renton Grows Accord",
        "m_spinoff_reader": "Compac Drive Accord",
        "m_remake_reader": "Eureka's Past Pinnacle",
        "m_collaboration_reader": "Renton Loves Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Endless Lift",
        "m_weekly_warrior": "Dawn Lift Season",
        "m_monthly_reader": "Out Zine Discipline",
        "m_comeback": "Renton's Heart Standard Standard",
        "m_weekend_streak": "Teenage Renton Thurston Fever",
        "m_no_zero_days": "Moonlit Lift Proof Proof",
        "m_iron_will": "Lift Resolve",
        "m_habit_formed": "Author Fan Crown Crown",
        "m_consistent_pace": "Lift Judge Scrutiny Scrutiny",
        "m_year_long": "Year Reading",
        "m_double_streak": "Lfo Nirvash Resolve",
        "m_streak_recovery": "Classic Mecha Resolve",
        "m_daily_minimum": "Out Archive Focus",
        "m_winter_streak": "Ageha Squad Observance Observance",
        "m_summer_streak": "Trapar World Observance",
        "m_morning_streak": "Endless Lift Clock",
        "m_night_streak": "Renton Loves Eureka Discipline",
        "m_unbreakable": "Teenage Renton Thurston Warrant",
        "m_eternal_flame": "Lfo Registry Record",
        "m_chapter_a_day": "Scub Coral Ledger Ledger",
        "m_genre_streak": "Decade Fan Streak",
        "m_completion_streak": "Eureka Expert Return",
        "m_rating_streak": "Decade Fan Appraisal",
        "m_multi_ch_streak": "Dawn Lift Tenure",
        "m_author_streak": "Out Archive Calendar",
        "m_perfect_week_manga": "Compac Drive Accord Accord",
        "m_diverse_streak": "Ao Sequel Streak",

        // ── MANGA SCORING ──
        "m_critic": "Sky Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_harsh_critic": "All Night Scale",
        "m_fair_judge": "Ray Out Eye Eye",
        "m_generous_spirit": "Endless Sky Decree",
        "m_score_all": "Aerial Journey Reckoning",
        "m_wide_range": "Out Zine Ledger Ledger",
        "m_controversial": "Sky Art Standard Standard",
        "m_consistent_scorer": "Trapar Alerts Grade",
        "m_score_sniper": "Loves Eureka Reckoning",
        "m_evolving_taste": "Lfo Nirvash Trial Trial",
        "m_bell_curve": "Out Zine Accord",
        "m_picky_reader": "Ao Sequel Ledger",
        "m_100_rated": "Out Zine Standard",
        "m_500_rated": "Hidden Trapar Aegis",
        "m_mediocre_majority": "Lfo Nirvash Canon",
        "m_rating_spree": "Endless Lift Verdict",
        "m_score_variance": "Eureka Seven Measure",
        "m_binge_rater": "Out Archive Passage",
        "m_reread_rerate": "Sky Revisit Banner Banner",
        "m_masterpiece_hunter": "Sky Art Banner",
        "m_contrarian": "Eureka Expert Aegis",
        "m_optimist": "Renton Grows Accord Accord",
        "m_score_distributor": "Dawn Lift Balance",
        "m_genre_critic": "Out Archive Critic",
        "m_mean_above_8": "Eureka Seven Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Unknown Lfos Season",
        "m_valentines_read": "Decade Fan Observance",
        "m_pi_day": "Lfo Nirvash Testament Testament",
        "m_april_fools": "Loves Eureka Devotion",
        "m_international_manga_day": "All Night Aegis",
        "m_free_comic_day": "Endless Sky Chronicle",
        "m_summer_solstice": "Bones Classic Focus Focus",
        "m_tanabata": "Lift Judge Tanabata",
        "m_friday_13th": "Eureka's Past Dominion Dominion",
        "m_halloween_read": "Bones Master Halloween",
        "m_thanksgiving_binge": "Compac Drive Charge",
        "m_christmas_read": "Sky Critic Pact",
        "m_new_years_eve": "Bones Classic Pilgrimage",
        "m_birthday_read": "Night Lift Focus",
        "m_holiday_marathon": "Daily Lift Rally",
        "m_independence_day": "Eureka Expert Aegis Aegis",
        "m_culture_day": "Hidden Trapar Seal Seal",
        "m_spring_equinox": "Bones Master Dominion",
        "m_earth_day": "Night Lift Trial",
        "m_labor_day": "Sky Critic Seal",
        "m_winter_solstice": "Author Fan Focus Focus",
        "m_manga_birthday": "Lift Judge Ritual",
        "m_every_holiday_reader": "Classic Mecha Watch",
        "m_consecutive_holidays": "Eureka's Past Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Lifting Off Aegis",
        "m_fibonacci": "Lift Resolve Dominion",
        "m_palindrome_day": "Lfo Nirvash Relic",
        "m_binary_day": "Author Fan Proof",
        "m_full_moon_read": "Teenage Renton Thurston Crown",
        "m_leap_year_read": "Ao Sequel Practice",
        "m_triple_seven": "Ray Out Trial Trial",
        "m_thousand_complete": "Ray Out Ascension",
        "m_nice": "Trapar Network Seal Seal",
        "m_power_level_chapters": "Renton's Heart Aegis",
        "m_answer_42": "Teenage Renton Thurston Trial",
        "m_square_number": "Lfo Registry Standard",
        "m_prime_count": "Ray Out Pinnacle",
        "m_matching_date": "Classic Mecha Mantle",
        "m_century_chapter": "Lifting Off Decree",
        "m_pi_chapters": "Night Lift Proof Proof",
        "m_synchronicity": "Decade Fan Emblem",
        "m_world_record": "Moonlit Lift Warrant",
        "m_genre_clash": "Coming Age Clash",
        "m_time_traveler": "Trapar Alerts Decree",
        "m_double_digits": "Winter Sky Dominion",
        "m_one_two_three": "Renton Loves Banner Banner",
        "m_lucky_seven": "Renton Loves Eureka Record Record",
        "m_exact_hundred_ch": "Lift Resolve Legend",
        "m_year_match_count": "Renton Fails Routine",
        "m_chapter_match_date": "Author Fan Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Winter Sky Index",
        "m_manhwa_format": "Bones Master Gallery",
        "m_manhua_format": "Ageha Squad Storehouse",
        "m_ln_format": "Ray Out Index",
        "m_oneshot_format": "Lfo Nirvash Index",
        "m_doujin_format": "Endless Lift Cabinet",
        "m_novel_format": "Loves Eureka Reserve Reserve",
        "m_format_master_manga": "Endless Lift Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Trapar Alerts Link",
        "m_meta_collector": "Hidden Trapar Reliquary",
        "m_meta_category_starter": "Ref Board Standard",
        "m_meta_tier_climber": "Renton Grows Token",
        "m_meta_tier_max": "Sky Complete",
        "m_meta_xp_earner": "Winter Sky Anchor",
        "m_meta_difficulty_easy": "Ray Out Panel",
        "m_meta_difficulty_hard": "Unknown Lfos Node",
        "m_meta_unlock_spree": "Winter Sky Marker",
        "m_meta_completionist": "Full Library",
        "m_meta_diverse": "Lfo Nirvash Anchor",
        "m_meta_dominator": "Trapar Network Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#000508",
        primary: "#0591c8",
        secondary: "#0373a5",
        accent: "#e0c830",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/eureka-seven.jpg",
    particleColor: "#40c8f8",
    backgroundDim: 0.32,
    backgroundBlur: 18,
    particleTypes: {
        trapar_waves: { label: "Trapar Waves", maxCount: 20, defaultEnabled: true, defaultIntensity: 65 },
        sparkles: { label: "Lift Sparkles", maxCount: 15, defaultEnabled: true, defaultIntensity: 55 },
    },
    milestoneNames: {
  1: "Threadbare Renton Meets Spark",
  8: "Nirvash's Tarnished Omen",
  14: "Fractured Gekkostate Escape",
  21: "Lifting Introduction Path",
  28: "Lowborn Begins Myth",
  35: "Renton Joins Pulse",
  41: "Eureka's Phase Crest",
  48: "Humble Nirvash Mark",
  55: "Ragged Scub Coral Vow",
  61: "Military's Faint Echo",
  68: "Lesser Lifting Battles",
  75: "Gekkostate Forms Form",
  81: "Doubtful Emotional Soul",
  88: "Renton Sigil",
  95: "War's Legacy Clash",
  102: "Really Cool Adroc Echo",
  108: "Awakened Human Coral Clash",
  115: "KLF's Resolute Seal",
  122: "Rising Nirvash Sync",
  128: "Compassion Awakening Myth",
  135: "Dauntless Legacy Pulse",
  142: "Enemy Pilot Crest",
  149: "Renton's Legacy Mark",
  155: "Fresh Gekkostate Clash",
  162: "Valiant Military Corruption Echo",
  169: "Scub's Prime Crown",
  175: "Polished Eureka Crisis",
  182: "Love Development Bloom",
  189: "Stormlit Further Sigil",
  195: "Lifting Rising Flame",
  202: "Battlefield's Legacy Clash",
  209: "Tempered Human Omen",
  216: "Trusted Eureka Collapse Soul",
  222: "Renton's Steadfast Force",
  229: "Ironclad War Moral",
  236: "Trapar Wave Pulse",
  242: "Core Surge Form",
  249: "Military Offensive Mark",
  256: "Gekkostate's Legacy Vow",
  262: "Formidable Eureka Form",
  269: "Lucid Renton Acceptance Crown",
  276: "Scub's Ranked Zenith",
  283: "Fabled Humanity Threat",
  289: "Nirvash Soul",
  296: "Seasoned Collision Clash",
  303: "Anemone Parallel Spark",
  309: "Enemy's Legacy Omen",
  316: "Valorous Eureka Force",
  323: "Stalwart Renton Leadership Path",
  330: "War's Commanding Clash",
  336: "Refined Scub Coral",
  343: "KLF Swarm Clash",
  350: "Blazing Collapse Mark",
  356: "Eureka Loss Vow",
  363: "Renton's Emotional Soul",
  370: "Peerless Military Crown",
  376: "Ardent Gekkostate Unity Zenith",
  383: "Turning's Focused Bloom",
  390: "Vigilant Scub Coral",
  397: "Eureka Evolution Form",
  403: "Elite Sync Spark",
  410: "Human Coral Clash",
  417: "Anemone's Legacy Seal",
  423: "Sovereign Battle Clash",
  430: "Regal Trapar Storm Myth",
  437: "Eureka's Crowned Form",
  444: "Mythborn Renton",
  450: "World Breakdown Mark",
  457: "Radiant Judgment Vow",
  464: "Nirvash Ultimate Echo",
  470: "Eureka's Identity Soul",
  477: "Climactic Humanity Zenith",
  484: "Epic Love Becomes Bloom",
  490: "Confrontation's Unreal Sigil",
  497: "Peak KLF Collapse",
  504: "Military Defeat Spark",
  511: "Exalted Communication Omen",
  517: "Planetary Shift Seal",
  524: "Eureka's Unity Path",
  531: "Celestial World Form",
  537: "Phantom Conflict Resolution Clash",
  544: "Anemone's Crimson Crest",
  551: "Silver Nirvash Calm",
  557: "Aftermath Reconstruction Vow",
  564: "Feral Balance Echo",
  571: "Gekkostate Disbanding Crown",
  578: "New's Formation Form",
  584: "Dread Peaceful Bloom",
  591: "Luminous Renton Growth Sigil",
  598: "Eureka's Thunderous Force",
  604: "Ultraviolet War",
  611: "Trapar Harmony Omen",
  618: "Secret Emerges Seal",
  625: "Scub Coral Path",
  631: "Human's Legacy Myth",
  638: "Worldclass Healing Soul",
  645: "Lawless Legacy Echo",
  651: "KLF's Chosen Form",
  658: "Fearless World",
  665: "Love Echo",
  671: "Cinematic Dawn Thread",
  678: "Eureka Myth Form",
  685: "Renton's Status Bloom",
  692: "Canonized Anemone Sigil",
  698: "Ascendant Nirvash Eternal Flame",
  705: "Quiet's Transfigured Spark",
  712: "Immortal Dormant",
  718: "Balance Seal",
  725: "Astral Seven Path",
  732: "Scub Coral Myth",
  739: "Renton's Story Pulse",
  745: "Prismatic Gekkostate Echo",
  752: "Abyssal Silent Planet Mark",
  759: "Dormant's Unbound Vow",
  765: "Eternal Legend Eureka",
  772: "Lifting Myth Crown",
  779: "Transcendent Union Zenith",
  785: "Nirvash Spirit Soul",
  792: "Humanity's Legacy Sigil",
  799: "Ultimate Planet Flame",
  806: "Mythic Love Nature Spark",
  812: "World's Godlike Force",
  819: "Canonical Nirvash Sync",
  826: "Renton Growth Path",
  832: "Heavenly Form Form",
  839: "Anemone Peace Pulse",
  846: "Closure's Emotional Soul",
  852: "Timeless Peace Mark",
  859: "Empyrean Acceptance Evolution Form",
  866: "Planet's Primordial Clash",
  873: "Omniscient Symbiosis",
  879: "Eureka Seven Zenith",
  886: "Apocalyptic Species Bloom",
  893: "Resolution Soul",
  899: "Harmony's Truth Secret",
  906: "Final Origin Secret",
  913: "Crowned Conflict Clash",
  920: "Planetary's Mythic Seal",
  926: "Absolute Legend Eureka",
  933: "Emotional Soul",
  940: "Cosmic Legacy Clash",
  946: "World Crest",
  953: "Symbiotic's Perfect Mark",
  960: "Definitive Ultimate Vow",
  966: "Ultimate Thought He Brush",
  973: "Thought's Infinite Brush",
  980: "Sovereign Thought Was",
  987: "Thought He Brush",
  993: "Legendary Escaping Brush",
  1000: "Ultimate Ultimate Planet"
}
}
