import { AnimeThemeConfig } from "./types"
import { GiFist, GiDeathSkull, GiFlame, GiDesert, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiSpikyExplosion } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const fistOfTheNorthStarTheme: AnimeThemeConfig = {
    id: "fist-of-the-north-star",
    displayName: "Fist of the North Star",
    description: "In a nuclear wasteland, Kenshiro wanders seeking Yuria — his fists strike the 708 pressure points of Hokuto Shinken, making enemies explode from the inside. You are already dead.",
    fontFamily: "'Anton', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Anton&display=swap",
    cssVars: {
        "--color-brand-200": "255 140 120",
        "--color-brand-300": "248 90 70",
        "--color-brand-400": "235 48 30",
        "--color-brand-500": "212 18 8",
        "--color-brand-600": "175 10 4",
        "--color-brand-700": "136 6 2",
        "--color-brand-800": "96 3 1",
        "--color-brand-900": "58 1 0",
        "--color-brand-950": "33 0 0",
        "--brand": "212 18 8",
        "--background": "#080300",
        "--paper": "#140600",
        "--color-gray-950": "8 3 0",
        "--color-gray-900": "18 8 2",
        "--color-gray-800": "34 16 6",
        "--color-gray-700": "56 28 12",
        "--color-gray-600": "84 44 20",
        "--color-gray-500": "122 70 36",
        "--color-gray-400": "164 108 72",
        "--color-gray-300": "198 148 110",
        "--color-gray-200": "220 182 150",
        "--color-gray-100": "236 212 190",
        "--color-gray-50": "248 238 228",
    },
    sidebarOverrides: {
        "home": { icon: GiDesert, label: "Nuclear Wasteland" },
        "schedule": { icon: GiAlarmClock, label: "Warrior's Schedule" },
        "manga": { icon: LuBookOpen, label: "Secret Scrolls" },
        "lists": { icon: GiDeathSkull, label: "Enemies Roster" },
        "discover": { icon: GiBullseye, label: "Territory Recon" },
        "torrent-list": { icon: GiFist, label: "Combat Cache" },
        "debrid": { icon: GiFlame, label: "Wasteland Fuel" },
        "unmatched": { icon: GiSpikyExplosion, label: "Unnamed Foes" },
        "enmasse": { icon: GiResize, label: "Army Deploy" },
        "scan-summaries": { icon: TbReportSearch, label: "Battle Intel" },
        "auto-downloader": { icon: LuRss, label: "Wasteland Signals" },
        "community": { icon: GiFist, label: "Fist School" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Enemy Alerts" },
        "achievements": { icon: GiTrophy, label: "Warrior Seals" },
        "milestones": { icon: LuFlag, label: "Fist Goals" },
        "theme-manager": { icon: GiPalette, label: "Scar Design" },
        "extensions": { icon: BiExtension, label: "Technique Unlocks" },
        "sync": { icon: IoCloudOfflineOutline, label: "Wasteland Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Pressure Points" },
    },
    achievementNames: {
        "a_first_episode": "First Strike",
        "a_first_complete": "Already Dead",
        "a_hundred_club": "Hundred Slain",
        "a_time_lord": "Wasteland Walker",
        "a_anime_collector": "Technique Mastered",
        "a_library_legend": "Hokuto Archives",
        "a_binge_king": "Non-Stop Carnage",
        "a_no_sleep": "All-Night Battle",
        "a_marathon_runner": "Endless Walk",
        "a_speed_run": "Teleport Strike",
        "a_completionist": "Wasteland Saved",
        "a_mega_completionist": "Hokuto Master",
        "a_loyal_fan": "Kenshiro's Ally",
        "a_rewatcher": "Return to Wasteland",
        "a_decade_watcher": "Decade Fighter",
        "a_genre_action": "Fist Action",
        "a_genre_adventure": "Wasteland Trek",
        "a_genre_comedy": "Bat Gang",
        "a_genre_drama": "Kenshiro's Grief",
        "a_genre_fantasy": "Martial Fantasy",
        "a_genre_horror": "You Are Dead",
        "a_genre_romance": "Yuria's Love",
        "a_genre_scifi": "Post-Nuke World",
        "a_genre_supernatural": "Death Touch",
        "a_genre_psychological": "Raoh's Will",
        "a_genre_mecha": "None Survived",
        "a_critic": "Fist Judge",
        "a_perfect_ten": "Perfect Kill",
        "a_harsh_critic": "Merciless Judge",
        "a_daily_streak": "Daily Training",
        "a_mega_streak": "Endless Journey",
        "a_year_long": "Year Walking",
        "a_iron_will": "Unbreakable Will",
        "a_hidden_gem": "Hidden Technique",
        "a_cult_classic": "Fist Classic",
        "a_classic_connoisseur": "84 Classic Fan",
        "a_new_years_resolution": "New Year Strike",
        "a_christmas_special": "Holiday Battle",
        "a_meta_tier_max": "Fist of the Stars",
        "a_meta_completionist": "Complete Mastery",
        "a_sequel_chain": "Sequel Strike",
        "a_zero_to_hero": "Survivor to Legend",
        "a_night_owl": "Night Walker",
        "a_early_bird": "Dawn Strike",
        "m_first_chapter": "First Strike",
        "m_first_complete": "Volume Survived",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Battle Marathon",
        "m_completionist": "Wasteland Complete",
        "m_mega_completionist": "Hokuto Expert",
        "m_loyal_reader": "Loyal Reader",
        "m_rereader": "Reread Battle",
        "m_genre_action": "Violent Action",
        "m_genre_adventure": "Desert Walk",
        "m_genre_romance": "Love Pursuit",
        "m_genre_fantasy": "Martial Arts",
        "m_genre_horror": "Graphic Horror",
        "m_genre_drama": "Tragedy Drama",
        "m_genre_scifi": "Post-Nuke",
        "m_genre_supernatural": "Death Touch",
        "m_genre_psychological": "Warrior Mind",
        "m_critic": "Death Critic",
        "m_perfect_ten": "Perfect Issue",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Unbroken Fist",
        "m_year_long": "Year Reading",
        "m_iron_will": "Iron Dedication",
        "m_hidden_gem": "Hidden Chapter",
        "m_cult_classic": "Classic Violence",
        "m_mangaka_lover": "Buronson Fan",
        "m_source_material_fan": "Original Reader",
        "m_meta_tier_max": "Complete Mastery",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Hara Art Fan",
        "m_manga_to_anime": "Source Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#080300",
        primary: "#d41208",
        secondary: "#880604",
        accent: "#c88040",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/fist-of-the-north-star.jpg",
    particleColor: "#d41208",
    backgroundDim: 0.4,
    backgroundBlur: 22,
    particleTypes: {
        explosions: { label: "Explosions", maxCount: 8, defaultEnabled: true, defaultIntensity: 60 },
        dust: { label: "Wasteland Dust", maxCount: 20, defaultEnabled: true, defaultIntensity: 55 },
    },
    milestoneNames: {
    "7": "Novice Rank 1",
    "13": "Novice Level 2",
    "20": "Novice Tier 3",
    "27": "Novice Class 4",
    "33": "Novice Grade 5",
    "40": "Novice Position 6",
    "47": "Novice Status 7",
    "53": "Novice Role 8",
    "60": "Novice Title 9",
    "67": "Novice Authority 10",
    "73": "Beginner Rank 11",
    "80": "Beginner Level 12",
    "87": "Beginner Tier 13",
    "93": "Beginner Class 14",
    "100": "Beginner Grade 15",
    "107": "Beginner Position 16",
    "113": "Beginner Status 17",
    "120": "Beginner Role 18",
    "127": "Beginner Title 19",
    "133": "Student Authority 20",
    "140": "Student Rank 21",
    "147": "Student Level 22",
    "153": "Student Tier 23",
    "160": "Student Class 24",
    "167": "Student Grade 25",
    "173": "Student Position 26",
    "180": "Student Status 27",
    "187": "Student Role 28",
    "193": "Student Title 29",
    "200": "Learner Authority 30",
    "207": "Learner Rank 31",
    "213": "Learner Level 32",
    "220": "Learner Tier 33",
    "227": "Learner Class 34",
    "233": "Learner Grade 35",
    "240": "Learner Position 36",
    "247": "Learner Status 37",
    "253": "Learner Role 38",
    "260": "Adept Title 39",
    "267": "Adept Authority 40",
    "273": "Adept Rank 41",
    "280": "Adept Level 42",
    "287": "Adept Tier 43",
    "293": "Adept Class 44",
    "300": "Adept Grade 45",
    "307": "Adept Position 46",
    "313": "Adept Status 47",
    "320": "Expert Role 48",
    "327": "Expert Title 49",
    "333": "Expert Authority 50",
    "340": "Expert Rank 51",
    "347": "Expert Level 52",
    "353": "Expert Tier 53",
    "360": "Expert Class 54",
    "367": "Expert Grade 55",
    "373": "Expert Position 56",
    "380": "Expert Status 57",
    "387": "Master Role 58",
    "393": "Master Title 59",
    "400": "Master Authority 60",
    "407": "Master Rank 61",
    "413": "Master Level 62",
    "420": "Master Tier 63",
    "427": "Master Class 64",
    "433": "Master Grade 65",
    "440": "Master Position 66",
    "447": "Grandmaster Status 67",
    "453": "Grandmaster Role 68",
    "460": "Grandmaster Title 69",
    "467": "Grandmaster Authority 70",
    "473": "Grandmaster Rank 71",
    "480": "Grandmaster Level 72",
    "487": "Grandmaster Tier 73",
    "493": "Grandmaster Class 74",
    "500": "Grandmaster Grade 75",
    "507": "Sage Position 76",
    "513": "Sage Status 77",
    "520": "Sage Role 78",
    "527": "Sage Title 79",
    "533": "Sage Authority 80",
    "540": "Sage Rank 81",
    "547": "Sage Level 82",
    "553": "Sage Tier 83",
    "560": "Sage Class 84",
    "567": "Sage Grade 85",
    "573": "Legend Position 86",
    "580": "Legend Status 87",
    "587": "Legend Role 88",
    "593": "Legend Title 89",
    "600": "Legend Authority 90",
    "607": "Legend Rank 91",
    "613": "Legend Level 92",
    "620": "Legend Tier 93",
    "627": "Legend Class 94",
    "633": "Mythical Grade 95",
    "640": "Mythical Position 96",
    "647": "Mythical Status 97",
    "653": "Mythical Role 98",
    "660": "Mythical Title 99",
    "667": "Mythical Authority 100",
    "673": "Mythical Rank 101",
    "680": "Mythical Level 102",
    "687": "Mythical Tier 103",
    "693": "Mythical Class 104",
    "700": "Godly Grade 105",
    "707": "Godly Position 106",
    "713": "Godly Status 107",
    "720": "Godly Role 108",
    "727": "Godly Title 109",
    "733": "Godly Authority 110",
    "740": "Godly Rank 111",
    "747": "Godly Level 112",
    "753": "Godly Tier 113",
    "760": "Supreme Class 114",
    "767": "Supreme Grade 115",
    "773": "Supreme Position 116",
    "780": "Supreme Status 117",
    "787": "Supreme Role 118",
    "793": "Supreme Title 119",
    "800": "Supreme Authority 120",
    "807": "Supreme Rank 121",
    "813": "Supreme Level 122",
    "820": "Infinite Tier 123",
    "827": "Infinite Class 124",
    "833": "Infinite Grade 125",
    "840": "Infinite Position 126",
    "847": "Infinite Status 127",
    "853": "Infinite Role 128",
    "860": "Infinite Title 129",
    "867": "Infinite Authority 130",
    "873": "Infinite Rank 131",
    "880": "Infinite Level 132",
    "887": "Eternal Tier 133",
    "893": "Eternal Class 134",
    "900": "Eternal Grade 135",
    "907": "Eternal Position 136",
    "913": "Eternal Status 137",
    "920": "Eternal Role 138",
    "927": "Eternal Title 139",
    "933": "Eternal Authority 140",
    "940": "Eternal Rank 141",
    "947": "Transcendent Level 142",
    "953": "Transcendent Tier 143",
    "960": "Transcendent Class 144",
    "967": "Transcendent Grade 145",
    "973": "Transcendent Position 146",
    "980": "Transcendent Status 147",
    "987": "Transcendent Role 148",
    "993": "Transcendent Title 149",
    "1000": "Transcendent Authority 150"
},
}
