import { AnimeThemeConfig } from "./types"
import { GiFist, GiDeathSkull, GiFlame, GiDesert, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiSpikyExplosion } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const fistOfTheNorthStarTheme: AnimeThemeConfig = {
    id: "fist-of-the-north-star",
    displayName: "Fist of the North Star",
    description: "In a nuclear wasteland, Kenshiro wanders seeking Yuria — his fists strike the 708 pressure points of Hokuto Shinken, making enemies explode from the inside. You are already dead.",
    fontFamily: "'Anton', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Anton&display=swap",
    cssVars: {
        "--color-brand-200": "255 140 120",
        "--color-brand-300": "248 90 70",
        "--color-brand-400": "235 48 30",
        "--color-brand-500": "212 18 8",
        "--color-brand-600": "175 10 4",
        "--color-brand-700": "136 6 2",
        "--color-brand-800": "96 3 1",
        "--color-brand-900": "58 1 0",
        "--color-brand-950": "33 0 0",
        "--brand": "212 18 8",
        "--background": "#080300",
        "--paper": "#140600",
        "--color-gray-950": "8 3 0",
        "--color-gray-900": "18 8 2",
        "--color-gray-800": "34 16 6",
        "--color-gray-700": "56 28 12",
        "--color-gray-600": "84 44 20",
        "--color-gray-500": "122 70 36",
        "--color-gray-400": "164 108 72",
        "--color-gray-300": "198 148 110",
        "--color-gray-200": "220 182 150",
        "--color-gray-100": "236 212 190",
        "--color-gray-50": "248 238 228",
    },
    sidebarOverrides: {
        "home": { icon: GiDesert, label: "Nuclear Wasteland" },
        "schedule": { icon: GiAlarmClock, label: "Warrior's Schedule" },
        "manga": { icon: LuBookOpen, label: "Secret Scrolls" },
        "lists": { icon: GiDeathSkull, label: "Enemies Roster" },
        "discover": { icon: GiBullseye, label: "Territory Recon" },
        "torrent-list": { icon: GiFist, label: "Combat Cache" },
        "debrid": { icon: GiFlame, label: "Wasteland Fuel" },
        "unmatched": { icon: GiSpikyExplosion, label: "Unnamed Foes" },
        "enmasse": { icon: GiResize, label: "Army Deploy" },
        "scan-summaries": { icon: TbReportSearch, label: "Battle Intel" },
        "auto-downloader": { icon: LuRss, label: "Wasteland Signals" },
        "community": { icon: GiFist, label: "Fist School" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Enemy Alerts" },
        "achievements": { icon: GiTrophy, label: "Warrior Seals" },
        "milestones": { icon: LuFlag, label: "Fist Goals" },
        "theme-manager": { icon: GiPalette, label: "Scar Design" },
        "extensions": { icon: BiExtension, label: "Technique Unlocks" },
        "sync": { icon: IoCloudOfflineOutline, label: "Wasteland Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Pressure Points" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Strike",
        "a_episode_counter": "Sequel Strike Mark",
        "a_episode_titan": "Stop Carnage Relic",
        "a_hours_invested": "Art Fan Proof",
        "a_time_lord": "Wasteland Walker",
        "a_anime_collector": "Technique Mastered",
        "a_library_legend": "Hokuto Archives",
        "a_first_complete": "Already Dead",
        "a_hundred_club": "Hundred Slain",
        "a_first_day": "Battle Intel Seal",
        "a_first_rating": "Stop Carnage Appraisal",
        "a_ten_thousand_min": "Warrior Mind Standard",
        "a_season_veteran": "Warrior Mind Library",
        "a_year_explorer": "Yuria's Love Map",
        "a_century_watcher": "Fist Classic Ledger",
        "a_five_hundred_eps": "Unnamed Foes Dominion",
        "a_thousand_eps": "Buronson Fan Record",
        "a_watching_ten": "Hara Art Fan Acclaim",
        "a_ptw_hoarder": "Secret Scrolls Library",
        "a_dropped_honesty": "Hara Art Fan Summit",
        "a_five_thousand_eps": "Night Walker Warrant",
        "a_ten_completed": "Desert Walk Afterglow",
        "a_fifty_completed": "Warrior Seals Ascension",
        "a_five_hundred_completed": "Hara Art Fan Clear",
        "a_mean_score_tracker": "Hokuto Expert Verdict",
        "a_unique_studios": "Buronson Fan Collection",
        "a_days_spent_watching": "Hokuto Shinken Dominion",
        "a_all_status": "Reread Battle Testament",
        "a_first_favorite": "Fist Stars Cabinet",
        "a_favorites_collector": "Already Dead Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Enemy Alerts Drive",
        "a_marathon_runner": "Endless Walk",
        "a_weekend_warrior": "Stop Carnage Ordeal",
        "a_non_stop": "Enemies Roster Fever",
        "a_one_more_episode": "Perfect Kill Mantle",
        "a_speed_run": "Teleport Strike",
        "a_double_feature": "Fist Judge Crown",
        "a_triple_threat": "Love Pursuit Record",
        "a_five_a_day": "Nuke World Accord",
        "a_back_to_back": "Hokuto Master Surge",
        "a_seasonal_binge": "Stop Carnage Cascade",
        "a_cour_crusher": "Hokuto Shinken Ordeal",
        "a_half_day_watch": "Sequel Strike Crown",
        "a_full_day_watch": "Fist Action Pinnacle",
        "a_power_weekend": "Battle Intel Run",
        "a_binge_king": "Non-Stop Carnage",
        "a_no_sleep": "All-Night Battle",
        "a_entire_season": "Classic Fan Library",
        "a_seven_day_challenge": "Fist Action Mark",
        "a_hundred_day_binge": "Battle Intel Surge",
        "a_genre_binge": "Wasteland Fuel Binge",
        "a_studio_binge": "Sequel Strike Fever",
        "a_season_sweep": "Decade Fighter Codex",
        "a_forty_eight_hour": "Death Touch Overture",
        "a_ep_counter_day": "Desert Walk Aegis",
        "a_multi_series_binge": "Secret Scrolls Streak",
        "a_midnight_binge": "Perfect Kill Cascade",
        "a_new_year_binge": "Dawn Strike Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Fist Action",
        "a_genre_adventure": "Wasteland Trek",
        "a_genre_comedy": "Bat Gang",
        "a_genre_drama": "Kenshiro's Grief",
        "a_genre_fantasy": "Martial Fantasy",
        "a_genre_horror": "You Are Dead",
        "a_genre_mystery": "Unbroken Fist Mystery",
        "a_genre_romance": "Yuria's Love",
        "a_genre_scifi": "Post-Nuke World",
        "a_genre_sol": "Night Walker Slice",
        "a_genre_sports": "Death Touch Sports",
        "a_genre_supernatural": "Death Touch",
        "a_genre_thriller": "Warrior Seals Thriller",
        "a_genre_mecha": "None Survived",
        "a_genre_music": "Warrior Mind Music",
        "a_genre_psychological": "Raoh's Will",
        "a_genre_ecchi": "Enemy Alerts Ecchi",
        "a_genre_mahou_shoujo": "Love Pursuit Magic Shoujo",
        "a_tag_isekai": "Bat Gang Isekai",
        "a_tag_harem": "All Night Harem",
        "a_tag_bl": "Death Touch Bl",
        "a_tag_gl": "Perfect Kill Gl",
        "a_tag_historical": "Hara Art Historical",
        "a_tag_military": "Unnamed Foes Military",
        "a_tag_school": "Secret Scrolls School",
        "a_tag_martial_arts": "Fist Action Martial Arts",
        "a_tag_vampire": "Love Pursuit Vampire",
        "a_tag_samurai": "Buronson Fan Samurai",
        "a_tag_space": "Post Nuke Space",
        "a_tag_parody": "Fist School Parody",
        "a_tag_idol": "Death Touch Idol",
        "a_tag_post_apocalyptic": "Tragedy Drama Post Apocalyptic",
        "a_tag_cyberpunk": "Enemies Roster Cyberpunk",
        "a_tag_shounen": "Tragedy Drama Shounen",
        "a_tag_seinen": "Scar Design Seinen",
        "a_tag_shoujo": "Scar Design Shoujo",
        "a_tag_josei": "Desert Walk Josei",
        "a_tag_survival": "Already Dead Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "Wasteland Saved",
        "a_mega_completionist": "Hokuto Master",
        "a_completion_rate_50": "Love Pursuit Return",
        "a_completion_rate_75": "Warrior Seals Crown",
        "a_completion_rate_90": "Desert Walk Resolution",
        "a_no_drop": "Unbroken Fist Decree",
        "a_long_runner_complete": "Battle Intel Clear",
        "a_sequel_chain": "Sequel Strike",
        "a_clean_list": "Decade Fighter Relic",
        "a_from_ptw": "Fist School Index",
        "a_rewatch_master": "Hokuto Expert Return",
        "a_short_complete": "Death Critic Endgame",
        "a_same_day_start_finish": "Perfect Issue Pinnacle",
        "a_revival": "Fist Classic Insignia",
        "a_zero_to_hero": "Survivor to Legend",
        "a_five_genre_complete": "Death Critic A Five Genre",
        "a_full_franchise": "Secret Scrolls Chronicle",
        "a_batch_complete": "Stop Carnage Crown",
        "a_paused_to_done": "Desert Walk Aegis Aegis",
        "a_completion_spree": "Endless Walk Triumph",
        "a_multi_rewatch": "Endless Walk Triumph Triumph",
        "a_dropped_recovery": "Sequel Strike Conquest",
        "a_ten_perfect_scores": "Battle Intel Acclaim",
        "a_seasonal_clear": "Hokuto Shinken Codex",
        "a_complete_genre_span": "North Star A Complete Genre",
        "a_monthly_completions": "Hokuto Expert Afterglow",
        "a_yearly_completions": "Reread Battle Epilogue",
        "a_rapid_complete": "Fist Action Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Kenshiro's Ally",
        "a_studio_devotee": "Unbroken Fist Treasury",
        "a_rewatcher": "Return to Wasteland",
        "a_triple_rewatch": "Wasteland Fuel Coda",
        "a_annual_tradition": "Fist Action Proof",
        "a_director_fan": "Decade Fighter Trial",
        "a_voice_actor_fan": "Sequel Strike Crown Crown",
        "a_ost_lover": "Secret Scrolls Seal",
        "a_source_reader": "Yuria's Love Cabinet",
        "a_waiting_weekly": "Unbroken Fist Clock",
        "a_childhood_revisit": "Night Battle Seal",
        "a_saga_tracker": "Post Nuke Standard",
        "a_genre_loyalty": "Night Walker Loyalty",
        "a_decade_watcher": "Decade Fighter",
        "a_adaptation_hunter": "Fist School Trial",
        "a_original_anime_fan": "Raoh's Will Testament",
        "a_long_commitment": "Fist Action Mark Mark",
        "a_perfect_attendance": "Hara Art Fan Standard",
        "a_favorite_studio_5": "Tragedy Drama Library",
        "a_complete_catalog": "Already Dead Seal",
        "a_franchise_collector": "Tragedy Drama Archive",
        "a_airing_follower": "Night Battle Signal",
        "a_genre_master": "Decade Fighter Master",
        "a_staff_follower": "Tragedy Drama Oath",
        "a_multi_season_fan": "Hara Art Hoard",
        "a_format_diversity": "Love Pursuit Cache",
        "a_year_dedication": "Stop Carnage Tenure",
        "a_season_dedication": "Unnamed Foes Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Wasteland Fuel Explorer",
        "a_studio_hopper": "Hokuto Expert Collection",
        "a_tag_explorer": "Stop Carnage Explorer",
        "a_decade_hopper": "Secret Scrolls Chronicle Chronicle",
        "a_hidden_gem": "Hidden Technique",
        "a_popular_taste": "Death Touch Decree",
        "a_retro_appreciator": "Already Dead Aegis",
        "a_modern_viewer": "Perfect Issue Pinnacle Pinnacle",
        "a_cross_demographic": "Enemy Alerts Pinnacle",
        "a_underdog_fan": "North Star Trial",
        "a_variety_week": "Tragedy Drama Horizon",
        "a_foreign_cinema": "Perfect Kill Expedition",
        "a_classic_connoisseur": "84 Classic Fan",
        "a_every_season": "Night Battle Archive",
        "a_award_winner": "Warrior Mind Insignia",
        "a_niche_explorer": "Scar Design Horizon",
        "a_global_anime": "Death Critic Crown",
        "a_cult_classic": "Fist Classic",
        "a_random_pick": "Death Touch Decree Decree",
        "a_new_genre_month": "Hara Art Fan A New",
        "a_seasonal_completionist": "Fist Classic Summit",
        "a_unpopular_opinion": "Fist Stars Standard",
        "a_top_rated_viewer": "Nuke World Seal",
        "a_source_variety": "Hokuto Shinken Storehouse",
        "a_low_score_brave": "Enemies Roster Measure",
        "a_upcoming_watcher": "Nuke World Seal Seal",
        "a_short_series_explorer": "Perfect Kill Expedition Expedition",
        "a_long_series_explorer": "Fist Judge Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Night Walker",
        "a_early_bird": "Dawn Strike",
        "a_lunch_break": "Non Stop Trial",
        "a_golden_hour": "Martial Arts Tenure",
        "a_four_am_club": "Endless Walk Gathering",
        "a_witching_hour": "Warrior Seals Tenure",
        "a_new_year_watch": "Stop Carnage Season",
        "a_midnight_premiere": "Dawn Strike Devotion",
        "a_all_hours": "Fist Classic Seal",
        "a_dawn_warrior": "Death Touch Aegis",
        "a_afternoon_delight": "Art Fan Proof Proof",
        "a_prime_time": "Warrior Mind Insignia Insignia",
        "a_workday_watcher": "Enemy Alerts Pinnacle Pinnacle",
        "a_sunday_marathon": "Battle Intel Momentum",
        "a_rainy_day": "Warrior Seals Relic",
        "a_morning_routine": "Hara Art Promise",
        "a_night_shift": "Love Pursuit Aegis",
        "a_twilight_zone": "Classic Fan Ledger",
        "a_seasonal_premier": "Unbroken Fist Cabinet",
        "a_clock_collector": "Endless Walk Repository",
        "a_weekend_binge_hours": "Scar Design Streak",
        "a_late_night_regular": "Reread Battle Dominion",
        "a_sunrise_watcher": "Decade Fighter Relic Relic",
        "a_holiday_watcher": "Nuke World Pact",
        "a_every_day_of_week": "Hokuto Master Ledger",
        "a_monthly_hours": "Death Touch Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Desert Walk Record",
        "a_party_host": "Love Pursuit Record Record",
        "a_social_butterfly": "Yuria's Love Company",
        "a_group_binge": "Buronson Fan Sprint",
        "a_party_regular": "Classic Fan Chronicle",
        "a_sync_viewer": "Endless Walk Standard",
        "a_commentator": "Already Dead Record",
        "a_party_marathon": "Wasteland Fuel Vigil",
        "a_full_house": "Unnamed Foes Trial",
        "a_community_pillar": "Reread Battle Alliance",
        "a_watch_party_streak": "Already Dead Vigil",
        "a_diverse_party": "Hara Art Seal",
        "a_late_night_party": "Reread Battle Testament Testament",
        "a_party_veteran": "Unnamed Foes Testament",
        "a_genre_party": "Perfect Kill Party",
        "a_weekly_party": "Endless Walk Calendar",
        "a_silent_viewer": "Raoh's Will Mantle",
        "a_recommendation_giver": "Scar Design Network",
        "a_party_completionist": "Post Nuke Coda",
        "a_social_scorer": "Decade Fighter Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Fist Judge Proof",
        "a_fibonacci": "Stop Carnage Dominion",
        "a_palindrome_day": "Stop Carnage Relic Relic",
        "a_binary_day": "Night Walker Mark",
        "a_full_moon": "Night Battle Insignia",
        "a_leap_year": "Death Critic Devotion",
        "a_time_traveler": "Unbroken Fist Record",
        "a_genre_clash": "Wasteland Fuel Clash",
        "a_triple_seven": "Stop Carnage Testament",
        "a_thousand_complete": "Raoh's Will Epilogue",
        "a_pi_episodes": "Enemy Alerts Crown",
        "a_synchronicity": "North Star Anchor",
        "a_world_record": "Sequel Strike Warrant",
        "a_nice": "Warrior Mind Chronicle",
        "a_power_level": "Raoh's Will Testament Testament",
        "a_answer_42": "Death Touch Standard",
        "a_square_number": "Wasteland Fuel Decree",
        "a_prime_count": "Warrior Mind Seal",
        "a_matching_date": "North Star Mantle",
        "a_century_episode": "Enemy Alerts Mark",
        "a_double_digits": "Warrior Seals Testament",
        "a_one_two_three": "Death Critic Crown Crown",
        "a_lucky_seven": "Fist Action Crown",
        "a_all_tens": "Enemies Roster Criterion",
        "a_exact_hundred_eps": "Post Nuke Legend",
        "a_year_match_count": "Unbroken Fist Yearlong",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Scar Design Ledger",
        "a_movie_buff": "Sequel Strike Mark Mark",
        "a_ova_hunter": "Post Nuke Standard Standard",
        "a_ona_explorer": "North Star Secret",
        "a_special_watcher": "Warrior Seals Relic Relic",
        "a_short_king": "All Night Crown",
        "a_variety_pack": "Sequel Strike Inquiry",
        "a_film_festival": "Nuke World Chronicle",
        "a_music_video": "Hara Art Chronicle",
        "a_tv_short": "Wasteland Fuel Record",
        "a_movie_marathon": "Wasteland Fuel Gauntlet",
        "a_double_length": "Fist Judge Crown Crown",
        "a_anthology": "Love Pursuit Aegis Aegis",
        "a_mini_series": "Fist Stars Decree",
        "a_theatrical": "Tragedy Drama Accord",
        "a_format_master": "Endless Walk Vault",
        "a_long_movie": "Fist Classic Insignia Insignia",
        "a_back_catalog": "Already Dead Standard",
        "a_cm_watcher": "Bat Gang Aegis",
        "a_pv_collector": "North Star Storehouse",
        "a_format_balance": "Endless Walk Vault Vault",
        "a_episodic_master": "Bat Gang Standard",
        "a_sequel_movie": "Death Critic Pinnacle",
        "a_recap_watcher": "Non Stop Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Training",
        "a_mega_streak": "Endless Journey",
        "a_weekly_warrior": "Unnamed Foes Season",
        "a_monthly_watcher": "Dawn Strike Calendar",
        "a_comeback": "Yuria's Love Decree",
        "a_weekend_streak": "Enemies Roster Passage",
        "a_no_zero_days": "Night Walker Warrant Warrant",
        "a_iron_will": "Unbreakable Will",
        "a_habit_formed": "Hokuto Master Banner",
        "a_consistent_pace": "Fist Judge Measure",
        "a_year_long": "Year Walking",
        "a_double_streak": "Decade Fighter Watch",
        "a_streak_recovery": "Raoh's Will Season",
        "a_daily_minimum": "Dawn Strike Focus",
        "a_winter_streak": "Perfect Kill Watch",
        "a_summer_streak": "Warrior Seals Resolve",
        "a_morning_streak": "Already Dead Clock",
        "a_night_streak": "Hokuto Master Constancy",
        "a_unbreakable": "All Night Proof",
        "a_eternal_flame": "Hokuto Expert Standard",
        "a_completion_streak": "Post Nuke Return",
        "a_rating_streak": "Stop Carnage Balance",
        "a_multi_ep_streak": "Sequel Strike Ritual",
        "a_genre_streak": "Stop Carnage Streak",
        "a_studio_streak": "Yuria's Love Cabinet Cabinet",
        "a_perfect_week": "North Star Relic",

        // ── ANIME SCORING ──
        "a_critic": "Fist Judge",
        "a_perfect_ten": "Perfect Kill",
        "a_harsh_critic": "Merciless Judge",
        "a_fair_judge": "Reread Battle Balance",
        "a_generous_spirit": "Dawn Strike Pinnacle",
        "a_score_all": "Art Fan Criterion",
        "a_wide_range": "Warrior Mind Ledger",
        "a_controversial": "Already Dead Decree",
        "a_consistent_scorer": "Unbroken Fist Verdict",
        "a_score_sniper": "Death Critic Score",
        "a_evolving_taste": "Decade Fighter Testament",
        "a_bell_curve": "Hara Art Fan Insignia",
        "a_picky_watcher": "Raoh's Will Warrant",
        "a_100_rated": "Endless Walk Warrant",
        "a_500_rated": "All Night Pinnacle",
        "a_mediocre_majority": "North Star Canon",
        "a_rating_spree": "Already Dead Review",
        "a_score_variance": "Enemies Roster Score",
        "a_masterpiece_hunter": "Already Dead Banner",
        "a_contrarian": "Wasteland Fuel Record Record",
        "a_optimist": "Hara Art Ledger",
        "a_score_distributor": "Non Stop Appraisal",
        "a_genre_critic": "Fist Judge Critic",
        "a_mean_above_8": "Fist Action Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Strike",
        "a_valentines_weeb": "Tragedy Drama Vow",
        "a_pi_day": "Reread Battle Trial",
        "a_april_fools": "Death Critic Devotion Devotion",
        "a_international_anime_day": "Fist Classic Record",
        "a_star_wars_day": "Battle Intel Chronicle",
        "a_summer_solstice": "Night Walker Calendar",
        "a_tanabata": "Perfect Issue Focus",
        "a_friday_13th": "Non Stop Relic",
        "a_halloween_spirit": "Scar Design Vow",
        "a_thanksgiving_binge": "Classic Fan Run",
        "a_christmas_special": "Holiday Battle",
        "a_new_years_eve": "Fist Action Pilgrimage",
        "a_birthday_watch": "Hara Art Fan Vow",
        "a_holiday_marathon": "Buronson Fan Overture",
        "a_independence_day": "Hokuto Expert Banner",
        "a_culture_day": "Secret Scrolls Insignia",
        "a_spring_equinox": "Buronson Fan Decree",
        "a_earth_day": "Sequel Strike Mantle",
        "a_labor_day": "Scar Design Seal",
        "a_winter_solstice": "Enemy Alerts Pilgrimage",
        "a_anime_birthday": "Sequel Strike Pilgrimage",
        "a_every_holiday": "Fist School Resolve",
        "a_consecutive_holidays": "Warrior Seals Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Yuria's Love Rank",
        "a_meta_collector": "Secret Scrolls Hoard",
        "a_meta_category_starter": "Dawn Strike Badge",
        "a_meta_tier_climber": "Secret Scrolls Glyph",
        "a_meta_tier_max": "Fist of the Stars",
        "a_meta_xp_earner": "Non Stop Emblem",
        "a_meta_difficulty_easy": "Reread Battle Mechanism",
        "a_meta_difficulty_hard": "Nuke World Writ",
        "a_meta_unlock_spree": "Unnamed Foes Panel",
        "a_meta_completionist": "Complete Mastery",
        "a_meta_diverse": "Stop Carnage Emblem",
        "a_meta_dominator": "Classic Fan Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Strike",
        "m_chapter_counter": "Endless Walk Pinnacle",
        "m_chapter_titan": "Hokuto Shinken Relic",
        "m_reading_hours": "Non Stop Relic Relic",
        "m_reading_time_lord": "Fist Classic Record Record",
        "m_manga_collector": "Unnamed Foes Ledger",
        "m_library_legend": "Secret Scrolls Reliquary",
        "m_first_complete": "Volume Survived",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "Tragedy Drama Seal",
        "m_first_rating": "Non Stop Eye",
        "m_ten_thousand_pages": "Tragedy Drama Gauge",
        "m_volume_collector": "Raoh's Will Storehouse",
        "m_year_explorer": "Death Touch Quest",
        "m_century_reader": "Perfect Kill Dominion",
        "m_five_hundred_ch": "Warrior Mind Legend",
        "m_thousand_ch": "Decade Fighter Legend",
        "m_reading_ten": "Perfect Kill Appraisal",
        "m_ptr_hoarder": "Decade Fighter Index",
        "m_dropped_honesty": "Secret Scrolls Summit",
        "m_season_reader": "Already Dead Treasury",
        "m_active_reader": "Warrior Seals Trial",
        "m_five_thousand_ch": "Wasteland Fuel Standard",
        "m_ten_completed": "Wasteland Fuel Resolution",
        "m_fifty_completed": "Decade Fighter Harvest",
        "m_five_hundred_completed": "Hokuto Master Legacy",
        "m_mean_score_tracker": "Unbroken Fist Audit",
        "m_unique_authors": "Sequel Strike Reserve",
        "m_all_status": "Warrior Seals Testament Testament",
        "m_first_favorite": "Post Nuke Cache",
        "m_favorites_collector": "Yuria's Love Shelf",
        "m_days_spent_reading": "Enemy Alerts Relic",

        // ── MANGA BINGE ──
        "m_binge_reader": "Hara Art Fan Streak",
        "m_marathon_reader": "Reread Battle Rush",
        "m_weekend_reader": "Night Battle Run",
        "m_non_stop_reading": "Post Nuke Gauntlet",
        "m_one_more_chapter": "Non Stop Testament Testament",
        "m_speed_read": "Night Walker Drive",
        "m_double_story": "Buronson Fan Banner",
        "m_triple_read": "Hokuto Expert Record",
        "m_five_a_day": "Hara Art Insignia",
        "m_chapter_chain": "Secret Scrolls Accord",
        "m_volume_binge": "Enemies Roster Drive",
        "m_power_reader": "Battle Intel Seal Seal",
        "m_half_day_read": "Yuria's Love Aegis",
        "m_full_day_read": "Bat Gang Aegis Aegis",
        "m_power_weekend": "Tragedy Drama Streak",
        "m_binge_king": "Battle Marathon",
        "m_no_sleep_read": "Perfect Kill Rush",
        "m_full_series_rush": "Reread Battle Cascade",
        "m_seven_day_challenge": "Perfect Issue Warrant",
        "m_hundred_day_read": "Stop Carnage Legend",
        "m_volume_rush": "Desert Walk Gauntlet",
        "m_series_sweep": "Fist School Trial Trial",
        "m_genre_binge": "Bat Gang Binge",
        "m_author_binge": "Night Battle Surge",
        "m_chapter_counter_day": "Classic Fan Ledger Ledger",
        "m_multi_series_binge": "Warrior Mind Charge",
        "m_midnight_binge": "Decade Fighter Tempest",
        "m_new_year_binge": "Sequel Strike Passage",
        "m_forty_eight_hour": "Unbroken Fist Rally",
        "m_oneshot_binge": "Night Walker Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Violent Action",
        "m_genre_adventure": "Desert Walk",
        "m_genre_comedy": "Yuria's Love Comedy",
        "m_genre_drama": "Tragedy Drama",
        "m_genre_fantasy": "Martial Arts",
        "m_genre_horror": "Graphic Horror",
        "m_genre_mystery": "Wasteland Fuel Mystery",
        "m_genre_romance": "Love Pursuit",
        "m_genre_scifi": "Post-Nuke",
        "m_genre_sol": "Endless Walk Slice",
        "m_genre_sports": "Desert Walk Sports",
        "m_genre_supernatural": "Death Touch",
        "m_genre_thriller": "North Star Thriller",
        "m_genre_psychological": "Warrior Mind",
        "m_genre_isekai": "Unnamed Foes Isekai",
        "m_genre_shounen": "Martial Arts Shounen",
        "m_genre_ecchi": "Fist Judge Ecchi",
        "m_genre_mahou_shoujo": "Yuria's Love Magic Shoujo",
        "m_genre_mecha": "Raoh's Will Mecha",
        "m_genre_music": "Scar Design Music",
        "m_tag_isekai_new": "Non Stop Isekai New",
        "m_tag_harem": "Art Fan Harem",
        "m_tag_bl": "Fist Stars Bl",
        "m_tag_gl": "Decade Fighter Gl",
        "m_tag_historical": "Warrior Mind Historical",
        "m_tag_military": "Martial Arts Military",
        "m_tag_school": "Tragedy Drama School",
        "m_tag_martial_arts": "Endless Walk Martial Arts",
        "m_tag_vampire": "Desert Walk Vampire",
        "m_tag_samurai": "Love Pursuit Samurai",
        "m_tag_space": "Fist Stars Space",
        "m_tag_parody": "Raoh's Will Parody",
        "m_tag_idol": "Fist Stars Idol",
        "m_tag_post_apocalyptic": "Secret Scrolls Post Apocalyptic",
        "m_tag_cyberpunk": "Art Fan Cyberpunk",
        "m_tag_shoujo": "Nuke World Shoujo",
        "m_tag_survival": "Yuria's Love Survival",
        "m_tag_cooking": "Hara Art Fan Cooking",
        "m_tag_medical": "Warrior Seals Medical",
        "m_tag_villainess": "Night Battle Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Wasteland Complete",
        "m_mega_completionist": "Hokuto Expert",
        "m_completion_rate_50": "Fist Stars Return",
        "m_completion_rate_75": "North Star Ascension",
        "m_completion_rate_90": "Hokuto Expert Resolution",
        "m_no_drop": "Post Nuke Decree",
        "m_long_runner_complete": "Classic Fan Clear",
        "m_sequel_chain": "Scar Design Seal Seal",
        "m_clean_list": "Hokuto Shinken Relic Relic",
        "m_from_ptr": "Nuke World Watchlist",
        "m_reread_master": "Reread Battle Trial Trial",
        "m_oneshot_complete": "Reread Battle Ascension",
        "m_same_day_start_finish": "Fist Action Crown Crown",
        "m_revival": "Classic Fan Accord",
        "m_zero_to_hundred": "Wasteland Fuel Banner",
        "m_five_genre_complete": "Night Walker M Five Genre",
        "m_full_collection": "Fist Action Proof Proof",
        "m_batch_complete": "Unbroken Fist Summit",
        "m_paused_to_done": "Hokuto Expert Standard Standard",
        "m_completion_spree": "All Night Triumph",
        "m_format_completionist": "Reread Battle Completion",
        "m_catch_up": "Fist Classic Chronicle",
        "m_multi_reread": "Post Nuke Banner",
        "m_dropped_recovery": "Fist Judge Conquest",
        "m_ten_perfect_scores": "Night Battle Judgment",
        "m_complete_genre_span": "Unnamed Foes M Complete Genre",
        "m_monthly_completions": "Bat Gang Return",
        "m_yearly_completions": "Unnamed Foes Epilogue",
        "m_rapid_complete": "Perfect Issue Finale",
        "m_author_complete": "Tragedy Drama Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Reader",
        "m_mangaka_lover": "Buronson Fan",
        "m_rereader": "Reread Battle",
        "m_triple_reread": "Stop Carnage Testament Testament",
        "m_annual_reread": "Wasteland Fuel Banner Banner",
        "m_publisher_fan": "All Night Mark",
        "m_artist_fan": "Scar Design Insignia",
        "m_adaptation_compare": "Hara Art Fan Insignia Insignia",
        "m_source_material_fan": "Original Reader",
        "m_waiting_weekly": "Love Pursuit Streak",
        "m_classic_reader": "Raoh's Will Lantern",
        "m_saga_reader": "Secret Scrolls Decree",
        "m_genre_loyalty": "Fist Judge Loyalty",
        "m_decade_reader": "Enemies Roster Warrant",
        "m_ln_adaptation": "Enemies Roster Mark",
        "m_original_work": "Desert Walk Standard",
        "m_long_commitment": "Fist Judge Mark",
        "m_up_to_date": "Sequel Strike Warrant Warrant",
        "m_favorite_mangaka": "Death Touch Treasury",
        "m_complete_portfolio": "All Night Triumph Triumph",
        "m_franchise_collector": "Fist Classic Archive",
        "m_serialization_follower": "Death Touch Handshake",
        "m_genre_master": "Hokuto Shinken Master",
        "m_multi_series_author": "Secret Scrolls Insignia Insignia",
        "m_format_diversity": "Desert Walk Shelf",
        "m_year_dedication": "Perfect Kill Tenure",
        "m_ongoing_follower": "Enemies Roster Fellowship",
        "m_genre_loyalty_50": "Decade Fighter Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Buronson Fan Explorer",
        "m_publisher_hopper": "All Night Mantle",
        "m_tag_explorer": "Fist School Explorer",
        "m_decade_hopper": "Nuke World Chronicle Chronicle",
        "m_hidden_gem": "Hidden Chapter",
        "m_popular_taste": "Unbroken Fist Record Record",
        "m_retro_reader": "Unbroken Fist Accord",
        "m_modern_reader": "Warrior Mind Seal Seal",
        "m_cross_demographic": "Dawn Strike Crown",
        "m_underdog_fan": "Unbroken Fist Accord Accord",
        "m_variety_week": "Scar Design Horizon Horizon",
        "m_manhwa_reader": "Death Critic Proof",
        "m_manhua_reader": "Raoh's Will Mantle Mantle",
        "m_classic_connoisseur": "Hokuto Master Glimpse",
        "m_award_winner": "Perfect Kill Warrant",
        "m_niche_explorer": "Hara Art Fan Horizon",
        "m_world_manga": "Fist Classic Chronicle Chronicle",
        "m_cult_classic": "Classic Violence",
        "m_random_pick": "Unbroken Fist Standard",
        "m_new_genre_month": "Fist Classic M New Genre",
        "m_year_completionist": "Endless Walk Fulfillment",
        "m_unpopular_opinion": "Sequel Strike Trial",
        "m_top_rated_reader": "Hara Art Fan Record",
        "m_source_variety": "Raoh's Will Catalogue",
        "m_low_score_brave": "Endless Walk Score",
        "m_short_manga_explorer": "Warrior Mind Compass",
        "m_long_manga_explorer": "Wasteland Fuel Survey",
        "m_serialization_explorer": "North Star Road",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Fist Stars Ledger",
        "m_commute_reader": "Warrior Seals Tenure Tenure",
        "m_four_am_club": "All Night Fellowship",
        "m_new_year_read": "Scar Design Pact",
        "m_all_hours": "Nuke World Accord Accord",
        "m_prime_time_reader": "Desert Walk Banner",
        "m_workday_reader": "Classic Fan Accord Accord",
        "m_sunday_read": "Fist Stars Standard Standard",
        "m_morning_routine": "Classic Fan Discipline",
        "m_night_shift_reader": "Tragedy Drama Accord Accord",
        "m_seasonal_premier_read": "Raoh's Will Seasonal",
        "m_clock_collector": "Enemy Alerts Reserve",
        "m_late_night_horror": "Night Walker Mark Mark",
        "m_afternoon_reader": "Perfect Kill Mantle Mantle",
        "m_golden_hour_reader": "Stop Carnage Observance",
        "m_dawn_reader": "Fist School Mantle",
        "m_twilight_reader": "Enemies Roster Crown",
        "m_midnight_start": "Desert Walk Routine",
        "m_weekend_binge_hours": "Night Battle Momentum",
        "m_late_night_regular": "Fist Stars Accord",
        "m_sunrise_reader": "Art Fan Mantle",
        "m_every_day_of_week": "Raoh's Will Warrant Warrant",
        "m_monthly_hours": "Buronson Fan Vigil",
        "m_bedtime_reader": "Endless Walk Warrant Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Hara Art Fan",
        "m_webtoon_reader": "Enemies Roster Mark Mark",
        "m_full_color": "Scar Design Accord",
        "m_doujin_reader": "Hokuto Expert Record Record",
        "m_anthology_reader": "Night Battle Accord",
        "m_adaptation_reader": "Unbroken Fist Banner",
        "m_longstrip_reader": "Stop Carnage Trial",
        "m_4koma_reader": "Love Pursuit Ledger",
        "m_oneshot_reader": "Unnamed Foes Mantle",
        "m_format_variety": "All Night Gallery",
        "m_light_novel_reader": "Nuke World Insignia",
        "m_novel_reader": "Endless Walk Crown",
        "m_visual_storyteller": "Perfect Kill Testament",
        "m_colored_classic": "Already Dead Survey",
        "m_webcomic_fan": "Hokuto Master Insignia",
        "m_manga_to_anime": "Source Adapted",
        "m_seinen_reader": "Fist Judge Pinnacle",
        "m_josei_reader": "Art Fan Pinnacle",
        "m_award_winning_art": "Martial Arts Relic",
        "m_debut_work": "Martial Arts Dominion",
        "m_vertical_scroll": "Secret Scrolls Decree Decree",
        "m_traditional_format": "Hara Art Fan Hoard",
        "m_cross_media": "Warrior Mind Accord",
        "m_spinoff_reader": "Fist Classic Accord",
        "m_remake_reader": "Reread Battle Pinnacle",
        "m_collaboration_reader": "Hokuto Master Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Unbroken Fist",
        "m_weekly_warrior": "North Star Season",
        "m_monthly_reader": "Hara Art Discipline",
        "m_comeback": "Wasteland Fuel Standard Standard",
        "m_weekend_streak": "Art Fan Fever",
        "m_no_zero_days": "Death Critic Proof Proof",
        "m_iron_will": "Iron Dedication",
        "m_habit_formed": "Dawn Strike Crown Crown",
        "m_consistent_pace": "Fist Action Scrutiny Scrutiny",
        "m_year_long": "Year Reading",
        "m_double_streak": "Unnamed Foes Resolve",
        "m_streak_recovery": "Hokuto Shinken Resolve",
        "m_daily_minimum": "Enemy Alerts Focus",
        "m_winter_streak": "Stop Carnage Observance Observance",
        "m_summer_streak": "Martial Arts Observance",
        "m_morning_streak": "Buronson Fan Clock",
        "m_night_streak": "Hara Art Fan Discipline",
        "m_unbreakable": "Art Fan Warrant",
        "m_eternal_flame": "Yuria's Love Record",
        "m_chapter_a_day": "Fist Stars Ledger Ledger",
        "m_genre_streak": "Fist School Streak",
        "m_completion_streak": "Unbroken Fist Return",
        "m_rating_streak": "Fist School Appraisal",
        "m_multi_ch_streak": "North Star Tenure",
        "m_author_streak": "Enemy Alerts Calendar",
        "m_perfect_week_manga": "Fist Classic Accord Accord",
        "m_diverse_streak": "Post Nuke Streak",

        // ── MANGA SCORING ──
        "m_critic": "Death Critic",
        "m_perfect_ten": "Perfect Issue",
        "m_harsh_critic": "Nuke World Scale",
        "m_fair_judge": "Non Stop Eye Eye",
        "m_generous_spirit": "Night Battle Decree",
        "m_score_all": "Enemies Roster Reckoning",
        "m_wide_range": "Hara Art Ledger Ledger",
        "m_controversial": "Bat Gang Standard Standard",
        "m_consistent_scorer": "Hokuto Expert Grade",
        "m_score_sniper": "Sequel Strike Reckoning",
        "m_evolving_taste": "Unnamed Foes Trial Trial",
        "m_bell_curve": "Hara Art Accord",
        "m_picky_reader": "Post Nuke Ledger",
        "m_100_rated": "Hara Art Standard",
        "m_500_rated": "Tragedy Drama Aegis",
        "m_mediocre_majority": "Unnamed Foes Canon",
        "m_rating_spree": "Buronson Fan Verdict",
        "m_score_variance": "Endless Walk Measure",
        "m_binge_rater": "Enemy Alerts Passage",
        "m_reread_rerate": "Already Dead Banner Banner",
        "m_masterpiece_hunter": "Bat Gang Banner",
        "m_contrarian": "Unbroken Fist Aegis",
        "m_optimist": "Warrior Mind Accord Accord",
        "m_score_distributor": "North Star Balance",
        "m_genre_critic": "Enemy Alerts Critic",
        "m_mean_above_8": "Endless Walk Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Perfect Kill Season",
        "m_valentines_read": "Fist School Observance",
        "m_pi_day": "Unnamed Foes Testament Testament",
        "m_april_fools": "Sequel Strike Devotion",
        "m_international_manga_day": "Nuke World Aegis",
        "m_free_comic_day": "Night Battle Chronicle",
        "m_summer_solstice": "Perfect Issue Focus Focus",
        "m_tanabata": "Fist Action Tanabata",
        "m_friday_13th": "Reread Battle Dominion Dominion",
        "m_halloween_read": "Night Walker Halloween",
        "m_thanksgiving_binge": "Fist Classic Charge",
        "m_christmas_read": "Classic Fan Pact",
        "m_new_years_eve": "Perfect Issue Pilgrimage",
        "m_birthday_read": "Fist Judge Focus",
        "m_holiday_marathon": "Death Touch Rally",
        "m_independence_day": "Unbroken Fist Aegis Aegis",
        "m_culture_day": "Tragedy Drama Seal Seal",
        "m_spring_equinox": "Night Walker Dominion",
        "m_earth_day": "Fist Judge Trial",
        "m_labor_day": "Classic Fan Seal",
        "m_winter_solstice": "Dawn Strike Focus Focus",
        "m_manga_birthday": "Fist Action Ritual",
        "m_every_holiday_reader": "Hokuto Shinken Watch",
        "m_consecutive_holidays": "Reread Battle Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Battle Intel Aegis",
        "m_fibonacci": "Warrior Seals Dominion",
        "m_palindrome_day": "Unnamed Foes Relic",
        "m_binary_day": "Dawn Strike Proof",
        "m_full_moon_read": "Art Fan Crown",
        "m_leap_year_read": "Post Nuke Practice",
        "m_triple_seven": "Non Stop Trial Trial",
        "m_thousand_complete": "Non Stop Ascension",
        "m_nice": "Secret Scrolls Seal Seal",
        "m_power_level_chapters": "Wasteland Fuel Aegis",
        "m_answer_42": "Art Fan Trial",
        "m_square_number": "Yuria's Love Standard",
        "m_prime_count": "Non Stop Pinnacle",
        "m_matching_date": "Hokuto Shinken Mantle",
        "m_century_chapter": "Battle Intel Decree",
        "m_pi_chapters": "Fist Judge Proof Proof",
        "m_synchronicity": "Fist School Emblem",
        "m_world_record": "Death Critic Warrant",
        "m_genre_clash": "Desert Walk Clash",
        "m_time_traveler": "Hokuto Expert Decree",
        "m_double_digits": "Raoh's Will Dominion",
        "m_one_two_three": "Hokuto Master Banner Banner",
        "m_lucky_seven": "Hara Art Fan Record Record",
        "m_exact_hundred_ch": "Warrior Seals Legend",
        "m_year_match_count": "Love Pursuit Routine",
        "m_chapter_match_date": "Dawn Strike Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Raoh's Will Index",
        "m_manhwa_format": "Night Walker Gallery",
        "m_manhua_format": "Stop Carnage Storehouse",
        "m_ln_format": "Non Stop Index",
        "m_oneshot_format": "Unnamed Foes Index",
        "m_doujin_format": "Buronson Fan Cabinet",
        "m_novel_format": "Sequel Strike Reserve Reserve",
        "m_format_master_manga": "Buronson Fan Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Hokuto Expert Link",
        "m_meta_collector": "Tragedy Drama Reliquary",
        "m_meta_category_starter": "All Night Standard",
        "m_meta_tier_climber": "Warrior Mind Token",
        "m_meta_tier_max": "Complete Mastery",
        "m_meta_xp_earner": "Raoh's Will Anchor",
        "m_meta_difficulty_easy": "Non Stop Panel",
        "m_meta_difficulty_hard": "Perfect Kill Node",
        "m_meta_unlock_spree": "Raoh's Will Marker",
        "m_meta_completionist": "Full Library",
        "m_meta_diverse": "Unnamed Foes Anchor",
        "m_meta_dominator": "Secret Scrolls Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#080300",
        primary: "#d41208",
        secondary: "#880604",
        accent: "#c88040",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/fist-of-the-north-star.jpg",
    particleColor: "#d41208",
    backgroundDim: 0.4,
    backgroundBlur: 22,
    particleTypes: {
        explosions: { label: "Explosions", maxCount: 8, defaultEnabled: true, defaultIntensity: 60 },
        dust: { label: "Wasteland Dust", maxCount: 20, defaultEnabled: true, defaultIntensity: 55 },
    },
    milestoneNames: {
  1: "Threadbare Kenshiro Wanders Spark",
  8: "Bat's Tarnished Omen",
  14: "Fractured Hokuto Shinken",
  21: "Post Apocalyptic Path",
  28: "Lowborn Legacy Myth",
  35: "Heart Hokuto Brush",
  41: "Zaku's Suppression Crest",
  48: "Humble Hokuto Secret",
  55: "Ragged Village Liberation Haven",
  61: "Ken's Faint Echo",
  68: "Lesser Raoh Shadow",
  75: "Shin Abduction Clash",
  81: "Doubtful Revealed Secret",
  88: "Nanto Seiken Sigil",
  95: "Martial's Expands Brush",
  102: "Really Cool Souther Spark",
  108: "Awakened Holy Emperor Crown",
  115: "Sacred's Resolute Clash",
  122: "Rising Fist Technique",
  128: "Warlord Territories Clash",
  135: "Dauntless S Pulse",
  142: "Ken Soul",
  149: "Hokuto's Mystery Secret",
  155: "Fresh Nanto Vow",
  162: "Valiant Desert Justice Echo",
  169: "Jagi's Prime Crown",
  175: "Polished Ken Brothers",
  182: "Raoh Conquest Bloom",
  189: "Stormlit Philosophy Sigil",
  195: "Wasteland Tyranny Flame",
  202: "Rei's Legacy Spark",
  209: "Tempered Friendship Vow",
  216: "Trusted Mamiya Village Haven",
  222: "Zao's Steadfast Path",
  229: "Ironclad Honor Survival",
  236: "Ryuga Wolf Pulse",
  242: "Core Legacy Crest",
  249: "Ken Journey Mark",
  256: "Nanto's Battles Clash",
  262: "Formidable Martial Brush",
  269: "Lucid Raoh Kenshiro Crown",
  276: "Fist's Ranked Clash",
  283: "Fabled Wasteland Armies",
  289: "Hokuto Mastery Sigil",
  296: "Seasoned Legacy Flame",
  303: "Souther Holy Crown",
  309: "Bloodlines's Truth Secret",
  316: "Valorous Ken Soul",
  323: "Stalwart Raoh Kingdom Crown",
  330: "Nanto's Commanding Myth",
  336: "Refined Brothers Conflict",
  343: "Ken Raoh Clash",
  350: "Blazing Legacy Mark",
  356: "Hokuto Ultimate Vow",
  363: "Martial's Order Brush",
  370: "Peerless Raoh Crown",
  376: "Ardent Ken Training Zenith",
  383: "Turning's Focused Bloom",
  390: "Vigilant Raoh Campaign",
  397: "Ken Resolve Flame",
  403: "Elite Legacy Pact",
  410: "Yuria Fate Omen",
  417: "Wasteland's Flicker Seal",
  423: "Sovereign Ken Clash",
  430: "Regal Musou Tensei Myth",
  437: "Raoh's Crowned Secret",
  444: "Mythborn Brotherhood Resolution",
  450: "Warlord Era Clash",
  457: "Radiant S Vow",
  464: "Ken Wanderer Echo",
  470: "Survivor's Rise Crown",
  477: "Climactic Legend Zenith",
  484: "Epic Peaceful Wasteland Bloom",
  490: "New's Unreal Sigil",
  497: "Peak Hokuto Tested",
  504: "Ken Protector Vow",
  511: "Exalted Return Omen",
  517: "Martial Reforms Brush",
  524: "Lost's Legacy Clash",
  531: "Celestial Ken Soul",
  537: "Phantom Nanto Survivors Pulse",
  544: "Wasteland's Crimson Crest",
  551: "Silver Hope Ruins",
  557: "Bandit Kingdoms Crown",
  564: "Feral Expands Echo",
  571: "Ken Legendary Crown",
  578: "Martial's Fragile Brush",
  584: "Dread Post Clash",
  591: "Luminous Survivor Generations Sigil",
  598: "Ken's Thunderous Flame",
  604: "Ultraviolet Raoh Echo",
  611: "Fist Philosophy Omen",
  618: "Secret Legacy Seal",
  625: "Martial Arts Brush",
  631: "Ken's Legend Myth",
  638: "Worldclass Humanity Pulse",
  645: "Lawless Myth North Crest",
  651: "Wasteland's Chosen Mark",
  658: "Fearless Hokuto Teachings",
  665: "Legacy Echo",
  671: "Cinematic Fighters Clash",
  678: "Ken Eternal Zenith",
  685: "Raoh's Fist Bloom",
  692: "Canonized Rei Sigil",
  698: "Ascendant Nanto Star Echo",
  705: "Quiet's Transfigured Spark",
  712: "Immortal Dormant Warlords",
  718: "Balance Seal",
  725: "Astral Ken Path",
  732: "Fist North Myth",
  739: "Ken's Legend Pulse",
  745: "Prismatic Raoh Crest",
  752: "Abyssal Silent Wasteland Mark",
  759: "Dormant's Unbound Brush",
  765: "Eternal Legend Fist",
  772: "Hokuto Martial Brush",
  779: "Transcendent Myth Crown",
  785: "Fist Philosophy Bloom",
  792: "Strength's Legacy Force",
  799: "Ultimate Martial Brush",
  806: "Mythic Survival Honor Spark",
  812: "World's Godlike Force",
  819: "Canonical Hokuto Mastery",
  826: "Ken Warrior Clash",
  832: "Heavenly King Crown",
  839: "Rei Spirit Echo",
  846: "Closure's Emotional Soul",
  852: "Timeless Acceptance Mark",
  859: "Empyrean Strength Responsibility Force",
  866: "Violence's Primordial Echo",
  873: "Omniscient Combat Flow",
  879: "Hokuto Eternal Zenith",
  886: "Apocalyptic Defined Brush",
  893: "Resolution Soul",
  899: "Fist's Truth Secret",
  906: "Final Origin Secret",
  913: "Crowned Survival Omen",
  920: "Martial's Mythic Brush",
  926: "Absolute Legend Hokuto",
  933: "Combat Flow Myth",
  940: "Cosmic Power Force",
  946: "Wasteland Crest",
  953: "Martial's Perfect Brush",
  960: "Definitive Ultimate Vow",
  966: "Ultimate Walked Ruined Vow",
  973: "Walked's Infinite Vow",
  980: "Sovereign Walked Ruined",
  987: "Walked Ruined Vow",
  993: "Legendary Violence Vow",
  1000: "Ultimate Ultimate Fist"
}
}
