import { AnimeThemeConfig } from "./types"
import { GiAnchor, GiWaves, GiSun, GiTreeBranch, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiBoomerang } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const futureBoyConanTheme: AnimeThemeConfig = {
    id: "future-boy-conan",
    displayName: "Future Boy Conan",
    description: "In a post-apocalyptic world reclaimed by the sea, a boy of incredible strength fights for Lana and a peaceful future — Miyazaki's first masterpiece of hope and adventure.",
    fontFamily: "'Nunito', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Nunito:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "160 230 235",
        "--color-brand-300": "90 205 215",
        "--color-brand-400": "40 180 195",
        "--color-brand-500": "10 155 170",
        "--color-brand-600": "6 125 140",
        "--color-brand-700": "4 96 108",
        "--color-brand-800": "2 68 76",
        "--color-brand-900": "1 40 45",
        "--color-brand-950": "0 22 25",
        "--brand": "10 155 170",
        "--background": "#020e0f",
        "--paper": "#061618",
        "--color-gray-950": "2 12 13",
        "--color-gray-900": "4 22 24",
        "--color-gray-800": "8 38 42",
        "--color-gray-700": "14 60 66",
        "--color-gray-600": "24 90 98",
        "--color-gray-500": "40 128 138",
        "--color-gray-400": "70 165 175",
        "--color-gray-300": "110 195 200",
        "--color-gray-200": "155 218 222",
        "--color-gray-100": "196 236 238",
        "--color-gray-50": "230 248 249",
    },
    sidebarOverrides: {
        "home": { icon: GiAnchor, label: "Remnant Island" },
        "schedule": { icon: GiAlarmClock, label: "Tide Schedule" },
        "manga": { icon: LuBookOpen, label: "Survival Manual" },
        "lists": { icon: GiBoomerang, label: "Adventure Log" },
        "discover": { icon: GiBullseye, label: "Horizon Scouting" },
        "torrent-list": { icon: GiWaves, label: "Ocean Cache" },
        "debrid": { icon: GiSun, label: "Solar Power" },
        "unmatched": { icon: GiTreeBranch, label: "Lost in Jungle" },
        "enmasse": { icon: GiResize, label: "Colony Deployment" },
        "scan-summaries": { icon: TbReportSearch, label: "Scout Reports" },
        "auto-downloader": { icon: LuRss, label: "Island Signals" },
        "community": { icon: GiAnchor, label: "Resistance Crew" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Island Alerts" },
        "achievements": { icon: GiTrophy, label: "Conan's Medals" },
        "milestones": { icon: LuFlag, label: "Island Goals" },
        "theme-manager": { icon: GiPalette, label: "Island Colors" },
        "extensions": { icon: BiExtension, label: "Survival Gear" },
        "sync": { icon: IoCloudOfflineOutline, label: "Remnant Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Colony Controls" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Rescue",
        "a_episode_counter": "Unbroken Tide Mark",
        "a_episode_titan": "Island Drama Relic",
        "a_hours_invested": "War Tech Proof",
        "a_time_lord": "Island Veteran",
        "a_anime_collector": "Survivor's Cache",
        "a_library_legend": "Island Archives",
        "a_first_complete": "Journey Done",
        "a_hundred_club": "Hundred Adventures",
        "a_first_day": "Island Judge Seal",
        "a_first_rating": "Island Drama Appraisal",
        "a_ten_thousand_min": "Island Master Standard",
        "a_season_veteran": "Island Master Library",
        "a_year_explorer": "Island Alerts Map",
        "a_century_watcher": "World Rebuilt Ledger",
        "a_five_hundred_eps": "Future World Dominion",
        "a_thousand_eps": "Wild Strength Record",
        "a_watching_ten": "Future Boy Conan Acclaim",
        "a_ptw_hoarder": "Conan's Sprint Library",
        "a_dropped_honesty": "Future Boy Conan Summit",
        "a_five_thousand_eps": "Island Return Warrant",
        "a_ten_completed": "Lana Rescued Afterglow",
        "a_fifty_completed": "Island Critic Ascension",
        "a_five_hundred_completed": "Future Boy Conan Clear",
        "a_mean_score_tracker": "Classic Story Verdict",
        "a_unique_studios": "Wild Strength Collection",
        "a_days_spent_watching": "Ocean Marathon Dominion",
        "a_all_status": "Remnant Island Testament",
        "a_first_favorite": "Author Fan Cabinet",
        "a_favorites_collector": "Return Visit Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Conan's Will Drive",
        "a_marathon_runner": "Ocean Marathon",
        "a_weekend_warrior": "Island Drama Ordeal",
        "a_non_stop": "Loyal Islander Fever",
        "a_one_more_episode": "Survival Gear Mantle",
        "a_speed_run": "Conan's Sprint",
        "a_double_feature": "Hidden Gem Crown",
        "a_triple_threat": "Endless Tides Record",
        "a_five_a_day": "Future Sci Accord",
        "a_back_to_back": "Perfect Score Surge",
        "a_seasonal_binge": "Island Drama Cascade",
        "a_cour_crusher": "Ocean Marathon Ordeal",
        "a_half_day_watch": "Unbroken Tide Crown",
        "a_full_day_watch": "Daily Watch Pinnacle",
        "a_power_weekend": "Island Judge Run",
        "a_binge_king": "Non-Stop Adventure",
        "a_no_sleep": "All-Night Rescue",
        "a_entire_season": "Dawn Patrol Library",
        "a_seven_day_challenge": "Daily Watch Mark",
        "a_hundred_day_binge": "Island Judge Surge",
        "a_genre_binge": "Conan's Antics Binge",
        "a_studio_binge": "Unbroken Tide Fever",
        "a_season_sweep": "Super Strength Codex",
        "a_forty_eight_hour": "Classic Fan Overture",
        "a_ep_counter_day": "Lana Rescued Aegis",
        "a_multi_series_binge": "Conan's Sprint Streak",
        "a_midnight_binge": "Survival Gear Cascade",
        "a_new_year_binge": "Night Rescue Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Survival Action",
        "a_genre_adventure": "Pacific Explorer",
        "a_genre_comedy": "Conan's Antics",
        "a_genre_drama": "Lana Rescued",
        "a_genre_fantasy": "Future World",
        "a_genre_horror": "Indastria Terror",
        "a_genre_mystery": "Stop Adventure Mystery",
        "a_genre_romance": "Conan and Lana",
        "a_genre_scifi": "Post-War Tech",
        "a_genre_sol": "Island Return Slice",
        "a_genre_sports": "Classic Fan Sports",
        "a_genre_supernatural": "Super Strength",
        "a_genre_thriller": "Island Critic Thriller",
        "a_genre_mecha": "Giant Lune",
        "a_genre_music": "Island Master Music",
        "a_genre_psychological": "Hope vs. Despair",
        "a_genre_ecchi": "Conan's Will Ecchi",
        "a_genre_mahou_shoujo": "Endless Tides Magic Shoujo",
        "a_tag_isekai": "Non Stop Isekai",
        "a_tag_harem": "All Night Harem",
        "a_tag_bl": "Classic Fan Bl",
        "a_tag_gl": "Survival Gear Gl",
        "a_tag_historical": "Boy Hero Historical",
        "a_tag_military": "Future World Military",
        "a_tag_school": "Conan's Sprint School",
        "a_tag_martial_arts": "Daily Watch Martial Arts",
        "a_tag_vampire": "Endless Tides Vampire",
        "a_tag_samurai": "Wild Strength Samurai",
        "a_tag_space": "Giant Lune Space",
        "a_tag_parody": "Conan Lana Parody",
        "a_tag_idol": "Classic Fan Idol",
        "a_tag_post_apocalyptic": "Island Signals Post Apocalyptic",
        "a_tag_cyberpunk": "Loyal Islander Cyberpunk",
        "a_tag_shounen": "Island Signals Shounen",
        "a_tag_seinen": "Solar Power Seinen",
        "a_tag_shoujo": "Solar Power Shoujo",
        "a_tag_josei": "Lana Rescued Josei",
        "a_tag_survival": "Return Visit Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "World Rebuilt",
        "a_mega_completionist": "Miyazaki Master",
        "a_completion_rate_50": "Endless Tides Return",
        "a_completion_rate_75": "Island Critic Crown",
        "a_completion_rate_90": "Lana Rescued Resolution",
        "a_no_drop": "Stop Adventure Decree",
        "a_long_runner_complete": "Island Judge Clear",
        "a_sequel_chain": "Next Chapter",
        "a_clean_list": "Super Strength Relic",
        "a_from_ptw": "Conan Lana Index",
        "a_rewatch_master": "Classic Story Return",
        "a_short_complete": "Sea Adventure Endgame",
        "a_same_day_start_finish": "Conan's Medals Pinnacle",
        "a_revival": "World Rebuilt Insignia",
        "a_zero_to_hero": "Boy to Hero",
        "a_five_genre_complete": "Sea Adventure A Five Genre",
        "a_full_franchise": "Conan's Sprint Chronicle",
        "a_batch_complete": "Island Drama Crown",
        "a_paused_to_done": "Lana Rescued Aegis Aegis",
        "a_completion_spree": "Miyazaki Art Triumph",
        "a_multi_rewatch": "Miyazaki Art Triumph Triumph",
        "a_dropped_recovery": "Unbroken Tide Conquest",
        "a_ten_perfect_scores": "Island Judge Acclaim",
        "a_seasonal_clear": "Ocean Marathon Codex",
        "a_complete_genre_span": "Action Fan A Complete Genre",
        "a_monthly_completions": "Classic Story Afterglow",
        "a_yearly_completions": "Remnant Island Epilogue",
        "a_rapid_complete": "Daily Watch Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Islander",
        "a_studio_devotee": "Stop Adventure Treasury",
        "a_rewatcher": "Island Return",
        "a_triple_rewatch": "Conan's Antics Coda",
        "a_annual_tradition": "Daily Watch Proof",
        "a_director_fan": "Super Strength Trial",
        "a_voice_actor_fan": "Unbroken Tide Crown Crown",
        "a_ost_lover": "Conan's Sprint Seal",
        "a_source_reader": "Island Alerts Cabinet",
        "a_waiting_weekly": "Stop Adventure Clock",
        "a_childhood_revisit": "Original Fan Seal",
        "a_saga_tracker": "Giant Lune Standard",
        "a_genre_loyalty": "Island Return Loyalty",
        "a_decade_watcher": "Decade Survivor",
        "a_adaptation_hunter": "Conan Lana Trial",
        "a_original_anime_fan": "Night Watch Testament",
        "a_long_commitment": "Daily Watch Mark Mark",
        "a_perfect_attendance": "Future Boy Conan Standard",
        "a_favorite_studio_5": "Island Signals Library",
        "a_complete_catalog": "Return Visit Seal",
        "a_franchise_collector": "Island Signals Archive",
        "a_airing_follower": "Original Fan Signal",
        "a_genre_master": "Super Strength Master",
        "a_staff_follower": "Island Signals Oath",
        "a_multi_season_fan": "Boy Hero Hoard",
        "a_format_diversity": "Endless Tides Cache",
        "a_year_dedication": "Island Drama Tenure",
        "a_season_dedication": "Future World Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Conan's Antics Explorer",
        "a_studio_hopper": "Classic Story Collection",
        "a_tag_explorer": "Island Drama Explorer",
        "a_decade_hopper": "Conan's Sprint Chronicle Chronicle",
        "a_hidden_gem": "Hidden Island",
        "a_popular_taste": "Classic Fan Decree",
        "a_retro_appreciator": "Return Visit Aegis",
        "a_modern_viewer": "Conan's Medals Pinnacle Pinnacle",
        "a_cross_demographic": "Conan's Will Pinnacle",
        "a_underdog_fan": "Action Fan Trial",
        "a_variety_week": "Island Signals Horizon",
        "a_foreign_cinema": "Survival Gear Expedition",
        "a_classic_connoisseur": "78 Classic Fan",
        "a_every_season": "Original Fan Archive",
        "a_award_winner": "Island Master Insignia",
        "a_niche_explorer": "Solar Power Horizon",
        "a_global_anime": "Sea Adventure Crown",
        "a_cult_classic": "Miyazaki Classic",
        "a_random_pick": "Classic Fan Decree Decree",
        "a_new_genre_month": "Future Boy Conan A New",
        "a_seasonal_completionist": "World Rebuilt Summit",
        "a_unpopular_opinion": "Author Fan Standard",
        "a_top_rated_viewer": "Future Sci Seal",
        "a_source_variety": "Ocean Marathon Storehouse",
        "a_low_score_brave": "Loyal Islander Measure",
        "a_upcoming_watcher": "Future Sci Seal Seal",
        "a_short_series_explorer": "Survival Gear Expedition Expedition",
        "a_long_series_explorer": "Hidden Gem Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Night Watch",
        "a_early_bird": "Dawn Patrol",
        "a_lunch_break": "Post War Trial",
        "a_golden_hour": "Hidden Island Tenure",
        "a_four_am_club": "Miyazaki Art Gathering",
        "a_witching_hour": "Island Critic Tenure",
        "a_new_year_watch": "Island Drama Season",
        "a_midnight_premiere": "Night Rescue Devotion",
        "a_all_hours": "World Rebuilt Seal",
        "a_dawn_warrior": "Classic Fan Aegis",
        "a_afternoon_delight": "War Tech Proof Proof",
        "a_prime_time": "Island Master Insignia Insignia",
        "a_workday_watcher": "Conan's Will Pinnacle Pinnacle",
        "a_sunday_marathon": "Island Judge Momentum",
        "a_rainy_day": "Island Critic Relic",
        "a_morning_routine": "Boy Hero Promise",
        "a_night_shift": "Endless Tides Aegis",
        "a_twilight_zone": "Dawn Patrol Ledger",
        "a_seasonal_premier": "Stop Adventure Cabinet",
        "a_clock_collector": "Miyazaki Art Repository",
        "a_weekend_binge_hours": "Solar Power Streak",
        "a_late_night_regular": "Remnant Island Dominion",
        "a_sunrise_watcher": "Super Strength Relic Relic",
        "a_holiday_watcher": "Future Sci Pact",
        "a_every_day_of_week": "Perfect Score Ledger",
        "a_monthly_hours": "Classic Fan Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Lana Rescued Record",
        "a_party_host": "Endless Tides Record Record",
        "a_social_butterfly": "Island Alerts Company",
        "a_group_binge": "Wild Strength Sprint",
        "a_party_regular": "Dawn Patrol Chronicle",
        "a_sync_viewer": "Miyazaki Art Standard",
        "a_commentator": "Return Visit Record",
        "a_party_marathon": "Conan's Antics Vigil",
        "a_full_house": "Future World Trial",
        "a_community_pillar": "Remnant Island Alliance",
        "a_watch_party_streak": "Return Visit Vigil",
        "a_diverse_party": "Boy Hero Seal",
        "a_late_night_party": "Remnant Island Testament Testament",
        "a_party_veteran": "Future World Testament",
        "a_genre_party": "Survival Gear Party",
        "a_weekly_party": "Miyazaki Art Calendar",
        "a_silent_viewer": "Night Watch Mantle",
        "a_recommendation_giver": "Solar Power Network",
        "a_party_completionist": "Giant Lune Coda",
        "a_social_scorer": "Super Strength Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Hidden Gem Proof",
        "a_fibonacci": "Island Drama Dominion",
        "a_palindrome_day": "Island Drama Relic Relic",
        "a_binary_day": "Island Return Mark",
        "a_full_moon": "Original Fan Insignia",
        "a_leap_year": "Sea Adventure Devotion",
        "a_time_traveler": "Stop Adventure Record",
        "a_genre_clash": "Conan's Antics Clash",
        "a_triple_seven": "Island Drama Testament",
        "a_thousand_complete": "Night Watch Epilogue",
        "a_pi_episodes": "Conan's Will Crown",
        "a_synchronicity": "Action Fan Anchor",
        "a_world_record": "Unbroken Tide Warrant",
        "a_nice": "Island Master Chronicle",
        "a_power_level": "Night Watch Testament Testament",
        "a_answer_42": "Classic Fan Standard",
        "a_square_number": "Conan's Antics Decree",
        "a_prime_count": "Island Master Seal",
        "a_matching_date": "Action Fan Mantle",
        "a_century_episode": "Conan's Will Mark",
        "a_double_digits": "Island Critic Testament",
        "a_one_two_three": "Sea Adventure Crown Crown",
        "a_lucky_seven": "Daily Watch Crown",
        "a_all_tens": "Loyal Islander Criterion",
        "a_exact_hundred_eps": "Giant Lune Legend",
        "a_year_match_count": "Stop Adventure Yearlong",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Solar Power Ledger",
        "a_movie_buff": "Unbroken Tide Mark Mark",
        "a_ova_hunter": "Giant Lune Standard Standard",
        "a_ona_explorer": "Action Fan Secret",
        "a_special_watcher": "Island Critic Relic Relic",
        "a_short_king": "All Night Crown",
        "a_variety_pack": "Unbroken Tide Inquiry",
        "a_film_festival": "Future Sci Chronicle",
        "a_music_video": "Boy Hero Chronicle",
        "a_tv_short": "Conan's Antics Record",
        "a_movie_marathon": "Conan's Antics Gauntlet",
        "a_double_length": "Hidden Gem Crown Crown",
        "a_anthology": "Endless Tides Aegis Aegis",
        "a_mini_series": "Author Fan Decree",
        "a_theatrical": "Island Signals Accord",
        "a_format_master": "Miyazaki Art Vault",
        "a_long_movie": "World Rebuilt Insignia Insignia",
        "a_back_catalog": "Return Visit Standard",
        "a_cm_watcher": "Non Stop Aegis",
        "a_pv_collector": "Action Fan Storehouse",
        "a_format_balance": "Miyazaki Art Vault Vault",
        "a_episodic_master": "Non Stop Standard",
        "a_sequel_movie": "Sea Adventure Pinnacle",
        "a_recap_watcher": "Post War Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Watch",
        "a_mega_streak": "Endless Tides",
        "a_weekly_warrior": "Future World Season",
        "a_monthly_watcher": "Night Rescue Calendar",
        "a_comeback": "Island Alerts Decree",
        "a_weekend_streak": "Loyal Islander Passage",
        "a_no_zero_days": "Island Return Warrant Warrant",
        "a_iron_will": "Conan's Will",
        "a_habit_formed": "Perfect Score Banner",
        "a_consistent_pace": "Hidden Gem Measure",
        "a_year_long": "Year Surviving",
        "a_double_streak": "Super Strength Watch",
        "a_streak_recovery": "Night Watch Season",
        "a_daily_minimum": "Night Rescue Focus",
        "a_winter_streak": "Survival Gear Watch",
        "a_summer_streak": "Island Critic Resolve",
        "a_morning_streak": "Return Visit Clock",
        "a_night_streak": "Perfect Score Constancy",
        "a_unbreakable": "All Night Proof",
        "a_eternal_flame": "Classic Story Standard",
        "a_completion_streak": "Giant Lune Return",
        "a_rating_streak": "Island Drama Balance",
        "a_multi_ep_streak": "Unbroken Tide Ritual",
        "a_genre_streak": "Island Drama Streak",
        "a_studio_streak": "Island Alerts Cabinet Cabinet",
        "a_perfect_week": "Action Fan Relic",

        // ── ANIME SCORING ──
        "a_critic": "Island Judge",
        "a_perfect_ten": "Perfect Island",
        "a_harsh_critic": "Strict Surveyor",
        "a_fair_judge": "Remnant Island Balance",
        "a_generous_spirit": "Night Rescue Pinnacle",
        "a_score_all": "War Tech Criterion",
        "a_wide_range": "Island Master Ledger",
        "a_controversial": "Return Visit Decree",
        "a_consistent_scorer": "Stop Adventure Verdict",
        "a_score_sniper": "Sea Adventure Score",
        "a_evolving_taste": "Super Strength Testament",
        "a_bell_curve": "Future Boy Conan Insignia",
        "a_picky_watcher": "Night Watch Warrant",
        "a_100_rated": "Miyazaki Art Warrant",
        "a_500_rated": "All Night Pinnacle",
        "a_mediocre_majority": "Action Fan Canon",
        "a_rating_spree": "Return Visit Review",
        "a_score_variance": "Loyal Islander Score",
        "a_masterpiece_hunter": "Return Visit Banner",
        "a_contrarian": "Conan's Antics Record Record",
        "a_optimist": "Boy Hero Ledger",
        "a_score_distributor": "Post War Appraisal",
        "a_genre_critic": "Hidden Gem Critic",
        "a_mean_above_8": "Daily Watch Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Tide",
        "a_valentines_weeb": "Island Signals Vow",
        "a_pi_day": "Remnant Island Trial",
        "a_april_fools": "Sea Adventure Devotion Devotion",
        "a_international_anime_day": "World Rebuilt Record",
        "a_star_wars_day": "Island Judge Chronicle",
        "a_summer_solstice": "Island Return Calendar",
        "a_tanabata": "Conan's Medals Focus",
        "a_friday_13th": "Post War Relic",
        "a_halloween_spirit": "Solar Power Vow",
        "a_thanksgiving_binge": "Dawn Patrol Run",
        "a_christmas_special": "Island Holiday",
        "a_new_years_eve": "Daily Watch Pilgrimage",
        "a_birthday_watch": "Future Boy Conan Vow",
        "a_holiday_marathon": "Wild Strength Overture",
        "a_independence_day": "Classic Story Banner",
        "a_culture_day": "Conan's Sprint Insignia",
        "a_spring_equinox": "Wild Strength Decree",
        "a_earth_day": "Unbroken Tide Mantle",
        "a_labor_day": "Solar Power Seal",
        "a_winter_solstice": "Conan's Will Pilgrimage",
        "a_anime_birthday": "Unbroken Tide Pilgrimage",
        "a_every_holiday": "Conan Lana Resolve",
        "a_consecutive_holidays": "Island Critic Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Island Alerts Rank",
        "a_meta_collector": "Conan's Sprint Hoard",
        "a_meta_category_starter": "Night Rescue Badge",
        "a_meta_tier_climber": "Conan's Sprint Glyph",
        "a_meta_tier_max": "Island Master",
        "a_meta_xp_earner": "Post War Emblem",
        "a_meta_difficulty_easy": "Remnant Island Mechanism",
        "a_meta_difficulty_hard": "Future Sci Writ",
        "a_meta_unlock_spree": "Future World Panel",
        "a_meta_completionist": "Complete Log",
        "a_meta_diverse": "Island Drama Emblem",
        "a_meta_dominator": "Dawn Patrol Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Page",
        "m_chapter_counter": "Miyazaki Art Pinnacle",
        "m_chapter_titan": "Ocean Marathon Relic",
        "m_reading_hours": "Post War Relic Relic",
        "m_reading_time_lord": "World Rebuilt Record Record",
        "m_manga_collector": "Future World Ledger",
        "m_library_legend": "Conan's Sprint Reliquary",
        "m_first_complete": "Volume Complete",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "Island Signals Seal",
        "m_first_rating": "Post War Eye",
        "m_ten_thousand_pages": "Island Signals Gauge",
        "m_volume_collector": "Night Watch Storehouse",
        "m_year_explorer": "Classic Fan Quest",
        "m_century_reader": "Survival Gear Dominion",
        "m_five_hundred_ch": "Island Master Legend",
        "m_thousand_ch": "Super Strength Legend",
        "m_reading_ten": "Survival Gear Appraisal",
        "m_ptr_hoarder": "Super Strength Index",
        "m_dropped_honesty": "Conan's Sprint Summit",
        "m_season_reader": "Return Visit Treasury",
        "m_active_reader": "Island Critic Trial",
        "m_five_thousand_ch": "Conan's Antics Standard",
        "m_ten_completed": "Conan's Antics Resolution",
        "m_fifty_completed": "Super Strength Harvest",
        "m_five_hundred_completed": "Perfect Score Legacy",
        "m_mean_score_tracker": "Stop Adventure Audit",
        "m_unique_authors": "Unbroken Tide Reserve",
        "m_all_status": "Island Critic Testament Testament",
        "m_first_favorite": "Giant Lune Cache",
        "m_favorites_collector": "Island Alerts Shelf",
        "m_days_spent_reading": "Conan's Will Relic",

        // ── MANGA BINGE ──
        "m_binge_reader": "Future Boy Conan Streak",
        "m_marathon_reader": "Remnant Island Rush",
        "m_weekend_reader": "Original Fan Run",
        "m_non_stop_reading": "Giant Lune Gauntlet",
        "m_one_more_chapter": "Post War Testament Testament",
        "m_speed_read": "Island Return Drive",
        "m_double_story": "Wild Strength Banner",
        "m_triple_read": "Classic Story Record",
        "m_five_a_day": "Boy Hero Insignia",
        "m_chapter_chain": "Conan's Sprint Accord",
        "m_volume_binge": "Loyal Islander Drive",
        "m_power_reader": "Island Judge Seal Seal",
        "m_half_day_read": "Island Alerts Aegis",
        "m_full_day_read": "Non Stop Aegis Aegis",
        "m_power_weekend": "Island Signals Streak",
        "m_binge_king": "Marathon Reader",
        "m_no_sleep_read": "Survival Gear Rush",
        "m_full_series_rush": "Remnant Island Cascade",
        "m_seven_day_challenge": "Conan's Medals Warrant",
        "m_hundred_day_read": "Island Drama Legend",
        "m_volume_rush": "Lana Rescued Gauntlet",
        "m_series_sweep": "Conan Lana Trial Trial",
        "m_genre_binge": "Non Stop Binge",
        "m_author_binge": "Original Fan Surge",
        "m_chapter_counter_day": "Dawn Patrol Ledger Ledger",
        "m_multi_series_binge": "Island Master Charge",
        "m_midnight_binge": "Super Strength Tempest",
        "m_new_year_binge": "Unbroken Tide Passage",
        "m_forty_eight_hour": "Stop Adventure Rally",
        "m_oneshot_binge": "Island Return Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Fan",
        "m_genre_adventure": "Sea Adventure",
        "m_genre_comedy": "Island Alerts Comedy",
        "m_genre_drama": "Island Drama",
        "m_genre_fantasy": "Island Fantasy",
        "m_genre_horror": "Dark Chapter",
        "m_genre_mystery": "Conan's Antics Mystery",
        "m_genre_romance": "Rescue Romance",
        "m_genre_scifi": "Future Sci-Fi",
        "m_genre_sol": "Miyazaki Art Slice",
        "m_genre_sports": "Lana Rescued Sports",
        "m_genre_supernatural": "Wild Strength",
        "m_genre_thriller": "Action Fan Thriller",
        "m_genre_psychological": "Deep Read",
        "m_genre_isekai": "Future World Isekai",
        "m_genre_shounen": "Hidden Island Shounen",
        "m_genre_ecchi": "Hidden Gem Ecchi",
        "m_genre_mahou_shoujo": "Island Alerts Magic Shoujo",
        "m_genre_mecha": "Night Watch Mecha",
        "m_genre_music": "Solar Power Music",
        "m_tag_isekai_new": "Post War Isekai New",
        "m_tag_harem": "War Tech Harem",
        "m_tag_bl": "Author Fan Bl",
        "m_tag_gl": "Super Strength Gl",
        "m_tag_historical": "Island Master Historical",
        "m_tag_military": "Hidden Island Military",
        "m_tag_school": "Island Signals School",
        "m_tag_martial_arts": "Miyazaki Art Martial Arts",
        "m_tag_vampire": "Lana Rescued Vampire",
        "m_tag_samurai": "Endless Tides Samurai",
        "m_tag_space": "Author Fan Space",
        "m_tag_parody": "Night Watch Parody",
        "m_tag_idol": "Author Fan Idol",
        "m_tag_post_apocalyptic": "Conan's Sprint Post Apocalyptic",
        "m_tag_cyberpunk": "War Tech Cyberpunk",
        "m_tag_shoujo": "Future Sci Shoujo",
        "m_tag_survival": "Island Alerts Survival",
        "m_tag_cooking": "Future Boy Conan Cooking",
        "m_tag_medical": "Island Critic Medical",
        "m_tag_villainess": "Original Fan Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Story",
        "m_mega_completionist": "Master Reader",
        "m_completion_rate_50": "Author Fan Return",
        "m_completion_rate_75": "Action Fan Ascension",
        "m_completion_rate_90": "Classic Story Resolution",
        "m_no_drop": "Giant Lune Decree",
        "m_long_runner_complete": "Dawn Patrol Clear",
        "m_sequel_chain": "Solar Power Seal Seal",
        "m_clean_list": "Ocean Marathon Relic Relic",
        "m_from_ptr": "Future Sci Watchlist",
        "m_reread_master": "Remnant Island Trial Trial",
        "m_oneshot_complete": "Remnant Island Ascension",
        "m_same_day_start_finish": "Daily Watch Crown Crown",
        "m_revival": "Dawn Patrol Accord",
        "m_zero_to_hundred": "Conan's Antics Banner",
        "m_five_genre_complete": "Island Return M Five Genre",
        "m_full_collection": "Daily Watch Proof Proof",
        "m_batch_complete": "Stop Adventure Summit",
        "m_paused_to_done": "Classic Story Standard Standard",
        "m_completion_spree": "All Night Triumph",
        "m_format_completionist": "Remnant Island Completion",
        "m_catch_up": "World Rebuilt Chronicle",
        "m_multi_reread": "Giant Lune Banner",
        "m_dropped_recovery": "Hidden Gem Conquest",
        "m_ten_perfect_scores": "Original Fan Judgment",
        "m_complete_genre_span": "Future World M Complete Genre",
        "m_monthly_completions": "Non Stop Return",
        "m_yearly_completions": "Future World Epilogue",
        "m_rapid_complete": "Conan's Medals Finale",
        "m_author_complete": "Island Signals Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Island Reader",
        "m_mangaka_lover": "Author Fan",
        "m_rereader": "Return Visit",
        "m_triple_reread": "Island Drama Testament Testament",
        "m_annual_reread": "Conan's Antics Banner Banner",
        "m_publisher_fan": "All Night Mark",
        "m_artist_fan": "Solar Power Insignia",
        "m_adaptation_compare": "Future Boy Conan Insignia Insignia",
        "m_source_material_fan": "Original Fan",
        "m_waiting_weekly": "Endless Tides Streak",
        "m_classic_reader": "Night Watch Lantern",
        "m_saga_reader": "Conan's Sprint Decree",
        "m_genre_loyalty": "Hidden Gem Loyalty",
        "m_decade_reader": "Loyal Islander Warrant",
        "m_ln_adaptation": "Loyal Islander Mark",
        "m_original_work": "Lana Rescued Standard",
        "m_long_commitment": "Hidden Gem Mark",
        "m_up_to_date": "Unbroken Tide Warrant Warrant",
        "m_favorite_mangaka": "Classic Fan Treasury",
        "m_complete_portfolio": "All Night Triumph Triumph",
        "m_franchise_collector": "World Rebuilt Archive",
        "m_serialization_follower": "Classic Fan Handshake",
        "m_genre_master": "Ocean Marathon Master",
        "m_multi_series_author": "Conan's Sprint Insignia Insignia",
        "m_format_diversity": "Lana Rescued Shelf",
        "m_year_dedication": "Survival Gear Tenure",
        "m_ongoing_follower": "Loyal Islander Fellowship",
        "m_genre_loyalty_50": "Super Strength Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Wild Strength Explorer",
        "m_publisher_hopper": "All Night Mantle",
        "m_tag_explorer": "Conan Lana Explorer",
        "m_decade_hopper": "Future Sci Chronicle Chronicle",
        "m_hidden_gem": "Hidden Gem",
        "m_popular_taste": "Stop Adventure Record Record",
        "m_retro_reader": "Stop Adventure Accord",
        "m_modern_reader": "Island Master Seal Seal",
        "m_cross_demographic": "Night Rescue Crown",
        "m_underdog_fan": "Stop Adventure Accord Accord",
        "m_variety_week": "Solar Power Horizon Horizon",
        "m_manhwa_reader": "Sea Adventure Proof",
        "m_manhua_reader": "Night Watch Mantle Mantle",
        "m_classic_connoisseur": "Perfect Score Glimpse",
        "m_award_winner": "Survival Gear Warrant",
        "m_niche_explorer": "Future Boy Conan Horizon",
        "m_world_manga": "World Rebuilt Chronicle Chronicle",
        "m_cult_classic": "Classic Story",
        "m_random_pick": "Stop Adventure Standard",
        "m_new_genre_month": "World Rebuilt M New Genre",
        "m_year_completionist": "Miyazaki Art Fulfillment",
        "m_unpopular_opinion": "Unbroken Tide Trial",
        "m_top_rated_reader": "Future Boy Conan Record",
        "m_source_variety": "Night Watch Catalogue",
        "m_low_score_brave": "Miyazaki Art Score",
        "m_short_manga_explorer": "Island Master Compass",
        "m_long_manga_explorer": "Conan's Antics Survey",
        "m_serialization_explorer": "Action Fan Road",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Author Fan Ledger",
        "m_commute_reader": "Island Critic Tenure Tenure",
        "m_four_am_club": "All Night Fellowship",
        "m_new_year_read": "Solar Power Pact",
        "m_all_hours": "Future Sci Accord Accord",
        "m_prime_time_reader": "Lana Rescued Banner",
        "m_workday_reader": "Dawn Patrol Accord Accord",
        "m_sunday_read": "Author Fan Standard Standard",
        "m_morning_routine": "Dawn Patrol Discipline",
        "m_night_shift_reader": "Island Signals Accord Accord",
        "m_seasonal_premier_read": "Night Watch Seasonal",
        "m_clock_collector": "Conan's Will Reserve",
        "m_late_night_horror": "Island Return Mark Mark",
        "m_afternoon_reader": "Survival Gear Mantle Mantle",
        "m_golden_hour_reader": "Island Drama Observance",
        "m_dawn_reader": "Conan Lana Mantle",
        "m_twilight_reader": "Loyal Islander Crown",
        "m_midnight_start": "Lana Rescued Routine",
        "m_weekend_binge_hours": "Original Fan Momentum",
        "m_late_night_regular": "Author Fan Accord",
        "m_sunrise_reader": "War Tech Mantle",
        "m_every_day_of_week": "Night Watch Warrant Warrant",
        "m_monthly_hours": "Wild Strength Vigil",
        "m_bedtime_reader": "Miyazaki Art Warrant Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Miyazaki Art",
        "m_webtoon_reader": "Loyal Islander Mark Mark",
        "m_full_color": "Solar Power Accord",
        "m_doujin_reader": "Classic Story Record Record",
        "m_anthology_reader": "Original Fan Accord",
        "m_adaptation_reader": "Stop Adventure Banner",
        "m_longstrip_reader": "Island Drama Trial",
        "m_4koma_reader": "Endless Tides Ledger",
        "m_oneshot_reader": "Future World Mantle",
        "m_format_variety": "All Night Gallery",
        "m_light_novel_reader": "Future Sci Insignia",
        "m_novel_reader": "Miyazaki Art Crown",
        "m_visual_storyteller": "Survival Gear Testament",
        "m_colored_classic": "Return Visit Survey",
        "m_webcomic_fan": "Perfect Score Insignia",
        "m_manga_to_anime": "Source Adapted",
        "m_seinen_reader": "Hidden Gem Pinnacle",
        "m_josei_reader": "War Tech Pinnacle",
        "m_award_winning_art": "Hidden Island Relic",
        "m_debut_work": "Hidden Island Dominion",
        "m_vertical_scroll": "Conan's Sprint Decree Decree",
        "m_traditional_format": "Future Boy Conan Hoard",
        "m_cross_media": "Island Master Accord",
        "m_spinoff_reader": "World Rebuilt Accord",
        "m_remake_reader": "Remnant Island Pinnacle",
        "m_collaboration_reader": "Perfect Score Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Unbroken Tide",
        "m_weekly_warrior": "Action Fan Season",
        "m_monthly_reader": "Boy Hero Discipline",
        "m_comeback": "Conan's Antics Standard Standard",
        "m_weekend_streak": "War Tech Fever",
        "m_no_zero_days": "Sea Adventure Proof Proof",
        "m_iron_will": "Survivor's Will",
        "m_habit_formed": "Night Rescue Crown Crown",
        "m_consistent_pace": "Daily Watch Scrutiny Scrutiny",
        "m_year_long": "Year Reading",
        "m_double_streak": "Future World Resolve",
        "m_streak_recovery": "Ocean Marathon Resolve",
        "m_daily_minimum": "Conan's Will Focus",
        "m_winter_streak": "Island Drama Observance Observance",
        "m_summer_streak": "Hidden Island Observance",
        "m_morning_streak": "Wild Strength Clock",
        "m_night_streak": "Future Boy Conan Discipline",
        "m_unbreakable": "War Tech Warrant",
        "m_eternal_flame": "Island Alerts Record",
        "m_chapter_a_day": "Author Fan Ledger Ledger",
        "m_genre_streak": "Conan Lana Streak",
        "m_completion_streak": "Stop Adventure Return",
        "m_rating_streak": "Conan Lana Appraisal",
        "m_multi_ch_streak": "Action Fan Tenure",
        "m_author_streak": "Conan's Will Calendar",
        "m_perfect_week_manga": "World Rebuilt Accord Accord",
        "m_diverse_streak": "Giant Lune Streak",

        // ── MANGA SCORING ──
        "m_critic": "Island Critic",
        "m_perfect_ten": "Perfect Score",
        "m_harsh_critic": "Future Sci Scale",
        "m_fair_judge": "Post War Eye Eye",
        "m_generous_spirit": "Original Fan Decree",
        "m_score_all": "Loyal Islander Reckoning",
        "m_wide_range": "Boy Hero Ledger Ledger",
        "m_controversial": "Non Stop Standard Standard",
        "m_consistent_scorer": "Classic Story Grade",
        "m_score_sniper": "Unbroken Tide Reckoning",
        "m_evolving_taste": "Future World Trial Trial",
        "m_bell_curve": "Boy Hero Accord",
        "m_picky_reader": "Giant Lune Ledger",
        "m_100_rated": "Boy Hero Standard",
        "m_500_rated": "Island Signals Aegis",
        "m_mediocre_majority": "Future World Canon",
        "m_rating_spree": "Wild Strength Verdict",
        "m_score_variance": "Miyazaki Art Measure",
        "m_binge_rater": "Conan's Will Passage",
        "m_reread_rerate": "Return Visit Banner Banner",
        "m_masterpiece_hunter": "Non Stop Banner",
        "m_contrarian": "Stop Adventure Aegis",
        "m_optimist": "Island Master Accord Accord",
        "m_score_distributor": "Action Fan Balance",
        "m_genre_critic": "Conan's Will Critic",
        "m_mean_above_8": "Miyazaki Art Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Survival Gear Season",
        "m_valentines_read": "Conan Lana Observance",
        "m_pi_day": "Future World Testament Testament",
        "m_april_fools": "Unbroken Tide Devotion",
        "m_international_manga_day": "Future Sci Aegis",
        "m_free_comic_day": "Original Fan Chronicle",
        "m_summer_solstice": "Conan's Medals Focus Focus",
        "m_tanabata": "Daily Watch Tanabata",
        "m_friday_13th": "Remnant Island Dominion Dominion",
        "m_halloween_read": "Island Return Halloween",
        "m_thanksgiving_binge": "World Rebuilt Charge",
        "m_christmas_read": "Dawn Patrol Pact",
        "m_new_years_eve": "Conan's Medals Pilgrimage",
        "m_birthday_read": "Hidden Gem Focus",
        "m_holiday_marathon": "Classic Fan Rally",
        "m_independence_day": "Stop Adventure Aegis Aegis",
        "m_culture_day": "Island Signals Seal Seal",
        "m_spring_equinox": "Island Return Dominion",
        "m_earth_day": "Hidden Gem Trial",
        "m_labor_day": "Dawn Patrol Seal",
        "m_winter_solstice": "Night Rescue Focus Focus",
        "m_manga_birthday": "Daily Watch Ritual",
        "m_every_holiday_reader": "Ocean Marathon Watch",
        "m_consecutive_holidays": "Remnant Island Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Island Judge Aegis",
        "m_fibonacci": "Island Critic Dominion",
        "m_palindrome_day": "Future World Relic",
        "m_binary_day": "Night Rescue Proof",
        "m_full_moon_read": "War Tech Crown",
        "m_leap_year_read": "Giant Lune Practice",
        "m_triple_seven": "Post War Trial Trial",
        "m_thousand_complete": "Post War Ascension",
        "m_nice": "Conan's Sprint Seal Seal",
        "m_power_level_chapters": "Conan's Antics Aegis",
        "m_answer_42": "War Tech Trial",
        "m_square_number": "Island Alerts Standard",
        "m_prime_count": "Post War Pinnacle",
        "m_matching_date": "Ocean Marathon Mantle",
        "m_century_chapter": "Island Judge Decree",
        "m_pi_chapters": "Hidden Gem Proof Proof",
        "m_synchronicity": "Conan Lana Emblem",
        "m_world_record": "Sea Adventure Warrant",
        "m_genre_clash": "Lana Rescued Clash",
        "m_time_traveler": "Classic Story Decree",
        "m_double_digits": "Night Watch Dominion",
        "m_one_two_three": "Perfect Score Banner Banner",
        "m_lucky_seven": "Future Boy Conan Record Record",
        "m_exact_hundred_ch": "Island Critic Legend",
        "m_year_match_count": "Endless Tides Routine",
        "m_chapter_match_date": "Night Rescue Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Night Watch Index",
        "m_manhwa_format": "Island Return Gallery",
        "m_manhua_format": "Island Drama Storehouse",
        "m_ln_format": "Post War Index",
        "m_oneshot_format": "Future World Index",
        "m_doujin_format": "Wild Strength Cabinet",
        "m_novel_format": "Unbroken Tide Reserve Reserve",
        "m_format_master_manga": "Wild Strength Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Classic Story Link",
        "m_meta_collector": "Island Signals Reliquary",
        "m_meta_category_starter": "All Night Standard",
        "m_meta_tier_climber": "Island Master Token",
        "m_meta_tier_max": "Complete Island",
        "m_meta_xp_earner": "Night Watch Anchor",
        "m_meta_difficulty_easy": "Post War Panel",
        "m_meta_difficulty_hard": "Survival Gear Node",
        "m_meta_unlock_spree": "Night Watch Marker",
        "m_meta_completionist": "Full Library",
        "m_meta_diverse": "Future World Anchor",
        "m_meta_dominator": "Conan's Sprint Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#020e0f",
        primary: "#0a9baa",
        secondary: "#067d8c",
        accent: "#e8a030",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/future-boy-conan.jpg",
    particleColor: "#4ac8d4",
    backgroundDim: 0.3,
    backgroundBlur: 18,
    particleTypes: {
        ocean_waves: { label: "Ocean Waves", maxCount: 10, defaultEnabled: true, defaultIntensity: 55 },
        tropical_leaves: { label: "Tropical Leaves", maxCount: 12, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
  1: "Threadbare Ocean World Spark",
  8: "Conan's Tarnished Omen",
  14: "Fractured Isolated Island",
  21: "Airship Crash Path",
  28: "Lowborn Legacy Vow",
  35: "Industria Shadow Secret",
  41: "Captain's Pursuit Crest",
  48: "Humble Lana Mark",
  55: "Ragged High Harbor Vow",
  61: "Escape's Faint Echo",
  68: "Lesser Conan Meets",
  75: "Friendship Formation Vow",
  81: "Doubtful Power Force",
  88: "Solar Weapon Secret",
  95: "Old's History Flame",
  102: "Really Cool Conan Spark",
  108: "Awakened Industria Exploration Omen",
  115: "Technology's Resolute Seal",
  122: "Rising Lana Importance",
  128: "Escape Attempt Myth",
  135: "Dauntless Society Pulse",
  142: "Dyce Moral Clash",
  149: "Industria's Legacy Mark",
  155: "Fresh Ocean Vow",
  162: "Valiant Ship Escape Echo",
  169: "Lana's Prime Force",
  175: "Polished Conan Physical",
  182: "Industria Resource Bloom",
  189: "Stormlit Legacy Form",
  195: "Nature Restoration Flame",
  202: "Capture's Legacy Spark",
  209: "Tempered Dyce Omen",
  216: "Trusted Industria Collapse Seal",
  222: "Sun's Steadfast Path",
  229: "Ironclad Lana Central",
  236: "Escape Sea Pulse",
  242: "Core Emerges Crest",
  249: "Old Machine Mark",
  256: "Human's Consequences Vow",
  262: "Formidable Survival Force",
  269: "Lucid Industria Internal Clash",
  276: "Lana's Ranked Zenith",
  283: "Fabled Conan Rescue",
  289: "Dyce Redemption Sigil",
  296: "Seasoned Industrialization Clash",
  303: "Pursuit Begins Spark",
  309: "Solar's Threat Omen",
  316: "Valorous Ocean Seal",
  323: "Stalwart Conan Agility Path",
  330: "Lana's Commanding Soul",
  336: "Refined Industria Collapse",
  343: "Machine Overload Crest",
  350: "Blazing Legacy Vow",
  356: "Dyce Choice Vow",
  363: "Humanity's Legacy Echo",
  370: "Peerless Infiltration Crown",
  376: "Ardent Lana Escape Zenith",
  383: "Turning's Focused Bloom",
  390: "Vigilant Solar Weapon",
  397: "Conan Industrial Force",
  403: "Elite Legacy Force",
  410: "Lana Telepathic Omen",
  417: "Industria's Legacy Seal",
  423: "Sovereign Battle Clash",
  430: "Regal Dyce Sacrifice Myth",
  437: "Conan's Crowned Pulse",
  444: "Mythborn Lana Guiding",
  450: "Old Technology Mark",
  457: "Radiant System Vow",
  464: "Nature Reclamation Echo",
  470: "Industria's Legacy Crown",
  477: "Climactic Humanity Zenith",
  484: "Epic Ocean Shift Bloom",
  490: "Escape's Unreal Sigil",
  497: "Peak Solar Tower",
  504: "Conan Forces Force",
  511: "Exalted Extraction Omen",
  517: "Industrial Era Seal",
  524: "Aftermath's World Path",
  531: "Celestial Survivor Myth",
  537: "Phantom Dyce Redemption Pulse",
  544: "Conan's Crimson Vow",
  551: "Silver Nature Restoration",
  557: "New Civilization Vow",
  564: "Feral Ruins Echo",
  571: "Ocean Harmony Crown",
  578: "Humanity's Survival Zenith",
  584: "Dread Peaceful Haven",
  591: "Luminous Lana Integration Sigil",
  598: "Conan's Thunderous Thread",
  604: "Ultraviolet Dyce",
  611: "World Healing Omen",
  618: "Secret Seeds Seal",
  625: "Ocean Ecosystem Path",
  631: "Human's Rise Myth",
  638: "Worldclass Technology Pulse",
  645: "Lawless Legend Conan Crest",
  651: "Industria's Chosen Mark",
  658: "Fearless Lana Psychic",
  665: "Survivor Story Echo",
  671: "Cinematic Civilization Crown",
  678: "Conan Hero Zenith",
  685: "Dyce's Legend Bloom",
  692: "Canonized Ocean Force",
  698: "Ascendant Old Echo",
  705: "Quiet's Transfigured Spark",
  712: "Immortal Dormant Machine",
  718: "Balance Seal",
  725: "Astral Conan Thread",
  732: "Post Apocalyptic Myth",
  739: "Ocean's Legacy Pulse",
  745: "Prismatic Conan Crest",
  752: "Abyssal Silent Earth Brush",
  759: "Dormant's Unbound Vow",
  765: "Eternal Legend Rebuilt",
  772: "Human Survival Crown",
  779: "Transcendent Myth Zenith",
  785: "Lost Civilization Bloom",
  792: "Industrial's Legacy Sigil",
  799: "Ultimate Natural Flame",
  806: "Mythic Humanity Earth Brush",
  812: "Ocean's Godlike Omen",
  819: "Canonical Survival Mastery",
  826: "Conan Human Form",
  832: "Heavenly Presence Myth",
  839: "Dyce Eternal Pulse",
  846: "Closure's Emotional Soul",
  852: "Timeless Acceptance Thread",
  859: "Empyrean Hope Future Brush",
  866: "Ruin's Primordial Echo",
  873: "Omniscient Narrative Renewal",
  879: "Conan Eternal Zenith",
  886: "Apocalyptic Legacy Bloom",
  893: "Resolution Soul",
  899: "Civilization's Truth Secret",
  906: "Final Origin Secret",
  913: "Crowned Technology Omen",
  920: "Human's Mythic Seal",
  926: "Absolute Legend Future",
  933: "Ocean Flow Myth",
  940: "Cosmic Legacy Pulse",
  946: "World Crest",
  953: "Survival's Perfect Mark",
  960: "Definitive Ultimate Brush",
  966: "Ultimate Grew Up Vow",
  973: "Grew's Infinite Vow",
  980: "Sovereign Grew Ruined",
  987: "Grew Up Vow",
  993: "Legendary Earth Vow",
  1000: "Ultimate Ultimate Earth"
}
}
