import { AnimeThemeConfig } from "./types"
import { GiSteamLocomotive, GiPlanetCore, GiGhost, GiCrown, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiStarFormation } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const galaxyExpress999Theme: AnimeThemeConfig = {
    id: "galaxy-express-999",
    displayName: "Galaxy Express 999",
    description: "Board the steam locomotive that crosses the stars — Tetsuro's journey for a mechanical body becomes a philosophical voyage across the galaxy with the mysterious Maetel.",
    fontFamily: "'Cinzel', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "255 240 170",
        "--color-brand-300": "248 222 110",
        "--color-brand-400": "238 198 50",
        "--color-brand-500": "218 172 10",
        "--color-brand-600": "182 140 6",
        "--color-brand-700": "142 108 4",
        "--color-brand-800": "100 76 2",
        "--color-brand-900": "60 44 1",
        "--color-brand-950": "34 24 0",
        "--brand": "218 172 10",
        "--background": "#060408",
        "--paper": "#0e0814",
        "--color-gray-950": "6 4 8",
        "--color-gray-900": "12 8 18",
        "--color-gray-800": "22 16 34",
        "--color-gray-700": "36 28 56",
        "--color-gray-600": "56 44 84",
        "--color-gray-500": "84 68 120",
        "--color-gray-400": "124 106 160",
        "--color-gray-300": "165 148 195",
        "--color-gray-200": "198 186 220",
        "--color-gray-100": "222 215 238",
        "--color-gray-50": "242 238 250",
    },
    sidebarOverrides: {
        "home": { icon: GiSteamLocomotive, label: "Platform 999" },
        "schedule": { icon: GiAlarmClock, label: "Departure Times" },
        "manga": { icon: LuBookOpen, label: "Traveler's Journal" },
        "lists": { icon: GiStarFormation, label: "Star Registry" },
        "discover": { icon: GiBullseye, label: "Galaxy Map" },
        "torrent-list": { icon: GiPlanetCore, label: "Planet Cache" },
        "debrid": { icon: GiGhost, label: "Phantom Stations" },
        "unmatched": { icon: GiCrown, label: "Lost Travelers" },
        "enmasse": { icon: GiResize, label: "Mass Transit" },
        "scan-summaries": { icon: TbReportSearch, label: "Station Reports" },
        "auto-downloader": { icon: LuRss, label: "Express Signals" },
        "community": { icon: GiSteamLocomotive, label: "Fellow Travelers" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Departure Bells" },
        "achievements": { icon: GiTrophy, label: "Journey Medals" },
        "milestones": { icon: LuFlag, label: "Station Goals" },
        "theme-manager": { icon: GiPalette, label: "Train Colors" },
        "extensions": { icon: BiExtension, label: "Ticket Upgrades" },
        "sync": { icon: IoCloudOfflineOutline, label: "Galaxy Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Conductor's Cabin" },
    },
    achievementNames: {
        "a_first_episode": "First Boarding",
        "a_first_complete": "Terminus Reached",
        "a_hundred_club": "Hundred Stations",
        "a_time_lord": "Eternal Passenger",
        "a_anime_collector": "Starfield Collected",
        "a_library_legend": "Galaxy Archives",
        "a_binge_king": "Non-Stop Express",
        "a_no_sleep": "All-Night Journey",
        "a_marathon_runner": "Galaxy Marathon",
        "a_speed_run": "Express Run",
        "a_completionist": "Journey Complete",
        "a_mega_completionist": "Galaxy Master",
        "a_loyal_fan": "Loyal Passenger",
        "a_rewatcher": "Return Journey",
        "a_decade_watcher": "Decade Traveler",
        "a_genre_action": "Star Battle",
        "a_genre_adventure": "Galaxy Explorer",
        "a_genre_comedy": "Conductor's Jokes",
        "a_genre_drama": "Maetel's Secret",
        "a_genre_fantasy": "Machine Empire",
        "a_genre_horror": "Dark Stations",
        "a_genre_romance": "Tetsuro's Heart",
        "a_genre_scifi": "Mechanical Bodies",
        "a_genre_supernatural": "Beyond Mortality",
        "a_genre_psychological": "Identity Question",
        "a_genre_mecha": "Machine Planet",
        "a_critic": "Station Judge",
        "a_perfect_ten": "Perfect Journey",
        "a_harsh_critic": "Strict Conductor",
        "a_daily_streak": "Daily Boarding",
        "a_mega_streak": "Endless Rails",
        "a_year_long": "Year on Rails",
        "a_iron_will": "Iron Rails",
        "a_hidden_gem": "Hidden Station",
        "a_cult_classic": "Galaxy Express Legacy",
        "a_classic_connoisseur": "Matsumoto Classic Fan",
        "a_new_years_resolution": "New Year Ticket",
        "a_christmas_special": "Holiday Express",
        "a_meta_tier_max": "Final Station",
        "a_meta_completionist": "Complete Journey",
        "a_sequel_chain": "Sequel Express",
        "a_zero_to_hero": "Tetsuro's Path",
        "a_night_owl": "Midnight Rails",
        "a_early_bird": "Dawn Departure",
        "m_first_chapter": "First Ticket",
        "m_first_complete": "Volume Station",
        "m_hundred_club": "Hundred Stops",
        "m_binge_king": "Non-Stop Read",
        "m_completionist": "Full Route",
        "m_mega_completionist": "Ultimate Traveler",
        "m_loyal_reader": "Rail Reader",
        "m_rereader": "Return Trip",
        "m_genre_action": "Action Reader",
        "m_genre_adventure": "Galaxy Reader",
        "m_genre_romance": "Star Romance",
        "m_genre_fantasy": "Fantasy World",
        "m_genre_horror": "Dark Read",
        "m_genre_drama": "Drama Express",
        "m_genre_scifi": "Hard Sci-Fi",
        "m_genre_supernatural": "Beyond Reality",
        "m_genre_psychological": "Deep Mind",
        "m_critic": "Manga Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Log",
        "m_mega_streak": "Unbroken Rails",
        "m_year_long": "Year of Pages",
        "m_iron_will": "Iron Dedication",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Classic Manga",
        "m_mangaka_lover": "Matsumoto Fan",
        "m_source_material_fan": "Original Manga",
        "m_meta_tier_max": "Final Chapter",
        "m_meta_completionist": "Complete Library",
        "m_art_appreciator": "Star Art",
        "m_manga_to_anime": "Page to Screen",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060408",
        primary: "#daac0a",
        secondary: "#8c6c04",
        accent: "#7848b0",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/galaxy-express-999.jpg",
    particleColor: "#daac0a",
    backgroundDim: 0.4,
    backgroundBlur: 25,
    particleTypes: {
        stars: { label: "Stars", maxCount: 50, defaultEnabled: true, defaultIntensity: 65 },
        steam: { label: "Steam Clouds", maxCount: 10, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
    "7": "Novice Rank 1",
    "13": "Novice Level 2",
    "20": "Novice Tier 3",
    "27": "Novice Class 4",
    "33": "Novice Grade 5",
    "40": "Novice Position 6",
    "47": "Novice Status 7",
    "53": "Novice Role 8",
    "60": "Novice Title 9",
    "67": "Novice Authority 10",
    "73": "Beginner Rank 11",
    "80": "Beginner Level 12",
    "87": "Beginner Tier 13",
    "93": "Beginner Class 14",
    "100": "Beginner Grade 15",
    "107": "Beginner Position 16",
    "113": "Beginner Status 17",
    "120": "Beginner Role 18",
    "127": "Beginner Title 19",
    "133": "Student Authority 20",
    "140": "Student Rank 21",
    "147": "Student Level 22",
    "153": "Student Tier 23",
    "160": "Student Class 24",
    "167": "Student Grade 25",
    "173": "Student Position 26",
    "180": "Student Status 27",
    "187": "Student Role 28",
    "193": "Student Title 29",
    "200": "Learner Authority 30",
    "207": "Learner Rank 31",
    "213": "Learner Level 32",
    "220": "Learner Tier 33",
    "227": "Learner Class 34",
    "233": "Learner Grade 35",
    "240": "Learner Position 36",
    "247": "Learner Status 37",
    "253": "Learner Role 38",
    "260": "Adept Title 39",
    "267": "Adept Authority 40",
    "273": "Adept Rank 41",
    "280": "Adept Level 42",
    "287": "Adept Tier 43",
    "293": "Adept Class 44",
    "300": "Adept Grade 45",
    "307": "Adept Position 46",
    "313": "Adept Status 47",
    "320": "Expert Role 48",
    "327": "Expert Title 49",
    "333": "Expert Authority 50",
    "340": "Expert Rank 51",
    "347": "Expert Level 52",
    "353": "Expert Tier 53",
    "360": "Expert Class 54",
    "367": "Expert Grade 55",
    "373": "Expert Position 56",
    "380": "Expert Status 57",
    "387": "Master Role 58",
    "393": "Master Title 59",
    "400": "Master Authority 60",
    "407": "Master Rank 61",
    "413": "Master Level 62",
    "420": "Master Tier 63",
    "427": "Master Class 64",
    "433": "Master Grade 65",
    "440": "Master Position 66",
    "447": "Grandmaster Status 67",
    "453": "Grandmaster Role 68",
    "460": "Grandmaster Title 69",
    "467": "Grandmaster Authority 70",
    "473": "Grandmaster Rank 71",
    "480": "Grandmaster Level 72",
    "487": "Grandmaster Tier 73",
    "493": "Grandmaster Class 74",
    "500": "Grandmaster Grade 75",
    "507": "Sage Position 76",
    "513": "Sage Status 77",
    "520": "Sage Role 78",
    "527": "Sage Title 79",
    "533": "Sage Authority 80",
    "540": "Sage Rank 81",
    "547": "Sage Level 82",
    "553": "Sage Tier 83",
    "560": "Sage Class 84",
    "567": "Sage Grade 85",
    "573": "Legend Position 86",
    "580": "Legend Status 87",
    "587": "Legend Role 88",
    "593": "Legend Title 89",
    "600": "Legend Authority 90",
    "607": "Legend Rank 91",
    "613": "Legend Level 92",
    "620": "Legend Tier 93",
    "627": "Legend Class 94",
    "633": "Mythical Grade 95",
    "640": "Mythical Position 96",
    "647": "Mythical Status 97",
    "653": "Mythical Role 98",
    "660": "Mythical Title 99",
    "667": "Mythical Authority 100",
    "673": "Mythical Rank 101",
    "680": "Mythical Level 102",
    "687": "Mythical Tier 103",
    "693": "Mythical Class 104",
    "700": "Godly Grade 105",
    "707": "Godly Position 106",
    "713": "Godly Status 107",
    "720": "Godly Role 108",
    "727": "Godly Title 109",
    "733": "Godly Authority 110",
    "740": "Godly Rank 111",
    "747": "Godly Level 112",
    "753": "Godly Tier 113",
    "760": "Supreme Class 114",
    "767": "Supreme Grade 115",
    "773": "Supreme Position 116",
    "780": "Supreme Status 117",
    "787": "Supreme Role 118",
    "793": "Supreme Title 119",
    "800": "Supreme Authority 120",
    "807": "Supreme Rank 121",
    "813": "Supreme Level 122",
    "820": "Infinite Tier 123",
    "827": "Infinite Class 124",
    "833": "Infinite Grade 125",
    "840": "Infinite Position 126",
    "847": "Infinite Status 127",
    "853": "Infinite Role 128",
    "860": "Infinite Title 129",
    "867": "Infinite Authority 130",
    "873": "Infinite Rank 131",
    "880": "Infinite Level 132",
    "887": "Eternal Tier 133",
    "893": "Eternal Class 134",
    "900": "Eternal Grade 135",
    "907": "Eternal Position 136",
    "913": "Eternal Status 137",
    "920": "Eternal Role 138",
    "927": "Eternal Title 139",
    "933": "Eternal Authority 140",
    "940": "Eternal Rank 141",
    "947": "Transcendent Level 142",
    "953": "Transcendent Tier 143",
    "960": "Transcendent Class 144",
    "967": "Transcendent Grade 145",
    "973": "Transcendent Position 146",
    "980": "Transcendent Status 147",
    "987": "Transcendent Role 148",
    "993": "Transcendent Title 149",
    "1000": "Transcendent Authority 150"
},
}
