import { AnimeThemeConfig } from "./types"
import { GiGoldBar, GiHeartKey, GiMoon, GiFlowerEmblem, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiRose } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const goldenTimeTheme: AnimeThemeConfig = {
    id: "golden-time",
    displayName: "Golden Time",
    description: "Law student Banri Tada suffers from amnesia after an accident, and in college he meets the vivacious Kouko Kaga — their college romance unfolds as Banri struggles between his past self and the new life he is building.",
    fontFamily: "'Raleway', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,400;0,700;1,400&display=swap",
    cssVars: {
        "--color-brand-200": "245 220 165",
        "--color-brand-300": "232 198 118",
        "--color-brand-400": "215 172 68",
        "--color-brand-500": "192 145 25",
        "--color-brand-600": "158 115 5",
        "--color-brand-700": "118 84 1",
        "--color-brand-800": "78 54 0",
        "--color-brand-900": "40 26 0",
        "--color-brand-950": "18 10 0",
        "--brand": "192 145 25",
        "--background": "#060400",
        "--paper": "#0e0900",
        "--color-gray-950": "6 4 0",
        "--color-gray-900": "12 8 1",
        "--color-gray-800": "22 16 4",
        "--color-gray-700": "36 28 10",
        "--color-gray-600": "58 45 20",
        "--color-gray-500": "90 72 38",
        "--color-gray-400": "130 108 68",
        "--color-gray-300": "172 150 108",
        "--color-gray-200": "205 188 148",
        "--color-gray-100": "228 215 182",
        "--color-gray-50": "245 235 215",
    },
    sidebarOverrides: {
        "home": { icon: GiGoldBar, label: "College Life" },
        "schedule": { icon: GiAlarmClock, label: "Class Schedule" },
        "manga": { icon: LuBookOpen, label: "Love Notes" },
        "lists": { icon: GiRose, label: "Romance List" },
        "discover": { icon: GiBullseye, label: "New Friendships" },
        "torrent-list": { icon: GiHeartKey, label: "Memory Cache" },
        "debrid": { icon: GiFlowerEmblem, label: "Golden Store" },
        "unmatched": { icon: GiMoon, label: "Lost Memories" },
        "enmasse": { icon: GiResize, label: "College Events" },
        "scan-summaries": { icon: TbReportSearch, label: "Memory Reports" },
        "auto-downloader": { icon: LuRss, label: "Romance Feed" },
        "community": { icon: GiGoldBar, label: "Festival Club" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Romance Alerts" },
        "achievements": { icon: GiTrophy, label: "Golden Trophies" },
        "milestones": { icon: LuFlag, label: "Memory Goals" },
        "theme-manager": { icon: GiPalette, label: "Amber Colors" },
        "extensions": { icon: BiExtension, label: "Memory Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Golden Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Banri's Settings" },
    },
    achievementNames: {
        "a_first_episode": "First Day",
        "a_first_complete": "Golden Memories",
        "a_hundred_club": "Hundred Episodes",
        "a_time_lord": "College Veteran",
        "a_anime_collector": "Memory Collection",
        "a_library_legend": "Golden Archives",
        "a_binge_king": "Romance Marathon",
        "a_no_sleep": "All-Night Feelings",
        "a_marathon_runner": "Banri's Walk",
        "a_speed_run": "Kouko's Dash",
        "a_completionist": "All Episodes",
        "a_mega_completionist": "Yuyuko Master",
        "a_loyal_fan": "Kouko's Partner",
        "a_rewatcher": "College Return",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "None Here",
        "a_genre_adventure": "College Journey",
        "a_genre_comedy": "Kouko's Antics",
        "a_genre_drama": "Ghost Banri",
        "a_genre_fantasy": "Ghost World",
        "a_genre_horror": "Memory Loss",
        "a_genre_romance": "Banri Kouko",
        "a_genre_scifi": "None Here",
        "a_genre_supernatural": "Ghost Self",
        "a_genre_psychological": "Two Selves",
        "a_genre_mecha": "None Here",
        "a_critic": "Romance Critic",
        "a_perfect_ten": "Perfect Romance",
        "a_harsh_critic": "Linda Standard",
        "a_daily_streak": "Daily Romance",
        "a_mega_streak": "Endless Romance",
        "a_year_long": "Year of College",
        "a_iron_will": "Banri's Will",
        "a_hidden_gem": "Hidden Episode",
        "a_cult_classic": "Yuyuko Classic",
        "a_classic_connoisseur": "2013 Fan",
        "a_new_years_resolution": "New Year Festival",
        "a_christmas_special": "Winter Romance",
        "a_meta_tier_max": "Golden Legend",
        "a_meta_completionist": "All Moments",
        "a_sequel_chain": "Manga Complete",
        "a_zero_to_hero": "Forgotten to Found",
        "a_night_owl": "Night Romance",
        "a_early_bird": "Morning Class",
        "m_first_chapter": "First Page",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Romance Marathon",
        "m_completionist": "Full Novel",
        "m_mega_completionist": "Golden Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Golden Return",
        "m_genre_action": "None Here",
        "m_genre_adventure": "College Chapter",
        "m_genre_romance": "Love Chapter",
        "m_genre_fantasy": "Ghost Chapter",
        "m_genre_horror": "Memory Chapter",
        "m_genre_drama": "Heart Chapter",
        "m_genre_scifi": "Unusual Chapter",
        "m_genre_supernatural": "Ghost Banri",
        "m_genre_psychological": "Self Depth",
        "m_critic": "Romance Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Golden Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Amnesiac Resolve",
        "m_hidden_gem": "Hidden Chapter",
        "m_cult_classic": "Yuyuko Classic",
        "m_mangaka_lover": "Yuyuko Fan",
        "m_source_material_fan": "Novel First",
        "m_meta_tier_max": "Golden Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Yuyuko Art",
        "m_manga_to_anime": "Novel Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060400",
        primary: "#c09119",
        secondary: "#9e7305",
        accent: "#d06880",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/golden-time.jpg",
    particleColor: "#d4a820",
    backgroundDim: 0.30,
    backgroundBlur: 14,
    particleTypes: {
        golden_leaves: { label: "Golden Leaves", maxCount: 18, defaultEnabled: true, defaultIntensity: 55 },
        memory_shards: { label: "Memory Shards", maxCount: 10, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
    "7": "Novice Rank 1",
    "13": "Novice Level 2",
    "20": "Novice Tier 3",
    "27": "Novice Class 4",
    "33": "Novice Grade 5",
    "40": "Novice Position 6",
    "47": "Novice Status 7",
    "53": "Novice Role 8",
    "60": "Novice Title 9",
    "67": "Novice Authority 10",
    "73": "Beginner Rank 11",
    "80": "Beginner Level 12",
    "87": "Beginner Tier 13",
    "93": "Beginner Class 14",
    "100": "Beginner Grade 15",
    "107": "Beginner Position 16",
    "113": "Beginner Status 17",
    "120": "Beginner Role 18",
    "127": "Beginner Title 19",
    "133": "Student Authority 20",
    "140": "Student Rank 21",
    "147": "Student Level 22",
    "153": "Student Tier 23",
    "160": "Student Class 24",
    "167": "Student Grade 25",
    "173": "Student Position 26",
    "180": "Student Status 27",
    "187": "Student Role 28",
    "193": "Student Title 29",
    "200": "Learner Authority 30",
    "207": "Learner Rank 31",
    "213": "Learner Level 32",
    "220": "Learner Tier 33",
    "227": "Learner Class 34",
    "233": "Learner Grade 35",
    "240": "Learner Position 36",
    "247": "Learner Status 37",
    "253": "Learner Role 38",
    "260": "Adept Title 39",
    "267": "Adept Authority 40",
    "273": "Adept Rank 41",
    "280": "Adept Level 42",
    "287": "Adept Tier 43",
    "293": "Adept Class 44",
    "300": "Adept Grade 45",
    "307": "Adept Position 46",
    "313": "Adept Status 47",
    "320": "Expert Role 48",
    "327": "Expert Title 49",
    "333": "Expert Authority 50",
    "340": "Expert Rank 51",
    "347": "Expert Level 52",
    "353": "Expert Tier 53",
    "360": "Expert Class 54",
    "367": "Expert Grade 55",
    "373": "Expert Position 56",
    "380": "Expert Status 57",
    "387": "Master Role 58",
    "393": "Master Title 59",
    "400": "Master Authority 60",
    "407": "Master Rank 61",
    "413": "Master Level 62",
    "420": "Master Tier 63",
    "427": "Master Class 64",
    "433": "Master Grade 65",
    "440": "Master Position 66",
    "447": "Grandmaster Status 67",
    "453": "Grandmaster Role 68",
    "460": "Grandmaster Title 69",
    "467": "Grandmaster Authority 70",
    "473": "Grandmaster Rank 71",
    "480": "Grandmaster Level 72",
    "487": "Grandmaster Tier 73",
    "493": "Grandmaster Class 74",
    "500": "Grandmaster Grade 75",
    "507": "Sage Position 76",
    "513": "Sage Status 77",
    "520": "Sage Role 78",
    "527": "Sage Title 79",
    "533": "Sage Authority 80",
    "540": "Sage Rank 81",
    "547": "Sage Level 82",
    "553": "Sage Tier 83",
    "560": "Sage Class 84",
    "567": "Sage Grade 85",
    "573": "Legend Position 86",
    "580": "Legend Status 87",
    "587": "Legend Role 88",
    "593": "Legend Title 89",
    "600": "Legend Authority 90",
    "607": "Legend Rank 91",
    "613": "Legend Level 92",
    "620": "Legend Tier 93",
    "627": "Legend Class 94",
    "633": "Mythical Grade 95",
    "640": "Mythical Position 96",
    "647": "Mythical Status 97",
    "653": "Mythical Role 98",
    "660": "Mythical Title 99",
    "667": "Mythical Authority 100",
    "673": "Mythical Rank 101",
    "680": "Mythical Level 102",
    "687": "Mythical Tier 103",
    "693": "Mythical Class 104",
    "700": "Godly Grade 105",
    "707": "Godly Position 106",
    "713": "Godly Status 107",
    "720": "Godly Role 108",
    "727": "Godly Title 109",
    "733": "Godly Authority 110",
    "740": "Godly Rank 111",
    "747": "Godly Level 112",
    "753": "Godly Tier 113",
    "760": "Supreme Class 114",
    "767": "Supreme Grade 115",
    "773": "Supreme Position 116",
    "780": "Supreme Status 117",
    "787": "Supreme Role 118",
    "793": "Supreme Title 119",
    "800": "Supreme Authority 120",
    "807": "Supreme Rank 121",
    "813": "Supreme Level 122",
    "820": "Infinite Tier 123",
    "827": "Infinite Class 124",
    "833": "Infinite Grade 125",
    "840": "Infinite Position 126",
    "847": "Infinite Status 127",
    "853": "Infinite Role 128",
    "860": "Infinite Title 129",
    "867": "Infinite Authority 130",
    "873": "Infinite Rank 131",
    "880": "Infinite Level 132",
    "887": "Eternal Tier 133",
    "893": "Eternal Class 134",
    "900": "Eternal Grade 135",
    "907": "Eternal Position 136",
    "913": "Eternal Status 137",
    "920": "Eternal Role 138",
    "927": "Eternal Title 139",
    "933": "Eternal Authority 140",
    "940": "Eternal Rank 141",
    "947": "Transcendent Level 142",
    "953": "Transcendent Tier 143",
    "960": "Transcendent Class 144",
    "967": "Transcendent Grade 145",
    "973": "Transcendent Position 146",
    "980": "Transcendent Status 147",
    "987": "Transcendent Role 148",
    "993": "Transcendent Title 149",
    "1000": "Transcendent Authority 150"
},
}
