import { AnimeThemeConfig } from "./types"
import { GiDevilMask, GiCrown, GiSpellBook, GiLaurelCrown, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiMagicSwirl, GiHeartKey, GiCastle } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const greatestDemonLordTheme: AnimeThemeConfig = {
    id: "greatest-demon-lord",
    displayName: "The Greatest Demon Lord is Reborn as a Typical Nobody",
    description: "Varvatos, the greatest Demon Lord in history, chooses to reincarnate as an ordinary person to experience friendship and connection. But his godlike power still leaks out, making a normal school life completely impossible.",
    fontFamily: "'Cinzel', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "215 180 255",
        "--color-brand-300": "175 130 248",
        "--color-brand-400": "138 86 230",
        "--color-brand-500": "104 50 205",
        "--color-brand-600": "74 24 170",
        "--color-brand-700": "50 8 132",
        "--color-brand-800": "30 0 90",
        "--color-brand-900": "14 0 50",
        "--color-brand-950": "5 0 22",
        "--brand": "104 50 205",
        "--background": "#030004",
        "--paper": "#0a000e",
        "--color-gray-950": "3 0 4",
        "--color-gray-900": "8 2 12",
        "--color-gray-800": "18 6 24",
        "--color-gray-700": "32 12 42",
        "--color-gray-600": "52 22 68",
        "--color-gray-500": "84 42 108",
        "--color-gray-400": "126 74 155",
        "--color-gray-300": "168 114 200",
        "--color-gray-200": "206 158 232",
        "--color-gray-100": "230 198 248",
        "--color-gray-50": "248 232 255",
    },
    sidebarOverrides: {
        "home": { icon: GiDevilMask, label: "Demon Lord's Domain" },
        "schedule": { icon: GiAlarmClock, label: "School Schedule" },
        "manga": { icon: LuBookOpen, label: "Ancient Tomes" },
        "lists": { icon: GiFlowerEmblem, label: "Follower Registry" },
        "discover": { icon: GiBullseye, label: "New Challenges" },
        "torrent-list": { icon: GiSpellBook, label: "Spell Cache" },
        "debrid": { icon: GiCastle, label: "Ancient Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Followers" },
        "enmasse": { icon: GiResize, label: "Demon Army" },
        "scan-summaries": { icon: TbReportSearch, label: "Demon Reports" },
        "auto-downloader": { icon: LuRss, label: "Ancient Intel" },
        "community": { icon: GiMagicSwirl, label: "Follower Circle" },
        "achievements": { icon: GiTrophy, label: "Demon Trophies" },
        "milestones": { icon: LuFlag, label: "Demon Milestones" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Demon Alerts" },
        "theme-manager": { icon: GiPalette, label: "Ancient Palette" },
        "extensions": { icon: BiExtension, label: "Demon Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Demon Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Ard's Config" },
    },
    achievementNames: {
        "a_first_episode": "Reincarnated",
        "a_first_complete": "School Survived",
        "a_hundred_club": "Hundred Powers",
        "a_time_lord": "Legendary Elder",
        "a_anime_collector": "Demon Archive",
        "a_library_legend": "Ancient Library",
        "a_binge_king": "Power Marathon",
        "a_no_sleep": "All-Night Study",
        "a_marathon_runner": "Ard's Run",
        "a_speed_run": "Ancient Speed",
        "a_completionist": "Full Power",
        "a_mega_completionist": "True Demon Lord",
        "a_loyal_fan": "Loyal Follower",
        "a_rewatcher": "Replay Life",
        "a_decade_watcher": "Decade Ancient",
        "a_genre_action": "Power Battle",
        "a_genre_adventure": "School Journey",
        "a_genre_comedy": "Average Comedy",
        "a_genre_drama": "Demon Drama",
        "a_genre_fantasy": "Demon World",
        "a_genre_horror": "None Here",
        "a_genre_romance": "Ard's Love",
        "a_genre_scifi": "None Here",
        "a_genre_supernatural": "Ancient Power",
        "a_genre_psychological": "Ard's Mind",
        "a_genre_mecha": "None Here",
        "a_critic": "Power Critic",
        "a_perfect_ten": "Perfect Power",
        "a_harsh_critic": "Demon Standard",
        "a_daily_streak": "Daily Study",
        "a_mega_streak": "Ancient Streak",
        "a_year_long": "Year of Power",
        "a_iron_will": "Unyielding Power",
        "a_hidden_gem": "Hidden Power",
        "a_cult_classic": "Demon Classic",
        "a_classic_connoisseur": "2021 Fan",
        "a_new_years_resolution": "New Year Power",
        "a_christmas_special": "Winter Demon",
        "a_meta_tier_max": "Ancient Legend",
        "a_meta_completionist": "All Powers",
        "a_sequel_chain": "Demon Chain",
        "a_zero_to_hero": "Average to Legend",
        "a_night_owl": "Night Study",
        "a_early_bird": "Dawn Power",
        "m_first_chapter": "First Reincarnation",
        "m_first_complete": "Arc Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Demon Binge",
        "m_completionist": "Full Novel",
        "m_mega_completionist": "Demon Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Second Life",
        "m_genre_action": "Power Chapter",
        "m_genre_adventure": "School Chapter",
        "m_genre_romance": "Love Chapter",
        "m_genre_fantasy": "Ancient Chapter",
        "m_genre_horror": "None Here",
        "m_genre_drama": "Drama Chapter",
        "m_genre_scifi": "None Here",
        "m_genre_supernatural": "Ancient Power",
        "m_genre_psychological": "Mind Chapter",
        "m_critic": "Demon Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Ancient Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Iron Demon",
        "m_hidden_gem": "Hidden Chapter",
        "m_cult_classic": "Classic Chapter",
        "m_mangaka_lover": "Tsukishima Fan",
        "m_source_material_fan": "Novel First",
        "m_meta_tier_max": "Demon Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Ancient Art",
        "m_manga_to_anime": "Adapted Demon",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#030004",
        primary: "#6832cd",
        secondary: "#4a18aa",
        accent: "#d0a820",
    },
    particleColor: "#9050d8",
    backgroundDim: 0.32,
    backgroundBlur: 20,
    particleTypes: {
        purple_sparks: { label: "Ancient Power", maxCount: 14, defaultEnabled: true, defaultIntensity: 50 },
        golden_sparks: { label: "Golden Aura", maxCount: 10, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
    "7": "Novice Rank 1",
    "13": "Novice Level 2",
    "20": "Novice Tier 3",
    "27": "Novice Class 4",
    "33": "Novice Grade 5",
    "40": "Novice Position 6",
    "47": "Novice Status 7",
    "53": "Novice Role 8",
    "60": "Novice Title 9",
    "67": "Novice Authority 10",
    "73": "Beginner Rank 11",
    "80": "Beginner Level 12",
    "87": "Beginner Tier 13",
    "93": "Beginner Class 14",
    "100": "Beginner Grade 15",
    "107": "Beginner Position 16",
    "113": "Beginner Status 17",
    "120": "Beginner Role 18",
    "127": "Beginner Title 19",
    "133": "Student Authority 20",
    "140": "Student Rank 21",
    "147": "Student Level 22",
    "153": "Student Tier 23",
    "160": "Student Class 24",
    "167": "Student Grade 25",
    "173": "Student Position 26",
    "180": "Student Status 27",
    "187": "Student Role 28",
    "193": "Student Title 29",
    "200": "Learner Authority 30",
    "207": "Learner Rank 31",
    "213": "Learner Level 32",
    "220": "Learner Tier 33",
    "227": "Learner Class 34",
    "233": "Learner Grade 35",
    "240": "Learner Position 36",
    "247": "Learner Status 37",
    "253": "Learner Role 38",
    "260": "Adept Title 39",
    "267": "Adept Authority 40",
    "273": "Adept Rank 41",
    "280": "Adept Level 42",
    "287": "Adept Tier 43",
    "293": "Adept Class 44",
    "300": "Adept Grade 45",
    "307": "Adept Position 46",
    "313": "Adept Status 47",
    "320": "Expert Role 48",
    "327": "Expert Title 49",
    "333": "Expert Authority 50",
    "340": "Expert Rank 51",
    "347": "Expert Level 52",
    "353": "Expert Tier 53",
    "360": "Expert Class 54",
    "367": "Expert Grade 55",
    "373": "Expert Position 56",
    "380": "Expert Status 57",
    "387": "Master Role 58",
    "393": "Master Title 59",
    "400": "Master Authority 60",
    "407": "Master Rank 61",
    "413": "Master Level 62",
    "420": "Master Tier 63",
    "427": "Master Class 64",
    "433": "Master Grade 65",
    "440": "Master Position 66",
    "447": "Grandmaster Status 67",
    "453": "Grandmaster Role 68",
    "460": "Grandmaster Title 69",
    "467": "Grandmaster Authority 70",
    "473": "Grandmaster Rank 71",
    "480": "Grandmaster Level 72",
    "487": "Grandmaster Tier 73",
    "493": "Grandmaster Class 74",
    "500": "Grandmaster Grade 75",
    "507": "Sage Position 76",
    "513": "Sage Status 77",
    "520": "Sage Role 78",
    "527": "Sage Title 79",
    "533": "Sage Authority 80",
    "540": "Sage Rank 81",
    "547": "Sage Level 82",
    "553": "Sage Tier 83",
    "560": "Sage Class 84",
    "567": "Sage Grade 85",
    "573": "Legend Position 86",
    "580": "Legend Status 87",
    "587": "Legend Role 88",
    "593": "Legend Title 89",
    "600": "Legend Authority 90",
    "607": "Legend Rank 91",
    "613": "Legend Level 92",
    "620": "Legend Tier 93",
    "627": "Legend Class 94",
    "633": "Mythical Grade 95",
    "640": "Mythical Position 96",
    "647": "Mythical Status 97",
    "653": "Mythical Role 98",
    "660": "Mythical Title 99",
    "667": "Mythical Authority 100",
    "673": "Mythical Rank 101",
    "680": "Mythical Level 102",
    "687": "Mythical Tier 103",
    "693": "Mythical Class 104",
    "700": "Godly Grade 105",
    "707": "Godly Position 106",
    "713": "Godly Status 107",
    "720": "Godly Role 108",
    "727": "Godly Title 109",
    "733": "Godly Authority 110",
    "740": "Godly Rank 111",
    "747": "Godly Level 112",
    "753": "Godly Tier 113",
    "760": "Supreme Class 114",
    "767": "Supreme Grade 115",
    "773": "Supreme Position 116",
    "780": "Supreme Status 117",
    "787": "Supreme Role 118",
    "793": "Supreme Title 119",
    "800": "Supreme Authority 120",
    "807": "Supreme Rank 121",
    "813": "Supreme Level 122",
    "820": "Infinite Tier 123",
    "827": "Infinite Class 124",
    "833": "Infinite Grade 125",
    "840": "Infinite Position 126",
    "847": "Infinite Status 127",
    "853": "Infinite Role 128",
    "860": "Infinite Title 129",
    "867": "Infinite Authority 130",
    "873": "Infinite Rank 131",
    "880": "Infinite Level 132",
    "887": "Eternal Tier 133",
    "893": "Eternal Class 134",
    "900": "Eternal Grade 135",
    "907": "Eternal Position 136",
    "913": "Eternal Status 137",
    "920": "Eternal Role 138",
    "927": "Eternal Title 139",
    "933": "Eternal Authority 140",
    "940": "Eternal Rank 141",
    "947": "Transcendent Level 142",
    "953": "Transcendent Tier 143",
    "960": "Transcendent Class 144",
    "967": "Transcendent Grade 145",
    "973": "Transcendent Position 146",
    "980": "Transcendent Status 147",
    "987": "Transcendent Role 148",
    "993": "Transcendent Title 149",
    "1000": "Transcendent Authority 150"
},
}
