import { AnimeThemeConfig } from "./types"
import { GiMusicalNotes, GiTrumpet, GiTuba, GiFlute, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const hibikeEuphoniumTheme: AnimeThemeConfig = {
    id: "hibike-euphonium",
    displayName: "Sound! Euphonium",
    description: "First-year student Kumiko Oumae reluctantly joins her high school concert band after an awkward middle school incident, but as the demanding conductor pushes the ensemble toward nationals, she rediscovers her passion for music.",
    fontFamily: "'Noto Serif JP', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "215 195 255",
        "--color-brand-300": "185 155 248",
        "--color-brand-400": "152 112 235",
        "--color-brand-500": "118 68 215",
        "--color-brand-600": "88 38 178",
        "--color-brand-700": "60 16 138",
        "--color-brand-800": "36 4 92",
        "--color-brand-900": "16 0 46",
        "--color-brand-950": "6 0 20",
        "--brand": "118 68 215",
        "--background": "#030005",
        "--paper": "#08000e",
        "--color-gray-950": "3 0 5",
        "--color-gray-900": "8 1 12",
        "--color-gray-800": "16 3 22",
        "--color-gray-700": "28 7 38",
        "--color-gray-600": "46 14 62",
        "--color-gray-500": "75 28 100",
        "--color-gray-400": "112 55 150",
        "--color-gray-300": "155 95 195",
        "--color-gray-200": "195 145 230",
        "--color-gray-100": "220 185 245",
        "--color-gray-50": "240 220 255",
    },
    sidebarOverrides: {
        "home": { icon: GiTuba, label: "Kitauji Band" },
        "schedule": { icon: GiAlarmClock, label: "Practice Schedule" },
        "manga": { icon: LuBookOpen, label: "Score Library" },
        "lists": { icon: GiMusicalNotes, label: "Setlist" },
        "discover": { icon: GiBullseye, label: "Nationals" },
        "torrent-list": { icon: GiTrumpet, label: "Instrument Cache" },
        "debrid": { icon: GiFlute, label: "Music Store" },
        "unmatched": { icon: GiMusicalNotes, label: "Missed Notes" },
        "enmasse": { icon: GiResize, label: "Competitions" },
        "scan-summaries": { icon: TbReportSearch, label: "Practice Reports" },
        "auto-downloader": { icon: LuRss, label: "Band Feed" },
        "community": { icon: GiTuba, label: "Concert Band" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Practice Alerts" },
        "achievements": { icon: GiTrophy, label: "Band Trophies" },
        "milestones": { icon: LuFlag, label: "Band Goals" },
        "theme-manager": { icon: GiPalette, label: "Brass Colors" },
        "extensions": { icon: BiExtension, label: "Music Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Kitauji Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Kumiko's Settings" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Practice",
        "a_episode_counter": "Sound Euphonium Mark",
        "a_episode_titan": "Honest Depth Relic",
        "a_hours_invested": "Gold Prize Winner Proof",
        "a_time_lord": "Band Veteran",
        "a_anime_collector": "Score Collection",
        "a_library_legend": "Kitauji Archives",
        "a_first_complete": "Nationals Reached",
        "a_hundred_club": "Hundred Pieces",
        "a_first_day": "Missed Notes Seal",
        "a_first_rating": "Honest Depth Appraisal",
        "a_ten_thousand_min": "Daily Practice Standard",
        "a_season_veteran": "Daily Practice Library",
        "a_year_explorer": "Score Library Map",
        "a_century_watcher": "Long Practice Ledger",
        "a_five_hundred_eps": "Kitauji Band Dominion",
        "a_thousand_eps": "Winter Concert Record",
        "a_watching_ten": "Kumiko Reina Bond Acclaim",
        "a_ptw_hoarder": "Kitauji Archives Library",
        "a_dropped_honesty": "Kumiko Reina Bond Summit",
        "a_five_thousand_eps": "Takeda Master Warrant",
        "a_ten_completed": "Kumiko Oumae Afterglow",
        "a_fifty_completed": "Night Practice Ascension",
        "a_five_hundred_completed": "Kumiko Reina Bond Clear",
        "a_mean_score_tracker": "Practice Alerts Verdict",
        "a_unique_studios": "Winter Concert Collection",
        "a_days_spent_watching": "Score Collection Dominion",
        "a_all_status": "Night Rehearsal Testament",
        "a_first_favorite": "Reina Bond Cabinet",
        "a_favorites_collector": "Reina's Solo Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Concert Band Drive",
        "a_marathon_runner": "Long Practice",
        "a_weekend_warrior": "Honest Depth Ordeal",
        "a_non_stop": "Kumiko's Partner Fever",
        "a_one_more_episode": "Band Trophies Mantle",
        "a_speed_run": "Reina's Solo",
        "a_double_feature": "Kyoani Art Crown",
        "a_triple_threat": "Novel Adapted Record",
        "a_five_a_day": "Takeda Fan Accord",
        "a_back_to_back": "Morning Scales Surge",
        "a_seasonal_binge": "Honest Depth Cascade",
        "a_cour_crusher": "Score Collection Ordeal",
        "a_half_day_watch": "Sound Euphonium Crown",
        "a_full_day_watch": "Music Dream Pinnacle",
        "a_power_weekend": "Missed Notes Run",
        "a_binge_king": "Practice Marathon",
        "a_no_sleep": "All-Night Rehearsal",
        "a_entire_season": "Hidden Solo Library",
        "a_seven_day_challenge": "Music Dream Mark",
        "a_hundred_day_binge": "Missed Notes Surge",
        "a_genre_binge": "Reina's Ambition Binge",
        "a_studio_binge": "Sound Euphonium Fever",
        "a_season_sweep": "Audition Tension Codex",
        "a_forty_eight_hour": "Music Magic Overture",
        "a_ep_counter_day": "Kumiko Oumae Aegis",
        "a_multi_series_binge": "Kitauji Archives Streak",
        "a_midnight_binge": "Band Trophies Cascade",
        "a_new_year_binge": "Taki Sensei Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "None Here",
        "a_genre_adventure": "Nationals Journey",
        "a_genre_comedy": "Hazuki Moments",
        "a_genre_drama": "Reina's Ambition",
        "a_genre_fantasy": "Music Dream",
        "a_genre_horror": "Audition Tension",
        "a_genre_mystery": "Sensei Standard Mystery",
        "a_genre_romance": "Kumiko Reina Bond",
        "a_genre_scifi": "None Here",
        "a_genre_sol": "Takeda Master Slice",
        "a_genre_sports": "Music Magic Sports",
        "a_genre_supernatural": "Music Magic",
        "a_genre_thriller": "Night Practice Thriller",
        "a_genre_mecha": "None Here",
        "a_genre_music": "Daily Practice Music",
        "a_genre_psychological": "Kumiko's Honesty",
        "a_genre_ecchi": "Concert Band Ecchi",
        "a_genre_mahou_shoujo": "Novel Adapted Magic Shoujo",
        "a_tag_isekai": "Taki Sensei Standard Isekai",
        "a_tag_harem": "Blue Bird Harem",
        "a_tag_bl": "Music Magic Bl",
        "a_tag_gl": "Band Trophies Gl",
        "a_tag_historical": "Liz Blue Historical",
        "a_tag_military": "Kitauji Band Military",
        "a_tag_school": "Kitauji Archives School",
        "a_tag_martial_arts": "Music Dream Martial Arts",
        "a_tag_vampire": "Novel Adapted Vampire",
        "a_tag_samurai": "Winter Concert Samurai",
        "a_tag_space": "All Night Space",
        "a_tag_parody": "Gold Prize Parody",
        "a_tag_idol": "Music Magic Idol",
        "a_tag_post_apocalyptic": "Perfect Concert Post Apocalyptic",
        "a_tag_cyberpunk": "Kumiko's Partner Cyberpunk",
        "a_tag_shounen": "Perfect Concert Shounen",
        "a_tag_seinen": "Band Return Seinen",
        "a_tag_shoujo": "Band Return Shoujo",
        "a_tag_josei": "Kumiko Oumae Josei",
        "a_tag_survival": "Reina's Solo Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "All Seasons",
        "a_mega_completionist": "Takeda Master",
        "a_completion_rate_50": "Novel Adapted Return",
        "a_completion_rate_75": "Night Practice Crown",
        "a_completion_rate_90": "Kumiko Oumae Resolution",
        "a_no_drop": "Sensei Standard Decree",
        "a_long_runner_complete": "Missed Notes Clear",
        "a_sequel_chain": "Liz and the Blue Bird",
        "a_clean_list": "Audition Tension Relic",
        "a_from_ptw": "Gold Prize Index",
        "a_rewatch_master": "Practice Alerts Return",
        "a_short_complete": "Kyoani Classic Endgame",
        "a_same_day_start_finish": "Practice Streak Pinnacle",
        "a_revival": "Long Practice Insignia",
        "a_zero_to_hero": "Reluctant to Passionate",
        "a_five_genre_complete": "Kyoani Classic A Five Genre",
        "a_full_franchise": "Kitauji Archives Chronicle",
        "a_batch_complete": "Honest Depth Crown",
        "a_paused_to_done": "Kumiko Oumae Aegis Aegis",
        "a_completion_spree": "Prize Winner Triumph",
        "a_multi_rewatch": "Prize Winner Triumph Triumph",
        "a_dropped_recovery": "Sound Euphonium Conquest",
        "a_ten_perfect_scores": "Missed Notes Acclaim",
        "a_seasonal_clear": "Score Collection Codex",
        "a_complete_genre_span": "Decade Fan A Complete Genre",
        "a_monthly_completions": "Practice Alerts Afterglow",
        "a_yearly_completions": "Night Rehearsal Epilogue",
        "a_rapid_complete": "Music Dream Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Kumiko's Partner",
        "a_studio_devotee": "Sensei Standard Treasury",
        "a_rewatcher": "Band Return",
        "a_triple_rewatch": "Reina's Ambition Coda",
        "a_annual_tradition": "Music Dream Proof",
        "a_director_fan": "Audition Tension Trial",
        "a_voice_actor_fan": "Sound Euphonium Crown Crown",
        "a_ost_lover": "Kitauji Archives Seal",
        "a_source_reader": "Score Library Cabinet",
        "a_waiting_weekly": "Sensei Standard Clock",
        "a_childhood_revisit": "Kumiko Reina Seal",
        "a_saga_tracker": "All Night Standard",
        "a_genre_loyalty": "Takeda Master Loyalty",
        "a_decade_watcher": "Decade Fan",
        "a_adaptation_hunter": "Gold Prize Trial",
        "a_original_anime_fan": "Band Critic Testament",
        "a_long_commitment": "Music Dream Mark Mark",
        "a_perfect_attendance": "Kumiko Reina Bond Standard",
        "a_favorite_studio_5": "Perfect Concert Library",
        "a_complete_catalog": "Reina's Solo Seal",
        "a_franchise_collector": "Perfect Concert Archive",
        "a_airing_follower": "Kumiko Reina Signal",
        "a_genre_master": "Audition Tension Master",
        "a_staff_follower": "Perfect Concert Oath",
        "a_multi_season_fan": "Liz Blue Hoard",
        "a_format_diversity": "Novel Adapted Cache",
        "a_year_dedication": "Honest Depth Tenure",
        "a_season_dedication": "Kitauji Band Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Reina's Ambition Explorer",
        "a_studio_hopper": "Practice Alerts Collection",
        "a_tag_explorer": "Honest Depth Explorer",
        "a_decade_hopper": "Kitauji Archives Chronicle Chronicle",
        "a_hidden_gem": "Hidden Solo",
        "a_popular_taste": "Music Magic Decree",
        "a_retro_appreciator": "Reina's Solo Aegis",
        "a_modern_viewer": "Practice Streak Pinnacle Pinnacle",
        "a_cross_demographic": "Concert Band Pinnacle",
        "a_underdog_fan": "Decade Fan Trial",
        "a_variety_week": "Perfect Concert Horizon",
        "a_foreign_cinema": "Band Trophies Expedition",
        "a_classic_connoisseur": "2013 Fan",
        "a_every_season": "Kumiko Reina Archive",
        "a_award_winner": "Daily Practice Insignia",
        "a_niche_explorer": "Band Return Horizon",
        "a_global_anime": "Kyoani Classic Crown",
        "a_cult_classic": "KyoAni Classic",
        "a_random_pick": "Music Magic Decree Decree",
        "a_new_genre_month": "Kumiko Reina Bond A New",
        "a_seasonal_completionist": "Long Practice Summit",
        "a_unpopular_opinion": "Reina Bond Standard",
        "a_top_rated_viewer": "Takeda Fan Seal",
        "a_source_variety": "Score Collection Storehouse",
        "a_low_score_brave": "Kumiko's Partner Measure",
        "a_upcoming_watcher": "Takeda Fan Seal Seal",
        "a_short_series_explorer": "Band Trophies Expedition Expedition",
        "a_long_series_explorer": "Kyoani Art Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Night Practice",
        "a_early_bird": "Morning Scales",
        "a_lunch_break": "All Arcs Trial",
        "a_golden_hour": "Hazuki Moments Tenure",
        "a_four_am_club": "Prize Winner Gathering",
        "a_witching_hour": "Night Practice Tenure",
        "a_new_year_watch": "Honest Depth Season",
        "a_midnight_premiere": "Taki Sensei Devotion",
        "a_all_hours": "Long Practice Seal",
        "a_dawn_warrior": "Music Magic Aegis",
        "a_afternoon_delight": "Gold Prize Winner Proof Proof",
        "a_prime_time": "Daily Practice Insignia Insignia",
        "a_workday_watcher": "Concert Band Pinnacle Pinnacle",
        "a_sunday_marathon": "Missed Notes Momentum",
        "a_rainy_day": "Night Practice Relic",
        "a_morning_routine": "Liz Blue Promise",
        "a_night_shift": "Novel Adapted Aegis",
        "a_twilight_zone": "Hidden Solo Ledger",
        "a_seasonal_premier": "Sensei Standard Cabinet",
        "a_clock_collector": "Prize Winner Repository",
        "a_weekend_binge_hours": "Band Return Streak",
        "a_late_night_regular": "Night Rehearsal Dominion",
        "a_sunrise_watcher": "Audition Tension Relic Relic",
        "a_holiday_watcher": "Takeda Fan Pact",
        "a_every_day_of_week": "Morning Scales Ledger",
        "a_monthly_hours": "Music Magic Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Kumiko Oumae Record",
        "a_party_host": "Novel Adapted Record Record",
        "a_social_butterfly": "Score Library Company",
        "a_group_binge": "Winter Concert Sprint",
        "a_party_regular": "Hidden Solo Chronicle",
        "a_sync_viewer": "Prize Winner Standard",
        "a_commentator": "Reina's Solo Record",
        "a_party_marathon": "Reina's Ambition Vigil",
        "a_full_house": "Kitauji Band Trial",
        "a_community_pillar": "Night Rehearsal Alliance",
        "a_watch_party_streak": "Reina's Solo Vigil",
        "a_diverse_party": "Liz Blue Seal",
        "a_late_night_party": "Night Rehearsal Testament Testament",
        "a_party_veteran": "Kitauji Band Testament",
        "a_genre_party": "Band Trophies Party",
        "a_weekly_party": "Prize Winner Calendar",
        "a_silent_viewer": "Band Critic Mantle",
        "a_recommendation_giver": "Band Return Network",
        "a_party_completionist": "All Night Coda",
        "a_social_scorer": "Audition Tension Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Kyoani Art Proof",
        "a_fibonacci": "Honest Depth Dominion",
        "a_palindrome_day": "Honest Depth Relic Relic",
        "a_binary_day": "Takeda Master Mark",
        "a_full_moon": "Kumiko Reina Insignia",
        "a_leap_year": "Kyoani Classic Devotion",
        "a_time_traveler": "Sensei Standard Record",
        "a_genre_clash": "Reina's Ambition Clash",
        "a_triple_seven": "Honest Depth Testament",
        "a_thousand_complete": "Band Critic Epilogue",
        "a_pi_episodes": "Concert Band Crown",
        "a_synchronicity": "Decade Fan Anchor",
        "a_world_record": "Sound Euphonium Warrant",
        "a_nice": "Daily Practice Chronicle",
        "a_power_level": "Band Critic Testament Testament",
        "a_answer_42": "Music Magic Standard",
        "a_square_number": "Reina's Ambition Decree",
        "a_prime_count": "Daily Practice Seal",
        "a_matching_date": "Decade Fan Mantle",
        "a_century_episode": "Concert Band Mark",
        "a_double_digits": "Night Practice Testament",
        "a_one_two_three": "Kyoani Classic Crown Crown",
        "a_lucky_seven": "Music Dream Crown",
        "a_all_tens": "Kumiko's Partner Criterion",
        "a_exact_hundred_eps": "All Night Legend",
        "a_year_match_count": "Sensei Standard Yearlong",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Band Return Ledger",
        "a_movie_buff": "Sound Euphonium Mark Mark",
        "a_ova_hunter": "All Night Standard Standard",
        "a_ona_explorer": "Decade Fan Secret",
        "a_special_watcher": "Night Practice Relic Relic",
        "a_short_king": "Blue Bird Crown",
        "a_variety_pack": "Sound Euphonium Inquiry",
        "a_film_festival": "Takeda Fan Chronicle",
        "a_music_video": "Liz Blue Chronicle",
        "a_tv_short": "Reina's Ambition Record",
        "a_movie_marathon": "Reina's Ambition Gauntlet",
        "a_double_length": "Kyoani Art Crown Crown",
        "a_anthology": "Novel Adapted Aegis Aegis",
        "a_mini_series": "Reina Bond Decree",
        "a_theatrical": "Perfect Concert Accord",
        "a_format_master": "Prize Winner Vault",
        "a_long_movie": "Long Practice Insignia Insignia",
        "a_back_catalog": "Reina's Solo Standard",
        "a_cm_watcher": "Taki Sensei Standard Aegis",
        "a_pv_collector": "Decade Fan Storehouse",
        "a_format_balance": "Prize Winner Vault Vault",
        "a_episodic_master": "Taki Sensei Standard Standard",
        "a_sequel_movie": "Kyoani Classic Pinnacle",
        "a_recap_watcher": "All Arcs Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Practice",
        "a_mega_streak": "Endless Rehearsal",
        "a_weekly_warrior": "Kitauji Band Season",
        "a_monthly_watcher": "Taki Sensei Calendar",
        "a_comeback": "Score Library Decree",
        "a_weekend_streak": "Kumiko's Partner Passage",
        "a_no_zero_days": "Takeda Master Warrant Warrant",
        "a_iron_will": "Kumiko's Resolve",
        "a_habit_formed": "Morning Scales Banner",
        "a_consistent_pace": "Kyoani Art Measure",
        "a_year_long": "Year of Music",
        "a_double_streak": "Audition Tension Watch",
        "a_streak_recovery": "Band Critic Season",
        "a_daily_minimum": "Taki Sensei Focus",
        "a_winter_streak": "Band Trophies Watch",
        "a_summer_streak": "Night Practice Resolve",
        "a_morning_streak": "Reina's Solo Clock",
        "a_night_streak": "Morning Scales Constancy",
        "a_unbreakable": "Blue Bird Proof",
        "a_eternal_flame": "Practice Alerts Standard",
        "a_completion_streak": "All Night Return",
        "a_rating_streak": "Honest Depth Balance",
        "a_multi_ep_streak": "Sound Euphonium Ritual",
        "a_genre_streak": "Honest Depth Streak",
        "a_studio_streak": "Score Library Cabinet Cabinet",
        "a_perfect_week": "Decade Fan Relic",

        // ── ANIME SCORING ──
        "a_critic": "Band Critic",
        "a_perfect_ten": "Perfect Concert",
        "a_harsh_critic": "Taki Sensei Standard",
        "a_fair_judge": "Night Rehearsal Balance",
        "a_generous_spirit": "Taki Sensei Pinnacle",
        "a_score_all": "Gold Prize Winner Criterion",
        "a_wide_range": "Daily Practice Ledger",
        "a_controversial": "Reina's Solo Decree",
        "a_consistent_scorer": "Sensei Standard Verdict",
        "a_score_sniper": "Kyoani Classic Score",
        "a_evolving_taste": "Audition Tension Testament",
        "a_bell_curve": "Kumiko Reina Bond Insignia",
        "a_picky_watcher": "Band Critic Warrant",
        "a_100_rated": "Prize Winner Warrant",
        "a_500_rated": "Blue Bird Pinnacle",
        "a_mediocre_majority": "Decade Fan Canon",
        "a_rating_spree": "Reina's Solo Review",
        "a_score_variance": "Kumiko's Partner Score",
        "a_masterpiece_hunter": "Reina's Solo Banner",
        "a_contrarian": "Reina's Ambition Record Record",
        "a_optimist": "Liz Blue Ledger",
        "a_score_distributor": "All Arcs Appraisal",
        "a_genre_critic": "Kyoani Art Critic",
        "a_mean_above_8": "Music Dream Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Practice",
        "a_valentines_weeb": "Perfect Concert Vow",
        "a_pi_day": "Night Rehearsal Trial",
        "a_april_fools": "Kyoani Classic Devotion Devotion",
        "a_international_anime_day": "Long Practice Record",
        "a_star_wars_day": "Missed Notes Chronicle",
        "a_summer_solstice": "Takeda Master Calendar",
        "a_tanabata": "Practice Streak Focus",
        "a_friday_13th": "All Arcs Relic",
        "a_halloween_spirit": "Band Return Vow",
        "a_thanksgiving_binge": "Hidden Solo Run",
        "a_christmas_special": "Winter Concert",
        "a_new_years_eve": "Music Dream Pilgrimage",
        "a_birthday_watch": "Kumiko Reina Bond Vow",
        "a_holiday_marathon": "Winter Concert Overture",
        "a_independence_day": "Practice Alerts Banner",
        "a_culture_day": "Kitauji Archives Insignia",
        "a_spring_equinox": "Winter Concert Decree",
        "a_earth_day": "Sound Euphonium Mantle",
        "a_labor_day": "Band Return Seal",
        "a_winter_solstice": "Concert Band Pilgrimage",
        "a_anime_birthday": "Sound Euphonium Pilgrimage",
        "a_every_holiday": "Gold Prize Resolve",
        "a_consecutive_holidays": "Night Practice Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Score Library Rank",
        "a_meta_collector": "Kitauji Archives Hoard",
        "a_meta_category_starter": "Taki Sensei Badge",
        "a_meta_tier_climber": "Kitauji Archives Glyph",
        "a_meta_tier_max": "Gold Prize Winner",
        "a_meta_xp_earner": "All Arcs Emblem",
        "a_meta_difficulty_easy": "Night Rehearsal Mechanism",
        "a_meta_difficulty_hard": "Takeda Fan Writ",
        "a_meta_unlock_spree": "Kitauji Band Panel",
        "a_meta_completionist": "All Arcs",
        "a_meta_diverse": "Honest Depth Emblem",
        "a_meta_dominator": "Hidden Solo Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Note",
        "m_chapter_counter": "Prize Winner Pinnacle",
        "m_chapter_titan": "Score Collection Relic",
        "m_reading_hours": "All Arcs Relic Relic",
        "m_reading_time_lord": "Long Practice Record Record",
        "m_manga_collector": "Kitauji Band Ledger",
        "m_library_legend": "Kitauji Archives Reliquary",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "Perfect Concert Seal",
        "m_first_rating": "All Arcs Eye",
        "m_ten_thousand_pages": "Perfect Concert Gauge",
        "m_volume_collector": "Band Critic Storehouse",
        "m_year_explorer": "Music Magic Quest",
        "m_century_reader": "Band Trophies Dominion",
        "m_five_hundred_ch": "Daily Practice Legend",
        "m_thousand_ch": "Audition Tension Legend",
        "m_reading_ten": "Band Trophies Appraisal",
        "m_ptr_hoarder": "Audition Tension Index",
        "m_dropped_honesty": "Kitauji Archives Summit",
        "m_season_reader": "Reina's Solo Treasury",
        "m_active_reader": "Night Practice Trial",
        "m_five_thousand_ch": "Reina's Ambition Standard",
        "m_ten_completed": "Reina's Ambition Resolution",
        "m_fifty_completed": "Audition Tension Harvest",
        "m_five_hundred_completed": "Morning Scales Legacy",
        "m_mean_score_tracker": "Sensei Standard Audit",
        "m_unique_authors": "Sound Euphonium Reserve",
        "m_all_status": "Night Practice Testament Testament",
        "m_first_favorite": "All Night Cache",
        "m_favorites_collector": "Score Library Shelf",
        "m_days_spent_reading": "Concert Band Relic",

        // ── MANGA BINGE ──
        "m_binge_reader": "Kumiko Reina Bond Streak",
        "m_marathon_reader": "Night Rehearsal Rush",
        "m_weekend_reader": "Kumiko Reina Run",
        "m_non_stop_reading": "All Night Gauntlet",
        "m_one_more_chapter": "All Arcs Testament Testament",
        "m_speed_read": "Takeda Master Drive",
        "m_double_story": "Winter Concert Banner",
        "m_triple_read": "Practice Alerts Record",
        "m_five_a_day": "Liz Blue Insignia",
        "m_chapter_chain": "Kitauji Archives Accord",
        "m_volume_binge": "Kumiko's Partner Drive",
        "m_power_reader": "Missed Notes Seal Seal",
        "m_half_day_read": "Score Library Aegis",
        "m_full_day_read": "Taki Sensei Standard Aegis Aegis",
        "m_power_weekend": "Perfect Concert Streak",
        "m_binge_king": "Practice Marathon",
        "m_no_sleep_read": "Band Trophies Rush",
        "m_full_series_rush": "Night Rehearsal Cascade",
        "m_seven_day_challenge": "Practice Streak Warrant",
        "m_hundred_day_read": "Honest Depth Legend",
        "m_volume_rush": "Kumiko Oumae Gauntlet",
        "m_series_sweep": "Gold Prize Trial Trial",
        "m_genre_binge": "Taki Sensei Standard Binge",
        "m_author_binge": "Kumiko Reina Surge",
        "m_chapter_counter_day": "Hidden Solo Ledger Ledger",
        "m_multi_series_binge": "Daily Practice Charge",
        "m_midnight_binge": "Audition Tension Tempest",
        "m_new_year_binge": "Sound Euphonium Passage",
        "m_forty_eight_hour": "Sensei Standard Rally",
        "m_oneshot_binge": "Takeda Master Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "None Here",
        "m_genre_adventure": "Nationals Chapter",
        "m_genre_comedy": "Score Library Comedy",
        "m_genre_drama": "Ambition Chapter",
        "m_genre_fantasy": "Music Chapter",
        "m_genre_horror": "Tension Chapter",
        "m_genre_mystery": "Reina's Ambition Mystery",
        "m_genre_romance": "Heart Chapter",
        "m_genre_scifi": "Unusual Chapter",
        "m_genre_sol": "Prize Winner Slice",
        "m_genre_sports": "Kumiko Oumae Sports",
        "m_genre_supernatural": "Sound Chapter",
        "m_genre_thriller": "Decade Fan Thriller",
        "m_genre_psychological": "Honest Depth",
        "m_genre_isekai": "Kitauji Band Isekai",
        "m_genre_shounen": "Hazuki Moments Shounen",
        "m_genre_ecchi": "Kyoani Art Ecchi",
        "m_genre_mahou_shoujo": "Score Library Magic Shoujo",
        "m_genre_mecha": "Band Critic Mecha",
        "m_genre_music": "Band Return Music",
        "m_tag_isekai_new": "All Arcs Isekai New",
        "m_tag_harem": "Gold Prize Winner Harem",
        "m_tag_bl": "Reina Bond Bl",
        "m_tag_gl": "Audition Tension Gl",
        "m_tag_historical": "Daily Practice Historical",
        "m_tag_military": "Hazuki Moments Military",
        "m_tag_school": "Perfect Concert School",
        "m_tag_martial_arts": "Prize Winner Martial Arts",
        "m_tag_vampire": "Kumiko Oumae Vampire",
        "m_tag_samurai": "Novel Adapted Samurai",
        "m_tag_space": "Reina Bond Space",
        "m_tag_parody": "Band Critic Parody",
        "m_tag_idol": "Reina Bond Idol",
        "m_tag_post_apocalyptic": "Kitauji Archives Post Apocalyptic",
        "m_tag_cyberpunk": "Gold Prize Winner Cyberpunk",
        "m_tag_shoujo": "Takeda Fan Shoujo",
        "m_tag_survival": "Score Library Survival",
        "m_tag_cooking": "Kumiko Reina Bond Cooking",
        "m_tag_medical": "Night Practice Medical",
        "m_tag_villainess": "Kumiko Reina Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Novel",
        "m_mega_completionist": "Euphonium Expert",
        "m_completion_rate_50": "Reina Bond Return",
        "m_completion_rate_75": "Decade Fan Ascension",
        "m_completion_rate_90": "Practice Alerts Resolution",
        "m_no_drop": "All Night Decree",
        "m_long_runner_complete": "Hidden Solo Clear",
        "m_sequel_chain": "Band Return Seal Seal",
        "m_clean_list": "Score Collection Relic Relic",
        "m_from_ptr": "Takeda Fan Watchlist",
        "m_reread_master": "Night Rehearsal Trial Trial",
        "m_oneshot_complete": "Night Rehearsal Ascension",
        "m_same_day_start_finish": "Music Dream Crown Crown",
        "m_revival": "Hidden Solo Accord",
        "m_zero_to_hundred": "Reina's Ambition Banner",
        "m_five_genre_complete": "Takeda Master M Five Genre",
        "m_full_collection": "Music Dream Proof Proof",
        "m_batch_complete": "Sensei Standard Summit",
        "m_paused_to_done": "Practice Alerts Standard Standard",
        "m_completion_spree": "Blue Bird Triumph",
        "m_format_completionist": "Night Rehearsal Completion",
        "m_catch_up": "Long Practice Chronicle",
        "m_multi_reread": "All Night Banner",
        "m_dropped_recovery": "Kyoani Art Conquest",
        "m_ten_perfect_scores": "Kumiko Reina Judgment",
        "m_complete_genre_span": "Kitauji Band M Complete Genre",
        "m_monthly_completions": "Taki Sensei Standard Return",
        "m_yearly_completions": "Kitauji Band Epilogue",
        "m_rapid_complete": "Practice Streak Finale",
        "m_author_complete": "Perfect Concert Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Devoted Reader",
        "m_mangaka_lover": "Takeda Fan",
        "m_rereader": "Band Return",
        "m_triple_reread": "Honest Depth Testament Testament",
        "m_annual_reread": "Reina's Ambition Banner Banner",
        "m_publisher_fan": "Blue Bird Mark",
        "m_artist_fan": "Band Return Insignia",
        "m_adaptation_compare": "Kumiko Reina Bond Insignia Insignia",
        "m_source_material_fan": "Novel First",
        "m_waiting_weekly": "Novel Adapted Streak",
        "m_classic_reader": "Band Critic Lantern",
        "m_saga_reader": "Kitauji Archives Decree",
        "m_genre_loyalty": "Kyoani Art Loyalty",
        "m_decade_reader": "Kumiko's Partner Warrant",
        "m_ln_adaptation": "Kumiko's Partner Mark",
        "m_original_work": "Kumiko Oumae Standard",
        "m_long_commitment": "Kyoani Art Mark",
        "m_up_to_date": "Sound Euphonium Warrant Warrant",
        "m_favorite_mangaka": "Music Magic Treasury",
        "m_complete_portfolio": "Blue Bird Triumph Triumph",
        "m_franchise_collector": "Long Practice Archive",
        "m_serialization_follower": "Music Magic Handshake",
        "m_genre_master": "Score Collection Master",
        "m_multi_series_author": "Kitauji Archives Insignia Insignia",
        "m_format_diversity": "Kumiko Oumae Shelf",
        "m_year_dedication": "Band Trophies Tenure",
        "m_ongoing_follower": "Kumiko's Partner Fellowship",
        "m_genre_loyalty_50": "Audition Tension Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Winter Concert Explorer",
        "m_publisher_hopper": "Blue Bird Mantle",
        "m_tag_explorer": "Gold Prize Explorer",
        "m_decade_hopper": "Takeda Fan Chronicle Chronicle",
        "m_hidden_gem": "Hidden Volume",
        "m_popular_taste": "Sensei Standard Record Record",
        "m_retro_reader": "Sensei Standard Accord",
        "m_modern_reader": "Daily Practice Seal Seal",
        "m_cross_demographic": "Taki Sensei Crown",
        "m_underdog_fan": "Sensei Standard Accord Accord",
        "m_variety_week": "Band Return Horizon Horizon",
        "m_manhwa_reader": "Kyoani Classic Proof",
        "m_manhua_reader": "Band Critic Mantle Mantle",
        "m_classic_connoisseur": "Morning Scales Glimpse",
        "m_award_winner": "Band Trophies Warrant",
        "m_niche_explorer": "Kumiko Reina Bond Horizon",
        "m_world_manga": "Long Practice Chronicle Chronicle",
        "m_cult_classic": "KyoAni Classic",
        "m_random_pick": "Sensei Standard Standard",
        "m_new_genre_month": "Long Practice M New Genre",
        "m_year_completionist": "Prize Winner Fulfillment",
        "m_unpopular_opinion": "Sound Euphonium Trial",
        "m_top_rated_reader": "Kumiko Reina Bond Record",
        "m_source_variety": "Band Critic Catalogue",
        "m_low_score_brave": "Prize Winner Score",
        "m_short_manga_explorer": "Daily Practice Compass",
        "m_long_manga_explorer": "Reina's Ambition Survey",
        "m_serialization_explorer": "Decade Fan Road",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Reina Bond Ledger",
        "m_commute_reader": "Night Practice Tenure Tenure",
        "m_four_am_club": "Blue Bird Fellowship",
        "m_new_year_read": "Band Return Pact",
        "m_all_hours": "Takeda Fan Accord Accord",
        "m_prime_time_reader": "Kumiko Oumae Banner",
        "m_workday_reader": "Hidden Solo Accord Accord",
        "m_sunday_read": "Reina Bond Standard Standard",
        "m_morning_routine": "Hidden Solo Discipline",
        "m_night_shift_reader": "Perfect Concert Accord Accord",
        "m_seasonal_premier_read": "Band Critic Seasonal",
        "m_clock_collector": "Concert Band Reserve",
        "m_late_night_horror": "Takeda Master Mark Mark",
        "m_afternoon_reader": "Band Trophies Mantle Mantle",
        "m_golden_hour_reader": "Honest Depth Observance",
        "m_dawn_reader": "Gold Prize Mantle",
        "m_twilight_reader": "Kumiko's Partner Crown",
        "m_midnight_start": "Kumiko Oumae Routine",
        "m_weekend_binge_hours": "Kumiko Reina Momentum",
        "m_late_night_regular": "Reina Bond Accord",
        "m_sunrise_reader": "Gold Prize Winner Mantle",
        "m_every_day_of_week": "Band Critic Warrant Warrant",
        "m_monthly_hours": "Winter Concert Vigil",
        "m_bedtime_reader": "Prize Winner Warrant Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "KyoAni Art",
        "m_webtoon_reader": "Kumiko's Partner Mark Mark",
        "m_full_color": "Band Return Accord",
        "m_doujin_reader": "Practice Alerts Record Record",
        "m_anthology_reader": "Kumiko Reina Accord",
        "m_adaptation_reader": "Sensei Standard Banner",
        "m_longstrip_reader": "Honest Depth Trial",
        "m_4koma_reader": "Novel Adapted Ledger",
        "m_oneshot_reader": "Kitauji Band Mantle",
        "m_format_variety": "Blue Bird Gallery",
        "m_light_novel_reader": "Takeda Fan Insignia",
        "m_novel_reader": "Prize Winner Crown",
        "m_visual_storyteller": "Band Trophies Testament",
        "m_colored_classic": "Reina's Solo Survey",
        "m_webcomic_fan": "Morning Scales Insignia",
        "m_manga_to_anime": "Novel Adapted",
        "m_seinen_reader": "Kyoani Art Pinnacle",
        "m_josei_reader": "Gold Prize Winner Pinnacle",
        "m_award_winning_art": "Hazuki Moments Relic",
        "m_debut_work": "Hazuki Moments Dominion",
        "m_vertical_scroll": "Kitauji Archives Decree Decree",
        "m_traditional_format": "Kumiko Reina Bond Hoard",
        "m_cross_media": "Daily Practice Accord",
        "m_spinoff_reader": "Long Practice Accord",
        "m_remake_reader": "Night Rehearsal Pinnacle",
        "m_collaboration_reader": "Morning Scales Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Practice Streak",
        "m_weekly_warrior": "Decade Fan Season",
        "m_monthly_reader": "Liz Blue Discipline",
        "m_comeback": "Reina's Ambition Standard Standard",
        "m_weekend_streak": "Gold Prize Winner Fever",
        "m_no_zero_days": "Kyoani Classic Proof Proof",
        "m_iron_will": "Musician Resolve",
        "m_habit_formed": "Taki Sensei Crown Crown",
        "m_consistent_pace": "Music Dream Scrutiny Scrutiny",
        "m_year_long": "Year Reading",
        "m_double_streak": "Kitauji Band Resolve",
        "m_streak_recovery": "Score Collection Resolve",
        "m_daily_minimum": "Concert Band Focus",
        "m_winter_streak": "Honest Depth Observance Observance",
        "m_summer_streak": "Hazuki Moments Observance",
        "m_morning_streak": "Winter Concert Clock",
        "m_night_streak": "Kumiko Reina Bond Discipline",
        "m_unbreakable": "Gold Prize Winner Warrant",
        "m_eternal_flame": "Score Library Record",
        "m_chapter_a_day": "Reina Bond Ledger Ledger",
        "m_genre_streak": "Gold Prize Streak",
        "m_completion_streak": "Sensei Standard Return",
        "m_rating_streak": "Gold Prize Appraisal",
        "m_multi_ch_streak": "Decade Fan Tenure",
        "m_author_streak": "Concert Band Calendar",
        "m_perfect_week_manga": "Long Practice Accord Accord",
        "m_diverse_streak": "All Night Streak",

        // ── MANGA SCORING ──
        "m_critic": "Band Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_harsh_critic": "Takeda Fan Scale",
        "m_fair_judge": "All Arcs Eye Eye",
        "m_generous_spirit": "Kumiko Reina Decree",
        "m_score_all": "Kumiko's Partner Reckoning",
        "m_wide_range": "Liz Blue Ledger Ledger",
        "m_controversial": "Taki Sensei Standard Standard Standard",
        "m_consistent_scorer": "Practice Alerts Grade",
        "m_score_sniper": "Sound Euphonium Reckoning",
        "m_evolving_taste": "Kitauji Band Trial Trial",
        "m_bell_curve": "Liz Blue Accord",
        "m_picky_reader": "All Night Ledger",
        "m_100_rated": "Liz Blue Standard",
        "m_500_rated": "Perfect Concert Aegis",
        "m_mediocre_majority": "Kitauji Band Canon",
        "m_rating_spree": "Winter Concert Verdict",
        "m_score_variance": "Prize Winner Measure",
        "m_binge_rater": "Concert Band Passage",
        "m_reread_rerate": "Reina's Solo Banner Banner",
        "m_masterpiece_hunter": "Taki Sensei Standard Banner",
        "m_contrarian": "Sensei Standard Aegis",
        "m_optimist": "Daily Practice Accord Accord",
        "m_score_distributor": "Decade Fan Balance",
        "m_genre_critic": "Concert Band Critic",
        "m_mean_above_8": "Prize Winner Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Band Trophies Season",
        "m_valentines_read": "Gold Prize Observance",
        "m_pi_day": "Kitauji Band Testament Testament",
        "m_april_fools": "Sound Euphonium Devotion",
        "m_international_manga_day": "Takeda Fan Aegis",
        "m_free_comic_day": "Kumiko Reina Chronicle",
        "m_summer_solstice": "Practice Streak Focus Focus",
        "m_tanabata": "Music Dream Tanabata",
        "m_friday_13th": "Night Rehearsal Dominion Dominion",
        "m_halloween_read": "Takeda Master Halloween",
        "m_thanksgiving_binge": "Long Practice Charge",
        "m_christmas_read": "Hidden Solo Pact",
        "m_new_years_eve": "Practice Streak Pilgrimage",
        "m_birthday_read": "Kyoani Art Focus",
        "m_holiday_marathon": "Music Magic Rally",
        "m_independence_day": "Sensei Standard Aegis Aegis",
        "m_culture_day": "Perfect Concert Seal Seal",
        "m_spring_equinox": "Takeda Master Dominion",
        "m_earth_day": "Kyoani Art Trial",
        "m_labor_day": "Hidden Solo Seal",
        "m_winter_solstice": "Taki Sensei Focus Focus",
        "m_manga_birthday": "Music Dream Ritual",
        "m_every_holiday_reader": "Score Collection Watch",
        "m_consecutive_holidays": "Night Rehearsal Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Missed Notes Aegis",
        "m_fibonacci": "Night Practice Dominion",
        "m_palindrome_day": "Kitauji Band Relic",
        "m_binary_day": "Taki Sensei Proof",
        "m_full_moon_read": "Gold Prize Winner Crown",
        "m_leap_year_read": "All Night Practice",
        "m_triple_seven": "All Arcs Trial Trial",
        "m_thousand_complete": "All Arcs Ascension",
        "m_nice": "Kitauji Archives Seal Seal",
        "m_power_level_chapters": "Reina's Ambition Aegis",
        "m_answer_42": "Gold Prize Winner Trial",
        "m_square_number": "Score Library Standard",
        "m_prime_count": "All Arcs Pinnacle",
        "m_matching_date": "Score Collection Mantle",
        "m_century_chapter": "Missed Notes Decree",
        "m_pi_chapters": "Kyoani Art Proof Proof",
        "m_synchronicity": "Gold Prize Emblem",
        "m_world_record": "Kyoani Classic Warrant",
        "m_genre_clash": "Kumiko Oumae Clash",
        "m_time_traveler": "Practice Alerts Decree",
        "m_double_digits": "Band Critic Dominion",
        "m_one_two_three": "Morning Scales Banner Banner",
        "m_lucky_seven": "Kumiko Reina Bond Record Record",
        "m_exact_hundred_ch": "Night Practice Legend",
        "m_year_match_count": "Novel Adapted Routine",
        "m_chapter_match_date": "Taki Sensei Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Band Critic Index",
        "m_manhwa_format": "Takeda Master Gallery",
        "m_manhua_format": "Honest Depth Storehouse",
        "m_ln_format": "All Arcs Index",
        "m_oneshot_format": "Kitauji Band Index",
        "m_doujin_format": "Winter Concert Cabinet",
        "m_novel_format": "Sound Euphonium Reserve Reserve",
        "m_format_master_manga": "Winter Concert Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Practice Alerts Link",
        "m_meta_collector": "Perfect Concert Reliquary",
        "m_meta_category_starter": "Blue Bird Standard",
        "m_meta_tier_climber": "Daily Practice Token",
        "m_meta_tier_max": "Euphonium Complete",
        "m_meta_xp_earner": "Band Critic Anchor",
        "m_meta_difficulty_easy": "All Arcs Panel",
        "m_meta_difficulty_hard": "Band Trophies Node",
        "m_meta_unlock_spree": "Band Critic Marker",
        "m_meta_completionist": "Full Library",
        "m_meta_diverse": "Kitauji Band Anchor",
        "m_meta_dominator": "Kitauji Archives Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#030005",
        primary: "#7644d7",
        secondary: "#5826b2",
        accent: "#d4a020",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/hibike-euphonium.jpg",
    particleColor: "#9060e0",
    backgroundDim: 0.32,
    backgroundBlur: 16,
    particleTypes: {
        music_notes: { label: "Music Notes", maxCount: 18, defaultEnabled: true, defaultIntensity: 60 },
        brass_shimmer: { label: "Brass Shimmer", maxCount: 12, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
  1: "Threadbare Kumiko Middle Haven",
  8: "Kitauji's Tarnished Omen",
  14: "Fractured Concert Band",
  21: "Reina Friendship Vow",
  28: "Lowborn Return Myth",
  35: "Beginner Ensemble Pulse",
  41: "Basic's Training Brush",
  48: "Humble Sectional Mark",
  55: "Ragged Conductor Authority Force",
  61: "Sound's Faint Echo",
  68: "Lesser Daily Practice",
  75: "Section Competition Clash",
  81: "Doubtful Legacy Soul",
  88: "Band Hierarchy Sigil",
  95: "Ensemble's Legacy Flame",
  102: "Really Cool Regional Spark",
  108: "Awakened Reina Trumpet Omen",
  115: "Performance's Resolute Form",
  122: "Rising Tuba Section",
  128: "Musical Form",
  135: "Dauntless Legacy Clash",
  142: "Tension Band Soul",
  149: "Solo's Debate Mark",
  155: "Fresh Kumiko Clash",
  162: "Valiant Rehearsal Intensity Echo",
  169: "Audition's Prime Crown",
  175: "Polished Friendship Ambition",
  182: "Sound Struggle Bloom",
  189: "Stormlit Emotional Soul",
  195: "Conductor Expectations Flame",
  202: "Contest's Qualification Spark",
  209: "Tempered Performance Form",
  216: "Trusted Section Rivalries Seal",
  222: "Kumiko's Steadfast Path",
  229: "Ironclad Band Unity",
  236: "Regional Contest Pulse",
  242: "Core Focus Form",
  249: "Reina Solo Pact",
  256: "Kumiko's Understanding Vow",
  262: "Formidable Musical Echo",
  269: "Lucid Judgement Crown",
  276: "Performance's Ranked Form",
  283: "Fabled Band",
  289: "Technical Push Sigil",
  296: "Seasoned Building Flame",
  303: "Result Announcement Spark",
  309: "Success's Legacy Clash",
  316: "Valorous Reina Seal",
  323: "Stalwart Band Reflection Soul",
  330: "Future's Commanding Thread",
  336: "Refined Next Season",
  343: "New Members Crest",
  350: "Blazing Responsibility Mark",
  356: "Practice Discipline Vow",
  363: "Section's Strengthening Force",
  370: "Peerless National Crown",
  376: "Ardent Audition Competition Zenith",
  383: "Turning's Focused Bloom",
  390: "Vigilant Solo Performance",
  397: "Reina Career Flame",
  403: "Elite Emergence Spark",
  410: "Expression Music Soul",
  417: "Band's Conflict Clash",
  423: "Sovereign High Form",
  430: "Regal Sound Pursuit Myth",
  437: "Section's Crowned Pulse",
  444: "Mythborn Resonance",
  450: "Competition Deadline Mark",
  457: "Radiant Final Clash",
  464: "Performance Form",
  470: "Kumiko's Emotional Soul",
  477: "Climactic Reina Brush",
  484: "Epic Ensemble Unity Bloom",
  490: "Post's Unreal Sigil",
  497: "Peak Exhaustion",
  504: "Musical Solidification Soul",
  511: "Exalted Legacy Vow",
  517: "Future Direction Thread",
  524: "New's Year Path",
  531: "Celestial Fresh Myth",
  537: "Phantom Leadership Transition Pulse",
  544: "Practice's Crimson Crest",
  551: "Silver Section Harmony",
  557: "Advanced Technique Vow",
  564: "Feral Legacy Echo",
  571: "Maturity Soul",
  578: "Band's Strength Force",
  584: "Dread Pre Bloom",
  591: "Luminous Internal Rivalry Sigil",
  598: "Reina's Thunderous Flame",
  604: "Ultraviolet Performance Stability",
  611: "Collective Sound Omen",
  618: "Secret Legacy Seal",
  625: "Practice Execution Path",
  631: "Musical's Emotional Soul",
  638: "Worldclass Ensemble Pulse",
  645: "Lawless Legend Kitauji Crest",
  651: "Kumiko's Chosen Mark",
  658: "Fearless Reina Trumpet",
  665: "Concert Band Echo",
  671: "Cinematic Seasons Crown",
  678: "Dormant Competition Zenith",
  685: "Performances's Memory Echo",
  692: "Canonized School Haven",
  698: "Ascendant Youth Music Flame",
  705: "Silent's Transfigured Spark",
  712: "Immortal Dormant Notes",
  718: "Balance Seal",
  725: "Astral Euphonium Path",
  732: "Youth Orchestra Myth",
  739: "Kumiko's Legacy Pulse",
  745: "Prismatic Ensemble Crest",
  752: "Abyssal Quiet Horizon Mark",
  759: "Dormant's Unbound Soul",
  765: "Eternal Legend School",
  772: "Practice Performance Form",
  779: "Transcendent Emotion Soul",
  785: "Youth Competition Bloom",
  792: "Talent's Legacy Sigil",
  799: "Ultimate Ensemble Flame",
  806: "Mythic Emotion Soul",
  812: "Growth's Godlike Omen",
  819: "Canonical Musical Mastery",
  826: "Kumiko Euphonium Path",
  832: "Heavenly Apex Brush",
  839: "Band Unity Pulse",
  846: "Closure's Emotional Soul",
  852: "Timeless Acceptance Mark",
  859: "Empyrean Identity Soul",
  866: "Competition's Primordial Clash",
  873: "Omniscient Narrative Musical",
  879: "Sound Euphonium Zenith",
  886: "Apocalyptic Legacy Bloom",
  893: "Resolution Soul",
  899: "Sound's Truth Secret",
  906: "Final Origin Secret",
  913: "Crowned Performance Anxiety Form",
  920: "Harmonic's Mythic Seal",
  926: "Absolute Legend Sound",
  933: "Ensemble Flow Myth",
  940: "Cosmic Legacy Pulse",
  946: "Music Crest",
  953: "Sound's Perfect Mark",
  960: "Definitive Ultimate Vow",
  966: "Ultimate Quiet Questioned Echo",
  973: "Quiet's Infinite Crown",
  980: "Sovereign Quiet Questioned",
  987: "Quiet Questioned Bloom",
  993: "Legendary Place Sigil",
  1000: "Ultimate Ultimate Musical"
}
}
