import { AnimeThemeConfig } from "./types"
import { GiFlowerEmblem, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiCrystalBall, GiStarSwirl, GiMusicalNotes } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const hidamariSketchTheme: AnimeThemeConfig = {
    id: "hidamari-sketch",
    displayName: "Hidamari Sketch",
    description: "Yuno enrolls in an art high school and moves into the Hidamari Apartments, where she and her neighbors — Miyako, Hiro, and Sae — share cozy daily life while growing as artists.",
    cssVars: {
        "--color-brand-200": "255 228 165",
        "--color-brand-300": "252 198 98",
        "--color-brand-400": "238 160 38",
        "--color-brand-500": "210 122 5",
        "--color-brand-600": "165 84 0",
        "--color-brand-700": "118 50 0",
        "--color-brand-800": "74 24 0",
        "--color-brand-900": "38 8 0",
        "--color-brand-950": "15 3 0",
        "--brand": "210 122 5",
        "--background": "#060300",
        "--paper": "#0f0600",
        "--color-gray-950": "6 3 0",
        "--color-gray-900": "16 8 1",
        "--color-gray-800": "30 16 3",
        "--color-gray-700": "52 30 7",
        "--color-gray-600": "82 52 14",
        "--color-gray-500": "125 84 28",
        "--color-gray-400": "168 130 60",
        "--color-gray-300": "208 172 98",
        "--color-gray-200": "238 208 148",
        "--color-gray-100": "252 232 195",
        "--color-gray-50": "255 246 232",
    },
    sidebarOverrides: {
        "home": { icon: GiFlowerEmblem, label: "Hidamari Apts" },
        "schedule": { icon: GiAlarmClock, label: "School Schedule" },
        "manga": { icon: LuBookOpen, label: "Sketchbook" },
        "lists": { icon: GiScrollUnfurled, label: "Class List" },
        "discover": { icon: GiBullseye, label: "New Inspirations" },
        "torrent-list": { icon: GiStarSwirl, label: "Art Cache" },
        "debrid": { icon: GiHeartKey, label: "Studio Vault" },
        "unmatched": { icon: GiCrystalBall, label: "Unfinished Sketches" },
        "enmasse": { icon: GiResize, label: "Art Exhibition" },
        "scan-summaries": { icon: TbReportSearch, label: "Art Reports" },
        "auto-downloader": { icon: LuRss, label: "School Feed" },
        "community": { icon: GiMusicalNotes, label: "Hidamari Circle" },
        "achievements": { icon: GiTrophyCup, label: "Art Trophies" },
        "milestones": { icon: LuFlag, label: "Art Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "School Alerts" },
        "theme-manager": { icon: GiPalette, label: "Sunny Colors" },
        "extensions": { icon: BiExtension, label: "Art Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Studio Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Yuno Config" },
    },
    achievementNames: {
        "a_first_episode": "Moved In",
        "a_first_complete": "First Sketch",
        "a_hundred_club": "Hundred School Days",
        "a_binge_king": "Hidamari Marathon",
        "a_completionist": "Art School Graduate",
        "a_mega_completionist": "Hidamari Legend",
        "a_loyal_fan": "Apartment Regular",
        "a_zero_to_hero": "New Student to Artist",
        "m_first_chapter": "First Brush",
        "m_completionist": "Full Manga Archive",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060300",
        primary: "#d27a05",
        secondary: "#6868a8",
        accent: "#f8e0a0",
    },
    particleColor: "#e09020",
    backgroundDim: 0.2,
    backgroundBlur: 12,
milestoneNames: {
    1: "Yuno Entrance to Yamabuki",
    8: "Hidamari Apartments Move-In",
    15: "Room 202 First Day",
    22: "Miyako Neighbor Meeting",
    29: "Sae and Hiro Introduction",

    36: "Art School Orientation",
    43: "Sketchbook First Pages",
    50: "Daily Life Rhythm Begins",
    57: "Studio Habit Formation",
    64: "Classroom Familiarity",

    71: "First Art Assignments",
    78: "Creative Doubt Emerges",
    85: "Friendship Comfort Growth",
    92: "Seasonal Life Awareness",
    99: "Quiet Routine Acceptance",

    106: "Winter Dorm Warmth",
    113: "Art Critique Anxiety",
    120: "Miyako Chaos Energy",
    127: "Sae Writing Ambition",
    134: "Hiro Caregiver Role",

    141: "School Festival Preparation",
    148: "Group Project Collaboration",
    155: "Art Block Moments",
    162: "Emotional Support Cycles",
    169: "Shared Meals and Talks",

    176: "Spring Cherry Blossom Days",
    183: "New Class Year Begins",
    190: "Creative Inspiration Return",
    197: "Yuno Confidence Struggles",
    204: "Room 202 Bond Deepens",

    211: "Summer Heat Days",
    218: "Art Practice Intensifies",
    225: "Small Achievements Noticed",
    232: "Friendship Routine Stability",
    239: "Quiet Emotional Reflection",

    246: "Field Sketching Trips",
    253: "Cultural Festival Arc",
    260: "Group Exhibition Attempts",
    267: "Creative Comparison Anxiety",
    274: "Personal Growth Recognition",

    281: "Autumn Transition Mood",
    288: "Life Balance Learning",
    295: "Art Skill Gradual Growth",
    302: "Support Between Friends",
    309: "Everyday Meaning Discovery",

    316: "Winter Preparation Season",
    323: "Warmth of Shared Living",
    330: "Creative Confidence Build",
    337: "Sae Career Aspirations",
    344: "Hiro Emotional Stability",

    351: "School Year Milestone",
    358: "New Assignments Growth",
    365: "Art Style Exploration",
    372: "Miyako Emotional Anchor",
    379: "Room 202 Harmony",

    386: "Personal Art Identity",
    393: "Small Exhibition Arc",
    400: "Turning Point of Growth",

    407: "Life Observation Deepens",
    414: "Quiet Emotional Moments",
    421: "Friendship Reflection Arc",
    428: "Creative Struggle Acceptance",
    435: "Everyday Inspiration Flow",

    442: "Seasonal Memory Montage",
    449: "Group Living Comfort Peak",
    456: "Yuno Self Acceptance",
    463: "Art Expression Maturity",
    470: "Life Detail Appreciation",

    477: "Final School Events",
    484: "Graduation Implied Pressure",
    491: "Emotional Attachment Growth",
    498: "Art Portfolio Completion",
    505: "Shared Memories Solidify",

    512: "Post-Class Reflection",
    519: "Room 202 Continuation",
    526: "Friendship Stability",
    533: "Creative Life Continuation",
    540: "Gentle Everyday Rhythm",

    547: "New Year Calm Start",
    554: "Art Practice Continuation",
    561: "Subtle Personal Growth",
    568: "Shared Routine Comfort",
    575: "Life in Motion Slowly",

    582: "Quiet City Seasons",
    589: "Dormant Creative Doubt",
    596: "Emotional Warmth Return",
    603: "Friendship Deep Stability",

    610: "Everyday Apartment Life",
    617: "Routine and Inspiration Balance",
    624: "Small Artistic Breakthroughs",
    631: "Gentle Self Awareness",
    638: "Comfort in Simplicity",

    645: "Seasonal Flow Continuation",
    652: "Quiet Study Days",
    659: "Soft Emotional Growth",
    666: "Stable Life Harmony",

    673: "Legend of Hidamari Sketch",
    680: "Room 202 Memory Myth",
    687: "Yuno Gentle Growth Story",
    694: "Art School Life Legend",

    701: "Silent Apartment Evenings",
    708: "Dormant Creative Echo",
    715: "Memory of Seasons Past",
    722: "Everyday Life Appreciation",
    729: "Soft Youth Chronicle",

    736: "Quiet Sunrise Routine",
    743: "Dormant Emotional Sketches",
    750: "Balance of Life and Art",

    757: "Legend of Hidamari Life",
    764: "Slice of Life Myth",
    771: "Room 202 Harmony Story",
    778: "Gentle Growth Narrative",

    785: "Silent Afternoon Light",
    792: "Dormant Inspiration Flow",

    799: "Legend of Everyday Beauty",
    806: "Cycle of Seasons and Growth",
    813: "Human Softness Myth",
    820: "Youth Life Reflection",

    827: "Beyond Achievement and Competition",
    834: "Perfect Everyday Harmony",
    841: "Life as Gentle Art",
    848: "Growth Through Small Moments",

    855: "Absolute Daily Life Mastery",
    862: "Yuno Peak Self Expression",
    869: "Room 202 Emotional Unity",
    876: "Creative Life Stability",

    883: "Final Emotional Closure",
    890: "Acceptance of Ordinary Happiness",
    897: "Life Fully Appreciated",

    904: "Beyond Time and Ambition",
    911: "Perfect Narrative Soft Flow",
    918: "Hidamari Sketch Eternal Status",
    925: "Life as Continuous Warmth",

    932: "Final Identity Resolution",
    939: "Absolute Truth of Everyday Life",
    946: "Origin of Creative Joy Revealed",
    953: "Beyond Pressure and Expectation",

    960: "Absolute Gentle Existence",
    967: "Legend of Hidamari Sketch",
    974: "Perfect Daily Flow",
    981: "Beyond Worry",
    988: "Absolute Warm State",
    995: "Perfect Life State",
    998: "Ultimate Gentle Harmony",
    1000: "A Young Artist Living in a Small Apartment Learned That Life’s Meaning Is Not Found in Great Achievements, but in the Quiet Accumulation of Days Shared With Friends, Where Even Ordinary Moments Become Something Worth Sketching and Remembering"
}
}
