import { AnimeThemeConfig } from "./types"
import { GiCrossedSwords, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiCrystalBall, GiStarSwirl, GiSpellBook } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const infiniteStratosTheme: AnimeThemeConfig = {
    id: "infinite-stratos",
    displayName: "Infinite Stratos",
    description: "IS battle suits can only be piloted by women — except Ichika Orimura, the first and only male pilot. He enrolls in the IS Academy as the sole boy in an all-female school, surrounded by representatives from every nation.",
    cssVars: {
        "--color-brand-200": "175 208 255",
        "--color-brand-300": "112 168 248",
        "--color-brand-400": "58 125 235",
        "--color-brand-500": "18 85 208",
        "--color-brand-600": "5 52 165",
        "--color-brand-700": "1 28 122",
        "--color-brand-800": "0 12 76",
        "--color-brand-900": "0 4 38",
        "--color-brand-950": "0 1 16",
        "--brand": "18 85 208",
        "--background": "#000208",
        "--paper": "#000412",
        "--color-gray-950": "0 2 8",
        "--color-gray-900": "1 6 18",
        "--color-gray-800": "3 14 35",
        "--color-gray-700": "6 26 58",
        "--color-gray-600": "11 46 90",
        "--color-gray-500": "20 76 130",
        "--color-gray-400": "42 116 168",
        "--color-gray-300": "78 156 205",
        "--color-gray-200": "122 192 232",
        "--color-gray-100": "175 220 250",
        "--color-gray-50": "222 242 255",
    },
    sidebarOverrides: {
        "home": { icon: GiCrossedSwords, label: "IS Academy" },
        "schedule": { icon: GiAlarmClock, label: "Training Schedule" },
        "manga": { icon: LuBookOpen, label: "IS Manual" },
        "lists": { icon: GiScrollUnfurled, label: "Pilot Registry" },
        "discover": { icon: GiBullseye, label: "New Rivals" },
        "torrent-list": { icon: GiCrystalBall, label: "IS Cache" },
        "debrid": { icon: GiHeartKey, label: "Academy Vault" },
        "unmatched": { icon: GiStarSwirl, label: "Unknown IS" },
        "enmasse": { icon: GiResize, label: "Tournament Battle" },
        "scan-summaries": { icon: TbReportSearch, label: "Battle Reports" },
        "auto-downloader": { icon: LuRss, label: "IS Feed" },
        "community": { icon: GiSpellBook, label: "IS Circle" },
        "achievements": { icon: GiTrophyCup, label: "IS Trophies" },
        "milestones": { icon: LuFlag, label: "Pilot Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "IS Alerts" },
        "theme-manager": { icon: GiPalette, label: "Mech Colors" },
        "extensions": { icon: BiExtension, label: "IS Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "IS Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Ichika Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "Enrolled Male Pilot",
        "a_episode_counter": "Trophies Mark",
        "a_episode_titan": "Trophies Relic",
        "a_hours_invested": "Training Proof",
        "a_time_lord": "Academy Vault Decree",
        "a_anime_collector": "Mech Catalogue",
        "a_library_legend": "Academy Library",
        "a_first_complete": "First IS Battle",
        "a_hundred_club": "Hundred Training Days",
        "a_first_day": "Battle Seal",
        "a_first_rating": "Champion Appraisal",
        "a_ten_thousand_min": "Male Pilot Standard",
        "a_season_veteran": "Infinite Stratos Library",
        "a_year_explorer": "Male Champion Map",
        "a_century_watcher": "Tournament Battle Ledger",
        "a_five_hundred_eps": "Champion Dominion",
        "a_thousand_eps": "Mech Record",
        "a_watching_ten": "Academy Champion Acclaim",
        "a_ptw_hoarder": "Activation Library",
        "a_dropped_honesty": "Infinite Stratos Summit",
        "a_five_thousand_eps": "Trophies Warrant",
        "a_ten_completed": "Male Afterglow",
        "a_fifty_completed": "Pilot Ascension",
        "a_five_hundred_completed": "Sole Clear",
        "a_mean_score_tracker": "Male Champion Verdict",
        "a_unique_studios": "Pilot Registry Collection",
        "a_days_spent_watching": "Male Dominion",
        "a_all_status": "Pilot Testament",
        "a_first_favorite": "Training Cabinet",
        "a_favorites_collector": "Enrolled Male Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Academy Drive",
        "a_marathon_runner": "Male Champion Gauntlet",
        "a_weekend_warrior": "Activation Ordeal",
        "a_non_stop": "Alerts Fever",
        "a_one_more_episode": "Trophies Mantle",
        "a_speed_run": "Marathon Vigil",
        "a_double_feature": "Training Crown",
        "a_triple_threat": "Enrolled Record",
        "a_five_a_day": "Battle Accord",
        "a_back_to_back": "Sole Surge",
        "a_seasonal_binge": "Academy Champion Cascade",
        "a_cour_crusher": "Marathon Ordeal",
        "a_half_day_watch": "Circle Crown",
        "a_full_day_watch": "Enrolled Pinnacle",
        "a_power_weekend": "Sole Run",
        "a_binge_king": "IS Marathon",
        "a_no_sleep": "Circle Vigil",
        "a_entire_season": "Activation Library Library",
        "a_seven_day_challenge": "Mech Mark",
        "a_hundred_day_binge": "Enrolled Male Surge",
        "a_genre_binge": "Enrolled Male Binge",
        "a_studio_binge": "Pilot Fever",
        "a_season_sweep": "Male Codex",
        "a_forty_eight_hour": "Sole Male Overture",
        "a_ep_counter_day": "Infinite Stratos Aegis",
        "a_multi_series_binge": "Training Streak",
        "a_midnight_binge": "Enrolled Male Cascade",
        "a_new_year_binge": "Enrolled Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Male Pilot Action",
        "a_genre_adventure": "Activation Adventure",
        "a_genre_comedy": "Enrolled Male Comedy",
        "a_genre_drama": "Battle Drama",
        "a_genre_fantasy": "Activation Fantasy",
        "a_genre_horror": "Academy Champion Horror",
        "a_genre_mystery": "Battle Mystery",
        "a_genre_romance": "Manual Romance",
        "a_genre_scifi": "Battle Sci-Fi",
        "a_genre_sol": "Academy Champion Slice",
        "a_genre_sports": "Academy Vault Sports",
        "a_genre_supernatural": "Training Supernatural",
        "a_genre_thriller": "Alerts Thriller",
        "a_genre_mecha": "Champion Mecha",
        "a_genre_music": "Academy Vault Music",
        "a_genre_psychological": "Male Pilot Psychological",
        "a_genre_ecchi": "Trophies Ecchi",
        "a_genre_mahou_shoujo": "Ichika Orimura Magic Shoujo",
        "a_tag_isekai": "Marathon Isekai",
        "a_tag_harem": "Academy Harem",
        "a_tag_bl": "Battle Bl",
        "a_tag_gl": "Rivals Gl",
        "a_tag_historical": "Unknown Historical",
        "a_tag_military": "Rivals Military",
        "a_tag_school": "Training School",
        "a_tag_martial_arts": "Academy Champion Martial Arts",
        "a_tag_vampire": "Tournament Battle Vampire",
        "a_tag_samurai": "Circle Samurai",
        "a_tag_space": "Trophies Space",
        "a_tag_parody": "Trophies Parody",
        "a_tag_idol": "Tournament Battle Idol",
        "a_tag_post_apocalyptic": "Activation Post Apocalyptic",
        "a_tag_cyberpunk": "Academy Champion Cyberpunk",
        "a_tag_shounen": "Archive Shounen",
        "a_tag_seinen": "Enrolled Male Pilot Seinen",
        "a_tag_shoujo": "Ichika Orimura Shoujo",
        "a_tag_josei": "Tournament Battle Josei",
        "a_tag_survival": "Fan Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "Academy Champion",
        "a_mega_completionist": "IS Legend",
        "a_completion_rate_50": "Ichika Return",
        "a_completion_rate_75": "Enrolled Crown",
        "a_completion_rate_90": "Pilot Resolution",
        "a_no_drop": "Unknown Decree",
        "a_long_runner_complete": "Unknown Clear",
        "a_sequel_chain": "Infinite Stratos Insignia",
        "a_clean_list": "Fan Relic",
        "a_from_ptw": "Ichika Orimura Index",
        "a_rewatch_master": "Sole Return",
        "a_short_complete": "Mech Endgame",
        "a_same_day_start_finish": "Unknown Pinnacle",
        "a_revival": "Activation Insignia",
        "a_zero_to_hero": "Sole Male to Champion",
        "a_five_genre_complete": "Alerts A Five Genre Complete",
        "a_full_franchise": "Ichika Chronicle",
        "a_batch_complete": "Pilot Registry Crown",
        "a_paused_to_done": "Archive Aegis",
        "a_completion_spree": "Ichika Orimura Triumph",
        "a_multi_rewatch": "Archive Triumph",
        "a_dropped_recovery": "Pilot Conquest",
        "a_ten_perfect_scores": "Ichika Orimura Acclaim",
        "a_seasonal_clear": "Trophies Codex",
        "a_complete_genre_span": "Rivals A Complete Genre Span",
        "a_monthly_completions": "Academy Champion Afterglow",
        "a_yearly_completions": "Male Champion Epilogue",
        "a_rapid_complete": "Academy Vault Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "IS Fan",
        "a_studio_devotee": "Manual Treasury",
        "a_rewatcher": "Marathon Closure",
        "a_triple_rewatch": "Unknown Coda",
        "a_annual_tradition": "Fan Proof",
        "a_director_fan": "Alerts Trial",
        "a_voice_actor_fan": "Unknown Crown",
        "a_ost_lover": "Academy Champion Seal",
        "a_source_reader": "Pilot Cabinet",
        "a_waiting_weekly": "Ichika Orimura Clock",
        "a_childhood_revisit": "Mech Seal",
        "a_saga_tracker": "Academy Standard",
        "a_genre_loyalty": "Enrolled Male Loyalty",
        "a_decade_watcher": "Archive Banner",
        "a_adaptation_hunter": "Unknown Trial",
        "a_original_anime_fan": "Archive Testament",
        "a_long_commitment": "Archive Mark",
        "a_perfect_attendance": "Circle Standard",
        "a_favorite_studio_5": "Pilot Registry Library",
        "a_complete_catalog": "Pilot Seal",
        "a_franchise_collector": "Academy Vault Archive",
        "a_airing_follower": "Fan Signal",
        "a_genre_master": "Male Master",
        "a_staff_follower": "Sole Oath",
        "a_multi_season_fan": "Enrolled Hoard",
        "a_format_diversity": "Tournament Battle Cache",
        "a_year_dedication": "Male Pilot Tenure",
        "a_season_dedication": "Infinite Stratos Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Infinite Stratos Explorer",
        "a_studio_hopper": "Training Collection",
        "a_tag_explorer": "Unknown Explorer",
        "a_decade_hopper": "Academy Vault Chronicle",
        "a_hidden_gem": "Male Pilot Warrant",
        "a_popular_taste": "Enrolled Decree",
        "a_retro_appreciator": "Academy Aegis",
        "a_modern_viewer": "Infinite Stratos Pinnacle",
        "a_cross_demographic": "Battle Pinnacle",
        "a_underdog_fan": "Fan Trial",
        "a_variety_week": "Trophies Horizon",
        "a_foreign_cinema": "Marathon Expedition",
        "a_classic_connoisseur": "Marathon Glimpse",
        "a_every_season": "Academy Archive",
        "a_award_winner": "Rivals Insignia",
        "a_niche_explorer": "Male Pilot Horizon",
        "a_global_anime": "Battle Crown",
        "a_cult_classic": "Male Champion Classic",
        "a_random_pick": "Ichika Orimura Decree",
        "a_new_genre_month": "Trophies A New Genre Month",
        "a_seasonal_completionist": "Battle Summit",
        "a_unpopular_opinion": "Battle Standard",
        "a_top_rated_viewer": "Unknown Seal",
        "a_source_variety": "Alerts Storehouse",
        "a_low_score_brave": "Sole Male Measure",
        "a_upcoming_watcher": "Pilot Registry Seal",
        "a_short_series_explorer": "Enrolled Male Pilot Expedition",
        "a_long_series_explorer": "Tournament Battle Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Enrolled Male Insignia",
        "a_early_bird": "Pilot Registry Banner",
        "a_lunch_break": "Marathon Trial",
        "a_golden_hour": "Enrolled Male Pilot Tenure",
        "a_four_am_club": "Champion Gathering",
        "a_witching_hour": "Enrolled Male Tenure",
        "a_new_year_watch": "Pilot Season",
        "a_midnight_premiere": "Mech Devotion",
        "a_all_hours": "Rivals Seal",
        "a_dawn_warrior": "Marathon Aegis",
        "a_afternoon_delight": "Enrolled Male Proof",
        "a_prime_time": "Pilot Insignia",
        "a_workday_watcher": "Ichika Orimura Pinnacle",
        "a_sunday_marathon": "Alerts Momentum",
        "a_rainy_day": "Sole Male Relic",
        "a_morning_routine": "Male Pilot Promise",
        "a_night_shift": "Academy Champion Aegis",
        "a_twilight_zone": "Academy Vault Ledger",
        "a_seasonal_premier": "Male Champion Cabinet",
        "a_clock_collector": "Alerts Repository",
        "a_weekend_binge_hours": "Tournament Battle Streak",
        "a_late_night_regular": "Manual Dominion",
        "a_sunrise_watcher": "Male Champion Relic",
        "a_holiday_watcher": "Marathon Pact",
        "a_every_day_of_week": "Trophies Ledger",
        "a_monthly_hours": "Training Monthly",

        // ── ANIME SOCIAL ──
        "a_first_party": "Archive Record",
        "a_party_host": "Rivals Record",
        "a_social_butterfly": "Ichika Orimura Company",
        "a_group_binge": "Academy Vault Sprint",
        "a_party_regular": "Enrolled Male Chronicle",
        "a_sync_viewer": "Mech Standard",
        "a_commentator": "Fan Record",
        "a_party_marathon": "Sole Male Vigil",
        "a_full_house": "Tournament Battle Trial",
        "a_community_pillar": "Activation Alliance",
        "a_watch_party_streak": "Battle Vigil",
        "a_diverse_party": "Ichika Orimura Seal",
        "a_late_night_party": "Archive Testament Testament",
        "a_party_veteran": "Male Champion Testament",
        "a_genre_party": "Sole Party",
        "a_weekly_party": "Pilot Registry Calendar",
        "a_silent_viewer": "Tournament Battle Mantle",
        "a_recommendation_giver": "Infinite Stratos Network",
        "a_party_completionist": "Marathon Coda",
        "a_social_scorer": "Infinite Stratos Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Champion Proof",
        "a_fibonacci": "Champion Dominion Dominion",
        "a_palindrome_day": "Male Relic",
        "a_binary_day": "Academy Vault Mark",
        "a_full_moon": "Tournament Battle Insignia",
        "a_leap_year": "Enrolled Male Pilot Devotion",
        "a_time_traveler": "Trophies Record",
        "a_genre_clash": "Academy Vault Clash",
        "a_triple_seven": "Unknown Testament",
        "a_thousand_complete": "Unknown Epilogue",
        "a_pi_episodes": "Marathon Crown",
        "a_synchronicity": "Archive Anchor",
        "a_world_record": "Male Warrant",
        "a_nice": "Sole Male Chronicle",
        "a_power_level": "Rivals Testament",
        "a_answer_42": "Activation Standard",
        "a_square_number": "Ichika Orimura Decree Decree",
        "a_prime_count": "Tournament Battle Seal",
        "a_matching_date": "Unknown Mantle",
        "a_century_episode": "Archive Mark Mark",
        "a_double_digits": "Male Pilot Testament",
        "a_one_two_three": "Pilot Registry Crown Crown",
        "a_lucky_seven": "Battle Crown Crown",
        "a_all_tens": "Alerts Criterion",
        "a_exact_hundred_eps": "Rivals Standard",
        "a_year_match_count": "Ichika Clock",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Male Champion Ledger",
        "a_movie_buff": "Champion Mark",
        "a_ova_hunter": "Sole Standard",
        "a_ona_explorer": "Battle Secret",
        "a_special_watcher": "Academy Champion Relic",
        "a_short_king": "Circle Crown Crown",
        "a_variety_pack": "Academy Inquiry",
        "a_film_festival": "Academy Vault Chronicle Chronicle",
        "a_music_video": "Circle Chronicle",
        "a_tv_short": "Ichika Record",
        "a_movie_marathon": "Enrolled Gauntlet",
        "a_double_length": "Academy Champion Crown",
        "a_anthology": "Circle Aegis",
        "a_mini_series": "Alerts Decree",
        "a_theatrical": "Male Pilot Accord",
        "a_format_master": "Pilot Vault",
        "a_long_movie": "Rivals Insignia Insignia",
        "a_back_catalog": "Male Pilot Standard Standard",
        "a_cm_watcher": "Academy Aegis Aegis",
        "a_pv_collector": "Rivals Storehouse",
        "a_format_balance": "Ichika Vault",
        "a_episodic_master": "Infinite Stratos Standard",
        "a_sequel_movie": "Tournament Battle Pinnacle",
        "a_recap_watcher": "Enrolled Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Ichika Orimura Devotion",
        "a_mega_streak": "Champion Streak",
        "a_weekly_warrior": "Unknown Season",
        "a_monthly_watcher": "Male Champion Calendar",
        "a_comeback": "Battle Decree",
        "a_weekend_streak": "Fan Passage",
        "a_no_zero_days": "Sole Warrant",
        "a_iron_will": "Activation Seal",
        "a_habit_formed": "Pilot Warrant",
        "a_consistent_pace": "Tournament Battle Measure",
        "a_year_long": "Male Champion Season",
        "a_double_streak": "Enrolled Watch",
        "a_streak_recovery": "Sole Season",
        "a_daily_minimum": "Academy Champion Focus",
        "a_winter_streak": "Male Pilot Watch",
        "a_summer_streak": "Battle Resolve",
        "a_morning_streak": "Rivals Clock",
        "a_night_streak": "Rivals Constancy",
        "a_unbreakable": "Enrolled Proof",
        "a_eternal_flame": "Marathon Standard",
        "a_completion_streak": "Academy Vault Return",
        "a_rating_streak": "Manual Balance",
        "a_multi_ep_streak": "Enrolled Male Pilot Ritual",
        "a_genre_streak": "Mech Streak",
        "a_studio_streak": "Activation Cabinet",
        "a_perfect_week": "Tournament Battle Relic",

        // ── ANIME SCORING ──
        "a_critic": "Circle Scrutiny",
        "a_perfect_ten": "Trophies Audit",
        "a_harsh_critic": "Male Champion Gauge",
        "a_fair_judge": "Pilot Registry Balance",
        "a_generous_spirit": "Champion Pinnacle",
        "a_score_all": "Enrolled Criterion",
        "a_wide_range": "Mech Ledger",
        "a_controversial": "Sole Male Decree",
        "a_consistent_scorer": "Marathon Verdict",
        "a_score_sniper": "Enrolled Score",
        "a_evolving_taste": "Male Testament",
        "a_bell_curve": "Trophies Insignia",
        "a_picky_watcher": "Unknown Seal Seal",
        "a_100_rated": "Champion Warrant",
        "a_500_rated": "Unknown Pinnacle Pinnacle",
        "a_mediocre_majority": "Training Canon",
        "a_rating_spree": "Infinite Stratos Review",
        "a_score_variance": "Infinite Stratos Score",
        "a_masterpiece_hunter": "Mech Banner",
        "a_contrarian": "Academy Vault Record",
        "a_optimist": "Academy Ledger",
        "a_score_distributor": "Academy Vault Appraisal",
        "a_genre_critic": "Battle Critic",
        "a_mean_above_8": "Archive Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "Academy Champion Resolve",
        "a_valentines_weeb": "Mech Vow",
        "a_pi_day": "Fan Trial Trial",
        "a_april_fools": "Alerts Devotion",
        "a_international_anime_day": "Enrolled Pinnacle Pinnacle",
        "a_star_wars_day": "Academy Champion Chronicle",
        "a_summer_solstice": "Pilot Registry Calendar Calendar",
        "a_tanabata": "Unknown Focus",
        "a_friday_13th": "Male Relic Relic",
        "a_halloween_spirit": "Ichika Vow",
        "a_thanksgiving_binge": "Sole Male Run",
        "a_christmas_special": "Alerts Season",
        "a_new_years_eve": "Sole Male Pilgrimage",
        "a_birthday_watch": "Battle Vow",
        "a_holiday_marathon": "Sole Overture",
        "a_independence_day": "Tournament Battle Banner",
        "a_culture_day": "Activation Insignia Insignia",
        "a_spring_equinox": "Sole Decree",
        "a_earth_day": "Academy Vault Record Record",
        "a_labor_day": "Sole Seal",
        "a_winter_solstice": "Ichika Pilgrimage",
        "a_anime_birthday": "Male Pilot Pilgrimage",
        "a_every_holiday": "Tournament Battle Resolve",
        "a_consecutive_holidays": "Circle Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Mech Rank",
        "a_meta_collector": "Activation Hoard",
        "a_meta_category_starter": "Champion Badge",
        "a_meta_tier_climber": "Ichika Glyph",
        "a_meta_tier_max": "Ichika Orimura Writ",
        "a_meta_xp_earner": "Pilot Registry Emblem",
        "a_meta_difficulty_easy": "Sole Male Mechanism",
        "a_meta_difficulty_hard": "Academy Vault Writ",
        "a_meta_unlock_spree": "Enrolled Male Pilot Panel",
        "a_meta_completionist": "Sole Male Fulfillment",
        "a_meta_diverse": "Alerts Emblem",
        "a_meta_dominator": "Rivals Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Activation",
        "m_chapter_counter": "Sole Male Pinnacle",
        "m_chapter_titan": "Sole Male Legend",
        "m_reading_hours": "Circle Relic",
        "m_reading_time_lord": "Sole Male Pinnacle Pinnacle",
        "m_manga_collector": "Sole Male Ledger",
        "m_library_legend": "Male Reliquary",
        "m_first_complete": "Marathon Triumph",
        "m_hundred_club": "Infinite Stratos Legend",
        "m_first_day": "Rivals Dawn",
        "m_first_rating": "Tournament Battle Eye",
        "m_ten_thousand_pages": "Academy Champion Gauge",
        "m_volume_collector": "Enrolled Male Storehouse",
        "m_year_explorer": "Fan Quest",
        "m_century_reader": "Male Pilot Dominion",
        "m_five_hundred_ch": "Academy Vault Legend",
        "m_thousand_ch": "Sole Testament",
        "m_reading_ten": "Champion Tenfold",
        "m_ptr_hoarder": "Circle Index",
        "m_dropped_honesty": "Trophies Summit",
        "m_season_reader": "Male Treasury",
        "m_active_reader": "Rivals Trial",
        "m_five_thousand_ch": "Enrolled Male Pilot Standard",
        "m_ten_completed": "Male Pilot Resolution",
        "m_fifty_completed": "Academy Champion Harvest",
        "m_five_hundred_completed": "Pilot Registry Legacy",
        "m_mean_score_tracker": "Enrolled Audit",
        "m_unique_authors": "Academy Champion Reserve",
        "m_all_status": "Manual Testament",
        "m_first_favorite": "Pilot Registry Cache",
        "m_favorites_collector": "Champion Shelf",
        "m_days_spent_reading": "Training Decree",

        // ── MANGA BINGE ──
        "m_binge_reader": "Enrolled Male Streak",
        "m_marathon_reader": "Enrolled Male Pilot Rush",
        "m_weekend_reader": "Infinite Stratos Run",
        "m_non_stop_reading": "Male Pilot Gauntlet",
        "m_one_more_chapter": "Academy Champion Testament",
        "m_speed_read": "Rivals Drive",
        "m_double_story": "Infinite Stratos Banner",
        "m_triple_read": "Pilot Record",
        "m_five_a_day": "Infinite Stratos Insignia Insignia",
        "m_chapter_chain": "Pilot Accord",
        "m_volume_binge": "Rivals Drive Drive",
        "m_power_reader": "Trophies Seal",
        "m_half_day_read": "Champion Aegis",
        "m_full_day_read": "Trophies Aegis",
        "m_power_weekend": "Academy Champion Streak",
        "m_binge_king": "Sole Momentum",
        "m_no_sleep_read": "Academy Champion Rush",
        "m_full_series_rush": "Ichika Orimura Cascade",
        "m_seven_day_challenge": "Mech Warrant",
        "m_hundred_day_read": "Enrolled Relic",
        "m_volume_rush": "Male Pilot Gauntlet Gauntlet",
        "m_series_sweep": "Training Trial",
        "m_genre_binge": "Pilot Registry Binge",
        "m_author_binge": "Male Surge",
        "m_chapter_counter_day": "Champion Ledger",
        "m_multi_series_binge": "Activation Charge",
        "m_midnight_binge": "Enrolled Male Tempest",
        "m_new_year_binge": "Enrolled Male Pilot Passage",
        "m_forty_eight_hour": "Ichika Rally",
        "m_oneshot_binge": "Trophies Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Male Champion Action",
        "m_genre_adventure": "Training Adventure",
        "m_genre_comedy": "Trophies Comedy",
        "m_genre_drama": "Academy Drama",
        "m_genre_fantasy": "Activation Fantasy Style",
        "m_genre_horror": "Sole Male Horror",
        "m_genre_mystery": "Male Pilot Mystery",
        "m_genre_romance": "Circle Romance",
        "m_genre_scifi": "Pilot Registry Sci-Fi",
        "m_genre_sol": "Marathon Slice",
        "m_genre_sports": "Battle Sports",
        "m_genre_supernatural": "Infinite Stratos Supernatural",
        "m_genre_thriller": "Infinite Stratos Thriller",
        "m_genre_psychological": "Academy Psychological",
        "m_genre_isekai": "Unknown Isekai",
        "m_genre_shounen": "Circle Shounen",
        "m_genre_ecchi": "Training Ecchi",
        "m_genre_mahou_shoujo": "Academy Magic Shoujo",
        "m_genre_mecha": "Activation Mecha",
        "m_genre_music": "Archive Music",
        "m_tag_isekai_new": "Academy Isekai New",
        "m_tag_harem": "Enrolled Male Pilot Harem",
        "m_tag_bl": "Activation Bl",
        "m_tag_gl": "Enrolled Gl",
        "m_tag_historical": "Male Champion Historical",
        "m_tag_military": "Manual Military",
        "m_tag_school": "Academy Vault School",
        "m_tag_martial_arts": "Rivals Martial Arts",
        "m_tag_vampire": "Pilot Vampire",
        "m_tag_samurai": "Mech Samurai",
        "m_tag_space": "Academy Space",
        "m_tag_parody": "Circle Parody",
        "m_tag_idol": "Male Pilot Idol",
        "m_tag_post_apocalyptic": "Infinite Stratos Post Apocalyptic",
        "m_tag_cyberpunk": "Male Pilot Cyberpunk",
        "m_tag_shoujo": "Battle Shoujo",
        "m_tag_survival": "Ichika Survival",
        "m_tag_cooking": "Academy Cooking",
        "m_tag_medical": "Tournament Battle Medical",
        "m_tag_villainess": "Mech Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full IS Archive",
        "m_mega_completionist": "Ichika Orimura Resolution",
        "m_completion_rate_50": "Sole Return Return",
        "m_completion_rate_75": "Champion Ascension",
        "m_completion_rate_90": "Enrolled Male Resolution",
        "m_no_drop": "Circle Decree",
        "m_long_runner_complete": "Pilot Clear",
        "m_sequel_chain": "Archive Seal",
        "m_clean_list": "Male Champion Relic Relic",
        "m_from_ptr": "Male Champion Accord",
        "m_reread_master": "Alerts Trial Trial",
        "m_oneshot_complete": "Enrolled Male Ascension",
        "m_same_day_start_finish": "Unknown Crown Crown",
        "m_revival": "Ichika Orimura Accord",
        "m_zero_to_hundred": "Battle Banner",
        "m_five_genre_complete": "Battle M Five Genre Complete",
        "m_full_collection": "Fan Proof Proof",
        "m_batch_complete": "Fan Testament",
        "m_paused_to_done": "Sole Male Standard",
        "m_completion_spree": "Marathon Triumph Triumph",
        "m_format_completionist": "Pilot Registry Testament",
        "m_catch_up": "Training Chronicle",
        "m_multi_reread": "Sole Banner",
        "m_dropped_recovery": "Ichika Orimura Conquest",
        "m_ten_perfect_scores": "Enrolled Male Judgment",
        "m_complete_genre_span": "Activation M Complete Genre Span",
        "m_monthly_completions": "Activation Return",
        "m_yearly_completions": "Enrolled Male Pilot Epilogue",
        "m_rapid_complete": "Sole Finale",
        "m_author_complete": "Unknown Clear Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Enrolled Male Pilot Legacy",
        "m_mangaka_lover": "Enrolled Male Standard",
        "m_rereader": "Manual Relic",
        "m_triple_reread": "Champion Testament",
        "m_annual_reread": "Unknown Banner",
        "m_publisher_fan": "Rivals Mark",
        "m_artist_fan": "Battle Insignia",
        "m_adaptation_compare": "Male Champion Insignia",
        "m_source_material_fan": "Mech Cache",
        "m_waiting_weekly": "Enrolled Male Pilot Streak",
        "m_classic_reader": "Ichika Lantern",
        "m_saga_reader": "Trophies Crown",
        "m_genre_loyalty": "Sole Loyalty",
        "m_decade_reader": "Sole Male Warrant",
        "m_ln_adaptation": "Male Champion Mark",
        "m_original_work": "Archive Standard",
        "m_long_commitment": "Mech Mark Mark",
        "m_up_to_date": "Enrolled Male Pilot Warrant",
        "m_favorite_mangaka": "Rivals Treasury",
        "m_complete_portfolio": "Archive Triumph Triumph",
        "m_franchise_collector": "Pilot Registry Archive",
        "m_serialization_follower": "Circle Handshake",
        "m_genre_master": "Enrolled Male Pilot Master",
        "m_multi_series_author": "Academy Insignia",
        "m_format_diversity": "Ichika Orimura Shelf",
        "m_year_dedication": "Infinite Stratos Tenure",
        "m_ongoing_follower": "Male Pilot Fellowship",
        "m_genre_loyalty_50": "Trophies Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Fan Explorer",
        "m_publisher_hopper": "Academy Champion Record",
        "m_tag_explorer": "Mech Explorer",
        "m_decade_hopper": "Unknown Chronicle",
        "m_hidden_gem": "Sole Male Mark",
        "m_popular_taste": "Training Record",
        "m_retro_reader": "Rivals Testament Testament",
        "m_modern_reader": "Enrolled Male Pilot Seal",
        "m_cross_demographic": "Ichika Orimura Crown",
        "m_underdog_fan": "Sole Male Testament",
        "m_variety_week": "Pilot Horizon",
        "m_manhwa_reader": "Sole Male Proof",
        "m_manhua_reader": "Male Pilot Mantle",
        "m_classic_connoisseur": "Academy Glimpse",
        "m_award_winner": "Circle Seal",
        "m_niche_explorer": "Sole Horizon",
        "m_world_manga": "Sole Male Chronicle Chronicle",
        "m_cult_classic": "Champion Map",
        "m_random_pick": "Male Standard",
        "m_new_genre_month": "Sole M New Genre Month",
        "m_year_completionist": "Unknown Fulfillment",
        "m_unpopular_opinion": "Pilot Aegis",
        "m_top_rated_reader": "Male Champion Pinnacle",
        "m_source_variety": "Rivals Catalogue",
        "m_low_score_brave": "Archive Score",
        "m_short_manga_explorer": "Ichika Orimura Compass",
        "m_long_manga_explorer": "Sole Survey",
        "m_serialization_explorer": "Academy Road",

        // ── MANGA TIME ──
        "m_night_owl": "Tournament Battle Accord",
        "m_early_bird": "Mech Banner Banner",
        "m_lunch_reader": "Pilot Registry Relic",
        "m_commute_reader": "Tournament Battle Tenure",
        "m_four_am_club": "Enrolled Male Fellowship",
        "m_new_year_read": "Champion Pact",
        "m_all_hours": "Tournament Battle Accord Accord",
        "m_prime_time_reader": "Male Pilot Banner",
        "m_workday_reader": "Mech Accord",
        "m_sunday_read": "Circle Standard Standard",
        "m_morning_routine": "Ichika Discipline",
        "m_night_shift_reader": "Mech Accord Accord",
        "m_seasonal_premier_read": "Circle Storehouse",
        "m_clock_collector": "Ichika Orimura Reserve",
        "m_late_night_horror": "Champion Mark Mark",
        "m_afternoon_reader": "Trophies Mantle Mantle",
        "m_golden_hour_reader": "Champion Observance",
        "m_dawn_reader": "Circle Mantle",
        "m_twilight_reader": "Sole Decree Decree",
        "m_midnight_start": "Pilot Routine",
        "m_weekend_binge_hours": "Unknown Momentum",
        "m_late_night_regular": "Ichika Orimura Testament",
        "m_sunrise_reader": "Ichika Record Record",
        "m_every_day_of_week": "Rivals Seal Seal",
        "m_monthly_hours": "Rivals Vigil",
        "m_bedtime_reader": "Unknown Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Male Pilot Mantle Mantle",
        "m_webtoon_reader": "Enrolled Male Pilot Mark",
        "m_full_color": "Manual Accord",
        "m_doujin_reader": "Tournament Battle Record",
        "m_anthology_reader": "Academy Vault Accord",
        "m_adaptation_reader": "Academy Vault Banner",
        "m_longstrip_reader": "Circle Trial",
        "m_4koma_reader": "Champion Relic",
        "m_oneshot_reader": "Archive Mantle",
        "m_format_variety": "Fan Gallery",
        "m_light_novel_reader": "Marathon Insignia",
        "m_novel_reader": "Enrolled Male Pilot Crown",
        "m_visual_storyteller": "Enrolled Male Pilot Testament",
        "m_colored_classic": "Rivals Survey",
        "m_webcomic_fan": "Male Insignia",
        "m_manga_to_anime": "Sole Male Record",
        "m_seinen_reader": "Sole Pinnacle",
        "m_josei_reader": "Academy Pinnacle",
        "m_award_winning_art": "Enrolled Male Relic",
        "m_debut_work": "Fan Dominion",
        "m_vertical_scroll": "Activation Crown",
        "m_traditional_format": "Fan Hoard",
        "m_cross_media": "Enrolled Male Accord",
        "m_spinoff_reader": "Ichika Accord",
        "m_remake_reader": "Archive Pinnacle",
        "m_collaboration_reader": "Pilot Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Infinite Stratos Focus",
        "m_mega_streak": "Academy Champion Routine",
        "m_weekly_warrior": "Activation Season",
        "m_monthly_reader": "Male Champion Discipline",
        "m_comeback": "Alerts Standard",
        "m_weekend_streak": "Mech Fever",
        "m_no_zero_days": "Tournament Battle Proof",
        "m_iron_will": "Battle Ledger",
        "m_habit_formed": "Activation Decree",
        "m_consistent_pace": "Academy Scrutiny",
        "m_year_long": "Activation Observance",
        "m_double_streak": "Manual Resolve",
        "m_streak_recovery": "Pilot Registry Resolve",
        "m_daily_minimum": "Marathon Focus",
        "m_winter_streak": "Circle Observance",
        "m_summer_streak": "Training Observance",
        "m_morning_streak": "Unknown Clock",
        "m_night_streak": "Ichika Discipline Discipline",
        "m_unbreakable": "Ichika Warrant",
        "m_eternal_flame": "Infinite Stratos Record",
        "m_chapter_a_day": "Unknown Relic",
        "m_genre_streak": "Tournament Battle Streak Mode",
        "m_completion_streak": "Sole Male Return",
        "m_rating_streak": "Circle Appraisal",
        "m_multi_ch_streak": "Sole Male Tenure",
        "m_author_streak": "Activation Calendar",
        "m_perfect_week_manga": "Sole Accord",
        "m_diverse_streak": "Enrolled Streak",

        // ── MANGA SCORING ──
        "m_critic": "Academy Champion Scrutiny",
        "m_perfect_ten": "Mech Verdict",
        "m_harsh_critic": "Training Scale",
        "m_fair_judge": "Alerts Eye",
        "m_generous_spirit": "Pilot Crown",
        "m_score_all": "Academy Vault Reckoning",
        "m_wide_range": "Tournament Battle Ledger Ledger",
        "m_controversial": "Academy Champion Testament Testament",
        "m_consistent_scorer": "Alerts Grade",
        "m_score_sniper": "Marathon Reckoning",
        "m_evolving_taste": "Pilot Trial",
        "m_bell_curve": "Enrolled Male Accord Accord",
        "m_picky_reader": "Manual Relic Relic",
        "m_100_rated": "Sole Mark",
        "m_500_rated": "Infinite Stratos Proof",
        "m_mediocre_majority": "Marathon Canon",
        "m_rating_spree": "Male Pilot Verdict",
        "m_score_variance": "Enrolled Male Measure",
        "m_binge_rater": "Marathon Passage",
        "m_reread_rerate": "Infinite Stratos Banner Banner",
        "m_masterpiece_hunter": "Pilot Banner",
        "m_contrarian": "Male Aegis",
        "m_optimist": "Male Accord",
        "m_score_distributor": "Male Champion Balance",
        "m_genre_critic": "Marathon Critic",
        "m_mean_above_8": "Fan Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Alerts New Year",
        "m_valentines_read": "Ichika Orimura Observance",
        "m_pi_day": "Training Testament",
        "m_april_fools": "Academy Devotion",
        "m_international_manga_day": "Circle Proof",
        "m_free_comic_day": "Manual Chronicle",
        "m_summer_solstice": "Marathon Focus Focus",
        "m_tanabata": "Activation Pilgrimage",
        "m_friday_13th": "Academy Dominion",
        "m_halloween_read": "Enrolled Male Calendar",
        "m_thanksgiving_binge": "Male Champion Charge",
        "m_christmas_read": "Fan Pact",
        "m_new_years_eve": "Circle Pilgrimage",
        "m_birthday_read": "Male Focus",
        "m_holiday_marathon": "Battle Rally",
        "m_independence_day": "Rivals Aegis",
        "m_culture_day": "Alerts Seal",
        "m_spring_equinox": "Ichika Banner",
        "m_earth_day": "Enrolled Male Pilot Aegis",
        "m_labor_day": "Ichika Seal",
        "m_winter_solstice": "Enrolled Male Pilot Focus",
        "m_manga_birthday": "Trophies Ritual",
        "m_every_holiday_reader": "Fan Watch",
        "m_consecutive_holidays": "Academy Champion Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Champion Proof Proof",
        "m_fibonacci": "Pilot Registry Dominion",
        "m_palindrome_day": "Mech Ledger Ledger",
        "m_binary_day": "Ichika Orimura Proof",
        "m_full_moon_read": "Sole Crown",
        "m_leap_year_read": "Pilot Registry Practice",
        "m_triple_seven": "Male Champion Trial",
        "m_thousand_complete": "Academy Vault Ascension",
        "m_nice": "Fan Seal",
        "m_power_level_chapters": "Unknown Aegis",
        "m_answer_42": "Sole Aegis",
        "m_square_number": "Marathon Standard Standard",
        "m_prime_count": "Training Insignia",
        "m_matching_date": "Activation Mantle",
        "m_century_chapter": "Archive Crown",
        "m_pi_chapters": "Ichika Orimura Proof Proof",
        "m_synchronicity": "Battle Emblem",
        "m_world_record": "Archive Warrant",
        "m_genre_clash": "Enrolled Male Clash",
        "m_time_traveler": "Sole Male Decree Decree",
        "m_double_digits": "Enrolled Male Pilot Dominion",
        "m_one_two_three": "Archive Warrant Warrant",
        "m_lucky_seven": "Pilot Registry Pinnacle",
        "m_exact_hundred_ch": "Archive Legend",
        "m_year_match_count": "Fan Routine",
        "m_chapter_match_date": "Trophies Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Activation Index",
        "m_manhwa_format": "Activation Gallery",
        "m_manhua_format": "Sole Storehouse",
        "m_ln_format": "Enrolled Index",
        "m_oneshot_format": "Unknown Index",
        "m_doujin_format": "Tournament Battle Cabinet",
        "m_novel_format": "Enrolled Male Pilot Reserve",
        "m_format_master_manga": "Enrolled Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Sole Link",
        "m_meta_collector": "Fan Reliquary",
        "m_meta_category_starter": "Academy Champion Key",
        "m_meta_tier_climber": "Unknown Token",
        "m_meta_tier_max": "Champion Token",
        "m_meta_xp_earner": "Pilot Registry Anchor",
        "m_meta_difficulty_easy": "Marathon Panel",
        "m_meta_difficulty_hard": "Ichika Seal Seal",
        "m_meta_unlock_spree": "Activation Marker",
        "m_meta_completionist": "Manual Triumph",
        "m_meta_diverse": "Enrolled Male Anchor",
        "m_meta_dominator": "Sole Male Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#000208",
        primary: "#1255d0",
        secondary: "#cc4040",
        accent: "#a8c8f8",
    },
    particleColor: "#3878e0",
    backgroundDim: 0.28,
    backgroundBlur: 18,
    milestoneNames: {
  1: "Threadbare Ichika Orimura Spark",
  8: "Suit's Tarnished Omen",
  14: "Fractured Female Academy",
  21: "IS Path",
  28: "Lowborn Begins Myth",
  35: "Houki Classmate Pulse",
  41: "Chifuyu's Authority Force",
  48: "Humble Training Mark",
  55: "Ragged Rin Cecilia Vow",
  61: "Pilot's Faint Echo",
  68: "Lesser Combat Simulation",
  75: "Romantic Misunderstanding Zenith",
  81: "Doubtful Legacy Clash",
  88: "Second Year Sigil",
  95: "Ichika's Surge Flame",
  102: "Really Cool Suit Spark",
  108: "Awakened Pilot Skill Omen",
  115: "Rival's Resolute Seal",
  122: "Rising Orimura Family",
  128: "Combat Training Myth",
  135: "Dauntless Legacy Pulse",
  142: "Charlotte Disguise Secret",
  149: "Confusion's Emotional Soul",
  155: "Fresh Duel Clash",
  162: "Valiant Team Chaos Form",
  169: "Cecilia's Prime Crown",
  175: "Polished Houki",
  182: "Rin Competitive Bloom",
  189: "Stormlit Legacy Sigil",
  195: "International Flame",
  202: "Technology's IS Spark",
  209: "Tempered Combat Omen",
  216: "Trusted Romantic Entanglement Seal",
  222: "Academy's Steadfast Path",
  229: "Ironclad Pilot Ranking",
  236: "IS Clash",
  242: "Core Legacy Crest",
  249: "Multi Rival Mark",
  256: "Bonds's Emotional Vow",
  262: "Formidable Combat Echo",
  269: "Lucid Laura Rivalry Crown",
  276: "Charlotte's Ranked Clash",
  283: "Fabled Houki Breakpoints",
  289: "Tactical IS Form",
  296: "Seasoned Chaos Flame",
  303: "International Clash",
  309: "Pilot's Training Omen",
  316: "Valorous Romantic Seal",
  323: "Stalwart Academy Strain Force",
  330: "Infinite's Commanding Force",
  336: "Refined Battlefield Simulation",
  343: "Threat Organizations Secret",
  350: "Blazing Responsibility Mark",
  356: "Overload Soul",
  363: "Rival's Moments Echo",
  370: "Peerless Duel Clash",
  376: "Ardent Romantic Attempts Zenith",
  383: "Turning's Focused Bloom",
  390: "Vigilant External Nation",
  397: "IS Flame",
  403: "Elite Emotional Soul",
  410: "Ichika Leadership Omen",
  417: "Team's Legacy Form",
  423: "Sovereign Large Clash",
  430: "Regal Romantic Rival Myth",
  437: "Strategic's Crowned Form",
  444: "Mythborn Revealed",
  450: "Academy Crisis Mark",
  457: "Radiant Final Clash",
  464: "Character Battles Clash",
  470: "Ichika's Legacy Form",
  477: "Climactic Rival Zenith",
  484: "Epic Combat Fusion Soul",
  490: "Post's Unreal Clash",
  497: "Peak Academy",
  504: "Emotional Soul",
  511: "Exalted Direction Omen",
  517: "Peaceful School Haven",
  524: "Political's Returns Path",
  531: "Celestial Dormant Myth",
  537: "Phantom Character Relationship Force",
  544: "Era's Crimson Crest",
  551: "Silver Quiet",
  557: "Everyday Academy Vow",
  564: "Feral Readiness Echo",
  571: "Friendship Vow",
  578: "Romantic's Aftermath Zenith",
  584: "Dread Routine Bloom",
  591: "Luminous Emotional Soul",
  598: "International's Thunderous Clash",
  604: "Ultraviolet Pilot Acceptance",
  611: "Balanced Academy Omen",
  618: "Secret Period Seal",
  625: "Dormant Signals Clash",
  631: "Achieved's Emotional Soul",
  638: "Worldclass Mecha Pulse",
  645: "Lawless Legend Infinite Crest",
  651: "Pilot's Chosen Mark",
  658: "Fearless Ichika Orimura",
  665: "Academy Rivalry Echo",
  671: "Cinematic Hangars Crown",
  678: "Dormant Political Zenith",
  685: "Battles's Memory Echo",
  692: "Canonized Pilot Sigil",
  698: "Ascendant Academy Chronicle Clash",
  705: "Quiet's Transfigured Spark",
  712: "Immortal Dormant Echo",
  718: "Balance Clash",
  725: "Astral Stratos Path",
  732: "Mecha Harem Clash",
  739: "Ichika's Story Pulse",
  745: "Prismatic Combat Crest",
  752: "Abyssal Silent Sky Mark",
  759: "Dormant's Unbound Force",
  765: "Eternal Legend Mecha",
  772: "Cycle Rivalry Crown",
  779: "Transcendent Myth Clash",
  785: "Academy Warfare Clash",
  792: "Love's Legacy Sigil",
  799: "Ultimate Pilot Flame",
  806: "Mythic Emotion Soul",
  812: "Growth's Godlike Omen",
  819: "Canonical Mastery",
  826: "Ichika Synchronization Path",
  832: "Heavenly Legacy Myth",
  839: "Academy Unity Pulse",
  846: "Closure's Emotional Soul",
  852: "Timeless Acceptance Vow",
  859: "Empyrean Pilot Formed Form",
  866: "War's Primordial Clash",
  873: "Omniscient Narrative Mecha",
  879: "Infinite Stratos Zenith",
  886: "Apocalyptic Battle Clash",
  893: "Resolution Soul",
  899: "Infinite's Truth Secret",
  906: "Final Origin Secret",
  913: "Crowned Conflict Desire Clash",
  920: "Mecha's Mythic Seal",
  926: "Absolute Legend Infinite",
  933: "Combat Flow Myth",
  940: "Cosmic Legacy Pulse",
  946: "Synchronization Crest",
  953: "Pilot's Perfect Mark",
  960: "Definitive Ultimate Soul",
  966: "Ultimate Accidentally Entered Vow",
  973: "Accidentally's Infinite Vow",
  980: "Sovereign Accidentally Entered",
  987: "Accidentally Entered Vow",
  993: "Legendary All Vow",
  1000: "Ultimate Ultimate Combat"
}
}
