import { AnimeThemeConfig } from "./types"
import { GiCrystalBall, GiPunch, GiScrollUnfurled, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiSpellBook, GiStarSwirl, GiFist, GiCrossedSwords, GiHeartKey } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const jojoBizarreAdventureTheme: AnimeThemeConfig = {
    id: "jojo-bizarre-adventure",
    displayName: "JoJo's Bizarre Adventure",
    description: "WRRYYYY! The Joestar bloodline battles Stands, vampires, and ultimate beings across generations. Bold poses, golden winds, and an unforgettable art style await.",
    fontFamily: "'Bebas Neue', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap",
    cssVars: {
        "--color-brand-200": "255 240 150",
        "--color-brand-300": "255 220 80",
        "--color-brand-400": "255 195 20",
        "--color-brand-500": "220 155 0",
        "--color-brand-600": "170 110 0",
        "--color-brand-700": "120 70 0",
        "--color-brand-800": "75 38 0",
        "--color-brand-900": "40 18 0",
        "--color-brand-950": "18 6 0",
        "--brand": "220 155 0",
        "--background": "#0a0600",
        "--paper": "#150c00",
        "--color-gray-950": "10 6 0",
        "--color-gray-900": "22 14 2",
        "--color-gray-800": "42 26 5",
        "--color-gray-700": "66 44 10",
        "--color-gray-600": "95 65 20",
        "--color-gray-500": "138 100 40",
        "--color-gray-400": "180 140 70",
        "--color-gray-300": "215 182 110",
        "--color-gray-200": "240 215 155",
        "--color-gray-100": "252 238 196",
        "--color-gray-50": "255 249 230",
    },
    sidebarOverrides: {
        "home": { icon: GiFist, label: "Joestar Estate" },
        "schedule": { icon: GiAlarmClock, label: "Stand Schedule" },
        "manga": { icon: LuBookOpen, label: "Joestar Archives" },
        "lists": { icon: GiScrollUnfurled, label: "Part Registry" },
        "discover": { icon: GiBullseye, label: "Discover Stands" },
        "torrent-list": { icon: GiCrossedSwords, label: "Battle Cache" },
        "debrid": { icon: GiCrystalBall, label: "Arrow Vault" },
        "unmatched": { icon: GiHeartKey, label: "Missing Parts" },
        "enmasse": { icon: GiResize, label: "Part Sweep" },
        "scan-summaries": { icon: TbReportSearch, label: "Battle Reports" },
        "auto-downloader": { icon: LuRss, label: "Stand Alerts" },
        "community": { icon: GiPunch, label: "Joestar Circle" },
        "achievements": { icon: GiTrophyCup, label: "Joestar Trophies" },
        "milestones": { icon: LuFlag, label: "Part Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Stand Alerts" },
        "theme-manager": { icon: GiPalette, label: "Bizarre Palette" },
        "extensions": { icon: BiExtension, label: "Stand Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Joestar Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Hamon Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Bizarre Adventure",
        "a_episode_counter": "Part Sweep Mark",
        "a_episode_titan": "Archive Relic",
        "a_hours_invested": "Loyal Proof",
        "a_time_lord": "ZA WARUDO",
        "a_anime_collector": "Midnight Catalogue",
        "a_library_legend": "Stand Battle Library",
        "a_first_complete": "Part Cleared",
        "a_hundred_club": "Hundred Stands",
        "a_first_day": "Midnight Stand Seal",
        "a_first_rating": "Joestar Marathon Appraisal",
        "a_ten_thousand_min": "Joestar Marathon Standard",
        "a_season_veteran": "Archive Library",
        "a_year_explorer": "Weakling Hamon Map",
        "a_century_watcher": "Missing Parts Ledger",
        "a_five_hundred_eps": "Archive Dominion",
        "a_thousand_eps": "Loyalist Record",
        "a_watching_ten": "Weakling Hamon Acclaim",
        "a_ptw_hoarder": "Joestar Trophies Library",
        "a_dropped_honesty": "Part Cleared Summit",
        "a_five_thousand_eps": "Joestar Circle Warrant",
        "a_ten_completed": "Stand Battle Afterglow",
        "a_fifty_completed": "Loyalist Ascension",
        "a_five_hundred_completed": "Weakling Clear",
        "a_mean_score_tracker": "Hamon Verdict",
        "a_unique_studios": "All Parts Collection",
        "a_days_spent_watching": "Bizarre Palette Dominion",
        "a_all_status": "Jojo's Bizarre Adventure Testament",
        "a_first_favorite": "Wrryyyy Cabinet",
        "a_favorites_collector": "Part Cleared Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Joestar Loyalist Drive",
        "a_marathon_runner": "Stands Gauntlet",
        "a_weekend_warrior": "Adventure Ordeal",
        "a_non_stop": "Master Fever",
        "a_one_more_episode": "Midnight Stand Mantle",
        "a_speed_run": "Joestar Fan Vigil",
        "a_double_feature": "Bizarre Adventure Crown",
        "a_triple_threat": "Bizarre Palette Record",
        "a_five_a_day": "Midnight Stand Accord",
        "a_back_to_back": "Cleared Surge",
        "a_seasonal_binge": "Bizarre Cascade",
        "a_cour_crusher": "Joestar Trophies Ordeal",
        "a_half_day_watch": "Arrow Vault Crown",
        "a_full_day_watch": "Joestar Circle Pinnacle",
        "a_power_weekend": "Weakling Run",
        "a_binge_king": "Joestar Marathon",
        "a_no_sleep": "All Parts Vigil",
        "a_entire_season": "Midnight Stand Battle Library",
        "a_seven_day_challenge": "Loyal Mark",
        "a_hundred_day_binge": "Cleared Legend",
        "a_genre_binge": "Joestar Estate Binge",
        "a_studio_binge": "Marathon Fever",
        "a_season_sweep": "Midnight Stand Codex",
        "a_forty_eight_hour": "Midnight Stand Overture",
        "a_ep_counter_day": "Wrryyyy Aegis",
        "a_multi_series_binge": "Za Warudo Streak",
        "a_midnight_binge": "Hamon Master Cascade",
        "a_new_year_binge": "Wrryyyy Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Part Cleared Action",
        "a_genre_adventure": "Arrow Vault Adventure",
        "a_genre_comedy": "Stand Alerts Comedy",
        "a_genre_drama": "Stand Alerts Drama",
        "a_genre_fantasy": "Stand Fantasy",
        "a_genre_horror": "Joestar Horror",
        "a_genre_mystery": "Loyal Joestar Fan Mystery",
        "a_genre_romance": "Za Warudo Romance",
        "a_genre_scifi": "Missing Parts Sci-Fi",
        "a_genre_sol": "Stands Slice",
        "a_genre_sports": "Part Registry Sports",
        "a_genre_supernatural": "Midnight Stand Battle Supernatural",
        "a_genre_thriller": "Loyal Thriller",
        "a_genre_mecha": "Joestar Archives Mecha",
        "a_genre_music": "Marathon Music",
        "a_genre_psychological": "Bizarre Psychological",
        "a_genre_ecchi": "Hamon Master Ecchi",
        "a_genre_mahou_shoujo": "All Parts Cleared Magic Shoujo",
        "a_tag_isekai": "Marathon Isekai",
        "a_tag_harem": "All Parts Harem",
        "a_tag_bl": "Za Warudo Bl",
        "a_tag_gl": "Parts Cleared Gl",
        "a_tag_historical": "Joestar Estate Historical",
        "a_tag_military": "Joestar Fan Military",
        "a_tag_school": "All Parts School",
        "a_tag_martial_arts": "Za Warudo Martial Arts",
        "a_tag_vampire": "Weakling Hamon Vampire",
        "a_tag_samurai": "Master Samurai",
        "a_tag_space": "Archive Space",
        "a_tag_parody": "All Parts Parody",
        "a_tag_idol": "Cleared Idol",
        "a_tag_post_apocalyptic": "All Parts Post Apocalyptic",
        "a_tag_cyberpunk": "Joestar Loyalist Cyberpunk",
        "a_tag_shounen": "Joestar Estate Shounen",
        "a_tag_seinen": "Loyal Joestar Fan Seinen",
        "a_tag_shoujo": "Adventure Shoujo",
        "a_tag_josei": "Loyal Joestar Fan Josei",
        "a_tag_survival": "Joestar Loyalist Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "All Parts Cleared",
        "a_mega_completionist": "Joestar Legend",
        "a_completion_rate_50": "Loyal Joestar Fan Return",
        "a_completion_rate_75": "Weakling Hamon Crown",
        "a_completion_rate_90": "Cleared Resolution",
        "a_no_drop": "Parts Cleared Decree",
        "a_long_runner_complete": "Loyalist Clear",
        "a_sequel_chain": "Stand Insignia",
        "a_clean_list": "Midnight Stand Relic",
        "a_from_ptw": "Hamon Index",
        "a_rewatch_master": "Arrow Vault Return",
        "a_short_complete": "All Parts Cleared Endgame",
        "a_same_day_start_finish": "Joestar Archives Pinnacle",
        "a_revival": "Joestar Archives Insignia",
        "a_zero_to_hero": "Weakling to Hamon Master",
        "a_five_genre_complete": "Stand Battle A Five Genre",
        "a_full_franchise": "Bizarre Palette Chronicle",
        "a_batch_complete": "Parts Cleared Crown",
        "a_paused_to_done": "Adventure Aegis",
        "a_completion_spree": "Hamon Triumph",
        "a_multi_rewatch": "Part Triumph",
        "a_dropped_recovery": "Bizarre Palette Conquest",
        "a_ten_perfect_scores": "Joestar Circle Acclaim",
        "a_seasonal_clear": "Missing Parts Codex",
        "a_complete_genre_span": "Midnight Stand Battle A Complete",
        "a_monthly_completions": "Part Cleared Afterglow",
        "a_yearly_completions": "Stands Epilogue",
        "a_rapid_complete": "Wrryyyy Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Joestar Loyalist",
        "a_studio_devotee": "Loyalist Treasury",
        "a_rewatcher": "Parts Closure",
        "a_triple_rewatch": "Joestar Circle Coda",
        "a_annual_tradition": "Master Proof",
        "a_director_fan": "Missing Parts Trial",
        "a_voice_actor_fan": "Bizarre Crown",
        "a_ost_lover": "Part Cleared Seal",
        "a_source_reader": "Wrryyyy Cabinet Cabinet",
        "a_waiting_weekly": "Stands Clock",
        "a_childhood_revisit": "Battle Seal",
        "a_saga_tracker": "Midnight Stand Standard",
        "a_genre_loyalty": "Stand Alerts Loyalty",
        "a_decade_watcher": "Missing Parts Banner",
        "a_adaptation_hunter": "Hamon Trial",
        "a_original_anime_fan": "Part Registry Testament",
        "a_long_commitment": "Loyalist Mark",
        "a_perfect_attendance": "Joestar Standard",
        "a_favorite_studio_5": "Bizarre Adventure Library",
        "a_complete_catalog": "Jojo's Bizarre Adventure Seal",
        "a_franchise_collector": "Joestar Trophies Archive",
        "a_airing_follower": "Bizarre Adventure Signal",
        "a_genre_master": "Joestar Marathon Master",
        "a_staff_follower": "Archive Oath",
        "a_multi_season_fan": "All Parts Hoard",
        "a_format_diversity": "Bizarre Cache",
        "a_year_dedication": "Part Cleared Tenure",
        "a_season_dedication": "Part Cleared Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Bizarre Explorer",
        "a_studio_hopper": "Part Cleared Collection",
        "a_tag_explorer": "All Parts Explorer",
        "a_decade_hopper": "Wrryyyy Chronicle",
        "a_hidden_gem": "Cleared Warrant",
        "a_popular_taste": "Stand Battle Decree",
        "a_retro_appreciator": "Part Aegis",
        "a_modern_viewer": "Joestar Loyalist Pinnacle",
        "a_cross_demographic": "Stand Alerts Pinnacle",
        "a_underdog_fan": "All Parts Cleared Trial",
        "a_variety_week": "Bizarre Horizon",
        "a_foreign_cinema": "Loyalist Expedition",
        "a_classic_connoisseur": "Stands Glimpse",
        "a_every_season": "Za Warudo Archive",
        "a_award_winner": "Part Registry Insignia",
        "a_niche_explorer": "Wrryyyy Horizon",
        "a_global_anime": "Archive Crown",
        "a_cult_classic": "Archive Map",
        "a_random_pick": "Midnight Stand Decree",
        "a_new_genre_month": "Midnight Stand A New Genre",
        "a_seasonal_completionist": "Parts Summit",
        "a_unpopular_opinion": "Joestar Archives Standard",
        "a_top_rated_viewer": "Joestar Circle Seal",
        "a_source_variety": "Missing Parts Storehouse",
        "a_low_score_brave": "Joestar Archives Measure",
        "a_upcoming_watcher": "All Parts Seal",
        "a_short_series_explorer": "Hamon Master Expedition",
        "a_long_series_explorer": "Part Sweep Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Midnight Stand Battle",
        "a_early_bird": "Joestar Circle Banner",
        "a_lunch_break": "Part Sweep Trial",
        "a_golden_hour": "Bold Tenure",
        "a_four_am_club": "Midnight Stand Battle Gathering",
        "a_witching_hour": "Part Sweep Tenure",
        "a_new_year_watch": "Midnight Stand Season",
        "a_midnight_premiere": "Adventure Devotion",
        "a_all_hours": "Part Registry Seal",
        "a_dawn_warrior": "Joestar Marathon Aegis",
        "a_afternoon_delight": "Archive Proof",
        "a_prime_time": "Arrow Vault Insignia",
        "a_workday_watcher": "Master Pinnacle",
        "a_sunday_marathon": "Bold Momentum",
        "a_rainy_day": "Part Relic",
        "a_morning_routine": "Midnight Stand Battle Promise",
        "a_night_shift": "Stand Battle Aegis",
        "a_twilight_zone": "Midnight Stand Ledger",
        "a_seasonal_premier": "Joestar Cabinet",
        "a_clock_collector": "Za Warudo Repository",
        "a_weekend_binge_hours": "Midnight Stand Streak",
        "a_late_night_regular": "Bizarre Adventure Dominion",
        "a_sunrise_watcher": "Archive Relic Relic",
        "a_holiday_watcher": "Joestar Fan Pact",
        "a_every_day_of_week": "Part Cleared Ledger",
        "a_monthly_hours": "Loyal Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Loyal Joestar Record",
        "a_party_host": "Midnight Stand Battle Record",
        "a_social_butterfly": "All Parts Company",
        "a_group_binge": "Stands Sprint",
        "a_party_regular": "Loyal Joestar Chronicle",
        "a_sync_viewer": "Bizarre Adventure Standard",
        "a_commentator": "Joestar Estate Record",
        "a_party_marathon": "Bold Vigil",
        "a_full_house": "Joestar Circle Trial",
        "a_community_pillar": "Marathon Alliance",
        "a_watch_party_streak": "Weakling Vigil",
        "a_diverse_party": "Marathon Seal",
        "a_late_night_party": "Stand Testament",
        "a_party_veteran": "Stands Testament",
        "a_genre_party": "Midnight Party",
        "a_weekly_party": "Arrow Vault Calendar",
        "a_silent_viewer": "Archive Mantle",
        "a_recommendation_giver": "Stand Alerts Network",
        "a_party_completionist": "Part Cleared Coda",
        "a_social_scorer": "Adventure Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Joestar Loyalist Proof",
        "a_fibonacci": "Joestar Trophies Dominion",
        "a_palindrome_day": "Weakling Hamon Relic",
        "a_binary_day": "Part Cleared Mark",
        "a_full_moon": "Bizarre Adventure Insignia",
        "a_leap_year": "Stands Devotion",
        "a_time_traveler": "All Parts Record",
        "a_genre_clash": "Bizarre Palette Clash",
        "a_triple_seven": "Midnight Stand Battle Testament",
        "a_thousand_complete": "Marathon Epilogue",
        "a_pi_episodes": "Part Sweep Crown",
        "a_synchronicity": "Part Anchor",
        "a_world_record": "Part Cleared Warrant",
        "a_nice": "Stands Chronicle",
        "a_power_level": "Loyal Testament",
        "a_answer_42": "Part Sweep Standard",
        "a_square_number": "Arrow Vault Decree",
        "a_prime_count": "Loyal Joestar Fan Seal",
        "a_matching_date": "Part Sweep Mantle",
        "a_century_episode": "Part Cleared Mark Mark",
        "a_double_digits": "Battle Testament",
        "a_one_two_three": "Hamon Master Crown",
        "a_lucky_seven": "Loyalist Crown",
        "a_all_tens": "Weakling Hamon Criterion",
        "a_exact_hundred_eps": "Weakling Standard",
        "a_year_match_count": "Stand Battle Clock",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Joestar Fan Ledger",
        "a_movie_buff": "Hamon Master Mark",
        "a_ova_hunter": "Master Standard",
        "a_ona_explorer": "Joestar Estate Secret",
        "a_special_watcher": "Wrryyyy Relic",
        "a_short_king": "Stand Crown",
        "a_variety_pack": "Part Cleared Inquiry",
        "a_film_festival": "Warudo Chronicle",
        "a_music_video": "Part Registry Chronicle",
        "a_tv_short": "Joestar Trophies Record",
        "a_movie_marathon": "Bizarre Palette Gauntlet",
        "a_double_length": "Loyal Joestar Crown",
        "a_anthology": "Joestar Aegis",
        "a_mini_series": "Parts Cleared Decree Decree",
        "a_theatrical": "Joestar Trophies Accord",
        "a_format_master": "Joestar Circle Vault",
        "a_long_movie": "Joestar Archives Insignia Insignia",
        "a_back_catalog": "Joestar Standard Standard",
        "a_cm_watcher": "Part Registry Aegis",
        "a_pv_collector": "Arrow Vault Storehouse",
        "a_format_balance": "Loyal Joestar Fan Vault",
        "a_episodic_master": "Weakling Hamon Standard",
        "a_sequel_movie": "Bizarre Adventure Pinnacle",
        "a_recap_watcher": "Joestar Loyalist Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Battle Devotion",
        "a_mega_streak": "Parts Streak",
        "a_weekly_warrior": "Joestar Marathon Season",
        "a_monthly_watcher": "Loyal Joestar Fan Calendar",
        "a_comeback": "Stand Alerts Decree",
        "a_weekend_streak": "Hamon Passage",
        "a_no_zero_days": "Part Warrant",
        "a_iron_will": "Stand Battle Seal",
        "a_habit_formed": "Midnight Warrant",
        "a_consistent_pace": "Part Cleared Measure",
        "a_year_long": "Midnight Stand Yearlong",
        "a_double_streak": "Cleared Watch",
        "a_streak_recovery": "Stand Battle Season",
        "a_daily_minimum": "Archive Focus",
        "a_winter_streak": "Joestar Trophies Watch",
        "a_summer_streak": "Parts Cleared Resolve",
        "a_morning_streak": "Missing Parts Clock",
        "a_night_streak": "Part Constancy",
        "a_unbreakable": "Parts Cleared Proof",
        "a_eternal_flame": "Weakling Standard Standard",
        "a_completion_streak": "Weakling Hamon Return",
        "a_rating_streak": "All Parts Cleared Balance",
        "a_multi_ep_streak": "All Parts Cleared Ritual",
        "a_genre_streak": "Hamon Streak",
        "a_studio_streak": "Loyal Joestar Cabinet",
        "a_perfect_week": "Stand Battle Relic",

        // ── ANIME SCORING ──
        "a_critic": "Master Scrutiny",
        "a_perfect_ten": "Joestar Trophies Audit",
        "a_harsh_critic": "Loyal Joestar Fan Gauge",
        "a_fair_judge": "Stands Balance",
        "a_generous_spirit": "Joestar Trophies Pinnacle",
        "a_score_all": "Joestar Fan Criterion",
        "a_wide_range": "Bizarre Ledger",
        "a_controversial": "Adventure Decree",
        "a_consistent_scorer": "Jojo's Bizarre Adventure Verdict",
        "a_score_sniper": "Warudo Score",
        "a_evolving_taste": "All Parts Cleared Testament",
        "a_bell_curve": "Arrow Vault Insignia Insignia",
        "a_picky_watcher": "Joestar Fan Seal",
        "a_100_rated": "Joestar Fan Warrant",
        "a_500_rated": "Jojo's Bizarre Adventure Pinnacle",
        "a_mediocre_majority": "All Parts Canon",
        "a_rating_spree": "Joestar Loyalist Review",
        "a_score_variance": "All Parts Cleared Score",
        "a_masterpiece_hunter": "Part Sweep Banner",
        "a_contrarian": "Stands Record",
        "a_optimist": "Master Ledger",
        "a_score_distributor": "Midnight Stand Battle Appraisal",
        "a_genre_critic": "Bold Critic",
        "a_mean_above_8": "All Parts Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "Parts Resolve",
        "a_valentines_weeb": "Parts Vow",
        "a_pi_day": "Battle Trial",
        "a_april_fools": "Loyal Joestar Devotion",
        "a_international_anime_day": "Loyal Joestar Fan Pinnacle",
        "a_star_wars_day": "Joestar Archives Chronicle",
        "a_summer_solstice": "Archive Calendar",
        "a_tanabata": "Archive Tanabata",
        "a_friday_13th": "Jojo's Bizarre Adventure Relic",
        "a_halloween_spirit": "Part Cleared Vow",
        "a_thanksgiving_binge": "Loyalist Run",
        "a_christmas_special": "Joestar Season",
        "a_new_years_eve": "Za Warudo Pilgrimage",
        "a_birthday_watch": "Stand Battle Vow",
        "a_holiday_marathon": "Stands Overture",
        "a_independence_day": "Joestar Marathon Banner",
        "a_culture_day": "Marathon Insignia",
        "a_spring_equinox": "Hamon Decree",
        "a_earth_day": "Warudo Record",
        "a_labor_day": "All Parts Seal Seal",
        "a_winter_solstice": "Joestar Trophies Pilgrimage",
        "a_anime_birthday": "Bizarre Adventure Pilgrimage",
        "a_every_holiday": "Battle Resolve",
        "a_consecutive_holidays": "Stand Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Parts Rank",
        "a_meta_collector": "Arrow Vault Hoard",
        "a_meta_category_starter": "Parts Cleared Badge",
        "a_meta_tier_climber": "Archive Glyph",
        "a_meta_tier_max": "Stand Battle Writ",
        "a_meta_xp_earner": "Za Warudo Emblem",
        "a_meta_difficulty_easy": "Hamon Mechanism",
        "a_meta_difficulty_hard": "Stand Battle Writ Writ",
        "a_meta_unlock_spree": "Bizarre Panel",
        "a_meta_completionist": "Weakling Hamon Fulfillment",
        "a_meta_diverse": "Master Emblem",
        "a_meta_dominator": "Stand Battle Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Manga Chapter",
        "m_chapter_counter": "Jojo's Bizarre Adventure Ledger",
        "m_chapter_titan": "Battle Relic",
        "m_reading_hours": "Wrryyyy Relic Relic",
        "m_reading_time_lord": "Adventure Pinnacle",
        "m_manga_collector": "Joestar Archives Ledger",
        "m_library_legend": "Parts Cleared Reliquary",
        "m_first_complete": "Joestar Triumph",
        "m_hundred_club": "Stand Alerts Legend",
        "m_first_day": "Part Registry Dawn",
        "m_first_rating": "Parts Eye",
        "m_ten_thousand_pages": "Loyal Joestar Gauge",
        "m_volume_collector": "Loyal Joestar Storehouse",
        "m_year_explorer": "Joestar Estate Quest",
        "m_century_reader": "Midnight Dominion",
        "m_five_hundred_ch": "Stand Ledger",
        "m_thousand_ch": "Part Testament",
        "m_reading_ten": "Loyalist Appraisal",
        "m_ptr_hoarder": "Part Registry Index",
        "m_dropped_honesty": "Jojo's Bizarre Adventure Summit",
        "m_season_reader": "Parts Cleared Treasury",
        "m_active_reader": "Parts Trial",
        "m_five_thousand_ch": "Jojo's Bizarre Adventure Standard",
        "m_ten_completed": "Joestar Loyalist Resolution",
        "m_fifty_completed": "Weakling Harvest",
        "m_five_hundred_completed": "Stand Battle Legacy",
        "m_mean_score_tracker": "Za Warudo Audit",
        "m_unique_authors": "Loyalist Reserve",
        "m_all_status": "Joestar Estate Testament",
        "m_first_favorite": "Hamon Master Cache",
        "m_favorites_collector": "Master Shelf",
        "m_days_spent_reading": "Adventure Decree Decree",

        // ── MANGA BINGE ──
        "m_binge_reader": "Master Streak",
        "m_marathon_reader": "Arrow Vault Rush",
        "m_weekend_reader": "Joestar Marathon Run",
        "m_non_stop_reading": "Warudo Gauntlet",
        "m_one_more_chapter": "Adventure Testament",
        "m_speed_read": "All Parts Drive",
        "m_double_story": "Arrow Vault Banner",
        "m_triple_read": "Loyal Joestar Fan Record",
        "m_five_a_day": "Joestar Insignia",
        "m_chapter_chain": "Battle Accord",
        "m_volume_binge": "Stand Battle Drive",
        "m_power_reader": "Archive Seal",
        "m_half_day_read": "All Parts Cleared Aegis",
        "m_full_day_read": "Midnight Aegis",
        "m_power_weekend": "Wrryyyy Streak",
        "m_binge_king": "Manga Marathon",
        "m_no_sleep_read": "Hamon Rush",
        "m_full_series_rush": "Parts Cascade",
        "m_seven_day_challenge": "Part Registry Warrant",
        "m_hundred_day_read": "Jojo's Bizarre Adventure Legend",
        "m_volume_rush": "All Parts Cleared Gauntlet",
        "m_series_sweep": "Parts Trial Trial",
        "m_genre_binge": "Warudo Binge",
        "m_author_binge": "Midnight Surge",
        "m_chapter_counter_day": "Joestar Loyalist Ledger",
        "m_multi_series_binge": "Archive Charge",
        "m_midnight_binge": "Joestar Trophies Tempest",
        "m_new_year_binge": "Joestar Loyalist Passage",
        "m_forty_eight_hour": "Bizarre Adventure Rally",
        "m_oneshot_binge": "Joestar Trophies Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Part Cleared Action Proof",
        "m_genre_adventure": "Weakling Adventure",
        "m_genre_comedy": "Marathon Comedy",
        "m_genre_drama": "Midnight Stand Drama",
        "m_genre_fantasy": "Stands Fantasy",
        "m_genre_horror": "Stands Horror",
        "m_genre_mystery": "Part Mystery",
        "m_genre_romance": "All Parts Romance",
        "m_genre_scifi": "Weakling Sci-Fi",
        "m_genre_sol": "Joestar Circle Slice",
        "m_genre_sports": "Loyal Sports",
        "m_genre_supernatural": "Arrow Vault Supernatural",
        "m_genre_thriller": "Stand Thriller",
        "m_genre_psychological": "Part Psychological",
        "m_genre_isekai": "Missing Parts Isekai",
        "m_genre_shounen": "Stand Shounen",
        "m_genre_ecchi": "Midnight Stand Battle Ecchi",
        "m_genre_mahou_shoujo": "Part Registry Magic Shoujo",
        "m_genre_mecha": "Loyal Joestar Mecha",
        "m_genre_music": "Weakling Hamon Music",
        "m_tag_isekai_new": "Battle Isekai New",
        "m_tag_harem": "Jojo's Bizarre Adventure Harem",
        "m_tag_bl": "Wrryyyy Bl",
        "m_tag_gl": "Bizarre Palette Gl",
        "m_tag_historical": "Hamon Historical",
        "m_tag_military": "Loyal Military",
        "m_tag_school": "Bizarre Palette School",
        "m_tag_martial_arts": "All Parts Martial Arts",
        "m_tag_vampire": "Marathon Vampire",
        "m_tag_samurai": "Archive Samurai",
        "m_tag_space": "Battle Space",
        "m_tag_parody": "Part Registry Parody",
        "m_tag_idol": "Weakling Hamon Idol",
        "m_tag_post_apocalyptic": "Joestar Circle Post Apocalyptic",
        "m_tag_cyberpunk": "Midnight Cyberpunk",
        "m_tag_shoujo": "Wrryyyy Shoujo",
        "m_tag_survival": "Master Survival",
        "m_tag_cooking": "Marathon Cooking",
        "m_tag_medical": "Part Sweep Medical",
        "m_tag_villainess": "Part Sweep Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Manga Archive",
        "m_mega_completionist": "All Parts Resolution",
        "m_completion_rate_50": "Part Cleared Return",
        "m_completion_rate_75": "Bizarre Palette Ascension",
        "m_completion_rate_90": "Part Resolution",
        "m_no_drop": "Archive Decree",
        "m_long_runner_complete": "Jojo's Bizarre Adventure Clear",
        "m_sequel_chain": "Missing Parts Seal",
        "m_clean_list": "Joestar Estate Relic",
        "m_from_ptr": "Adventure Accord",
        "m_reread_master": "Marathon Trial",
        "m_oneshot_complete": "Part Cleared Ascension",
        "m_same_day_start_finish": "Master Crown",
        "m_revival": "Battle Accord Accord",
        "m_zero_to_hundred": "Adventure Banner",
        "m_five_genre_complete": "Missing Parts M Five Genre",
        "m_full_collection": "Cleared Proof",
        "m_batch_complete": "Stands Testament Testament",
        "m_paused_to_done": "Joestar Fan Standard",
        "m_completion_spree": "Weakling Triumph",
        "m_format_completionist": "Hamon Testament",
        "m_catch_up": "Joestar Estate Chronicle",
        "m_multi_reread": "Stand Alerts Banner",
        "m_dropped_recovery": "Parts Conquest",
        "m_ten_perfect_scores": "Loyal Joestar Fan Judgment",
        "m_complete_genre_span": "Loyalist M Complete Genre Span",
        "m_monthly_completions": "Parts Return",
        "m_yearly_completions": "Joestar Fan Epilogue",
        "m_rapid_complete": "Joestar Archives Finale",
        "m_author_complete": "Stands Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Joestar Fan",
        "m_mangaka_lover": "Part Registry Standard",
        "m_rereader": "Master Relic",
        "m_triple_reread": "Bizarre Palette Testament",
        "m_annual_reread": "Joestar Estate Banner",
        "m_publisher_fan": "Part Registry Mark",
        "m_artist_fan": "Part Cleared Insignia",
        "m_adaptation_compare": "Joestar Insignia Insignia",
        "m_source_material_fan": "Joestar Fan Cache",
        "m_waiting_weekly": "Archive Streak",
        "m_classic_reader": "Joestar Loyalist Lantern",
        "m_saga_reader": "Part Sweep Crown Crown",
        "m_genre_loyalty": "Joestar Fan Loyalty",
        "m_decade_reader": "Joestar Warrant",
        "m_ln_adaptation": "Loyal Mark Mark",
        "m_original_work": "Stand Alerts Standard",
        "m_long_commitment": "Parts Cleared Mark",
        "m_up_to_date": "Joestar Estate Warrant",
        "m_favorite_mangaka": "Joestar Trophies Treasury",
        "m_complete_portfolio": "Marathon Triumph",
        "m_franchise_collector": "Midnight Stand Archive",
        "m_serialization_follower": "Weakling Hamon Handshake",
        "m_genre_master": "Joestar Loyalist Master",
        "m_multi_series_author": "Stands Insignia",
        "m_format_diversity": "Weakling Shelf",
        "m_year_dedication": "Bizarre Tenure",
        "m_ongoing_follower": "Parts Cleared Fellowship",
        "m_genre_loyalty_50": "Joestar Estate Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Midnight Stand Explorer",
        "m_publisher_hopper": "Part Record",
        "m_tag_explorer": "Master Explorer",
        "m_decade_hopper": "Joestar Estate Chronicle Chronicle",
        "m_hidden_gem": "Joestar Fan Mark",
        "m_popular_taste": "Midnight Stand Battle Record Record",
        "m_retro_reader": "All Parts Cleared Testament Testament",
        "m_modern_reader": "Joestar Trophies Seal",
        "m_cross_demographic": "Loyal Crown",
        "m_underdog_fan": "Loyal Joestar Testament",
        "m_variety_week": "Loyal Joestar Fan Horizon",
        "m_manhwa_reader": "Loyal Joestar Proof",
        "m_manhua_reader": "Midnight Mantle",
        "m_classic_connoisseur": "Joestar Estate Glimpse",
        "m_award_winner": "Joestar Archives Seal",
        "m_niche_explorer": "Missing Parts Horizon",
        "m_world_manga": "Midnight Chronicle",
        "m_cult_classic": "Warudo Map",
        "m_random_pick": "Midnight Stand Battle Standard",
        "m_new_genre_month": "Stand Battle M New Genre",
        "m_year_completionist": "Part Cleared Fulfillment",
        "m_unpopular_opinion": "Midnight Stand Battle Aegis",
        "m_top_rated_reader": "Midnight Stand Battle Pinnacle",
        "m_source_variety": "Battle Catalogue",
        "m_low_score_brave": "All Parts Score",
        "m_short_manga_explorer": "Loyal Compass",
        "m_long_manga_explorer": "Joestar Circle Survey",
        "m_serialization_explorer": "Midnight Stand Road",

        // ── MANGA TIME ──
        "m_night_owl": "Joestar Trophies Accord Accord",
        "m_early_bird": "Marathon Banner",
        "m_lunch_reader": "Loyalist Ledger",
        "m_commute_reader": "Archive Tenure",
        "m_four_am_club": "Weakling Hamon Fellowship",
        "m_new_year_read": "Missing Parts Pact",
        "m_all_hours": "Wrryyyy Accord",
        "m_prime_time_reader": "All Parts Cleared Banner",
        "m_workday_reader": "Marathon Accord",
        "m_sunday_read": "Hamon Master Standard",
        "m_morning_routine": "Weakling Discipline",
        "m_night_shift_reader": "Weakling Accord",
        "m_seasonal_premier_read": "Bizarre Storehouse",
        "m_clock_collector": "Loyal Joestar Fan Reserve",
        "m_late_night_horror": "Loyalist Mark Mark",
        "m_afternoon_reader": "Stand Alerts Mantle",
        "m_golden_hour_reader": "Za Warudo Observance",
        "m_dawn_reader": "Hamon Master Mantle",
        "m_twilight_reader": "Midnight Stand Battle Crown",
        "m_midnight_start": "Hamon Routine",
        "m_weekend_binge_hours": "Midnight Stand Battle Momentum",
        "m_late_night_regular": "Bizarre Testament",
        "m_sunrise_reader": "Loyal Joestar Fan Record Record",
        "m_every_day_of_week": "Bizarre Seal",
        "m_monthly_hours": "Parts Cleared Vigil",
        "m_bedtime_reader": "Weakling Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Joestar Loyalist Mantle",
        "m_webtoon_reader": "Stands Mark",
        "m_full_color": "Joestar Marathon Accord",
        "m_doujin_reader": "Jojo's Bizarre Adventure Record",
        "m_anthology_reader": "Joestar Archives Accord",
        "m_adaptation_reader": "Stands Banner",
        "m_longstrip_reader": "Warudo Trial",
        "m_4koma_reader": "Parts Cleared Relic",
        "m_oneshot_reader": "Loyalist Mantle",
        "m_format_variety": "Bold Gallery",
        "m_light_novel_reader": "Weakling Insignia",
        "m_novel_reader": "Bold Crown",
        "m_visual_storyteller": "Part Cleared Testament",
        "m_colored_classic": "Loyalist Survey",
        "m_webcomic_fan": "Adventure Insignia",
        "m_manga_to_anime": "All Parts Cleared Record",
        "m_seinen_reader": "Stands Pinnacle",
        "m_josei_reader": "Marathon Pinnacle",
        "m_award_winning_art": "Loyalist Ledger Ledger",
        "m_debut_work": "Archive Dominion Dominion",
        "m_vertical_scroll": "Stand Alerts Crown",
        "m_traditional_format": "Joestar Loyalist Hoard",
        "m_cross_media": "Bold Accord",
        "m_spinoff_reader": "Part Accord",
        "m_remake_reader": "Missing Parts Insignia",
        "m_collaboration_reader": "Stands Chronicle Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Za Warudo Focus",
        "m_mega_streak": "All Parts Cleared Routine",
        "m_weekly_warrior": "Loyal Joestar Season",
        "m_monthly_reader": "Joestar Trophies Discipline",
        "m_comeback": "Warudo Standard",
        "m_weekend_streak": "Joestar Trophies Fever",
        "m_no_zero_days": "Joestar Estate Proof",
        "m_iron_will": "Stand Ledger Ledger",
        "m_habit_formed": "All Parts Crown",
        "m_consistent_pace": "Joestar Scrutiny",
        "m_year_long": "Joestar Observance",
        "m_double_streak": "Loyal Joestar Resolve",
        "m_streak_recovery": "Bizarre Palette Resolve",
        "m_daily_minimum": "Archive Daily",
        "m_winter_streak": "Joestar Observance Observance",
        "m_summer_streak": "Loyal Joestar Observance",
        "m_morning_streak": "Loyalist Clock",
        "m_night_streak": "Za Warudo Discipline",
        "m_unbreakable": "Hamon Master Warrant",
        "m_eternal_flame": "Wrryyyy Record",
        "m_chapter_a_day": "Joestar Fan Relic",
        "m_genre_streak": "Missing Parts Streak",
        "m_completion_streak": "Part Return",
        "m_rating_streak": "Joestar Fan Appraisal",
        "m_multi_ch_streak": "Archive Tenure Tenure",
        "m_author_streak": "Hamon Calendar",
        "m_perfect_week_manga": "Arrow Vault Accord",
        "m_diverse_streak": "Wrryyyy Streak Streak",

        // ── MANGA SCORING ──
        "m_critic": "Adventure Scrutiny",
        "m_perfect_ten": "Battle Verdict",
        "m_harsh_critic": "Midnight Scale",
        "m_fair_judge": "Weakling Eye",
        "m_generous_spirit": "Joestar Marathon Crown",
        "m_score_all": "Za Warudo Reckoning",
        "m_wide_range": "Joestar Archives Ledger Ledger",
        "m_controversial": "Joestar Loyalist Standard",
        "m_consistent_scorer": "Midnight Stand Grade",
        "m_score_sniper": "Bold Reckoning",
        "m_evolving_taste": "Joestar Trial",
        "m_bell_curve": "Bizarre Adventure Accord",
        "m_picky_reader": "Bizarre Palette Relic",
        "m_100_rated": "Archive Mark",
        "m_500_rated": "Part Sweep Proof",
        "m_mediocre_majority": "Part Registry Canon",
        "m_rating_spree": "All Parts Verdict",
        "m_score_variance": "Adventure Measure",
        "m_binge_rater": "Joestar Trophies Passage",
        "m_reread_rerate": "Joestar Fan Banner",
        "m_masterpiece_hunter": "Marathon Banner Banner",
        "m_contrarian": "Weakling Aegis",
        "m_optimist": "Weakling Hamon Accord",
        "m_score_distributor": "Joestar Fan Balance",
        "m_genre_critic": "Marathon Critic",
        "m_mean_above_8": "Stand Battle Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Battle Season",
        "m_valentines_read": "Master Observance",
        "m_pi_day": "Hamon Master Testament",
        "m_april_fools": "Joestar Circle Devotion",
        "m_international_manga_day": "Part Proof",
        "m_free_comic_day": "Missing Parts Chronicle",
        "m_summer_solstice": "Adventure Focus",
        "m_tanabata": "Wrryyyy Pilgrimage",
        "m_friday_13th": "Loyal Joestar Fan Dominion",
        "m_halloween_read": "Battle Calendar",
        "m_thanksgiving_binge": "Battle Charge",
        "m_christmas_read": "Archive Pact",
        "m_new_years_eve": "Bold Pilgrimage",
        "m_birthday_read": "Bizarre Palette Focus",
        "m_holiday_marathon": "Warudo Rally",
        "m_independence_day": "Midnight Aegis Aegis",
        "m_culture_day": "Midnight Stand Battle Seal",
        "m_spring_equinox": "Part Cleared Banner",
        "m_earth_day": "Stands Aegis",
        "m_labor_day": "Battle Seal Seal",
        "m_winter_solstice": "All Parts Cleared Focus",
        "m_manga_birthday": "All Parts Ritual",
        "m_every_holiday_reader": "Master Watch",
        "m_consecutive_holidays": "Part Sweep Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Loyal Joestar Fan Proof",
        "m_fibonacci": "Wrryyyy Dominion",
        "m_palindrome_day": "Joestar Estate Relic Relic",
        "m_binary_day": "Bizarre Adventure Proof",
        "m_full_moon_read": "Bold Crown Crown",
        "m_leap_year_read": "Stand Battle Practice",
        "m_triple_seven": "Midnight Stand Battle Trial",
        "m_thousand_complete": "Stand Battle Ascension",
        "m_nice": "Parts Seal",
        "m_power_level_chapters": "Marathon Aegis",
        "m_answer_42": "Bizarre Adventure Aegis",
        "m_square_number": "All Parts Standard",
        "m_prime_count": "Part Cleared Insignia Insignia",
        "m_matching_date": "Stands Mantle",
        "m_century_chapter": "Joestar Archives Crown",
        "m_pi_chapters": "Warudo Proof",
        "m_synchronicity": "Wrryyyy Emblem",
        "m_world_record": "Cleared Warrant Warrant",
        "m_genre_clash": "Stands Clash",
        "m_time_traveler": "Part Cleared Decree",
        "m_double_digits": "Joestar Trophies Dominion Dominion",
        "m_one_two_three": "Warudo Warrant",
        "m_lucky_seven": "Cleared Pinnacle",
        "m_exact_hundred_ch": "Midnight Stand Battle Legend",
        "m_year_match_count": "Adventure Routine",
        "m_chapter_match_date": "Weakling Hamon Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Joestar Circle Index",
        "m_manhwa_format": "Battle Gallery",
        "m_manhua_format": "All Parts Storehouse",
        "m_ln_format": "Battle Index",
        "m_oneshot_format": "Loyal Joestar Index",
        "m_doujin_format": "Adventure Cabinet",
        "m_novel_format": "Midnight Stand Reserve",
        "m_format_master_manga": "Stand Alerts Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Weakling Link",
        "m_meta_collector": "Weakling Reliquary",
        "m_meta_category_starter": "Arrow Vault Standard",
        "m_meta_tier_climber": "Loyal Joestar Fan Token",
        "m_meta_tier_max": "Master Token",
        "m_meta_xp_earner": "Bizarre Anchor",
        "m_meta_difficulty_easy": "Hamon Panel",
        "m_meta_difficulty_hard": "Arrow Vault Seal",
        "m_meta_unlock_spree": "Missing Parts Marker",
        "m_meta_completionist": "Loyal Joestar Fan Triumph",
        "m_meta_diverse": "Joestar Marathon Anchor",
        "m_meta_dominator": "Warudo Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#0a0600",
        primary: "#dca000",
        secondary: "#6a4a00",
        accent: "#8060a0",
    },
    particleColor: "#dca000",
    backgroundDim: 0.28,
    backgroundBlur: 15,
    particleTypes: {
        golden_sparks: { label: "Golden Sparks", maxCount: 14, defaultEnabled: true, defaultIntensity: 60 },
        stand_wisps: { label: "Stand Wisps", maxCount: 6, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
  1: "Threadbare Generic Rank Spark",
  8: "Generic's Tarnished Omen",
  14: "Fractured Generic Rank",
  21: "Generic Rank Path",
  28: "Lowborn Legacy Myth",
  35: "Generic Rank Pulse",
  41: "Generic's Legacy Crest",
  48: "Humble Generic Mark",
  55: "Ragged Generic Rank Vow",
  61: "Generic's Faint Echo",
  68: "Lesser Generic Rank",
  75: "Generic Rank Zenith",
  81: "Doubtful Legacy Bloom",
  88: "Generic Rank Sigil",
  95: "Generic's Legacy Flame",
  102: "Really Cool Generic Spark",
  108: "Awakened Generic Rank Omen",
  115: "Generic's Resolute Seal",
  122: "Rising Generic Rank",
  128: "Generic Rank Myth",
  135: "Dauntless Legacy Pulse",
  142: "Generic Rank Crest",
  149: "Generic's Legacy Mark",
  155: "Fresh Generic Vow",
  162: "Valiant Generic Rank Echo",
  169: "Generic's Prime Crown",
  175: "Polished Generic Rank",
  182: "Generic Rank Bloom",
  189: "Stormlit Legacy Sigil",
  195: "Generic Rank Flame",
  202: "Generic's Legacy Spark",
  209: "Tempered Generic Omen",
  216: "Trusted Generic Rank Seal",
  222: "Generic's Steadfast Path",
  229: "Ironclad Generic Rank",
  236: "Veteran Legacy Pulse",
  242: "Core Legacy Crest",
  249: "Generic Rank Mark",
  256: "Generic's Legacy Vow",
  262: "Formidable Generic Echo",
  269: "Lucid Generic Rank Crown",
  276: "Generic's Ranked Zenith",
  283: "Fabled Generic Rank",
  289: "Grand Legacy Sigil",
  296: "Seasoned Legacy Flame",
  303: "Generic Rank Spark",
  309: "Generic's Legacy Omen",
  316: "Valorous Generic Seal",
  323: "Stalwart Generic Rank Path",
  330: "Generic's Commanding Myth",
  336: "Refined Generic Rank",
  343: "Unbroken Legacy Crest",
  350: "Blazing Legacy Mark",
  356: "Generic Rank Vow",
  363: "Generic's Legacy Echo",
  370: "Peerless Generic Crown",
  376: "Ardent Generic Rank Zenith",
  383: "Generic's Focused Bloom",
  390: "Vigilant Generic Rank",
  397: "Dominant Legacy Flame",
  403: "Elite Legacy Spark",
  410: "Generic Rank Omen",
  417: "Generic's Legacy Seal",
  423: "Sovereign Generic Path",
  430: "Regal Generic Rank Myth",
  437: "Generic's Crowned Pulse",
  444: "Mythborn Generic Rank",
  450: "Limitless Legacy Mark",
  457: "Radiant Legacy Vow",
  464: "Generic Rank Echo",
  470: "Generic's Legacy Crown",
  477: "Climactic Generic Zenith",
  484: "Epic Generic Rank Bloom",
  490: "Generic's Unreal Sigil",
  497: "Peak Generic Rank",
  504: "Supreme Legacy Spark",
  511: "Exalted Legacy Omen",
  517: "Generic Rank Seal",
  524: "Generic's Legacy Path",
  531: "Celestial Generic Myth",
  537: "Phantom Generic Rank Pulse",
  544: "Generic's Crimson Crest",
  551: "Silver Generic Rank",
  557: "Golden Legacy Vow",
  564: "Feral Legacy Echo",
  571: "Generic Rank Crown",
  578: "Generic's Legacy Zenith",
  584: "Dread Generic Bloom",
  591: "Luminous Generic Rank Sigil",
  598: "Generic's Thunderous Flame",
  604: "Ultraviolet Generic Rank",
  611: "Unleashed Legacy Omen",
  618: "Secret Legacy Seal",
  625: "Final Generic Path",
  631: "Generic's Legacy Myth",
  638: "Worldclass Generic Pulse",
  645: "Lawless Generic Rank Crest",
  651: "Generic's Chosen Mark",
  658: "Fearless Generic Rank",
  665: "Overdrive Legacy Echo",
  671: "Cinematic Legacy Crown",
  678: "Impossible Generic Zenith",
  685: "Generic's Legacy Bloom",
  692: "Canonized Generic Sigil",
  698: "Ascendant Generic Rank Flame",
  705: "Generic's Transfigured Spark",
  712: "Immortal Generic Rank",
  718: "Eclipsed Legacy Seal",
  725: "Astral Legacy Path",
  732: "Sublime Generic Myth",
  739: "Generic's Legacy Pulse",
  745: "Prismatic Generic Crest",
  752: "Abyssal Generic Rank Mark",
  759: "Generic's Unbound Vow",
  765: "Eternal Generic Rank",
  772: "Cosmic Legacy Crown",
  779: "Transcendent Legacy Zenith",
  785: "Perfected Generic Bloom",
  792: "Generic's Legacy Sigil",
  799: "Ultimate Generic Flame",
  806: "Mythic Generic Rank Spark",
  812: "Generic's Godlike Omen",
  819: "Canonical Generic Rank",
  826: "Reality-Bent Legacy Path",
  832: "Heavenly Legacy Myth",
  839: "Absolute Generic Pulse",
  846: "Untouchable Generic Crest",
  852: "Timeless Generic Mark",
  859: "Empyrean Generic Rank Vow",
  866: "Generic's Primordial Echo",
  873: "Omniscient Generic Rank",
  879: "Unfathomed Legacy Zenith",
  886: "Apocalyptic Legacy Bloom",
  893: "Seraphic Generic Sigil",
  899: "Omega Generic Flame",
  906: "Final Generic Spark",
  913: "Crowned Generic Rank Omen",
  920: "Generic's Mythic Seal",
  926: "Absolute Generic Rank",
  933: "Eternal Legacy Myth",
  940: "Cosmic Legacy Pulse",
  946: "Transcendent Generic Crest",
  953: "Perfected Generic Mark",
  960: "Definitive Generic Vow",
  966: "Ultimate Generic Rank Echo",
  973: "Generic's Infinite Crown",
  980: "Sovereign Generic Rank",
  987: "Celestial Legacy Bloom",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate Generic Rank"
},
}
