import { AnimeThemeConfig } from "./types"
import { GiGuitar, GiMusicalNotes, GiHeadphones, GiPianoKeys, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiMicrophone } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const kOnTheme: AnimeThemeConfig = {
    id: "k-on",
    displayName: "K-On!",
    description: "Four girls with zero musical experience stumble into forming the Light Music Club. Tea, cake, and guitar solos carry them from school concerts to the Budokan — in their dreams and hearts.",
    fontFamily: "'Fredoka One', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap",
    cssVars: {
        "--color-brand-200": "255 210 240",
        "--color-brand-300": "255 170 220",
        "--color-brand-400": "250 125 198",
        "--color-brand-500": "238 88 172",
        "--color-brand-600": "208 60 142",
        "--color-brand-700": "165 38 105",
        "--color-brand-800": "118 20 70",
        "--color-brand-900": "72 8 40",
        "--color-brand-950": "36 2 18",
        "--brand": "238 88 172",
        "--background": "#090204",
        "--paper": "#130408",
        "--color-gray-950": "9 2 4",
        "--color-gray-900": "20 5 10",
        "--color-gray-800": "38 12 22",
        "--color-gray-700": "60 22 38",
        "--color-gray-600": "90 38 62",
        "--color-gray-500": "132 65 95",
        "--color-gray-400": "175 102 138",
        "--color-gray-300": "212 148 178",
        "--color-gray-200": "238 190 212",
        "--color-gray-100": "252 225 238",
        "--color-gray-50": "255 244 250",
    },
    sidebarOverrides: {
        "home": { icon: GiGuitar, label: "Light Music Club" },
        "schedule": { icon: GiAlarmClock, label: "Practice Schedule" },
        "manga": { icon: LuBookOpen, label: "Song Archive" },
        "lists": { icon: GiScrollUnfurled, label: "Setlist" },
        "discover": { icon: GiMusicalNotes, label: "New Music" },
        "torrent-list": { icon: GiHeadphones, label: "Equipment Room" },
        "debrid": { icon: GiPianoKeys, label: "Tea Room Vault" },
        "unmatched": { icon: GiPalette, label: "Lost Songs" },
        "enmasse": { icon: GiResize, label: "Band Deploy" },
        "scan-summaries": { icon: TbReportSearch, label: "Concert Reports" },
        "auto-downloader": { icon: LuRss, label: "New Songs" },
        "community": { icon: GiMicrophone, label: "HTT Fan Club" },
        "achievements": { icon: GiTrophyCup, label: "Performance Awards" },
        "milestones": { icon: LuFlag, label: "Band Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Rehearsal Alerts" },
        "theme-manager": { icon: GiPalette, label: "Stage Colors" },
        "extensions": { icon: BiExtension, label: "Guitar Pedals" },
        "sync": { icon: IoCloudOfflineOutline, label: "Band Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Amp Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Club Meeting",
        "a_episode_counter": "Htt Mark",
        "a_episode_titan": "Budokan Relic",
        "a_hours_invested": "Music Proof",
        "a_time_lord": "Beginner Budokan Decree",
        "a_anime_collector": "Cake Catalogue",
        "a_library_legend": "Chord Library",
        "a_first_complete": "First Concert Done",
        "a_hundred_club": "Hundred Songs Learned",
        "a_first_day": "Practice Seal",
        "a_first_rating": "Song Archive Appraisal",
        "a_ten_thousand_min": "Equipment Room Standard",
        "a_season_veteran": "Song Archive Library",
        "a_year_explorer": "Budokan Map",
        "a_century_watcher": "Beginner Budokan Ledger",
        "a_five_hundred_eps": "Beginner Budokan Dominion",
        "a_thousand_eps": "Htt Record",
        "a_watching_ten": "Guitar Pedals Acclaim",
        "a_ptw_hoarder": "Songs Library",
        "a_dropped_honesty": "Marathon Summit",
        "a_five_thousand_eps": "Song Archive Warrant",
        "a_ten_completed": "Loyal Cake Afterglow",
        "a_fifty_completed": "Songs Ascension",
        "a_five_hundred_completed": "Rehearsal Alerts Clear",
        "a_mean_score_tracker": "Lost Songs Verdict",
        "a_unique_studios": "Loyal Cake Fan Collection",
        "a_days_spent_watching": "Cake Fan Dominion",
        "a_all_status": "Cake Testament",
        "a_first_favorite": "Beginner Budokan Cabinet",
        "a_favorites_collector": "Learned Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Marathon Drive",
        "a_marathon_runner": "Loyal Cake Fan Gauntlet",
        "a_weekend_warrior": "Song Archive Ordeal",
        "a_non_stop": "Rehearsal Alerts Fever",
        "a_one_more_episode": "Marathon Mantle",
        "a_speed_run": "Cake Fan Vigil",
        "a_double_feature": "Tea Room Vault Crown",
        "a_triple_threat": "Setlist Record",
        "a_five_a_day": "Song Archive Accord",
        "a_back_to_back": "Setlist Surge",
        "a_seasonal_binge": "Performance Cascade",
        "a_cour_crusher": "Beginner Budokan Ordeal",
        "a_half_day_watch": "Cake Fan Crown",
        "a_full_day_watch": "Learned Pinnacle",
        "a_power_weekend": "K On Run",
        "a_binge_king": "K-On Marathon",
        "a_no_sleep": "Meeting Vigil",
        "a_entire_season": "Beginner Budokan Library",
        "a_seven_day_challenge": "Loyal Cake Fan Mark",
        "a_hundred_day_binge": "Performance Surge",
        "a_genre_binge": "Beginner Binge",
        "a_studio_binge": "Learned Fever",
        "a_season_sweep": "Song Archive Codex",
        "a_forty_eight_hour": "Songs Overture",
        "a_ep_counter_day": "Loyal Cake Aegis",
        "a_multi_series_binge": "Band Streak",
        "a_midnight_binge": "Chord Cascade",
        "a_new_year_binge": "Songs Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Light Music Action",
        "a_genre_adventure": "Song Archive Adventure",
        "a_genre_comedy": "Chord Comedy",
        "a_genre_drama": "Rehearsal Alerts Drama",
        "a_genre_fantasy": "Band Fantasy",
        "a_genre_horror": "Performance Horror",
        "a_genre_mystery": "Guitar Pedals Mystery",
        "a_genre_romance": "Archive Romance",
        "a_genre_scifi": "Lost Songs Sci-Fi",
        "a_genre_sol": "Tea Slice",
        "a_genre_sports": "Practice Sports",
        "a_genre_supernatural": "Budokan Supernatural",
        "a_genre_thriller": "Meeting Thriller",
        "a_genre_mecha": "Songs Learned Mecha",
        "a_genre_music": "K On Music",
        "a_genre_psychological": "Beginner Budokan Psychological",
        "a_genre_ecchi": "Cake Ecchi",
        "a_genre_mahou_shoujo": "Rehearsal Alerts Magic Shoujo",
        "a_tag_isekai": "Songs Isekai",
        "a_tag_harem": "K On Harem",
        "a_tag_bl": "Band Bl",
        "a_tag_gl": "Cake Gl",
        "a_tag_historical": "Loyal Historical",
        "a_tag_military": "Loyal Military",
        "a_tag_school": "Meeting School",
        "a_tag_martial_arts": "Light Music Martial Arts",
        "a_tag_vampire": "Archive Vampire",
        "a_tag_samurai": "Concert Samurai",
        "a_tag_space": "Marathon Space",
        "a_tag_parody": "Band Parody",
        "a_tag_idol": "Songs Idol",
        "a_tag_post_apocalyptic": "Songs Learned Post Apocalyptic",
        "a_tag_cyberpunk": "Amp Cyberpunk",
        "a_tag_shounen": "Songs Learned Shounen",
        "a_tag_seinen": "Setlist Seinen",
        "a_tag_shoujo": "Setlist Shoujo",
        "a_tag_josei": "Loyal Cake Josei",
        "a_tag_survival": "Songs Learned Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "HTT Complete",
        "a_mega_completionist": "HTT Legend",
        "a_completion_rate_50": "Rehearsal Alerts Return",
        "a_completion_rate_75": "K On Crown",
        "a_completion_rate_90": "Loyal Cake Resolution",
        "a_no_drop": "Rehearsal Alerts Decree",
        "a_long_runner_complete": "Lost Songs Clear",
        "a_sequel_chain": "Beginner Insignia",
        "a_clean_list": "Song Archive Relic",
        "a_from_ptw": "Lost Songs Index",
        "a_rewatch_master": "Practice Return",
        "a_short_complete": "Guitar Pedals Endgame",
        "a_same_day_start_finish": "K On Pinnacle",
        "a_revival": "Concert Insignia",
        "a_zero_to_hero": "Beginner to Budokan",
        "a_five_genre_complete": "Cake A Five Genre Complete",
        "a_full_franchise": "Budokan Chronicle",
        "a_batch_complete": "Songs Crown",
        "a_paused_to_done": "Guitar Pedals Aegis",
        "a_completion_spree": "Loyal Triumph",
        "a_multi_rewatch": "Beginner Budokan Triumph",
        "a_dropped_recovery": "Loyal Cake Fan Conquest",
        "a_ten_perfect_scores": "Meeting Acclaim",
        "a_seasonal_clear": "Loyal Codex",
        "a_complete_genre_span": "Htt A Complete Genre Span",
        "a_monthly_completions": "Band Afterglow",
        "a_yearly_completions": "Htt Fan Epilogue",
        "a_rapid_complete": "Htt Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Cake Fan",
        "a_studio_devotee": "Chord Treasury",
        "a_rewatcher": "Amp Closure",
        "a_triple_rewatch": "Cake Fan Coda",
        "a_annual_tradition": "Music Proof Proof",
        "a_director_fan": "Practice Trial",
        "a_voice_actor_fan": "Songs Learned Crown",
        "a_ost_lover": "Songs Seal",
        "a_source_reader": "Song Archive Cabinet",
        "a_waiting_weekly": "Cake Clock",
        "a_childhood_revisit": "Cake Seal",
        "a_saga_tracker": "Archive Standard",
        "a_genre_loyalty": "Practice Loyalty",
        "a_decade_watcher": "Loyal Cake Banner",
        "a_adaptation_hunter": "Lost Songs Trial",
        "a_original_anime_fan": "Marathon Testament",
        "a_long_commitment": "Beginner Mark",
        "a_perfect_attendance": "Chord Standard",
        "a_favorite_studio_5": "Htt Library",
        "a_complete_catalog": "Concert Seal",
        "a_franchise_collector": "Beginner Archive",
        "a_airing_follower": "Rehearsal Alerts Signal",
        "a_genre_master": "Performance Master",
        "a_staff_follower": "Beginner Oath",
        "a_multi_season_fan": "Light Music Hoard",
        "a_format_diversity": "Rehearsal Alerts Cache",
        "a_year_dedication": "Equipment Room Tenure",
        "a_season_dedication": "Beginner Budokan Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Beginner Explorer",
        "a_studio_hopper": "Budokan Collection",
        "a_tag_explorer": "K On Explorer",
        "a_decade_hopper": "K On Chronicle",
        "a_hidden_gem": "Learned Warrant",
        "a_popular_taste": "Band Decree",
        "a_retro_appreciator": "Music Aegis",
        "a_modern_viewer": "Equipment Room Pinnacle",
        "a_cross_demographic": "Htt Fan Pinnacle",
        "a_underdog_fan": "Concert Trial",
        "a_variety_week": "Loyal Cake Fan Horizon",
        "a_foreign_cinema": "Loyal Cake Expedition",
        "a_classic_connoisseur": "Practice Glimpse",
        "a_every_season": "Loyal Cake Archive",
        "a_award_winner": "Song Archive Insignia",
        "a_niche_explorer": "Rehearsal Alerts Horizon",
        "a_global_anime": "Rehearsal Alerts Crown",
        "a_cult_classic": "Budokan Classic",
        "a_random_pick": "Meeting Decree",
        "a_new_genre_month": "Cake A New Genre Month",
        "a_seasonal_completionist": "Loyal Summit",
        "a_unpopular_opinion": "Beginner Standard",
        "a_top_rated_viewer": "Budokan Seal",
        "a_source_variety": "Learned Storehouse",
        "a_low_score_brave": "Rehearsal Alerts Measure",
        "a_upcoming_watcher": "K On Seal",
        "a_short_series_explorer": "Tea Room Vault Expedition",
        "a_long_series_explorer": "Guitar Pedals Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Cake Fan Insignia",
        "a_early_bird": "Amp Banner",
        "a_lunch_break": "Tea Room Vault Trial",
        "a_golden_hour": "Learned Tenure",
        "a_four_am_club": "Learned Gathering",
        "a_witching_hour": "Lost Songs Tenure",
        "a_new_year_watch": "Song Archive Season",
        "a_midnight_premiere": "Lost Songs Devotion",
        "a_all_hours": "Loyal Seal",
        "a_dawn_warrior": "Performance Aegis",
        "a_afternoon_delight": "Learned Proof",
        "a_prime_time": "Songs Insignia",
        "a_workday_watcher": "Marathon Pinnacle",
        "a_sunday_marathon": "Meeting Momentum",
        "a_rainy_day": "Meeting Relic",
        "a_morning_routine": "Htt Promise",
        "a_night_shift": "Loyal Cake Aegis Aegis",
        "a_twilight_zone": "Songs Learned Ledger",
        "a_seasonal_premier": "Chord Cabinet",
        "a_clock_collector": "Htt Repository",
        "a_weekend_binge_hours": "Chord Streak",
        "a_late_night_regular": "Tea Room Vault Dominion",
        "a_sunrise_watcher": "Meeting Relic Relic",
        "a_holiday_watcher": "Performance Pact",
        "a_every_day_of_week": "Loyal Cake Ledger",
        "a_monthly_hours": "Band Monthly",

        // ── ANIME SOCIAL ──
        "a_first_party": "Setlist Record Record",
        "a_party_host": "Beginner Mantle",
        "a_social_butterfly": "Performance Company",
        "a_group_binge": "Beginner Budokan Sprint",
        "a_party_regular": "Beginner Budokan Chronicle",
        "a_sync_viewer": "Light Music Standard",
        "a_commentator": "Songs Learned Record",
        "a_party_marathon": "Light Music Vigil",
        "a_full_house": "Learned Trial",
        "a_community_pillar": "Guitar Pedals Alliance",
        "a_watch_party_streak": "Beginner Budokan Vigil",
        "a_diverse_party": "Concert Seal Seal",
        "a_late_night_party": "Loyal Cake Testament",
        "a_party_veteran": "Light Music Testament",
        "a_genre_party": "Htt Fan Party",
        "a_weekly_party": "Loyal Calendar",
        "a_silent_viewer": "Rehearsal Alerts Mantle",
        "a_recommendation_giver": "Marathon Network",
        "a_party_completionist": "Tea Room Vault Coda",
        "a_social_scorer": "Budokan Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Setlist Proof",
        "a_fibonacci": "Songs Dominion",
        "a_palindrome_day": "Performance Relic",
        "a_binary_day": "K On Mark",
        "a_full_moon": "Setlist Insignia",
        "a_leap_year": "Htt Fan Devotion",
        "a_time_traveler": "Guitar Pedals Record",
        "a_genre_clash": "Cake Fan Clash",
        "a_triple_seven": "Budokan Testament",
        "a_thousand_complete": "Loyal Cake Epilogue",
        "a_pi_episodes": "Loyal Cake Crown",
        "a_synchronicity": "Concert Anchor",
        "a_world_record": "Learned Warrant Warrant",
        "a_nice": "Tea Chronicle",
        "a_power_level": "Guitar Pedals Testament",
        "a_answer_42": "Performance Standard",
        "a_square_number": "Loyal Decree",
        "a_prime_count": "Practice Seal Seal",
        "a_matching_date": "Loyal Mantle",
        "a_century_episode": "Rehearsal Alerts Mark",
        "a_double_digits": "Budokan Testament Testament",
        "a_one_two_three": "Tea Room Vault Crown Crown",
        "a_lucky_seven": "Loyal Crown",
        "a_all_tens": "Loyal Cake Criterion",
        "a_exact_hundred_eps": "Tea Room Vault Standard",
        "a_year_match_count": "Archive Clock",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Cake Ledger",
        "a_movie_buff": "Learned Mark",
        "a_ova_hunter": "Amp Standard",
        "a_ona_explorer": "Light Music Secret",
        "a_special_watcher": "Lost Songs Relic",
        "a_short_king": "Song Archive Crown",
        "a_variety_pack": "Htt Inquiry",
        "a_film_festival": "Budokan Chronicle Chronicle",
        "a_music_video": "Light Music Chronicle",
        "a_tv_short": "Beginner Record",
        "a_movie_marathon": "Cake Fan Gauntlet",
        "a_double_length": "Loyal Cake Crown Crown",
        "a_anthology": "Tea Room Vault Aegis",
        "a_mini_series": "Cake Fan Decree",
        "a_theatrical": "Concert Accord",
        "a_format_master": "Songs Learned Vault",
        "a_long_movie": "Music Insignia",
        "a_back_catalog": "Loyal Standard",
        "a_cm_watcher": "Meeting Aegis",
        "a_pv_collector": "Learned Storehouse Storehouse",
        "a_format_balance": "Htt Vault",
        "a_episodic_master": "Song Archive Standard",
        "a_sequel_movie": "Chord Pinnacle",
        "a_recap_watcher": "Archive Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Concert Devotion",
        "a_mega_streak": "Guitar Pedals Streak",
        "a_weekly_warrior": "Loyal Cake Fan Season",
        "a_monthly_watcher": "Band Calendar",
        "a_comeback": "Band Decree Decree",
        "a_weekend_streak": "Tea Room Vault Passage",
        "a_no_zero_days": "Performance Warrant",
        "a_iron_will": "Songs Seal Seal",
        "a_habit_formed": "Performance Warrant Warrant",
        "a_consistent_pace": "Archive Measure",
        "a_year_long": "Light Music Season",
        "a_double_streak": "Budokan Watch",
        "a_streak_recovery": "Chord Season",
        "a_daily_minimum": "Meeting Focus",
        "a_winter_streak": "Marathon Watch",
        "a_summer_streak": "Equipment Room Resolve",
        "a_morning_streak": "Concert Clock",
        "a_night_streak": "Archive Constancy",
        "a_unbreakable": "Songs Proof",
        "a_eternal_flame": "Lost Songs Standard",
        "a_completion_streak": "Htt Fan Return",
        "a_rating_streak": "Performance Balance",
        "a_multi_ep_streak": "Loyal Ritual",
        "a_genre_streak": "Performance Streak",
        "a_studio_streak": "Song Archive Cabinet Cabinet",
        "a_perfect_week": "Cake Fan Relic",

        // ── ANIME SCORING ──
        "a_critic": "Loyal Cake Fan Scrutiny",
        "a_perfect_ten": "Marathon Audit",
        "a_harsh_critic": "Loyal Cake Gauge",
        "a_fair_judge": "Marathon Balance",
        "a_generous_spirit": "Budokan Pinnacle",
        "a_score_all": "Loyal Criterion",
        "a_wide_range": "Practice Ledger",
        "a_controversial": "Cake Fan Decree Decree",
        "a_consistent_scorer": "Marathon Verdict",
        "a_score_sniper": "Tea Room Vault Score",
        "a_evolving_taste": "Band Testament",
        "a_bell_curve": "Amp Insignia",
        "a_picky_watcher": "Meeting Seal",
        "a_100_rated": "Songs Learned Warrant",
        "a_500_rated": "Practice Pinnacle",
        "a_mediocre_majority": "Learned Canon",
        "a_rating_spree": "Beginner Review",
        "a_score_variance": "Archive Score",
        "a_masterpiece_hunter": "Beginner Banner",
        "a_contrarian": "Loyal Record",
        "a_optimist": "Light Music Ledger",
        "a_score_distributor": "Rehearsal Alerts Appraisal",
        "a_genre_critic": "Amp Critic",
        "a_mean_above_8": "Light Music Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "Beginner Budokan Resolve",
        "a_valentines_weeb": "Htt Vow",
        "a_pi_day": "Cake Trial",
        "a_april_fools": "Marathon Devotion",
        "a_international_anime_day": "Htt Fan Pinnacle Pinnacle",
        "a_star_wars_day": "Practice Chronicle",
        "a_summer_solstice": "Meeting Calendar",
        "a_tanabata": "Band Focus",
        "a_friday_13th": "Amp Relic",
        "a_halloween_spirit": "Tea Room Vault Vow",
        "a_thanksgiving_binge": "Light Music Run",
        "a_christmas_special": "Htt Fan Season",
        "a_new_years_eve": "Music Pilgrimage",
        "a_birthday_watch": "Chord Vow",
        "a_holiday_marathon": "Loyal Overture",
        "a_independence_day": "Song Archive Banner",
        "a_culture_day": "Meeting Insignia",
        "a_spring_equinox": "Htt Decree",
        "a_earth_day": "Beginner Mantle Mantle",
        "a_labor_day": "Cake Seal Seal",
        "a_winter_solstice": "Setlist Pilgrimage",
        "a_anime_birthday": "Beginner Budokan Pilgrimage",
        "a_every_holiday": "Equipment Room Resolve Resolve",
        "a_consecutive_holidays": "Practice Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Practice Rank",
        "a_meta_collector": "K On Hoard",
        "a_meta_category_starter": "Song Archive Badge",
        "a_meta_tier_climber": "Band Glyph",
        "a_meta_tier_max": "Songs Writ",
        "a_meta_xp_earner": "Htt Fan Emblem",
        "a_meta_difficulty_easy": "Archive Mechanism",
        "a_meta_difficulty_hard": "Performance Writ",
        "a_meta_unlock_spree": "Loyal Cake Fan Panel",
        "a_meta_completionist": "Songs Learned Fulfillment",
        "a_meta_diverse": "K On Emblem",
        "a_meta_dominator": "Beginner Budokan Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Manga Chord",
        "m_chapter_counter": "Light Music Pinnacle",
        "m_chapter_titan": "Music Relic",
        "m_reading_hours": "Rehearsal Alerts Relic",
        "m_reading_time_lord": "Songs Learned Record Record",
        "m_manga_collector": "Loyal Ledger",
        "m_library_legend": "Meeting Reliquary",
        "m_first_complete": "Loyal Cake Fan Triumph",
        "m_hundred_club": "Htt Network",
        "m_first_day": "Loyal Dawn",
        "m_first_rating": "Cake Eye",
        "m_ten_thousand_pages": "Light Music Gauge",
        "m_volume_collector": "Loyal Cake Storehouse",
        "m_year_explorer": "Performance Quest",
        "m_century_reader": "Guitar Pedals Dominion",
        "m_five_hundred_ch": "Song Archive Ledger",
        "m_thousand_ch": "Budokan Legend",
        "m_reading_ten": "Loyal Cake Appraisal",
        "m_ptr_hoarder": "Songs Index",
        "m_dropped_honesty": "Song Archive Summit",
        "m_season_reader": "Songs Learned Treasury",
        "m_active_reader": "Band Trial",
        "m_five_thousand_ch": "Loyal Cake Fan Standard",
        "m_ten_completed": "Songs Learned Resolution",
        "m_fifty_completed": "Song Archive Harvest",
        "m_five_hundred_completed": "Rehearsal Alerts Legacy",
        "m_mean_score_tracker": "Tea Room Vault Audit",
        "m_unique_authors": "Loyal Reserve",
        "m_all_status": "Songs Testament",
        "m_first_favorite": "Setlist Cache",
        "m_favorites_collector": "Band Shelf",
        "m_days_spent_reading": "Budokan Decree",

        // ── MANGA BINGE ──
        "m_binge_reader": "Cake Streak",
        "m_marathon_reader": "Guitar Pedals Rush",
        "m_weekend_reader": "Archive Run",
        "m_non_stop_reading": "Cake Gauntlet",
        "m_one_more_chapter": "Htt Fan Testament",
        "m_speed_read": "Band Drive",
        "m_double_story": "Songs Learned Banner",
        "m_triple_read": "Lost Songs Record",
        "m_five_a_day": "Songs Learned Insignia",
        "m_chapter_chain": "Practice Accord",
        "m_volume_binge": "Amp Drive",
        "m_power_reader": "Archive Warrant",
        "m_half_day_read": "Equipment Room Aegis",
        "m_full_day_read": "Band Aegis",
        "m_power_weekend": "Beginner Budokan Streak",
        "m_binge_king": "Cake Momentum",
        "m_no_sleep_read": "Guitar Pedals Sleepless",
        "m_full_series_rush": "Archive Cascade",
        "m_seven_day_challenge": "Meeting Warrant",
        "m_hundred_day_read": "Songs Relic",
        "m_volume_rush": "Loyal Cake Gauntlet",
        "m_series_sweep": "Lost Songs Trial Trial",
        "m_genre_binge": "Lost Songs Binge",
        "m_author_binge": "Htt Fan Surge",
        "m_chapter_counter_day": "Concert Ledger",
        "m_multi_series_binge": "Songs Charge",
        "m_midnight_binge": "Lost Songs Tempest",
        "m_new_year_binge": "Loyal Passage",
        "m_forty_eight_hour": "Marathon Rally",
        "m_oneshot_binge": "Band Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Band Action",
        "m_genre_adventure": "Meeting Adventure",
        "m_genre_comedy": "Song Archive Comedy",
        "m_genre_drama": "Beginner Budokan Drama",
        "m_genre_fantasy": "Chord Fantasy",
        "m_genre_horror": "Band Horror",
        "m_genre_mystery": "Loyal Cake Fan Mystery",
        "m_genre_romance": "Setlist Romance",
        "m_genre_scifi": "Loyal Sci-Fi",
        "m_genre_sol": "Beginner Budokan Slice",
        "m_genre_sports": "Rehearsal Alerts Sports",
        "m_genre_supernatural": "Music Supernatural",
        "m_genre_thriller": "Music Thriller",
        "m_genre_psychological": "Marathon Psychological",
        "m_genre_isekai": "Loyal Cake Fan Isekai",
        "m_genre_shounen": "Beginner Budokan Shounen",
        "m_genre_ecchi": "Chord Ecchi",
        "m_genre_mahou_shoujo": "Tea Magic Shoujo",
        "m_genre_mecha": "Setlist Mecha",
        "m_genre_music": "Tea Room Vault Music",
        "m_tag_isekai_new": "Rehearsal Alerts Isekai New",
        "m_tag_harem": "Concert Harem",
        "m_tag_bl": "Concert Bl",
        "m_tag_gl": "Meeting Gl",
        "m_tag_historical": "Equipment Room Historical",
        "m_tag_military": "Beginner Military",
        "m_tag_school": "Concert School",
        "m_tag_martial_arts": "Concert Martial Arts",
        "m_tag_vampire": "Setlist Vampire",
        "m_tag_samurai": "Amp Samurai",
        "m_tag_space": "Loyal Space",
        "m_tag_parody": "Setlist Parody",
        "m_tag_idol": "Learned Idol",
        "m_tag_post_apocalyptic": "Songs Post Apocalyptic",
        "m_tag_cyberpunk": "Light Music Cyberpunk",
        "m_tag_shoujo": "Performance Shoujo",
        "m_tag_survival": "Song Archive Survival",
        "m_tag_cooking": "Tea Room Vault Cooking",
        "m_tag_medical": "Song Archive Medical",
        "m_tag_villainess": "Guitar Pedals Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Manga Archive",
        "m_mega_completionist": "Songs Learned Completion",
        "m_completion_rate_50": "Learned Return",
        "m_completion_rate_75": "Loyal Cake Fan Ascension",
        "m_completion_rate_90": "Equipment Room Resolution",
        "m_no_drop": "Rehearsal Alerts Decree Decree",
        "m_long_runner_complete": "Learned Clear",
        "m_sequel_chain": "Chord Seal",
        "m_clean_list": "Loyal Cake Fan Relic",
        "m_from_ptr": "Practice Watchlist",
        "m_reread_master": "Marathon Trial",
        "m_oneshot_complete": "Amp Ascension",
        "m_same_day_start_finish": "Loyal Cake Fan Crown",
        "m_revival": "Learned Accord",
        "m_zero_to_hundred": "Light Music Banner",
        "m_five_genre_complete": "Song Archive M Five Genre",
        "m_full_collection": "Loyal Proof",
        "m_batch_complete": "Practice Testament",
        "m_paused_to_done": "Meeting Standard",
        "m_completion_spree": "Songs Triumph",
        "m_format_completionist": "Htt Fan Completion",
        "m_catch_up": "Loyal Chronicle",
        "m_multi_reread": "Tea Room Vault Banner",
        "m_dropped_recovery": "Chord Conquest",
        "m_ten_perfect_scores": "Setlist Judgment",
        "m_complete_genre_span": "Music M Complete Genre Span",
        "m_monthly_completions": "Song Archive Return",
        "m_yearly_completions": "Music Epilogue",
        "m_rapid_complete": "Lost Songs Finale",
        "m_author_complete": "Light Music Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Performance Legacy",
        "m_mangaka_lover": "Rehearsal Alerts Standard",
        "m_rereader": "Cake Relic",
        "m_triple_reread": "Practice Testament Testament",
        "m_annual_reread": "Learned Banner",
        "m_publisher_fan": "Practice Mark",
        "m_artist_fan": "Marathon Insignia",
        "m_adaptation_compare": "Chord Insignia",
        "m_source_material_fan": "Lost Songs Cache",
        "m_waiting_weekly": "Marathon Streak",
        "m_classic_reader": "Amp Lantern",
        "m_saga_reader": "Beginner Budokan Crown",
        "m_genre_loyalty": "Archive Loyalty",
        "m_decade_reader": "Tea Room Vault Warrant",
        "m_ln_adaptation": "Amp Mark",
        "m_original_work": "Cake Standard",
        "m_long_commitment": "Cake Mark",
        "m_up_to_date": "Loyal Warrant",
        "m_favorite_mangaka": "Songs Treasury",
        "m_complete_portfolio": "Practice Triumph",
        "m_franchise_collector": "Loyal Cake Fan Archive",
        "m_serialization_follower": "Meeting Handshake",
        "m_genre_master": "Music Master",
        "m_multi_series_author": "Lost Songs Insignia",
        "m_format_diversity": "Cake Shelf",
        "m_year_dedication": "Tea Room Vault Tenure",
        "m_ongoing_follower": "Htt Fan Fellowship",
        "m_genre_loyalty_50": "Song Archive Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Light Music Explorer",
        "m_publisher_hopper": "Light Music Record",
        "m_tag_explorer": "Equipment Room Explorer",
        "m_decade_hopper": "Marathon Proof",
        "m_hidden_gem": "Rehearsal Alerts Mark Mark",
        "m_popular_taste": "Tea Room Vault Record",
        "m_retro_reader": "Htt Fan Accord",
        "m_modern_reader": "Performance Seal",
        "m_cross_demographic": "Meeting Crown",
        "m_underdog_fan": "Lost Songs Testament",
        "m_variety_week": "Tea Room Vault Horizon",
        "m_manhwa_reader": "Guitar Pedals Proof",
        "m_manhua_reader": "Cake Mantle",
        "m_classic_connoisseur": "Chord Glimpse",
        "m_award_winner": "Archive Warrant Warrant",
        "m_niche_explorer": "Cake Horizon",
        "m_world_manga": "Concert Chronicle",
        "m_cult_classic": "Setlist Map",
        "m_random_pick": "Archive Standard Standard",
        "m_new_genre_month": "Loyal M New Genre Month",
        "m_year_completionist": "Songs Learned Completion Fulfillment",
        "m_unpopular_opinion": "Archive Aegis",
        "m_top_rated_reader": "Meeting Pinnacle",
        "m_source_variety": "Setlist Catalogue",
        "m_low_score_brave": "Loyal Cake Fan Score",
        "m_short_manga_explorer": "Tea Compass",
        "m_long_manga_explorer": "Learned Survey",
        "m_serialization_explorer": "Songs Learned Road",

        // ── MANGA TIME ──
        "m_night_owl": "Htt Fan Accord Accord",
        "m_early_bird": "Practice Banner",
        "m_lunch_reader": "Setlist Relic",
        "m_commute_reader": "Songs Tenure",
        "m_four_am_club": "K On Fellowship",
        "m_new_year_read": "Cake Pact",
        "m_all_hours": "Budokan Accord",
        "m_prime_time_reader": "Guitar Pedals Banner",
        "m_workday_reader": "Cake Fan Accord",
        "m_sunday_read": "Beginner Standard Standard",
        "m_morning_routine": "Htt Discipline",
        "m_night_shift_reader": "Cake Fan Accord Accord",
        "m_seasonal_premier_read": "Archive Storehouse",
        "m_clock_collector": "Loyal Cake Reserve",
        "m_late_night_horror": "K On Mark Mark",
        "m_afternoon_reader": "Amp Mantle",
        "m_golden_hour_reader": "Tea Observance",
        "m_dawn_reader": "Meeting Mantle",
        "m_twilight_reader": "Marathon Crown",
        "m_midnight_start": "Amp Routine",
        "m_weekend_binge_hours": "Rehearsal Alerts Momentum",
        "m_late_night_regular": "Cake Testament Testament",
        "m_sunrise_reader": "Tea Room Vault Record Record",
        "m_every_day_of_week": "Budokan Seal Seal",
        "m_monthly_hours": "Songs Learned Vigil",
        "m_bedtime_reader": "Light Music Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Chord Mantle",
        "m_webtoon_reader": "Archive Mark",
        "m_full_color": "Cake Accord",
        "m_doujin_reader": "Performance Record",
        "m_anthology_reader": "Archive Accord",
        "m_adaptation_reader": "Archive Banner",
        "m_longstrip_reader": "Equipment Room Trial",
        "m_4koma_reader": "Band Relic",
        "m_oneshot_reader": "Music Mantle",
        "m_format_variety": "Song Archive Gallery",
        "m_light_novel_reader": "Equipment Room Insignia",
        "m_novel_reader": "Beginner Budokan Crown Crown",
        "m_visual_storyteller": "Tea Room Vault Testament",
        "m_colored_classic": "Htt Survey",
        "m_webcomic_fan": "Guitar Pedals Insignia",
        "m_manga_to_anime": "Band Record",
        "m_seinen_reader": "Setlist Pinnacle",
        "m_josei_reader": "Beginner Pinnacle",
        "m_award_winning_art": "Htt Relic",
        "m_debut_work": "Learned Dominion",
        "m_vertical_scroll": "Songs Learned Crown Crown",
        "m_traditional_format": "Loyal Cake Hoard",
        "m_cross_media": "Performance Accord",
        "m_spinoff_reader": "Songs Learned Accord",
        "m_remake_reader": "Performance Insignia",
        "m_collaboration_reader": "Archive Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "K On Focus",
        "m_mega_streak": "Cake Fan Routine",
        "m_weekly_warrior": "Concert Season",
        "m_monthly_reader": "Htt Monthly",
        "m_comeback": "Learned Standard",
        "m_weekend_streak": "Music Fever",
        "m_no_zero_days": "Cake Proof",
        "m_iron_will": "Chord Ledger",
        "m_habit_formed": "Meeting Crown Crown",
        "m_consistent_pace": "Loyal Cake Fan Scrutiny Scrutiny",
        "m_year_long": "Equipment Room Observance",
        "m_double_streak": "Music Resolve",
        "m_streak_recovery": "Songs Learned Resolve",
        "m_daily_minimum": "Htt Fan Focus",
        "m_winter_streak": "Equipment Room Observance Observance",
        "m_summer_streak": "Concert Observance",
        "m_morning_streak": "Music Clock",
        "m_night_streak": "Rehearsal Alerts Discipline",
        "m_unbreakable": "Songs Learned Warrant Warrant",
        "m_eternal_flame": "Band Record Record",
        "m_chapter_a_day": "Amp Relic Relic",
        "m_genre_streak": "Tea Streak",
        "m_completion_streak": "Loyal Cake Return",
        "m_rating_streak": "Band Appraisal",
        "m_multi_ch_streak": "Cake Fan Tenure",
        "m_author_streak": "Loyal Cake Calendar",
        "m_perfect_week_manga": "Beginner Accord",
        "m_diverse_streak": "Setlist Streak",

        // ── MANGA SCORING ──
        "m_critic": "Marathon Scrutiny",
        "m_perfect_ten": "Practice Verdict",
        "m_harsh_critic": "K On Scale",
        "m_fair_judge": "Amp Eye",
        "m_generous_spirit": "Learned Crown",
        "m_score_all": "Chord Reckoning",
        "m_wide_range": "Songs Learned Ledger Ledger",
        "m_controversial": "Equipment Room Standard Standard",
        "m_consistent_scorer": "Songs Grade",
        "m_score_sniper": "Learned Reckoning",
        "m_evolving_taste": "Loyal Cake Fan Trial",
        "m_bell_curve": "Learned Accord Accord",
        "m_picky_reader": "Tea Room Vault Ledger",
        "m_100_rated": "Archive Mark Mark",
        "m_500_rated": "Htt Fan Proof",
        "m_mediocre_majority": "Light Music Canon",
        "m_rating_spree": "Light Music Verdict",
        "m_score_variance": "Htt Measure",
        "m_binge_rater": "Chord Passage",
        "m_reread_rerate": "Loyal Banner",
        "m_masterpiece_hunter": "Band Banner",
        "m_contrarian": "Setlist Aegis",
        "m_optimist": "Lost Songs Accord",
        "m_score_distributor": "Loyal Balance",
        "m_genre_critic": "Setlist Critic",
        "m_mean_above_8": "Htt Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Archive Season",
        "m_valentines_read": "Meeting Observance",
        "m_pi_day": "Cake Fan Testament",
        "m_april_fools": "Songs Learned Devotion",
        "m_international_manga_day": "Learned Proof Proof",
        "m_free_comic_day": "Amp Chronicle",
        "m_summer_solstice": "Song Archive Focus",
        "m_tanabata": "Songs Learned Pilgrimage",
        "m_friday_13th": "Marathon Dominion",
        "m_halloween_read": "Performance Calendar",
        "m_thanksgiving_binge": "Music Charge",
        "m_christmas_read": "Loyal Pact",
        "m_new_years_eve": "Lost Songs Pilgrimage",
        "m_birthday_read": "Archive Focus",
        "m_holiday_marathon": "K On Rally",
        "m_independence_day": "Amp Aegis",
        "m_culture_day": "Loyal Cake Fan Seal",
        "m_spring_equinox": "Light Music Banner Banner",
        "m_earth_day": "Budokan Aegis",
        "m_labor_day": "Songs Learned Seal",
        "m_winter_solstice": "Songs Focus",
        "m_manga_birthday": "Cake Fan Ritual",
        "m_every_holiday_reader": "Learned Watch",
        "m_consecutive_holidays": "Chord Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Concert Proof",
        "m_fibonacci": "K On Dominion",
        "m_palindrome_day": "Cake Fan Relic Relic",
        "m_binary_day": "Tea Proof",
        "m_full_moon_read": "Learned Crown Crown",
        "m_leap_year_read": "Tea Room Vault Practice",
        "m_triple_seven": "Loyal Cake Trial",
        "m_thousand_complete": "Marathon Ascension",
        "m_nice": "Song Archive Seal",
        "m_power_level_chapters": "Songs Learned Aegis",
        "m_answer_42": "Guitar Pedals Aegis Aegis",
        "m_square_number": "Practice Standard",
        "m_prime_count": "Practice Insignia",
        "m_matching_date": "Loyal Cake Fan Mantle",
        "m_century_chapter": "K On Decree",
        "m_pi_chapters": "Guitar Pedals Proof Proof",
        "m_synchronicity": "Practice Emblem",
        "m_world_record": "Cake Warrant",
        "m_genre_clash": "Chord Clash",
        "m_time_traveler": "Equipment Room Decree",
        "m_double_digits": "Marathon Dominion Dominion",
        "m_one_two_three": "K On Warrant",
        "m_lucky_seven": "Song Archive Pinnacle",
        "m_exact_hundred_ch": "Tea Testament",
        "m_year_match_count": "Amp Yearlong",
        "m_chapter_match_date": "Song Archive Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Htt Fan Index",
        "m_manhwa_format": "Band Gallery",
        "m_manhua_format": "Lost Songs Storehouse",
        "m_ln_format": "Guitar Pedals Index",
        "m_oneshot_format": "Loyal Cake Fan Index",
        "m_doujin_format": "Songs Learned Cabinet",
        "m_novel_format": "Music Reserve",
        "m_format_master_manga": "Htt Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Equipment Room Link",
        "m_meta_collector": "Learned Reliquary",
        "m_meta_category_starter": "Songs Standard",
        "m_meta_tier_climber": "K On Token",
        "m_meta_tier_max": "Performance Token",
        "m_meta_xp_earner": "Setlist Anchor",
        "m_meta_difficulty_easy": "Setlist Panel",
        "m_meta_difficulty_hard": "Archive Node",
        "m_meta_unlock_spree": "Rehearsal Alerts Marker",
        "m_meta_completionist": "Band Triumph",
        "m_meta_diverse": "Loyal Cake Fan Anchor",
        "m_meta_dominator": "Practice Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#090204",
        primary: "#ee58ac",
        secondary: "#d03c8e",
        accent: "#f0d020",
    },
    particleColor: "#f070c0",
    backgroundDim: 0.22,
    backgroundBlur: 18,
    particleTypes: {
        music_notes: { label: "Music Notes", maxCount: 12, defaultEnabled: true, defaultIntensity: 60 },
        sparkles: { label: "Sparkles", maxCount: 10, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
  1: "Threadbare Generic Rank Spark",
  8: "Generic's Tarnished Omen",
  14: "Fractured Generic Rank",
  21: "Generic Rank Path",
  28: "Lowborn Legacy Myth",
  35: "Generic Rank Pulse",
  41: "Generic's Legacy Crest",
  48: "Humble Generic Mark",
  55: "Ragged Generic Rank Vow",
  61: "Generic's Faint Echo",
  68: "Lesser Generic Rank",
  75: "Generic Rank Zenith",
  81: "Doubtful Legacy Bloom",
  88: "Generic Rank Sigil",
  95: "Generic's Legacy Flame",
  102: "Really Cool Generic Spark",
  108: "Awakened Generic Rank Omen",
  115: "Generic's Resolute Seal",
  122: "Rising Generic Rank",
  128: "Generic Rank Myth",
  135: "Dauntless Legacy Pulse",
  142: "Generic Rank Crest",
  149: "Generic's Legacy Mark",
  155: "Fresh Generic Vow",
  162: "Valiant Generic Rank Echo",
  169: "Generic's Prime Crown",
  175: "Polished Generic Rank",
  182: "Generic Rank Bloom",
  189: "Stormlit Legacy Sigil",
  195: "Generic Rank Flame",
  202: "Generic's Legacy Spark",
  209: "Tempered Generic Omen",
  216: "Trusted Generic Rank Seal",
  222: "Generic's Steadfast Path",
  229: "Ironclad Generic Rank",
  236: "Veteran Legacy Pulse",
  242: "Core Legacy Crest",
  249: "Generic Rank Mark",
  256: "Generic's Legacy Vow",
  262: "Formidable Generic Echo",
  269: "Lucid Generic Rank Crown",
  276: "Generic's Ranked Zenith",
  283: "Fabled Generic Rank",
  289: "Grand Legacy Sigil",
  296: "Seasoned Legacy Flame",
  303: "Generic Rank Spark",
  309: "Generic's Legacy Omen",
  316: "Valorous Generic Seal",
  323: "Stalwart Generic Rank Path",
  330: "Generic's Commanding Myth",
  336: "Refined Generic Rank",
  343: "Unbroken Legacy Crest",
  350: "Blazing Legacy Mark",
  356: "Generic Rank Vow",
  363: "Generic's Legacy Echo",
  370: "Peerless Generic Crown",
  376: "Ardent Generic Rank Zenith",
  383: "Generic's Focused Bloom",
  390: "Vigilant Generic Rank",
  397: "Dominant Legacy Flame",
  403: "Elite Legacy Spark",
  410: "Generic Rank Omen",
  417: "Generic's Legacy Seal",
  423: "Sovereign Generic Path",
  430: "Regal Generic Rank Myth",
  437: "Generic's Crowned Pulse",
  444: "Mythborn Generic Rank",
  450: "Limitless Legacy Mark",
  457: "Radiant Legacy Vow",
  464: "Generic Rank Echo",
  470: "Generic's Legacy Crown",
  477: "Climactic Generic Zenith",
  484: "Epic Generic Rank Bloom",
  490: "Generic's Unreal Sigil",
  497: "Peak Generic Rank",
  504: "Supreme Legacy Spark",
  511: "Exalted Legacy Omen",
  517: "Generic Rank Seal",
  524: "Generic's Legacy Path",
  531: "Celestial Generic Myth",
  537: "Phantom Generic Rank Pulse",
  544: "Generic's Crimson Crest",
  551: "Silver Generic Rank",
  557: "Golden Legacy Vow",
  564: "Feral Legacy Echo",
  571: "Generic Rank Crown",
  578: "Generic's Legacy Zenith",
  584: "Dread Generic Bloom",
  591: "Luminous Generic Rank Sigil",
  598: "Generic's Thunderous Flame",
  604: "Ultraviolet Generic Rank",
  611: "Unleashed Legacy Omen",
  618: "Secret Legacy Seal",
  625: "Final Generic Path",
  631: "Generic's Legacy Myth",
  638: "Worldclass Generic Pulse",
  645: "Lawless Generic Rank Crest",
  651: "Generic's Chosen Mark",
  658: "Fearless Generic Rank",
  665: "Overdrive Legacy Echo",
  671: "Cinematic Legacy Crown",
  678: "Impossible Generic Zenith",
  685: "Generic's Legacy Bloom",
  692: "Canonized Generic Sigil",
  698: "Ascendant Generic Rank Flame",
  705: "Generic's Transfigured Spark",
  712: "Immortal Generic Rank",
  718: "Eclipsed Legacy Seal",
  725: "Astral Legacy Path",
  732: "Sublime Generic Myth",
  739: "Generic's Legacy Pulse",
  745: "Prismatic Generic Crest",
  752: "Abyssal Generic Rank Mark",
  759: "Generic's Unbound Vow",
  765: "Eternal Generic Rank",
  772: "Cosmic Legacy Crown",
  779: "Transcendent Legacy Zenith",
  785: "Perfected Generic Bloom",
  792: "Generic's Legacy Sigil",
  799: "Ultimate Generic Flame",
  806: "Mythic Generic Rank Spark",
  812: "Generic's Godlike Omen",
  819: "Canonical Generic Rank",
  826: "Reality-Bent Legacy Path",
  832: "Heavenly Legacy Myth",
  839: "Absolute Generic Pulse",
  846: "Untouchable Generic Crest",
  852: "Timeless Generic Mark",
  859: "Empyrean Generic Rank Vow",
  866: "Generic's Primordial Echo",
  873: "Omniscient Generic Rank",
  879: "Unfathomed Legacy Zenith",
  886: "Apocalyptic Legacy Bloom",
  893: "Seraphic Generic Sigil",
  899: "Omega Generic Flame",
  906: "Final Generic Spark",
  913: "Crowned Generic Rank Omen",
  920: "Generic's Mythic Seal",
  926: "Absolute Generic Rank",
  933: "Eternal Legacy Myth",
  940: "Cosmic Legacy Pulse",
  946: "Transcendent Generic Crest",
  953: "Perfected Generic Mark",
  960: "Definitive Generic Vow",
  966: "Ultimate Generic Rank Echo",
  973: "Generic's Infinite Crown",
  980: "Sovereign Generic Rank",
  987: "Celestial Legacy Bloom",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate Generic Rank"
},
}
