import { AnimeThemeConfig } from "./types"
import { GiCrown, GiHeartKey, GiRose, GiPaperArrow, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiQuillInk } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const kaguyaSamaTheme: AnimeThemeConfig = {
    id: "kaguya-sama",
    displayName: "Kaguya-sama: Love is War",
    description: "Student council president Miyuki Shirogane and vice-president Kaguya Shinomiya are both deeply in love with each other — but too proud to confess, they scheme endlessly to make the other confess first in this battle of wits and hearts.",
    fontFamily: "'Sawarabi Gothic', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Sawarabi+Gothic&display=swap",
    cssVars: {
        "--color-brand-200": "250 185 185",
        "--color-brand-300": "238 130 130",
        "--color-brand-400": "220 75 75",
        "--color-brand-500": "198 28 28",
        "--color-brand-600": "158 10 10",
        "--color-brand-700": "114 3 3",
        "--color-brand-800": "72 0 0",
        "--color-brand-900": "36 0 0",
        "--color-brand-950": "15 0 0",
        "--brand": "198 28 28",
        "--background": "#060000",
        "--paper": "#120000",
        "--color-gray-950": "6 0 0",
        "--color-gray-900": "12 2 2",
        "--color-gray-800": "22 4 4",
        "--color-gray-700": "36 8 8",
        "--color-gray-600": "58 14 14",
        "--color-gray-500": "90 24 24",
        "--color-gray-400": "130 48 48",
        "--color-gray-300": "172 85 85",
        "--color-gray-200": "205 130 130",
        "--color-gray-100": "228 175 175",
        "--color-gray-50": "245 215 215",
    },
    sidebarOverrides: {
        "home": { icon: GiCrown, label: "Shuchiin Academy" },
        "schedule": { icon: GiAlarmClock, label: "Council Schedule" },
        "manga": { icon: LuBookOpen, label: "Love War Files" },
        "lists": { icon: GiRose, label: "Scheme Registry" },
        "discover": { icon: GiBullseye, label: "New Battles" },
        "torrent-list": { icon: GiPaperArrow, label: "Letter Cache" },
        "debrid": { icon: GiHeartKey, label: "Council Store" },
        "unmatched": { icon: GiQuillInk, label: "Failed Schemes" },
        "enmasse": { icon: GiResize, label: "Council Events" },
        "scan-summaries": { icon: TbReportSearch, label: "Battle Reports" },
        "auto-downloader": { icon: LuRss, label: "Love War Feed" },
        "community": { icon: GiCrown, label: "Student Council" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Council Alerts" },
        "achievements": { icon: GiTrophy, label: "Council Trophies" },
        "milestones": { icon: LuFlag, label: "Confession Goals" },
        "theme-manager": { icon: GiPalette, label: "Crimson Colors" },
        "extensions": { icon: BiExtension, label: "Scheme Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Love War Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Miyuki Settings" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Battle",
        "a_episode_counter": "Council Return Mark",
        "a_episode_titan": "Scheme Depth Relic",
        "a_hours_invested": "Love War Streak Proof",
        "a_time_lord": "Council Veteran",
        "a_anime_collector": "Scheme Collection",
        "a_library_legend": "Shuchiin Archives",
        "a_first_complete": "Love Confessed",
        "a_hundred_club": "Hundred Battles",
        "a_first_day": "Love Destiny Seal",
        "a_first_rating": "Scheme Depth Appraisal",
        "a_ten_thousand_min": "Council Alerts Standard",
        "a_season_veteran": "Council Alerts Library",
        "a_year_explorer": "Miyuki Kaguya Map",
        "a_century_watcher": "Kaguya Expert Ledger",
        "a_five_hundred_eps": "Kaguya's Ice Dominion",
        "a_thousand_eps": "Night Scheming Record",
        "a_watching_ten": "Love War Fan Acclaim",
        "a_ptw_hoarder": "Battle Marathon Library",
        "a_dropped_honesty": "Love War Fan Summit",
        "a_five_thousand_eps": "Pride Resolve Warrant",
        "a_ten_completed": "Rival Lover Afterglow",
        "a_fifty_completed": "Miyuki's Grind Ascension",
        "a_five_hundred_completed": "Love War Fan Clear",
        "a_mean_score_tracker": "School Journey Verdict",
        "a_unique_studios": "Night Scheming Collection",
        "a_days_spent_watching": "Student Council Dominion",
        "a_all_status": "Kaguya's Heart Testament",
        "a_first_favorite": "Aka Master Cabinet",
        "a_favorites_collector": "Daily Battle Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Perfect Plan Drive",
        "a_marathon_runner": "Miyuki's Grind",
        "a_weekend_warrior": "Scheme Depth Ordeal",
        "a_non_stop": "Kaguya Standard Fever",
        "a_one_more_episode": "Night Schemes Mantle",
        "a_speed_run": "Kaguya's Speed",
        "a_double_feature": "All Night Crown",
        "a_triple_threat": "Failed Schemes Record",
        "a_five_a_day": "Too Proud Accord",
        "a_back_to_back": "Kaguya's Speed Surge",
        "a_seasonal_binge": "Scheme Depth Cascade",
        "a_cour_crusher": "Student Council Ordeal",
        "a_half_day_watch": "Council Return Crown",
        "a_full_day_watch": "War Critic Pinnacle",
        "a_power_weekend": "Love Destiny Run",
        "a_binge_king": "Battle Marathon",
        "a_no_sleep": "All-Night Scheming",
        "a_entire_season": "Aka Classic Library",
        "a_seven_day_challenge": "War Critic Mark",
        "a_hundred_day_binge": "Love Destiny Surge",
        "a_genre_binge": "Morning Tactics Binge",
        "a_studio_binge": "Council Return Fever",
        "a_season_sweep": "Miyuki Shirogane Codex",
        "a_forty_eight_hour": "War Streak Overture",
        "a_ep_counter_day": "Rival Lover Aegis",
        "a_multi_series_binge": "Battle Marathon Streak",
        "a_midnight_binge": "Night Schemes Cascade",
        "a_new_year_binge": "Battle Wits Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Battle of Wits",
        "a_genre_adventure": "School Journey",
        "a_genre_comedy": "Chika's Chaos",
        "a_genre_drama": "Kaguya's Heart",
        "a_genre_fantasy": "Love War",
        "a_genre_horror": "Kaguya's Ice",
        "a_genre_mystery": "Scheme Registry Mystery",
        "a_genre_romance": "Miyuki Kaguya",
        "a_genre_scifi": "None Here",
        "a_genre_sol": "Pride Resolve Slice",
        "a_genre_sports": "War Streak Sports",
        "a_genre_supernatural": "Love Destiny",
        "a_genre_thriller": "Miyuki's Grind Thriller",
        "a_genre_mecha": "None Here",
        "a_genre_music": "Council Alerts Music",
        "a_genre_psychological": "Scheming Minds",
        "a_genre_ecchi": "Perfect Plan Ecchi",
        "a_genre_mahou_shoujo": "Failed Schemes Magic Shoujo",
        "a_tag_isekai": "Kaguya Ultra Romantic Isekai",
        "a_tag_harem": "War Fan Harem",
        "a_tag_bl": "War Streak Bl",
        "a_tag_gl": "Night Schemes Gl",
        "a_tag_historical": "Aka Art Historical",
        "a_tag_military": "Kaguya's Ice Military",
        "a_tag_school": "Battle Marathon School",
        "a_tag_martial_arts": "War Critic Martial Arts",
        "a_tag_vampire": "Failed Schemes Vampire",
        "a_tag_samurai": "Night Scheming Samurai",
        "a_tag_space": "Love War Space",
        "a_tag_parody": "Decade Fan Parody",
        "a_tag_idol": "War Streak Idol",
        "a_tag_post_apocalyptic": "Scheming Minds Post Apocalyptic",
        "a_tag_cyberpunk": "Kaguya Standard Cyberpunk",
        "a_tag_shounen": "Scheming Minds Shounen",
        "a_tag_seinen": "Wit Critic Seinen",
        "a_tag_shoujo": "Wit Critic Shoujo",
        "a_tag_josei": "Rival Lover Josei",
        "a_tag_survival": "Daily Battle Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "All Seasons",
        "a_mega_completionist": "Aka Master",
        "a_completion_rate_50": "Failed Schemes Return",
        "a_completion_rate_75": "Miyuki's Grind Crown",
        "a_completion_rate_90": "Rival Lover Resolution",
        "a_no_drop": "Scheme Registry Decree",
        "a_long_runner_complete": "Love Destiny Clear",
        "a_sequel_chain": "Kaguya Ultra Romantic",
        "a_clean_list": "Miyuki Shirogane Relic",
        "a_from_ptw": "Decade Fan Index",
        "a_rewatch_master": "School Journey Return",
        "a_short_complete": "Love Confessed Endgame",
        "a_same_day_start_finish": "Ultra Romantic Pinnacle",
        "a_revival": "Kaguya Expert Insignia",
        "a_zero_to_hero": "Rival to Lover",
        "a_five_genre_complete": "Love Confessed A Five Genre",
        "a_full_franchise": "Battle Marathon Chronicle",
        "a_batch_complete": "Scheme Depth Crown",
        "a_paused_to_done": "Rival Lover Aegis Aegis",
        "a_completion_spree": "Chika's Chaos Triumph",
        "a_multi_rewatch": "Chika's Chaos Triumph Triumph",
        "a_dropped_recovery": "Council Return Conquest",
        "a_ten_perfect_scores": "Love Destiny Acclaim",
        "a_seasonal_clear": "Student Council Codex",
        "a_complete_genre_span": "All Arcs A Complete Genre",
        "a_monthly_completions": "School Journey Afterglow",
        "a_yearly_completions": "Kaguya's Heart Epilogue",
        "a_rapid_complete": "War Critic Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Love War Fan",
        "a_studio_devotee": "Scheme Registry Treasury",
        "a_rewatcher": "Council Return",
        "a_triple_rewatch": "Morning Tactics Coda",
        "a_annual_tradition": "War Critic Proof",
        "a_director_fan": "Miyuki Shirogane Trial",
        "a_voice_actor_fan": "Council Return Crown Crown",
        "a_ost_lover": "Battle Marathon Seal",
        "a_source_reader": "Miyuki Kaguya Cabinet",
        "a_waiting_weekly": "Scheme Registry Clock",
        "a_childhood_revisit": "Kaguya Ultra Seal",
        "a_saga_tracker": "Love War Standard",
        "a_genre_loyalty": "Pride Resolve Loyalty",
        "a_decade_watcher": "Decade Fan",
        "a_adaptation_hunter": "Decade Fan Trial",
        "a_original_anime_fan": "Endless War Testament",
        "a_long_commitment": "War Critic Mark Mark",
        "a_perfect_attendance": "Love War Fan Standard",
        "a_favorite_studio_5": "Scheming Minds Library",
        "a_complete_catalog": "Daily Battle Seal",
        "a_franchise_collector": "Scheming Minds Archive",
        "a_airing_follower": "Kaguya Ultra Signal",
        "a_genre_master": "Miyuki Shirogane Master",
        "a_staff_follower": "Scheming Minds Oath",
        "a_multi_season_fan": "Aka Art Hoard",
        "a_format_diversity": "Failed Schemes Cache",
        "a_year_dedication": "Scheme Depth Tenure",
        "a_season_dedication": "Kaguya's Ice Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Morning Tactics Explorer",
        "a_studio_hopper": "School Journey Collection",
        "a_tag_explorer": "Scheme Depth Explorer",
        "a_decade_hopper": "Battle Marathon Chronicle Chronicle",
        "a_hidden_gem": "Hidden Episode",
        "a_popular_taste": "War Streak Decree",
        "a_retro_appreciator": "Daily Battle Aegis",
        "a_modern_viewer": "Ultra Romantic Pinnacle Pinnacle",
        "a_cross_demographic": "Perfect Plan Pinnacle",
        "a_underdog_fan": "All Arcs Trial",
        "a_variety_week": "Scheming Minds Horizon",
        "a_foreign_cinema": "Night Schemes Expedition",
        "a_classic_connoisseur": "2015 Fan",
        "a_every_season": "Kaguya Ultra Archive",
        "a_award_winner": "Council Alerts Insignia",
        "a_niche_explorer": "Wit Critic Horizon",
        "a_global_anime": "Love Confessed Crown",
        "a_cult_classic": "Aka Classic",
        "a_random_pick": "War Streak Decree Decree",
        "a_new_genre_month": "Love War Fan A New",
        "a_seasonal_completionist": "Kaguya Expert Summit",
        "a_unpopular_opinion": "Aka Master Standard",
        "a_top_rated_viewer": "Too Proud Seal",
        "a_source_variety": "Student Council Storehouse",
        "a_low_score_brave": "Kaguya Standard Measure",
        "a_upcoming_watcher": "Too Proud Seal Seal",
        "a_short_series_explorer": "Night Schemes Expedition Expedition",
        "a_long_series_explorer": "All Night Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Night Schemes",
        "a_early_bird": "Morning Tactics",
        "a_lunch_break": "Aka Fan Trial",
        "a_golden_hour": "Council Events Tenure",
        "a_four_am_club": "Chika's Chaos Gathering",
        "a_witching_hour": "Miyuki's Grind Tenure",
        "a_new_year_watch": "Scheme Depth Season",
        "a_midnight_premiere": "Battle Wits Devotion",
        "a_all_hours": "Kaguya Expert Seal",
        "a_dawn_warrior": "War Streak Aegis",
        "a_afternoon_delight": "Love War Streak Proof Proof",
        "a_prime_time": "Council Alerts Insignia Insignia",
        "a_workday_watcher": "Perfect Plan Pinnacle Pinnacle",
        "a_sunday_marathon": "Love Destiny Momentum",
        "a_rainy_day": "Miyuki's Grind Relic",
        "a_morning_routine": "Aka Art Promise",
        "a_night_shift": "Failed Schemes Aegis",
        "a_twilight_zone": "Aka Classic Ledger",
        "a_seasonal_premier": "Scheme Registry Cabinet",
        "a_clock_collector": "Chika's Chaos Repository",
        "a_weekend_binge_hours": "Wit Critic Streak",
        "a_late_night_regular": "Kaguya's Heart Dominion",
        "a_sunrise_watcher": "Miyuki Shirogane Relic Relic",
        "a_holiday_watcher": "Too Proud Pact",
        "a_every_day_of_week": "Kaguya's Speed Ledger",
        "a_monthly_hours": "War Streak Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Rival Lover Record",
        "a_party_host": "Failed Schemes Record Record",
        "a_social_butterfly": "Miyuki Kaguya Company",
        "a_group_binge": "Night Scheming Sprint",
        "a_party_regular": "Aka Classic Chronicle",
        "a_sync_viewer": "Chika's Chaos Standard",
        "a_commentator": "Daily Battle Record",
        "a_party_marathon": "Morning Tactics Vigil",
        "a_full_house": "Kaguya's Ice Trial",
        "a_community_pillar": "Kaguya's Heart Alliance",
        "a_watch_party_streak": "Daily Battle Vigil",
        "a_diverse_party": "Aka Art Seal",
        "a_late_night_party": "Kaguya's Heart Testament Testament",
        "a_party_veteran": "Kaguya's Ice Testament",
        "a_genre_party": "Night Schemes Party",
        "a_weekly_party": "Chika's Chaos Calendar",
        "a_silent_viewer": "Endless War Mantle",
        "a_recommendation_giver": "Wit Critic Network",
        "a_party_completionist": "Love War Coda",
        "a_social_scorer": "Miyuki Shirogane Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "All Night Proof",
        "a_fibonacci": "Scheme Depth Dominion",
        "a_palindrome_day": "Scheme Depth Relic Relic",
        "a_binary_day": "Pride Resolve Mark",
        "a_full_moon": "Kaguya Ultra Insignia",
        "a_leap_year": "Love Confessed Devotion",
        "a_time_traveler": "Scheme Registry Record",
        "a_genre_clash": "Morning Tactics Clash",
        "a_triple_seven": "Scheme Depth Testament",
        "a_thousand_complete": "Endless War Epilogue",
        "a_pi_episodes": "Perfect Plan Crown",
        "a_synchronicity": "All Arcs Anchor",
        "a_world_record": "Council Return Warrant",
        "a_nice": "Council Alerts Chronicle",
        "a_power_level": "Endless War Testament Testament",
        "a_answer_42": "War Streak Standard",
        "a_square_number": "Morning Tactics Decree",
        "a_prime_count": "Council Alerts Seal",
        "a_matching_date": "All Arcs Mantle",
        "a_century_episode": "Perfect Plan Mark",
        "a_double_digits": "Miyuki's Grind Testament",
        "a_one_two_three": "Love Confessed Crown Crown",
        "a_lucky_seven": "War Critic Crown",
        "a_all_tens": "Kaguya Standard Criterion",
        "a_exact_hundred_eps": "Love War Legend Standard",
        "a_year_match_count": "Scheme Registry Yearlong",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Wit Critic Ledger",
        "a_movie_buff": "Council Return Mark Mark",
        "a_ova_hunter": "Love War Standard Standard",
        "a_ona_explorer": "All Arcs Secret",
        "a_special_watcher": "Miyuki's Grind Relic Relic",
        "a_short_king": "War Fan Crown",
        "a_variety_pack": "Council Return Inquiry",
        "a_film_festival": "Too Proud Chronicle",
        "a_music_video": "Aka Art Chronicle",
        "a_tv_short": "Morning Tactics Record",
        "a_movie_marathon": "Morning Tactics Gauntlet",
        "a_double_length": "All Night Crown Crown",
        "a_anthology": "Failed Schemes Aegis Aegis",
        "a_mini_series": "Aka Master Decree",
        "a_theatrical": "Scheming Minds Accord",
        "a_format_master": "Chika's Chaos Vault",
        "a_long_movie": "Kaguya Expert Insignia Insignia",
        "a_back_catalog": "Daily Battle Standard",
        "a_cm_watcher": "Kaguya Ultra Romantic Aegis",
        "a_pv_collector": "All Arcs Storehouse",
        "a_format_balance": "Chika's Chaos Vault Vault",
        "a_episodic_master": "Kaguya Ultra Romantic Standard",
        "a_sequel_movie": "Love Confessed Pinnacle",
        "a_recap_watcher": "Aka Fan Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Battle",
        "a_mega_streak": "Endless War",
        "a_weekly_warrior": "Kaguya's Ice Season",
        "a_monthly_watcher": "Battle Wits Calendar",
        "a_comeback": "Miyuki Kaguya Decree",
        "a_weekend_streak": "Kaguya Standard Passage",
        "a_no_zero_days": "Pride Resolve Warrant Warrant",
        "a_iron_will": "Too Proud",
        "a_habit_formed": "Kaguya's Speed Banner",
        "a_consistent_pace": "All Night Measure",
        "a_year_long": "Year of Schemes",
        "a_double_streak": "Miyuki Shirogane Watch",
        "a_streak_recovery": "Endless War Season",
        "a_daily_minimum": "Battle Wits Focus",
        "a_winter_streak": "Night Schemes Watch",
        "a_summer_streak": "Miyuki's Grind Resolve",
        "a_morning_streak": "Daily Battle Clock",
        "a_night_streak": "Kaguya's Speed Constancy",
        "a_unbreakable": "War Fan Proof",
        "a_eternal_flame": "School Journey Standard",
        "a_completion_streak": "Love War Return",
        "a_rating_streak": "Scheme Depth Balance",
        "a_multi_ep_streak": "Council Return Ritual",
        "a_genre_streak": "Scheme Depth Streak",
        "a_studio_streak": "Miyuki Kaguya Cabinet Cabinet",
        "a_perfect_week": "All Arcs Relic",

        // ── ANIME SCORING ──
        "a_critic": "Wit Critic",
        "a_perfect_ten": "Perfect Plan",
        "a_harsh_critic": "Kaguya Standard",
        "a_fair_judge": "Kaguya's Heart Balance",
        "a_generous_spirit": "Battle Wits Pinnacle",
        "a_score_all": "Love War Streak Criterion",
        "a_wide_range": "Council Alerts Ledger",
        "a_controversial": "Daily Battle Decree",
        "a_consistent_scorer": "Scheme Registry Verdict",
        "a_score_sniper": "Love Confessed Score",
        "a_evolving_taste": "Miyuki Shirogane Testament",
        "a_bell_curve": "Love War Fan Insignia",
        "a_picky_watcher": "Endless War Warrant",
        "a_100_rated": "Chika's Chaos Warrant",
        "a_500_rated": "War Fan Pinnacle",
        "a_mediocre_majority": "All Arcs Canon",
        "a_rating_spree": "Daily Battle Review",
        "a_score_variance": "Kaguya Standard Score",
        "a_masterpiece_hunter": "Daily Battle Banner",
        "a_contrarian": "Morning Tactics Record Record",
        "a_optimist": "Aka Art Ledger",
        "a_score_distributor": "Aka Fan Appraisal",
        "a_genre_critic": "All Night Critic",
        "a_mean_above_8": "War Critic Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Council",
        "a_valentines_weeb": "Scheming Minds Vow",
        "a_pi_day": "Kaguya's Heart Trial",
        "a_april_fools": "Love Confessed Devotion Devotion",
        "a_international_anime_day": "Kaguya Expert Record",
        "a_star_wars_day": "Love Destiny Chronicle",
        "a_summer_solstice": "Pride Resolve Calendar",
        "a_tanabata": "Ultra Romantic Focus",
        "a_friday_13th": "Aka Fan Relic",
        "a_halloween_spirit": "Wit Critic Vow",
        "a_thanksgiving_binge": "Aka Classic Run",
        "a_christmas_special": "Winter Confession",
        "a_new_years_eve": "War Critic Pilgrimage",
        "a_birthday_watch": "Love War Fan Vow",
        "a_holiday_marathon": "Night Scheming Overture",
        "a_independence_day": "School Journey Banner",
        "a_culture_day": "Battle Marathon Insignia",
        "a_spring_equinox": "Night Scheming Decree",
        "a_earth_day": "Council Return Mantle",
        "a_labor_day": "Wit Critic Seal",
        "a_winter_solstice": "Perfect Plan Pilgrimage",
        "a_anime_birthday": "Council Return Pilgrimage",
        "a_every_holiday": "Decade Fan Resolve",
        "a_consecutive_holidays": "Miyuki's Grind Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Miyuki Kaguya Rank",
        "a_meta_collector": "Battle Marathon Hoard",
        "a_meta_category_starter": "Battle Wits Badge",
        "a_meta_tier_climber": "Battle Marathon Glyph",
        "a_meta_tier_max": "Love War Legend",
        "a_meta_xp_earner": "Aka Fan Emblem",
        "a_meta_difficulty_easy": "Kaguya's Heart Mechanism",
        "a_meta_difficulty_hard": "Too Proud Writ",
        "a_meta_unlock_spree": "Kaguya's Ice Panel",
        "a_meta_completionist": "All Arcs",
        "a_meta_diverse": "Scheme Depth Emblem",
        "a_meta_dominator": "Aka Classic Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Scheme",
        "m_chapter_counter": "Chika's Chaos Pinnacle",
        "m_chapter_titan": "Student Council Relic",
        "m_reading_hours": "Aka Fan Relic Relic",
        "m_reading_time_lord": "Kaguya Expert Record Record",
        "m_manga_collector": "Kaguya's Ice Ledger",
        "m_library_legend": "Battle Marathon Reliquary",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "Scheming Minds Seal",
        "m_first_rating": "Aka Fan Eye",
        "m_ten_thousand_pages": "Scheming Minds Gauge",
        "m_volume_collector": "Endless War Storehouse",
        "m_year_explorer": "War Streak Quest",
        "m_century_reader": "Night Schemes Dominion",
        "m_five_hundred_ch": "Council Alerts Legend",
        "m_thousand_ch": "Miyuki Shirogane Legend",
        "m_reading_ten": "Night Schemes Appraisal",
        "m_ptr_hoarder": "Miyuki Shirogane Index",
        "m_dropped_honesty": "Battle Marathon Summit",
        "m_season_reader": "Daily Battle Treasury",
        "m_active_reader": "Miyuki's Grind Trial",
        "m_five_thousand_ch": "Morning Tactics Standard",
        "m_ten_completed": "Morning Tactics Resolution",
        "m_fifty_completed": "Miyuki Shirogane Harvest",
        "m_five_hundred_completed": "Kaguya's Speed Legacy",
        "m_mean_score_tracker": "Scheme Registry Audit",
        "m_unique_authors": "Council Return Reserve",
        "m_all_status": "Miyuki's Grind Testament Testament",
        "m_first_favorite": "Love War Cache",
        "m_favorites_collector": "Miyuki Kaguya Shelf",
        "m_days_spent_reading": "Perfect Plan Relic",

        // ── MANGA BINGE ──
        "m_binge_reader": "Love War Fan Streak",
        "m_marathon_reader": "Kaguya's Heart Rush",
        "m_weekend_reader": "Kaguya Ultra Run",
        "m_non_stop_reading": "Love War Gauntlet",
        "m_one_more_chapter": "Aka Fan Testament Testament",
        "m_speed_read": "Pride Resolve Drive",
        "m_double_story": "Night Scheming Banner",
        "m_triple_read": "School Journey Record",
        "m_five_a_day": "Aka Art Insignia",
        "m_chapter_chain": "Battle Marathon Accord",
        "m_volume_binge": "Kaguya Standard Drive",
        "m_power_reader": "Love Destiny Seal Seal",
        "m_half_day_read": "Miyuki Kaguya Aegis",
        "m_full_day_read": "Kaguya Ultra Romantic Aegis Aegis",
        "m_power_weekend": "Scheming Minds Streak",
        "m_binge_king": "Battle Marathon",
        "m_no_sleep_read": "Night Schemes Rush",
        "m_full_series_rush": "Kaguya's Heart Cascade",
        "m_seven_day_challenge": "Ultra Romantic Warrant",
        "m_hundred_day_read": "Scheme Depth Legend",
        "m_volume_rush": "Rival Lover Gauntlet",
        "m_series_sweep": "Decade Fan Trial Trial",
        "m_genre_binge": "Kaguya Ultra Romantic Binge",
        "m_author_binge": "Kaguya Ultra Surge",
        "m_chapter_counter_day": "Aka Classic Ledger Ledger",
        "m_multi_series_binge": "Council Alerts Charge",
        "m_midnight_binge": "Miyuki Shirogane Tempest",
        "m_new_year_binge": "Council Return Passage",
        "m_forty_eight_hour": "Scheme Registry Rally",
        "m_oneshot_binge": "Pride Resolve Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Battle Chapter",
        "m_genre_adventure": "School Chapter",
        "m_genre_comedy": "Miyuki Kaguya Comedy",
        "m_genre_drama": "Confession Chapter",
        "m_genre_fantasy": "War Chapter",
        "m_genre_horror": "Ice Chapter",
        "m_genre_mystery": "Morning Tactics Mystery",
        "m_genre_romance": "Heart Chapter",
        "m_genre_scifi": "Unusual Chapter",
        "m_genre_sol": "Chika's Chaos Slice",
        "m_genre_sports": "Rival Lover Sports",
        "m_genre_supernatural": "Destiny Chapter",
        "m_genre_thriller": "All Arcs Thriller",
        "m_genre_psychological": "Scheme Depth",
        "m_genre_isekai": "Kaguya's Ice Isekai",
        "m_genre_shounen": "Council Events Shounen",
        "m_genre_ecchi": "All Night Ecchi",
        "m_genre_mahou_shoujo": "Miyuki Kaguya Magic Shoujo",
        "m_genre_mecha": "Endless War Mecha",
        "m_genre_music": "Wit Critic Music",
        "m_tag_isekai_new": "Aka Fan Isekai New",
        "m_tag_harem": "Love War Streak Harem",
        "m_tag_bl": "Aka Master Bl",
        "m_tag_gl": "Miyuki Shirogane Gl",
        "m_tag_historical": "Council Alerts Historical",
        "m_tag_military": "Council Events Military",
        "m_tag_school": "Scheming Minds School",
        "m_tag_martial_arts": "Chika's Chaos Martial Arts",
        "m_tag_vampire": "Rival Lover Vampire",
        "m_tag_samurai": "Failed Schemes Samurai",
        "m_tag_space": "Aka Master Space",
        "m_tag_parody": "Endless War Parody",
        "m_tag_idol": "Aka Master Idol",
        "m_tag_post_apocalyptic": "Battle Marathon Post Apocalyptic",
        "m_tag_cyberpunk": "Love War Streak Cyberpunk",
        "m_tag_shoujo": "Too Proud Shoujo",
        "m_tag_survival": "Miyuki Kaguya Survival",
        "m_tag_cooking": "Love War Fan Cooking",
        "m_tag_medical": "Miyuki's Grind Medical",
        "m_tag_villainess": "Kaguya Ultra Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Kaguya Expert",
        "m_completion_rate_50": "Aka Master Return",
        "m_completion_rate_75": "All Arcs Ascension",
        "m_completion_rate_90": "School Journey Resolution",
        "m_no_drop": "Love War Decree",
        "m_long_runner_complete": "Aka Classic Clear",
        "m_sequel_chain": "Wit Critic Seal Seal",
        "m_clean_list": "Student Council Relic Relic",
        "m_from_ptr": "Too Proud Watchlist",
        "m_reread_master": "Kaguya's Heart Trial Trial",
        "m_oneshot_complete": "Kaguya's Heart Ascension",
        "m_same_day_start_finish": "War Critic Crown Crown",
        "m_revival": "Aka Classic Accord",
        "m_zero_to_hundred": "Morning Tactics Banner",
        "m_five_genre_complete": "Pride Resolve M Five Genre",
        "m_full_collection": "War Critic Proof Proof",
        "m_batch_complete": "Scheme Registry Summit",
        "m_paused_to_done": "School Journey Standard Standard",
        "m_completion_spree": "War Fan Triumph",
        "m_format_completionist": "Kaguya's Heart Completion",
        "m_catch_up": "Kaguya Expert Chronicle",
        "m_multi_reread": "Love War Banner",
        "m_dropped_recovery": "All Night Conquest",
        "m_ten_perfect_scores": "Kaguya Ultra Judgment",
        "m_complete_genre_span": "Kaguya's Ice M Complete Genre",
        "m_monthly_completions": "Kaguya Ultra Romantic Return",
        "m_yearly_completions": "Kaguya's Ice Epilogue",
        "m_rapid_complete": "Ultra Romantic Finale",
        "m_author_complete": "Scheming Minds Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Devoted Reader",
        "m_mangaka_lover": "Aka Fan",
        "m_rereader": "Council Return",
        "m_triple_reread": "Scheme Depth Testament Testament",
        "m_annual_reread": "Morning Tactics Banner Banner",
        "m_publisher_fan": "War Fan Mark",
        "m_artist_fan": "Wit Critic Insignia",
        "m_adaptation_compare": "Love War Fan Insignia Insignia",
        "m_source_material_fan": "Manga First",
        "m_waiting_weekly": "Failed Schemes Streak",
        "m_classic_reader": "Endless War Lantern",
        "m_saga_reader": "Battle Marathon Decree",
        "m_genre_loyalty": "All Night Loyalty",
        "m_decade_reader": "Kaguya Standard Warrant",
        "m_ln_adaptation": "Kaguya Standard Mark",
        "m_original_work": "Rival Lover Standard",
        "m_long_commitment": "All Night Mark",
        "m_up_to_date": "Council Return Warrant Warrant",
        "m_favorite_mangaka": "War Streak Treasury",
        "m_complete_portfolio": "War Fan Triumph Triumph",
        "m_franchise_collector": "Kaguya Expert Archive",
        "m_serialization_follower": "War Streak Handshake",
        "m_genre_master": "Student Council Master",
        "m_multi_series_author": "Battle Marathon Insignia Insignia",
        "m_format_diversity": "Rival Lover Shelf",
        "m_year_dedication": "Night Schemes Tenure",
        "m_ongoing_follower": "Kaguya Standard Fellowship",
        "m_genre_loyalty_50": "Miyuki Shirogane Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Night Scheming Explorer",
        "m_publisher_hopper": "War Fan Mantle",
        "m_tag_explorer": "Decade Fan Explorer",
        "m_decade_hopper": "Too Proud Chronicle Chronicle",
        "m_hidden_gem": "Hidden Volume",
        "m_popular_taste": "Scheme Registry Record Record",
        "m_retro_reader": "Scheme Registry Accord",
        "m_modern_reader": "Council Alerts Seal Seal",
        "m_cross_demographic": "Battle Wits Crown",
        "m_underdog_fan": "Scheme Registry Accord Accord",
        "m_variety_week": "Wit Critic Horizon Horizon",
        "m_manhwa_reader": "Love Confessed Proof",
        "m_manhua_reader": "Endless War Mantle Mantle",
        "m_classic_connoisseur": "Kaguya's Speed Glimpse",
        "m_award_winner": "Night Schemes Warrant",
        "m_niche_explorer": "Love War Fan Horizon",
        "m_world_manga": "Kaguya Expert Chronicle Chronicle",
        "m_cult_classic": "Aka Classic",
        "m_random_pick": "Scheme Registry Standard",
        "m_new_genre_month": "Kaguya Expert M New Genre",
        "m_year_completionist": "Chika's Chaos Fulfillment",
        "m_unpopular_opinion": "Council Return Trial",
        "m_top_rated_reader": "Love War Fan Record",
        "m_source_variety": "Endless War Catalogue",
        "m_low_score_brave": "Chika's Chaos Score",
        "m_short_manga_explorer": "Council Alerts Compass",
        "m_long_manga_explorer": "Morning Tactics Survey",
        "m_serialization_explorer": "All Arcs Road",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Aka Master Ledger",
        "m_commute_reader": "Miyuki's Grind Tenure Tenure",
        "m_four_am_club": "War Fan Fellowship",
        "m_new_year_read": "Wit Critic Pact",
        "m_all_hours": "Too Proud Accord Accord",
        "m_prime_time_reader": "Rival Lover Banner",
        "m_workday_reader": "Aka Classic Accord Accord",
        "m_sunday_read": "Aka Master Standard Standard",
        "m_morning_routine": "Aka Classic Discipline",
        "m_night_shift_reader": "Scheming Minds Accord Accord",
        "m_seasonal_premier_read": "Endless War Seasonal",
        "m_clock_collector": "Perfect Plan Reserve",
        "m_late_night_horror": "Pride Resolve Mark Mark",
        "m_afternoon_reader": "Night Schemes Mantle Mantle",
        "m_golden_hour_reader": "Scheme Depth Observance",
        "m_dawn_reader": "Decade Fan Mantle",
        "m_twilight_reader": "Kaguya Standard Crown",
        "m_midnight_start": "Rival Lover Routine",
        "m_weekend_binge_hours": "Kaguya Ultra Momentum",
        "m_late_night_regular": "Aka Master Accord",
        "m_sunrise_reader": "Love War Streak Mantle",
        "m_every_day_of_week": "Endless War Warrant Warrant",
        "m_monthly_hours": "Night Scheming Vigil",
        "m_bedtime_reader": "Chika's Chaos Warrant Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Aka Art",
        "m_webtoon_reader": "Kaguya Standard Mark Mark",
        "m_full_color": "Wit Critic Accord",
        "m_doujin_reader": "School Journey Record Record",
        "m_anthology_reader": "Kaguya Ultra Accord",
        "m_adaptation_reader": "Scheme Registry Banner",
        "m_longstrip_reader": "Scheme Depth Trial",
        "m_4koma_reader": "Failed Schemes Ledger",
        "m_oneshot_reader": "Kaguya's Ice Mantle",
        "m_format_variety": "War Fan Gallery",
        "m_light_novel_reader": "Too Proud Insignia",
        "m_novel_reader": "Chika's Chaos Crown",
        "m_visual_storyteller": "Night Schemes Testament",
        "m_colored_classic": "Daily Battle Survey",
        "m_webcomic_fan": "Kaguya's Speed Insignia",
        "m_manga_to_anime": "Manga Adapted",
        "m_seinen_reader": "All Night Pinnacle",
        "m_josei_reader": "Love War Streak Pinnacle",
        "m_award_winning_art": "Council Events Relic",
        "m_debut_work": "Council Events Dominion",
        "m_vertical_scroll": "Battle Marathon Decree Decree",
        "m_traditional_format": "Love War Fan Hoard",
        "m_cross_media": "Council Alerts Accord",
        "m_spinoff_reader": "Kaguya Expert Accord",
        "m_remake_reader": "Kaguya's Heart Pinnacle",
        "m_collaboration_reader": "Kaguya's Speed Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Love War Streak",
        "m_weekly_warrior": "All Arcs Season",
        "m_monthly_reader": "Aka Art Discipline",
        "m_comeback": "Morning Tactics Standard Standard",
        "m_weekend_streak": "Love War Streak Fever",
        "m_no_zero_days": "Love Confessed Proof Proof",
        "m_iron_will": "Pride Resolve",
        "m_habit_formed": "Battle Wits Crown Crown",
        "m_consistent_pace": "War Critic Scrutiny Scrutiny",
        "m_year_long": "Year Reading",
        "m_double_streak": "Kaguya's Ice Resolve",
        "m_streak_recovery": "Student Council Resolve",
        "m_daily_minimum": "Perfect Plan Focus",
        "m_winter_streak": "Scheme Depth Observance Observance",
        "m_summer_streak": "Council Events Observance",
        "m_morning_streak": "Night Scheming Clock",
        "m_night_streak": "Love War Fan Discipline",
        "m_unbreakable": "Love War Streak Warrant",
        "m_eternal_flame": "Miyuki Kaguya Record",
        "m_chapter_a_day": "Aka Master Ledger Ledger",
        "m_genre_streak": "Decade Fan Streak",
        "m_completion_streak": "Scheme Registry Return",
        "m_rating_streak": "Decade Fan Appraisal",
        "m_multi_ch_streak": "All Arcs Tenure",
        "m_author_streak": "Perfect Plan Calendar",
        "m_perfect_week_manga": "Kaguya Expert Accord Accord",
        "m_diverse_streak": "Love War Streak Streak",

        // ── MANGA SCORING ──
        "m_critic": "War Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_harsh_critic": "Too Proud Scale",
        "m_fair_judge": "Aka Fan Eye Eye",
        "m_generous_spirit": "Kaguya Ultra Decree",
        "m_score_all": "Kaguya Standard Reckoning",
        "m_wide_range": "Aka Art Ledger Ledger",
        "m_controversial": "Kaguya Ultra Romantic Standard Standard",
        "m_consistent_scorer": "School Journey Grade",
        "m_score_sniper": "Council Return Reckoning",
        "m_evolving_taste": "Kaguya's Ice Trial Trial",
        "m_bell_curve": "Aka Art Accord",
        "m_picky_reader": "Love War Ledger",
        "m_100_rated": "Aka Art Standard",
        "m_500_rated": "Scheming Minds Aegis",
        "m_mediocre_majority": "Kaguya's Ice Canon",
        "m_rating_spree": "Night Scheming Verdict",
        "m_score_variance": "Chika's Chaos Measure",
        "m_binge_rater": "Perfect Plan Passage",
        "m_reread_rerate": "Daily Battle Banner Banner",
        "m_masterpiece_hunter": "Kaguya Ultra Romantic Banner",
        "m_contrarian": "Scheme Registry Aegis",
        "m_optimist": "Council Alerts Accord Accord",
        "m_score_distributor": "All Arcs Balance",
        "m_genre_critic": "Perfect Plan Critic",
        "m_mean_above_8": "Chika's Chaos Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Night Schemes Season",
        "m_valentines_read": "Decade Fan Observance",
        "m_pi_day": "Kaguya's Ice Testament Testament",
        "m_april_fools": "Council Return Devotion",
        "m_international_manga_day": "Too Proud Aegis",
        "m_free_comic_day": "Kaguya Ultra Chronicle",
        "m_summer_solstice": "Ultra Romantic Focus Focus",
        "m_tanabata": "War Critic Tanabata",
        "m_friday_13th": "Kaguya's Heart Dominion Dominion",
        "m_halloween_read": "Pride Resolve Halloween",
        "m_thanksgiving_binge": "Kaguya Expert Charge",
        "m_christmas_read": "Aka Classic Pact",
        "m_new_years_eve": "Ultra Romantic Pilgrimage",
        "m_birthday_read": "All Night Focus",
        "m_holiday_marathon": "War Streak Rally",
        "m_independence_day": "Scheme Registry Aegis Aegis",
        "m_culture_day": "Scheming Minds Seal Seal",
        "m_spring_equinox": "Pride Resolve Dominion",
        "m_earth_day": "All Night Trial",
        "m_labor_day": "Aka Classic Seal",
        "m_winter_solstice": "Battle Wits Focus Focus",
        "m_manga_birthday": "War Critic Ritual",
        "m_every_holiday_reader": "Student Council Watch",
        "m_consecutive_holidays": "Kaguya's Heart Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Love Destiny Aegis",
        "m_fibonacci": "Miyuki's Grind Dominion",
        "m_palindrome_day": "Kaguya's Ice Relic",
        "m_binary_day": "Battle Wits Proof",
        "m_full_moon_read": "Love War Streak Crown",
        "m_leap_year_read": "Love War Practice",
        "m_triple_seven": "Aka Fan Trial Trial",
        "m_thousand_complete": "Aka Fan Ascension",
        "m_nice": "Battle Marathon Seal Seal",
        "m_power_level_chapters": "Morning Tactics Aegis",
        "m_answer_42": "Love War Streak Trial",
        "m_square_number": "Miyuki Kaguya Standard",
        "m_prime_count": "Aka Fan Pinnacle",
        "m_matching_date": "Student Council Mantle",
        "m_century_chapter": "Love Destiny Decree",
        "m_pi_chapters": "All Night Proof Proof",
        "m_synchronicity": "Decade Fan Emblem",
        "m_world_record": "Love Confessed Warrant",
        "m_genre_clash": "Rival Lover Clash",
        "m_time_traveler": "School Journey Decree",
        "m_double_digits": "Endless War Dominion",
        "m_one_two_three": "Kaguya's Speed Banner Banner",
        "m_lucky_seven": "Love War Fan Record Record",
        "m_exact_hundred_ch": "Miyuki's Grind Legend",
        "m_year_match_count": "Failed Schemes Routine",
        "m_chapter_match_date": "Battle Wits Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Endless War Index",
        "m_manhwa_format": "Pride Resolve Gallery",
        "m_manhua_format": "Scheme Depth Storehouse",
        "m_ln_format": "Aka Fan Index",
        "m_oneshot_format": "Kaguya's Ice Index",
        "m_doujin_format": "Night Scheming Cabinet",
        "m_novel_format": "Council Return Reserve Reserve",
        "m_format_master_manga": "Night Scheming Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "School Journey Link",
        "m_meta_collector": "Scheming Minds Reliquary",
        "m_meta_category_starter": "War Fan Standard",
        "m_meta_tier_climber": "Council Alerts Token",
        "m_meta_tier_max": "Kaguya Complete",
        "m_meta_xp_earner": "Endless War Anchor",
        "m_meta_difficulty_easy": "Aka Fan Panel",
        "m_meta_difficulty_hard": "Night Schemes Node",
        "m_meta_unlock_spree": "Endless War Marker",
        "m_meta_completionist": "Full Library",
        "m_meta_diverse": "Kaguya's Ice Anchor",
        "m_meta_dominator": "Battle Marathon Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060000",
        primary: "#c61c1c",
        secondary: "#9e0a0a",
        accent: "#f0f0f0",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/kaguya-sama.jpg",
    particleColor: "#e04040",
    backgroundDim: 0.35,
    backgroundBlur: 16,
    particleTypes: {
        rose_petals: { label: "Rose Petals", maxCount: 18, defaultEnabled: true, defaultIntensity: 60 },
        battle_sparks: { label: "Battle Sparks", maxCount: 12, defaultEnabled: true, defaultIntensity: 48 },
    },
    milestoneNames: {
  1: "Threadbare Generic Rank Spark",
  8: "Generic's Tarnished Omen",
  14: "Fractured Generic Rank",
  21: "Generic Rank Path",
  28: "Lowborn Legacy Myth",
  35: "Generic Rank Pulse",
  41: "Generic's Legacy Crest",
  48: "Humble Generic Mark",
  55: "Ragged Generic Rank Vow",
  61: "Generic's Faint Echo",
  68: "Lesser Generic Rank",
  75: "Generic Rank Zenith",
  81: "Doubtful Legacy Bloom",
  88: "Generic Rank Sigil",
  95: "Generic's Legacy Flame",
  102: "Really Cool Generic Spark",
  108: "Awakened Generic Rank Omen",
  115: "Generic's Resolute Seal",
  122: "Rising Generic Rank",
  128: "Generic Rank Myth",
  135: "Dauntless Legacy Pulse",
  142: "Generic Rank Crest",
  149: "Generic's Legacy Mark",
  155: "Fresh Generic Vow",
  162: "Valiant Generic Rank Echo",
  169: "Generic's Prime Crown",
  175: "Polished Generic Rank",
  182: "Generic Rank Bloom",
  189: "Stormlit Legacy Sigil",
  195: "Generic Rank Flame",
  202: "Generic's Legacy Spark",
  209: "Tempered Generic Omen",
  216: "Trusted Generic Rank Seal",
  222: "Generic's Steadfast Path",
  229: "Ironclad Generic Rank",
  236: "Veteran Legacy Pulse",
  242: "Core Legacy Crest",
  249: "Generic Rank Mark",
  256: "Generic's Legacy Vow",
  262: "Formidable Generic Echo",
  269: "Lucid Generic Rank Crown",
  276: "Generic's Ranked Zenith",
  283: "Fabled Generic Rank",
  289: "Grand Legacy Sigil",
  296: "Seasoned Legacy Flame",
  303: "Generic Rank Spark",
  309: "Generic's Legacy Omen",
  316: "Valorous Generic Seal",
  323: "Stalwart Generic Rank Path",
  330: "Generic's Commanding Myth",
  336: "Refined Generic Rank",
  343: "Unbroken Legacy Crest",
  350: "Blazing Legacy Mark",
  356: "Generic Rank Vow",
  363: "Generic's Legacy Echo",
  370: "Peerless Generic Crown",
  376: "Ardent Generic Rank Zenith",
  383: "Generic's Focused Bloom",
  390: "Vigilant Generic Rank",
  397: "Dominant Legacy Flame",
  403: "Elite Legacy Spark",
  410: "Generic Rank Omen",
  417: "Generic's Legacy Seal",
  423: "Sovereign Generic Path",
  430: "Regal Generic Rank Myth",
  437: "Generic's Crowned Pulse",
  444: "Mythborn Generic Rank",
  450: "Limitless Legacy Mark",
  457: "Radiant Legacy Vow",
  464: "Generic Rank Echo",
  470: "Generic's Legacy Crown",
  477: "Climactic Generic Zenith",
  484: "Epic Generic Rank Bloom",
  490: "Generic's Unreal Sigil",
  497: "Peak Generic Rank",
  504: "Supreme Legacy Spark",
  511: "Exalted Legacy Omen",
  517: "Generic Rank Seal",
  524: "Generic's Legacy Path",
  531: "Celestial Generic Myth",
  537: "Phantom Generic Rank Pulse",
  544: "Generic's Crimson Crest",
  551: "Silver Generic Rank",
  557: "Golden Legacy Vow",
  564: "Feral Legacy Echo",
  571: "Generic Rank Crown",
  578: "Generic's Legacy Zenith",
  584: "Dread Generic Bloom",
  591: "Luminous Generic Rank Sigil",
  598: "Generic's Thunderous Flame",
  604: "Ultraviolet Generic Rank",
  611: "Unleashed Legacy Omen",
  618: "Secret Legacy Seal",
  625: "Final Generic Path",
  631: "Generic's Legacy Myth",
  638: "Worldclass Generic Pulse",
  645: "Lawless Generic Rank Crest",
  651: "Generic's Chosen Mark",
  658: "Fearless Generic Rank",
  665: "Overdrive Legacy Echo",
  671: "Cinematic Legacy Crown",
  678: "Impossible Generic Zenith",
  685: "Generic's Legacy Bloom",
  692: "Canonized Generic Sigil",
  698: "Ascendant Generic Rank Flame",
  705: "Generic's Transfigured Spark",
  712: "Immortal Generic Rank",
  718: "Eclipsed Legacy Seal",
  725: "Astral Legacy Path",
  732: "Sublime Generic Myth",
  739: "Generic's Legacy Pulse",
  745: "Prismatic Generic Crest",
  752: "Abyssal Generic Rank Mark",
  759: "Generic's Unbound Vow",
  765: "Eternal Generic Rank",
  772: "Cosmic Legacy Crown",
  779: "Transcendent Legacy Zenith",
  785: "Perfected Generic Bloom",
  792: "Generic's Legacy Sigil",
  799: "Ultimate Generic Flame",
  806: "Mythic Generic Rank Spark",
  812: "Generic's Godlike Omen",
  819: "Canonical Generic Rank",
  826: "Reality-Bent Legacy Path",
  832: "Heavenly Legacy Myth",
  839: "Absolute Generic Pulse",
  846: "Untouchable Generic Crest",
  852: "Timeless Generic Mark",
  859: "Empyrean Generic Rank Vow",
  866: "Generic's Primordial Echo",
  873: "Omniscient Generic Rank",
  879: "Unfathomed Legacy Zenith",
  886: "Apocalyptic Legacy Bloom",
  893: "Seraphic Generic Sigil",
  899: "Omega Generic Flame",
  906: "Final Generic Spark",
  913: "Crowned Generic Rank Omen",
  920: "Generic's Mythic Seal",
  926: "Absolute Generic Rank",
  933: "Eternal Legacy Myth",
  940: "Cosmic Legacy Pulse",
  946: "Transcendent Generic Crest",
  953: "Perfected Generic Mark",
  960: "Definitive Generic Vow",
  966: "Ultimate Generic Rank Echo",
  973: "Generic's Infinite Crown",
  980: "Sovereign Generic Rank",
  987: "Celestial Legacy Bloom",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate Generic Rank"
},
}
