import { AnimeThemeConfig } from "./types"
import { GiCrown, GiHeartKey, GiRose, GiPaperArrow, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiQuillInk } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const kaguyaSamaTheme: AnimeThemeConfig = {
    id: "kaguya-sama",
    displayName: "Kaguya-sama: Love is War",
    description: "Student council president Miyuki Shirogane and vice-president Kaguya Shinomiya are both deeply in love with each other — but too proud to confess, they scheme endlessly to make the other confess first in this battle of wits and hearts.",
    fontFamily: "'Sawarabi Gothic', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Sawarabi+Gothic&display=swap",
    cssVars: {
        "--color-brand-200": "250 185 185",
        "--color-brand-300": "238 130 130",
        "--color-brand-400": "220 75 75",
        "--color-brand-500": "198 28 28",
        "--color-brand-600": "158 10 10",
        "--color-brand-700": "114 3 3",
        "--color-brand-800": "72 0 0",
        "--color-brand-900": "36 0 0",
        "--color-brand-950": "15 0 0",
        "--brand": "198 28 28",
        "--background": "#060000",
        "--paper": "#120000",
        "--color-gray-950": "6 0 0",
        "--color-gray-900": "12 2 2",
        "--color-gray-800": "22 4 4",
        "--color-gray-700": "36 8 8",
        "--color-gray-600": "58 14 14",
        "--color-gray-500": "90 24 24",
        "--color-gray-400": "130 48 48",
        "--color-gray-300": "172 85 85",
        "--color-gray-200": "205 130 130",
        "--color-gray-100": "228 175 175",
        "--color-gray-50": "245 215 215",
    },
    sidebarOverrides: {
        "home": { icon: GiCrown, label: "Shuchiin Academy" },
        "schedule": { icon: GiAlarmClock, label: "Council Schedule" },
        "manga": { icon: LuBookOpen, label: "Love War Files" },
        "lists": { icon: GiRose, label: "Scheme Registry" },
        "discover": { icon: GiBullseye, label: "New Battles" },
        "torrent-list": { icon: GiPaperArrow, label: "Letter Cache" },
        "debrid": { icon: GiHeartKey, label: "Council Store" },
        "unmatched": { icon: GiQuillInk, label: "Failed Schemes" },
        "enmasse": { icon: GiResize, label: "Council Events" },
        "scan-summaries": { icon: TbReportSearch, label: "Battle Reports" },
        "auto-downloader": { icon: LuRss, label: "Love War Feed" },
        "community": { icon: GiCrown, label: "Student Council" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Council Alerts" },
        "achievements": { icon: GiTrophy, label: "Council Trophies" },
        "milestones": { icon: LuFlag, label: "Confession Goals" },
        "theme-manager": { icon: GiPalette, label: "Crimson Colors" },
        "extensions": { icon: BiExtension, label: "Scheme Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Love War Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Miyuki Settings" },
    },
    achievementNames: {
        "a_first_episode": "First Battle",
        "a_first_complete": "Love Confessed",
        "a_hundred_club": "Hundred Battles",
        "a_time_lord": "Council Veteran",
        "a_anime_collector": "Scheme Collection",
        "a_library_legend": "Shuchiin Archives",
        "a_binge_king": "Battle Marathon",
        "a_no_sleep": "All-Night Scheming",
        "a_marathon_runner": "Miyuki's Grind",
        "a_speed_run": "Kaguya's Speed",
        "a_completionist": "All Seasons",
        "a_mega_completionist": "Aka Master",
        "a_loyal_fan": "Love War Fan",
        "a_rewatcher": "Council Return",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Battle of Wits",
        "a_genre_adventure": "School Journey",
        "a_genre_comedy": "Chika's Chaos",
        "a_genre_drama": "Kaguya's Heart",
        "a_genre_fantasy": "Love War",
        "a_genre_horror": "Kaguya's Ice",
        "a_genre_romance": "Miyuki Kaguya",
        "a_genre_scifi": "None Here",
        "a_genre_supernatural": "Love Destiny",
        "a_genre_psychological": "Scheming Minds",
        "a_genre_mecha": "None Here",
        "a_critic": "Wit Critic",
        "a_perfect_ten": "Perfect Plan",
        "a_harsh_critic": "Kaguya Standard",
        "a_daily_streak": "Daily Battle",
        "a_mega_streak": "Endless War",
        "a_year_long": "Year of Schemes",
        "a_iron_will": "Too Proud",
        "a_hidden_gem": "Hidden Episode",
        "a_cult_classic": "Aka Classic",
        "a_classic_connoisseur": "2015 Fan",
        "a_new_years_resolution": "New Year Council",
        "a_christmas_special": "Winter Confession",
        "a_meta_tier_max": "Love War Legend",
        "a_meta_completionist": "All Arcs",
        "a_sequel_chain": "Kaguya Ultra Romantic",
        "a_zero_to_hero": "Rival to Lover",
        "a_night_owl": "Night Schemes",
        "a_early_bird": "Morning Tactics",
        "m_first_chapter": "First Scheme",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Battle Marathon",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Kaguya Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Council Return",
        "m_genre_action": "Battle Chapter",
        "m_genre_adventure": "School Chapter",
        "m_genre_romance": "Heart Chapter",
        "m_genre_fantasy": "War Chapter",
        "m_genre_horror": "Ice Chapter",
        "m_genre_drama": "Confession Chapter",
        "m_genre_scifi": "Unusual Chapter",
        "m_genre_supernatural": "Destiny Chapter",
        "m_genre_psychological": "Scheme Depth",
        "m_critic": "War Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Love War Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Pride Resolve",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Aka Classic",
        "m_mangaka_lover": "Aka Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Kaguya Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Aka Art",
        "m_manga_to_anime": "Manga Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060000",
        primary: "#c61c1c",
        secondary: "#9e0a0a",
        accent: "#f0f0f0",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/kaguya-sama.jpg",
    particleColor: "#e04040",
    backgroundDim: 0.35,
    backgroundBlur: 16,
    particleTypes: {
        rose_petals: { label: "Rose Petals", maxCount: 18, defaultEnabled: true, defaultIntensity: 60 },
        battle_sparks: { label: "Battle Sparks", maxCount: 12, defaultEnabled: true, defaultIntensity: 48 },
    },
    milestoneNames: {
    1: "Generic Rank",
    7: "Generic Rank",
    14: "Generic Rank",
    21: "Generic Rank",
    27: "Generic Rank",
    34: "Generic Rank",
    41: "Generic Rank",
    47: "Generic Rank",
    54: "Generic Rank",
    61: "Generic Rank",
    68: "Generic Rank",
    74: "Generic Rank",
    81: "Generic Rank",
    88: "Generic Rank",
    94: "Generic Rank",
    101: "Generic Rank",
    108: "Generic Rank",
    114: "Generic Rank",
    121: "Generic Rank",
    128: "Generic Rank",
    135: "Generic Rank",
    141: "Generic Rank",
    148: "Generic Rank",
    155: "Generic Rank",
    161: "Generic Rank",
    168: "Generic Rank",
    175: "Generic Rank",
    182: "Generic Rank",
    188: "Generic Rank",
    195: "Generic Rank",
    202: "Generic Rank",
    208: "Generic Rank",
    215: "Generic Rank",
    222: "Generic Rank",
    228: "Generic Rank",
    235: "Generic Rank",
    242: "Generic Rank",
    249: "Generic Rank",
    255: "Generic Rank",
    262: "Generic Rank",
    269: "Generic Rank",
    275: "Generic Rank",
    282: "Generic Rank",
    289: "Generic Rank",
    296: "Generic Rank",
    302: "Generic Rank",
    309: "Generic Rank",
    316: "Generic Rank",
    322: "Generic Rank",
    329: "Generic Rank",
    336: "Generic Rank",
    342: "Generic Rank",
    349: "Generic Rank",
    356: "Generic Rank",
    363: "Generic Rank",
    369: "Generic Rank",
    376: "Generic Rank",
    383: "Generic Rank",
    389: "Generic Rank",
    396: "Generic Rank",
    403: "Generic Rank",
    409: "Generic Rank",
    416: "Generic Rank",
    423: "Generic Rank",
    430: "Generic Rank",
    436: "Generic Rank",
    443: "Generic Rank",
    450: "Generic Rank",
    456: "Generic Rank",
    463: "Generic Rank",
    470: "Generic Rank",
    477: "Generic Rank",
    483: "Generic Rank",
    490: "Generic Rank",
    497: "Generic Rank",
    503: "Generic Rank",
    510: "Generic Rank",
    517: "Generic Rank",
    523: "Generic Rank",
    530: "Generic Rank",
    537: "Generic Rank",
    544: "Generic Rank",
    550: "Generic Rank",
    557: "Generic Rank",
    564: "Generic Rank",
    570: "Generic Rank",
    577: "Generic Rank",
    584: "Generic Rank",
    591: "Generic Rank",
    597: "Generic Rank",
    604: "Generic Rank",
    611: "Generic Rank",
    617: "Generic Rank",
    624: "Generic Rank",
    631: "Generic Rank",
    637: "Generic Rank",
    644: "Generic Rank",
    651: "Generic Rank",
    658: "Generic Rank",
    664: "Generic Rank",
    671: "Generic Rank",
    678: "Generic Rank",
    684: "Generic Rank",
    691: "Generic Rank",
    698: "Generic Rank",
    704: "Generic Rank",
    711: "Generic Rank",
    718: "Generic Rank",
    725: "Generic Rank",
    731: "Generic Rank",
    738: "Generic Rank",
    745: "Generic Rank",
    751: "Generic Rank",
    758: "Generic Rank",
    765: "Generic Rank",
    772: "Generic Rank",
    778: "Generic Rank",
    785: "Generic Rank",
    792: "Generic Rank",
    798: "Generic Rank",
    805: "Generic Rank",
    812: "Generic Rank",
    818: "Generic Rank",
    825: "Generic Rank",
    832: "Generic Rank",
    839: "Generic Rank",
    845: "Generic Rank",
    852: "Generic Rank",
    859: "Generic Rank",
    865: "Generic Rank",
    872: "Generic Rank",
    879: "Generic Rank",
    886: "Generic Rank",
    892: "Generic Rank",
    899: "Generic Rank",
    906: "Generic Rank",
    912: "Generic Rank",
    919: "Generic Rank",
    926: "Generic Rank",
    932: "Generic Rank",
    939: "Generic Rank",
    946: "Generic Rank",
    953: "Generic Rank",
    959: "Generic Rank",
    966: "Generic Rank",
    973: "Generic Rank",
    979: "Generic Rank",
    986: "Generic Rank",
    993: "Generic Rank",
    1000: "Generic Rank",
  },
}
