import { AnimeThemeConfig } from "./types"
import { GiFlowerEmblem, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiCrystalBall, GiStarSwirl, GiSpellBook } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const kamisamaKissTheme: AnimeThemeConfig = {
    id: "kamisama-kiss",
    displayName: "Kamisama Kiss",
    description: "Homeless high-schooler Nanami is accidentally made a land god by a stranger. She inherits his shrine and his reluctant fox familiar Tomoe — who is proud, powerful, and slowly, unavoidably falling for her.",
    cssVars: {
        "--color-brand-200": "255 218 175",
        "--color-brand-300": "252 178 108",
        "--color-brand-400": "240 132 45",
        "--color-brand-500": "212 88 8",
        "--color-brand-600": "168 52 0",
        "--color-brand-700": "120 26 0",
        "--color-brand-800": "76 10 0",
        "--color-brand-900": "38 3 0",
        "--color-brand-950": "16 1 0",
        "--brand": "212 88 8",
        "--background": "#060200",
        "--paper": "#0f0400",
        "--color-gray-950": "6 2 0",
        "--color-gray-900": "16 6 1",
        "--color-gray-800": "30 14 2",
        "--color-gray-700": "52 26 5",
        "--color-gray-600": "82 45 12",
        "--color-gray-500": "125 78 25",
        "--color-gray-400": "168 122 55",
        "--color-gray-300": "208 168 92",
        "--color-gray-200": "238 205 142",
        "--color-gray-100": "252 232 192",
        "--color-gray-50": "255 246 230",
    },
    sidebarOverrides: {
        "home": { icon: GiFlowerEmblem, label: "Mikage Shrine" },
        "schedule": { icon: GiAlarmClock, label: "Divine Schedule" },
        "manga": { icon: LuBookOpen, label: "Shrine Scrolls" },
        "lists": { icon: GiScrollUnfurled, label: "Familiar Registry" },
        "discover": { icon: GiBullseye, label: "New Yokai" },
        "torrent-list": { icon: GiCrystalBall, label: "Spirit Cache" },
        "debrid": { icon: GiHeartKey, label: "Divine Vault" },
        "unmatched": { icon: GiStarSwirl, label: "Lost Spirits" },
        "enmasse": { icon: GiResize, label: "Divine Gathering" },
        "scan-summaries": { icon: TbReportSearch, label: "Shrine Reports" },
        "auto-downloader": { icon: LuRss, label: "Spirit Feed" },
        "community": { icon: GiSpellBook, label: "Shrine Circle" },
        "achievements": { icon: GiTrophyCup, label: "Divine Trophies" },
        "milestones": { icon: LuFlag, label: "Divine Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Shrine Alerts" },
        "theme-manager": { icon: GiPalette, label: "Shrine Colors" },
        "extensions": { icon: BiExtension, label: "Fox Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Divine Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Nanami Config" },
    },
    achievementNames: {
        "a_first_episode": "Became a God",
        "a_first_complete": "First Miracle",
        "a_hundred_club": "Hundred Divine Days",
        "a_binge_king": "Kamisama Marathon",
        "a_completionist": "All Shrines Visited",
        "a_mega_completionist": "True God",
        "a_loyal_fan": "Shrine Devotee",
        "a_zero_to_hero": "Homeless to Divine",
        "m_first_chapter": "First Prayer",
        "m_completionist": "Full Shrine Archive",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060200",
        primary: "#d45808",
        secondary: "#5858a0",
        accent: "#f8d888",
    },
    particleColor: "#e08030",
    backgroundDim: 0.28,
    backgroundBlur: 20,
    milestoneNames: {
    1: "Generic Rank",
    7: "Generic Rank",
    14: "Generic Rank",
    21: "Generic Rank",
    27: "Generic Rank",
    34: "Generic Rank",
    41: "Generic Rank",
    47: "Generic Rank",
    54: "Generic Rank",
    61: "Generic Rank",
    68: "Generic Rank",
    74: "Generic Rank",
    81: "Generic Rank",
    88: "Generic Rank",
    94: "Generic Rank",
    101: "Generic Rank",
    108: "Generic Rank",
    114: "Generic Rank",
    121: "Generic Rank",
    128: "Generic Rank",
    135: "Generic Rank",
    141: "Generic Rank",
    148: "Generic Rank",
    155: "Generic Rank",
    161: "Generic Rank",
    168: "Generic Rank",
    175: "Generic Rank",
    182: "Generic Rank",
    188: "Generic Rank",
    195: "Generic Rank",
    202: "Generic Rank",
    208: "Generic Rank",
    215: "Generic Rank",
    222: "Generic Rank",
    228: "Generic Rank",
    235: "Generic Rank",
    242: "Generic Rank",
    249: "Generic Rank",
    255: "Generic Rank",
    262: "Generic Rank",
    269: "Generic Rank",
    275: "Generic Rank",
    282: "Generic Rank",
    289: "Generic Rank",
    296: "Generic Rank",
    302: "Generic Rank",
    309: "Generic Rank",
    316: "Generic Rank",
    322: "Generic Rank",
    329: "Generic Rank",
    336: "Generic Rank",
    342: "Generic Rank",
    349: "Generic Rank",
    356: "Generic Rank",
    363: "Generic Rank",
    369: "Generic Rank",
    376: "Generic Rank",
    383: "Generic Rank",
    389: "Generic Rank",
    396: "Generic Rank",
    403: "Generic Rank",
    409: "Generic Rank",
    416: "Generic Rank",
    423: "Generic Rank",
    430: "Generic Rank",
    436: "Generic Rank",
    443: "Generic Rank",
    450: "Generic Rank",
    456: "Generic Rank",
    463: "Generic Rank",
    470: "Generic Rank",
    477: "Generic Rank",
    483: "Generic Rank",
    490: "Generic Rank",
    497: "Generic Rank",
    503: "Generic Rank",
    510: "Generic Rank",
    517: "Generic Rank",
    523: "Generic Rank",
    530: "Generic Rank",
    537: "Generic Rank",
    544: "Generic Rank",
    550: "Generic Rank",
    557: "Generic Rank",
    564: "Generic Rank",
    570: "Generic Rank",
    577: "Generic Rank",
    584: "Generic Rank",
    591: "Generic Rank",
    597: "Generic Rank",
    604: "Generic Rank",
    611: "Generic Rank",
    617: "Generic Rank",
    624: "Generic Rank",
    631: "Generic Rank",
    637: "Generic Rank",
    644: "Generic Rank",
    651: "Generic Rank",
    658: "Generic Rank",
    664: "Generic Rank",
    671: "Generic Rank",
    678: "Generic Rank",
    684: "Generic Rank",
    691: "Generic Rank",
    698: "Generic Rank",
    704: "Generic Rank",
    711: "Generic Rank",
    718: "Generic Rank",
    725: "Generic Rank",
    731: "Generic Rank",
    738: "Generic Rank",
    745: "Generic Rank",
    751: "Generic Rank",
    758: "Generic Rank",
    765: "Generic Rank",
    772: "Generic Rank",
    778: "Generic Rank",
    785: "Generic Rank",
    792: "Generic Rank",
    798: "Generic Rank",
    805: "Generic Rank",
    812: "Generic Rank",
    818: "Generic Rank",
    825: "Generic Rank",
    832: "Generic Rank",
    839: "Generic Rank",
    845: "Generic Rank",
    852: "Generic Rank",
    859: "Generic Rank",
    865: "Generic Rank",
    872: "Generic Rank",
    879: "Generic Rank",
    886: "Generic Rank",
    892: "Generic Rank",
    899: "Generic Rank",
    906: "Generic Rank",
    912: "Generic Rank",
    919: "Generic Rank",
    926: "Generic Rank",
    932: "Generic Rank",
    939: "Generic Rank",
    946: "Generic Rank",
    953: "Generic Rank",
    959: "Generic Rank",
    966: "Generic Rank",
    973: "Generic Rank",
    979: "Generic Rank",
    986: "Generic Rank",
    993: "Generic Rank",
    1000: "Generic Rank",
  },
}
