import { AnimeThemeConfig } from "./types"
import { GiRose, GiHeartKey, GiSchoolBag, GiMusicalNotes, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiCherish } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const kareKanoTheme: AnimeThemeConfig = {
    id: "kare-kano",
    displayName: "Kare Kano",
    description: "Two model students — the perfect-looking Yukino and the cool Arima — discover each other's true selves, then fall deeply in love. Hideaki Anno's intimate romance masterpiece.",
    fontFamily: "'Nunito', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,400;0,600;1,400&display=swap",
    cssVars: {
        "--color-brand-200": "240 190 205",
        "--color-brand-300": "225 155 175",
        "--color-brand-400": "208 118 144",
        "--color-brand-500": "186 82 112",
        "--color-brand-600": "153 56 86",
        "--color-brand-700": "118 34 62",
        "--color-brand-800": "82 18 40",
        "--color-brand-900": "50 8 24",
        "--color-brand-950": "28 3 13",
        "--brand": "186 82 112",
        "--background": "#060103",
        "--paper": "#0e050a",
        "--color-gray-950": "6 1 3",
        "--color-gray-900": "14 5 8",
        "--color-gray-800": "26 10 16",
        "--color-gray-700": "44 18 28",
        "--color-gray-600": "68 30 46",
        "--color-gray-500": "105 50 72",
        "--color-gray-400": "148 85 112",
        "--color-gray-300": "186 128 152",
        "--color-gray-200": "214 164 184",
        "--color-gray-100": "232 198 212",
        "--color-gray-50": "246 232 238",
    },
    sidebarOverrides: {
        "home": { icon: GiHeartKey, label: "True Self" },
        "schedule": { icon: GiAlarmClock, label: "School Schedule" },
        "manga": { icon: LuBookOpen, label: "Manga Club" },
        "lists": { icon: GiSchoolBag, label: "Class Roster" },
        "discover": { icon: GiBullseye, label: "Discover Hearts" },
        "torrent-list": { icon: GiMusicalNotes, label: "Drama Club" },
        "debrid": { icon: GiRose, label: "Secret Feelings" },
        "unmatched": { icon: GiCherish, label: "Unspoken" },
        "enmasse": { icon: GiResize, label: "School Events" },
        "scan-summaries": { icon: TbReportSearch, label: "Diary" },
        "auto-downloader": { icon: LuRss, label: "Gossip Feed" },
        "community": { icon: GiHeartKey, label: "Kare Kano Club" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Heart Alerts" },
        "achievements": { icon: GiTrophy, label: "Romance Milestones" },
        "milestones": { icon: LuFlag, label: "Romance Goals" },
        "theme-manager": { icon: GiPalette, label: "Pastel Colors" },
        "extensions": { icon: BiExtension, label: "Drama Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Heart Sync" },
        "settings": { icon: GiSettingsKnobs, label: "True Settings" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "True Self",
        "a_episode_counter": "Night Feelings Mark",
        "a_episode_titan": "Heart Journey Relic",
        "a_hours_invested": "Tsuda Fan Proof",
        "a_time_lord": "Romance Veteran",
        "a_anime_collector": "Drama Cache",
        "a_library_legend": "Manga Archives",
        "a_first_complete": "Love Bloomed",
        "a_hundred_club": "Hundred Moments",
        "a_first_day": "Eternal Love Seal",
        "a_first_rating": "Heart Journey Appraisal",
        "a_ten_thousand_min": "Yukino's Faces Standard",
        "a_season_veteran": "Yukino's Faces Library",
        "a_year_explorer": "Romance Judge Map",
        "a_century_watcher": "Romance Binge Ledger",
        "a_five_hundred_eps": "Endless Love Dominion",
        "a_thousand_eps": "Love's Resolve Record",
        "a_watching_ten": "Kare Kano Acclaim",
        "a_ptw_hoarder": "Classic Romance Library",
        "a_dropped_honesty": "Kare Kano Summit",
        "a_five_thousand_eps": "Unbroken Love Warrant",
        "a_ten_completed": "Daily Hearts Afterglow",
        "a_fifty_completed": "Hidden Feeling Ascension",
        "a_five_hundred_completed": "Kare Kano Clear",
        "a_mean_score_tracker": "Romance Master Verdict",
        "a_unique_studios": "Love's Resolve Collection",
        "a_days_spent_watching": "Winter Together Dominion",
        "a_all_status": "Romance Critic Testament",
        "a_first_favorite": "Anno Master Cabinet",
        "a_favorites_collector": "School Events Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Love Revisit Drive",
        "a_marathon_runner": "Romance Run",
        "a_weekend_warrior": "Heart Journey Ordeal",
        "a_non_stop": "Romance Marathon Fever",
        "a_one_more_episode": "Strict Review Mantle",
        "a_speed_run": "Love Sprint",
        "a_double_feature": "Love Sprint Crown",
        "a_triple_threat": "Hideaki Anno's Record",
        "a_five_a_day": "Romance Run Accord",
        "a_back_to_back": "Gainax Classic Surge",
        "a_seasonal_binge": "Heart Journey Cascade",
        "a_cour_crusher": "Winter Together Ordeal",
        "a_half_day_watch": "Night Feelings Crown",
        "a_full_day_watch": "Heart Alerts Pinnacle",
        "a_power_weekend": "Eternal Love Run",
        "a_binge_king": "Romance Marathon",
        "a_no_sleep": "All-Night Love",
        "a_entire_season": "Rival Terror Library",
        "a_seven_day_challenge": "Heart Alerts Mark",
        "a_hundred_day_binge": "Eternal Love Surge",
        "a_genre_binge": "Morning Together Binge",
        "a_studio_binge": "Night Feelings Fever",
        "a_season_sweep": "Reader's Resolve Codex",
        "a_forty_eight_hour": "Love Bloomed Overture",
        "a_ep_counter_day": "Daily Hearts Aegis",
        "a_multi_series_binge": "Classic Romance Streak",
        "a_midnight_binge": "Strict Review Cascade",
        "a_new_year_binge": "Anno's Depth Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Drama Action",
        "a_genre_adventure": "Heart Journey",
        "a_genre_comedy": "Yukino's Faces",
        "a_genre_drama": "Deep Feelings",
        "a_genre_fantasy": "Dream Romance",
        "a_genre_horror": "Rival Terror",
        "a_genre_mystery": "Romance Revisit Mystery",
        "a_genre_romance": "True Love",
        "a_genre_scifi": "None Here",
        "a_genre_sol": "Unbroken Love Slice",
        "a_genre_sports": "Love Bloomed Sports",
        "a_genre_supernatural": "Love Magic",
        "a_genre_thriller": "Hidden Feeling Thriller",
        "a_genre_mecha": "None Here",
        "a_genre_music": "Yukino's Faces Music",
        "a_genre_psychological": "Anno's Depth",
        "a_genre_ecchi": "Love Revisit Ecchi",
        "a_genre_mahou_shoujo": "Hideaki Anno's Magic Shoujo",
        "a_tag_isekai": "All Night Isekai",
        "a_tag_harem": "Decade Fan Harem",
        "a_tag_bl": "Love Bloomed Bl",
        "a_tag_gl": "Strict Review Gl",
        "a_tag_historical": "Night Love Historical",
        "a_tag_military": "Endless Love Military",
        "a_tag_school": "Classic Romance School",
        "a_tag_martial_arts": "Heart Alerts Martial Arts",
        "a_tag_vampire": "Hideaki Anno's Vampire",
        "a_tag_samurai": "Love's Resolve Samurai",
        "a_tag_space": "Love Magic Space",
        "a_tag_parody": "Classic Fan Parody",
        "a_tag_idol": "Love Bloomed Idol",
        "a_tag_post_apocalyptic": "Secret Feelings Post Apocalyptic",
        "a_tag_cyberpunk": "Romance Marathon Cyberpunk",
        "a_tag_shounen": "Secret Feelings Shounen",
        "a_tag_seinen": "Class Roster Seinen",
        "a_tag_shoujo": "Class Roster Shoujo",
        "a_tag_josei": "Daily Hearts Josei",
        "a_tag_survival": "School Events Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "Together Always",
        "a_mega_completionist": "Anno Master",
        "a_completion_rate_50": "Hideaki Anno's Return",
        "a_completion_rate_75": "Hidden Feeling Crown",
        "a_completion_rate_90": "Daily Hearts Resolution",
        "a_no_drop": "Romance Revisit Decree",
        "a_long_runner_complete": "Eternal Love Clear",
        "a_sequel_chain": "Manga Continues",
        "a_clean_list": "Reader's Resolve Relic",
        "a_from_ptw": "Classic Fan Index",
        "a_rewatch_master": "Romance Master Return",
        "a_short_complete": "Perfect Couple Endgame",
        "a_same_day_start_finish": "Together Always Pinnacle",
        "a_revival": "Romance Binge Insignia",
        "a_zero_to_hero": "Mask to Real",
        "a_five_genre_complete": "Perfect Couple A Five Genre",
        "a_full_franchise": "Classic Romance Chronicle",
        "a_batch_complete": "Heart Journey Crown",
        "a_paused_to_done": "Daily Hearts Aegis Aegis",
        "a_completion_spree": "Dream Romance Triumph",
        "a_multi_rewatch": "Dream Romance Triumph Triumph",
        "a_dropped_recovery": "Night Feelings Conquest",
        "a_ten_perfect_scores": "Eternal Love Acclaim",
        "a_seasonal_clear": "Winter Together Codex",
        "a_complete_genre_span": "Pastel Art A Complete Genre",
        "a_monthly_completions": "Romance Master Afterglow",
        "a_yearly_completions": "Romance Critic Epilogue",
        "a_rapid_complete": "Heart Alerts Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Yukino's Heart",
        "a_studio_devotee": "Romance Revisit Treasury",
        "a_rewatcher": "Romance Revisit",
        "a_triple_rewatch": "Morning Together Coda",
        "a_annual_tradition": "Heart Alerts Proof",
        "a_director_fan": "Reader's Resolve Trial",
        "a_voice_actor_fan": "Night Feelings Crown Crown",
        "a_ost_lover": "Classic Romance Seal",
        "a_source_reader": "Romance Judge Cabinet",
        "a_waiting_weekly": "Romance Revisit Clock",
        "a_childhood_revisit": "Deep Feelings Seal",
        "a_saga_tracker": "Love Magic Standard",
        "a_genre_loyalty": "Unbroken Love Loyalty",
        "a_decade_watcher": "Decade Fan",
        "a_adaptation_hunter": "Classic Fan Trial",
        "a_original_anime_fan": "Drama Action Testament",
        "a_long_commitment": "Heart Alerts Mark Mark",
        "a_perfect_attendance": "Kare Kano Standard",
        "a_favorite_studio_5": "Secret Feelings Library",
        "a_complete_catalog": "School Events Seal",
        "a_franchise_collector": "Secret Feelings Archive",
        "a_airing_follower": "Deep Feelings Signal",
        "a_genre_master": "Reader's Resolve Master",
        "a_staff_follower": "Secret Feelings Oath",
        "a_multi_season_fan": "Night Love Hoard",
        "a_format_diversity": "Hideaki Anno's Cache",
        "a_year_dedication": "Heart Journey Tenure",
        "a_season_dedication": "Endless Love Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Morning Together Explorer",
        "a_studio_hopper": "Romance Master Collection",
        "a_tag_explorer": "Heart Journey Explorer",
        "a_decade_hopper": "Classic Romance Chronicle Chronicle",
        "a_hidden_gem": "Hidden Feeling",
        "a_popular_taste": "Love Bloomed Decree",
        "a_retro_appreciator": "School Events Aegis",
        "a_modern_viewer": "Together Always Pinnacle Pinnacle",
        "a_cross_demographic": "Love Revisit Pinnacle",
        "a_underdog_fan": "Pastel Art Trial",
        "a_variety_week": "Secret Feelings Horizon",
        "a_foreign_cinema": "Strict Review Expedition",
        "a_classic_connoisseur": "98 Classic Fan",
        "a_every_season": "Deep Feelings Archive",
        "a_award_winner": "Yukino's Faces Insignia",
        "a_niche_explorer": "Class Roster Horizon",
        "a_global_anime": "Perfect Couple Crown",
        "a_cult_classic": "GAINAX Classic",
        "a_random_pick": "Love Bloomed Decree Decree",
        "a_new_genre_month": "Kare Kano A New Genre",
        "a_seasonal_completionist": "Romance Binge Summit",
        "a_unpopular_opinion": "Anno Master Standard",
        "a_top_rated_viewer": "Romance Run Seal",
        "a_source_variety": "Winter Together Storehouse",
        "a_low_score_brave": "Romance Marathon Measure",
        "a_upcoming_watcher": "Romance Run Seal Seal",
        "a_short_series_explorer": "Strict Review Expedition Expedition",
        "a_long_series_explorer": "Love Sprint Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Night Feelings",
        "a_early_bird": "Morning Together",
        "a_lunch_break": "Mask Real Trial",
        "a_golden_hour": "Yukino's Heart Tenure",
        "a_four_am_club": "Dream Romance Gathering",
        "a_witching_hour": "Hidden Feeling Tenure",
        "a_new_year_watch": "Heart Journey Season",
        "a_midnight_premiere": "Anno's Depth Devotion",
        "a_all_hours": "Romance Binge Seal",
        "a_dawn_warrior": "Love Bloomed Aegis",
        "a_afternoon_delight": "Tsuda Fan Proof Proof",
        "a_prime_time": "Yukino's Faces Insignia Insignia",
        "a_workday_watcher": "Love Revisit Pinnacle Pinnacle",
        "a_sunday_marathon": "Eternal Love Momentum",
        "a_rainy_day": "Hidden Feeling Relic",
        "a_morning_routine": "Night Love Promise",
        "a_night_shift": "Hideaki Anno's Aegis",
        "a_twilight_zone": "Rival Terror Ledger",
        "a_seasonal_premier": "Romance Revisit Cabinet",
        "a_clock_collector": "Dream Romance Repository",
        "a_weekend_binge_hours": "Class Roster Streak",
        "a_late_night_regular": "Romance Critic Dominion",
        "a_sunrise_watcher": "Reader's Resolve Relic Relic",
        "a_holiday_watcher": "Romance Run Pact",
        "a_every_day_of_week": "Gainax Classic Ledger",
        "a_monthly_hours": "Love Bloomed Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Daily Hearts Record",
        "a_party_host": "Hideaki Anno's Record Record",
        "a_social_butterfly": "Romance Judge Company",
        "a_group_binge": "Love's Resolve Sprint",
        "a_party_regular": "Rival Terror Chronicle",
        "a_sync_viewer": "Dream Romance Standard",
        "a_commentator": "School Events Record",
        "a_party_marathon": "Morning Together Vigil",
        "a_full_house": "Endless Love Trial",
        "a_community_pillar": "Romance Critic Alliance",
        "a_watch_party_streak": "School Events Vigil",
        "a_diverse_party": "Night Love Seal",
        "a_late_night_party": "Romance Critic Testament Testament",
        "a_party_veteran": "Endless Love Testament",
        "a_genre_party": "Strict Review Party",
        "a_weekly_party": "Dream Romance Calendar",
        "a_silent_viewer": "Drama Action Mantle",
        "a_recommendation_giver": "Class Roster Network",
        "a_party_completionist": "Love Magic Coda",
        "a_social_scorer": "Reader's Resolve Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Love Sprint Proof",
        "a_fibonacci": "Heart Journey Dominion",
        "a_palindrome_day": "Heart Journey Relic Relic",
        "a_binary_day": "Unbroken Love Mark",
        "a_full_moon": "Deep Feelings Insignia",
        "a_leap_year": "Perfect Couple Devotion",
        "a_time_traveler": "Romance Revisit Record",
        "a_genre_clash": "Morning Together Clash",
        "a_triple_seven": "Heart Journey Testament",
        "a_thousand_complete": "Drama Action Epilogue",
        "a_pi_episodes": "Love Revisit Crown",
        "a_synchronicity": "Pastel Art Anchor",
        "a_world_record": "Night Feelings Warrant",
        "a_nice": "Yukino's Faces Chronicle",
        "a_power_level": "Drama Action Testament Testament",
        "a_answer_42": "Love Bloomed Standard",
        "a_square_number": "Morning Together Decree",
        "a_prime_count": "Yukino's Faces Seal",
        "a_matching_date": "Pastel Art Mantle",
        "a_century_episode": "Love Revisit Mark",
        "a_double_digits": "Hidden Feeling Testament",
        "a_one_two_three": "Perfect Couple Crown Crown",
        "a_lucky_seven": "Heart Alerts Crown",
        "a_all_tens": "Romance Marathon Criterion",
        "a_exact_hundred_eps": "Love Magic Legend",
        "a_year_match_count": "Romance Revisit Yearlong",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Class Roster Ledger",
        "a_movie_buff": "Night Feelings Mark Mark",
        "a_ova_hunter": "Love Magic Standard Standard",
        "a_ona_explorer": "Pastel Art Secret",
        "a_special_watcher": "Hidden Feeling Relic Relic",
        "a_short_king": "Decade Fan Crown",
        "a_variety_pack": "Night Feelings Inquiry",
        "a_film_festival": "Romance Run Chronicle",
        "a_music_video": "Night Love Chronicle",
        "a_tv_short": "Morning Together Record",
        "a_movie_marathon": "Morning Together Gauntlet",
        "a_double_length": "Love Sprint Crown Crown",
        "a_anthology": "Hideaki Anno's Aegis Aegis",
        "a_mini_series": "Anno Master Decree",
        "a_theatrical": "Secret Feelings Accord",
        "a_format_master": "Dream Romance Vault",
        "a_long_movie": "Romance Binge Insignia Insignia",
        "a_back_catalog": "School Events Standard",
        "a_cm_watcher": "All Night Aegis",
        "a_pv_collector": "Pastel Art Storehouse",
        "a_format_balance": "Dream Romance Vault Vault",
        "a_episodic_master": "All Night Standard",
        "a_sequel_movie": "Perfect Couple Pinnacle",
        "a_recap_watcher": "Mask Real Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Hearts",
        "a_mega_streak": "Endless Love",
        "a_weekly_warrior": "Endless Love Season",
        "a_monthly_watcher": "Anno's Depth Calendar",
        "a_comeback": "Romance Judge Decree",
        "a_weekend_streak": "Romance Marathon Passage",
        "a_no_zero_days": "Unbroken Love Warrant Warrant",
        "a_iron_will": "Love's Resolve",
        "a_habit_formed": "Gainax Classic Banner",
        "a_consistent_pace": "Love Sprint Measure",
        "a_year_long": "Year Together",
        "a_double_streak": "Reader's Resolve Watch",
        "a_streak_recovery": "Drama Action Season",
        "a_daily_minimum": "Anno's Depth Focus",
        "a_winter_streak": "Strict Review Watch",
        "a_summer_streak": "Hidden Feeling Resolve",
        "a_morning_streak": "School Events Clock",
        "a_night_streak": "Gainax Classic Constancy",
        "a_unbreakable": "Decade Fan Proof",
        "a_eternal_flame": "Romance Master Standard",
        "a_completion_streak": "Love Magic Return",
        "a_rating_streak": "Heart Journey Balance",
        "a_multi_ep_streak": "Night Feelings Ritual",
        "a_genre_streak": "Heart Journey Streak",
        "a_studio_streak": "Romance Judge Cabinet Cabinet",
        "a_perfect_week": "Pastel Art Relic",

        // ── ANIME SCORING ──
        "a_critic": "Romance Judge",
        "a_perfect_ten": "Perfect Couple",
        "a_harsh_critic": "Strict Review",
        "a_fair_judge": "Romance Critic Balance",
        "a_generous_spirit": "Anno's Depth Pinnacle",
        "a_score_all": "Tsuda Fan Criterion",
        "a_wide_range": "Yukino's Faces Ledger",
        "a_controversial": "School Events Decree",
        "a_consistent_scorer": "Romance Revisit Verdict",
        "a_score_sniper": "Perfect Couple Score",
        "a_evolving_taste": "Reader's Resolve Testament",
        "a_bell_curve": "Kare Kano Insignia",
        "a_picky_watcher": "Drama Action Warrant",
        "a_100_rated": "Dream Romance Warrant",
        "a_500_rated": "Decade Fan Pinnacle",
        "a_mediocre_majority": "Pastel Art Canon",
        "a_rating_spree": "School Events Review",
        "a_score_variance": "Romance Marathon Score",
        "a_masterpiece_hunter": "School Events Banner",
        "a_contrarian": "Morning Together Record Record",
        "a_optimist": "Night Love Ledger",
        "a_score_distributor": "Mask Real Appraisal",
        "a_genre_critic": "Love Sprint Critic",
        "a_mean_above_8": "Heart Alerts Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Love",
        "a_valentines_weeb": "Secret Feelings Vow",
        "a_pi_day": "Romance Critic Trial",
        "a_april_fools": "Perfect Couple Devotion Devotion",
        "a_international_anime_day": "Romance Binge Record",
        "a_star_wars_day": "Eternal Love Chronicle",
        "a_summer_solstice": "Unbroken Love Calendar",
        "a_tanabata": "Together Always Focus",
        "a_friday_13th": "Mask Real Relic",
        "a_halloween_spirit": "Class Roster Vow",
        "a_thanksgiving_binge": "Rival Terror Run",
        "a_christmas_special": "Winter Together",
        "a_new_years_eve": "Heart Alerts Pilgrimage",
        "a_birthday_watch": "Kare Kano Vow",
        "a_holiday_marathon": "Love's Resolve Overture",
        "a_independence_day": "Romance Master Banner",
        "a_culture_day": "Classic Romance Insignia",
        "a_spring_equinox": "Love's Resolve Decree",
        "a_earth_day": "Night Feelings Mantle",
        "a_labor_day": "Class Roster Seal",
        "a_winter_solstice": "Love Revisit Pilgrimage",
        "a_anime_birthday": "Night Feelings Pilgrimage",
        "a_every_holiday": "Classic Fan Resolve",
        "a_consecutive_holidays": "Hidden Feeling Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Romance Judge Rank",
        "a_meta_collector": "Classic Romance Hoard",
        "a_meta_category_starter": "Anno's Depth Badge",
        "a_meta_tier_climber": "Classic Romance Glyph",
        "a_meta_tier_max": "Eternal Love",
        "a_meta_xp_earner": "Mask Real Emblem",
        "a_meta_difficulty_easy": "Romance Critic Mechanism",
        "a_meta_difficulty_hard": "Romance Run Writ",
        "a_meta_unlock_spree": "Endless Love Panel",
        "a_meta_completionist": "Complete Romance",
        "a_meta_diverse": "Heart Journey Emblem",
        "a_meta_dominator": "Rival Terror Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Blush",
        "m_chapter_counter": "Dream Romance Pinnacle",
        "m_chapter_titan": "Winter Together Relic",
        "m_reading_hours": "Mask Real Relic Relic",
        "m_reading_time_lord": "Romance Binge Record Record",
        "m_manga_collector": "Endless Love Ledger",
        "m_library_legend": "Classic Romance Reliquary",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "Secret Feelings Seal",
        "m_first_rating": "Mask Real Eye",
        "m_ten_thousand_pages": "Secret Feelings Gauge",
        "m_volume_collector": "Drama Action Storehouse",
        "m_year_explorer": "Love Bloomed Quest",
        "m_century_reader": "Strict Review Dominion",
        "m_five_hundred_ch": "Yukino's Faces Legend",
        "m_thousand_ch": "Reader's Resolve Legend",
        "m_reading_ten": "Strict Review Appraisal",
        "m_ptr_hoarder": "Reader's Resolve Index",
        "m_dropped_honesty": "Classic Romance Summit",
        "m_season_reader": "School Events Treasury",
        "m_active_reader": "Hidden Feeling Trial",
        "m_five_thousand_ch": "Morning Together Standard",
        "m_ten_completed": "Morning Together Resolution",
        "m_fifty_completed": "Reader's Resolve Harvest",
        "m_five_hundred_completed": "Gainax Classic Legacy",
        "m_mean_score_tracker": "Romance Revisit Audit",
        "m_unique_authors": "Night Feelings Reserve",
        "m_all_status": "Hidden Feeling Testament Testament",
        "m_first_favorite": "Love Magic Cache",
        "m_favorites_collector": "Romance Judge Shelf",
        "m_days_spent_reading": "Love Revisit Relic",

        // ── MANGA BINGE ──
        "m_binge_reader": "Kare Kano Streak",
        "m_marathon_reader": "Romance Critic Rush",
        "m_weekend_reader": "Deep Feelings Run",
        "m_non_stop_reading": "Love Magic Gauntlet",
        "m_one_more_chapter": "Mask Real Testament Testament",
        "m_speed_read": "Unbroken Love Drive",
        "m_double_story": "Love's Resolve Banner",
        "m_triple_read": "Romance Master Record",
        "m_five_a_day": "Night Love Insignia",
        "m_chapter_chain": "Classic Romance Accord",
        "m_volume_binge": "Romance Marathon Drive",
        "m_power_reader": "Eternal Love Seal Seal",
        "m_half_day_read": "Romance Judge Aegis",
        "m_full_day_read": "All Night Aegis Aegis",
        "m_power_weekend": "Secret Feelings Streak",
        "m_binge_king": "Romance Binge",
        "m_no_sleep_read": "Strict Review Rush",
        "m_full_series_rush": "Romance Critic Cascade",
        "m_seven_day_challenge": "Together Always Warrant",
        "m_hundred_day_read": "Heart Journey Legend",
        "m_volume_rush": "Daily Hearts Gauntlet",
        "m_series_sweep": "Classic Fan Trial Trial",
        "m_genre_binge": "All Night Binge",
        "m_author_binge": "Deep Feelings Surge",
        "m_chapter_counter_day": "Rival Terror Ledger Ledger",
        "m_multi_series_binge": "Yukino's Faces Charge",
        "m_midnight_binge": "Reader's Resolve Tempest",
        "m_new_year_binge": "Night Feelings Passage",
        "m_forty_eight_hour": "Romance Revisit Rally",
        "m_oneshot_binge": "Unbroken Love Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Drama Chapter",
        "m_genre_adventure": "Heart Chapter",
        "m_genre_comedy": "Romance Judge Comedy",
        "m_genre_drama": "Deep Chapter",
        "m_genre_fantasy": "Dream Chapter",
        "m_genre_horror": "Rival Chapter",
        "m_genre_mystery": "Morning Together Mystery",
        "m_genre_romance": "Love Chapter",
        "m_genre_scifi": "Unusual Chapter",
        "m_genre_sol": "Dream Romance Slice",
        "m_genre_sports": "Daily Hearts Sports",
        "m_genre_supernatural": "Magic Chapter",
        "m_genre_thriller": "Pastel Art Thriller",
        "m_genre_psychological": "Inner Chapter",
        "m_genre_isekai": "Endless Love Isekai",
        "m_genre_shounen": "Yukino's Heart Shounen",
        "m_genre_ecchi": "Love Sprint Ecchi",
        "m_genre_mahou_shoujo": "Romance Judge Magic Shoujo",
        "m_genre_mecha": "Drama Action Mecha",
        "m_genre_music": "Class Roster Music",
        "m_tag_isekai_new": "Mask Real Isekai New",
        "m_tag_harem": "Tsuda Fan Harem",
        "m_tag_bl": "Anno Master Bl",
        "m_tag_gl": "Reader's Resolve Gl",
        "m_tag_historical": "Yukino's Faces Historical",
        "m_tag_military": "Yukino's Heart Military",
        "m_tag_school": "Secret Feelings School",
        "m_tag_martial_arts": "Dream Romance Martial Arts",
        "m_tag_vampire": "Daily Hearts Vampire",
        "m_tag_samurai": "Hideaki Anno's Samurai",
        "m_tag_space": "Anno Master Space",
        "m_tag_parody": "Drama Action Parody",
        "m_tag_idol": "Anno Master Idol",
        "m_tag_post_apocalyptic": "Classic Romance Post Apocalyptic",
        "m_tag_cyberpunk": "Tsuda Fan Cyberpunk",
        "m_tag_shoujo": "Romance Run Shoujo",
        "m_tag_survival": "Romance Judge Survival",
        "m_tag_cooking": "Kare Kano Cooking",
        "m_tag_medical": "Hidden Feeling Medical",
        "m_tag_villainess": "Deep Feelings Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Romance Master",
        "m_completion_rate_50": "Anno Master Return",
        "m_completion_rate_75": "Pastel Art Ascension",
        "m_completion_rate_90": "Romance Master Resolution",
        "m_no_drop": "Love Magic Decree",
        "m_long_runner_complete": "Rival Terror Clear",
        "m_sequel_chain": "Class Roster Seal Seal",
        "m_clean_list": "Winter Together Relic Relic",
        "m_from_ptr": "Romance Run Watchlist",
        "m_reread_master": "Romance Critic Trial Trial",
        "m_oneshot_complete": "Romance Critic Ascension",
        "m_same_day_start_finish": "Heart Alerts Crown Crown",
        "m_revival": "Rival Terror Accord",
        "m_zero_to_hundred": "Morning Together Banner",
        "m_five_genre_complete": "Unbroken Love M Five Genre",
        "m_full_collection": "Heart Alerts Proof Proof",
        "m_batch_complete": "Romance Revisit Summit",
        "m_paused_to_done": "Romance Master Standard Standard",
        "m_completion_spree": "Decade Fan Triumph",
        "m_format_completionist": "Romance Critic Completion",
        "m_catch_up": "Romance Binge Chronicle",
        "m_multi_reread": "Love Magic Banner",
        "m_dropped_recovery": "Love Sprint Conquest",
        "m_ten_perfect_scores": "Deep Feelings Judgment",
        "m_complete_genre_span": "Endless Love M Complete Genre",
        "m_monthly_completions": "All Night Return",
        "m_yearly_completions": "Endless Love Epilogue",
        "m_rapid_complete": "Together Always Finale",
        "m_author_complete": "Secret Feelings Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Devoted Reader",
        "m_mangaka_lover": "Tsuda Fan",
        "m_rereader": "Love Revisit",
        "m_triple_reread": "Heart Journey Testament Testament",
        "m_annual_reread": "Morning Together Banner Banner",
        "m_publisher_fan": "Decade Fan Mark",
        "m_artist_fan": "Class Roster Insignia",
        "m_adaptation_compare": "Kare Kano Insignia Insignia",
        "m_source_material_fan": "Manga First",
        "m_waiting_weekly": "Hideaki Anno's Streak",
        "m_classic_reader": "Drama Action Lantern",
        "m_saga_reader": "Classic Romance Decree",
        "m_genre_loyalty": "Love Sprint Loyalty",
        "m_decade_reader": "Romance Marathon Warrant",
        "m_ln_adaptation": "Romance Marathon Mark",
        "m_original_work": "Daily Hearts Standard",
        "m_long_commitment": "Love Sprint Mark",
        "m_up_to_date": "Night Feelings Warrant Warrant",
        "m_favorite_mangaka": "Love Bloomed Treasury",
        "m_complete_portfolio": "Decade Fan Triumph Triumph",
        "m_franchise_collector": "Romance Binge Archive",
        "m_serialization_follower": "Love Bloomed Handshake",
        "m_genre_master": "Winter Together Master",
        "m_multi_series_author": "Classic Romance Insignia Insignia",
        "m_format_diversity": "Daily Hearts Shelf",
        "m_year_dedication": "Strict Review Tenure",
        "m_ongoing_follower": "Romance Marathon Fellowship",
        "m_genre_loyalty_50": "Reader's Resolve Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Love's Resolve Explorer",
        "m_publisher_hopper": "Decade Fan Mantle",
        "m_tag_explorer": "Classic Fan Explorer",
        "m_decade_hopper": "Romance Run Chronicle Chronicle",
        "m_hidden_gem": "Hidden Volume",
        "m_popular_taste": "Romance Revisit Record Record",
        "m_retro_reader": "Romance Revisit Accord",
        "m_modern_reader": "Yukino's Faces Seal Seal",
        "m_cross_demographic": "Anno's Depth Crown",
        "m_underdog_fan": "Romance Revisit Accord Accord",
        "m_variety_week": "Class Roster Horizon Horizon",
        "m_manhwa_reader": "Perfect Couple Proof",
        "m_manhua_reader": "Drama Action Mantle Mantle",
        "m_classic_connoisseur": "Gainax Classic Glimpse",
        "m_award_winner": "Strict Review Warrant",
        "m_niche_explorer": "Kare Kano Horizon",
        "m_world_manga": "Romance Binge Chronicle Chronicle",
        "m_cult_classic": "Classic Romance",
        "m_random_pick": "Romance Revisit Standard",
        "m_new_genre_month": "Romance Binge M New Genre",
        "m_year_completionist": "Dream Romance Fulfillment",
        "m_unpopular_opinion": "Night Feelings Trial",
        "m_top_rated_reader": "Kare Kano Record",
        "m_source_variety": "Drama Action Catalogue",
        "m_low_score_brave": "Dream Romance Score",
        "m_short_manga_explorer": "Yukino's Faces Compass",
        "m_long_manga_explorer": "Morning Together Survey",
        "m_serialization_explorer": "Pastel Art Road",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Anno Master Ledger",
        "m_commute_reader": "Hidden Feeling Tenure Tenure",
        "m_four_am_club": "Decade Fan Fellowship",
        "m_new_year_read": "Class Roster Pact",
        "m_all_hours": "Romance Run Accord Accord",
        "m_prime_time_reader": "Daily Hearts Banner",
        "m_workday_reader": "Rival Terror Accord Accord",
        "m_sunday_read": "Anno Master Standard Standard",
        "m_morning_routine": "Rival Terror Discipline",
        "m_night_shift_reader": "Secret Feelings Accord Accord",
        "m_seasonal_premier_read": "Drama Action Seasonal",
        "m_clock_collector": "Love Revisit Reserve",
        "m_late_night_horror": "Unbroken Love Mark Mark",
        "m_afternoon_reader": "Strict Review Mantle Mantle",
        "m_golden_hour_reader": "Heart Journey Observance",
        "m_dawn_reader": "Classic Fan Mantle",
        "m_twilight_reader": "Romance Marathon Crown",
        "m_midnight_start": "Daily Hearts Routine",
        "m_weekend_binge_hours": "Deep Feelings Momentum",
        "m_late_night_regular": "Anno Master Accord",
        "m_sunrise_reader": "Tsuda Fan Mantle",
        "m_every_day_of_week": "Drama Action Warrant Warrant",
        "m_monthly_hours": "Love's Resolve Vigil",
        "m_bedtime_reader": "Dream Romance Warrant Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Pastel Art",
        "m_webtoon_reader": "Romance Marathon Mark Mark",
        "m_full_color": "Class Roster Accord",
        "m_doujin_reader": "Romance Master Record Record",
        "m_anthology_reader": "Deep Feelings Accord",
        "m_adaptation_reader": "Romance Revisit Banner",
        "m_longstrip_reader": "Heart Journey Trial",
        "m_4koma_reader": "Hideaki Anno's Ledger",
        "m_oneshot_reader": "Endless Love Mantle",
        "m_format_variety": "Decade Fan Gallery",
        "m_light_novel_reader": "Romance Run Insignia",
        "m_novel_reader": "Dream Romance Crown",
        "m_visual_storyteller": "Strict Review Testament",
        "m_colored_classic": "School Events Survey",
        "m_webcomic_fan": "Gainax Classic Insignia",
        "m_manga_to_anime": "Manga Adapted",
        "m_seinen_reader": "Love Sprint Pinnacle",
        "m_josei_reader": "Tsuda Fan Pinnacle",
        "m_award_winning_art": "Yukino's Heart Relic",
        "m_debut_work": "Yukino's Heart Dominion",
        "m_vertical_scroll": "Classic Romance Decree Decree",
        "m_traditional_format": "Kare Kano Hoard",
        "m_cross_media": "Yukino's Faces Accord",
        "m_spinoff_reader": "Romance Binge Accord",
        "m_remake_reader": "Romance Critic Pinnacle",
        "m_collaboration_reader": "Gainax Classic Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Unbroken Love",
        "m_weekly_warrior": "Pastel Art Season",
        "m_monthly_reader": "Night Love Discipline",
        "m_comeback": "Morning Together Standard Standard",
        "m_weekend_streak": "Tsuda Fan Fever",
        "m_no_zero_days": "Perfect Couple Proof Proof",
        "m_iron_will": "Reader's Resolve",
        "m_habit_formed": "Anno's Depth Crown Crown",
        "m_consistent_pace": "Heart Alerts Scrutiny Scrutiny",
        "m_year_long": "Year Reading",
        "m_double_streak": "Endless Love Resolve",
        "m_streak_recovery": "Winter Together Resolve",
        "m_daily_minimum": "Love Revisit Focus",
        "m_winter_streak": "Heart Journey Observance Observance",
        "m_summer_streak": "Yukino's Heart Observance",
        "m_morning_streak": "Love's Resolve Clock",
        "m_night_streak": "Kare Kano Discipline",
        "m_unbreakable": "Tsuda Fan Warrant",
        "m_eternal_flame": "Romance Judge Record",
        "m_chapter_a_day": "Anno Master Ledger Ledger",
        "m_genre_streak": "Classic Fan Streak",
        "m_completion_streak": "Romance Revisit Return",
        "m_rating_streak": "Classic Fan Appraisal",
        "m_multi_ch_streak": "Pastel Art Tenure",
        "m_author_streak": "Love Revisit Calendar",
        "m_perfect_week_manga": "Romance Binge Accord Accord",
        "m_diverse_streak": "Love Magic Streak",

        // ── MANGA SCORING ──
        "m_critic": "Romance Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_harsh_critic": "Romance Run Scale",
        "m_fair_judge": "Mask Real Eye Eye",
        "m_generous_spirit": "Deep Feelings Decree",
        "m_score_all": "Romance Marathon Reckoning",
        "m_wide_range": "Night Love Ledger Ledger",
        "m_controversial": "All Night Standard Standard",
        "m_consistent_scorer": "Romance Master Grade",
        "m_score_sniper": "Night Feelings Reckoning",
        "m_evolving_taste": "Endless Love Trial Trial",
        "m_bell_curve": "Night Love Accord",
        "m_picky_reader": "Love Magic Ledger",
        "m_100_rated": "Night Love Standard",
        "m_500_rated": "Secret Feelings Aegis",
        "m_mediocre_majority": "Endless Love Canon",
        "m_rating_spree": "Love's Resolve Verdict",
        "m_score_variance": "Dream Romance Measure",
        "m_binge_rater": "Love Revisit Passage",
        "m_reread_rerate": "School Events Banner Banner",
        "m_masterpiece_hunter": "All Night Banner",
        "m_contrarian": "Romance Revisit Aegis",
        "m_optimist": "Yukino's Faces Accord Accord",
        "m_score_distributor": "Pastel Art Balance",
        "m_genre_critic": "Love Revisit Critic",
        "m_mean_above_8": "Dream Romance Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Strict Review Season",
        "m_valentines_read": "Classic Fan Observance",
        "m_pi_day": "Endless Love Testament Testament",
        "m_april_fools": "Night Feelings Devotion",
        "m_international_manga_day": "Romance Run Aegis",
        "m_free_comic_day": "Deep Feelings Chronicle",
        "m_summer_solstice": "Together Always Focus Focus",
        "m_tanabata": "Heart Alerts Tanabata",
        "m_friday_13th": "Romance Critic Dominion Dominion",
        "m_halloween_read": "Unbroken Love Halloween",
        "m_thanksgiving_binge": "Romance Binge Charge",
        "m_christmas_read": "Rival Terror Pact",
        "m_new_years_eve": "Together Always Pilgrimage",
        "m_birthday_read": "Love Sprint Focus",
        "m_holiday_marathon": "Love Bloomed Rally",
        "m_independence_day": "Romance Revisit Aegis Aegis",
        "m_culture_day": "Secret Feelings Seal Seal",
        "m_spring_equinox": "Unbroken Love Dominion",
        "m_earth_day": "Love Sprint Trial",
        "m_labor_day": "Rival Terror Seal",
        "m_winter_solstice": "Anno's Depth Focus Focus",
        "m_manga_birthday": "Heart Alerts Ritual",
        "m_every_holiday_reader": "Winter Together Watch",
        "m_consecutive_holidays": "Romance Critic Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Eternal Love Aegis",
        "m_fibonacci": "Hidden Feeling Dominion",
        "m_palindrome_day": "Endless Love Relic",
        "m_binary_day": "Anno's Depth Proof",
        "m_full_moon_read": "Tsuda Fan Crown",
        "m_leap_year_read": "Love Magic Practice",
        "m_triple_seven": "Mask Real Trial Trial",
        "m_thousand_complete": "Mask Real Ascension",
        "m_nice": "Classic Romance Seal Seal",
        "m_power_level_chapters": "Morning Together Aegis",
        "m_answer_42": "Tsuda Fan Trial",
        "m_square_number": "Romance Judge Standard",
        "m_prime_count": "Mask Real Pinnacle",
        "m_matching_date": "Winter Together Mantle",
        "m_century_chapter": "Eternal Love Decree",
        "m_pi_chapters": "Love Sprint Proof Proof",
        "m_synchronicity": "Classic Fan Emblem",
        "m_world_record": "Perfect Couple Warrant",
        "m_genre_clash": "Daily Hearts Clash",
        "m_time_traveler": "Romance Master Decree",
        "m_double_digits": "Drama Action Dominion",
        "m_one_two_three": "Gainax Classic Banner Banner",
        "m_lucky_seven": "Kare Kano Record Record",
        "m_exact_hundred_ch": "Hidden Feeling Legend",
        "m_year_match_count": "Hideaki Anno's Routine",
        "m_chapter_match_date": "Anno's Depth Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Drama Action Index",
        "m_manhwa_format": "Unbroken Love Gallery",
        "m_manhua_format": "Heart Journey Storehouse",
        "m_ln_format": "Mask Real Index",
        "m_oneshot_format": "Endless Love Index",
        "m_doujin_format": "Love's Resolve Cabinet",
        "m_novel_format": "Night Feelings Reserve Reserve",
        "m_format_master_manga": "Love's Resolve Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Romance Master Link",
        "m_meta_collector": "Secret Feelings Reliquary",
        "m_meta_category_starter": "Decade Fan Standard",
        "m_meta_tier_climber": "Yukino's Faces Token",
        "m_meta_tier_max": "Love Complete",
        "m_meta_xp_earner": "Drama Action Anchor",
        "m_meta_difficulty_easy": "Mask Real Panel",
        "m_meta_difficulty_hard": "Strict Review Node",
        "m_meta_unlock_spree": "Drama Action Marker",
        "m_meta_completionist": "Full Library",
        "m_meta_diverse": "Endless Love Anchor",
        "m_meta_dominator": "Classic Romance Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060103",
        primary: "#ba5270",
        secondary: "#7a2242",
        accent: "#80a0d8",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/kare-kano.jpg",
    particleColor: "#e89ab4",
    backgroundDim: 0.3,
    backgroundBlur: 16,
    particleTypes: {
        rose_petals: { label: "Rose Petals", maxCount: 18, defaultEnabled: true, defaultIntensity: 60 },
        hearts: { label: "Hearts", maxCount: 12, defaultEnabled: true, defaultIntensity: 50 },
    },
    milestoneNames: {
  1: "Threadbare Generic Rank Spark",
  8: "Generic's Tarnished Omen",
  14: "Fractured Generic Rank",
  21: "Generic Rank Path",
  28: "Lowborn Legacy Myth",
  35: "Generic Rank Pulse",
  41: "Generic's Legacy Crest",
  48: "Humble Generic Mark",
  55: "Ragged Generic Rank Vow",
  61: "Generic's Faint Echo",
  68: "Lesser Generic Rank",
  75: "Generic Rank Zenith",
  81: "Doubtful Legacy Bloom",
  88: "Generic Rank Sigil",
  95: "Generic's Legacy Flame",
  102: "Really Cool Generic Spark",
  108: "Awakened Generic Rank Omen",
  115: "Generic's Resolute Seal",
  122: "Rising Generic Rank",
  128: "Generic Rank Myth",
  135: "Dauntless Legacy Pulse",
  142: "Generic Rank Crest",
  149: "Generic's Legacy Mark",
  155: "Fresh Generic Vow",
  162: "Valiant Generic Rank Echo",
  169: "Generic's Prime Crown",
  175: "Polished Generic Rank",
  182: "Generic Rank Bloom",
  189: "Stormlit Legacy Sigil",
  195: "Generic Rank Flame",
  202: "Generic's Legacy Spark",
  209: "Tempered Generic Omen",
  216: "Trusted Generic Rank Seal",
  222: "Generic's Steadfast Path",
  229: "Ironclad Generic Rank",
  236: "Veteran Legacy Pulse",
  242: "Core Legacy Crest",
  249: "Generic Rank Mark",
  256: "Generic's Legacy Vow",
  262: "Formidable Generic Echo",
  269: "Lucid Generic Rank Crown",
  276: "Generic's Ranked Zenith",
  283: "Fabled Generic Rank",
  289: "Grand Legacy Sigil",
  296: "Seasoned Legacy Flame",
  303: "Generic Rank Spark",
  309: "Generic's Legacy Omen",
  316: "Valorous Generic Seal",
  323: "Stalwart Generic Rank Path",
  330: "Generic's Commanding Myth",
  336: "Refined Generic Rank",
  343: "Unbroken Legacy Crest",
  350: "Blazing Legacy Mark",
  356: "Generic Rank Vow",
  363: "Generic's Legacy Echo",
  370: "Peerless Generic Crown",
  376: "Ardent Generic Rank Zenith",
  383: "Generic's Focused Bloom",
  390: "Vigilant Generic Rank",
  397: "Dominant Legacy Flame",
  403: "Elite Legacy Spark",
  410: "Generic Rank Omen",
  417: "Generic's Legacy Seal",
  423: "Sovereign Generic Path",
  430: "Regal Generic Rank Myth",
  437: "Generic's Crowned Pulse",
  444: "Mythborn Generic Rank",
  450: "Limitless Legacy Mark",
  457: "Radiant Legacy Vow",
  464: "Generic Rank Echo",
  470: "Generic's Legacy Crown",
  477: "Climactic Generic Zenith",
  484: "Epic Generic Rank Bloom",
  490: "Generic's Unreal Sigil",
  497: "Peak Generic Rank",
  504: "Supreme Legacy Spark",
  511: "Exalted Legacy Omen",
  517: "Generic Rank Seal",
  524: "Generic's Legacy Path",
  531: "Celestial Generic Myth",
  537: "Phantom Generic Rank Pulse",
  544: "Generic's Crimson Crest",
  551: "Silver Generic Rank",
  557: "Golden Legacy Vow",
  564: "Feral Legacy Echo",
  571: "Generic Rank Crown",
  578: "Generic's Legacy Zenith",
  584: "Dread Generic Bloom",
  591: "Luminous Generic Rank Sigil",
  598: "Generic's Thunderous Flame",
  604: "Ultraviolet Generic Rank",
  611: "Unleashed Legacy Omen",
  618: "Secret Legacy Seal",
  625: "Final Generic Path",
  631: "Generic's Legacy Myth",
  638: "Worldclass Generic Pulse",
  645: "Lawless Generic Rank Crest",
  651: "Generic's Chosen Mark",
  658: "Fearless Generic Rank",
  665: "Overdrive Legacy Echo",
  671: "Cinematic Legacy Crown",
  678: "Impossible Generic Zenith",
  685: "Generic's Legacy Bloom",
  692: "Canonized Generic Sigil",
  698: "Ascendant Generic Rank Flame",
  705: "Generic's Transfigured Spark",
  712: "Immortal Generic Rank",
  718: "Eclipsed Legacy Seal",
  725: "Astral Legacy Path",
  732: "Sublime Generic Myth",
  739: "Generic's Legacy Pulse",
  745: "Prismatic Generic Crest",
  752: "Abyssal Generic Rank Mark",
  759: "Generic's Unbound Vow",
  765: "Eternal Generic Rank",
  772: "Cosmic Legacy Crown",
  779: "Transcendent Legacy Zenith",
  785: "Perfected Generic Bloom",
  792: "Generic's Legacy Sigil",
  799: "Ultimate Generic Flame",
  806: "Mythic Generic Rank Spark",
  812: "Generic's Godlike Omen",
  819: "Canonical Generic Rank",
  826: "Reality-Bent Legacy Path",
  832: "Heavenly Legacy Myth",
  839: "Absolute Generic Pulse",
  846: "Untouchable Generic Crest",
  852: "Timeless Generic Mark",
  859: "Empyrean Generic Rank Vow",
  866: "Generic's Primordial Echo",
  873: "Omniscient Generic Rank",
  879: "Unfathomed Legacy Zenith",
  886: "Apocalyptic Legacy Bloom",
  893: "Seraphic Generic Sigil",
  899: "Omega Generic Flame",
  906: "Final Generic Spark",
  913: "Crowned Generic Rank Omen",
  920: "Generic's Mythic Seal",
  926: "Absolute Generic Rank",
  933: "Eternal Legacy Myth",
  940: "Cosmic Legacy Pulse",
  946: "Transcendent Generic Crest",
  953: "Perfected Generic Mark",
  960: "Definitive Generic Vow",
  966: "Ultimate Generic Rank Echo",
  973: "Generic's Infinite Crown",
  980: "Sovereign Generic Rank",
  987: "Celestial Legacy Bloom",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate Generic Rank"
},
}
