import { AnimeThemeConfig } from "./types"
import { GiFlame, GiFist, GiDeathSkull, GiBullets, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiLightningBow } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const katekyoHitmanRebornTheme: AnimeThemeConfig = {
    id: "katekyo-hitman-reborn",
    displayName: "Katekyo Hitman Reborn!",
    description: "Tsuna Sawada is told he's the heir to the Vongola mafia family by Reborn — a baby hitman tutor. Forced into battles with dying will flames, the No-Good Tsuna becomes a true boss.",
    fontFamily: "'Exo 2', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Exo+2:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "255 180 140",
        "--color-brand-300": "248 148 90",
        "--color-brand-400": "235 112 38",
        "--color-brand-500": "214 80 0",
        "--color-brand-600": "175 62 0",
        "--color-brand-700": "136 46 0",
        "--color-brand-800": "96 32 0",
        "--color-brand-900": "58 18 0",
        "--color-brand-950": "32 10 0",
        "--brand": "214 80 0",
        "--background": "#060200",
        "--paper": "#0e0600",
        "--color-gray-950": "6 2 0",
        "--color-gray-900": "14 6 0",
        "--color-gray-800": "26 12 4",
        "--color-gray-700": "44 22 8",
        "--color-gray-600": "68 38 16",
        "--color-gray-500": "105 64 32",
        "--color-gray-400": "148 105 68",
        "--color-gray-300": "186 148 108",
        "--color-gray-200": "214 182 148",
        "--color-gray-100": "232 210 182",
        "--color-gray-50": "246 234 220",
    },
    sidebarOverrides: {
        "home": { icon: GiFlame, label: "Vongola HQ" },
        "schedule": { icon: GiAlarmClock, label: "Training Schedule" },
        "manga": { icon: LuBookOpen, label: "Vongola Files" },
        "lists": { icon: GiFist, label: "Guardian Registry" },
        "discover": { icon: GiBullseye, label: "Enemy Scouting" },
        "torrent-list": { icon: GiBullets, label: "Flame Cache" },
        "debrid": { icon: GiLightningBow, label: "Dying Will" },
        "unmatched": { icon: GiDeathSkull, label: "Unknown Family" },
        "enmasse": { icon: GiResize, label: "Family Deploy" },
        "scan-summaries": { icon: TbReportSearch, label: "Battle Reports" },
        "auto-downloader": { icon: LuRss, label: "Mafia Network" },
        "community": { icon: GiFlame, label: "Vongola Family" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Vongola Alerts" },
        "achievements": { icon: GiTrophy, label: "Boss Titles" },
        "milestones": { icon: LuFlag, label: "Flame Goals" },
        "theme-manager": { icon: GiPalette, label: "Flame Colors" },
        "extensions": { icon: BiExtension, label: "Box Weapon Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Vongola Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Flame Settings" },
    },
    achievementNames: {
        "a_first_episode": "No-Good Tsuna",
        "a_first_complete": "Vongola Tenth",
        "a_hundred_club": "Hundred Battles",
        "a_time_lord": "Mafia Veteran",
        "a_anime_collector": "Box Collection",
        "a_library_legend": "Vongola Archives",
        "a_binge_king": "Training Marathon",
        "a_no_sleep": "All-Night Training",
        "a_marathon_runner": "Dying Will",
        "a_speed_run": "X Burner",
        "a_completionist": "All Guardians",
        "a_mega_completionist": "Amano Master",
        "a_loyal_fan": "Tsuna's Family",
        "a_rewatcher": "Reborn Return",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Box Weapon Battle",
        "a_genre_adventure": "Future Arc",
        "a_genre_comedy": "Tsuna Fails",
        "a_genre_drama": "Byakuran Arc",
        "a_genre_fantasy": "Vongola World",
        "a_genre_horror": "Millefiore Terror",
        "a_genre_romance": "Kyoko's Friend",
        "a_genre_scifi": "Box Weapons",
        "a_genre_supernatural": "Dying Will Flame",
        "a_genre_psychological": "Tsuna Grows",
        "a_genre_mecha": "Nuts Box",
        "a_critic": "Flame Judge",
        "a_perfect_ten": "Vongola Gear",
        "a_harsh_critic": "Reborn Strict",
        "a_daily_streak": "Daily Training",
        "a_mega_streak": "Endless Dying Will",
        "a_year_long": "Year in Mafia",
        "a_iron_will": "Dying Will",
        "a_hidden_gem": "Hidden Flame",
        "a_cult_classic": "Amano Classic",
        "a_classic_connoisseur": "2004 Fan",
        "a_new_years_resolution": "New Battle",
        "a_christmas_special": "Family Christmas",
        "a_meta_tier_max": "Vongola Tenth",
        "a_meta_completionist": "All Flames",
        "a_sequel_chain": "Future Arc",
        "a_zero_to_hero": "No-Good to Boss",
        "a_night_owl": "Night Training",
        "a_early_bird": "Dawn Lesson",
        "m_first_chapter": "First Lesson",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Flame Marathon",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Reborn Expert",
        "m_loyal_reader": "Family Reader",
        "m_rereader": "Vongola Return",
        "m_genre_action": "Battle Chapter",
        "m_genre_adventure": "Journey Chapter",
        "m_genre_romance": "Heart Chapter",
        "m_genre_fantasy": "Mafia World",
        "m_genre_horror": "Dark Chapter",
        "m_genre_drama": "Sacrifice Chapter",
        "m_genre_scifi": "Box Chapter",
        "m_genre_supernatural": "Flame Chapter",
        "m_genre_psychological": "Growth Chapter",
        "m_critic": "Vongola Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Dying Will Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Boss Resolve",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Classic Manga",
        "m_mangaka_lover": "Amano Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Vongola Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Flame Art",
        "m_manga_to_anime": "Manga Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060200",
        primary: "#d65000",
        secondary: "#883200",
        accent: "#80a8d8",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/katekyo-hitman-reborn.jpg",
    particleColor: "#f07800",
    backgroundDim: 0.38,
    backgroundBlur: 20,
    particleTypes: {
        dying_will_flames: { label: "Dying Will Flames", maxCount: 15, defaultEnabled: true, defaultIntensity: 70 },
        mafia_sparks: { label: "Mafia Sparks", maxCount: 10, defaultEnabled: true, defaultIntensity: 55 },
    },
    milestoneNames: {
    "7": "Novice Rank 1",
    "13": "Novice Level 2",
    "20": "Novice Tier 3",
    "27": "Novice Class 4",
    "33": "Novice Grade 5",
    "40": "Novice Position 6",
    "47": "Novice Status 7",
    "53": "Novice Role 8",
    "60": "Novice Title 9",
    "67": "Novice Authority 10",
    "73": "Beginner Rank 11",
    "80": "Beginner Level 12",
    "87": "Beginner Tier 13",
    "93": "Beginner Class 14",
    "100": "Beginner Grade 15",
    "107": "Beginner Position 16",
    "113": "Beginner Status 17",
    "120": "Beginner Role 18",
    "127": "Beginner Title 19",
    "133": "Student Authority 20",
    "140": "Student Rank 21",
    "147": "Student Level 22",
    "153": "Student Tier 23",
    "160": "Student Class 24",
    "167": "Student Grade 25",
    "173": "Student Position 26",
    "180": "Student Status 27",
    "187": "Student Role 28",
    "193": "Student Title 29",
    "200": "Learner Authority 30",
    "207": "Learner Rank 31",
    "213": "Learner Level 32",
    "220": "Learner Tier 33",
    "227": "Learner Class 34",
    "233": "Learner Grade 35",
    "240": "Learner Position 36",
    "247": "Learner Status 37",
    "253": "Learner Role 38",
    "260": "Adept Title 39",
    "267": "Adept Authority 40",
    "273": "Adept Rank 41",
    "280": "Adept Level 42",
    "287": "Adept Tier 43",
    "293": "Adept Class 44",
    "300": "Adept Grade 45",
    "307": "Adept Position 46",
    "313": "Adept Status 47",
    "320": "Expert Role 48",
    "327": "Expert Title 49",
    "333": "Expert Authority 50",
    "340": "Expert Rank 51",
    "347": "Expert Level 52",
    "353": "Expert Tier 53",
    "360": "Expert Class 54",
    "367": "Expert Grade 55",
    "373": "Expert Position 56",
    "380": "Expert Status 57",
    "387": "Master Role 58",
    "393": "Master Title 59",
    "400": "Master Authority 60",
    "407": "Master Rank 61",
    "413": "Master Level 62",
    "420": "Master Tier 63",
    "427": "Master Class 64",
    "433": "Master Grade 65",
    "440": "Master Position 66",
    "447": "Grandmaster Status 67",
    "453": "Grandmaster Role 68",
    "460": "Grandmaster Title 69",
    "467": "Grandmaster Authority 70",
    "473": "Grandmaster Rank 71",
    "480": "Grandmaster Level 72",
    "487": "Grandmaster Tier 73",
    "493": "Grandmaster Class 74",
    "500": "Grandmaster Grade 75",
    "507": "Sage Position 76",
    "513": "Sage Status 77",
    "520": "Sage Role 78",
    "527": "Sage Title 79",
    "533": "Sage Authority 80",
    "540": "Sage Rank 81",
    "547": "Sage Level 82",
    "553": "Sage Tier 83",
    "560": "Sage Class 84",
    "567": "Sage Grade 85",
    "573": "Legend Position 86",
    "580": "Legend Status 87",
    "587": "Legend Role 88",
    "593": "Legend Title 89",
    "600": "Legend Authority 90",
    "607": "Legend Rank 91",
    "613": "Legend Level 92",
    "620": "Legend Tier 93",
    "627": "Legend Class 94",
    "633": "Mythical Grade 95",
    "640": "Mythical Position 96",
    "647": "Mythical Status 97",
    "653": "Mythical Role 98",
    "660": "Mythical Title 99",
    "667": "Mythical Authority 100",
    "673": "Mythical Rank 101",
    "680": "Mythical Level 102",
    "687": "Mythical Tier 103",
    "693": "Mythical Class 104",
    "700": "Godly Grade 105",
    "707": "Godly Position 106",
    "713": "Godly Status 107",
    "720": "Godly Role 108",
    "727": "Godly Title 109",
    "733": "Godly Authority 110",
    "740": "Godly Rank 111",
    "747": "Godly Level 112",
    "753": "Godly Tier 113",
    "760": "Supreme Class 114",
    "767": "Supreme Grade 115",
    "773": "Supreme Position 116",
    "780": "Supreme Status 117",
    "787": "Supreme Role 118",
    "793": "Supreme Title 119",
    "800": "Supreme Authority 120",
    "807": "Supreme Rank 121",
    "813": "Supreme Level 122",
    "820": "Infinite Tier 123",
    "827": "Infinite Class 124",
    "833": "Infinite Grade 125",
    "840": "Infinite Position 126",
    "847": "Infinite Status 127",
    "853": "Infinite Role 128",
    "860": "Infinite Title 129",
    "867": "Infinite Authority 130",
    "873": "Infinite Rank 131",
    "880": "Infinite Level 132",
    "887": "Eternal Tier 133",
    "893": "Eternal Class 134",
    "900": "Eternal Grade 135",
    "907": "Eternal Position 136",
    "913": "Eternal Status 137",
    "920": "Eternal Role 138",
    "927": "Eternal Title 139",
    "933": "Eternal Authority 140",
    "940": "Eternal Rank 141",
    "947": "Transcendent Level 142",
    "953": "Transcendent Tier 143",
    "960": "Transcendent Class 144",
    "967": "Transcendent Grade 145",
    "973": "Transcendent Position 146",
    "980": "Transcendent Status 147",
    "987": "Transcendent Role 148",
    "993": "Transcendent Title 149",
    "1000": "Transcendent Authority 150"
},
}
