import { AnimeThemeConfig } from "./types"
import { GiBroom, GiCat, GiMagicPortal, GiCrystalBall, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiWindmill } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const kikiDeliveryServiceTheme: AnimeThemeConfig = {
    id: "kiki-delivery-service",
    displayName: "Kiki's Delivery Service",
    description: "Young witch Kiki sets off alone to prove herself, setting up a delivery service in a seaside city with only her black cat Jiji. A story of growing up and finding your own magic.",
    fontFamily: "'Patrick Hand', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Patrick+Hand&display=swap",
    cssVars: {
        "--color-brand-200": "175 130 230",
        "--color-brand-300": "145 90 210",
        "--color-brand-400": "112 55 188",
        "--color-brand-500": "80 25 165",
        "--color-brand-600": "60 16 136",
        "--color-brand-700": "44 10 106",
        "--color-brand-800": "30 6 76",
        "--color-brand-900": "18 3 46",
        "--color-brand-950": "10 1 26",
        "--brand": "80 25 165",
        "--background": "#020106",
        "--paper": "#06040e",
        "--color-gray-950": "2 1 6",
        "--color-gray-900": "6 4 12",
        "--color-gray-800": "12 8 22",
        "--color-gray-700": "22 16 38",
        "--color-gray-600": "36 26 60",
        "--color-gray-500": "58 44 95",
        "--color-gray-400": "90 72 135",
        "--color-gray-300": "128 108 170",
        "--color-gray-200": "164 148 200",
        "--color-gray-100": "200 188 225",
        "--color-gray-50": "230 224 242",
    },
    sidebarOverrides: {
        "home": { icon: GiBroom, label: "Witch's Home" },
        "schedule": { icon: GiAlarmClock, label: "Delivery Schedule" },
        "manga": { icon: LuBookOpen, label: "Witch's Journal" },
        "lists": { icon: GiCat, label: "Jiji's List" },
        "discover": { icon: GiBullseye, label: "City Explore" },
        "torrent-list": { icon: GiWindmill, label: "Delivery Cache" },
        "debrid": { icon: GiCrystalBall, label: "Magic Store" },
        "unmatched": { icon: GiMagicPortal, label: "Lost Packages" },
        "enmasse": { icon: GiResize, label: "Batch Delivery" },
        "scan-summaries": { icon: TbReportSearch, label: "Delivery Logs" },
        "auto-downloader": { icon: LuRss, label: "Customer Calls" },
        "community": { icon: GiBroom, label: "Witch Network" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Delivery Bells" },
        "achievements": { icon: GiTrophy, label: "Witch Badges" },
        "milestones": { icon: LuFlag, label: "Delivery Goals" },
        "theme-manager": { icon: GiPalette, label: "Witch Colors" },
        "extensions": { icon: BiExtension, label: "Broom Upgrades" },
        "sync": { icon: IoCloudOfflineOutline, label: "Witch Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Magic Settings" },
    },
    achievementNames: {
        "a_first_episode": "First Flight",
        "a_first_complete": "Delivery Done",
        "a_hundred_club": "Hundred Deliveries",
        "a_time_lord": "Seasoned Witch",
        "a_anime_collector": "Magic Cache",
        "a_library_legend": "Witch's Archive",
        "a_binge_king": "Delivery Marathon",
        "a_no_sleep": "All-Night Delivery",
        "a_marathon_runner": "Broom Marathon",
        "a_speed_run": "Quick Delivery",
        "a_completionist": "All Delivered",
        "a_mega_completionist": "Miyazaki Expert",
        "a_loyal_fan": "Kiki's Friend",
        "a_rewatcher": "Sky Return",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Blimp Rescue",
        "a_genre_adventure": "City Adventure",
        "a_genre_comedy": "Jiji's Jokes",
        "a_genre_drama": "Lost Magic",
        "a_genre_fantasy": "Witch's World",
        "a_genre_horror": "Magic Lost",
        "a_genre_romance": "First Crush",
        "a_genre_scifi": "Steam Machines",
        "a_genre_supernatural": "Witch Power",
        "a_genre_psychological": "Growing Pains",
        "a_genre_mecha": "Blimp Tech",
        "a_critic": "Delivery Judge",
        "a_perfect_ten": "Perfect Delivery",
        "a_harsh_critic": "Strict Review",
        "a_daily_streak": "Daily Delivery",
        "a_mega_streak": "Endless Flights",
        "a_year_long": "Year of Witching",
        "a_iron_will": "Kiki's Courage",
        "a_hidden_gem": "Hidden Package",
        "a_cult_classic": "Miyazaki Classic",
        "a_classic_connoisseur": "89 Classic Fan",
        "a_new_years_resolution": "New Year Flight",
        "a_christmas_special": "Holiday Delivery",
        "a_meta_tier_max": "Master Witch",
        "a_meta_completionist": "Full Collection",
        "a_sequel_chain": "Ghibli Journey",
        "a_zero_to_hero": "Apprentice to Pro",
        "a_night_owl": "Moonlit Flight",
        "a_early_bird": "Dawn Delivery",
        "m_first_chapter": "First Package",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Delivery Marathon",
        "m_completionist": "Full Journey",
        "m_mega_completionist": "Ghibli Expert",
        "m_loyal_reader": "Kiki's Fan",
        "m_rereader": "Return Delivery",
        "m_genre_action": "Action Chapter",
        "m_genre_adventure": "Sky Chapter",
        "m_genre_romance": "Crush Chapter",
        "m_genre_fantasy": "Witch Chapter",
        "m_genre_horror": "Dark Chapter",
        "m_genre_drama": "Growth Chapter",
        "m_genre_scifi": "Steam Chapter",
        "m_genre_supernatural": "Magic Chapter",
        "m_genre_psychological": "Heart Chapter",
        "m_critic": "Ghibli Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Unbroken Flights",
        "m_year_long": "Year Reading",
        "m_iron_will": "Witch Resolve",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Classic Ghibli",
        "m_mangaka_lover": "Miyazaki Fan",
        "m_source_material_fan": "Novel First",
        "m_meta_tier_max": "Sky Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Sky Art",
        "m_manga_to_anime": "Novel Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#020106",
        primary: "#5019a5",
        secondary: "#3c1088",
        accent: "#e8a040",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/kiki-delivery-service.jpg",
    particleColor: "#9060e0",
    backgroundDim: 0.3,
    backgroundBlur: 15,
    particleTypes: {
        stars: { label: "Night Stars", maxCount: 20, defaultEnabled: true, defaultIntensity: 55 },
        sparks: { label: "Magic Sparks", maxCount: 15, defaultEnabled: true, defaultIntensity: 50 },
    },
    milestoneNames: {
        1: "Witch in Training",
        5: "Kiki",
        15: "Delivery Girl",
        30: "City Witch",
        50: "Osono's Friend",
        75: "Sky Master",
        100: "True Witch",
    },
}
