import { AnimeThemeConfig } from "./types"
import { GiFlowerEmblem, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiCrystalBall, GiStarSwirl, GiSpellBook } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const kimiNiTodokeTheme: AnimeThemeConfig = {
    id: "kimi-ni-todoke",
    displayName: "Kimi ni Todoke",
    description: "Misunderstood Sawako Kuronuma, nicknamed Sadako for her resemblance to a horror film ghost, only wants real friends. When popular Shouta Kazehaya speaks to her, her world slowly begins to open.",
    cssVars: {
        "--color-brand-200": "255 195 215",
        "--color-brand-300": "248 148 178",
        "--color-brand-400": "232 98 138",
        "--color-brand-500": "205 55 98",
        "--color-brand-600": "162 25 65",
        "--color-brand-700": "115 8 38",
        "--color-brand-800": "72 2 18",
        "--color-brand-900": "38 0 8",
        "--color-brand-950": "16 0 3",
        "--brand": "205 55 98",
        "--background": "#060001",
        "--paper": "#0e0003",
        "--color-gray-950": "6 0 1",
        "--color-gray-900": "16 2 5",
        "--color-gray-800": "30 5 12",
        "--color-gray-700": "52 10 22",
        "--color-gray-600": "82 18 38",
        "--color-gray-500": "122 35 62",
        "--color-gray-400": "165 68 98",
        "--color-gray-300": "205 110 142",
        "--color-gray-200": "235 155 182",
        "--color-gray-100": "250 198 218",
        "--color-gray-50": "255 235 245",
    },
    sidebarOverrides: {
        "home": { icon: GiFlowerEmblem, label: "Sawako's World" },
        "schedule": { icon: GiAlarmClock, label: "Class Schedule" },
        "manga": { icon: LuBookOpen, label: "Diary" },
        "lists": { icon: GiScrollUnfurled, label: "Friendship List" },
        "discover": { icon: GiBullseye, label: "New Friends" },
        "torrent-list": { icon: GiStarSwirl, label: "Memory Cache" },
        "debrid": { icon: GiHeartKey, label: "Heart Vault" },
        "unmatched": { icon: GiCrystalBall, label: "Unresolved Feelings" },
        "enmasse": { icon: GiResize, label: "Class Reunion" },
        "scan-summaries": { icon: TbReportSearch, label: "Class Reports" },
        "auto-downloader": { icon: LuRss, label: "Friendship Feed" },
        "community": { icon: GiSpellBook, label: "Sawako Circle" },
        "achievements": { icon: GiTrophyCup, label: "Friendship Trophies" },
        "milestones": { icon: LuFlag, label: "Heartfelt Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Gentle Alerts" },
        "theme-manager": { icon: GiPalette, label: "Soft Colors" },
        "extensions": { icon: BiExtension, label: "Friendship Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Heart Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Sawako Config" },
    },
    achievementNames: {
        "a_first_episode": "First Smile",
        "a_first_complete": "First Real Friend",
        "a_hundred_club": "Hundred Warm Moments",
        "a_binge_king": "Kimi ni Todoke Marathon",
        "a_completionist": "Full Circle of Friends",
        "a_mega_completionist": "Reaching Your Heart",
        "a_loyal_fan": "Gentle Fan",
        "a_zero_to_hero": "Ghost to Sunshine",
        "m_first_chapter": "First Blush",
        "m_completionist": "Full Manga Archive",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060001",
        primary: "#cd3762",
        secondary: "#8888aa",
        accent: "#ffd8e8",
    },
    particleColor: "#e070a0",
    backgroundDim: 0.28,
    backgroundBlur: 22,
    milestoneNames: {
        1: "Misunderstood Newcomer",
        5: "First Spoken Word",
        15: "Classroom Smile",
        30: "Real Friendship",
        50: "Love Acknowledged",
        75: "Happiness Found",
        100: "Reaching Your Heart",
    },
}
