import { AnimeThemeConfig } from "./types"
import { GiBasketballBall, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiRunningShoe, GiHeartKey, GiAnvilImpact, GiPunch } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const kurokoNoBasukeTheme: AnimeThemeConfig = {
    id: "kuroko-no-basuke",
    displayName: "Kuroko's Basketball",
    description: "The phantom sixth man of the Generation of Miracles, Tetsuya Kuroko uses his misdirection to help Seirin High defeat his former teammates and claim the top of Japanese high school basketball.",
    cssVars: {
        "--color-brand-200": "150 220 240",
        "--color-brand-300": "80 190 220",
        "--color-brand-400": "20 155 195",
        "--color-brand-500": "0 120 165",
        "--color-brand-600": "0 88 128",
        "--color-brand-700": "0 58 92",
        "--color-brand-800": "0 32 60",
        "--color-brand-900": "0 14 36",
        "--color-brand-950": "0 4 18",
        "--brand": "0 120 165",
        "--background": "#00030e",
        "--paper": "#000614",
        "--color-gray-950": "0 3 14",
        "--color-gray-900": "0 8 26",
        "--color-gray-800": "2 18 46",
        "--color-gray-700": "5 34 70",
        "--color-gray-600": "10 58 102",
        "--color-gray-500": "22 95 138",
        "--color-gray-400": "48 138 175",
        "--color-gray-300": "88 178 208",
        "--color-gray-200": "138 210 232",
        "--color-gray-100": "188 235 248",
        "--color-gray-50": "228 248 255",
    },
    sidebarOverrides: {
        "home": { icon: GiBasketballBall, label: "Seirin Gym" },
        "schedule": { icon: GiAlarmClock, label: "Game Schedule" },
        "manga": { icon: LuBookOpen, label: "Play Archive" },
        "lists": { icon: GiScrollUnfurled, label: "Team Roster" },
        "discover": { icon: GiBullseye, label: "Scouting" },
        "torrent-list": { icon: GiAnvilImpact, label: "Equipment Room" },
        "debrid": { icon: GiHeartKey, label: "Team Vault" },
        "unmatched": { icon: GiRunningShoe, label: "Unscreened Players" },
        "enmasse": { icon: GiResize, label: "Tournament Bracket" },
        "scan-summaries": { icon: TbReportSearch, label: "Game Reports" },
        "auto-downloader": { icon: LuRss, label: "Match Alerts" },
        "community": { icon: GiPunch, label: "Fan Circle" },
        "achievements": { icon: GiTrophyCup, label: "Championship Trophies" },
        "milestones": { icon: LuFlag, label: "Team Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Game Alerts" },
        "theme-manager": { icon: GiPalette, label: "Court Colors" },
        "extensions": { icon: BiExtension, label: "Team Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Team Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Coach Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Pass",
        "a_episode_counter": "Seirin High Mark",
        "a_episode_titan": "Game Relic",
        "a_hours_invested": "Generation Proof",
        "a_time_lord": "Seirin Gym Decree",
        "a_anime_collector": "Game Alerts Catalogue",
        "a_library_legend": "Player Library",
        "a_first_complete": "Game Won",
        "a_hundred_club": "Hundred Points Scored",
        "a_first_day": "Marathon Seal",
        "a_first_rating": "Basketball Marathon Appraisal",
        "a_ten_thousand_min": "Game Won Standard",
        "a_season_veteran": "Play Archive Library",
        "a_year_explorer": "Phantom Map",
        "a_century_watcher": "Team Ledger",
        "a_five_hundred_eps": "Archive Dominion",
        "a_thousand_eps": "Scouting Record",
        "a_watching_ten": "Generation Miracles Acclaim",
        "a_ptw_hoarder": "Generation Miracles Library",
        "a_dropped_honesty": "Play Archive Summit",
        "a_five_thousand_eps": "Generation Warrant",
        "a_ten_completed": "Team Roster Afterglow",
        "a_fifty_completed": "Scored Ascension",
        "a_five_hundred_completed": "Tetsuya Kuroko Clear",
        "a_mean_score_tracker": "Scouting Verdict",
        "a_unique_studios": "Phantom Collection",
        "a_days_spent_watching": "Player Champion Dominion",
        "a_all_status": "Game Alerts Testament",
        "a_first_favorite": "Seirin Gym Cabinet",
        "a_favorites_collector": "Team Roster Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Generation Drive",
        "a_marathon_runner": "Phantom Gauntlet",
        "a_weekend_warrior": "Basketball Marathon Ordeal",
        "a_non_stop": "Loyal Fan Fever",
        "a_one_more_episode": "Basketball Marathon Mantle",
        "a_speed_run": "Play Vigil",
        "a_double_feature": "Journey Crown",
        "a_triple_threat": "Seirin Gym Record",
        "a_five_a_day": "Play Archive Accord",
        "a_back_to_back": "Team Surge",
        "a_seasonal_binge": "Championship Cascade",
        "a_cour_crusher": "Archive Ordeal",
        "a_half_day_watch": "Japanese Crown",
        "a_full_day_watch": "Tournament Bracket Pinnacle",
        "a_power_weekend": "Team Run",
        "a_binge_king": "Basketball Marathon",
        "a_no_sleep": "Play Sleepless",
        "a_entire_season": "Team Library",
        "a_seven_day_challenge": "Loyal Fan Mark",
        "a_hundred_day_binge": "Player Surge",
        "a_genre_binge": "Basketball Binge",
        "a_studio_binge": "Tournament Bracket Fever",
        "a_season_sweep": "Basketball Marathon Codex",
        "a_forty_eight_hour": "Basketball Overture",
        "a_ep_counter_day": "Team Roster Aegis",
        "a_multi_series_binge": "Coach Streak",
        "a_midnight_binge": "Championship Midnight",
        "a_new_year_binge": "Match Alerts Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Game Alerts Action",
        "a_genre_adventure": "Basketball Marathon Adventure",
        "a_genre_comedy": "Points Scored Comedy",
        "a_genre_drama": "Tetsuya Kuroko Drama",
        "a_genre_fantasy": "Tournament Bracket Fantasy",
        "a_genre_horror": "Championship Journey Horror",
        "a_genre_mystery": "Basketball Mystery",
        "a_genre_romance": "Scouting Romance",
        "a_genre_scifi": "Court Sci-Fi",
        "a_genre_sol": "Pass Slice",
        "a_genre_sports": "Kuroko's Basketball Sports",
        "a_genre_supernatural": "Loyal Fan Supernatural",
        "a_genre_thriller": "Player Champion Thriller",
        "a_genre_mecha": "Championship Mecha",
        "a_genre_music": "Team Music",
        "a_genre_psychological": "Team Psychological",
        "a_genre_ecchi": "Loyal Ecchi",
        "a_genre_mahou_shoujo": "Phantom Magic Shoujo",
        "a_tag_isekai": "Basketball Isekai",
        "a_tag_harem": "Equipment Room Harem",
        "a_tag_bl": "Team Roster Bl",
        "a_tag_gl": "Game Alerts Gl",
        "a_tag_historical": "Game Won Historical",
        "a_tag_military": "Court Archive Military",
        "a_tag_school": "Fan Circle School",
        "a_tag_martial_arts": "Loyal Martial Arts",
        "a_tag_vampire": "Scouting Vampire",
        "a_tag_samurai": "Phantom Player Samurai",
        "a_tag_space": "Points Space",
        "a_tag_parody": "Champion Parody",
        "a_tag_idol": "Basketball Idol",
        "a_tag_post_apocalyptic": "Player Post Apocalyptic",
        "a_tag_cyberpunk": "Japanese Cyberpunk",
        "a_tag_shounen": "Player Shounen",
        "a_tag_seinen": "Team Seinen",
        "a_tag_shoujo": "Team Shoujo",
        "a_tag_josei": "Team Roster Josei",
        "a_tag_survival": "Points Scored Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "Championship Journey",
        "a_mega_completionist": "Generation of Miracles",
        "a_completion_rate_50": "Phantom Return",
        "a_completion_rate_75": "Archive Crown",
        "a_completion_rate_90": "Team Roster Resolution",
        "a_no_drop": "Phantom Decree",
        "a_long_runner_complete": "Unscreened Players Clear",
        "a_sequel_chain": "Generation Miracles Insignia",
        "a_clean_list": "Basketball Marathon Relic",
        "a_from_ptw": "Court Index",
        "a_rewatch_master": "Kuroko's Basketball Return",
        "a_short_complete": "Match Alerts Endgame",
        "a_same_day_start_finish": "Equipment Room Pinnacle",
        "a_revival": "Miracles Insignia",
        "a_zero_to_hero": "Phantom Player to Champion",
        "a_five_genre_complete": "Loyal A Five Genre Complete",
        "a_full_franchise": "Tetsuya Kuroko Chronicle",
        "a_batch_complete": "Scored Crown",
        "a_paused_to_done": "Basketball Aegis",
        "a_completion_spree": "Journey Triumph",
        "a_multi_rewatch": "Equipment Room Triumph",
        "a_dropped_recovery": "Loyal Fan Conquest",
        "a_ten_perfect_scores": "Fan Circle Acclaim",
        "a_seasonal_clear": "Court Archive Codex",
        "a_complete_genre_span": "Court A Complete Genre Span",
        "a_monthly_completions": "Team Roster Monthly",
        "a_yearly_completions": "Team Vault Epilogue",
        "a_rapid_complete": "Seirin High Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Fan",
        "a_studio_devotee": "Points Scored Treasury",
        "a_rewatcher": "Fan Circle Closure",
        "a_triple_rewatch": "Play Coda",
        "a_annual_tradition": "Generation Proof Proof",
        "a_director_fan": "Game Alerts Trial",
        "a_voice_actor_fan": "Championship Journey Crown",
        "a_ost_lover": "Generation Miracles Seal",
        "a_source_reader": "Points Cabinet",
        "a_waiting_weekly": "Kuroko's Basketball Clock",
        "a_childhood_revisit": "Marathon Seal Seal",
        "a_saga_tracker": "Scouting Standard",
        "a_genre_loyalty": "Loyal Loyalty",
        "a_decade_watcher": "Team Roster Banner",
        "a_adaptation_hunter": "Court Trial",
        "a_original_anime_fan": "Basketball Marathon Testament",
        "a_long_commitment": "Match Alerts Mark",
        "a_perfect_attendance": "Player Standard",
        "a_favorite_studio_5": "Unscreened Players Library",
        "a_complete_catalog": "Phantom Player Seal",
        "a_franchise_collector": "Generation Miracles Archive",
        "a_airing_follower": "Tetsuya Kuroko Signal",
        "a_genre_master": "Championship Master",
        "a_staff_follower": "Generation Miracles Oath",
        "a_multi_season_fan": "Marathon Hoard",
        "a_format_diversity": "Phantom Cache",
        "a_year_dedication": "Court Archive Tenure",
        "a_season_dedication": "Archive Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Basketball Explorer",
        "a_studio_hopper": "Phantom Collection Collection",
        "a_tag_explorer": "Archive Explorer",
        "a_decade_hopper": "Team Chronicle",
        "a_hidden_gem": "Tournament Bracket Warrant",
        "a_popular_taste": "Team Roster Decree",
        "a_retro_appreciator": "Points Aegis",
        "a_modern_viewer": "Journey Pinnacle",
        "a_cross_demographic": "Pass Pinnacle",
        "a_underdog_fan": "Team Vault Trial",
        "a_variety_week": "Tetsuya Kuroko Horizon",
        "a_foreign_cinema": "Champion Expedition",
        "a_classic_connoisseur": "Marathon Glimpse",
        "a_every_season": "Coach Archive",
        "a_award_winner": "Play Archive Insignia",
        "a_niche_explorer": "Tetsuya Kuroko Horizon Horizon",
        "a_global_anime": "Loyal Fan Crown",
        "a_cult_classic": "Phantom Classic",
        "a_random_pick": "Play Decree",
        "a_new_genre_month": "Marathon A New Genre Month",
        "a_seasonal_completionist": "Game Won Summit",
        "a_unpopular_opinion": "Basketball Standard",
        "a_top_rated_viewer": "Tetsuya Kuroko Seal",
        "a_source_variety": "Champion Storehouse",
        "a_low_score_brave": "Loyal Fan Measure",
        "a_upcoming_watcher": "Team Seal",
        "a_short_series_explorer": "Court Archive Expedition",
        "a_long_series_explorer": "Match Alerts Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Fan Circle Insignia",
        "a_early_bird": "Play Banner",
        "a_lunch_break": "Court Archive Trial",
        "a_golden_hour": "Champion Tenure",
        "a_four_am_club": "Tournament Bracket Gathering",
        "a_witching_hour": "Court Tenure",
        "a_new_year_watch": "Basketball Marathon Season",
        "a_midnight_premiere": "Seirin High Devotion",
        "a_all_hours": "Game Won Seal",
        "a_dawn_warrior": "Points Scored Aegis",
        "a_afternoon_delight": "Tournament Bracket Proof",
        "a_prime_time": "Generation Miracles Insignia Insignia",
        "a_workday_watcher": "Generation Pinnacle",
        "a_sunday_marathon": "Fan Circle Momentum",
        "a_rainy_day": "Player Champion Relic",
        "a_morning_routine": "Unscreened Players Promise",
        "a_night_shift": "Team Roster Aegis Aegis",
        "a_twilight_zone": "Player Ledger",
        "a_seasonal_premier": "Points Scored Cabinet",
        "a_clock_collector": "Seirin High Repository",
        "a_weekend_binge_hours": "Player Streak",
        "a_late_night_regular": "Court Archive Dominion",
        "a_sunrise_watcher": "Player Champion Relic Relic",
        "a_holiday_watcher": "Player Pact",
        "a_every_day_of_week": "Coach Ledger",
        "a_monthly_hours": "Team Roster Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Seirin Gym Record Record",
        "a_party_host": "Match Alerts Mantle",
        "a_social_butterfly": "Points Scored Company",
        "a_group_binge": "Seirin Gym Sprint",
        "a_party_regular": "Team Chronicle Chronicle",
        "a_sync_viewer": "Loyal Standard",
        "a_commentator": "Points Scored Record",
        "a_party_marathon": "Kuroko's Basketball Vigil",
        "a_full_house": "Champion Trial",
        "a_community_pillar": "Scored Alliance",
        "a_watch_party_streak": "Seirin Gym Vigil",
        "a_diverse_party": "Miracles Seal",
        "a_late_night_party": "Champion Testament",
        "a_party_veteran": "Game Alerts Testament Testament",
        "a_genre_party": "Team Vault Party",
        "a_weekly_party": "Journey Calendar",
        "a_silent_viewer": "Game Mantle",
        "a_recommendation_giver": "Play Archive Network",
        "a_party_completionist": "Championship Trophies Coda",
        "a_social_scorer": "Game Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Equipment Room Proof",
        "a_fibonacci": "Scored Dominion",
        "a_palindrome_day": "Championship Relic",
        "a_binary_day": "Equipment Room Mark",
        "a_full_moon": "Team Insignia",
        "a_leap_year": "Pass Devotion",
        "a_time_traveler": "Basketball Record",
        "a_genre_clash": "Play Clash",
        "a_triple_seven": "Game Testament",
        "a_thousand_complete": "Champion Epilogue",
        "a_pi_episodes": "Tournament Bracket Crown",
        "a_synchronicity": "Team Vault Anchor",
        "a_world_record": "Tournament Bracket Warrant Warrant",
        "a_nice": "Miracles Chronicle",
        "a_power_level": "Scored Testament",
        "a_answer_42": "Points Scored Standard",
        "a_square_number": "Championship Trophies Decree",
        "a_prime_count": "Team Vault Warrant",
        "a_matching_date": "Court Archive Mantle",
        "a_century_episode": "Loyal Fan Mark Mark",
        "a_double_digits": "Game Testament Testament",
        "a_one_two_three": "Journey Crown Crown",
        "a_lucky_seven": "Marathon Decree",
        "a_all_tens": "Tournament Bracket Criterion",
        "a_exact_hundred_eps": "Championship Trophies Standard",
        "a_year_match_count": "Scouting Clock",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Marathon Ledger",
        "a_movie_buff": "Tournament Bracket Mark",
        "a_ova_hunter": "Play Standard",
        "a_ona_explorer": "Game Alerts Secret",
        "a_special_watcher": "Court Relic",
        "a_short_king": "Generation Crown",
        "a_variety_pack": "Seirin High Inquiry",
        "a_film_festival": "Tetsuya Kuroko Chronicle Chronicle",
        "a_music_video": "Marathon Chronicle",
        "a_tv_short": "Basketball Record Record",
        "a_movie_marathon": "Play Gauntlet",
        "a_double_length": "Tournament Bracket Crown Crown",
        "a_anthology": "Championship Trophies Aegis",
        "a_mini_series": "Play Decree Decree",
        "a_theatrical": "Miracles Accord",
        "a_format_master": "Championship Journey Vault",
        "a_long_movie": "Play Archive Insignia Insignia",
        "a_back_catalog": "Championship Trophies Standard Standard",
        "a_cm_watcher": "Play Aegis",
        "a_pv_collector": "Champion Storehouse Storehouse",
        "a_format_balance": "Seirin High Vault",
        "a_episodic_master": "Points Standard",
        "a_sequel_movie": "Championship Journey Pinnacle",
        "a_recap_watcher": "Court Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Pass Daily",
        "a_mega_streak": "Basketball Streak",
        "a_weekly_warrior": "Game Season",
        "a_monthly_watcher": "Tournament Bracket Calendar",
        "a_comeback": "Team Roster Decree Decree",
        "a_weekend_streak": "Journey Passage",
        "a_no_zero_days": "Championship Journey Warrant",
        "a_iron_will": "Generation Miracles Seal Seal",
        "a_habit_formed": "Championship Journey Warrant Warrant",
        "a_consistent_pace": "Seirin High Measure",
        "a_year_long": "Game Alerts Season",
        "a_double_streak": "Game Watch",
        "a_streak_recovery": "Championship Season",
        "a_daily_minimum": "Japanese Focus",
        "a_winter_streak": "Basketball Marathon Watch",
        "a_summer_streak": "Court Archive Resolve",
        "a_morning_streak": "Phantom Player Clock",
        "a_night_streak": "Unscreened Players Constancy",
        "a_unbreakable": "Match Alerts Proof",
        "a_eternal_flame": "Scouting Standard Standard",
        "a_completion_streak": "Phantom Player Return",
        "a_rating_streak": "Championship Balance",
        "a_multi_ep_streak": "Journey Ritual",
        "a_genre_streak": "Championship Streak",
        "a_studio_streak": "Points Cabinet Cabinet",
        "a_perfect_week": "Championship Trophies Ledger",

        // ── ANIME SCORING ──
        "a_critic": "Loyal Fan Scrutiny",
        "a_perfect_ten": "Points Audit",
        "a_harsh_critic": "Coach Gauge",
        "a_fair_judge": "Basketball Marathon Balance",
        "a_generous_spirit": "Loyal Fan Pinnacle",
        "a_score_all": "Journey Criterion",
        "a_wide_range": "Marathon Ledger Ledger",
        "a_controversial": "Journey Relic",
        "a_consistent_scorer": "Points Verdict",
        "a_score_sniper": "Journey Score",
        "a_evolving_taste": "Champion Testament Testament",
        "a_bell_curve": "Fan Circle Insignia Insignia",
        "a_picky_watcher": "Fan Circle Seal",
        "a_100_rated": "Coach Banner",
        "a_500_rated": "Loyal Pinnacle",
        "a_mediocre_majority": "Champion Canon",
        "a_rating_spree": "Basketball Review",
        "a_score_variance": "Seirin High Score",
        "a_masterpiece_hunter": "Basketball Banner",
        "a_contrarian": "Championship Trophies Record",
        "a_optimist": "Team Vault Crown",
        "a_score_distributor": "Game Appraisal",
        "a_genre_critic": "Japanese Critic",
        "a_mean_above_8": "Loyal Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "Archive Resolve",
        "a_valentines_weeb": "Unscreened Players Vow",
        "a_pi_day": "Game Alerts Trial Trial",
        "a_april_fools": "Generation Devotion",
        "a_international_anime_day": "Pass Pinnacle Pinnacle",
        "a_star_wars_day": "Marathon Chronicle Chronicle",
        "a_summer_solstice": "Japanese Calendar",
        "a_tanabata": "Tournament Bracket Focus",
        "a_friday_13th": "Championship Trophies Ledger Ledger",
        "a_halloween_spirit": "Game Won Vow",
        "a_thanksgiving_binge": "Marathon Run",
        "a_christmas_special": "Team Vault Season",
        "a_new_years_eve": "Generation Pilgrimage",
        "a_birthday_watch": "Player Vow",
        "a_holiday_marathon": "Championship Trophies Overture",
        "a_independence_day": "Points Banner",
        "a_culture_day": "Court Archive Pinnacle",
        "a_spring_equinox": "Scouting Decree",
        "a_earth_day": "Match Alerts Mantle Mantle",
        "a_labor_day": "Team Vault Warrant Warrant",
        "a_winter_solstice": "Equipment Room Pilgrimage",
        "a_anime_birthday": "Equipment Room Birthday",
        "a_every_holiday": "Court Archive Resolve Resolve",
        "a_consecutive_holidays": "Game Alerts Season Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Kuroko's Basketball Rank",
        "a_meta_collector": "Team Hoard",
        "a_meta_category_starter": "Generation Badge",
        "a_meta_tier_climber": "Coach Glyph",
        "a_meta_tier_max": "Generation Miracles Writ",
        "a_meta_xp_earner": "Team Vault Emblem",
        "a_meta_difficulty_easy": "Court Mechanism",
        "a_meta_difficulty_hard": "Player Writ",
        "a_meta_unlock_spree": "Game Panel",
        "a_meta_completionist": "Championship Journey Fulfillment",
        "a_meta_diverse": "Archive Emblem",
        "a_meta_dominator": "Team Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Play",
        "m_chapter_counter": "Loyal Ledger",
        "m_chapter_titan": "Basketball Marathon Legend",
        "m_reading_hours": "Game Relic Relic",
        "m_reading_time_lord": "Player Record",
        "m_manga_collector": "Court Archive Ledger",
        "m_library_legend": "Fan Circle Reliquary",
        "m_first_complete": "Loyal Fan Triumph",
        "m_hundred_club": "Unscreened Players Network",
        "m_first_day": "Game Won Dawn",
        "m_first_rating": "Game Alerts Eye",
        "m_ten_thousand_pages": "Marathon Gauge",
        "m_volume_collector": "Seirin Gym Hoard",
        "m_year_explorer": "Points Scored Quest",
        "m_century_reader": "Scored Dominion Dominion",
        "m_five_hundred_ch": "Play Archive Ledger",
        "m_thousand_ch": "Game Legend",
        "m_reading_ten": "Champion Appraisal",
        "m_ptr_hoarder": "Scored Index",
        "m_dropped_honesty": "Play Archive Honesty",
        "m_season_reader": "Points Scored Treasury Treasury",
        "m_active_reader": "Champion Trial Trial",
        "m_five_thousand_ch": "Phantom Standard",
        "m_ten_completed": "Points Scored Resolution",
        "m_fifty_completed": "Basketball Marathon Harvest",
        "m_five_hundred_completed": "Tetsuya Kuroko Legacy",
        "m_mean_score_tracker": "Championship Trophies Audit",
        "m_unique_authors": "Journey Reserve",
        "m_all_status": "Scored Testament Testament",
        "m_first_favorite": "Seirin Gym Cache",
        "m_favorites_collector": "Team Roster Shelf Shelf",
        "m_days_spent_reading": "Phantom Decree Decree",

        // ── MANGA BINGE ──
        "m_binge_reader": "Marathon Streak",
        "m_marathon_reader": "Scored Rush",
        "m_weekend_reader": "Unscreened Players Run",
        "m_non_stop_reading": "Kuroko's Basketball Gauntlet",
        "m_one_more_chapter": "Team Vault Testament",
        "m_speed_read": "Tournament Bracket Drive",
        "m_double_story": "Points Scored Banner",
        "m_triple_read": "Scouting Record Record",
        "m_five_a_day": "Player Insignia",
        "m_chapter_chain": "Marathon Accord",
        "m_volume_binge": "Japanese Drive",
        "m_power_reader": "Court Warrant",
        "m_half_day_read": "Championship Trophies Aegis Aegis",
        "m_full_day_read": "Equipment Room Trial",
        "m_power_weekend": "Team Streak",
        "m_binge_king": "Marathon Momentum",
        "m_no_sleep_read": "Scored Sleepless",
        "m_full_series_rush": "Court Cascade",
        "m_seven_day_challenge": "Japanese Warrant",
        "m_hundred_day_read": "Scored Relic",
        "m_volume_rush": "Team Roster Gauntlet",
        "m_series_sweep": "Court Trial Trial",
        "m_genre_binge": "Scouting Binge",
        "m_author_binge": "Miracles Surge",
        "m_chapter_counter_day": "Miracles Ledger",
        "m_multi_series_binge": "Generation Miracles Charge",
        "m_midnight_binge": "Court Tempest",
        "m_new_year_binge": "Journey New Year",
        "m_forty_eight_hour": "Points Rally",
        "m_oneshot_binge": "Tournament Bracket Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Champion Action",
        "m_genre_adventure": "Player Champion Adventure",
        "m_genre_comedy": "Points Comedy",
        "m_genre_drama": "Team Drama",
        "m_genre_fantasy": "Championship Journey Fantasy",
        "m_genre_horror": "Tournament Bracket Horror",
        "m_genre_mystery": "Phantom Mystery",
        "m_genre_romance": "Seirin Gym Romance",
        "m_genre_scifi": "Court Archive Sci-Fi",
        "m_genre_sol": "Equipment Room Slice",
        "m_genre_sports": "Phantom Sports",
        "m_genre_supernatural": "Generation Supernatural",
        "m_genre_thriller": "Basketball Marathon Thriller",
        "m_genre_psychological": "Play Archive Psychological",
        "m_genre_isekai": "Game Isekai",
        "m_genre_shounen": "Archive Shounen",
        "m_genre_ecchi": "Championship Journey Ecchi",
        "m_genre_mahou_shoujo": "Phantom Player Magic Shoujo",
        "m_genre_mecha": "Archive Mecha",
        "m_genre_music": "Game Won Music",
        "m_tag_isekai_new": "Game Isekai New",
        "m_tag_harem": "Pass Harem",
        "m_tag_bl": "Phantom Player Bl",
        "m_tag_gl": "Player Champion Gl",
        "m_tag_historical": "Game Won Historical Badge",
        "m_tag_military": "Scored Military",
        "m_tag_school": "Miracles School",
        "m_tag_martial_arts": "Pass Martial Arts",
        "m_tag_vampire": "Seirin Gym Vampire",
        "m_tag_samurai": "Play Samurai",
        "m_tag_space": "Championship Trophies Space",
        "m_tag_parody": "Archive Parody",
        "m_tag_idol": "Team Roster Idol",
        "m_tag_post_apocalyptic": "Generation Miracles Post Apocalyptic",
        "m_tag_cyberpunk": "Loyal Cyberpunk",
        "m_tag_shoujo": "Player Shoujo",
        "m_tag_survival": "Points Survival",
        "m_tag_cooking": "Game Won Cooking",
        "m_tag_medical": "Basketball Marathon Medical",
        "m_tag_villainess": "Generation Miracles Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Court Archive",
        "m_mega_completionist": "Points Scored Completion",
        "m_completion_rate_50": "Team Roster Return",
        "m_completion_rate_75": "Game Ascension",
        "m_completion_rate_90": "Championship Trophies Resolution",
        "m_no_drop": "Generation Relic",
        "m_long_runner_complete": "Coach Clear",
        "m_sequel_chain": "Player Seal",
        "m_clean_list": "Points Ledger",
        "m_from_ptr": "Marathon Watchlist",
        "m_reread_master": "Basketball Marathon Trial",
        "m_oneshot_complete": "Player Champion Ascension",
        "m_same_day_start_finish": "Loyal Fan Crown Crown",
        "m_revival": "Coach Accord",
        "m_zero_to_hundred": "Kuroko's Basketball Banner",
        "m_five_genre_complete": "Generation M Five Genre Complete",
        "m_full_collection": "Journey Proof",
        "m_batch_complete": "Phantom Player Summit",
        "m_paused_to_done": "Play Standard Standard",
        "m_completion_spree": "Match Alerts Triumph",
        "m_format_completionist": "Team Vault Completion",
        "m_catch_up": "Game Won Chronicle",
        "m_multi_reread": "Championship Trophies Banner",
        "m_dropped_recovery": "Championship Journey Conquest",
        "m_ten_perfect_scores": "Team Judgment",
        "m_complete_genre_span": "Basketball Marathon M Complete Genre",
        "m_monthly_completions": "Points Return",
        "m_yearly_completions": "Basketball Marathon Epilogue",
        "m_rapid_complete": "Seirin High Finale Finale",
        "m_author_complete": "Marathon Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Player Legacy",
        "m_mangaka_lover": "Phantom Standard Standard",
        "m_rereader": "Game Alerts Relic",
        "m_triple_reread": "Phantom Player Accord",
        "m_annual_reread": "Team Roster Banner Banner",
        "m_publisher_fan": "Loyal Mark",
        "m_artist_fan": "Player Champion Pinnacle",
        "m_adaptation_compare": "Player Insignia Insignia",
        "m_source_material_fan": "Scouting Cache",
        "m_waiting_weekly": "Points Streak",
        "m_classic_reader": "Player Champion Lantern",
        "m_saga_reader": "Equipment Room Crown",
        "m_genre_loyalty": "Seirin High Loyalty",
        "m_decade_reader": "Journey Warrant",
        "m_ln_adaptation": "Japanese Mark",
        "m_original_work": "Kuroko's Basketball Standard",
        "m_long_commitment": "Loyal Mark Mark",
        "m_up_to_date": "Journey Warrant Warrant",
        "m_favorite_mangaka": "Basketball Treasury",
        "m_complete_portfolio": "Loyal Triumph",
        "m_franchise_collector": "Tetsuya Kuroko Archive",
        "m_serialization_follower": "Play Handshake",
        "m_genre_master": "Basketball Marathon Master",
        "m_multi_series_author": "Unscreened Players Insignia",
        "m_format_diversity": "Kuroko's Basketball Shelf",
        "m_year_dedication": "Court Archive Yearlong",
        "m_ongoing_follower": "Pass Fellowship",
        "m_genre_loyalty_50": "Basketball Marathon Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Kuroko's Basketball Explorer",
        "m_publisher_hopper": "Kuroko's Basketball Record",
        "m_tag_explorer": "Court Archive Explorer",
        "m_decade_hopper": "Basketball Marathon Proof",
        "m_hidden_gem": "Play Archive Standard",
        "m_popular_taste": "Championship Trophies Record Record",
        "m_retro_reader": "Phantom Player Accord Accord",
        "m_modern_reader": "Player Seal Seal",
        "m_cross_demographic": "Japanese Crown Crown",
        "m_underdog_fan": "Court Testament Testament",
        "m_variety_week": "Game Won Horizon",
        "m_manhwa_reader": "Match Alerts Proof Proof",
        "m_manhua_reader": "Game Alerts Mantle",
        "m_classic_connoisseur": "Player Glimpse",
        "m_award_winner": "Court Warrant Warrant",
        "m_niche_explorer": "Marathon Horizon",
        "m_world_manga": "Miracles Chronicle Chronicle",
        "m_cult_classic": "Seirin Gym Map",
        "m_random_pick": "Loyal Fan Testament",
        "m_new_genre_month": "Game Won M New Genre",
        "m_year_completionist": "Championship Journey Completion",
        "m_unpopular_opinion": "Scouting Aegis",
        "m_top_rated_reader": "Japanese Pinnacle",
        "m_source_variety": "Archive Catalogue",
        "m_low_score_brave": "Loyal Fan Score",
        "m_short_manga_explorer": "Miracles Compass",
        "m_long_manga_explorer": "Team Roster Survey",
        "m_serialization_explorer": "Championship Road",

        // ── MANGA TIME ──
        "m_night_owl": "Miracles Accord Accord",
        "m_early_bird": "Kuroko's Basketball Banner Banner",
        "m_lunch_reader": "Archive Relic",
        "m_commute_reader": "Scored Tenure",
        "m_four_am_club": "Equipment Room Fellowship",
        "m_new_year_read": "Marathon Pact",
        "m_all_hours": "Tetsuya Kuroko Accord",
        "m_prime_time_reader": "Basketball Banner Banner",
        "m_workday_reader": "Fan Circle Accord",
        "m_sunday_read": "Basketball Standard Standard",
        "m_morning_routine": "Unscreened Players Discipline",
        "m_night_shift_reader": "Fan Circle Accord Accord",
        "m_seasonal_premier_read": "Court Storehouse",
        "m_clock_collector": "Tournament Bracket Reserve",
        "m_late_night_horror": "Equipment Room Mark Mark",
        "m_afternoon_reader": "Player Champion Mantle",
        "m_golden_hour_reader": "Team Vault Observance",
        "m_dawn_reader": "Player Champion Mantle Mantle",
        "m_twilight_reader": "Generation Crown Crown",
        "m_midnight_start": "Play Routine",
        "m_weekend_binge_hours": "Tetsuya Kuroko Momentum",
        "m_late_night_regular": "Championship Journey Mark",
        "m_sunrise_reader": "Loyal Mantle",
        "m_every_day_of_week": "Tetsuya Kuroko Seal Seal",
        "m_monthly_hours": "Points Scored Vigil",
        "m_bedtime_reader": "Loyal Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Championship Mantle",
        "m_webtoon_reader": "Seirin High Mark Mark",
        "m_full_color": "Marathon Accord Accord",
        "m_doujin_reader": "Points Scored Record Record",
        "m_anthology_reader": "Unscreened Players Accord",
        "m_adaptation_reader": "Scouting Banner",
        "m_longstrip_reader": "Court Archive Trial Trial",
        "m_4koma_reader": "Champion Relic",
        "m_oneshot_reader": "Basketball Marathon Mantle Mantle",
        "m_format_variety": "Generation Gallery",
        "m_light_novel_reader": "Game Won Insignia",
        "m_novel_reader": "Equipment Room Crown Crown",
        "m_visual_storyteller": "Court Archive Testament",
        "m_colored_classic": "Scouting Survey",
        "m_webcomic_fan": "Court Pinnacle",
        "m_manga_to_anime": "Team Roster Record",
        "m_seinen_reader": "Equipment Room Pinnacle Pinnacle",
        "m_josei_reader": "Match Alerts Pinnacle",
        "m_award_winning_art": "Court Relic Relic",
        "m_debut_work": "Champion Dominion",
        "m_vertical_scroll": "Championship Journey Crown Crown",
        "m_traditional_format": "Coach Hoard",
        "m_cross_media": "Player Accord",
        "m_spinoff_reader": "Player Accord Accord",
        "m_remake_reader": "Champion Pinnacle",
        "m_collaboration_reader": "Unscreened Players Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Equipment Room Focus",
        "m_mega_streak": "Play Routine Routine",
        "m_weekly_warrior": "Team Vault Weekly",
        "m_monthly_reader": "Unscreened Players Monthly",
        "m_comeback": "Team Roster Standard",
        "m_weekend_streak": "Generation Fever",
        "m_no_zero_days": "Loyal Proof",
        "m_iron_will": "Player Ledger Ledger",
        "m_habit_formed": "Game Won Decree",
        "m_consistent_pace": "Loyal Fan Scrutiny Scrutiny",
        "m_year_long": "Court Archive Observance",
        "m_double_streak": "Basketball Marathon Resolve",
        "m_streak_recovery": "Championship Resolve",
        "m_daily_minimum": "Pass Focus",
        "m_winter_streak": "Court Archive Observance Observance",
        "m_summer_streak": "Team Vault Observance Observance",
        "m_morning_streak": "Points Clock",
        "m_night_streak": "Tetsuya Kuroko Discipline",
        "m_unbreakable": "Coach Banner Banner",
        "m_eternal_flame": "Team Roster Record Record",
        "m_chapter_a_day": "Loyal Crown",
        "m_genre_streak": "Team Vault Streak",
        "m_completion_streak": "Team Roster Return Return",
        "m_rating_streak": "Champion Appraisal Appraisal",
        "m_multi_ch_streak": "Player Champion Tenure",
        "m_author_streak": "Tournament Bracket Calendar Calendar",
        "m_perfect_week_manga": "Generation Miracles Accord",
        "m_diverse_streak": "Seirin Gym Streak",

        // ── MANGA SCORING ──
        "m_critic": "Generation Scrutiny",
        "m_perfect_ten": "Kuroko's Basketball Verdict",
        "m_harsh_critic": "Team Scale",
        "m_fair_judge": "Player Champion Eye",
        "m_generous_spirit": "Team Decree",
        "m_score_all": "Championship Journey Reckoning",
        "m_wide_range": "Champion Crown",
        "m_controversial": "Loyal Testament",
        "m_consistent_scorer": "Basketball Grade",
        "m_score_sniper": "Tournament Bracket Reckoning",
        "m_evolving_taste": "Game Trial",
        "m_bell_curve": "Coach Accord Accord",
        "m_picky_reader": "Loyal Crown Crown",
        "m_100_rated": "Tetsuya Kuroko Standard",
        "m_500_rated": "Pass Proof",
        "m_mediocre_majority": "Game Alerts Canon",
        "m_rating_spree": "Kuroko's Basketball Verdict Verdict",
        "m_score_variance": "Seirin High Measure Measure",
        "m_binge_rater": "Championship Journey Passage",
        "m_reread_rerate": "Championship Trophies Banner Banner",
        "m_masterpiece_hunter": "Equipment Room Dominion",
        "m_contrarian": "Seirin Gym Aegis",
        "m_optimist": "Unscreened Players Accord Accord",
        "m_score_distributor": "Court Archive Balance",
        "m_genre_critic": "Equipment Room Critic",
        "m_mean_above_8": "Seirin High Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Court Season",
        "m_valentines_read": "Player Champion Observance",
        "m_pi_day": "Player Champion Testament",
        "m_april_fools": "Championship Journey Devotion",
        "m_international_manga_day": "Tournament Bracket Proof Proof",
        "m_free_comic_day": "Fan Circle Chronicle",
        "m_summer_solstice": "Generation Focus",
        "m_tanabata": "Championship Journey Pilgrimage",
        "m_friday_13th": "Basketball Marathon Dominion",
        "m_halloween_read": "Championship Journey Calendar",
        "m_thanksgiving_binge": "Play Archive Charge",
        "m_christmas_read": "Game Won Pact",
        "m_new_years_eve": "Seirin High Pilgrimage",
        "m_birthday_read": "Seirin High Focus",
        "m_holiday_marathon": "Seirin Gym Rally",
        "m_independence_day": "Play Aegis Aegis",
        "m_culture_day": "Basketball Marathon Warrant",
        "m_spring_equinox": "Pass Dominion",
        "m_earth_day": "Phantom Aegis",
        "m_labor_day": "Champion Warrant",
        "m_winter_solstice": "Match Alerts Focus",
        "m_manga_birthday": "Japanese Ritual",
        "m_every_holiday_reader": "Champion Watch",
        "m_consecutive_holidays": "Championship Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Pass Proof Proof",
        "m_fibonacci": "Archive Dominion Dominion",
        "m_palindrome_day": "Miracles Decree",
        "m_binary_day": "Player Aegis",
        "m_full_moon_read": "Team Decree Decree",
        "m_leap_year_read": "Championship Trophies Practice",
        "m_triple_seven": "Seirin Gym Chronicle",
        "m_thousand_complete": "Basketball Marathon Ascension",
        "m_nice": "Play Archive Seal",
        "m_power_level_chapters": "Points Scored Aegis Aegis",
        "m_answer_42": "Basketball Aegis Aegis",
        "m_square_number": "Kuroko's Basketball Standard Standard",
        "m_prime_count": "Marathon Insignia",
        "m_matching_date": "Game Mantle Mantle",
        "m_century_chapter": "Scored Relic Relic",
        "m_pi_chapters": "Unscreened Players Aegis",
        "m_synchronicity": "Game Alerts Emblem",
        "m_world_record": "Loyal Warrant Warrant",
        "m_genre_clash": "Points Scored Clash",
        "m_time_traveler": "Championship Trophies Decree Decree",
        "m_double_digits": "Basketball Marathon Dominion Dominion",
        "m_one_two_three": "Equipment Room Warrant",
        "m_lucky_seven": "Generation Pinnacle Pinnacle",
        "m_exact_hundred_ch": "Team Vault Legend",
        "m_year_match_count": "Play Yearlong",
        "m_chapter_match_date": "Fan Circle Record",

        // ── MANGA FORMATS ──
        "m_manga_format": "Team Vault Index",
        "m_manhwa_format": "Tournament Bracket Gallery",
        "m_manhua_format": "Court Storehouse Storehouse",
        "m_ln_format": "Scored Index Index",
        "m_oneshot_format": "Game Index",
        "m_doujin_format": "Points Scored Cabinet Cabinet",
        "m_novel_format": "Generation Reserve",
        "m_format_master_manga": "Scouting Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Championship Trophies Link",
        "m_meta_collector": "Coach Reliquary",
        "m_meta_category_starter": "Match Alerts Standard",
        "m_meta_tier_climber": "Team Token Token",
        "m_meta_tier_max": "Player Token",
        "m_meta_xp_earner": "Archive Anchor",
        "m_meta_difficulty_easy": "Archive Panel",
        "m_meta_difficulty_hard": "Court Node",
        "m_meta_unlock_spree": "Game Marker",
        "m_meta_completionist": "Tournament Bracket Triumph",
        "m_meta_diverse": "Game Anchor",
        "m_meta_dominator": "Marathon Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#00030e",
        primary: "#0078a5",
        secondary: "#004888",
        accent: "#e85020",
    },
    particleColor: "#0078a5",
    backgroundDim: 0.28,
    backgroundBlur: 12,
    milestoneNames: {
  1: "Threadbare Generic Rank Spark",
  8: "Generic's Tarnished Omen",
  14: "Fractured Generic Rank",
  21: "Generic Rank Path",
  28: "Lowborn Legacy Myth",
  35: "Generic Rank Pulse",
  41: "Generic's Legacy Crest",
  48: "Humble Generic Mark",
  55: "Ragged Generic Rank Vow",
  61: "Generic's Faint Echo",
  68: "Lesser Generic Rank",
  75: "Generic Rank Zenith",
  81: "Doubtful Legacy Bloom",
  88: "Generic Rank Sigil",
  95: "Generic's Legacy Flame",
  102: "Really Cool Generic Spark",
  108: "Awakened Generic Rank Omen",
  115: "Generic's Resolute Seal",
  122: "Rising Generic Rank",
  128: "Generic Rank Myth",
  135: "Dauntless Legacy Pulse",
  142: "Generic Rank Crest",
  149: "Generic's Legacy Mark",
  155: "Fresh Generic Vow",
  162: "Valiant Generic Rank Echo",
  169: "Generic's Prime Crown",
  175: "Polished Generic Rank",
  182: "Generic Rank Bloom",
  189: "Stormlit Legacy Sigil",
  195: "Generic Rank Flame",
  202: "Generic's Legacy Spark",
  209: "Tempered Generic Omen",
  216: "Trusted Generic Rank Seal",
  222: "Generic's Steadfast Path",
  229: "Ironclad Generic Rank",
  236: "Veteran Legacy Pulse",
  242: "Core Legacy Crest",
  249: "Generic Rank Mark",
  256: "Generic's Legacy Vow",
  262: "Formidable Generic Echo",
  269: "Lucid Generic Rank Crown",
  276: "Generic's Ranked Zenith",
  283: "Fabled Generic Rank",
  289: "Grand Legacy Sigil",
  296: "Seasoned Legacy Flame",
  303: "Generic Rank Spark",
  309: "Generic's Legacy Omen",
  316: "Valorous Generic Seal",
  323: "Stalwart Generic Rank Path",
  330: "Generic's Commanding Myth",
  336: "Refined Generic Rank",
  343: "Unbroken Legacy Crest",
  350: "Blazing Legacy Mark",
  356: "Generic Rank Vow",
  363: "Generic's Legacy Echo",
  370: "Peerless Generic Crown",
  376: "Ardent Generic Rank Zenith",
  383: "Generic's Focused Bloom",
  390: "Vigilant Generic Rank",
  397: "Dominant Legacy Flame",
  403: "Elite Legacy Spark",
  410: "Generic Rank Omen",
  417: "Generic's Legacy Seal",
  423: "Sovereign Generic Path",
  430: "Regal Generic Rank Myth",
  437: "Generic's Crowned Pulse",
  444: "Mythborn Generic Rank",
  450: "Limitless Legacy Mark",
  457: "Radiant Legacy Vow",
  464: "Generic Rank Echo",
  470: "Generic's Legacy Crown",
  477: "Climactic Generic Zenith",
  484: "Epic Generic Rank Bloom",
  490: "Generic's Unreal Sigil",
  497: "Peak Generic Rank",
  504: "Supreme Legacy Spark",
  511: "Exalted Legacy Omen",
  517: "Generic Rank Seal",
  524: "Generic's Legacy Path",
  531: "Celestial Generic Myth",
  537: "Phantom Generic Rank Pulse",
  544: "Generic's Crimson Crest",
  551: "Silver Generic Rank",
  557: "Golden Legacy Vow",
  564: "Feral Legacy Echo",
  571: "Generic Rank Crown",
  578: "Generic's Legacy Zenith",
  584: "Dread Generic Bloom",
  591: "Luminous Generic Rank Sigil",
  598: "Generic's Thunderous Flame",
  604: "Ultraviolet Generic Rank",
  611: "Unleashed Legacy Omen",
  618: "Secret Legacy Seal",
  625: "Final Generic Path",
  631: "Generic's Legacy Myth",
  638: "Worldclass Generic Pulse",
  645: "Lawless Generic Rank Crest",
  651: "Generic's Chosen Mark",
  658: "Fearless Generic Rank",
  665: "Overdrive Legacy Echo",
  671: "Cinematic Legacy Crown",
  678: "Impossible Generic Zenith",
  685: "Generic's Legacy Bloom",
  692: "Canonized Generic Sigil",
  698: "Ascendant Generic Rank Flame",
  705: "Generic's Transfigured Spark",
  712: "Immortal Generic Rank",
  718: "Eclipsed Legacy Seal",
  725: "Astral Legacy Path",
  732: "Sublime Generic Myth",
  739: "Generic's Legacy Pulse",
  745: "Prismatic Generic Crest",
  752: "Abyssal Generic Rank Mark",
  759: "Generic's Unbound Vow",
  765: "Eternal Generic Rank",
  772: "Cosmic Legacy Crown",
  779: "Transcendent Legacy Zenith",
  785: "Perfected Generic Bloom",
  792: "Generic's Legacy Sigil",
  799: "Ultimate Generic Flame",
  806: "Mythic Generic Rank Spark",
  812: "Generic's Godlike Omen",
  819: "Canonical Generic Rank",
  826: "Reality-Bent Legacy Path",
  832: "Heavenly Legacy Myth",
  839: "Absolute Generic Pulse",
  846: "Untouchable Generic Crest",
  852: "Timeless Generic Mark",
  859: "Empyrean Generic Rank Vow",
  866: "Generic's Primordial Echo",
  873: "Omniscient Generic Rank",
  879: "Unfathomed Legacy Zenith",
  886: "Apocalyptic Legacy Bloom",
  893: "Seraphic Generic Sigil",
  899: "Omega Generic Flame",
  906: "Final Generic Spark",
  913: "Crowned Generic Rank Omen",
  920: "Generic's Mythic Seal",
  926: "Absolute Generic Rank",
  933: "Eternal Legacy Myth",
  940: "Cosmic Legacy Pulse",
  946: "Transcendent Generic Crest",
  953: "Perfected Generic Mark",
  960: "Definitive Generic Vow",
  966: "Ultimate Generic Rank Echo",
  973: "Generic's Infinite Crown",
  980: "Sovereign Generic Rank",
  987: "Celestial Legacy Bloom",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate Generic Rank"
},
}
