import { AnimeThemeConfig } from "./types"
import { GiImperialCrown, GiAncientSword, GiSpaceship, GiGoldBar, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiCannon } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const legendOfGalacticHeroesTheme: AnimeThemeConfig = {
    id: "legend-of-galactic-heroes",
    displayName: "Legend of the Galactic Heroes",
    description: "An epic struggle between the Galactic Empire and the Free Planets Alliance, told through two military geniuses on opposing sides — Yang Wenli and Reinhard von Lohengramm.",
    fontFamily: "'IM Fell English', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=IM+Fell+English:ital@0;1&display=swap",
    cssVars: {
        "--color-brand-200": "255 228 140",
        "--color-brand-300": "250 206 80",
        "--color-brand-400": "238 180 22",
        "--color-brand-500": "218 152 0",
        "--color-brand-600": "180 122 0",
        "--color-brand-700": "140 94 0",
        "--color-brand-800": "100 66 0",
        "--color-brand-900": "60 38 0",
        "--color-brand-950": "35 22 0",
        "--brand": "218 152 0",
        "--background": "#050503",
        "--paper": "#0c0c08",
        "--color-gray-950": "5 5 3",
        "--color-gray-900": "12 12 8",
        "--color-gray-800": "22 22 16",
        "--color-gray-700": "38 38 28",
        "--color-gray-600": "60 58 44",
        "--color-gray-500": "95 92 72",
        "--color-gray-400": "138 134 108",
        "--color-gray-300": "175 172 148",
        "--color-gray-200": "206 204 182",
        "--color-gray-100": "228 226 210",
        "--color-gray-50": "244 244 236",
    },
    sidebarOverrides: {
        "home": { icon: GiImperialCrown, label: "Imperial Palace" },
        "schedule": { icon: GiAlarmClock, label: "Battle Schedule" },
        "manga": { icon: LuBookOpen, label: "Historical Records" },
        "lists": { icon: GiAncientSword, label: "Fleet Registry" },
        "discover": { icon: GiBullseye, label: "Star Map" },
        "torrent-list": { icon: GiCannon, label: "Arms Cache" },
        "debrid": { icon: GiGoldBar, label: "Imperial Treasury" },
        "unmatched": { icon: GiSpaceship, label: "Unregistered Ships" },
        "enmasse": { icon: GiResize, label: "Fleet Deploy" },
        "scan-summaries": { icon: TbReportSearch, label: "Battle Reports" },
        "auto-downloader": { icon: LuRss, label: "Alliance Signals" },
        "community": { icon: GiImperialCrown, label: "Galaxy Council" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Imperial Orders" },
        "achievements": { icon: GiTrophy, label: "Galactic Honors" },
        "milestones": { icon: LuFlag, label: "Admiral Goals" },
        "theme-manager": { icon: GiPalette, label: "Imperial Colors" },
        "extensions": { icon: BiExtension, label: "Fleet Upgrades" },
        "sync": { icon: IoCloudOfflineOutline, label: "Galaxy Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Fleet Settings" },
    },
    achievementNames: {
        "a_first_episode": "First Campaign",
        "a_first_complete": "Battle Won",
        "a_hundred_club": "Hundred Battles",
        "a_time_lord": "Galactic Veteran",
        "a_anime_collector": "Fleet Collection",
        "a_library_legend": "Historical Archives",
        "a_binge_king": "Campaign Marathon",
        "a_no_sleep": "All-Night Strategy",
        "a_marathon_runner": "Galactic Marathon",
        "a_speed_run": "Blitzkrieg",
        "a_completionist": "Galaxy Unified",
        "a_mega_completionist": "Tanaka Master",
        "a_loyal_fan": "Yang's Ally",
        "a_rewatcher": "History Revisited",
        "a_decade_watcher": "Decade Scholar",
        "a_genre_action": "Fleet Combat",
        "a_genre_adventure": "Galactic Journey",
        "a_genre_comedy": "Merkatz's Sigh",
        "a_genre_drama": "Tragic Genius",
        "a_genre_fantasy": "Galactic Empire",
        "a_genre_horror": "Terrasenkreig",
        "a_genre_romance": "Reinhard's Love",
        "a_genre_scifi": "Space Opera",
        "a_genre_supernatural": "Imperial Myth",
        "a_genre_psychological": "Strategic Mind",
        "a_genre_mecha": "Fleet Warfare",
        "a_critic": "Historian's Eye",
        "a_perfect_ten": "Magnum Opus",
        "a_harsh_critic": "Strict Analyst",
        "a_daily_streak": "Daily Campaign",
        "a_mega_streak": "Decades of War",
        "a_year_long": "Year of History",
        "a_iron_will": "Iron Chancellor",
        "a_hidden_gem": "Hidden Record",
        "a_cult_classic": "Tanaka Classic",
        "a_classic_connoisseur": "88 Classic Fan",
        "a_new_years_resolution": "New Year Campaign",
        "a_christmas_special": "Imperial Gala",
        "a_meta_tier_max": "Galactic Kaiser",
        "a_meta_completionist": "Complete History",
        "a_sequel_chain": "Gaiden Arc",
        "a_zero_to_hero": "Commoner to Kaiser",
        "a_night_owl": "Night Strategy",
        "a_early_bird": "Dawn Campaign",
        "m_first_chapter": "First Record",
        "m_first_complete": "Volume Complete",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "History Marathon",
        "m_completionist": "Full Saga",
        "m_mega_completionist": "Galactic Master",
        "m_loyal_reader": "Imperial Reader",
        "m_rereader": "History Revisit",
        "m_genre_action": "Battle Chapter",
        "m_genre_adventure": "Galaxy Chapter",
        "m_genre_romance": "Hearts of War",
        "m_genre_fantasy": "Empire Chapter",
        "m_genre_horror": "War Crimes",
        "m_genre_drama": "Strategic Drama",
        "m_genre_scifi": "Galactic Science",
        "m_genre_supernatural": "Legend Chapter",
        "m_genre_psychological": "Political Mind",
        "m_critic": "History Critic",
        "m_perfect_ten": "Magnum Opus",
        "m_daily_streak": "Daily Record",
        "m_mega_streak": "Unbroken History",
        "m_year_long": "Year of Study",
        "m_iron_will": "Chancellor's Will",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Classic Space Opera",
        "m_mangaka_lover": "Tanaka Fan",
        "m_source_material_fan": "Novel First",
        "m_meta_tier_max": "Galaxy Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Space Opera Art",
        "m_manga_to_anime": "Novel to Screen",
        "m_night_owl": "Night Scholar",
        "m_early_bird": "Dawn Scholar",
    },
    musicUrl: "",
    previewColors: {
        bg: "#050503",
        primary: "#da9800",
        secondary: "#8c6000",
        accent: "#4060c8",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/legend-of-galactic-heroes.jpg",
    particleColor: "#f0cc40",
    backgroundDim: 0.42,
    backgroundBlur: 22,
    particleTypes: {
        battleships: { label: "Battleships", maxCount: 8, defaultEnabled: true, defaultIntensity: 50 },
        stars: { label: "Galactic Stars", maxCount: 25, defaultEnabled: true, defaultIntensity: 65 },
    },
    milestoneNames: {
    "7": "Novice Rank 1",
    "13": "Novice Level 2",
    "20": "Novice Tier 3",
    "27": "Novice Class 4",
    "33": "Novice Grade 5",
    "40": "Novice Position 6",
    "47": "Novice Status 7",
    "53": "Novice Role 8",
    "60": "Novice Title 9",
    "67": "Novice Authority 10",
    "73": "Beginner Rank 11",
    "80": "Beginner Level 12",
    "87": "Beginner Tier 13",
    "93": "Beginner Class 14",
    "100": "Beginner Grade 15",
    "107": "Beginner Position 16",
    "113": "Beginner Status 17",
    "120": "Beginner Role 18",
    "127": "Beginner Title 19",
    "133": "Student Authority 20",
    "140": "Student Rank 21",
    "147": "Student Level 22",
    "153": "Student Tier 23",
    "160": "Student Class 24",
    "167": "Student Grade 25",
    "173": "Student Position 26",
    "180": "Student Status 27",
    "187": "Student Role 28",
    "193": "Student Title 29",
    "200": "Learner Authority 30",
    "207": "Learner Rank 31",
    "213": "Learner Level 32",
    "220": "Learner Tier 33",
    "227": "Learner Class 34",
    "233": "Learner Grade 35",
    "240": "Learner Position 36",
    "247": "Learner Status 37",
    "253": "Learner Role 38",
    "260": "Adept Title 39",
    "267": "Adept Authority 40",
    "273": "Adept Rank 41",
    "280": "Adept Level 42",
    "287": "Adept Tier 43",
    "293": "Adept Class 44",
    "300": "Adept Grade 45",
    "307": "Adept Position 46",
    "313": "Adept Status 47",
    "320": "Expert Role 48",
    "327": "Expert Title 49",
    "333": "Expert Authority 50",
    "340": "Expert Rank 51",
    "347": "Expert Level 52",
    "353": "Expert Tier 53",
    "360": "Expert Class 54",
    "367": "Expert Grade 55",
    "373": "Expert Position 56",
    "380": "Expert Status 57",
    "387": "Master Role 58",
    "393": "Master Title 59",
    "400": "Master Authority 60",
    "407": "Master Rank 61",
    "413": "Master Level 62",
    "420": "Master Tier 63",
    "427": "Master Class 64",
    "433": "Master Grade 65",
    "440": "Master Position 66",
    "447": "Grandmaster Status 67",
    "453": "Grandmaster Role 68",
    "460": "Grandmaster Title 69",
    "467": "Grandmaster Authority 70",
    "473": "Grandmaster Rank 71",
    "480": "Grandmaster Level 72",
    "487": "Grandmaster Tier 73",
    "493": "Grandmaster Class 74",
    "500": "Grandmaster Grade 75",
    "507": "Sage Position 76",
    "513": "Sage Status 77",
    "520": "Sage Role 78",
    "527": "Sage Title 79",
    "533": "Sage Authority 80",
    "540": "Sage Rank 81",
    "547": "Sage Level 82",
    "553": "Sage Tier 83",
    "560": "Sage Class 84",
    "567": "Sage Grade 85",
    "573": "Legend Position 86",
    "580": "Legend Status 87",
    "587": "Legend Role 88",
    "593": "Legend Title 89",
    "600": "Legend Authority 90",
    "607": "Legend Rank 91",
    "613": "Legend Level 92",
    "620": "Legend Tier 93",
    "627": "Legend Class 94",
    "633": "Mythical Grade 95",
    "640": "Mythical Position 96",
    "647": "Mythical Status 97",
    "653": "Mythical Role 98",
    "660": "Mythical Title 99",
    "667": "Mythical Authority 100",
    "673": "Mythical Rank 101",
    "680": "Mythical Level 102",
    "687": "Mythical Tier 103",
    "693": "Mythical Class 104",
    "700": "Godly Grade 105",
    "707": "Godly Position 106",
    "713": "Godly Status 107",
    "720": "Godly Role 108",
    "727": "Godly Title 109",
    "733": "Godly Authority 110",
    "740": "Godly Rank 111",
    "747": "Godly Level 112",
    "753": "Godly Tier 113",
    "760": "Supreme Class 114",
    "767": "Supreme Grade 115",
    "773": "Supreme Position 116",
    "780": "Supreme Status 117",
    "787": "Supreme Role 118",
    "793": "Supreme Title 119",
    "800": "Supreme Authority 120",
    "807": "Supreme Rank 121",
    "813": "Supreme Level 122",
    "820": "Infinite Tier 123",
    "827": "Infinite Class 124",
    "833": "Infinite Grade 125",
    "840": "Infinite Position 126",
    "847": "Infinite Status 127",
    "853": "Infinite Role 128",
    "860": "Infinite Title 129",
    "867": "Infinite Authority 130",
    "873": "Infinite Rank 131",
    "880": "Infinite Level 132",
    "887": "Eternal Tier 133",
    "893": "Eternal Class 134",
    "900": "Eternal Grade 135",
    "907": "Eternal Position 136",
    "913": "Eternal Status 137",
    "920": "Eternal Role 138",
    "927": "Eternal Title 139",
    "933": "Eternal Authority 140",
    "940": "Eternal Rank 141",
    "947": "Transcendent Level 142",
    "953": "Transcendent Tier 143",
    "960": "Transcendent Class 144",
    "967": "Transcendent Grade 145",
    "973": "Transcendent Position 146",
    "980": "Transcendent Status 147",
    "987": "Transcendent Role 148",
    "993": "Transcendent Title 149",
    "1000": "Transcendent Authority 150"
},
}
