import { AnimeThemeConfig } from "./types"
import { GiSpellBook, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiCrystalBall, GiStarSwirl, GiMicrophone } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const littleWitchAcademiaTheme: AnimeThemeConfig = {
    id: "little-witch-academia",
    displayName: "Little Witch Academia",
    description: "Atsuko Kagari enrolls in Luna Nova Magical Academy inspired by legendary witch Shiny Chariot. Despite having no innate magic talent, her boundless enthusiasm and the Shiny Rod carry her toward something extraordinary.",
    cssVars: {
        "--color-brand-200": "210 185 252",
        "--color-brand-300": "172 138 248",
        "--color-brand-400": "130 85 238",
        "--color-brand-500": "92 42 218",
        "--color-brand-600": "62 16 178",
        "--color-brand-700": "38 5 132",
        "--color-brand-800": "18 1 85",
        "--color-brand-900": "8 0 42",
        "--color-brand-950": "3 0 18",
        "--brand": "92 42 218",
        "--background": "#020008",
        "--paper": "#050015",
        "--color-gray-950": "2 0 8",
        "--color-gray-900": "6 2 18",
        "--color-gray-800": "14 5 38",
        "--color-gray-700": "26 10 62",
        "--color-gray-600": "42 18 95",
        "--color-gray-500": "65 32 135",
        "--color-gray-400": "100 60 172",
        "--color-gray-300": "145 98 208",
        "--color-gray-200": "192 148 238",
        "--color-gray-100": "228 198 252",
        "--color-gray-50": "246 235 255",
    },
    sidebarOverrides: {
        "home": { icon: GiSpellBook, label: "Luna Nova" },
        "schedule": { icon: GiAlarmClock, label: "Magic Classes" },
        "manga": { icon: LuBookOpen, label: "Spellbook" },
        "lists": { icon: GiScrollUnfurled, label: "Spell Registry" },
        "discover": { icon: GiBullseye, label: "New Spells" },
        "torrent-list": { icon: GiCrystalBall, label: "Magic Cache" },
        "debrid": { icon: GiHeartKey, label: "Shiny Vault" },
        "unmatched": { icon: GiStarSwirl, label: "Lost Words" },
        "enmasse": { icon: GiResize, label: "Grand Witch Trials" },
        "scan-summaries": { icon: TbReportSearch, label: "Magic Reports" },
        "auto-downloader": { icon: LuRss, label: "Spell Feed" },
        "community": { icon: GiMicrophone, label: "Witch Circle" },
        "achievements": { icon: GiTrophyCup, label: "Witch Trophies" },
        "milestones": { icon: LuFlag, label: "Shiny Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Magic Alerts" },
        "theme-manager": { icon: GiPalette, label: "Starry Colors" },
        "extensions": { icon: BiExtension, label: "Wand Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Magic Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Akko Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "Akko Arrives",
        "a_episode_counter": "Witch Trophies Mark",
        "a_episode_titan": "Lwa Marathon Relic",
        "a_hours_invested": "Starry Proof",
        "a_time_lord": "Grand Witch Decree",
        "a_anime_collector": "Spell Catalogue",
        "a_library_legend": "Atsuko Kagari Library",
        "a_first_complete": "First Spell Cast",
        "a_hundred_club": "Hundred Magic Days",
        "a_first_day": "Shiny Rod Seal",
        "a_first_rating": "Lost Words Appraisal",
        "a_ten_thousand_min": "Akko Standard",
        "a_season_veteran": "Atsuko Kagari Library Library",
        "a_year_explorer": "Little Witch Academia Map",
        "a_century_watcher": "Spell Registry Ledger",
        "a_five_hundred_eps": "Magic Archive Dominion",
        "a_thousand_eps": "Little Witch Academia Record",
        "a_watching_ten": "Spells Acclaim",
        "a_ptw_hoarder": "Archive Library",
        "a_dropped_honesty": "Spells Summit",
        "a_five_thousand_eps": "Words Warrant",
        "a_ten_completed": "Grand Witch Afterglow",
        "a_fifty_completed": "Magic Archive Ascension",
        "a_five_hundred_completed": "Luna Nova Magical Clear",
        "a_mean_score_tracker": "Shiny Rodentata Verdict",
        "a_unique_studios": "Little Witch Academia Collection",
        "a_days_spent_watching": "Magic Archive Dominion Dominion",
        "a_all_status": "Lost Words Testament",
        "a_first_favorite": "Despite Cabinet",
        "a_favorites_collector": "Grand Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Marathon Drive",
        "a_marathon_runner": "Despite Gauntlet",
        "a_weekend_warrior": "Rodentata Ordeal",
        "a_non_stop": "Words Fever",
        "a_one_more_episode": "Spell Mantle",
        "a_speed_run": "Shiny Rodentata Vigil",
        "a_double_feature": "Cast Crown",
        "a_triple_threat": "Shiny Rodentata Record",
        "a_five_a_day": "Atsuko Kagari Accord",
        "a_back_to_back": "Shiny Rod Surge",
        "a_seasonal_binge": "Lwa Marathon Cascade",
        "a_cour_crusher": "Magic Archive Ordeal",
        "a_half_day_watch": "Luna Nova Crown",
        "a_full_day_watch": "Marathon Pinnacle",
        "a_power_weekend": "Spell Registry Run",
        "a_binge_king": "LWA Marathon",
        "a_no_sleep": "Shiny Rodentata Sleepless",
        "a_entire_season": "Wand Vault",
        "a_seven_day_challenge": "Witch Trophies Mark Mark",
        "a_hundred_day_binge": "Shiny Rod Legend",
        "a_genre_binge": "Shiny Rodentata Binge",
        "a_studio_binge": "Words Fever Fever",
        "a_season_sweep": "Lwa Marathon Codex",
        "a_forty_eight_hour": "Spellbook Overture",
        "a_ep_counter_day": "Magic Classes Aegis",
        "a_multi_series_binge": "Shiny Streak",
        "a_midnight_binge": "Arrives Cascade",
        "a_new_year_binge": "Shiny Chariot Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Spell Action",
        "a_genre_adventure": "Rodentata Adventure",
        "a_genre_comedy": "Spellbook Comedy",
        "a_genre_drama": "Archive Drama",
        "a_genre_fantasy": "Starry Fantasy",
        "a_genre_horror": "Witch Trophies Horror",
        "a_genre_mystery": "Magic Mystery",
        "a_genre_romance": "Akko Arrives Romance",
        "a_genre_scifi": "Lost Words Sci-Fi",
        "a_genre_sol": "Witch Trophies Slice",
        "a_genre_sports": "Akko Arrives Sports",
        "a_genre_supernatural": "Shiny Vault Supernatural",
        "a_genre_thriller": "Spell Thriller",
        "a_genre_mecha": "Spell Mecha",
        "a_genre_music": "Akko Music",
        "a_genre_psychological": "Shiny Psychological",
        "a_genre_ecchi": "Witch Trophies Ecchi",
        "a_genre_mahou_shoujo": "Grand Magic Shoujo",
        "a_tag_isekai": "Grand Witch Isekai",
        "a_tag_harem": "Magic Alerts Harem",
        "a_tag_bl": "Shiny Fan Bl",
        "a_tag_gl": "Magic Shiny Gl",
        "a_tag_historical": "Witch Circle Historical",
        "a_tag_military": "Magic Shiny Military",
        "a_tag_school": "Archive School",
        "a_tag_martial_arts": "Luna Nova Martial Arts",
        "a_tag_vampire": "Grand Vampire",
        "a_tag_samurai": "Magic Samurai",
        "a_tag_space": "Grand Space",
        "a_tag_parody": "Magic Shiny Parody",
        "a_tag_idol": "Grand Idol",
        "a_tag_post_apocalyptic": "Spells Post Apocalyptic",
        "a_tag_cyberpunk": "Words Cyberpunk",
        "a_tag_shounen": "Luna Nova Magical Shounen",
        "a_tag_seinen": "Archive Seinen",
        "a_tag_shoujo": "Witch Circle Shoujo",
        "a_tag_josei": "Despite Josei",
        "a_tag_survival": "Shiny Rodentata Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "Seven Words Complete",
        "a_mega_completionist": "Grand Witch",
        "a_completion_rate_50": "Spellbook Return",
        "a_completion_rate_75": "No Magic Crown",
        "a_completion_rate_90": "Magic Resolution",
        "a_no_drop": "Grand Witch Decree Decree",
        "a_long_runner_complete": "Spell Registry Clear",
        "a_sequel_chain": "Spells Insignia",
        "a_clean_list": "Lwa Marathon Relic Relic",
        "a_from_ptw": "Magic Shiny Index",
        "a_rewatch_master": "Spellbook Return Return",
        "a_short_complete": "Cast Endgame",
        "a_same_day_start_finish": "Shiny Chariot Pinnacle",
        "a_revival": "Witch Circle Insignia",
        "a_zero_to_hero": "No Magic to Shiny Rod",
        "a_five_genre_complete": "Grand Witch Trials A Five",
        "a_full_franchise": "Shiny Chronicle",
        "a_batch_complete": "Wand Crown",
        "a_paused_to_done": "Magic Classes Aegis Aegis",
        "a_completion_spree": "Shiny Vault Triumph",
        "a_multi_rewatch": "Shiny Vault Triumph Triumph",
        "a_dropped_recovery": "Magic Alerts Conquest",
        "a_ten_perfect_scores": "Witch Circle Acclaim",
        "a_seasonal_clear": "Arrives Codex",
        "a_complete_genre_span": "Lost Words A Complete Genre",
        "a_monthly_completions": "Grand Afterglow",
        "a_yearly_completions": "Witch Epilogue",
        "a_rapid_complete": "Witch Trophies Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Shiny Fan",
        "a_studio_devotee": "Magic Treasury",
        "a_rewatcher": "Shiny Rod Closure",
        "a_triple_rewatch": "Akko Arrives Coda",
        "a_annual_tradition": "Magic Alerts Proof",
        "a_director_fan": "Wand Trial",
        "a_voice_actor_fan": "Luna Nova Crown Crown",
        "a_ost_lover": "Shiny Rod Seal Seal",
        "a_source_reader": "Despite Cabinet Cabinet",
        "a_waiting_weekly": "Despite Clock",
        "a_childhood_revisit": "Akko Seal",
        "a_saga_tracker": "Shiny Fan Standard",
        "a_genre_loyalty": "Luna Nova Loyalty",
        "a_decade_watcher": "Akko Arrives Banner",
        "a_adaptation_hunter": "No Magic Trial",
        "a_original_anime_fan": "Witch Testament",
        "a_long_commitment": "Shiny Standard",
        "a_perfect_attendance": "Akko Standard Standard",
        "a_favorite_studio_5": "Wand Vault Vault",
        "a_complete_catalog": "Shiny Rodentata Seal",
        "a_franchise_collector": "Luna Nova Magical Archive",
        "a_airing_follower": "Atsuko Kagari Signal",
        "a_genre_master": "Lwa Marathon Master",
        "a_staff_follower": "Akko Oath",
        "a_multi_season_fan": "Shiny Rod Hoard",
        "a_format_diversity": "Spellbook Cache",
        "a_year_dedication": "Wand Tenure",
        "a_season_dedication": "Arrives Codex Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Shiny Fan Explorer",
        "a_studio_hopper": "Shiny Rodentata Collection",
        "a_tag_explorer": "Lost Words Explorer",
        "a_decade_hopper": "Shiny Chronicle Chronicle",
        "a_hidden_gem": "Words Warrant Warrant",
        "a_popular_taste": "Grand Decree",
        "a_retro_appreciator": "Spellbook Aegis",
        "a_modern_viewer": "Shiny Chariot Pinnacle Pinnacle",
        "a_cross_demographic": "Marathon Pinnacle Pinnacle",
        "a_underdog_fan": "Wand Trial Trial",
        "a_variety_week": "Spell Cast Horizon",
        "a_foreign_cinema": "Magic Shiny Expedition",
        "a_classic_connoisseur": "Atsuko Kagari Glimpse",
        "a_every_season": "Luna Nova Magical Archive Archive",
        "a_award_winner": "Spells Insignia Insignia",
        "a_niche_explorer": "Shiny Horizon",
        "a_global_anime": "Cast Crown Crown",
        "a_cult_classic": "Shiny Rodentata Map",
        "a_random_pick": "Grand Decree Decree",
        "a_new_genre_month": "Spell Cast A New Genre",
        "a_seasonal_completionist": "Witch Circle Summit",
        "a_unpopular_opinion": "Magic Standard",
        "a_top_rated_viewer": "Akko Seal Seal",
        "a_source_variety": "Magic Archive Storehouse",
        "a_low_score_brave": "Luna Nova Measure",
        "a_upcoming_watcher": "Witch Warrant",
        "a_short_series_explorer": "Magic Shiny Expedition Expedition",
        "a_long_series_explorer": "Cast Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Rodentata Pinnacle",
        "a_early_bird": "Despite Banner",
        "a_lunch_break": "No Magic Trial Trial",
        "a_golden_hour": "Wand Tenure Tenure",
        "a_four_am_club": "Cast Gathering",
        "a_witching_hour": "No Magic Tenure",
        "a_new_year_watch": "Lwa Marathon Season",
        "a_midnight_premiere": "Cast Devotion",
        "a_all_hours": "Magic Shiny Warrant",
        "a_dawn_warrior": "Spellbook Aegis Aegis",
        "a_afternoon_delight": "Starry Proof Proof",
        "a_prime_time": "Rodentata Pinnacle Pinnacle",
        "a_workday_watcher": "Shiny Rod Record",
        "a_sunday_marathon": "Archive Momentum",
        "a_rainy_day": "Arrives Relic",
        "a_morning_routine": "Archive Promise",
        "a_night_shift": "Luna Nova Trial",
        "a_twilight_zone": "Luna Nova Magical Ledger",
        "a_seasonal_premier": "Despite Seasonal",
        "a_clock_collector": "Shiny Chariot Repository",
        "a_weekend_binge_hours": "Shiny Streak Streak",
        "a_late_night_regular": "Rodentata Dominion",
        "a_sunrise_watcher": "Shiny Rodentata Ledger",
        "a_holiday_watcher": "Spell Cast Pact",
        "a_every_day_of_week": "Spell Registry Ledger Ledger",
        "a_monthly_hours": "Shiny Fan Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Little Witch Academia Record Record",
        "a_party_host": "Shiny Rodentata Record Record",
        "a_social_butterfly": "Grand Witch Company",
        "a_group_binge": "Magic Sprint",
        "a_party_regular": "Spell Cast Chronicle",
        "a_sync_viewer": "Starry Standard",
        "a_commentator": "Words Mantle",
        "a_party_marathon": "Shiny Rodentata Vigil Vigil",
        "a_full_house": "Grand Witch Chronicle",
        "a_community_pillar": "Wand Alliance",
        "a_watch_party_streak": "Words Watch",
        "a_diverse_party": "Magic Shiny Warrant Warrant",
        "a_late_night_party": "Witch Testament Testament",
        "a_party_veteran": "Magic Shiny Testament",
        "a_genre_party": "Spell Party",
        "a_weekly_party": "Starry Calendar",
        "a_silent_viewer": "Lost Words Mantle",
        "a_recommendation_giver": "Shiny Network",
        "a_party_completionist": "Akko Arrives Completion",
        "a_social_scorer": "Lwa Marathon Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Luna Nova Magical Aegis",
        "a_fibonacci": "Rodentata Dominion Dominion",
        "a_palindrome_day": "Shiny Rodentata Ledger Ledger",
        "a_binary_day": "Shiny Standard Standard",
        "a_full_moon": "Shiny Fan Record",
        "a_leap_year": "Cast Yearlong",
        "a_time_traveler": "Shiny Vault Mantle",
        "a_genre_clash": "Shiny Fan Clash",
        "a_triple_seven": "Spellbook Accord",
        "a_thousand_complete": "Witch Legend",
        "a_pi_episodes": "Witch Circle Decree",
        "a_synchronicity": "Lost Words Anchor",
        "a_world_record": "Archive Banner",
        "a_nice": "Spell Cast Chronicle Chronicle",
        "a_power_level": "Spellbook Accord Accord",
        "a_answer_42": "Shiny Fan Standard Standard",
        "a_square_number": "Marathon Relic",
        "a_prime_count": "Witch Warrant Warrant",
        "a_matching_date": "Lost Words Mantle Mantle",
        "a_century_episode": "Arrives Testament",
        "a_double_digits": "Magic Shiny Testament Testament",
        "a_one_two_three": "Spells Decree",
        "a_lucky_seven": "Witch Circle Decree Decree",
        "a_all_tens": "Words Criterion",
        "a_exact_hundred_eps": "Shiny Fan Legend",
        "a_year_match_count": "Despite Yearlong",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Spell Crown",
        "a_movie_buff": "Arrives Testament Testament",
        "a_ova_hunter": "Magic Alerts Testament",
        "a_ona_explorer": "Wand Secret",
        "a_special_watcher": "Arrives Relic Relic",
        "a_short_king": "Magic Archive Relic",
        "a_variety_pack": "Marathon Inquiry",
        "a_film_festival": "Lwa Marathon Proof",
        "a_music_video": "Arrives Proof",
        "a_tv_short": "Words Mantle Mantle",
        "a_movie_marathon": "Akko Arrives Gauntlet",
        "a_double_length": "Spells Decree Decree",
        "a_anthology": "Luna Nova Trial Trial",
        "a_mini_series": "Shiny Chariot Relic",
        "a_theatrical": "Atsuko Kagari Accord Accord",
        "a_format_master": "Grand Witch Trials Vault",
        "a_long_movie": "Witch Circle Insignia Insignia",
        "a_back_catalog": "Magic Alerts Testament Testament",
        "a_cm_watcher": "Cast Trial",
        "a_pv_collector": "Rodentata Storehouse",
        "a_format_balance": "Grand Witch Trials Vault Vault",
        "a_episodic_master": "Magic Standard Standard",
        "a_sequel_movie": "Akko Record",
        "a_recap_watcher": "Magic Classes Accord",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Cast Daily",
        "a_mega_streak": "Magic Streak",
        "a_weekly_warrior": "Arrives Season",
        "a_monthly_watcher": "Starry Monthly",
        "a_comeback": "Shiny Chariot Relic Relic",
        "a_weekend_streak": "Magic Alerts Passage",
        "a_no_zero_days": "Archive Banner Banner",
        "a_iron_will": "Magic Classes Banner",
        "a_habit_formed": "No Magic Dominion",
        "a_consistent_pace": "Cast Measure",
        "a_year_long": "Arrives Yearlong",
        "a_double_streak": "Lost Words Watch",
        "a_streak_recovery": "Lwa Marathon Season Season",
        "a_daily_minimum": "Shiny Chariot Focus",
        "a_winter_streak": "Spell Watch",
        "a_summer_streak": "Magic Archive Resolve",
        "a_morning_streak": "Akko Arrives Clock",
        "a_night_streak": "Witch Circle Constancy",
        "a_unbreakable": "Magic Alerts Proof Proof",
        "a_eternal_flame": "Spell Registry Accord",
        "a_completion_streak": "Witch Circle Curtain",
        "a_rating_streak": "Lwa Marathon Balance Balance",
        "a_multi_ep_streak": "Witch Trophies Ritual",
        "a_genre_streak": "Lwa Marathon Streak",
        "a_studio_streak": "Grand Witch Trials Storehouse",
        "a_perfect_week": "Words Crown",

        // ── ANIME SCORING ──
        "a_critic": "Starry Scrutiny",
        "a_perfect_ten": "Grand Audit",
        "a_harsh_critic": "Archive Gauge",
        "a_fair_judge": "Shiny Rodentata Judgment",
        "a_generous_spirit": "Akko Record Record",
        "a_score_all": "Shiny Vault Criterion",
        "a_wide_range": "Luna Nova Magical Ledger Ledger",
        "a_controversial": "Marathon Relic Relic",
        "a_consistent_scorer": "Little Witch Academia Verdict",
        "a_score_sniper": "Grand Witch Trials Score",
        "a_evolving_taste": "Luna Nova Mark",
        "a_bell_curve": "Shiny Fan Record Record",
        "a_picky_watcher": "Spellbook Banner",
        "a_100_rated": "Shiny Vault Warrant",
        "a_500_rated": "Shiny Rod Record Record",
        "a_mediocre_majority": "Rodentata Canon",
        "a_rating_spree": "Shiny Fan Review",
        "a_score_variance": "Witch Trophies Score",
        "a_masterpiece_hunter": "Akko Arrives Banner Banner",
        "a_contrarian": "Archive Insignia",
        "a_optimist": "Spell Crown Crown",
        "a_score_distributor": "Spell Appraisal",
        "a_genre_critic": "Grand Witch Trials Critic",
        "a_mean_above_8": "Magic Alerts Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "Rodentata Resolve",
        "a_valentines_weeb": "Luna Nova Magical Vow",
        "a_pi_day": "Grand Chronicle",
        "a_april_fools": "Cast Devotion Devotion",
        "a_international_anime_day": "Magic Shiny Mantle",
        "a_star_wars_day": "Arrives Proof Proof",
        "a_summer_solstice": "Magic Alerts Calendar",
        "a_tanabata": "Shiny Chariot Tanabata",
        "a_friday_13th": "Little Witch Academia Ledger",
        "a_halloween_spirit": "Spell Registry Vow",
        "a_thanksgiving_binge": "Luna Nova Magical Run",
        "a_christmas_special": "Arrives Christmas",
        "a_new_years_eve": "Words Pilgrimage",
        "a_birthday_watch": "Luna Nova Magical Birthday",
        "a_holiday_marathon": "Magic Classes Overture",
        "a_independence_day": "Witch Trophies Dominion",
        "a_culture_day": "Magic Archive Pinnacle",
        "a_spring_equinox": "Akko Ledger",
        "a_earth_day": "Archive Insignia Insignia",
        "a_labor_day": "Magic Classes Banner Banner",
        "a_winter_solstice": "Words Pilgrimage Pilgrimage",
        "a_anime_birthday": "Words Birthday",
        "a_every_holiday": "Magic Archive Resolve Resolve",
        "a_consecutive_holidays": "Arrives Season Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Little Witch Academia Rank",
        "a_meta_collector": "Shiny Rod Hoard Hoard",
        "a_meta_category_starter": "Shiny Chariot Badge",
        "a_meta_tier_climber": "Shiny Glyph",
        "a_meta_tier_max": "Atsuko Kagari Writ",
        "a_meta_xp_earner": "No Magic Emblem",
        "a_meta_difficulty_easy": "Lwa Marathon Mechanism",
        "a_meta_difficulty_hard": "Atsuko Kagari Writ Writ",
        "a_meta_unlock_spree": "Magic Shiny Panel",
        "a_meta_completionist": "Shiny Chariot Fulfillment",
        "a_meta_diverse": "Wand Emblem",
        "a_meta_dominator": "Spells Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Shiny Rodentata",
        "m_chapter_counter": "Shiny Chariot Ledger",
        "m_chapter_titan": "Arrives Legend",
        "m_reading_hours": "Little Witch Academia Ledger Ledger",
        "m_reading_time_lord": "Magic Shiny Mantle Mantle",
        "m_manga_collector": "No Magic Ledger",
        "m_library_legend": "Shiny Reliquary",
        "m_first_complete": "Atsuko Kagari Coda",
        "m_hundred_club": "Spell Cast Network",
        "m_first_day": "Akko Dawn",
        "m_first_rating": "No Magic Eye",
        "m_ten_thousand_pages": "Atsuko Kagari Gauge",
        "m_volume_collector": "Rodentata Storehouse Storehouse",
        "m_year_explorer": "Akko Arrives Quest",
        "m_century_reader": "Magic Seal",
        "m_five_hundred_ch": "Luna Nova Magical Legend",
        "m_thousand_ch": "Witch Legend Testament",
        "m_reading_ten": "Spell Tenfold",
        "m_ptr_hoarder": "Witch Index",
        "m_dropped_honesty": "Witch Circle Honesty",
        "m_season_reader": "Shiny Fan Treasury",
        "m_active_reader": "Grand Witch Chronicle Chronicle",
        "m_five_thousand_ch": "Shiny Fan Legend Standard",
        "m_ten_completed": "Shiny Fan Resolution",
        "m_fifty_completed": "Lwa Marathon Harvest",
        "m_five_hundred_completed": "Archive Legacy",
        "m_mean_score_tracker": "Grand Witch Audit",
        "m_unique_authors": "Magic Alerts Reserve",
        "m_all_status": "Spell Testament",
        "m_first_favorite": "Spellbook Cache Cache",
        "m_favorites_collector": "Grand Witch Shelf",
        "m_days_spent_reading": "Shiny Rod Ledger",

        // ── MANGA BINGE ──
        "m_binge_reader": "Spell Cast Streak",
        "m_marathon_reader": "Wand Rush",
        "m_weekend_reader": "Luna Nova Magical Run Run",
        "m_non_stop_reading": "Akko Arrives Gauntlet Gauntlet",
        "m_one_more_chapter": "Magic Classes Accord Accord",
        "m_speed_read": "Marathon Drive Drive",
        "m_double_story": "Despite Banner Banner",
        "m_triple_read": "No Magic Pinnacle",
        "m_five_a_day": "Magic Archive Pinnacle Pinnacle",
        "m_chapter_chain": "Archive Accord",
        "m_volume_binge": "Shiny Rod Vigil",
        "m_power_reader": "Cast Dominion",
        "m_half_day_read": "Cast Trial Trial",
        "m_full_day_read": "Spells Chronicle",
        "m_power_weekend": "Spell Cast Streak Streak",
        "m_binge_king": "Archive Momentum Momentum",
        "m_no_sleep_read": "No Magic Rush",
        "m_full_series_rush": "Lwa Marathon Cascade Cascade",
        "m_seven_day_challenge": "Shiny Vault Warrant Warrant",
        "m_hundred_day_read": "Lwa Marathon Legend",
        "m_volume_rush": "Despite Gauntlet Gauntlet",
        "m_series_sweep": "Shiny Chariot Proof",
        "m_genre_binge": "Little Witch Academia Binge",
        "m_author_binge": "Akko Surge",
        "m_chapter_counter_day": "Lost Words Crown",
        "m_multi_series_binge": "Spells Charge",
        "m_midnight_binge": "Witch Tempest",
        "m_new_year_binge": "Magic Alerts New Year",
        "m_forty_eight_hour": "Grand Witch Rally",
        "m_oneshot_binge": "Witch Trophies Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Rodentata Action",
        "m_genre_adventure": "Arrives Adventure",
        "m_genre_comedy": "Despite Comedy",
        "m_genre_drama": "Luna Nova Magical Drama",
        "m_genre_fantasy": "Witch Trophies Fantasy",
        "m_genre_horror": "Cast Horror",
        "m_genre_mystery": "Akko Arrives Mystery",
        "m_genre_romance": "Magic Romance",
        "m_genre_scifi": "Spell Sci-Fi",
        "m_genre_sol": "Cast Slice",
        "m_genre_sports": "Grand Witch Sports",
        "m_genre_supernatural": "Magic Alerts Supernatural",
        "m_genre_thriller": "Witch Thriller",
        "m_genre_psychological": "Spells Psychological",
        "m_genre_isekai": "Spell Isekai",
        "m_genre_shounen": "Wand Shounen",
        "m_genre_ecchi": "Shiny Vault Ecchi",
        "m_genre_mahou_shoujo": "Magic Magic Shoujo",
        "m_genre_mecha": "Witch Mecha",
        "m_genre_music": "Shiny Rod Music",
        "m_tag_isekai_new": "Magic Shiny Isekai New",
        "m_tag_harem": "Grand Witch Trials Harem",
        "m_tag_bl": "Magic Bl",
        "m_tag_gl": "Lwa Marathon Gl",
        "m_tag_historical": "Luna Nova Magical Historical",
        "m_tag_military": "Rodentata Military",
        "m_tag_school": "Akko School",
        "m_tag_martial_arts": "Shiny Vault Martial Arts",
        "m_tag_vampire": "Little Witch Academia Vampire",
        "m_tag_samurai": "Spellbook Samurai",
        "m_tag_space": "Grand Witch Space",
        "m_tag_parody": "Rodentata Parody",
        "m_tag_idol": "Little Witch Academia Idol",
        "m_tag_post_apocalyptic": "Archive Post Apocalyptic",
        "m_tag_cyberpunk": "Grand Witch Trials Cyberpunk",
        "m_tag_shoujo": "Spell Cast Shoujo",
        "m_tag_survival": "Grand Witch Survival",
        "m_tag_cooking": "Luna Nova Magical Cooking",
        "m_tag_medical": "Spell Medical",
        "m_tag_villainess": "Spells Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Magic Archive",
        "m_mega_completionist": "Shiny Fan Completion",
        "m_completion_rate_50": "Magic Classes Return",
        "m_completion_rate_75": "Rodentata Ascension",
        "m_completion_rate_90": "Shiny Fan Resolution Resolution",
        "m_no_drop": "Shiny Rod Ledger Ledger",
        "m_long_runner_complete": "Luna Nova Magical Clear Clear",
        "m_sequel_chain": "Cast Dominion Dominion",
        "m_clean_list": "Shiny Vault Crown",
        "m_from_ptr": "Atsuko Kagari Watchlist",
        "m_reread_master": "Grand Chronicle Chronicle",
        "m_oneshot_complete": "Rodentata Ascension Ascension",
        "m_same_day_start_finish": "Magic Archive Relic Relic",
        "m_revival": "Wand Mark",
        "m_zero_to_hundred": "Akko Arrives Legend",
        "m_five_genre_complete": "Magic Alerts M Five Genre",
        "m_full_collection": "Spell Registry Aegis",
        "m_batch_complete": "Spell Testament Testament",
        "m_paused_to_done": "Spell Registry Accord Accord",
        "m_completion_spree": "Words Triumph",
        "m_format_completionist": "Lost Words Completion",
        "m_catch_up": "Little Witch Academia Aegis",
        "m_multi_reread": "Witch Trophies Dominion Dominion",
        "m_dropped_recovery": "Starry Conquest",
        "m_ten_perfect_scores": "Luna Nova Magical Judgment",
        "m_complete_genre_span": "Magic Archive M Complete Genre",
        "m_monthly_completions": "Magic Classes Monthly",
        "m_yearly_completions": "Magic Shiny Epilogue",
        "m_rapid_complete": "Grand Witch Trials Finale",
        "m_author_complete": "Lost Words Endgame",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Atsuko Kagari Legacy",
        "m_mangaka_lover": "Starry Testament",
        "m_rereader": "Arrives Return",
        "m_triple_reread": "Luna Nova Mark Mark",
        "m_annual_reread": "Shiny Seal",
        "m_publisher_fan": "Little Witch Academia Accord",
        "m_artist_fan": "Magic Record",
        "m_adaptation_compare": "Magic Alerts Mantle",
        "m_source_material_fan": "Magic Classes Cache",
        "m_waiting_weekly": "Shiny Fan Weekly",
        "m_classic_reader": "Lost Words Lantern",
        "m_saga_reader": "Magic Ledger",
        "m_genre_loyalty": "Starry Loyalty",
        "m_decade_reader": "No Magic Dominion Dominion",
        "m_ln_adaptation": "Little Witch Academia Accord Accord",
        "m_original_work": "Starry Testament Testament",
        "m_long_commitment": "Grand Witch Trials Mark",
        "m_up_to_date": "Grand Witch Seal",
        "m_favorite_mangaka": "Shiny Fan Treasury Treasury",
        "m_complete_portfolio": "Words Triumph Triumph",
        "m_franchise_collector": "Spell Registry Archive",
        "m_serialization_follower": "Spellbook Handshake",
        "m_genre_master": "Arrives Master",
        "m_multi_series_author": "Magic Record Record",
        "m_format_diversity": "Grand Witch Shelf Shelf",
        "m_year_dedication": "No Magic Yearlong",
        "m_ongoing_follower": "Magic Alerts Fellowship",
        "m_genre_loyalty_50": "Wand Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Despite Explorer",
        "m_publisher_hopper": "No Magic Pinnacle Pinnacle",
        "m_tag_explorer": "Magic Shiny Explorer",
        "m_decade_hopper": "Lwa Marathon Proof Proof",
        "m_hidden_gem": "Grand Witch Trials Mark Mark",
        "m_popular_taste": "Shiny Vault Mantle Mantle",
        "m_retro_reader": "Cast Mark",
        "m_modern_reader": "Spellbook Banner Banner",
        "m_cross_demographic": "Rodentata Relic",
        "m_underdog_fan": "Cast Mark Mark",
        "m_variety_week": "Shiny Horizon Horizon",
        "m_manhwa_reader": "Luna Nova Magical Aegis Aegis",
        "m_manhua_reader": "Akko Arrives Insignia",
        "m_classic_connoisseur": "Archive Glimpse",
        "m_award_winner": "Spells Seal",
        "m_niche_explorer": "Spell Cast Horizon Horizon",
        "m_world_manga": "Little Witch Academia Aegis Aegis",
        "m_cult_classic": "Little Witch Academia Classic",
        "m_random_pick": "Luna Nova Magical Accord",
        "m_new_genre_month": "Spell Registry M New Genre",
        "m_year_completionist": "Shiny Chariot Completion",
        "m_unpopular_opinion": "Witch Circle Chronicle",
        "m_top_rated_reader": "Witch Mantle",
        "m_source_variety": "Lost Words Catalogue",
        "m_low_score_brave": "Grand Witch Trials Score Score",
        "m_short_manga_explorer": "Akko Compass",
        "m_long_manga_explorer": "Shiny Fan Survey",
        "m_serialization_explorer": "Lwa Marathon Road",

        // ── MANGA TIME ──
        "m_night_owl": "Archive Accord Accord",
        "m_early_bird": "Shiny Seal Seal",
        "m_lunch_reader": "Shiny Vault Crown Crown",
        "m_commute_reader": "No Magic Tenure Tenure",
        "m_four_am_club": "Magic Alerts Fellowship Fellowship",
        "m_new_year_read": "Shiny Pact",
        "m_all_hours": "Wand Mark Mark",
        "m_prime_time_reader": "Grand Witch Trials Dominion",
        "m_workday_reader": "Grand Standard",
        "m_sunday_read": "Luna Nova Magical Accord Accord",
        "m_morning_routine": "Akko Discipline",
        "m_night_shift_reader": "Grand Standard Standard",
        "m_seasonal_premier_read": "Rodentata Seasonal",
        "m_clock_collector": "Magic Alerts Reserve Reserve",
        "m_late_night_horror": "Shiny Vault Mark",
        "m_afternoon_reader": "Spell Mantle Mantle",
        "m_golden_hour_reader": "Witch Observance",
        "m_dawn_reader": "Despite Insignia",
        "m_twilight_reader": "Magic Ledger Ledger",
        "m_midnight_start": "Grand Witch Routine",
        "m_weekend_binge_hours": "Atsuko Kagari Momentum",
        "m_late_night_regular": "Spells Standard",
        "m_sunrise_reader": "Atsuko Kagari Insignia",
        "m_every_day_of_week": "Luna Nova Dominion",
        "m_monthly_hours": "Little Witch Academia Vigil",
        "m_bedtime_reader": "Atsuko Kagari Banner",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Akko Arrives Insignia Insignia",
        "m_webtoon_reader": "Shiny Vault Mark Mark",
        "m_full_color": "No Magic Mark",
        "m_doujin_reader": "Grand Witch Record",
        "m_anthology_reader": "Marathon Testament",
        "m_adaptation_reader": "Grand Witch Trials Dominion Dominion",
        "m_longstrip_reader": "Marathon Proof",
        "m_4koma_reader": "Words Crown Crown",
        "m_oneshot_reader": "Despite Insignia Insignia",
        "m_format_variety": "Luna Nova Gallery",
        "m_light_novel_reader": "Magic Alerts Mantle Mantle",
        "m_novel_reader": "Rodentata Relic Relic",
        "m_visual_storyteller": "Spells Standard Standard",
        "m_colored_classic": "Shiny Fan Classic",
        "m_webcomic_fan": "Starry Mantle",
        "m_manga_to_anime": "Grand Witch Record Record",
        "m_seinen_reader": "Witch Mantle Mantle",
        "m_josei_reader": "Spellbook Insignia",
        "m_award_winning_art": "Archive Decree",
        "m_debut_work": "Shiny Fan Seal",
        "m_vertical_scroll": "Starry Crown",
        "m_traditional_format": "Akko Hoard",
        "m_cross_media": "Marathon Testament Testament",
        "m_spinoff_reader": "No Magic Mark Mark",
        "m_remake_reader": "Spell Registry Insignia",
        "m_collaboration_reader": "Shiny Vault Trial",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Marathon Focus",
        "m_mega_streak": "Grand Routine",
        "m_weekly_warrior": "Lwa Marathon Weekly",
        "m_monthly_reader": "Shiny Rod Discipline",
        "m_comeback": "Spell Mark",
        "m_weekend_streak": "Shiny Vault Fever",
        "m_no_zero_days": "Lost Words Trial",
        "m_iron_will": "Lost Words Crown Crown",
        "m_habit_formed": "Shiny Fan Ledger",
        "m_consistent_pace": "Magic Alerts Scrutiny Scrutiny",
        "m_year_long": "Witch Yearlong",
        "m_double_streak": "Magic Discipline",
        "m_streak_recovery": "Magic Discipline Discipline",
        "m_daily_minimum": "Marathon Daily",
        "m_winter_streak": "Witch Observance Observance",
        "m_summer_streak": "Spellbook Promise",
        "m_morning_streak": "Despite Clock Clock",
        "m_night_streak": "Akko Discipline Discipline",
        "m_unbreakable": "Atsuko Kagari Banner Banner",
        "m_eternal_flame": "Atsuko Kagari Insignia Insignia",
        "m_chapter_a_day": "Atsuko Kagari Decree",
        "m_genre_streak": "No Magic Streak",
        "m_completion_streak": "Magic Classes Return Return",
        "m_rating_streak": "Spell Appraisal Appraisal",
        "m_multi_ch_streak": "Grand Pact",
        "m_author_streak": "Magic Alerts Calendar Calendar",
        "m_perfect_week_manga": "Grand Witch Standard",
        "m_diverse_streak": "Shiny Fan Streak Streak",

        // ── MANGA SCORING ──
        "m_critic": "Spell Registry Taste",
        "m_perfect_ten": "Little Witch Academia Perfect",
        "m_harsh_critic": "Spell Cast Scale",
        "m_fair_judge": "No Magic Eye Eye",
        "m_generous_spirit": "Starry Crown Crown",
        "m_score_all": "Marathon Reckoning",
        "m_wide_range": "Despite Decree",
        "m_controversial": "Lost Words Mark",
        "m_consistent_scorer": "Akko Arrives Grade",
        "m_score_sniper": "Marathon Reckoning Reckoning",
        "m_evolving_taste": "Shiny Chariot Proof Proof",
        "m_bell_curve": "Grand Witch Standard Standard",
        "m_picky_reader": "Archive Decree Decree",
        "m_100_rated": "Atsuko Kagari Standard",
        "m_500_rated": "Lost Words Trial Trial",
        "m_mediocre_majority": "Magic Archive Canon",
        "m_rating_spree": "Little Witch Academia Verdict Verdict",
        "m_score_variance": "Cast Measure Measure",
        "m_binge_rater": "Magic Alerts Passage Passage",
        "m_reread_rerate": "Arrives Warrant",
        "m_masterpiece_hunter": "Spell Cast Seal",
        "m_contrarian": "Spells Chronicle Chronicle",
        "m_optimist": "Shiny Rod Accord",
        "m_score_distributor": "Shiny Rodentata Judgment Judgment",
        "m_genre_critic": "Witch Trophies Critic",
        "m_mean_above_8": "Spell Cast Review",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Arrives New Year",
        "m_valentines_read": "Magic Shiny Observance",
        "m_pi_day": "Rodentata Testament",
        "m_april_fools": "Luna Nova Devotion",
        "m_international_manga_day": "Akko Arrives Chronicle",
        "m_free_comic_day": "Shiny Rodentata Aegis",
        "m_summer_solstice": "Shiny Chariot Focus Focus",
        "m_tanabata": "Words Tanabata",
        "m_friday_13th": "Shiny Fan Seal Seal",
        "m_halloween_read": "Magic Alerts Halloween",
        "m_thanksgiving_binge": "Witch Circle Charge",
        "m_christmas_read": "Spell Cast Christmas",
        "m_new_years_eve": "Shiny Vault Pilgrimage",
        "m_birthday_read": "Shiny Chariot Birthday",
        "m_holiday_marathon": "Grand Rally",
        "m_independence_day": "Rodentata Proof",
        "m_culture_day": "Luna Nova Dominion Dominion",
        "m_spring_equinox": "Arrives Warrant Warrant",
        "m_earth_day": "Rodentata Proof Proof",
        "m_labor_day": "Witch Circle Seal",
        "m_winter_solstice": "Akko Vigil",
        "m_manga_birthday": "Witch Trophies Birthday",
        "m_every_holiday_reader": "Spell Watch Watch",
        "m_consecutive_holidays": "Lost Words Watch Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Spell Registry Aegis Aegis",
        "m_fibonacci": "Magic Seal Seal",
        "m_palindrome_day": "Atsuko Kagari Decree Decree",
        "m_binary_day": "Akko Arrives Chronicle Chronicle",
        "m_full_moon_read": "Shiny Fan Ledger Ledger",
        "m_leap_year_read": "Spellbook Practice",
        "m_triple_seven": "Akko Aegis",
        "m_thousand_complete": "Magic Archive Legend",
        "m_nice": "Spells Seal Seal",
        "m_power_level_chapters": "Witch Circle Chronicle Chronicle",
        "m_answer_42": "Shiny Fan Aegis",
        "m_square_number": "Lost Words Mark Mark",
        "m_prime_count": "Starry Mantle Mantle",
        "m_matching_date": "Grand Witch Trials Pinnacle",
        "m_century_chapter": "Luna Nova Magical Decree",
        "m_pi_chapters": "Witch Trophies Proof",
        "m_synchronicity": "No Magic Emblem Emblem",
        "m_world_record": "Wand Dominion",
        "m_genre_clash": "Little Witch Academia Clash",
        "m_time_traveler": "Magic Shiny Crown",
        "m_double_digits": "Magic Alerts Warrant",
        "m_one_two_three": "Grand Witch Seal Seal",
        "m_lucky_seven": "Spellbook Insignia Insignia",
        "m_exact_hundred_ch": "Magic Shiny Legend",
        "m_year_match_count": "Grand Yearlong",
        "m_chapter_match_date": "Luna Nova Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Witch Index Index",
        "m_manhwa_format": "Luna Nova Gallery Gallery",
        "m_manhua_format": "Shiny Fan Hoard",
        "m_ln_format": "Magic Shiny Index Index",
        "m_oneshot_format": "Magic Classes Library",
        "m_doujin_format": "Grand Witch Trials Storehouse Storehouse",
        "m_novel_format": "Spell Registry Cache",
        "m_format_master_manga": "Magic Treasury Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Shiny Fan Link",
        "m_meta_collector": "Spell Cast Reliquary",
        "m_meta_category_starter": "Magic Alerts Standard",
        "m_meta_tier_climber": "Spells Token Token",
        "m_meta_tier_max": "Witch Circle Token",
        "m_meta_xp_earner": "Lost Words Anchor Anchor",
        "m_meta_difficulty_easy": "Magic Shiny Panel Panel",
        "m_meta_difficulty_hard": "Magic Shiny Node",
        "m_meta_unlock_spree": "Rodentata Marker",
        "m_meta_completionist": "Words Completion",
        "m_meta_diverse": "Spell Anchor",
        "m_meta_dominator": "Archive Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#020008",
        primary: "#5c2ada",
        secondary: "#c84848",
        accent: "#d8c8f8",
    },
    particleColor: "#8858e8",
    backgroundDim: 0.28,
    backgroundBlur: 20,
    particleTypes: {
        stars: { label: "Magic Stars", maxCount: 25, defaultEnabled: true, defaultIntensity: 65 },
    },
    milestoneNames: {
  1: "Threadbare Generic Rank Spark",
  8: "Generic's Tarnished Omen",
  14: "Fractured Generic Rank",
  21: "Generic Rank Path",
  28: "Lowborn Legacy Myth",
  35: "Generic Rank Pulse",
  41: "Generic's Legacy Crest",
  48: "Humble Generic Mark",
  55: "Ragged Generic Rank Vow",
  61: "Generic's Faint Echo",
  68: "Lesser Generic Rank",
  75: "Generic Rank Zenith",
  81: "Doubtful Legacy Bloom",
  88: "Generic Rank Sigil",
  95: "Generic's Legacy Flame",
  102: "Really Cool Generic Spark",
  108: "Awakened Generic Rank Omen",
  115: "Generic's Resolute Seal",
  122: "Rising Generic Rank",
  128: "Generic Rank Myth",
  135: "Dauntless Legacy Pulse",
  142: "Generic Rank Crest",
  149: "Generic's Legacy Mark",
  155: "Fresh Generic Vow",
  162: "Valiant Generic Rank Echo",
  169: "Generic's Prime Crown",
  175: "Polished Generic Rank",
  182: "Generic Rank Bloom",
  189: "Stormlit Legacy Sigil",
  195: "Generic Rank Flame",
  202: "Generic's Legacy Spark",
  209: "Tempered Generic Omen",
  216: "Trusted Generic Rank Seal",
  222: "Generic's Steadfast Path",
  229: "Ironclad Generic Rank",
  236: "Veteran Legacy Pulse",
  242: "Core Legacy Crest",
  249: "Generic Rank Mark",
  256: "Generic's Legacy Vow",
  262: "Formidable Generic Echo",
  269: "Lucid Generic Rank Crown",
  276: "Generic's Ranked Zenith",
  283: "Fabled Generic Rank",
  289: "Grand Legacy Sigil",
  296: "Seasoned Legacy Flame",
  303: "Generic Rank Spark",
  309: "Generic's Legacy Omen",
  316: "Valorous Generic Seal",
  323: "Stalwart Generic Rank Path",
  330: "Generic's Commanding Myth",
  336: "Refined Generic Rank",
  343: "Unbroken Legacy Crest",
  350: "Blazing Legacy Mark",
  356: "Generic Rank Vow",
  363: "Generic's Legacy Echo",
  370: "Peerless Generic Crown",
  376: "Ardent Generic Rank Zenith",
  383: "Generic's Focused Bloom",
  390: "Vigilant Generic Rank",
  397: "Dominant Legacy Flame",
  403: "Elite Legacy Spark",
  410: "Generic Rank Omen",
  417: "Generic's Legacy Seal",
  423: "Sovereign Generic Path",
  430: "Regal Generic Rank Myth",
  437: "Generic's Crowned Pulse",
  444: "Mythborn Generic Rank",
  450: "Limitless Legacy Mark",
  457: "Radiant Legacy Vow",
  464: "Generic Rank Echo",
  470: "Generic's Legacy Crown",
  477: "Climactic Generic Zenith",
  484: "Epic Generic Rank Bloom",
  490: "Generic's Unreal Sigil",
  497: "Peak Generic Rank",
  504: "Supreme Legacy Spark",
  511: "Exalted Legacy Omen",
  517: "Generic Rank Seal",
  524: "Generic's Legacy Path",
  531: "Celestial Generic Myth",
  537: "Phantom Generic Rank Pulse",
  544: "Generic's Crimson Crest",
  551: "Silver Generic Rank",
  557: "Golden Legacy Vow",
  564: "Feral Legacy Echo",
  571: "Generic Rank Crown",
  578: "Generic's Legacy Zenith",
  584: "Dread Generic Bloom",
  591: "Luminous Generic Rank Sigil",
  598: "Generic's Thunderous Flame",
  604: "Ultraviolet Generic Rank",
  611: "Unleashed Legacy Omen",
  618: "Secret Legacy Seal",
  625: "Final Generic Path",
  631: "Generic's Legacy Myth",
  638: "Worldclass Generic Pulse",
  645: "Lawless Generic Rank Crest",
  651: "Generic's Chosen Mark",
  658: "Fearless Generic Rank",
  665: "Overdrive Legacy Echo",
  671: "Cinematic Legacy Crown",
  678: "Impossible Generic Zenith",
  685: "Generic's Legacy Bloom",
  692: "Canonized Generic Sigil",
  698: "Ascendant Generic Rank Flame",
  705: "Generic's Transfigured Spark",
  712: "Immortal Generic Rank",
  718: "Eclipsed Legacy Seal",
  725: "Astral Legacy Path",
  732: "Sublime Generic Myth",
  739: "Generic's Legacy Pulse",
  745: "Prismatic Generic Crest",
  752: "Abyssal Generic Rank Mark",
  759: "Generic's Unbound Vow",
  765: "Eternal Generic Rank",
  772: "Cosmic Legacy Crown",
  779: "Transcendent Legacy Zenith",
  785: "Perfected Generic Bloom",
  792: "Generic's Legacy Sigil",
  799: "Ultimate Generic Flame",
  806: "Mythic Generic Rank Spark",
  812: "Generic's Godlike Omen",
  819: "Canonical Generic Rank",
  826: "Reality-Bent Legacy Path",
  832: "Heavenly Legacy Myth",
  839: "Absolute Generic Pulse",
  846: "Untouchable Generic Crest",
  852: "Timeless Generic Mark",
  859: "Empyrean Generic Rank Vow",
  866: "Generic's Primordial Echo",
  873: "Omniscient Generic Rank",
  879: "Unfathomed Legacy Zenith",
  886: "Apocalyptic Legacy Bloom",
  893: "Seraphic Generic Sigil",
  899: "Omega Generic Flame",
  906: "Final Generic Spark",
  913: "Crowned Generic Rank Omen",
  920: "Generic's Mythic Seal",
  926: "Absolute Generic Rank",
  933: "Eternal Legacy Myth",
  940: "Cosmic Legacy Pulse",
  946: "Transcendent Generic Crest",
  953: "Perfected Generic Mark",
  960: "Definitive Generic Vow",
  966: "Ultimate Generic Rank Echo",
  973: "Generic's Infinite Crown",
  980: "Sovereign Generic Rank",
  987: "Celestial Legacy Bloom",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate Generic Rank"
},
}
