import { AnimeThemeConfig } from "./types"
import { GiStarSwirl, GiMusicalNotes, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiCrystalBall, GiFireworkRocket } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const luckyStarTheme: AnimeThemeConfig = {
    id: "lucky-star",
    displayName: "Lucky☆Star",
    description: "Konata Izumi and her friends navigate high school life with moe charm, otaku obsessions, and the eternal question of how to eat a chocolate cornet. Slice of life at its most endearingly absurd.",
    fontFamily: "'Fredoka One', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap",
    cssVars: {
        "--color-brand-200": "210 185 240",
        "--color-brand-300": "172 145 228",
        "--color-brand-400": "132 100 212",
        "--color-brand-500": "98 62 192",
        "--color-brand-600": "70 38 155",
        "--color-brand-700": "46 20 118",
        "--color-brand-800": "26 8 78",
        "--color-brand-900": "12 3 44",
        "--color-brand-950": "5 0 20",
        "--brand": "98 62 192",
        "--background": "#030010",
        "--paper": "#060018",
        "--color-gray-950": "3 0 16",
        "--color-gray-900": "8 2 28",
        "--color-gray-800": "18 6 50",
        "--color-gray-700": "30 12 78",
        "--color-gray-600": "48 22 112",
        "--color-gray-500": "72 42 148",
        "--color-gray-400": "105 72 185",
        "--color-gray-300": "145 112 215",
        "--color-gray-200": "188 158 235",
        "--color-gray-100": "225 208 248",
        "--color-gray-50": "248 240 254",
    },
    sidebarOverrides: {
        "home": { icon: GiStarSwirl, label: "Ryouou High" },
        "schedule": { icon: GiAlarmClock, label: "Class Schedule" },
        "manga": { icon: LuBookOpen, label: "Manga Collection" },
        "lists": { icon: GiScrollUnfurled, label: "Friend List" },
        "discover": { icon: GiBullseye, label: "New Interests" },
        "torrent-list": { icon: GiMusicalNotes, label: "Anime Vault" },
        "debrid": { icon: GiCrystalBall, label: "Lucky Channel" },
        "unmatched": { icon: GiHeartKey, label: "Uncharted Interests" },
        "enmasse": { icon: GiResize, label: "School Festival" },
        "scan-summaries": { icon: TbReportSearch, label: "Lucky Reports" },
        "auto-downloader": { icon: LuRss, label: "Anime Alerts" },
        "community": { icon: GiFireworkRocket, label: "Otaku Circle" },
        "achievements": { icon: GiTrophyCup, label: "Lucky Trophies" },
        "milestones": { icon: LuFlag, label: "Lucky Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Lucky Alerts" },
        "theme-manager": { icon: GiPalette, label: "Lucky Colors" },
        "extensions": { icon: BiExtension, label: "Otaku Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Lucky Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Konata Config" },
    },
    achievementNames: {
        "a_first_episode": "Chocolate Cornet Debate",
        "a_first_complete": "School Year Complete",
        "a_hundred_club": "Hundred Lucky Episodes",
        "a_binge_king": "Lucky Marathon",
        "a_completionist": "Lucky Star Complete",
        "a_loyal_fan": "Loyal Otaku",
        "m_first_chapter": "First 4-Koma",
        "m_completionist": "Full 4-Koma Collection",
    },
    musicUrl: "",
    previewColors: {
        bg: "#030010",
        primary: "#623ec0",
        secondary: "#ff69b4",
        accent: "#f0d020",
    },
    particleColor: "#8060e0",
    backgroundDim: 0.25,
    backgroundBlur: 15,
    milestoneNames: {
        1: "Ordinary Student",
        5: "Otaku Initiate",
        15: "Anime Expert",
        30: "Lucky Star Regular",
        50: "Comiket Veteran",
        75: "Lucky Channel Star",
        100: "Full-Time Otaku",
    },
}
