import { AnimeThemeConfig } from "./types"
import { GiSawedOffShotgun, GiCherish, GiCoffeeCup, GiTargetArrows, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiDramaMasks, GiHeartKey, GiStarFormation } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const lycorisRecoilTheme: AnimeThemeConfig = {
    id: "lycoris-recoil",
    displayName: "Lycoris Recoil",
    description: "Former DA agent Chisato Nishikigi and reserved marksman Takina Inoue run the LycoReco café by day — and protect the city as elite Lycoris operatives by night, in a thrilling action series wrapped in cherry-blossom warmth.",
    fontFamily: "'Zen Kaku Gothic New', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Zen+Kaku+Gothic+New:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "255 190 210",
        "--color-brand-300": "248 150 178",
        "--color-brand-400": "235 100 140",
        "--color-brand-500": "210 58 100",
        "--color-brand-600": "170 28 65",
        "--color-brand-700": "125 10 40",
        "--color-brand-800": "80 0 22",
        "--color-brand-900": "42 0 10",
        "--color-brand-950": "20 0 4",
        "--brand": "210 58 100",
        "--background": "#040101",
        "--paper": "#0e0304",
        "--color-gray-950": "4 1 1",
        "--color-gray-900": "10 4 5",
        "--color-gray-800": "20 8 10",
        "--color-gray-700": "35 14 18",
        "--color-gray-600": "56 24 30",
        "--color-gray-500": "88 45 55",
        "--color-gray-400": "130 80 92",
        "--color-gray-300": "172 120 135",
        "--color-gray-200": "210 162 175",
        "--color-gray-100": "235 198 208",
        "--color-gray-50": "250 228 235",
    },
    sidebarOverrides: {
        "home": { icon: GiCoffeeCup, label: "LycoReco Café" },
        "schedule": { icon: GiAlarmClock, label: "Mission Schedule" },
        "manga": { icon: LuBookOpen, label: "Field Reports" },
        "lists": { icon: GiFlowerEmblem, label: "Target Registry" },
        "discover": { icon: GiBullseye, label: "New Missions" },
        "torrent-list": { icon: GiSawedOffShotgun, label: "Weapon Cache" },
        "debrid": { icon: GiDramaMasks, label: "Covert Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Packages" },
        "enmasse": { icon: GiResize, label: "Joint Operations" },
        "scan-summaries": { icon: TbReportSearch, label: "Mission Logs" },
        "auto-downloader": { icon: LuRss, label: "DA Intel Feed" },
        "community": { icon: GiCherish, label: "Chisato's Circle" },
        "achievements": { icon: GiTrophy, label: "Lycoris Awards" },
        "milestones": { icon: LuFlag, label: "DA Milestones" },
        "search": { icon: FiSearch, label: "Target Search" },
        "notifications": { icon: LuBell, label: "DA Alerts" },
        "theme-manager": { icon: GiPalette, label: "Café Ambiance" },
        "extensions": { icon: BiExtension, label: "DA Modules" },
        "sync": { icon: IoCloudOfflineOutline, label: "Radio Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Takina's Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Customer",
        "a_episode_counter": "Devoted Agent Mark",
        "a_episode_titan": "Covert Vault Relic",
        "a_hours_invested": "Da Intel Proof",
        "a_time_lord": "Veteran Lycoris",
        "a_anime_collector": "Lycoris Archive",
        "a_library_legend": "DA Database",
        "a_first_complete": "Mission Complete",
        "a_hundred_club": "Hundred Targets",
        "a_first_day": "Winter Cafe Seal",
        "a_first_rating": "Covert Vault Appraisal",
        "a_ten_thousand_min": "Mind Chisato Standard",
        "a_season_veteran": "Mind Chisato Library",
        "a_year_explorer": "Wish Crystal Map",
        "a_century_watcher": "Endless Duty Ledger",
        "a_five_hundred_eps": "Cafe Action Dominion",
        "a_thousand_eps": "Lycoris Drama Record",
        "a_watching_ten": "Da Tech Acclaim",
        "a_ptw_hoarder": "Target Registry Library",
        "a_dropped_honesty": "Da Tech Summit",
        "a_five_thousand_eps": "Hidden Bloom Warrant",
        "a_ten_completed": "Hidden File Afterglow",
        "a_fifty_completed": "Partners Bond Ascension",
        "a_five_hundred_completed": "Da Tech Clear",
        "a_mean_score_tracker": "Lycoris Recoil Verdict",
        "a_unique_studios": "Lycoris Drama Collection",
        "a_days_spent_watching": "Takina's Notes Dominion",
        "a_all_status": "Mission Replay Testament",
        "a_first_favorite": "Winter Caf Cabinet",
        "a_favorites_collector": "Lycoreco Caf Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Takina Inoue Drive",
        "a_marathon_runner": "Chisato's Sprint",
        "a_weekend_warrior": "Covert Vault Ordeal",
        "a_non_stop": "Lycoris Archive Fever",
        "a_one_more_episode": "Daily Patrol Mantle",
        "a_speed_run": "Takina Speed",
        "a_double_feature": "Da Modules Crown",
        "a_triple_threat": "Agent Streak Record",
        "a_five_a_day": "All Night Accord",
        "a_back_to_back": "Mission Filed Surge",
        "a_seasonal_binge": "Covert Vault Cascade",
        "a_cour_crusher": "Takina's Notes Ordeal",
        "a_half_day_watch": "Devoted Agent Crown",
        "a_full_day_watch": "Da Database Pinnacle",
        "a_power_weekend": "Winter Cafe Run",
        "a_binge_king": "Action Marathon",
        "a_no_sleep": "All-Night Watch",
        "a_entire_season": "Night Shift Library",
        "a_seven_day_challenge": "Da Database Mark",
        "a_hundred_day_binge": "Winter Cafe Surge",
        "a_genre_binge": "Action Marathon Binge",
        "a_studio_binge": "Devoted Agent Fever",
        "a_season_sweep": "Devoted Partner Codex",
        "a_forty_eight_hour": "Night Watch Overture",
        "a_ep_counter_day": "Hidden File Aegis",
        "a_multi_series_binge": "Target Registry Streak",
        "a_midnight_binge": "Daily Patrol Cascade",
        "a_new_year_binge": "Dawn Patrol Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Café Action",
        "a_genre_adventure": "City Adventure",
        "a_genre_comedy": "Café Chaos",
        "a_genre_drama": "Lycoris Drama",
        "a_genre_fantasy": "Wish Crystal",
        "a_genre_horror": "None Here",
        "a_genre_mystery": "Cherry Classic Mystery",
        "a_genre_romance": "Partners' Bond",
        "a_genre_scifi": "DA Tech",
        "a_genre_sol": "Hidden Bloom Slice",
        "a_genre_sports": "Night Watch Sports",
        "a_genre_supernatural": "None Here",
        "a_genre_thriller": "Partners Bond Thriller",
        "a_genre_mecha": "None Here",
        "a_genre_music": "Mind Chisato Music",
        "a_genre_psychological": "Mind of Chisato",
        "a_genre_ecchi": "Takina Inoue Ecchi",
        "a_genre_mahou_shoujo": "Agent Streak Magic Shoujo",
        "a_tag_isekai": "Da Drama Isekai",
        "a_tag_harem": "Da Alerts Harem",
        "a_tag_bl": "Night Watch Bl",
        "a_tag_gl": "Daily Patrol Gl",
        "a_tag_historical": "Former Da Historical",
        "a_tag_military": "Cafe Action Military",
        "a_tag_school": "Target Registry School",
        "a_tag_martial_arts": "Da Database Martial Arts",
        "a_tag_vampire": "Agent Streak Vampire",
        "a_tag_samurai": "Lycoris Drama Samurai",
        "a_tag_space": "Da Master Space",
        "a_tag_parody": "Artist Fan Parody",
        "a_tag_idol": "Night Watch Idol",
        "a_tag_post_apocalyptic": "Decade Lycoris Post Apocalyptic",
        "a_tag_cyberpunk": "Lycoris Archive Cyberpunk",
        "a_tag_shounen": "Decade Lycoris Shounen",
        "a_tag_seinen": "Cafe Chaos Seinen",
        "a_tag_shoujo": "Cafe Chaos Shoujo",
        "a_tag_josei": "Hidden File Josei",
        "a_tag_survival": "Lycoreco Caf Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Debrief",
        "a_mega_completionist": "DA Master",
        "a_completion_rate_50": "Agent Streak Return",
        "a_completion_rate_75": "Partners Bond Crown",
        "a_completion_rate_90": "Hidden File Resolution",
        "a_no_drop": "Cherry Classic Decree",
        "a_long_runner_complete": "Winter Cafe Clear",
        "a_sequel_chain": "Chisato's Chain",
        "a_clean_list": "Devoted Partner Relic",
        "a_from_ptw": "Artist Fan Index",
        "a_rewatch_master": "Lycoris Recoil Return",
        "a_short_complete": "Lost Packages Endgame",
        "a_same_day_start_finish": "City Adventure Pinnacle",
        "a_revival": "Endless Duty Insignia",
        "a_zero_to_hero": "New Recruit",
        "a_five_genre_complete": "Lost Packages A Five Genre",
        "a_full_franchise": "Target Registry Chronicle",
        "a_batch_complete": "Covert Vault Crown",
        "a_paused_to_done": "Hidden File Aegis Aegis",
        "a_completion_spree": "Takina Speed Triumph",
        "a_multi_rewatch": "Takina Speed Triumph Triumph",
        "a_dropped_recovery": "Devoted Agent Conquest",
        "a_ten_perfect_scores": "Winter Cafe Acclaim",
        "a_seasonal_clear": "Takina's Notes Codex",
        "a_complete_genre_span": "Da Expert A Complete Genre",
        "a_monthly_completions": "Lycoris Recoil Afterglow",
        "a_yearly_completions": "Mission Replay Epilogue",
        "a_rapid_complete": "Da Database Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Devoted Partner",
        "a_studio_devotee": "Cherry Classic Treasury",
        "a_rewatcher": "Mission Replay",
        "a_triple_rewatch": "Action Marathon Coda",
        "a_annual_tradition": "Da Database Proof",
        "a_director_fan": "Devoted Partner Trial",
        "a_voice_actor_fan": "Devoted Agent Crown Crown",
        "a_ost_lover": "Target Registry Seal",
        "a_source_reader": "Wish Crystal Cabinet",
        "a_waiting_weekly": "Cherry Classic Clock",
        "a_childhood_revisit": "Mission Logs Seal",
        "a_saga_tracker": "Da Master Standard",
        "a_genre_loyalty": "Hidden Bloom Loyalty",
        "a_decade_watcher": "Decade Lycoris",
        "a_adaptation_hunter": "Artist Fan Trial",
        "a_original_anime_fan": "Da Standard Testament",
        "a_long_commitment": "Da Database Mark Mark",
        "a_perfect_attendance": "Da Tech Standard",
        "a_favorite_studio_5": "Decade Lycoris Library",
        "a_complete_catalog": "Lycoreco Caf Seal",
        "a_franchise_collector": "Decade Lycoris Archive",
        "a_airing_follower": "Mission Logs Signal",
        "a_genre_master": "Devoted Partner Master",
        "a_staff_follower": "Decade Lycoris Oath",
        "a_multi_season_fan": "Former Da Hoard",
        "a_format_diversity": "Agent Streak Cache",
        "a_year_dedication": "Covert Vault Tenure",
        "a_season_dedication": "Cafe Action Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Action Marathon Explorer",
        "a_studio_hopper": "Lycoris Recoil Collection",
        "a_tag_explorer": "Covert Vault Explorer",
        "a_decade_hopper": "Target Registry Chronicle Chronicle",
        "a_hidden_gem": "Hidden Bloom",
        "a_popular_taste": "Night Watch Decree",
        "a_retro_appreciator": "Lycoreco Caf Aegis",
        "a_modern_viewer": "City Adventure Pinnacle Pinnacle",
        "a_cross_demographic": "Takina Inoue Pinnacle",
        "a_underdog_fan": "Da Expert Trial",
        "a_variety_week": "Decade Lycoris Horizon",
        "a_foreign_cinema": "Daily Patrol Expedition",
        "a_classic_connoisseur": "2022 Fan",
        "a_every_season": "Mission Logs Archive",
        "a_award_winner": "Mind Chisato Insignia",
        "a_niche_explorer": "Cafe Chaos Horizon",
        "a_global_anime": "Lost Packages Crown",
        "a_cult_classic": "Cherry Classic",
        "a_random_pick": "Night Watch Decree Decree",
        "a_new_genre_month": "Da Tech A New Genre",
        "a_seasonal_completionist": "Endless Duty Summit",
        "a_unpopular_opinion": "Winter Caf Standard",
        "a_top_rated_viewer": "All Night Seal",
        "a_source_variety": "Takina's Notes Storehouse",
        "a_low_score_brave": "Lycoris Archive Measure",
        "a_upcoming_watcher": "All Night Seal Seal",
        "a_short_series_explorer": "Daily Patrol Expedition Expedition",
        "a_long_series_explorer": "Da Modules Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Night Shift",
        "a_early_bird": "Dawn Patrol",
        "a_lunch_break": "Cafe Art Trial",
        "a_golden_hour": "Classic File Tenure",
        "a_four_am_club": "Takina Speed Gathering",
        "a_witching_hour": "Partners Bond Tenure",
        "a_new_year_watch": "Covert Vault Season",
        "a_midnight_premiere": "Dawn Patrol Devotion",
        "a_all_hours": "Endless Duty Seal",
        "a_dawn_warrior": "Night Watch Aegis",
        "a_afternoon_delight": "Da Intel Proof Proof",
        "a_prime_time": "Mind Chisato Insignia Insignia",
        "a_workday_watcher": "Takina Inoue Pinnacle Pinnacle",
        "a_sunday_marathon": "Winter Cafe Momentum",
        "a_rainy_day": "Partners Bond Relic",
        "a_morning_routine": "Former Da Promise",
        "a_night_shift": "Agent Streak Aegis",
        "a_twilight_zone": "Night Shift Ledger",
        "a_seasonal_premier": "Cherry Classic Cabinet",
        "a_clock_collector": "Takina Speed Repository",
        "a_weekend_binge_hours": "Cafe Chaos Streak",
        "a_late_night_regular": "Mission Replay Dominion",
        "a_sunrise_watcher": "Devoted Partner Relic Relic",
        "a_holiday_watcher": "All Night Pact",
        "a_every_day_of_week": "Mission Filed Ledger",
        "a_monthly_hours": "Night Watch Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Hidden File Record",
        "a_party_host": "Agent Streak Record Record",
        "a_social_butterfly": "Wish Crystal Company",
        "a_group_binge": "Lycoris Drama Sprint",
        "a_party_regular": "Night Shift Chronicle",
        "a_sync_viewer": "Takina Speed Standard",
        "a_commentator": "Lycoreco Caf Record",
        "a_party_marathon": "Action Marathon Vigil",
        "a_full_house": "Cafe Action Trial",
        "a_community_pillar": "Mission Replay Alliance",
        "a_watch_party_streak": "Lycoreco Caf Vigil",
        "a_diverse_party": "Former Da Seal",
        "a_late_night_party": "Mission Replay Testament Testament",
        "a_party_veteran": "Cafe Action Testament",
        "a_genre_party": "Daily Patrol Party",
        "a_weekly_party": "Takina Speed Calendar",
        "a_silent_viewer": "Da Standard Mantle",
        "a_recommendation_giver": "Cafe Chaos Network",
        "a_party_completionist": "Da Master Coda",
        "a_social_scorer": "Devoted Partner Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Da Modules Proof",
        "a_fibonacci": "Covert Vault Dominion",
        "a_palindrome_day": "Covert Vault Relic Relic",
        "a_binary_day": "Hidden Bloom Mark",
        "a_full_moon": "Mission Logs Insignia",
        "a_leap_year": "Lost Packages Devotion",
        "a_time_traveler": "Cherry Classic Record",
        "a_genre_clash": "Action Marathon Clash",
        "a_triple_seven": "Covert Vault Testament",
        "a_thousand_complete": "Da Standard Epilogue",
        "a_pi_episodes": "Takina Inoue Crown",
        "a_synchronicity": "Da Expert Anchor",
        "a_world_record": "Devoted Agent Warrant",
        "a_nice": "Mind Chisato Chronicle",
        "a_power_level": "Da Standard Testament Testament",
        "a_answer_42": "Night Watch Standard",
        "a_square_number": "Action Marathon Decree",
        "a_prime_count": "Mind Chisato Seal",
        "a_matching_date": "Da Expert Mantle",
        "a_century_episode": "Takina Inoue Mark",
        "a_double_digits": "Partners Bond Testament",
        "a_one_two_three": "Lost Packages Crown Crown",
        "a_lucky_seven": "Da Database Crown",
        "a_all_tens": "Lycoris Archive Criterion",
        "a_exact_hundred_eps": "Da Master Legend",
        "a_year_match_count": "Cherry Classic Yearlong",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Cafe Chaos Ledger",
        "a_movie_buff": "Devoted Agent Mark Mark",
        "a_ova_hunter": "Da Master Standard Standard",
        "a_ona_explorer": "Da Expert Secret",
        "a_special_watcher": "Partners Bond Relic Relic",
        "a_short_king": "Da Alerts Crown",
        "a_variety_pack": "Devoted Agent Inquiry",
        "a_film_festival": "All Night Chronicle",
        "a_music_video": "Former Da Chronicle",
        "a_tv_short": "Action Marathon Record",
        "a_movie_marathon": "Action Marathon Gauntlet",
        "a_double_length": "Da Modules Crown Crown",
        "a_anthology": "Agent Streak Aegis Aegis",
        "a_mini_series": "Winter Caf Decree",
        "a_theatrical": "Decade Lycoris Accord",
        "a_format_master": "Takina Speed Vault",
        "a_long_movie": "Endless Duty Insignia Insignia",
        "a_back_catalog": "Lycoreco Caf Standard",
        "a_cm_watcher": "Da Drama Aegis",
        "a_pv_collector": "Da Expert Storehouse",
        "a_format_balance": "Takina Speed Vault Vault",
        "a_episodic_master": "Da Drama Standard",
        "a_sequel_movie": "Lost Packages Pinnacle",
        "a_recap_watcher": "Cafe Art Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Patrol",
        "a_mega_streak": "Endless Duty",
        "a_weekly_warrior": "Cafe Action Season",
        "a_monthly_watcher": "Dawn Patrol Calendar",
        "a_comeback": "Wish Crystal Decree",
        "a_weekend_streak": "Lycoris Archive Passage",
        "a_no_zero_days": "Hidden Bloom Warrant Warrant",
        "a_iron_will": "Chisato's Resolve",
        "a_habit_formed": "Mission Filed Banner",
        "a_consistent_pace": "Da Modules Measure",
        "a_year_long": "Full Year Lycoris",
        "a_double_streak": "Devoted Partner Watch",
        "a_streak_recovery": "Da Standard Season",
        "a_daily_minimum": "Dawn Patrol Focus",
        "a_winter_streak": "Daily Patrol Watch",
        "a_summer_streak": "Partners Bond Resolve",
        "a_morning_streak": "Lycoreco Caf Clock",
        "a_night_streak": "Mission Filed Constancy",
        "a_unbreakable": "Da Alerts Proof",
        "a_eternal_flame": "Lycoris Recoil Standard",
        "a_completion_streak": "Da Master Return",
        "a_rating_streak": "Covert Vault Balance",
        "a_multi_ep_streak": "Devoted Agent Ritual",
        "a_genre_streak": "Covert Vault Streak",
        "a_studio_streak": "Wish Crystal Cabinet Cabinet",
        "a_perfect_week": "Da Expert Relic",

        // ── ANIME SCORING ──
        "a_critic": "Takina's Review",
        "a_perfect_ten": "Perfect Mission",
        "a_harsh_critic": "DA Standard",
        "a_fair_judge": "Mission Replay Balance",
        "a_generous_spirit": "Dawn Patrol Pinnacle",
        "a_score_all": "Da Intel Criterion",
        "a_wide_range": "Mind Chisato Ledger",
        "a_controversial": "Lycoreco Caf Decree",
        "a_consistent_scorer": "Cherry Classic Verdict",
        "a_score_sniper": "Lost Packages Score",
        "a_evolving_taste": "Devoted Partner Testament",
        "a_bell_curve": "Da Tech Insignia",
        "a_picky_watcher": "Da Standard Warrant",
        "a_100_rated": "Takina Speed Warrant",
        "a_500_rated": "Da Alerts Pinnacle",
        "a_mediocre_majority": "Da Expert Canon",
        "a_rating_spree": "Lycoreco Caf Review",
        "a_score_variance": "Lycoris Archive Score",
        "a_masterpiece_hunter": "Lycoreco Caf Banner",
        "a_contrarian": "Action Marathon Record Record",
        "a_optimist": "Former Da Ledger",
        "a_score_distributor": "Cafe Art Appraisal",
        "a_genre_critic": "Da Modules Critic",
        "a_mean_above_8": "Da Database Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Patrol",
        "a_valentines_weeb": "Decade Lycoris Vow",
        "a_pi_day": "Mission Replay Trial",
        "a_april_fools": "Lost Packages Devotion Devotion",
        "a_international_anime_day": "Endless Duty Record",
        "a_star_wars_day": "Winter Cafe Chronicle",
        "a_summer_solstice": "Hidden Bloom Calendar",
        "a_tanabata": "City Adventure Focus",
        "a_friday_13th": "Cafe Art Relic",
        "a_halloween_spirit": "Cafe Chaos Vow",
        "a_thanksgiving_binge": "Night Shift Run",
        "a_christmas_special": "Winter Café",
        "a_new_years_eve": "Da Database Pilgrimage",
        "a_birthday_watch": "Da Tech Vow",
        "a_holiday_marathon": "Lycoris Drama Overture",
        "a_independence_day": "Lycoris Recoil Banner",
        "a_culture_day": "Target Registry Insignia",
        "a_spring_equinox": "Lycoris Drama Decree",
        "a_earth_day": "Devoted Agent Mantle",
        "a_labor_day": "Cafe Chaos Seal",
        "a_winter_solstice": "Takina Inoue Pilgrimage",
        "a_anime_birthday": "Devoted Agent Pilgrimage",
        "a_every_holiday": "Artist Fan Resolve",
        "a_consecutive_holidays": "Partners Bond Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Wish Crystal Rank",
        "a_meta_collector": "Target Registry Hoard",
        "a_meta_category_starter": "Dawn Patrol Badge",
        "a_meta_tier_climber": "Target Registry Glyph",
        "a_meta_tier_max": "True Lycoris",
        "a_meta_xp_earner": "Cafe Art Emblem",
        "a_meta_difficulty_easy": "Mission Replay Mechanism",
        "a_meta_difficulty_hard": "All Night Writ",
        "a_meta_unlock_spree": "Cafe Action Panel",
        "a_meta_completionist": "All Files",
        "a_meta_diverse": "Covert Vault Emblem",
        "a_meta_dominator": "Night Shift Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Report",
        "m_chapter_counter": "Takina Speed Pinnacle",
        "m_chapter_titan": "Takina's Notes Relic",
        "m_reading_hours": "Cafe Art Relic Relic",
        "m_reading_time_lord": "Endless Duty Record Record",
        "m_manga_collector": "Cafe Action Ledger",
        "m_library_legend": "Target Registry Reliquary",
        "m_first_complete": "Mission Filed",
        "m_hundred_club": "Hundred Pages",
        "m_first_day": "Decade Lycoris Seal",
        "m_first_rating": "Cafe Art Eye",
        "m_ten_thousand_pages": "Decade Lycoris Gauge",
        "m_volume_collector": "Da Standard Storehouse",
        "m_year_explorer": "Night Watch Quest",
        "m_century_reader": "Daily Patrol Dominion",
        "m_five_hundred_ch": "Mind Chisato Legend",
        "m_thousand_ch": "Devoted Partner Legend",
        "m_reading_ten": "Daily Patrol Appraisal",
        "m_ptr_hoarder": "Devoted Partner Index",
        "m_dropped_honesty": "Target Registry Summit",
        "m_season_reader": "Lycoreco Caf Treasury",
        "m_active_reader": "Partners Bond Trial",
        "m_five_thousand_ch": "Action Marathon Standard",
        "m_ten_completed": "Action Marathon Resolution",
        "m_fifty_completed": "Devoted Partner Harvest",
        "m_five_hundred_completed": "Mission Filed Legacy",
        "m_mean_score_tracker": "Cherry Classic Audit",
        "m_unique_authors": "Devoted Agent Reserve",
        "m_all_status": "Partners Bond Testament Testament",
        "m_first_favorite": "Da Master Cache",
        "m_favorites_collector": "Wish Crystal Shelf",
        "m_days_spent_reading": "Takina Inoue Relic",

        // ── MANGA BINGE ──
        "m_binge_reader": "Da Tech Streak",
        "m_marathon_reader": "Mission Replay Rush",
        "m_weekend_reader": "Mission Logs Run",
        "m_non_stop_reading": "Da Master Gauntlet",
        "m_one_more_chapter": "Cafe Art Testament Testament",
        "m_speed_read": "Hidden Bloom Drive",
        "m_double_story": "Lycoris Drama Banner",
        "m_triple_read": "Lycoris Recoil Record",
        "m_five_a_day": "Former Da Insignia",
        "m_chapter_chain": "Target Registry Accord",
        "m_volume_binge": "Lycoris Archive Drive",
        "m_power_reader": "Winter Cafe Seal Seal",
        "m_half_day_read": "Wish Crystal Aegis",
        "m_full_day_read": "Da Drama Aegis Aegis",
        "m_power_weekend": "Decade Lycoris Streak",
        "m_binge_king": "Café Reading",
        "m_no_sleep_read": "Daily Patrol Rush",
        "m_full_series_rush": "Mission Replay Cascade",
        "m_seven_day_challenge": "City Adventure Warrant",
        "m_hundred_day_read": "Covert Vault Legend",
        "m_volume_rush": "Hidden File Gauntlet",
        "m_series_sweep": "Artist Fan Trial Trial",
        "m_genre_binge": "Da Drama Binge",
        "m_author_binge": "Mission Logs Surge",
        "m_chapter_counter_day": "Night Shift Ledger Ledger",
        "m_multi_series_binge": "Mind Chisato Charge",
        "m_midnight_binge": "Devoted Partner Tempest",
        "m_new_year_binge": "Devoted Agent Passage",
        "m_forty_eight_hour": "Cherry Classic Rally",
        "m_oneshot_binge": "Hidden Bloom Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Report",
        "m_genre_adventure": "Field Chapter",
        "m_genre_comedy": "Wish Crystal Comedy",
        "m_genre_drama": "DA Drama",
        "m_genre_fantasy": "Wish Chapter",
        "m_genre_horror": "None Here",
        "m_genre_mystery": "Action Marathon Mystery",
        "m_genre_romance": "Bond Chapter",
        "m_genre_scifi": "Tech Report",
        "m_genre_sol": "Takina Speed Slice",
        "m_genre_sports": "Hidden File Sports",
        "m_genre_supernatural": "None Here",
        "m_genre_thriller": "Da Expert Thriller",
        "m_genre_psychological": "Mind Report",
        "m_genre_isekai": "Cafe Action Isekai",
        "m_genre_shounen": "Classic File Shounen",
        "m_genre_ecchi": "Da Modules Ecchi",
        "m_genre_mahou_shoujo": "Wish Crystal Magic Shoujo",
        "m_genre_mecha": "Da Standard Mecha",
        "m_genre_music": "Cafe Chaos Music",
        "m_tag_isekai_new": "Cafe Art Isekai New",
        "m_tag_harem": "Da Intel Harem",
        "m_tag_bl": "Winter Caf Bl",
        "m_tag_gl": "Devoted Partner Gl",
        "m_tag_historical": "Mind Chisato Historical",
        "m_tag_military": "Classic File Military",
        "m_tag_school": "Decade Lycoris School",
        "m_tag_martial_arts": "Takina Speed Martial Arts",
        "m_tag_vampire": "Hidden File Vampire",
        "m_tag_samurai": "Agent Streak Samurai",
        "m_tag_space": "Winter Caf Space",
        "m_tag_parody": "Da Standard Parody",
        "m_tag_idol": "Winter Caf Idol",
        "m_tag_post_apocalyptic": "Target Registry Post Apocalyptic",
        "m_tag_cyberpunk": "Da Intel Cyberpunk",
        "m_tag_shoujo": "All Night Shoujo",
        "m_tag_survival": "Wish Crystal Survival",
        "m_tag_cooking": "Da Tech Cooking",
        "m_tag_medical": "Partners Bond Medical",
        "m_tag_villainess": "Mission Logs Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Dossier",
        "m_mega_completionist": "DA Expert",
        "m_completion_rate_50": "Winter Caf Return",
        "m_completion_rate_75": "Da Expert Ascension",
        "m_completion_rate_90": "Lycoris Recoil Resolution",
        "m_no_drop": "Da Master Decree",
        "m_long_runner_complete": "Night Shift Clear",
        "m_sequel_chain": "Cafe Chaos Seal Seal",
        "m_clean_list": "Takina's Notes Relic Relic",
        "m_from_ptr": "All Night Watchlist",
        "m_reread_master": "Mission Replay Trial Trial",
        "m_oneshot_complete": "Mission Replay Ascension",
        "m_same_day_start_finish": "Da Database Crown Crown",
        "m_revival": "Night Shift Accord",
        "m_zero_to_hundred": "Action Marathon Banner",
        "m_five_genre_complete": "Hidden Bloom M Five Genre",
        "m_full_collection": "Da Database Proof Proof",
        "m_batch_complete": "Cherry Classic Summit",
        "m_paused_to_done": "Lycoris Recoil Standard Standard",
        "m_completion_spree": "Da Alerts Triumph",
        "m_format_completionist": "Mission Replay Completion",
        "m_catch_up": "Endless Duty Chronicle",
        "m_multi_reread": "Da Master Banner",
        "m_dropped_recovery": "Da Modules Conquest",
        "m_ten_perfect_scores": "Mission Logs Judgment",
        "m_complete_genre_span": "Cafe Action M Complete Genre",
        "m_monthly_completions": "Da Drama Return",
        "m_yearly_completions": "Cafe Action Epilogue",
        "m_rapid_complete": "City Adventure Finale",
        "m_author_complete": "Decade Lycoris Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Devoted Agent",
        "m_mangaka_lover": "Artist Fan",
        "m_rereader": "Second Read",
        "m_triple_reread": "Covert Vault Testament Testament",
        "m_annual_reread": "Action Marathon Banner Banner",
        "m_publisher_fan": "Da Alerts Mark",
        "m_artist_fan": "Cafe Chaos Insignia",
        "m_adaptation_compare": "Da Tech Insignia Insignia",
        "m_source_material_fan": "Manga First",
        "m_waiting_weekly": "Agent Streak Streak",
        "m_classic_reader": "Da Standard Lantern",
        "m_saga_reader": "Target Registry Decree",
        "m_genre_loyalty": "Da Modules Loyalty",
        "m_decade_reader": "Lycoris Archive Warrant",
        "m_ln_adaptation": "Lycoris Archive Mark",
        "m_original_work": "Hidden File Standard",
        "m_long_commitment": "Da Modules Mark",
        "m_up_to_date": "Devoted Agent Warrant Warrant",
        "m_favorite_mangaka": "Night Watch Treasury",
        "m_complete_portfolio": "Da Alerts Triumph Triumph",
        "m_franchise_collector": "Endless Duty Archive",
        "m_serialization_follower": "Night Watch Handshake",
        "m_genre_master": "Takina's Notes Master",
        "m_multi_series_author": "Target Registry Insignia Insignia",
        "m_format_diversity": "Hidden File Shelf",
        "m_year_dedication": "Daily Patrol Tenure",
        "m_ongoing_follower": "Lycoris Archive Fellowship",
        "m_genre_loyalty_50": "Devoted Partner Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Lycoris Drama Explorer",
        "m_publisher_hopper": "Da Alerts Mantle",
        "m_tag_explorer": "Artist Fan Explorer",
        "m_decade_hopper": "All Night Chronicle Chronicle",
        "m_hidden_gem": "Hidden File",
        "m_popular_taste": "Cherry Classic Record Record",
        "m_retro_reader": "Cherry Classic Accord",
        "m_modern_reader": "Mind Chisato Seal Seal",
        "m_cross_demographic": "Dawn Patrol Crown",
        "m_underdog_fan": "Cherry Classic Accord Accord",
        "m_variety_week": "Cafe Chaos Horizon Horizon",
        "m_manhwa_reader": "Lost Packages Proof",
        "m_manhua_reader": "Da Standard Mantle Mantle",
        "m_classic_connoisseur": "Mission Filed Glimpse",
        "m_award_winner": "Daily Patrol Warrant",
        "m_niche_explorer": "Da Tech Horizon",
        "m_world_manga": "Endless Duty Chronicle Chronicle",
        "m_cult_classic": "Classic File",
        "m_random_pick": "Cherry Classic Standard",
        "m_new_genre_month": "Endless Duty M New Genre",
        "m_year_completionist": "Takina Speed Fulfillment",
        "m_unpopular_opinion": "Devoted Agent Trial",
        "m_top_rated_reader": "Da Tech Record",
        "m_source_variety": "Da Standard Catalogue",
        "m_low_score_brave": "Takina Speed Score",
        "m_short_manga_explorer": "Mind Chisato Compass",
        "m_long_manga_explorer": "Action Marathon Survey",
        "m_serialization_explorer": "Da Expert Road",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Winter Caf Ledger",
        "m_commute_reader": "Partners Bond Tenure Tenure",
        "m_four_am_club": "Da Alerts Fellowship",
        "m_new_year_read": "Cafe Chaos Pact",
        "m_all_hours": "All Night Accord Accord",
        "m_prime_time_reader": "Hidden File Banner",
        "m_workday_reader": "Night Shift Accord Accord",
        "m_sunday_read": "Winter Caf Standard Standard",
        "m_morning_routine": "Night Shift Discipline",
        "m_night_shift_reader": "Decade Lycoris Accord Accord",
        "m_seasonal_premier_read": "Da Standard Seasonal",
        "m_clock_collector": "Takina Inoue Reserve",
        "m_late_night_horror": "Hidden Bloom Mark Mark",
        "m_afternoon_reader": "Daily Patrol Mantle Mantle",
        "m_golden_hour_reader": "Covert Vault Observance",
        "m_dawn_reader": "Artist Fan Mantle",
        "m_twilight_reader": "Lycoris Archive Crown",
        "m_midnight_start": "Hidden File Routine",
        "m_weekend_binge_hours": "Mission Logs Momentum",
        "m_late_night_regular": "Winter Caf Accord",
        "m_sunrise_reader": "Da Intel Mantle",
        "m_every_day_of_week": "Da Standard Warrant Warrant",
        "m_monthly_hours": "Lycoris Drama Vigil",
        "m_bedtime_reader": "Takina Speed Warrant Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Café Art",
        "m_webtoon_reader": "Lycoris Archive Mark Mark",
        "m_full_color": "Cafe Chaos Accord",
        "m_doujin_reader": "Lycoris Recoil Record Record",
        "m_anthology_reader": "Mission Logs Accord",
        "m_adaptation_reader": "Cherry Classic Banner",
        "m_longstrip_reader": "Covert Vault Trial",
        "m_4koma_reader": "Agent Streak Ledger",
        "m_oneshot_reader": "Cafe Action Mantle",
        "m_format_variety": "Da Alerts Gallery",
        "m_light_novel_reader": "All Night Insignia",
        "m_novel_reader": "Takina Speed Crown",
        "m_visual_storyteller": "Daily Patrol Testament",
        "m_colored_classic": "Lycoreco Caf Survey",
        "m_webcomic_fan": "Mission Filed Insignia",
        "m_manga_to_anime": "Adapted Mission",
        "m_seinen_reader": "Da Modules Pinnacle",
        "m_josei_reader": "Da Intel Pinnacle",
        "m_award_winning_art": "Classic File Relic",
        "m_debut_work": "Classic File Dominion",
        "m_vertical_scroll": "Target Registry Decree Decree",
        "m_traditional_format": "Da Tech Hoard",
        "m_cross_media": "Mind Chisato Accord",
        "m_spinoff_reader": "Endless Duty Accord",
        "m_remake_reader": "Mission Replay Pinnacle",
        "m_collaboration_reader": "Mission Filed Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Agent Streak",
        "m_weekly_warrior": "Da Expert Season",
        "m_monthly_reader": "Former Da Discipline",
        "m_comeback": "Action Marathon Standard Standard",
        "m_weekend_streak": "Da Intel Fever",
        "m_no_zero_days": "Lost Packages Proof Proof",
        "m_iron_will": "Resolve Chapter",
        "m_habit_formed": "Dawn Patrol Crown Crown",
        "m_consistent_pace": "Da Database Scrutiny Scrutiny",
        "m_year_long": "Year Mission",
        "m_double_streak": "Cafe Action Resolve",
        "m_streak_recovery": "Takina's Notes Resolve",
        "m_daily_minimum": "Takina Inoue Focus",
        "m_winter_streak": "Covert Vault Observance Observance",
        "m_summer_streak": "Classic File Observance",
        "m_morning_streak": "Lycoris Drama Clock",
        "m_night_streak": "Da Tech Discipline",
        "m_unbreakable": "Da Intel Warrant",
        "m_eternal_flame": "Wish Crystal Record",
        "m_chapter_a_day": "Winter Caf Ledger Ledger",
        "m_genre_streak": "Artist Fan Streak",
        "m_completion_streak": "Cherry Classic Return",
        "m_rating_streak": "Artist Fan Appraisal",
        "m_multi_ch_streak": "Da Expert Tenure",
        "m_author_streak": "Takina Inoue Calendar",
        "m_perfect_week_manga": "Endless Duty Accord Accord",
        "m_diverse_streak": "Da Master Streak",

        // ── MANGA SCORING ──
        "m_critic": "Takina's Notes",
        "m_perfect_ten": "Perfect Chapter",
        "m_harsh_critic": "All Night Scale",
        "m_fair_judge": "Cafe Art Eye Eye",
        "m_generous_spirit": "Mission Logs Decree",
        "m_score_all": "Lycoris Archive Reckoning",
        "m_wide_range": "Former Da Ledger Ledger",
        "m_controversial": "Da Drama Standard Standard",
        "m_consistent_scorer": "Lycoris Recoil Grade",
        "m_score_sniper": "Devoted Agent Reckoning",
        "m_evolving_taste": "Cafe Action Trial Trial",
        "m_bell_curve": "Former Da Accord",
        "m_picky_reader": "Da Master Ledger",
        "m_100_rated": "Former Da Standard",
        "m_500_rated": "Decade Lycoris Aegis",
        "m_mediocre_majority": "Cafe Action Canon",
        "m_rating_spree": "Lycoris Drama Verdict",
        "m_score_variance": "Takina Speed Measure",
        "m_binge_rater": "Takina Inoue Passage",
        "m_reread_rerate": "Lycoreco Caf Banner Banner",
        "m_masterpiece_hunter": "Da Drama Banner",
        "m_contrarian": "Cherry Classic Aegis",
        "m_optimist": "Mind Chisato Accord Accord",
        "m_score_distributor": "Da Expert Balance",
        "m_genre_critic": "Takina Inoue Critic",
        "m_mean_above_8": "Takina Speed Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Daily Patrol Season",
        "m_valentines_read": "Artist Fan Observance",
        "m_pi_day": "Cafe Action Testament Testament",
        "m_april_fools": "Devoted Agent Devotion",
        "m_international_manga_day": "All Night Aegis",
        "m_free_comic_day": "Mission Logs Chronicle",
        "m_summer_solstice": "City Adventure Focus Focus",
        "m_tanabata": "Da Database Tanabata",
        "m_friday_13th": "Mission Replay Dominion Dominion",
        "m_halloween_read": "Hidden Bloom Halloween",
        "m_thanksgiving_binge": "Endless Duty Charge",
        "m_christmas_read": "Night Shift Pact",
        "m_new_years_eve": "City Adventure Pilgrimage",
        "m_birthday_read": "Da Modules Focus",
        "m_holiday_marathon": "Night Watch Rally",
        "m_independence_day": "Cherry Classic Aegis Aegis",
        "m_culture_day": "Decade Lycoris Seal Seal",
        "m_spring_equinox": "Hidden Bloom Dominion",
        "m_earth_day": "Da Modules Trial",
        "m_labor_day": "Night Shift Seal",
        "m_winter_solstice": "Dawn Patrol Focus Focus",
        "m_manga_birthday": "Da Database Ritual",
        "m_every_holiday_reader": "Takina's Notes Watch",
        "m_consecutive_holidays": "Mission Replay Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Winter Cafe Aegis",
        "m_fibonacci": "Partners Bond Dominion",
        "m_palindrome_day": "Cafe Action Relic",
        "m_binary_day": "Dawn Patrol Proof",
        "m_full_moon_read": "Da Intel Crown",
        "m_leap_year_read": "Da Master Practice",
        "m_triple_seven": "Cafe Art Trial Trial",
        "m_thousand_complete": "Cafe Art Ascension",
        "m_nice": "Target Registry Seal Seal",
        "m_power_level_chapters": "Action Marathon Aegis",
        "m_answer_42": "Da Intel Trial",
        "m_square_number": "Wish Crystal Standard",
        "m_prime_count": "Cafe Art Pinnacle",
        "m_matching_date": "Takina's Notes Mantle",
        "m_century_chapter": "Winter Cafe Decree",
        "m_pi_chapters": "Da Modules Proof Proof",
        "m_synchronicity": "Artist Fan Emblem",
        "m_world_record": "Lost Packages Warrant",
        "m_genre_clash": "Hidden File Clash",
        "m_time_traveler": "Lycoris Recoil Decree",
        "m_double_digits": "Da Standard Dominion",
        "m_one_two_three": "Mission Filed Banner Banner",
        "m_lucky_seven": "Da Tech Record Record",
        "m_exact_hundred_ch": "Partners Bond Legend",
        "m_year_match_count": "Agent Streak Routine",
        "m_chapter_match_date": "Dawn Patrol Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Da Standard Index",
        "m_manhwa_format": "Hidden Bloom Gallery",
        "m_manhua_format": "Covert Vault Storehouse",
        "m_ln_format": "Cafe Art Index",
        "m_oneshot_format": "Cafe Action Index",
        "m_doujin_format": "Lycoris Drama Cabinet",
        "m_novel_format": "Devoted Agent Reserve Reserve",
        "m_format_master_manga": "Lycoris Drama Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Lycoris Recoil Link",
        "m_meta_collector": "Decade Lycoris Reliquary",
        "m_meta_category_starter": "Da Alerts Standard",
        "m_meta_tier_climber": "Mind Chisato Token",
        "m_meta_tier_max": "Lycoris Complete",
        "m_meta_xp_earner": "Da Standard Anchor",
        "m_meta_difficulty_easy": "Cafe Art Panel",
        "m_meta_difficulty_hard": "Daily Patrol Node",
        "m_meta_unlock_spree": "Da Standard Marker",
        "m_meta_completionist": "Full Library",
        "m_meta_diverse": "Cafe Action Anchor",
        "m_meta_dominator": "Target Registry Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#040101",
        primary: "#d23a64",
        secondary: "#aa1c41",
        accent: "#b0b8c8",
    },
    particleColor: "#e878a0",
    backgroundDim: 0.28,
    backgroundBlur: 16,
    particleTypes: {
        cherry_petals: { label: "Cherry Petals", maxCount: 20, defaultEnabled: true, defaultIntensity: 60 },
        golden_sparks: { label: "Golden Sparks", maxCount: 12, defaultEnabled: true, defaultIntensity: 35 },
    },
    milestoneNames: {
  1: "Threadbare Generic Rank Spark",
  8: "Generic's Tarnished Omen",
  14: "Fractured Generic Rank",
  21: "Generic Rank Path",
  28: "Lowborn Legacy Myth",
  35: "Generic Rank Pulse",
  41: "Generic's Legacy Crest",
  48: "Humble Generic Mark",
  55: "Ragged Generic Rank Vow",
  61: "Generic's Faint Echo",
  68: "Lesser Generic Rank",
  75: "Generic Rank Zenith",
  81: "Doubtful Legacy Bloom",
  88: "Generic Rank Sigil",
  95: "Generic's Legacy Flame",
  102: "Really Cool Generic Spark",
  108: "Awakened Generic Rank Omen",
  115: "Generic's Resolute Seal",
  122: "Rising Generic Rank",
  128: "Generic Rank Myth",
  135: "Dauntless Legacy Pulse",
  142: "Generic Rank Crest",
  149: "Generic's Legacy Mark",
  155: "Fresh Generic Vow",
  162: "Valiant Generic Rank Echo",
  169: "Generic's Prime Crown",
  175: "Polished Generic Rank",
  182: "Generic Rank Bloom",
  189: "Stormlit Legacy Sigil",
  195: "Generic Rank Flame",
  202: "Generic's Legacy Spark",
  209: "Tempered Generic Omen",
  216: "Trusted Generic Rank Seal",
  222: "Generic's Steadfast Path",
  229: "Ironclad Generic Rank",
  236: "Veteran Legacy Pulse",
  242: "Core Legacy Crest",
  249: "Generic Rank Mark",
  256: "Generic's Legacy Vow",
  262: "Formidable Generic Echo",
  269: "Lucid Generic Rank Crown",
  276: "Generic's Ranked Zenith",
  283: "Fabled Generic Rank",
  289: "Grand Legacy Sigil",
  296: "Seasoned Legacy Flame",
  303: "Generic Rank Spark",
  309: "Generic's Legacy Omen",
  316: "Valorous Generic Seal",
  323: "Stalwart Generic Rank Path",
  330: "Generic's Commanding Myth",
  336: "Refined Generic Rank",
  343: "Unbroken Legacy Crest",
  350: "Blazing Legacy Mark",
  356: "Generic Rank Vow",
  363: "Generic's Legacy Echo",
  370: "Peerless Generic Crown",
  376: "Ardent Generic Rank Zenith",
  383: "Generic's Focused Bloom",
  390: "Vigilant Generic Rank",
  397: "Dominant Legacy Flame",
  403: "Elite Legacy Spark",
  410: "Generic Rank Omen",
  417: "Generic's Legacy Seal",
  423: "Sovereign Generic Path",
  430: "Regal Generic Rank Myth",
  437: "Generic's Crowned Pulse",
  444: "Mythborn Generic Rank",
  450: "Limitless Legacy Mark",
  457: "Radiant Legacy Vow",
  464: "Generic Rank Echo",
  470: "Generic's Legacy Crown",
  477: "Climactic Generic Zenith",
  484: "Epic Generic Rank Bloom",
  490: "Generic's Unreal Sigil",
  497: "Peak Generic Rank",
  504: "Supreme Legacy Spark",
  511: "Exalted Legacy Omen",
  517: "Generic Rank Seal",
  524: "Generic's Legacy Path",
  531: "Celestial Generic Myth",
  537: "Phantom Generic Rank Pulse",
  544: "Generic's Crimson Crest",
  551: "Silver Generic Rank",
  557: "Golden Legacy Vow",
  564: "Feral Legacy Echo",
  571: "Generic Rank Crown",
  578: "Generic's Legacy Zenith",
  584: "Dread Generic Bloom",
  591: "Luminous Generic Rank Sigil",
  598: "Generic's Thunderous Flame",
  604: "Ultraviolet Generic Rank",
  611: "Unleashed Legacy Omen",
  618: "Secret Legacy Seal",
  625: "Final Generic Path",
  631: "Generic's Legacy Myth",
  638: "Worldclass Generic Pulse",
  645: "Lawless Generic Rank Crest",
  651: "Generic's Chosen Mark",
  658: "Fearless Generic Rank",
  665: "Overdrive Legacy Echo",
  671: "Cinematic Legacy Crown",
  678: "Impossible Generic Zenith",
  685: "Generic's Legacy Bloom",
  692: "Canonized Generic Sigil",
  698: "Ascendant Generic Rank Flame",
  705: "Generic's Transfigured Spark",
  712: "Immortal Generic Rank",
  718: "Eclipsed Legacy Seal",
  725: "Astral Legacy Path",
  732: "Sublime Generic Myth",
  739: "Generic's Legacy Pulse",
  745: "Prismatic Generic Crest",
  752: "Abyssal Generic Rank Mark",
  759: "Generic's Unbound Vow",
  765: "Eternal Generic Rank",
  772: "Cosmic Legacy Crown",
  779: "Transcendent Legacy Zenith",
  785: "Perfected Generic Bloom",
  792: "Generic's Legacy Sigil",
  799: "Ultimate Generic Flame",
  806: "Mythic Generic Rank Spark",
  812: "Generic's Godlike Omen",
  819: "Canonical Generic Rank",
  826: "Reality-Bent Legacy Path",
  832: "Heavenly Legacy Myth",
  839: "Absolute Generic Pulse",
  846: "Untouchable Generic Crest",
  852: "Timeless Generic Mark",
  859: "Empyrean Generic Rank Vow",
  866: "Generic's Primordial Echo",
  873: "Omniscient Generic Rank",
  879: "Unfathomed Legacy Zenith",
  886: "Apocalyptic Legacy Bloom",
  893: "Seraphic Generic Sigil",
  899: "Omega Generic Flame",
  906: "Final Generic Spark",
  913: "Crowned Generic Rank Omen",
  920: "Generic's Mythic Seal",
  926: "Absolute Generic Rank",
  933: "Eternal Legacy Myth",
  940: "Cosmic Legacy Pulse",
  946: "Transcendent Generic Crest",
  953: "Perfected Generic Mark",
  960: "Definitive Generic Vow",
  966: "Ultimate Generic Rank Echo",
  973: "Generic's Infinite Crown",
  980: "Sovereign Generic Rank",
  987: "Celestial Legacy Bloom",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate Generic Rank"
},
}
