import { AnimeThemeConfig } from "./types"
import { GiLanternFlame, GiMagicLamp, GiAncientSword, GiCrown, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiObelisk } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const magiTheme: AnimeThemeConfig = {
    id: "magi",
    displayName: "Magi: The Labyrinth of Magic",
    description: "In a world of dungeons containing ancient treasures, young Magi Aladdin and wanderer Alibaba set out to capture the dungeon Amon — and are drawn into a grand conflict over the fate of the world.",
    fontFamily: "'Cinzel', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "255 225 165",
        "--color-brand-300": "248 200 112",
        "--color-brand-400": "235 172 55",
        "--color-brand-500": "215 140 0",
        "--color-brand-600": "172 108 0",
        "--color-brand-700": "130 78 0",
        "--color-brand-800": "88 50 0",
        "--color-brand-900": "50 28 0",
        "--color-brand-950": "26 14 0",
        "--brand": "215 140 0",
        "--background": "#060300",
        "--paper": "#0e0900",
        "--color-gray-950": "6 3 0",
        "--color-gray-900": "14 9 0",
        "--color-gray-800": "26 17 4",
        "--color-gray-700": "44 30 8",
        "--color-gray-600": "68 50 18",
        "--color-gray-500": "105 80 38",
        "--color-gray-400": "148 122 78",
        "--color-gray-300": "186 163 120",
        "--color-gray-200": "214 195 160",
        "--color-gray-100": "232 220 194",
        "--color-gray-50": "245 238 225",
    },
    sidebarOverrides: {
        "home": { icon: GiObelisk, label: "Dungeon Gate" },
        "schedule": { icon: GiAlarmClock, label: "Dungeon Schedule" },
        "manga": { icon: LuBookOpen, label: "Magi Files" },
        "lists": { icon: GiMagicLamp, label: "Djinn Registry" },
        "discover": { icon: GiBullseye, label: "Dungeon Hunt" },
        "torrent-list": { icon: GiLanternFlame, label: "Magic Cache" },
        "debrid": { icon: GiCrown, label: "King Store" },
        "unmatched": { icon: GiAncientSword, label: "Unknown Dungeons" },
        "enmasse": { icon: GiResize, label: "Kingdom Deploy" },
        "scan-summaries": { icon: TbReportSearch, label: "Dungeon Reports" },
        "auto-downloader": { icon: LuRss, label: "Magic Feed" },
        "community": { icon: GiMagicLamp, label: "Dungeon Conquerors" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Djinn Alerts" },
        "achievements": { icon: GiTrophy, label: "King Vessels" },
        "milestones": { icon: LuFlag, label: "Djinn Goals" },
        "theme-manager": { icon: GiPalette, label: "Desert Colors" },
        "extensions": { icon: BiExtension, label: "Djinn Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Rukh Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Magi Settings" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "Djinn Equip",
        "a_episode_counter": "Dungeon Critic Mark",
        "a_episode_titan": "Burden Depth Relic",
        "a_hours_invested": "Dark Rukh Proof",
        "a_time_lord": "Dungeon Veteran",
        "a_anime_collector": "Djinn Collection",
        "a_library_legend": "Solomon's Archives",
        "a_first_complete": "King Vessel",
        "a_hundred_club": "Hundred Dungeons",
        "a_first_day": "All Dungeons Seal",
        "a_first_rating": "Burden Depth Appraisal",
        "a_ten_thousand_min": "Night Conquest Standard",
        "a_season_veteran": "Night Conquest Library",
        "a_year_explorer": "King's Burden Map",
        "a_century_watcher": "Desert Return Ledger",
        "a_five_hundred_eps": "Djinn Alerts Dominion",
        "a_thousand_eps": "Hidden Dungeon Record",
        "a_watching_ten": "Magic Carpet Ride Acclaim",
        "a_ptw_hoarder": "Aladdin's Friend Library",
        "a_dropped_honesty": "Magic Carpet Ride Summit",
        "a_five_thousand_eps": "Desert Streak Warrant",
        "a_ten_completed": "Dungeon Hunt Afterglow",
        "a_fifty_completed": "Ohtaka Classic Ascension",
        "a_five_hundred_completed": "Magic Carpet Ride Clear",
        "a_mean_score_tracker": "Dungeon Revisit Verdict",
        "a_unique_studios": "Hidden Dungeon Collection",
        "a_days_spent_watching": "Aladdin's Flight Dominion",
        "a_all_status": "Arabian Classic Testament",
        "a_first_favorite": "All Vessels Cabinet",
        "a_favorites_collector": "Rukh Science Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Djinn Battle Drive",
        "a_marathon_runner": "Magic Carpet Ride",
        "a_weekend_warrior": "Burden Depth Ordeal",
        "a_non_stop": "Morgiana's Heart Fever",
        "a_one_more_episode": "Desert Winter Mantle",
        "a_speed_run": "Aladdin's Flight",
        "a_double_feature": "Daily Quest Crown",
        "a_triple_threat": "Kingdom Magic Record",
        "a_five_a_day": "Djinn Power Accord",
        "a_back_to_back": "Magic Marathon Surge",
        "a_seasonal_binge": "Burden Depth Cascade",
        "a_cour_crusher": "Aladdin's Flight Ordeal",
        "a_half_day_watch": "Dungeon Critic Crown",
        "a_full_day_watch": "Magi Expert Pinnacle",
        "a_power_weekend": "All Dungeons Run",
        "a_binge_king": "Dungeon Marathon",
        "a_no_sleep": "All-Night Conquest",
        "a_entire_season": "Magi Aladdin Library",
        "a_seven_day_challenge": "Magi Expert Mark",
        "a_hundred_day_binge": "All Dungeons Surge",
        "a_genre_binge": "Alibaba's Kingdom Binge",
        "a_studio_binge": "Dungeon Critic Fever",
        "a_season_sweep": "Endless Adventure Codex",
        "a_forty_eight_hour": "Arabian Art Overture",
        "a_ep_counter_day": "Dungeon Hunt Aegis",
        "a_multi_series_binge": "Aladdin's Friend Streak",
        "a_midnight_binge": "Desert Winter Cascade",
        "a_new_year_binge": "Dungeon Gate Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Djinn Battle",
        "a_genre_adventure": "Desert Journey",
        "a_genre_comedy": "Aladdin's Curiosity",
        "a_genre_drama": "Alibaba's Kingdom",
        "a_genre_fantasy": "Magic World",
        "a_genre_horror": "Dark Rukh",
        "a_genre_mystery": "Dungeon Marathon Mystery",
        "a_genre_romance": "Morgiana's Heart",
        "a_genre_scifi": "Rukh Science",
        "a_genre_sol": "Desert Streak Slice",
        "a_genre_sports": "Arabian Art Sports",
        "a_genre_supernatural": "Djinn Power",
        "a_genre_thriller": "Ohtaka Classic Thriller",
        "a_genre_mecha": "None Here",
        "a_genre_music": "Night Conquest Music",
        "a_genre_psychological": "King's Burden",
        "a_genre_ecchi": "Djinn Battle Ecchi",
        "a_genre_mahou_shoujo": "Kingdom Magic Magic Shoujo",
        "a_tag_isekai": "All Night Isekai",
        "a_tag_harem": "Ohtaka Fan Harem",
        "a_tag_bl": "Arabian Art Bl",
        "a_tag_gl": "Desert Winter Gl",
        "a_tag_historical": "Amon Equip Historical",
        "a_tag_military": "Djinn Alerts Military",
        "a_tag_school": "Aladdin's Friend School",
        "a_tag_martial_arts": "Magi Expert Martial Arts",
        "a_tag_vampire": "Kingdom Magic Vampire",
        "a_tag_samurai": "Hidden Dungeon Samurai",
        "a_tag_space": "Djinn Equip Space",
        "a_tag_parody": "Night Quest Parody",
        "a_tag_idol": "Arabian Art Idol",
        "a_tag_post_apocalyptic": "Unknown Dungeons Post Apocalyptic",
        "a_tag_cyberpunk": "Morgiana's Heart Cyberpunk",
        "a_tag_shounen": "Unknown Dungeons Shounen",
        "a_tag_seinen": "Desert Dawn Seinen",
        "a_tag_shoujo": "Desert Dawn Shoujo",
        "a_tag_josei": "Dungeon Hunt Josei",
        "a_tag_survival": "Rukh Science Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "All Dungeons",
        "a_mega_completionist": "Ohtaka Master",
        "a_completion_rate_50": "Kingdom Magic Return",
        "a_completion_rate_75": "Ohtaka Classic Crown",
        "a_completion_rate_90": "Dungeon Hunt Resolution",
        "a_no_drop": "Dungeon Marathon Decree",
        "a_long_runner_complete": "All Dungeons Clear",
        "a_sequel_chain": "Kingdom of Magic",
        "a_clean_list": "Endless Adventure Relic",
        "a_from_ptw": "Night Quest Index",
        "a_rewatch_master": "Dungeon Revisit Return",
        "a_short_complete": "Desert Journey Endgame",
        "a_same_day_start_finish": "Djinn Collection Pinnacle",
        "a_revival": "Desert Return Insignia",
        "a_zero_to_hero": "Wanderer to King",
        "a_five_genre_complete": "Desert Journey A Five Genre",
        "a_full_franchise": "Aladdin's Friend Chronicle",
        "a_batch_complete": "Burden Depth Crown",
        "a_paused_to_done": "Dungeon Hunt Aegis Aegis",
        "a_completion_spree": "Ohtaka Master Triumph",
        "a_multi_rewatch": "Ohtaka Master Triumph Triumph",
        "a_dropped_recovery": "Dungeon Critic Conquest",
        "a_ten_perfect_scores": "All Dungeons Acclaim",
        "a_seasonal_clear": "Aladdin's Flight Codex",
        "a_complete_genre_span": "Magic World A Complete Genre",
        "a_monthly_completions": "Dungeon Revisit Afterglow",
        "a_yearly_completions": "Arabian Classic Epilogue",
        "a_rapid_complete": "Magi Expert Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Aladdin's Friend",
        "a_studio_devotee": "Dungeon Marathon Treasury",
        "a_rewatcher": "Dungeon Revisit",
        "a_triple_rewatch": "Alibaba's Kingdom Coda",
        "a_annual_tradition": "Magi Expert Proof",
        "a_director_fan": "Endless Adventure Trial",
        "a_voice_actor_fan": "Dungeon Critic Crown Crown",
        "a_ost_lover": "Aladdin's Friend Seal",
        "a_source_reader": "King's Burden Cabinet",
        "a_waiting_weekly": "Dungeon Marathon Clock",
        "a_childhood_revisit": "Magic Carpet Seal",
        "a_saga_tracker": "Djinn Equip Standard",
        "a_genre_loyalty": "Desert Streak Loyalty",
        "a_decade_watcher": "Decade Fan",
        "a_adaptation_hunter": "Night Quest Trial",
        "a_original_anime_fan": "Carpet Ride Testament",
        "a_long_commitment": "Magi Expert Mark Mark",
        "a_perfect_attendance": "Magic Carpet Ride Standard",
        "a_favorite_studio_5": "Unknown Dungeons Library",
        "a_complete_catalog": "Rukh Science Seal",
        "a_franchise_collector": "Unknown Dungeons Archive",
        "a_airing_follower": "Magic Carpet Signal",
        "a_genre_master": "Endless Adventure Master",
        "a_staff_follower": "Unknown Dungeons Oath",
        "a_multi_season_fan": "Amon Equip Hoard",
        "a_format_diversity": "Kingdom Magic Cache",
        "a_year_dedication": "Burden Depth Tenure",
        "a_season_dedication": "Djinn Alerts Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Alibaba's Kingdom Explorer",
        "a_studio_hopper": "Dungeon Revisit Collection",
        "a_tag_explorer": "Burden Depth Explorer",
        "a_decade_hopper": "Aladdin's Friend Chronicle Chronicle",
        "a_hidden_gem": "Hidden Dungeon",
        "a_popular_taste": "Arabian Art Decree",
        "a_retro_appreciator": "Rukh Science Aegis",
        "a_modern_viewer": "Djinn Collection Pinnacle Pinnacle",
        "a_cross_demographic": "Djinn Battle Pinnacle",
        "a_underdog_fan": "Magic World Trial",
        "a_variety_week": "Unknown Dungeons Horizon",
        "a_foreign_cinema": "Desert Winter Expedition",
        "a_classic_connoisseur": "2009 Fan",
        "a_every_season": "Magic Carpet Archive",
        "a_award_winner": "Night Conquest Insignia",
        "a_niche_explorer": "Desert Dawn Horizon",
        "a_global_anime": "Desert Journey Crown",
        "a_cult_classic": "Ohtaka Classic",
        "a_random_pick": "Arabian Art Decree Decree",
        "a_new_genre_month": "Magic Carpet Ride A New",
        "a_seasonal_completionist": "Desert Return Summit",
        "a_unpopular_opinion": "All Vessels Standard",
        "a_top_rated_viewer": "Djinn Power Seal",
        "a_source_variety": "Aladdin's Flight Storehouse",
        "a_low_score_brave": "Morgiana's Heart Measure",
        "a_upcoming_watcher": "Djinn Power Seal Seal",
        "a_short_series_explorer": "Desert Winter Expedition Expedition",
        "a_long_series_explorer": "Daily Quest Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Night Quest",
        "a_early_bird": "Desert Dawn",
        "a_lunch_break": "Decade Fan Trial",
        "a_golden_hour": "Djinn Registry Tenure",
        "a_four_am_club": "Ohtaka Master Gathering",
        "a_witching_hour": "Ohtaka Classic Tenure",
        "a_new_year_watch": "Burden Depth Season",
        "a_midnight_premiere": "Dungeon Gate Devotion",
        "a_all_hours": "Desert Return Seal",
        "a_dawn_warrior": "Arabian Art Aegis",
        "a_afternoon_delight": "Dark Rukh Proof Proof",
        "a_prime_time": "Night Conquest Insignia Insignia",
        "a_workday_watcher": "Djinn Battle Pinnacle Pinnacle",
        "a_sunday_marathon": "All Dungeons Momentum",
        "a_rainy_day": "Ohtaka Classic Relic",
        "a_morning_routine": "Amon Equip Promise",
        "a_night_shift": "Kingdom Magic Aegis",
        "a_twilight_zone": "Magi Aladdin Ledger",
        "a_seasonal_premier": "Dungeon Marathon Cabinet",
        "a_clock_collector": "Ohtaka Master Repository",
        "a_weekend_binge_hours": "Desert Dawn Streak",
        "a_late_night_regular": "Arabian Classic Dominion",
        "a_sunrise_watcher": "Endless Adventure Relic Relic",
        "a_holiday_watcher": "Djinn Power Pact",
        "a_every_day_of_week": "Magic Marathon Ledger",
        "a_monthly_hours": "Arabian Art Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Dungeon Hunt Record",
        "a_party_host": "Kingdom Magic Record Record",
        "a_social_butterfly": "King's Burden Company",
        "a_group_binge": "Hidden Dungeon Sprint",
        "a_party_regular": "Magi Aladdin Chronicle",
        "a_sync_viewer": "Ohtaka Master Standard",
        "a_commentator": "Rukh Science Record",
        "a_party_marathon": "Alibaba's Kingdom Vigil",
        "a_full_house": "Djinn Alerts Trial",
        "a_community_pillar": "Arabian Classic Alliance",
        "a_watch_party_streak": "Rukh Science Vigil",
        "a_diverse_party": "Amon Equip Seal",
        "a_late_night_party": "Arabian Classic Testament Testament",
        "a_party_veteran": "Djinn Alerts Testament",
        "a_genre_party": "Desert Winter Party",
        "a_weekly_party": "Ohtaka Master Calendar",
        "a_silent_viewer": "Carpet Ride Mantle",
        "a_recommendation_giver": "Desert Dawn Network",
        "a_party_completionist": "Djinn Equip Coda",
        "a_social_scorer": "Endless Adventure Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Daily Quest Proof",
        "a_fibonacci": "Burden Depth Dominion",
        "a_palindrome_day": "Burden Depth Relic Relic",
        "a_binary_day": "Desert Streak Mark",
        "a_full_moon": "Magic Carpet Insignia",
        "a_leap_year": "Desert Journey Devotion",
        "a_time_traveler": "Dungeon Marathon Record",
        "a_genre_clash": "Alibaba's Kingdom Clash",
        "a_triple_seven": "Burden Depth Testament",
        "a_thousand_complete": "Carpet Ride Epilogue",
        "a_pi_episodes": "Djinn Battle Crown",
        "a_synchronicity": "Magic World Anchor",
        "a_world_record": "Dungeon Critic Warrant",
        "a_nice": "Night Conquest Chronicle",
        "a_power_level": "Carpet Ride Testament Testament",
        "a_answer_42": "Arabian Art Standard",
        "a_square_number": "Alibaba's Kingdom Decree",
        "a_prime_count": "Night Conquest Seal",
        "a_matching_date": "Magic World Mantle",
        "a_century_episode": "Djinn Battle Mark",
        "a_double_digits": "Ohtaka Classic Testament",
        "a_one_two_three": "Desert Journey Crown Crown",
        "a_lucky_seven": "Magi Expert Crown",
        "a_all_tens": "Morgiana's Heart Criterion",
        "a_exact_hundred_eps": "Djinn Equip Legend",
        "a_year_match_count": "Dungeon Marathon Yearlong",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Desert Dawn Ledger",
        "a_movie_buff": "Dungeon Critic Mark Mark",
        "a_ova_hunter": "Djinn Equip Standard Standard",
        "a_ona_explorer": "Magic World Secret",
        "a_special_watcher": "Ohtaka Classic Relic Relic",
        "a_short_king": "Ohtaka Fan Crown",
        "a_variety_pack": "Dungeon Critic Inquiry",
        "a_film_festival": "Djinn Power Chronicle",
        "a_music_video": "Amon Equip Chronicle",
        "a_tv_short": "Alibaba's Kingdom Record",
        "a_movie_marathon": "Alibaba's Kingdom Gauntlet",
        "a_double_length": "Daily Quest Crown Crown",
        "a_anthology": "Kingdom Magic Aegis Aegis",
        "a_mini_series": "All Vessels Decree",
        "a_theatrical": "Unknown Dungeons Accord",
        "a_format_master": "Ohtaka Master Vault",
        "a_long_movie": "Desert Return Insignia Insignia",
        "a_back_catalog": "Rukh Science Standard",
        "a_cm_watcher": "All Night Aegis",
        "a_pv_collector": "Magic World Storehouse",
        "a_format_balance": "Ohtaka Master Vault Vault",
        "a_episodic_master": "All Night Standard",
        "a_sequel_movie": "Desert Journey Pinnacle",
        "a_recap_watcher": "Decade Fan Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Quest",
        "a_mega_streak": "Endless Adventure",
        "a_weekly_warrior": "Djinn Alerts Season",
        "a_monthly_watcher": "Dungeon Gate Calendar",
        "a_comeback": "King's Burden Decree",
        "a_weekend_streak": "Morgiana's Heart Passage",
        "a_no_zero_days": "Desert Streak Warrant Warrant",
        "a_iron_will": "Alibaba's Vow",
        "a_habit_formed": "Magic Marathon Banner",
        "a_consistent_pace": "Daily Quest Measure",
        "a_year_long": "Year of Magic",
        "a_double_streak": "Endless Adventure Watch",
        "a_streak_recovery": "Carpet Ride Season",
        "a_daily_minimum": "Dungeon Gate Focus",
        "a_winter_streak": "Desert Winter Watch",
        "a_summer_streak": "Ohtaka Classic Resolve",
        "a_morning_streak": "Rukh Science Clock",
        "a_night_streak": "Magic Marathon Constancy",
        "a_unbreakable": "Ohtaka Fan Proof",
        "a_eternal_flame": "Dungeon Revisit Standard",
        "a_completion_streak": "Djinn Equip Return",
        "a_rating_streak": "Burden Depth Balance",
        "a_multi_ep_streak": "Dungeon Critic Ritual",
        "a_genre_streak": "Burden Depth Streak",
        "a_studio_streak": "King's Burden Cabinet Cabinet",
        "a_perfect_week": "Magic World Relic",

        // ── ANIME SCORING ──
        "a_critic": "King Judge",
        "a_perfect_ten": "Amon Equip",
        "a_harsh_critic": "Scheherazade's Review",
        "a_fair_judge": "Arabian Classic Balance",
        "a_generous_spirit": "Dungeon Gate Pinnacle",
        "a_score_all": "Dark Rukh Criterion",
        "a_wide_range": "Night Conquest Ledger",
        "a_controversial": "Rukh Science Decree",
        "a_consistent_scorer": "Dungeon Marathon Verdict",
        "a_score_sniper": "Desert Journey Score",
        "a_evolving_taste": "Endless Adventure Testament",
        "a_bell_curve": "Magic Carpet Ride Insignia",
        "a_picky_watcher": "Carpet Ride Warrant",
        "a_100_rated": "Ohtaka Master Warrant",
        "a_500_rated": "Ohtaka Fan Pinnacle",
        "a_mediocre_majority": "Magic World Canon",
        "a_rating_spree": "Rukh Science Review",
        "a_score_variance": "Morgiana's Heart Score",
        "a_masterpiece_hunter": "Rukh Science Banner",
        "a_contrarian": "Alibaba's Kingdom Record Record",
        "a_optimist": "Amon Equip Ledger",
        "a_score_distributor": "Decade Fan Appraisal",
        "a_genre_critic": "Daily Quest Critic",
        "a_mean_above_8": "Magi Expert Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Quest",
        "a_valentines_weeb": "Unknown Dungeons Vow",
        "a_pi_day": "Arabian Classic Trial",
        "a_april_fools": "Desert Journey Devotion Devotion",
        "a_international_anime_day": "Desert Return Record",
        "a_star_wars_day": "All Dungeons Chronicle",
        "a_summer_solstice": "Desert Streak Calendar",
        "a_tanabata": "Djinn Collection Focus",
        "a_friday_13th": "Decade Fan Relic",
        "a_halloween_spirit": "Desert Dawn Vow",
        "a_thanksgiving_binge": "Magi Aladdin Run",
        "a_christmas_special": "Desert Winter",
        "a_new_years_eve": "Magi Expert Pilgrimage",
        "a_birthday_watch": "Magic Carpet Ride Vow",
        "a_holiday_marathon": "Hidden Dungeon Overture",
        "a_independence_day": "Dungeon Revisit Banner",
        "a_culture_day": "Aladdin's Friend Insignia",
        "a_spring_equinox": "Hidden Dungeon Decree",
        "a_earth_day": "Dungeon Critic Mantle",
        "a_labor_day": "Desert Dawn Seal",
        "a_winter_solstice": "Djinn Battle Pilgrimage",
        "a_anime_birthday": "Dungeon Critic Pilgrimage",
        "a_every_holiday": "Night Quest Resolve",
        "a_consecutive_holidays": "Ohtaka Classic Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "King's Burden Rank",
        "a_meta_collector": "Aladdin's Friend Hoard",
        "a_meta_category_starter": "Dungeon Gate Badge",
        "a_meta_tier_climber": "Aladdin's Friend Glyph",
        "a_meta_tier_max": "Magi",
        "a_meta_xp_earner": "Decade Fan Emblem",
        "a_meta_difficulty_easy": "Arabian Classic Mechanism",
        "a_meta_difficulty_hard": "Djinn Power Writ",
        "a_meta_unlock_spree": "Djinn Alerts Panel",
        "a_meta_completionist": "All King Vessels",
        "a_meta_diverse": "Burden Depth Emblem",
        "a_meta_dominator": "Magi Aladdin Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Dungeon",
        "m_chapter_counter": "Ohtaka Master Pinnacle",
        "m_chapter_titan": "Aladdin's Flight Relic",
        "m_reading_hours": "Decade Fan Relic Relic",
        "m_reading_time_lord": "Desert Return Record Record",
        "m_manga_collector": "Djinn Alerts Ledger",
        "m_library_legend": "Aladdin's Friend Reliquary",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "Unknown Dungeons Seal",
        "m_first_rating": "Decade Fan Eye",
        "m_ten_thousand_pages": "Unknown Dungeons Gauge",
        "m_volume_collector": "Carpet Ride Storehouse",
        "m_year_explorer": "Arabian Art Quest",
        "m_century_reader": "Desert Winter Dominion",
        "m_five_hundred_ch": "Night Conquest Legend",
        "m_thousand_ch": "Endless Adventure Legend",
        "m_reading_ten": "Desert Winter Appraisal",
        "m_ptr_hoarder": "Endless Adventure Index",
        "m_dropped_honesty": "Aladdin's Friend Summit",
        "m_season_reader": "Rukh Science Treasury",
        "m_active_reader": "Ohtaka Classic Trial",
        "m_five_thousand_ch": "Alibaba's Kingdom Standard",
        "m_ten_completed": "Alibaba's Kingdom Resolution",
        "m_fifty_completed": "Endless Adventure Harvest",
        "m_five_hundred_completed": "Magic Marathon Legacy",
        "m_mean_score_tracker": "Dungeon Marathon Audit",
        "m_unique_authors": "Dungeon Critic Reserve",
        "m_all_status": "Ohtaka Classic Testament Testament",
        "m_first_favorite": "Djinn Equip Cache",
        "m_favorites_collector": "King's Burden Shelf",
        "m_days_spent_reading": "Djinn Battle Relic",

        // ── MANGA BINGE ──
        "m_binge_reader": "Magic Carpet Ride Streak",
        "m_marathon_reader": "Arabian Classic Rush",
        "m_weekend_reader": "Magic Carpet Run",
        "m_non_stop_reading": "Djinn Equip Gauntlet",
        "m_one_more_chapter": "Decade Fan Testament Testament",
        "m_speed_read": "Desert Streak Drive",
        "m_double_story": "Hidden Dungeon Banner",
        "m_triple_read": "Dungeon Revisit Record",
        "m_five_a_day": "Amon Equip Insignia",
        "m_chapter_chain": "Aladdin's Friend Accord",
        "m_volume_binge": "Morgiana's Heart Drive",
        "m_power_reader": "All Dungeons Seal Seal",
        "m_half_day_read": "King's Burden Aegis",
        "m_full_day_read": "All Night Aegis Aegis",
        "m_power_weekend": "Unknown Dungeons Streak",
        "m_binge_king": "Magic Marathon",
        "m_no_sleep_read": "Desert Winter Rush",
        "m_full_series_rush": "Arabian Classic Cascade",
        "m_seven_day_challenge": "Djinn Collection Warrant",
        "m_hundred_day_read": "Burden Depth Legend",
        "m_volume_rush": "Dungeon Hunt Gauntlet",
        "m_series_sweep": "Night Quest Trial Trial",
        "m_genre_binge": "All Night Binge",
        "m_author_binge": "Magic Carpet Surge",
        "m_chapter_counter_day": "Magi Aladdin Ledger Ledger",
        "m_multi_series_binge": "Night Conquest Charge",
        "m_midnight_binge": "Endless Adventure Tempest",
        "m_new_year_binge": "Dungeon Critic Passage",
        "m_forty_eight_hour": "Dungeon Marathon Rally",
        "m_oneshot_binge": "Desert Streak Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Battle Chapter",
        "m_genre_adventure": "Journey Chapter",
        "m_genre_comedy": "King's Burden Comedy",
        "m_genre_drama": "Kingdom Chapter",
        "m_genre_fantasy": "Magic Chapter",
        "m_genre_horror": "Dark Chapter",
        "m_genre_mystery": "Alibaba's Kingdom Mystery",
        "m_genre_romance": "Morgiana Chapter",
        "m_genre_scifi": "Rukh Chapter",
        "m_genre_sol": "Ohtaka Master Slice",
        "m_genre_sports": "Dungeon Hunt Sports",
        "m_genre_supernatural": "Djinn Chapter",
        "m_genre_thriller": "Magic World Thriller",
        "m_genre_psychological": "Burden Depth",
        "m_genre_isekai": "Djinn Alerts Isekai",
        "m_genre_shounen": "Djinn Registry Shounen",
        "m_genre_ecchi": "Daily Quest Ecchi",
        "m_genre_mahou_shoujo": "King's Burden Magic Shoujo",
        "m_genre_mecha": "Carpet Ride Mecha",
        "m_genre_music": "Desert Dawn Music",
        "m_tag_isekai_new": "Decade Fan Isekai New",
        "m_tag_harem": "Dark Rukh Harem",
        "m_tag_bl": "All Vessels Bl",
        "m_tag_gl": "Endless Adventure Gl",
        "m_tag_historical": "Night Conquest Historical",
        "m_tag_military": "Djinn Registry Military",
        "m_tag_school": "Unknown Dungeons School",
        "m_tag_martial_arts": "Ohtaka Master Martial Arts",
        "m_tag_vampire": "Dungeon Hunt Vampire",
        "m_tag_samurai": "Kingdom Magic Samurai",
        "m_tag_space": "All Vessels Space",
        "m_tag_parody": "Carpet Ride Parody",
        "m_tag_idol": "All Vessels Idol",
        "m_tag_post_apocalyptic": "Aladdin's Friend Post Apocalyptic",
        "m_tag_cyberpunk": "Dark Rukh Cyberpunk",
        "m_tag_shoujo": "Djinn Power Shoujo",
        "m_tag_survival": "King's Burden Survival",
        "m_tag_cooking": "Magic Carpet Ride Cooking",
        "m_tag_medical": "Ohtaka Classic Medical",
        "m_tag_villainess": "Magic Carpet Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Magi Expert",
        "m_completion_rate_50": "All Vessels Return",
        "m_completion_rate_75": "Magic World Ascension",
        "m_completion_rate_90": "Dungeon Revisit Resolution",
        "m_no_drop": "Djinn Equip Decree",
        "m_long_runner_complete": "Magi Aladdin Clear",
        "m_sequel_chain": "Desert Dawn Seal Seal",
        "m_clean_list": "Aladdin's Flight Relic Relic",
        "m_from_ptr": "Djinn Power Watchlist",
        "m_reread_master": "Arabian Classic Trial Trial",
        "m_oneshot_complete": "Arabian Classic Ascension",
        "m_same_day_start_finish": "Magi Expert Crown Crown",
        "m_revival": "Magi Aladdin Accord",
        "m_zero_to_hundred": "Alibaba's Kingdom Banner",
        "m_five_genre_complete": "Desert Streak M Five Genre",
        "m_full_collection": "Magi Expert Proof Proof",
        "m_batch_complete": "Dungeon Marathon Summit",
        "m_paused_to_done": "Dungeon Revisit Standard Standard",
        "m_completion_spree": "Ohtaka Fan Triumph",
        "m_format_completionist": "Arabian Classic Completion",
        "m_catch_up": "Desert Return Chronicle",
        "m_multi_reread": "Djinn Equip Banner",
        "m_dropped_recovery": "Daily Quest Conquest",
        "m_ten_perfect_scores": "Magic Carpet Judgment",
        "m_complete_genre_span": "Djinn Alerts M Complete Genre",
        "m_monthly_completions": "All Night Return",
        "m_yearly_completions": "Djinn Alerts Epilogue",
        "m_rapid_complete": "Djinn Collection Finale",
        "m_author_complete": "Unknown Dungeons Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Devoted Reader",
        "m_mangaka_lover": "Ohtaka Fan",
        "m_rereader": "Desert Return",
        "m_triple_reread": "Burden Depth Testament Testament",
        "m_annual_reread": "Alibaba's Kingdom Banner Banner",
        "m_publisher_fan": "Ohtaka Fan Mark",
        "m_artist_fan": "Desert Dawn Insignia",
        "m_adaptation_compare": "Magic Carpet Ride Insignia Insignia",
        "m_source_material_fan": "Manga First",
        "m_waiting_weekly": "Kingdom Magic Streak",
        "m_classic_reader": "Carpet Ride Lantern",
        "m_saga_reader": "Aladdin's Friend Decree",
        "m_genre_loyalty": "Daily Quest Loyalty",
        "m_decade_reader": "Morgiana's Heart Warrant",
        "m_ln_adaptation": "Morgiana's Heart Mark",
        "m_original_work": "Dungeon Hunt Standard",
        "m_long_commitment": "Daily Quest Mark",
        "m_up_to_date": "Dungeon Critic Warrant Warrant",
        "m_favorite_mangaka": "Arabian Art Treasury",
        "m_complete_portfolio": "Ohtaka Fan Triumph Triumph",
        "m_franchise_collector": "Desert Return Archive",
        "m_serialization_follower": "Arabian Art Handshake",
        "m_genre_master": "Aladdin's Flight Master",
        "m_multi_series_author": "Aladdin's Friend Insignia Insignia",
        "m_format_diversity": "Dungeon Hunt Shelf",
        "m_year_dedication": "Desert Winter Tenure",
        "m_ongoing_follower": "Morgiana's Heart Fellowship",
        "m_genre_loyalty_50": "Endless Adventure Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Hidden Dungeon Explorer",
        "m_publisher_hopper": "Ohtaka Fan Mantle",
        "m_tag_explorer": "Night Quest Explorer",
        "m_decade_hopper": "Djinn Power Chronicle Chronicle",
        "m_hidden_gem": "Hidden Volume",
        "m_popular_taste": "Dungeon Marathon Record Record",
        "m_retro_reader": "Dungeon Marathon Accord",
        "m_modern_reader": "Night Conquest Seal Seal",
        "m_cross_demographic": "Dungeon Gate Crown",
        "m_underdog_fan": "Dungeon Marathon Accord Accord",
        "m_variety_week": "Desert Dawn Horizon Horizon",
        "m_manhwa_reader": "Desert Journey Proof",
        "m_manhua_reader": "Carpet Ride Mantle Mantle",
        "m_classic_connoisseur": "Magic Marathon Glimpse",
        "m_award_winner": "Desert Winter Warrant",
        "m_niche_explorer": "Magic Carpet Ride Horizon",
        "m_world_manga": "Desert Return Chronicle Chronicle",
        "m_cult_classic": "Arabian Classic",
        "m_random_pick": "Dungeon Marathon Standard",
        "m_new_genre_month": "Desert Return M New Genre",
        "m_year_completionist": "Ohtaka Master Fulfillment",
        "m_unpopular_opinion": "Dungeon Critic Trial",
        "m_top_rated_reader": "Magic Carpet Ride Record",
        "m_source_variety": "Carpet Ride Catalogue",
        "m_low_score_brave": "Ohtaka Master Score",
        "m_short_manga_explorer": "Night Conquest Compass",
        "m_long_manga_explorer": "Alibaba's Kingdom Survey",
        "m_serialization_explorer": "Magic World Road",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Desert Dawn Read",
        "m_lunch_reader": "All Vessels Ledger",
        "m_commute_reader": "Ohtaka Classic Tenure Tenure",
        "m_four_am_club": "Ohtaka Fan Fellowship",
        "m_new_year_read": "Desert Dawn Pact",
        "m_all_hours": "Djinn Power Accord Accord",
        "m_prime_time_reader": "Dungeon Hunt Banner",
        "m_workday_reader": "Magi Aladdin Accord Accord",
        "m_sunday_read": "All Vessels Standard Standard",
        "m_morning_routine": "Magi Aladdin Discipline",
        "m_night_shift_reader": "Unknown Dungeons Accord Accord",
        "m_seasonal_premier_read": "Carpet Ride Seasonal",
        "m_clock_collector": "Djinn Battle Reserve",
        "m_late_night_horror": "Desert Streak Mark Mark",
        "m_afternoon_reader": "Desert Winter Mantle Mantle",
        "m_golden_hour_reader": "Burden Depth Observance",
        "m_dawn_reader": "Night Quest Mantle",
        "m_twilight_reader": "Morgiana's Heart Crown",
        "m_midnight_start": "Dungeon Hunt Routine",
        "m_weekend_binge_hours": "Magic Carpet Momentum",
        "m_late_night_regular": "All Vessels Accord",
        "m_sunrise_reader": "Dark Rukh Mantle",
        "m_every_day_of_week": "Carpet Ride Warrant Warrant",
        "m_monthly_hours": "Hidden Dungeon Vigil",
        "m_bedtime_reader": "Ohtaka Master Warrant Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Arabian Art",
        "m_webtoon_reader": "Morgiana's Heart Mark Mark",
        "m_full_color": "Desert Dawn Accord",
        "m_doujin_reader": "Dungeon Revisit Record Record",
        "m_anthology_reader": "Magic Carpet Accord",
        "m_adaptation_reader": "Dungeon Marathon Banner",
        "m_longstrip_reader": "Burden Depth Trial",
        "m_4koma_reader": "Kingdom Magic Ledger",
        "m_oneshot_reader": "Djinn Alerts Mantle",
        "m_format_variety": "Ohtaka Fan Gallery",
        "m_light_novel_reader": "Djinn Power Insignia",
        "m_novel_reader": "Ohtaka Master Crown",
        "m_visual_storyteller": "Desert Winter Testament",
        "m_colored_classic": "Rukh Science Survey",
        "m_webcomic_fan": "Magic Marathon Insignia",
        "m_manga_to_anime": "Manga Adapted",
        "m_seinen_reader": "Daily Quest Pinnacle",
        "m_josei_reader": "Dark Rukh Pinnacle",
        "m_award_winning_art": "Djinn Registry Relic",
        "m_debut_work": "Djinn Registry Dominion",
        "m_vertical_scroll": "Aladdin's Friend Decree Decree",
        "m_traditional_format": "Magic Carpet Ride Hoard",
        "m_cross_media": "Night Conquest Accord",
        "m_spinoff_reader": "Desert Return Accord",
        "m_remake_reader": "Arabian Classic Pinnacle",
        "m_collaboration_reader": "Magic Marathon Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Desert Streak",
        "m_weekly_warrior": "Magic World Season",
        "m_monthly_reader": "Amon Equip Discipline",
        "m_comeback": "Alibaba's Kingdom Standard Standard",
        "m_weekend_streak": "Dark Rukh Fever",
        "m_no_zero_days": "Desert Journey Proof Proof",
        "m_iron_will": "King Resolve",
        "m_habit_formed": "Dungeon Gate Crown Crown",
        "m_consistent_pace": "Magi Expert Scrutiny Scrutiny",
        "m_year_long": "Year Reading",
        "m_double_streak": "Djinn Alerts Resolve",
        "m_streak_recovery": "Aladdin's Flight Resolve",
        "m_daily_minimum": "Djinn Battle Focus",
        "m_winter_streak": "Burden Depth Observance Observance",
        "m_summer_streak": "Djinn Registry Observance",
        "m_morning_streak": "Hidden Dungeon Clock",
        "m_night_streak": "Magic Carpet Ride Discipline",
        "m_unbreakable": "Dark Rukh Warrant",
        "m_eternal_flame": "King's Burden Record",
        "m_chapter_a_day": "All Vessels Ledger Ledger",
        "m_genre_streak": "Night Quest Streak",
        "m_completion_streak": "Dungeon Marathon Return",
        "m_rating_streak": "Night Quest Appraisal",
        "m_multi_ch_streak": "Magic World Tenure",
        "m_author_streak": "Djinn Battle Calendar",
        "m_perfect_week_manga": "Desert Return Accord Accord",
        "m_diverse_streak": "Djinn Equip Streak",

        // ── MANGA SCORING ──
        "m_critic": "Dungeon Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_harsh_critic": "Djinn Power Scale",
        "m_fair_judge": "Decade Fan Eye Eye",
        "m_generous_spirit": "Magic Carpet Decree",
        "m_score_all": "Morgiana's Heart Reckoning",
        "m_wide_range": "Amon Equip Ledger Ledger",
        "m_controversial": "All Night Standard Standard",
        "m_consistent_scorer": "Dungeon Revisit Grade",
        "m_score_sniper": "Dungeon Critic Reckoning",
        "m_evolving_taste": "Djinn Alerts Trial Trial",
        "m_bell_curve": "Amon Equip Accord",
        "m_picky_reader": "Djinn Equip Ledger",
        "m_100_rated": "Amon Equip Standard",
        "m_500_rated": "Unknown Dungeons Aegis",
        "m_mediocre_majority": "Djinn Alerts Canon",
        "m_rating_spree": "Hidden Dungeon Verdict",
        "m_score_variance": "Ohtaka Master Measure",
        "m_binge_rater": "Djinn Battle Passage",
        "m_reread_rerate": "Rukh Science Banner Banner",
        "m_masterpiece_hunter": "All Night Banner",
        "m_contrarian": "Dungeon Marathon Aegis",
        "m_optimist": "Night Conquest Accord Accord",
        "m_score_distributor": "Magic World Balance",
        "m_genre_critic": "Djinn Battle Critic",
        "m_mean_above_8": "Ohtaka Master Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Desert Winter Season",
        "m_valentines_read": "Night Quest Observance",
        "m_pi_day": "Djinn Alerts Testament Testament",
        "m_april_fools": "Dungeon Critic Devotion",
        "m_international_manga_day": "Djinn Power Aegis",
        "m_free_comic_day": "Magic Carpet Chronicle",
        "m_summer_solstice": "Djinn Collection Focus Focus",
        "m_tanabata": "Magi Expert Tanabata",
        "m_friday_13th": "Arabian Classic Dominion Dominion",
        "m_halloween_read": "Desert Streak Halloween",
        "m_thanksgiving_binge": "Desert Return Charge",
        "m_christmas_read": "Magi Aladdin Pact",
        "m_new_years_eve": "Djinn Collection Pilgrimage",
        "m_birthday_read": "Daily Quest Focus",
        "m_holiday_marathon": "Arabian Art Rally",
        "m_independence_day": "Dungeon Marathon Aegis Aegis",
        "m_culture_day": "Unknown Dungeons Seal Seal",
        "m_spring_equinox": "Desert Streak Dominion",
        "m_earth_day": "Daily Quest Trial",
        "m_labor_day": "Magi Aladdin Seal",
        "m_winter_solstice": "Dungeon Gate Focus Focus",
        "m_manga_birthday": "Magi Expert Ritual",
        "m_every_holiday_reader": "Aladdin's Flight Watch",
        "m_consecutive_holidays": "Arabian Classic Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "All Dungeons Aegis",
        "m_fibonacci": "Ohtaka Classic Dominion",
        "m_palindrome_day": "Djinn Alerts Relic",
        "m_binary_day": "Dungeon Gate Proof",
        "m_full_moon_read": "Dark Rukh Crown",
        "m_leap_year_read": "Djinn Equip Practice",
        "m_triple_seven": "Decade Fan Trial Trial",
        "m_thousand_complete": "Decade Fan Ascension",
        "m_nice": "Aladdin's Friend Seal Seal",
        "m_power_level_chapters": "Alibaba's Kingdom Aegis",
        "m_answer_42": "Dark Rukh Trial",
        "m_square_number": "King's Burden Standard",
        "m_prime_count": "Decade Fan Pinnacle",
        "m_matching_date": "Aladdin's Flight Mantle",
        "m_century_chapter": "All Dungeons Decree",
        "m_pi_chapters": "Daily Quest Proof Proof",
        "m_synchronicity": "Night Quest Emblem",
        "m_world_record": "Desert Journey Warrant",
        "m_genre_clash": "Dungeon Hunt Clash",
        "m_time_traveler": "Dungeon Revisit Decree",
        "m_double_digits": "Carpet Ride Dominion",
        "m_one_two_three": "Magic Marathon Banner Banner",
        "m_lucky_seven": "Magic Carpet Ride Record Record",
        "m_exact_hundred_ch": "Ohtaka Classic Legend",
        "m_year_match_count": "Kingdom Magic Routine",
        "m_chapter_match_date": "Dungeon Gate Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Carpet Ride Index",
        "m_manhwa_format": "Desert Streak Gallery",
        "m_manhua_format": "Burden Depth Storehouse",
        "m_ln_format": "Decade Fan Index",
        "m_oneshot_format": "Djinn Alerts Index",
        "m_doujin_format": "Hidden Dungeon Cabinet",
        "m_novel_format": "Dungeon Critic Reserve Reserve",
        "m_format_master_manga": "Hidden Dungeon Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Dungeon Revisit Link",
        "m_meta_collector": "Unknown Dungeons Reliquary",
        "m_meta_category_starter": "Ohtaka Fan Standard",
        "m_meta_tier_climber": "Night Conquest Token",
        "m_meta_tier_max": "Magi Complete",
        "m_meta_xp_earner": "Carpet Ride Anchor",
        "m_meta_difficulty_easy": "Decade Fan Panel",
        "m_meta_difficulty_hard": "Desert Winter Node",
        "m_meta_unlock_spree": "Carpet Ride Marker",
        "m_meta_completionist": "Full Library",
        "m_meta_diverse": "Djinn Alerts Anchor",
        "m_meta_dominator": "Aladdin's Friend Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060300",
        primary: "#d78c00",
        secondary: "#826000",
        accent: "#8060d0",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/magi.jpg",
    particleColor: "#f0b820",
    backgroundDim: 0.32,
    backgroundBlur: 16,
    particleTypes: {
        rukh_birds: { label: "Rukh Birds", maxCount: 18, defaultEnabled: true, defaultIntensity: 60 },
        desert_sand: { label: "Desert Sand", maxCount: 15, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
  1: "Threadbare Generic Rank Spark",
  8: "Generic's Tarnished Omen",
  14: "Fractured Generic Rank",
  21: "Generic Rank Path",
  28: "Lowborn Legacy Myth",
  35: "Generic Rank Pulse",
  41: "Generic's Legacy Crest",
  48: "Humble Generic Mark",
  55: "Ragged Generic Rank Vow",
  61: "Generic's Faint Echo",
  68: "Lesser Generic Rank",
  75: "Generic Rank Zenith",
  81: "Doubtful Legacy Bloom",
  88: "Generic Rank Sigil",
  95: "Generic's Legacy Flame",
  102: "Really Cool Generic Spark",
  108: "Awakened Generic Rank Omen",
  115: "Generic's Resolute Seal",
  122: "Rising Generic Rank",
  128: "Generic Rank Myth",
  135: "Dauntless Legacy Pulse",
  142: "Generic Rank Crest",
  149: "Generic's Legacy Mark",
  155: "Fresh Generic Vow",
  162: "Valiant Generic Rank Echo",
  169: "Generic's Prime Crown",
  175: "Polished Generic Rank",
  182: "Generic Rank Bloom",
  189: "Stormlit Legacy Sigil",
  195: "Generic Rank Flame",
  202: "Generic's Legacy Spark",
  209: "Tempered Generic Omen",
  216: "Trusted Generic Rank Seal",
  222: "Generic's Steadfast Path",
  229: "Ironclad Generic Rank",
  236: "Veteran Legacy Pulse",
  242: "Core Legacy Crest",
  249: "Generic Rank Mark",
  256: "Generic's Legacy Vow",
  262: "Formidable Generic Echo",
  269: "Lucid Generic Rank Crown",
  276: "Generic's Ranked Zenith",
  283: "Fabled Generic Rank",
  289: "Grand Legacy Sigil",
  296: "Seasoned Legacy Flame",
  303: "Generic Rank Spark",
  309: "Generic's Legacy Omen",
  316: "Valorous Generic Seal",
  323: "Stalwart Generic Rank Path",
  330: "Generic's Commanding Myth",
  336: "Refined Generic Rank",
  343: "Unbroken Legacy Crest",
  350: "Blazing Legacy Mark",
  356: "Generic Rank Vow",
  363: "Generic's Legacy Echo",
  370: "Peerless Generic Crown",
  376: "Ardent Generic Rank Zenith",
  383: "Generic's Focused Bloom",
  390: "Vigilant Generic Rank",
  397: "Dominant Legacy Flame",
  403: "Elite Legacy Spark",
  410: "Generic Rank Omen",
  417: "Generic's Legacy Seal",
  423: "Sovereign Generic Path",
  430: "Regal Generic Rank Myth",
  437: "Generic's Crowned Pulse",
  444: "Mythborn Generic Rank",
  450: "Limitless Legacy Mark",
  457: "Radiant Legacy Vow",
  464: "Generic Rank Echo",
  470: "Generic's Legacy Crown",
  477: "Climactic Generic Zenith",
  484: "Epic Generic Rank Bloom",
  490: "Generic's Unreal Sigil",
  497: "Peak Generic Rank",
  504: "Supreme Legacy Spark",
  511: "Exalted Legacy Omen",
  517: "Generic Rank Seal",
  524: "Generic's Legacy Path",
  531: "Celestial Generic Myth",
  537: "Phantom Generic Rank Pulse",
  544: "Generic's Crimson Crest",
  551: "Silver Generic Rank",
  557: "Golden Legacy Vow",
  564: "Feral Legacy Echo",
  571: "Generic Rank Crown",
  578: "Generic's Legacy Zenith",
  584: "Dread Generic Bloom",
  591: "Luminous Generic Rank Sigil",
  598: "Generic's Thunderous Flame",
  604: "Ultraviolet Generic Rank",
  611: "Unleashed Legacy Omen",
  618: "Secret Legacy Seal",
  625: "Final Generic Path",
  631: "Generic's Legacy Myth",
  638: "Worldclass Generic Pulse",
  645: "Lawless Generic Rank Crest",
  651: "Generic's Chosen Mark",
  658: "Fearless Generic Rank",
  665: "Overdrive Legacy Echo",
  671: "Cinematic Legacy Crown",
  678: "Impossible Generic Zenith",
  685: "Generic's Legacy Bloom",
  692: "Canonized Generic Sigil",
  698: "Ascendant Generic Rank Flame",
  705: "Generic's Transfigured Spark",
  712: "Immortal Generic Rank",
  718: "Eclipsed Legacy Seal",
  725: "Astral Legacy Path",
  732: "Sublime Generic Myth",
  739: "Generic's Legacy Pulse",
  745: "Prismatic Generic Crest",
  752: "Abyssal Generic Rank Mark",
  759: "Generic's Unbound Vow",
  765: "Eternal Generic Rank",
  772: "Cosmic Legacy Crown",
  779: "Transcendent Legacy Zenith",
  785: "Perfected Generic Bloom",
  792: "Generic's Legacy Sigil",
  799: "Ultimate Generic Flame",
  806: "Mythic Generic Rank Spark",
  812: "Generic's Godlike Omen",
  819: "Canonical Generic Rank",
  826: "Reality-Bent Legacy Path",
  832: "Heavenly Legacy Myth",
  839: "Absolute Generic Pulse",
  846: "Untouchable Generic Crest",
  852: "Timeless Generic Mark",
  859: "Empyrean Generic Rank Vow",
  866: "Generic's Primordial Echo",
  873: "Omniscient Generic Rank",
  879: "Unfathomed Legacy Zenith",
  886: "Apocalyptic Legacy Bloom",
  893: "Seraphic Generic Sigil",
  899: "Omega Generic Flame",
  906: "Final Generic Spark",
  913: "Crowned Generic Rank Omen",
  920: "Generic's Mythic Seal",
  926: "Absolute Generic Rank",
  933: "Eternal Legacy Myth",
  940: "Cosmic Legacy Pulse",
  946: "Transcendent Generic Crest",
  953: "Perfected Generic Mark",
  960: "Definitive Generic Vow",
  966: "Ultimate Generic Rank Echo",
  973: "Generic's Infinite Crown",
  980: "Sovereign Generic Rank",
  987: "Celestial Legacy Bloom",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate Generic Rank"
},
}
