import { AnimeThemeConfig } from "./types"
import { GiDragonHead, GiFireworkRocket, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiCrystalBall, GiMusicalNotes } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const missKobayashisDragonMaidTheme: AnimeThemeConfig = {
    id: "miss-kobayashis-dragon-maid",
    displayName: "Miss Kobayashi's Dragon Maid",
    description: "Software engineer Kobayashi wakes up to find a dragon at her door — Tohru, who she drunkenly invited to be her maid. A quirky found-family grows as more dragons arrive in suburban Japan.",
    fontFamily: "'Fredoka One', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap",
    cssVars: {
        "--color-brand-200": "200 235 180",
        "--color-brand-300": "148 210 120",
        "--color-brand-400": "92 180 62",
        "--color-brand-500": "52 148 28",
        "--color-brand-600": "28 112 10",
        "--color-brand-700": "12 78 4",
        "--color-brand-800": "5 48 1",
        "--color-brand-900": "2 26 0",
        "--color-brand-950": "0 10 0",
        "--brand": "52 148 28",
        "--background": "#000400",
        "--paper": "#010800",
        "--color-gray-950": "0 4 0",
        "--color-gray-900": "2 10 1",
        "--color-gray-800": "5 22 3",
        "--color-gray-700": "10 38 6",
        "--color-gray-600": "18 62 12",
        "--color-gray-500": "32 96 22",
        "--color-gray-400": "55 138 42",
        "--color-gray-300": "88 178 72",
        "--color-gray-200": "130 210 115",
        "--color-gray-100": "178 235 165",
        "--color-gray-50": "222 248 215",
    },
    sidebarOverrides: {
        "home": { icon: GiDragonHead, label: "Kobayashi's Flat" },
        "schedule": { icon: GiAlarmClock, label: "Maid Schedule" },
        "manga": { icon: LuBookOpen, label: "Dragon Codex" },
        "lists": { icon: GiScrollUnfurled, label: "Dragon Roster" },
        "discover": { icon: GiBullseye, label: "New Dragons" },
        "torrent-list": { icon: GiFireworkRocket, label: "Dragon Cache" },
        "debrid": { icon: GiCrystalBall, label: "Dragon World Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Dragons" },
        "enmasse": { icon: GiResize, label: "Dragon Parade" },
        "scan-summaries": { icon: TbReportSearch, label: "Maid Reports" },
        "auto-downloader": { icon: LuRss, label: "Dragon Alerts" },
        "community": { icon: GiMusicalNotes, label: "Dragon Family" },
        "achievements": { icon: GiTrophyCup, label: "Dragon Trophies" },
        "milestones": { icon: LuFlag, label: "Family Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Dragon Alerts" },
        "theme-manager": { icon: GiPalette, label: "Dragon Colors" },
        "extensions": { icon: BiExtension, label: "Dragon Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Dragon Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Kobayashi Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Maid Day",
        "a_episode_counter": "Dragon Alerts Mark",
        "a_episode_titan": "Maid Marathon Relic",
        "a_hours_invested": "Kobayashi Proof",
        "a_time_lord": "Dragon Parade Decree",
        "a_anime_collector": "Dragon Roster Catalogue",
        "a_library_legend": "Archive Library",
        "a_first_complete": "Dragon Arc Done",
        "a_hundred_club": "Hundred Dragon Days",
        "a_first_day": "Dragon Parade Seal",
        "a_first_rating": "Dragon Roster Appraisal",
        "a_ten_thousand_min": "Lost Dragons Standard",
        "a_season_veteran": "Archive Library Library",
        "a_year_explorer": "Dragon Parade Map",
        "a_century_watcher": "Archive Ledger",
        "a_five_hundred_eps": "Kobayashi's Flat Dominion",
        "a_thousand_eps": "Maid Record",
        "a_watching_ten": "Marathon Acclaim",
        "a_ptw_hoarder": "Maid Library",
        "a_dropped_honesty": "Lost Dragons Summit",
        "a_five_thousand_eps": "Dragon Warrant",
        "a_ten_completed": "Family Afterglow",
        "a_fifty_completed": "Kobayashi's Flat Ascension",
        "a_five_hundred_completed": "Family Clear",
        "a_mean_score_tracker": "Japan Verdict",
        "a_unique_studios": "Japan Collection",
        "a_days_spent_watching": "Family Fan Dominion",
        "a_all_status": "Dragon Roster Testament",
        "a_first_favorite": "Marathon Cabinet",
        "a_favorites_collector": "Dragon Maid Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Kobayashi's Flat Drive",
        "a_marathon_runner": "Archive Gauntlet",
        "a_weekend_warrior": "Dragon Family Fan Ordeal",
        "a_non_stop": "Dragon Family Fan Fever",
        "a_one_more_episode": "Tohru Mantle",
        "a_speed_run": "Lost Dragons Vigil",
        "a_double_feature": "Family Fan Crown",
        "a_triple_threat": "Maid Record Record",
        "a_five_a_day": "Japan Accord",
        "a_back_to_back": "Dragon Family Surge",
        "a_seasonal_binge": "Dragon Roster Cascade",
        "a_cour_crusher": "Family Fan Ordeal",
        "a_half_day_watch": "Dragon Alerts Crown",
        "a_full_day_watch": "Dragon Pinnacle",
        "a_power_weekend": "Maid Run",
        "a_binge_king": "Dragon Maid Marathon",
        "a_no_sleep": "Miss Kobayashi's Dragon Vigil",
        "a_entire_season": "Family Library",
        "a_seven_day_challenge": "Dragon Mark",
        "a_hundred_day_binge": "Lost Dragons Surge",
        "a_genre_binge": "Family Binge",
        "a_studio_binge": "Kobayashi Fever",
        "a_season_sweep": "Tohru Codex",
        "a_forty_eight_hour": "Miss Kobayashi's Dragon Overture",
        "a_ep_counter_day": "Dragon Maid Aegis",
        "a_multi_series_binge": "Marathon Streak",
        "a_midnight_binge": "Dragon Maid Marathon Cascade",
        "a_new_year_binge": "Dragon Maid Marathon Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Dragon Codex Action",
        "a_genre_adventure": "Dragon Roster Adventure",
        "a_genre_comedy": "Marathon Comedy",
        "a_genre_drama": "Miss Kobayashi's Dragon Drama",
        "a_genre_fantasy": "Kobayashi's Flat Fantasy",
        "a_genre_horror": "Software Horror",
        "a_genre_mystery": "Archive Mystery",
        "a_genre_romance": "Marathon Romance",
        "a_genre_scifi": "Family Fan Sci-Fi",
        "a_genre_sol": "Dragon Alerts Slice",
        "a_genre_sports": "Dragon Trophies Sports",
        "a_genre_supernatural": "Kobayashi's Flat Supernatural",
        "a_genre_thriller": "Family Fan Thriller",
        "a_genre_mecha": "Dragon Mecha",
        "a_genre_music": "Japan Music",
        "a_genre_psychological": "Japan Psychological",
        "a_genre_ecchi": "Dragon Maid Marathon Ecchi",
        "a_genre_mahou_shoujo": "Dragon Parade Magic Shoujo",
        "a_tag_isekai": "Dragon World Vault Isekai",
        "a_tag_harem": "Software Harem",
        "a_tag_bl": "Family Bl",
        "a_tag_gl": "Family Fan Gl",
        "a_tag_historical": "Japan Historical",
        "a_tag_military": "Kobayashi's Flat Military",
        "a_tag_school": "Archive School",
        "a_tag_martial_arts": "Dragons Martial Arts",
        "a_tag_vampire": "Archive Vampire",
        "a_tag_samurai": "Dragon Parade Samurai",
        "a_tag_space": "Marathon Space",
        "a_tag_parody": "Dragon Roster Parody",
        "a_tag_idol": "Maid Idol",
        "a_tag_post_apocalyptic": "Miss Kobayashi's Dragon Maid Post",
        "a_tag_cyberpunk": "Maid Marathon Cyberpunk",
        "a_tag_shounen": "Family Shounen",
        "a_tag_seinen": "Dragon Trophies Seinen",
        "a_tag_shoujo": "Archive Shoujo",
        "a_tag_josei": "Miss Kobayashi's Dragon Josei",
        "a_tag_survival": "Miss Kobayashi's Dragon Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Dragon Family",
        "a_mega_completionist": "Dragon Maid Legend",
        "a_completion_rate_50": "Archive Return",
        "a_completion_rate_75": "Dragon Codex Crown",
        "a_completion_rate_90": "Maid Resolution",
        "a_no_drop": "Miss Kobayashi's Dragon Decree",
        "a_long_runner_complete": "Dragon Family Clear",
        "a_sequel_chain": "Lost Dragons Insignia",
        "a_clean_list": "Dragon Family Fan Relic",
        "a_from_ptw": "Kobayashi's Flat Index",
        "a_rewatch_master": "Maid Return",
        "a_short_complete": "Family Fan Endgame",
        "a_same_day_start_finish": "Family Fan Pinnacle",
        "a_revival": "Japan Insignia",
        "a_zero_to_hero": "Dragon Maid Banner",
        "a_five_genre_complete": "Dragon Maid Marathon A Five",
        "a_full_franchise": "Miss Kobayashi's Dragon Chronicle",
        "a_batch_complete": "Dragon Crown",
        "a_paused_to_done": "Archive Aegis",
        "a_completion_spree": "Dragons Triumph",
        "a_multi_rewatch": "Dragon Roster Triumph",
        "a_dropped_recovery": "Dragons Conquest",
        "a_ten_perfect_scores": "Dragon Maid Acclaim",
        "a_seasonal_clear": "Dragon Maid Marathon Codex",
        "a_complete_genre_span": "Family Fan A Complete Genre",
        "a_monthly_completions": "Lost Dragons Afterglow",
        "a_yearly_completions": "Software Epilogue",
        "a_rapid_complete": "Kobayashi Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Dragon Family Fan",
        "a_studio_devotee": "Miss Kobayashi's Dragon Treasury",
        "a_rewatcher": "Miss Kobayashi's Dragon Maid Closure",
        "a_triple_rewatch": "Maid Coda",
        "a_annual_tradition": "Family Fan Proof",
        "a_director_fan": "Dragon Trial",
        "a_voice_actor_fan": "Tohru Crown",
        "a_ost_lover": "Japan Seal",
        "a_source_reader": "Dragon Family Cabinet",
        "a_waiting_weekly": "Dragon Family Clock",
        "a_childhood_revisit": "Miss Kobayashi's Dragon Seal",
        "a_saga_tracker": "Japan Standard",
        "a_genre_loyalty": "Tohru Loyalty",
        "a_decade_watcher": "Lost Dragons Banner",
        "a_adaptation_hunter": "Dragon Codex Trial",
        "a_original_anime_fan": "Dragon Maid Marathon Testament",
        "a_long_commitment": "Dragon Codex Mark",
        "a_perfect_attendance": "Marathon Standard",
        "a_favorite_studio_5": "Miss Kobayashi's Dragon Library",
        "a_complete_catalog": "Miss Kobayashi's Dragon Seal Seal",
        "a_franchise_collector": "Dragon Trophies Archive",
        "a_airing_follower": "Japan Signal",
        "a_genre_master": "Dragon Alerts Master",
        "a_staff_follower": "Miss Kobayashi's Dragon Oath",
        "a_multi_season_fan": "Miss Kobayashi's Dragon Maid Hoard",
        "a_format_diversity": "Dragon Trophies Cache",
        "a_year_dedication": "Dragon Maid Marathon Tenure",
        "a_season_dedication": "Dragons Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Maid Explorer",
        "a_studio_hopper": "Dragon Family Collection",
        "a_tag_explorer": "Family Fan Explorer",
        "a_decade_hopper": "Family Chronicle",
        "a_hidden_gem": "Maid Marathon Warrant",
        "a_popular_taste": "Maid Decree",
        "a_retro_appreciator": "Dragon Family Aegis",
        "a_modern_viewer": "Family Fan Pinnacle Pinnacle",
        "a_cross_demographic": "Dragon Family Fan Pinnacle",
        "a_underdog_fan": "Dragon Alerts Trial",
        "a_variety_week": "Miss Kobayashi's Dragon Maid Horizon",
        "a_foreign_cinema": "Dragons Expedition",
        "a_classic_connoisseur": "Dragon World Vault Glimpse",
        "a_every_season": "Marathon Archive",
        "a_award_winner": "Family Insignia",
        "a_niche_explorer": "Dragon Parade Horizon",
        "a_global_anime": "Dragon Family Fan Crown",
        "a_cult_classic": "Japan Map",
        "a_random_pick": "Dragon Trophies Decree",
        "a_new_genre_month": "Japan A New Genre Month",
        "a_seasonal_completionist": "Family Summit",
        "a_unpopular_opinion": "Maid Standard",
        "a_top_rated_viewer": "Dragon Family Seal",
        "a_source_variety": "Software Storehouse",
        "a_low_score_brave": "Maid Marathon Measure",
        "a_upcoming_watcher": "Dragon Maid Seal",
        "a_short_series_explorer": "Dragon Family Fan Expedition",
        "a_long_series_explorer": "Dragon Maid Marathon Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Dragon Trophies Insignia",
        "a_early_bird": "Dragon Trophies Banner",
        "a_lunch_break": "Dragon Codex Trial Trial",
        "a_golden_hour": "Dragons Tenure",
        "a_four_am_club": "Software Gathering",
        "a_witching_hour": "Tohru Tenure",
        "a_new_year_watch": "Kobayashi Season",
        "a_midnight_premiere": "Dragon Maid Marathon Devotion",
        "a_all_hours": "Lost Dragons Seal",
        "a_dawn_warrior": "Marathon Aegis",
        "a_afternoon_delight": "Software Proof",
        "a_prime_time": "Japan Insignia Insignia",
        "a_workday_watcher": "Kobayashi Pinnacle",
        "a_sunday_marathon": "Family Momentum",
        "a_rainy_day": "Software Relic",
        "a_morning_routine": "Dragon World Vault Promise",
        "a_night_shift": "Maid Aegis",
        "a_twilight_zone": "Dragon Maid Ledger",
        "a_seasonal_premier": "Family Cabinet",
        "a_clock_collector": "Dragon Alerts Repository",
        "a_weekend_binge_hours": "Maid Streak",
        "a_late_night_regular": "Kobayashi's Flat Dominion Dominion",
        "a_sunrise_watcher": "Family Fan Relic",
        "a_holiday_watcher": "Miss Kobayashi's Dragon Maid Pact",
        "a_every_day_of_week": "Miss Kobayashi's Dragon Maid Ledger",
        "a_monthly_hours": "Dragon Maid Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Marathon Record",
        "a_party_host": "Dragon Trophies Record",
        "a_social_butterfly": "Dragon Maid Company",
        "a_group_binge": "Dragon Trophies Sprint",
        "a_party_regular": "Family Chronicle Chronicle",
        "a_sync_viewer": "Tohru Standard",
        "a_commentator": "Marathon Record Record",
        "a_party_marathon": "Dragon Parade Vigil",
        "a_full_house": "Family Fan Trial",
        "a_community_pillar": "Dragon Alerts Alliance",
        "a_watch_party_streak": "Miss Kobayashi's Dragon Maid Vigil",
        "a_diverse_party": "Archive Seal",
        "a_late_night_party": "Tohru Testament",
        "a_party_veteran": "Family Fan Testament",
        "a_genre_party": "Dragon Codex Party",
        "a_weekly_party": "Dragon Maid Marathon Calendar",
        "a_silent_viewer": "Dragon Mantle",
        "a_recommendation_giver": "Japan Network",
        "a_party_completionist": "Miss Kobayashi's Dragon Coda",
        "a_social_scorer": "Dragon Alerts Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Dragon Proof",
        "a_fibonacci": "Dragon Maid Marathon Dominion",
        "a_palindrome_day": "Dragon Alerts Relic",
        "a_binary_day": "Dragon Mark Mark",
        "a_full_moon": "Marathon Insignia",
        "a_leap_year": "Dragons Devotion",
        "a_time_traveler": "Miss Kobayashi's Dragon Maid Record",
        "a_genre_clash": "Dragon Parade Clash",
        "a_triple_seven": "Dragon Roster Testament Testament",
        "a_thousand_complete": "Dragon Maid Marathon Epilogue",
        "a_pi_episodes": "Tohru Crown Crown",
        "a_synchronicity": "Maid Marathon Anchor",
        "a_world_record": "Software Warrant",
        "a_nice": "Marathon Chronicle",
        "a_power_level": "Family Fan Testament Testament",
        "a_answer_42": "Marathon Standard Standard",
        "a_square_number": "Miss Kobayashi's Dragon Maid Decree",
        "a_prime_count": "Dragon Family Seal Seal",
        "a_matching_date": "Dragon Family Fan Mantle",
        "a_century_episode": "Miss Kobayashi's Dragon Maid Standard",
        "a_double_digits": "Dragon Codex Testament",
        "a_one_two_three": "Dragons Crown",
        "a_lucky_seven": "Kobayashi's Flat Crown",
        "a_all_tens": "Dragon Codex Criterion",
        "a_exact_hundred_eps": "Lost Dragons Legend",
        "a_year_match_count": "Lost Dragons Clock",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Dragon Codex Crown Crown",
        "a_movie_buff": "Dragon Family Fan Mark",
        "a_ova_hunter": "Family Standard",
        "a_ona_explorer": "Tohru Secret",
        "a_special_watcher": "Dragons Relic",
        "a_short_king": "Family Fan Crown Crown",
        "a_variety_pack": "Family Fan Inquiry",
        "a_film_festival": "Miss Kobayashi's Dragon Maid Chronicle",
        "a_music_video": "Dragon Family Fan Proof",
        "a_tv_short": "Dragon Trophies Record Record",
        "a_movie_marathon": "Dragon Trophies Gauntlet",
        "a_double_length": "Maid Marathon Crown",
        "a_anthology": "Lost Dragons Aegis",
        "a_mini_series": "Lost Dragons Decree",
        "a_theatrical": "Archive Accord",
        "a_format_master": "Family Fan Vault",
        "a_long_movie": "Maid Insignia",
        "a_back_catalog": "Dragon World Vault Standard",
        "a_cm_watcher": "Maid Aegis Aegis",
        "a_pv_collector": "Dragon Storehouse",
        "a_format_balance": "Dragon Roster Vault",
        "a_episodic_master": "Dragon Trophies Standard",
        "a_sequel_movie": "Kobayashi's Flat Pinnacle",
        "a_recap_watcher": "Maid Accord",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Dragons Daily",
        "a_mega_streak": "Dragon Parade Streak",
        "a_weekly_warrior": "Kobayashi's Flat Season",
        "a_monthly_watcher": "Maid Marathon Calendar",
        "a_comeback": "Archive Decree",
        "a_weekend_streak": "Kobayashi Passage",
        "a_no_zero_days": "Dragon Maid Marathon Warrant",
        "a_iron_will": "Maid Seal",
        "a_habit_formed": "Software Warrant Warrant",
        "a_consistent_pace": "Dragon Roster Measure",
        "a_year_long": "Software Season",
        "a_double_streak": "Dragon Codex Watch",
        "a_streak_recovery": "Dragon Alerts Season",
        "a_daily_minimum": "Maid Marathon Focus",
        "a_winter_streak": "Kobayashi Watch",
        "a_summer_streak": "Dragons Resolve",
        "a_morning_streak": "Maid Clock",
        "a_night_streak": "Japan Constancy",
        "a_unbreakable": "Dragon Maid Marathon Proof",
        "a_eternal_flame": "Family Standard Standard",
        "a_completion_streak": "Miss Kobayashi's Dragon Return",
        "a_rating_streak": "Software Balance",
        "a_multi_ep_streak": "Maid Marathon Ritual",
        "a_genre_streak": "Dragon Streak",
        "a_studio_streak": "Lost Dragons Cabinet",
        "a_perfect_week": "Kobayashi Relic",

        // ── ANIME SCORING ──
        "a_critic": "Kobayashi's Flat Scrutiny",
        "a_perfect_ten": "Archive Audit",
        "a_harsh_critic": "Family Gauge",
        "a_fair_judge": "Tohru Balance",
        "a_generous_spirit": "Software Pinnacle",
        "a_score_all": "Tohru Criterion",
        "a_wide_range": "Dragon Parade Ledger",
        "a_controversial": "Dragon World Vault Decree",
        "a_consistent_scorer": "Dragon World Vault Verdict",
        "a_score_sniper": "Dragon Roster Score",
        "a_evolving_taste": "Kobayashi Testament",
        "a_bell_curve": "Dragon Maid Insignia",
        "a_picky_watcher": "Dragon Warrant Warrant",
        "a_100_rated": "Miss Kobayashi's Dragon Maid Banner",
        "a_500_rated": "Maid Marathon Pinnacle",
        "a_mediocre_majority": "Kobayashi Canon",
        "a_rating_spree": "Dragon Parade Review",
        "a_score_variance": "Maid Marathon Score",
        "a_masterpiece_hunter": "Miss Kobayashi's Dragon Banner",
        "a_contrarian": "Archive Record",
        "a_optimist": "Marathon Ledger",
        "a_score_distributor": "Kobayashi's Flat Appraisal",
        "a_genre_critic": "Dragon Codex Critic",
        "a_mean_above_8": "Dragon Maid Marathon Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "Software Resolve",
        "a_valentines_weeb": "Family Vow",
        "a_pi_day": "Family Fan Trial Trial",
        "a_april_fools": "Dragon Maid Marathon Devotion Devotion",
        "a_international_anime_day": "Tohru Pinnacle",
        "a_star_wars_day": "Dragon Family Chronicle",
        "a_summer_solstice": "Dragon Family Fan Calendar",
        "a_tanabata": "Dragon Codex Focus",
        "a_friday_13th": "Dragon Codex Relic",
        "a_halloween_spirit": "Dragon Trophies Vow",
        "a_thanksgiving_binge": "Maid Run Run",
        "a_christmas_special": "Maid Marathon Season",
        "a_new_years_eve": "Family Fan Pilgrimage",
        "a_birthday_watch": "Dragon Parade Vow",
        "a_holiday_marathon": "Miss Kobayashi's Dragon Overture Overture",
        "a_independence_day": "Miss Kobayashi's Dragon Banner Banner",
        "a_culture_day": "Dragon World Vault Insignia",
        "a_spring_equinox": "Family Decree",
        "a_earth_day": "Family Record",
        "a_labor_day": "Archive Seal Seal",
        "a_winter_solstice": "Dragon Alerts Pilgrimage",
        "a_anime_birthday": "Dragon Codex Pilgrimage",
        "a_every_holiday": "Kobayashi's Flat Resolve",
        "a_consecutive_holidays": "Tohru Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Dragon Parade Rank",
        "a_meta_collector": "Dragon Trophies Hoard",
        "a_meta_category_starter": "Kobayashi Badge",
        "a_meta_tier_climber": "Miss Kobayashi's Dragon Glyph",
        "a_meta_tier_max": "Japan Writ",
        "a_meta_xp_earner": "Dragon Emblem",
        "a_meta_difficulty_easy": "Dragons Mechanism",
        "a_meta_difficulty_hard": "Maid Writ",
        "a_meta_unlock_spree": "Kobayashi Panel",
        "a_meta_completionist": "Dragon Family Fan Fulfillment",
        "a_meta_diverse": "Dragon Alerts Emblem",
        "a_meta_dominator": "Family Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Chapter",
        "m_chapter_counter": "Tohru Ledger",
        "m_chapter_titan": "Maid Marathon Legend",
        "m_reading_hours": "Tohru Relic",
        "m_reading_time_lord": "Kobayashi Pinnacle Pinnacle",
        "m_manga_collector": "Kobayashi's Flat Ledger",
        "m_library_legend": "Maid Reliquary",
        "m_first_complete": "Tohru Triumph",
        "m_hundred_club": "Family Network",
        "m_first_day": "Lost Dragons Dawn",
        "m_first_rating": "Dragon Maid Marathon Eye",
        "m_ten_thousand_pages": "Dragon Family Gauge",
        "m_volume_collector": "Dragon Codex Storehouse",
        "m_year_explorer": "Archive Quest",
        "m_century_reader": "Software Dominion",
        "m_five_hundred_ch": "Dragon Trophies Ledger",
        "m_thousand_ch": "Dragons Testament",
        "m_reading_ten": "Dragon Codex Appraisal",
        "m_ptr_hoarder": "Maid Marathon Index",
        "m_dropped_honesty": "Japan Summit",
        "m_season_reader": "Archive Treasury",
        "m_active_reader": "Dragons Trial",
        "m_five_thousand_ch": "Maid Legend",
        "m_ten_completed": "Marathon Resolution",
        "m_fifty_completed": "Kobayashi's Flat Harvest",
        "m_five_hundred_completed": "Miss Kobayashi's Dragon Legacy",
        "m_mean_score_tracker": "Maid Audit",
        "m_unique_authors": "Dragon Codex Reserve",
        "m_all_status": "Dragon Alerts Testament",
        "m_first_favorite": "Archive Cache",
        "m_favorites_collector": "Archive Shelf",
        "m_days_spent_reading": "Family Decree Decree",

        // ── MANGA BINGE ──
        "m_binge_reader": "Dragon World Vault Streak",
        "m_marathon_reader": "Dragon Rush",
        "m_weekend_reader": "Software Night",
        "m_non_stop_reading": "Dragon Maid Gauntlet",
        "m_one_more_chapter": "Tohru Testament Testament",
        "m_speed_read": "Dragons Drive",
        "m_double_story": "Dragon Alerts Dominion",
        "m_triple_read": "Dragons Mantle",
        "m_five_a_day": "Dragon Family Insignia",
        "m_chapter_chain": "Maid Accord Accord",
        "m_volume_binge": "Dragon Maid Marathon Drive Drive",
        "m_power_reader": "Dragon Trophies Seal",
        "m_half_day_read": "Archive Aegis Aegis",
        "m_full_day_read": "Family Aegis",
        "m_power_weekend": "Japan Streak",
        "m_binge_king": "Dragon Maid Momentum",
        "m_no_sleep_read": "Dragon Family Fan Rush",
        "m_full_series_rush": "Tohru Cascade",
        "m_seven_day_challenge": "Kobayashi Warrant",
        "m_hundred_day_read": "Dragon Maid Marathon Relic",
        "m_volume_rush": "Miss Kobayashi's Dragon Maid Gauntlet",
        "m_series_sweep": "Kobayashi Trial",
        "m_genre_binge": "Marathon Binge",
        "m_author_binge": "Dragon Maid Surge",
        "m_chapter_counter_day": "Dragon Family Ledger",
        "m_multi_series_binge": "Dragon World Vault Charge",
        "m_midnight_binge": "Software Tempest",
        "m_new_year_binge": "Maid Marathon Passage",
        "m_forty_eight_hour": "Dragon Parade Rally",
        "m_oneshot_binge": "Kobayashi Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Dragon Action",
        "m_genre_adventure": "Kobayashi's Flat Adventure",
        "m_genre_comedy": "Lost Dragons Comedy",
        "m_genre_drama": "Dragon Trophies Drama",
        "m_genre_fantasy": "Kobayashi Fantasy",
        "m_genre_horror": "Dragon Family Fan Horror",
        "m_genre_mystery": "Family Mystery",
        "m_genre_romance": "Japan Romance",
        "m_genre_scifi": "Dragon Family Fan Sci-Fi",
        "m_genre_sol": "Tohru Slice",
        "m_genre_sports": "Miss Kobayashi's Dragon Maid Sports",
        "m_genre_supernatural": "Dragon Roster Supernatural",
        "m_genre_thriller": "Dragon Maid Marathon Thriller",
        "m_genre_psychological": "Dragon World Vault Psychological",
        "m_genre_isekai": "Dragon Isekai",
        "m_genre_shounen": "Kobayashi's Flat Shounen",
        "m_genre_ecchi": "Kobayashi's Flat Ecchi",
        "m_genre_mahou_shoujo": "Miss Kobayashi's Dragon Maid Magic",
        "m_genre_mecha": "Dragon Maid Marathon Mecha",
        "m_genre_music": "Japan Music Current",
        "m_tag_isekai_new": "Dragon Codex Isekai New",
        "m_tag_harem": "Software Harem Style",
        "m_tag_bl": "Archive Bl",
        "m_tag_gl": "Dragon Codex Gl",
        "m_tag_historical": "Japan Historical Badge",
        "m_tag_military": "Dragon Family Fan Military",
        "m_tag_school": "Japan School",
        "m_tag_martial_arts": "Dragon Maid Marathon Martial Arts",
        "m_tag_vampire": "Dragon Trophies Vampire",
        "m_tag_samurai": "Dragon Parade Samurai Domain",
        "m_tag_space": "Dragon Family Space",
        "m_tag_parody": "Dragon Family Fan Parody",
        "m_tag_idol": "Dragon Parade Idol",
        "m_tag_post_apocalyptic": "Dragon Family Post Apocalyptic",
        "m_tag_cyberpunk": "Dragon Family Fan Cyberpunk",
        "m_tag_shoujo": "Lost Dragons Shoujo",
        "m_tag_survival": "Archive Survival",
        "m_tag_cooking": "Japan Cooking",
        "m_tag_medical": "Dragon Codex Medical",
        "m_tag_villainess": "Archive Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Manga Archive",
        "m_mega_completionist": "Marathon Completion",
        "m_completion_rate_50": "Dragon Parade Return",
        "m_completion_rate_75": "Dragon Family Fan Ascension",
        "m_completion_rate_90": "Dragon Parade Resolution",
        "m_no_drop": "Dragon Maid Decree",
        "m_long_runner_complete": "Marathon Clear",
        "m_sequel_chain": "Dragon Maid Marathon Warrant Warrant",
        "m_clean_list": "Maid Marathon Relic Relic",
        "m_from_ptr": "Dragon Family Accord",
        "m_reread_master": "Software Trial",
        "m_oneshot_complete": "Kobayashi's Flat Ascension Ascension",
        "m_same_day_start_finish": "Maid Marathon Crown Crown",
        "m_revival": "Miss Kobayashi's Dragon Maid Accord",
        "m_zero_to_hundred": "Dragon Maid Legend Banner",
        "m_five_genre_complete": "Family Fan M Five Genre",
        "m_full_collection": "Tohru Proof",
        "m_batch_complete": "Maid Summit",
        "m_paused_to_done": "Dragon Family Fan Testament",
        "m_completion_spree": "Tohru Triumph Triumph",
        "m_format_completionist": "Maid Marathon Testament",
        "m_catch_up": "Maid Chronicle",
        "m_multi_reread": "Lost Dragons Banner Banner",
        "m_dropped_recovery": "Kobayashi Conquest",
        "m_ten_perfect_scores": "Japan Judgment",
        "m_complete_genre_span": "Dragon Alerts M Complete Genre",
        "m_monthly_completions": "Lost Dragons Return",
        "m_yearly_completions": "Kobayashi Epilogue",
        "m_rapid_complete": "Kobayashi's Flat Finale",
        "m_author_complete": "Dragon Trophies Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Dragon Family Legacy",
        "m_mangaka_lover": "Dragon Family Fan Testament Testament",
        "m_rereader": "Dragon Roster Relic",
        "m_triple_reread": "Dragon Codex Testament Testament",
        "m_annual_reread": "Dragon Codex Dominion",
        "m_publisher_fan": "Kobayashi's Flat Mark",
        "m_artist_fan": "Marathon Insignia Insignia",
        "m_adaptation_compare": "Dragon Parade Insignia",
        "m_source_material_fan": "Lost Dragons Cache",
        "m_waiting_weekly": "Japan Weekly",
        "m_classic_reader": "Kobayashi's Flat Lantern",
        "m_saga_reader": "Dragon Roster Crown",
        "m_genre_loyalty": "Kobayashi Loyalty",
        "m_decade_reader": "Dragon Codex Warrant",
        "m_ln_adaptation": "Dragon Trophies Accord",
        "m_original_work": "Archive Standard",
        "m_long_commitment": "Dragon Trophies Accord Accord",
        "m_up_to_date": "Dragon Alerts Dominion Dominion",
        "m_favorite_mangaka": "Dragon World Vault Treasury",
        "m_complete_portfolio": "Dragon Triumph",
        "m_franchise_collector": "Lost Dragons Archive",
        "m_serialization_follower": "Maid Handshake",
        "m_genre_master": "Software Master",
        "m_multi_series_author": "Dragon Family Record",
        "m_format_diversity": "Dragon World Vault Shelf",
        "m_year_dedication": "Maid Marathon Tenure",
        "m_ongoing_follower": "Dragon Roster Fellowship",
        "m_genre_loyalty_50": "Dragon Codex Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Japan Explorer",
        "m_publisher_hopper": "Family Fan Mantle",
        "m_tag_explorer": "Dragon Family Fan Explorer",
        "m_decade_hopper": "Dragon Maid Chronicle",
        "m_hidden_gem": "Software Mark",
        "m_popular_taste": "Dragon Codex Mantle",
        "m_retro_reader": "Lost Dragons Accord",
        "m_modern_reader": "Japan Seal Seal",
        "m_cross_demographic": "Dragon Maid Marathon Crown",
        "m_underdog_fan": "Software Mark Mark",
        "m_variety_week": "Lost Dragons Horizon",
        "m_manhwa_reader": "Dragons Proof",
        "m_manhua_reader": "Dragons Mantle Mantle",
        "m_classic_connoisseur": "Lost Dragons Glimpse",
        "m_award_winner": "Dragon Maid Seal Seal",
        "m_niche_explorer": "Dragon Codex Prospect",
        "m_world_manga": "Maid Chronicle Chronicle",
        "m_cult_classic": "Dragon World Vault Map",
        "m_random_pick": "Dragons Mark",
        "m_new_genre_month": "Dragon Maid M New Genre",
        "m_year_completionist": "Dragon Codex Fulfillment",
        "m_unpopular_opinion": "Dragon Maid Marathon Trial",
        "m_top_rated_reader": "Software Pinnacle Pinnacle",
        "m_source_variety": "Tohru Catalogue",
        "m_low_score_brave": "Dragon Maid Marathon Score",
        "m_short_manga_explorer": "Dragon Trophies Compass",
        "m_long_manga_explorer": "Dragon Trophies Survey",
        "m_serialization_explorer": "Dragon Alerts Road",

        // ── MANGA TIME ──
        "m_night_owl": "Dragon Codex Mark Mark",
        "m_early_bird": "Archive Banner",
        "m_lunch_reader": "Family Fan Relic Relic",
        "m_commute_reader": "Kobayashi's Flat Tenure",
        "m_four_am_club": "Dragon Maid Marathon Fellowship",
        "m_new_year_read": "Archive Pact",
        "m_all_hours": "Japan Accord Accord",
        "m_prime_time_reader": "Family Banner",
        "m_workday_reader": "Dragon Trophies Standard Standard",
        "m_sunday_read": "Dragon Family Accord Accord",
        "m_morning_routine": "Dragon Family Discipline",
        "m_night_shift_reader": "Dragon Maid Accord",
        "m_seasonal_premier_read": "Software Seasonal",
        "m_clock_collector": "Family Fan Reserve",
        "m_late_night_horror": "Dragons Mark Mark",
        "m_afternoon_reader": "Tohru Mantle Mantle",
        "m_golden_hour_reader": "Tohru Observance",
        "m_dawn_reader": "Family Fan Mantle Mantle",
        "m_twilight_reader": "Dragon Family Fan Relic Relic",
        "m_midnight_start": "Japan Routine",
        "m_weekend_binge_hours": "Dragon Parade Momentum",
        "m_late_night_regular": "Maid Marathon Testament Testament",
        "m_sunrise_reader": "Dragon World Vault Insignia Insignia",
        "m_every_day_of_week": "Lost Dragons Seal Seal",
        "m_monthly_hours": "Dragon Family Vigil",
        "m_bedtime_reader": "Kobayashi Warrant Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Dragon Roster Pinnacle",
        "m_webtoon_reader": "Dragon Alerts Mark Mark",
        "m_full_color": "Kobayashi Mark",
        "m_doujin_reader": "Family Record Record",
        "m_anthology_reader": "Dragon Maid Accord Accord",
        "m_adaptation_reader": "Dragon World Vault Banner",
        "m_longstrip_reader": "Dragons Trial Trial",
        "m_4koma_reader": "Kobayashi's Flat Relic",
        "m_oneshot_reader": "Kobayashi Mantle",
        "m_format_variety": "Dragon Alerts Gallery",
        "m_light_novel_reader": "Family Insignia Insignia",
        "m_novel_reader": "Dragon Alerts Crown Crown",
        "m_visual_storyteller": "Software Testament",
        "m_colored_classic": "Dragon Parade Survey",
        "m_webcomic_fan": "Dragon Family Record Record",
        "m_manga_to_anime": "Dragon Codex Mantle Mantle",
        "m_seinen_reader": "Dragon Pinnacle Pinnacle",
        "m_josei_reader": "Dragon Roster Pinnacle Pinnacle",
        "m_award_winning_art": "Dragon Roster Relic Relic",
        "m_debut_work": "Software Dominion Dominion",
        "m_vertical_scroll": "Dragon Trophies Decree Decree",
        "m_traditional_format": "Family Hoard",
        "m_cross_media": "Lost Dragons Accord Accord",
        "m_spinoff_reader": "Dragon World Vault Standard Standard",
        "m_remake_reader": "Dragon Maid Insignia Insignia",
        "m_collaboration_reader": "Dragon Codex Proof",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Family Fan Focus",
        "m_mega_streak": "Marathon Routine",
        "m_weekly_warrior": "Dragon Codex Season",
        "m_monthly_reader": "Family Discipline",
        "m_comeback": "Dragon Parade Standard",
        "m_weekend_streak": "Family Fan Fever",
        "m_no_zero_days": "Dragon Roster Proof",
        "m_iron_will": "Miss Kobayashi's Dragon Ledger",
        "m_habit_formed": "Kobayashi's Flat Crown Crown",
        "m_consistent_pace": "Tohru Scrutiny",
        "m_year_long": "Maid Marathon Observance",
        "m_double_streak": "Dragon Maid Marathon Resolve",
        "m_streak_recovery": "Tohru Resolve",
        "m_daily_minimum": "Dragon Maid Marathon Focus",
        "m_winter_streak": "Dragons Observance",
        "m_summer_streak": "Kobayashi Observance",
        "m_morning_streak": "Lost Dragons Clock Clock",
        "m_night_streak": "Miss Kobayashi's Dragon Discipline",
        "m_unbreakable": "Maid Marathon Warrant Warrant",
        "m_eternal_flame": "Dragon Parade Record",
        "m_chapter_a_day": "Dragon Family Ledger Ledger",
        "m_genre_streak": "Dragons Streak",
        "m_completion_streak": "Maid Return Return",
        "m_rating_streak": "Dragon Appraisal",
        "m_multi_ch_streak": "Dragon Tenure",
        "m_author_streak": "Tohru Calendar",
        "m_perfect_week_manga": "Miss Kobayashi's Dragon Standard",
        "m_diverse_streak": "Miss Kobayashi's Dragon Streak",

        // ── MANGA SCORING ──
        "m_critic": "Family Fan Scrutiny",
        "m_perfect_ten": "Dragon Parade Verdict",
        "m_harsh_critic": "Maid Scale",
        "m_fair_judge": "Kobayashi Eye",
        "m_generous_spirit": "Dragon Crown Crown",
        "m_score_all": "Tohru Reckoning",
        "m_wide_range": "Miss Kobayashi's Dragon Ledger Ledger",
        "m_controversial": "Dragon Family Standard",
        "m_consistent_scorer": "Dragon Trophies Grade",
        "m_score_sniper": "Dragon Maid Marathon Reckoning",
        "m_evolving_taste": "Dragon Alerts Trial Trial",
        "m_bell_curve": "Maid Marathon Mark",
        "m_picky_reader": "Dragon Relic",
        "m_100_rated": "Family Fan Mark",
        "m_500_rated": "Kobayashi's Flat Proof",
        "m_mediocre_majority": "Dragon Codex Canon",
        "m_rating_spree": "Archive Verdict",
        "m_score_variance": "Dragon Roster Measure Measure",
        "m_binge_rater": "Family Fan Passage",
        "m_reread_rerate": "Dragon Family Banner",
        "m_masterpiece_hunter": "Archive Banner Banner",
        "m_contrarian": "Dragon World Vault Aegis",
        "m_optimist": "Archive Accord Accord",
        "m_score_distributor": "Dragon Codex Balance",
        "m_genre_critic": "Kobayashi's Flat Critic",
        "m_mean_above_8": "Software Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Dragon Alerts New Year",
        "m_valentines_read": "Kobayashi's Flat Observance",
        "m_pi_day": "Kobayashi Testament Testament",
        "m_april_fools": "Dragon Parade Routine",
        "m_international_manga_day": "Dragon Codex Proof Proof",
        "m_free_comic_day": "Japan Chronicle",
        "m_summer_solstice": "Dragon Roster Focus",
        "m_tanabata": "Maid Marathon Pilgrimage",
        "m_friday_13th": "Dragon Dominion",
        "m_halloween_read": "Family Fan Calendar",
        "m_thanksgiving_binge": "Miss Kobayashi's Dragon Charge",
        "m_christmas_read": "Marathon Pact",
        "m_new_years_eve": "Dragons Pilgrimage",
        "m_birthday_read": "Dragon Maid Marathon Birthday",
        "m_holiday_marathon": "Miss Kobayashi's Dragon Rally",
        "m_independence_day": "Dragon Maid Aegis Aegis",
        "m_culture_day": "Marathon Seal",
        "m_spring_equinox": "Dragon Maid Banner Banner",
        "m_earth_day": "Dragon Trophies Aegis",
        "m_labor_day": "Marathon Seal Seal",
        "m_winter_solstice": "Dragon Family Fan Focus",
        "m_manga_birthday": "Kobayashi Ritual",
        "m_every_holiday_reader": "Dragon Alerts Watch",
        "m_consecutive_holidays": "Kobayashi's Flat Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Dragon Family Fan Proof Proof",
        "m_fibonacci": "Dragon Codex Dominion Dominion",
        "m_palindrome_day": "Dragon Relic Relic",
        "m_binary_day": "Dragons Proof Proof",
        "m_full_moon_read": "Software Crown",
        "m_leap_year_read": "Miss Kobayashi's Dragon Practice",
        "m_triple_seven": "Maid Marathon Trial",
        "m_thousand_complete": "Dragon Roster Ascension",
        "m_nice": "Dragon World Vault Seal",
        "m_power_level_chapters": "Dragon Parade Aegis",
        "m_answer_42": "Maid Marathon Trial Trial",
        "m_square_number": "Miss Kobayashi's Dragon Standard Standard",
        "m_prime_count": "Dragon Maid Record",
        "m_matching_date": "Software Mantle",
        "m_century_chapter": "Dragon Maid Marathon Crown Crown",
        "m_pi_chapters": "Dragon Trophies Aegis Aegis",
        "m_synchronicity": "Software Emblem",
        "m_world_record": "Family Fan Warrant",
        "m_genre_clash": "Dragon Parade Clash Route",
        "m_time_traveler": "Maid Decree Decree",
        "m_double_digits": "Dragon Parade Banner",
        "m_one_two_three": "Dragon Codex Warrant Warrant",
        "m_lucky_seven": "Tohru Pinnacle Pinnacle",
        "m_exact_hundred_ch": "Kobayashi's Flat Testament",
        "m_year_match_count": "Lost Dragons Routine",
        "m_chapter_match_date": "Dragon Family Fan Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Maid Marathon Index Index",
        "m_manhwa_format": "Dragon Roster Gallery",
        "m_manhua_format": "Family Fan Storehouse",
        "m_ln_format": "Dragon Index",
        "m_oneshot_format": "Dragon Index Index",
        "m_doujin_format": "Dragon World Vault Cabinet",
        "m_novel_format": "Dragon Maid Marathon Reserve",
        "m_format_master_manga": "Family Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Dragon Maid Link",
        "m_meta_collector": "Maid Reliquary Reliquary",
        "m_meta_category_starter": "Dragon Family Fan Standard",
        "m_meta_tier_climber": "Dragon Family Token",
        "m_meta_tier_max": "Miss Kobayashi's Dragon Maid Token",
        "m_meta_xp_earner": "Software Anchor",
        "m_meta_difficulty_easy": "Dragon Alerts Panel",
        "m_meta_difficulty_hard": "Maid Marathon Node",
        "m_meta_unlock_spree": "Dragon Codex Marker",
        "m_meta_completionist": "Software Triumph",
        "m_meta_diverse": "Software Anchor Anchor",
        "m_meta_dominator": "Archive Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#000400",
        primary: "#349428",
        secondary: "#e03030",
        accent: "#f0c020",
    },
    particleColor: "#40b830",
    backgroundDim: 0.25,
    backgroundBlur: 15,
    milestoneNames: {
  1: "Threadbare Generic Rank Spark",
  8: "Generic's Tarnished Omen",
  14: "Fractured Generic Rank",
  21: "Generic Rank Path",
  28: "Lowborn Legacy Myth",
  35: "Generic Rank Pulse",
  41: "Generic's Legacy Crest",
  48: "Humble Generic Mark",
  55: "Ragged Generic Rank Vow",
  61: "Generic's Faint Echo",
  68: "Lesser Generic Rank",
  75: "Generic Rank Zenith",
  81: "Doubtful Legacy Bloom",
  88: "Generic Rank Sigil",
  95: "Generic's Legacy Flame",
  102: "Really Cool Generic Spark",
  108: "Awakened Generic Rank Omen",
  115: "Generic's Resolute Seal",
  122: "Rising Generic Rank",
  128: "Generic Rank Myth",
  135: "Dauntless Legacy Pulse",
  142: "Generic Rank Crest",
  149: "Generic's Legacy Mark",
  155: "Fresh Generic Vow",
  162: "Valiant Generic Rank Echo",
  169: "Generic's Prime Crown",
  175: "Polished Generic Rank",
  182: "Generic Rank Bloom",
  189: "Stormlit Legacy Sigil",
  195: "Generic Rank Flame",
  202: "Generic's Legacy Spark",
  209: "Tempered Generic Omen",
  216: "Trusted Generic Rank Seal",
  222: "Generic's Steadfast Path",
  229: "Ironclad Generic Rank",
  236: "Veteran Legacy Pulse",
  242: "Core Legacy Crest",
  249: "Generic Rank Mark",
  256: "Generic's Legacy Vow",
  262: "Formidable Generic Echo",
  269: "Lucid Generic Rank Crown",
  276: "Generic's Ranked Zenith",
  283: "Fabled Generic Rank",
  289: "Grand Legacy Sigil",
  296: "Seasoned Legacy Flame",
  303: "Generic Rank Spark",
  309: "Generic's Legacy Omen",
  316: "Valorous Generic Seal",
  323: "Stalwart Generic Rank Path",
  330: "Generic's Commanding Myth",
  336: "Refined Generic Rank",
  343: "Unbroken Legacy Crest",
  350: "Blazing Legacy Mark",
  356: "Generic Rank Vow",
  363: "Generic's Legacy Echo",
  370: "Peerless Generic Crown",
  376: "Ardent Generic Rank Zenith",
  383: "Generic's Focused Bloom",
  390: "Vigilant Generic Rank",
  397: "Dominant Legacy Flame",
  403: "Elite Legacy Spark",
  410: "Generic Rank Omen",
  417: "Generic's Legacy Seal",
  423: "Sovereign Generic Path",
  430: "Regal Generic Rank Myth",
  437: "Generic's Crowned Pulse",
  444: "Mythborn Generic Rank",
  450: "Limitless Legacy Mark",
  457: "Radiant Legacy Vow",
  464: "Generic Rank Echo",
  470: "Generic's Legacy Crown",
  477: "Climactic Generic Zenith",
  484: "Epic Generic Rank Bloom",
  490: "Generic's Unreal Sigil",
  497: "Peak Generic Rank",
  504: "Supreme Legacy Spark",
  511: "Exalted Legacy Omen",
  517: "Generic Rank Seal",
  524: "Generic's Legacy Path",
  531: "Celestial Generic Myth",
  537: "Phantom Generic Rank Pulse",
  544: "Generic's Crimson Crest",
  551: "Silver Generic Rank",
  557: "Golden Legacy Vow",
  564: "Feral Legacy Echo",
  571: "Generic Rank Crown",
  578: "Generic's Legacy Zenith",
  584: "Dread Generic Bloom",
  591: "Luminous Generic Rank Sigil",
  598: "Generic's Thunderous Flame",
  604: "Ultraviolet Generic Rank",
  611: "Unleashed Legacy Omen",
  618: "Secret Legacy Seal",
  625: "Final Generic Path",
  631: "Generic's Legacy Myth",
  638: "Worldclass Generic Pulse",
  645: "Lawless Generic Rank Crest",
  651: "Generic's Chosen Mark",
  658: "Fearless Generic Rank",
  665: "Overdrive Legacy Echo",
  671: "Cinematic Legacy Crown",
  678: "Impossible Generic Zenith",
  685: "Generic's Legacy Bloom",
  692: "Canonized Generic Sigil",
  698: "Ascendant Generic Rank Flame",
  705: "Generic's Transfigured Spark",
  712: "Immortal Generic Rank",
  718: "Eclipsed Legacy Seal",
  725: "Astral Legacy Path",
  732: "Sublime Generic Myth",
  739: "Generic's Legacy Pulse",
  745: "Prismatic Generic Crest",
  752: "Abyssal Generic Rank Mark",
  759: "Generic's Unbound Vow",
  765: "Eternal Generic Rank",
  772: "Cosmic Legacy Crown",
  779: "Transcendent Legacy Zenith",
  785: "Perfected Generic Bloom",
  792: "Generic's Legacy Sigil",
  799: "Ultimate Generic Flame",
  806: "Mythic Generic Rank Spark",
  812: "Generic's Godlike Omen",
  819: "Canonical Generic Rank",
  826: "Reality-Bent Legacy Path",
  832: "Heavenly Legacy Myth",
  839: "Absolute Generic Pulse",
  846: "Untouchable Generic Crest",
  852: "Timeless Generic Mark",
  859: "Empyrean Generic Rank Vow",
  866: "Generic's Primordial Echo",
  873: "Omniscient Generic Rank",
  879: "Unfathomed Legacy Zenith",
  886: "Apocalyptic Legacy Bloom",
  893: "Seraphic Generic Sigil",
  899: "Omega Generic Flame",
  906: "Final Generic Spark",
  913: "Crowned Generic Rank Omen",
  920: "Generic's Mythic Seal",
  926: "Absolute Generic Rank",
  933: "Eternal Legacy Myth",
  940: "Cosmic Legacy Pulse",
  946: "Transcendent Generic Crest",
  953: "Perfected Generic Mark",
  960: "Definitive Generic Vow",
  966: "Ultimate Generic Rank Echo",
  973: "Generic's Infinite Crown",
  980: "Sovereign Generic Rank",
  987: "Celestial Legacy Bloom",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate Generic Rank"
},
}
