import { AnimeThemeConfig } from "./types"
import { GiSpearHook, GiForestCamp, GiAncientSword, GiWaterDrop, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiMountainRoad } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const moribitoTheme: AnimeThemeConfig = {
    id: "moribito",
    displayName: "Moribito: Guardian of the Spirit",
    description: "Balsa, a female spear-wielder with a vow to protect eight lives, becomes bodyguard to Prince Chagum — a boy who carries a water spirit's egg that the empire wants destroyed.",
    fontFamily: "'Noto Serif JP', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "165 200 155",
        "--color-brand-300": "120 172 108",
        "--color-brand-400": "78 144 65",
        "--color-brand-500": "44 116 30",
        "--color-brand-600": "28 90 18",
        "--color-brand-700": "16 66 10",
        "--color-brand-800": "8 44 5",
        "--color-brand-900": "4 26 2",
        "--color-brand-950": "1 14 1",
        "--brand": "44 116 30",
        "--background": "#010600",
        "--paper": "#050e04",
        "--color-gray-950": "1 6 0",
        "--color-gray-900": "4 12 3",
        "--color-gray-800": "8 22 7",
        "--color-gray-700": "14 38 12",
        "--color-gray-600": "24 60 20",
        "--color-gray-500": "40 90 34",
        "--color-gray-400": "72 130 64",
        "--color-gray-300": "112 170 104",
        "--color-gray-200": "155 200 148",
        "--color-gray-100": "192 224 186",
        "--color-gray-50": "228 242 225",
    },
    sidebarOverrides: {
        "home": { icon: GiForestCamp, label: "Yogo Kingdom" },
        "schedule": { icon: GiAlarmClock, label: "Journey Schedule" },
        "manga": { icon: LuBookOpen, label: "Spirit Texts" },
        "lists": { icon: GiAncientSword, label: "Guardian Registry" },
        "discover": { icon: GiBullseye, label: "Empire Scouting" },
        "torrent-list": { icon: GiSpearHook, label: "Spear Cache" },
        "debrid": { icon: GiWaterDrop, label: "Water Spirit" },
        "unmatched": { icon: GiMountainRoad, label: "Lost Paths" },
        "enmasse": { icon: GiResize, label: "Empire Forces" },
        "scan-summaries": { icon: TbReportSearch, label: "Journey Records" },
        "auto-downloader": { icon: LuRss, label: "Spirit News" },
        "community": { icon: GiForestCamp, label: "Village Network" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Spirit Calls" },
        "achievements": { icon: GiTrophy, label: "Guardian Titles" },
        "milestones": { icon: LuFlag, label: "Guardian Goals" },
        "theme-manager": { icon: GiPalette, label: "Earth Colors" },
        "extensions": { icon: BiExtension, label: "Spear Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Spirit Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Guardian Rules" },
    },
    achievementNames: {
        "a_first_episode": "Guardian Vow",
        "a_first_complete": "Spirit Released",
        "a_hundred_club": "Hundred Battles",
        "a_time_lord": "Spear Veteran",
        "a_anime_collector": "Spear Collection",
        "a_library_legend": "Kingdom Archives",
        "a_binge_king": "Journey Marathon",
        "a_no_sleep": "All-Night Guard",
        "a_marathon_runner": "Long March",
        "a_speed_run": "Balsa's Speed",
        "a_completionist": "All Guarded",
        "a_mega_completionist": "Uehashi Master",
        "a_loyal_fan": "Chagum's Guard",
        "a_rewatcher": "Journey Revisit",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Spear Combat",
        "a_genre_adventure": "Kingdom Journey",
        "a_genre_comedy": "Tanda's Care",
        "a_genre_drama": "Vow of Eight",
        "a_genre_fantasy": "Spirit World",
        "a_genre_horror": "Empire Terror",
        "a_genre_romance": "Balsa Tanda",
        "a_genre_scifi": "Spirit Biology",
        "a_genre_supernatural": "Water Spirit",
        "a_genre_psychological": "Guardian's Burden",
        "a_genre_mecha": "None Here",
        "a_critic": "Guardian Judge",
        "a_perfect_ten": "Spear Master",
        "a_harsh_critic": "Strict Guardian",
        "a_daily_streak": "Daily Guard",
        "a_mega_streak": "Endless Vigil",
        "a_year_long": "Year of Guarding",
        "a_iron_will": "Balsa's Vow",
        "a_hidden_gem": "Spirit Gem",
        "a_cult_classic": "Uehashi Classic",
        "a_classic_connoisseur": "2007 Fan",
        "a_new_years_resolution": "New Year Vow",
        "a_christmas_special": "Winter Guard",
        "a_meta_tier_max": "Legend Guardian",
        "a_meta_completionist": "Complete Vigil",
        "a_sequel_chain": "Novel Series",
        "a_zero_to_hero": "Wanderer to Guardian",
        "a_night_owl": "Night Guard",
        "a_early_bird": "Dawn Vigil",
        "m_first_chapter": "First Vow",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Guardian Marathon",
        "m_completionist": "Full Journey",
        "m_mega_completionist": "Spirit Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Journey Revisit",
        "m_genre_action": "Spear Chapter",
        "m_genre_adventure": "Kingdom Chapter",
        "m_genre_romance": "Heart Chapter",
        "m_genre_fantasy": "Spirit Chapter",
        "m_genre_horror": "Empire Chapter",
        "m_genre_drama": "Vow Chapter",
        "m_genre_scifi": "Spirit Science",
        "m_genre_supernatural": "Water Chapter",
        "m_genre_psychological": "Guardian Depth",
        "m_critic": "Spirit Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Unbroken Vigil",
        "m_year_long": "Year Reading",
        "m_iron_will": "Guardian Resolve",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Classic Novel",
        "m_mangaka_lover": "Uehashi Fan",
        "m_source_material_fan": "Novel First",
        "m_meta_tier_max": "Guardian Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Spirit Art",
        "m_manga_to_anime": "Novel Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#010600",
        primary: "#2c741e",
        secondary: "#1c5a12",
        accent: "#a08030",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/moribito.jpg",
    particleColor: "#60c050",
    backgroundDim: 0.32,
    backgroundBlur: 18,
    particleTypes: {
        water_droplets: { label: "Water Droplets", maxCount: 18, defaultEnabled: true, defaultIntensity: 55 },
        leaves: { label: "Forest Leaves", maxCount: 15, defaultEnabled: true, defaultIntensity: 50 },
    },
    milestoneNames: {
    1: "Generic Rank",
    7: "Generic Rank",
    14: "Generic Rank",
    21: "Generic Rank",
    27: "Generic Rank",
    34: "Generic Rank",
    41: "Generic Rank",
    47: "Generic Rank",
    54: "Generic Rank",
    61: "Generic Rank",
    68: "Generic Rank",
    74: "Generic Rank",
    81: "Generic Rank",
    88: "Generic Rank",
    94: "Generic Rank",
    101: "Generic Rank",
    108: "Generic Rank",
    114: "Generic Rank",
    121: "Generic Rank",
    128: "Generic Rank",
    135: "Generic Rank",
    141: "Generic Rank",
    148: "Generic Rank",
    155: "Generic Rank",
    161: "Generic Rank",
    168: "Generic Rank",
    175: "Generic Rank",
    182: "Generic Rank",
    188: "Generic Rank",
    195: "Generic Rank",
    202: "Generic Rank",
    208: "Generic Rank",
    215: "Generic Rank",
    222: "Generic Rank",
    228: "Generic Rank",
    235: "Generic Rank",
    242: "Generic Rank",
    249: "Generic Rank",
    255: "Generic Rank",
    262: "Generic Rank",
    269: "Generic Rank",
    275: "Generic Rank",
    282: "Generic Rank",
    289: "Generic Rank",
    296: "Generic Rank",
    302: "Generic Rank",
    309: "Generic Rank",
    316: "Generic Rank",
    322: "Generic Rank",
    329: "Generic Rank",
    336: "Generic Rank",
    342: "Generic Rank",
    349: "Generic Rank",
    356: "Generic Rank",
    363: "Generic Rank",
    369: "Generic Rank",
    376: "Generic Rank",
    383: "Generic Rank",
    389: "Generic Rank",
    396: "Generic Rank",
    403: "Generic Rank",
    409: "Generic Rank",
    416: "Generic Rank",
    423: "Generic Rank",
    430: "Generic Rank",
    436: "Generic Rank",
    443: "Generic Rank",
    450: "Generic Rank",
    456: "Generic Rank",
    463: "Generic Rank",
    470: "Generic Rank",
    477: "Generic Rank",
    483: "Generic Rank",
    490: "Generic Rank",
    497: "Generic Rank",
    503: "Generic Rank",
    510: "Generic Rank",
    517: "Generic Rank",
    523: "Generic Rank",
    530: "Generic Rank",
    537: "Generic Rank",
    544: "Generic Rank",
    550: "Generic Rank",
    557: "Generic Rank",
    564: "Generic Rank",
    570: "Generic Rank",
    577: "Generic Rank",
    584: "Generic Rank",
    591: "Generic Rank",
    597: "Generic Rank",
    604: "Generic Rank",
    611: "Generic Rank",
    617: "Generic Rank",
    624: "Generic Rank",
    631: "Generic Rank",
    637: "Generic Rank",
    644: "Generic Rank",
    651: "Generic Rank",
    658: "Generic Rank",
    664: "Generic Rank",
    671: "Generic Rank",
    678: "Generic Rank",
    684: "Generic Rank",
    691: "Generic Rank",
    698: "Generic Rank",
    704: "Generic Rank",
    711: "Generic Rank",
    718: "Generic Rank",
    725: "Generic Rank",
    731: "Generic Rank",
    738: "Generic Rank",
    745: "Generic Rank",
    751: "Generic Rank",
    758: "Generic Rank",
    765: "Generic Rank",
    772: "Generic Rank",
    778: "Generic Rank",
    785: "Generic Rank",
    792: "Generic Rank",
    798: "Generic Rank",
    805: "Generic Rank",
    812: "Generic Rank",
    818: "Generic Rank",
    825: "Generic Rank",
    832: "Generic Rank",
    839: "Generic Rank",
    845: "Generic Rank",
    852: "Generic Rank",
    859: "Generic Rank",
    865: "Generic Rank",
    872: "Generic Rank",
    879: "Generic Rank",
    886: "Generic Rank",
    892: "Generic Rank",
    899: "Generic Rank",
    906: "Generic Rank",
    912: "Generic Rank",
    919: "Generic Rank",
    926: "Generic Rank",
    932: "Generic Rank",
    939: "Generic Rank",
    946: "Generic Rank",
    953: "Generic Rank",
    959: "Generic Rank",
    966: "Generic Rank",
    973: "Generic Rank",
    979: "Generic Rank",
    986: "Generic Rank",
    993: "Generic Rank",
    1000: "Generic Rank",
  },
}
