import { AnimeThemeConfig } from "./types"
import { GiHeartKey, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiCrystalBall, GiStarSwirl, GiSpellBook, GiFlowerEmblem } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const nagiNoAsukaraTheme: AnimeThemeConfig = {
    id: "nagi-no-asukara",
    displayName: "Nagi-Asu: A Lull in the Sea",
    description: "Sea people Hikari and friends are forced to attend school on land when their underwater school closes. Torn between two worlds, they navigate first loves and an ancient conflict as winter threatens to swallow them all.",
    cssVars: {
        "--color-brand-200": "168 218 255",
        "--color-brand-300": "100 178 250",
        "--color-brand-400": "42 135 238",
        "--color-brand-500": "5 95 215",
        "--color-brand-600": "0 62 172",
        "--color-brand-700": "0 36 128",
        "--color-brand-800": "0 18 80",
        "--color-brand-900": "0 6 40",
        "--color-brand-950": "0 2 18",
        "--brand": "5 95 215",
        "--background": "#000209",
        "--paper": "#000518",
        "--color-gray-950": "0 2 9",
        "--color-gray-900": "0 6 20",
        "--color-gray-800": "1 14 40",
        "--color-gray-700": "3 26 65",
        "--color-gray-600": "6 48 100",
        "--color-gray-500": "12 80 145",
        "--color-gray-400": "28 120 185",
        "--color-gray-300": "58 162 218",
        "--color-gray-200": "100 198 242",
        "--color-gray-100": "155 225 255",
        "--color-gray-50": "210 244 255",
    },
    sidebarOverrides: {
        "home": { icon: GiFlowerEmblem, label: "Shioshishio" },
        "schedule": { icon: GiAlarmClock, label: "Tide Schedule" },
        "manga": { icon: LuBookOpen, label: "Sea Scrolls" },
        "lists": { icon: GiScrollUnfurled, label: "Sea Registry" },
        "discover": { icon: GiBullseye, label: "New Currents" },
        "torrent-list": { icon: GiCrystalBall, label: "Deep Cache" },
        "debrid": { icon: GiHeartKey, label: "Sea Vault" },
        "unmatched": { icon: GiStarSwirl, label: "Lost Currents" },
        "enmasse": { icon: GiResize, label: "Ofunehiki" },
        "scan-summaries": { icon: TbReportSearch, label: "Ocean Reports" },
        "auto-downloader": { icon: LuRss, label: "Sea Feed" },
        "community": { icon: GiSpellBook, label: "Lull Circle" },
        "achievements": { icon: GiTrophyCup, label: "Ocean Trophies" },
        "milestones": { icon: LuFlag, label: "Tide Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Tide Alerts" },
        "theme-manager": { icon: GiPalette, label: "Ocean Colors" },
        "extensions": { icon: BiExtension, label: "Sea Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Ocean Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Hikari Config" },
    },
    achievementNames: {
        "a_first_episode": "Surfaced to Land",
        "a_first_complete": "First Land Friendship",
        "a_hundred_club": "Hundred Ocean Days",
        "a_binge_king": "Nagi-Asu Marathon",
        "a_completionist": "Ofunehiki Complete",
        "a_mega_completionist": "Two Worlds United",
        "a_loyal_fan": "Ocean Fan",
        "a_zero_to_hero": "Sea Child to Bridge",
        "m_first_chapter": "First Wave",
        "m_completionist": "Full Ocean Archive",
    },
    musicUrl: "",
    previewColors: {
        bg: "#000209",
        primary: "#055fd7",
        secondary: "#c06820",
        accent: "#a0d8f8",
    },
    particleColor: "#2890e8",
    backgroundDim: 0.32,
    backgroundBlur: 25,
    milestoneNames: {
        1: "Sea Child",
        5: "Land School Student",
        15: "Bridge Builder",
        30: "Hibernation Prepared",
        50: "Woken from the Deep",
        75: "Time Passed",
        100: "Sea and Land United",
    },
}
