import { AnimeThemeConfig } from "./types"
import { GiGasMask, GiTreeBranch, GiMushroom, GiWindsock, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiLeafSwirl } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const nausicaaTheme: AnimeThemeConfig = {
    id: "nausicaa",
    displayName: "Nausicaä of the Valley of the Wind",
    description: "In a world consumed by the toxic Sea of Decay, Nausicaä rides the winds and seeks understanding between humanity and the giant insects — Miyazaki's ecological manifesto.",
    fontFamily: "'Cormorant Garamond', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;600&display=swap",
    cssVars: {
        "--color-brand-200": "215 200 150",
        "--color-brand-300": "195 172 100",
        "--color-brand-400": "175 145 58",
        "--color-brand-500": "155 120 22",
        "--color-brand-600": "128 98 14",
        "--color-brand-700": "100 76 8",
        "--color-brand-800": "72 54 4",
        "--color-brand-900": "44 32 2",
        "--color-brand-950": "25 18 0",
        "--brand": "155 120 22",
        "--background": "#050604",
        "--paper": "#0d0e08",
        "--color-gray-950": "5 6 4",
        "--color-gray-900": "12 14 9",
        "--color-gray-800": "22 26 16",
        "--color-gray-700": "36 42 26",
        "--color-gray-600": "56 64 40",
        "--color-gray-500": "85 96 62",
        "--color-gray-400": "125 135 100",
        "--color-gray-300": "165 172 138",
        "--color-gray-200": "198 202 175",
        "--color-gray-100": "222 225 206",
        "--color-gray-50": "242 244 234",
    },
    sidebarOverrides: {
        "home": { icon: GiWindsock, label: "Valley of the Wind" },
        "schedule": { icon: GiAlarmClock, label: "Migration Times" },
        "manga": { icon: LuBookOpen, label: "Ancient Tomes" },
        "lists": { icon: GiLeafSwirl, label: "Forest Registry" },
        "discover": { icon: GiBullseye, label: "Ohm Territory" },
        "torrent-list": { icon: GiMushroom, label: "Spore Cache" },
        "debrid": { icon: GiGasMask, label: "Toxic Filter" },
        "unmatched": { icon: GiTreeBranch, label: "Lost in Jungle" },
        "enmasse": { icon: GiResize, label: "Insect Swarm" },
        "scan-summaries": { icon: TbReportSearch, label: "Valley Reports" },
        "auto-downloader": { icon: LuRss, label: "Wind Signals" },
        "community": { icon: GiWindsock, label: "Valley Folk" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Ohm Warning" },
        "achievements": { icon: GiTrophy, label: "Peace Medals" },
        "milestones": { icon: LuFlag, label: "Valley Goals" },
        "theme-manager": { icon: GiPalette, label: "Forest Colors" },
        "extensions": { icon: BiExtension, label: "Mehve Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Valley Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Valley Controls" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Flight",
        "a_episode_counter": "Perfect Peace Mark",
        "a_episode_titan": "Peace Medals Relic",
        "a_hours_invested": "Non Stop Proof",
        "a_time_lord": "Valley Elder",
        "a_anime_collector": "Spore Collected",
        "a_library_legend": "Ancient Archives",
        "a_first_complete": "Ohm Calm",
        "a_hundred_club": "Hundred Flights",
        "a_first_day": "Toxic Filter Seal",
        "a_first_rating": "Peace Medals Appraisal",
        "a_ten_thousand_min": "Miyazaki Fan Standard",
        "a_season_veteran": "Miyazaki Fan Library",
        "a_year_explorer": "Toxic Jungle Map",
        "a_century_watcher": "Daily Flight Ledger",
        "a_five_hundred_eps": "Dawn Flight Dominion",
        "a_thousand_eps": "Ohm Territory Record",
        "a_watching_ten": "Ohm Calm Acclaim",
        "a_ptw_hoarder": "Ecological Art Library",
        "a_dropped_honesty": "Ohm Calm Summit",
        "a_five_thousand_eps": "Endless Wind Warrant",
        "a_ten_completed": "Night Rider Afterglow",
        "a_fifty_completed": "Wind Marathon Ascension",
        "a_five_hundred_completed": "Ohm Calm Clear",
        "a_mean_score_tracker": "Stern Warrior Verdict",
        "a_unique_studios": "Ohm Territory Collection",
        "a_days_spent_watching": "Valley Revisit Dominion",
        "a_all_status": "Hidden Valley Testament",
        "a_first_favorite": "Ohm Warning Cabinet",
        "a_favorites_collector": "Wind Signals Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Insect Swarm Drive",
        "a_marathon_runner": "Wind Marathon",
        "a_weekend_warrior": "Peace Medals Ordeal",
        "a_non_stop": "Migration Times Fever",
        "a_one_more_episode": "Ohm Stampede Mantle",
        "a_speed_run": "Mehve Speed",
        "a_double_feature": "Valley Folk Crown",
        "a_triple_threat": "Jungle World Record",
        "a_five_a_day": "Daily Wind Accord",
        "a_back_to_back": "Teto's Tricks Surge",
        "a_seasonal_binge": "Peace Medals Cascade",
        "a_cour_crusher": "Valley Revisit Ordeal",
        "a_half_day_watch": "Perfect Peace Crown",
        "a_full_day_watch": "Mehve Speed Pinnacle",
        "a_power_weekend": "Toxic Filter Run",
        "a_binge_king": "Non-Stop Flight",
        "a_no_sleep": "All-Night Watch",
        "a_entire_season": "God Warrior Library",
        "a_seven_day_challenge": "Mehve Speed Mark",
        "a_hundred_day_binge": "Toxic Filter Surge",
        "a_genre_binge": "Forest Registry Binge",
        "a_studio_binge": "Perfect Peace Fever",
        "a_season_sweep": "Valley Controls Codex",
        "a_forty_eight_hour": "Wind Return Overture",
        "a_ep_counter_day": "Night Rider Aegis",
        "a_multi_series_binge": "Ecological Art Streak",
        "a_midnight_binge": "Ohm Stampede Cascade",
        "a_new_year_binge": "Classic Fan Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Battle Rider",
        "a_genre_adventure": "World Explorer",
        "a_genre_comedy": "Teto's Tricks",
        "a_genre_drama": "Nausicaa's Burden",
        "a_genre_fantasy": "Toxic Jungle",
        "a_genre_horror": "Ohm Stampede",
        "a_genre_mystery": "Valley's Heart Mystery",
        "a_genre_romance": "Valley's Heart",
        "a_genre_scifi": "Ancient Technology",
        "a_genre_sol": "Endless Wind Slice",
        "a_genre_sports": "Wind Return Sports",
        "a_genre_supernatural": "Prophet's Child",
        "a_genre_thriller": "Wind Marathon Thriller",
        "a_genre_mecha": "God Warrior",
        "a_genre_music": "Miyazaki Fan Music",
        "a_genre_psychological": "War's Truth",
        "a_genre_ecchi": "Insect Swarm Ecchi",
        "a_genre_mahou_shoujo": "Jungle World Magic Shoujo",
        "a_tag_isekai": "Blue Clad Isekai",
        "a_tag_harem": "All Night Harem",
        "a_tag_bl": "Wind Return Bl",
        "a_tag_gl": "Ohm Stampede Gl",
        "a_tag_historical": "Iron Will Historical",
        "a_tag_military": "Dawn Flight Military",
        "a_tag_school": "Ecological Art School",
        "a_tag_martial_arts": "Mehve Speed Martial Arts",
        "a_tag_vampire": "Jungle World Vampire",
        "a_tag_samurai": "Ohm Territory Samurai",
        "a_tag_space": "Decade Fan Space",
        "a_tag_parody": "Stop Flight Parody",
        "a_tag_idol": "Wind Return Idol",
        "a_tag_post_apocalyptic": "Unbroken Gale Post Apocalyptic",
        "a_tag_cyberpunk": "Migration Times Cyberpunk",
        "a_tag_shounen": "Unbroken Gale Shounen",
        "a_tag_seinen": "Night Watch Seinen",
        "a_tag_shoujo": "Night Watch Shoujo",
        "a_tag_josei": "Night Rider Josei",
        "a_tag_survival": "Wind Signals Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "Peace Achieved",
        "a_mega_completionist": "Miyazaki Master",
        "a_completion_rate_50": "Jungle World Return",
        "a_completion_rate_75": "Wind Marathon Crown",
        "a_completion_rate_90": "Night Rider Resolution",
        "a_no_drop": "Valley's Heart Decree",
        "a_long_runner_complete": "Toxic Filter Clear",
        "a_sequel_chain": "Manga Sequel",
        "a_clean_list": "Valley Controls Relic",
        "a_from_ptw": "Stop Flight Index",
        "a_rewatch_master": "Stern Warrior Return",
        "a_short_complete": "Ancient Tomes Endgame",
        "a_same_day_start_finish": "Peace Achieved Pinnacle",
        "a_revival": "Daily Flight Insignia",
        "a_zero_to_hero": "Princess to Legend",
        "a_five_genre_complete": "Ancient Tomes A Five Genre",
        "a_full_franchise": "Ecological Art Chronicle",
        "a_batch_complete": "Peace Medals Crown",
        "a_paused_to_done": "Night Rider Aegis Aegis",
        "a_completion_spree": "Battle Rider Triumph",
        "a_multi_rewatch": "Battle Rider Triumph Triumph",
        "a_dropped_recovery": "Perfect Peace Conquest",
        "a_ten_perfect_scores": "Toxic Filter Acclaim",
        "a_seasonal_clear": "Valley Revisit Codex",
        "a_complete_genre_span": "Wind Judge A Complete Genre",
        "a_monthly_completions": "Stern Warrior Afterglow",
        "a_yearly_completions": "Hidden Valley Epilogue",
        "a_rapid_complete": "Mehve Speed Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Valley Guardian",
        "a_studio_devotee": "Valley's Heart Treasury",
        "a_rewatcher": "Wind Return",
        "a_triple_rewatch": "Forest Registry Coda",
        "a_annual_tradition": "Mehve Speed Proof",
        "a_director_fan": "Valley Controls Trial",
        "a_voice_actor_fan": "Perfect Peace Crown Crown",
        "a_ost_lover": "Ecological Art Seal",
        "a_source_reader": "Toxic Jungle Cabinet",
        "a_waiting_weekly": "Valley's Heart Clock",
        "a_childhood_revisit": "Valley Elder Seal",
        "a_saga_tracker": "Decade Fan Standard",
        "a_genre_loyalty": "Endless Wind Loyalty",
        "a_decade_watcher": "Decade Fan",
        "a_adaptation_hunter": "Stop Flight Trial",
        "a_original_anime_fan": "War's Truth Testament",
        "a_long_commitment": "Mehve Speed Mark Mark",
        "a_perfect_attendance": "Ohm Calm Standard",
        "a_favorite_studio_5": "Unbroken Gale Library",
        "a_complete_catalog": "Wind Signals Seal",
        "a_franchise_collector": "Unbroken Gale Archive",
        "a_airing_follower": "Valley Elder Signal",
        "a_genre_master": "Valley Controls Master",
        "a_staff_follower": "Unbroken Gale Oath",
        "a_multi_season_fan": "Iron Will Hoard",
        "a_format_diversity": "Jungle World Cache",
        "a_year_dedication": "Peace Medals Tenure",
        "a_season_dedication": "Dawn Flight Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Forest Registry Explorer",
        "a_studio_hopper": "Stern Warrior Collection",
        "a_tag_explorer": "Peace Medals Explorer",
        "a_decade_hopper": "Ecological Art Chronicle Chronicle",
        "a_hidden_gem": "Hidden Valley",
        "a_popular_taste": "Wind Return Decree",
        "a_retro_appreciator": "Wind Signals Aegis",
        "a_modern_viewer": "Peace Achieved Pinnacle Pinnacle",
        "a_cross_demographic": "Insect Swarm Pinnacle",
        "a_underdog_fan": "Wind Judge Trial",
        "a_variety_week": "Unbroken Gale Horizon",
        "a_foreign_cinema": "Ohm Stampede Expedition",
        "a_classic_connoisseur": "84 Classic Fan",
        "a_every_season": "Valley Elder Archive",
        "a_award_winner": "Miyazaki Fan Insignia",
        "a_niche_explorer": "Night Watch Horizon",
        "a_global_anime": "Ancient Tomes Crown",
        "a_cult_classic": "Miyazaki Classic",
        "a_random_pick": "Wind Return Decree Decree",
        "a_new_genre_month": "Ohm Calm A New Genre",
        "a_seasonal_completionist": "Daily Flight Summit",
        "a_unpopular_opinion": "Ohm Warning Standard",
        "a_top_rated_viewer": "Daily Wind Seal",
        "a_source_variety": "Valley Revisit Storehouse",
        "a_low_score_brave": "Migration Times Measure",
        "a_upcoming_watcher": "Daily Wind Seal Seal",
        "a_short_series_explorer": "Ohm Stampede Expedition Expedition",
        "a_long_series_explorer": "Valley Folk Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Night Rider",
        "a_early_bird": "Dawn Flight",
        "a_lunch_break": "Deep Mind Trial",
        "a_golden_hour": "Ancient Tech Tenure",
        "a_four_am_club": "Battle Rider Gathering",
        "a_witching_hour": "Wind Marathon Tenure",
        "a_new_year_watch": "Peace Medals Season",
        "a_midnight_premiere": "Classic Fan Devotion",
        "a_all_hours": "Daily Flight Seal",
        "a_dawn_warrior": "Wind Return Aegis",
        "a_afternoon_delight": "Non Stop Proof Proof",
        "a_prime_time": "Miyazaki Fan Insignia Insignia",
        "a_workday_watcher": "Insect Swarm Pinnacle Pinnacle",
        "a_sunday_marathon": "Toxic Filter Momentum",
        "a_rainy_day": "Wind Marathon Relic",
        "a_morning_routine": "Iron Will Promise",
        "a_night_shift": "Jungle World Aegis",
        "a_twilight_zone": "God Warrior Ledger",
        "a_seasonal_premier": "Valley's Heart Cabinet",
        "a_clock_collector": "Battle Rider Repository",
        "a_weekend_binge_hours": "Night Watch Streak",
        "a_late_night_regular": "Hidden Valley Dominion",
        "a_sunrise_watcher": "Valley Controls Relic Relic",
        "a_holiday_watcher": "Daily Wind Pact",
        "a_every_day_of_week": "Teto's Tricks Ledger",
        "a_monthly_hours": "Wind Return Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Night Rider Record",
        "a_party_host": "Jungle World Record Record",
        "a_social_butterfly": "Toxic Jungle Company",
        "a_group_binge": "Ohm Territory Sprint",
        "a_party_regular": "God Warrior Chronicle",
        "a_sync_viewer": "Battle Rider Standard",
        "a_commentator": "Wind Signals Record",
        "a_party_marathon": "Forest Registry Vigil",
        "a_full_house": "Dawn Flight Trial",
        "a_community_pillar": "Hidden Valley Alliance",
        "a_watch_party_streak": "Wind Signals Vigil",
        "a_diverse_party": "Iron Will Seal",
        "a_late_night_party": "Hidden Valley Testament Testament",
        "a_party_veteran": "Dawn Flight Testament",
        "a_genre_party": "Ohm Stampede Party",
        "a_weekly_party": "Battle Rider Calendar",
        "a_silent_viewer": "War's Truth Mantle",
        "a_recommendation_giver": "Night Watch Network",
        "a_party_completionist": "Decade Fan Coda",
        "a_social_scorer": "Valley Controls Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Valley Folk Proof",
        "a_fibonacci": "Peace Medals Dominion",
        "a_palindrome_day": "Peace Medals Relic Relic",
        "a_binary_day": "Endless Wind Mark",
        "a_full_moon": "Valley Elder Insignia",
        "a_leap_year": "Ancient Tomes Devotion",
        "a_time_traveler": "Valley's Heart Record",
        "a_genre_clash": "Forest Registry Clash",
        "a_triple_seven": "Peace Medals Testament",
        "a_thousand_complete": "War's Truth Epilogue",
        "a_pi_episodes": "Insect Swarm Crown",
        "a_synchronicity": "Wind Judge Anchor",
        "a_world_record": "Perfect Peace Warrant",
        "a_nice": "Miyazaki Fan Chronicle",
        "a_power_level": "War's Truth Testament Testament",
        "a_answer_42": "Wind Return Standard",
        "a_square_number": "Forest Registry Decree",
        "a_prime_count": "Miyazaki Fan Seal",
        "a_matching_date": "Wind Judge Mantle",
        "a_century_episode": "Insect Swarm Mark",
        "a_double_digits": "Wind Marathon Testament",
        "a_one_two_three": "Ancient Tomes Crown Crown",
        "a_lucky_seven": "Mehve Speed Crown",
        "a_all_tens": "Migration Times Criterion",
        "a_exact_hundred_eps": "Decade Fan Legend",
        "a_year_match_count": "Valley's Heart Yearlong",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Night Watch Ledger",
        "a_movie_buff": "Perfect Peace Mark Mark",
        "a_ova_hunter": "Decade Fan Standard Standard",
        "a_ona_explorer": "Wind Judge Secret",
        "a_special_watcher": "Wind Marathon Relic Relic",
        "a_short_king": "All Night Crown",
        "a_variety_pack": "Perfect Peace Inquiry",
        "a_film_festival": "Daily Wind Chronicle",
        "a_music_video": "Iron Will Chronicle",
        "a_tv_short": "Forest Registry Record",
        "a_movie_marathon": "Forest Registry Gauntlet",
        "a_double_length": "Valley Folk Crown Crown",
        "a_anthology": "Jungle World Aegis Aegis",
        "a_mini_series": "Ohm Warning Decree",
        "a_theatrical": "Unbroken Gale Accord",
        "a_format_master": "Battle Rider Vault",
        "a_long_movie": "Daily Flight Insignia Insignia",
        "a_back_catalog": "Wind Signals Standard",
        "a_cm_watcher": "Blue Clad Aegis",
        "a_pv_collector": "Wind Judge Storehouse",
        "a_format_balance": "Battle Rider Vault Vault",
        "a_episodic_master": "Blue Clad Standard",
        "a_sequel_movie": "Ancient Tomes Pinnacle",
        "a_recap_watcher": "Deep Mind Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Flight",
        "a_mega_streak": "Endless Wind",
        "a_weekly_warrior": "Dawn Flight Season",
        "a_monthly_watcher": "Classic Fan Calendar",
        "a_comeback": "Toxic Jungle Decree",
        "a_weekend_streak": "Migration Times Passage",
        "a_no_zero_days": "Endless Wind Warrant Warrant",
        "a_iron_will": "Nausicaa's Will",
        "a_habit_formed": "Teto's Tricks Banner",
        "a_consistent_pace": "Valley Folk Measure",
        "a_year_long": "Year in Valley",
        "a_double_streak": "Valley Controls Watch",
        "a_streak_recovery": "War's Truth Season",
        "a_daily_minimum": "Classic Fan Focus",
        "a_winter_streak": "Ohm Stampede Watch",
        "a_summer_streak": "Wind Marathon Resolve",
        "a_morning_streak": "Wind Signals Clock",
        "a_night_streak": "Teto's Tricks Constancy",
        "a_unbreakable": "All Night Proof",
        "a_eternal_flame": "Stern Warrior Standard",
        "a_completion_streak": "Decade Fan Return",
        "a_rating_streak": "Peace Medals Balance",
        "a_multi_ep_streak": "Perfect Peace Ritual",
        "a_genre_streak": "Peace Medals Streak",
        "a_studio_streak": "Toxic Jungle Cabinet Cabinet",
        "a_perfect_week": "Wind Judge Relic",

        // ── ANIME SCORING ──
        "a_critic": "Wind Judge",
        "a_perfect_ten": "Perfect Peace",
        "a_harsh_critic": "Stern Warrior",
        "a_fair_judge": "Hidden Valley Balance",
        "a_generous_spirit": "Classic Fan Pinnacle",
        "a_score_all": "Non Stop Criterion",
        "a_wide_range": "Miyazaki Fan Ledger",
        "a_controversial": "Wind Signals Decree",
        "a_consistent_scorer": "Valley's Heart Verdict",
        "a_score_sniper": "Ancient Tomes Score",
        "a_evolving_taste": "Valley Controls Testament",
        "a_bell_curve": "Ohm Calm Insignia",
        "a_picky_watcher": "War's Truth Warrant",
        "a_100_rated": "Battle Rider Warrant",
        "a_500_rated": "All Night Pinnacle",
        "a_mediocre_majority": "Wind Judge Canon",
        "a_rating_spree": "Wind Signals Review",
        "a_score_variance": "Migration Times Score",
        "a_masterpiece_hunter": "Wind Signals Banner",
        "a_contrarian": "Forest Registry Record Record",
        "a_optimist": "Iron Will Ledger",
        "a_score_distributor": "Deep Mind Appraisal",
        "a_genre_critic": "Valley Folk Critic",
        "a_mean_above_8": "Mehve Speed Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Flight",
        "a_valentines_weeb": "Unbroken Gale Vow",
        "a_pi_day": "Hidden Valley Trial",
        "a_april_fools": "Ancient Tomes Devotion Devotion",
        "a_international_anime_day": "Daily Flight Record",
        "a_star_wars_day": "Toxic Filter Chronicle",
        "a_summer_solstice": "Endless Wind Calendar",
        "a_tanabata": "Peace Achieved Focus",
        "a_friday_13th": "Deep Mind Relic",
        "a_halloween_spirit": "Night Watch Vow",
        "a_thanksgiving_binge": "God Warrior Run",
        "a_christmas_special": "Spore Season",
        "a_new_years_eve": "Mehve Speed Pilgrimage",
        "a_birthday_watch": "Ohm Calm Vow",
        "a_holiday_marathon": "Ohm Territory Overture",
        "a_independence_day": "Stern Warrior Banner",
        "a_culture_day": "Ecological Art Insignia",
        "a_spring_equinox": "Ohm Territory Decree",
        "a_earth_day": "Perfect Peace Mantle",
        "a_labor_day": "Night Watch Seal",
        "a_winter_solstice": "Insect Swarm Pilgrimage",
        "a_anime_birthday": "Perfect Peace Pilgrimage",
        "a_every_holiday": "Stop Flight Resolve",
        "a_consecutive_holidays": "Wind Marathon Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Toxic Jungle Rank",
        "a_meta_collector": "Ecological Art Hoard",
        "a_meta_category_starter": "Classic Fan Badge",
        "a_meta_tier_climber": "Ecological Art Glyph",
        "a_meta_tier_max": "Blue Clad One",
        "a_meta_xp_earner": "Deep Mind Emblem",
        "a_meta_difficulty_easy": "Hidden Valley Mechanism",
        "a_meta_difficulty_hard": "Daily Wind Writ",
        "a_meta_unlock_spree": "Dawn Flight Panel",
        "a_meta_completionist": "Complete Chronicles",
        "a_meta_diverse": "Peace Medals Emblem",
        "a_meta_dominator": "God Warrior Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Wind",
        "m_chapter_counter": "Battle Rider Pinnacle",
        "m_chapter_titan": "Valley Revisit Relic",
        "m_reading_hours": "Deep Mind Relic Relic",
        "m_reading_time_lord": "Daily Flight Record Record",
        "m_manga_collector": "Dawn Flight Ledger",
        "m_library_legend": "Ecological Art Reliquary",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "Unbroken Gale Seal",
        "m_first_rating": "Deep Mind Eye",
        "m_ten_thousand_pages": "Unbroken Gale Gauge",
        "m_volume_collector": "War's Truth Storehouse",
        "m_year_explorer": "Wind Return Quest",
        "m_century_reader": "Ohm Stampede Dominion",
        "m_five_hundred_ch": "Miyazaki Fan Legend",
        "m_thousand_ch": "Valley Controls Legend",
        "m_reading_ten": "Ohm Stampede Appraisal",
        "m_ptr_hoarder": "Valley Controls Index",
        "m_dropped_honesty": "Ecological Art Summit",
        "m_season_reader": "Wind Signals Treasury",
        "m_active_reader": "Wind Marathon Trial",
        "m_five_thousand_ch": "Forest Registry Standard",
        "m_ten_completed": "Forest Registry Resolution",
        "m_fifty_completed": "Valley Controls Harvest",
        "m_five_hundred_completed": "Teto's Tricks Legacy",
        "m_mean_score_tracker": "Valley's Heart Audit",
        "m_unique_authors": "Perfect Peace Reserve",
        "m_all_status": "Wind Marathon Testament Testament",
        "m_first_favorite": "Decade Fan Cache",
        "m_favorites_collector": "Toxic Jungle Shelf",
        "m_days_spent_reading": "Insect Swarm Relic",

        // ── MANGA BINGE ──
        "m_binge_reader": "Ohm Calm Streak",
        "m_marathon_reader": "Hidden Valley Rush",
        "m_weekend_reader": "Valley Elder Run",
        "m_non_stop_reading": "Decade Fan Gauntlet",
        "m_one_more_chapter": "Deep Mind Testament Testament",
        "m_speed_read": "Endless Wind Drive",
        "m_double_story": "Ohm Territory Banner",
        "m_triple_read": "Stern Warrior Record",
        "m_five_a_day": "Iron Will Insignia",
        "m_chapter_chain": "Ecological Art Accord",
        "m_volume_binge": "Migration Times Drive",
        "m_power_reader": "Toxic Filter Seal Seal",
        "m_half_day_read": "Toxic Jungle Aegis",
        "m_full_day_read": "Blue Clad Aegis Aegis",
        "m_power_weekend": "Unbroken Gale Streak",
        "m_binge_king": "Marathon Read",
        "m_no_sleep_read": "Ohm Stampede Rush",
        "m_full_series_rush": "Hidden Valley Cascade",
        "m_seven_day_challenge": "Peace Achieved Warrant",
        "m_hundred_day_read": "Peace Medals Legend",
        "m_volume_rush": "Night Rider Gauntlet",
        "m_series_sweep": "Stop Flight Trial Trial",
        "m_genre_binge": "Blue Clad Binge",
        "m_author_binge": "Valley Elder Surge",
        "m_chapter_counter_day": "God Warrior Ledger Ledger",
        "m_multi_series_binge": "Miyazaki Fan Charge",
        "m_midnight_binge": "Valley Controls Tempest",
        "m_new_year_binge": "Perfect Peace Passage",
        "m_forty_eight_hour": "Valley's Heart Rally",
        "m_oneshot_binge": "Endless Wind Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Battle Chapter",
        "m_genre_adventure": "World Chapter",
        "m_genre_comedy": "Toxic Jungle Comedy",
        "m_genre_drama": "Drama Chapter",
        "m_genre_fantasy": "Jungle World",
        "m_genre_horror": "Dark Chapter",
        "m_genre_mystery": "Forest Registry Mystery",
        "m_genre_romance": "Heart Chapter",
        "m_genre_scifi": "Ancient Tech",
        "m_genre_sol": "Battle Rider Slice",
        "m_genre_sports": "Night Rider Sports",
        "m_genre_supernatural": "Prophet Chapter",
        "m_genre_thriller": "Wind Judge Thriller",
        "m_genre_psychological": "Deep Mind",
        "m_genre_isekai": "Dawn Flight Isekai",
        "m_genre_shounen": "Ancient Tech Shounen",
        "m_genre_ecchi": "Valley Folk Ecchi",
        "m_genre_mahou_shoujo": "Toxic Jungle Magic Shoujo",
        "m_genre_mecha": "War's Truth Mecha",
        "m_genre_music": "Night Watch Music",
        "m_tag_isekai_new": "Deep Mind Isekai New",
        "m_tag_harem": "Non Stop Harem",
        "m_tag_bl": "Ohm Warning Bl",
        "m_tag_gl": "Valley Controls Gl",
        "m_tag_historical": "Miyazaki Fan Historical",
        "m_tag_military": "Ancient Tech Military",
        "m_tag_school": "Unbroken Gale School",
        "m_tag_martial_arts": "Battle Rider Martial Arts",
        "m_tag_vampire": "Night Rider Vampire",
        "m_tag_samurai": "Jungle World Samurai",
        "m_tag_space": "Ohm Warning Space",
        "m_tag_parody": "War's Truth Parody",
        "m_tag_idol": "Ohm Warning Idol",
        "m_tag_post_apocalyptic": "Ecological Art Post Apocalyptic",
        "m_tag_cyberpunk": "Non Stop Cyberpunk",
        "m_tag_shoujo": "Daily Wind Shoujo",
        "m_tag_survival": "Toxic Jungle Survival",
        "m_tag_cooking": "Ohm Calm Cooking",
        "m_tag_medical": "Wind Marathon Medical",
        "m_tag_villainess": "Valley Elder Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Journey",
        "m_mega_completionist": "Manga Master",
        "m_completion_rate_50": "Ohm Warning Return",
        "m_completion_rate_75": "Wind Judge Ascension",
        "m_completion_rate_90": "Stern Warrior Resolution",
        "m_no_drop": "Decade Fan Decree",
        "m_long_runner_complete": "God Warrior Clear",
        "m_sequel_chain": "Night Watch Seal Seal",
        "m_clean_list": "Valley Revisit Relic Relic",
        "m_from_ptr": "Daily Wind Watchlist",
        "m_reread_master": "Hidden Valley Trial Trial",
        "m_oneshot_complete": "Hidden Valley Ascension",
        "m_same_day_start_finish": "Mehve Speed Crown Crown",
        "m_revival": "God Warrior Accord",
        "m_zero_to_hundred": "Forest Registry Banner",
        "m_five_genre_complete": "Endless Wind M Five Genre",
        "m_full_collection": "Mehve Speed Proof Proof",
        "m_batch_complete": "Valley's Heart Summit",
        "m_paused_to_done": "Stern Warrior Standard Standard",
        "m_completion_spree": "All Night Triumph",
        "m_format_completionist": "Hidden Valley Completion",
        "m_catch_up": "Daily Flight Chronicle",
        "m_multi_reread": "Decade Fan Banner",
        "m_dropped_recovery": "Valley Folk Conquest",
        "m_ten_perfect_scores": "Valley Elder Judgment",
        "m_complete_genre_span": "Dawn Flight M Complete Genre",
        "m_monthly_completions": "Blue Clad Return",
        "m_yearly_completions": "Dawn Flight Epilogue",
        "m_rapid_complete": "Peace Achieved Finale",
        "m_author_complete": "Unbroken Gale Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Wind Reader",
        "m_mangaka_lover": "Miyazaki Fan",
        "m_rereader": "Valley Revisit",
        "m_triple_reread": "Peace Medals Testament Testament",
        "m_annual_reread": "Forest Registry Banner Banner",
        "m_publisher_fan": "All Night Mark",
        "m_artist_fan": "Night Watch Insignia",
        "m_adaptation_compare": "Ohm Calm Insignia Insignia",
        "m_source_material_fan": "Manga First",
        "m_waiting_weekly": "Jungle World Streak",
        "m_classic_reader": "War's Truth Lantern",
        "m_saga_reader": "Ecological Art Decree",
        "m_genre_loyalty": "Valley Folk Loyalty",
        "m_decade_reader": "Migration Times Warrant",
        "m_ln_adaptation": "Migration Times Mark",
        "m_original_work": "Night Rider Standard",
        "m_long_commitment": "Valley Folk Mark",
        "m_up_to_date": "Perfect Peace Warrant Warrant",
        "m_favorite_mangaka": "Wind Return Treasury",
        "m_complete_portfolio": "All Night Triumph Triumph",
        "m_franchise_collector": "Daily Flight Archive",
        "m_serialization_follower": "Wind Return Handshake",
        "m_genre_master": "Valley Revisit Master",
        "m_multi_series_author": "Ecological Art Insignia Insignia",
        "m_format_diversity": "Night Rider Shelf",
        "m_year_dedication": "Ohm Stampede Tenure",
        "m_ongoing_follower": "Migration Times Fellowship",
        "m_genre_loyalty_50": "Valley Controls Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Ohm Territory Explorer",
        "m_publisher_hopper": "All Night Mantle",
        "m_tag_explorer": "Stop Flight Explorer",
        "m_decade_hopper": "Daily Wind Chronicle Chronicle",
        "m_hidden_gem": "Hidden Volume",
        "m_popular_taste": "Valley's Heart Record Record",
        "m_retro_reader": "Valley's Heart Accord",
        "m_modern_reader": "Miyazaki Fan Seal Seal",
        "m_cross_demographic": "Classic Fan Crown",
        "m_underdog_fan": "Valley's Heart Accord Accord",
        "m_variety_week": "Night Watch Horizon Horizon",
        "m_manhwa_reader": "Ancient Tomes Proof",
        "m_manhua_reader": "War's Truth Mantle Mantle",
        "m_classic_connoisseur": "Teto's Tricks Glimpse",
        "m_award_winner": "Ohm Stampede Warrant",
        "m_niche_explorer": "Ohm Calm Horizon",
        "m_world_manga": "Daily Flight Chronicle Chronicle",
        "m_cult_classic": "Classic Manga",
        "m_random_pick": "Valley's Heart Standard",
        "m_new_genre_month": "Daily Flight M New Genre",
        "m_year_completionist": "Battle Rider Fulfillment",
        "m_unpopular_opinion": "Perfect Peace Trial",
        "m_top_rated_reader": "Ohm Calm Record",
        "m_source_variety": "War's Truth Catalogue",
        "m_low_score_brave": "Battle Rider Score",
        "m_short_manga_explorer": "Miyazaki Fan Compass",
        "m_long_manga_explorer": "Forest Registry Survey",
        "m_serialization_explorer": "Wind Judge Road",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Ohm Warning Ledger",
        "m_commute_reader": "Wind Marathon Tenure Tenure",
        "m_four_am_club": "All Night Fellowship",
        "m_new_year_read": "Night Watch Pact",
        "m_all_hours": "Daily Wind Accord Accord",
        "m_prime_time_reader": "Night Rider Banner",
        "m_workday_reader": "God Warrior Accord Accord",
        "m_sunday_read": "Ohm Warning Standard Standard",
        "m_morning_routine": "God Warrior Discipline",
        "m_night_shift_reader": "Unbroken Gale Accord Accord",
        "m_seasonal_premier_read": "War's Truth Seasonal",
        "m_clock_collector": "Insect Swarm Reserve",
        "m_late_night_horror": "Endless Wind Mark Mark",
        "m_afternoon_reader": "Ohm Stampede Mantle Mantle",
        "m_golden_hour_reader": "Peace Medals Observance",
        "m_dawn_reader": "Stop Flight Mantle",
        "m_twilight_reader": "Migration Times Crown",
        "m_midnight_start": "Night Rider Routine",
        "m_weekend_binge_hours": "Valley Elder Momentum",
        "m_late_night_regular": "Ohm Warning Accord",
        "m_sunrise_reader": "Non Stop Mantle",
        "m_every_day_of_week": "War's Truth Warrant Warrant",
        "m_monthly_hours": "Ohm Territory Vigil",
        "m_bedtime_reader": "Battle Rider Warrant Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Ecological Art",
        "m_webtoon_reader": "Migration Times Mark Mark",
        "m_full_color": "Night Watch Accord",
        "m_doujin_reader": "Stern Warrior Record Record",
        "m_anthology_reader": "Valley Elder Accord",
        "m_adaptation_reader": "Valley's Heart Banner",
        "m_longstrip_reader": "Peace Medals Trial",
        "m_4koma_reader": "Jungle World Ledger",
        "m_oneshot_reader": "Dawn Flight Mantle",
        "m_format_variety": "All Night Gallery",
        "m_light_novel_reader": "Daily Wind Insignia",
        "m_novel_reader": "Battle Rider Crown",
        "m_visual_storyteller": "Ohm Stampede Testament",
        "m_colored_classic": "Wind Signals Survey",
        "m_webcomic_fan": "Teto's Tricks Insignia",
        "m_manga_to_anime": "Manga to Film",
        "m_seinen_reader": "Valley Folk Pinnacle",
        "m_josei_reader": "Non Stop Pinnacle",
        "m_award_winning_art": "Ancient Tech Relic",
        "m_debut_work": "Ancient Tech Dominion",
        "m_vertical_scroll": "Ecological Art Decree Decree",
        "m_traditional_format": "Ohm Calm Hoard",
        "m_cross_media": "Miyazaki Fan Accord",
        "m_spinoff_reader": "Daily Flight Accord",
        "m_remake_reader": "Hidden Valley Pinnacle",
        "m_collaboration_reader": "Teto's Tricks Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Wind",
        "m_mega_streak": "Unbroken Gale",
        "m_weekly_warrior": "Wind Judge Season",
        "m_monthly_reader": "Iron Will Discipline",
        "m_comeback": "Forest Registry Standard Standard",
        "m_weekend_streak": "Non Stop Fever",
        "m_no_zero_days": "Ancient Tomes Proof Proof",
        "m_iron_will": "Iron Will",
        "m_habit_formed": "Classic Fan Crown Crown",
        "m_consistent_pace": "Mehve Speed Scrutiny Scrutiny",
        "m_year_long": "Year Reading",
        "m_double_streak": "Dawn Flight Resolve",
        "m_streak_recovery": "Valley Revisit Resolve",
        "m_daily_minimum": "Insect Swarm Focus",
        "m_winter_streak": "Peace Medals Observance Observance",
        "m_summer_streak": "Ancient Tech Observance",
        "m_morning_streak": "Ohm Territory Clock",
        "m_night_streak": "Ohm Calm Discipline",
        "m_unbreakable": "Non Stop Warrant",
        "m_eternal_flame": "Toxic Jungle Record",
        "m_chapter_a_day": "Ohm Warning Ledger Ledger",
        "m_genre_streak": "Stop Flight Streak",
        "m_completion_streak": "Valley's Heart Return",
        "m_rating_streak": "Stop Flight Appraisal",
        "m_multi_ch_streak": "Wind Judge Tenure",
        "m_author_streak": "Insect Swarm Calendar",
        "m_perfect_week_manga": "Daily Flight Accord Accord",
        "m_diverse_streak": "Decade Fan Streak",

        // ── MANGA SCORING ──
        "m_critic": "Manga Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_harsh_critic": "Daily Wind Scale",
        "m_fair_judge": "Deep Mind Eye Eye",
        "m_generous_spirit": "Valley Elder Decree",
        "m_score_all": "Migration Times Reckoning",
        "m_wide_range": "Iron Will Ledger Ledger",
        "m_controversial": "Blue Clad Standard Standard",
        "m_consistent_scorer": "Stern Warrior Grade",
        "m_score_sniper": "Perfect Peace Reckoning",
        "m_evolving_taste": "Dawn Flight Trial Trial",
        "m_bell_curve": "Iron Will Accord",
        "m_picky_reader": "Decade Fan Ledger",
        "m_100_rated": "Iron Will Standard",
        "m_500_rated": "Unbroken Gale Aegis",
        "m_mediocre_majority": "Dawn Flight Canon",
        "m_rating_spree": "Ohm Territory Verdict",
        "m_score_variance": "Battle Rider Measure",
        "m_binge_rater": "Insect Swarm Passage",
        "m_reread_rerate": "Wind Signals Banner Banner",
        "m_masterpiece_hunter": "Blue Clad Banner",
        "m_contrarian": "Valley's Heart Aegis",
        "m_optimist": "Miyazaki Fan Accord Accord",
        "m_score_distributor": "Wind Judge Balance",
        "m_genre_critic": "Insect Swarm Critic",
        "m_mean_above_8": "Battle Rider Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Ohm Stampede Season",
        "m_valentines_read": "Stop Flight Observance",
        "m_pi_day": "Dawn Flight Testament Testament",
        "m_april_fools": "Perfect Peace Devotion",
        "m_international_manga_day": "Daily Wind Aegis",
        "m_free_comic_day": "Valley Elder Chronicle",
        "m_summer_solstice": "Peace Achieved Focus Focus",
        "m_tanabata": "Mehve Speed Tanabata",
        "m_friday_13th": "Hidden Valley Dominion Dominion",
        "m_halloween_read": "Endless Wind Halloween",
        "m_thanksgiving_binge": "Daily Flight Charge",
        "m_christmas_read": "God Warrior Pact",
        "m_new_years_eve": "Peace Achieved Pilgrimage",
        "m_birthday_read": "Valley Folk Focus",
        "m_holiday_marathon": "Wind Return Rally",
        "m_independence_day": "Valley's Heart Aegis Aegis",
        "m_culture_day": "Unbroken Gale Seal Seal",
        "m_spring_equinox": "Endless Wind Dominion",
        "m_earth_day": "Valley Folk Trial",
        "m_labor_day": "God Warrior Seal",
        "m_winter_solstice": "Classic Fan Focus Focus",
        "m_manga_birthday": "Mehve Speed Ritual",
        "m_every_holiday_reader": "Valley Revisit Watch",
        "m_consecutive_holidays": "Hidden Valley Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Toxic Filter Aegis",
        "m_fibonacci": "Wind Marathon Dominion",
        "m_palindrome_day": "Dawn Flight Relic",
        "m_binary_day": "Classic Fan Proof",
        "m_full_moon_read": "Non Stop Crown",
        "m_leap_year_read": "Decade Fan Practice",
        "m_triple_seven": "Deep Mind Trial Trial",
        "m_thousand_complete": "Deep Mind Ascension",
        "m_nice": "Ecological Art Seal Seal",
        "m_power_level_chapters": "Forest Registry Aegis",
        "m_answer_42": "Non Stop Trial",
        "m_square_number": "Toxic Jungle Standard",
        "m_prime_count": "Deep Mind Pinnacle",
        "m_matching_date": "Valley Revisit Mantle",
        "m_century_chapter": "Toxic Filter Decree",
        "m_pi_chapters": "Valley Folk Proof Proof",
        "m_synchronicity": "Stop Flight Emblem",
        "m_world_record": "Ancient Tomes Warrant",
        "m_genre_clash": "Night Rider Clash",
        "m_time_traveler": "Stern Warrior Decree",
        "m_double_digits": "War's Truth Dominion",
        "m_one_two_three": "Teto's Tricks Banner Banner",
        "m_lucky_seven": "Ohm Calm Record Record",
        "m_exact_hundred_ch": "Wind Marathon Legend",
        "m_year_match_count": "Jungle World Routine",
        "m_chapter_match_date": "Classic Fan Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "War's Truth Index",
        "m_manhwa_format": "Endless Wind Gallery",
        "m_manhua_format": "Peace Medals Storehouse",
        "m_ln_format": "Deep Mind Index",
        "m_oneshot_format": "Dawn Flight Index",
        "m_doujin_format": "Ohm Territory Cabinet",
        "m_novel_format": "Perfect Peace Reserve Reserve",
        "m_format_master_manga": "Ohm Territory Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Stern Warrior Link",
        "m_meta_collector": "Unbroken Gale Reliquary",
        "m_meta_category_starter": "All Night Standard",
        "m_meta_tier_climber": "Miyazaki Fan Token",
        "m_meta_tier_max": "Complete Journey",
        "m_meta_xp_earner": "War's Truth Anchor",
        "m_meta_difficulty_easy": "Deep Mind Panel",
        "m_meta_difficulty_hard": "Ohm Stampede Node",
        "m_meta_unlock_spree": "War's Truth Marker",
        "m_meta_completionist": "Full Library",
        "m_meta_diverse": "Dawn Flight Anchor",
        "m_meta_dominator": "Ecological Art Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#050604",
        primary: "#9b7816",
        secondary: "#64460e",
        accent: "#3a8060",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/nausicaa.jpg",
    particleColor: "#c4bc80",
    backgroundDim: 0.35,
    backgroundBlur: 20,
    particleTypes: {
        spores: { label: "Toxic Spores", maxCount: 25, defaultEnabled: true, defaultIntensity: 60 },
        wind_currents: { label: "Wind Currents", maxCount: 8, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
  1: "Threadbare Generic Rank Spark",
  8: "Generic's Tarnished Omen",
  14: "Fractured Generic Rank",
  21: "Generic Rank Path",
  28: "Lowborn Legacy Myth",
  35: "Generic Rank Pulse",
  41: "Generic's Legacy Crest",
  48: "Humble Generic Mark",
  55: "Ragged Generic Rank Vow",
  61: "Generic's Faint Echo",
  68: "Lesser Generic Rank",
  75: "Generic Rank Zenith",
  81: "Doubtful Legacy Bloom",
  88: "Generic Rank Sigil",
  95: "Generic's Legacy Flame",
  102: "Really Cool Generic Spark",
  108: "Awakened Generic Rank Omen",
  115: "Generic's Resolute Seal",
  122: "Rising Generic Rank",
  128: "Generic Rank Myth",
  135: "Dauntless Legacy Pulse",
  142: "Generic Rank Crest",
  149: "Generic's Legacy Mark",
  155: "Fresh Generic Vow",
  162: "Valiant Generic Rank Echo",
  169: "Generic's Prime Crown",
  175: "Polished Generic Rank",
  182: "Generic Rank Bloom",
  189: "Stormlit Legacy Sigil",
  195: "Generic Rank Flame",
  202: "Generic's Legacy Spark",
  209: "Tempered Generic Omen",
  216: "Trusted Generic Rank Seal",
  222: "Generic's Steadfast Path",
  229: "Ironclad Generic Rank",
  236: "Veteran Legacy Pulse",
  242: "Core Legacy Crest",
  249: "Generic Rank Mark",
  256: "Generic's Legacy Vow",
  262: "Formidable Generic Echo",
  269: "Lucid Generic Rank Crown",
  276: "Generic's Ranked Zenith",
  283: "Fabled Generic Rank",
  289: "Grand Legacy Sigil",
  296: "Seasoned Legacy Flame",
  303: "Generic Rank Spark",
  309: "Generic's Legacy Omen",
  316: "Valorous Generic Seal",
  323: "Stalwart Generic Rank Path",
  330: "Generic's Commanding Myth",
  336: "Refined Generic Rank",
  343: "Unbroken Legacy Crest",
  350: "Blazing Legacy Mark",
  356: "Generic Rank Vow",
  363: "Generic's Legacy Echo",
  370: "Peerless Generic Crown",
  376: "Ardent Generic Rank Zenith",
  383: "Generic's Focused Bloom",
  390: "Vigilant Generic Rank",
  397: "Dominant Legacy Flame",
  403: "Elite Legacy Spark",
  410: "Generic Rank Omen",
  417: "Generic's Legacy Seal",
  423: "Sovereign Generic Path",
  430: "Regal Generic Rank Myth",
  437: "Generic's Crowned Pulse",
  444: "Mythborn Generic Rank",
  450: "Limitless Legacy Mark",
  457: "Radiant Legacy Vow",
  464: "Generic Rank Echo",
  470: "Generic's Legacy Crown",
  477: "Climactic Generic Zenith",
  484: "Epic Generic Rank Bloom",
  490: "Generic's Unreal Sigil",
  497: "Peak Generic Rank",
  504: "Supreme Legacy Spark",
  511: "Exalted Legacy Omen",
  517: "Generic Rank Seal",
  524: "Generic's Legacy Path",
  531: "Celestial Generic Myth",
  537: "Phantom Generic Rank Pulse",
  544: "Generic's Crimson Crest",
  551: "Silver Generic Rank",
  557: "Golden Legacy Vow",
  564: "Feral Legacy Echo",
  571: "Generic Rank Crown",
  578: "Generic's Legacy Zenith",
  584: "Dread Generic Bloom",
  591: "Luminous Generic Rank Sigil",
  598: "Generic's Thunderous Flame",
  604: "Ultraviolet Generic Rank",
  611: "Unleashed Legacy Omen",
  618: "Secret Legacy Seal",
  625: "Final Generic Path",
  631: "Generic's Legacy Myth",
  638: "Worldclass Generic Pulse",
  645: "Lawless Generic Rank Crest",
  651: "Generic's Chosen Mark",
  658: "Fearless Generic Rank",
  665: "Overdrive Legacy Echo",
  671: "Cinematic Legacy Crown",
  678: "Impossible Generic Zenith",
  685: "Generic's Legacy Bloom",
  692: "Canonized Generic Sigil",
  698: "Ascendant Generic Rank Flame",
  705: "Generic's Transfigured Spark",
  712: "Immortal Generic Rank",
  718: "Eclipsed Legacy Seal",
  725: "Astral Legacy Path",
  732: "Sublime Generic Myth",
  739: "Generic's Legacy Pulse",
  745: "Prismatic Generic Crest",
  752: "Abyssal Generic Rank Mark",
  759: "Generic's Unbound Vow",
  765: "Eternal Generic Rank",
  772: "Cosmic Legacy Crown",
  779: "Transcendent Legacy Zenith",
  785: "Perfected Generic Bloom",
  792: "Generic's Legacy Sigil",
  799: "Ultimate Generic Flame",
  806: "Mythic Generic Rank Spark",
  812: "Generic's Godlike Omen",
  819: "Canonical Generic Rank",
  826: "Reality-Bent Legacy Path",
  832: "Heavenly Legacy Myth",
  839: "Absolute Generic Pulse",
  846: "Untouchable Generic Crest",
  852: "Timeless Generic Mark",
  859: "Empyrean Generic Rank Vow",
  866: "Generic's Primordial Echo",
  873: "Omniscient Generic Rank",
  879: "Unfathomed Legacy Zenith",
  886: "Apocalyptic Legacy Bloom",
  893: "Seraphic Generic Sigil",
  899: "Omega Generic Flame",
  906: "Final Generic Spark",
  913: "Crowned Generic Rank Omen",
  920: "Generic's Mythic Seal",
  926: "Absolute Generic Rank",
  933: "Eternal Legacy Myth",
  940: "Cosmic Legacy Pulse",
  946: "Transcendent Generic Crest",
  953: "Perfected Generic Mark",
  960: "Definitive Generic Vow",
  966: "Ultimate Generic Rank Echo",
  973: "Generic's Infinite Crown",
  980: "Sovereign Generic Rank",
  987: "Celestial Legacy Bloom",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate Generic Rank"
},
}
