import { AnimeThemeConfig } from "./types"
import { GiComputerFan, GiGamepad, GiDiamonds, GiHeartKey, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiCandyCanes } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const netJuuNoSusumeTheme: AnimeThemeConfig = {
    id: "net-juu-no-susume",
    displayName: "Recovery of an MMO Junkie",
    description: "Unemployed 30-year-old Moriko Morioka becomes a NEET and escapes into an online RPG, where her male avatar forms an unlikely bond with a guild member — unbeknownst to her, a surprising real-world connection lies beneath.",
    fontFamily: "'Nunito', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,400;0,700;1,400&display=swap",
    cssVars: {
        "--color-brand-200": "162 242 240",
        "--color-brand-300": "115 228 222",
        "--color-brand-400": "68 208 200",
        "--color-brand-500": "28 182 175",
        "--color-brand-600": "8 148 142",
        "--color-brand-700": "2 108 104",
        "--color-brand-800": "0 68 65",
        "--color-brand-900": "0 34 32",
        "--color-brand-950": "0 14 13",
        "--brand": "28 182 175",
        "--background": "#000606",
        "--paper": "#000f10",
        "--color-gray-950": "0 6 6",
        "--color-gray-900": "1 12 12",
        "--color-gray-800": "3 20 20",
        "--color-gray-700": "6 34 34",
        "--color-gray-600": "10 55 55",
        "--color-gray-500": "16 86 86",
        "--color-gray-400": "28 125 125",
        "--color-gray-300": "48 165 162",
        "--color-gray-200": "82 195 192",
        "--color-gray-100": "125 218 215",
        "--color-gray-50": "192 240 238",
    },
    sidebarOverrides: {
        "home": { icon: GiComputerFan, label: "MMO World" },
        "schedule": { icon: GiAlarmClock, label: "Login Schedule" },
        "manga": { icon: LuBookOpen, label: "Guild Notes" },
        "lists": { icon: GiGamepad, label: "Game List" },
        "discover": { icon: GiBullseye, label: "New Quests" },
        "torrent-list": { icon: GiDiamonds, label: "Item Cache" },
        "debrid": { icon: GiCandyCanes, label: "Game Store" },
        "unmatched": { icon: GiHeartKey, label: "Lost Logs" },
        "enmasse": { icon: GiResize, label: "Guild Events" },
        "scan-summaries": { icon: TbReportSearch, label: "Guild Reports" },
        "auto-downloader": { icon: LuRss, label: "Game Feed" },
        "community": { icon: GiComputerFan, label: "MMO Guild" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Login Alerts" },
        "achievements": { icon: GiTrophy, label: "Game Trophies" },
        "milestones": { icon: LuFlag, label: "Game Goals" },
        "theme-manager": { icon: GiPalette, label: "Neon Colors" },
        "extensions": { icon: BiExtension, label: "Game Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "MMO Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Morioka Settings" },
    },
    achievementNames: {
        "a_first_episode": "First Login",
        "a_first_complete": "Real Connection",
        "a_hundred_club": "Level 100",
        "a_time_lord": "MMO Veteran",
        "a_anime_collector": "Item Collection",
        "a_library_legend": "Game Archives",
        "a_binge_king": "Game Marathon",
        "a_no_sleep": "All-Night Gaming",
        "a_marathon_runner": "Long Session",
        "a_speed_run": "Speed Gamer",
        "a_completionist": "All Episodes",
        "a_mega_completionist": "Nanako Master",
        "a_loyal_fan": "Lily's Friend",
        "a_rewatcher": "MMO Return",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Guild Battle",
        "a_genre_adventure": "Game World",
        "a_genre_comedy": "NEET Humor",
        "a_genre_drama": "Real World Reveal",
        "a_genre_fantasy": "MMO Fantasy",
        "a_genre_horror": "Social Anxiety",
        "a_genre_romance": "Morioka Sakurai",
        "a_genre_scifi": "Online World",
        "a_genre_supernatural": "None Here",
        "a_genre_psychological": "NEET Recovery",
        "a_genre_mecha": "None Here",
        "a_critic": "Game Critic",
        "a_perfect_ten": "Perfect Session",
        "a_harsh_critic": "Gamer Standard",
        "a_daily_streak": "Daily Login",
        "a_mega_streak": "Endless Grinding",
        "a_year_long": "Year in MMO",
        "a_iron_will": "Morioka's Return",
        "a_hidden_gem": "Hidden Quest",
        "a_cult_classic": "Cozy Classic",
        "a_classic_connoisseur": "2012 Fan",
        "a_new_years_resolution": "New Year Login",
        "a_christmas_special": "Holiday Event",
        "a_meta_tier_max": "MMO Legend",
        "a_meta_completionist": "All Arcs",
        "a_sequel_chain": "Manga Continues",
        "a_zero_to_hero": "NEET to Partner",
        "a_night_owl": "Night Gaming",
        "a_early_bird": "Morning Login",
        "m_first_chapter": "First Quest",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Game Marathon",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "MMO Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "MMO Return",
        "m_genre_action": "Battle Chapter",
        "m_genre_adventure": "World Chapter",
        "m_genre_romance": "Heart Chapter",
        "m_genre_fantasy": "Game Chapter",
        "m_genre_horror": "Anxiety Chapter",
        "m_genre_drama": "Real Chapter",
        "m_genre_scifi": "Online Chapter",
        "m_genre_supernatural": "None Here",
        "m_genre_psychological": "Recovery Depth",
        "m_critic": "Game Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Game Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "NEET Resolve",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Nanako Classic",
        "m_mangaka_lover": "Nanako Fan",
        "m_source_material_fan": "Novel First",
        "m_meta_tier_max": "MMO Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Nanako Art",
        "m_manga_to_anime": "Novel Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#000606",
        primary: "#1cb6af",
        secondary: "#08948e",
        accent: "#f080c0",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/net-juu-no-susume.jpg",
    particleColor: "#40d8d0",
    backgroundDim: 0.32,
    backgroundBlur: 16,
    particleTypes: {
        pixel_sparkles: { label: "Pixel Sparkles", maxCount: 18, defaultEnabled: true, defaultIntensity: 58 },
        heart_bits: { label: "Heart Bits", maxCount: 12, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
        1: "New Account",
        5: "Moriko Morioka",
        15: "Guild Member",
        30: "Online Duo",
        50: "Real World Bridge",
        75: "Recovery Path",
        100: "MMO Legend",
    },
}
