import { AnimeThemeConfig } from "./types"
import { GiRobotGolem, GiCat, GiDeer, GiMilkCarton, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiPencilBrush } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const nichijouTheme: AnimeThemeConfig = {
    id: "nichijou",
    displayName: "Nichijou",
    description: "Three high school girls live hilariously mundane lives alongside Nano, a robot who goes to their school, the young Professor who built her, and Sakamoto — a cat who can talk. Daily life has never been so dramatic or absurd.",
    fontFamily: "'Quicksand', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Quicksand:wght@400;600;700&display=swap",
    cssVars: {
        "--color-brand-200": "218 185 240",
        "--color-brand-300": "195 148 232",
        "--color-brand-400": "170 108 218",
        "--color-brand-500": "145 68 200",
        "--color-brand-600": "115 42 170",
        "--color-brand-700": "85 22 135",
        "--color-brand-800": "56 8 100",
        "--color-brand-900": "28 2 60",
        "--color-brand-950": "12 0 28",
        "--brand": "145 68 200",
        "--background": "#040206",
        "--paper": "#0a050e",
        "--color-gray-950": "4 2 6",
        "--color-gray-900": "10 5 14",
        "--color-gray-800": "18 10 24",
        "--color-gray-700": "30 18 40",
        "--color-gray-600": "50 30 65",
        "--color-gray-500": "80 52 100",
        "--color-gray-400": "120 85 148",
        "--color-gray-300": "162 128 192",
        "--color-gray-200": "198 170 225",
        "--color-gray-100": "222 205 240",
        "--color-gray-50": "240 230 250",
    },
    sidebarOverrides: {
        "home": { icon: GiRobotGolem, label: "Nano's World" },
        "schedule": { icon: GiAlarmClock, label: "Class Schedule" },
        "manga": { icon: LuBookOpen, label: "Arawi's Manga" },
        "lists": { icon: GiPencilBrush, label: "Daily Events" },
        "discover": { icon: GiBullseye, label: "New Moments" },
        "torrent-list": { icon: GiCat, label: "Sakamoto's Picks" },
        "debrid": { icon: GiDeer, label: "Nano's Store" },
        "unmatched": { icon: GiMilkCarton, label: "Lost Episodes" },
        "enmasse": { icon: GiResize, label: "School Events" },
        "scan-summaries": { icon: TbReportSearch, label: "Daily Reports" },
        "auto-downloader": { icon: LuRss, label: "Life Feed" },
        "community": { icon: GiRobotGolem, label: "Hakase's Lab" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Daily Alerts" },
        "achievements": { icon: GiTrophy, label: "Daily Trophies" },
        "milestones": { icon: LuFlag, label: "Daily Goals" },
        "theme-manager": { icon: GiPalette, label: "Pastel Colors" },
        "extensions": { icon: BiExtension, label: "Robot Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Daily Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Nano's Settings" },
    },
    achievementNames: {
        "a_first_episode": "First Day",
        "a_first_complete": "Graduation",
        "a_hundred_club": "Hundred Episodes",
        "a_time_lord": "Daily Life Veteran",
        "a_anime_collector": "Episode Collection",
        "a_library_legend": "Nichijou Archives",
        "a_binge_king": "Daily Marathon",
        "a_no_sleep": "All-Night Laughs",
        "a_marathon_runner": "Long School Day",
        "a_speed_run": "Yuuko's Speed",
        "a_completionist": "All Episodes",
        "a_mega_completionist": "Arawi Master",
        "a_loyal_fan": "Nano's Friend",
        "a_rewatcher": "Daily Return",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Over-Dramatic Action",
        "a_genre_adventure": "Town Exploration",
        "a_genre_comedy": "Absurd Humor",
        "a_genre_drama": "Daily Drama",
        "a_genre_fantasy": "Deer Fantasy",
        "a_genre_horror": "Daiku-Sensei Horror",
        "a_genre_romance": "Mio Likes Somebody",
        "a_genre_scifi": "Nano's Science",
        "a_genre_supernatural": "Talking Cat",
        "a_genre_psychological": "Deep Thoughts",
        "a_genre_mecha": "Nano Robot",
        "a_critic": "Absurdist Critic",
        "a_perfect_ten": "Perfect Daily Life",
        "a_harsh_critic": "Yukko's Standard",
        "a_daily_streak": "Truly Daily",
        "a_mega_streak": "Endless Days",
        "a_year_long": "Year of Dailies",
        "a_iron_will": "Nano's Determination",
        "a_hidden_gem": "Hidden Sketch",
        "a_cult_classic": "KyoAni Classic",
        "a_classic_connoisseur": "2011 Fan",
        "a_new_years_resolution": "New Year Sketch",
        "a_christmas_special": "Winter Daily",
        "a_meta_tier_max": "Nichijou Legend",
        "a_meta_completionist": "All Sketches",
        "a_sequel_chain": "Manga Continues",
        "a_zero_to_hero": "Ordinary to Extraordinary",
        "a_night_owl": "Night Daily",
        "a_early_bird": "Morning Class",
        "m_first_chapter": "First Sketch",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Daily Marathon",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Nichijou Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Daily Return",
        "m_genre_action": "Dramatic Sketch",
        "m_genre_adventure": "Town Sketch",
        "m_genre_romance": "Mio's Chapter",
        "m_genre_fantasy": "Robot Chapter",
        "m_genre_horror": "Shark Chapter",
        "m_genre_drama": "Mai's Chapter",
        "m_genre_scifi": "Nano's Chapter",
        "m_genre_supernatural": "Sakamoto's Chapter",
        "m_genre_psychological": "Deep Daily",
        "m_critic": "Sketch Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Daily Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Nano Resolve",
        "m_hidden_gem": "Hidden Chapter",
        "m_cult_classic": "KyoAni Classic",
        "m_mangaka_lover": "Arawi Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Nichijou Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Arawi's Art",
        "m_manga_to_anime": "Manga Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#040206",
        primary: "#9144c8",
        secondary: "#732aaa",
        accent: "#f0a020",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/nichijou.jpg",
    particleColor: "#c080e0",
    backgroundDim: 0.28,
    backgroundBlur: 14,
    particleTypes: {
        kawaii_sparkles: { label: "Kawaii Sparkles", maxCount: 20, defaultEnabled: true, defaultIntensity: 60 },
        screw_bolts: { label: "Nano's Screws", maxCount: 8, defaultEnabled: true, defaultIntensity: 35 },
    },
    milestoneNames: {
    1: "Generic Rank",
    7: "Generic Rank",
    14: "Generic Rank",
    21: "Generic Rank",
    27: "Generic Rank",
    34: "Generic Rank",
    41: "Generic Rank",
    47: "Generic Rank",
    54: "Generic Rank",
    61: "Generic Rank",
    68: "Generic Rank",
    74: "Generic Rank",
    81: "Generic Rank",
    88: "Generic Rank",
    94: "Generic Rank",
    101: "Generic Rank",
    108: "Generic Rank",
    114: "Generic Rank",
    121: "Generic Rank",
    128: "Generic Rank",
    135: "Generic Rank",
    141: "Generic Rank",
    148: "Generic Rank",
    155: "Generic Rank",
    161: "Generic Rank",
    168: "Generic Rank",
    175: "Generic Rank",
    182: "Generic Rank",
    188: "Generic Rank",
    195: "Generic Rank",
    202: "Generic Rank",
    208: "Generic Rank",
    215: "Generic Rank",
    222: "Generic Rank",
    228: "Generic Rank",
    235: "Generic Rank",
    242: "Generic Rank",
    249: "Generic Rank",
    255: "Generic Rank",
    262: "Generic Rank",
    269: "Generic Rank",
    275: "Generic Rank",
    282: "Generic Rank",
    289: "Generic Rank",
    296: "Generic Rank",
    302: "Generic Rank",
    309: "Generic Rank",
    316: "Generic Rank",
    322: "Generic Rank",
    329: "Generic Rank",
    336: "Generic Rank",
    342: "Generic Rank",
    349: "Generic Rank",
    356: "Generic Rank",
    363: "Generic Rank",
    369: "Generic Rank",
    376: "Generic Rank",
    383: "Generic Rank",
    389: "Generic Rank",
    396: "Generic Rank",
    403: "Generic Rank",
    409: "Generic Rank",
    416: "Generic Rank",
    423: "Generic Rank",
    430: "Generic Rank",
    436: "Generic Rank",
    443: "Generic Rank",
    450: "Generic Rank",
    456: "Generic Rank",
    463: "Generic Rank",
    470: "Generic Rank",
    477: "Generic Rank",
    483: "Generic Rank",
    490: "Generic Rank",
    497: "Generic Rank",
    503: "Generic Rank",
    510: "Generic Rank",
    517: "Generic Rank",
    523: "Generic Rank",
    530: "Generic Rank",
    537: "Generic Rank",
    544: "Generic Rank",
    550: "Generic Rank",
    557: "Generic Rank",
    564: "Generic Rank",
    570: "Generic Rank",
    577: "Generic Rank",
    584: "Generic Rank",
    591: "Generic Rank",
    597: "Generic Rank",
    604: "Generic Rank",
    611: "Generic Rank",
    617: "Generic Rank",
    624: "Generic Rank",
    631: "Generic Rank",
    637: "Generic Rank",
    644: "Generic Rank",
    651: "Generic Rank",
    658: "Generic Rank",
    664: "Generic Rank",
    671: "Generic Rank",
    678: "Generic Rank",
    684: "Generic Rank",
    691: "Generic Rank",
    698: "Generic Rank",
    704: "Generic Rank",
    711: "Generic Rank",
    718: "Generic Rank",
    725: "Generic Rank",
    731: "Generic Rank",
    738: "Generic Rank",
    745: "Generic Rank",
    751: "Generic Rank",
    758: "Generic Rank",
    765: "Generic Rank",
    772: "Generic Rank",
    778: "Generic Rank",
    785: "Generic Rank",
    792: "Generic Rank",
    798: "Generic Rank",
    805: "Generic Rank",
    812: "Generic Rank",
    818: "Generic Rank",
    825: "Generic Rank",
    832: "Generic Rank",
    839: "Generic Rank",
    845: "Generic Rank",
    852: "Generic Rank",
    859: "Generic Rank",
    865: "Generic Rank",
    872: "Generic Rank",
    879: "Generic Rank",
    886: "Generic Rank",
    892: "Generic Rank",
    899: "Generic Rank",
    906: "Generic Rank",
    912: "Generic Rank",
    919: "Generic Rank",
    926: "Generic Rank",
    932: "Generic Rank",
    939: "Generic Rank",
    946: "Generic Rank",
    953: "Generic Rank",
    959: "Generic Rank",
    966: "Generic Rank",
    973: "Generic Rank",
    979: "Generic Rank",
    986: "Generic Rank",
    993: "Generic Rank",
    1000: "Generic Rank",
  },
}
