import { AnimeThemeConfig } from "./types"
import { GiGhost, GiShuriken, GiMoonBats, GiBroadsword, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiSpiralShell } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const noragamiTheme: AnimeThemeConfig = {
    id: "noragami",
    displayName: "Noragami",
    description: "Yato is a minor deity with no shrine who dreams of fame and worshippers, working odd jobs for five-yen coins alongside his human Regalia Yukine and school girl Hiyori, who can slip between the human and spirit realms.",
    fontFamily: "'Sawarabi Mincho', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Sawarabi+Mincho&display=swap",
    cssVars: {
        "--color-brand-200": "172 210 248",
        "--color-brand-300": "128 178 240",
        "--color-brand-400": "82 142 225",
        "--color-brand-500": "42 108 205",
        "--color-brand-600": "18 76 168",
        "--color-brand-700": "5 50 128",
        "--color-brand-800": "1 28 82",
        "--color-brand-900": "0 12 44",
        "--color-brand-950": "0 4 20",
        "--brand": "42 108 205",
        "--background": "#000208",
        "--paper": "#03060e",
        "--color-gray-950": "0 2 8",
        "--color-gray-900": "3 6 14",
        "--color-gray-800": "6 12 22",
        "--color-gray-700": "12 20 36",
        "--color-gray-600": "20 34 58",
        "--color-gray-500": "32 55 88",
        "--color-gray-400": "56 88 128",
        "--color-gray-300": "92 130 170",
        "--color-gray-200": "135 172 205",
        "--color-gray-100": "175 205 228",
        "--color-gray-50": "215 232 245",
    },
    sidebarOverrides: {
        "home": { icon: GiGhost, label: "Far Shore" },
        "schedule": { icon: GiAlarmClock, label: "Divine Schedule" },
        "manga": { icon: LuBookOpen, label: "Divine Records" },
        "lists": { icon: GiSpiralShell, label: "Regalia Registry" },
        "discover": { icon: GiBullseye, label: "New Requests" },
        "torrent-list": { icon: GiShuriken, label: "Spirit Cache" },
        "debrid": { icon: GiMoonBats, label: "Divine Store" },
        "unmatched": { icon: GiBroadsword, label: "Lost Spirits" },
        "enmasse": { icon: GiResize, label: "Divine Battles" },
        "scan-summaries": { icon: TbReportSearch, label: "Shrine Reports" },
        "auto-downloader": { icon: LuRss, label: "Divine Feed" },
        "community": { icon: GiGhost, label: "Yato's Shrine" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Divine Alerts" },
        "achievements": { icon: GiTrophy, label: "God Trophies" },
        "milestones": { icon: LuFlag, label: "Stray Goals" },
        "theme-manager": { icon: GiPalette, label: "Sky Colors" },
        "extensions": { icon: BiExtension, label: "Spirit Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Shore Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Yato's Settings" },
    },
    achievementNames: {
        "a_first_episode": "Five Yen Found",
        "a_first_complete": "True Regalia",
        "a_hundred_club": "Hundred Prayers",
        "a_time_lord": "Divine Veteran",
        "a_anime_collector": "Regalia Collection",
        "a_library_legend": "Noragami Archives",
        "a_binge_king": "Prayer Marathon",
        "a_no_sleep": "Night Patrol",
        "a_marathon_runner": "Hiyori's Run",
        "a_speed_run": "Yato's Dash",
        "a_completionist": "All Episodes",
        "a_mega_completionist": "Adachitoka Master",
        "a_loyal_fan": "Yato's Follower",
        "a_rewatcher": "Far Shore Return",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "God Battle",
        "a_genre_adventure": "Far Shore Journey",
        "a_genre_comedy": "Yato's Dream",
        "a_genre_drama": "Yukine's Blight",
        "a_genre_fantasy": "Divine World",
        "a_genre_horror": "Phantoms",
        "a_genre_romance": "Yato Hiyori",
        "a_genre_scifi": "None Here",
        "a_genre_supernatural": "Spirit Realm",
        "a_genre_psychological": "Regalia's Pain",
        "a_genre_mecha": "None Here",
        "a_critic": "Shrine Critic",
        "a_perfect_ten": "Perfect Prayer",
        "a_harsh_critic": "Bishamon Standard",
        "a_daily_streak": "Daily Prayer",
        "a_mega_streak": "Endless Prayers",
        "a_year_long": "Year of Prayers",
        "a_iron_will": "Yato's Determination",
        "a_hidden_gem": "Hidden Shrine",
        "a_cult_classic": "Adachitoka Classic",
        "a_classic_connoisseur": "2010 Fan",
        "a_new_years_resolution": "New Year Shrine",
        "a_christmas_special": "Winter Prayer",
        "a_meta_tier_max": "True God",
        "a_meta_completionist": "All Arcs",
        "a_sequel_chain": "Noragami Aragoto",
        "a_zero_to_hero": "No Shrine to God",
        "a_night_owl": "Night Spirit",
        "a_early_bird": "Dawn Shrine",
        "m_first_chapter": "First Prayer",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Prayer Marathon",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Noragami Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Far Shore Return",
        "m_genre_action": "God Battle Chapter",
        "m_genre_adventure": "Shore Chapter",
        "m_genre_romance": "Heart Chapter",
        "m_genre_fantasy": "Divine Chapter",
        "m_genre_horror": "Phantom Chapter",
        "m_genre_drama": "Regalia Chapter",
        "m_genre_scifi": "Unusual Chapter",
        "m_genre_supernatural": "Spirit Chapter",
        "m_genre_psychological": "God's Truth",
        "m_critic": "Shrine Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Divine Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "God's Resolve",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Adachitoka Classic",
        "m_mangaka_lover": "Adachitoka Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Noragami Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Adachitoka Art",
        "m_manga_to_anime": "Manga Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#000208",
        primary: "#2a6ccd",
        secondary: "#124ca8",
        accent: "#f0c030",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/noragami.jpg",
    particleColor: "#5090e0",
    backgroundDim: 0.38,
    backgroundBlur: 18,
    particleTypes: {
        spirit_wisps: { label: "Spirit Wisps", maxCount: 18, defaultEnabled: true, defaultIntensity: 60 },
        divine_sparks: { label: "Divine Sparks", maxCount: 12, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
    "7": "Novice Rank 1",
    "13": "Novice Level 2",
    "20": "Novice Tier 3",
    "27": "Novice Class 4",
    "33": "Novice Grade 5",
    "40": "Novice Position 6",
    "47": "Novice Status 7",
    "53": "Novice Role 8",
    "60": "Novice Title 9",
    "67": "Novice Authority 10",
    "73": "Beginner Rank 11",
    "80": "Beginner Level 12",
    "87": "Beginner Tier 13",
    "93": "Beginner Class 14",
    "100": "Beginner Grade 15",
    "107": "Beginner Position 16",
    "113": "Beginner Status 17",
    "120": "Beginner Role 18",
    "127": "Beginner Title 19",
    "133": "Student Authority 20",
    "140": "Student Rank 21",
    "147": "Student Level 22",
    "153": "Student Tier 23",
    "160": "Student Class 24",
    "167": "Student Grade 25",
    "173": "Student Position 26",
    "180": "Student Status 27",
    "187": "Student Role 28",
    "193": "Student Title 29",
    "200": "Learner Authority 30",
    "207": "Learner Rank 31",
    "213": "Learner Level 32",
    "220": "Learner Tier 33",
    "227": "Learner Class 34",
    "233": "Learner Grade 35",
    "240": "Learner Position 36",
    "247": "Learner Status 37",
    "253": "Learner Role 38",
    "260": "Adept Title 39",
    "267": "Adept Authority 40",
    "273": "Adept Rank 41",
    "280": "Adept Level 42",
    "287": "Adept Tier 43",
    "293": "Adept Class 44",
    "300": "Adept Grade 45",
    "307": "Adept Position 46",
    "313": "Adept Status 47",
    "320": "Expert Role 48",
    "327": "Expert Title 49",
    "333": "Expert Authority 50",
    "340": "Expert Rank 51",
    "347": "Expert Level 52",
    "353": "Expert Tier 53",
    "360": "Expert Class 54",
    "367": "Expert Grade 55",
    "373": "Expert Position 56",
    "380": "Expert Status 57",
    "387": "Master Role 58",
    "393": "Master Title 59",
    "400": "Master Authority 60",
    "407": "Master Rank 61",
    "413": "Master Level 62",
    "420": "Master Tier 63",
    "427": "Master Class 64",
    "433": "Master Grade 65",
    "440": "Master Position 66",
    "447": "Grandmaster Status 67",
    "453": "Grandmaster Role 68",
    "460": "Grandmaster Title 69",
    "467": "Grandmaster Authority 70",
    "473": "Grandmaster Rank 71",
    "480": "Grandmaster Level 72",
    "487": "Grandmaster Tier 73",
    "493": "Grandmaster Class 74",
    "500": "Grandmaster Grade 75",
    "507": "Sage Position 76",
    "513": "Sage Status 77",
    "520": "Sage Role 78",
    "527": "Sage Title 79",
    "533": "Sage Authority 80",
    "540": "Sage Rank 81",
    "547": "Sage Level 82",
    "553": "Sage Tier 83",
    "560": "Sage Class 84",
    "567": "Sage Grade 85",
    "573": "Legend Position 86",
    "580": "Legend Status 87",
    "587": "Legend Role 88",
    "593": "Legend Title 89",
    "600": "Legend Authority 90",
    "607": "Legend Rank 91",
    "613": "Legend Level 92",
    "620": "Legend Tier 93",
    "627": "Legend Class 94",
    "633": "Mythical Grade 95",
    "640": "Mythical Position 96",
    "647": "Mythical Status 97",
    "653": "Mythical Role 98",
    "660": "Mythical Title 99",
    "667": "Mythical Authority 100",
    "673": "Mythical Rank 101",
    "680": "Mythical Level 102",
    "687": "Mythical Tier 103",
    "693": "Mythical Class 104",
    "700": "Godly Grade 105",
    "707": "Godly Position 106",
    "713": "Godly Status 107",
    "720": "Godly Role 108",
    "727": "Godly Title 109",
    "733": "Godly Authority 110",
    "740": "Godly Rank 111",
    "747": "Godly Level 112",
    "753": "Godly Tier 113",
    "760": "Supreme Class 114",
    "767": "Supreme Grade 115",
    "773": "Supreme Position 116",
    "780": "Supreme Status 117",
    "787": "Supreme Role 118",
    "793": "Supreme Title 119",
    "800": "Supreme Authority 120",
    "807": "Supreme Rank 121",
    "813": "Supreme Level 122",
    "820": "Infinite Tier 123",
    "827": "Infinite Class 124",
    "833": "Infinite Grade 125",
    "840": "Infinite Position 126",
    "847": "Infinite Status 127",
    "853": "Infinite Role 128",
    "860": "Infinite Title 129",
    "867": "Infinite Authority 130",
    "873": "Infinite Rank 131",
    "880": "Infinite Level 132",
    "887": "Eternal Tier 133",
    "893": "Eternal Class 134",
    "900": "Eternal Grade 135",
    "907": "Eternal Position 136",
    "913": "Eternal Status 137",
    "920": "Eternal Role 138",
    "927": "Eternal Title 139",
    "933": "Eternal Authority 140",
    "940": "Eternal Rank 141",
    "947": "Transcendent Level 142",
    "953": "Transcendent Tier 143",
    "960": "Transcendent Class 144",
    "967": "Transcendent Grade 145",
    "973": "Transcendent Position 146",
    "980": "Transcendent Status 147",
    "987": "Transcendent Role 148",
    "993": "Transcendent Title 149",
    "1000": "Transcendent Authority 150"
},
}
