import { AnimeThemeConfig } from "./types"
import { GiDesert, GiSun, GiBroadsword, GiFlame, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiDustCloud, GiRun, GiSandstorm } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const nowAndThenHereAndThereTheme: AnimeThemeConfig = {
    id: "now-and-then-here-and-there",
    displayName: "Now and Then, Here and There",
    description: "A cheerful boy is swept into a post-apocalyptic hellscape of sand and war, where children are conscripted as soldiers. One of anime's most unrelenting depictions of human cruelty and the unyielding hope that endures through it.",
    fontFamily: "'Lora', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Lora:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "220 196 148",
        "--color-brand-300": "195 164 106",
        "--color-brand-400": "168 130 68",
        "--color-brand-500": "138 98 38",
        "--color-brand-600": "104 70 18",
        "--color-brand-700": "72 46 6",
        "--color-brand-800": "44 26 2",
        "--color-brand-900": "22 12 0",
        "--color-brand-950": "8 4 0",
        "--brand": "138 98 38",
        "--background": "#060400",
        "--paper": "#100800",
        "--color-gray-950": "6 4 0",
        "--color-gray-900": "12 8 2",
        "--color-gray-800": "24 16 4",
        "--color-gray-700": "42 30 8",
        "--color-gray-600": "68 50 16",
        "--color-gray-500": "106 82 34",
        "--color-gray-400": "148 118 68",
        "--color-gray-300": "188 158 108",
        "--color-gray-200": "220 196 152",
        "--color-gray-100": "242 226 192",
        "--color-gray-50": "254 248 235",
    },
    sidebarOverrides: {
        "home": { icon: GiDesert, label: "Sand World" },
        "schedule": { icon: GiAlarmClock, label: "War Schedule" },
        "manga": { icon: LuBookOpen, label: "Sand Records" },
        "lists": { icon: GiFlowerEmblem, label: "Survivor Registry" },
        "discover": { icon: GiBullseye, label: "New Worlds" },
        "torrent-list": { icon: GiBroadsword, label: "War Cache" },
        "debrid": { icon: GiSandstorm, label: "Sand Vault" },
        "unmatched": { icon: GiRun, label: "Lost Children" },
        "enmasse": { icon: GiResize, label: "Desert Ops" },
        "scan-summaries": { icon: TbReportSearch, label: "War Reports" },
        "auto-downloader": { icon: LuRss, label: "Desert Intel" },
        "community": { icon: GiSun, label: "Survivor Circle" },
        "achievements": { icon: GiTrophy, label: "Sand Trophies" },
        "milestones": { icon: LuFlag, label: "Desert Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Sand Alerts" },
        "theme-manager": { icon: GiPalette, label: "Desert Palette" },
        "extensions": { icon: BiExtension, label: "Desert Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Desert Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Shu's Config" },
    },
    achievementNames: {
        "a_first_episode": "Transported",
        "a_first_complete": "Survived",
        "a_hundred_club": "Hundred Wars",
        "a_time_lord": "Desert Elder",
        "a_anime_collector": "Desert Archive",
        "a_library_legend": "Sand Library",
        "a_binge_king": "Despair Marathon",
        "a_no_sleep": "All-Night Despair",
        "a_marathon_runner": "Shu's Run",
        "a_speed_run": "Desert Speed",
        "a_completionist": "Full Desert",
        "a_mega_completionist": "Desert Expert",
        "a_loyal_fan": "Loyal Survivor",
        "a_rewatcher": "Revisit Desert",
        "a_decade_watcher": "Decade War",
        "a_genre_action": "Sand Battle",
        "a_genre_adventure": "Desert Journey",
        "a_genre_comedy": "None Here",
        "a_genre_drama": "War Drama",
        "a_genre_fantasy": "None Here",
        "a_genre_horror": "War Horror",
        "a_genre_romance": "None Here",
        "a_genre_scifi": "Desert Future",
        "a_genre_supernatural": "None Here",
        "a_genre_psychological": "Shu's Mind",
        "a_genre_mecha": "Desert Machine",
        "a_critic": "Desert Critic",
        "a_perfect_ten": "Perfect Despair",
        "a_harsh_critic": "Sand Standard",
        "a_daily_streak": "Daily Survival",
        "a_mega_streak": "Endless War",
        "a_year_long": "Year of War",
        "a_iron_will": "Shu's Will",
        "a_hidden_gem": "Hidden Memory",
        "a_cult_classic": "Desert Classic",
        "a_classic_connoisseur": "1999 Fan",
        "a_new_years_resolution": "New Year Hope",
        "a_christmas_special": "Winter Desert",
        "a_meta_tier_max": "True Survivor",
        "a_meta_completionist": "All Deserts",
        "a_sequel_chain": "Desert Chain",
        "a_zero_to_hero": "Lost to Legend",
        "a_night_owl": "Night Watch",
        "a_early_bird": "Dawn Survivor",
        "m_first_chapter": "First Day",
        "m_first_complete": "Desert Arc",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "War Binge",
        "m_completionist": "Full Series",
        "m_mega_completionist": "Desert Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Second Desert",
        "m_genre_action": "War Chapter",
        "m_genre_adventure": "Journey Chapter",
        "m_genre_romance": "None Here",
        "m_genre_fantasy": "None Here",
        "m_genre_horror": "Horror Chapter",
        "m_genre_drama": "Despair Chapter",
        "m_genre_scifi": "Future Chapter",
        "m_genre_supernatural": "None Here",
        "m_genre_psychological": "Mind Chapter",
        "m_critic": "Desert Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Desert Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Iron Survival",
        "m_hidden_gem": "Hidden War",
        "m_cult_classic": "Classic Desert",
        "m_mangaka_lover": "Abe Fan",
        "m_source_material_fan": "Anime First",
        "m_meta_tier_max": "Desert Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Desert Art",
        "m_manga_to_anime": "None Here",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060400",
        primary: "#8a6226",
        secondary: "#684612",
        accent: "#4060a0",
    },
    particleColor: "#c0a060",
    backgroundDim: 0.38,
    backgroundBlur: 14,
    particleTypes: {
        dust_wisps: { label: "Sand Dust", maxCount: 16, defaultEnabled: true, defaultIntensity: 55 },
        ember_wisps: { label: "Ember Wisps", maxCount: 10, defaultEnabled: true, defaultIntensity: 36 },
    },
    milestoneNames: {
    "7": "Novice Rank 1",
    "13": "Novice Level 2",
    "20": "Novice Tier 3",
    "27": "Novice Class 4",
    "33": "Novice Grade 5",
    "40": "Novice Position 6",
    "47": "Novice Status 7",
    "53": "Novice Role 8",
    "60": "Novice Title 9",
    "67": "Novice Authority 10",
    "73": "Beginner Rank 11",
    "80": "Beginner Level 12",
    "87": "Beginner Tier 13",
    "93": "Beginner Class 14",
    "100": "Beginner Grade 15",
    "107": "Beginner Position 16",
    "113": "Beginner Status 17",
    "120": "Beginner Role 18",
    "127": "Beginner Title 19",
    "133": "Student Authority 20",
    "140": "Student Rank 21",
    "147": "Student Level 22",
    "153": "Student Tier 23",
    "160": "Student Class 24",
    "167": "Student Grade 25",
    "173": "Student Position 26",
    "180": "Student Status 27",
    "187": "Student Role 28",
    "193": "Student Title 29",
    "200": "Learner Authority 30",
    "207": "Learner Rank 31",
    "213": "Learner Level 32",
    "220": "Learner Tier 33",
    "227": "Learner Class 34",
    "233": "Learner Grade 35",
    "240": "Learner Position 36",
    "247": "Learner Status 37",
    "253": "Learner Role 38",
    "260": "Adept Title 39",
    "267": "Adept Authority 40",
    "273": "Adept Rank 41",
    "280": "Adept Level 42",
    "287": "Adept Tier 43",
    "293": "Adept Class 44",
    "300": "Adept Grade 45",
    "307": "Adept Position 46",
    "313": "Adept Status 47",
    "320": "Expert Role 48",
    "327": "Expert Title 49",
    "333": "Expert Authority 50",
    "340": "Expert Rank 51",
    "347": "Expert Level 52",
    "353": "Expert Tier 53",
    "360": "Expert Class 54",
    "367": "Expert Grade 55",
    "373": "Expert Position 56",
    "380": "Expert Status 57",
    "387": "Master Role 58",
    "393": "Master Title 59",
    "400": "Master Authority 60",
    "407": "Master Rank 61",
    "413": "Master Level 62",
    "420": "Master Tier 63",
    "427": "Master Class 64",
    "433": "Master Grade 65",
    "440": "Master Position 66",
    "447": "Grandmaster Status 67",
    "453": "Grandmaster Role 68",
    "460": "Grandmaster Title 69",
    "467": "Grandmaster Authority 70",
    "473": "Grandmaster Rank 71",
    "480": "Grandmaster Level 72",
    "487": "Grandmaster Tier 73",
    "493": "Grandmaster Class 74",
    "500": "Grandmaster Grade 75",
    "507": "Sage Position 76",
    "513": "Sage Status 77",
    "520": "Sage Role 78",
    "527": "Sage Title 79",
    "533": "Sage Authority 80",
    "540": "Sage Rank 81",
    "547": "Sage Level 82",
    "553": "Sage Tier 83",
    "560": "Sage Class 84",
    "567": "Sage Grade 85",
    "573": "Legend Position 86",
    "580": "Legend Status 87",
    "587": "Legend Role 88",
    "593": "Legend Title 89",
    "600": "Legend Authority 90",
    "607": "Legend Rank 91",
    "613": "Legend Level 92",
    "620": "Legend Tier 93",
    "627": "Legend Class 94",
    "633": "Mythical Grade 95",
    "640": "Mythical Position 96",
    "647": "Mythical Status 97",
    "653": "Mythical Role 98",
    "660": "Mythical Title 99",
    "667": "Mythical Authority 100",
    "673": "Mythical Rank 101",
    "680": "Mythical Level 102",
    "687": "Mythical Tier 103",
    "693": "Mythical Class 104",
    "700": "Godly Grade 105",
    "707": "Godly Position 106",
    "713": "Godly Status 107",
    "720": "Godly Role 108",
    "727": "Godly Title 109",
    "733": "Godly Authority 110",
    "740": "Godly Rank 111",
    "747": "Godly Level 112",
    "753": "Godly Tier 113",
    "760": "Supreme Class 114",
    "767": "Supreme Grade 115",
    "773": "Supreme Position 116",
    "780": "Supreme Status 117",
    "787": "Supreme Role 118",
    "793": "Supreme Title 119",
    "800": "Supreme Authority 120",
    "807": "Supreme Rank 121",
    "813": "Supreme Level 122",
    "820": "Infinite Tier 123",
    "827": "Infinite Class 124",
    "833": "Infinite Grade 125",
    "840": "Infinite Position 126",
    "847": "Infinite Status 127",
    "853": "Infinite Role 128",
    "860": "Infinite Title 129",
    "867": "Infinite Authority 130",
    "873": "Infinite Rank 131",
    "880": "Infinite Level 132",
    "887": "Eternal Tier 133",
    "893": "Eternal Class 134",
    "900": "Eternal Grade 135",
    "907": "Eternal Position 136",
    "913": "Eternal Status 137",
    "920": "Eternal Role 138",
    "927": "Eternal Title 139",
    "933": "Eternal Authority 140",
    "940": "Eternal Rank 141",
    "947": "Transcendent Level 142",
    "953": "Transcendent Tier 143",
    "960": "Transcendent Class 144",
    "967": "Transcendent Grade 145",
    "973": "Transcendent Position 146",
    "980": "Transcendent Status 147",
    "987": "Transcendent Role 148",
    "993": "Transcendent Title 149",
    "1000": "Transcendent Authority 150"
},
}
