import { AnimeThemeConfig } from "./types"
import { GiBookCover, GiQuill, GiSpellBook, GiBroadsword, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiBookAura, GiHeartKey, GiCrown } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const omniscientReaderTheme: AnimeThemeConfig = {
    id: "omniscient-reader",
    displayName: "Omniscient Reader's Viewpoint",
    description: "Kim Dokja is the only reader of an obscure web novel called Three Ways to Survive the Apocalypse — and when the world begins following the novel's plot exactly, his knowledge of the story becomes humanity's greatest weapon.",
    fontFamily: "'Crimson Text', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Crimson+Text:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "210 190 255",
        "--color-brand-300": "175 148 248",
        "--color-brand-400": "140 108 232",
        "--color-brand-500": "108 74 205",
        "--color-brand-600": "80 50 170",
        "--color-brand-700": "56 30 132",
        "--color-brand-800": "34 14 90",
        "--color-brand-900": "16 5 50",
        "--color-brand-950": "6 0 22",
        "--brand": "108 74 205",
        "--background": "#020104",
        "--paper": "#07040e",
        "--color-gray-950": "2 1 4",
        "--color-gray-900": "7 4 12",
        "--color-gray-800": "16 10 24",
        "--color-gray-700": "28 18 42",
        "--color-gray-600": "46 32 68",
        "--color-gray-500": "76 55 108",
        "--color-gray-400": "114 88 155",
        "--color-gray-300": "156 128 200",
        "--color-gray-200": "195 170 235",
        "--color-gray-100": "225 205 250",
        "--color-gray-50": "246 238 255",
    },
    sidebarOverrides: {
        "home": { icon: GiBookCover, label: "Dokja's Library" },
        "schedule": { icon: GiAlarmClock, label: "Scenario Schedule" },
        "manga": { icon: LuBookOpen, label: "Web Novel" },
        "lists": { icon: GiFlowerEmblem, label: "Character Registry" },
        "discover": { icon: GiBullseye, label: "New Scenarios" },
        "torrent-list": { icon: GiSpellBook, label: "Story Cache" },
        "debrid": { icon: GiBookAura, label: "Dokja's Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Companions" },
        "enmasse": { icon: GiResize, label: "Company Ops" },
        "scan-summaries": { icon: TbReportSearch, label: "Plot Reports" },
        "auto-downloader": { icon: LuRss, label: "Novel Feed" },
        "community": { icon: GiQuill, label: "Readers Circle" },
        "achievements": { icon: GiTrophy, label: "Reader Awards" },
        "milestones": { icon: LuFlag, label: "Story Milestones" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Plot Alerts" },
        "theme-manager": { icon: GiPalette, label: "Indigo Palette" },
        "extensions": { icon: BiExtension, label: "Story Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Story Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Dokja's Config" },
    },
    achievementNames: {
        "a_first_episode": "Sole Reader Awakens",
        "a_first_complete": "First Scenario Cleared",
        "a_hundred_club": "Hundred Scenarios Witnessed",
        "a_time_lord": "Time-Loop Survivor",
        "a_anime_collector": "Three Ways Archive",
        "a_library_legend": "Dokja's Full Canon",
        "a_binge_king": "Regression Marathon",
        "a_no_sleep": "All-Night Scenario Watch",
        "a_marathon_runner": "Dokja's Endurance Run",
        "a_speed_run": "Speed-Read the Regression",
        "a_completionist": "Every Route Witnessed",
        "a_mega_completionist": "Omniscient Reader",
        "a_loyal_fan": "Last Reader Standing",
        "a_rewatcher": "Second Regression",
        "a_decade_watcher": "Decade of Scenarios",
        "a_genre_action": "Constellation Battle Stage",
        "a_genre_adventure": "Scenario Journey Beyond",
        "a_genre_comedy": "Yoo Joonghyuk's Exasperation",
        "a_genre_drama": "Kim Dokja's Sacrifice",
        "a_genre_fantasy": "Apocalyptic World Reborn",
        "a_genre_horror": "Dark Scenario Unleashed",
        "a_genre_romance": "Han Sooyoung's Devotion",
        "a_genre_scifi": "Regression Science Decoded",
        "a_genre_supernatural": "Constellation's Sponsorship",
        "a_genre_psychological": "Dokja's Endless Mind",
        "a_genre_mecha": "Iron Armour Scenario",
        "a_critic": "Plot Constellation Judge",
        "a_perfect_ten": "Perfect Narrative Score",
        "a_harsh_critic": "Omniscient Standard Set",
        "a_daily_streak": "Daily Scenario Read",
        "a_mega_streak": "Regression Story Streak",
        "a_year_long": "Year of Three Ways",
        "a_iron_will": "Dokja's Unbreakable Will",
        "a_hidden_gem": "Hidden Constellation Discovered",
        "a_cult_classic": "Sole Reader's Classic",
        "a_classic_connoisseur": "ORV First Edition Fan",
        "a_new_years_resolution": "New Year Scenario",
        "a_christmas_special": "Winter Constellation Gift",
        "a_meta_tier_max": "True Omniscient Achieved",
        "a_meta_completionist": "All Chapters Cleared",
        "a_sequel_chain": "Regression Chain Completed",
        "a_zero_to_hero": "Sole Reader to Savior",
        "a_night_owl": "Midnight Scenario Reader",
        "a_early_bird": "Dawn Chapter Opened",
        "m_first_chapter": "First Page of Three Ways",
        "m_first_complete": "Manhwa Arc Completed",
        "m_hundred_club": "Hundred Chapters Witnessed",
        "m_binge_king": "Manhwa Regression Binge",
        "m_completionist": "Full ORV Manhwa Run",
        "m_mega_completionist": "Omniscient Manhwa Master",
        "m_loyal_reader": "Sole Devoted Reader",
        "m_rereader": "Second Regression Reading",
        "m_genre_action": "Constellation Battle Chapter",
        "m_genre_adventure": "Scenario Journey Chapter",
        "m_genre_romance": "Sooyoung's Hidden Feeling",
        "m_genre_fantasy": "Regression Fantasy Chapter",
        "m_genre_horror": "Dark Scenario Chapter",
        "m_genre_drama": "Dokja's Sacrifice Chapter",
        "m_genre_scifi": "Regression Science Chapter",
        "m_genre_supernatural": "Constellation Blessing Chapter",
        "m_genre_psychological": "Mind Maze Chapter",
        "m_critic": "Dokja's Narrative Review",
        "m_perfect_ten": "Perfect Manhwa Score",
        "m_daily_streak": "Daily Manhwa Chapter",
        "m_mega_streak": "Regression Streak Unbroken",
        "m_year_long": "Year Reading Three Ways",
        "m_iron_will": "Iron Will of the Reader",
        "m_hidden_gem": "Hidden Chapter Discovered",
        "m_cult_classic": "Web Novel Cult Reader",
        "m_mangaka_lover": "Singshong's Devoted Fan",
        "m_source_material_fan": "Novel Before Manhwa",
        "m_meta_tier_max": "ORV Manhwa Completed",
        "m_meta_completionist": "Full Library Cleared",
        "m_art_appreciator": "Singshong's Art Admired",
        "m_manga_to_anime": "Three Ways Adaptation",
        "m_night_owl": "Midnight Manhwa Reader",
        "m_early_bird": "Dawn Manhwa Chapter",
    },
    musicUrl: "",
    previewColors: {
        bg: "#020104",
        primary: "#6c4acd",
        secondary: "#5032aa",
        accent: "#c09850",
    },
    particleColor: "#9068d8",
    backgroundDim: 0.30,
    backgroundBlur: 18,
    particleTypes: {
        purple_sparks: { label: "Constellation Stars", maxCount: 18, defaultEnabled: true, defaultIntensity: 55 },
        book_pages: { label: "Story Pages", maxCount: 10, defaultEnabled: true, defaultIntensity: 38 },
    },
    milestoneNames: {
    1: "Generic Rank",
    7: "Generic Rank",
    14: "Generic Rank",
    21: "Generic Rank",
    27: "Generic Rank",
    34: "Generic Rank",
    41: "Generic Rank",
    47: "Generic Rank",
    54: "Generic Rank",
    61: "Generic Rank",
    68: "Generic Rank",
    74: "Generic Rank",
    81: "Generic Rank",
    88: "Generic Rank",
    94: "Generic Rank",
    101: "Generic Rank",
    108: "Generic Rank",
    114: "Generic Rank",
    121: "Generic Rank",
    128: "Generic Rank",
    135: "Generic Rank",
    141: "Generic Rank",
    148: "Generic Rank",
    155: "Generic Rank",
    161: "Generic Rank",
    168: "Generic Rank",
    175: "Generic Rank",
    182: "Generic Rank",
    188: "Generic Rank",
    195: "Generic Rank",
    202: "Generic Rank",
    208: "Generic Rank",
    215: "Generic Rank",
    222: "Generic Rank",
    228: "Generic Rank",
    235: "Generic Rank",
    242: "Generic Rank",
    249: "Generic Rank",
    255: "Generic Rank",
    262: "Generic Rank",
    269: "Generic Rank",
    275: "Generic Rank",
    282: "Generic Rank",
    289: "Generic Rank",
    296: "Generic Rank",
    302: "Generic Rank",
    309: "Generic Rank",
    316: "Generic Rank",
    322: "Generic Rank",
    329: "Generic Rank",
    336: "Generic Rank",
    342: "Generic Rank",
    349: "Generic Rank",
    356: "Generic Rank",
    363: "Generic Rank",
    369: "Generic Rank",
    376: "Generic Rank",
    383: "Generic Rank",
    389: "Generic Rank",
    396: "Generic Rank",
    403: "Generic Rank",
    409: "Generic Rank",
    416: "Generic Rank",
    423: "Generic Rank",
    430: "Generic Rank",
    436: "Generic Rank",
    443: "Generic Rank",
    450: "Generic Rank",
    456: "Generic Rank",
    463: "Generic Rank",
    470: "Generic Rank",
    477: "Generic Rank",
    483: "Generic Rank",
    490: "Generic Rank",
    497: "Generic Rank",
    503: "Generic Rank",
    510: "Generic Rank",
    517: "Generic Rank",
    523: "Generic Rank",
    530: "Generic Rank",
    537: "Generic Rank",
    544: "Generic Rank",
    550: "Generic Rank",
    557: "Generic Rank",
    564: "Generic Rank",
    570: "Generic Rank",
    577: "Generic Rank",
    584: "Generic Rank",
    591: "Generic Rank",
    597: "Generic Rank",
    604: "Generic Rank",
    611: "Generic Rank",
    617: "Generic Rank",
    624: "Generic Rank",
    631: "Generic Rank",
    637: "Generic Rank",
    644: "Generic Rank",
    651: "Generic Rank",
    658: "Generic Rank",
    664: "Generic Rank",
    671: "Generic Rank",
    678: "Generic Rank",
    684: "Generic Rank",
    691: "Generic Rank",
    698: "Generic Rank",
    704: "Generic Rank",
    711: "Generic Rank",
    718: "Generic Rank",
    725: "Generic Rank",
    731: "Generic Rank",
    738: "Generic Rank",
    745: "Generic Rank",
    751: "Generic Rank",
    758: "Generic Rank",
    765: "Generic Rank",
    772: "Generic Rank",
    778: "Generic Rank",
    785: "Generic Rank",
    792: "Generic Rank",
    798: "Generic Rank",
    805: "Generic Rank",
    812: "Generic Rank",
    818: "Generic Rank",
    825: "Generic Rank",
    832: "Generic Rank",
    839: "Generic Rank",
    845: "Generic Rank",
    852: "Generic Rank",
    859: "Generic Rank",
    865: "Generic Rank",
    872: "Generic Rank",
    879: "Generic Rank",
    886: "Generic Rank",
    892: "Generic Rank",
    899: "Generic Rank",
    906: "Generic Rank",
    912: "Generic Rank",
    919: "Generic Rank",
    926: "Generic Rank",
    932: "Generic Rank",
    939: "Generic Rank",
    946: "Generic Rank",
    953: "Generic Rank",
    959: "Generic Rank",
    966: "Generic Rank",
    973: "Generic Rank",
    979: "Generic Rank",
    986: "Generic Rank",
    993: "Generic Rank",
    1000: "Generic Rank",
  },
}
