import { AnimeThemeConfig } from "./types"
import { GiRose, GiCrown, GiGoldBar, GiCherish, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiDiamondHard } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const ouranHostClubTheme: AnimeThemeConfig = {
    id: "ouran-host-club",
    displayName: "Ouran High School Host Club",
    description: "When scholarship student Haruhi breaks an expensive vase, she's forced to join the Host Club — a group of rich, eccentric boys who entertain female clients. A reverse harem comedy with real heart.",
    fontFamily: "'Playfair Display', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700;1,400&display=swap",
    cssVars: {
        "--color-brand-200": "255 228 190",
        "--color-brand-300": "248 204 148",
        "--color-brand-400": "235 176 100",
        "--color-brand-500": "218 146 52",
        "--color-brand-600": "180 116 30",
        "--color-brand-700": "140 88 16",
        "--color-brand-800": "100 62 8",
        "--color-brand-900": "60 36 3",
        "--color-brand-950": "34 20 1",
        "--brand": "218 146 52",
        "--background": "#060500",
        "--paper": "#100e02",
        "--color-gray-950": "6 5 0",
        "--color-gray-900": "14 12 2",
        "--color-gray-800": "26 22 6",
        "--color-gray-700": "44 38 12",
        "--color-gray-600": "68 60 24",
        "--color-gray-500": "105 95 48",
        "--color-gray-400": "148 138 92",
        "--color-gray-300": "186 178 138",
        "--color-gray-200": "214 208 175",
        "--color-gray-100": "232 228 208",
        "--color-gray-50": "246 244 235",
    },
    sidebarOverrides: {
        "home": { icon: GiRose, label: "Music Room 3" },
        "schedule": { icon: GiAlarmClock, label: "Club Schedule" },
        "manga": { icon: LuBookOpen, label: "Club Records" },
        "lists": { icon: GiCrown, label: "Host Registry" },
        "discover": { icon: GiBullseye, label: "New Clients" },
        "torrent-list": { icon: GiGoldBar, label: "Club Treasury" },
        "debrid": { icon: GiDiamondHard, label: "Elite Store" },
        "unmatched": { icon: GiCherish, label: "New Members" },
        "enmasse": { icon: GiResize, label: "Club Events" },
        "scan-summaries": { icon: TbReportSearch, label: "Guest Reports" },
        "auto-downloader": { icon: LuRss, label: "Club Announcements" },
        "community": { icon: GiRose, label: "Host Club" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Club Bells" },
        "achievements": { icon: GiTrophy, label: "Elite Trophies" },
        "milestones": { icon: LuFlag, label: "Host Goals" },
        "theme-manager": { icon: GiPalette, label: "Club Colors" },
        "extensions": { icon: BiExtension, label: "Host Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Club Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Tamaki's Rules" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "Welcome, Princess",
        "a_episode_counter": "Endless Hosting Mark",
        "a_episode_titan": "Elite Trophies Relic",
        "a_hours_invested": "Top Host Proof",
        "a_time_lord": "Host Club Veteran",
        "a_anime_collector": "Rose Collection",
        "a_library_legend": "Club Archives",
        "a_first_complete": "Host Club Complete",
        "a_hundred_club": "Hundred Guests",
        "a_first_day": "Karate Haruhi Seal",
        "a_first_rating": "Elite Trophies Appraisal",
        "a_ten_thousand_min": "Haruhi Resolve Standard",
        "a_season_veteran": "Haruhi Resolve Library",
        "a_year_explorer": "Family Secrets Map",
        "a_century_watcher": "Haruhi's Heart Ledger",
        "a_five_hundred_eps": "Hatori Master Dominion",
        "a_thousand_eps": "Rose Collection Record",
        "a_watching_ten": "Ouran High School Acclaim",
        "a_ptw_hoarder": "Love Library",
        "a_dropped_honesty": "Ouran High School Summit",
        "a_five_thousand_eps": "Kyoya's Review Warrant",
        "a_ten_completed": "Night Hosting Afterglow",
        "a_fifty_completed": "Haruhi's Friend Ascension",
        "a_five_hundred_completed": "Ouran High School Clear",
        "a_mean_score_tracker": "Welcome Princess Verdict",
        "a_unique_studios": "Rose Collection Collection",
        "a_days_spent_watching": "Trip Dominion",
        "a_all_status": "Haruhi's Independence Testament",
        "a_first_favorite": "Twins Trick Cabinet",
        "a_favorites_collector": "Commoner Host Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Nekozawa Cult Drive",
        "a_marathon_runner": "Endless Events",
        "a_weekend_warrior": "Elite Trophies Ordeal",
        "a_non_stop": "Dawn Fever",
        "a_one_more_episode": "Mother Control Mantle",
        "a_speed_run": "Twins Trick",
        "a_double_feature": "Hatori Fan Crown",
        "a_triple_threat": "Hatori Classic Record",
        "a_five_a_day": "Host Judge Accord",
        "a_back_to_back": "Tamaki's Antics Surge",
        "a_seasonal_binge": "Elite Trophies Cascade",
        "a_cour_crusher": "Trip Ordeal",
        "a_half_day_watch": "Endless Hosting Crown",
        "a_full_day_watch": "Host Critic Pinnacle",
        "a_power_weekend": "Karate Haruhi Run",
        "a_binge_king": "Club Marathon",
        "a_no_sleep": "All-Night Hosting",
        "a_entire_season": "Morning Rose Library",
        "a_seven_day_challenge": "Host Critic Mark",
        "a_hundred_day_binge": "Karate Haruhi Surge",
        "a_genre_binge": "Rose Binge",
        "a_studio_binge": "Endless Hosting Fever",
        "a_season_sweep": "Cult Codex",
        "a_forty_eight_hour": "Kyoya's Mind Overture",
        "a_ep_counter_day": "Night Hosting Aegis",
        "a_multi_series_binge": "Love Streak",
        "a_midnight_binge": "Mother Control Cascade",
        "a_new_year_binge": "Host Registry Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Karate Haruhi",
        "a_genre_adventure": "Club Field Trip",
        "a_genre_comedy": "Tamaki's Antics",
        "a_genre_drama": "Family Secrets",
        "a_genre_fantasy": "Host World",
        "a_genre_horror": "Mother Control",
        "a_genre_mystery": "Host Mystery",
        "a_genre_romance": "Haruhi's Heart",
        "a_genre_scifi": "None Here",
        "a_genre_sol": "Kyoya's Review Slice",
        "a_genre_sports": "Kyoya's Mind Sports",
        "a_genre_supernatural": "Nekozawa Cult",
        "a_genre_thriller": "Haruhi's Friend Thriller",
        "a_genre_mecha": "None Here",
        "a_genre_music": "Haruhi Resolve Music",
        "a_genre_psychological": "Kyoya's Mind",
        "a_genre_ecchi": "Nekozawa Cult Ecchi",
        "a_genre_mahou_shoujo": "Hatori Classic Magic Shoujo",
        "a_tag_isekai": "Rose Art Isekai",
        "a_tag_harem": "Decade Fan Harem",
        "a_tag_bl": "Kyoya's Mind Bl",
        "a_tag_gl": "Mother Control Gl",
        "a_tag_historical": "Music Room Historical",
        "a_tag_military": "Hatori Master Military",
        "a_tag_school": "Love School",
        "a_tag_martial_arts": "Host Critic Martial Arts",
        "a_tag_vampire": "Hatori Classic Vampire",
        "a_tag_samurai": "Rose Collection Samurai",
        "a_tag_space": "Field Trip Space",
        "a_tag_parody": "All Members Parody",
        "a_tag_idol": "Kyoya's Mind Idol",
        "a_tag_post_apocalyptic": "All Post Apocalyptic",
        "a_tag_cyberpunk": "Dawn Cyberpunk",
        "a_tag_shounen": "All Shounen",
        "a_tag_seinen": "Host Expert Seinen",
        "a_tag_shoujo": "Host Expert Shoujo",
        "a_tag_josei": "Night Hosting Josei",
        "a_tag_survival": "Commoner Host Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "All Members",
        "a_mega_completionist": "Hatori Master",
        "a_completion_rate_50": "Hatori Classic Return",
        "a_completion_rate_75": "Haruhi's Friend Crown",
        "a_completion_rate_90": "Night Hosting Resolution",
        "a_no_drop": "Host Decree",
        "a_long_runner_complete": "Karate Haruhi Clear",
        "a_sequel_chain": "Manga Continues",
        "a_clean_list": "Cult Relic",
        "a_from_ptw": "All Members Index",
        "a_rewatch_master": "Welcome Princess Return",
        "a_short_complete": "Classic Comedy Endgame",
        "a_same_day_start_finish": "Fan Pinnacle",
        "a_revival": "Haruhi's Heart Insignia",
        "a_zero_to_hero": "Commoner to Host",
        "a_five_genre_complete": "Classic Comedy A Five Genre",
        "a_full_franchise": "Love Chronicle",
        "a_batch_complete": "Elite Trophies Crown",
        "a_paused_to_done": "Night Hosting Aegis Aegis",
        "a_completion_spree": "Endless Events Triumph",
        "a_multi_rewatch": "Endless Events Triumph Triumph",
        "a_dropped_recovery": "Endless Hosting Conquest",
        "a_ten_perfect_scores": "Karate Haruhi Acclaim",
        "a_seasonal_clear": "Trip Codex",
        "a_complete_genre_span": "Host World A Complete Genre",
        "a_monthly_completions": "Welcome Princess Afterglow",
        "a_yearly_completions": "Haruhi's Independence Epilogue",
        "a_rapid_complete": "Host Critic Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Haruhi's Friend",
        "a_studio_devotee": "Host Treasury",
        "a_rewatcher": "Club Revisit",
        "a_triple_rewatch": "Rose Coda",
        "a_annual_tradition": "Host Critic Proof",
        "a_director_fan": "Cult Trial",
        "a_voice_actor_fan": "Endless Hosting Crown Crown",
        "a_ost_lover": "Love Seal",
        "a_source_reader": "Family Secrets Cabinet",
        "a_waiting_weekly": "Host Clock",
        "a_childhood_revisit": "Tamaki's Rules Seal",
        "a_saga_tracker": "Field Trip Standard",
        "a_genre_loyalty": "Kyoya's Review Loyalty",
        "a_decade_watcher": "Decade Fan",
        "a_adaptation_hunter": "All Members Trial",
        "a_original_anime_fan": "Holiday Ball Testament",
        "a_long_commitment": "Host Critic Mark Mark",
        "a_perfect_attendance": "Ouran High School Standard",
        "a_favorite_studio_5": "All Library",
        "a_complete_catalog": "Commoner Host Seal",
        "a_franchise_collector": "All Archive",
        "a_airing_follower": "Tamaki's Rules Signal",
        "a_genre_master": "Cult Master",
        "a_staff_follower": "All Oath",
        "a_multi_season_fan": "Music Room Hoard",
        "a_format_diversity": "Hatori Classic Cache",
        "a_year_dedication": "Elite Trophies Tenure",
        "a_season_dedication": "Hatori Master Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Rose Explorer",
        "a_studio_hopper": "Welcome Princess Collection",
        "a_tag_explorer": "Elite Trophies Explorer",
        "a_decade_hopper": "Love Chronicle Chronicle",
        "a_hidden_gem": "Hidden Episode",
        "a_popular_taste": "Kyoya's Mind Decree",
        "a_retro_appreciator": "Commoner Host Aegis",
        "a_modern_viewer": "Fan Pinnacle Pinnacle",
        "a_cross_demographic": "Nekozawa Cult Pinnacle",
        "a_underdog_fan": "Host World Trial",
        "a_variety_week": "All Horizon",
        "a_foreign_cinema": "Mother Control Expedition",
        "a_classic_connoisseur": "2006 Fan",
        "a_every_season": "Tamaki's Rules Archive",
        "a_award_winner": "Haruhi Resolve Insignia",
        "a_niche_explorer": "Host Expert Horizon",
        "a_global_anime": "Classic Comedy Crown",
        "a_cult_classic": "Hatori Classic",
        "a_random_pick": "Kyoya's Mind Decree Decree",
        "a_new_genre_month": "Ouran High School A New",
        "a_seasonal_completionist": "Haruhi's Heart Summit",
        "a_unpopular_opinion": "Twins Trick Standard",
        "a_top_rated_viewer": "Host Judge Seal",
        "a_source_variety": "Trip Storehouse",
        "a_low_score_brave": "Dawn Measure",
        "a_upcoming_watcher": "Host Judge Seal Seal",
        "a_short_series_explorer": "Mother Control Expedition Expedition",
        "a_long_series_explorer": "Hatori Fan Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Night Club",
        "a_early_bird": "Morning Rose",
        "a_lunch_break": "All Night Trial",
        "a_golden_hour": "Tamaki's Daddy Tenure",
        "a_four_am_club": "Endless Events Gathering",
        "a_witching_hour": "Haruhi's Friend Tenure",
        "a_new_year_watch": "Elite Trophies Season",
        "a_midnight_premiere": "Host Registry Devotion",
        "a_all_hours": "Haruhi's Heart Seal",
        "a_dawn_warrior": "Kyoya's Mind Aegis",
        "a_afternoon_delight": "Top Host Proof Proof",
        "a_prime_time": "Haruhi Resolve Insignia Insignia",
        "a_workday_watcher": "Nekozawa Cult Pinnacle Pinnacle",
        "a_sunday_marathon": "Karate Haruhi Momentum",
        "a_rainy_day": "Haruhi's Friend Relic",
        "a_morning_routine": "Music Room Promise",
        "a_night_shift": "Hatori Classic Aegis",
        "a_twilight_zone": "Morning Rose Ledger",
        "a_seasonal_premier": "Host Cabinet",
        "a_clock_collector": "Endless Events Repository",
        "a_weekend_binge_hours": "Host Expert Streak",
        "a_late_night_regular": "Haruhi's Independence Dominion",
        "a_sunrise_watcher": "Cult Relic Relic",
        "a_holiday_watcher": "Host Judge Pact",
        "a_every_day_of_week": "Tamaki's Antics Ledger",
        "a_monthly_hours": "Kyoya's Mind Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Night Hosting Record",
        "a_party_host": "Hatori Classic Record Record",
        "a_social_butterfly": "Family Secrets Company",
        "a_group_binge": "Rose Collection Sprint",
        "a_party_regular": "Morning Rose Chronicle",
        "a_sync_viewer": "Endless Events Standard",
        "a_commentator": "Commoner Host Record",
        "a_party_marathon": "Rose Vigil",
        "a_full_house": "Hatori Master Trial",
        "a_community_pillar": "Haruhi's Independence Alliance",
        "a_watch_party_streak": "Commoner Host Vigil",
        "a_diverse_party": "Music Room Seal",
        "a_late_night_party": "Haruhi's Independence Testament Testament",
        "a_party_veteran": "Hatori Master Testament",
        "a_genre_party": "Mother Control Party",
        "a_weekly_party": "Endless Events Calendar",
        "a_silent_viewer": "Holiday Ball Mantle",
        "a_recommendation_giver": "Host Expert Network",
        "a_party_completionist": "Field Trip Coda",
        "a_social_scorer": "Cult Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Hatori Fan Proof",
        "a_fibonacci": "Elite Trophies Dominion",
        "a_palindrome_day": "Elite Trophies Relic Relic",
        "a_binary_day": "Kyoya's Review Mark",
        "a_full_moon": "Tamaki's Rules Insignia",
        "a_leap_year": "Classic Comedy Devotion",
        "a_time_traveler": "Host Record",
        "a_genre_clash": "Rose Clash",
        "a_triple_seven": "Elite Trophies Testament",
        "a_thousand_complete": "Holiday Ball Epilogue",
        "a_pi_episodes": "Nekozawa Cult Crown",
        "a_synchronicity": "Host World Anchor",
        "a_world_record": "Endless Hosting Warrant",
        "a_nice": "Haruhi Resolve Chronicle",
        "a_power_level": "Holiday Ball Testament Testament",
        "a_answer_42": "Kyoya's Mind Standard",
        "a_square_number": "Rose Decree",
        "a_prime_count": "Haruhi Resolve Seal",
        "a_matching_date": "Host World Mantle",
        "a_century_episode": "Nekozawa Cult Mark",
        "a_double_digits": "Haruhi's Friend Testament",
        "a_one_two_three": "Classic Comedy Crown Crown",
        "a_lucky_seven": "Host Critic Crown",
        "a_all_tens": "Dawn Criterion",
        "a_exact_hundred_eps": "Field Trip Legend",
        "a_year_match_count": "Host Yearlong",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Host Expert Ledger",
        "a_movie_buff": "Endless Hosting Mark Mark",
        "a_ova_hunter": "Field Trip Standard Standard",
        "a_ona_explorer": "Host World Secret",
        "a_special_watcher": "Haruhi's Friend Relic Relic",
        "a_short_king": "Decade Fan Crown",
        "a_variety_pack": "Endless Hosting Inquiry",
        "a_film_festival": "Host Judge Chronicle",
        "a_music_video": "Music Room Chronicle",
        "a_tv_short": "Rose Record",
        "a_movie_marathon": "Rose Gauntlet",
        "a_double_length": "Hatori Fan Crown Crown",
        "a_anthology": "Hatori Classic Aegis Aegis",
        "a_mini_series": "Twins Trick Decree",
        "a_theatrical": "All Accord",
        "a_format_master": "Endless Events Vault",
        "a_long_movie": "Haruhi's Heart Insignia Insignia",
        "a_back_catalog": "Commoner Host Standard",
        "a_cm_watcher": "Rose Art Aegis",
        "a_pv_collector": "Host World Storehouse",
        "a_format_balance": "Endless Events Vault Vault",
        "a_episodic_master": "Rose Art Standard",
        "a_sequel_movie": "Classic Comedy Pinnacle",
        "a_recap_watcher": "All Night Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Club",
        "a_mega_streak": "Endless Hosting",
        "a_weekly_warrior": "Hatori Master Season",
        "a_monthly_watcher": "Host Registry Calendar",
        "a_comeback": "Family Secrets Decree",
        "a_weekend_streak": "Dawn Passage",
        "a_no_zero_days": "Kyoya's Review Warrant Warrant",
        "a_iron_will": "Haruhi's Independence",
        "a_habit_formed": "Tamaki's Antics Banner",
        "a_consistent_pace": "Hatori Fan Measure",
        "a_year_long": "Full Club Year",
        "a_double_streak": "Cult Watch",
        "a_streak_recovery": "Holiday Ball Season",
        "a_daily_minimum": "Host Registry Focus",
        "a_winter_streak": "Mother Control Watch",
        "a_summer_streak": "Haruhi's Friend Resolve",
        "a_morning_streak": "Commoner Host Clock",
        "a_night_streak": "Tamaki's Antics Constancy",
        "a_unbreakable": "Decade Fan Proof",
        "a_eternal_flame": "Welcome Princess Standard",
        "a_completion_streak": "Field Trip Return",
        "a_rating_streak": "Elite Trophies Balance",
        "a_multi_ep_streak": "Endless Hosting Ritual",
        "a_genre_streak": "Elite Trophies Streak",
        "a_studio_streak": "Family Secrets Cabinet Cabinet",
        "a_perfect_week": "Host World Relic",

        // ── ANIME SCORING ──
        "a_critic": "Host Judge",
        "a_perfect_ten": "Top Host",
        "a_harsh_critic": "Kyoya's Review",
        "a_fair_judge": "Haruhi's Independence Balance",
        "a_generous_spirit": "Host Registry Pinnacle",
        "a_score_all": "Top Host Criterion",
        "a_wide_range": "Haruhi Resolve Ledger",
        "a_controversial": "Commoner Host Decree",
        "a_consistent_scorer": "Host Verdict",
        "a_score_sniper": "Classic Comedy Score",
        "a_evolving_taste": "Cult Testament",
        "a_bell_curve": "Ouran High School Insignia",
        "a_picky_watcher": "Holiday Ball Warrant",
        "a_100_rated": "Endless Events Warrant",
        "a_500_rated": "Decade Fan Pinnacle",
        "a_mediocre_majority": "Host World Canon",
        "a_rating_spree": "Commoner Host Review",
        "a_score_variance": "Dawn Score",
        "a_masterpiece_hunter": "Commoner Host Banner",
        "a_contrarian": "Rose Record Record",
        "a_optimist": "Music Room Ledger",
        "a_score_distributor": "All Night Appraisal",
        "a_genre_critic": "Hatori Fan Critic",
        "a_mean_above_8": "Host Critic Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Club",
        "a_valentines_weeb": "All Vow",
        "a_pi_day": "Haruhi's Independence Trial",
        "a_april_fools": "Classic Comedy Devotion Devotion",
        "a_international_anime_day": "Haruhi's Heart Record",
        "a_star_wars_day": "Karate Haruhi Chronicle",
        "a_summer_solstice": "Kyoya's Review Calendar",
        "a_tanabata": "Fan Focus",
        "a_friday_13th": "All Night Relic",
        "a_halloween_spirit": "Host Expert Vow",
        "a_thanksgiving_binge": "Morning Rose Run",
        "a_christmas_special": "Holiday Ball",
        "a_new_years_eve": "Host Critic Pilgrimage",
        "a_birthday_watch": "Ouran High School Vow",
        "a_holiday_marathon": "Rose Collection Overture",
        "a_independence_day": "Welcome Princess Banner",
        "a_culture_day": "Love Insignia",
        "a_spring_equinox": "Rose Collection Decree",
        "a_earth_day": "Endless Hosting Mantle",
        "a_labor_day": "Host Expert Seal",
        "a_winter_solstice": "Nekozawa Cult Pilgrimage",
        "a_anime_birthday": "Endless Hosting Pilgrimage",
        "a_every_holiday": "All Members Resolve",
        "a_consecutive_holidays": "Haruhi's Friend Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Family Secrets Rank",
        "a_meta_collector": "Love Hoard",
        "a_meta_category_starter": "Host Registry Badge",
        "a_meta_tier_climber": "Love Glyph",
        "a_meta_tier_max": "Tamaki's Daddy",
        "a_meta_xp_earner": "All Night Emblem",
        "a_meta_difficulty_easy": "Haruhi's Independence Mechanism",
        "a_meta_difficulty_hard": "Host Judge Writ",
        "a_meta_unlock_spree": "Hatori Master Panel",
        "a_meta_completionist": "Complete Club",
        "a_meta_diverse": "Elite Trophies Emblem",
        "a_meta_dominator": "Morning Rose Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Guest",
        "m_chapter_counter": "Endless Events Pinnacle",
        "m_chapter_titan": "Trip Relic",
        "m_reading_hours": "All Night Relic Relic",
        "m_reading_time_lord": "Haruhi's Heart Record Record",
        "m_manga_collector": "Hatori Master Ledger",
        "m_library_legend": "Love Reliquary",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "All Seal",
        "m_first_rating": "All Night Eye",
        "m_ten_thousand_pages": "All Gauge",
        "m_volume_collector": "Holiday Ball Storehouse",
        "m_year_explorer": "Kyoya's Mind Quest",
        "m_century_reader": "Mother Control Dominion",
        "m_five_hundred_ch": "Haruhi Resolve Legend",
        "m_thousand_ch": "Cult Legend",
        "m_reading_ten": "Mother Control Appraisal",
        "m_ptr_hoarder": "Cult Index",
        "m_dropped_honesty": "Love Summit",
        "m_season_reader": "Commoner Host Treasury",
        "m_active_reader": "Haruhi's Friend Trial",
        "m_five_thousand_ch": "Rose Standard",
        "m_ten_completed": "Rose Resolution",
        "m_fifty_completed": "Cult Harvest",
        "m_five_hundred_completed": "Tamaki's Antics Legacy",
        "m_mean_score_tracker": "Host Audit",
        "m_unique_authors": "Endless Hosting Reserve",
        "m_all_status": "Haruhi's Friend Testament Testament",
        "m_first_favorite": "Field Trip Cache",
        "m_favorites_collector": "Family Secrets Shelf",
        "m_days_spent_reading": "Nekozawa Cult Relic",

        // ── MANGA BINGE ──
        "m_binge_reader": "Ouran High School Streak",
        "m_marathon_reader": "Haruhi's Independence Rush",
        "m_weekend_reader": "Tamaki's Rules Run",
        "m_non_stop_reading": "Field Trip Gauntlet",
        "m_one_more_chapter": "All Night Testament Testament",
        "m_speed_read": "Kyoya's Review Drive",
        "m_double_story": "Rose Collection Banner",
        "m_triple_read": "Welcome Princess Record",
        "m_five_a_day": "Music Room Insignia",
        "m_chapter_chain": "Love Accord",
        "m_volume_binge": "Dawn Drive",
        "m_power_reader": "Karate Haruhi Seal Seal",
        "m_half_day_read": "Family Secrets Aegis",
        "m_full_day_read": "Rose Art Aegis Aegis",
        "m_power_weekend": "All Streak",
        "m_binge_king": "Club Marathon",
        "m_no_sleep_read": "Mother Control Rush",
        "m_full_series_rush": "Haruhi's Independence Cascade",
        "m_seven_day_challenge": "Fan Warrant",
        "m_hundred_day_read": "Elite Trophies Legend",
        "m_volume_rush": "Night Hosting Gauntlet",
        "m_series_sweep": "All Members Trial Trial",
        "m_genre_binge": "Rose Art Binge",
        "m_author_binge": "Tamaki's Rules Surge",
        "m_chapter_counter_day": "Morning Rose Ledger Ledger",
        "m_multi_series_binge": "Haruhi Resolve Charge",
        "m_midnight_binge": "Cult Tempest",
        "m_new_year_binge": "Endless Hosting Passage",
        "m_forty_eight_hour": "Host Rally",
        "m_oneshot_binge": "Kyoya's Review Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Chapter",
        "m_genre_adventure": "Trip Chapter",
        "m_genre_comedy": "Family Secrets Comedy",
        "m_genre_drama": "Family Chapter",
        "m_genre_fantasy": "Club World",
        "m_genre_horror": "Drama Chapter",
        "m_genre_mystery": "Rose Mystery",
        "m_genre_romance": "Love Chapter",
        "m_genre_scifi": "Unusual Chapter",
        "m_genre_sol": "Endless Events Slice",
        "m_genre_sports": "Night Hosting Sports",
        "m_genre_supernatural": "Nekozawa Chapter",
        "m_genre_thriller": "Host World Thriller",
        "m_genre_psychological": "Kyoya Chapter",
        "m_genre_isekai": "Hatori Master Isekai",
        "m_genre_shounen": "Tamaki's Daddy Shounen",
        "m_genre_ecchi": "Hatori Fan Ecchi",
        "m_genre_mahou_shoujo": "Family Secrets Magic Shoujo",
        "m_genre_mecha": "Holiday Ball Mecha",
        "m_genre_music": "Host Expert Music",
        "m_tag_isekai_new": "All Night Isekai New",
        "m_tag_harem": "Top Host Harem",
        "m_tag_bl": "Twins Trick Bl",
        "m_tag_gl": "Cult Gl",
        "m_tag_historical": "Haruhi Resolve Historical",
        "m_tag_military": "Tamaki's Daddy Military",
        "m_tag_school": "All School",
        "m_tag_martial_arts": "Endless Events Martial Arts",
        "m_tag_vampire": "Night Hosting Vampire",
        "m_tag_samurai": "Hatori Classic Samurai",
        "m_tag_space": "Twins Trick Space",
        "m_tag_parody": "Holiday Ball Parody",
        "m_tag_idol": "Twins Trick Idol",
        "m_tag_post_apocalyptic": "Love Post Apocalyptic",
        "m_tag_cyberpunk": "Top Host Cyberpunk",
        "m_tag_shoujo": "Host Judge Shoujo",
        "m_tag_survival": "Family Secrets Survival",
        "m_tag_cooking": "Ouran High School Cooking",
        "m_tag_medical": "Haruhi's Friend Medical",
        "m_tag_villainess": "Tamaki's Rules Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Host Expert",
        "m_completion_rate_50": "Twins Trick Return",
        "m_completion_rate_75": "Host World Ascension",
        "m_completion_rate_90": "Welcome Princess Resolution",
        "m_no_drop": "Field Trip Decree",
        "m_long_runner_complete": "Morning Rose Clear",
        "m_sequel_chain": "Host Expert Seal Seal",
        "m_clean_list": "Trip Relic Relic",
        "m_from_ptr": "Host Judge Watchlist",
        "m_reread_master": "Haruhi's Independence Trial Trial",
        "m_oneshot_complete": "Haruhi's Independence Ascension",
        "m_same_day_start_finish": "Host Critic Crown Crown",
        "m_revival": "Morning Rose Accord",
        "m_zero_to_hundred": "Rose Banner",
        "m_five_genre_complete": "Kyoya's Review M Five Genre",
        "m_full_collection": "Host Critic Proof Proof",
        "m_batch_complete": "Host Summit",
        "m_paused_to_done": "Welcome Princess Standard Standard",
        "m_completion_spree": "Decade Fan Triumph",
        "m_format_completionist": "Haruhi's Independence Completion",
        "m_catch_up": "Haruhi's Heart Chronicle",
        "m_multi_reread": "Field Trip Banner",
        "m_dropped_recovery": "Hatori Fan Conquest",
        "m_ten_perfect_scores": "Tamaki's Rules Judgment",
        "m_complete_genre_span": "Hatori Master M Complete Genre",
        "m_monthly_completions": "Rose Art Return",
        "m_yearly_completions": "Hatori Master Epilogue",
        "m_rapid_complete": "Fan Finale",
        "m_author_complete": "All Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Club Reader",
        "m_mangaka_lover": "Hatori Fan",
        "m_rereader": "Club Return",
        "m_triple_reread": "Elite Trophies Testament Testament",
        "m_annual_reread": "Rose Banner Banner",
        "m_publisher_fan": "Decade Fan Mark",
        "m_artist_fan": "Host Expert Insignia",
        "m_adaptation_compare": "Ouran High School Insignia Insignia",
        "m_source_material_fan": "Manga First",
        "m_waiting_weekly": "Hatori Classic Streak",
        "m_classic_reader": "Holiday Ball Lantern",
        "m_saga_reader": "Love Decree",
        "m_genre_loyalty": "Hatori Fan Loyalty",
        "m_decade_reader": "Dawn Warrant",
        "m_ln_adaptation": "Dawn Mark",
        "m_original_work": "Night Hosting Standard",
        "m_long_commitment": "Hatori Fan Mark",
        "m_up_to_date": "Endless Hosting Warrant Warrant",
        "m_favorite_mangaka": "Kyoya's Mind Treasury",
        "m_complete_portfolio": "Decade Fan Triumph Triumph",
        "m_franchise_collector": "Haruhi's Heart Archive",
        "m_serialization_follower": "Kyoya's Mind Handshake",
        "m_genre_master": "Trip Master",
        "m_multi_series_author": "Love Insignia Insignia",
        "m_format_diversity": "Night Hosting Shelf",
        "m_year_dedication": "Mother Control Tenure",
        "m_ongoing_follower": "Dawn Fellowship",
        "m_genre_loyalty_50": "Cult Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Rose Collection Explorer",
        "m_publisher_hopper": "Decade Fan Mantle",
        "m_tag_explorer": "All Members Explorer",
        "m_decade_hopper": "Host Judge Chronicle Chronicle",
        "m_hidden_gem": "Hidden Volume",
        "m_popular_taste": "Host Record Record",
        "m_retro_reader": "Host Accord",
        "m_modern_reader": "Haruhi Resolve Seal Seal",
        "m_cross_demographic": "Host Registry Crown",
        "m_underdog_fan": "Host Accord Accord",
        "m_variety_week": "Host Expert Horizon Horizon",
        "m_manhwa_reader": "Classic Comedy Proof",
        "m_manhua_reader": "Holiday Ball Mantle Mantle",
        "m_classic_connoisseur": "Tamaki's Antics Glimpse",
        "m_award_winner": "Mother Control Warrant",
        "m_niche_explorer": "Ouran High School Horizon",
        "m_world_manga": "Haruhi's Heart Chronicle Chronicle",
        "m_cult_classic": "Classic Comedy",
        "m_random_pick": "Host Standard",
        "m_new_genre_month": "Haruhi's Heart M New Genre",
        "m_year_completionist": "Endless Events Fulfillment",
        "m_unpopular_opinion": "Endless Hosting Trial",
        "m_top_rated_reader": "Ouran High School Record",
        "m_source_variety": "Holiday Ball Catalogue",
        "m_low_score_brave": "Endless Events Score",
        "m_short_manga_explorer": "Haruhi Resolve Compass",
        "m_long_manga_explorer": "Rose Survey",
        "m_serialization_explorer": "Host World Road",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Twins Trick Ledger",
        "m_commute_reader": "Haruhi's Friend Tenure Tenure",
        "m_four_am_club": "Decade Fan Fellowship",
        "m_new_year_read": "Host Expert Pact",
        "m_all_hours": "Host Judge Accord Accord",
        "m_prime_time_reader": "Night Hosting Banner",
        "m_workday_reader": "Morning Rose Accord Accord",
        "m_sunday_read": "Twins Trick Standard Standard",
        "m_morning_routine": "Morning Rose Discipline",
        "m_night_shift_reader": "All Accord Accord",
        "m_seasonal_premier_read": "Holiday Ball Seasonal",
        "m_clock_collector": "Nekozawa Cult Reserve",
        "m_late_night_horror": "Kyoya's Review Mark Mark",
        "m_afternoon_reader": "Mother Control Mantle Mantle",
        "m_golden_hour_reader": "Elite Trophies Observance",
        "m_dawn_reader": "All Members Mantle",
        "m_twilight_reader": "Dawn Crown",
        "m_midnight_start": "Night Hosting Routine",
        "m_weekend_binge_hours": "Tamaki's Rules Momentum",
        "m_late_night_regular": "Twins Trick Accord",
        "m_sunrise_reader": "Top Host Mantle",
        "m_every_day_of_week": "Holiday Ball Warrant Warrant",
        "m_monthly_hours": "Rose Collection Vigil",
        "m_bedtime_reader": "Endless Events Warrant Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Rose Art",
        "m_webtoon_reader": "Dawn Mark Mark",
        "m_full_color": "Host Expert Accord",
        "m_doujin_reader": "Welcome Princess Record Record",
        "m_anthology_reader": "Tamaki's Rules Accord",
        "m_adaptation_reader": "Host Banner",
        "m_longstrip_reader": "Elite Trophies Trial",
        "m_4koma_reader": "Hatori Classic Ledger",
        "m_oneshot_reader": "Hatori Master Mantle",
        "m_format_variety": "Decade Fan Gallery",
        "m_light_novel_reader": "Host Judge Insignia",
        "m_novel_reader": "Endless Events Crown",
        "m_visual_storyteller": "Mother Control Testament",
        "m_colored_classic": "Commoner Host Survey",
        "m_webcomic_fan": "Tamaki's Antics Insignia",
        "m_manga_to_anime": "Manga Adapted",
        "m_seinen_reader": "Hatori Fan Pinnacle",
        "m_josei_reader": "Top Host Pinnacle",
        "m_award_winning_art": "Tamaki's Daddy Relic",
        "m_debut_work": "Tamaki's Daddy Dominion",
        "m_vertical_scroll": "Love Decree Decree",
        "m_traditional_format": "Ouran High School Hoard",
        "m_cross_media": "Haruhi Resolve Accord",
        "m_spinoff_reader": "Haruhi's Heart Accord",
        "m_remake_reader": "Haruhi's Independence Pinnacle",
        "m_collaboration_reader": "Tamaki's Antics Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Club Streak",
        "m_weekly_warrior": "Host World Season",
        "m_monthly_reader": "Music Room Discipline",
        "m_comeback": "Rose Standard Standard",
        "m_weekend_streak": "Top Host Fever",
        "m_no_zero_days": "Classic Comedy Proof Proof",
        "m_iron_will": "Haruhi Resolve",
        "m_habit_formed": "Host Registry Crown Crown",
        "m_consistent_pace": "Host Critic Scrutiny Scrutiny",
        "m_year_long": "Year Reading",
        "m_double_streak": "Hatori Master Resolve",
        "m_streak_recovery": "Trip Resolve",
        "m_daily_minimum": "Nekozawa Cult Focus",
        "m_winter_streak": "Elite Trophies Observance Observance",
        "m_summer_streak": "Tamaki's Daddy Observance",
        "m_morning_streak": "Rose Collection Clock",
        "m_night_streak": "Ouran High School Discipline",
        "m_unbreakable": "Top Host Warrant",
        "m_eternal_flame": "Family Secrets Record",
        "m_chapter_a_day": "Twins Trick Ledger Ledger",
        "m_genre_streak": "All Members Streak",
        "m_completion_streak": "Host Return",
        "m_rating_streak": "All Members Appraisal",
        "m_multi_ch_streak": "Host World Tenure",
        "m_author_streak": "Nekozawa Cult Calendar",
        "m_perfect_week_manga": "Haruhi's Heart Accord Accord",
        "m_diverse_streak": "Field Trip Streak",

        // ── MANGA SCORING ──
        "m_critic": "Host Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_harsh_critic": "Host Judge Scale",
        "m_fair_judge": "All Night Eye Eye",
        "m_generous_spirit": "Tamaki's Rules Decree",
        "m_score_all": "Dawn Reckoning",
        "m_wide_range": "Music Room Ledger Ledger",
        "m_controversial": "Rose Art Standard Standard",
        "m_consistent_scorer": "Welcome Princess Grade",
        "m_score_sniper": "Endless Hosting Reckoning",
        "m_evolving_taste": "Hatori Master Trial Trial",
        "m_bell_curve": "Music Room Accord",
        "m_picky_reader": "Field Trip Ledger",
        "m_100_rated": "Music Room Standard",
        "m_500_rated": "All Aegis",
        "m_mediocre_majority": "Hatori Master Canon",
        "m_rating_spree": "Rose Collection Verdict",
        "m_score_variance": "Endless Events Measure",
        "m_binge_rater": "Nekozawa Cult Passage",
        "m_reread_rerate": "Commoner Host Banner Banner",
        "m_masterpiece_hunter": "Rose Art Banner",
        "m_contrarian": "Host Aegis",
        "m_optimist": "Haruhi Resolve Accord Accord",
        "m_score_distributor": "Host World Balance",
        "m_genre_critic": "Nekozawa Cult Critic",
        "m_mean_above_8": "Endless Events Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Mother Control Season",
        "m_valentines_read": "All Members Observance",
        "m_pi_day": "Hatori Master Testament Testament",
        "m_april_fools": "Endless Hosting Devotion",
        "m_international_manga_day": "Host Judge Aegis",
        "m_free_comic_day": "Tamaki's Rules Chronicle",
        "m_summer_solstice": "Fan Focus Focus",
        "m_tanabata": "Host Critic Tanabata",
        "m_friday_13th": "Haruhi's Independence Dominion Dominion",
        "m_halloween_read": "Kyoya's Review Halloween",
        "m_thanksgiving_binge": "Haruhi's Heart Charge",
        "m_christmas_read": "Morning Rose Pact",
        "m_new_years_eve": "Fan Pilgrimage",
        "m_birthday_read": "Hatori Fan Focus",
        "m_holiday_marathon": "Kyoya's Mind Rally",
        "m_independence_day": "Host Aegis Aegis",
        "m_culture_day": "All Seal Seal",
        "m_spring_equinox": "Kyoya's Review Dominion",
        "m_earth_day": "Hatori Fan Trial",
        "m_labor_day": "Morning Rose Seal",
        "m_winter_solstice": "Host Registry Focus Focus",
        "m_manga_birthday": "Host Critic Ritual",
        "m_every_holiday_reader": "Trip Watch",
        "m_consecutive_holidays": "Haruhi's Independence Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Karate Haruhi Aegis",
        "m_fibonacci": "Haruhi's Friend Dominion",
        "m_palindrome_day": "Hatori Master Relic",
        "m_binary_day": "Host Registry Proof",
        "m_full_moon_read": "Top Host Crown",
        "m_leap_year_read": "Field Trip Practice",
        "m_triple_seven": "All Night Trial Trial",
        "m_thousand_complete": "All Night Ascension",
        "m_nice": "Love Seal Seal",
        "m_power_level_chapters": "Rose Aegis",
        "m_answer_42": "Top Host Trial",
        "m_square_number": "Family Secrets Standard",
        "m_prime_count": "All Night Pinnacle",
        "m_matching_date": "Trip Mantle",
        "m_century_chapter": "Karate Haruhi Decree",
        "m_pi_chapters": "Hatori Fan Proof Proof",
        "m_synchronicity": "All Members Emblem",
        "m_world_record": "Classic Comedy Warrant",
        "m_genre_clash": "Night Hosting Clash",
        "m_time_traveler": "Welcome Princess Decree",
        "m_double_digits": "Holiday Ball Dominion",
        "m_one_two_three": "Tamaki's Antics Banner Banner",
        "m_lucky_seven": "Ouran High School Record Record",
        "m_exact_hundred_ch": "Haruhi's Friend Legend",
        "m_year_match_count": "Hatori Classic Routine",
        "m_chapter_match_date": "Host Registry Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Holiday Ball Index",
        "m_manhwa_format": "Kyoya's Review Gallery",
        "m_manhua_format": "Elite Trophies Storehouse",
        "m_ln_format": "All Night Index",
        "m_oneshot_format": "Hatori Master Index",
        "m_doujin_format": "Rose Collection Cabinet",
        "m_novel_format": "Endless Hosting Reserve Reserve",
        "m_format_master_manga": "Rose Collection Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Welcome Princess Link",
        "m_meta_collector": "All Reliquary",
        "m_meta_category_starter": "Decade Fan Standard",
        "m_meta_tier_climber": "Haruhi Resolve Token",
        "m_meta_tier_max": "Host Complete",
        "m_meta_xp_earner": "Holiday Ball Anchor",
        "m_meta_difficulty_easy": "All Night Panel",
        "m_meta_difficulty_hard": "Mother Control Node",
        "m_meta_unlock_spree": "Holiday Ball Marker",
        "m_meta_completionist": "Full Library",
        "m_meta_diverse": "Hatori Master Anchor",
        "m_meta_dominator": "Love Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060500",
        primary: "#da9234",
        secondary: "#8c5810",
        accent: "#e0a0c8",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/ouran-host-club.jpg",
    particleColor: "#f8c860",
    backgroundDim: 0.28,
    backgroundBlur: 14,
    particleTypes: {
        rose_petals: { label: "Rose Petals", maxCount: 20, defaultEnabled: true, defaultIntensity: 60 },
        sparkles: { label: "Elite Sparkles", maxCount: 18, defaultEnabled: true, defaultIntensity: 55 },
    },
    milestoneNames: {
  1: "Threadbare Generic Rank Spark",
  8: "Generic's Tarnished Omen",
  14: "Fractured Generic Rank",
  21: "Generic Rank Path",
  28: "Lowborn Legacy Myth",
  35: "Generic Rank Pulse",
  41: "Generic's Legacy Crest",
  48: "Humble Generic Mark",
  55: "Ragged Generic Rank Vow",
  61: "Generic's Faint Echo",
  68: "Lesser Generic Rank",
  75: "Generic Rank Zenith",
  81: "Doubtful Legacy Bloom",
  88: "Generic Rank Sigil",
  95: "Generic's Legacy Flame",
  102: "Really Cool Generic Spark",
  108: "Awakened Generic Rank Omen",
  115: "Generic's Resolute Seal",
  122: "Rising Generic Rank",
  128: "Generic Rank Myth",
  135: "Dauntless Legacy Pulse",
  142: "Generic Rank Crest",
  149: "Generic's Legacy Mark",
  155: "Fresh Generic Vow",
  162: "Valiant Generic Rank Echo",
  169: "Generic's Prime Crown",
  175: "Polished Generic Rank",
  182: "Generic Rank Bloom",
  189: "Stormlit Legacy Sigil",
  195: "Generic Rank Flame",
  202: "Generic's Legacy Spark",
  209: "Tempered Generic Omen",
  216: "Trusted Generic Rank Seal",
  222: "Generic's Steadfast Path",
  229: "Ironclad Generic Rank",
  236: "Veteran Legacy Pulse",
  242: "Core Legacy Crest",
  249: "Generic Rank Mark",
  256: "Generic's Legacy Vow",
  262: "Formidable Generic Echo",
  269: "Lucid Generic Rank Crown",
  276: "Generic's Ranked Zenith",
  283: "Fabled Generic Rank",
  289: "Grand Legacy Sigil",
  296: "Seasoned Legacy Flame",
  303: "Generic Rank Spark",
  309: "Generic's Legacy Omen",
  316: "Valorous Generic Seal",
  323: "Stalwart Generic Rank Path",
  330: "Generic's Commanding Myth",
  336: "Refined Generic Rank",
  343: "Unbroken Legacy Crest",
  350: "Blazing Legacy Mark",
  356: "Generic Rank Vow",
  363: "Generic's Legacy Echo",
  370: "Peerless Generic Crown",
  376: "Ardent Generic Rank Zenith",
  383: "Generic's Focused Bloom",
  390: "Vigilant Generic Rank",
  397: "Dominant Legacy Flame",
  403: "Elite Legacy Spark",
  410: "Generic Rank Omen",
  417: "Generic's Legacy Seal",
  423: "Sovereign Generic Path",
  430: "Regal Generic Rank Myth",
  437: "Generic's Crowned Pulse",
  444: "Mythborn Generic Rank",
  450: "Limitless Legacy Mark",
  457: "Radiant Legacy Vow",
  464: "Generic Rank Echo",
  470: "Generic's Legacy Crown",
  477: "Climactic Generic Zenith",
  484: "Epic Generic Rank Bloom",
  490: "Generic's Unreal Sigil",
  497: "Peak Generic Rank",
  504: "Supreme Legacy Spark",
  511: "Exalted Legacy Omen",
  517: "Generic Rank Seal",
  524: "Generic's Legacy Path",
  531: "Celestial Generic Myth",
  537: "Phantom Generic Rank Pulse",
  544: "Generic's Crimson Crest",
  551: "Silver Generic Rank",
  557: "Golden Legacy Vow",
  564: "Feral Legacy Echo",
  571: "Generic Rank Crown",
  578: "Generic's Legacy Zenith",
  584: "Dread Generic Bloom",
  591: "Luminous Generic Rank Sigil",
  598: "Generic's Thunderous Flame",
  604: "Ultraviolet Generic Rank",
  611: "Unleashed Legacy Omen",
  618: "Secret Legacy Seal",
  625: "Final Generic Path",
  631: "Generic's Legacy Myth",
  638: "Worldclass Generic Pulse",
  645: "Lawless Generic Rank Crest",
  651: "Generic's Chosen Mark",
  658: "Fearless Generic Rank",
  665: "Overdrive Legacy Echo",
  671: "Cinematic Legacy Crown",
  678: "Impossible Generic Zenith",
  685: "Generic's Legacy Bloom",
  692: "Canonized Generic Sigil",
  698: "Ascendant Generic Rank Flame",
  705: "Generic's Transfigured Spark",
  712: "Immortal Generic Rank",
  718: "Eclipsed Legacy Seal",
  725: "Astral Legacy Path",
  732: "Sublime Generic Myth",
  739: "Generic's Legacy Pulse",
  745: "Prismatic Generic Crest",
  752: "Abyssal Generic Rank Mark",
  759: "Generic's Unbound Vow",
  765: "Eternal Generic Rank",
  772: "Cosmic Legacy Crown",
  779: "Transcendent Legacy Zenith",
  785: "Perfected Generic Bloom",
  792: "Generic's Legacy Sigil",
  799: "Ultimate Generic Flame",
  806: "Mythic Generic Rank Spark",
  812: "Generic's Godlike Omen",
  819: "Canonical Generic Rank",
  826: "Reality-Bent Legacy Path",
  832: "Heavenly Legacy Myth",
  839: "Absolute Generic Pulse",
  846: "Untouchable Generic Crest",
  852: "Timeless Generic Mark",
  859: "Empyrean Generic Rank Vow",
  866: "Generic's Primordial Echo",
  873: "Omniscient Generic Rank",
  879: "Unfathomed Legacy Zenith",
  886: "Apocalyptic Legacy Bloom",
  893: "Seraphic Generic Sigil",
  899: "Omega Generic Flame",
  906: "Final Generic Spark",
  913: "Crowned Generic Rank Omen",
  920: "Generic's Mythic Seal",
  926: "Absolute Generic Rank",
  933: "Eternal Legacy Myth",
  940: "Cosmic Legacy Pulse",
  946: "Transcendent Generic Crest",
  953: "Perfected Generic Mark",
  960: "Definitive Generic Vow",
  966: "Ultimate Generic Rank Echo",
  973: "Generic's Infinite Crown",
  980: "Sovereign Generic Rank",
  987: "Celestial Legacy Bloom",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate Generic Rank"
},
}
