import { AnimeThemeConfig } from "./types"
import { GiVampireDracula, GiHolyGrail, GiCrossedSwords, GiWingedSword, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiDragonBreath } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const owariNoSeraphTheme: AnimeThemeConfig = {
    id: "owari-no-seraph",
    displayName: "Seraph of the End",
    description: "After a mysterious virus wipes out most of humanity, vampires emerge to enslave the survivors — orphan Yuichiro Hyakuya escapes and joins the Japanese Imperial Demon Army's Moon Demon Company to take revenge on the vampires.",
    fontFamily: "'Cinzel Decorative', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Cinzel+Decorative:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "195 162 240",
        "--color-brand-300": "162 118 225",
        "--color-brand-400": "128 75 208",
        "--color-brand-500": "95 38 185",
        "--color-brand-600": "68 16 150",
        "--color-brand-700": "45 4 112",
        "--color-brand-800": "26 0 72",
        "--color-brand-900": "12 0 36",
        "--color-brand-950": "4 0 16",
        "--brand": "95 38 185",
        "--background": "#020004",
        "--paper": "#07000f",
        "--color-gray-950": "2 0 4",
        "--color-gray-900": "6 1 10",
        "--color-gray-800": "12 3 18",
        "--color-gray-700": "22 6 32",
        "--color-gray-600": "38 12 54",
        "--color-gray-500": "62 22 86",
        "--color-gray-400": "98 45 130",
        "--color-gray-300": "142 82 175",
        "--color-gray-200": "185 130 212",
        "--color-gray-100": "215 172 235",
        "--color-gray-50": "238 215 250",
    },
    sidebarOverrides: {
        "home": { icon: GiWingedSword, label: "Shinoa Squad" },
        "schedule": { icon: GiAlarmClock, label: "Mission Schedule" },
        "manga": { icon: LuBookOpen, label: "Demon Army Files" },
        "lists": { icon: GiCrossedSwords, label: "Curse Registry" },
        "discover": { icon: GiBullseye, label: "New Enemies" },
        "torrent-list": { icon: GiVampireDracula, label: "Vampire Cache" },
        "debrid": { icon: GiHolyGrail, label: "Holy Store" },
        "unmatched": { icon: GiDragonBreath, label: "Lost Comrades" },
        "enmasse": { icon: GiResize, label: "Major Battles" },
        "scan-summaries": { icon: TbReportSearch, label: "Mission Reports" },
        "auto-downloader": { icon: LuRss, label: "Army Feed" },
        "community": { icon: GiWingedSword, label: "Moon Demon Company" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Battle Alerts" },
        "achievements": { icon: GiTrophy, label: "Seraph Trophies" },
        "milestones": { icon: LuFlag, label: "Vampire Goals" },
        "theme-manager": { icon: GiPalette, label: "Cursed Colors" },
        "extensions": { icon: BiExtension, label: "Curse Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Demon Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Yuu's Settings" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "Vampire Escape",
        "a_episode_counter": "Cursed Weapons Mark",
        "a_episode_titan": "Yamamoto Art Relic",
        "a_hours_invested": "Yuu Mika Bond Proof",
        "a_time_lord": "Demon Army Veteran",
        "a_anime_collector": "Curse Collection",
        "a_library_legend": "Seraph Archives",
        "a_first_complete": "Seraph Awakened",
        "a_hundred_club": "Hundred Battles",
        "a_first_day": "Daily Battle Seal",
        "a_first_rating": "Yamamoto Art Appraisal",
        "a_ten_thousand_min": "Vampire Reign Standard",
        "a_season_veteran": "Vampire Reign Library",
        "a_year_explorer": "Battle Alerts Map",
        "a_century_watcher": "Mika's Choice Ledger",
        "a_five_hundred_eps": "Demon Critic Dominion",
        "a_thousand_eps": "Curse Registry Record",
        "a_watching_ten": "Seraph Of The End Acclaim",
        "a_ptw_hoarder": "Seraph Archives Library",
        "a_dropped_honesty": "Seraph Of The End Summit",
        "a_five_thousand_eps": "Vampire World Warrant",
        "a_ten_completed": "Mika's Speed Afterglow",
        "a_fifty_completed": "Vampire Escape Ascension",
        "a_five_hundred_completed": "Seraph Of The End Clear",
        "a_mean_score_tracker": "Perfect Battle Verdict",
        "a_unique_studios": "Curse Registry Collection",
        "a_days_spent_watching": "Seraph Awakened Dominion",
        "a_all_status": "Guren Standard Testament",
        "a_first_favorite": "War Streak Cabinet",
        "a_favorites_collector": "Dawn Mission Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Night Battle Drive",
        "a_marathon_runner": "Yuu's March",
        "a_weekend_warrior": "Yamamoto Art Ordeal",
        "a_non_stop": "Battle Marathon Fever",
        "a_one_more_episode": "Kagami Master Mantle",
        "a_speed_run": "Mika's Speed",
        "a_double_feature": "Winter War Crown",
        "a_triple_threat": "Seraph Demons Record",
        "a_five_a_day": "Decade Fan Accord",
        "a_back_to_back": "Mika's Brother Surge",
        "a_seasonal_binge": "Yamamoto Art Cascade",
        "a_cour_crusher": "Seraph Awakened Ordeal",
        "a_half_day_watch": "Cursed Weapons Crown",
        "a_full_day_watch": "Endless War Pinnacle",
        "a_power_weekend": "Daily Battle Run",
        "a_binge_king": "Battle Marathon",
        "a_no_sleep": "Night Patrol",
        "a_entire_season": "Shinoa Squad Library",
        "a_seven_day_challenge": "Endless War Mark",
        "a_hundred_day_binge": "Daily Battle Surge",
        "a_genre_binge": "Soldier Resolve Binge",
        "a_studio_binge": "Cursed Weapons Fever",
        "a_season_sweep": "Yuichiro Hyakuya Codex",
        "a_forty_eight_hour": "Truth Depth Overture",
        "a_ep_counter_day": "Mika's Speed Aegis",
        "a_multi_series_binge": "Seraph Archives Streak",
        "a_midnight_binge": "Kagami Master Cascade",
        "a_new_year_binge": "Night Patrol Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Yuu vs Ferid",
        "a_genre_adventure": "Nagoya Operation",
        "a_genre_comedy": "Shinoa's Teasing",
        "a_genre_drama": "Mika's Choice",
        "a_genre_fantasy": "Cursed Weapons",
        "a_genre_horror": "Vampire World",
        "a_genre_mystery": "Seraph Trophies Mystery",
        "a_genre_romance": "Yuu Mika Bond",
        "a_genre_scifi": "Apocalypse Virus",
        "a_genre_sol": "Vampire World Slice",
        "a_genre_sports": "Truth Depth Sports",
        "a_genre_supernatural": "Seraph Demons",
        "a_genre_thriller": "Vampire Escape Thriller",
        "a_genre_mecha": "None Here",
        "a_genre_music": "Vampire Reign Music",
        "a_genre_psychological": "Manipulation Web",
        "a_genre_ecchi": "Night Battle Ecchi",
        "a_genre_mahou_shoujo": "Seraph Demons Magic Shoujo",
        "a_tag_isekai": "Moon Demon Company Isekai",
        "a_tag_harem": "Yuu Mika Harem",
        "a_tag_bl": "Truth Depth Bl",
        "a_tag_gl": "Kagami Master Gl",
        "a_tag_historical": "All Arcs Historical",
        "a_tag_military": "Demon Critic Military",
        "a_tag_school": "Seraph Archives School",
        "a_tag_martial_arts": "Endless War Martial Arts",
        "a_tag_vampire": "Seraph Demons Vampire",
        "a_tag_samurai": "Curse Registry Samurai",
        "a_tag_space": "Mika Bond Space",
        "a_tag_parody": "Kagami Fan Parody",
        "a_tag_idol": "Truth Depth Idol",
        "a_tag_post_apocalyptic": "Kagami Classic Post Apocalyptic",
        "a_tag_cyberpunk": "Battle Marathon Cyberpunk",
        "a_tag_shounen": "Kagami Classic Shounen",
        "a_tag_seinen": "Yuu's March Seinen",
        "a_tag_shoujo": "Yuu's March Shoujo",
        "a_tag_josei": "Mika's Speed Josei",
        "a_tag_survival": "Dawn Mission Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "All Seasons",
        "a_mega_completionist": "Kagami Master",
        "a_completion_rate_50": "Seraph Demons Return",
        "a_completion_rate_75": "Vampire Escape Crown",
        "a_completion_rate_90": "Mika's Speed Resolution",
        "a_no_drop": "Seraph Trophies Decree",
        "a_long_runner_complete": "Daily Battle Clear",
        "a_sequel_chain": "Vampire Reign",
        "a_clean_list": "Yuichiro Hyakuya Relic",
        "a_from_ptw": "Kagami Fan Index",
        "a_rewatch_master": "Perfect Battle Return",
        "a_short_complete": "Seraph Expert Endgame",
        "a_same_day_start_finish": "Orphan Soldier Pinnacle",
        "a_revival": "Mika's Choice Insignia",
        "a_zero_to_hero": "Orphan to Soldier",
        "a_five_genre_complete": "Seraph Expert A Five Genre",
        "a_full_franchise": "Seraph Archives Chronicle",
        "a_batch_complete": "Yamamoto Art Crown",
        "a_paused_to_done": "Mika's Speed Aegis Aegis",
        "a_completion_spree": "Major Battles Triumph",
        "a_multi_rewatch": "Major Battles Triumph Triumph",
        "a_dropped_recovery": "Cursed Weapons Conquest",
        "a_ten_perfect_scores": "Daily Battle Acclaim",
        "a_seasonal_clear": "Seraph Awakened Codex",
        "a_complete_genre_span": "Demon Army A Complete Genre",
        "a_monthly_completions": "Perfect Battle Afterglow",
        "a_yearly_completions": "Guren Standard Epilogue",
        "a_rapid_complete": "Endless War Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Mika's Brother",
        "a_studio_devotee": "Seraph Trophies Treasury",
        "a_rewatcher": "Apocalypse Return",
        "a_triple_rewatch": "Soldier Resolve Coda",
        "a_annual_tradition": "Endless War Proof",
        "a_director_fan": "Yuichiro Hyakuya Trial",
        "a_voice_actor_fan": "Cursed Weapons Crown Crown",
        "a_ost_lover": "Seraph Archives Seal",
        "a_source_reader": "Battle Alerts Cabinet",
        "a_waiting_weekly": "Seraph Trophies Clock",
        "a_childhood_revisit": "Lost Comrades Seal",
        "a_saga_tracker": "Mika Bond Standard",
        "a_genre_loyalty": "Vampire World Loyalty",
        "a_decade_watcher": "Decade Fan",
        "a_adaptation_hunter": "Kagami Fan Trial",
        "a_original_anime_fan": "Army Critic Testament",
        "a_long_commitment": "Endless War Mark Mark",
        "a_perfect_attendance": "Seraph Of The End Standard",
        "a_favorite_studio_5": "Kagami Classic Library",
        "a_complete_catalog": "Dawn Mission Seal",
        "a_franchise_collector": "Kagami Classic Archive",
        "a_airing_follower": "Lost Comrades Signal",
        "a_genre_master": "Yuichiro Hyakuya Master",
        "a_staff_follower": "Kagami Classic Oath",
        "a_multi_season_fan": "All Arcs Hoard",
        "a_format_diversity": "Seraph Demons Cache",
        "a_year_dedication": "Yamamoto Art Tenure",
        "a_season_dedication": "Demon Critic Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Soldier Resolve Explorer",
        "a_studio_hopper": "Perfect Battle Collection",
        "a_tag_explorer": "Yamamoto Art Explorer",
        "a_decade_hopper": "Seraph Archives Chronicle Chronicle",
        "a_hidden_gem": "Hidden Episode",
        "a_popular_taste": "Truth Depth Decree",
        "a_retro_appreciator": "Dawn Mission Aegis",
        "a_modern_viewer": "Orphan Soldier Pinnacle Pinnacle",
        "a_cross_demographic": "Night Battle Pinnacle",
        "a_underdog_fan": "Demon Army Trial",
        "a_variety_week": "Kagami Classic Horizon",
        "a_foreign_cinema": "Kagami Master Expedition",
        "a_classic_connoisseur": "2013 Fan",
        "a_every_season": "Lost Comrades Archive",
        "a_award_winner": "Vampire Reign Insignia",
        "a_niche_explorer": "Yuu's March Horizon",
        "a_global_anime": "Seraph Expert Crown",
        "a_cult_classic": "Kagami Classic",
        "a_random_pick": "Truth Depth Decree Decree",
        "a_new_genre_month": "Seraph Of The End A",
        "a_seasonal_completionist": "Mika's Choice Summit",
        "a_unpopular_opinion": "War Streak Standard",
        "a_top_rated_viewer": "Decade Fan Seal",
        "a_source_variety": "Seraph Awakened Storehouse",
        "a_low_score_brave": "Battle Marathon Measure",
        "a_upcoming_watcher": "Decade Fan Seal Seal",
        "a_short_series_explorer": "Kagami Master Expedition Expedition",
        "a_long_series_explorer": "Winter War Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Night Battle",
        "a_early_bird": "Dawn Mission",
        "a_lunch_break": "Japanese Imperial Demon Trial",
        "a_golden_hour": "Yuu's Resolve Tenure",
        "a_four_am_club": "Major Battles Gathering",
        "a_witching_hour": "Vampire Escape Tenure",
        "a_new_year_watch": "Yamamoto Art Season",
        "a_midnight_premiere": "Night Patrol Devotion",
        "a_all_hours": "Mika's Choice Seal",
        "a_dawn_warrior": "Truth Depth Aegis",
        "a_afternoon_delight": "Yuu Mika Bond Proof Proof",
        "a_prime_time": "Vampire Reign Insignia Insignia",
        "a_workday_watcher": "Night Battle Pinnacle Pinnacle",
        "a_sunday_marathon": "Daily Battle Momentum",
        "a_rainy_day": "Vampire Escape Relic",
        "a_morning_routine": "All Arcs Promise",
        "a_night_shift": "Seraph Demons Aegis",
        "a_twilight_zone": "Shinoa Squad Ledger",
        "a_seasonal_premier": "Seraph Trophies Cabinet",
        "a_clock_collector": "Major Battles Repository",
        "a_weekend_binge_hours": "Yuu's March Streak",
        "a_late_night_regular": "Guren Standard Dominion",
        "a_sunrise_watcher": "Yuichiro Hyakuya Relic Relic",
        "a_holiday_watcher": "Decade Fan Pact",
        "a_every_day_of_week": "Mika's Brother Ledger",
        "a_monthly_hours": "Truth Depth Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Mika's Speed Record",
        "a_party_host": "Seraph Demons Record Record",
        "a_social_butterfly": "Battle Alerts Company",
        "a_group_binge": "Curse Registry Sprint",
        "a_party_regular": "Shinoa Squad Chronicle",
        "a_sync_viewer": "Major Battles Standard",
        "a_commentator": "Dawn Mission Record",
        "a_party_marathon": "Soldier Resolve Vigil",
        "a_full_house": "Demon Critic Trial",
        "a_community_pillar": "Guren Standard Alliance",
        "a_watch_party_streak": "Dawn Mission Vigil",
        "a_diverse_party": "All Arcs Seal",
        "a_late_night_party": "Guren Standard Testament Testament",
        "a_party_veteran": "Demon Critic Testament",
        "a_genre_party": "Kagami Master Party",
        "a_weekly_party": "Major Battles Calendar",
        "a_silent_viewer": "Army Critic Mantle",
        "a_recommendation_giver": "Yuu's March Network",
        "a_party_completionist": "Mika Bond Coda",
        "a_social_scorer": "Yuichiro Hyakuya Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Winter War Proof",
        "a_fibonacci": "Yamamoto Art Dominion",
        "a_palindrome_day": "Yamamoto Art Relic Relic",
        "a_binary_day": "Vampire World Mark",
        "a_full_moon": "Lost Comrades Insignia",
        "a_leap_year": "Seraph Expert Devotion",
        "a_time_traveler": "Seraph Trophies Record",
        "a_genre_clash": "Soldier Resolve Clash",
        "a_triple_seven": "Yamamoto Art Testament",
        "a_thousand_complete": "Army Critic Epilogue",
        "a_pi_episodes": "Night Battle Crown",
        "a_synchronicity": "Demon Army Anchor",
        "a_world_record": "Cursed Weapons Warrant",
        "a_nice": "Vampire Reign Chronicle",
        "a_power_level": "Army Critic Testament Testament",
        "a_answer_42": "Truth Depth Standard",
        "a_square_number": "Soldier Resolve Decree",
        "a_prime_count": "Vampire Reign Seal",
        "a_matching_date": "Demon Army Mantle",
        "a_century_episode": "Night Battle Mark",
        "a_double_digits": "Vampire Escape Testament",
        "a_one_two_three": "Seraph Expert Crown Crown",
        "a_lucky_seven": "Endless War Crown",
        "a_all_tens": "Battle Marathon Criterion",
        "a_exact_hundred_eps": "Mika Bond Legend",
        "a_year_match_count": "Seraph Trophies Yearlong",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Yuu's March Ledger",
        "a_movie_buff": "Cursed Weapons Mark Mark",
        "a_ova_hunter": "Mika Bond Standard Standard",
        "a_ona_explorer": "Demon Army Secret",
        "a_special_watcher": "Vampire Escape Relic Relic",
        "a_short_king": "Yuu Mika Crown",
        "a_variety_pack": "Cursed Weapons Inquiry",
        "a_film_festival": "Decade Fan Chronicle",
        "a_music_video": "All Arcs Chronicle",
        "a_tv_short": "Soldier Resolve Record",
        "a_movie_marathon": "Soldier Resolve Gauntlet",
        "a_double_length": "Winter War Crown Crown",
        "a_anthology": "Seraph Demons Aegis Aegis",
        "a_mini_series": "War Streak Decree",
        "a_theatrical": "Kagami Classic Accord",
        "a_format_master": "Major Battles Vault",
        "a_long_movie": "Mika's Choice Insignia Insignia",
        "a_back_catalog": "Dawn Mission Standard",
        "a_cm_watcher": "Moon Demon Company Aegis",
        "a_pv_collector": "Demon Army Storehouse",
        "a_format_balance": "Major Battles Vault Vault",
        "a_episodic_master": "Moon Demon Company Standard",
        "a_sequel_movie": "Seraph Expert Pinnacle",
        "a_recap_watcher": "Japanese Imperial Demon Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Battle",
        "a_mega_streak": "Endless War",
        "a_weekly_warrior": "Demon Critic Season",
        "a_monthly_watcher": "Night Patrol Calendar",
        "a_comeback": "Battle Alerts Decree",
        "a_weekend_streak": "Battle Marathon Passage",
        "a_no_zero_days": "Vampire World Warrant Warrant",
        "a_iron_will": "Yuu's Resolve",
        "a_habit_formed": "Mika's Brother Banner",
        "a_consistent_pace": "Winter War Measure",
        "a_year_long": "Year of Apocalypse",
        "a_double_streak": "Yuichiro Hyakuya Watch",
        "a_streak_recovery": "Army Critic Season",
        "a_daily_minimum": "Night Patrol Focus",
        "a_winter_streak": "Kagami Master Watch",
        "a_summer_streak": "Vampire Escape Resolve",
        "a_morning_streak": "Dawn Mission Clock",
        "a_night_streak": "Mika's Brother Constancy",
        "a_unbreakable": "Yuu Mika Proof",
        "a_eternal_flame": "Perfect Battle Standard",
        "a_completion_streak": "Mika Bond Return",
        "a_rating_streak": "Yamamoto Art Balance",
        "a_multi_ep_streak": "Cursed Weapons Ritual",
        "a_genre_streak": "Yamamoto Art Streak",
        "a_studio_streak": "Battle Alerts Cabinet Cabinet",
        "a_perfect_week": "Demon Army Relic",

        // ── ANIME SCORING ──
        "a_critic": "Demon Critic",
        "a_perfect_ten": "Perfect Battle",
        "a_harsh_critic": "Guren Standard",
        "a_fair_judge": "Guren Standard Balance",
        "a_generous_spirit": "Night Patrol Pinnacle",
        "a_score_all": "Yuu Mika Bond Criterion",
        "a_wide_range": "Vampire Reign Ledger",
        "a_controversial": "Dawn Mission Decree",
        "a_consistent_scorer": "Seraph Trophies Verdict",
        "a_score_sniper": "Seraph Expert Score",
        "a_evolving_taste": "Yuichiro Hyakuya Testament",
        "a_bell_curve": "Seraph Of The End Insignia",
        "a_picky_watcher": "Army Critic Warrant",
        "a_100_rated": "Major Battles Warrant",
        "a_500_rated": "Yuu Mika Pinnacle",
        "a_mediocre_majority": "Demon Army Canon",
        "a_rating_spree": "Dawn Mission Review",
        "a_score_variance": "Battle Marathon Score",
        "a_masterpiece_hunter": "Dawn Mission Banner",
        "a_contrarian": "Soldier Resolve Record Record",
        "a_optimist": "All Arcs Ledger",
        "a_score_distributor": "Japanese Imperial Demon Appraisal",
        "a_genre_critic": "Winter War Critic",
        "a_mean_above_8": "Endless War Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Battle",
        "a_valentines_weeb": "Kagami Classic Vow",
        "a_pi_day": "Guren Standard Trial",
        "a_april_fools": "Seraph Expert Devotion Devotion",
        "a_international_anime_day": "Mika's Choice Record",
        "a_star_wars_day": "Daily Battle Chronicle",
        "a_summer_solstice": "Vampire World Calendar",
        "a_tanabata": "Orphan Soldier Focus",
        "a_friday_13th": "Japanese Imperial Demon Relic",
        "a_halloween_spirit": "Yuu's March Vow",
        "a_thanksgiving_binge": "Shinoa Squad Run",
        "a_christmas_special": "Winter War",
        "a_new_years_eve": "Endless War Pilgrimage",
        "a_birthday_watch": "Seraph Of The End Vow",
        "a_holiday_marathon": "Curse Registry Overture",
        "a_independence_day": "Perfect Battle Banner",
        "a_culture_day": "Seraph Archives Insignia",
        "a_spring_equinox": "Curse Registry Decree",
        "a_earth_day": "Cursed Weapons Mantle",
        "a_labor_day": "Yuu's March Seal",
        "a_winter_solstice": "Night Battle Pilgrimage",
        "a_anime_birthday": "Cursed Weapons Pilgrimage",
        "a_every_holiday": "Kagami Fan Resolve",
        "a_consecutive_holidays": "Vampire Escape Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Battle Alerts Rank",
        "a_meta_collector": "Seraph Archives Hoard",
        "a_meta_category_starter": "Night Patrol Badge",
        "a_meta_tier_climber": "Seraph Archives Glyph",
        "a_meta_tier_max": "Seraph Legend",
        "a_meta_xp_earner": "Japanese Imperial Demon Emblem",
        "a_meta_difficulty_easy": "Guren Standard Mechanism",
        "a_meta_difficulty_hard": "Decade Fan Writ",
        "a_meta_unlock_spree": "Demon Critic Panel",
        "a_meta_completionist": "All Arcs",
        "a_meta_diverse": "Yamamoto Art Emblem",
        "a_meta_dominator": "Shinoa Squad Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Battle",
        "m_chapter_counter": "Major Battles Pinnacle",
        "m_chapter_titan": "Seraph Awakened Relic",
        "m_reading_hours": "Japanese Imperial Demon Relic Relic",
        "m_reading_time_lord": "Mika's Choice Record Record",
        "m_manga_collector": "Demon Critic Ledger",
        "m_library_legend": "Seraph Archives Reliquary",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "Kagami Classic Seal",
        "m_first_rating": "Japanese Imperial Demon Eye",
        "m_ten_thousand_pages": "Kagami Classic Gauge",
        "m_volume_collector": "Army Critic Storehouse",
        "m_year_explorer": "Truth Depth Quest",
        "m_century_reader": "Kagami Master Dominion",
        "m_five_hundred_ch": "Vampire Reign Legend",
        "m_thousand_ch": "Yuichiro Hyakuya Legend",
        "m_reading_ten": "Kagami Master Appraisal",
        "m_ptr_hoarder": "Yuichiro Hyakuya Index",
        "m_dropped_honesty": "Seraph Archives Summit",
        "m_season_reader": "Dawn Mission Treasury",
        "m_active_reader": "Vampire Escape Trial",
        "m_five_thousand_ch": "Soldier Resolve Standard",
        "m_ten_completed": "Soldier Resolve Resolution",
        "m_fifty_completed": "Yuichiro Hyakuya Harvest",
        "m_five_hundred_completed": "Mika's Brother Legacy",
        "m_mean_score_tracker": "Seraph Trophies Audit",
        "m_unique_authors": "Cursed Weapons Reserve",
        "m_all_status": "Vampire Escape Testament Testament",
        "m_first_favorite": "Mika Bond Cache",
        "m_favorites_collector": "Battle Alerts Shelf",
        "m_days_spent_reading": "Night Battle Relic",

        // ── MANGA BINGE ──
        "m_binge_reader": "Seraph Of The End Streak",
        "m_marathon_reader": "Guren Standard Rush",
        "m_weekend_reader": "Lost Comrades Run",
        "m_non_stop_reading": "Mika Bond Gauntlet",
        "m_one_more_chapter": "Japanese Imperial Demon Testament Testament",
        "m_speed_read": "Vampire World Drive",
        "m_double_story": "Curse Registry Banner",
        "m_triple_read": "Perfect Battle Record",
        "m_five_a_day": "All Arcs Insignia",
        "m_chapter_chain": "Seraph Archives Accord",
        "m_volume_binge": "Battle Marathon Drive",
        "m_power_reader": "Daily Battle Seal Seal",
        "m_half_day_read": "Battle Alerts Aegis",
        "m_full_day_read": "Moon Demon Company Aegis Aegis",
        "m_power_weekend": "Kagami Classic Streak",
        "m_binge_king": "Battle Marathon",
        "m_no_sleep_read": "Kagami Master Rush",
        "m_full_series_rush": "Guren Standard Cascade",
        "m_seven_day_challenge": "Orphan Soldier Warrant",
        "m_hundred_day_read": "Yamamoto Art Legend",
        "m_volume_rush": "Mika's Speed Gauntlet",
        "m_series_sweep": "Kagami Fan Trial Trial",
        "m_genre_binge": "Moon Demon Company Binge",
        "m_author_binge": "Lost Comrades Surge",
        "m_chapter_counter_day": "Shinoa Squad Ledger Ledger",
        "m_multi_series_binge": "Vampire Reign Charge",
        "m_midnight_binge": "Yuichiro Hyakuya Tempest",
        "m_new_year_binge": "Cursed Weapons Passage",
        "m_forty_eight_hour": "Seraph Trophies Rally",
        "m_oneshot_binge": "Vampire World Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Battle Chapter",
        "m_genre_adventure": "Nagoya Chapter",
        "m_genre_comedy": "Battle Alerts Comedy",
        "m_genre_drama": "Mika Chapter",
        "m_genre_fantasy": "Curse Chapter",
        "m_genre_horror": "Vampire Chapter",
        "m_genre_mystery": "Soldier Resolve Mystery",
        "m_genre_romance": "Bond Chapter",
        "m_genre_scifi": "Virus Chapter",
        "m_genre_sol": "Major Battles Slice",
        "m_genre_sports": "Mika's Speed Sports",
        "m_genre_supernatural": "Seraph Chapter",
        "m_genre_thriller": "Demon Army Thriller",
        "m_genre_psychological": "Truth Depth",
        "m_genre_isekai": "Demon Critic Isekai",
        "m_genre_shounen": "Yuu's Resolve Shounen",
        "m_genre_ecchi": "Winter War Ecchi",
        "m_genre_mahou_shoujo": "Battle Alerts Magic Shoujo",
        "m_genre_mecha": "Army Critic Mecha",
        "m_genre_music": "Yuu's March Music",
        "m_tag_isekai_new": "Japanese Imperial Demon Isekai New",
        "m_tag_harem": "Yuu Mika Bond Harem",
        "m_tag_bl": "War Streak Bl",
        "m_tag_gl": "Yuichiro Hyakuya Gl",
        "m_tag_historical": "Vampire Reign Historical",
        "m_tag_military": "Yuu's Resolve Military",
        "m_tag_school": "Kagami Classic School",
        "m_tag_martial_arts": "Major Battles Martial Arts",
        "m_tag_vampire": "Mika's Speed Vampire",
        "m_tag_samurai": "Seraph Demons Samurai",
        "m_tag_space": "War Streak Space",
        "m_tag_parody": "Army Critic Parody",
        "m_tag_idol": "War Streak Idol",
        "m_tag_post_apocalyptic": "Seraph Archives Post Apocalyptic",
        "m_tag_cyberpunk": "Yuu Mika Bond Cyberpunk",
        "m_tag_shoujo": "Decade Fan Shoujo",
        "m_tag_survival": "Battle Alerts Survival",
        "m_tag_cooking": "Seraph Of The End Cooking",
        "m_tag_medical": "Vampire Escape Medical",
        "m_tag_villainess": "Lost Comrades Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Seraph Expert",
        "m_completion_rate_50": "War Streak Return",
        "m_completion_rate_75": "Demon Army Ascension",
        "m_completion_rate_90": "Perfect Battle Resolution",
        "m_no_drop": "Mika Bond Decree",
        "m_long_runner_complete": "Shinoa Squad Clear",
        "m_sequel_chain": "Yuu's March Seal Seal",
        "m_clean_list": "Seraph Awakened Relic Relic",
        "m_from_ptr": "Decade Fan Watchlist",
        "m_reread_master": "Guren Standard Trial Trial",
        "m_oneshot_complete": "Guren Standard Ascension",
        "m_same_day_start_finish": "Endless War Crown Crown",
        "m_revival": "Shinoa Squad Accord",
        "m_zero_to_hundred": "Soldier Resolve Banner",
        "m_five_genre_complete": "Vampire World M Five Genre",
        "m_full_collection": "Endless War Proof Proof",
        "m_batch_complete": "Seraph Trophies Summit",
        "m_paused_to_done": "Perfect Battle Standard Standard",
        "m_completion_spree": "Yuu Mika Triumph",
        "m_format_completionist": "Guren Standard Completion",
        "m_catch_up": "Mika's Choice Chronicle",
        "m_multi_reread": "Mika Bond Banner",
        "m_dropped_recovery": "Winter War Conquest",
        "m_ten_perfect_scores": "Lost Comrades Judgment",
        "m_complete_genre_span": "Demon Critic M Complete Genre",
        "m_monthly_completions": "Moon Demon Company Return",
        "m_yearly_completions": "Demon Critic Epilogue",
        "m_rapid_complete": "Orphan Soldier Finale",
        "m_author_complete": "Kagami Classic Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Devoted Reader",
        "m_mangaka_lover": "Kagami Fan",
        "m_rereader": "Apocalypse Return",
        "m_triple_reread": "Yamamoto Art Testament Testament",
        "m_annual_reread": "Soldier Resolve Banner Banner",
        "m_publisher_fan": "Yuu Mika Mark",
        "m_artist_fan": "Yuu's March Insignia",
        "m_adaptation_compare": "Demon Army Pinnacle",
        "m_source_material_fan": "Novel First",
        "m_waiting_weekly": "Seraph Demons Streak",
        "m_classic_reader": "Army Critic Lantern",
        "m_saga_reader": "Seraph Archives Decree",
        "m_genre_loyalty": "Winter War Loyalty",
        "m_decade_reader": "Battle Marathon Warrant",
        "m_ln_adaptation": "Battle Marathon Mark",
        "m_original_work": "Mika's Speed Standard",
        "m_long_commitment": "Winter War Mark",
        "m_up_to_date": "Cursed Weapons Warrant Warrant",
        "m_favorite_mangaka": "Truth Depth Treasury",
        "m_complete_portfolio": "Yuu Mika Triumph Triumph",
        "m_franchise_collector": "Mika's Choice Archive",
        "m_serialization_follower": "Truth Depth Handshake",
        "m_genre_master": "Seraph Awakened Master",
        "m_multi_series_author": "Seraph Archives Insignia Insignia",
        "m_format_diversity": "Mika's Speed Shelf",
        "m_year_dedication": "Kagami Master Tenure",
        "m_ongoing_follower": "Battle Marathon Fellowship",
        "m_genre_loyalty_50": "Yuichiro Hyakuya Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Curse Registry Explorer",
        "m_publisher_hopper": "Yuu Mika Mantle",
        "m_tag_explorer": "Kagami Fan Explorer",
        "m_decade_hopper": "Decade Fan Chronicle Chronicle",
        "m_hidden_gem": "Hidden Volume",
        "m_popular_taste": "Seraph Trophies Record Record",
        "m_retro_reader": "Seraph Trophies Accord",
        "m_modern_reader": "Vampire Reign Seal Seal",
        "m_cross_demographic": "Night Patrol Crown",
        "m_underdog_fan": "Seraph Trophies Accord Accord",
        "m_variety_week": "Yuu's March Horizon Horizon",
        "m_manhwa_reader": "Seraph Expert Proof",
        "m_manhua_reader": "Army Critic Mantle Mantle",
        "m_classic_connoisseur": "Mika's Brother Glimpse",
        "m_award_winner": "Kagami Master Warrant",
        "m_niche_explorer": "Seraph Of The End Horizon",
        "m_world_manga": "Mika's Choice Chronicle Chronicle",
        "m_cult_classic": "Kagami Classic",
        "m_random_pick": "Seraph Trophies Standard",
        "m_new_genre_month": "Mika's Choice M New Genre",
        "m_year_completionist": "Major Battles Fulfillment",
        "m_unpopular_opinion": "Cursed Weapons Trial",
        "m_top_rated_reader": "Seraph Of The End Record",
        "m_source_variety": "Army Critic Catalogue",
        "m_low_score_brave": "Major Battles Score",
        "m_short_manga_explorer": "Vampire Reign Compass",
        "m_long_manga_explorer": "Soldier Resolve Survey",
        "m_serialization_explorer": "Demon Army Road",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "War Streak Ledger",
        "m_commute_reader": "Vampire Escape Tenure Tenure",
        "m_four_am_club": "Yuu Mika Fellowship",
        "m_new_year_read": "Yuu's March Pact",
        "m_all_hours": "Decade Fan Accord Accord",
        "m_prime_time_reader": "Mika's Speed Banner",
        "m_workday_reader": "Shinoa Squad Accord Accord",
        "m_sunday_read": "War Streak Standard Standard",
        "m_morning_routine": "Shinoa Squad Discipline",
        "m_night_shift_reader": "Kagami Classic Accord Accord",
        "m_seasonal_premier_read": "Army Critic Seasonal",
        "m_clock_collector": "Night Battle Reserve",
        "m_late_night_horror": "Vampire World Mark Mark",
        "m_afternoon_reader": "Kagami Master Mantle Mantle",
        "m_golden_hour_reader": "Yamamoto Art Observance",
        "m_dawn_reader": "Kagami Fan Mantle",
        "m_twilight_reader": "Battle Marathon Crown",
        "m_midnight_start": "Mika's Speed Routine",
        "m_weekend_binge_hours": "Lost Comrades Momentum",
        "m_late_night_regular": "War Streak Accord",
        "m_sunrise_reader": "Yuu Mika Bond Mantle",
        "m_every_day_of_week": "Army Critic Warrant Warrant",
        "m_monthly_hours": "Curse Registry Vigil",
        "m_bedtime_reader": "Major Battles Warrant Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Yamamoto Art",
        "m_webtoon_reader": "Battle Marathon Mark Mark",
        "m_full_color": "Yuu's March Accord",
        "m_doujin_reader": "Perfect Battle Record Record",
        "m_anthology_reader": "Lost Comrades Accord",
        "m_adaptation_reader": "Seraph Trophies Banner",
        "m_longstrip_reader": "Yamamoto Art Trial",
        "m_4koma_reader": "Seraph Demons Ledger",
        "m_oneshot_reader": "Demon Critic Mantle",
        "m_format_variety": "Yuu Mika Gallery",
        "m_light_novel_reader": "Decade Fan Insignia",
        "m_novel_reader": "Major Battles Crown",
        "m_visual_storyteller": "Kagami Master Testament",
        "m_colored_classic": "Dawn Mission Survey",
        "m_webcomic_fan": "Mika's Brother Insignia",
        "m_manga_to_anime": "Manga Adapted",
        "m_seinen_reader": "Winter War Pinnacle",
        "m_josei_reader": "Yuu Mika Bond Pinnacle",
        "m_award_winning_art": "Yuu's Resolve Relic",
        "m_debut_work": "Yuu's Resolve Dominion",
        "m_vertical_scroll": "Seraph Archives Decree Decree",
        "m_traditional_format": "Seraph Of The End Hoard",
        "m_cross_media": "Vampire Reign Accord",
        "m_spinoff_reader": "Mika's Choice Accord",
        "m_remake_reader": "Guren Standard Pinnacle",
        "m_collaboration_reader": "Mika's Brother Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "War Streak",
        "m_weekly_warrior": "Demon Army Season",
        "m_monthly_reader": "All Arcs Discipline",
        "m_comeback": "Soldier Resolve Standard Standard",
        "m_weekend_streak": "Yuu Mika Bond Fever",
        "m_no_zero_days": "Seraph Expert Proof Proof",
        "m_iron_will": "Soldier Resolve",
        "m_habit_formed": "Night Patrol Crown Crown",
        "m_consistent_pace": "Endless War Scrutiny Scrutiny",
        "m_year_long": "Year Reading",
        "m_double_streak": "Demon Critic Resolve",
        "m_streak_recovery": "Seraph Awakened Resolve",
        "m_daily_minimum": "Night Battle Focus",
        "m_winter_streak": "Yamamoto Art Observance Observance",
        "m_summer_streak": "Yuu's Resolve Observance",
        "m_morning_streak": "Curse Registry Clock",
        "m_night_streak": "Seraph Of The End Discipline",
        "m_unbreakable": "Yuu Mika Bond Warrant",
        "m_eternal_flame": "Battle Alerts Record",
        "m_chapter_a_day": "War Streak Ledger Ledger",
        "m_genre_streak": "Kagami Fan Streak",
        "m_completion_streak": "Seraph Trophies Return",
        "m_rating_streak": "Kagami Fan Appraisal",
        "m_multi_ch_streak": "Demon Army Tenure",
        "m_author_streak": "Night Battle Calendar",
        "m_perfect_week_manga": "Mika's Choice Accord Accord",
        "m_diverse_streak": "Mika Bond Streak",

        // ── MANGA SCORING ──
        "m_critic": "Army Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_harsh_critic": "Decade Fan Scale",
        "m_fair_judge": "Japanese Imperial Demon Eye Eye",
        "m_generous_spirit": "Lost Comrades Decree",
        "m_score_all": "Battle Marathon Reckoning",
        "m_wide_range": "All Arcs Ledger Ledger",
        "m_controversial": "Moon Demon Company Standard Standard",
        "m_consistent_scorer": "Perfect Battle Grade",
        "m_score_sniper": "Cursed Weapons Reckoning",
        "m_evolving_taste": "Demon Critic Trial Trial",
        "m_bell_curve": "All Arcs Accord",
        "m_picky_reader": "Mika Bond Ledger",
        "m_100_rated": "All Arcs Standard",
        "m_500_rated": "Kagami Classic Aegis",
        "m_mediocre_majority": "Demon Critic Canon",
        "m_rating_spree": "Curse Registry Verdict",
        "m_score_variance": "Major Battles Measure",
        "m_binge_rater": "Night Battle Passage",
        "m_reread_rerate": "Dawn Mission Banner Banner",
        "m_masterpiece_hunter": "Moon Demon Company Banner",
        "m_contrarian": "Seraph Trophies Aegis",
        "m_optimist": "Vampire Reign Accord Accord",
        "m_score_distributor": "Demon Army Balance",
        "m_genre_critic": "Night Battle Critic",
        "m_mean_above_8": "Major Battles Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Kagami Master Season",
        "m_valentines_read": "Kagami Fan Observance",
        "m_pi_day": "Demon Critic Testament Testament",
        "m_april_fools": "Cursed Weapons Devotion",
        "m_international_manga_day": "Decade Fan Aegis",
        "m_free_comic_day": "Lost Comrades Chronicle",
        "m_summer_solstice": "Orphan Soldier Focus Focus",
        "m_tanabata": "Endless War Tanabata",
        "m_friday_13th": "Guren Standard Dominion Dominion",
        "m_halloween_read": "Vampire World Halloween",
        "m_thanksgiving_binge": "Mika's Choice Charge",
        "m_christmas_read": "Shinoa Squad Pact",
        "m_new_years_eve": "Orphan Soldier Pilgrimage",
        "m_birthday_read": "Winter War Focus",
        "m_holiday_marathon": "Truth Depth Rally",
        "m_independence_day": "Seraph Trophies Aegis Aegis",
        "m_culture_day": "Kagami Classic Seal Seal",
        "m_spring_equinox": "Vampire World Dominion",
        "m_earth_day": "Winter War Trial",
        "m_labor_day": "Shinoa Squad Seal",
        "m_winter_solstice": "Night Patrol Focus Focus",
        "m_manga_birthday": "Endless War Ritual",
        "m_every_holiday_reader": "Seraph Awakened Watch",
        "m_consecutive_holidays": "Guren Standard Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Daily Battle Aegis",
        "m_fibonacci": "Vampire Escape Dominion",
        "m_palindrome_day": "Demon Critic Relic",
        "m_binary_day": "Night Patrol Proof",
        "m_full_moon_read": "Yuu Mika Bond Crown",
        "m_leap_year_read": "Mika Bond Practice",
        "m_triple_seven": "Japanese Imperial Demon Trial Trial",
        "m_thousand_complete": "Japanese Imperial Demon Ascension",
        "m_nice": "Seraph Archives Seal Seal",
        "m_power_level_chapters": "Soldier Resolve Aegis",
        "m_answer_42": "Yuu Mika Bond Trial",
        "m_square_number": "Battle Alerts Standard",
        "m_prime_count": "Japanese Imperial Demon Pinnacle",
        "m_matching_date": "Seraph Awakened Mantle",
        "m_century_chapter": "Daily Battle Decree",
        "m_pi_chapters": "Winter War Proof Proof",
        "m_synchronicity": "Kagami Fan Emblem",
        "m_world_record": "Seraph Expert Warrant",
        "m_genre_clash": "Mika's Speed Clash",
        "m_time_traveler": "Perfect Battle Decree",
        "m_double_digits": "Army Critic Dominion",
        "m_one_two_three": "Mika's Brother Banner Banner",
        "m_lucky_seven": "Demon Army Mantle Mantle",
        "m_exact_hundred_ch": "Vampire Escape Legend",
        "m_year_match_count": "Seraph Demons Routine",
        "m_chapter_match_date": "Night Patrol Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Army Critic Index",
        "m_manhwa_format": "Vampire World Gallery",
        "m_manhua_format": "Yamamoto Art Storehouse",
        "m_ln_format": "Japanese Imperial Demon Index",
        "m_oneshot_format": "Demon Critic Index",
        "m_doujin_format": "Curse Registry Cabinet",
        "m_novel_format": "Cursed Weapons Reserve Reserve",
        "m_format_master_manga": "Curse Registry Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Perfect Battle Link",
        "m_meta_collector": "Kagami Classic Reliquary",
        "m_meta_category_starter": "Yuu Mika Standard",
        "m_meta_tier_climber": "Vampire Reign Token",
        "m_meta_tier_max": "Seraph Complete",
        "m_meta_xp_earner": "Army Critic Anchor",
        "m_meta_difficulty_easy": "Japanese Imperial Demon Panel",
        "m_meta_difficulty_hard": "Kagami Master Node",
        "m_meta_unlock_spree": "Army Critic Marker",
        "m_meta_completionist": "Full Library",
        "m_meta_diverse": "Demon Critic Anchor",
        "m_meta_dominator": "Seraph Archives Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#020004",
        primary: "#5f26b9",
        secondary: "#441096",
        accent: "#d4a820",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/owari-no-seraph.jpg",
    particleColor: "#8050e0",
    backgroundDim: 0.42,
    backgroundBlur: 18,
    particleTypes: {
        cursed_aura: { label: "Cursed Aura", maxCount: 16, defaultEnabled: true, defaultIntensity: 60 },
        blood_mist: { label: "Blood Mist", maxCount: 12, defaultEnabled: true, defaultIntensity: 50 },
    },
    milestoneNames: {
  1: "Threadbare Generic Rank Spark",
  8: "Generic's Tarnished Omen",
  14: "Fractured Generic Rank",
  21: "Generic Rank Path",
  28: "Lowborn Legacy Myth",
  35: "Generic Rank Pulse",
  41: "Generic's Legacy Crest",
  48: "Humble Generic Mark",
  55: "Ragged Generic Rank Vow",
  61: "Generic's Faint Echo",
  68: "Lesser Generic Rank",
  75: "Generic Rank Zenith",
  81: "Doubtful Legacy Bloom",
  88: "Generic Rank Sigil",
  95: "Generic's Legacy Flame",
  102: "Really Cool Generic Spark",
  108: "Awakened Generic Rank Omen",
  115: "Generic's Resolute Seal",
  122: "Rising Generic Rank",
  128: "Generic Rank Myth",
  135: "Dauntless Legacy Pulse",
  142: "Generic Rank Crest",
  149: "Generic's Legacy Mark",
  155: "Fresh Generic Vow",
  162: "Valiant Generic Rank Echo",
  169: "Generic's Prime Crown",
  175: "Polished Generic Rank",
  182: "Generic Rank Bloom",
  189: "Stormlit Legacy Sigil",
  195: "Generic Rank Flame",
  202: "Generic's Legacy Spark",
  209: "Tempered Generic Omen",
  216: "Trusted Generic Rank Seal",
  222: "Generic's Steadfast Path",
  229: "Ironclad Generic Rank",
  236: "Veteran Legacy Pulse",
  242: "Core Legacy Crest",
  249: "Generic Rank Mark",
  256: "Generic's Legacy Vow",
  262: "Formidable Generic Echo",
  269: "Lucid Generic Rank Crown",
  276: "Generic's Ranked Zenith",
  283: "Fabled Generic Rank",
  289: "Grand Legacy Sigil",
  296: "Seasoned Legacy Flame",
  303: "Generic Rank Spark",
  309: "Generic's Legacy Omen",
  316: "Valorous Generic Seal",
  323: "Stalwart Generic Rank Path",
  330: "Generic's Commanding Myth",
  336: "Refined Generic Rank",
  343: "Unbroken Legacy Crest",
  350: "Blazing Legacy Mark",
  356: "Generic Rank Vow",
  363: "Generic's Legacy Echo",
  370: "Peerless Generic Crown",
  376: "Ardent Generic Rank Zenith",
  383: "Generic's Focused Bloom",
  390: "Vigilant Generic Rank",
  397: "Dominant Legacy Flame",
  403: "Elite Legacy Spark",
  410: "Generic Rank Omen",
  417: "Generic's Legacy Seal",
  423: "Sovereign Generic Path",
  430: "Regal Generic Rank Myth",
  437: "Generic's Crowned Pulse",
  444: "Mythborn Generic Rank",
  450: "Limitless Legacy Mark",
  457: "Radiant Legacy Vow",
  464: "Generic Rank Echo",
  470: "Generic's Legacy Crown",
  477: "Climactic Generic Zenith",
  484: "Epic Generic Rank Bloom",
  490: "Generic's Unreal Sigil",
  497: "Peak Generic Rank",
  504: "Supreme Legacy Spark",
  511: "Exalted Legacy Omen",
  517: "Generic Rank Seal",
  524: "Generic's Legacy Path",
  531: "Celestial Generic Myth",
  537: "Phantom Generic Rank Pulse",
  544: "Generic's Crimson Crest",
  551: "Silver Generic Rank",
  557: "Golden Legacy Vow",
  564: "Feral Legacy Echo",
  571: "Generic Rank Crown",
  578: "Generic's Legacy Zenith",
  584: "Dread Generic Bloom",
  591: "Luminous Generic Rank Sigil",
  598: "Generic's Thunderous Flame",
  604: "Ultraviolet Generic Rank",
  611: "Unleashed Legacy Omen",
  618: "Secret Legacy Seal",
  625: "Final Generic Path",
  631: "Generic's Legacy Myth",
  638: "Worldclass Generic Pulse",
  645: "Lawless Generic Rank Crest",
  651: "Generic's Chosen Mark",
  658: "Fearless Generic Rank",
  665: "Overdrive Legacy Echo",
  671: "Cinematic Legacy Crown",
  678: "Impossible Generic Zenith",
  685: "Generic's Legacy Bloom",
  692: "Canonized Generic Sigil",
  698: "Ascendant Generic Rank Flame",
  705: "Generic's Transfigured Spark",
  712: "Immortal Generic Rank",
  718: "Eclipsed Legacy Seal",
  725: "Astral Legacy Path",
  732: "Sublime Generic Myth",
  739: "Generic's Legacy Pulse",
  745: "Prismatic Generic Crest",
  752: "Abyssal Generic Rank Mark",
  759: "Generic's Unbound Vow",
  765: "Eternal Generic Rank",
  772: "Cosmic Legacy Crown",
  779: "Transcendent Legacy Zenith",
  785: "Perfected Generic Bloom",
  792: "Generic's Legacy Sigil",
  799: "Ultimate Generic Flame",
  806: "Mythic Generic Rank Spark",
  812: "Generic's Godlike Omen",
  819: "Canonical Generic Rank",
  826: "Reality-Bent Legacy Path",
  832: "Heavenly Legacy Myth",
  839: "Absolute Generic Pulse",
  846: "Untouchable Generic Crest",
  852: "Timeless Generic Mark",
  859: "Empyrean Generic Rank Vow",
  866: "Generic's Primordial Echo",
  873: "Omniscient Generic Rank",
  879: "Unfathomed Legacy Zenith",
  886: "Apocalyptic Legacy Bloom",
  893: "Seraphic Generic Sigil",
  899: "Omega Generic Flame",
  906: "Final Generic Spark",
  913: "Crowned Generic Rank Omen",
  920: "Generic's Mythic Seal",
  926: "Absolute Generic Rank",
  933: "Eternal Legacy Myth",
  940: "Cosmic Legacy Pulse",
  946: "Transcendent Generic Crest",
  953: "Perfected Generic Mark",
  960: "Definitive Generic Vow",
  966: "Ultimate Generic Rank Echo",
  973: "Generic's Infinite Crown",
  980: "Sovereign Generic Rank",
  987: "Celestial Legacy Bloom",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate Generic Rank"
},
}
