import { AnimeThemeConfig } from "./types"
import { GiRobotLeg, GiPoliceOfficerHead, GiHelicopter, GiShield, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiRadarSweep } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const patlaborTheme: AnimeThemeConfig = {
    id: "patlabor",
    displayName: "Patlabor",
    description: "In a near-future Tokyo, giant construction robots called Labors have become commonplace — and so has Labor crime. The Special Vehicles Section 2 polices them with their own police Labors.",
    fontFamily: "'Rajdhani', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;600&display=swap",
    cssVars: {
        "--color-brand-200": "145 180 240",
        "--color-brand-300": "100 148 220",
        "--color-brand-400": "58 118 195",
        "--color-brand-500": "25 88 168",
        "--color-brand-600": "16 68 136",
        "--color-brand-700": "10 50 104",
        "--color-brand-800": "6 34 72",
        "--color-brand-900": "3 20 42",
        "--color-brand-950": "1 10 24",
        "--brand": "25 88 168",
        "--background": "#010408",
        "--paper": "#040a10",
        "--color-gray-950": "1 4 8",
        "--color-gray-900": "4 8 16",
        "--color-gray-800": "8 16 28",
        "--color-gray-700": "14 28 46",
        "--color-gray-600": "24 46 72",
        "--color-gray-500": "40 72 108",
        "--color-gray-400": "72 112 150",
        "--color-gray-300": "112 155 190",
        "--color-gray-200": "158 196 220",
        "--color-gray-100": "196 220 236",
        "--color-gray-50": "232 242 248",
    },
    sidebarOverrides: {
        "home": { icon: GiRobotLeg, label: "SV2 HQ" },
        "schedule": { icon: GiAlarmClock, label: "Patrol Schedule" },
        "manga": { icon: LuBookOpen, label: "Case Files" },
        "lists": { icon: GiShield, label: "Unit Roster" },
        "discover": { icon: GiBullseye, label: "Labor Scouting" },
        "torrent-list": { icon: GiHelicopter, label: "Equipment Cache" },
        "debrid": { icon: GiRadarSweep, label: "Police Network" },
        "unmatched": { icon: GiPoliceOfficerHead, label: "Unregistered" },
        "enmasse": { icon: GiResize, label: "Force Deploy" },
        "scan-summaries": { icon: TbReportSearch, label: "Incident Reports" },
        "auto-downloader": { icon: LuRss, label: "Dispatch Feed" },
        "community": { icon: GiRobotLeg, label: "SV2 Team" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Dispatch Alerts" },
        "achievements": { icon: GiTrophy, label: "Police Medals" },
        "milestones": { icon: LuFlag, label: "Labor Goals" },
        "theme-manager": { icon: GiPalette, label: "Labor Colors" },
        "extensions": { icon: BiExtension, label: "Labor Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Police Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Labor Controls" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Dispatch",
        "a_episode_counter": "Case Archives Mark",
        "a_episode_titan": "Top Officer Relic",
        "a_hours_invested": "Special Vehicles Section Proof",
        "a_time_lord": "SV2 Veteran",
        "a_anime_collector": "Labor Arsenal",
        "a_library_legend": "Case Archives",
        "a_first_complete": "Case Resolved",
        "a_hundred_club": "Hundred Patrols",
        "a_first_day": "Daily Shift Seal",
        "a_first_rating": "Top Officer Appraisal",
        "a_ten_thousand_min": "Labor Critic Standard",
        "a_season_veteran": "Labor Critic Library",
        "a_year_explorer": "Police Drama Map",
        "a_century_watcher": "Labor Review Ledger",
        "a_five_hundred_eps": "Rogue Labor Dominion",
        "a_thousand_eps": "Police Medals Record",
        "a_watching_ten": "All Cases Solved Acclaim",
        "a_ptw_hoarder": "Police Network Library",
        "a_dropped_honesty": "All Cases Solved Summit",
        "a_five_thousand_eps": "Endless Duty Warrant",
        "a_ten_completed": "Near Future Afterglow",
        "a_fifty_completed": "Case Resolved Ascension",
        "a_five_hundred_completed": "All Cases Solved Clear",
        "a_mean_score_tracker": "Oshii's Depth Verdict",
        "a_unique_studios": "Police Medals Collection",
        "a_days_spent_watching": "Labor Scouting Dominion",
        "a_all_status": "Oshii Classic Testament",
        "a_first_favorite": "Decade Fan Cabinet",
        "a_favorites_collector": "Classic Fan Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Hidden File Drive",
        "a_marathon_runner": "Police Marathon",
        "a_weekend_warrior": "Top Officer Ordeal",
        "a_non_stop": "Labor Controls Fever",
        "a_one_more_episode": "Police Labor Mantle",
        "a_speed_run": "Quick Response",
        "a_double_feature": "Noa's Crew Crown",
        "a_triple_threat": "Holiday Duty Record",
        "a_five_a_day": "Night Duty Accord",
        "a_back_to_back": "Labor Arsenal Surge",
        "a_seasonal_binge": "Top Officer Cascade",
        "a_cour_crusher": "Labor Scouting Ordeal",
        "a_half_day_watch": "Case Archives Crown",
        "a_full_day_watch": "Daily Duty Pinnacle",
        "a_power_weekend": "Daily Shift Run",
        "a_binge_king": "Night Shift",
        "a_no_sleep": "All-Night Duty",
        "a_entire_season": "Night Shift Library",
        "a_seven_day_challenge": "Daily Duty Mark",
        "a_hundred_day_binge": "Daily Shift Surge",
        "a_genre_binge": "Quick Response Binge",
        "a_studio_binge": "Case Archives Fever",
        "a_season_sweep": "Beat Revisited Codex",
        "a_forty_eight_hour": "Rookie Ace Overture",
        "a_ep_counter_day": "Near Future Aegis",
        "a_multi_series_binge": "Police Network Streak",
        "a_midnight_binge": "Police Labor Cascade",
        "a_new_year_binge": "City Patrol Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Labor Combat",
        "a_genre_adventure": "City Patrol",
        "a_genre_comedy": "SV2 Antics",
        "a_genre_drama": "Police Drama",
        "a_genre_fantasy": "Near Future",
        "a_genre_horror": "Rogue Labor",
        "a_genre_mystery": "Perfect Issue Mystery",
        "a_genre_romance": "Noa's Love",
        "a_genre_scifi": "Labor Technology",
        "a_genre_sol": "Endless Duty Slice",
        "a_genre_sports": "Rookie Ace Sports",
        "a_genre_supernatural": "Urban Legend",
        "a_genre_thriller": "Case Resolved Thriller",
        "a_genre_mecha": "Police Labor",
        "a_genre_music": "Labor Critic Music",
        "a_genre_psychological": "Oshii's Depth",
        "a_genre_ecchi": "Hidden File Ecchi",
        "a_genre_mahou_shoujo": "Holiday Duty Magic Shoujo",
        "a_tag_isekai": "Sv2 Hq Isekai",
        "a_tag_harem": "Labor Art Harem",
        "a_tag_bl": "Rookie Ace Bl",
        "a_tag_gl": "Police Labor Gl",
        "a_tag_historical": "Yuuki Fan Historical",
        "a_tag_military": "Rogue Labor Military",
        "a_tag_school": "Police Network School",
        "a_tag_martial_arts": "Daily Duty Martial Arts",
        "a_tag_vampire": "Holiday Duty Vampire",
        "a_tag_samurai": "Police Medals Samurai",
        "a_tag_space": "All Night Space",
        "a_tag_parody": "Sv2 Antics Parody",
        "a_tag_idol": "Rookie Ace Idol",
        "a_tag_post_apocalyptic": "Next Division Post Apocalyptic",
        "a_tag_cyberpunk": "Labor Controls Cyberpunk",
        "a_tag_shounen": "Next Division Shounen",
        "a_tag_seinen": "Noa's Love Seinen",
        "a_tag_shoujo": "Noa's Love Shoujo",
        "a_tag_josei": "Near Future Josei",
        "a_tag_survival": "Classic Fan Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "All Cases Solved",
        "a_mega_completionist": "Oshii Master",
        "a_completion_rate_50": "Holiday Duty Return",
        "a_completion_rate_75": "Case Resolved Crown",
        "a_completion_rate_90": "Near Future Resolution",
        "a_no_drop": "Perfect Issue Decree",
        "a_long_runner_complete": "Daily Shift Clear",
        "a_sequel_chain": "Next Division",
        "a_clean_list": "Beat Revisited Relic",
        "a_from_ptw": "Sv2 Antics Index",
        "a_rewatch_master": "Oshii's Depth Return",
        "a_short_complete": "Cases Solved Endgame",
        "a_same_day_start_finish": "Police Master Pinnacle",
        "a_revival": "Labor Review Insignia",
        "a_zero_to_hero": "Rookie to Ace",
        "a_five_genre_complete": "Cases Solved A Five Genre",
        "a_full_franchise": "Police Network Chronicle",
        "a_batch_complete": "Top Officer Crown",
        "a_paused_to_done": "Near Future Aegis Aegis",
        "a_completion_spree": "Labor Combat Triumph",
        "a_multi_rewatch": "Labor Combat Triumph Triumph",
        "a_dropped_recovery": "Case Archives Conquest",
        "a_ten_perfect_scores": "Daily Shift Acclaim",
        "a_seasonal_clear": "Labor Scouting Codex",
        "a_complete_genre_span": "All Cases A Complete Genre",
        "a_monthly_completions": "Oshii's Depth Afterglow",
        "a_yearly_completions": "Oshii Classic Epilogue",
        "a_rapid_complete": "Daily Duty Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Noa's Crew",
        "a_studio_devotee": "Perfect Issue Treasury",
        "a_rewatcher": "Beat Revisited",
        "a_triple_rewatch": "Quick Response Coda",
        "a_annual_tradition": "Daily Duty Proof",
        "a_director_fan": "Beat Revisited Trial",
        "a_voice_actor_fan": "Case Archives Crown Crown",
        "a_ost_lover": "Police Network Seal",
        "a_source_reader": "Police Drama Cabinet",
        "a_waiting_weekly": "Perfect Issue Clock",
        "a_childhood_revisit": "Oshii Master Seal",
        "a_saga_tracker": "All Night Standard",
        "a_genre_loyalty": "Endless Duty Loyalty",
        "a_decade_watcher": "Decade Fan",
        "a_adaptation_hunter": "Sv2 Antics Trial",
        "a_original_anime_fan": "Unit Roster Testament",
        "a_long_commitment": "Daily Duty Mark Mark",
        "a_perfect_attendance": "All Cases Solved Standard",
        "a_favorite_studio_5": "Next Division Library",
        "a_complete_catalog": "Classic Fan Seal",
        "a_franchise_collector": "Next Division Archive",
        "a_airing_follower": "Oshii Master Signal",
        "a_genre_master": "Beat Revisited Master",
        "a_staff_follower": "Next Division Oath",
        "a_multi_season_fan": "Yuuki Fan Hoard",
        "a_format_diversity": "Holiday Duty Cache",
        "a_year_dedication": "Top Officer Tenure",
        "a_season_dedication": "Rogue Labor Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Quick Response Explorer",
        "a_studio_hopper": "Oshii's Depth Collection",
        "a_tag_explorer": "Top Officer Explorer",
        "a_decade_hopper": "Police Network Chronicle Chronicle",
        "a_hidden_gem": "Hidden File",
        "a_popular_taste": "Rookie Ace Decree",
        "a_retro_appreciator": "Classic Fan Aegis",
        "a_modern_viewer": "Police Master Pinnacle Pinnacle",
        "a_cross_demographic": "Hidden File Pinnacle",
        "a_underdog_fan": "All Cases Trial",
        "a_variety_week": "Next Division Horizon",
        "a_foreign_cinema": "Police Labor Expedition",
        "a_classic_connoisseur": "89 Classic Fan",
        "a_every_season": "Oshii Master Archive",
        "a_award_winner": "Labor Critic Insignia",
        "a_niche_explorer": "Noa's Love Horizon",
        "a_global_anime": "Cases Solved Crown",
        "a_cult_classic": "Oshii Classic",
        "a_random_pick": "Rookie Ace Decree Decree",
        "a_new_genre_month": "All Cases Solved A New",
        "a_seasonal_completionist": "Labor Review Summit",
        "a_unpopular_opinion": "Decade Fan Standard",
        "a_top_rated_viewer": "Night Duty Seal",
        "a_source_variety": "Labor Scouting Storehouse",
        "a_low_score_brave": "Labor Controls Measure",
        "a_upcoming_watcher": "Night Duty Seal Seal",
        "a_short_series_explorer": "Police Labor Expedition Expedition",
        "a_long_series_explorer": "Noa's Crew Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Night Shift",
        "a_early_bird": "Morning Patrol",
        "a_lunch_break": "Sv2 Team Trial",
        "a_golden_hour": "Case Revisit Tenure",
        "a_four_am_club": "Labor Combat Gathering",
        "a_witching_hour": "Case Resolved Tenure",
        "a_new_year_watch": "Top Officer Season",
        "a_midnight_premiere": "City Patrol Devotion",
        "a_all_hours": "Labor Review Seal",
        "a_dawn_warrior": "Rookie Ace Aegis",
        "a_afternoon_delight": "Special Vehicles Section Proof Proof",
        "a_prime_time": "Labor Critic Insignia Insignia",
        "a_workday_watcher": "Hidden File Pinnacle Pinnacle",
        "a_sunday_marathon": "Daily Shift Momentum",
        "a_rainy_day": "Case Resolved Relic",
        "a_morning_routine": "Yuuki Fan Promise",
        "a_night_shift": "Holiday Duty Aegis",
        "a_twilight_zone": "Night Shift Ledger",
        "a_seasonal_premier": "Perfect Issue Cabinet",
        "a_clock_collector": "Labor Combat Repository",
        "a_weekend_binge_hours": "Noa's Love Streak",
        "a_late_night_regular": "Oshii Classic Dominion",
        "a_sunrise_watcher": "Beat Revisited Relic Relic",
        "a_holiday_watcher": "Night Duty Pact",
        "a_every_day_of_week": "Labor Arsenal Ledger",
        "a_monthly_hours": "Rookie Ace Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Near Future Record",
        "a_party_host": "Holiday Duty Record Record",
        "a_social_butterfly": "Police Drama Company",
        "a_group_binge": "Police Medals Sprint",
        "a_party_regular": "Night Shift Chronicle",
        "a_sync_viewer": "Labor Combat Standard",
        "a_commentator": "Classic Fan Record",
        "a_party_marathon": "Quick Response Vigil",
        "a_full_house": "Rogue Labor Trial",
        "a_community_pillar": "Oshii Classic Alliance",
        "a_watch_party_streak": "Classic Fan Vigil",
        "a_diverse_party": "Yuuki Fan Seal",
        "a_late_night_party": "Oshii Classic Testament Testament",
        "a_party_veteran": "Rogue Labor Testament",
        "a_genre_party": "Police Labor Party",
        "a_weekly_party": "Labor Combat Calendar",
        "a_silent_viewer": "Unit Roster Mantle",
        "a_recommendation_giver": "Noa's Love Network",
        "a_party_completionist": "All Night Coda",
        "a_social_scorer": "Beat Revisited Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Noa's Crew Proof",
        "a_fibonacci": "Top Officer Dominion",
        "a_palindrome_day": "Top Officer Relic Relic",
        "a_binary_day": "Endless Duty Mark",
        "a_full_moon": "Oshii Master Insignia",
        "a_leap_year": "Cases Solved Devotion",
        "a_time_traveler": "Perfect Issue Record",
        "a_genre_clash": "Quick Response Clash",
        "a_triple_seven": "Top Officer Testament",
        "a_thousand_complete": "Unit Roster Epilogue",
        "a_pi_episodes": "Hidden File Crown",
        "a_synchronicity": "All Cases Anchor",
        "a_world_record": "Case Archives Warrant",
        "a_nice": "Labor Critic Chronicle",
        "a_power_level": "Unit Roster Testament Testament",
        "a_answer_42": "Rookie Ace Standard",
        "a_square_number": "Quick Response Decree",
        "a_prime_count": "Labor Critic Seal",
        "a_matching_date": "All Cases Mantle",
        "a_century_episode": "Hidden File Mark",
        "a_double_digits": "Case Resolved Testament",
        "a_one_two_three": "Cases Solved Crown Crown",
        "a_lucky_seven": "Daily Duty Crown",
        "a_all_tens": "Labor Controls Criterion",
        "a_exact_hundred_eps": "All Night Legend",
        "a_year_match_count": "Perfect Issue Yearlong",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Noa's Love Ledger",
        "a_movie_buff": "Case Archives Mark Mark",
        "a_ova_hunter": "All Night Standard Standard",
        "a_ona_explorer": "All Cases Secret",
        "a_special_watcher": "Case Resolved Relic Relic",
        "a_short_king": "Labor Art Crown",
        "a_variety_pack": "Case Archives Inquiry",
        "a_film_festival": "Night Duty Chronicle",
        "a_music_video": "Yuuki Fan Chronicle",
        "a_tv_short": "Quick Response Record",
        "a_movie_marathon": "Quick Response Gauntlet",
        "a_double_length": "Noa's Crew Crown Crown",
        "a_anthology": "Holiday Duty Aegis Aegis",
        "a_mini_series": "Decade Fan Decree",
        "a_theatrical": "Next Division Accord",
        "a_format_master": "Labor Combat Vault",
        "a_long_movie": "Labor Review Insignia Insignia",
        "a_back_catalog": "Classic Fan Standard",
        "a_cm_watcher": "Sv2 Hq Aegis",
        "a_pv_collector": "All Cases Storehouse",
        "a_format_balance": "Labor Combat Vault Vault",
        "a_episodic_master": "Sv2 Hq Standard",
        "a_sequel_movie": "Cases Solved Pinnacle",
        "a_recap_watcher": "Sv2 Team Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Shift",
        "a_mega_streak": "Endless Duty",
        "a_weekly_warrior": "Rogue Labor Season",
        "a_monthly_watcher": "City Patrol Calendar",
        "a_comeback": "Police Drama Decree",
        "a_weekend_streak": "Labor Controls Passage",
        "a_no_zero_days": "Endless Duty Warrant Warrant",
        "a_iron_will": "Police Resolve",
        "a_habit_formed": "Labor Arsenal Banner",
        "a_consistent_pace": "Noa's Crew Measure",
        "a_year_long": "Year of Service",
        "a_double_streak": "Beat Revisited Watch",
        "a_streak_recovery": "Unit Roster Season",
        "a_daily_minimum": "City Patrol Focus",
        "a_winter_streak": "Police Labor Watch",
        "a_summer_streak": "Case Resolved Resolve",
        "a_morning_streak": "Classic Fan Clock",
        "a_night_streak": "Labor Arsenal Constancy",
        "a_unbreakable": "Labor Art Proof",
        "a_eternal_flame": "Oshii's Depth Standard",
        "a_completion_streak": "All Night Return",
        "a_rating_streak": "Top Officer Balance",
        "a_multi_ep_streak": "Case Archives Ritual",
        "a_genre_streak": "Top Officer Streak",
        "a_studio_streak": "Police Drama Cabinet Cabinet",
        "a_perfect_week": "All Cases Relic",

        // ── ANIME SCORING ──
        "a_critic": "Labor Review",
        "a_perfect_ten": "Perfect Patrol",
        "a_harsh_critic": "Strict Officer",
        "a_fair_judge": "Oshii Classic Balance",
        "a_generous_spirit": "City Patrol Pinnacle",
        "a_score_all": "Special Vehicles Section Criterion",
        "a_wide_range": "Labor Critic Ledger",
        "a_controversial": "Classic Fan Decree",
        "a_consistent_scorer": "Perfect Issue Verdict",
        "a_score_sniper": "Cases Solved Score",
        "a_evolving_taste": "Beat Revisited Testament",
        "a_bell_curve": "All Cases Solved Insignia",
        "a_picky_watcher": "Unit Roster Warrant",
        "a_100_rated": "Labor Combat Warrant",
        "a_500_rated": "Labor Art Pinnacle",
        "a_mediocre_majority": "All Cases Canon",
        "a_rating_spree": "Classic Fan Review",
        "a_score_variance": "Labor Controls Score",
        "a_masterpiece_hunter": "Classic Fan Banner",
        "a_contrarian": "Quick Response Record Record",
        "a_optimist": "Yuuki Fan Ledger",
        "a_score_distributor": "Sv2 Team Appraisal",
        "a_genre_critic": "Noa's Crew Critic",
        "a_mean_above_8": "Daily Duty Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Patrol",
        "a_valentines_weeb": "Next Division Vow",
        "a_pi_day": "Oshii Classic Trial",
        "a_april_fools": "Cases Solved Devotion Devotion",
        "a_international_anime_day": "Labor Review Record",
        "a_star_wars_day": "Daily Shift Chronicle",
        "a_summer_solstice": "Endless Duty Calendar",
        "a_tanabata": "Police Master Focus",
        "a_friday_13th": "Sv2 Team Relic",
        "a_halloween_spirit": "Noa's Love Vow",
        "a_thanksgiving_binge": "Night Shift Run",
        "a_christmas_special": "Holiday Duty",
        "a_new_years_eve": "Daily Duty Pilgrimage",
        "a_birthday_watch": "All Cases Solved Vow",
        "a_holiday_marathon": "Police Medals Overture",
        "a_independence_day": "Oshii's Depth Banner",
        "a_culture_day": "Police Network Insignia",
        "a_spring_equinox": "Police Medals Decree",
        "a_earth_day": "Case Archives Mantle",
        "a_labor_day": "Noa's Love Seal",
        "a_winter_solstice": "Hidden File Pilgrimage",
        "a_anime_birthday": "Case Archives Pilgrimage",
        "a_every_holiday": "Sv2 Antics Resolve",
        "a_consecutive_holidays": "Case Resolved Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Police Drama Rank",
        "a_meta_collector": "Police Network Hoard",
        "a_meta_category_starter": "City Patrol Badge",
        "a_meta_tier_climber": "Police Network Glyph",
        "a_meta_tier_max": "Top Officer",
        "a_meta_xp_earner": "Sv2 Team Emblem",
        "a_meta_difficulty_easy": "Oshii Classic Mechanism",
        "a_meta_difficulty_hard": "Night Duty Writ",
        "a_meta_unlock_spree": "Rogue Labor Panel",
        "a_meta_completionist": "Complete Files",
        "a_meta_diverse": "Top Officer Emblem",
        "a_meta_dominator": "Night Shift Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Case",
        "m_chapter_counter": "Labor Combat Pinnacle",
        "m_chapter_titan": "Labor Scouting Relic",
        "m_reading_hours": "Sv2 Team Relic Relic",
        "m_reading_time_lord": "Labor Review Record Record",
        "m_manga_collector": "Rogue Labor Ledger",
        "m_library_legend": "Police Network Reliquary",
        "m_first_complete": "Arc Closed",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "Next Division Seal",
        "m_first_rating": "Sv2 Team Eye",
        "m_ten_thousand_pages": "Next Division Gauge",
        "m_volume_collector": "Unit Roster Storehouse",
        "m_year_explorer": "Rookie Ace Quest",
        "m_century_reader": "Police Labor Dominion",
        "m_five_hundred_ch": "Labor Critic Legend",
        "m_thousand_ch": "Beat Revisited Legend",
        "m_reading_ten": "Police Labor Appraisal",
        "m_ptr_hoarder": "Beat Revisited Index",
        "m_dropped_honesty": "Police Network Summit",
        "m_season_reader": "Classic Fan Treasury",
        "m_active_reader": "Case Resolved Trial",
        "m_five_thousand_ch": "Quick Response Standard",
        "m_ten_completed": "Quick Response Resolution",
        "m_fifty_completed": "Beat Revisited Harvest",
        "m_five_hundred_completed": "Labor Arsenal Legacy",
        "m_mean_score_tracker": "Perfect Issue Audit",
        "m_unique_authors": "Case Archives Reserve",
        "m_all_status": "Case Resolved Testament Testament",
        "m_first_favorite": "All Night Cache",
        "m_favorites_collector": "Police Drama Shelf",
        "m_days_spent_reading": "Hidden File Relic",

        // ── MANGA BINGE ──
        "m_binge_reader": "All Cases Solved Streak",
        "m_marathon_reader": "Oshii Classic Rush",
        "m_weekend_reader": "Oshii Master Run",
        "m_non_stop_reading": "All Night Gauntlet",
        "m_one_more_chapter": "Sv2 Team Testament Testament",
        "m_speed_read": "Endless Duty Drive",
        "m_double_story": "Police Medals Banner",
        "m_triple_read": "Oshii's Depth Record",
        "m_five_a_day": "Yuuki Fan Insignia",
        "m_chapter_chain": "Police Network Accord",
        "m_volume_binge": "Labor Controls Drive",
        "m_power_reader": "Daily Shift Seal Seal",
        "m_half_day_read": "Police Drama Aegis",
        "m_full_day_read": "Sv2 Hq Aegis Aegis",
        "m_power_weekend": "Next Division Streak",
        "m_binge_king": "Shift Marathon",
        "m_no_sleep_read": "Police Labor Rush",
        "m_full_series_rush": "Oshii Classic Cascade",
        "m_seven_day_challenge": "Police Master Warrant",
        "m_hundred_day_read": "Top Officer Legend",
        "m_volume_rush": "Near Future Gauntlet",
        "m_series_sweep": "Sv2 Antics Trial Trial",
        "m_genre_binge": "Sv2 Hq Binge",
        "m_author_binge": "Oshii Master Surge",
        "m_chapter_counter_day": "Night Shift Ledger Ledger",
        "m_multi_series_binge": "Labor Critic Charge",
        "m_midnight_binge": "Beat Revisited Tempest",
        "m_new_year_binge": "Case Archives Passage",
        "m_forty_eight_hour": "Perfect Issue Rally",
        "m_oneshot_binge": "Endless Duty Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Combat Chapter",
        "m_genre_adventure": "City Chapter",
        "m_genre_comedy": "Police Drama Comedy",
        "m_genre_drama": "Drama Chapter",
        "m_genre_fantasy": "Future Chapter",
        "m_genre_horror": "Rogue Chapter",
        "m_genre_mystery": "Quick Response Mystery",
        "m_genre_romance": "Team Chapter",
        "m_genre_scifi": "Labor Chapter",
        "m_genre_sol": "Labor Combat Slice",
        "m_genre_sports": "Near Future Sports",
        "m_genre_supernatural": "Myth Chapter",
        "m_genre_thriller": "All Cases Thriller",
        "m_genre_psychological": "Depth Chapter",
        "m_genre_isekai": "Rogue Labor Isekai",
        "m_genre_shounen": "Case Revisit Shounen",
        "m_genre_ecchi": "Noa's Crew Ecchi",
        "m_genre_mahou_shoujo": "Police Drama Magic Shoujo",
        "m_genre_mecha": "Unit Roster Mecha",
        "m_genre_music": "Noa's Love Music",
        "m_tag_isekai_new": "Sv2 Team Isekai New",
        "m_tag_harem": "Special Vehicles Section Harem",
        "m_tag_bl": "Decade Fan Bl",
        "m_tag_gl": "Beat Revisited Gl",
        "m_tag_historical": "Labor Critic Historical",
        "m_tag_military": "Case Revisit Military",
        "m_tag_school": "Next Division School",
        "m_tag_martial_arts": "Labor Combat Martial Arts",
        "m_tag_vampire": "Near Future Vampire",
        "m_tag_samurai": "Holiday Duty Samurai",
        "m_tag_space": "Decade Fan Space",
        "m_tag_parody": "Unit Roster Parody",
        "m_tag_idol": "Decade Fan Idol",
        "m_tag_post_apocalyptic": "Police Network Post Apocalyptic",
        "m_tag_cyberpunk": "Special Vehicles Section Cyberpunk",
        "m_tag_shoujo": "Night Duty Shoujo",
        "m_tag_survival": "Police Drama Survival",
        "m_tag_cooking": "All Cases Solved Cooking",
        "m_tag_medical": "Case Resolved Medical",
        "m_tag_villainess": "Oshii Master Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Dossier",
        "m_mega_completionist": "Police Master",
        "m_completion_rate_50": "Decade Fan Return",
        "m_completion_rate_75": "All Cases Ascension",
        "m_completion_rate_90": "Oshii's Depth Resolution",
        "m_no_drop": "All Night Decree",
        "m_long_runner_complete": "Night Shift Clear",
        "m_sequel_chain": "Noa's Love Seal Seal",
        "m_clean_list": "Labor Scouting Relic Relic",
        "m_from_ptr": "Night Duty Watchlist",
        "m_reread_master": "Oshii Classic Trial Trial",
        "m_oneshot_complete": "Oshii Classic Ascension",
        "m_same_day_start_finish": "Daily Duty Crown Crown",
        "m_revival": "Night Shift Accord",
        "m_zero_to_hundred": "Quick Response Banner",
        "m_five_genre_complete": "Endless Duty M Five Genre",
        "m_full_collection": "Daily Duty Proof Proof",
        "m_batch_complete": "Perfect Issue Summit",
        "m_paused_to_done": "Oshii's Depth Standard Standard",
        "m_completion_spree": "Labor Art Triumph",
        "m_format_completionist": "Oshii Classic Completion",
        "m_catch_up": "Labor Review Chronicle",
        "m_multi_reread": "All Night Banner",
        "m_dropped_recovery": "Noa's Crew Conquest",
        "m_ten_perfect_scores": "Oshii Master Judgment",
        "m_complete_genre_span": "Rogue Labor M Complete Genre",
        "m_monthly_completions": "Sv2 Hq Return",
        "m_yearly_completions": "Rogue Labor Epilogue",
        "m_rapid_complete": "Police Master Finale",
        "m_author_complete": "Next Division Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Duty Reader",
        "m_mangaka_lover": "Yuuki Fan",
        "m_rereader": "Case Revisit",
        "m_triple_reread": "Top Officer Testament Testament",
        "m_annual_reread": "Quick Response Banner Banner",
        "m_publisher_fan": "Labor Art Mark",
        "m_artist_fan": "Noa's Love Insignia",
        "m_adaptation_compare": "All Cases Solved Insignia Insignia",
        "m_source_material_fan": "Manga First",
        "m_waiting_weekly": "Holiday Duty Streak",
        "m_classic_reader": "Unit Roster Lantern",
        "m_saga_reader": "Police Network Decree",
        "m_genre_loyalty": "Noa's Crew Loyalty",
        "m_decade_reader": "Labor Controls Warrant",
        "m_ln_adaptation": "Labor Controls Mark",
        "m_original_work": "Near Future Standard",
        "m_long_commitment": "Noa's Crew Mark",
        "m_up_to_date": "Case Archives Warrant Warrant",
        "m_favorite_mangaka": "Rookie Ace Treasury",
        "m_complete_portfolio": "Labor Art Triumph Triumph",
        "m_franchise_collector": "Labor Review Archive",
        "m_serialization_follower": "Rookie Ace Handshake",
        "m_genre_master": "Labor Scouting Master",
        "m_multi_series_author": "Police Network Insignia Insignia",
        "m_format_diversity": "Near Future Shelf",
        "m_year_dedication": "Police Labor Tenure",
        "m_ongoing_follower": "Labor Controls Fellowship",
        "m_genre_loyalty_50": "Beat Revisited Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Police Medals Explorer",
        "m_publisher_hopper": "Labor Art Mantle",
        "m_tag_explorer": "Sv2 Antics Explorer",
        "m_decade_hopper": "Night Duty Chronicle Chronicle",
        "m_hidden_gem": "Hidden Volume",
        "m_popular_taste": "Perfect Issue Record Record",
        "m_retro_reader": "Perfect Issue Accord",
        "m_modern_reader": "Labor Critic Seal Seal",
        "m_cross_demographic": "City Patrol Crown",
        "m_underdog_fan": "Perfect Issue Accord Accord",
        "m_variety_week": "Noa's Love Horizon Horizon",
        "m_manhwa_reader": "Cases Solved Proof",
        "m_manhua_reader": "Unit Roster Mantle Mantle",
        "m_classic_connoisseur": "Labor Arsenal Glimpse",
        "m_award_winner": "Police Labor Warrant",
        "m_niche_explorer": "All Cases Solved Horizon",
        "m_world_manga": "Labor Review Chronicle Chronicle",
        "m_cult_classic": "Classic Manga",
        "m_random_pick": "Perfect Issue Standard",
        "m_new_genre_month": "Labor Review M New Genre",
        "m_year_completionist": "Labor Combat Fulfillment",
        "m_unpopular_opinion": "Case Archives Trial",
        "m_top_rated_reader": "All Cases Solved Record",
        "m_source_variety": "Unit Roster Catalogue",
        "m_low_score_brave": "Labor Combat Score",
        "m_short_manga_explorer": "Labor Critic Compass",
        "m_long_manga_explorer": "Quick Response Survey",
        "m_serialization_explorer": "All Cases Road",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Morning Reader",
        "m_lunch_reader": "Decade Fan Ledger",
        "m_commute_reader": "Case Resolved Tenure Tenure",
        "m_four_am_club": "Labor Art Fellowship",
        "m_new_year_read": "Noa's Love Pact",
        "m_all_hours": "Night Duty Accord Accord",
        "m_prime_time_reader": "Near Future Banner",
        "m_workday_reader": "Night Shift Accord Accord",
        "m_sunday_read": "Decade Fan Standard Standard",
        "m_morning_routine": "Night Shift Discipline",
        "m_night_shift_reader": "Next Division Accord Accord",
        "m_seasonal_premier_read": "Unit Roster Seasonal",
        "m_clock_collector": "Hidden File Reserve",
        "m_late_night_horror": "Endless Duty Mark Mark",
        "m_afternoon_reader": "Police Labor Mantle Mantle",
        "m_golden_hour_reader": "Top Officer Observance",
        "m_dawn_reader": "Sv2 Antics Mantle",
        "m_twilight_reader": "Labor Controls Crown",
        "m_midnight_start": "Near Future Routine",
        "m_weekend_binge_hours": "Oshii Master Momentum",
        "m_late_night_regular": "Decade Fan Accord",
        "m_sunrise_reader": "Special Vehicles Section Mantle",
        "m_every_day_of_week": "Unit Roster Warrant Warrant",
        "m_monthly_hours": "Police Medals Vigil",
        "m_bedtime_reader": "Labor Combat Warrant Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Labor Art",
        "m_webtoon_reader": "Labor Controls Mark Mark",
        "m_full_color": "Noa's Love Accord",
        "m_doujin_reader": "Oshii's Depth Record Record",
        "m_anthology_reader": "Oshii Master Accord",
        "m_adaptation_reader": "Perfect Issue Banner",
        "m_longstrip_reader": "Top Officer Trial",
        "m_4koma_reader": "Holiday Duty Ledger",
        "m_oneshot_reader": "Rogue Labor Mantle",
        "m_format_variety": "Labor Art Gallery",
        "m_light_novel_reader": "Night Duty Insignia",
        "m_novel_reader": "Labor Combat Crown",
        "m_visual_storyteller": "Police Labor Testament",
        "m_colored_classic": "Classic Fan Survey",
        "m_webcomic_fan": "Labor Arsenal Insignia",
        "m_manga_to_anime": "Manga Adapted",
        "m_seinen_reader": "Noa's Crew Pinnacle",
        "m_josei_reader": "Special Vehicles Section Pinnacle",
        "m_award_winning_art": "Case Revisit Relic",
        "m_debut_work": "Case Revisit Dominion",
        "m_vertical_scroll": "Police Network Decree Decree",
        "m_traditional_format": "All Cases Solved Hoard",
        "m_cross_media": "Labor Critic Accord",
        "m_spinoff_reader": "Labor Review Accord",
        "m_remake_reader": "Oshii Classic Pinnacle",
        "m_collaboration_reader": "Labor Arsenal Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Duty",
        "m_mega_streak": "Unbroken Service",
        "m_weekly_warrior": "All Cases Season",
        "m_monthly_reader": "Yuuki Fan Discipline",
        "m_comeback": "Quick Response Standard Standard",
        "m_weekend_streak": "Special Vehicles Section Fever",
        "m_no_zero_days": "Cases Solved Proof Proof",
        "m_iron_will": "Officer Resolve",
        "m_habit_formed": "City Patrol Crown Crown",
        "m_consistent_pace": "Daily Duty Scrutiny Scrutiny",
        "m_year_long": "Year Reading",
        "m_double_streak": "Rogue Labor Resolve",
        "m_streak_recovery": "Labor Scouting Resolve",
        "m_daily_minimum": "Hidden File Focus",
        "m_winter_streak": "Top Officer Observance Observance",
        "m_summer_streak": "Case Revisit Observance",
        "m_morning_streak": "Police Medals Clock",
        "m_night_streak": "All Cases Solved Discipline",
        "m_unbreakable": "Special Vehicles Section Warrant",
        "m_eternal_flame": "Police Drama Record",
        "m_chapter_a_day": "Decade Fan Ledger Ledger",
        "m_genre_streak": "Sv2 Antics Streak",
        "m_completion_streak": "Perfect Issue Return",
        "m_rating_streak": "Sv2 Antics Appraisal",
        "m_multi_ch_streak": "All Cases Tenure",
        "m_author_streak": "Hidden File Calendar",
        "m_perfect_week_manga": "Labor Review Accord Accord",
        "m_diverse_streak": "All Night Streak",

        // ── MANGA SCORING ──
        "m_critic": "Labor Critic",
        "m_perfect_ten": "Perfect Issue",
        "m_harsh_critic": "Night Duty Scale",
        "m_fair_judge": "Sv2 Team Eye Eye",
        "m_generous_spirit": "Oshii Master Decree",
        "m_score_all": "Labor Controls Reckoning",
        "m_wide_range": "Yuuki Fan Ledger Ledger",
        "m_controversial": "Sv2 Hq Standard Standard",
        "m_consistent_scorer": "Oshii's Depth Grade",
        "m_score_sniper": "Case Archives Reckoning",
        "m_evolving_taste": "Rogue Labor Trial Trial",
        "m_bell_curve": "Yuuki Fan Accord",
        "m_picky_reader": "All Night Ledger",
        "m_100_rated": "Yuuki Fan Standard",
        "m_500_rated": "Next Division Aegis",
        "m_mediocre_majority": "Rogue Labor Canon",
        "m_rating_spree": "Police Medals Verdict",
        "m_score_variance": "Labor Combat Measure",
        "m_binge_rater": "Hidden File Passage",
        "m_reread_rerate": "Classic Fan Banner Banner",
        "m_masterpiece_hunter": "Sv2 Hq Banner",
        "m_contrarian": "Perfect Issue Aegis",
        "m_optimist": "Labor Critic Accord Accord",
        "m_score_distributor": "All Cases Balance",
        "m_genre_critic": "Hidden File Critic",
        "m_mean_above_8": "Labor Combat Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Police Labor Season",
        "m_valentines_read": "Sv2 Antics Observance",
        "m_pi_day": "Rogue Labor Testament Testament",
        "m_april_fools": "Case Archives Devotion",
        "m_international_manga_day": "Night Duty Aegis",
        "m_free_comic_day": "Oshii Master Chronicle",
        "m_summer_solstice": "Police Master Focus Focus",
        "m_tanabata": "Daily Duty Tanabata",
        "m_friday_13th": "Oshii Classic Dominion Dominion",
        "m_halloween_read": "Endless Duty Halloween",
        "m_thanksgiving_binge": "Labor Review Charge",
        "m_christmas_read": "Night Shift Pact",
        "m_new_years_eve": "Police Master Pilgrimage",
        "m_birthday_read": "Noa's Crew Focus",
        "m_holiday_marathon": "Rookie Ace Rally",
        "m_independence_day": "Perfect Issue Aegis Aegis",
        "m_culture_day": "Next Division Seal Seal",
        "m_spring_equinox": "Endless Duty Dominion",
        "m_earth_day": "Noa's Crew Trial",
        "m_labor_day": "Night Shift Seal",
        "m_winter_solstice": "City Patrol Focus Focus",
        "m_manga_birthday": "Daily Duty Ritual",
        "m_every_holiday_reader": "Labor Scouting Watch",
        "m_consecutive_holidays": "Oshii Classic Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Daily Shift Aegis",
        "m_fibonacci": "Case Resolved Dominion",
        "m_palindrome_day": "Rogue Labor Relic",
        "m_binary_day": "City Patrol Proof",
        "m_full_moon_read": "Special Vehicles Section Crown",
        "m_leap_year_read": "All Night Practice",
        "m_triple_seven": "Sv2 Team Trial Trial",
        "m_thousand_complete": "Sv2 Team Ascension",
        "m_nice": "Police Network Seal Seal",
        "m_power_level_chapters": "Quick Response Aegis",
        "m_answer_42": "Special Vehicles Section Trial",
        "m_square_number": "Police Drama Standard",
        "m_prime_count": "Sv2 Team Pinnacle",
        "m_matching_date": "Labor Scouting Mantle",
        "m_century_chapter": "Daily Shift Decree",
        "m_pi_chapters": "Noa's Crew Proof Proof",
        "m_synchronicity": "Sv2 Antics Emblem",
        "m_world_record": "Cases Solved Warrant",
        "m_genre_clash": "Near Future Clash",
        "m_time_traveler": "Oshii's Depth Decree",
        "m_double_digits": "Unit Roster Dominion",
        "m_one_two_three": "Labor Arsenal Banner Banner",
        "m_lucky_seven": "All Cases Solved Record Record",
        "m_exact_hundred_ch": "Case Resolved Legend",
        "m_year_match_count": "Holiday Duty Routine",
        "m_chapter_match_date": "City Patrol Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Unit Roster Index",
        "m_manhwa_format": "Endless Duty Gallery",
        "m_manhua_format": "Top Officer Storehouse",
        "m_ln_format": "Sv2 Team Index",
        "m_oneshot_format": "Rogue Labor Index",
        "m_doujin_format": "Police Medals Cabinet",
        "m_novel_format": "Case Archives Reserve Reserve",
        "m_format_master_manga": "Police Medals Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Oshii's Depth Link",
        "m_meta_collector": "Next Division Reliquary",
        "m_meta_category_starter": "Labor Art Standard",
        "m_meta_tier_climber": "Labor Critic Token",
        "m_meta_tier_max": "Complete Force",
        "m_meta_xp_earner": "Unit Roster Anchor",
        "m_meta_difficulty_easy": "Sv2 Team Panel",
        "m_meta_difficulty_hard": "Police Labor Node",
        "m_meta_unlock_spree": "Unit Roster Marker",
        "m_meta_completionist": "Full Library",
        "m_meta_diverse": "Rogue Labor Anchor",
        "m_meta_dominator": "Police Network Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#010408",
        primary: "#1958a8",
        secondary: "#104488",
        accent: "#b8c840",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/patlabor.jpg",
    particleColor: "#4080d0",
    backgroundDim: 0.38,
    backgroundBlur: 20,
    particleTypes: {
        rain: { label: "Tokyo Rain", maxCount: 30, defaultEnabled: true, defaultIntensity: 60 },
        sparks: { label: "Labor Sparks", maxCount: 10, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
  1: "Threadbare Generic Rank Spark",
  8: "Generic's Tarnished Omen",
  14: "Fractured Generic Rank",
  21: "Generic Rank Path",
  28: "Lowborn Legacy Myth",
  35: "Generic Rank Pulse",
  41: "Generic's Legacy Crest",
  48: "Humble Generic Mark",
  55: "Ragged Generic Rank Vow",
  61: "Generic's Faint Echo",
  68: "Lesser Generic Rank",
  75: "Generic Rank Zenith",
  81: "Doubtful Legacy Bloom",
  88: "Generic Rank Sigil",
  95: "Generic's Legacy Flame",
  102: "Really Cool Generic Spark",
  108: "Awakened Generic Rank Omen",
  115: "Generic's Resolute Seal",
  122: "Rising Generic Rank",
  128: "Generic Rank Myth",
  135: "Dauntless Legacy Pulse",
  142: "Generic Rank Crest",
  149: "Generic's Legacy Mark",
  155: "Fresh Generic Vow",
  162: "Valiant Generic Rank Echo",
  169: "Generic's Prime Crown",
  175: "Polished Generic Rank",
  182: "Generic Rank Bloom",
  189: "Stormlit Legacy Sigil",
  195: "Generic Rank Flame",
  202: "Generic's Legacy Spark",
  209: "Tempered Generic Omen",
  216: "Trusted Generic Rank Seal",
  222: "Generic's Steadfast Path",
  229: "Ironclad Generic Rank",
  236: "Veteran Legacy Pulse",
  242: "Core Legacy Crest",
  249: "Generic Rank Mark",
  256: "Generic's Legacy Vow",
  262: "Formidable Generic Echo",
  269: "Lucid Generic Rank Crown",
  276: "Generic's Ranked Zenith",
  283: "Fabled Generic Rank",
  289: "Grand Legacy Sigil",
  296: "Seasoned Legacy Flame",
  303: "Generic Rank Spark",
  309: "Generic's Legacy Omen",
  316: "Valorous Generic Seal",
  323: "Stalwart Generic Rank Path",
  330: "Generic's Commanding Myth",
  336: "Refined Generic Rank",
  343: "Unbroken Legacy Crest",
  350: "Blazing Legacy Mark",
  356: "Generic Rank Vow",
  363: "Generic's Legacy Echo",
  370: "Peerless Generic Crown",
  376: "Ardent Generic Rank Zenith",
  383: "Generic's Focused Bloom",
  390: "Vigilant Generic Rank",
  397: "Dominant Legacy Flame",
  403: "Elite Legacy Spark",
  410: "Generic Rank Omen",
  417: "Generic's Legacy Seal",
  423: "Sovereign Generic Path",
  430: "Regal Generic Rank Myth",
  437: "Generic's Crowned Pulse",
  444: "Mythborn Generic Rank",
  450: "Limitless Legacy Mark",
  457: "Radiant Legacy Vow",
  464: "Generic Rank Echo",
  470: "Generic's Legacy Crown",
  477: "Climactic Generic Zenith",
  484: "Epic Generic Rank Bloom",
  490: "Generic's Unreal Sigil",
  497: "Peak Generic Rank",
  504: "Supreme Legacy Spark",
  511: "Exalted Legacy Omen",
  517: "Generic Rank Seal",
  524: "Generic's Legacy Path",
  531: "Celestial Generic Myth",
  537: "Phantom Generic Rank Pulse",
  544: "Generic's Crimson Crest",
  551: "Silver Generic Rank",
  557: "Golden Legacy Vow",
  564: "Feral Legacy Echo",
  571: "Generic Rank Crown",
  578: "Generic's Legacy Zenith",
  584: "Dread Generic Bloom",
  591: "Luminous Generic Rank Sigil",
  598: "Generic's Thunderous Flame",
  604: "Ultraviolet Generic Rank",
  611: "Unleashed Legacy Omen",
  618: "Secret Legacy Seal",
  625: "Final Generic Path",
  631: "Generic's Legacy Myth",
  638: "Worldclass Generic Pulse",
  645: "Lawless Generic Rank Crest",
  651: "Generic's Chosen Mark",
  658: "Fearless Generic Rank",
  665: "Overdrive Legacy Echo",
  671: "Cinematic Legacy Crown",
  678: "Impossible Generic Zenith",
  685: "Generic's Legacy Bloom",
  692: "Canonized Generic Sigil",
  698: "Ascendant Generic Rank Flame",
  705: "Generic's Transfigured Spark",
  712: "Immortal Generic Rank",
  718: "Eclipsed Legacy Seal",
  725: "Astral Legacy Path",
  732: "Sublime Generic Myth",
  739: "Generic's Legacy Pulse",
  745: "Prismatic Generic Crest",
  752: "Abyssal Generic Rank Mark",
  759: "Generic's Unbound Vow",
  765: "Eternal Generic Rank",
  772: "Cosmic Legacy Crown",
  779: "Transcendent Legacy Zenith",
  785: "Perfected Generic Bloom",
  792: "Generic's Legacy Sigil",
  799: "Ultimate Generic Flame",
  806: "Mythic Generic Rank Spark",
  812: "Generic's Godlike Omen",
  819: "Canonical Generic Rank",
  826: "Reality-Bent Legacy Path",
  832: "Heavenly Legacy Myth",
  839: "Absolute Generic Pulse",
  846: "Untouchable Generic Crest",
  852: "Timeless Generic Mark",
  859: "Empyrean Generic Rank Vow",
  866: "Generic's Primordial Echo",
  873: "Omniscient Generic Rank",
  879: "Unfathomed Legacy Zenith",
  886: "Apocalyptic Legacy Bloom",
  893: "Seraphic Generic Sigil",
  899: "Omega Generic Flame",
  906: "Final Generic Spark",
  913: "Crowned Generic Rank Omen",
  920: "Generic's Mythic Seal",
  926: "Absolute Generic Rank",
  933: "Eternal Legacy Myth",
  940: "Cosmic Legacy Pulse",
  946: "Transcendent Generic Crest",
  953: "Perfected Generic Mark",
  960: "Definitive Generic Vow",
  966: "Ultimate Generic Rank Echo",
  973: "Generic's Infinite Crown",
  980: "Sovereign Generic Rank",
  987: "Celestial Legacy Bloom",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate Generic Rank"
},
}
