import { AnimeThemeConfig } from "./types"
import { GiHeartKey, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiCrystalBall, GiStarSwirl, GiSpellBook, GiFlowerEmblem } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const plasticMemoriesTheme: AnimeThemeConfig = {
    id: "plastic-memories",
    displayName: "Plastic Memories",
    description: "In a future where androids called Giftias live among humans, Tsukasa works to retrieve them before their memories expire. Partnered with Giftia Isla, he learns that limited time only deepens love.",
    cssVars: {
        "--color-brand-200": "185 215 250",
        "--color-brand-300": "128 175 240",
        "--color-brand-400": "75 132 222",
        "--color-brand-500": "35 92 195",
        "--color-brand-600": "12 58 155",
        "--color-brand-700": "4 32 112",
        "--color-brand-800": "1 15 70",
        "--color-brand-900": "0 5 36",
        "--color-brand-950": "0 1 15",
        "--brand": "35 92 195",
        "--background": "#000208",
        "--paper": "#000412",
        "--color-gray-950": "0 2 8",
        "--color-gray-900": "1 5 18",
        "--color-gray-800": "3 12 35",
        "--color-gray-700": "6 22 58",
        "--color-gray-600": "10 40 90",
        "--color-gray-500": "18 68 128",
        "--color-gray-400": "38 105 165",
        "--color-gray-300": "72 148 202",
        "--color-gray-200": "115 188 228",
        "--color-gray-100": "168 218 245",
        "--color-gray-50": "218 238 255",
    },
    sidebarOverrides: {
        "home": { icon: GiFlowerEmblem, label: "Isla's World" },
        "schedule": { icon: GiAlarmClock, label: "Retrieval Schedule" },
        "manga": { icon: LuBookOpen, label: "Memory Log" },
        "lists": { icon: GiScrollUnfurled, label: "Giftia Registry" },
        "discover": { icon: GiBullseye, label: "New Terminals" },
        "torrent-list": { icon: GiStarSwirl, label: "Memory Cache" },
        "debrid": { icon: GiHeartKey, label: "Memory Vault" },
        "unmatched": { icon: GiCrystalBall, label: "Unresolved Cases" },
        "enmasse": { icon: GiResize, label: "Mass Retrieval" },
        "scan-summaries": { icon: TbReportSearch, label: "Terminal Reports" },
        "auto-downloader": { icon: LuRss, label: "Memory Feed" },
        "community": { icon: GiSpellBook, label: "SAI Corp Circle" },
        "achievements": { icon: GiTrophyCup, label: "Memory Trophies" },
        "milestones": { icon: LuFlag, label: "Time Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Terminal Alerts" },
        "theme-manager": { icon: GiPalette, label: "Memory Colors" },
        "extensions": { icon: BiExtension, label: "Memory Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Memory Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Terminal Config" },
    },
    achievementNames: {
        "a_first_episode": "First Assignment",
        "a_first_complete": "First Retrieval",
        "a_hundred_club": "Hundred Memories Saved",
        "a_binge_king": "Plastic Memories Marathon",
        "a_completionist": "All Terminals Retrieved",
        "a_mega_completionist": "Memory Complete",
        "a_loyal_fan": "Memory Keeper",
        "a_zero_to_hero": "Rookie to Partner",
        "m_first_chapter": "First Memory",
        "m_completionist": "Full Memory Archive",
    },
    musicUrl: "",
    previewColors: {
        bg: "#000208",
        primary: "#235cc3",
        secondary: "#cc8888",
        accent: "#c8e0f8",
    },
    particleColor: "#5090d8",
    backgroundDim: 0.32,
    backgroundBlur: 25,
    milestoneNames: {
    1: "Generic Rank",
    7: "Generic Rank",
    14: "Generic Rank",
    21: "Generic Rank",
    27: "Generic Rank",
    34: "Generic Rank",
    41: "Generic Rank",
    47: "Generic Rank",
    54: "Generic Rank",
    61: "Generic Rank",
    68: "Generic Rank",
    74: "Generic Rank",
    81: "Generic Rank",
    88: "Generic Rank",
    94: "Generic Rank",
    101: "Generic Rank",
    108: "Generic Rank",
    114: "Generic Rank",
    121: "Generic Rank",
    128: "Generic Rank",
    135: "Generic Rank",
    141: "Generic Rank",
    148: "Generic Rank",
    155: "Generic Rank",
    161: "Generic Rank",
    168: "Generic Rank",
    175: "Generic Rank",
    182: "Generic Rank",
    188: "Generic Rank",
    195: "Generic Rank",
    202: "Generic Rank",
    208: "Generic Rank",
    215: "Generic Rank",
    222: "Generic Rank",
    228: "Generic Rank",
    235: "Generic Rank",
    242: "Generic Rank",
    249: "Generic Rank",
    255: "Generic Rank",
    262: "Generic Rank",
    269: "Generic Rank",
    275: "Generic Rank",
    282: "Generic Rank",
    289: "Generic Rank",
    296: "Generic Rank",
    302: "Generic Rank",
    309: "Generic Rank",
    316: "Generic Rank",
    322: "Generic Rank",
    329: "Generic Rank",
    336: "Generic Rank",
    342: "Generic Rank",
    349: "Generic Rank",
    356: "Generic Rank",
    363: "Generic Rank",
    369: "Generic Rank",
    376: "Generic Rank",
    383: "Generic Rank",
    389: "Generic Rank",
    396: "Generic Rank",
    403: "Generic Rank",
    409: "Generic Rank",
    416: "Generic Rank",
    423: "Generic Rank",
    430: "Generic Rank",
    436: "Generic Rank",
    443: "Generic Rank",
    450: "Generic Rank",
    456: "Generic Rank",
    463: "Generic Rank",
    470: "Generic Rank",
    477: "Generic Rank",
    483: "Generic Rank",
    490: "Generic Rank",
    497: "Generic Rank",
    503: "Generic Rank",
    510: "Generic Rank",
    517: "Generic Rank",
    523: "Generic Rank",
    530: "Generic Rank",
    537: "Generic Rank",
    544: "Generic Rank",
    550: "Generic Rank",
    557: "Generic Rank",
    564: "Generic Rank",
    570: "Generic Rank",
    577: "Generic Rank",
    584: "Generic Rank",
    591: "Generic Rank",
    597: "Generic Rank",
    604: "Generic Rank",
    611: "Generic Rank",
    617: "Generic Rank",
    624: "Generic Rank",
    631: "Generic Rank",
    637: "Generic Rank",
    644: "Generic Rank",
    651: "Generic Rank",
    658: "Generic Rank",
    664: "Generic Rank",
    671: "Generic Rank",
    678: "Generic Rank",
    684: "Generic Rank",
    691: "Generic Rank",
    698: "Generic Rank",
    704: "Generic Rank",
    711: "Generic Rank",
    718: "Generic Rank",
    725: "Generic Rank",
    731: "Generic Rank",
    738: "Generic Rank",
    745: "Generic Rank",
    751: "Generic Rank",
    758: "Generic Rank",
    765: "Generic Rank",
    772: "Generic Rank",
    778: "Generic Rank",
    785: "Generic Rank",
    792: "Generic Rank",
    798: "Generic Rank",
    805: "Generic Rank",
    812: "Generic Rank",
    818: "Generic Rank",
    825: "Generic Rank",
    832: "Generic Rank",
    839: "Generic Rank",
    845: "Generic Rank",
    852: "Generic Rank",
    859: "Generic Rank",
    865: "Generic Rank",
    872: "Generic Rank",
    879: "Generic Rank",
    886: "Generic Rank",
    892: "Generic Rank",
    899: "Generic Rank",
    906: "Generic Rank",
    912: "Generic Rank",
    919: "Generic Rank",
    926: "Generic Rank",
    932: "Generic Rank",
    939: "Generic Rank",
    946: "Generic Rank",
    953: "Generic Rank",
    959: "Generic Rank",
    966: "Generic Rank",
    973: "Generic Rank",
    979: "Generic Rank",
    986: "Generic Rank",
    993: "Generic Rank",
    1000: "Generic Rank",
  },
}
