import { AnimeThemeConfig } from "./types"
import { GiPokecog, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiSpellBook, GiScrollUnfurled, GiCrystalBall, GiRunningShoe, GiFireworkRocket } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const pokemonTheme: AnimeThemeConfig = {
    id: "pokemon",
    displayName: "Pokémon",
    description: "Gotta catch 'em all! Ash and Pikachu travel across Kanto and beyond, battling Gym Leaders, foiling Team Rocket, and forging bonds with incredible creatures.",
    fontFamily: "'Fredoka One', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap",
    cssVars: {
        "--color-brand-200": "255 218 100",
        "--color-brand-300": "255 195 50",
        "--color-brand-400": "248 168 0",
        "--color-brand-500": "220 138 0",
        "--color-brand-600": "175 102 0",
        "--color-brand-700": "128 65 0",
        "--color-brand-800": "82 36 0",
        "--color-brand-900": "44 16 0",
        "--color-brand-950": "20 6 0",
        "--brand": "220 138 0",
        "--background": "#080400",
        "--paper": "#130800",
        "--color-gray-950": "8 4 0",
        "--color-gray-900": "18 9 0",
        "--color-gray-800": "36 18 2",
        "--color-gray-700": "58 32 5",
        "--color-gray-600": "88 55 15",
        "--color-gray-500": "130 88 32",
        "--color-gray-400": "175 130 60",
        "--color-gray-300": "215 175 100",
        "--color-gray-200": "240 210 145",
        "--color-gray-100": "252 235 192",
        "--color-gray-50": "255 248 228",
    },
    sidebarOverrides: {
        "home": { icon: GiRunningShoe, label: "Pallet Town" },
        "schedule": { icon: GiAlarmClock, label: "Gym Schedule" },
        "manga": { icon: LuBookOpen, label: "Pokédex" },
        "lists": { icon: GiScrollUnfurled, label: "Pokémon Roster" },
        "discover": { icon: GiBullseye, label: "Discover Routes" },
        "torrent-list": { icon: GiFireworkRocket, label: "Item Cache" },
        "debrid": { icon: GiCrystalBall, label: "Safari Vault" },
        "unmatched": { icon: GiSpellBook, label: "Unknown Pokémon" },
        "enmasse": { icon: GiResize, label: "Mass Release" },
        "scan-summaries": { icon: TbReportSearch, label: "Battle Reports" },
        "auto-downloader": { icon: LuRss, label: "New Pokémon Alert" },
        "community": { icon: GiTrophyCup, label: "Trainer Club" },
        "achievements": { icon: GiTrophyCup, label: "League Badges" },
        "milestones": { icon: LuFlag, label: "Journey Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Trainer Alerts" },
        "theme-manager": { icon: GiPalette, label: "Type Colors" },
        "extensions": { icon: BiExtension, label: "TM Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "PC Box Sync" },
        "settings": { icon: GiSettingsKnobs, label: "PC Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Catch",
        "a_episode_counter": "Pokedex Mark",
        "a_episode_titan": "Earned Relic",
        "a_hours_invested": "League Badges Proof",
        "a_time_lord": "Pokémon Master",
        "a_anime_collector": "Pok Catalogue",
        "a_library_legend": "Mass Release Library",
        "a_first_complete": "Badge Earned",
        "a_hundred_club": "Hundred Caught",
        "a_first_day": "Marathon Seal",
        "a_first_rating": "Earned Appraisal",
        "a_ten_thousand_min": "Pallet Standard",
        "a_season_veteran": "Town Library",
        "a_year_explorer": "Marathon Map",
        "a_century_watcher": "Unknown Pok Ledger",
        "a_five_hundred_eps": "Type Dominion",
        "a_thousand_eps": "Battle Record",
        "a_watching_ten": "Journey Acclaim",
        "a_ptw_hoarder": "Pallet Library",
        "a_dropped_honesty": "Item Summit",
        "a_five_thousand_eps": "Safari Vault Warrant",
        "a_ten_completed": "Mass Release Afterglow",
        "a_fifty_completed": "Alert Ascension",
        "a_five_hundred_completed": "Caught Clear",
        "a_mean_score_tracker": "Town Verdict",
        "a_unique_studios": "Pikachu Collection",
        "a_days_spent_watching": "League Badges Dominion",
        "a_all_status": "Routes Testament",
        "a_first_favorite": "Kanto Cabinet",
        "a_favorites_collector": "Pikachu Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Town Champion Drive",
        "a_marathon_runner": "Battle Gauntlet",
        "a_weekend_warrior": "Earned Ordeal",
        "a_non_stop": "Pokemon Fever",
        "a_one_more_episode": "Gotta Mantle",
        "a_speed_run": "Ash Vigil",
        "a_double_feature": "Pallet Town Crown",
        "a_triple_threat": "Journey Record",
        "a_five_a_day": "Town Accord",
        "a_back_to_back": "Caught Surge",
        "a_seasonal_binge": "Gym Cascade",
        "a_cour_crusher": "Master Ordeal",
        "a_half_day_watch": "Master Crown",
        "a_full_day_watch": "Pokemon Marathon Pinnacle",
        "a_power_weekend": "Nighttime Encounter Run",
        "a_binge_king": "Pokémon Marathon",
        "a_no_sleep": "Town Vigil",
        "a_entire_season": "Pikachu Library",
        "a_seven_day_challenge": "Pokedex Mark Mark",
        "a_hundred_day_binge": "Town Surge",
        "a_genre_binge": "Battle Binge",
        "a_studio_binge": "Master Fever",
        "a_season_sweep": "Encounter Codex",
        "a_forty_eight_hour": "Marathon Overture",
        "a_ep_counter_day": "Pc Box Aegis",
        "a_multi_series_binge": "Marathon Streak",
        "a_midnight_binge": "Town Champion Cascade",
        "a_new_year_binge": "Encounter Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Gym Leaders Action",
        "a_genre_adventure": "Trainer Adventure",
        "a_genre_comedy": "Journey Comedy",
        "a_genre_drama": "Catch Drama",
        "a_genre_fantasy": "Safari Vault Fantasy",
        "a_genre_horror": "Alert Horror",
        "a_genre_mystery": "Journey Mystery",
        "a_genre_romance": "Caught Romance",
        "a_genre_scifi": "Trainer Sci-Fi",
        "a_genre_sol": "Encounter Slice",
        "a_genre_sports": "Town Sports",
        "a_genre_supernatural": "Safari Vault Supernatural",
        "a_genre_thriller": "Trainer Thriller",
        "a_genre_mecha": "Pokemon Marathon Mecha",
        "a_genre_music": "Roster Music",
        "a_genre_psychological": "Pikachu Psychological",
        "a_genre_ecchi": "Pok Ecchi",
        "a_genre_mahou_shoujo": "Mass Release Magic Shoujo",
        "a_tag_isekai": "Nighttime Encounter Isekai",
        "a_tag_harem": "Safari Vault Harem",
        "a_tag_bl": "Team Rocket Bl",
        "a_tag_gl": "Gotta Gl",
        "a_tag_historical": "Unknown Pok Historical",
        "a_tag_military": "Type Military",
        "a_tag_school": "Pallet School",
        "a_tag_martial_arts": "Type Martial Arts",
        "a_tag_vampire": "Journey Vampire",
        "a_tag_samurai": "Ash Samurai",
        "a_tag_space": "Catch Space",
        "a_tag_parody": "Safari Vault Parody",
        "a_tag_idol": "Roster Idol",
        "a_tag_post_apocalyptic": "Ash Post Apocalyptic",
        "a_tag_cyberpunk": "Champion Cyberpunk",
        "a_tag_shounen": "Ash Shounen",
        "a_tag_seinen": "Caught Seinen",
        "a_tag_shoujo": "Journey Shoujo",
        "a_tag_josei": "Caught Josei",
        "a_tag_survival": "Pikachu Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "Pokédex Complete",
        "a_mega_completionist": "Champion Trainer",
        "a_completion_rate_50": "Champion Trainer Return",
        "a_completion_rate_75": "Encounter Crown",
        "a_completion_rate_90": "Catch Resolution",
        "a_no_drop": "Champion Trainer Decree",
        "a_long_runner_complete": "Team Rocket Clear",
        "a_sequel_chain": "Ash Insignia",
        "a_clean_list": "Gym Relic",
        "a_from_ptw": "Gym Index",
        "a_rewatch_master": "Nighttime Encounter Return",
        "a_short_complete": "Town Champion Endgame",
        "a_same_day_start_finish": "Encounter Pinnacle",
        "a_revival": "Trainer Alerts Insignia",
        "a_zero_to_hero": "Pallet Town to Champion",
        "a_five_genre_complete": "Pokemon A Five Genre Complete",
        "a_full_franchise": "Town Chronicle",
        "a_batch_complete": "Gym Crown",
        "a_paused_to_done": "Pc Box Aegis Aegis",
        "a_completion_spree": "Pokedex Triumph",
        "a_multi_rewatch": "Type Triumph",
        "a_dropped_recovery": "Loyal Conquest",
        "a_ten_perfect_scores": "Pallet Acclaim",
        "a_seasonal_clear": "League Badges Codex",
        "a_complete_genre_span": "Pokedex A Complete Genre Span",
        "a_monthly_completions": "Team Rocket Afterglow",
        "a_yearly_completions": "Pokemon Epilogue",
        "a_rapid_complete": "Loyal Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Trainer",
        "a_studio_devotee": "Catch Treasury",
        "a_rewatcher": "Journey Closure",
        "a_triple_rewatch": "Pikachu Coda",
        "a_annual_tradition": "Loyal Proof",
        "a_director_fan": "Pokemon Master Trial",
        "a_voice_actor_fan": "League Badges Crown",
        "a_ost_lover": "Team Rocket Seal",
        "a_source_reader": "Loyal Trainer Cabinet",
        "a_waiting_weekly": "Caught Clock",
        "a_childhood_revisit": "Item Seal",
        "a_saga_tracker": "Pc Box Standard",
        "a_genre_loyalty": "Gym Loyalty",
        "a_decade_watcher": "Mass Release Banner",
        "a_adaptation_hunter": "Encounter Trial",
        "a_original_anime_fan": "Gotta Testament",
        "a_long_commitment": "Type Mark",
        "a_perfect_attendance": "Pc Box Standard Standard",
        "a_favorite_studio_5": "Nighttime Library",
        "a_complete_catalog": "Trainer Alerts Seal",
        "a_franchise_collector": "Nighttime Archive",
        "a_airing_follower": "Catch Signal",
        "a_genre_master": "Safari Vault Master",
        "a_staff_follower": "Unknown Pok Oath",
        "a_multi_season_fan": "Ash Hoard",
        "a_format_diversity": "Mass Release Cache",
        "a_year_dedication": "Encounter Tenure",
        "a_season_dedication": "Loyal Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Pikachu Explorer",
        "a_studio_hopper": "Loyal Trainer Collection",
        "a_tag_explorer": "Alert Explorer",
        "a_decade_hopper": "Town Chronicle Chronicle",
        "a_hidden_gem": "League Badges Warrant",
        "a_popular_taste": "Team Rocket Decree",
        "a_retro_appreciator": "Trainer Alerts Aegis",
        "a_modern_viewer": "Alert Pinnacle",
        "a_cross_demographic": "Pokemon Pinnacle",
        "a_underdog_fan": "League Badges Trial",
        "a_variety_week": "Pikachu Horizon",
        "a_foreign_cinema": "Town Champion Expedition",
        "a_classic_connoisseur": "Roster Glimpse",
        "a_every_season": "Champion Trainer Archive",
        "a_award_winner": "Loyal Trainer Insignia",
        "a_niche_explorer": "Catch Horizon",
        "a_global_anime": "Pallet Town Crown Crown",
        "a_cult_classic": "Marathon Classic",
        "a_random_pick": "Loyal Trainer Decree",
        "a_new_genre_month": "Catch A New Genre Month",
        "a_seasonal_completionist": "Unknown Pok Summit",
        "a_unpopular_opinion": "Pikachu Standard",
        "a_top_rated_viewer": "Pallet Seal",
        "a_source_variety": "Type Storehouse",
        "a_low_score_brave": "Pok Measure",
        "a_upcoming_watcher": "Team Rocket Seal Seal",
        "a_short_series_explorer": "Pallet Town Expedition",
        "a_long_series_explorer": "Pokemon Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Nighttime Encounter",
        "a_early_bird": "Item Banner",
        "a_lunch_break": "Pallet Town Trial",
        "a_golden_hour": "League Badges Tenure",
        "a_four_am_club": "Type Gathering",
        "a_witching_hour": "Alert Tenure",
        "a_new_year_watch": "Gym Season",
        "a_midnight_premiere": "Gym Devotion",
        "a_all_hours": "Battle Seal",
        "a_dawn_warrior": "Loyal Trainer Aegis",
        "a_afternoon_delight": "Pokedex Proof",
        "a_prime_time": "Roster Insignia",
        "a_workday_watcher": "Champion Pinnacle",
        "a_sunday_marathon": "Marathon Momentum",
        "a_rainy_day": "Safari Vault Relic",
        "a_morning_routine": "Kanto Promise",
        "a_night_shift": "Caught Aegis",
        "a_twilight_zone": "Kanto Ledger",
        "a_seasonal_premier": "Caught Cabinet",
        "a_clock_collector": "Pokemon Marathon Repository",
        "a_weekend_binge_hours": "Catch Streak",
        "a_late_night_regular": "Routes Dominion",
        "a_sunrise_watcher": "Pokemon Master Relic",
        "a_holiday_watcher": "Marathon Pact",
        "a_every_day_of_week": "Caught Ledger",
        "a_monthly_hours": "Pallet Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Caught Record",
        "a_party_host": "Champion Trainer Record",
        "a_social_butterfly": "Marathon Company",
        "a_group_binge": "Battle Sprint",
        "a_party_regular": "Nighttime Chronicle",
        "a_sync_viewer": "Pokemon Marathon Standard",
        "a_commentator": "Pikachu Record",
        "a_party_marathon": "Nighttime Vigil",
        "a_full_house": "Master Trial",
        "a_community_pillar": "Town Champion Alliance",
        "a_watch_party_streak": "Nighttime Vigil Vigil",
        "a_diverse_party": "Battle Seal Seal",
        "a_late_night_party": "Routes Testament Testament",
        "a_party_veteran": "Pokemon Marathon Testament",
        "a_genre_party": "Gotta Party",
        "a_weekly_party": "Loyal Calendar",
        "a_silent_viewer": "Pallet Town Mantle",
        "a_recommendation_giver": "Item Network",
        "a_party_completionist": "Caught Coda",
        "a_social_scorer": "Safari Vault Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Pokemon Proof",
        "a_fibonacci": "Alert Dominion",
        "a_palindrome_day": "Gym Relic Relic",
        "a_binary_day": "Gym Mark",
        "a_full_moon": "Item Insignia",
        "a_leap_year": "Champion Devotion",
        "a_time_traveler": "Journey Record Record",
        "a_genre_clash": "Pikachu Clash",
        "a_triple_seven": "Gym Testament",
        "a_thousand_complete": "Gotta Epilogue",
        "a_pi_episodes": "Pokemon Crown",
        "a_synchronicity": "Master Anchor",
        "a_world_record": "Type Warrant",
        "a_nice": "Team Rocket Chronicle",
        "a_power_level": "Pikachu Accord",
        "a_answer_42": "Town Standard",
        "a_square_number": "Nighttime Decree",
        "a_prime_count": "Town Champion Warrant",
        "a_matching_date": "Master Mantle",
        "a_century_episode": "Pok Mark",
        "a_double_digits": "Gym Testament Testament",
        "a_one_two_three": "Trainer Alerts Decree",
        "a_lucky_seven": "Gym Leaders Crown",
        "a_all_tens": "Pallet Town Criterion",
        "a_exact_hundred_eps": "Catch Standard",
        "a_year_match_count": "Catch Clock",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Item Ledger",
        "a_movie_buff": "Type Mark Mark",
        "a_ova_hunter": "Champion Trainer Standard",
        "a_ona_explorer": "Pokemon Marathon Secret",
        "a_special_watcher": "Encounter Relic",
        "a_short_king": "Encounter Crown Crown",
        "a_variety_pack": "Loyal Inquiry",
        "a_film_festival": "Nighttime Encounter Chronicle",
        "a_music_video": "Battle Chronicle",
        "a_tv_short": "Nighttime Record",
        "a_movie_marathon": "Battle Gauntlet Gauntlet",
        "a_double_length": "Gotta Crown",
        "a_anthology": "Item Aegis",
        "a_mini_series": "Kanto Decree",
        "a_theatrical": "Ash Accord",
        "a_format_master": "Type Vault",
        "a_long_movie": "Pikachu Insignia",
        "a_back_catalog": "Pikachu Standard Standard",
        "a_cm_watcher": "Marathon Aegis",
        "a_pv_collector": "Pokemon Marathon Storehouse",
        "a_format_balance": "Loyal Vault",
        "a_episodic_master": "Roster Standard",
        "a_sequel_movie": "Pallet Town Pinnacle",
        "a_recap_watcher": "Pok Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Master Devotion",
        "a_mega_streak": "Catch Streak Streak",
        "a_weekly_warrior": "Pokedex Season",
        "a_monthly_watcher": "Earned Calendar",
        "a_comeback": "Roster Decree",
        "a_weekend_streak": "Pok Passage",
        "a_no_zero_days": "Encounter Warrant",
        "a_iron_will": "Loyal Trainer Seal",
        "a_habit_formed": "Earned Warrant",
        "a_consistent_pace": "Pokemon Measure",
        "a_year_long": "Gym Leaders Season",
        "a_double_streak": "Trainer Watch",
        "a_streak_recovery": "Town Champion Season",
        "a_daily_minimum": "Alert Focus",
        "a_winter_streak": "Champion Watch",
        "a_summer_streak": "Trainer Resolve",
        "a_morning_streak": "Nighttime Clock",
        "a_night_streak": "Caught Constancy",
        "a_unbreakable": "Encounter Proof",
        "a_eternal_flame": "Marathon Standard",
        "a_completion_streak": "Item Return",
        "a_rating_streak": "Gym Balance",
        "a_multi_ep_streak": "Type Ritual",
        "a_genre_streak": "Trainer Streak",
        "a_studio_streak": "Nighttime Encounter Cabinet",
        "a_perfect_week": "Master Relic",

        // ── ANIME SCORING ──
        "a_critic": "Pokedex Scrutiny",
        "a_perfect_ten": "Item Audit",
        "a_harsh_critic": "Pc Box Gauge",
        "a_fair_judge": "Pallet Town Balance",
        "a_generous_spirit": "Encounter Pinnacle Pinnacle",
        "a_score_all": "Loyal Criterion",
        "a_wide_range": "Team Rocket Ledger",
        "a_controversial": "Ash Decree",
        "a_consistent_scorer": "Journey Verdict",
        "a_score_sniper": "Champion Score",
        "a_evolving_taste": "Encounter Testament",
        "a_bell_curve": "Champion Trainer Insignia",
        "a_picky_watcher": "Pallet Seal Seal",
        "a_100_rated": "Type Warrant Warrant",
        "a_500_rated": "Trainer Pinnacle",
        "a_mediocre_majority": "Pokedex Canon",
        "a_rating_spree": "Unknown Pok Review",
        "a_score_variance": "Gotta Score",
        "a_masterpiece_hunter": "Nighttime Banner",
        "a_contrarian": "Unknown Pok Record",
        "a_optimist": "Unknown Pok Ledger Ledger",
        "a_score_distributor": "Pallet Town Appraisal",
        "a_genre_critic": "Town Champion Critic",
        "a_mean_above_8": "Pokemon Marathon Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "Master Resolve",
        "a_valentines_weeb": "Ash Vow",
        "a_pi_day": "Gotta Trial",
        "a_april_fools": "Town Champion Devotion",
        "a_international_anime_day": "Champion Pinnacle Pinnacle",
        "a_star_wars_day": "Marathon Chronicle",
        "a_summer_solstice": "Alert Calendar",
        "a_tanabata": "Trainer Focus",
        "a_friday_13th": "Pokemon Relic",
        "a_halloween_spirit": "Mass Release Vow",
        "a_thanksgiving_binge": "Pikachu Run",
        "a_christmas_special": "Routes Season",
        "a_new_years_eve": "League Badges Pilgrimage",
        "a_birthday_watch": "Pc Box Vow",
        "a_holiday_marathon": "Trainer Alerts Overture",
        "a_independence_day": "Pallet Banner",
        "a_culture_day": "Team Rocket Insignia",
        "a_spring_equinox": "Unknown Pok Decree",
        "a_earth_day": "Gym Leaders Mantle",
        "a_labor_day": "Catch Seal",
        "a_winter_solstice": "Pallet Town Pilgrimage",
        "a_anime_birthday": "Master Pilgrimage",
        "a_every_holiday": "Safari Vault Resolve",
        "a_consecutive_holidays": "Gym Season Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Loyal Trainer Rank",
        "a_meta_collector": "Nighttime Encounter Hoard",
        "a_meta_category_starter": "Alert Badge",
        "a_meta_tier_climber": "Town Glyph",
        "a_meta_tier_max": "Roster Writ",
        "a_meta_xp_earner": "Champion Emblem",
        "a_meta_difficulty_easy": "Gotta Mechanism",
        "a_meta_difficulty_hard": "Pallet Writ",
        "a_meta_unlock_spree": "Master Panel",
        "a_meta_completionist": "Gym Leaders Fulfillment",
        "a_meta_diverse": "Pokemon Master Emblem",
        "a_meta_dominator": "Pikachu Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Chapter Read",
        "m_chapter_counter": "Gym Leaders Pinnacle",
        "m_chapter_titan": "Master Legend",
        "m_reading_hours": "Champion Relic",
        "m_reading_time_lord": "Unknown Pok Record Record",
        "m_manga_collector": "Loyal Ledger",
        "m_library_legend": "Pallet Reliquary",
        "m_first_complete": "Master Triumph",
        "m_hundred_club": "Ash Network",
        "m_first_day": "Pikachu Seal",
        "m_first_rating": "Pallet Town Eye",
        "m_ten_thousand_pages": "Trainer Alerts Gauge",
        "m_volume_collector": "Pallet Town Storehouse",
        "m_year_explorer": "Pallet Quest",
        "m_century_reader": "Pallet Town Dominion",
        "m_five_hundred_ch": "Loyal Trainer Ledger",
        "m_thousand_ch": "Gym Legend",
        "m_reading_ten": "Gotta Appraisal",
        "m_ptr_hoarder": "Safari Vault Index",
        "m_dropped_honesty": "Pallet Summit",
        "m_season_reader": "Kanto Treasury",
        "m_active_reader": "Trainer Trial",
        "m_five_thousand_ch": "Pikachu Legend",
        "m_ten_completed": "Pikachu Resolution",
        "m_fifty_completed": "Encounter Harvest",
        "m_five_hundred_completed": "Champion Trainer Legacy",
        "m_mean_score_tracker": "Journey Audit",
        "m_unique_authors": "Pokemon Marathon Reserve",
        "m_all_status": "Safari Vault Testament",
        "m_first_favorite": "Journey Cache",
        "m_favorites_collector": "Nighttime Encounter Shelf",
        "m_days_spent_reading": "Pallet Decree",

        // ── MANGA BINGE ──
        "m_binge_reader": "Caught Streak",
        "m_marathon_reader": "Pokemon Rush",
        "m_weekend_reader": "Journey Run",
        "m_non_stop_reading": "Caught Gauntlet",
        "m_one_more_chapter": "Champion Testament",
        "m_speed_read": "Pokemon Master Drive",
        "m_double_story": "Battle Banner",
        "m_triple_read": "Nighttime Encounter Record",
        "m_five_a_day": "Battle Insignia",
        "m_chapter_chain": "Roster Accord",
        "m_volume_binge": "Champion Drive",
        "m_power_reader": "Roster Seal",
        "m_half_day_read": "Loyal Trainer Aegis Aegis",
        "m_full_day_read": "Team Rocket Aegis",
        "m_power_weekend": "Nighttime Streak",
        "m_binge_king": "Caught Momentum",
        "m_no_sleep_read": "Pallet Town Rush",
        "m_full_series_rush": "Pok Cascade",
        "m_seven_day_challenge": "Trainer Warrant",
        "m_hundred_day_read": "Earned Legend",
        "m_volume_rush": "Caught Gauntlet Gauntlet",
        "m_series_sweep": "Safari Vault Trial",
        "m_genre_binge": "Pallet Binge",
        "m_author_binge": "Pc Box Surge",
        "m_chapter_counter_day": "Trainer Alerts Ledger",
        "m_multi_series_binge": "Nighttime Encounter Charge",
        "m_midnight_binge": "Earned Tempest",
        "m_new_year_binge": "Master Passage",
        "m_forty_eight_hour": "Pc Box Rally",
        "m_oneshot_binge": "Gym Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Encounter Action",
        "m_genre_adventure": "Gym Adventure",
        "m_genre_comedy": "Nighttime Encounter Comedy",
        "m_genre_drama": "Battle Drama",
        "m_genre_fantasy": "Town Champion Fantasy",
        "m_genre_horror": "Encounter Horror",
        "m_genre_mystery": "Kanto Mystery",
        "m_genre_romance": "Champion Trainer Romance",
        "m_genre_scifi": "Type Sci-Fi",
        "m_genre_sol": "Master Slice",
        "m_genre_sports": "Caught Sports",
        "m_genre_supernatural": "League Badges Supernatural",
        "m_genre_thriller": "Gym Leaders Thriller",
        "m_genre_psychological": "Caught Psychological",
        "m_genre_isekai": "Pokedex Isekai",
        "m_genre_shounen": "Pokedex Shounen",
        "m_genre_ecchi": "Town Champion Ecchi",
        "m_genre_mahou_shoujo": "Loyal Trainer Magic Shoujo",
        "m_genre_mecha": "Town Champion Mecha",
        "m_genre_music": "Mass Release Music",
        "m_tag_isekai_new": "Town Champion Isekai New",
        "m_tag_harem": "Type Harem",
        "m_tag_bl": "Nighttime Bl",
        "m_tag_gl": "Alert Gl",
        "m_tag_historical": "Roster Historical",
        "m_tag_military": "Master Military",
        "m_tag_school": "Kanto School",
        "m_tag_martial_arts": "League Badges Martial Arts",
        "m_tag_vampire": "Caught Vampire",
        "m_tag_samurai": "Champion Trainer Samurai",
        "m_tag_space": "Pikachu Space",
        "m_tag_parody": "Pok Parody",
        "m_tag_idol": "Trainer Alerts Idol",
        "m_tag_post_apocalyptic": "Nighttime Encounter Post Apocalyptic",
        "m_tag_cyberpunk": "League Badges Cyberpunk",
        "m_tag_shoujo": "Pallet Shoujo",
        "m_tag_survival": "Nighttime Encounter Survival",
        "m_tag_cooking": "Champion Trainer Cooking",
        "m_tag_medical": "Pokemon Master Medical",
        "m_tag_villainess": "Item Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Pokédex Read",
        "m_mega_completionist": "Unknown Pok Resolution",
        "m_completion_rate_50": "Pikachu Return",
        "m_completion_rate_75": "Pokemon Marathon Ascension",
        "m_completion_rate_90": "Pallet Resolution",
        "m_no_drop": "Caught Decree",
        "m_long_runner_complete": "Kanto Clear",
        "m_sequel_chain": "Caught Seal",
        "m_clean_list": "Master Relic Relic",
        "m_from_ptr": "Nighttime Encounter Accord",
        "m_reread_master": "Routes Trial",
        "m_oneshot_complete": "Pallet Town Ascension",
        "m_same_day_start_finish": "League Badges Crown Crown",
        "m_revival": "Nighttime Accord",
        "m_zero_to_hundred": "Pikachu Banner",
        "m_five_genre_complete": "Trainer M Five Genre Complete",
        "m_full_collection": "Gym Leaders Proof",
        "m_batch_complete": "Catch Summit",
        "m_paused_to_done": "Loyal Trainer Standard",
        "m_completion_spree": "Encounter Triumph",
        "m_format_completionist": "Pokemon Testament",
        "m_catch_up": "Battle Chronicle Chronicle",
        "m_multi_reread": "Pc Box Banner",
        "m_dropped_recovery": "Pokemon Conquest",
        "m_ten_perfect_scores": "Journey Judgment",
        "m_complete_genre_span": "Gym Leaders M Complete Genre",
        "m_monthly_completions": "Nighttime Encounter Monthly",
        "m_yearly_completions": "Type Epilogue",
        "m_rapid_complete": "Gym Finale",
        "m_author_complete": "Unknown Pok Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Manga Trainer",
        "m_mangaka_lover": "Caught Standard",
        "m_rereader": "Champion Return",
        "m_triple_reread": "Earned Testament",
        "m_annual_reread": "Nighttime Banner Banner",
        "m_publisher_fan": "Trainer Mark",
        "m_artist_fan": "Item Insignia Insignia",
        "m_adaptation_compare": "Mass Release Insignia",
        "m_source_material_fan": "Town Cache",
        "m_waiting_weekly": "Champion Trainer Streak",
        "m_classic_reader": "Champion Lantern",
        "m_saga_reader": "Nighttime Encounter Decree",
        "m_genre_loyalty": "Pok Loyalty",
        "m_decade_reader": "Pokemon Warrant",
        "m_ln_adaptation": "Pallet Town Mark",
        "m_original_work": "Item Standard",
        "m_long_commitment": "Routes Mark",
        "m_up_to_date": "Pokedex Warrant",
        "m_favorite_mangaka": "Team Rocket Treasury",
        "m_complete_portfolio": "Pokemon Master Triumph",
        "m_franchise_collector": "Unknown Pok Archive",
        "m_serialization_follower": "Marathon Handshake",
        "m_genre_master": "Gym Leaders Master",
        "m_multi_series_author": "Town Insignia",
        "m_format_diversity": "Caught Shelf",
        "m_year_dedication": "Pallet Town Tenure",
        "m_ongoing_follower": "Pok Fellowship",
        "m_genre_loyalty_50": "Alert Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Battle Explorer",
        "m_publisher_hopper": "Pokemon Master Mantle",
        "m_tag_explorer": "Safari Vault Explorer",
        "m_decade_hopper": "Team Rocket Chronicle Chronicle",
        "m_hidden_gem": "Champion Mark",
        "m_popular_taste": "Item Record",
        "m_retro_reader": "Trainer Testament",
        "m_modern_reader": "Champion Warrant",
        "m_cross_demographic": "Earned Crown",
        "m_underdog_fan": "Trainer Testament Testament",
        "m_variety_week": "Champion Trainer Horizon",
        "m_manhwa_reader": "Gotta Proof",
        "m_manhua_reader": "Champion Mantle",
        "m_classic_connoisseur": "Catch Glimpse",
        "m_award_winner": "Marathon Seal Seal",
        "m_niche_explorer": "Champion Trainer Horizon Horizon",
        "m_world_manga": "Trainer Alerts Chronicle",
        "m_cult_classic": "Pc Box Map",
        "m_random_pick": "Catch Standard Standard",
        "m_new_genre_month": "Nighttime M New Genre Month",
        "m_year_completionist": "Pokedex Fulfillment",
        "m_unpopular_opinion": "Champion Trainer Aegis",
        "m_top_rated_reader": "Trainer Pinnacle Pinnacle",
        "m_source_variety": "Routes Catalogue",
        "m_low_score_brave": "Pokemon Marathon Score",
        "m_short_manga_explorer": "Pallet Compass",
        "m_long_manga_explorer": "Unknown Pok Survey",
        "m_serialization_explorer": "Type Road",

        // ── MANGA TIME ──
        "m_night_owl": "Champion Trainer Accord",
        "m_early_bird": "Pallet Banner Banner",
        "m_lunch_reader": "Champion Relic Relic",
        "m_commute_reader": "Trainer Tenure",
        "m_four_am_club": "Trainer Fellowship",
        "m_new_year_read": "Champion Trainer Pact",
        "m_all_hours": "Roster Accord Accord",
        "m_prime_time_reader": "Caught Banner",
        "m_workday_reader": "Unknown Pok Accord",
        "m_sunday_read": "Encounter Testament Testament",
        "m_morning_routine": "Unknown Pok Discipline",
        "m_night_shift_reader": "Battle Accord",
        "m_seasonal_premier_read": "Pok Storehouse",
        "m_clock_collector": "Pallet Town Reserve",
        "m_late_night_horror": "Earned Mark",
        "m_afternoon_reader": "Gotta Mantle Mantle",
        "m_golden_hour_reader": "Earned Observance",
        "m_dawn_reader": "Safari Vault Mantle",
        "m_twilight_reader": "Pokemon Crown Crown",
        "m_midnight_start": "Catch Routine",
        "m_weekend_binge_hours": "Catch Momentum",
        "m_late_night_regular": "Town Champion Testament",
        "m_sunrise_reader": "Pc Box Record",
        "m_every_day_of_week": "Roster Seal Seal",
        "m_monthly_hours": "Nighttime Monthly",
        "m_bedtime_reader": "League Badges Warrant Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Pokemon Mantle",
        "m_webtoon_reader": "Champion Mark Mark",
        "m_full_color": "Mass Release Accord",
        "m_doujin_reader": "Roster Record",
        "m_anthology_reader": "Catch Accord",
        "m_adaptation_reader": "Mass Release Banner Banner",
        "m_longstrip_reader": "Encounter Trial Trial",
        "m_4koma_reader": "Trainer Relic",
        "m_oneshot_reader": "League Badges Mantle",
        "m_format_variety": "Pokemon Master Gallery",
        "m_light_novel_reader": "Town Insignia Insignia",
        "m_novel_reader": "Gym Leaders Crown Crown",
        "m_visual_storyteller": "Pallet Town Testament",
        "m_colored_classic": "Battle Survey",
        "m_webcomic_fan": "Journey Insignia",
        "m_manga_to_anime": "Roster Record Record",
        "m_seinen_reader": "Pokemon Pinnacle Pinnacle",
        "m_josei_reader": "Pokedex Pinnacle",
        "m_award_winning_art": "League Badges Relic",
        "m_debut_work": "Pokemon Marathon Dominion",
        "m_vertical_scroll": "Master Crown Crown",
        "m_traditional_format": "Journey Hoard",
        "m_cross_media": "Marathon Accord",
        "m_spinoff_reader": "Pikachu Accord Accord",
        "m_remake_reader": "Team Rocket Insignia Insignia",
        "m_collaboration_reader": "Journey Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Gym Focus",
        "m_mega_streak": "Kanto Routine",
        "m_weekly_warrior": "League Badges Season",
        "m_monthly_reader": "Nighttime Discipline",
        "m_comeback": "Nighttime Standard",
        "m_weekend_streak": "Pokedex Fever",
        "m_no_zero_days": "Gotta Proof Proof",
        "m_iron_will": "Journey Ledger",
        "m_habit_formed": "Gym Crown Crown",
        "m_consistent_pace": "Master Scrutiny",
        "m_year_long": "Safari Vault Observance",
        "m_double_streak": "League Badges Resolve",
        "m_streak_recovery": "Gym Leaders Resolve",
        "m_daily_minimum": "Gotta Focus",
        "m_winter_streak": "Earned Observance Observance",
        "m_summer_streak": "Pokemon Marathon Observance",
        "m_morning_streak": "Battle Clock",
        "m_night_streak": "Mass Release Discipline",
        "m_unbreakable": "Gym Leaders Warrant",
        "m_eternal_flame": "Loyal Trainer Record",
        "m_chapter_a_day": "Pokemon Relic Relic",
        "m_genre_streak": "Alert Streak",
        "m_completion_streak": "Item Return Return",
        "m_rating_streak": "Earned Appraisal Appraisal",
        "m_multi_ch_streak": "Gym Leaders Tenure",
        "m_author_streak": "Pok Calendar",
        "m_perfect_week_manga": "Kanto Accord",
        "m_diverse_streak": "Journey Streak",

        // ── MANGA SCORING ──
        "m_critic": "Town Champion Scrutiny",
        "m_perfect_ten": "Nighttime Encounter Verdict",
        "m_harsh_critic": "Nighttime Encounter Scale",
        "m_fair_judge": "Pok Eye",
        "m_generous_spirit": "Marathon Decree",
        "m_score_all": "Pallet Town Reckoning",
        "m_wide_range": "Battle Ledger",
        "m_controversial": "Team Rocket Standard",
        "m_consistent_scorer": "Loyal Trainer Grade",
        "m_score_sniper": "Type Reckoning",
        "m_evolving_taste": "Pokedex Trial",
        "m_bell_curve": "Kanto Accord Accord",
        "m_picky_reader": "Catch Ledger",
        "m_100_rated": "Unknown Pok Standard",
        "m_500_rated": "Champion Proof",
        "m_mediocre_majority": "Master Canon",
        "m_rating_spree": "Nighttime Verdict",
        "m_score_variance": "League Badges Measure",
        "m_binge_rater": "Champion Passage",
        "m_reread_rerate": "Pikachu Banner Banner",
        "m_masterpiece_hunter": "Marathon Banner",
        "m_contrarian": "Caught Aegis Aegis",
        "m_optimist": "Loyal Trainer Accord",
        "m_score_distributor": "Type Balance",
        "m_genre_critic": "Pallet Town Critic",
        "m_mean_above_8": "Gym Leaders Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Champion Season",
        "m_valentines_read": "Pokemon Master Observance",
        "m_pi_day": "Gym Leaders Testament",
        "m_april_fools": "Type Devotion",
        "m_international_manga_day": "League Badges Proof Proof",
        "m_free_comic_day": "Item Chronicle",
        "m_summer_solstice": "Trainer Focus Focus",
        "m_tanabata": "Pokemon Marathon Pilgrimage",
        "m_friday_13th": "Routes Dominion Dominion",
        "m_halloween_read": "Pokemon Master Calendar",
        "m_thanksgiving_binge": "Nighttime Charge",
        "m_christmas_read": "Battle Pact",
        "m_new_years_eve": "Encounter Pilgrimage",
        "m_birthday_read": "Gotta Birthday",
        "m_holiday_marathon": "Team Rocket Rally",
        "m_independence_day": "Champion Trainer Aegis Aegis",
        "m_culture_day": "Pikachu Seal Seal",
        "m_spring_equinox": "Encounter Dominion",
        "m_earth_day": "Pallet Aegis",
        "m_labor_day": "Trainer Warrant Warrant",
        "m_winter_solstice": "Alert Focus Focus",
        "m_manga_birthday": "Gym Leaders Ritual",
        "m_every_holiday_reader": "Type Watch",
        "m_consecutive_holidays": "Pokemon Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Loyal Proof Proof",
        "m_fibonacci": "Earned Dominion",
        "m_palindrome_day": "Gym Leaders Relic",
        "m_binary_day": "Pokemon Master Proof",
        "m_full_moon_read": "Pokemon Marathon Crown",
        "m_leap_year_read": "Mass Release Practice",
        "m_triple_seven": "Pok Trial",
        "m_thousand_complete": "Gotta Ascension",
        "m_nice": "Pokemon Warrant Warrant",
        "m_power_level_chapters": "Kanto Aegis",
        "m_answer_42": "League Badges Trial Trial",
        "m_square_number": "Pallet Standard Standard",
        "m_prime_count": "Routes Pinnacle",
        "m_matching_date": "League Badges Mantle Mantle",
        "m_century_chapter": "Pokemon Marathon Crown Crown",
        "m_pi_chapters": "Pokemon Proof Proof",
        "m_synchronicity": "Earned Emblem",
        "m_world_record": "Champion Warrant Warrant",
        "m_genre_clash": "Champion Trainer Clash",
        "m_time_traveler": "Roster Decree Decree",
        "m_double_digits": "Pok Dominion",
        "m_one_two_three": "Alert Warrant",
        "m_lucky_seven": "Mass Release Record",
        "m_exact_hundred_ch": "Gym Legend Testament",
        "m_year_match_count": "Caught Routine",
        "m_chapter_match_date": "Pc Box Record Record",

        // ── MANGA FORMATS ──
        "m_manga_format": "Pallet Town Index",
        "m_manhwa_format": "Earned Gallery",
        "m_manhua_format": "Alert Storehouse",
        "m_ln_format": "Pok Index",
        "m_oneshot_format": "Gym Leaders Index",
        "m_doujin_format": "Nighttime Cabinet",
        "m_novel_format": "Pokedex Reserve",
        "m_format_master_manga": "Nighttime Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Town Link",
        "m_meta_collector": "Ash Reliquary",
        "m_meta_category_starter": "Pokemon Master Standard",
        "m_meta_tier_climber": "Roster Token",
        "m_meta_tier_max": "Loyal Trainer Token",
        "m_meta_xp_earner": "Gotta Anchor",
        "m_meta_difficulty_easy": "Champion Panel",
        "m_meta_difficulty_hard": "Pallet Town Node",
        "m_meta_unlock_spree": "Town Champion Marker",
        "m_meta_completionist": "Pokemon Master Completion",
        "m_meta_diverse": "Master Anchor Anchor",
        "m_meta_dominator": "Marathon Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#080400",
        primary: "#dc8a00",
        secondary: "#cc0000",
        accent: "#3366cc",
    },
    particleColor: "#f8a800",
    backgroundDim: 0.25,
    backgroundBlur: 10,
    particleTypes: {
        sparkles: { label: "Sparkles", maxCount: 16, defaultEnabled: true, defaultIntensity: 55 },
        pokeflash: { label: "Poké Flash", maxCount: 5, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
  1: "Threadbare Generic Rank Spark",
  8: "Generic's Tarnished Omen",
  14: "Fractured Generic Rank",
  21: "Generic Rank Path",
  28: "Lowborn Legacy Myth",
  35: "Generic Rank Pulse",
  41: "Generic's Legacy Crest",
  48: "Humble Generic Mark",
  55: "Ragged Generic Rank Vow",
  61: "Generic's Faint Echo",
  68: "Lesser Generic Rank",
  75: "Generic Rank Zenith",
  81: "Doubtful Legacy Bloom",
  88: "Generic Rank Sigil",
  95: "Generic's Legacy Flame",
  102: "Really Cool Generic Spark",
  108: "Awakened Generic Rank Omen",
  115: "Generic's Resolute Seal",
  122: "Rising Generic Rank",
  128: "Generic Rank Myth",
  135: "Dauntless Legacy Pulse",
  142: "Generic Rank Crest",
  149: "Generic's Legacy Mark",
  155: "Fresh Generic Vow",
  162: "Valiant Generic Rank Echo",
  169: "Generic's Prime Crown",
  175: "Polished Generic Rank",
  182: "Generic Rank Bloom",
  189: "Stormlit Legacy Sigil",
  195: "Generic Rank Flame",
  202: "Generic's Legacy Spark",
  209: "Tempered Generic Omen",
  216: "Trusted Generic Rank Seal",
  222: "Generic's Steadfast Path",
  229: "Ironclad Generic Rank",
  236: "Veteran Legacy Pulse",
  242: "Core Legacy Crest",
  249: "Generic Rank Mark",
  256: "Generic's Legacy Vow",
  262: "Formidable Generic Echo",
  269: "Lucid Generic Rank Crown",
  276: "Generic's Ranked Zenith",
  283: "Fabled Generic Rank",
  289: "Grand Legacy Sigil",
  296: "Seasoned Legacy Flame",
  303: "Generic Rank Spark",
  309: "Generic's Legacy Omen",
  316: "Valorous Generic Seal",
  323: "Stalwart Generic Rank Path",
  330: "Generic's Commanding Myth",
  336: "Refined Generic Rank",
  343: "Unbroken Legacy Crest",
  350: "Blazing Legacy Mark",
  356: "Generic Rank Vow",
  363: "Generic's Legacy Echo",
  370: "Peerless Generic Crown",
  376: "Ardent Generic Rank Zenith",
  383: "Generic's Focused Bloom",
  390: "Vigilant Generic Rank",
  397: "Dominant Legacy Flame",
  403: "Elite Legacy Spark",
  410: "Generic Rank Omen",
  417: "Generic's Legacy Seal",
  423: "Sovereign Generic Path",
  430: "Regal Generic Rank Myth",
  437: "Generic's Crowned Pulse",
  444: "Mythborn Generic Rank",
  450: "Limitless Legacy Mark",
  457: "Radiant Legacy Vow",
  464: "Generic Rank Echo",
  470: "Generic's Legacy Crown",
  477: "Climactic Generic Zenith",
  484: "Epic Generic Rank Bloom",
  490: "Generic's Unreal Sigil",
  497: "Peak Generic Rank",
  504: "Supreme Legacy Spark",
  511: "Exalted Legacy Omen",
  517: "Generic Rank Seal",
  524: "Generic's Legacy Path",
  531: "Celestial Generic Myth",
  537: "Phantom Generic Rank Pulse",
  544: "Generic's Crimson Crest",
  551: "Silver Generic Rank",
  557: "Golden Legacy Vow",
  564: "Feral Legacy Echo",
  571: "Generic Rank Crown",
  578: "Generic's Legacy Zenith",
  584: "Dread Generic Bloom",
  591: "Luminous Generic Rank Sigil",
  598: "Generic's Thunderous Flame",
  604: "Ultraviolet Generic Rank",
  611: "Unleashed Legacy Omen",
  618: "Secret Legacy Seal",
  625: "Final Generic Path",
  631: "Generic's Legacy Myth",
  638: "Worldclass Generic Pulse",
  645: "Lawless Generic Rank Crest",
  651: "Generic's Chosen Mark",
  658: "Fearless Generic Rank",
  665: "Overdrive Legacy Echo",
  671: "Cinematic Legacy Crown",
  678: "Impossible Generic Zenith",
  685: "Generic's Legacy Bloom",
  692: "Canonized Generic Sigil",
  698: "Ascendant Generic Rank Flame",
  705: "Generic's Transfigured Spark",
  712: "Immortal Generic Rank",
  718: "Eclipsed Legacy Seal",
  725: "Astral Legacy Path",
  732: "Sublime Generic Myth",
  739: "Generic's Legacy Pulse",
  745: "Prismatic Generic Crest",
  752: "Abyssal Generic Rank Mark",
  759: "Generic's Unbound Vow",
  765: "Eternal Generic Rank",
  772: "Cosmic Legacy Crown",
  779: "Transcendent Legacy Zenith",
  785: "Perfected Generic Bloom",
  792: "Generic's Legacy Sigil",
  799: "Ultimate Generic Flame",
  806: "Mythic Generic Rank Spark",
  812: "Generic's Godlike Omen",
  819: "Canonical Generic Rank",
  826: "Reality-Bent Legacy Path",
  832: "Heavenly Legacy Myth",
  839: "Absolute Generic Pulse",
  846: "Untouchable Generic Crest",
  852: "Timeless Generic Mark",
  859: "Empyrean Generic Rank Vow",
  866: "Generic's Primordial Echo",
  873: "Omniscient Generic Rank",
  879: "Unfathomed Legacy Zenith",
  886: "Apocalyptic Legacy Bloom",
  893: "Seraphic Generic Sigil",
  899: "Omega Generic Flame",
  906: "Final Generic Spark",
  913: "Crowned Generic Rank Omen",
  920: "Generic's Mythic Seal",
  926: "Absolute Generic Rank",
  933: "Eternal Legacy Myth",
  940: "Cosmic Legacy Pulse",
  946: "Transcendent Generic Crest",
  953: "Perfected Generic Mark",
  960: "Definitive Generic Vow",
  966: "Ultimate Generic Rank Echo",
  973: "Generic's Infinite Crown",
  980: "Sovereign Generic Rank",
  987: "Celestial Legacy Bloom",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate Generic Rank"
},
}
