import { AnimeThemeConfig } from "./types"
import { GiAirplane, GiPig, GiWaves, GiSunCloud, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiMountainRoad } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const porcoRossoTheme: AnimeThemeConfig = {
    id: "porco-rosso",
    displayName: "Porco Rosso",
    description: "A WWI flying ace cursed with a pig's face roams the Adriatic as a freelance bounty hunter in the 1930s — world-weary, romantic, and absolutely unmatched in the sky.",
    fontFamily: "'Lora', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,700;1,400&display=swap",
    cssVars: {
        "--color-brand-200": "210 170 140",
        "--color-brand-300": "185 135 100",
        "--color-brand-400": "158 102 65",
        "--color-brand-500": "130 72 38",
        "--color-brand-600": "104 54 26",
        "--color-brand-700": "78 38 16",
        "--color-brand-800": "54 24 8",
        "--color-brand-900": "32 14 4",
        "--color-brand-950": "18 7 2",
        "--brand": "130 72 38",
        "--background": "#060402",
        "--paper": "#0e0a06",
        "--color-gray-950": "6 4 2",
        "--color-gray-900": "14 10 6",
        "--color-gray-800": "26 20 12",
        "--color-gray-700": "44 34 22",
        "--color-gray-600": "68 54 38",
        "--color-gray-500": "105 86 66",
        "--color-gray-400": "148 128 106",
        "--color-gray-300": "186 168 148",
        "--color-gray-200": "214 198 180",
        "--color-gray-100": "232 222 208",
        "--color-gray-50": "246 240 232",
    },
    sidebarOverrides: {
        "home": { icon: GiAirplane, label: "Adriatic Base" },
        "schedule": { icon: GiAlarmClock, label: "Flight Log" },
        "manga": { icon: LuBookOpen, label: "Pilot's Journal" },
        "lists": { icon: GiPig, label: "Bounty List" },
        "discover": { icon: GiBullseye, label: "Sky Scouting" },
        "torrent-list": { icon: GiMountainRoad, label: "Route Cache" },
        "debrid": { icon: GiWaves, label: "Adriatic Network" },
        "unmatched": { icon: GiSunCloud, label: "Unknown Flights" },
        "enmasse": { icon: GiResize, label: "Pirate Fleet" },
        "scan-summaries": { icon: TbReportSearch, label: "Flight Reports" },
        "auto-downloader": { icon: LuRss, label: "Radio Signals" },
        "community": { icon: GiAirplane, label: "Adriatic Aces" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Radio Alerts" },
        "achievements": { icon: GiTrophy, label: "Ace Medals" },
        "milestones": { icon: LuFlag, label: "Ace Goals" },
        "theme-manager": { icon: GiPalette, label: "Seaplane Colors" },
        "extensions": { icon: BiExtension, label: "Engine Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Adriatic Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Cockpit Settings" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Takeoff",
        "a_episode_counter": "Ace's Resolve Mark",
        "a_episode_titan": "War Memories Relic",
        "a_hours_invested": "Pig Curse Proof",
        "a_time_lord": "Sky Veteran",
        "a_anime_collector": "Plane Cache",
        "a_library_legend": "Pilot Archives",
        "a_first_complete": "Bounty Claimed",
        "a_hundred_club": "Hundred Flights",
        "a_first_day": "Radio Alerts Seal",
        "a_first_rating": "War Memories Appraisal",
        "a_ten_thousand_min": "Radio Signals Standard",
        "a_season_veteran": "Radio Signals Library",
        "a_year_explorer": "Red Seaplane Map",
        "a_century_watcher": "Sky Marathon Ledger",
        "a_five_hundred_eps": "Pirate Fleet Dominion",
        "a_thousand_eps": "Aerial Combat Record",
        "a_watching_ten": "Pig Pilot Acclaim",
        "a_ptw_hoarder": "Perfect Flight Library",
        "a_dropped_honesty": "Pig Pilot Summit",
        "a_five_thousand_eps": "Miyazaki Fan Warrant",
        "a_ten_completed": "Sky Scouting Afterglow",
        "a_fifty_completed": "Seaplane Tech Ascension",
        "a_five_hundred_completed": "Pig Pilot Clear",
        "a_mean_score_tracker": "Ghibli Expert Verdict",
        "a_unique_studios": "Aerial Combat Collection",
        "a_days_spent_watching": "Adriatic World Dominion",
        "a_all_status": "Ghibli Critic Testament",
        "a_first_favorite": "Porco Rosso Cabinet",
        "a_favorites_collector": "All Bounties Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Night Flight Drive",
        "a_marathon_runner": "Long Flight",
        "a_weekend_warrior": "War Memories Ordeal",
        "a_non_stop": "Ghibli Journey Fever",
        "a_one_more_episode": "Dawn Takeoff Mantle",
        "a_speed_run": "Race Winner",
        "a_double_feature": "War Burden Crown",
        "a_triple_threat": "Adriatic Art Record",
        "a_five_a_day": "Cursed Ace Accord",
        "a_back_to_back": "Seaplane Body Surge",
        "a_seasonal_binge": "War Memories Cascade",
        "a_cour_crusher": "Adriatic World Ordeal",
        "a_half_day_watch": "Ace's Resolve Crown",
        "a_full_day_watch": "Gina's Love Pinnacle",
        "a_power_weekend": "Radio Alerts Run",
        "a_binge_king": "Adriatic Marathon",
        "a_no_sleep": "All-Night Flight",
        "a_entire_season": "Sky Revisit Library",
        "a_seven_day_challenge": "Gina's Love Mark",
        "a_hundred_day_binge": "Radio Alerts Surge",
        "a_genre_binge": "Classic Ghibli Binge",
        "a_studio_binge": "Ace's Resolve Fever",
        "a_season_sweep": "Pilot's Journal Codex",
        "a_forty_eight_hour": "Endless Sky Overture",
        "a_ep_counter_day": "Sky Scouting Aegis",
        "a_multi_series_binge": "Perfect Flight Streak",
        "a_midnight_binge": "Dawn Takeoff Cascade",
        "a_new_year_binge": "Soldier Ace Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Aerial Combat",
        "a_genre_adventure": "Mediterranean",
        "a_genre_comedy": "Pig Pilot",
        "a_genre_drama": "Cursed Ace",
        "a_genre_fantasy": "Adriatic World",
        "a_genre_horror": "War Memories",
        "a_genre_mystery": "Pilot Archives Mystery",
        "a_genre_romance": "Gina's Love",
        "a_genre_scifi": "Seaplane Tech",
        "a_genre_sol": "Miyazaki Fan Slice",
        "a_genre_sports": "Endless Sky Sports",
        "a_genre_supernatural": "Pig Curse",
        "a_genre_thriller": "Seaplane Tech Thriller",
        "a_genre_mecha": "Seaplane Body",
        "a_genre_music": "Radio Signals Music",
        "a_genre_psychological": "War Burden",
        "a_genre_ecchi": "Night Flight Ecchi",
        "a_genre_mahou_shoujo": "Adriatic Art Magic Shoujo",
        "a_tag_isekai": "Ace Judge Isekai",
        "a_tag_harem": "Fio's Crew Harem",
        "a_tag_bl": "Endless Sky Bl",
        "a_tag_gl": "Dawn Takeoff Gl",
        "a_tag_historical": "Ace Medals Historical",
        "a_tag_military": "Pirate Fleet Military",
        "a_tag_school": "Perfect Flight School",
        "a_tag_martial_arts": "Gina's Love Martial Arts",
        "a_tag_vampire": "Adriatic Art Vampire",
        "a_tag_samurai": "Aerial Combat Samurai",
        "a_tag_space": "Sky Return Space",
        "a_tag_parody": "Long Flight Parody",
        "a_tag_idol": "Endless Sky Idol",
        "a_tag_post_apocalyptic": "Pilot Resolve Post Apocalyptic",
        "a_tag_cyberpunk": "Ghibli Journey Cyberpunk",
        "a_tag_shounen": "Pilot Resolve Shounen",
        "a_tag_seinen": "Race Winner Seinen",
        "a_tag_shoujo": "Race Winner Shoujo",
        "a_tag_josei": "Sky Scouting Josei",
        "a_tag_survival": "All Bounties Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "All Bounties",
        "a_mega_completionist": "Miyazaki Expert",
        "a_completion_rate_50": "Adriatic Art Return",
        "a_completion_rate_75": "Seaplane Tech Crown",
        "a_completion_rate_90": "Sky Scouting Resolution",
        "a_no_drop": "Pilot Archives Decree",
        "a_long_runner_complete": "Radio Alerts Clear",
        "a_sequel_chain": "Ghibli Journey",
        "a_clean_list": "Pilot's Journal Relic",
        "a_from_ptw": "Long Flight Index",
        "a_rewatch_master": "Ghibli Expert Return",
        "a_short_complete": "Adriatic Aces Endgame",
        "a_same_day_start_finish": "Bounty Claimed Pinnacle",
        "a_revival": "Sky Marathon Insignia",
        "a_zero_to_hero": "Soldier to Ace",
        "a_five_genre_complete": "Adriatic Aces A Five Genre",
        "a_full_franchise": "Perfect Flight Chronicle",
        "a_batch_complete": "War Memories Crown",
        "a_paused_to_done": "Sky Scouting Aegis Aegis",
        "a_completion_spree": "Daily Flight Triumph",
        "a_multi_rewatch": "Daily Flight Triumph Triumph",
        "a_dropped_recovery": "Ace's Resolve Conquest",
        "a_ten_perfect_scores": "Radio Alerts Acclaim",
        "a_seasonal_clear": "Adriatic World Codex",
        "a_complete_genre_span": "Decade Fan A Complete Genre",
        "a_monthly_completions": "Ghibli Expert Afterglow",
        "a_yearly_completions": "Ghibli Critic Epilogue",
        "a_rapid_complete": "Gina's Love Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Fio's Crew",
        "a_studio_devotee": "Pilot Archives Treasury",
        "a_rewatcher": "Sky Return",
        "a_triple_rewatch": "Classic Ghibli Coda",
        "a_annual_tradition": "Gina's Love Proof",
        "a_director_fan": "Pilot's Journal Trial",
        "a_voice_actor_fan": "Ace's Resolve Crown Crown",
        "a_ost_lover": "Perfect Flight Seal",
        "a_source_reader": "Red Seaplane Cabinet",
        "a_waiting_weekly": "Pilot Archives Clock",
        "a_childhood_revisit": "Strict Pilot Seal",
        "a_saga_tracker": "Sky Return Standard",
        "a_genre_loyalty": "Miyazaki Fan Loyalty",
        "a_decade_watcher": "Decade Fan",
        "a_adaptation_hunter": "Long Flight Trial",
        "a_original_anime_fan": "Classic Fan Testament",
        "a_long_commitment": "Gina's Love Mark Mark",
        "a_perfect_attendance": "Pig Pilot Standard",
        "a_favorite_studio_5": "Pilot Resolve Library",
        "a_complete_catalog": "All Bounties Seal",
        "a_franchise_collector": "Pilot Resolve Archive",
        "a_airing_follower": "Strict Pilot Signal",
        "a_genre_master": "Pilot's Journal Master",
        "a_staff_follower": "Pilot Resolve Oath",
        "a_multi_season_fan": "Ace Medals Hoard",
        "a_format_diversity": "Adriatic Art Cache",
        "a_year_dedication": "War Memories Tenure",
        "a_season_dedication": "Pirate Fleet Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Classic Ghibli Explorer",
        "a_studio_hopper": "Ghibli Expert Collection",
        "a_tag_explorer": "War Memories Explorer",
        "a_decade_hopper": "Perfect Flight Chronicle Chronicle",
        "a_hidden_gem": "Hidden Route",
        "a_popular_taste": "Endless Sky Decree",
        "a_retro_appreciator": "All Bounties Aegis",
        "a_modern_viewer": "Bounty Claimed Pinnacle Pinnacle",
        "a_cross_demographic": "Night Flight Pinnacle",
        "a_underdog_fan": "Decade Fan Trial",
        "a_variety_week": "Pilot Resolve Horizon",
        "a_foreign_cinema": "Dawn Takeoff Expedition",
        "a_classic_connoisseur": "92 Classic Fan",
        "a_every_season": "Strict Pilot Archive",
        "a_award_winner": "Radio Signals Insignia",
        "a_niche_explorer": "Race Winner Horizon",
        "a_global_anime": "Adriatic Aces Crown",
        "a_cult_classic": "Miyazaki Classic",
        "a_random_pick": "Endless Sky Decree Decree",
        "a_new_genre_month": "Pig Pilot A New Genre",
        "a_seasonal_completionist": "Sky Marathon Summit",
        "a_unpopular_opinion": "Porco Rosso Standard",
        "a_top_rated_viewer": "Cursed Ace Seal",
        "a_source_variety": "Adriatic World Storehouse",
        "a_low_score_brave": "Ghibli Journey Measure",
        "a_upcoming_watcher": "Cursed Ace Seal Seal",
        "a_short_series_explorer": "Dawn Takeoff Expedition Expedition",
        "a_long_series_explorer": "War Burden Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Night Flight",
        "a_early_bird": "Dawn Takeoff",
        "a_lunch_break": "All Night Trial",
        "a_golden_hour": "Adriatic Base Tenure",
        "a_four_am_club": "Daily Flight Gathering",
        "a_witching_hour": "Seaplane Tech Tenure",
        "a_new_year_watch": "War Memories Season",
        "a_midnight_premiere": "Soldier Ace Devotion",
        "a_all_hours": "Sky Marathon Seal",
        "a_dawn_warrior": "Endless Sky Aegis",
        "a_afternoon_delight": "Pig Curse Proof Proof",
        "a_prime_time": "Radio Signals Insignia Insignia",
        "a_workday_watcher": "Night Flight Pinnacle Pinnacle",
        "a_sunday_marathon": "Radio Alerts Momentum",
        "a_rainy_day": "Seaplane Tech Relic",
        "a_morning_routine": "Ace Medals Promise",
        "a_night_shift": "Adriatic Art Aegis",
        "a_twilight_zone": "Sky Revisit Ledger",
        "a_seasonal_premier": "Pilot Archives Cabinet",
        "a_clock_collector": "Daily Flight Repository",
        "a_weekend_binge_hours": "Race Winner Streak",
        "a_late_night_regular": "Ghibli Critic Dominion",
        "a_sunrise_watcher": "Pilot's Journal Relic Relic",
        "a_holiday_watcher": "Cursed Ace Pact",
        "a_every_day_of_week": "Seaplane Body Ledger",
        "a_monthly_hours": "Endless Sky Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Sky Scouting Record",
        "a_party_host": "Adriatic Art Record Record",
        "a_social_butterfly": "Red Seaplane Company",
        "a_group_binge": "Aerial Combat Sprint",
        "a_party_regular": "Sky Revisit Chronicle",
        "a_sync_viewer": "Daily Flight Standard",
        "a_commentator": "All Bounties Record",
        "a_party_marathon": "Classic Ghibli Vigil",
        "a_full_house": "Pirate Fleet Trial",
        "a_community_pillar": "Ghibli Critic Alliance",
        "a_watch_party_streak": "All Bounties Vigil",
        "a_diverse_party": "Ace Medals Seal",
        "a_late_night_party": "Ghibli Critic Testament Testament",
        "a_party_veteran": "Pirate Fleet Testament",
        "a_genre_party": "Dawn Takeoff Party",
        "a_weekly_party": "Daily Flight Calendar",
        "a_silent_viewer": "Classic Fan Mantle",
        "a_recommendation_giver": "Race Winner Network",
        "a_party_completionist": "Sky Return Coda",
        "a_social_scorer": "Pilot's Journal Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "War Burden Proof",
        "a_fibonacci": "War Memories Dominion",
        "a_palindrome_day": "War Memories Relic Relic",
        "a_binary_day": "Miyazaki Fan Mark",
        "a_full_moon": "Strict Pilot Insignia",
        "a_leap_year": "Adriatic Aces Devotion",
        "a_time_traveler": "Pilot Archives Record",
        "a_genre_clash": "Classic Ghibli Clash",
        "a_triple_seven": "War Memories Testament",
        "a_thousand_complete": "Classic Fan Epilogue",
        "a_pi_episodes": "Night Flight Crown",
        "a_synchronicity": "Decade Fan Anchor",
        "a_world_record": "Ace's Resolve Warrant",
        "a_nice": "Radio Signals Chronicle",
        "a_power_level": "Classic Fan Testament Testament",
        "a_answer_42": "Endless Sky Standard",
        "a_square_number": "Classic Ghibli Decree",
        "a_prime_count": "Radio Signals Seal",
        "a_matching_date": "Decade Fan Mantle",
        "a_century_episode": "Night Flight Mark",
        "a_double_digits": "Seaplane Tech Testament",
        "a_one_two_three": "Adriatic Aces Crown Crown",
        "a_lucky_seven": "Gina's Love Crown",
        "a_all_tens": "Ghibli Journey Criterion",
        "a_exact_hundred_eps": "Sky Return Legend",
        "a_year_match_count": "Pilot Archives Yearlong",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Race Winner Ledger",
        "a_movie_buff": "Ace's Resolve Mark Mark",
        "a_ova_hunter": "Sky Return Standard Standard",
        "a_ona_explorer": "Decade Fan Secret",
        "a_special_watcher": "Seaplane Tech Relic Relic",
        "a_short_king": "Fio's Crew Crown",
        "a_variety_pack": "Ace's Resolve Inquiry",
        "a_film_festival": "Cursed Ace Chronicle",
        "a_music_video": "Ace Medals Chronicle",
        "a_tv_short": "Classic Ghibli Record",
        "a_movie_marathon": "Classic Ghibli Gauntlet",
        "a_double_length": "War Burden Crown Crown",
        "a_anthology": "Adriatic Art Aegis Aegis",
        "a_mini_series": "Porco Rosso Decree",
        "a_theatrical": "Pilot Resolve Accord",
        "a_format_master": "Daily Flight Vault",
        "a_long_movie": "Sky Marathon Insignia Insignia",
        "a_back_catalog": "All Bounties Standard",
        "a_cm_watcher": "Ace Judge Aegis",
        "a_pv_collector": "Decade Fan Storehouse",
        "a_format_balance": "Daily Flight Vault Vault",
        "a_episodic_master": "Ace Judge Standard",
        "a_sequel_movie": "Adriatic Aces Pinnacle",
        "a_recap_watcher": "All Night Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Flight",
        "a_mega_streak": "Endless Sky",
        "a_weekly_warrior": "Pirate Fleet Season",
        "a_monthly_watcher": "Soldier Ace Calendar",
        "a_comeback": "Red Seaplane Decree",
        "a_weekend_streak": "Ghibli Journey Passage",
        "a_no_zero_days": "Miyazaki Fan Warrant Warrant",
        "a_iron_will": "Ace's Resolve",
        "a_habit_formed": "Seaplane Body Banner",
        "a_consistent_pace": "War Burden Measure",
        "a_year_long": "Year in Sky",
        "a_double_streak": "Pilot's Journal Watch",
        "a_streak_recovery": "Classic Fan Season",
        "a_daily_minimum": "Soldier Ace Focus",
        "a_winter_streak": "Dawn Takeoff Watch",
        "a_summer_streak": "Seaplane Tech Resolve",
        "a_morning_streak": "All Bounties Clock",
        "a_night_streak": "Seaplane Body Constancy",
        "a_unbreakable": "Fio's Crew Proof",
        "a_eternal_flame": "Ghibli Expert Standard",
        "a_completion_streak": "Sky Return Return",
        "a_rating_streak": "War Memories Balance",
        "a_multi_ep_streak": "Ace's Resolve Ritual",
        "a_genre_streak": "War Memories Streak",
        "a_studio_streak": "Red Seaplane Cabinet Cabinet",
        "a_perfect_week": "Decade Fan Relic",

        // ── ANIME SCORING ──
        "a_critic": "Ace Judge",
        "a_perfect_ten": "Perfect Flight",
        "a_harsh_critic": "Strict Pilot",
        "a_fair_judge": "Ghibli Critic Balance",
        "a_generous_spirit": "Soldier Ace Pinnacle",
        "a_score_all": "Pig Curse Criterion",
        "a_wide_range": "Radio Signals Ledger",
        "a_controversial": "All Bounties Decree",
        "a_consistent_scorer": "Pilot Archives Verdict",
        "a_score_sniper": "Adriatic Aces Score",
        "a_evolving_taste": "Pilot's Journal Testament",
        "a_bell_curve": "Pig Pilot Insignia",
        "a_picky_watcher": "Classic Fan Warrant",
        "a_100_rated": "Daily Flight Warrant",
        "a_500_rated": "Fio's Crew Pinnacle",
        "a_mediocre_majority": "Decade Fan Canon",
        "a_rating_spree": "All Bounties Review",
        "a_score_variance": "Ghibli Journey Score",
        "a_masterpiece_hunter": "All Bounties Banner",
        "a_contrarian": "Classic Ghibli Record Record",
        "a_optimist": "Ace Medals Ledger",
        "a_score_distributor": "All Night Appraisal",
        "a_genre_critic": "War Burden Critic",
        "a_mean_above_8": "Gina's Love Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Flight",
        "a_valentines_weeb": "Pilot Resolve Vow",
        "a_pi_day": "Ghibli Critic Trial",
        "a_april_fools": "Adriatic Aces Devotion Devotion",
        "a_international_anime_day": "Sky Marathon Record",
        "a_star_wars_day": "Radio Alerts Chronicle",
        "a_summer_solstice": "Miyazaki Fan Calendar",
        "a_tanabata": "Bounty Claimed Focus",
        "a_friday_13th": "All Night Relic",
        "a_halloween_spirit": "Race Winner Vow",
        "a_thanksgiving_binge": "Sky Revisit Run",
        "a_christmas_special": "Winter Adriatic",
        "a_new_years_eve": "Gina's Love Pilgrimage",
        "a_birthday_watch": "Pig Pilot Vow",
        "a_holiday_marathon": "Aerial Combat Overture",
        "a_independence_day": "Ghibli Expert Banner",
        "a_culture_day": "Perfect Flight Insignia",
        "a_spring_equinox": "Aerial Combat Decree",
        "a_earth_day": "Ace's Resolve Mantle",
        "a_labor_day": "Race Winner Seal",
        "a_winter_solstice": "Night Flight Pilgrimage",
        "a_anime_birthday": "Ace's Resolve Pilgrimage",
        "a_every_holiday": "Long Flight Resolve",
        "a_consecutive_holidays": "Seaplane Tech Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Red Seaplane Rank",
        "a_meta_collector": "Perfect Flight Hoard",
        "a_meta_category_starter": "Soldier Ace Badge",
        "a_meta_tier_climber": "Perfect Flight Glyph",
        "a_meta_tier_max": "Red Seaplane",
        "a_meta_xp_earner": "All Night Emblem",
        "a_meta_difficulty_easy": "Ghibli Critic Mechanism",
        "a_meta_difficulty_hard": "Cursed Ace Writ",
        "a_meta_unlock_spree": "Pirate Fleet Panel",
        "a_meta_completionist": "Full Collection",
        "a_meta_diverse": "War Memories Emblem",
        "a_meta_dominator": "Sky Revisit Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Sortie",
        "m_chapter_counter": "Daily Flight Pinnacle",
        "m_chapter_titan": "Adriatic World Relic",
        "m_reading_hours": "All Night Relic Relic",
        "m_reading_time_lord": "Sky Marathon Record Record",
        "m_manga_collector": "Pirate Fleet Ledger",
        "m_library_legend": "Perfect Flight Reliquary",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "Pilot Resolve Seal",
        "m_first_rating": "All Night Eye",
        "m_ten_thousand_pages": "Pilot Resolve Gauge",
        "m_volume_collector": "Classic Fan Storehouse",
        "m_year_explorer": "Endless Sky Quest",
        "m_century_reader": "Dawn Takeoff Dominion",
        "m_five_hundred_ch": "Radio Signals Legend",
        "m_thousand_ch": "Pilot's Journal Legend",
        "m_reading_ten": "Dawn Takeoff Appraisal",
        "m_ptr_hoarder": "Pilot's Journal Index",
        "m_dropped_honesty": "Perfect Flight Summit",
        "m_season_reader": "All Bounties Treasury",
        "m_active_reader": "Seaplane Tech Trial",
        "m_five_thousand_ch": "Classic Ghibli Standard",
        "m_ten_completed": "Classic Ghibli Resolution",
        "m_fifty_completed": "Pilot's Journal Harvest",
        "m_five_hundred_completed": "Seaplane Body Legacy",
        "m_mean_score_tracker": "Pilot Archives Audit",
        "m_unique_authors": "Ace's Resolve Reserve",
        "m_all_status": "Seaplane Tech Testament Testament",
        "m_first_favorite": "Sky Return Cache",
        "m_favorites_collector": "Red Seaplane Shelf",
        "m_days_spent_reading": "Night Flight Relic",

        // ── MANGA BINGE ──
        "m_binge_reader": "Pig Pilot Streak",
        "m_marathon_reader": "Ghibli Critic Rush",
        "m_weekend_reader": "Strict Pilot Run",
        "m_non_stop_reading": "Sky Return Gauntlet",
        "m_one_more_chapter": "All Night Testament Testament",
        "m_speed_read": "Miyazaki Fan Drive",
        "m_double_story": "Aerial Combat Banner",
        "m_triple_read": "Ghibli Expert Record",
        "m_five_a_day": "Ace Medals Insignia",
        "m_chapter_chain": "Perfect Flight Accord",
        "m_volume_binge": "Ghibli Journey Drive",
        "m_power_reader": "Radio Alerts Seal Seal",
        "m_half_day_read": "Red Seaplane Aegis",
        "m_full_day_read": "Ace Judge Aegis Aegis",
        "m_power_weekend": "Pilot Resolve Streak",
        "m_binge_king": "Sky Marathon",
        "m_no_sleep_read": "Dawn Takeoff Rush",
        "m_full_series_rush": "Ghibli Critic Cascade",
        "m_seven_day_challenge": "Bounty Claimed Warrant",
        "m_hundred_day_read": "War Memories Legend",
        "m_volume_rush": "Sky Scouting Gauntlet",
        "m_series_sweep": "Long Flight Trial Trial",
        "m_genre_binge": "Ace Judge Binge",
        "m_author_binge": "Strict Pilot Surge",
        "m_chapter_counter_day": "Sky Revisit Ledger Ledger",
        "m_multi_series_binge": "Radio Signals Charge",
        "m_midnight_binge": "Pilot's Journal Tempest",
        "m_new_year_binge": "Ace's Resolve Passage",
        "m_forty_eight_hour": "Pilot Archives Rally",
        "m_oneshot_binge": "Miyazaki Fan Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Aerial Chapter",
        "m_genre_adventure": "Sea Chapter",
        "m_genre_comedy": "Red Seaplane Comedy",
        "m_genre_drama": "Drama Chapter",
        "m_genre_fantasy": "Adriatic World",
        "m_genre_horror": "War Chapter",
        "m_genre_mystery": "Classic Ghibli Mystery",
        "m_genre_romance": "Romance Chapter",
        "m_genre_scifi": "Plane Chapter",
        "m_genre_sol": "Daily Flight Slice",
        "m_genre_sports": "Sky Scouting Sports",
        "m_genre_supernatural": "Curse Chapter",
        "m_genre_thriller": "Decade Fan Thriller",
        "m_genre_psychological": "Solitude",
        "m_genre_isekai": "Pirate Fleet Isekai",
        "m_genre_shounen": "Adriatic Base Shounen",
        "m_genre_ecchi": "War Burden Ecchi",
        "m_genre_mahou_shoujo": "Red Seaplane Magic Shoujo",
        "m_genre_mecha": "Classic Fan Mecha",
        "m_genre_music": "Race Winner Music",
        "m_tag_isekai_new": "All Night Isekai New",
        "m_tag_harem": "Pig Curse Harem",
        "m_tag_bl": "Porco Rosso Bl",
        "m_tag_gl": "Pilot's Journal Gl",
        "m_tag_historical": "Radio Signals Historical",
        "m_tag_military": "Adriatic Base Military",
        "m_tag_school": "Pilot Resolve School",
        "m_tag_martial_arts": "Daily Flight Martial Arts",
        "m_tag_vampire": "Sky Scouting Vampire",
        "m_tag_samurai": "Adriatic Art Samurai",
        "m_tag_space": "Porco Rosso Space",
        "m_tag_parody": "Classic Fan Parody",
        "m_tag_idol": "Porco Rosso Idol",
        "m_tag_post_apocalyptic": "Perfect Flight Post Apocalyptic",
        "m_tag_cyberpunk": "Pig Curse Cyberpunk",
        "m_tag_shoujo": "Cursed Ace Shoujo",
        "m_tag_survival": "Red Seaplane Survival",
        "m_tag_cooking": "Pig Pilot Cooking",
        "m_tag_medical": "Seaplane Tech Medical",
        "m_tag_villainess": "Strict Pilot Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Journey",
        "m_mega_completionist": "Ghibli Expert",
        "m_completion_rate_50": "Porco Rosso Return",
        "m_completion_rate_75": "Decade Fan Ascension",
        "m_completion_rate_90": "Ghibli Expert Resolution",
        "m_no_drop": "Sky Return Decree",
        "m_long_runner_complete": "Sky Revisit Clear",
        "m_sequel_chain": "Race Winner Seal Seal",
        "m_clean_list": "Adriatic World Relic Relic",
        "m_from_ptr": "Cursed Ace Watchlist",
        "m_reread_master": "Ghibli Critic Trial Trial",
        "m_oneshot_complete": "Ghibli Critic Ascension",
        "m_same_day_start_finish": "Gina's Love Crown Crown",
        "m_revival": "Sky Revisit Accord",
        "m_zero_to_hundred": "Classic Ghibli Banner",
        "m_five_genre_complete": "Miyazaki Fan M Five Genre",
        "m_full_collection": "Gina's Love Proof Proof",
        "m_batch_complete": "Pilot Archives Summit",
        "m_paused_to_done": "Ghibli Expert Standard Standard",
        "m_completion_spree": "Fio's Crew Triumph",
        "m_format_completionist": "Ghibli Critic Completion",
        "m_catch_up": "Sky Marathon Chronicle",
        "m_multi_reread": "Sky Return Banner",
        "m_dropped_recovery": "War Burden Conquest",
        "m_ten_perfect_scores": "Strict Pilot Judgment",
        "m_complete_genre_span": "Pirate Fleet M Complete Genre",
        "m_monthly_completions": "Ace Judge Return",
        "m_yearly_completions": "Pirate Fleet Epilogue",
        "m_rapid_complete": "Bounty Claimed Finale",
        "m_author_complete": "Pilot Resolve Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Ace Reader",
        "m_mangaka_lover": "Miyazaki Fan",
        "m_rereader": "Sky Revisit",
        "m_triple_reread": "War Memories Testament Testament",
        "m_annual_reread": "Classic Ghibli Banner Banner",
        "m_publisher_fan": "Fio's Crew Mark",
        "m_artist_fan": "Race Winner Insignia",
        "m_adaptation_compare": "Pig Pilot Insignia Insignia",
        "m_source_material_fan": "Manga First",
        "m_waiting_weekly": "Adriatic Art Streak",
        "m_classic_reader": "Classic Fan Lantern",
        "m_saga_reader": "Perfect Flight Decree",
        "m_genre_loyalty": "War Burden Loyalty",
        "m_decade_reader": "Ghibli Journey Warrant",
        "m_ln_adaptation": "Ghibli Journey Mark",
        "m_original_work": "Sky Scouting Standard",
        "m_long_commitment": "War Burden Mark",
        "m_up_to_date": "Ace's Resolve Warrant Warrant",
        "m_favorite_mangaka": "Endless Sky Treasury",
        "m_complete_portfolio": "Fio's Crew Triumph Triumph",
        "m_franchise_collector": "Sky Marathon Archive",
        "m_serialization_follower": "Endless Sky Handshake",
        "m_genre_master": "Adriatic World Master",
        "m_multi_series_author": "Perfect Flight Insignia Insignia",
        "m_format_diversity": "Sky Scouting Shelf",
        "m_year_dedication": "Dawn Takeoff Tenure",
        "m_ongoing_follower": "Ghibli Journey Fellowship",
        "m_genre_loyalty_50": "Pilot's Journal Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Aerial Combat Explorer",
        "m_publisher_hopper": "Fio's Crew Mantle",
        "m_tag_explorer": "Long Flight Explorer",
        "m_decade_hopper": "Cursed Ace Chronicle Chronicle",
        "m_hidden_gem": "Hidden Volume",
        "m_popular_taste": "Pilot Archives Record Record",
        "m_retro_reader": "Pilot Archives Accord",
        "m_modern_reader": "Radio Signals Seal Seal",
        "m_cross_demographic": "Soldier Ace Crown",
        "m_underdog_fan": "Pilot Archives Accord Accord",
        "m_variety_week": "Race Winner Horizon Horizon",
        "m_manhwa_reader": "Adriatic Aces Proof",
        "m_manhua_reader": "Classic Fan Mantle Mantle",
        "m_classic_connoisseur": "Seaplane Body Glimpse",
        "m_award_winner": "Dawn Takeoff Warrant",
        "m_niche_explorer": "Pig Pilot Horizon",
        "m_world_manga": "Sky Marathon Chronicle Chronicle",
        "m_cult_classic": "Classic Ghibli",
        "m_random_pick": "Pilot Archives Standard",
        "m_new_genre_month": "Sky Marathon M New Genre",
        "m_year_completionist": "Daily Flight Fulfillment",
        "m_unpopular_opinion": "Ace's Resolve Trial",
        "m_top_rated_reader": "Pig Pilot Record",
        "m_source_variety": "Classic Fan Catalogue",
        "m_low_score_brave": "Daily Flight Score",
        "m_short_manga_explorer": "Radio Signals Compass",
        "m_long_manga_explorer": "Classic Ghibli Survey",
        "m_serialization_explorer": "Decade Fan Road",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Porco Rosso Ledger",
        "m_commute_reader": "Seaplane Tech Tenure Tenure",
        "m_four_am_club": "Fio's Crew Fellowship",
        "m_new_year_read": "Race Winner Pact",
        "m_all_hours": "Cursed Ace Accord Accord",
        "m_prime_time_reader": "Sky Scouting Banner",
        "m_workday_reader": "Sky Revisit Accord Accord",
        "m_sunday_read": "Porco Rosso Standard Standard",
        "m_morning_routine": "Sky Revisit Discipline",
        "m_night_shift_reader": "Pilot Resolve Accord Accord",
        "m_seasonal_premier_read": "Classic Fan Seasonal",
        "m_clock_collector": "Night Flight Reserve",
        "m_late_night_horror": "Miyazaki Fan Mark Mark",
        "m_afternoon_reader": "Dawn Takeoff Mantle Mantle",
        "m_golden_hour_reader": "War Memories Observance",
        "m_dawn_reader": "Long Flight Mantle",
        "m_twilight_reader": "Ghibli Journey Crown",
        "m_midnight_start": "Sky Scouting Routine",
        "m_weekend_binge_hours": "Strict Pilot Momentum",
        "m_late_night_regular": "Porco Rosso Accord",
        "m_sunrise_reader": "Pig Curse Mantle",
        "m_every_day_of_week": "Classic Fan Warrant Warrant",
        "m_monthly_hours": "Aerial Combat Vigil",
        "m_bedtime_reader": "Daily Flight Warrant Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Adriatic Art",
        "m_webtoon_reader": "Ghibli Journey Mark Mark",
        "m_full_color": "Race Winner Accord",
        "m_doujin_reader": "Ghibli Expert Record Record",
        "m_anthology_reader": "Strict Pilot Accord",
        "m_adaptation_reader": "Pilot Archives Banner",
        "m_longstrip_reader": "War Memories Trial",
        "m_4koma_reader": "Adriatic Art Ledger",
        "m_oneshot_reader": "Pirate Fleet Mantle",
        "m_format_variety": "Fio's Crew Gallery",
        "m_light_novel_reader": "Cursed Ace Insignia",
        "m_novel_reader": "Daily Flight Crown",
        "m_visual_storyteller": "Dawn Takeoff Testament",
        "m_colored_classic": "All Bounties Survey",
        "m_webcomic_fan": "Seaplane Body Insignia",
        "m_manga_to_anime": "Manga Adapted",
        "m_seinen_reader": "War Burden Pinnacle",
        "m_josei_reader": "Pig Curse Pinnacle",
        "m_award_winning_art": "Adriatic Base Relic",
        "m_debut_work": "Adriatic Base Dominion",
        "m_vertical_scroll": "Perfect Flight Decree Decree",
        "m_traditional_format": "Pig Pilot Hoard",
        "m_cross_media": "Radio Signals Accord",
        "m_spinoff_reader": "Sky Marathon Accord",
        "m_remake_reader": "Ghibli Critic Pinnacle",
        "m_collaboration_reader": "Seaplane Body Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Adriatic Streak",
        "m_weekly_warrior": "Decade Fan Season",
        "m_monthly_reader": "Ace Medals Discipline",
        "m_comeback": "Classic Ghibli Standard Standard",
        "m_weekend_streak": "Pig Curse Fever",
        "m_no_zero_days": "Adriatic Aces Proof Proof",
        "m_iron_will": "Pilot Resolve",
        "m_habit_formed": "Soldier Ace Crown Crown",
        "m_consistent_pace": "Gina's Love Scrutiny Scrutiny",
        "m_year_long": "Year Reading",
        "m_double_streak": "Pirate Fleet Resolve",
        "m_streak_recovery": "Adriatic World Resolve",
        "m_daily_minimum": "Night Flight Focus",
        "m_winter_streak": "War Memories Observance Observance",
        "m_summer_streak": "Adriatic Base Observance",
        "m_morning_streak": "Aerial Combat Clock",
        "m_night_streak": "Pig Pilot Discipline",
        "m_unbreakable": "Pig Curse Warrant",
        "m_eternal_flame": "Red Seaplane Record",
        "m_chapter_a_day": "Porco Rosso Ledger Ledger",
        "m_genre_streak": "Long Flight Streak",
        "m_completion_streak": "Pilot Archives Return",
        "m_rating_streak": "Long Flight Appraisal",
        "m_multi_ch_streak": "Decade Fan Tenure",
        "m_author_streak": "Night Flight Calendar",
        "m_perfect_week_manga": "Sky Marathon Accord Accord",
        "m_diverse_streak": "Sky Return Streak",

        // ── MANGA SCORING ──
        "m_critic": "Ghibli Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_harsh_critic": "Cursed Ace Scale",
        "m_fair_judge": "All Night Eye Eye",
        "m_generous_spirit": "Strict Pilot Decree",
        "m_score_all": "Ghibli Journey Reckoning",
        "m_wide_range": "Ace Medals Ledger Ledger",
        "m_controversial": "Ace Judge Standard Standard",
        "m_consistent_scorer": "Ghibli Expert Grade",
        "m_score_sniper": "Ace's Resolve Reckoning",
        "m_evolving_taste": "Pirate Fleet Trial Trial",
        "m_bell_curve": "Ace Medals Accord",
        "m_picky_reader": "Sky Return Ledger",
        "m_100_rated": "Ace Medals Standard",
        "m_500_rated": "Pilot Resolve Aegis",
        "m_mediocre_majority": "Pirate Fleet Canon",
        "m_rating_spree": "Aerial Combat Verdict",
        "m_score_variance": "Daily Flight Measure",
        "m_binge_rater": "Night Flight Passage",
        "m_reread_rerate": "All Bounties Banner Banner",
        "m_masterpiece_hunter": "Ace Judge Banner",
        "m_contrarian": "Pilot Archives Aegis",
        "m_optimist": "Radio Signals Accord Accord",
        "m_score_distributor": "Decade Fan Balance",
        "m_genre_critic": "Night Flight Critic",
        "m_mean_above_8": "Daily Flight Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Dawn Takeoff Season",
        "m_valentines_read": "Long Flight Observance",
        "m_pi_day": "Pirate Fleet Testament Testament",
        "m_april_fools": "Ace's Resolve Devotion",
        "m_international_manga_day": "Cursed Ace Aegis",
        "m_free_comic_day": "Strict Pilot Chronicle",
        "m_summer_solstice": "Bounty Claimed Focus Focus",
        "m_tanabata": "Gina's Love Tanabata",
        "m_friday_13th": "Ghibli Critic Dominion Dominion",
        "m_halloween_read": "Miyazaki Fan Halloween",
        "m_thanksgiving_binge": "Sky Marathon Charge",
        "m_christmas_read": "Sky Revisit Pact",
        "m_new_years_eve": "Bounty Claimed Pilgrimage",
        "m_birthday_read": "War Burden Focus",
        "m_holiday_marathon": "Endless Sky Rally",
        "m_independence_day": "Pilot Archives Aegis Aegis",
        "m_culture_day": "Pilot Resolve Seal Seal",
        "m_spring_equinox": "Miyazaki Fan Dominion",
        "m_earth_day": "War Burden Trial",
        "m_labor_day": "Sky Revisit Seal",
        "m_winter_solstice": "Soldier Ace Focus Focus",
        "m_manga_birthday": "Gina's Love Ritual",
        "m_every_holiday_reader": "Adriatic World Watch",
        "m_consecutive_holidays": "Ghibli Critic Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Radio Alerts Aegis",
        "m_fibonacci": "Seaplane Tech Dominion",
        "m_palindrome_day": "Pirate Fleet Relic",
        "m_binary_day": "Soldier Ace Proof",
        "m_full_moon_read": "Pig Curse Crown",
        "m_leap_year_read": "Sky Return Practice",
        "m_triple_seven": "All Night Trial Trial",
        "m_thousand_complete": "All Night Ascension",
        "m_nice": "Perfect Flight Seal Seal",
        "m_power_level_chapters": "Classic Ghibli Aegis",
        "m_answer_42": "Pig Curse Trial",
        "m_square_number": "Red Seaplane Standard",
        "m_prime_count": "All Night Pinnacle",
        "m_matching_date": "Adriatic World Mantle",
        "m_century_chapter": "Radio Alerts Decree",
        "m_pi_chapters": "War Burden Proof Proof",
        "m_synchronicity": "Long Flight Emblem",
        "m_world_record": "Adriatic Aces Warrant",
        "m_genre_clash": "Sky Scouting Clash",
        "m_time_traveler": "Ghibli Expert Decree",
        "m_double_digits": "Classic Fan Dominion",
        "m_one_two_three": "Seaplane Body Banner Banner",
        "m_lucky_seven": "Pig Pilot Record Record",
        "m_exact_hundred_ch": "Seaplane Tech Legend",
        "m_year_match_count": "Adriatic Art Routine",
        "m_chapter_match_date": "Soldier Ace Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Classic Fan Index",
        "m_manhwa_format": "Miyazaki Fan Gallery",
        "m_manhua_format": "War Memories Storehouse",
        "m_ln_format": "All Night Index",
        "m_oneshot_format": "Pirate Fleet Index",
        "m_doujin_format": "Aerial Combat Cabinet",
        "m_novel_format": "Ace's Resolve Reserve Reserve",
        "m_format_master_manga": "Aerial Combat Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Ghibli Expert Link",
        "m_meta_collector": "Pilot Resolve Reliquary",
        "m_meta_category_starter": "Fio's Crew Standard",
        "m_meta_tier_climber": "Radio Signals Token",
        "m_meta_tier_max": "Sky Complete",
        "m_meta_xp_earner": "Classic Fan Anchor",
        "m_meta_difficulty_easy": "All Night Panel",
        "m_meta_difficulty_hard": "Dawn Takeoff Node",
        "m_meta_unlock_spree": "Classic Fan Marker",
        "m_meta_completionist": "Full Library",
        "m_meta_diverse": "Pirate Fleet Anchor",
        "m_meta_dominator": "Perfect Flight Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060402",
        primary: "#824826",
        secondary: "#523618",
        accent: "#60a0d0",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/porco-rosso.jpg",
    particleColor: "#a07050",
    backgroundDim: 0.32,
    backgroundBlur: 18,
    particleTypes: {
        sea_breeze: { label: "Sea Breeze", maxCount: 18, defaultEnabled: true, defaultIntensity: 55 },
        engine_sparks: { label: "Engine Sparks", maxCount: 10, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
  1: "Threadbare Generic Rank Spark",
  8: "Generic's Tarnished Omen",
  14: "Fractured Generic Rank",
  21: "Generic Rank Path",
  28: "Lowborn Legacy Myth",
  35: "Generic Rank Pulse",
  41: "Generic's Legacy Crest",
  48: "Humble Generic Mark",
  55: "Ragged Generic Rank Vow",
  61: "Generic's Faint Echo",
  68: "Lesser Generic Rank",
  75: "Generic Rank Zenith",
  81: "Doubtful Legacy Bloom",
  88: "Generic Rank Sigil",
  95: "Generic's Legacy Flame",
  102: "Really Cool Generic Spark",
  108: "Awakened Generic Rank Omen",
  115: "Generic's Resolute Seal",
  122: "Rising Generic Rank",
  128: "Generic Rank Myth",
  135: "Dauntless Legacy Pulse",
  142: "Generic Rank Crest",
  149: "Generic's Legacy Mark",
  155: "Fresh Generic Vow",
  162: "Valiant Generic Rank Echo",
  169: "Generic's Prime Crown",
  175: "Polished Generic Rank",
  182: "Generic Rank Bloom",
  189: "Stormlit Legacy Sigil",
  195: "Generic Rank Flame",
  202: "Generic's Legacy Spark",
  209: "Tempered Generic Omen",
  216: "Trusted Generic Rank Seal",
  222: "Generic's Steadfast Path",
  229: "Ironclad Generic Rank",
  236: "Veteran Legacy Pulse",
  242: "Core Legacy Crest",
  249: "Generic Rank Mark",
  256: "Generic's Legacy Vow",
  262: "Formidable Generic Echo",
  269: "Lucid Generic Rank Crown",
  276: "Generic's Ranked Zenith",
  283: "Fabled Generic Rank",
  289: "Grand Legacy Sigil",
  296: "Seasoned Legacy Flame",
  303: "Generic Rank Spark",
  309: "Generic's Legacy Omen",
  316: "Valorous Generic Seal",
  323: "Stalwart Generic Rank Path",
  330: "Generic's Commanding Myth",
  336: "Refined Generic Rank",
  343: "Unbroken Legacy Crest",
  350: "Blazing Legacy Mark",
  356: "Generic Rank Vow",
  363: "Generic's Legacy Echo",
  370: "Peerless Generic Crown",
  376: "Ardent Generic Rank Zenith",
  383: "Generic's Focused Bloom",
  390: "Vigilant Generic Rank",
  397: "Dominant Legacy Flame",
  403: "Elite Legacy Spark",
  410: "Generic Rank Omen",
  417: "Generic's Legacy Seal",
  423: "Sovereign Generic Path",
  430: "Regal Generic Rank Myth",
  437: "Generic's Crowned Pulse",
  444: "Mythborn Generic Rank",
  450: "Limitless Legacy Mark",
  457: "Radiant Legacy Vow",
  464: "Generic Rank Echo",
  470: "Generic's Legacy Crown",
  477: "Climactic Generic Zenith",
  484: "Epic Generic Rank Bloom",
  490: "Generic's Unreal Sigil",
  497: "Peak Generic Rank",
  504: "Supreme Legacy Spark",
  511: "Exalted Legacy Omen",
  517: "Generic Rank Seal",
  524: "Generic's Legacy Path",
  531: "Celestial Generic Myth",
  537: "Phantom Generic Rank Pulse",
  544: "Generic's Crimson Crest",
  551: "Silver Generic Rank",
  557: "Golden Legacy Vow",
  564: "Feral Legacy Echo",
  571: "Generic Rank Crown",
  578: "Generic's Legacy Zenith",
  584: "Dread Generic Bloom",
  591: "Luminous Generic Rank Sigil",
  598: "Generic's Thunderous Flame",
  604: "Ultraviolet Generic Rank",
  611: "Unleashed Legacy Omen",
  618: "Secret Legacy Seal",
  625: "Final Generic Path",
  631: "Generic's Legacy Myth",
  638: "Worldclass Generic Pulse",
  645: "Lawless Generic Rank Crest",
  651: "Generic's Chosen Mark",
  658: "Fearless Generic Rank",
  665: "Overdrive Legacy Echo",
  671: "Cinematic Legacy Crown",
  678: "Impossible Generic Zenith",
  685: "Generic's Legacy Bloom",
  692: "Canonized Generic Sigil",
  698: "Ascendant Generic Rank Flame",
  705: "Generic's Transfigured Spark",
  712: "Immortal Generic Rank",
  718: "Eclipsed Legacy Seal",
  725: "Astral Legacy Path",
  732: "Sublime Generic Myth",
  739: "Generic's Legacy Pulse",
  745: "Prismatic Generic Crest",
  752: "Abyssal Generic Rank Mark",
  759: "Generic's Unbound Vow",
  765: "Eternal Generic Rank",
  772: "Cosmic Legacy Crown",
  779: "Transcendent Legacy Zenith",
  785: "Perfected Generic Bloom",
  792: "Generic's Legacy Sigil",
  799: "Ultimate Generic Flame",
  806: "Mythic Generic Rank Spark",
  812: "Generic's Godlike Omen",
  819: "Canonical Generic Rank",
  826: "Reality-Bent Legacy Path",
  832: "Heavenly Legacy Myth",
  839: "Absolute Generic Pulse",
  846: "Untouchable Generic Crest",
  852: "Timeless Generic Mark",
  859: "Empyrean Generic Rank Vow",
  866: "Generic's Primordial Echo",
  873: "Omniscient Generic Rank",
  879: "Unfathomed Legacy Zenith",
  886: "Apocalyptic Legacy Bloom",
  893: "Seraphic Generic Sigil",
  899: "Omega Generic Flame",
  906: "Final Generic Spark",
  913: "Crowned Generic Rank Omen",
  920: "Generic's Mythic Seal",
  926: "Absolute Generic Rank",
  933: "Eternal Legacy Myth",
  940: "Cosmic Legacy Pulse",
  946: "Transcendent Generic Crest",
  953: "Perfected Generic Mark",
  960: "Definitive Generic Vow",
  966: "Ultimate Generic Rank Echo",
  973: "Generic's Infinite Crown",
  980: "Sovereign Generic Rank",
  987: "Celestial Legacy Bloom",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate Generic Rank"
},
}
