import { AnimeThemeConfig } from "./types"
import { GiQuillInk, GiBookmarklet, GiScrollUnfurled, GiPencilBrush, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiLaptop } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const reCreatorsTheme: AnimeThemeConfig = {
    id: "re-creators",
    displayName: "Re:CREATORS",
    description: "Fictional characters from anime, manga, and games are pulled into the real world, and the creators who made them must confront their own creations as a rogue character called the Military Uniform Princess seeks to destroy reality itself.",
    fontFamily: "'Orbitron', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "210 210 228",
        "--color-brand-300": "178 178 215",
        "--color-brand-400": "142 142 198",
        "--color-brand-500": "108 108 180",
        "--color-brand-600": "78 78 152",
        "--color-brand-700": "52 52 118",
        "--color-brand-800": "30 30 80",
        "--color-brand-900": "14 14 42",
        "--color-brand-950": "5 5 18",
        "--brand": "108 108 180",
        "--background": "#030304",
        "--paper": "#08080e",
        "--color-gray-950": "3 3 4",
        "--color-gray-900": "8 8 12",
        "--color-gray-800": "15 15 22",
        "--color-gray-700": "26 26 38",
        "--color-gray-600": "44 44 62",
        "--color-gray-500": "72 72 95",
        "--color-gray-400": "108 108 138",
        "--color-gray-300": "152 152 182",
        "--color-gray-200": "192 192 215",
        "--color-gray-100": "218 218 235",
        "--color-gray-50": "238 238 250",
    },
    sidebarOverrides: {
        "home": { icon: GiScrollUnfurled, label: "Creation World" },
        "schedule": { icon: GiAlarmClock, label: "Story Schedule" },
        "manga": { icon: LuBookOpen, label: "Creator Notes" },
        "lists": { icon: GiBookmarklet, label: "Character Registry" },
        "discover": { icon: GiBullseye, label: "New Creations" },
        "torrent-list": { icon: GiQuillInk, label: "Story Cache" },
        "debrid": { icon: GiLaptop, label: "Creator Studio" },
        "unmatched": { icon: GiPencilBrush, label: "Unknown Characters" },
        "enmasse": { icon: GiResize, label: "Grand Battle" },
        "scan-summaries": { icon: TbReportSearch, label: "Story Reports" },
        "auto-downloader": { icon: LuRss, label: "Creator Feed" },
        "community": { icon: GiScrollUnfurled, label: "Creator Circle" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Story Alerts" },
        "achievements": { icon: GiTrophy, label: "Creator Trophies" },
        "milestones": { icon: LuFlag, label: "Creator Goals" },
        "theme-manager": { icon: GiPalette, label: "Meta Colors" },
        "extensions": { icon: BiExtension, label: "Story Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Creator Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Sota's Settings" },
    },
    achievementNames: {
        "a_first_episode": "First Creation",
        "a_first_complete": "Reality Saved",
        "a_hundred_club": "Hundred Stories",
        "a_time_lord": "Creator Veteran",
        "a_anime_collector": "Character Collection",
        "a_library_legend": "Creation Archives",
        "a_binge_king": "Story Marathon",
        "a_no_sleep": "All-Night Creation",
        "a_marathon_runner": "Sota's Run",
        "a_speed_run": "Selesia Speed",
        "a_completionist": "All Episodes",
        "a_mega_completionist": "Rei Master",
        "a_loyal_fan": "Creator Ally",
        "a_rewatcher": "World Return",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Character Battle",
        "a_genre_adventure": "Real World",
        "a_genre_comedy": "Celestia Moments",
        "a_genre_drama": "Creator's Choice",
        "a_genre_fantasy": "Fictional World",
        "a_genre_horror": "Altair's Plan",
        "a_genre_romance": "Sota's Guilt",
        "a_genre_scifi": "Reality Bending",
        "a_genre_supernatural": "Story Power",
        "a_genre_psychological": "Creator Responsibility",
        "a_genre_mecha": "Selesia's Mech",
        "a_critic": "Story Critic",
        "a_perfect_ten": "Perfect Story",
        "a_harsh_critic": "Altair's Standard",
        "a_daily_streak": "Daily Creation",
        "a_mega_streak": "Endless Stories",
        "a_year_long": "Year of Stories",
        "a_iron_will": "Creator's Will",
        "a_hidden_gem": "Hidden Episode",
        "a_cult_classic": "Troyca Classic",
        "a_classic_connoisseur": "2017 Fan",
        "a_new_years_resolution": "New Year Story",
        "a_christmas_special": "Winter Creation",
        "a_meta_tier_max": "Meta Creator",
        "a_meta_completionist": "All Stories",
        "a_sequel_chain": "Manga Continues",
        "a_zero_to_hero": "Fan to Hero",
        "a_night_owl": "Night Creation",
        "a_early_bird": "Dawn Writing",
        "m_first_chapter": "First Draft",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Story Marathon",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Re:Creators Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "World Return",
        "m_genre_action": "Battle Chapter",
        "m_genre_adventure": "Real Chapter",
        "m_genre_romance": "Guilt Chapter",
        "m_genre_fantasy": "Fiction Chapter",
        "m_genre_horror": "Altair Chapter",
        "m_genre_drama": "Creation Chapter",
        "m_genre_scifi": "Reality Chapter",
        "m_genre_supernatural": "Power Chapter",
        "m_genre_psychological": "Creator Depth",
        "m_critic": "Story Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Creator Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Author Resolve",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Troyca Classic",
        "m_mangaka_lover": "Rei Fan",
        "m_source_material_fan": "Original Work",
        "m_meta_tier_max": "Re:Creators Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Creator Art",
        "m_manga_to_anime": "Original Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#030304",
        primary: "#6c6cb4",
        secondary: "#4e4e98",
        accent: "#e05820",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/re-creators.jpg",
    particleColor: "#9090d0",
    backgroundDim: 0.38,
    backgroundBlur: 18,
    particleTypes: {
        story_fragments: { label: "Story Fragments", maxCount: 18, defaultEnabled: true, defaultIntensity: 58 },
        code_particles: { label: "Code Particles", maxCount: 12, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
        1: "Fan Artist",
        5: "Sota Mizushino",
        15: "Creation Witness",
        30: "Anime-Ka",
        50: "Creator's Ally",
        75: "Reality Defender",
        100: "True Creator",
    },
}
