import { AnimeThemeConfig } from "./types"
import { GiQuillInk, GiBookmarklet, GiScrollUnfurled, GiPencilBrush, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiLaptop } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const reCreatorsTheme: AnimeThemeConfig = {
    id: "re-creators",
    displayName: "Re:CREATORS",
    description: "Fictional characters from anime, manga, and games are pulled into the real world, and the creators who made them must confront their own creations as a rogue character called the Military Uniform Princess seeks to destroy reality itself.",
    fontFamily: "'Orbitron', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "210 210 228",
        "--color-brand-300": "178 178 215",
        "--color-brand-400": "142 142 198",
        "--color-brand-500": "108 108 180",
        "--color-brand-600": "78 78 152",
        "--color-brand-700": "52 52 118",
        "--color-brand-800": "30 30 80",
        "--color-brand-900": "14 14 42",
        "--color-brand-950": "5 5 18",
        "--brand": "108 108 180",
        "--background": "#030304",
        "--paper": "#08080e",
        "--color-gray-950": "3 3 4",
        "--color-gray-900": "8 8 12",
        "--color-gray-800": "15 15 22",
        "--color-gray-700": "26 26 38",
        "--color-gray-600": "44 44 62",
        "--color-gray-500": "72 72 95",
        "--color-gray-400": "108 108 138",
        "--color-gray-300": "152 152 182",
        "--color-gray-200": "192 192 215",
        "--color-gray-100": "218 218 235",
        "--color-gray-50": "238 238 250",
    },
    sidebarOverrides: {
        "home": { icon: GiScrollUnfurled, label: "Creation World" },
        "schedule": { icon: GiAlarmClock, label: "Story Schedule" },
        "manga": { icon: LuBookOpen, label: "Creator Notes" },
        "lists": { icon: GiBookmarklet, label: "Character Registry" },
        "discover": { icon: GiBullseye, label: "New Creations" },
        "torrent-list": { icon: GiQuillInk, label: "Story Cache" },
        "debrid": { icon: GiLaptop, label: "Creator Studio" },
        "unmatched": { icon: GiPencilBrush, label: "Unknown Characters" },
        "enmasse": { icon: GiResize, label: "Grand Battle" },
        "scan-summaries": { icon: TbReportSearch, label: "Story Reports" },
        "auto-downloader": { icon: LuRss, label: "Creator Feed" },
        "community": { icon: GiScrollUnfurled, label: "Creator Circle" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Story Alerts" },
        "achievements": { icon: GiTrophy, label: "Creator Trophies" },
        "milestones": { icon: LuFlag, label: "Creator Goals" },
        "theme-manager": { icon: GiPalette, label: "Meta Colors" },
        "extensions": { icon: BiExtension, label: "Story Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Creator Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Sota's Settings" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Creation",
        "a_episode_counter": "Author Resolve Mark",
        "a_episode_titan": "Altair's Plan Relic",
        "a_hours_invested": "Rei Fan Proof",
        "a_time_lord": "Creator Veteran",
        "a_anime_collector": "Character Collection",
        "a_library_legend": "Creation Archives",
        "a_first_complete": "Reality Saved",
        "a_hundred_club": "Hundred Stories",
        "a_first_day": "Creator Notes Seal",
        "a_first_rating": "Altair's Plan Appraisal",
        "a_ten_thousand_min": "Selesia's Mech Standard",
        "a_season_veteran": "Selesia's Mech Library",
        "a_year_explorer": "Original Work Map",
        "a_century_watcher": "Creator Studio Ledger",
        "a_five_hundred_eps": "Dawn Writing Dominion",
        "a_thousand_eps": "Creator's Will Record",
        "a_watching_ten": "Military Uniform Princess Acclaim",
        "a_ptw_hoarder": "Character Battle Library",
        "a_dropped_honesty": "Military Uniform Princess Summit",
        "a_five_thousand_eps": "Creator Circle Warrant",
        "a_ten_completed": "Meta Creator Afterglow",
        "a_fifty_completed": "Troyca Classic Ascension",
        "a_five_hundred_completed": "Military Uniform Princess Clear",
        "a_mean_score_tracker": "Fictional World Verdict",
        "a_unique_studios": "Creator's Will Collection",
        "a_days_spent_watching": "Creator Trophies Dominion",
        "a_all_status": "Reality Bending Testament",
        "a_first_favorite": "All Stories Cabinet",
        "a_favorites_collector": "Selesia Speed Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Reality Saved Drive",
        "a_marathon_runner": "Sota's Run",
        "a_weekend_warrior": "Altair's Plan Ordeal",
        "a_non_stop": "Celestia Moments Fever",
        "a_one_more_episode": "Creation World Mantle",
        "a_speed_run": "Selesia Speed",
        "a_double_feature": "Story Power Crown",
        "a_triple_threat": "Story Marathon Record",
        "a_five_a_day": "Re Creators Accord",
        "a_back_to_back": "Creator Streak Surge",
        "a_seasonal_binge": "Altair's Plan Cascade",
        "a_cour_crusher": "Creator Trophies Ordeal",
        "a_half_day_watch": "Author Resolve Crown",
        "a_full_day_watch": "Story Alerts Pinnacle",
        "a_power_weekend": "Creator Notes Run",
        "a_binge_king": "Story Marathon",
        "a_no_sleep": "All-Night Creation",
        "a_entire_season": "Sota's Guilt Library",
        "a_seven_day_challenge": "Story Alerts Mark",
        "a_hundred_day_binge": "Creator Notes Surge",
        "a_genre_binge": "Creator's Choice Binge",
        "a_studio_binge": "Author Resolve Fever",
        "a_season_sweep": "Original Adapted Codex",
        "a_forty_eight_hour": "Creator Ally Overture",
        "a_ep_counter_day": "Meta Creator Aegis",
        "a_multi_series_binge": "Character Battle Streak",
        "a_midnight_binge": "Creation World Cascade",
        "a_new_year_binge": "Story Critic Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Character Battle",
        "a_genre_adventure": "Real World",
        "a_genre_comedy": "Celestia Moments",
        "a_genre_drama": "Creator's Choice",
        "a_genre_fantasy": "Fictional World",
        "a_genre_horror": "Altair's Plan",
        "a_genre_mystery": "Creators Expert Mystery",
        "a_genre_romance": "Sota's Guilt",
        "a_genre_scifi": "Reality Bending",
        "a_genre_sol": "Creator Circle Slice",
        "a_genre_sports": "Creator Ally Sports",
        "a_genre_supernatural": "Story Power",
        "a_genre_thriller": "Troyca Classic Thriller",
        "a_genre_mecha": "Selesia's Mech",
        "a_genre_music": "Selesia's Mech Music",
        "a_genre_psychological": "Creator Responsibility",
        "a_genre_ecchi": "Reality Saved Ecchi",
        "a_genre_mahou_shoujo": "Story Marathon Magic Shoujo",
        "a_tag_isekai": "Fan Hero Isekai",
        "a_tag_harem": "Rei Master Harem",
        "a_tag_bl": "Creator Ally Bl",
        "a_tag_gl": "Creation World Gl",
        "a_tag_historical": "Sota's Run Historical",
        "a_tag_military": "Dawn Writing Military",
        "a_tag_school": "Character Battle School",
        "a_tag_martial_arts": "Story Alerts Martial Arts",
        "a_tag_vampire": "Story Marathon Vampire",
        "a_tag_samurai": "Creator's Will Samurai",
        "a_tag_space": "Decade Fan Space",
        "a_tag_parody": "Creator Art Parody",
        "a_tag_idol": "Creator Ally Idol",
        "a_tag_post_apocalyptic": "Endless Stories Post Apocalyptic",
        "a_tag_cyberpunk": "Celestia Moments Cyberpunk",
        "a_tag_shounen": "Endless Stories Shounen",
        "a_tag_seinen": "Grand Battle Seinen",
        "a_tag_shoujo": "Grand Battle Shoujo",
        "a_tag_josei": "Meta Creator Josei",
        "a_tag_survival": "Selesia Speed Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "All Episodes",
        "a_mega_completionist": "Rei Master",
        "a_completion_rate_50": "Story Marathon Return",
        "a_completion_rate_75": "Troyca Classic Crown",
        "a_completion_rate_90": "Meta Creator Resolution",
        "a_no_drop": "Creators Expert Decree",
        "a_long_runner_complete": "Creator Notes Clear",
        "a_sequel_chain": "Manga Continues",
        "a_clean_list": "Original Adapted Relic",
        "a_from_ptw": "Creator Art Index",
        "a_rewatch_master": "Fictional World Return",
        "a_short_complete": "Daily Creation Endgame",
        "a_same_day_start_finish": "Winter Creation Pinnacle",
        "a_revival": "Creator Studio Insignia",
        "a_zero_to_hero": "Fan to Hero",
        "a_five_genre_complete": "Daily Creation A Five Genre",
        "a_full_franchise": "Character Battle Chronicle",
        "a_batch_complete": "Altair's Plan Crown",
        "a_paused_to_done": "Meta Creator Aegis Aegis",
        "a_completion_spree": "Creator Depth Triumph",
        "a_multi_rewatch": "Creator Depth Triumph Triumph",
        "a_dropped_recovery": "Author Resolve Conquest",
        "a_ten_perfect_scores": "Creator Notes Acclaim",
        "a_seasonal_clear": "Creator Trophies Codex",
        "a_complete_genre_span": "Real World A Complete Genre",
        "a_monthly_completions": "Fictional World Afterglow",
        "a_yearly_completions": "Reality Bending Epilogue",
        "a_rapid_complete": "Story Alerts Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Creator Ally",
        "a_studio_devotee": "Creators Expert Treasury",
        "a_rewatcher": "World Return",
        "a_triple_rewatch": "Creator's Choice Coda",
        "a_annual_tradition": "Story Alerts Proof",
        "a_director_fan": "Original Adapted Trial",
        "a_voice_actor_fan": "Author Resolve Crown Crown",
        "a_ost_lover": "Character Battle Seal",
        "a_source_reader": "Original Work Cabinet",
        "a_waiting_weekly": "Creators Expert Clock",
        "a_childhood_revisit": "Perfect Story Seal",
        "a_saga_tracker": "Decade Fan Standard",
        "a_genre_loyalty": "Creator Circle Loyalty",
        "a_decade_watcher": "Decade Fan",
        "a_adaptation_hunter": "Creator Art Trial",
        "a_original_anime_fan": "World Return Testament",
        "a_long_commitment": "Story Alerts Mark Mark",
        "a_perfect_attendance": "Military Uniform Princess Standard",
        "a_favorite_studio_5": "Endless Stories Library",
        "a_complete_catalog": "Selesia Speed Seal",
        "a_franchise_collector": "Endless Stories Archive",
        "a_airing_follower": "Perfect Story Signal",
        "a_genre_master": "Original Adapted Master",
        "a_staff_follower": "Endless Stories Oath",
        "a_multi_season_fan": "Sota's Run Hoard",
        "a_format_diversity": "Story Marathon Cache",
        "a_year_dedication": "Altair's Plan Tenure",
        "a_season_dedication": "Dawn Writing Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Creator's Choice Explorer",
        "a_studio_hopper": "Fictional World Collection",
        "a_tag_explorer": "Altair's Plan Explorer",
        "a_decade_hopper": "Character Battle Chronicle Chronicle",
        "a_hidden_gem": "Hidden Episode",
        "a_popular_taste": "Creator Ally Decree",
        "a_retro_appreciator": "Selesia Speed Aegis",
        "a_modern_viewer": "Winter Creation Pinnacle Pinnacle",
        "a_cross_demographic": "Reality Saved Pinnacle",
        "a_underdog_fan": "Real World Trial",
        "a_variety_week": "Endless Stories Horizon",
        "a_foreign_cinema": "Creation World Expedition",
        "a_classic_connoisseur": "2017 Fan",
        "a_every_season": "Perfect Story Archive",
        "a_award_winner": "Selesia's Mech Insignia",
        "a_niche_explorer": "Grand Battle Horizon",
        "a_global_anime": "Daily Creation Crown",
        "a_cult_classic": "Troyca Classic",
        "a_random_pick": "Creator Ally Decree Decree",
        "a_new_genre_month": "Military Uniform Princess A New",
        "a_seasonal_completionist": "Creator Studio Summit",
        "a_unpopular_opinion": "All Stories Standard",
        "a_top_rated_viewer": "Re Creators Seal",
        "a_source_variety": "Creator Trophies Storehouse",
        "a_low_score_brave": "Celestia Moments Measure",
        "a_upcoming_watcher": "Re Creators Seal Seal",
        "a_short_series_explorer": "Creation World Expedition Expedition",
        "a_long_series_explorer": "Story Power Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Night Creation",
        "a_early_bird": "Dawn Writing",
        "a_lunch_break": "All Night Trial",
        "a_golden_hour": "Night Creation Tenure",
        "a_four_am_club": "Creator Depth Gathering",
        "a_witching_hour": "Troyca Classic Tenure",
        "a_new_year_watch": "Altair's Plan Season",
        "a_midnight_premiere": "Story Critic Devotion",
        "a_all_hours": "Creator Studio Seal",
        "a_dawn_warrior": "Creator Ally Aegis",
        "a_afternoon_delight": "Rei Fan Proof Proof",
        "a_prime_time": "Selesia's Mech Insignia Insignia",
        "a_workday_watcher": "Reality Saved Pinnacle Pinnacle",
        "a_sunday_marathon": "Creator Notes Momentum",
        "a_rainy_day": "Troyca Classic Relic",
        "a_morning_routine": "Sota's Run Promise",
        "a_night_shift": "Story Marathon Aegis",
        "a_twilight_zone": "Sota's Guilt Ledger",
        "a_seasonal_premier": "Creators Expert Cabinet",
        "a_clock_collector": "Creator Depth Repository",
        "a_weekend_binge_hours": "Grand Battle Streak",
        "a_late_night_regular": "Reality Bending Dominion",
        "a_sunrise_watcher": "Original Adapted Relic Relic",
        "a_holiday_watcher": "Re Creators Pact",
        "a_every_day_of_week": "Creator Streak Ledger",
        "a_monthly_hours": "Creator Ally Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Meta Creator Record",
        "a_party_host": "Story Marathon Record Record",
        "a_social_butterfly": "Original Work Company",
        "a_group_binge": "Creator's Will Sprint",
        "a_party_regular": "Sota's Guilt Chronicle",
        "a_sync_viewer": "Creator Depth Standard",
        "a_commentator": "Selesia Speed Record",
        "a_party_marathon": "Creator's Choice Vigil",
        "a_full_house": "Dawn Writing Trial",
        "a_community_pillar": "Reality Bending Alliance",
        "a_watch_party_streak": "Selesia Speed Vigil",
        "a_diverse_party": "Sota's Run Seal",
        "a_late_night_party": "Reality Bending Testament Testament",
        "a_party_veteran": "Dawn Writing Testament",
        "a_genre_party": "Creation World Party",
        "a_weekly_party": "Creator Depth Calendar",
        "a_silent_viewer": "World Return Mantle",
        "a_recommendation_giver": "Grand Battle Network",
        "a_party_completionist": "Decade Fan Coda",
        "a_social_scorer": "Original Adapted Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Story Power Proof",
        "a_fibonacci": "Altair's Plan Dominion",
        "a_palindrome_day": "Altair's Plan Relic Relic",
        "a_binary_day": "Creator Circle Mark",
        "a_full_moon": "Perfect Story Insignia",
        "a_leap_year": "Daily Creation Devotion",
        "a_time_traveler": "Creators Expert Record",
        "a_genre_clash": "Creator's Choice Clash",
        "a_triple_seven": "Altair's Plan Testament",
        "a_thousand_complete": "World Return Epilogue",
        "a_pi_episodes": "Reality Saved Crown",
        "a_synchronicity": "Real World Anchor",
        "a_world_record": "Author Resolve Warrant",
        "a_nice": "Selesia's Mech Chronicle",
        "a_power_level": "World Return Testament Testament",
        "a_answer_42": "Creator Ally Standard",
        "a_square_number": "Creator's Choice Decree",
        "a_prime_count": "Selesia's Mech Seal",
        "a_matching_date": "Real World Mantle",
        "a_century_episode": "Reality Saved Mark",
        "a_double_digits": "Troyca Classic Testament",
        "a_one_two_three": "Daily Creation Crown Crown",
        "a_lucky_seven": "Story Alerts Crown",
        "a_all_tens": "Celestia Moments Criterion",
        "a_exact_hundred_eps": "Decade Fan Legend",
        "a_year_match_count": "Creators Expert Yearlong",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Grand Battle Ledger",
        "a_movie_buff": "Author Resolve Mark Mark",
        "a_ova_hunter": "Decade Fan Standard Standard",
        "a_ona_explorer": "Real World Secret",
        "a_special_watcher": "Troyca Classic Relic Relic",
        "a_short_king": "Rei Master Crown",
        "a_variety_pack": "Author Resolve Inquiry",
        "a_film_festival": "Re Creators Chronicle",
        "a_music_video": "Sota's Run Chronicle",
        "a_tv_short": "Creator's Choice Record",
        "a_movie_marathon": "Creator's Choice Gauntlet",
        "a_double_length": "Story Power Crown Crown",
        "a_anthology": "Story Marathon Aegis Aegis",
        "a_mini_series": "All Stories Decree",
        "a_theatrical": "Endless Stories Accord",
        "a_format_master": "Creator Depth Vault",
        "a_long_movie": "Creator Studio Insignia Insignia",
        "a_back_catalog": "Selesia Speed Standard",
        "a_cm_watcher": "Fan Hero Aegis",
        "a_pv_collector": "Real World Storehouse",
        "a_format_balance": "Creator Depth Vault Vault",
        "a_episodic_master": "Fan Hero Standard",
        "a_sequel_movie": "Daily Creation Pinnacle",
        "a_recap_watcher": "All Night Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Creation",
        "a_mega_streak": "Endless Stories",
        "a_weekly_warrior": "Dawn Writing Season",
        "a_monthly_watcher": "Story Critic Calendar",
        "a_comeback": "Original Work Decree",
        "a_weekend_streak": "Celestia Moments Passage",
        "a_no_zero_days": "Creator Circle Warrant Warrant",
        "a_iron_will": "Creator's Will",
        "a_habit_formed": "Creator Streak Banner",
        "a_consistent_pace": "Story Power Measure",
        "a_year_long": "Year of Stories",
        "a_double_streak": "Original Adapted Watch",
        "a_streak_recovery": "World Return Season",
        "a_daily_minimum": "Story Critic Focus",
        "a_winter_streak": "Creation World Watch",
        "a_summer_streak": "Troyca Classic Resolve",
        "a_morning_streak": "Selesia Speed Clock",
        "a_night_streak": "Creator Streak Constancy",
        "a_unbreakable": "Rei Master Proof",
        "a_eternal_flame": "Fictional World Standard",
        "a_completion_streak": "Decade Fan Return",
        "a_rating_streak": "Altair's Plan Balance",
        "a_multi_ep_streak": "Author Resolve Ritual",
        "a_genre_streak": "Altair's Plan Streak",
        "a_studio_streak": "Original Work Cabinet Cabinet",
        "a_perfect_week": "Real World Relic",

        // ── ANIME SCORING ──
        "a_critic": "Story Critic",
        "a_perfect_ten": "Perfect Story",
        "a_harsh_critic": "Altair's Standard",
        "a_fair_judge": "Reality Bending Balance",
        "a_generous_spirit": "Story Critic Pinnacle",
        "a_score_all": "Rei Fan Criterion",
        "a_wide_range": "Selesia's Mech Ledger",
        "a_controversial": "Selesia Speed Decree",
        "a_consistent_scorer": "Creators Expert Verdict",
        "a_score_sniper": "Daily Creation Score",
        "a_evolving_taste": "Original Adapted Testament",
        "a_bell_curve": "Military Uniform Princess Insignia",
        "a_picky_watcher": "World Return Warrant",
        "a_100_rated": "Creator Depth Warrant",
        "a_500_rated": "Rei Master Pinnacle",
        "a_mediocre_majority": "Real World Canon",
        "a_rating_spree": "Selesia Speed Review",
        "a_score_variance": "Celestia Moments Score",
        "a_masterpiece_hunter": "Selesia Speed Banner",
        "a_contrarian": "Creator's Choice Record Record",
        "a_optimist": "Sota's Run Ledger",
        "a_score_distributor": "All Night Appraisal",
        "a_genre_critic": "Story Power Critic",
        "a_mean_above_8": "Story Alerts Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Story",
        "a_valentines_weeb": "Endless Stories Vow",
        "a_pi_day": "Reality Bending Trial",
        "a_april_fools": "Daily Creation Devotion Devotion",
        "a_international_anime_day": "Creator Studio Record",
        "a_star_wars_day": "Creator Notes Chronicle",
        "a_summer_solstice": "Creator Circle Calendar",
        "a_tanabata": "Winter Creation Focus",
        "a_friday_13th": "All Night Relic",
        "a_halloween_spirit": "Grand Battle Vow",
        "a_thanksgiving_binge": "Sota's Guilt Run",
        "a_christmas_special": "Winter Creation",
        "a_new_years_eve": "Story Alerts Pilgrimage",
        "a_birthday_watch": "Military Uniform Princess Vow",
        "a_holiday_marathon": "Creator's Will Overture",
        "a_independence_day": "Fictional World Banner",
        "a_culture_day": "Character Battle Insignia",
        "a_spring_equinox": "Creator's Will Decree",
        "a_earth_day": "Author Resolve Mantle",
        "a_labor_day": "Grand Battle Seal",
        "a_winter_solstice": "Reality Saved Pilgrimage",
        "a_anime_birthday": "Author Resolve Pilgrimage",
        "a_every_holiday": "Creator Art Resolve",
        "a_consecutive_holidays": "Troyca Classic Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Original Work Rank",
        "a_meta_collector": "Character Battle Hoard",
        "a_meta_category_starter": "Story Critic Badge",
        "a_meta_tier_climber": "Character Battle Glyph",
        "a_meta_tier_max": "Meta Creator",
        "a_meta_xp_earner": "All Night Emblem",
        "a_meta_difficulty_easy": "Reality Bending Mechanism",
        "a_meta_difficulty_hard": "Re Creators Writ",
        "a_meta_unlock_spree": "Dawn Writing Panel",
        "a_meta_completionist": "All Stories",
        "a_meta_diverse": "Altair's Plan Emblem",
        "a_meta_dominator": "Sota's Guilt Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Draft",
        "m_chapter_counter": "Creator Depth Pinnacle",
        "m_chapter_titan": "Creator Trophies Relic",
        "m_reading_hours": "All Night Relic Relic",
        "m_reading_time_lord": "Creator Studio Record Record",
        "m_manga_collector": "Dawn Writing Ledger",
        "m_library_legend": "Character Battle Reliquary",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "Endless Stories Seal",
        "m_first_rating": "All Night Eye",
        "m_ten_thousand_pages": "Endless Stories Gauge",
        "m_volume_collector": "World Return Storehouse",
        "m_year_explorer": "Creator Ally Quest",
        "m_century_reader": "Creation World Dominion",
        "m_five_hundred_ch": "Selesia's Mech Legend",
        "m_thousand_ch": "Original Adapted Legend",
        "m_reading_ten": "Creation World Appraisal",
        "m_ptr_hoarder": "Original Adapted Index",
        "m_dropped_honesty": "Character Battle Summit",
        "m_season_reader": "Selesia Speed Treasury",
        "m_active_reader": "Troyca Classic Trial",
        "m_five_thousand_ch": "Creator's Choice Standard",
        "m_ten_completed": "Creator's Choice Resolution",
        "m_fifty_completed": "Original Adapted Harvest",
        "m_five_hundred_completed": "Creator Streak Legacy",
        "m_mean_score_tracker": "Creators Expert Audit",
        "m_unique_authors": "Author Resolve Reserve",
        "m_all_status": "Troyca Classic Testament Testament",
        "m_first_favorite": "Decade Fan Cache",
        "m_favorites_collector": "Original Work Shelf",
        "m_days_spent_reading": "Reality Saved Relic",

        // ── MANGA BINGE ──
        "m_binge_reader": "Military Uniform Princess Streak",
        "m_marathon_reader": "Reality Bending Rush",
        "m_weekend_reader": "Perfect Story Run",
        "m_non_stop_reading": "Decade Fan Gauntlet",
        "m_one_more_chapter": "All Night Testament Testament",
        "m_speed_read": "Creator Circle Drive",
        "m_double_story": "Creator's Will Banner",
        "m_triple_read": "Fictional World Record",
        "m_five_a_day": "Sota's Run Insignia",
        "m_chapter_chain": "Character Battle Accord",
        "m_volume_binge": "Celestia Moments Drive",
        "m_power_reader": "Creator Notes Seal Seal",
        "m_half_day_read": "Original Work Aegis",
        "m_full_day_read": "Fan Hero Aegis Aegis",
        "m_power_weekend": "Endless Stories Streak",
        "m_binge_king": "Story Marathon",
        "m_no_sleep_read": "Creation World Rush",
        "m_full_series_rush": "Reality Bending Cascade",
        "m_seven_day_challenge": "Winter Creation Warrant",
        "m_hundred_day_read": "Altair's Plan Legend",
        "m_volume_rush": "Meta Creator Gauntlet",
        "m_series_sweep": "Creator Art Trial Trial",
        "m_genre_binge": "Fan Hero Binge",
        "m_author_binge": "Perfect Story Surge",
        "m_chapter_counter_day": "Sota's Guilt Ledger Ledger",
        "m_multi_series_binge": "Selesia's Mech Charge",
        "m_midnight_binge": "Original Adapted Tempest",
        "m_new_year_binge": "Author Resolve Passage",
        "m_forty_eight_hour": "Creators Expert Rally",
        "m_oneshot_binge": "Creator Circle Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Battle Chapter",
        "m_genre_adventure": "Real Chapter",
        "m_genre_comedy": "Original Work Comedy",
        "m_genre_drama": "Creation Chapter",
        "m_genre_fantasy": "Fiction Chapter",
        "m_genre_horror": "Altair Chapter",
        "m_genre_mystery": "Creator's Choice Mystery",
        "m_genre_romance": "Guilt Chapter",
        "m_genre_scifi": "Reality Chapter",
        "m_genre_sol": "Creator Depth Slice",
        "m_genre_sports": "Meta Creator Sports",
        "m_genre_supernatural": "Power Chapter",
        "m_genre_thriller": "Real World Thriller",
        "m_genre_psychological": "Creator Depth",
        "m_genre_isekai": "Dawn Writing Isekai",
        "m_genre_shounen": "Night Creation Shounen",
        "m_genre_ecchi": "Story Power Ecchi",
        "m_genre_mahou_shoujo": "Original Work Magic Shoujo",
        "m_genre_mecha": "World Return Mecha",
        "m_genre_music": "Grand Battle Music",
        "m_tag_isekai_new": "All Night Isekai New",
        "m_tag_harem": "Rei Fan Harem",
        "m_tag_bl": "All Stories Bl",
        "m_tag_gl": "Original Adapted Gl",
        "m_tag_historical": "Selesia's Mech Historical",
        "m_tag_military": "Night Creation Military",
        "m_tag_school": "Endless Stories School",
        "m_tag_martial_arts": "Creator Depth Martial Arts",
        "m_tag_vampire": "Meta Creator Vampire",
        "m_tag_samurai": "Story Marathon Samurai",
        "m_tag_space": "All Stories Space",
        "m_tag_parody": "World Return Parody",
        "m_tag_idol": "All Stories Idol",
        "m_tag_post_apocalyptic": "Character Battle Post Apocalyptic",
        "m_tag_cyberpunk": "Rei Fan Cyberpunk",
        "m_tag_shoujo": "Re Creators Shoujo",
        "m_tag_survival": "Original Work Survival",
        "m_tag_cooking": "Military Uniform Princess Cooking",
        "m_tag_medical": "Troyca Classic Medical",
        "m_tag_villainess": "Perfect Story Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Re:Creators Expert",
        "m_completion_rate_50": "All Stories Return",
        "m_completion_rate_75": "Real World Ascension",
        "m_completion_rate_90": "Fictional World Resolution",
        "m_no_drop": "Decade Fan Decree",
        "m_long_runner_complete": "Sota's Guilt Clear",
        "m_sequel_chain": "Grand Battle Seal Seal",
        "m_clean_list": "Creator Trophies Relic Relic",
        "m_from_ptr": "Re Creators Watchlist",
        "m_reread_master": "Reality Bending Trial Trial",
        "m_oneshot_complete": "Reality Bending Ascension",
        "m_same_day_start_finish": "Story Alerts Crown Crown",
        "m_revival": "Sota's Guilt Accord",
        "m_zero_to_hundred": "Creator's Choice Banner",
        "m_five_genre_complete": "Creator Circle M Five Genre",
        "m_full_collection": "Story Alerts Proof Proof",
        "m_batch_complete": "Creators Expert Summit",
        "m_paused_to_done": "Fictional World Standard Standard",
        "m_completion_spree": "Rei Master Triumph",
        "m_format_completionist": "Reality Bending Completion",
        "m_catch_up": "Creator Studio Chronicle",
        "m_multi_reread": "Decade Fan Banner",
        "m_dropped_recovery": "Story Power Conquest",
        "m_ten_perfect_scores": "Perfect Story Judgment",
        "m_complete_genre_span": "Dawn Writing M Complete Genre",
        "m_monthly_completions": "Fan Hero Return",
        "m_yearly_completions": "Dawn Writing Epilogue",
        "m_rapid_complete": "Winter Creation Finale",
        "m_author_complete": "Endless Stories Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Devoted Reader",
        "m_mangaka_lover": "Rei Fan",
        "m_rereader": "World Return",
        "m_triple_reread": "Altair's Plan Testament Testament",
        "m_annual_reread": "Creator's Choice Banner Banner",
        "m_publisher_fan": "Rei Master Mark",
        "m_artist_fan": "Grand Battle Insignia",
        "m_adaptation_compare": "Military Uniform Princess Insignia Insignia",
        "m_source_material_fan": "Original Work",
        "m_waiting_weekly": "Story Marathon Streak",
        "m_classic_reader": "World Return Lantern",
        "m_saga_reader": "Character Battle Decree",
        "m_genre_loyalty": "Story Power Loyalty",
        "m_decade_reader": "Celestia Moments Warrant",
        "m_ln_adaptation": "Celestia Moments Mark",
        "m_original_work": "Meta Creator Standard",
        "m_long_commitment": "Story Power Mark",
        "m_up_to_date": "Author Resolve Warrant Warrant",
        "m_favorite_mangaka": "Creator Ally Treasury",
        "m_complete_portfolio": "Rei Master Triumph Triumph",
        "m_franchise_collector": "Creator Studio Archive",
        "m_serialization_follower": "Creator Ally Handshake",
        "m_genre_master": "Creator Trophies Master",
        "m_multi_series_author": "Character Battle Insignia Insignia",
        "m_format_diversity": "Meta Creator Shelf",
        "m_year_dedication": "Creation World Tenure",
        "m_ongoing_follower": "Celestia Moments Fellowship",
        "m_genre_loyalty_50": "Original Adapted Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Creator's Will Explorer",
        "m_publisher_hopper": "Rei Master Mantle",
        "m_tag_explorer": "Creator Art Explorer",
        "m_decade_hopper": "Re Creators Chronicle Chronicle",
        "m_hidden_gem": "Hidden Volume",
        "m_popular_taste": "Creators Expert Record Record",
        "m_retro_reader": "Creators Expert Accord",
        "m_modern_reader": "Selesia's Mech Seal Seal",
        "m_cross_demographic": "Story Critic Crown",
        "m_underdog_fan": "Creators Expert Accord Accord",
        "m_variety_week": "Grand Battle Horizon Horizon",
        "m_manhwa_reader": "Daily Creation Proof",
        "m_manhua_reader": "World Return Mantle Mantle",
        "m_classic_connoisseur": "Creator Streak Glimpse",
        "m_award_winner": "Creation World Warrant",
        "m_niche_explorer": "Military Uniform Princess Horizon",
        "m_world_manga": "Creator Studio Chronicle Chronicle",
        "m_cult_classic": "Troyca Classic",
        "m_random_pick": "Creators Expert Standard",
        "m_new_genre_month": "Creator Studio M New Genre",
        "m_year_completionist": "Creator Depth Fulfillment",
        "m_unpopular_opinion": "Author Resolve Trial",
        "m_top_rated_reader": "Military Uniform Princess Record",
        "m_source_variety": "World Return Catalogue",
        "m_low_score_brave": "Creator Depth Score",
        "m_short_manga_explorer": "Selesia's Mech Compass",
        "m_long_manga_explorer": "Creator's Choice Survey",
        "m_serialization_explorer": "Real World Road",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "All Stories Ledger",
        "m_commute_reader": "Troyca Classic Tenure Tenure",
        "m_four_am_club": "Rei Master Fellowship",
        "m_new_year_read": "Grand Battle Pact",
        "m_all_hours": "Re Creators Accord Accord",
        "m_prime_time_reader": "Meta Creator Banner",
        "m_workday_reader": "Sota's Guilt Accord Accord",
        "m_sunday_read": "All Stories Standard Standard",
        "m_morning_routine": "Sota's Guilt Discipline",
        "m_night_shift_reader": "Endless Stories Accord Accord",
        "m_seasonal_premier_read": "World Return Seasonal",
        "m_clock_collector": "Reality Saved Reserve",
        "m_late_night_horror": "Creator Circle Mark Mark",
        "m_afternoon_reader": "Creation World Mantle Mantle",
        "m_golden_hour_reader": "Altair's Plan Observance",
        "m_dawn_reader": "Creator Art Mantle",
        "m_twilight_reader": "Celestia Moments Crown",
        "m_midnight_start": "Meta Creator Routine",
        "m_weekend_binge_hours": "Perfect Story Momentum",
        "m_late_night_regular": "All Stories Accord",
        "m_sunrise_reader": "Rei Fan Mantle",
        "m_every_day_of_week": "World Return Warrant Warrant",
        "m_monthly_hours": "Creator's Will Vigil",
        "m_bedtime_reader": "Creator Depth Warrant Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Creator Art",
        "m_webtoon_reader": "Celestia Moments Mark Mark",
        "m_full_color": "Grand Battle Accord",
        "m_doujin_reader": "Fictional World Record Record",
        "m_anthology_reader": "Perfect Story Accord",
        "m_adaptation_reader": "Creators Expert Banner",
        "m_longstrip_reader": "Altair's Plan Trial",
        "m_4koma_reader": "Story Marathon Ledger",
        "m_oneshot_reader": "Dawn Writing Mantle",
        "m_format_variety": "Rei Master Gallery",
        "m_light_novel_reader": "Re Creators Insignia",
        "m_novel_reader": "Creator Depth Crown",
        "m_visual_storyteller": "Creation World Testament",
        "m_colored_classic": "Selesia Speed Survey",
        "m_webcomic_fan": "Creator Streak Insignia",
        "m_manga_to_anime": "Original Adapted",
        "m_seinen_reader": "Story Power Pinnacle",
        "m_josei_reader": "Rei Fan Pinnacle",
        "m_award_winning_art": "Night Creation Relic",
        "m_debut_work": "Night Creation Dominion",
        "m_vertical_scroll": "Character Battle Decree Decree",
        "m_traditional_format": "Military Uniform Princess Hoard",
        "m_cross_media": "Selesia's Mech Accord",
        "m_spinoff_reader": "Creator Studio Accord",
        "m_remake_reader": "Reality Bending Pinnacle",
        "m_collaboration_reader": "Creator Streak Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Creator Streak",
        "m_weekly_warrior": "Real World Season",
        "m_monthly_reader": "Sota's Run Discipline",
        "m_comeback": "Creator's Choice Standard Standard",
        "m_weekend_streak": "Rei Fan Fever",
        "m_no_zero_days": "Daily Creation Proof Proof",
        "m_iron_will": "Author Resolve",
        "m_habit_formed": "Story Critic Crown Crown",
        "m_consistent_pace": "Story Alerts Scrutiny Scrutiny",
        "m_year_long": "Year Reading",
        "m_double_streak": "Dawn Writing Resolve",
        "m_streak_recovery": "Creator Trophies Resolve",
        "m_daily_minimum": "Reality Saved Focus",
        "m_winter_streak": "Altair's Plan Observance Observance",
        "m_summer_streak": "Night Creation Observance",
        "m_morning_streak": "Creator's Will Clock",
        "m_night_streak": "Military Uniform Princess Discipline",
        "m_unbreakable": "Rei Fan Warrant",
        "m_eternal_flame": "Original Work Record",
        "m_chapter_a_day": "All Stories Ledger Ledger",
        "m_genre_streak": "Creator Art Streak",
        "m_completion_streak": "Creators Expert Return",
        "m_rating_streak": "Creator Art Appraisal",
        "m_multi_ch_streak": "Real World Tenure",
        "m_author_streak": "Reality Saved Calendar",
        "m_perfect_week_manga": "Creator Studio Accord Accord",
        "m_diverse_streak": "Decade Fan Streak",

        // ── MANGA SCORING ──
        "m_critic": "Story Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_harsh_critic": "Re Creators Scale",
        "m_fair_judge": "All Night Eye Eye",
        "m_generous_spirit": "Perfect Story Decree",
        "m_score_all": "Celestia Moments Reckoning",
        "m_wide_range": "Sota's Run Ledger Ledger",
        "m_controversial": "Fan Hero Standard Standard",
        "m_consistent_scorer": "Fictional World Grade",
        "m_score_sniper": "Author Resolve Reckoning",
        "m_evolving_taste": "Dawn Writing Trial Trial",
        "m_bell_curve": "Sota's Run Accord",
        "m_picky_reader": "Decade Fan Ledger",
        "m_100_rated": "Sota's Run Standard",
        "m_500_rated": "Endless Stories Aegis",
        "m_mediocre_majority": "Dawn Writing Canon",
        "m_rating_spree": "Creator's Will Verdict",
        "m_score_variance": "Creator Depth Measure",
        "m_binge_rater": "Reality Saved Passage",
        "m_reread_rerate": "Selesia Speed Banner Banner",
        "m_masterpiece_hunter": "Fan Hero Banner",
        "m_contrarian": "Creators Expert Aegis",
        "m_optimist": "Selesia's Mech Accord Accord",
        "m_score_distributor": "Real World Balance",
        "m_genre_critic": "Reality Saved Critic",
        "m_mean_above_8": "Creator Depth Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Creation World Season",
        "m_valentines_read": "Creator Art Observance",
        "m_pi_day": "Dawn Writing Testament Testament",
        "m_april_fools": "Author Resolve Devotion",
        "m_international_manga_day": "Re Creators Aegis",
        "m_free_comic_day": "Perfect Story Chronicle",
        "m_summer_solstice": "Winter Creation Focus Focus",
        "m_tanabata": "Story Alerts Tanabata",
        "m_friday_13th": "Reality Bending Dominion Dominion",
        "m_halloween_read": "Creator Circle Halloween",
        "m_thanksgiving_binge": "Creator Studio Charge",
        "m_christmas_read": "Sota's Guilt Pact",
        "m_new_years_eve": "Winter Creation Pilgrimage",
        "m_birthday_read": "Story Power Focus",
        "m_holiday_marathon": "Creator Ally Rally",
        "m_independence_day": "Creators Expert Aegis Aegis",
        "m_culture_day": "Endless Stories Seal Seal",
        "m_spring_equinox": "Creator Circle Dominion",
        "m_earth_day": "Story Power Trial",
        "m_labor_day": "Sota's Guilt Seal",
        "m_winter_solstice": "Story Critic Focus Focus",
        "m_manga_birthday": "Story Alerts Ritual",
        "m_every_holiday_reader": "Creator Trophies Watch",
        "m_consecutive_holidays": "Reality Bending Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Creator Notes Aegis",
        "m_fibonacci": "Troyca Classic Dominion",
        "m_palindrome_day": "Dawn Writing Relic",
        "m_binary_day": "Story Critic Proof",
        "m_full_moon_read": "Rei Fan Crown",
        "m_leap_year_read": "Decade Fan Practice",
        "m_triple_seven": "All Night Trial Trial",
        "m_thousand_complete": "All Night Ascension",
        "m_nice": "Character Battle Seal Seal",
        "m_power_level_chapters": "Creator's Choice Aegis",
        "m_answer_42": "Rei Fan Trial",
        "m_square_number": "Original Work Standard",
        "m_prime_count": "All Night Pinnacle",
        "m_matching_date": "Creator Trophies Mantle",
        "m_century_chapter": "Creator Notes Decree",
        "m_pi_chapters": "Story Power Proof Proof",
        "m_synchronicity": "Creator Art Emblem",
        "m_world_record": "Daily Creation Warrant",
        "m_genre_clash": "Meta Creator Clash",
        "m_time_traveler": "Fictional World Decree",
        "m_double_digits": "World Return Dominion",
        "m_one_two_three": "Creator Streak Banner Banner",
        "m_lucky_seven": "Military Uniform Princess Record Record",
        "m_exact_hundred_ch": "Troyca Classic Legend",
        "m_year_match_count": "Story Marathon Routine",
        "m_chapter_match_date": "Story Critic Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "World Return Index",
        "m_manhwa_format": "Creator Circle Gallery",
        "m_manhua_format": "Altair's Plan Storehouse",
        "m_ln_format": "All Night Index",
        "m_oneshot_format": "Dawn Writing Index",
        "m_doujin_format": "Creator's Will Cabinet",
        "m_novel_format": "Author Resolve Reserve Reserve",
        "m_format_master_manga": "Creator's Will Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Fictional World Link",
        "m_meta_collector": "Endless Stories Reliquary",
        "m_meta_category_starter": "Rei Master Standard",
        "m_meta_tier_climber": "Selesia's Mech Token",
        "m_meta_tier_max": "Re:Creators Complete",
        "m_meta_xp_earner": "World Return Anchor",
        "m_meta_difficulty_easy": "All Night Panel",
        "m_meta_difficulty_hard": "Creation World Node",
        "m_meta_unlock_spree": "World Return Marker",
        "m_meta_completionist": "Full Library",
        "m_meta_diverse": "Dawn Writing Anchor",
        "m_meta_dominator": "Character Battle Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#030304",
        primary: "#6c6cb4",
        secondary: "#4e4e98",
        accent: "#e05820",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/re-creators.jpg",
    particleColor: "#9090d0",
    backgroundDim: 0.38,
    backgroundBlur: 18,
    particleTypes: {
        story_fragments: { label: "Story Fragments", maxCount: 18, defaultEnabled: true, defaultIntensity: 58 },
        code_particles: { label: "Code Particles", maxCount: 12, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
  1: "Threadbare Generic Rank Spark",
  8: "Generic's Tarnished Omen",
  14: "Fractured Generic Rank",
  21: "Generic Rank Path",
  28: "Lowborn Legacy Myth",
  35: "Generic Rank Pulse",
  41: "Generic's Legacy Crest",
  48: "Humble Generic Mark",
  55: "Ragged Generic Rank Vow",
  61: "Generic's Faint Echo",
  68: "Lesser Generic Rank",
  75: "Generic Rank Zenith",
  81: "Doubtful Legacy Bloom",
  88: "Generic Rank Sigil",
  95: "Generic's Legacy Flame",
  102: "Really Cool Generic Spark",
  108: "Awakened Generic Rank Omen",
  115: "Generic's Resolute Seal",
  122: "Rising Generic Rank",
  128: "Generic Rank Myth",
  135: "Dauntless Legacy Pulse",
  142: "Generic Rank Crest",
  149: "Generic's Legacy Mark",
  155: "Fresh Generic Vow",
  162: "Valiant Generic Rank Echo",
  169: "Generic's Prime Crown",
  175: "Polished Generic Rank",
  182: "Generic Rank Bloom",
  189: "Stormlit Legacy Sigil",
  195: "Generic Rank Flame",
  202: "Generic's Legacy Spark",
  209: "Tempered Generic Omen",
  216: "Trusted Generic Rank Seal",
  222: "Generic's Steadfast Path",
  229: "Ironclad Generic Rank",
  236: "Veteran Legacy Pulse",
  242: "Core Legacy Crest",
  249: "Generic Rank Mark",
  256: "Generic's Legacy Vow",
  262: "Formidable Generic Echo",
  269: "Lucid Generic Rank Crown",
  276: "Generic's Ranked Zenith",
  283: "Fabled Generic Rank",
  289: "Grand Legacy Sigil",
  296: "Seasoned Legacy Flame",
  303: "Generic Rank Spark",
  309: "Generic's Legacy Omen",
  316: "Valorous Generic Seal",
  323: "Stalwart Generic Rank Path",
  330: "Generic's Commanding Myth",
  336: "Refined Generic Rank",
  343: "Unbroken Legacy Crest",
  350: "Blazing Legacy Mark",
  356: "Generic Rank Vow",
  363: "Generic's Legacy Echo",
  370: "Peerless Generic Crown",
  376: "Ardent Generic Rank Zenith",
  383: "Generic's Focused Bloom",
  390: "Vigilant Generic Rank",
  397: "Dominant Legacy Flame",
  403: "Elite Legacy Spark",
  410: "Generic Rank Omen",
  417: "Generic's Legacy Seal",
  423: "Sovereign Generic Path",
  430: "Regal Generic Rank Myth",
  437: "Generic's Crowned Pulse",
  444: "Mythborn Generic Rank",
  450: "Limitless Legacy Mark",
  457: "Radiant Legacy Vow",
  464: "Generic Rank Echo",
  470: "Generic's Legacy Crown",
  477: "Climactic Generic Zenith",
  484: "Epic Generic Rank Bloom",
  490: "Generic's Unreal Sigil",
  497: "Peak Generic Rank",
  504: "Supreme Legacy Spark",
  511: "Exalted Legacy Omen",
  517: "Generic Rank Seal",
  524: "Generic's Legacy Path",
  531: "Celestial Generic Myth",
  537: "Phantom Generic Rank Pulse",
  544: "Generic's Crimson Crest",
  551: "Silver Generic Rank",
  557: "Golden Legacy Vow",
  564: "Feral Legacy Echo",
  571: "Generic Rank Crown",
  578: "Generic's Legacy Zenith",
  584: "Dread Generic Bloom",
  591: "Luminous Generic Rank Sigil",
  598: "Generic's Thunderous Flame",
  604: "Ultraviolet Generic Rank",
  611: "Unleashed Legacy Omen",
  618: "Secret Legacy Seal",
  625: "Final Generic Path",
  631: "Generic's Legacy Myth",
  638: "Worldclass Generic Pulse",
  645: "Lawless Generic Rank Crest",
  651: "Generic's Chosen Mark",
  658: "Fearless Generic Rank",
  665: "Overdrive Legacy Echo",
  671: "Cinematic Legacy Crown",
  678: "Impossible Generic Zenith",
  685: "Generic's Legacy Bloom",
  692: "Canonized Generic Sigil",
  698: "Ascendant Generic Rank Flame",
  705: "Generic's Transfigured Spark",
  712: "Immortal Generic Rank",
  718: "Eclipsed Legacy Seal",
  725: "Astral Legacy Path",
  732: "Sublime Generic Myth",
  739: "Generic's Legacy Pulse",
  745: "Prismatic Generic Crest",
  752: "Abyssal Generic Rank Mark",
  759: "Generic's Unbound Vow",
  765: "Eternal Generic Rank",
  772: "Cosmic Legacy Crown",
  779: "Transcendent Legacy Zenith",
  785: "Perfected Generic Bloom",
  792: "Generic's Legacy Sigil",
  799: "Ultimate Generic Flame",
  806: "Mythic Generic Rank Spark",
  812: "Generic's Godlike Omen",
  819: "Canonical Generic Rank",
  826: "Reality-Bent Legacy Path",
  832: "Heavenly Legacy Myth",
  839: "Absolute Generic Pulse",
  846: "Untouchable Generic Crest",
  852: "Timeless Generic Mark",
  859: "Empyrean Generic Rank Vow",
  866: "Generic's Primordial Echo",
  873: "Omniscient Generic Rank",
  879: "Unfathomed Legacy Zenith",
  886: "Apocalyptic Legacy Bloom",
  893: "Seraphic Generic Sigil",
  899: "Omega Generic Flame",
  906: "Final Generic Spark",
  913: "Crowned Generic Rank Omen",
  920: "Generic's Mythic Seal",
  926: "Absolute Generic Rank",
  933: "Eternal Legacy Myth",
  940: "Cosmic Legacy Pulse",
  946: "Transcendent Generic Crest",
  953: "Perfected Generic Mark",
  960: "Definitive Generic Vow",
  966: "Ultimate Generic Rank Echo",
  973: "Generic's Infinite Crown",
  980: "Sovereign Generic Rank",
  987: "Celestial Legacy Bloom",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate Generic Rank"
},
}
