import { AnimeThemeConfig } from "./types"
import { GiHeartKey, GiDress, GiCoins, GiStarFormation, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiDramaMasks, GiFilmProjector, GiCrown } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const rentAGirlfriendTheme: AnimeThemeConfig = {
    id: "rent-a-girlfriend",
    displayName: "Rent-A-Girlfriend",
    description: "After being dumped, college student Kazuya Kinoshita discovers rental girlfriend services and hires Chizuru Mizuhara — a stunningly beautiful and professional companion with secrets of her own.",
    fontFamily: "'M PLUS Rounded 1c', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "255 230 150",
        "--color-brand-300": "245 205 90",
        "--color-brand-400": "230 175 40",
        "--color-brand-500": "210 144 10",
        "--color-brand-600": "175 110 0",
        "--color-brand-700": "135 80 0",
        "--color-brand-800": "92 52 0",
        "--color-brand-900": "52 26 0",
        "--color-brand-950": "24 10 0",
        "--brand": "210 144 10",
        "--background": "#050400",
        "--paper": "#100a00",
        "--color-gray-950": "5 4 0",
        "--color-gray-900": "12 9 0",
        "--color-gray-800": "22 16 2",
        "--color-gray-700": "38 28 5",
        "--color-gray-600": "62 48 12",
        "--color-gray-500": "98 78 28",
        "--color-gray-400": "145 118 58",
        "--color-gray-300": "188 158 96",
        "--color-gray-200": "220 195 142",
        "--color-gray-100": "242 225 185",
        "--color-gray-50": "252 245 225",
    },
    sidebarOverrides: {
        "home": { icon: GiHeartKey, label: "Date HQ" },
        "schedule": { icon: GiAlarmClock, label: "Date Schedule" },
        "manga": { icon: LuBookOpen, label: "Chizuru's Scripts" },
        "lists": { icon: GiFlowerEmblem, label: "Girlfriend List" },
        "discover": { icon: GiBullseye, label: "New Faces" },
        "torrent-list": { icon: GiCoins, label: "Rental Cache" },
        "debrid": { icon: GiDramaMasks, label: "Secret Vault" },
        "unmatched": { icon: GiDress, label: "Lost Matches" },
        "enmasse": { icon: GiResize, label: "Group Dates" },
        "scan-summaries": { icon: TbReportSearch, label: "Date Reports" },
        "auto-downloader": { icon: LuRss, label: "Chizuru's Feed" },
        "community": { icon: GiStarFormation, label: "Date Circle" },
        "achievements": { icon: GiTrophy, label: "Romance Awards" },
        "milestones": { icon: LuFlag, label: "Relationship Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Love Alerts" },
        "theme-manager": { icon: GiPalette, label: "Gold Palette" },
        "extensions": { icon: BiExtension, label: "Date Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Heart Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Kazuya's Config" },
    },
    achievementNames: {
        "a_first_episode": "First Date",
        "a_first_complete": "Date Complete",
        "a_hundred_club": "Hundred Dates",
        "a_time_lord": "Veteran Dater",
        "a_anime_collector": "Date Archive",
        "a_library_legend": "Romance Library",
        "a_binge_king": "Date Marathon",
        "a_no_sleep": "All-Night Romance",
        "a_marathon_runner": "Kazuya's Run",
        "a_speed_run": "Speed Date",
        "a_completionist": "Full Relationship",
        "a_mega_completionist": "Romance Master",
        "a_loyal_fan": "Loyal Partner",
        "a_rewatcher": "Replay Dates",
        "a_decade_watcher": "Decade Romance",
        "a_genre_action": "None Here",
        "a_genre_adventure": "City Adventure",
        "a_genre_comedy": "Kazuya's Comedy",
        "a_genre_drama": "Rental Drama",
        "a_genre_fantasy": "Dream Date",
        "a_genre_horror": "None Here",
        "a_genre_romance": "Chizuru's Love",
        "a_genre_scifi": "None Here",
        "a_genre_supernatural": "None Here",
        "a_genre_psychological": "Kazuya's Mind",
        "a_genre_mecha": "None Here",
        "a_critic": "Date Critic",
        "a_perfect_ten": "Perfect Date",
        "a_harsh_critic": "High Standards",
        "a_daily_streak": "Daily Date",
        "a_mega_streak": "Endless Romance",
        "a_year_long": "Year of Dates",
        "a_iron_will": "Never Give Up",
        "a_hidden_gem": "Hidden Heart",
        "a_cult_classic": "Rental Classic",
        "a_classic_connoisseur": "2020 Fan",
        "a_new_years_resolution": "New Year Love",
        "a_christmas_special": "Winter Date",
        "a_meta_tier_max": "True Boyfriend",
        "a_meta_completionist": "All Dates",
        "a_sequel_chain": "Chizuru's Chain",
        "a_zero_to_hero": "Dumped to Loved",
        "a_night_owl": "Night Romance",
        "a_early_bird": "Dawn Date",
        "m_first_chapter": "First Meeting",
        "m_first_complete": "First Arc Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Romance Binge",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Rental Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Re-read Romance",
        "m_genre_action": "None Here",
        "m_genre_adventure": "Adventure Chapter",
        "m_genre_romance": "Chizuru's Chapter",
        "m_genre_fantasy": "Dream Chapter",
        "m_genre_horror": "None Here",
        "m_genre_drama": "Drama Chapter",
        "m_genre_scifi": "None Here",
        "m_genre_supernatural": "None Here",
        "m_genre_psychological": "Inner Chapter",
        "m_critic": "Date Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Romance Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Iron Heart",
        "m_hidden_gem": "Hidden Gem",
        "m_cult_classic": "Rental Classic",
        "m_mangaka_lover": "Miyajima Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Romance Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Chizuru's Beauty",
        "m_manga_to_anime": "Adapted Date",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#050400",
        primary: "#d2900a",
        secondary: "#af6e00",
        accent: "#f080b0",
    },
    particleColor: "#f0c840",
    backgroundDim: 0.26,
    backgroundBlur: 12,
    particleTypes: {
        golden_sparks: { label: "Golden Sparks", maxCount: 16, defaultEnabled: true, defaultIntensity: 52 },
        cherry_petals: { label: "Petals", maxCount: 10, defaultEnabled: true, defaultIntensity: 38 },
    },
    milestoneNames: {
    1: "Generic Rank",
    7: "Generic Rank",
    14: "Generic Rank",
    21: "Generic Rank",
    27: "Generic Rank",
    34: "Generic Rank",
    41: "Generic Rank",
    47: "Generic Rank",
    54: "Generic Rank",
    61: "Generic Rank",
    68: "Generic Rank",
    74: "Generic Rank",
    81: "Generic Rank",
    88: "Generic Rank",
    94: "Generic Rank",
    101: "Generic Rank",
    108: "Generic Rank",
    114: "Generic Rank",
    121: "Generic Rank",
    128: "Generic Rank",
    135: "Generic Rank",
    141: "Generic Rank",
    148: "Generic Rank",
    155: "Generic Rank",
    161: "Generic Rank",
    168: "Generic Rank",
    175: "Generic Rank",
    182: "Generic Rank",
    188: "Generic Rank",
    195: "Generic Rank",
    202: "Generic Rank",
    208: "Generic Rank",
    215: "Generic Rank",
    222: "Generic Rank",
    228: "Generic Rank",
    235: "Generic Rank",
    242: "Generic Rank",
    249: "Generic Rank",
    255: "Generic Rank",
    262: "Generic Rank",
    269: "Generic Rank",
    275: "Generic Rank",
    282: "Generic Rank",
    289: "Generic Rank",
    296: "Generic Rank",
    302: "Generic Rank",
    309: "Generic Rank",
    316: "Generic Rank",
    322: "Generic Rank",
    329: "Generic Rank",
    336: "Generic Rank",
    342: "Generic Rank",
    349: "Generic Rank",
    356: "Generic Rank",
    363: "Generic Rank",
    369: "Generic Rank",
    376: "Generic Rank",
    383: "Generic Rank",
    389: "Generic Rank",
    396: "Generic Rank",
    403: "Generic Rank",
    409: "Generic Rank",
    416: "Generic Rank",
    423: "Generic Rank",
    430: "Generic Rank",
    436: "Generic Rank",
    443: "Generic Rank",
    450: "Generic Rank",
    456: "Generic Rank",
    463: "Generic Rank",
    470: "Generic Rank",
    477: "Generic Rank",
    483: "Generic Rank",
    490: "Generic Rank",
    497: "Generic Rank",
    503: "Generic Rank",
    510: "Generic Rank",
    517: "Generic Rank",
    523: "Generic Rank",
    530: "Generic Rank",
    537: "Generic Rank",
    544: "Generic Rank",
    550: "Generic Rank",
    557: "Generic Rank",
    564: "Generic Rank",
    570: "Generic Rank",
    577: "Generic Rank",
    584: "Generic Rank",
    591: "Generic Rank",
    597: "Generic Rank",
    604: "Generic Rank",
    611: "Generic Rank",
    617: "Generic Rank",
    624: "Generic Rank",
    631: "Generic Rank",
    637: "Generic Rank",
    644: "Generic Rank",
    651: "Generic Rank",
    658: "Generic Rank",
    664: "Generic Rank",
    671: "Generic Rank",
    678: "Generic Rank",
    684: "Generic Rank",
    691: "Generic Rank",
    698: "Generic Rank",
    704: "Generic Rank",
    711: "Generic Rank",
    718: "Generic Rank",
    725: "Generic Rank",
    731: "Generic Rank",
    738: "Generic Rank",
    745: "Generic Rank",
    751: "Generic Rank",
    758: "Generic Rank",
    765: "Generic Rank",
    772: "Generic Rank",
    778: "Generic Rank",
    785: "Generic Rank",
    792: "Generic Rank",
    798: "Generic Rank",
    805: "Generic Rank",
    812: "Generic Rank",
    818: "Generic Rank",
    825: "Generic Rank",
    832: "Generic Rank",
    839: "Generic Rank",
    845: "Generic Rank",
    852: "Generic Rank",
    859: "Generic Rank",
    865: "Generic Rank",
    872: "Generic Rank",
    879: "Generic Rank",
    886: "Generic Rank",
    892: "Generic Rank",
    899: "Generic Rank",
    906: "Generic Rank",
    912: "Generic Rank",
    919: "Generic Rank",
    926: "Generic Rank",
    932: "Generic Rank",
    939: "Generic Rank",
    946: "Generic Rank",
    953: "Generic Rank",
    959: "Generic Rank",
    966: "Generic Rank",
    973: "Generic Rank",
    979: "Generic Rank",
    986: "Generic Rank",
    993: "Generic Rank",
    1000: "Generic Rank",
  },
}
