import { AnimeThemeConfig } from "./types"
import { GiJoystick, GiCastle, GiArrowhead, GiLightningTrio, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiBroadsword, GiHeartKey, GiCrown } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const shangriLaFrontierTheme: AnimeThemeConfig = {
    id: "shangri-la-frontier",
    displayName: "Shangri-La Frontier",
    description: "Gamer Rakurou Hizutome specialises in conquering terrible games — but when friends convince him to try the legendary full-dive VR title Shangri-La Frontier, he discovers a massive world with hidden depths no guide can prepare you for.",
    fontFamily: "'Rajdhani', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "255 198 140",
        "--color-brand-300": "255 162 75",
        "--color-brand-400": "248 120 18",
        "--color-brand-500": "220 88 0",
        "--color-brand-600": "178 60 0",
        "--color-brand-700": "132 38 0",
        "--color-brand-800": "88 22 0",
        "--color-brand-900": "48 10 0",
        "--color-brand-950": "20 4 0",
        "--brand": "220 88 0",
        "--background": "#060200",
        "--paper": "#120500",
        "--color-gray-950": "6 2 0",
        "--color-gray-900": "14 5 0",
        "--color-gray-800": "26 10 2",
        "--color-gray-700": "44 18 4",
        "--color-gray-600": "70 32 8",
        "--color-gray-500": "110 58 18",
        "--color-gray-400": "158 96 42",
        "--color-gray-300": "200 138 78",
        "--color-gray-200": "228 178 120",
        "--color-gray-100": "245 210 162",
        "--color-gray-50": "255 238 210",
    },
    sidebarOverrides: {
        "home": { icon: GiJoystick, label: "Lobby" },
        "schedule": { icon: GiAlarmClock, label: "Server Time" },
        "manga": { icon: LuBookOpen, label: "Patch Notes" },
        "lists": { icon: GiFlowerEmblem, label: "Quest Log" },
        "discover": { icon: GiBullseye, label: "New Zones" },
        "torrent-list": { icon: GiArrowhead, label: "Gear Cache" },
        "debrid": { icon: GiCastle, label: "Vault Server" },
        "unmatched": { icon: GiHeartKey, label: "Lost Items" },
        "enmasse": { icon: GiResize, label: "Party Finder" },
        "scan-summaries": { icon: TbReportSearch, label: "Server Logs" },
        "auto-downloader": { icon: LuRss, label: "Patch Feed" },
        "community": { icon: GiBroadsword, label: "Player Guild" },
        "achievements": { icon: GiTrophy, label: "Achievement Scores" },
        "milestones": { icon: LuFlag, label: "Rank Milestones" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Server Alerts" },
        "theme-manager": { icon: GiPalette, label: "Neon Palette" },
        "extensions": { icon: BiExtension, label: "Game Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Server Sync" },
        "settings": { icon: GiSettingsKnobs, label: "SLF Config" },
    },
    achievementNames: {
        "a_first_episode": "Server Joined",
        "a_first_complete": "Dungeon Cleared",
        "a_hundred_club": "Hundred Quests",
        "a_time_lord": "Veteran Gamer",
        "a_anime_collector": "Game Archive",
        "a_library_legend": "Server Library",
        "a_binge_king": "Game Marathon",
        "a_no_sleep": "No-Sleep Run",
        "a_marathon_runner": "Hizutome's Run",
        "a_speed_run": "Speed Clear",
        "a_completionist": "100% Complete",
        "a_mega_completionist": "Master Gamer",
        "a_loyal_fan": "Main Account",
        "a_rewatcher": "New Game+",
        "a_decade_watcher": "Decade Grind",
        "a_genre_action": "Action Quest",
        "a_genre_adventure": "Open World",
        "a_genre_comedy": "Kusoge Comedy",
        "a_genre_drama": "Story Mode",
        "a_genre_fantasy": "RPG World",
        "a_genre_horror": "Horror Dungeon",
        "a_genre_romance": "None Here",
        "a_genre_scifi": "VR World",
        "a_genre_supernatural": "Hidden Lore",
        "a_genre_psychological": "Mind Game",
        "a_genre_mecha": "None Here",
        "a_critic": "Game Critic",
        "a_perfect_ten": "Perfect Score",
        "a_harsh_critic": "Kusoge Hunter",
        "a_daily_streak": "Daily Login",
        "a_mega_streak": "Endless Grind",
        "a_year_long": "Year Online",
        "a_iron_will": "Never Quit",
        "a_hidden_gem": "Hidden Zone",
        "a_cult_classic": "Classic Server",
        "a_classic_connoisseur": "2023 Fan",
        "a_new_years_resolution": "New Year Quest",
        "a_christmas_special": "Winter Event",
        "a_meta_tier_max": "True Player",
        "a_meta_completionist": "All Quests",
        "a_sequel_chain": "Sequel Chain",
        "a_zero_to_hero": "LvL 1 to Legend",
        "a_night_owl": "Night Grind",
        "a_early_bird": "Dawn Login",
        "m_first_chapter": "Tutorial Done",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Chapter Binge",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "SLF Expert",
        "m_loyal_reader": "Regular Reader",
        "m_rereader": "New Game+ Read",
        "m_genre_action": "Action Chapter",
        "m_genre_adventure": "Adventure Chapter",
        "m_genre_romance": "None Here",
        "m_genre_fantasy": "Fantasy Chapter",
        "m_genre_horror": "Horror Chapter",
        "m_genre_drama": "Story Chapter",
        "m_genre_scifi": "VR Chapter",
        "m_genre_supernatural": "Lore Chapter",
        "m_genre_psychological": "Depth Chapter",
        "m_critic": "Server Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Grind Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Iron Gamer",
        "m_hidden_gem": "Hidden Zone",
        "m_cult_classic": "Classic Chapter",
        "m_mangaka_lover": "Fuji Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "SLF Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Game Art",
        "m_manga_to_anime": "Adapted Quest",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060200",
        primary: "#dc5800",
        secondary: "#b23c00",
        accent: "#20d8f0",
    },
    particleColor: "#f07820",
    backgroundDim: 0.26,
    backgroundBlur: 14,
    particleTypes: {
        neon_glitch: { label: "Neon Glitch", maxCount: 14, defaultEnabled: true, defaultIntensity: 48 },
        golden_sparks: { label: "Game Sparks", maxCount: 12, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
    "7": "Novice Rank 1",
    "13": "Novice Level 2",
    "20": "Novice Tier 3",
    "27": "Novice Class 4",
    "33": "Novice Grade 5",
    "40": "Novice Position 6",
    "47": "Novice Status 7",
    "53": "Novice Role 8",
    "60": "Novice Title 9",
    "67": "Novice Authority 10",
    "73": "Beginner Rank 11",
    "80": "Beginner Level 12",
    "87": "Beginner Tier 13",
    "93": "Beginner Class 14",
    "100": "Beginner Grade 15",
    "107": "Beginner Position 16",
    "113": "Beginner Status 17",
    "120": "Beginner Role 18",
    "127": "Beginner Title 19",
    "133": "Student Authority 20",
    "140": "Student Rank 21",
    "147": "Student Level 22",
    "153": "Student Tier 23",
    "160": "Student Class 24",
    "167": "Student Grade 25",
    "173": "Student Position 26",
    "180": "Student Status 27",
    "187": "Student Role 28",
    "193": "Student Title 29",
    "200": "Learner Authority 30",
    "207": "Learner Rank 31",
    "213": "Learner Level 32",
    "220": "Learner Tier 33",
    "227": "Learner Class 34",
    "233": "Learner Grade 35",
    "240": "Learner Position 36",
    "247": "Learner Status 37",
    "253": "Learner Role 38",
    "260": "Adept Title 39",
    "267": "Adept Authority 40",
    "273": "Adept Rank 41",
    "280": "Adept Level 42",
    "287": "Adept Tier 43",
    "293": "Adept Class 44",
    "300": "Adept Grade 45",
    "307": "Adept Position 46",
    "313": "Adept Status 47",
    "320": "Expert Role 48",
    "327": "Expert Title 49",
    "333": "Expert Authority 50",
    "340": "Expert Rank 51",
    "347": "Expert Level 52",
    "353": "Expert Tier 53",
    "360": "Expert Class 54",
    "367": "Expert Grade 55",
    "373": "Expert Position 56",
    "380": "Expert Status 57",
    "387": "Master Role 58",
    "393": "Master Title 59",
    "400": "Master Authority 60",
    "407": "Master Rank 61",
    "413": "Master Level 62",
    "420": "Master Tier 63",
    "427": "Master Class 64",
    "433": "Master Grade 65",
    "440": "Master Position 66",
    "447": "Grandmaster Status 67",
    "453": "Grandmaster Role 68",
    "460": "Grandmaster Title 69",
    "467": "Grandmaster Authority 70",
    "473": "Grandmaster Rank 71",
    "480": "Grandmaster Level 72",
    "487": "Grandmaster Tier 73",
    "493": "Grandmaster Class 74",
    "500": "Grandmaster Grade 75",
    "507": "Sage Position 76",
    "513": "Sage Status 77",
    "520": "Sage Role 78",
    "527": "Sage Title 79",
    "533": "Sage Authority 80",
    "540": "Sage Rank 81",
    "547": "Sage Level 82",
    "553": "Sage Tier 83",
    "560": "Sage Class 84",
    "567": "Sage Grade 85",
    "573": "Legend Position 86",
    "580": "Legend Status 87",
    "587": "Legend Role 88",
    "593": "Legend Title 89",
    "600": "Legend Authority 90",
    "607": "Legend Rank 91",
    "613": "Legend Level 92",
    "620": "Legend Tier 93",
    "627": "Legend Class 94",
    "633": "Mythical Grade 95",
    "640": "Mythical Position 96",
    "647": "Mythical Status 97",
    "653": "Mythical Role 98",
    "660": "Mythical Title 99",
    "667": "Mythical Authority 100",
    "673": "Mythical Rank 101",
    "680": "Mythical Level 102",
    "687": "Mythical Tier 103",
    "693": "Mythical Class 104",
    "700": "Godly Grade 105",
    "707": "Godly Position 106",
    "713": "Godly Status 107",
    "720": "Godly Role 108",
    "727": "Godly Title 109",
    "733": "Godly Authority 110",
    "740": "Godly Rank 111",
    "747": "Godly Level 112",
    "753": "Godly Tier 113",
    "760": "Supreme Class 114",
    "767": "Supreme Grade 115",
    "773": "Supreme Position 116",
    "780": "Supreme Status 117",
    "787": "Supreme Role 118",
    "793": "Supreme Title 119",
    "800": "Supreme Authority 120",
    "807": "Supreme Rank 121",
    "813": "Supreme Level 122",
    "820": "Infinite Tier 123",
    "827": "Infinite Class 124",
    "833": "Infinite Grade 125",
    "840": "Infinite Position 126",
    "847": "Infinite Status 127",
    "853": "Infinite Role 128",
    "860": "Infinite Title 129",
    "867": "Infinite Authority 130",
    "873": "Infinite Rank 131",
    "880": "Infinite Level 132",
    "887": "Eternal Tier 133",
    "893": "Eternal Class 134",
    "900": "Eternal Grade 135",
    "907": "Eternal Position 136",
    "913": "Eternal Status 137",
    "920": "Eternal Role 138",
    "927": "Eternal Title 139",
    "933": "Eternal Authority 140",
    "940": "Eternal Rank 141",
    "947": "Transcendent Level 142",
    "953": "Transcendent Tier 143",
    "960": "Transcendent Class 144",
    "967": "Transcendent Grade 145",
    "973": "Transcendent Position 146",
    "980": "Transcendent Status 147",
    "987": "Transcendent Role 148",
    "993": "Transcendent Title 149",
    "1000": "Transcendent Authority 150"
},
}
