import { AnimeThemeConfig } from "./types"
import { GiFlowerEmblem, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiCrystalBall, GiStarSwirl, GiSpellBook } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const takagiSanTheme: AnimeThemeConfig = {
    id: "takagi-san",
    displayName: "Teasing Master Takagi-san",
    description: "Middle schooler Nishikata vows to get back at his classmate Takagi, who teases him mercilessly. But she always reads him perfectly — and her gentle teasing hides feelings deeper than either will admit.",
    cssVars: {
        "--color-brand-200": "190 225 255",
        "--color-brand-300": "135 190 248",
        "--color-brand-400": "82 152 235",
        "--color-brand-500": "40 112 208",
        "--color-brand-600": "15 76 168",
        "--color-brand-700": "4 46 122",
        "--color-brand-800": "1 22 78",
        "--color-brand-900": "0 8 40",
        "--color-brand-950": "0 2 16",
        "--brand": "40 112 208",
        "--background": "#000208",
        "--paper": "#000514",
        "--color-gray-950": "0 2 8",
        "--color-gray-900": "1 6 18",
        "--color-gray-800": "3 14 35",
        "--color-gray-700": "6 26 58",
        "--color-gray-600": "10 45 90",
        "--color-gray-500": "18 75 130",
        "--color-gray-400": "40 115 168",
        "--color-gray-300": "75 155 205",
        "--color-gray-200": "118 192 230",
        "--color-gray-100": "170 218 248",
        "--color-gray-50": "220 240 255",
    },
    sidebarOverrides: {
        "home": { icon: GiFlowerEmblem, label: "Classroom" },
        "schedule": { icon: GiAlarmClock, label: "School Schedule" },
        "manga": { icon: LuBookOpen, label: "Prank Log" },
        "lists": { icon: GiScrollUnfurled, label: "Tease Record" },
        "discover": { icon: GiBullseye, label: "New Pranks" },
        "torrent-list": { icon: GiStarSwirl, label: "Memory Cache" },
        "debrid": { icon: GiHeartKey, label: "Secret Vault" },
        "unmatched": { icon: GiCrystalBall, label: "Unread Feelings" },
        "enmasse": { icon: GiResize, label: "School Event" },
        "scan-summaries": { icon: TbReportSearch, label: "Prank Reports" },
        "auto-downloader": { icon: LuRss, label: "Tease Feed" },
        "community": { icon: GiSpellBook, label: "Classroom Circle" },
        "achievements": { icon: GiTrophyCup, label: "Blush Trophies" },
        "milestones": { icon: LuFlag, label: "Tease Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Class Alerts" },
        "theme-manager": { icon: GiPalette, label: "Summer Colors" },
        "extensions": { icon: BiExtension, label: "School Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Class Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Nishikata Config" },
    },
    achievementNames: {
        "a_first_episode": "First Prank",
        "a_first_complete": "Outsmarted Again",
        "a_hundred_club": "Hundred Rounds Lost",
        "a_binge_king": "Takagi-san Marathon",
        "a_completionist": "All Pranks Logged",
        "a_mega_completionist": "Finally Understood",
        "a_loyal_fan": "Classroom Regular",
        "a_zero_to_hero": "Flustered to Lovestruck",
        "m_first_chapter": "First Match",
        "m_completionist": "Full Manga Archive",
    },
    musicUrl: "",
    previewColors: {
        bg: "#000208",
        primary: "#2870d0",
        secondary: "#cc6688",
        accent: "#b8d8f8",
    },
    particleColor: "#5090d8",
    backgroundDim: 0.25,
    backgroundBlur: 18,
    milestoneNames: {
    1: "Generic Rank",
    7: "Generic Rank",
    14: "Generic Rank",
    21: "Generic Rank",
    27: "Generic Rank",
    34: "Generic Rank",
    41: "Generic Rank",
    47: "Generic Rank",
    54: "Generic Rank",
    61: "Generic Rank",
    68: "Generic Rank",
    74: "Generic Rank",
    81: "Generic Rank",
    88: "Generic Rank",
    94: "Generic Rank",
    101: "Generic Rank",
    108: "Generic Rank",
    114: "Generic Rank",
    121: "Generic Rank",
    128: "Generic Rank",
    135: "Generic Rank",
    141: "Generic Rank",
    148: "Generic Rank",
    155: "Generic Rank",
    161: "Generic Rank",
    168: "Generic Rank",
    175: "Generic Rank",
    182: "Generic Rank",
    188: "Generic Rank",
    195: "Generic Rank",
    202: "Generic Rank",
    208: "Generic Rank",
    215: "Generic Rank",
    222: "Generic Rank",
    228: "Generic Rank",
    235: "Generic Rank",
    242: "Generic Rank",
    249: "Generic Rank",
    255: "Generic Rank",
    262: "Generic Rank",
    269: "Generic Rank",
    275: "Generic Rank",
    282: "Generic Rank",
    289: "Generic Rank",
    296: "Generic Rank",
    302: "Generic Rank",
    309: "Generic Rank",
    316: "Generic Rank",
    322: "Generic Rank",
    329: "Generic Rank",
    336: "Generic Rank",
    342: "Generic Rank",
    349: "Generic Rank",
    356: "Generic Rank",
    363: "Generic Rank",
    369: "Generic Rank",
    376: "Generic Rank",
    383: "Generic Rank",
    389: "Generic Rank",
    396: "Generic Rank",
    403: "Generic Rank",
    409: "Generic Rank",
    416: "Generic Rank",
    423: "Generic Rank",
    430: "Generic Rank",
    436: "Generic Rank",
    443: "Generic Rank",
    450: "Generic Rank",
    456: "Generic Rank",
    463: "Generic Rank",
    470: "Generic Rank",
    477: "Generic Rank",
    483: "Generic Rank",
    490: "Generic Rank",
    497: "Generic Rank",
    503: "Generic Rank",
    510: "Generic Rank",
    517: "Generic Rank",
    523: "Generic Rank",
    530: "Generic Rank",
    537: "Generic Rank",
    544: "Generic Rank",
    550: "Generic Rank",
    557: "Generic Rank",
    564: "Generic Rank",
    570: "Generic Rank",
    577: "Generic Rank",
    584: "Generic Rank",
    591: "Generic Rank",
    597: "Generic Rank",
    604: "Generic Rank",
    611: "Generic Rank",
    617: "Generic Rank",
    624: "Generic Rank",
    631: "Generic Rank",
    637: "Generic Rank",
    644: "Generic Rank",
    651: "Generic Rank",
    658: "Generic Rank",
    664: "Generic Rank",
    671: "Generic Rank",
    678: "Generic Rank",
    684: "Generic Rank",
    691: "Generic Rank",
    698: "Generic Rank",
    704: "Generic Rank",
    711: "Generic Rank",
    718: "Generic Rank",
    725: "Generic Rank",
    731: "Generic Rank",
    738: "Generic Rank",
    745: "Generic Rank",
    751: "Generic Rank",
    758: "Generic Rank",
    765: "Generic Rank",
    772: "Generic Rank",
    778: "Generic Rank",
    785: "Generic Rank",
    792: "Generic Rank",
    798: "Generic Rank",
    805: "Generic Rank",
    812: "Generic Rank",
    818: "Generic Rank",
    825: "Generic Rank",
    832: "Generic Rank",
    839: "Generic Rank",
    845: "Generic Rank",
    852: "Generic Rank",
    859: "Generic Rank",
    865: "Generic Rank",
    872: "Generic Rank",
    879: "Generic Rank",
    886: "Generic Rank",
    892: "Generic Rank",
    899: "Generic Rank",
    906: "Generic Rank",
    912: "Generic Rank",
    919: "Generic Rank",
    926: "Generic Rank",
    932: "Generic Rank",
    939: "Generic Rank",
    946: "Generic Rank",
    953: "Generic Rank",
    959: "Generic Rank",
    966: "Generic Rank",
    973: "Generic Rank",
    979: "Generic Rank",
    986: "Generic Rank",
    993: "Generic Rank",
    1000: "Generic Rank",
  },
}
