import { AnimeThemeConfig } from "./types"
import { GiNinjaHead, GiDaggers, GiShadowGrasp, GiCrown, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiDramaMasks, GiHeartKey, GiBroadsword } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const theEminenceInShadowTheme: AnimeThemeConfig = {
    id: "the-eminence-in-shadow",
    displayName: "The Eminence in Shadow",
    description: "Reincarnated as Cid Kagenou, a boy obsessed with becoming an all-powerful shadowy mastermind, he creates a fictional organisation called Shadow Garden — only to discover it's fighting a real ancient evil.",
    fontFamily: "'Cinzel', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "200 168 255",
        "--color-brand-300": "162 120 240",
        "--color-brand-400": "128 80 218",
        "--color-brand-500": "96 48 188",
        "--color-brand-600": "68 24 160",
        "--color-brand-700": "46 10 128",
        "--color-brand-800": "30 4 92",
        "--color-brand-900": "16 0 56",
        "--color-brand-950": "6 0 24",
        "--brand": "96 48 188",
        "--background": "#010004",
        "--paper": "#06000e",
        "--color-gray-950": "1 0 4",
        "--color-gray-900": "6 2 12",
        "--color-gray-800": "14 6 26",
        "--color-gray-700": "26 12 46",
        "--color-gray-600": "44 22 74",
        "--color-gray-500": "72 40 115",
        "--color-gray-400": "108 70 158",
        "--color-gray-300": "150 108 200",
        "--color-gray-200": "190 155 232",
        "--color-gray-100": "220 195 248",
        "--color-gray-50": "244 232 255",
    },
    sidebarOverrides: {
        "home": { icon: GiShadowGrasp, label: "Shadow Garden HQ" },
        "schedule": { icon: GiAlarmClock, label: "Operation Schedule" },
        "manga": { icon: LuBookOpen, label: "Ancient Texts" },
        "lists": { icon: GiFlowerEmblem, label: "Cult Registry" },
        "discover": { icon: GiBullseye, label: "New Targets" },
        "torrent-list": { icon: GiDaggers, label: "Shadow Arsenal" },
        "debrid": { icon: GiDramaMasks, label: "Shadow Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Shadows" },
        "enmasse": { icon: GiResize, label: "Shadow Ops" },
        "scan-summaries": { icon: TbReportSearch, label: "Op Reports" },
        "auto-downloader": { icon: LuRss, label: "Cult Intel" },
        "community": { icon: GiNinjaHead, label: "Shadow Circle" },
        "achievements": { icon: GiTrophy, label: "Shadow Trophies" },
        "milestones": { icon: LuFlag, label: "Shadow Milestones" },
        "search": { icon: FiSearch, label: "Shadow Search" },
        "notifications": { icon: LuBell, label: "Cult Alerts" },
        "theme-manager": { icon: GiPalette, label: "Shadow Palette" },
        "extensions": { icon: BiExtension, label: "Shadow Modules" },
        "sync": { icon: IoCloudOfflineOutline, label: "Shadow Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Cid's Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Infiltration",
        "a_episode_counter": "Night Stalker Mark",
        "a_episode_titan": "Ancient Evil Relic",
        "a_hours_invested": "Shadow Garden Hq Proof",
        "a_time_lord": "Shadow Elder",
        "a_anime_collector": "Shadow Archive",
        "a_library_legend": "Ancient Vault",
        "a_first_complete": "Shadow Revealed",
        "a_hundred_club": "Hundred Shadows",
        "a_first_day": "Loyal Shadow Seal",
        "a_first_rating": "Ancient Evil Appraisal",
        "a_ten_thousand_min": "Ancient Vault Standard",
        "a_season_veteran": "Ancient Vault Library",
        "a_year_explorer": "Shadow Chain Map",
        "a_century_watcher": "Shadow Garden Ledger",
        "a_five_hundred_eps": "Shadow Blitz Dominion",
        "a_thousand_eps": "Shadow Action Record",
        "a_watching_ten": "The Eminence In Shadow Acclaim",
        "a_ptw_hoarder": "Shadow Arsenal Library",
        "a_dropped_honesty": "The Eminence In Shadow Summit",
        "a_five_thousand_eps": "Ancient Texts Warrant",
        "a_ten_completed": "Night Lurker Afterglow",
        "a_fifty_completed": "Shadow Critic Ascension",
        "a_five_hundred_completed": "The Eminence In Shadow Clear",
        "a_mean_score_tracker": "Shadow Expert Verdict",
        "a_unique_studios": "Shadow Action Collection",
        "a_days_spent_watching": "Decade Shadow Dominion",
        "a_all_status": "Action Shadow Testament",
        "a_first_favorite": "Cid Kagenou Cabinet",
        "a_favorites_collector": "Shadow World Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Shadow Drama Drive",
        "a_marathon_runner": "Cid's Dash",
        "a_weekend_warrior": "Ancient Evil Ordeal",
        "a_non_stop": "Shadow Palette Fever",
        "a_one_more_episode": "Dawn Phantom Mantle",
        "a_speed_run": "Shadow Blitz",
        "a_double_feature": "Shadow Art Crown",
        "a_triple_threat": "Cult Registry Record",
        "a_five_a_day": "Cid's Mind Accord",
        "a_back_to_back": "Winter Shadow Surge",
        "a_seasonal_binge": "Ancient Evil Cascade",
        "a_cour_crusher": "Decade Shadow Ordeal",
        "a_half_day_watch": "Night Stalker Crown",
        "a_full_day_watch": "Iron Shadow Pinnacle",
        "a_power_weekend": "Loyal Shadow Run",
        "a_binge_king": "Shadow Marathon",
        "a_no_sleep": "All-Night Lurker",
        "a_entire_season": "Lost Shadows Library",
        "a_seven_day_challenge": "Iron Shadow Mark",
        "a_hundred_day_binge": "Loyal Shadow Surge",
        "a_genre_binge": "Shadow Modules Binge",
        "a_studio_binge": "Night Stalker Fever",
        "a_season_sweep": "Shadow Archive Codex",
        "a_forty_eight_hour": "Beta Shadow Overture",
        "a_ep_counter_day": "Night Lurker Aegis",
        "a_multi_series_binge": "Shadow Arsenal Streak",
        "a_midnight_binge": "Dawn Phantom Cascade",
        "a_new_year_binge": "Shadow Elder Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Shadow Action",
        "a_genre_adventure": "Shadow Journey",
        "a_genre_comedy": "Accidental Genius",
        "a_genre_drama": "Shadow Drama",
        "a_genre_fantasy": "Shadow World",
        "a_genre_horror": "Cult Fear",
        "a_genre_mystery": "Shadow Artist Mystery",
        "a_genre_romance": "None Here",
        "a_genre_scifi": "None Here",
        "a_genre_sol": "Ancient Texts Slice",
        "a_genre_sports": "Beta Shadow Sports",
        "a_genre_supernatural": "Ancient Evil",
        "a_genre_thriller": "Shadow Critic Thriller",
        "a_genre_mecha": "None Here",
        "a_genre_music": "Ancient Vault Music",
        "a_genre_psychological": "Cid's Mind",
        "a_genre_ecchi": "Shadow Drama Ecchi",
        "a_genre_mahou_shoujo": "Cult Registry Magic Shoujo",
        "a_tag_isekai": "Mind Cid Isekai",
        "a_tag_harem": "Shadow Ops Harem",
        "a_tag_bl": "Beta Shadow Bl",
        "a_tag_gl": "Dawn Phantom Gl",
        "a_tag_historical": "All Night Historical",
        "a_tag_military": "Shadow Blitz Military",
        "a_tag_school": "Shadow Arsenal School",
        "a_tag_martial_arts": "Iron Shadow Martial Arts",
        "a_tag_vampire": "Cult Registry Vampire",
        "a_tag_samurai": "Shadow Action Samurai",
        "a_tag_space": "Cult Intel Space",
        "a_tag_parody": "Cult Alerts Parody",
        "a_tag_idol": "Beta Shadow Idol",
        "a_tag_post_apocalyptic": "Shadow Review Post Apocalyptic",
        "a_tag_cyberpunk": "Shadow Palette Cyberpunk",
        "a_tag_shounen": "Shadow Review Shounen",
        "a_tag_seinen": "All Shadows Seinen",
        "a_tag_shoujo": "All Shadows Shoujo",
        "a_tag_josei": "Night Lurker Josei",
        "a_tag_survival": "Shadow World Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Operation",
        "a_mega_completionist": "Shadow Master",
        "a_completion_rate_50": "Cult Registry Return",
        "a_completion_rate_75": "Shadow Critic Crown",
        "a_completion_rate_90": "Night Lurker Resolution",
        "a_no_drop": "Shadow Artist Decree",
        "a_long_runner_complete": "Loyal Shadow Clear",
        "a_sequel_chain": "Shadow Chain",
        "a_clean_list": "Shadow Archive Relic",
        "a_from_ptw": "Cult Alerts Index",
        "a_rewatch_master": "Shadow Expert Return",
        "a_short_complete": "Shadow Master Endgame",
        "a_same_day_start_finish": "Shadow Streak Pinnacle",
        "a_revival": "Shadow Garden Insignia",
        "a_zero_to_hero": "Beta to Shadow",
        "a_five_genre_complete": "Shadow Master A Five Genre",
        "a_full_franchise": "Shadow Arsenal Chronicle",
        "a_batch_complete": "Ancient Evil Crown",
        "a_paused_to_done": "Night Lurker Aegis Aegis",
        "a_completion_spree": "Daily Shadow Triumph",
        "a_multi_rewatch": "Daily Shadow Triumph Triumph",
        "a_dropped_recovery": "Night Stalker Conquest",
        "a_ten_perfect_scores": "Loyal Shadow Acclaim",
        "a_seasonal_clear": "Decade Shadow Codex",
        "a_complete_genre_span": "Cid's Dash A Complete Genre",
        "a_monthly_completions": "Shadow Expert Afterglow",
        "a_yearly_completions": "Action Shadow Epilogue",
        "a_rapid_complete": "Iron Shadow Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Shadow",
        "a_studio_devotee": "Shadow Artist Treasury",
        "a_rewatcher": "Replay Infiltration",
        "a_triple_rewatch": "Shadow Modules Coda",
        "a_annual_tradition": "Iron Shadow Proof",
        "a_director_fan": "Shadow Archive Trial",
        "a_voice_actor_fan": "Night Stalker Crown Crown",
        "a_ost_lover": "Shadow Arsenal Seal",
        "a_source_reader": "Shadow Chain Cabinet",
        "a_waiting_weekly": "Shadow Artist Clock",
        "a_childhood_revisit": "Perfect Plan Seal",
        "a_saga_tracker": "Cult Intel Standard",
        "a_genre_loyalty": "Ancient Texts Loyalty",
        "a_decade_watcher": "Decade in Shadow",
        "a_adaptation_hunter": "Cult Alerts Trial",
        "a_original_anime_fan": "Shadow Vault Testament",
        "a_long_commitment": "Iron Shadow Mark Mark",
        "a_perfect_attendance": "The Eminence In Shadow Standard",
        "a_favorite_studio_5": "Shadow Review Library",
        "a_complete_catalog": "Shadow World Seal",
        "a_franchise_collector": "Shadow Review Archive",
        "a_airing_follower": "Perfect Plan Signal",
        "a_genre_master": "Shadow Archive Master",
        "a_staff_follower": "Shadow Review Oath",
        "a_multi_season_fan": "All Night Hoard",
        "a_format_diversity": "Cult Registry Cache",
        "a_year_dedication": "Ancient Evil Tenure",
        "a_season_dedication": "Shadow Blitz Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Shadow Modules Explorer",
        "a_studio_hopper": "Shadow Expert Collection",
        "a_tag_explorer": "Ancient Evil Explorer",
        "a_decade_hopper": "Shadow Arsenal Chronicle Chronicle",
        "a_hidden_gem": "Hidden Darkness",
        "a_popular_taste": "Beta Shadow Decree",
        "a_retro_appreciator": "Shadow World Aegis",
        "a_modern_viewer": "Shadow Streak Pinnacle Pinnacle",
        "a_cross_demographic": "Shadow Drama Pinnacle",
        "a_underdog_fan": "Cid's Dash Trial",
        "a_variety_week": "Shadow Review Horizon",
        "a_foreign_cinema": "Dawn Phantom Expedition",
        "a_classic_connoisseur": "2022 Fan",
        "a_every_season": "Perfect Plan Archive",
        "a_award_winner": "Ancient Vault Insignia",
        "a_niche_explorer": "All Shadows Horizon",
        "a_global_anime": "Shadow Master Crown",
        "a_cult_classic": "Shadow Classic",
        "a_random_pick": "Beta Shadow Decree Decree",
        "a_new_genre_month": "The Eminence In Shadow A",
        "a_seasonal_completionist": "Shadow Garden Summit",
        "a_unpopular_opinion": "Cid Kagenou Standard",
        "a_top_rated_viewer": "Cid's Mind Seal",
        "a_source_variety": "Decade Shadow Storehouse",
        "a_low_score_brave": "Shadow Palette Measure",
        "a_upcoming_watcher": "Cid's Mind Seal Seal",
        "a_short_series_explorer": "Dawn Phantom Expedition Expedition",
        "a_long_series_explorer": "Shadow Art Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Night Stalker",
        "a_early_bird": "Dawn Phantom",
        "a_lunch_break": "Cult Fear Trial",
        "a_golden_hour": "Shadow Circle Tenure",
        "a_four_am_club": "Daily Shadow Gathering",
        "a_witching_hour": "Shadow Critic Tenure",
        "a_new_year_watch": "Ancient Evil Season",
        "a_midnight_premiere": "Shadow Elder Devotion",
        "a_all_hours": "Shadow Garden Seal",
        "a_dawn_warrior": "Beta Shadow Aegis",
        "a_afternoon_delight": "Shadow Garden Hq Proof Proof",
        "a_prime_time": "Ancient Vault Insignia Insignia",
        "a_workday_watcher": "Shadow Drama Pinnacle Pinnacle",
        "a_sunday_marathon": "Loyal Shadow Momentum",
        "a_rainy_day": "Shadow Critic Relic",
        "a_morning_routine": "All Night Promise",
        "a_night_shift": "Cult Registry Aegis",
        "a_twilight_zone": "Lost Shadows Ledger",
        "a_seasonal_premier": "Shadow Artist Cabinet",
        "a_clock_collector": "Daily Shadow Repository",
        "a_weekend_binge_hours": "All Shadows Streak",
        "a_late_night_regular": "Action Shadow Dominion",
        "a_sunrise_watcher": "Shadow Archive Relic Relic",
        "a_holiday_watcher": "Cid's Mind Pact",
        "a_every_day_of_week": "Winter Shadow Ledger",
        "a_monthly_hours": "Beta Shadow Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Night Lurker Record",
        "a_party_host": "Cult Registry Record Record",
        "a_social_butterfly": "Shadow Chain Company",
        "a_group_binge": "Shadow Action Sprint",
        "a_party_regular": "Lost Shadows Chronicle",
        "a_sync_viewer": "Daily Shadow Standard",
        "a_commentator": "Shadow World Record",
        "a_party_marathon": "Shadow Modules Vigil",
        "a_full_house": "Shadow Blitz Trial",
        "a_community_pillar": "Action Shadow Alliance",
        "a_watch_party_streak": "Shadow World Vigil",
        "a_diverse_party": "All Night Seal",
        "a_late_night_party": "Action Shadow Testament Testament",
        "a_party_veteran": "Shadow Blitz Testament",
        "a_genre_party": "Dawn Phantom Party",
        "a_weekly_party": "Daily Shadow Calendar",
        "a_silent_viewer": "Shadow Vault Mantle",
        "a_recommendation_giver": "All Shadows Network",
        "a_party_completionist": "Cult Intel Coda",
        "a_social_scorer": "Shadow Archive Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Shadow Art Proof",
        "a_fibonacci": "Ancient Evil Dominion",
        "a_palindrome_day": "Ancient Evil Relic Relic",
        "a_binary_day": "Ancient Texts Mark",
        "a_full_moon": "Perfect Plan Insignia",
        "a_leap_year": "Shadow Master Devotion",
        "a_time_traveler": "Shadow Artist Record",
        "a_genre_clash": "Shadow Modules Clash",
        "a_triple_seven": "Ancient Evil Testament",
        "a_thousand_complete": "Shadow Vault Epilogue",
        "a_pi_episodes": "Shadow Drama Crown",
        "a_synchronicity": "Cid's Dash Anchor",
        "a_world_record": "Night Stalker Warrant",
        "a_nice": "Ancient Vault Chronicle",
        "a_power_level": "Shadow Vault Testament Testament",
        "a_answer_42": "Beta Shadow Standard",
        "a_square_number": "Shadow Modules Decree",
        "a_prime_count": "Ancient Vault Seal",
        "a_matching_date": "Cid's Dash Mantle",
        "a_century_episode": "Shadow Drama Mark",
        "a_double_digits": "Shadow Critic Testament",
        "a_one_two_three": "Shadow Master Crown Crown",
        "a_lucky_seven": "Iron Shadow Crown",
        "a_all_tens": "Shadow Palette Criterion",
        "a_exact_hundred_eps": "Cult Intel Legend",
        "a_year_match_count": "Shadow Artist Yearlong",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "All Shadows Ledger",
        "a_movie_buff": "Night Stalker Mark Mark",
        "a_ova_hunter": "Cult Intel Standard Standard",
        "a_ona_explorer": "Cid's Dash Secret",
        "a_special_watcher": "Shadow Critic Relic Relic",
        "a_short_king": "Shadow Ops Crown",
        "a_variety_pack": "Night Stalker Inquiry",
        "a_film_festival": "Cid's Mind Chronicle",
        "a_music_video": "All Night Chronicle",
        "a_tv_short": "Shadow Modules Record",
        "a_movie_marathon": "Shadow Modules Gauntlet",
        "a_double_length": "Shadow Art Crown Crown",
        "a_anthology": "Cult Registry Aegis Aegis",
        "a_mini_series": "Cid Kagenou Decree",
        "a_theatrical": "Shadow Review Accord",
        "a_format_master": "Daily Shadow Vault",
        "a_long_movie": "Shadow Garden Insignia Insignia",
        "a_back_catalog": "Shadow World Standard",
        "a_cm_watcher": "Mind Cid Aegis",
        "a_pv_collector": "Cid's Dash Storehouse",
        "a_format_balance": "Daily Shadow Vault Vault",
        "a_episodic_master": "Mind Cid Standard",
        "a_sequel_movie": "Shadow Master Pinnacle",
        "a_recap_watcher": "Cult Fear Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Shadow",
        "a_mega_streak": "Eternal Shadow",
        "a_weekly_warrior": "Shadow Blitz Season",
        "a_monthly_watcher": "Shadow Elder Calendar",
        "a_comeback": "Shadow Chain Decree",
        "a_weekend_streak": "Shadow Palette Passage",
        "a_no_zero_days": "Ancient Texts Warrant Warrant",
        "a_iron_will": "Unyielding Shadow",
        "a_habit_formed": "Winter Shadow Banner",
        "a_consistent_pace": "Shadow Art Measure",
        "a_year_long": "Year in Darkness",
        "a_double_streak": "Shadow Archive Watch",
        "a_streak_recovery": "Shadow Vault Season",
        "a_daily_minimum": "Shadow Elder Focus",
        "a_winter_streak": "Dawn Phantom Watch",
        "a_summer_streak": "Shadow Critic Resolve",
        "a_morning_streak": "Shadow World Clock",
        "a_night_streak": "Winter Shadow Constancy",
        "a_unbreakable": "Shadow Ops Proof",
        "a_eternal_flame": "Shadow Expert Standard",
        "a_completion_streak": "Cult Intel Return",
        "a_rating_streak": "Ancient Evil Balance",
        "a_multi_ep_streak": "Night Stalker Ritual",
        "a_genre_streak": "Ancient Evil Streak",
        "a_studio_streak": "Shadow Chain Cabinet Cabinet",
        "a_perfect_week": "Cid's Dash Relic",

        // ── ANIME SCORING ──
        "a_critic": "Shadow Critic",
        "a_perfect_ten": "Perfect Plan",
        "a_harsh_critic": "Shadow Standard",
        "a_fair_judge": "Action Shadow Balance",
        "a_generous_spirit": "Shadow Elder Pinnacle",
        "a_score_all": "Shadow Garden Hq Criterion",
        "a_wide_range": "Ancient Vault Ledger",
        "a_controversial": "Shadow World Decree",
        "a_consistent_scorer": "Shadow Artist Verdict",
        "a_score_sniper": "Shadow Master Score",
        "a_evolving_taste": "Shadow Archive Testament",
        "a_bell_curve": "The Eminence In Shadow Insignia",
        "a_picky_watcher": "Shadow Vault Warrant",
        "a_100_rated": "Daily Shadow Warrant",
        "a_500_rated": "Shadow Ops Pinnacle",
        "a_mediocre_majority": "Cid's Dash Canon",
        "a_rating_spree": "Shadow World Review",
        "a_score_variance": "Shadow Palette Score",
        "a_masterpiece_hunter": "Shadow World Banner",
        "a_contrarian": "Shadow Modules Record Record",
        "a_optimist": "All Night Ledger",
        "a_score_distributor": "Cult Fear Appraisal",
        "a_genre_critic": "Shadow Art Critic",
        "a_mean_above_8": "Iron Shadow Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Dark",
        "a_valentines_weeb": "Shadow Review Vow",
        "a_pi_day": "Action Shadow Trial",
        "a_april_fools": "Shadow Master Devotion Devotion",
        "a_international_anime_day": "Shadow Garden Record",
        "a_star_wars_day": "Loyal Shadow Chronicle",
        "a_summer_solstice": "Ancient Texts Calendar",
        "a_tanabata": "Shadow Streak Focus",
        "a_friday_13th": "Cult Fear Relic",
        "a_halloween_spirit": "All Shadows Vow",
        "a_thanksgiving_binge": "Lost Shadows Run",
        "a_christmas_special": "Winter Shadow",
        "a_new_years_eve": "Iron Shadow Pilgrimage",
        "a_birthday_watch": "The Eminence In Shadow Vow",
        "a_holiday_marathon": "Shadow Action Overture",
        "a_independence_day": "Shadow Expert Banner",
        "a_culture_day": "Shadow Arsenal Insignia",
        "a_spring_equinox": "Shadow Action Decree",
        "a_earth_day": "Night Stalker Mantle",
        "a_labor_day": "All Shadows Seal",
        "a_winter_solstice": "Shadow Drama Pilgrimage",
        "a_anime_birthday": "Night Stalker Pilgrimage",
        "a_every_holiday": "Cult Alerts Resolve",
        "a_consecutive_holidays": "Shadow Critic Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Shadow Chain Rank",
        "a_meta_collector": "Shadow Arsenal Hoard",
        "a_meta_category_starter": "Shadow Elder Badge",
        "a_meta_tier_climber": "Shadow Arsenal Glyph",
        "a_meta_tier_max": "True Eminence",
        "a_meta_xp_earner": "Cult Fear Emblem",
        "a_meta_difficulty_easy": "Action Shadow Mechanism",
        "a_meta_difficulty_hard": "Cid's Mind Writ",
        "a_meta_unlock_spree": "Shadow Blitz Panel",
        "a_meta_completionist": "All Shadows",
        "a_meta_diverse": "Ancient Evil Emblem",
        "a_meta_dominator": "Lost Shadows Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Shadow",
        "m_chapter_counter": "Daily Shadow Pinnacle",
        "m_chapter_titan": "Decade Shadow Relic",
        "m_reading_hours": "Cult Fear Relic Relic",
        "m_reading_time_lord": "Shadow Garden Record Record",
        "m_manga_collector": "Shadow Blitz Ledger",
        "m_library_legend": "Shadow Arsenal Reliquary",
        "m_first_complete": "Op Complete",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "Shadow Review Seal",
        "m_first_rating": "Cult Fear Eye",
        "m_ten_thousand_pages": "Shadow Review Gauge",
        "m_volume_collector": "Shadow Vault Storehouse",
        "m_year_explorer": "Beta Shadow Quest",
        "m_century_reader": "Dawn Phantom Dominion",
        "m_five_hundred_ch": "Ancient Vault Legend",
        "m_thousand_ch": "Shadow Archive Legend",
        "m_reading_ten": "Dawn Phantom Appraisal",
        "m_ptr_hoarder": "Shadow Archive Index",
        "m_dropped_honesty": "Shadow Arsenal Summit",
        "m_season_reader": "Shadow World Treasury",
        "m_active_reader": "Shadow Critic Trial",
        "m_five_thousand_ch": "Shadow Modules Standard",
        "m_ten_completed": "Shadow Modules Resolution",
        "m_fifty_completed": "Shadow Archive Harvest",
        "m_five_hundred_completed": "Winter Shadow Legacy",
        "m_mean_score_tracker": "Shadow Artist Audit",
        "m_unique_authors": "Night Stalker Reserve",
        "m_all_status": "Shadow Critic Testament Testament",
        "m_first_favorite": "Cult Intel Cache",
        "m_favorites_collector": "Shadow Chain Shelf",
        "m_days_spent_reading": "Shadow Drama Relic",

        // ── MANGA BINGE ──
        "m_binge_reader": "The Eminence In Shadow Streak",
        "m_marathon_reader": "Action Shadow Rush",
        "m_weekend_reader": "Perfect Plan Run",
        "m_non_stop_reading": "Cult Intel Gauntlet",
        "m_one_more_chapter": "Cult Fear Testament Testament",
        "m_speed_read": "Ancient Texts Drive",
        "m_double_story": "Shadow Action Banner",
        "m_triple_read": "Shadow Expert Record",
        "m_five_a_day": "All Night Insignia",
        "m_chapter_chain": "Shadow Arsenal Accord",
        "m_volume_binge": "Shadow Palette Drive",
        "m_power_reader": "Loyal Shadow Seal Seal",
        "m_half_day_read": "Shadow Chain Aegis",
        "m_full_day_read": "Mind Cid Aegis Aegis",
        "m_power_weekend": "Shadow Review Streak",
        "m_binge_king": "Shadow Reading",
        "m_no_sleep_read": "Dawn Phantom Rush",
        "m_full_series_rush": "Action Shadow Cascade",
        "m_seven_day_challenge": "Shadow Streak Warrant",
        "m_hundred_day_read": "Ancient Evil Legend",
        "m_volume_rush": "Night Lurker Gauntlet",
        "m_series_sweep": "Cult Alerts Trial Trial",
        "m_genre_binge": "Mind Cid Binge",
        "m_author_binge": "Perfect Plan Surge",
        "m_chapter_counter_day": "Lost Shadows Ledger Ledger",
        "m_multi_series_binge": "Ancient Vault Charge",
        "m_midnight_binge": "Shadow Archive Tempest",
        "m_new_year_binge": "Night Stalker Passage",
        "m_forty_eight_hour": "Shadow Artist Rally",
        "m_oneshot_binge": "Ancient Texts Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Shadow",
        "m_genre_adventure": "Stealth Chapter",
        "m_genre_comedy": "Shadow Chain Comedy",
        "m_genre_drama": "Shadow Drama",
        "m_genre_fantasy": "Ancient Chapter",
        "m_genre_horror": "Cult Chapter",
        "m_genre_mystery": "Shadow Modules Mystery",
        "m_genre_romance": "None Here",
        "m_genre_scifi": "None Here",
        "m_genre_sol": "Daily Shadow Slice",
        "m_genre_sports": "Night Lurker Sports",
        "m_genre_supernatural": "Dark Chapter",
        "m_genre_thriller": "Cid's Dash Thriller",
        "m_genre_psychological": "Mind of Cid",
        "m_genre_isekai": "Shadow Blitz Isekai",
        "m_genre_shounen": "Shadow Circle Shounen",
        "m_genre_ecchi": "Shadow Art Ecchi",
        "m_genre_mahou_shoujo": "Shadow Chain Magic Shoujo",
        "m_genre_mecha": "Shadow Vault Mecha",
        "m_genre_music": "All Shadows Music",
        "m_tag_isekai_new": "Cult Fear Isekai New",
        "m_tag_harem": "Shadow Garden Hq Harem",
        "m_tag_bl": "Cid Kagenou Bl",
        "m_tag_gl": "Shadow Archive Gl",
        "m_tag_historical": "Ancient Vault Historical",
        "m_tag_military": "Shadow Circle Military",
        "m_tag_school": "Shadow Review School",
        "m_tag_martial_arts": "Daily Shadow Martial Arts",
        "m_tag_vampire": "Night Lurker Vampire",
        "m_tag_samurai": "Cult Registry Samurai",
        "m_tag_space": "Cid Kagenou Space",
        "m_tag_parody": "Shadow Vault Parody",
        "m_tag_idol": "Cid Kagenou Idol",
        "m_tag_post_apocalyptic": "Shadow Arsenal Post Apocalyptic",
        "m_tag_cyberpunk": "Shadow Garden Hq Cyberpunk",
        "m_tag_shoujo": "Cid's Mind Shoujo",
        "m_tag_survival": "Shadow Chain Survival",
        "m_tag_cooking": "The Eminence In Shadow Cooking",
        "m_tag_medical": "Shadow Critic Medical",
        "m_tag_villainess": "Perfect Plan Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Dossier",
        "m_mega_completionist": "Shadow Expert",
        "m_completion_rate_50": "Cid Kagenou Return",
        "m_completion_rate_75": "Cid's Dash Ascension",
        "m_completion_rate_90": "Shadow Expert Resolution",
        "m_no_drop": "Cult Intel Decree",
        "m_long_runner_complete": "Lost Shadows Clear",
        "m_sequel_chain": "All Shadows Seal Seal",
        "m_clean_list": "Decade Shadow Relic Relic",
        "m_from_ptr": "Cid's Mind Watchlist",
        "m_reread_master": "Action Shadow Trial Trial",
        "m_oneshot_complete": "Action Shadow Ascension",
        "m_same_day_start_finish": "Iron Shadow Crown Crown",
        "m_revival": "Lost Shadows Accord",
        "m_zero_to_hundred": "Shadow Modules Banner",
        "m_five_genre_complete": "Ancient Texts M Five Genre",
        "m_full_collection": "Iron Shadow Proof Proof",
        "m_batch_complete": "Shadow Artist Summit",
        "m_paused_to_done": "Shadow Expert Standard Standard",
        "m_completion_spree": "Shadow Ops Triumph",
        "m_format_completionist": "Action Shadow Completion",
        "m_catch_up": "Shadow Garden Chronicle",
        "m_multi_reread": "Cult Intel Banner",
        "m_dropped_recovery": "Shadow Art Conquest",
        "m_ten_perfect_scores": "Perfect Plan Judgment",
        "m_complete_genre_span": "Shadow Blitz M Complete Genre",
        "m_monthly_completions": "Mind Cid Return",
        "m_yearly_completions": "Shadow Blitz Epilogue",
        "m_rapid_complete": "Shadow Streak Finale",
        "m_author_complete": "Shadow Review Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Devoted Shadow",
        "m_mangaka_lover": "Shadow Artist",
        "m_rereader": "Second Recon",
        "m_triple_reread": "Ancient Evil Testament Testament",
        "m_annual_reread": "Shadow Modules Banner Banner",
        "m_publisher_fan": "Shadow Ops Mark",
        "m_artist_fan": "All Shadows Insignia",
        "m_adaptation_compare": "Cid's Dash Pinnacle",
        "m_source_material_fan": "Manga First",
        "m_waiting_weekly": "Cult Registry Streak",
        "m_classic_reader": "Shadow Vault Lantern",
        "m_saga_reader": "Shadow Arsenal Decree",
        "m_genre_loyalty": "Shadow Art Loyalty",
        "m_decade_reader": "Shadow Palette Warrant",
        "m_ln_adaptation": "Shadow Palette Mark",
        "m_original_work": "Night Lurker Standard",
        "m_long_commitment": "Shadow Art Mark",
        "m_up_to_date": "Night Stalker Warrant Warrant",
        "m_favorite_mangaka": "Beta Shadow Treasury",
        "m_complete_portfolio": "Shadow Ops Triumph Triumph",
        "m_franchise_collector": "Shadow Garden Archive",
        "m_serialization_follower": "Beta Shadow Handshake",
        "m_genre_master": "Decade Shadow Master",
        "m_multi_series_author": "Shadow Arsenal Insignia Insignia",
        "m_format_diversity": "Night Lurker Shelf",
        "m_year_dedication": "Dawn Phantom Tenure",
        "m_ongoing_follower": "Shadow Palette Fellowship",
        "m_genre_loyalty_50": "Shadow Archive Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Shadow Action Explorer",
        "m_publisher_hopper": "Shadow Ops Mantle",
        "m_tag_explorer": "Cult Alerts Explorer",
        "m_decade_hopper": "Cid's Mind Chronicle Chronicle",
        "m_hidden_gem": "Hidden Chapter",
        "m_popular_taste": "Shadow Artist Record Record",
        "m_retro_reader": "Shadow Artist Accord",
        "m_modern_reader": "Ancient Vault Seal Seal",
        "m_cross_demographic": "Shadow Elder Crown",
        "m_underdog_fan": "Shadow Artist Accord Accord",
        "m_variety_week": "All Shadows Horizon Horizon",
        "m_manhwa_reader": "Shadow Master Proof",
        "m_manhua_reader": "Shadow Vault Mantle Mantle",
        "m_classic_connoisseur": "Winter Shadow Glimpse",
        "m_award_winner": "Dawn Phantom Warrant",
        "m_niche_explorer": "The Eminence In Shadow Horizon",
        "m_world_manga": "Shadow Garden Chronicle Chronicle",
        "m_cult_classic": "Cult Chapter",
        "m_random_pick": "Shadow Artist Standard",
        "m_new_genre_month": "Shadow Garden M New Genre",
        "m_year_completionist": "Daily Shadow Fulfillment",
        "m_unpopular_opinion": "Night Stalker Trial",
        "m_top_rated_reader": "The Eminence In Shadow Record",
        "m_source_variety": "Shadow Vault Catalogue",
        "m_low_score_brave": "Daily Shadow Score",
        "m_short_manga_explorer": "Ancient Vault Compass",
        "m_long_manga_explorer": "Shadow Modules Survey",
        "m_serialization_explorer": "Cid's Dash Road",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Cid Kagenou Ledger",
        "m_commute_reader": "Shadow Critic Tenure Tenure",
        "m_four_am_club": "Shadow Ops Fellowship",
        "m_new_year_read": "All Shadows Pact",
        "m_all_hours": "Cid's Mind Accord Accord",
        "m_prime_time_reader": "Night Lurker Banner",
        "m_workday_reader": "Lost Shadows Accord Accord",
        "m_sunday_read": "Cid Kagenou Standard Standard",
        "m_morning_routine": "Lost Shadows Discipline",
        "m_night_shift_reader": "Shadow Review Accord Accord",
        "m_seasonal_premier_read": "Shadow Vault Seasonal",
        "m_clock_collector": "Shadow Drama Reserve",
        "m_late_night_horror": "Ancient Texts Mark Mark",
        "m_afternoon_reader": "Dawn Phantom Mantle Mantle",
        "m_golden_hour_reader": "Ancient Evil Observance",
        "m_dawn_reader": "Cult Alerts Mantle",
        "m_twilight_reader": "Shadow Palette Crown",
        "m_midnight_start": "Night Lurker Routine",
        "m_weekend_binge_hours": "Perfect Plan Momentum",
        "m_late_night_regular": "Cid Kagenou Accord",
        "m_sunrise_reader": "Shadow Garden Hq Mantle",
        "m_every_day_of_week": "Shadow Vault Warrant Warrant",
        "m_monthly_hours": "Shadow Action Vigil",
        "m_bedtime_reader": "Daily Shadow Warrant Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Shadow Art",
        "m_webtoon_reader": "Shadow Palette Mark Mark",
        "m_full_color": "All Shadows Accord",
        "m_doujin_reader": "Shadow Expert Record Record",
        "m_anthology_reader": "Perfect Plan Accord",
        "m_adaptation_reader": "Shadow Artist Banner",
        "m_longstrip_reader": "Ancient Evil Trial",
        "m_4koma_reader": "Cult Registry Ledger",
        "m_oneshot_reader": "Shadow Blitz Mantle",
        "m_format_variety": "Shadow Ops Gallery",
        "m_light_novel_reader": "Cid's Mind Insignia",
        "m_novel_reader": "Daily Shadow Crown",
        "m_visual_storyteller": "Dawn Phantom Testament",
        "m_colored_classic": "Shadow World Survey",
        "m_webcomic_fan": "Winter Shadow Insignia",
        "m_manga_to_anime": "Adapted Shadow",
        "m_seinen_reader": "Shadow Art Pinnacle",
        "m_josei_reader": "Shadow Garden Hq Pinnacle",
        "m_award_winning_art": "Shadow Circle Relic",
        "m_debut_work": "Shadow Circle Dominion",
        "m_vertical_scroll": "Shadow Arsenal Decree Decree",
        "m_traditional_format": "The Eminence In Shadow Hoard",
        "m_cross_media": "Ancient Vault Accord",
        "m_spinoff_reader": "Shadow Garden Accord",
        "m_remake_reader": "Action Shadow Pinnacle",
        "m_collaboration_reader": "Winter Shadow Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Shadow Streak",
        "m_weekly_warrior": "Cid's Dash Season",
        "m_monthly_reader": "All Night Discipline",
        "m_comeback": "Shadow Modules Standard Standard",
        "m_weekend_streak": "Shadow Garden Hq Fever",
        "m_no_zero_days": "Shadow Master Proof Proof",
        "m_iron_will": "Iron Shadow",
        "m_habit_formed": "Shadow Elder Crown Crown",
        "m_consistent_pace": "Iron Shadow Scrutiny Scrutiny",
        "m_year_long": "Year in Darkness",
        "m_double_streak": "Shadow Blitz Resolve",
        "m_streak_recovery": "Decade Shadow Resolve",
        "m_daily_minimum": "Shadow Drama Focus",
        "m_winter_streak": "Ancient Evil Observance Observance",
        "m_summer_streak": "Shadow Circle Observance",
        "m_morning_streak": "Shadow Action Clock",
        "m_night_streak": "The Eminence In Shadow Discipline",
        "m_unbreakable": "Shadow Garden Hq Warrant",
        "m_eternal_flame": "Shadow Chain Record",
        "m_chapter_a_day": "Cid Kagenou Ledger Ledger",
        "m_genre_streak": "Cult Alerts Streak",
        "m_completion_streak": "Shadow Artist Return",
        "m_rating_streak": "Cult Alerts Appraisal",
        "m_multi_ch_streak": "Cid's Dash Tenure",
        "m_author_streak": "Shadow Drama Calendar",
        "m_perfect_week_manga": "Shadow Garden Accord Accord",
        "m_diverse_streak": "Cult Intel Streak",

        // ── MANGA SCORING ──
        "m_critic": "Shadow Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_harsh_critic": "Cid's Mind Scale",
        "m_fair_judge": "Cult Fear Eye Eye",
        "m_generous_spirit": "Perfect Plan Decree",
        "m_score_all": "Shadow Palette Reckoning",
        "m_wide_range": "All Night Ledger Ledger",
        "m_controversial": "Mind Cid Standard Standard",
        "m_consistent_scorer": "Shadow Expert Grade",
        "m_score_sniper": "Night Stalker Reckoning",
        "m_evolving_taste": "Shadow Blitz Trial Trial",
        "m_bell_curve": "All Night Accord",
        "m_picky_reader": "Cult Intel Ledger",
        "m_100_rated": "All Night Standard",
        "m_500_rated": "Shadow Review Aegis",
        "m_mediocre_majority": "Shadow Blitz Canon",
        "m_rating_spree": "Shadow Action Verdict",
        "m_score_variance": "Daily Shadow Measure",
        "m_binge_rater": "Shadow Drama Passage",
        "m_reread_rerate": "Shadow World Banner Banner",
        "m_masterpiece_hunter": "Mind Cid Banner",
        "m_contrarian": "Shadow Artist Aegis",
        "m_optimist": "Ancient Vault Accord Accord",
        "m_score_distributor": "Cid's Dash Balance",
        "m_genre_critic": "Shadow Drama Critic",
        "m_mean_above_8": "Daily Shadow Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Dawn Phantom Season",
        "m_valentines_read": "Cult Alerts Observance",
        "m_pi_day": "Shadow Blitz Testament Testament",
        "m_april_fools": "Night Stalker Devotion",
        "m_international_manga_day": "Cid's Mind Aegis",
        "m_free_comic_day": "Perfect Plan Chronicle",
        "m_summer_solstice": "Shadow Streak Focus Focus",
        "m_tanabata": "Iron Shadow Tanabata",
        "m_friday_13th": "Action Shadow Dominion Dominion",
        "m_halloween_read": "Ancient Texts Halloween",
        "m_thanksgiving_binge": "Shadow Garden Charge",
        "m_christmas_read": "Lost Shadows Pact",
        "m_new_years_eve": "Shadow Streak Pilgrimage",
        "m_birthday_read": "Shadow Art Focus",
        "m_holiday_marathon": "Beta Shadow Rally",
        "m_independence_day": "Shadow Artist Aegis Aegis",
        "m_culture_day": "Shadow Review Seal Seal",
        "m_spring_equinox": "Ancient Texts Dominion",
        "m_earth_day": "Shadow Art Trial",
        "m_labor_day": "Lost Shadows Seal",
        "m_winter_solstice": "Shadow Elder Focus Focus",
        "m_manga_birthday": "Iron Shadow Ritual",
        "m_every_holiday_reader": "Decade Shadow Watch",
        "m_consecutive_holidays": "Action Shadow Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Loyal Shadow Aegis",
        "m_fibonacci": "Shadow Critic Dominion",
        "m_palindrome_day": "Shadow Blitz Relic",
        "m_binary_day": "Shadow Elder Proof",
        "m_full_moon_read": "Shadow Garden Hq Crown",
        "m_leap_year_read": "Cult Intel Practice",
        "m_triple_seven": "Cult Fear Trial Trial",
        "m_thousand_complete": "Cult Fear Ascension",
        "m_nice": "Shadow Arsenal Seal Seal",
        "m_power_level_chapters": "Shadow Modules Aegis",
        "m_answer_42": "Shadow Garden Hq Trial",
        "m_square_number": "Shadow Chain Standard",
        "m_prime_count": "Cult Fear Pinnacle",
        "m_matching_date": "Decade Shadow Mantle",
        "m_century_chapter": "Loyal Shadow Decree",
        "m_pi_chapters": "Shadow Art Proof Proof",
        "m_synchronicity": "Cult Alerts Emblem",
        "m_world_record": "Shadow Master Warrant",
        "m_genre_clash": "Night Lurker Clash",
        "m_time_traveler": "Shadow Expert Decree",
        "m_double_digits": "Shadow Vault Dominion",
        "m_one_two_three": "Winter Shadow Banner Banner",
        "m_lucky_seven": "Cid's Dash Mantle Mantle",
        "m_exact_hundred_ch": "Shadow Critic Legend",
        "m_year_match_count": "Cult Registry Routine",
        "m_chapter_match_date": "Shadow Elder Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Shadow Vault Index",
        "m_manhwa_format": "Ancient Texts Gallery",
        "m_manhua_format": "Ancient Evil Storehouse",
        "m_ln_format": "Cult Fear Index",
        "m_oneshot_format": "Shadow Blitz Index",
        "m_doujin_format": "Shadow Action Cabinet",
        "m_novel_format": "Night Stalker Reserve Reserve",
        "m_format_master_manga": "Shadow Action Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Shadow Expert Link",
        "m_meta_collector": "Shadow Review Reliquary",
        "m_meta_category_starter": "Shadow Ops Standard",
        "m_meta_tier_climber": "Ancient Vault Token",
        "m_meta_tier_max": "Shadow Complete",
        "m_meta_xp_earner": "Shadow Vault Anchor",
        "m_meta_difficulty_easy": "Cult Fear Panel",
        "m_meta_difficulty_hard": "Dawn Phantom Node",
        "m_meta_unlock_spree": "Shadow Vault Marker",
        "m_meta_completionist": "Full Library",
        "m_meta_diverse": "Shadow Blitz Anchor",
        "m_meta_dominator": "Shadow Arsenal Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#010004",
        primary: "#6030bc",
        secondary: "#4418a0",
        accent: "#d0a010",
    },
    particleColor: "#8060d8",
    backgroundDim: 0.32,
    backgroundBlur: 20,
    particleTypes: {
        shadow_wisps: { label: "Shadow Wisps", maxCount: 14, defaultEnabled: true, defaultIntensity: 50 },
        purple_sparks: { label: "Purple Sparks", maxCount: 10, defaultEnabled: true, defaultIntensity: 38 },
    },
    milestoneNames: {
  1: "Threadbare Generic Rank Spark",
  8: "Generic's Tarnished Omen",
  14: "Fractured Generic Rank",
  21: "Generic Rank Path",
  28: "Lowborn Legacy Myth",
  35: "Generic Rank Pulse",
  41: "Generic's Legacy Crest",
  48: "Humble Generic Mark",
  55: "Ragged Generic Rank Vow",
  61: "Generic's Faint Echo",
  68: "Lesser Generic Rank",
  75: "Generic Rank Zenith",
  81: "Doubtful Legacy Bloom",
  88: "Generic Rank Sigil",
  95: "Generic's Legacy Flame",
  102: "Really Cool Generic Spark",
  108: "Awakened Generic Rank Omen",
  115: "Generic's Resolute Seal",
  122: "Rising Generic Rank",
  128: "Generic Rank Myth",
  135: "Dauntless Legacy Pulse",
  142: "Generic Rank Crest",
  149: "Generic's Legacy Mark",
  155: "Fresh Generic Vow",
  162: "Valiant Generic Rank Echo",
  169: "Generic's Prime Crown",
  175: "Polished Generic Rank",
  182: "Generic Rank Bloom",
  189: "Stormlit Legacy Sigil",
  195: "Generic Rank Flame",
  202: "Generic's Legacy Spark",
  209: "Tempered Generic Omen",
  216: "Trusted Generic Rank Seal",
  222: "Generic's Steadfast Path",
  229: "Ironclad Generic Rank",
  236: "Veteran Legacy Pulse",
  242: "Core Legacy Crest",
  249: "Generic Rank Mark",
  256: "Generic's Legacy Vow",
  262: "Formidable Generic Echo",
  269: "Lucid Generic Rank Crown",
  276: "Generic's Ranked Zenith",
  283: "Fabled Generic Rank",
  289: "Grand Legacy Sigil",
  296: "Seasoned Legacy Flame",
  303: "Generic Rank Spark",
  309: "Generic's Legacy Omen",
  316: "Valorous Generic Seal",
  323: "Stalwart Generic Rank Path",
  330: "Generic's Commanding Myth",
  336: "Refined Generic Rank",
  343: "Unbroken Legacy Crest",
  350: "Blazing Legacy Mark",
  356: "Generic Rank Vow",
  363: "Generic's Legacy Echo",
  370: "Peerless Generic Crown",
  376: "Ardent Generic Rank Zenith",
  383: "Generic's Focused Bloom",
  390: "Vigilant Generic Rank",
  397: "Dominant Legacy Flame",
  403: "Elite Legacy Spark",
  410: "Generic Rank Omen",
  417: "Generic's Legacy Seal",
  423: "Sovereign Generic Path",
  430: "Regal Generic Rank Myth",
  437: "Generic's Crowned Pulse",
  444: "Mythborn Generic Rank",
  450: "Limitless Legacy Mark",
  457: "Radiant Legacy Vow",
  464: "Generic Rank Echo",
  470: "Generic's Legacy Crown",
  477: "Climactic Generic Zenith",
  484: "Epic Generic Rank Bloom",
  490: "Generic's Unreal Sigil",
  497: "Peak Generic Rank",
  504: "Supreme Legacy Spark",
  511: "Exalted Legacy Omen",
  517: "Generic Rank Seal",
  524: "Generic's Legacy Path",
  531: "Celestial Generic Myth",
  537: "Phantom Generic Rank Pulse",
  544: "Generic's Crimson Crest",
  551: "Silver Generic Rank",
  557: "Golden Legacy Vow",
  564: "Feral Legacy Echo",
  571: "Generic Rank Crown",
  578: "Generic's Legacy Zenith",
  584: "Dread Generic Bloom",
  591: "Luminous Generic Rank Sigil",
  598: "Generic's Thunderous Flame",
  604: "Ultraviolet Generic Rank",
  611: "Unleashed Legacy Omen",
  618: "Secret Legacy Seal",
  625: "Final Generic Path",
  631: "Generic's Legacy Myth",
  638: "Worldclass Generic Pulse",
  645: "Lawless Generic Rank Crest",
  651: "Generic's Chosen Mark",
  658: "Fearless Generic Rank",
  665: "Overdrive Legacy Echo",
  671: "Cinematic Legacy Crown",
  678: "Impossible Generic Zenith",
  685: "Generic's Legacy Bloom",
  692: "Canonized Generic Sigil",
  698: "Ascendant Generic Rank Flame",
  705: "Generic's Transfigured Spark",
  712: "Immortal Generic Rank",
  718: "Eclipsed Legacy Seal",
  725: "Astral Legacy Path",
  732: "Sublime Generic Myth",
  739: "Generic's Legacy Pulse",
  745: "Prismatic Generic Crest",
  752: "Abyssal Generic Rank Mark",
  759: "Generic's Unbound Vow",
  765: "Eternal Generic Rank",
  772: "Cosmic Legacy Crown",
  779: "Transcendent Legacy Zenith",
  785: "Perfected Generic Bloom",
  792: "Generic's Legacy Sigil",
  799: "Ultimate Generic Flame",
  806: "Mythic Generic Rank Spark",
  812: "Generic's Godlike Omen",
  819: "Canonical Generic Rank",
  826: "Reality-Bent Legacy Path",
  832: "Heavenly Legacy Myth",
  839: "Absolute Generic Pulse",
  846: "Untouchable Generic Crest",
  852: "Timeless Generic Mark",
  859: "Empyrean Generic Rank Vow",
  866: "Generic's Primordial Echo",
  873: "Omniscient Generic Rank",
  879: "Unfathomed Legacy Zenith",
  886: "Apocalyptic Legacy Bloom",
  893: "Seraphic Generic Sigil",
  899: "Omega Generic Flame",
  906: "Final Generic Spark",
  913: "Crowned Generic Rank Omen",
  920: "Generic's Mythic Seal",
  926: "Absolute Generic Rank",
  933: "Eternal Legacy Myth",
  940: "Cosmic Legacy Pulse",
  946: "Transcendent Generic Crest",
  953: "Perfected Generic Mark",
  960: "Definitive Generic Vow",
  966: "Ultimate Generic Rank Echo",
  973: "Generic's Infinite Crown",
  980: "Sovereign Generic Rank",
  987: "Celestial Legacy Bloom",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate Generic Rank"
},
}
