import { AnimeThemeConfig } from "./types"
import { GiNinjaHead, GiDaggers, GiShadowGrasp, GiCrown, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiDramaMasks, GiHeartKey, GiBroadsword } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const theEminenceInShadowTheme: AnimeThemeConfig = {
    id: "the-eminence-in-shadow",
    displayName: "The Eminence in Shadow",
    description: "Reincarnated as Cid Kagenou, a boy obsessed with becoming an all-powerful shadowy mastermind, he creates a fictional organisation called Shadow Garden — only to discover it's fighting a real ancient evil.",
    fontFamily: "'Cinzel', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "200 168 255",
        "--color-brand-300": "162 120 240",
        "--color-brand-400": "128 80 218",
        "--color-brand-500": "96 48 188",
        "--color-brand-600": "68 24 160",
        "--color-brand-700": "46 10 128",
        "--color-brand-800": "30 4 92",
        "--color-brand-900": "16 0 56",
        "--color-brand-950": "6 0 24",
        "--brand": "96 48 188",
        "--background": "#010004",
        "--paper": "#06000e",
        "--color-gray-950": "1 0 4",
        "--color-gray-900": "6 2 12",
        "--color-gray-800": "14 6 26",
        "--color-gray-700": "26 12 46",
        "--color-gray-600": "44 22 74",
        "--color-gray-500": "72 40 115",
        "--color-gray-400": "108 70 158",
        "--color-gray-300": "150 108 200",
        "--color-gray-200": "190 155 232",
        "--color-gray-100": "220 195 248",
        "--color-gray-50": "244 232 255",
    },
    sidebarOverrides: {
        "home": { icon: GiShadowGrasp, label: "Shadow Garden HQ" },
        "schedule": { icon: GiAlarmClock, label: "Operation Schedule" },
        "manga": { icon: LuBookOpen, label: "Ancient Texts" },
        "lists": { icon: GiFlowerEmblem, label: "Cult Registry" },
        "discover": { icon: GiBullseye, label: "New Targets" },
        "torrent-list": { icon: GiDaggers, label: "Shadow Arsenal" },
        "debrid": { icon: GiDramaMasks, label: "Shadow Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Shadows" },
        "enmasse": { icon: GiResize, label: "Shadow Ops" },
        "scan-summaries": { icon: TbReportSearch, label: "Op Reports" },
        "auto-downloader": { icon: LuRss, label: "Cult Intel" },
        "community": { icon: GiNinjaHead, label: "Shadow Circle" },
        "achievements": { icon: GiTrophy, label: "Shadow Trophies" },
        "milestones": { icon: LuFlag, label: "Shadow Milestones" },
        "search": { icon: FiSearch, label: "Shadow Search" },
        "notifications": { icon: LuBell, label: "Cult Alerts" },
        "theme-manager": { icon: GiPalette, label: "Shadow Palette" },
        "extensions": { icon: BiExtension, label: "Shadow Modules" },
        "sync": { icon: IoCloudOfflineOutline, label: "Shadow Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Cid's Config" },
    },
    achievementNames: {
        "a_first_episode": "First Infiltration",
        "a_first_complete": "Shadow Revealed",
        "a_hundred_club": "Hundred Shadows",
        "a_time_lord": "Shadow Elder",
        "a_anime_collector": "Shadow Archive",
        "a_library_legend": "Ancient Vault",
        "a_binge_king": "Shadow Marathon",
        "a_no_sleep": "All-Night Lurker",
        "a_marathon_runner": "Cid's Dash",
        "a_speed_run": "Shadow Blitz",
        "a_completionist": "Full Operation",
        "a_mega_completionist": "Shadow Master",
        "a_loyal_fan": "Loyal Shadow",
        "a_rewatcher": "Replay Infiltration",
        "a_decade_watcher": "Decade in Shadow",
        "a_genre_action": "Shadow Action",
        "a_genre_adventure": "Shadow Journey",
        "a_genre_comedy": "Accidental Genius",
        "a_genre_drama": "Shadow Drama",
        "a_genre_fantasy": "Shadow World",
        "a_genre_horror": "Cult Fear",
        "a_genre_romance": "None Here",
        "a_genre_scifi": "None Here",
        "a_genre_supernatural": "Ancient Evil",
        "a_genre_psychological": "Cid's Mind",
        "a_genre_mecha": "None Here",
        "a_critic": "Shadow Critic",
        "a_perfect_ten": "Perfect Plan",
        "a_harsh_critic": "Shadow Standard",
        "a_daily_streak": "Daily Shadow",
        "a_mega_streak": "Eternal Shadow",
        "a_year_long": "Year in Darkness",
        "a_iron_will": "Unyielding Shadow",
        "a_hidden_gem": "Hidden Darkness",
        "a_cult_classic": "Shadow Classic",
        "a_classic_connoisseur": "2022 Fan",
        "a_new_years_resolution": "New Year Dark",
        "a_christmas_special": "Winter Shadow",
        "a_meta_tier_max": "True Eminence",
        "a_meta_completionist": "All Shadows",
        "a_sequel_chain": "Shadow Chain",
        "a_zero_to_hero": "Beta to Shadow",
        "a_night_owl": "Night Stalker",
        "a_early_bird": "Dawn Phantom",
        "m_first_chapter": "First Shadow",
        "m_first_complete": "Op Complete",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Shadow Reading",
        "m_completionist": "Full Dossier",
        "m_mega_completionist": "Shadow Expert",
        "m_loyal_reader": "Devoted Shadow",
        "m_rereader": "Second Recon",
        "m_genre_action": "Action Shadow",
        "m_genre_adventure": "Stealth Chapter",
        "m_genre_romance": "None Here",
        "m_genre_fantasy": "Ancient Chapter",
        "m_genre_horror": "Cult Chapter",
        "m_genre_drama": "Shadow Drama",
        "m_genre_scifi": "None Here",
        "m_genre_supernatural": "Dark Chapter",
        "m_genre_psychological": "Mind of Cid",
        "m_critic": "Shadow Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Shadow Streak",
        "m_year_long": "Year in Darkness",
        "m_iron_will": "Iron Shadow",
        "m_hidden_gem": "Hidden Chapter",
        "m_cult_classic": "Cult Chapter",
        "m_mangaka_lover": "Shadow Artist",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Shadow Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Shadow Art",
        "m_manga_to_anime": "Adapted Shadow",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#010004",
        primary: "#6030bc",
        secondary: "#4418a0",
        accent: "#d0a010",
    },
    particleColor: "#8060d8",
    backgroundDim: 0.32,
    backgroundBlur: 20,
    particleTypes: {
        shadow_wisps: { label: "Shadow Wisps", maxCount: 14, defaultEnabled: true, defaultIntensity: 50 },
        purple_sparks: { label: "Purple Sparks", maxCount: 10, defaultEnabled: true, defaultIntensity: 38 },
    },
    milestoneNames: {
    "7": "Novice Rank 1",
    "13": "Novice Level 2",
    "20": "Novice Tier 3",
    "27": "Novice Class 4",
    "33": "Novice Grade 5",
    "40": "Novice Position 6",
    "47": "Novice Status 7",
    "53": "Novice Role 8",
    "60": "Novice Title 9",
    "67": "Novice Authority 10",
    "73": "Beginner Rank 11",
    "80": "Beginner Level 12",
    "87": "Beginner Tier 13",
    "93": "Beginner Class 14",
    "100": "Beginner Grade 15",
    "107": "Beginner Position 16",
    "113": "Beginner Status 17",
    "120": "Beginner Role 18",
    "127": "Beginner Title 19",
    "133": "Student Authority 20",
    "140": "Student Rank 21",
    "147": "Student Level 22",
    "153": "Student Tier 23",
    "160": "Student Class 24",
    "167": "Student Grade 25",
    "173": "Student Position 26",
    "180": "Student Status 27",
    "187": "Student Role 28",
    "193": "Student Title 29",
    "200": "Learner Authority 30",
    "207": "Learner Rank 31",
    "213": "Learner Level 32",
    "220": "Learner Tier 33",
    "227": "Learner Class 34",
    "233": "Learner Grade 35",
    "240": "Learner Position 36",
    "247": "Learner Status 37",
    "253": "Learner Role 38",
    "260": "Adept Title 39",
    "267": "Adept Authority 40",
    "273": "Adept Rank 41",
    "280": "Adept Level 42",
    "287": "Adept Tier 43",
    "293": "Adept Class 44",
    "300": "Adept Grade 45",
    "307": "Adept Position 46",
    "313": "Adept Status 47",
    "320": "Expert Role 48",
    "327": "Expert Title 49",
    "333": "Expert Authority 50",
    "340": "Expert Rank 51",
    "347": "Expert Level 52",
    "353": "Expert Tier 53",
    "360": "Expert Class 54",
    "367": "Expert Grade 55",
    "373": "Expert Position 56",
    "380": "Expert Status 57",
    "387": "Master Role 58",
    "393": "Master Title 59",
    "400": "Master Authority 60",
    "407": "Master Rank 61",
    "413": "Master Level 62",
    "420": "Master Tier 63",
    "427": "Master Class 64",
    "433": "Master Grade 65",
    "440": "Master Position 66",
    "447": "Grandmaster Status 67",
    "453": "Grandmaster Role 68",
    "460": "Grandmaster Title 69",
    "467": "Grandmaster Authority 70",
    "473": "Grandmaster Rank 71",
    "480": "Grandmaster Level 72",
    "487": "Grandmaster Tier 73",
    "493": "Grandmaster Class 74",
    "500": "Grandmaster Grade 75",
    "507": "Sage Position 76",
    "513": "Sage Status 77",
    "520": "Sage Role 78",
    "527": "Sage Title 79",
    "533": "Sage Authority 80",
    "540": "Sage Rank 81",
    "547": "Sage Level 82",
    "553": "Sage Tier 83",
    "560": "Sage Class 84",
    "567": "Sage Grade 85",
    "573": "Legend Position 86",
    "580": "Legend Status 87",
    "587": "Legend Role 88",
    "593": "Legend Title 89",
    "600": "Legend Authority 90",
    "607": "Legend Rank 91",
    "613": "Legend Level 92",
    "620": "Legend Tier 93",
    "627": "Legend Class 94",
    "633": "Mythical Grade 95",
    "640": "Mythical Position 96",
    "647": "Mythical Status 97",
    "653": "Mythical Role 98",
    "660": "Mythical Title 99",
    "667": "Mythical Authority 100",
    "673": "Mythical Rank 101",
    "680": "Mythical Level 102",
    "687": "Mythical Tier 103",
    "693": "Mythical Class 104",
    "700": "Godly Grade 105",
    "707": "Godly Position 106",
    "713": "Godly Status 107",
    "720": "Godly Role 108",
    "727": "Godly Title 109",
    "733": "Godly Authority 110",
    "740": "Godly Rank 111",
    "747": "Godly Level 112",
    "753": "Godly Tier 113",
    "760": "Supreme Class 114",
    "767": "Supreme Grade 115",
    "773": "Supreme Position 116",
    "780": "Supreme Status 117",
    "787": "Supreme Role 118",
    "793": "Supreme Title 119",
    "800": "Supreme Authority 120",
    "807": "Supreme Rank 121",
    "813": "Supreme Level 122",
    "820": "Infinite Tier 123",
    "827": "Infinite Class 124",
    "833": "Infinite Grade 125",
    "840": "Infinite Position 126",
    "847": "Infinite Status 127",
    "853": "Infinite Role 128",
    "860": "Infinite Title 129",
    "867": "Infinite Authority 130",
    "873": "Infinite Rank 131",
    "880": "Infinite Level 132",
    "887": "Eternal Tier 133",
    "893": "Eternal Class 134",
    "900": "Eternal Grade 135",
    "907": "Eternal Position 136",
    "913": "Eternal Status 137",
    "920": "Eternal Role 138",
    "927": "Eternal Title 139",
    "933": "Eternal Authority 140",
    "940": "Eternal Rank 141",
    "947": "Transcendent Level 142",
    "953": "Transcendent Tier 143",
    "960": "Transcendent Class 144",
    "967": "Transcendent Grade 145",
    "973": "Transcendent Position 146",
    "980": "Transcendent Status 147",
    "987": "Transcendent Role 148",
    "993": "Transcendent Title 149",
    "1000": "Transcendent Authority 150"
},
}
