import { AnimeThemeConfig } from "./types"
import { GiNinjaHead, GiDaggers, GiShadowGrasp, GiCrown, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiDramaMasks, GiHeartKey, GiBroadsword } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const theEminenceInShadowTheme: AnimeThemeConfig = {
    id: "the-eminence-in-shadow",
    displayName: "The Eminence in Shadow",
    description: "Reincarnated as Cid Kagenou, a boy obsessed with becoming an all-powerful shadowy mastermind, he creates a fictional organisation called Shadow Garden — only to discover it's fighting a real ancient evil.",
    fontFamily: "'Cinzel', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "200 168 255",
        "--color-brand-300": "162 120 240",
        "--color-brand-400": "128 80 218",
        "--color-brand-500": "96 48 188",
        "--color-brand-600": "68 24 160",
        "--color-brand-700": "46 10 128",
        "--color-brand-800": "30 4 92",
        "--color-brand-900": "16 0 56",
        "--color-brand-950": "6 0 24",
        "--brand": "96 48 188",
        "--background": "#010004",
        "--paper": "#06000e",
        "--color-gray-950": "1 0 4",
        "--color-gray-900": "6 2 12",
        "--color-gray-800": "14 6 26",
        "--color-gray-700": "26 12 46",
        "--color-gray-600": "44 22 74",
        "--color-gray-500": "72 40 115",
        "--color-gray-400": "108 70 158",
        "--color-gray-300": "150 108 200",
        "--color-gray-200": "190 155 232",
        "--color-gray-100": "220 195 248",
        "--color-gray-50": "244 232 255",
    },
    sidebarOverrides: {
        "home": { icon: GiShadowGrasp, label: "Shadow Garden HQ" },
        "schedule": { icon: GiAlarmClock, label: "Operation Schedule" },
        "manga": { icon: LuBookOpen, label: "Ancient Texts" },
        "lists": { icon: GiFlowerEmblem, label: "Cult Registry" },
        "discover": { icon: GiBullseye, label: "New Targets" },
        "torrent-list": { icon: GiDaggers, label: "Shadow Arsenal" },
        "debrid": { icon: GiDramaMasks, label: "Shadow Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Shadows" },
        "enmasse": { icon: GiResize, label: "Shadow Ops" },
        "scan-summaries": { icon: TbReportSearch, label: "Op Reports" },
        "auto-downloader": { icon: LuRss, label: "Cult Intel" },
        "community": { icon: GiNinjaHead, label: "Shadow Circle" },
        "achievements": { icon: GiTrophy, label: "Shadow Trophies" },
        "milestones": { icon: LuFlag, label: "Shadow Milestones" },
        "search": { icon: FiSearch, label: "Shadow Search" },
        "notifications": { icon: LuBell, label: "Cult Alerts" },
        "theme-manager": { icon: GiPalette, label: "Shadow Palette" },
        "extensions": { icon: BiExtension, label: "Shadow Modules" },
        "sync": { icon: IoCloudOfflineOutline, label: "Shadow Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Cid's Config" },
    },
    achievementNames: {
        "a_first_episode": "First Infiltration",
        "a_first_complete": "Shadow Revealed",
        "a_hundred_club": "Hundred Shadows",
        "a_time_lord": "Shadow Elder",
        "a_anime_collector": "Shadow Archive",
        "a_library_legend": "Ancient Vault",
        "a_binge_king": "Shadow Marathon",
        "a_no_sleep": "All-Night Lurker",
        "a_marathon_runner": "Cid's Dash",
        "a_speed_run": "Shadow Blitz",
        "a_completionist": "Full Operation",
        "a_mega_completionist": "Shadow Master",
        "a_loyal_fan": "Loyal Shadow",
        "a_rewatcher": "Replay Infiltration",
        "a_decade_watcher": "Decade in Shadow",
        "a_genre_action": "Shadow Action",
        "a_genre_adventure": "Shadow Journey",
        "a_genre_comedy": "Accidental Genius",
        "a_genre_drama": "Shadow Drama",
        "a_genre_fantasy": "Shadow World",
        "a_genre_horror": "Cult Fear",
        "a_genre_romance": "None Here",
        "a_genre_scifi": "None Here",
        "a_genre_supernatural": "Ancient Evil",
        "a_genre_psychological": "Cid's Mind",
        "a_genre_mecha": "None Here",
        "a_critic": "Shadow Critic",
        "a_perfect_ten": "Perfect Plan",
        "a_harsh_critic": "Shadow Standard",
        "a_daily_streak": "Daily Shadow",
        "a_mega_streak": "Eternal Shadow",
        "a_year_long": "Year in Darkness",
        "a_iron_will": "Unyielding Shadow",
        "a_hidden_gem": "Hidden Darkness",
        "a_cult_classic": "Shadow Classic",
        "a_classic_connoisseur": "2022 Fan",
        "a_new_years_resolution": "New Year Dark",
        "a_christmas_special": "Winter Shadow",
        "a_meta_tier_max": "True Eminence",
        "a_meta_completionist": "All Shadows",
        "a_sequel_chain": "Shadow Chain",
        "a_zero_to_hero": "Beta to Shadow",
        "a_night_owl": "Night Stalker",
        "a_early_bird": "Dawn Phantom",
        "m_first_chapter": "First Shadow",
        "m_first_complete": "Op Complete",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Shadow Reading",
        "m_completionist": "Full Dossier",
        "m_mega_completionist": "Shadow Expert",
        "m_loyal_reader": "Devoted Shadow",
        "m_rereader": "Second Recon",
        "m_genre_action": "Action Shadow",
        "m_genre_adventure": "Stealth Chapter",
        "m_genre_romance": "None Here",
        "m_genre_fantasy": "Ancient Chapter",
        "m_genre_horror": "Cult Chapter",
        "m_genre_drama": "Shadow Drama",
        "m_genre_scifi": "None Here",
        "m_genre_supernatural": "Dark Chapter",
        "m_genre_psychological": "Mind of Cid",
        "m_critic": "Shadow Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Shadow Streak",
        "m_year_long": "Year in Darkness",
        "m_iron_will": "Iron Shadow",
        "m_hidden_gem": "Hidden Chapter",
        "m_cult_classic": "Cult Chapter",
        "m_mangaka_lover": "Shadow Artist",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Shadow Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Shadow Art",
        "m_manga_to_anime": "Adapted Shadow",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#010004",
        primary: "#6030bc",
        secondary: "#4418a0",
        accent: "#d0a010",
    },
    particleColor: "#8060d8",
    backgroundDim: 0.32,
    backgroundBlur: 20,
    particleTypes: {
        shadow_wisps: { label: "Shadow Wisps", maxCount: 14, defaultEnabled: true, defaultIntensity: 50 },
        purple_sparks: { label: "Purple Sparks", maxCount: 10, defaultEnabled: true, defaultIntensity: 38 },
    },
    milestoneNames: {
    1: "Generic Rank",
    7: "Generic Rank",
    14: "Generic Rank",
    21: "Generic Rank",
    27: "Generic Rank",
    34: "Generic Rank",
    41: "Generic Rank",
    47: "Generic Rank",
    54: "Generic Rank",
    61: "Generic Rank",
    68: "Generic Rank",
    74: "Generic Rank",
    81: "Generic Rank",
    88: "Generic Rank",
    94: "Generic Rank",
    101: "Generic Rank",
    108: "Generic Rank",
    114: "Generic Rank",
    121: "Generic Rank",
    128: "Generic Rank",
    135: "Generic Rank",
    141: "Generic Rank",
    148: "Generic Rank",
    155: "Generic Rank",
    161: "Generic Rank",
    168: "Generic Rank",
    175: "Generic Rank",
    182: "Generic Rank",
    188: "Generic Rank",
    195: "Generic Rank",
    202: "Generic Rank",
    208: "Generic Rank",
    215: "Generic Rank",
    222: "Generic Rank",
    228: "Generic Rank",
    235: "Generic Rank",
    242: "Generic Rank",
    249: "Generic Rank",
    255: "Generic Rank",
    262: "Generic Rank",
    269: "Generic Rank",
    275: "Generic Rank",
    282: "Generic Rank",
    289: "Generic Rank",
    296: "Generic Rank",
    302: "Generic Rank",
    309: "Generic Rank",
    316: "Generic Rank",
    322: "Generic Rank",
    329: "Generic Rank",
    336: "Generic Rank",
    342: "Generic Rank",
    349: "Generic Rank",
    356: "Generic Rank",
    363: "Generic Rank",
    369: "Generic Rank",
    376: "Generic Rank",
    383: "Generic Rank",
    389: "Generic Rank",
    396: "Generic Rank",
    403: "Generic Rank",
    409: "Generic Rank",
    416: "Generic Rank",
    423: "Generic Rank",
    430: "Generic Rank",
    436: "Generic Rank",
    443: "Generic Rank",
    450: "Generic Rank",
    456: "Generic Rank",
    463: "Generic Rank",
    470: "Generic Rank",
    477: "Generic Rank",
    483: "Generic Rank",
    490: "Generic Rank",
    497: "Generic Rank",
    503: "Generic Rank",
    510: "Generic Rank",
    517: "Generic Rank",
    523: "Generic Rank",
    530: "Generic Rank",
    537: "Generic Rank",
    544: "Generic Rank",
    550: "Generic Rank",
    557: "Generic Rank",
    564: "Generic Rank",
    570: "Generic Rank",
    577: "Generic Rank",
    584: "Generic Rank",
    591: "Generic Rank",
    597: "Generic Rank",
    604: "Generic Rank",
    611: "Generic Rank",
    617: "Generic Rank",
    624: "Generic Rank",
    631: "Generic Rank",
    637: "Generic Rank",
    644: "Generic Rank",
    651: "Generic Rank",
    658: "Generic Rank",
    664: "Generic Rank",
    671: "Generic Rank",
    678: "Generic Rank",
    684: "Generic Rank",
    691: "Generic Rank",
    698: "Generic Rank",
    704: "Generic Rank",
    711: "Generic Rank",
    718: "Generic Rank",
    725: "Generic Rank",
    731: "Generic Rank",
    738: "Generic Rank",
    745: "Generic Rank",
    751: "Generic Rank",
    758: "Generic Rank",
    765: "Generic Rank",
    772: "Generic Rank",
    778: "Generic Rank",
    785: "Generic Rank",
    792: "Generic Rank",
    798: "Generic Rank",
    805: "Generic Rank",
    812: "Generic Rank",
    818: "Generic Rank",
    825: "Generic Rank",
    832: "Generic Rank",
    839: "Generic Rank",
    845: "Generic Rank",
    852: "Generic Rank",
    859: "Generic Rank",
    865: "Generic Rank",
    872: "Generic Rank",
    879: "Generic Rank",
    886: "Generic Rank",
    892: "Generic Rank",
    899: "Generic Rank",
    906: "Generic Rank",
    912: "Generic Rank",
    919: "Generic Rank",
    926: "Generic Rank",
    932: "Generic Rank",
    939: "Generic Rank",
    946: "Generic Rank",
    953: "Generic Rank",
    959: "Generic Rank",
    966: "Generic Rank",
    973: "Generic Rank",
    979: "Generic Rank",
    986: "Generic Rank",
    993: "Generic Rank",
    1000: "Generic Rank",
  },
}
