import { AnimeThemeConfig } from "./types"
import { GiShield, GiTurtle, GiBroadsword, GiCrown, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiRibbonShield, GiHeartKey, GiAnchor } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const theRisingOfTheShieldHeroTheme: AnimeThemeConfig = {
    id: "the-rising-of-the-shield-hero",
    displayName: "The Rising of the Shield Hero",
    description: "Wrongly accused and betrayed on his first day as a summoned hero, Naofumi Iwatani is left with only his shield and his rage. Rising from disgrace, he forges his own path — building a party, earning trust, and fighting for a world that doubted him.",
    fontFamily: "'Exo 2', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Exo+2:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "185 202 220",
        "--color-brand-300": "148 168 192",
        "--color-brand-400": "110 132 164",
        "--color-brand-500": "78 100 138",
        "--color-brand-600": "52 72 112",
        "--color-brand-700": "32 48 88",
        "--color-brand-800": "18 28 62",
        "--color-brand-900": "8 12 36",
        "--color-brand-950": "2 4 14",
        "--brand": "78 100 138",
        "--background": "#020304",
        "--paper": "#060a0e",
        "--color-gray-950": "2 3 4",
        "--color-gray-900": "6 9 12",
        "--color-gray-800": "14 20 26",
        "--color-gray-700": "25 36 46",
        "--color-gray-600": "42 60 76",
        "--color-gray-500": "70 98 122",
        "--color-gray-400": "105 140 168",
        "--color-gray-300": "148 182 208",
        "--color-gray-200": "188 214 235",
        "--color-gray-100": "220 236 248",
        "--color-gray-50": "244 250 255",
    },
    sidebarOverrides: {
        "home": { icon: GiRibbonShield, label: "Shield's Domain" },
        "schedule": { icon: GiAlarmClock, label: "Wave Schedule" },
        "manga": { icon: LuBookOpen, label: "Hero Records" },
        "lists": { icon: GiFlowerEmblem, label: "Companion Registry" },
        "discover": { icon: GiBullseye, label: "New Waves" },
        "torrent-list": { icon: GiShield, label: "Shield Cache" },
        "debrid": { icon: GiTurtle, label: "Raphtalia's Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Companions" },
        "enmasse": { icon: GiResize, label: "Hero Ops" },
        "scan-summaries": { icon: TbReportSearch, label: "Wave Reports" },
        "auto-downloader": { icon: LuRss, label: "Wave Intel" },
        "community": { icon: GiBroadsword, label: "Shield's Circle" },
        "achievements": { icon: GiTrophy, label: "Hero Trophies" },
        "milestones": { icon: LuFlag, label: "Wave Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Wave Alerts" },
        "theme-manager": { icon: GiPalette, label: "Iron Palette" },
        "extensions": { icon: BiExtension, label: "Hero Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Party Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Naofumi's Config" },
    },
    achievementNames: {
        "a_first_episode": "Summoned",
        "a_first_complete": "Wave Survived",
        "a_hundred_club": "Hundred Waves",
        "a_time_lord": "Veteran Hero",
        "a_anime_collector": "Hero Archive",
        "a_library_legend": "Hero Library",
        "a_binge_king": "Wave Marathon",
        "a_no_sleep": "All-Night Defense",
        "a_marathon_runner": "Naofumi's Run",
        "a_speed_run": "Wave Speed",
        "a_completionist": "Full Wave Set",
        "a_mega_completionist": "True Shield Hero",
        "a_loyal_fan": "Loyal Companion",
        "a_rewatcher": "Replay Wave",
        "a_decade_watcher": "Decade Hero",
        "a_genre_action": "Wave Battle",
        "a_genre_adventure": "Hero Journey",
        "a_genre_comedy": "None Here",
        "a_genre_drama": "Betrayal Drama",
        "a_genre_fantasy": "Hero World",
        "a_genre_horror": "None Here",
        "a_genre_romance": "Raphtalia's Bond",
        "a_genre_scifi": "None Here",
        "a_genre_supernatural": "Wave Magic",
        "a_genre_psychological": "Naofumi's Mind",
        "a_genre_mecha": "None Here",
        "a_critic": "Hero Critic",
        "a_perfect_ten": "Perfect Defense",
        "a_harsh_critic": "Shield Standard",
        "a_daily_streak": "Daily Training",
        "a_mega_streak": "Endless Defense",
        "a_year_long": "Year of Waves",
        "a_iron_will": "Shield's Will",
        "a_hidden_gem": "Hidden Power",
        "a_cult_classic": "Shield Classic",
        "a_classic_connoisseur": "2019 Fan",
        "a_new_years_resolution": "New Year Wave",
        "a_christmas_special": "Winter Defense",
        "a_meta_tier_max": "True Rising Hero",
        "a_meta_completionist": "All Waves",
        "a_sequel_chain": "Shield's Chain",
        "a_zero_to_hero": "Betrayed to Hero",
        "a_night_owl": "Night Watch",
        "a_early_bird": "Dawn Defense",
        "m_first_chapter": "First Shield",
        "m_first_complete": "Arc Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Wave Binge",
        "m_completionist": "Full Novel",
        "m_mega_completionist": "Shield Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "New Wave",
        "m_genre_action": "Battle Chapter",
        "m_genre_adventure": "Journey Chapter",
        "m_genre_romance": "Bond Chapter",
        "m_genre_fantasy": "Hero Chapter",
        "m_genre_horror": "None Here",
        "m_genre_drama": "Drama Chapter",
        "m_genre_scifi": "None Here",
        "m_genre_supernatural": "Magic Chapter",
        "m_genre_psychological": "Mind Chapter",
        "m_critic": "Shield Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Shield Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Iron Shield",
        "m_hidden_gem": "Hidden Chapter",
        "m_cult_classic": "Classic Chapter",
        "m_mangaka_lover": "Aneko Fan",
        "m_source_material_fan": "Novel First",
        "m_meta_tier_max": "Shield Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Hero Art",
        "m_manga_to_anime": "Adapted Wave",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#020304",
        primary: "#4e648a",
        secondary: "#344870",
        accent: "#50b870",
    },
    particleColor: "#789ab8",
    backgroundDim: 0.30,
    backgroundBlur: 16,
    particleTypes: {
        blue_sparks: { label: "Shield Energy", maxCount: 14, defaultEnabled: true, defaultIntensity: 50 },
        golden_sparks: { label: "Wave Sparks", maxCount: 10, defaultEnabled: true, defaultIntensity: 38 },
    },
    milestoneNames: {
    1: "Generic Rank",
    7: "Generic Rank",
    14: "Generic Rank",
    21: "Generic Rank",
    27: "Generic Rank",
    34: "Generic Rank",
    41: "Generic Rank",
    47: "Generic Rank",
    54: "Generic Rank",
    61: "Generic Rank",
    68: "Generic Rank",
    74: "Generic Rank",
    81: "Generic Rank",
    88: "Generic Rank",
    94: "Generic Rank",
    101: "Generic Rank",
    108: "Generic Rank",
    114: "Generic Rank",
    121: "Generic Rank",
    128: "Generic Rank",
    135: "Generic Rank",
    141: "Generic Rank",
    148: "Generic Rank",
    155: "Generic Rank",
    161: "Generic Rank",
    168: "Generic Rank",
    175: "Generic Rank",
    182: "Generic Rank",
    188: "Generic Rank",
    195: "Generic Rank",
    202: "Generic Rank",
    208: "Generic Rank",
    215: "Generic Rank",
    222: "Generic Rank",
    228: "Generic Rank",
    235: "Generic Rank",
    242: "Generic Rank",
    249: "Generic Rank",
    255: "Generic Rank",
    262: "Generic Rank",
    269: "Generic Rank",
    275: "Generic Rank",
    282: "Generic Rank",
    289: "Generic Rank",
    296: "Generic Rank",
    302: "Generic Rank",
    309: "Generic Rank",
    316: "Generic Rank",
    322: "Generic Rank",
    329: "Generic Rank",
    336: "Generic Rank",
    342: "Generic Rank",
    349: "Generic Rank",
    356: "Generic Rank",
    363: "Generic Rank",
    369: "Generic Rank",
    376: "Generic Rank",
    383: "Generic Rank",
    389: "Generic Rank",
    396: "Generic Rank",
    403: "Generic Rank",
    409: "Generic Rank",
    416: "Generic Rank",
    423: "Generic Rank",
    430: "Generic Rank",
    436: "Generic Rank",
    443: "Generic Rank",
    450: "Generic Rank",
    456: "Generic Rank",
    463: "Generic Rank",
    470: "Generic Rank",
    477: "Generic Rank",
    483: "Generic Rank",
    490: "Generic Rank",
    497: "Generic Rank",
    503: "Generic Rank",
    510: "Generic Rank",
    517: "Generic Rank",
    523: "Generic Rank",
    530: "Generic Rank",
    537: "Generic Rank",
    544: "Generic Rank",
    550: "Generic Rank",
    557: "Generic Rank",
    564: "Generic Rank",
    570: "Generic Rank",
    577: "Generic Rank",
    584: "Generic Rank",
    591: "Generic Rank",
    597: "Generic Rank",
    604: "Generic Rank",
    611: "Generic Rank",
    617: "Generic Rank",
    624: "Generic Rank",
    631: "Generic Rank",
    637: "Generic Rank",
    644: "Generic Rank",
    651: "Generic Rank",
    658: "Generic Rank",
    664: "Generic Rank",
    671: "Generic Rank",
    678: "Generic Rank",
    684: "Generic Rank",
    691: "Generic Rank",
    698: "Generic Rank",
    704: "Generic Rank",
    711: "Generic Rank",
    718: "Generic Rank",
    725: "Generic Rank",
    731: "Generic Rank",
    738: "Generic Rank",
    745: "Generic Rank",
    751: "Generic Rank",
    758: "Generic Rank",
    765: "Generic Rank",
    772: "Generic Rank",
    778: "Generic Rank",
    785: "Generic Rank",
    792: "Generic Rank",
    798: "Generic Rank",
    805: "Generic Rank",
    812: "Generic Rank",
    818: "Generic Rank",
    825: "Generic Rank",
    832: "Generic Rank",
    839: "Generic Rank",
    845: "Generic Rank",
    852: "Generic Rank",
    859: "Generic Rank",
    865: "Generic Rank",
    872: "Generic Rank",
    879: "Generic Rank",
    886: "Generic Rank",
    892: "Generic Rank",
    899: "Generic Rank",
    906: "Generic Rank",
    912: "Generic Rank",
    919: "Generic Rank",
    926: "Generic Rank",
    932: "Generic Rank",
    939: "Generic Rank",
    946: "Generic Rank",
    953: "Generic Rank",
    959: "Generic Rank",
    966: "Generic Rank",
    973: "Generic Rank",
    979: "Generic Rank",
    986: "Generic Rank",
    993: "Generic Rank",
    1000: "Generic Rank",
  },
}
