import { AnimeThemeConfig } from "./types"
import { GiCookingPot, GiMeat, GiFoodChain, GiForest, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiMuscleUp, GiHeartKey, GiEagleHead } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const torikoTheme: AnimeThemeConfig = {
    id: "toriko",
    displayName: "Toriko",
    description: "In a world where the best flavours of nature are the ultimate prize, the Gourmet Hunter Toriko ventures into the most dangerous wildernesses to capture legendary ingredients for his ever-growing Full Course Menu.",
    fontFamily: "'Permanent Marker', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap",
    cssVars: {
        "--color-brand-200": "252 220 140",
        "--color-brand-300": "245 190 70",
        "--color-brand-400": "230 158 10",
        "--color-brand-500": "200 124 0",
        "--color-brand-600": "160 92 0",
        "--color-brand-700": "118 64 0",
        "--color-brand-800": "78 40 0",
        "--color-brand-900": "42 18 0",
        "--color-brand-950": "18 6 0",
        "--brand": "200 124 0",
        "--background": "#060300",
        "--paper": "#120800",
        "--color-gray-950": "6 3 0",
        "--color-gray-900": "14 7 0",
        "--color-gray-800": "26 14 2",
        "--color-gray-700": "44 24 6",
        "--color-gray-600": "70 40 12",
        "--color-gray-500": "112 70 25",
        "--color-gray-400": "160 112 55",
        "--color-gray-300": "205 155 88",
        "--color-gray-200": "232 192 128",
        "--color-gray-100": "248 222 172",
        "--color-gray-50": "255 244 225",
    },
    sidebarOverrides: {
        "home": { icon: GiFoodChain, label: "Gourmet World" },
        "schedule": { icon: GiAlarmClock, label: "Hunt Schedule" },
        "manga": { icon: LuBookOpen, label: "Gourmet Bible" },
        "lists": { icon: GiFlowerEmblem, label: "Ingredient Registry" },
        "discover": { icon: GiBullseye, label: "New Beasts" },
        "torrent-list": { icon: GiMeat, label: "Full Course Cache" },
        "debrid": { icon: GiForest, label: "Gourmet Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Ingredients" },
        "enmasse": { icon: GiResize, label: "Combo Hunt" },
        "scan-summaries": { icon: TbReportSearch, label: "Hunt Reports" },
        "auto-downloader": { icon: LuRss, label: "Gourmet Feed" },
        "community": { icon: GiEagleHead, label: "Hunter Circle" },
        "achievements": { icon: GiTrophy, label: "Gourmet Trophies" },
        "milestones": { icon: LuFlag, label: "Full Course Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Ingredient Alerts" },
        "theme-manager": { icon: GiPalette, label: "Gold Palette" },
        "extensions": { icon: BiExtension, label: "Hunt Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Menu Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Toriko's Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Hunt",
        "a_episode_counter": "Gourmet Review Mark",
        "a_episode_titan": "Decade Hunter Relic",
        "a_hours_invested": "Dawn Hunt Proof",
        "a_time_lord": "Master Hunter",
        "a_anime_collector": "Gourmet Archive",
        "a_library_legend": "Gourmet Library",
        "a_first_complete": "Ingredient Captured",
        "a_hundred_club": "Hundred Ingredients",
        "a_first_day": "Master Hunter Seal",
        "a_first_rating": "Decade Hunter Appraisal",
        "a_ten_thousand_min": "Feast Marathon Standard",
        "a_season_veteran": "Feast Marathon Library",
        "a_year_explorer": "Toriko's Mind Map",
        "a_century_watcher": "Gourmet Binge Ledger",
        "a_five_hundred_eps": "Hunter Circle Dominion",
        "a_thousand_eps": "Komatsu Comedy Record",
        "a_watching_ten": "Gourmet Hunter Toriko Acclaim",
        "a_ptw_hoarder": "Shimabukuro Fan Library",
        "a_dropped_honesty": "Gourmet Hunter Toriko Summit",
        "a_five_thousand_eps": "Toriko Expert Warrant",
        "a_ten_completed": "Gourmet Vault Afterglow",
        "a_fifty_completed": "Gourmet Critic Ascension",
        "a_five_hundred_completed": "Gourmet Hunter Toriko Clear",
        "a_mean_score_tracker": "Gourmet Streak Verdict",
        "a_unique_studios": "Komatsu Comedy Collection",
        "a_days_spent_watching": "Gourmet Classic Dominion",
        "a_all_status": "Gourmet Archive Testament",
        "a_first_favorite": "Devoted Fan Cabinet",
        "a_favorites_collector": "Loyal Partner Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Quick Capture Drive",
        "a_marathon_runner": "Toriko's Run",
        "a_weekend_warrior": "Decade Hunter Ordeal",
        "a_non_stop": "Lost Ingredients Fever",
        "a_one_more_episode": "Endless Feast Mantle",
        "a_speed_run": "Quick Capture",
        "a_double_feature": "Winter Hunt Crown",
        "a_triple_threat": "Hidden Recipe Record",
        "a_five_a_day": "Replay Hunt Accord",
        "a_back_to_back": "Toriko's Chain Surge",
        "a_seasonal_binge": "Decade Hunter Cascade",
        "a_cour_crusher": "Gourmet Classic Ordeal",
        "a_half_day_watch": "Gourmet Review Crown",
        "a_full_day_watch": "Gold Palette Pinnacle",
        "a_power_weekend": "Master Hunter Run",
        "a_binge_king": "Feast Marathon",
        "a_no_sleep": "All-Night Hunt",
        "a_entire_season": "Gourmet World Library",
        "a_seven_day_challenge": "Gold Palette Mark",
        "a_hundred_day_binge": "Master Hunter Surge",
        "a_genre_binge": "Gourmet Trophies Binge",
        "a_studio_binge": "Gourmet Review Fever",
        "a_season_sweep": "Gourmet Standard Codex",
        "a_forty_eight_hour": "Toriko's Run Overture",
        "a_ep_counter_day": "Gourmet Vault Aegis",
        "a_multi_series_binge": "Shimabukuro Fan Streak",
        "a_midnight_binge": "Endless Feast Cascade",
        "a_new_year_binge": "Gourmet Bible Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Gourmet Battle",
        "a_genre_adventure": "Gourmet World",
        "a_genre_comedy": "Komatsu Comedy",
        "a_genre_drama": "Gourmet Drama",
        "a_genre_fantasy": "Gourmet World",
        "a_genre_horror": "None Here",
        "a_genre_mystery": "Toriko's Hunger Mystery",
        "a_genre_romance": "None Here",
        "a_genre_scifi": "Gourmet Science",
        "a_genre_sol": "Toriko Expert Slice",
        "a_genre_sports": "Toriko's Run Sports",
        "a_genre_supernatural": "Gourmet Power",
        "a_genre_thriller": "Gourmet Critic Thriller",
        "a_genre_mecha": "None Here",
        "a_genre_music": "Feast Marathon Music",
        "a_genre_psychological": "Toriko's Mind",
        "a_genre_ecchi": "Quick Capture Ecchi",
        "a_genre_mahou_shoujo": "Hidden Recipe Magic Shoujo",
        "a_tag_isekai": "All Night Isekai",
        "a_tag_harem": "Daily Hunt Harem",
        "a_tag_bl": "Toriko's Run Bl",
        "a_tag_gl": "Endless Feast Gl",
        "a_tag_historical": "Night Hunt Historical",
        "a_tag_military": "Hunter Circle Military",
        "a_tag_school": "Shimabukuro Fan School",
        "a_tag_martial_arts": "Gold Palette Martial Arts",
        "a_tag_vampire": "Hidden Recipe Vampire",
        "a_tag_samurai": "Komatsu Comedy Samurai",
        "a_tag_space": "Course Menu Space",
        "a_tag_parody": "Iron Hunger Parody",
        "a_tag_idol": "Toriko's Run Idol",
        "a_tag_post_apocalyptic": "Gourmet Library Post Apocalyptic",
        "a_tag_cyberpunk": "Lost Ingredients Cyberpunk",
        "a_tag_shounen": "Gourmet Library Shounen",
        "a_tag_seinen": "Gourmet Art Seinen",
        "a_tag_shoujo": "Gourmet Art Shoujo",
        "a_tag_josei": "Gourmet Vault Josei",
        "a_tag_survival": "Loyal Partner Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Course",
        "a_mega_completionist": "Gourmet God",
        "a_completion_rate_50": "Hidden Recipe Return",
        "a_completion_rate_75": "Gourmet Critic Crown",
        "a_completion_rate_90": "Gourmet Vault Resolution",
        "a_no_drop": "Toriko's Hunger Decree",
        "a_long_runner_complete": "Master Hunter Clear",
        "a_sequel_chain": "Toriko's Chain",
        "a_clean_list": "Gourmet Standard Relic",
        "a_from_ptw": "Iron Hunger Index",
        "a_rewatch_master": "Gourmet Streak Return",
        "a_short_complete": "Gourmet Battle Endgame",
        "a_same_day_start_finish": "Gourmet Science Pinnacle",
        "a_revival": "Gourmet Binge Insignia",
        "a_zero_to_hero": "Taste to Legend",
        "a_five_genre_complete": "Gourmet Battle A Five Genre",
        "a_full_franchise": "Shimabukuro Fan Chronicle",
        "a_batch_complete": "Decade Hunter Crown",
        "a_paused_to_done": "Gourmet Vault Aegis Aegis",
        "a_completion_spree": "Gourmet Power Triumph",
        "a_multi_rewatch": "Gourmet Power Triumph Triumph",
        "a_dropped_recovery": "Gourmet Review Conquest",
        "a_ten_perfect_scores": "Master Hunter Acclaim",
        "a_seasonal_clear": "Gourmet Classic Codex",
        "a_complete_genre_span": "Gourmet God A Complete Genre",
        "a_monthly_completions": "Gourmet Streak Afterglow",
        "a_yearly_completions": "Gourmet Archive Epilogue",
        "a_rapid_complete": "Gold Palette Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Partner",
        "a_studio_devotee": "Toriko's Hunger Treasury",
        "a_rewatcher": "Replay Hunt",
        "a_triple_rewatch": "Gourmet Trophies Coda",
        "a_annual_tradition": "Gold Palette Proof",
        "a_director_fan": "Gourmet Standard Trial",
        "a_voice_actor_fan": "Gourmet Review Crown Crown",
        "a_ost_lover": "Shimabukuro Fan Seal",
        "a_source_reader": "Toriko's Mind Cabinet",
        "a_waiting_weekly": "Toriko's Hunger Clock",
        "a_childhood_revisit": "Gourmet Drama Seal",
        "a_saga_tracker": "Course Menu Standard",
        "a_genre_loyalty": "Toriko Expert Loyalty",
        "a_decade_watcher": "Decade Hunter",
        "a_adaptation_hunter": "Iron Hunger Trial",
        "a_original_anime_fan": "Perfect Dish Testament",
        "a_long_commitment": "Gold Palette Mark Mark",
        "a_perfect_attendance": "Gourmet Hunter Toriko Standard",
        "a_favorite_studio_5": "Gourmet Library Library",
        "a_complete_catalog": "Loyal Partner Seal",
        "a_franchise_collector": "Gourmet Library Archive",
        "a_airing_follower": "Gourmet Drama Signal",
        "a_genre_master": "Gourmet Standard Master",
        "a_staff_follower": "Gourmet Library Oath",
        "a_multi_season_fan": "Night Hunt Hoard",
        "a_format_diversity": "Hidden Recipe Cache",
        "a_year_dedication": "Decade Hunter Tenure",
        "a_season_dedication": "Hunter Circle Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Gourmet Trophies Explorer",
        "a_studio_hopper": "Gourmet Streak Collection",
        "a_tag_explorer": "Decade Hunter Explorer",
        "a_decade_hopper": "Shimabukuro Fan Chronicle Chronicle",
        "a_hidden_gem": "Hidden Ingredient",
        "a_popular_taste": "Toriko's Run Decree",
        "a_retro_appreciator": "Loyal Partner Aegis",
        "a_modern_viewer": "Gourmet Science Pinnacle Pinnacle",
        "a_cross_demographic": "Quick Capture Pinnacle",
        "a_underdog_fan": "Gourmet God Trial",
        "a_variety_week": "Gourmet Library Horizon",
        "a_foreign_cinema": "Endless Feast Expedition",
        "a_classic_connoisseur": "2011 Fan",
        "a_every_season": "Gourmet Drama Archive",
        "a_award_winner": "Feast Marathon Insignia",
        "a_niche_explorer": "Gourmet Art Horizon",
        "a_global_anime": "Gourmet Battle Crown",
        "a_cult_classic": "Gourmet Classic",
        "a_random_pick": "Toriko's Run Decree Decree",
        "a_new_genre_month": "Gourmet Hunter Toriko A New",
        "a_seasonal_completionist": "Gourmet Binge Summit",
        "a_unpopular_opinion": "Devoted Fan Standard",
        "a_top_rated_viewer": "Replay Hunt Seal",
        "a_source_variety": "Gourmet Classic Storehouse",
        "a_low_score_brave": "Lost Ingredients Measure",
        "a_upcoming_watcher": "Replay Hunt Seal Seal",
        "a_short_series_explorer": "Endless Feast Expedition Expedition",
        "a_long_series_explorer": "Winter Hunt Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Night Hunt",
        "a_early_bird": "Dawn Hunt",
        "a_lunch_break": "Combo Hunt Trial",
        "a_golden_hour": "Adapted Feast Tenure",
        "a_four_am_club": "Gourmet Power Gathering",
        "a_witching_hour": "Gourmet Critic Tenure",
        "a_new_year_watch": "Decade Hunter Season",
        "a_midnight_premiere": "Gourmet Bible Devotion",
        "a_all_hours": "Gourmet Binge Seal",
        "a_dawn_warrior": "Toriko's Run Aegis",
        "a_afternoon_delight": "Dawn Hunt Proof Proof",
        "a_prime_time": "Feast Marathon Insignia Insignia",
        "a_workday_watcher": "Quick Capture Pinnacle Pinnacle",
        "a_sunday_marathon": "Master Hunter Momentum",
        "a_rainy_day": "Gourmet Critic Relic",
        "a_morning_routine": "Night Hunt Promise",
        "a_night_shift": "Hidden Recipe Aegis",
        "a_twilight_zone": "Gourmet World Ledger",
        "a_seasonal_premier": "Toriko's Hunger Cabinet",
        "a_clock_collector": "Gourmet Power Repository",
        "a_weekend_binge_hours": "Gourmet Art Streak",
        "a_late_night_regular": "Gourmet Archive Dominion",
        "a_sunrise_watcher": "Gourmet Standard Relic Relic",
        "a_holiday_watcher": "Replay Hunt Pact",
        "a_every_day_of_week": "Toriko's Chain Ledger",
        "a_monthly_hours": "Toriko's Run Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Gourmet Vault Record",
        "a_party_host": "Hidden Recipe Record Record",
        "a_social_butterfly": "Toriko's Mind Company",
        "a_group_binge": "Komatsu Comedy Sprint",
        "a_party_regular": "Gourmet World Chronicle",
        "a_sync_viewer": "Gourmet Power Standard",
        "a_commentator": "Loyal Partner Record",
        "a_party_marathon": "Gourmet Trophies Vigil",
        "a_full_house": "Hunter Circle Trial",
        "a_community_pillar": "Gourmet Archive Alliance",
        "a_watch_party_streak": "Loyal Partner Vigil",
        "a_diverse_party": "Night Hunt Seal",
        "a_late_night_party": "Gourmet Archive Testament Testament",
        "a_party_veteran": "Hunter Circle Testament",
        "a_genre_party": "Endless Feast Party",
        "a_weekly_party": "Gourmet Power Calendar",
        "a_silent_viewer": "Perfect Dish Mantle",
        "a_recommendation_giver": "Gourmet Art Network",
        "a_party_completionist": "Course Menu Coda",
        "a_social_scorer": "Gourmet Standard Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Winter Hunt Proof",
        "a_fibonacci": "Decade Hunter Dominion",
        "a_palindrome_day": "Decade Hunter Relic Relic",
        "a_binary_day": "Toriko Expert Mark",
        "a_full_moon": "Gourmet Drama Insignia",
        "a_leap_year": "Gourmet Battle Devotion",
        "a_time_traveler": "Toriko's Hunger Record",
        "a_genre_clash": "Gourmet Trophies Clash",
        "a_triple_seven": "Decade Hunter Testament",
        "a_thousand_complete": "Perfect Dish Epilogue",
        "a_pi_episodes": "Quick Capture Crown",
        "a_synchronicity": "Gourmet God Anchor",
        "a_world_record": "Gourmet Review Warrant",
        "a_nice": "Feast Marathon Chronicle",
        "a_power_level": "Perfect Dish Testament Testament",
        "a_answer_42": "Toriko's Run Standard",
        "a_square_number": "Gourmet Trophies Decree",
        "a_prime_count": "Feast Marathon Seal",
        "a_matching_date": "Gourmet God Mantle",
        "a_century_episode": "Quick Capture Mark",
        "a_double_digits": "Gourmet Critic Testament",
        "a_one_two_three": "Gourmet Battle Crown Crown",
        "a_lucky_seven": "Gold Palette Crown",
        "a_all_tens": "Lost Ingredients Criterion",
        "a_exact_hundred_eps": "Course Menu Legend",
        "a_year_match_count": "Toriko's Hunger Yearlong",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Gourmet Art Ledger",
        "a_movie_buff": "Gourmet Review Mark Mark",
        "a_ova_hunter": "Course Menu Standard Standard",
        "a_ona_explorer": "Gourmet God Secret",
        "a_special_watcher": "Gourmet Critic Relic Relic",
        "a_short_king": "Daily Hunt Crown",
        "a_variety_pack": "Gourmet Review Inquiry",
        "a_film_festival": "Replay Hunt Chronicle",
        "a_music_video": "Night Hunt Chronicle",
        "a_tv_short": "Gourmet Trophies Record",
        "a_movie_marathon": "Gourmet Trophies Gauntlet",
        "a_double_length": "Winter Hunt Crown Crown",
        "a_anthology": "Hidden Recipe Aegis Aegis",
        "a_mini_series": "Devoted Fan Decree",
        "a_theatrical": "Gourmet Library Accord",
        "a_format_master": "Gourmet Power Vault",
        "a_long_movie": "Gourmet Binge Insignia Insignia",
        "a_back_catalog": "Loyal Partner Standard",
        "a_cm_watcher": "All Night Aegis",
        "a_pv_collector": "Gourmet God Storehouse",
        "a_format_balance": "Gourmet Power Vault Vault",
        "a_episodic_master": "All Night Standard",
        "a_sequel_movie": "Gourmet Battle Pinnacle",
        "a_recap_watcher": "Combo Hunt Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Hunt",
        "a_mega_streak": "Endless Feast",
        "a_weekly_warrior": "Hunter Circle Season",
        "a_monthly_watcher": "Gourmet Bible Calendar",
        "a_comeback": "Toriko's Mind Decree",
        "a_weekend_streak": "Lost Ingredients Passage",
        "a_no_zero_days": "Toriko Expert Warrant Warrant",
        "a_iron_will": "Toriko's Hunger",
        "a_habit_formed": "Toriko's Chain Banner",
        "a_consistent_pace": "Winter Hunt Measure",
        "a_year_long": "Year of Feasts",
        "a_double_streak": "Gourmet Standard Watch",
        "a_streak_recovery": "Perfect Dish Season",
        "a_daily_minimum": "Gourmet Bible Focus",
        "a_winter_streak": "Endless Feast Watch",
        "a_summer_streak": "Gourmet Critic Resolve",
        "a_morning_streak": "Loyal Partner Clock",
        "a_night_streak": "Toriko's Chain Constancy",
        "a_unbreakable": "Daily Hunt Proof",
        "a_eternal_flame": "Gourmet Streak Standard",
        "a_completion_streak": "Course Menu Return",
        "a_rating_streak": "Decade Hunter Balance",
        "a_multi_ep_streak": "Gourmet Review Ritual",
        "a_genre_streak": "Decade Hunter Streak",
        "a_studio_streak": "Toriko's Mind Cabinet Cabinet",
        "a_perfect_week": "Gourmet God Relic",

        // ── ANIME SCORING ──
        "a_critic": "Gourmet Critic",
        "a_perfect_ten": "Perfect Dish",
        "a_harsh_critic": "Gourmet Standard",
        "a_fair_judge": "Gourmet Archive Balance",
        "a_generous_spirit": "Gourmet Bible Pinnacle",
        "a_score_all": "Dawn Hunt Criterion",
        "a_wide_range": "Feast Marathon Ledger",
        "a_controversial": "Loyal Partner Decree",
        "a_consistent_scorer": "Toriko's Hunger Verdict",
        "a_score_sniper": "Gourmet Battle Score",
        "a_evolving_taste": "Gourmet Standard Testament",
        "a_bell_curve": "Gourmet Hunter Toriko Insignia",
        "a_picky_watcher": "Perfect Dish Warrant",
        "a_100_rated": "Gourmet Power Warrant",
        "a_500_rated": "Daily Hunt Pinnacle",
        "a_mediocre_majority": "Gourmet God Canon",
        "a_rating_spree": "Loyal Partner Review",
        "a_score_variance": "Lost Ingredients Score",
        "a_masterpiece_hunter": "Loyal Partner Banner",
        "a_contrarian": "Gourmet Trophies Record Record",
        "a_optimist": "Night Hunt Ledger",
        "a_score_distributor": "Combo Hunt Appraisal",
        "a_genre_critic": "Winter Hunt Critic",
        "a_mean_above_8": "Gold Palette Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Feast",
        "a_valentines_weeb": "Gourmet Library Vow",
        "a_pi_day": "Gourmet Archive Trial",
        "a_april_fools": "Gourmet Battle Devotion Devotion",
        "a_international_anime_day": "Gourmet Binge Record",
        "a_star_wars_day": "Master Hunter Chronicle",
        "a_summer_solstice": "Toriko Expert Calendar",
        "a_tanabata": "Gourmet Science Focus",
        "a_friday_13th": "Combo Hunt Relic",
        "a_halloween_spirit": "Gourmet Art Vow",
        "a_thanksgiving_binge": "Gourmet World Run",
        "a_christmas_special": "Winter Hunt",
        "a_new_years_eve": "Gold Palette Pilgrimage",
        "a_birthday_watch": "Gourmet Hunter Toriko Vow",
        "a_holiday_marathon": "Komatsu Comedy Overture",
        "a_independence_day": "Gourmet Streak Banner",
        "a_culture_day": "Shimabukuro Fan Insignia",
        "a_spring_equinox": "Komatsu Comedy Decree",
        "a_earth_day": "Gourmet Review Mantle",
        "a_labor_day": "Gourmet Art Seal",
        "a_winter_solstice": "Quick Capture Pilgrimage",
        "a_anime_birthday": "Gourmet Review Pilgrimage",
        "a_every_holiday": "Iron Hunger Resolve",
        "a_consecutive_holidays": "Gourmet Critic Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Toriko's Mind Rank",
        "a_meta_collector": "Shimabukuro Fan Hoard",
        "a_meta_category_starter": "Gourmet Bible Badge",
        "a_meta_tier_climber": "Shimabukuro Fan Glyph",
        "a_meta_tier_max": "True Gourmet",
        "a_meta_xp_earner": "Combo Hunt Emblem",
        "a_meta_difficulty_easy": "Gourmet Archive Mechanism",
        "a_meta_difficulty_hard": "Replay Hunt Writ",
        "a_meta_unlock_spree": "Hunter Circle Panel",
        "a_meta_completionist": "Full Course Done",
        "a_meta_diverse": "Decade Hunter Emblem",
        "a_meta_dominator": "Gourmet World Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Bite",
        "m_chapter_counter": "Gourmet Power Pinnacle",
        "m_chapter_titan": "Gourmet Classic Relic",
        "m_reading_hours": "Combo Hunt Relic Relic",
        "m_reading_time_lord": "Gourmet Binge Record Record",
        "m_manga_collector": "Hunter Circle Ledger",
        "m_library_legend": "Shimabukuro Fan Reliquary",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "Gourmet Library Seal",
        "m_first_rating": "Combo Hunt Eye",
        "m_ten_thousand_pages": "Gourmet Library Gauge",
        "m_volume_collector": "Perfect Dish Storehouse",
        "m_year_explorer": "Toriko's Run Quest",
        "m_century_reader": "Endless Feast Dominion",
        "m_five_hundred_ch": "Feast Marathon Legend",
        "m_thousand_ch": "Gourmet Standard Legend",
        "m_reading_ten": "Endless Feast Appraisal",
        "m_ptr_hoarder": "Gourmet Standard Index",
        "m_dropped_honesty": "Shimabukuro Fan Summit",
        "m_season_reader": "Loyal Partner Treasury",
        "m_active_reader": "Gourmet Critic Trial",
        "m_five_thousand_ch": "Gourmet Trophies Standard",
        "m_ten_completed": "Gourmet Trophies Resolution",
        "m_fifty_completed": "Gourmet Standard Harvest",
        "m_five_hundred_completed": "Toriko's Chain Legacy",
        "m_mean_score_tracker": "Toriko's Hunger Audit",
        "m_unique_authors": "Gourmet Review Reserve",
        "m_all_status": "Gourmet Critic Testament Testament",
        "m_first_favorite": "Course Menu Cache",
        "m_favorites_collector": "Toriko's Mind Shelf",
        "m_days_spent_reading": "Quick Capture Relic",

        // ── MANGA BINGE ──
        "m_binge_reader": "Gourmet Hunter Toriko Streak",
        "m_marathon_reader": "Gourmet Archive Rush",
        "m_weekend_reader": "Gourmet Drama Run",
        "m_non_stop_reading": "Course Menu Gauntlet",
        "m_one_more_chapter": "Combo Hunt Testament Testament",
        "m_speed_read": "Toriko Expert Drive",
        "m_double_story": "Komatsu Comedy Banner",
        "m_triple_read": "Gourmet Streak Record",
        "m_five_a_day": "Night Hunt Insignia",
        "m_chapter_chain": "Shimabukuro Fan Accord",
        "m_volume_binge": "Lost Ingredients Drive",
        "m_power_reader": "Master Hunter Seal Seal",
        "m_half_day_read": "Toriko's Mind Aegis",
        "m_full_day_read": "All Night Aegis Aegis",
        "m_power_weekend": "Gourmet Library Streak",
        "m_binge_king": "Gourmet Binge",
        "m_no_sleep_read": "Endless Feast Rush",
        "m_full_series_rush": "Gourmet Archive Cascade",
        "m_seven_day_challenge": "Gourmet Science Warrant",
        "m_hundred_day_read": "Decade Hunter Legend",
        "m_volume_rush": "Gourmet Vault Gauntlet",
        "m_series_sweep": "Iron Hunger Trial Trial",
        "m_genre_binge": "All Night Binge",
        "m_author_binge": "Gourmet Drama Surge",
        "m_chapter_counter_day": "Gourmet World Ledger Ledger",
        "m_multi_series_binge": "Feast Marathon Charge",
        "m_midnight_binge": "Gourmet Standard Tempest",
        "m_new_year_binge": "Gourmet Review Passage",
        "m_forty_eight_hour": "Toriko's Hunger Rally",
        "m_oneshot_binge": "Toriko Expert Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Battle Chapter",
        "m_genre_adventure": "Hunt Chapter",
        "m_genre_comedy": "Toriko's Mind Comedy",
        "m_genre_drama": "Drama Chapter",
        "m_genre_fantasy": "Gourmet Chapter",
        "m_genre_horror": "None Here",
        "m_genre_mystery": "Gourmet Trophies Mystery",
        "m_genre_romance": "None Here",
        "m_genre_scifi": "Science Chapter",
        "m_genre_sol": "Gourmet Power Slice",
        "m_genre_sports": "Gourmet Vault Sports",
        "m_genre_supernatural": "Power Chapter",
        "m_genre_thriller": "Gourmet God Thriller",
        "m_genre_psychological": "Mind Chapter",
        "m_genre_isekai": "Hunter Circle Isekai",
        "m_genre_shounen": "Adapted Feast Shounen",
        "m_genre_ecchi": "Winter Hunt Ecchi",
        "m_genre_mahou_shoujo": "Toriko's Mind Magic Shoujo",
        "m_genre_mecha": "Perfect Dish Mecha",
        "m_genre_music": "Gourmet Art Music",
        "m_tag_isekai_new": "Combo Hunt Isekai New",
        "m_tag_harem": "Dawn Hunt Harem",
        "m_tag_bl": "Devoted Fan Bl",
        "m_tag_gl": "Gourmet Standard Gl",
        "m_tag_historical": "Feast Marathon Historical",
        "m_tag_military": "Adapted Feast Military",
        "m_tag_school": "Gourmet Library School",
        "m_tag_martial_arts": "Gourmet Power Martial Arts",
        "m_tag_vampire": "Gourmet Vault Vampire",
        "m_tag_samurai": "Hidden Recipe Samurai",
        "m_tag_space": "Devoted Fan Space",
        "m_tag_parody": "Perfect Dish Parody",
        "m_tag_idol": "Devoted Fan Idol",
        "m_tag_post_apocalyptic": "Shimabukuro Fan Post Apocalyptic",
        "m_tag_cyberpunk": "Dawn Hunt Cyberpunk",
        "m_tag_shoujo": "Replay Hunt Shoujo",
        "m_tag_survival": "Toriko's Mind Survival",
        "m_tag_cooking": "Gourmet Hunter Toriko Cooking",
        "m_tag_medical": "Gourmet Critic Medical",
        "m_tag_villainess": "Gourmet Drama Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Toriko Expert",
        "m_completion_rate_50": "Devoted Fan Return",
        "m_completion_rate_75": "Gourmet God Ascension",
        "m_completion_rate_90": "Gourmet Streak Resolution",
        "m_no_drop": "Course Menu Decree",
        "m_long_runner_complete": "Gourmet World Clear",
        "m_sequel_chain": "Gourmet Art Seal Seal",
        "m_clean_list": "Gourmet Classic Relic Relic",
        "m_from_ptr": "Replay Hunt Watchlist",
        "m_reread_master": "Gourmet Archive Trial Trial",
        "m_oneshot_complete": "Gourmet Archive Ascension",
        "m_same_day_start_finish": "Gold Palette Crown Crown",
        "m_revival": "Gourmet World Accord",
        "m_zero_to_hundred": "Gourmet Trophies Banner",
        "m_five_genre_complete": "Toriko Expert M Five Genre",
        "m_full_collection": "Gold Palette Proof Proof",
        "m_batch_complete": "Toriko's Hunger Summit",
        "m_paused_to_done": "Gourmet Streak Standard Standard",
        "m_completion_spree": "Daily Hunt Triumph",
        "m_format_completionist": "Gourmet Archive Completion",
        "m_catch_up": "Gourmet Binge Chronicle",
        "m_multi_reread": "Course Menu Banner",
        "m_dropped_recovery": "Winter Hunt Conquest",
        "m_ten_perfect_scores": "Gourmet Drama Judgment",
        "m_complete_genre_span": "Hunter Circle M Complete Genre",
        "m_monthly_completions": "All Night Return",
        "m_yearly_completions": "Hunter Circle Epilogue",
        "m_rapid_complete": "Gourmet Science Finale",
        "m_author_complete": "Gourmet Library Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Devoted Fan",
        "m_mangaka_lover": "Shimabukuro Fan",
        "m_rereader": "Second Course",
        "m_triple_reread": "Decade Hunter Testament Testament",
        "m_annual_reread": "Gourmet Trophies Banner Banner",
        "m_publisher_fan": "Daily Hunt Mark",
        "m_artist_fan": "Gourmet Art Insignia",
        "m_adaptation_compare": "Gourmet Hunter Toriko Insignia Insignia",
        "m_source_material_fan": "Manga First",
        "m_waiting_weekly": "Hidden Recipe Streak",
        "m_classic_reader": "Perfect Dish Lantern",
        "m_saga_reader": "Shimabukuro Fan Decree",
        "m_genre_loyalty": "Winter Hunt Loyalty",
        "m_decade_reader": "Lost Ingredients Warrant",
        "m_ln_adaptation": "Lost Ingredients Mark",
        "m_original_work": "Gourmet Vault Standard",
        "m_long_commitment": "Winter Hunt Mark",
        "m_up_to_date": "Gourmet Review Warrant Warrant",
        "m_favorite_mangaka": "Toriko's Run Treasury",
        "m_complete_portfolio": "Daily Hunt Triumph Triumph",
        "m_franchise_collector": "Gourmet Binge Archive",
        "m_serialization_follower": "Toriko's Run Handshake",
        "m_genre_master": "Gourmet Classic Master",
        "m_multi_series_author": "Shimabukuro Fan Insignia Insignia",
        "m_format_diversity": "Gourmet Vault Shelf",
        "m_year_dedication": "Endless Feast Tenure",
        "m_ongoing_follower": "Lost Ingredients Fellowship",
        "m_genre_loyalty_50": "Gourmet Standard Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Komatsu Comedy Explorer",
        "m_publisher_hopper": "Daily Hunt Mantle",
        "m_tag_explorer": "Iron Hunger Explorer",
        "m_decade_hopper": "Replay Hunt Chronicle Chronicle",
        "m_hidden_gem": "Hidden Recipe",
        "m_popular_taste": "Toriko's Hunger Record Record",
        "m_retro_reader": "Toriko's Hunger Accord",
        "m_modern_reader": "Feast Marathon Seal Seal",
        "m_cross_demographic": "Gourmet Bible Crown",
        "m_underdog_fan": "Toriko's Hunger Accord Accord",
        "m_variety_week": "Gourmet Art Horizon Horizon",
        "m_manhwa_reader": "Gourmet Battle Proof",
        "m_manhua_reader": "Perfect Dish Mantle Mantle",
        "m_classic_connoisseur": "Toriko's Chain Glimpse",
        "m_award_winner": "Endless Feast Warrant",
        "m_niche_explorer": "Gourmet Hunter Toriko Horizon",
        "m_world_manga": "Gourmet Binge Chronicle Chronicle",
        "m_cult_classic": "Classic Chapter",
        "m_random_pick": "Toriko's Hunger Standard",
        "m_new_genre_month": "Gourmet Binge M New Genre",
        "m_year_completionist": "Gourmet Power Fulfillment",
        "m_unpopular_opinion": "Gourmet Review Trial",
        "m_top_rated_reader": "Gourmet Hunter Toriko Record",
        "m_source_variety": "Perfect Dish Catalogue",
        "m_low_score_brave": "Gourmet Power Score",
        "m_short_manga_explorer": "Feast Marathon Compass",
        "m_long_manga_explorer": "Gourmet Trophies Survey",
        "m_serialization_explorer": "Gourmet God Road",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Devoted Fan Ledger",
        "m_commute_reader": "Gourmet Critic Tenure Tenure",
        "m_four_am_club": "Daily Hunt Fellowship",
        "m_new_year_read": "Gourmet Art Pact",
        "m_all_hours": "Replay Hunt Accord Accord",
        "m_prime_time_reader": "Gourmet Vault Banner",
        "m_workday_reader": "Gourmet World Accord Accord",
        "m_sunday_read": "Devoted Fan Standard Standard",
        "m_morning_routine": "Gourmet World Discipline",
        "m_night_shift_reader": "Gourmet Library Accord Accord",
        "m_seasonal_premier_read": "Perfect Dish Seasonal",
        "m_clock_collector": "Quick Capture Reserve",
        "m_late_night_horror": "Toriko Expert Mark Mark",
        "m_afternoon_reader": "Endless Feast Mantle Mantle",
        "m_golden_hour_reader": "Decade Hunter Observance",
        "m_dawn_reader": "Iron Hunger Mantle",
        "m_twilight_reader": "Lost Ingredients Crown",
        "m_midnight_start": "Gourmet Vault Routine",
        "m_weekend_binge_hours": "Gourmet Drama Momentum",
        "m_late_night_regular": "Devoted Fan Accord",
        "m_sunrise_reader": "Dawn Hunt Mantle",
        "m_every_day_of_week": "Perfect Dish Warrant Warrant",
        "m_monthly_hours": "Komatsu Comedy Vigil",
        "m_bedtime_reader": "Gourmet Power Warrant Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Gourmet Art",
        "m_webtoon_reader": "Lost Ingredients Mark Mark",
        "m_full_color": "Gourmet Art Accord",
        "m_doujin_reader": "Gourmet Streak Record Record",
        "m_anthology_reader": "Gourmet Drama Accord",
        "m_adaptation_reader": "Toriko's Hunger Banner",
        "m_longstrip_reader": "Decade Hunter Trial",
        "m_4koma_reader": "Hidden Recipe Ledger",
        "m_oneshot_reader": "Hunter Circle Mantle",
        "m_format_variety": "Daily Hunt Gallery",
        "m_light_novel_reader": "Replay Hunt Insignia",
        "m_novel_reader": "Gourmet Power Crown",
        "m_visual_storyteller": "Endless Feast Testament",
        "m_colored_classic": "Loyal Partner Survey",
        "m_webcomic_fan": "Toriko's Chain Insignia",
        "m_manga_to_anime": "Adapted Feast",
        "m_seinen_reader": "Winter Hunt Pinnacle",
        "m_josei_reader": "Dawn Hunt Pinnacle",
        "m_award_winning_art": "Adapted Feast Relic",
        "m_debut_work": "Adapted Feast Dominion",
        "m_vertical_scroll": "Shimabukuro Fan Decree Decree",
        "m_traditional_format": "Gourmet Hunter Toriko Hoard",
        "m_cross_media": "Feast Marathon Accord",
        "m_spinoff_reader": "Gourmet Binge Accord",
        "m_remake_reader": "Gourmet Archive Pinnacle",
        "m_collaboration_reader": "Toriko's Chain Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Gourmet Streak",
        "m_weekly_warrior": "Gourmet God Season",
        "m_monthly_reader": "Night Hunt Discipline",
        "m_comeback": "Gourmet Trophies Standard Standard",
        "m_weekend_streak": "Dawn Hunt Fever",
        "m_no_zero_days": "Gourmet Battle Proof Proof",
        "m_iron_will": "Iron Hunger",
        "m_habit_formed": "Gourmet Bible Crown Crown",
        "m_consistent_pace": "Gold Palette Scrutiny Scrutiny",
        "m_year_long": "Year Reading",
        "m_double_streak": "Hunter Circle Resolve",
        "m_streak_recovery": "Gourmet Classic Resolve",
        "m_daily_minimum": "Quick Capture Focus",
        "m_winter_streak": "Decade Hunter Observance Observance",
        "m_summer_streak": "Adapted Feast Observance",
        "m_morning_streak": "Komatsu Comedy Clock",
        "m_night_streak": "Gourmet Hunter Toriko Discipline",
        "m_unbreakable": "Dawn Hunt Warrant",
        "m_eternal_flame": "Toriko's Mind Record",
        "m_chapter_a_day": "Devoted Fan Ledger Ledger",
        "m_genre_streak": "Iron Hunger Streak",
        "m_completion_streak": "Toriko's Hunger Return",
        "m_rating_streak": "Iron Hunger Appraisal",
        "m_multi_ch_streak": "Gourmet God Tenure",
        "m_author_streak": "Quick Capture Calendar",
        "m_perfect_week_manga": "Gourmet Binge Accord Accord",
        "m_diverse_streak": "Course Menu Streak",

        // ── MANGA SCORING ──
        "m_critic": "Gourmet Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_harsh_critic": "Replay Hunt Scale",
        "m_fair_judge": "Combo Hunt Eye Eye",
        "m_generous_spirit": "Gourmet Drama Decree",
        "m_score_all": "Lost Ingredients Reckoning",
        "m_wide_range": "Night Hunt Ledger Ledger",
        "m_controversial": "All Night Standard Standard",
        "m_consistent_scorer": "Gourmet Streak Grade",
        "m_score_sniper": "Gourmet Review Reckoning",
        "m_evolving_taste": "Hunter Circle Trial Trial",
        "m_bell_curve": "Night Hunt Accord",
        "m_picky_reader": "Course Menu Ledger",
        "m_100_rated": "Night Hunt Standard",
        "m_500_rated": "Gourmet Library Aegis",
        "m_mediocre_majority": "Hunter Circle Canon",
        "m_rating_spree": "Komatsu Comedy Verdict",
        "m_score_variance": "Gourmet Power Measure",
        "m_binge_rater": "Quick Capture Passage",
        "m_reread_rerate": "Loyal Partner Banner Banner",
        "m_masterpiece_hunter": "All Night Banner",
        "m_contrarian": "Toriko's Hunger Aegis",
        "m_optimist": "Feast Marathon Accord Accord",
        "m_score_distributor": "Gourmet God Balance",
        "m_genre_critic": "Quick Capture Critic",
        "m_mean_above_8": "Gourmet Power Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Endless Feast Season",
        "m_valentines_read": "Iron Hunger Observance",
        "m_pi_day": "Hunter Circle Testament Testament",
        "m_april_fools": "Gourmet Review Devotion",
        "m_international_manga_day": "Replay Hunt Aegis",
        "m_free_comic_day": "Gourmet Drama Chronicle",
        "m_summer_solstice": "Gourmet Science Focus Focus",
        "m_tanabata": "Gold Palette Tanabata",
        "m_friday_13th": "Gourmet Archive Dominion Dominion",
        "m_halloween_read": "Toriko Expert Halloween",
        "m_thanksgiving_binge": "Gourmet Binge Charge",
        "m_christmas_read": "Gourmet World Pact",
        "m_new_years_eve": "Gourmet Science Pilgrimage",
        "m_birthday_read": "Winter Hunt Focus",
        "m_holiday_marathon": "Toriko's Run Rally",
        "m_independence_day": "Toriko's Hunger Aegis Aegis",
        "m_culture_day": "Gourmet Library Seal Seal",
        "m_spring_equinox": "Toriko Expert Dominion",
        "m_earth_day": "Winter Hunt Trial",
        "m_labor_day": "Gourmet World Seal",
        "m_winter_solstice": "Gourmet Bible Focus Focus",
        "m_manga_birthday": "Gold Palette Ritual",
        "m_every_holiday_reader": "Gourmet Classic Watch",
        "m_consecutive_holidays": "Gourmet Archive Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Master Hunter Aegis",
        "m_fibonacci": "Gourmet Critic Dominion",
        "m_palindrome_day": "Hunter Circle Relic",
        "m_binary_day": "Gourmet Bible Proof",
        "m_full_moon_read": "Dawn Hunt Crown",
        "m_leap_year_read": "Course Menu Practice",
        "m_triple_seven": "Combo Hunt Trial Trial",
        "m_thousand_complete": "Combo Hunt Ascension",
        "m_nice": "Shimabukuro Fan Seal Seal",
        "m_power_level_chapters": "Gourmet Trophies Aegis",
        "m_answer_42": "Dawn Hunt Trial",
        "m_square_number": "Toriko's Mind Standard",
        "m_prime_count": "Combo Hunt Pinnacle",
        "m_matching_date": "Gourmet Classic Mantle",
        "m_century_chapter": "Master Hunter Decree",
        "m_pi_chapters": "Winter Hunt Proof Proof",
        "m_synchronicity": "Iron Hunger Emblem",
        "m_world_record": "Gourmet Battle Warrant",
        "m_genre_clash": "Gourmet Vault Clash",
        "m_time_traveler": "Gourmet Streak Decree",
        "m_double_digits": "Perfect Dish Dominion",
        "m_one_two_three": "Toriko's Chain Banner Banner",
        "m_lucky_seven": "Gourmet Hunter Toriko Record Record",
        "m_exact_hundred_ch": "Gourmet Critic Legend",
        "m_year_match_count": "Hidden Recipe Routine",
        "m_chapter_match_date": "Gourmet Bible Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Perfect Dish Index",
        "m_manhwa_format": "Toriko Expert Gallery",
        "m_manhua_format": "Decade Hunter Storehouse",
        "m_ln_format": "Combo Hunt Index",
        "m_oneshot_format": "Hunter Circle Index",
        "m_doujin_format": "Komatsu Comedy Cabinet",
        "m_novel_format": "Gourmet Review Reserve Reserve",
        "m_format_master_manga": "Komatsu Comedy Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Gourmet Streak Link",
        "m_meta_collector": "Gourmet Library Reliquary",
        "m_meta_category_starter": "Daily Hunt Standard",
        "m_meta_tier_climber": "Feast Marathon Token",
        "m_meta_tier_max": "Toriko Complete",
        "m_meta_xp_earner": "Perfect Dish Anchor",
        "m_meta_difficulty_easy": "Combo Hunt Panel",
        "m_meta_difficulty_hard": "Endless Feast Node",
        "m_meta_unlock_spree": "Perfect Dish Marker",
        "m_meta_completionist": "Full Library",
        "m_meta_diverse": "Hunter Circle Anchor",
        "m_meta_dominator": "Shimabukuro Fan Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060300",
        primary: "#c87c00",
        secondary: "#a05c00",
        accent: "#40c050",
    },
    particleColor: "#e8a820",
    backgroundDim: 0.28,
    backgroundBlur: 14,
    particleTypes: {
        golden_sparks: { label: "Gourmet Sparks", maxCount: 16, defaultEnabled: true, defaultIntensity: 52 },
        falling_leaves: { label: "Nature Leaves", maxCount: 12, defaultEnabled: true, defaultIntensity: 38 },
    },
    milestoneNames: {
  1: "Starving Drifter",
  7: "Food Scraps Scavenger",
  14: "Weak Stomach Rookie",
  21: "Failed Hunter",
  27: "Barely Surviving",
  34: "Low Tier Forager",
  41: "Untrained Eater",
  47: "Wild Food Victim",
  54: "Hunger Driven Fighter",
  61: "Broken Appetite",
  68: "Poisoned Survivor",
  74: "Failed Ingredient Seeker",
  81: "Disposable Hunter",
  88: "Unworthy Palate",
  94: "Forgotten Gourmet",

  101: "Gourmet Hunter Trainee",
  108: "Ingredient Seeker",
  114: "Capture Level Beginner",
  121: "Jungle Food Scout",
  128: "Beast Encounter Survivor",
  135: "Basic Knife User",
  141: "Food Combat Rookie",
  148: "Low Capture Hunter",
  155: "Wild Ingredient Collector",
  161: "Battle Appetite Awakening",
  168: "First Beast Kill",
  175: "Food Chain Climber",
  182: "Gourmet Association Rookie",
  188: "Stable Hunter",
  195: "Rising Appetite",

  202: "Mid-Level Gourmet Hunter",
  208: "Capture Level Climber",
  215: "Beast Slayer",
  222: "Advanced Ingredient Seeker",
  228: "Food Combat Specialist",
  235: "Gourmet Field Veteran",
  242: "Enhanced Appetite",
  249: "Battle Hardened Hunter",
  255: "Mid Capture Fighter",
  262: "Rare Ingredient Hunter",
  269: "Gourmet Combatant",
  275: "Food Chain Predator",
  282: "Balanced Appetite",
  289: "Near Elite Hunter",
  296: "Rising Gourmet Beast",

  302: "Elite Gourmet Hunter",
  309: "High Capture Specialist",
  316: "Beast Dominator",
  322: "Advanced Appetite User",
  329: "Battle Chef Fighter",
  336: "Gourmet Association Operative",
  342: "High Tier Predator",
  349: "Food Chain Enforcer",
  356: "Savage Appetite",
  363: "Territory Dominator",
  369: "Gourmet World Candidate",
  376: "Near Heavenly King",
  383: "Legendary Hunter",
  389: "Apex Predator Candidate",
  396: "Gourmet Elite",

  403: "Heavenly King Tier",
  409: "Gourmet Master",
  416: "High Capture Monster",
  423: "Beast King Slayer",
  430: "Gourmet World Explorer",
  436: "Battle Appetite Master",
  443: "Elite Predator",
  450: "Food Chain Apex",
  456: "Territory King",
  463: "Savage King",
  470: "Gourmet Champion",
  477: "Near Eight Kings",
  483: "Legendary Devourer",
  490: "Mythical Hunter",
  497: "Gourmet Ace",

  503: "Eight Kings Challenger",
  510: "Gourmet World Apex",
  517: "Battle Appetite Unleashed",
  523: "Absolute Predator",
  530: "Food Chain Tyrant",
  537: "Gourmet World Ruler",
  544: "Infinite Appetite",
  550: "Beast Devourer",
  557: "Ultimate Hunter",
  564: "King of Consumption",
  570: "Top Gourmet Entity",
  577: "Predator Incarnate",
  584: "Near GOD Ingredient",
  591: "Myth of Toriko",
  597: "Devouring Legend",

  604: "GOD Ingredient Candidate",
  611: "Gourmet Cell Apex",
  617: "Appetite Demon Awakening",
  624: "Monster of Consumption",
  631: "Gourmet World Overlord",
  637: "Food Chain Breaker",
  644: "Infinite Stomach",
  651: "Gourmet Deity Candidate",
  658: "Appetite King",
  664: "World Devourer",
  671: "Near Absolute Hunger",
  678: "Legend of Gourmet World",
  684: "Fully Realized Hunter",
  691: "Mythic Appetite",
  698: "True Toriko Form",

  704: "Appetite Awakening Phase",
  711: "Gourmet Cell Surge",
  718: "Battle Appetite Peak",
  725: "Consumption Singularity",
  731: "Food Chain Collapse I",
  738: "Gourmet World Expansion",
  745: "Appetite Evolution II",
  751: "Infinite Hunger State",
  758: "Devouring Convergence",
  765: "Apex Consumption",
  772: "Near Infinite Appetite",
  778: "Final Gourmet Evolution",
  785: "End of Hunger Limits",
  792: "World of Gourmet",
  798: "Peak Consumption Era",

  805: "Apex Gourmet King",
  812: "Beyond Food Chain",
  818: "World Strongest Eater",
  825: "Absolute Consumption Entity",
  832: "Gourmet System Overlord",
  839: "Reality of Appetite",
  845: "Perfect Devourer Form",
  852: "Infinite Consumption",
  859: "True Toriko",
  865: "Legend Beyond Hunger",
  872: "Myth of Appetite",
  879: "Absolute Gourmet Entity",
  886: "World Devouring Myth",
  892: "GOD Incarnate",
  899: "Near Omnivorous Deity",

  906: "Apex Appetite God",
  912: "Beyond Consumption",
  919: "Final Devourer Form",
  926: "Absolute Hunger Entity",
  932: "Infinite Appetite Presence",
  939: "Reality of Consumption",
  946: "Perfect Gourmet Balance",
  953: "True Appetite Essence",
  959: "God of Food",
  966: "End of Hunger",
  973: "End of Food Chain",
  979: "Abyss of Appetite",
  986: "Final Meal",
  993: "Nothing Left to Eat",
  1000: "Toriko"
}
}
