import { AnimeThemeConfig } from "./types"
import { GiRevolver, GiDesert, GiCactus, GiSun, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiTumbleweed, GiSandstorm, GiWesternHat } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const trigunStampedeTheme: AnimeThemeConfig = {
    id: "trigun-stampede",
    displayName: "Trigun Stampede",
    description: "Vash the Stampede wanders a desert wasteland planet with a $$60 billion bounty on his head, spreading love and peace while somehow surviving every catastrophe he attracts. TRIGUN STAMPEDE reimagines this classic with stunning modern animation.",
    fontFamily: "'Bebas Neue', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap",
    cssVars: {
        "--color-brand-200": "255 240 180",
        "--color-brand-300": "252 226 130",
        "--color-brand-400": "248 206 68",
        "--color-brand-500": "238 182 16",
        "--color-brand-600": "200 148 0",
        "--color-brand-700": "155 108 0",
        "--color-brand-800": "106 68 0",
        "--color-brand-900": "60 36 0",
        "--color-brand-950": "24 12 0",
        "--brand": "238 182 16",
        "--background": "#060500",
        "--paper": "#0e0c00",
        "--color-gray-950": "6 5 0",
        "--color-gray-900": "12 10 2",
        "--color-gray-800": "24 20 4",
        "--color-gray-700": "40 34 6",
        "--color-gray-600": "64 56 12",
        "--color-gray-500": "104 92 26",
        "--color-gray-400": "148 132 58",
        "--color-gray-300": "190 174 100",
        "--color-gray-200": "224 212 150",
        "--color-gray-100": "244 236 200",
        "--color-gray-50": "254 250 238",
    },
    sidebarOverrides: {
        "home": { icon: GiWesternHat, label: "Vash's World" },
        "schedule": { icon: GiAlarmClock, label: "Bounty Schedule" },
        "manga": { icon: LuBookOpen, label: "Stampede Files" },
        "lists": { icon: GiFlowerEmblem, label: "Survivor List" },
        "discover": { icon: GiBullseye, label: "New Targets" },
        "torrent-list": { icon: GiRevolver, label: "Gun Cache" },
        "debrid": { icon: GiCactus, label: "Desert Vault" },
        "unmatched": { icon: GiTumbleweed, label: "Lost Wanderers" },
        "enmasse": { icon: GiResize, label: "Stampede Ops" },
        "scan-summaries": { icon: TbReportSearch, label: "Bounty Reports" },
        "auto-downloader": { icon: LuRss, label: "Stampede Intel" },
        "community": { icon: GiSun, label: "Desert Circle" },
        "achievements": { icon: GiTrophy, label: "Bounty Trophies" },
        "milestones": { icon: LuFlag, label: "Peace Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Bounty Alerts" },
        "theme-manager": { icon: GiPalette, label: "Desert Palette" },
        "extensions": { icon: BiExtension, label: "Vash Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Desert Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Vash's Config" },
    },
    achievementNames: {
        "a_first_episode": "Stampede Begins",
        "a_first_complete": "Love and Peace",
        "a_hundred_club": "Hundred Towns",
        "a_time_lord": "Desert Elder",
        "a_anime_collector": "Vash Archive",
        "a_library_legend": "Stampede Library",
        "a_binge_king": "Desert Marathon",
        "a_no_sleep": "All-Night Wandering",
        "a_marathon_runner": "Vash's Run",
        "a_speed_run": "Stampede Speed",
        "a_completionist": "Full Desert",
        "a_mega_completionist": "True Humanoid",
        "a_loyal_fan": "Loyal Fan",
        "a_rewatcher": "Stampede Replay",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Gun Battle",
        "a_genre_adventure": "Desert Journey",
        "a_genre_comedy": "Vash's Antics",
        "a_genre_drama": "July's Memory",
        "a_genre_fantasy": "Trigun World",
        "a_genre_horror": "None Here",
        "a_genre_romance": "None Here",
        "a_genre_scifi": "Plant Science",
        "a_genre_supernatural": "Plant Power",
        "a_genre_psychological": "Vash's Mind",
        "a_genre_mecha": "None Here",
        "a_critic": "Desert Critic",
        "a_perfect_ten": "Perfect Stampede",
        "a_harsh_critic": "60B Standard",
        "a_daily_streak": "Daily Wandering",
        "a_mega_streak": "Endless Stampede",
        "a_year_long": "Year of Vash",
        "a_iron_will": "Love and Peace",
        "a_hidden_gem": "Hidden Town",
        "a_cult_classic": "1998 Classic",
        "a_classic_connoisseur": "Original Fan",
        "a_new_years_resolution": "New Year Peace",
        "a_christmas_special": "Winter Desert",
        "a_meta_tier_max": "True Typhoon",
        "a_meta_completionist": "All Deserts",
        "a_sequel_chain": "Stampede Chain",
        "a_zero_to_hero": "Wanderer to Legend",
        "a_night_owl": "Night Wandering",
        "a_early_bird": "Dawn Desert",
        "m_first_chapter": "First Town",
        "m_first_complete": "Stampede Arc",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Desert Binge",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Vash Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Replay Stampede",
        "m_genre_action": "Gun Chapter",
        "m_genre_adventure": "Journey Chapter",
        "m_genre_romance": "None Here",
        "m_genre_fantasy": "Desert Chapter",
        "m_genre_horror": "None Here",
        "m_genre_drama": "Memory Chapter",
        "m_genre_scifi": "Plant Chapter",
        "m_genre_supernatural": "Power Chapter",
        "m_genre_psychological": "Mind Chapter",
        "m_critic": "Stampede Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Desert Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Iron Peace",
        "m_hidden_gem": "Hidden Town",
        "m_cult_classic": "Classic Trigun",
        "m_mangaka_lover": "Nightow Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Typhoon Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Desert Art",
        "m_manga_to_anime": "Adapted Vash",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060500",
        primary: "#eeb610",
        secondary: "#c89400",
        accent: "#2090d0",
    },
    particleColor: "#f0c830",
    backgroundDim: 0.30,
    backgroundBlur: 12,
    particleTypes: {
        golden_sparks: { label: "Bullet Sparks", maxCount: 14, defaultEnabled: true, defaultIntensity: 52 },
        dust_wisps: { label: "Desert Dust", maxCount: 12, defaultEnabled: true, defaultIntensity: 42 },
    },
    milestoneNames: {
    "7": "Novice Rank 1",
    "13": "Novice Level 2",
    "20": "Novice Tier 3",
    "27": "Novice Class 4",
    "33": "Novice Grade 5",
    "40": "Novice Position 6",
    "47": "Novice Status 7",
    "53": "Novice Role 8",
    "60": "Novice Title 9",
    "67": "Novice Authority 10",
    "73": "Beginner Rank 11",
    "80": "Beginner Level 12",
    "87": "Beginner Tier 13",
    "93": "Beginner Class 14",
    "100": "Beginner Grade 15",
    "107": "Beginner Position 16",
    "113": "Beginner Status 17",
    "120": "Beginner Role 18",
    "127": "Beginner Title 19",
    "133": "Student Authority 20",
    "140": "Student Rank 21",
    "147": "Student Level 22",
    "153": "Student Tier 23",
    "160": "Student Class 24",
    "167": "Student Grade 25",
    "173": "Student Position 26",
    "180": "Student Status 27",
    "187": "Student Role 28",
    "193": "Student Title 29",
    "200": "Learner Authority 30",
    "207": "Learner Rank 31",
    "213": "Learner Level 32",
    "220": "Learner Tier 33",
    "227": "Learner Class 34",
    "233": "Learner Grade 35",
    "240": "Learner Position 36",
    "247": "Learner Status 37",
    "253": "Learner Role 38",
    "260": "Adept Title 39",
    "267": "Adept Authority 40",
    "273": "Adept Rank 41",
    "280": "Adept Level 42",
    "287": "Adept Tier 43",
    "293": "Adept Class 44",
    "300": "Adept Grade 45",
    "307": "Adept Position 46",
    "313": "Adept Status 47",
    "320": "Expert Role 48",
    "327": "Expert Title 49",
    "333": "Expert Authority 50",
    "340": "Expert Rank 51",
    "347": "Expert Level 52",
    "353": "Expert Tier 53",
    "360": "Expert Class 54",
    "367": "Expert Grade 55",
    "373": "Expert Position 56",
    "380": "Expert Status 57",
    "387": "Master Role 58",
    "393": "Master Title 59",
    "400": "Master Authority 60",
    "407": "Master Rank 61",
    "413": "Master Level 62",
    "420": "Master Tier 63",
    "427": "Master Class 64",
    "433": "Master Grade 65",
    "440": "Master Position 66",
    "447": "Grandmaster Status 67",
    "453": "Grandmaster Role 68",
    "460": "Grandmaster Title 69",
    "467": "Grandmaster Authority 70",
    "473": "Grandmaster Rank 71",
    "480": "Grandmaster Level 72",
    "487": "Grandmaster Tier 73",
    "493": "Grandmaster Class 74",
    "500": "Grandmaster Grade 75",
    "507": "Sage Position 76",
    "513": "Sage Status 77",
    "520": "Sage Role 78",
    "527": "Sage Title 79",
    "533": "Sage Authority 80",
    "540": "Sage Rank 81",
    "547": "Sage Level 82",
    "553": "Sage Tier 83",
    "560": "Sage Class 84",
    "567": "Sage Grade 85",
    "573": "Legend Position 86",
    "580": "Legend Status 87",
    "587": "Legend Role 88",
    "593": "Legend Title 89",
    "600": "Legend Authority 90",
    "607": "Legend Rank 91",
    "613": "Legend Level 92",
    "620": "Legend Tier 93",
    "627": "Legend Class 94",
    "633": "Mythical Grade 95",
    "640": "Mythical Position 96",
    "647": "Mythical Status 97",
    "653": "Mythical Role 98",
    "660": "Mythical Title 99",
    "667": "Mythical Authority 100",
    "673": "Mythical Rank 101",
    "680": "Mythical Level 102",
    "687": "Mythical Tier 103",
    "693": "Mythical Class 104",
    "700": "Godly Grade 105",
    "707": "Godly Position 106",
    "713": "Godly Status 107",
    "720": "Godly Role 108",
    "727": "Godly Title 109",
    "733": "Godly Authority 110",
    "740": "Godly Rank 111",
    "747": "Godly Level 112",
    "753": "Godly Tier 113",
    "760": "Supreme Class 114",
    "767": "Supreme Grade 115",
    "773": "Supreme Position 116",
    "780": "Supreme Status 117",
    "787": "Supreme Role 118",
    "793": "Supreme Title 119",
    "800": "Supreme Authority 120",
    "807": "Supreme Rank 121",
    "813": "Supreme Level 122",
    "820": "Infinite Tier 123",
    "827": "Infinite Class 124",
    "833": "Infinite Grade 125",
    "840": "Infinite Position 126",
    "847": "Infinite Status 127",
    "853": "Infinite Role 128",
    "860": "Infinite Title 129",
    "867": "Infinite Authority 130",
    "873": "Infinite Rank 131",
    "880": "Infinite Level 132",
    "887": "Eternal Tier 133",
    "893": "Eternal Class 134",
    "900": "Eternal Grade 135",
    "907": "Eternal Position 136",
    "913": "Eternal Status 137",
    "920": "Eternal Role 138",
    "927": "Eternal Title 139",
    "933": "Eternal Authority 140",
    "940": "Eternal Rank 141",
    "947": "Transcendent Level 142",
    "953": "Transcendent Tier 143",
    "960": "Transcendent Class 144",
    "967": "Transcendent Grade 145",
    "973": "Transcendent Position 146",
    "980": "Transcendent Status 147",
    "987": "Transcendent Role 148",
    "993": "Transcendent Title 149",
    "1000": "Transcendent Authority 150"
},
}
