import { AnimeThemeConfig } from "./types"
import { GiRevolver, GiDesert, GiCactus, GiSun, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiTumbleweed, GiSandstorm, GiWesternHat } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const trigunStampedeTheme: AnimeThemeConfig = {
    id: "trigun-stampede",
    displayName: "Trigun Stampede",
    description: "Vash the Stampede wanders a desert wasteland planet with a $$60 billion bounty on his head, spreading love and peace while somehow surviving every catastrophe he attracts. TRIGUN STAMPEDE reimagines this classic with stunning modern animation.",
    fontFamily: "'Bebas Neue', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap",
    cssVars: {
        "--color-brand-200": "255 240 180",
        "--color-brand-300": "252 226 130",
        "--color-brand-400": "248 206 68",
        "--color-brand-500": "238 182 16",
        "--color-brand-600": "200 148 0",
        "--color-brand-700": "155 108 0",
        "--color-brand-800": "106 68 0",
        "--color-brand-900": "60 36 0",
        "--color-brand-950": "24 12 0",
        "--brand": "238 182 16",
        "--background": "#060500",
        "--paper": "#0e0c00",
        "--color-gray-950": "6 5 0",
        "--color-gray-900": "12 10 2",
        "--color-gray-800": "24 20 4",
        "--color-gray-700": "40 34 6",
        "--color-gray-600": "64 56 12",
        "--color-gray-500": "104 92 26",
        "--color-gray-400": "148 132 58",
        "--color-gray-300": "190 174 100",
        "--color-gray-200": "224 212 150",
        "--color-gray-100": "244 236 200",
        "--color-gray-50": "254 250 238",
    },
    sidebarOverrides: {
        "home": { icon: GiWesternHat, label: "Vash's World" },
        "schedule": { icon: GiAlarmClock, label: "Bounty Schedule" },
        "manga": { icon: LuBookOpen, label: "Stampede Files" },
        "lists": { icon: GiFlowerEmblem, label: "Survivor List" },
        "discover": { icon: GiBullseye, label: "New Targets" },
        "torrent-list": { icon: GiRevolver, label: "Gun Cache" },
        "debrid": { icon: GiCactus, label: "Desert Vault" },
        "unmatched": { icon: GiTumbleweed, label: "Lost Wanderers" },
        "enmasse": { icon: GiResize, label: "Stampede Ops" },
        "scan-summaries": { icon: TbReportSearch, label: "Bounty Reports" },
        "auto-downloader": { icon: LuRss, label: "Stampede Intel" },
        "community": { icon: GiSun, label: "Desert Circle" },
        "achievements": { icon: GiTrophy, label: "Bounty Trophies" },
        "milestones": { icon: LuFlag, label: "Peace Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Bounty Alerts" },
        "theme-manager": { icon: GiPalette, label: "Desert Palette" },
        "extensions": { icon: BiExtension, label: "Vash Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Desert Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Vash's Config" },
    },
    achievementNames: {
        "a_first_episode": "Stampede Begins",
        "a_first_complete": "Love and Peace",
        "a_hundred_club": "Hundred Towns",
        "a_time_lord": "Desert Elder",
        "a_anime_collector": "Vash Archive",
        "a_library_legend": "Stampede Library",
        "a_binge_king": "Desert Marathon",
        "a_no_sleep": "All-Night Wandering",
        "a_marathon_runner": "Vash's Run",
        "a_speed_run": "Stampede Speed",
        "a_completionist": "Full Desert",
        "a_mega_completionist": "True Humanoid",
        "a_loyal_fan": "Loyal Fan",
        "a_rewatcher": "Stampede Replay",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Gun Battle",
        "a_genre_adventure": "Desert Journey",
        "a_genre_comedy": "Vash's Antics",
        "a_genre_drama": "July's Memory",
        "a_genre_fantasy": "Trigun World",
        "a_genre_horror": "None Here",
        "a_genre_romance": "None Here",
        "a_genre_scifi": "Plant Science",
        "a_genre_supernatural": "Plant Power",
        "a_genre_psychological": "Vash's Mind",
        "a_genre_mecha": "None Here",
        "a_critic": "Desert Critic",
        "a_perfect_ten": "Perfect Stampede",
        "a_harsh_critic": "60B Standard",
        "a_daily_streak": "Daily Wandering",
        "a_mega_streak": "Endless Stampede",
        "a_year_long": "Year of Vash",
        "a_iron_will": "Love and Peace",
        "a_hidden_gem": "Hidden Town",
        "a_cult_classic": "1998 Classic",
        "a_classic_connoisseur": "Original Fan",
        "a_new_years_resolution": "New Year Peace",
        "a_christmas_special": "Winter Desert",
        "a_meta_tier_max": "True Typhoon",
        "a_meta_completionist": "All Deserts",
        "a_sequel_chain": "Stampede Chain",
        "a_zero_to_hero": "Wanderer to Legend",
        "a_night_owl": "Night Wandering",
        "a_early_bird": "Dawn Desert",
        "m_first_chapter": "First Town",
        "m_first_complete": "Stampede Arc",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Desert Binge",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Vash Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Replay Stampede",
        "m_genre_action": "Gun Chapter",
        "m_genre_adventure": "Journey Chapter",
        "m_genre_romance": "None Here",
        "m_genre_fantasy": "Desert Chapter",
        "m_genre_horror": "None Here",
        "m_genre_drama": "Memory Chapter",
        "m_genre_scifi": "Plant Chapter",
        "m_genre_supernatural": "Power Chapter",
        "m_genre_psychological": "Mind Chapter",
        "m_critic": "Stampede Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Desert Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Iron Peace",
        "m_hidden_gem": "Hidden Town",
        "m_cult_classic": "Classic Trigun",
        "m_mangaka_lover": "Nightow Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Typhoon Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Desert Art",
        "m_manga_to_anime": "Adapted Vash",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060500",
        primary: "#eeb610",
        secondary: "#c89400",
        accent: "#2090d0",
    },
    particleColor: "#f0c830",
    backgroundDim: 0.30,
    backgroundBlur: 12,
    particleTypes: {
        golden_sparks: { label: "Bullet Sparks", maxCount: 14, defaultEnabled: true, defaultIntensity: 52 },
        dust_wisps: { label: "Desert Dust", maxCount: 12, defaultEnabled: true, defaultIntensity: 42 },
    },
    milestoneNames: {
    1: "Generic Rank",
    7: "Generic Rank",
    14: "Generic Rank",
    21: "Generic Rank",
    27: "Generic Rank",
    34: "Generic Rank",
    41: "Generic Rank",
    47: "Generic Rank",
    54: "Generic Rank",
    61: "Generic Rank",
    68: "Generic Rank",
    74: "Generic Rank",
    81: "Generic Rank",
    88: "Generic Rank",
    94: "Generic Rank",
    101: "Generic Rank",
    108: "Generic Rank",
    114: "Generic Rank",
    121: "Generic Rank",
    128: "Generic Rank",
    135: "Generic Rank",
    141: "Generic Rank",
    148: "Generic Rank",
    155: "Generic Rank",
    161: "Generic Rank",
    168: "Generic Rank",
    175: "Generic Rank",
    182: "Generic Rank",
    188: "Generic Rank",
    195: "Generic Rank",
    202: "Generic Rank",
    208: "Generic Rank",
    215: "Generic Rank",
    222: "Generic Rank",
    228: "Generic Rank",
    235: "Generic Rank",
    242: "Generic Rank",
    249: "Generic Rank",
    255: "Generic Rank",
    262: "Generic Rank",
    269: "Generic Rank",
    275: "Generic Rank",
    282: "Generic Rank",
    289: "Generic Rank",
    296: "Generic Rank",
    302: "Generic Rank",
    309: "Generic Rank",
    316: "Generic Rank",
    322: "Generic Rank",
    329: "Generic Rank",
    336: "Generic Rank",
    342: "Generic Rank",
    349: "Generic Rank",
    356: "Generic Rank",
    363: "Generic Rank",
    369: "Generic Rank",
    376: "Generic Rank",
    383: "Generic Rank",
    389: "Generic Rank",
    396: "Generic Rank",
    403: "Generic Rank",
    409: "Generic Rank",
    416: "Generic Rank",
    423: "Generic Rank",
    430: "Generic Rank",
    436: "Generic Rank",
    443: "Generic Rank",
    450: "Generic Rank",
    456: "Generic Rank",
    463: "Generic Rank",
    470: "Generic Rank",
    477: "Generic Rank",
    483: "Generic Rank",
    490: "Generic Rank",
    497: "Generic Rank",
    503: "Generic Rank",
    510: "Generic Rank",
    517: "Generic Rank",
    523: "Generic Rank",
    530: "Generic Rank",
    537: "Generic Rank",
    544: "Generic Rank",
    550: "Generic Rank",
    557: "Generic Rank",
    564: "Generic Rank",
    570: "Generic Rank",
    577: "Generic Rank",
    584: "Generic Rank",
    591: "Generic Rank",
    597: "Generic Rank",
    604: "Generic Rank",
    611: "Generic Rank",
    617: "Generic Rank",
    624: "Generic Rank",
    631: "Generic Rank",
    637: "Generic Rank",
    644: "Generic Rank",
    651: "Generic Rank",
    658: "Generic Rank",
    664: "Generic Rank",
    671: "Generic Rank",
    678: "Generic Rank",
    684: "Generic Rank",
    691: "Generic Rank",
    698: "Generic Rank",
    704: "Generic Rank",
    711: "Generic Rank",
    718: "Generic Rank",
    725: "Generic Rank",
    731: "Generic Rank",
    738: "Generic Rank",
    745: "Generic Rank",
    751: "Generic Rank",
    758: "Generic Rank",
    765: "Generic Rank",
    772: "Generic Rank",
    778: "Generic Rank",
    785: "Generic Rank",
    792: "Generic Rank",
    798: "Generic Rank",
    805: "Generic Rank",
    812: "Generic Rank",
    818: "Generic Rank",
    825: "Generic Rank",
    832: "Generic Rank",
    839: "Generic Rank",
    845: "Generic Rank",
    852: "Generic Rank",
    859: "Generic Rank",
    865: "Generic Rank",
    872: "Generic Rank",
    879: "Generic Rank",
    886: "Generic Rank",
    892: "Generic Rank",
    899: "Generic Rank",
    906: "Generic Rank",
    912: "Generic Rank",
    919: "Generic Rank",
    926: "Generic Rank",
    932: "Generic Rank",
    939: "Generic Rank",
    946: "Generic Rank",
    953: "Generic Rank",
    959: "Generic Rank",
    966: "Generic Rank",
    973: "Generic Rank",
    979: "Generic Rank",
    986: "Generic Rank",
    993: "Generic Rank",
    1000: "Generic Rank",
  },
}
