import { AnimeThemeConfig } from "./types"
import { GiStarSwirl, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiCrystalBall, GiFlowerEmblem, GiSpellBook } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const weatheringWithYouTheme: AnimeThemeConfig = {
    id: "weathering-with-you",
    displayName: "Weathering with You",
    description: "Runaway Hodaka arrives in a rain-drenched Tokyo and meets Hina, a girl who can stop the rain and bring sunshine. As they build a life together, he must choose between the girl he loves and the world's weather.",
    cssVars: {
        "--color-brand-200": "185 220 255",
        "--color-brand-300": "128 185 250",
        "--color-brand-400": "72 145 238",
        "--color-brand-500": "28 108 215",
        "--color-brand-600": "8 72 172",
        "--color-brand-700": "2 44 128",
        "--color-brand-800": "0 20 80",
        "--color-brand-900": "0 8 40",
        "--color-brand-950": "0 2 18",
        "--brand": "28 108 215",
        "--background": "#000209",
        "--paper": "#000516",
        "--color-gray-950": "0 2 9",
        "--color-gray-900": "1 6 20",
        "--color-gray-800": "3 14 38",
        "--color-gray-700": "6 26 62",
        "--color-gray-600": "11 48 96",
        "--color-gray-500": "20 80 138",
        "--color-gray-400": "42 120 175",
        "--color-gray-300": "78 162 215",
        "--color-gray-200": "122 198 240",
        "--color-gray-100": "175 225 255",
        "--color-gray-50": "222 244 255",
    },
    sidebarOverrides: {
        "home": { icon: GiFlowerEmblem, label: "Rainy Tokyo" },
        "schedule": { icon: GiAlarmClock, label: "Weather Schedule" },
        "manga": { icon: LuBookOpen, label: "Sky Journal" },
        "lists": { icon: GiScrollUnfurled, label: "Sunshine List" },
        "discover": { icon: GiBullseye, label: "New Skies" },
        "torrent-list": { icon: GiCrystalBall, label: "Weather Cache" },
        "debrid": { icon: GiHeartKey, label: "Sky Vault" },
        "unmatched": { icon: GiStarSwirl, label: "Missing Sunshine" },
        "enmasse": { icon: GiResize, label: "Tokyo Storm" },
        "scan-summaries": { icon: TbReportSearch, label: "Weather Reports" },
        "auto-downloader": { icon: LuRss, label: "Sky Feed" },
        "community": { icon: GiSpellBook, label: "Weather Circle" },
        "achievements": { icon: GiTrophyCup, label: "Sunshine Trophies" },
        "milestones": { icon: LuFlag, label: "Sky Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Rain Alerts" },
        "theme-manager": { icon: GiPalette, label: "Sky Colors" },
        "extensions": { icon: BiExtension, label: "Weather Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Sky Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Hodaka Config" },
    },
    achievementNames: {
        "a_first_episode": "Arrived in Tokyo",
        "a_first_complete": "First Sunshine",
        "a_hundred_club": "Hundred Rainy Days",
        "a_binge_king": "Weathering Marathon",
        "a_completionist": "Choice Made",
        "a_mega_completionist": "Sunshine Girl",
        "a_loyal_fan": "Rain Fan",
        "a_zero_to_hero": "Runaway to Protector",
        "m_first_chapter": "First Drop",
        "m_completionist": "Full Sky Archive",
    },
    musicUrl: "",
    previewColors: {
        bg: "#000209",
        primary: "#1c6cd7",
        secondary: "#f0a020",
        accent: "#a8d8f8",
    },
    particleColor: "#4090e8",
    backgroundDim: 0.3,
    backgroundBlur: 22,
    milestoneNames: {
    1: "Generic Rank",
    7: "Generic Rank",
    14: "Generic Rank",
    21: "Generic Rank",
    27: "Generic Rank",
    34: "Generic Rank",
    41: "Generic Rank",
    47: "Generic Rank",
    54: "Generic Rank",
    61: "Generic Rank",
    68: "Generic Rank",
    74: "Generic Rank",
    81: "Generic Rank",
    88: "Generic Rank",
    94: "Generic Rank",
    101: "Generic Rank",
    108: "Generic Rank",
    114: "Generic Rank",
    121: "Generic Rank",
    128: "Generic Rank",
    135: "Generic Rank",
    141: "Generic Rank",
    148: "Generic Rank",
    155: "Generic Rank",
    161: "Generic Rank",
    168: "Generic Rank",
    175: "Generic Rank",
    182: "Generic Rank",
    188: "Generic Rank",
    195: "Generic Rank",
    202: "Generic Rank",
    208: "Generic Rank",
    215: "Generic Rank",
    222: "Generic Rank",
    228: "Generic Rank",
    235: "Generic Rank",
    242: "Generic Rank",
    249: "Generic Rank",
    255: "Generic Rank",
    262: "Generic Rank",
    269: "Generic Rank",
    275: "Generic Rank",
    282: "Generic Rank",
    289: "Generic Rank",
    296: "Generic Rank",
    302: "Generic Rank",
    309: "Generic Rank",
    316: "Generic Rank",
    322: "Generic Rank",
    329: "Generic Rank",
    336: "Generic Rank",
    342: "Generic Rank",
    349: "Generic Rank",
    356: "Generic Rank",
    363: "Generic Rank",
    369: "Generic Rank",
    376: "Generic Rank",
    383: "Generic Rank",
    389: "Generic Rank",
    396: "Generic Rank",
    403: "Generic Rank",
    409: "Generic Rank",
    416: "Generic Rank",
    423: "Generic Rank",
    430: "Generic Rank",
    436: "Generic Rank",
    443: "Generic Rank",
    450: "Generic Rank",
    456: "Generic Rank",
    463: "Generic Rank",
    470: "Generic Rank",
    477: "Generic Rank",
    483: "Generic Rank",
    490: "Generic Rank",
    497: "Generic Rank",
    503: "Generic Rank",
    510: "Generic Rank",
    517: "Generic Rank",
    523: "Generic Rank",
    530: "Generic Rank",
    537: "Generic Rank",
    544: "Generic Rank",
    550: "Generic Rank",
    557: "Generic Rank",
    564: "Generic Rank",
    570: "Generic Rank",
    577: "Generic Rank",
    584: "Generic Rank",
    591: "Generic Rank",
    597: "Generic Rank",
    604: "Generic Rank",
    611: "Generic Rank",
    617: "Generic Rank",
    624: "Generic Rank",
    631: "Generic Rank",
    637: "Generic Rank",
    644: "Generic Rank",
    651: "Generic Rank",
    658: "Generic Rank",
    664: "Generic Rank",
    671: "Generic Rank",
    678: "Generic Rank",
    684: "Generic Rank",
    691: "Generic Rank",
    698: "Generic Rank",
    704: "Generic Rank",
    711: "Generic Rank",
    718: "Generic Rank",
    725: "Generic Rank",
    731: "Generic Rank",
    738: "Generic Rank",
    745: "Generic Rank",
    751: "Generic Rank",
    758: "Generic Rank",
    765: "Generic Rank",
    772: "Generic Rank",
    778: "Generic Rank",
    785: "Generic Rank",
    792: "Generic Rank",
    798: "Generic Rank",
    805: "Generic Rank",
    812: "Generic Rank",
    818: "Generic Rank",
    825: "Generic Rank",
    832: "Generic Rank",
    839: "Generic Rank",
    845: "Generic Rank",
    852: "Generic Rank",
    859: "Generic Rank",
    865: "Generic Rank",
    872: "Generic Rank",
    879: "Generic Rank",
    886: "Generic Rank",
    892: "Generic Rank",
    899: "Generic Rank",
    906: "Generic Rank",
    912: "Generic Rank",
    919: "Generic Rank",
    926: "Generic Rank",
    932: "Generic Rank",
    939: "Generic Rank",
    946: "Generic Rank",
    953: "Generic Rank",
    959: "Generic Rank",
    966: "Generic Rank",
    973: "Generic Rank",
    979: "Generic Rank",
    986: "Generic Rank",
    993: "Generic Rank",
    1000: "Generic Rank",
  },
}
