import { AnimeThemeConfig } from "./types"
import { GiCrystalBall, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiStarSwirl, GiSpellBook, GiMusicalNotes } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const welcomeToNhkTheme: AnimeThemeConfig = {
    id: "welcome-to-nhk",
    displayName: "Welcome to the NHK",
    description: "Tatsuhiro Satou is a hikikomori convinced a conspiracy called NHK is ruining his life. When a mysterious girl named Misaki knocks on his door offering help, his shut-in existence is slowly, painfully dismantled.",
    cssVars: {
        "--color-brand-200": "200 225 200",
        "--color-brand-300": "148 198 148",
        "--color-brand-400": "95 168 98",
        "--color-brand-500": "52 135 55",
        "--color-brand-600": "22 100 25",
        "--color-brand-700": "6 68 8",
        "--color-brand-800": "1 40 2",
        "--color-brand-900": "0 18 0",
        "--color-brand-950": "0 7 0",
        "--brand": "52 135 55",
        "--background": "#010400",
        "--paper": "#030900",
        "--color-gray-950": "1 4 0",
        "--color-gray-900": "3 10 2",
        "--color-gray-800": "7 22 5",
        "--color-gray-700": "14 38 10",
        "--color-gray-600": "22 62 18",
        "--color-gray-500": "38 96 32",
        "--color-gray-400": "62 138 58",
        "--color-gray-300": "98 178 95",
        "--color-gray-200": "145 215 142",
        "--color-gray-100": "195 240 192",
        "--color-gray-50": "232 252 230",
    },
    sidebarOverrides: {
        "home": { icon: GiCrystalBall, label: "Satou's Apartment" },
        "schedule": { icon: GiAlarmClock, label: "Outside Schedule" },
        "manga": { icon: LuBookOpen, label: "Conspiracy Files" },
        "lists": { icon: GiScrollUnfurled, label: "Hikikomori List" },
        "discover": { icon: GiBullseye, label: "New Exits" },
        "torrent-list": { icon: GiMusicalNotes, label: "Game Cache" },
        "debrid": { icon: GiHeartKey, label: "Room Vault" },
        "unmatched": { icon: GiStarSwirl, label: "Unresolved Issues" },
        "enmasse": { icon: GiResize, label: "Outside World" },
        "scan-summaries": { icon: TbReportSearch, label: "Session Reports" },
        "auto-downloader": { icon: LuRss, label: "Misaki's Feed" },
        "community": { icon: GiSpellBook, label: "NHK Circle" },
        "achievements": { icon: GiTrophyCup, label: "Outside Trophies" },
        "milestones": { icon: LuFlag, label: "Recovery Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Door Knocks" },
        "theme-manager": { icon: GiPalette, label: "Room Colors" },
        "extensions": { icon: BiExtension, label: "Hikikomori Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Room Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Satou Config" },
    },
    achievementNames: {
        "a_first_episode": "Door Knocked",
        "a_first_complete": "First Outside Trip",
        "a_hundred_club": "Hundred Room Days",
        "a_binge_king": "NHK Marathon",
        "a_completionist": "Hikikomori Healed",
        "a_mega_completionist": "Welcome to Life",
        "a_loyal_fan": "Shut-in Fan",
        "a_zero_to_hero": "Hikikomori to Functioning",
        "m_first_chapter": "First Chapter Outside",
        "m_completionist": "Full Archive",
    },
    musicUrl: "",
    previewColors: {
        bg: "#010400",
        primary: "#348737",
        secondary: "#888888",
        accent: "#c8f0c0",
    },
    particleColor: "#50a850",
    backgroundDim: 0.35,
    backgroundBlur: 22,
    milestoneNames: {
    1: "Generic Rank",
    7: "Generic Rank",
    14: "Generic Rank",
    21: "Generic Rank",
    27: "Generic Rank",
    34: "Generic Rank",
    41: "Generic Rank",
    47: "Generic Rank",
    54: "Generic Rank",
    61: "Generic Rank",
    68: "Generic Rank",
    74: "Generic Rank",
    81: "Generic Rank",
    88: "Generic Rank",
    94: "Generic Rank",
    101: "Generic Rank",
    108: "Generic Rank",
    114: "Generic Rank",
    121: "Generic Rank",
    128: "Generic Rank",
    135: "Generic Rank",
    141: "Generic Rank",
    148: "Generic Rank",
    155: "Generic Rank",
    161: "Generic Rank",
    168: "Generic Rank",
    175: "Generic Rank",
    182: "Generic Rank",
    188: "Generic Rank",
    195: "Generic Rank",
    202: "Generic Rank",
    208: "Generic Rank",
    215: "Generic Rank",
    222: "Generic Rank",
    228: "Generic Rank",
    235: "Generic Rank",
    242: "Generic Rank",
    249: "Generic Rank",
    255: "Generic Rank",
    262: "Generic Rank",
    269: "Generic Rank",
    275: "Generic Rank",
    282: "Generic Rank",
    289: "Generic Rank",
    296: "Generic Rank",
    302: "Generic Rank",
    309: "Generic Rank",
    316: "Generic Rank",
    322: "Generic Rank",
    329: "Generic Rank",
    336: "Generic Rank",
    342: "Generic Rank",
    349: "Generic Rank",
    356: "Generic Rank",
    363: "Generic Rank",
    369: "Generic Rank",
    376: "Generic Rank",
    383: "Generic Rank",
    389: "Generic Rank",
    396: "Generic Rank",
    403: "Generic Rank",
    409: "Generic Rank",
    416: "Generic Rank",
    423: "Generic Rank",
    430: "Generic Rank",
    436: "Generic Rank",
    443: "Generic Rank",
    450: "Generic Rank",
    456: "Generic Rank",
    463: "Generic Rank",
    470: "Generic Rank",
    477: "Generic Rank",
    483: "Generic Rank",
    490: "Generic Rank",
    497: "Generic Rank",
    503: "Generic Rank",
    510: "Generic Rank",
    517: "Generic Rank",
    523: "Generic Rank",
    530: "Generic Rank",
    537: "Generic Rank",
    544: "Generic Rank",
    550: "Generic Rank",
    557: "Generic Rank",
    564: "Generic Rank",
    570: "Generic Rank",
    577: "Generic Rank",
    584: "Generic Rank",
    591: "Generic Rank",
    597: "Generic Rank",
    604: "Generic Rank",
    611: "Generic Rank",
    617: "Generic Rank",
    624: "Generic Rank",
    631: "Generic Rank",
    637: "Generic Rank",
    644: "Generic Rank",
    651: "Generic Rank",
    658: "Generic Rank",
    664: "Generic Rank",
    671: "Generic Rank",
    678: "Generic Rank",
    684: "Generic Rank",
    691: "Generic Rank",
    698: "Generic Rank",
    704: "Generic Rank",
    711: "Generic Rank",
    718: "Generic Rank",
    725: "Generic Rank",
    731: "Generic Rank",
    738: "Generic Rank",
    745: "Generic Rank",
    751: "Generic Rank",
    758: "Generic Rank",
    765: "Generic Rank",
    772: "Generic Rank",
    778: "Generic Rank",
    785: "Generic Rank",
    792: "Generic Rank",
    798: "Generic Rank",
    805: "Generic Rank",
    812: "Generic Rank",
    818: "Generic Rank",
    825: "Generic Rank",
    832: "Generic Rank",
    839: "Generic Rank",
    845: "Generic Rank",
    852: "Generic Rank",
    859: "Generic Rank",
    865: "Generic Rank",
    872: "Generic Rank",
    879: "Generic Rank",
    886: "Generic Rank",
    892: "Generic Rank",
    899: "Generic Rank",
    906: "Generic Rank",
    912: "Generic Rank",
    919: "Generic Rank",
    926: "Generic Rank",
    932: "Generic Rank",
    939: "Generic Rank",
    946: "Generic Rank",
    953: "Generic Rank",
    959: "Generic Rank",
    966: "Generic Rank",
    973: "Generic Rank",
    979: "Generic Rank",
    986: "Generic Rank",
    993: "Generic Rank",
    1000: "Generic Rank",
  },
}
