import { AnimeThemeConfig } from "./types"
import { GiCrystalBall, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiStarSwirl, GiSpellBook, GiMusicalNotes } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const welcomeToNhkTheme: AnimeThemeConfig = {
    id: "welcome-to-nhk",
    displayName: "Welcome to the NHK",
    description: "Tatsuhiro Satou is a hikikomori convinced a conspiracy called NHK is ruining his life. When a mysterious girl named Misaki knocks on his door offering help, his shut-in existence is slowly, painfully dismantled.",
    cssVars: {
        "--color-brand-200": "200 225 200",
        "--color-brand-300": "148 198 148",
        "--color-brand-400": "95 168 98",
        "--color-brand-500": "52 135 55",
        "--color-brand-600": "22 100 25",
        "--color-brand-700": "6 68 8",
        "--color-brand-800": "1 40 2",
        "--color-brand-900": "0 18 0",
        "--color-brand-950": "0 7 0",
        "--brand": "52 135 55",
        "--background": "#010400",
        "--paper": "#030900",
        "--color-gray-950": "1 4 0",
        "--color-gray-900": "3 10 2",
        "--color-gray-800": "7 22 5",
        "--color-gray-700": "14 38 10",
        "--color-gray-600": "22 62 18",
        "--color-gray-500": "38 96 32",
        "--color-gray-400": "62 138 58",
        "--color-gray-300": "98 178 95",
        "--color-gray-200": "145 215 142",
        "--color-gray-100": "195 240 192",
        "--color-gray-50": "232 252 230",
    },
    sidebarOverrides: {
        "home": { icon: GiCrystalBall, label: "Satou's Apartment" },
        "schedule": { icon: GiAlarmClock, label: "Outside Schedule" },
        "manga": { icon: LuBookOpen, label: "Conspiracy Files" },
        "lists": { icon: GiScrollUnfurled, label: "Hikikomori List" },
        "discover": { icon: GiBullseye, label: "New Exits" },
        "torrent-list": { icon: GiMusicalNotes, label: "Game Cache" },
        "debrid": { icon: GiHeartKey, label: "Room Vault" },
        "unmatched": { icon: GiStarSwirl, label: "Unresolved Issues" },
        "enmasse": { icon: GiResize, label: "Outside World" },
        "scan-summaries": { icon: TbReportSearch, label: "Session Reports" },
        "auto-downloader": { icon: LuRss, label: "Misaki's Feed" },
        "community": { icon: GiSpellBook, label: "NHK Circle" },
        "achievements": { icon: GiTrophyCup, label: "Outside Trophies" },
        "milestones": { icon: LuFlag, label: "Recovery Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Door Knocks" },
        "theme-manager": { icon: GiPalette, label: "Room Colors" },
        "extensions": { icon: BiExtension, label: "Hikikomori Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Room Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Satou Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "Door Knocked",
        "a_episode_counter": "Hikikomori Mark",
        "a_episode_titan": "Misaki Relic",
        "a_hours_invested": "Satou Proof",
        "a_time_lord": "Tatsuhiro Satou Decree",
        "a_anime_collector": "Outside World Catalogue",
        "a_library_legend": "Outside World Library",
        "a_first_complete": "First Outside Trip",
        "a_hundred_club": "Hundred Room Days",
        "a_first_day": "Trip Seal",
        "a_first_rating": "Marathon Appraisal",
        "a_ten_thousand_min": "Welcome Life Standard",
        "a_season_veteran": "Marathon Library",
        "a_year_explorer": "Trip Map",
        "a_century_watcher": "Door Ledger",
        "a_five_hundred_eps": "Welcome Dominion",
        "a_thousand_eps": "NHK Record",
        "a_watching_ten": "Exits Acclaim",
        "a_ptw_hoarder": "Outside Library",
        "a_dropped_honesty": "Shut Summit",
        "a_five_thousand_eps": "Knocked Warrant",
        "a_ten_completed": "Misaki's Afterglow",
        "a_fifty_completed": "Room Vault Ascension",
        "a_five_hundred_completed": "Misaki's Clear",
        "a_mean_score_tracker": "Door Knocked Verdict",
        "a_unique_studios": "Archive Collection",
        "a_days_spent_watching": "Archive Dominion",
        "a_all_status": "Outside World Testament",
        "a_first_favorite": "Hikikomori Cabinet",
        "a_favorites_collector": "Room Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Hikikomori Functioning Drive",
        "a_marathon_runner": "Door Gauntlet",
        "a_weekend_warrior": "Hikikomori Healed Ordeal",
        "a_non_stop": "Healed Fever",
        "a_one_more_episode": "Session Mantle",
        "a_speed_run": "Recovery Vigil",
        "a_double_feature": "Game Crown",
        "a_triple_threat": "NHK Circle Record",
        "a_five_a_day": "Door Knocked Accord",
        "a_back_to_back": "Satou's Apartment Surge",
        "a_seasonal_binge": "Marathon Cascade",
        "a_cour_crusher": "Archive Ordeal",
        "a_half_day_watch": "Hikikomori Crown",
        "a_full_day_watch": "Room Pinnacle",
        "a_power_weekend": "Outside Run",
        "a_binge_king": "NHK Marathon",
        "a_no_sleep": "Fan Vigil",
        "a_entire_season": "NHK Marathon Library",
        "a_seven_day_challenge": "Room Mark",
        "a_hundred_day_binge": "Welcome Life Surge",
        "a_genre_binge": "NHK Marathon Binge",
        "a_studio_binge": "Satou Fever",
        "a_season_sweep": "Fan Codex",
        "a_forty_eight_hour": "Fan Overture",
        "a_ep_counter_day": "Outside Trip Aegis",
        "a_multi_series_binge": "Outside Trophies Streak",
        "a_midnight_binge": "NHK Circle Cascade",
        "a_new_year_binge": "Outside Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "NHK Marathon Action",
        "a_genre_adventure": "Marathon Adventure",
        "a_genre_comedy": "Exits Comedy",
        "a_genre_drama": "Session Drama",
        "a_genre_fantasy": "Room Vault Fantasy",
        "a_genre_horror": "Trip Horror",
        "a_genre_mystery": "Outside World Mystery",
        "a_genre_romance": "Exits Romance",
        "a_genre_scifi": "Door Knocked Sci-Fi",
        "a_genre_sol": "Outside Trophies Slice",
        "a_genre_sports": "Hikikomori Healed Sports",
        "a_genre_supernatural": "Room Vault Supernatural",
        "a_genre_thriller": "Door Knocked Thriller",
        "a_genre_mecha": "Room Mecha",
        "a_genre_music": "Door Knocked Music",
        "a_genre_psychological": "Archive Psychological",
        "a_genre_ecchi": "NHK Circle Ecchi",
        "a_genre_mahou_shoujo": "Conspiracy Magic Shoujo",
        "a_tag_isekai": "Room Vault Isekai",
        "a_tag_harem": "Trip Harem",
        "a_tag_bl": "Life Bl",
        "a_tag_gl": "Game Gl",
        "a_tag_historical": "Archive Historical",
        "a_tag_military": "Welcome Military",
        "a_tag_school": "Marathon School",
        "a_tag_martial_arts": "Recovery Martial Arts",
        "a_tag_vampire": "Outside World Vampire",
        "a_tag_samurai": "Tatsuhiro Satou Samurai",
        "a_tag_space": "Exits Space",
        "a_tag_parody": "Marathon Parody",
        "a_tag_idol": "Outside Idol",
        "a_tag_post_apocalyptic": "Unresolved Issues Post Apocalyptic",
        "a_tag_cyberpunk": "Welcome To The NHK Cyberpunk",
        "a_tag_shounen": "NHK Marathon Shounen",
        "a_tag_seinen": "Healed Seinen",
        "a_tag_shoujo": "Outside World Shoujo",
        "a_tag_josei": "Session Josei",
        "a_tag_survival": "Door Knocks Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "Hikikomori Healed",
        "a_mega_completionist": "Welcome to Life",
        "a_completion_rate_50": "Outside World Return",
        "a_completion_rate_75": "Life Crown",
        "a_completion_rate_90": "NHK Circle Resolution",
        "a_no_drop": "Session Decree",
        "a_long_runner_complete": "Functioning Clear",
        "a_sequel_chain": "Recovery Insignia",
        "a_clean_list": "Hikikomori Healed Relic",
        "a_from_ptw": "Room Vault Index",
        "a_rewatch_master": "Outside Return",
        "a_short_complete": "Game Endgame",
        "a_same_day_start_finish": "Door Knocked Pinnacle",
        "a_revival": "Archive Insignia",
        "a_zero_to_hero": "Hikikomori to Functioning",
        "a_five_genre_complete": "NHK Circle A Five Genre",
        "a_full_franchise": "Fan Chronicle",
        "a_batch_complete": "Knocked Crown",
        "a_paused_to_done": "Outside World Aegis",
        "a_completion_spree": "Recovery Triumph",
        "a_multi_rewatch": "Door Triumph",
        "a_dropped_recovery": "Recovery Conquest",
        "a_ten_perfect_scores": "Knocked Acclaim",
        "a_seasonal_clear": "NHK Codex",
        "a_complete_genre_span": "Archive A Complete Genre Span",
        "a_monthly_completions": "Welcome Life Afterglow",
        "a_yearly_completions": "Conspiracy Epilogue",
        "a_rapid_complete": "Satou Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Shut-in Fan",
        "a_studio_devotee": "Session Treasury",
        "a_rewatcher": "Welcome To The NHK Closure",
        "a_triple_rewatch": "NHK Coda",
        "a_annual_tradition": "Archive Proof",
        "a_director_fan": "Knocked Trial",
        "a_voice_actor_fan": "Door Knocks Crown",
        "a_ost_lover": "Door Knocked Seal",
        "a_source_reader": "Functioning Cabinet",
        "a_waiting_weekly": "Satou's Apartment Clock",
        "a_childhood_revisit": "Session Seal",
        "a_saga_tracker": "Game Standard",
        "a_genre_loyalty": "Fan Loyalty",
        "a_decade_watcher": "Shut Banner",
        "a_adaptation_hunter": "Life Trial",
        "a_original_anime_fan": "NHK Circle Testament",
        "a_long_commitment": "NHK Marathon Mark",
        "a_perfect_attendance": "Exits Standard",
        "a_favorite_studio_5": "Door Knocks Library",
        "a_complete_catalog": "Door Knocks Seal",
        "a_franchise_collector": "Shut Fan Archive",
        "a_airing_follower": "Game Signal",
        "a_genre_master": "Outside Trophies Master",
        "a_staff_follower": "Door Knocks Oath",
        "a_multi_season_fan": "Unresolved Issues Hoard",
        "a_format_diversity": "Healed Cache",
        "a_year_dedication": "Outside Tenure",
        "a_season_dedication": "Recovery Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "NHK Explorer",
        "a_studio_hopper": "Functioning Collection",
        "a_tag_explorer": "Door Knocked Explorer",
        "a_decade_hopper": "Life Chronicle",
        "a_hidden_gem": "Unresolved Issues Warrant",
        "a_popular_taste": "Outside Decree",
        "a_retro_appreciator": "Satou Aegis",
        "a_modern_viewer": "Door Knocked Pinnacle Pinnacle",
        "a_cross_demographic": "Healed Pinnacle",
        "a_underdog_fan": "Hikikomori Trial",
        "a_variety_week": "Unresolved Issues Horizon",
        "a_foreign_cinema": "Shut Expedition",
        "a_classic_connoisseur": "Room Vault Glimpse",
        "a_every_season": "Exits Archive",
        "a_award_winner": "Life Insignia",
        "a_niche_explorer": "Conspiracy Horizon",
        "a_global_anime": "Healed Crown",
        "a_cult_classic": "Door Knocked Map",
        "a_random_pick": "Hikikomori Healed Decree",
        "a_new_genre_month": "Game A New Genre Month",
        "a_seasonal_completionist": "NHK Marathon Summit",
        "a_unpopular_opinion": "NHK Standard",
        "a_top_rated_viewer": "Functioning Seal",
        "a_source_variety": "Tatsuhiro Satou Storehouse",
        "a_low_score_brave": "Welcome To The NHK Measure",
        "a_upcoming_watcher": "Knocked Seal",
        "a_short_series_explorer": "Healed Expedition",
        "a_long_series_explorer": "NHK Circle Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Shut Fan Insignia",
        "a_early_bird": "Healed Banner",
        "a_lunch_break": "Misaki's Trial",
        "a_golden_hour": "Recovery Tenure",
        "a_four_am_club": "Tatsuhiro Satou Gathering",
        "a_witching_hour": "Fan Tenure",
        "a_new_year_watch": "Functioning Season",
        "a_midnight_premiere": "Outside Devotion",
        "a_all_hours": "Recovery Seal",
        "a_dawn_warrior": "Outside Trophies Aegis",
        "a_afternoon_delight": "Tatsuhiro Satou Proof",
        "a_prime_time": "Door Knocked Insignia",
        "a_workday_watcher": "Satou's Apartment Pinnacle",
        "a_sunday_marathon": "Life Momentum",
        "a_rainy_day": "Trip Relic",
        "a_morning_routine": "Welcome Promise",
        "a_night_shift": "NHK Circle Aegis",
        "a_twilight_zone": "Room Ledger",
        "a_seasonal_premier": "Misaki's Cabinet",
        "a_clock_collector": "Hikikomori Repository",
        "a_weekend_binge_hours": "NHK Circle Streak",
        "a_late_night_regular": "Hikikomori Functioning Dominion",
        "a_sunrise_watcher": "Door Knocked Relic",
        "a_holiday_watcher": "Misaki Pact",
        "a_every_day_of_week": "Welcome To The NHK Ledger",
        "a_monthly_hours": "Knocked Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Exits Record",
        "a_party_host": "Healed Record",
        "a_social_butterfly": "Knocked Company",
        "a_group_binge": "Shut Fan Sprint",
        "a_party_regular": "NHK Marathon Chronicle",
        "a_sync_viewer": "Door Knocks Standard",
        "a_commentator": "Hikikomori Record",
        "a_party_marathon": "Tatsuhiro Satou Vigil",
        "a_full_house": "Archive Trial",
        "a_community_pillar": "Exits Alliance",
        "a_watch_party_streak": "Unresolved Issues Vigil",
        "a_diverse_party": "Door Seal",
        "a_late_night_party": "Session Testament",
        "a_party_veteran": "Archive Testament",
        "a_genre_party": "Misaki's Party",
        "a_weekly_party": "NHK Calendar",
        "a_silent_viewer": "Outside Trip Mantle",
        "a_recommendation_giver": "Game Network",
        "a_party_completionist": "Session Coda",
        "a_social_scorer": "Outside Trophies Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Outside Trip Proof",
        "a_fibonacci": "Outside Dominion",
        "a_palindrome_day": "Outside Trophies Relic",
        "a_binary_day": "Knocked Mark",
        "a_full_moon": "Exits Insignia",
        "a_leap_year": "Shut Devotion",
        "a_time_traveler": "Welcome To The NHK Record",
        "a_genre_clash": "Tatsuhiro Satou Clash",
        "a_triple_seven": "Marathon Testament",
        "a_thousand_complete": "NHK Circle Epilogue",
        "a_pi_episodes": "Session Crown",
        "a_synchronicity": "Unresolved Issues Anchor",
        "a_world_record": "Tatsuhiro Satou Warrant",
        "a_nice": "Outside Trophies Chronicle",
        "a_power_level": "Game Testament",
        "a_answer_42": "Outside Trophies Standard",
        "a_square_number": "Unresolved Issues Decree",
        "a_prime_count": "Functioning Seal Seal",
        "a_matching_date": "Shut Fan Mantle",
        "a_century_episode": "Outside Trip Mark",
        "a_double_digits": "Life Testament",
        "a_one_two_three": "Shut Crown",
        "a_lucky_seven": "Welcome Crown",
        "a_all_tens": "Misaki's Criterion",
        "a_exact_hundred_eps": "Shut Standard",
        "a_year_match_count": "Shut Clock",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "NHK Marathon Crown",
        "a_movie_buff": "Shut Fan Mark",
        "a_ova_hunter": "Misaki's Standard",
        "a_ona_explorer": "Door Knocks Secret",
        "a_special_watcher": "Welcome Life Relic",
        "a_short_king": "Door Knocked Crown",
        "a_variety_pack": "Archive Inquiry",
        "a_film_festival": "Misaki Chronicle",
        "a_music_video": "NHK Marathon Chronicle Chronicle",
        "a_tv_short": "Shut Fan Record",
        "a_movie_marathon": "Shut Fan Gauntlet",
        "a_double_length": "Welcome To The NHK Crown",
        "a_anthology": "Shut Aegis",
        "a_mini_series": "Recovery Decree",
        "a_theatrical": "Door Accord",
        "a_format_master": "Archive Vault",
        "a_long_movie": "NHK Insignia",
        "a_back_catalog": "Welcome Standard",
        "a_cm_watcher": "Outside Aegis",
        "a_pv_collector": "Room Storehouse",
        "a_format_balance": "Door Vault",
        "a_episodic_master": "Hikikomori Healed Standard",
        "a_sequel_movie": "Hikikomori Functioning Pinnacle",
        "a_recap_watcher": "Outside World Testament Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Recovery Devotion",
        "a_mega_streak": "Conspiracy Streak",
        "a_weekly_warrior": "Welcome Season",
        "a_monthly_watcher": "Misaki Calendar",
        "a_comeback": "Marathon Decree",
        "a_weekend_streak": "Satou's Apartment Passage",
        "a_no_zero_days": "Outside Warrant",
        "a_iron_will": "Outside Seal",
        "a_habit_formed": "Trip Warrant",
        "a_consistent_pace": "Outside World Measure",
        "a_year_long": "Tatsuhiro Satou Season",
        "a_double_streak": "Life Watch",
        "a_streak_recovery": "Exits Season",
        "a_daily_minimum": "Misaki Focus",
        "a_winter_streak": "Satou's Apartment Watch",
        "a_summer_streak": "Welcome Life Resolve",
        "a_morning_streak": "NHK Clock",
        "a_night_streak": "Game Constancy",
        "a_unbreakable": "Outside Proof",
        "a_eternal_flame": "Life Standard",
        "a_completion_streak": "Session Return",
        "a_rating_streak": "Trip Balance",
        "a_multi_ep_streak": "Unresolved Issues Ritual",
        "a_genre_streak": "Knocked Streak Signature",
        "a_studio_streak": "Welcome Life Cabinet",
        "a_perfect_week": "Satou Relic",

        // ── ANIME SCORING ──
        "a_critic": "Welcome Scrutiny",
        "a_perfect_ten": "Outside World Audit",
        "a_harsh_critic": "Misaki's Gauge",
        "a_fair_judge": "Session Balance",
        "a_generous_spirit": "Trip Pinnacle",
        "a_score_all": "Door Knocks Criterion",
        "a_wide_range": "Trip Ledger",
        "a_controversial": "Welcome Decree",
        "a_consistent_scorer": "Hikikomori Functioning Verdict",
        "a_score_sniper": "Outside World Score",
        "a_evolving_taste": "Functioning Testament",
        "a_bell_curve": "Outside Trip Insignia",
        "a_picky_watcher": "Outside Trip Warrant",
        "a_100_rated": "Room Warrant",
        "a_500_rated": "Misaki Pinnacle",
        "a_mediocre_majority": "Satou Canon",
        "a_rating_spree": "Tatsuhiro Satou Review",
        "a_score_variance": "Welcome To The NHK Score",
        "a_masterpiece_hunter": "Door Knocks Banner",
        "a_contrarian": "Door Record",
        "a_optimist": "Hikikomori Ledger",
        "a_score_distributor": "Hikikomori Functioning Appraisal",
        "a_genre_critic": "Misaki's Critic",
        "a_mean_above_8": "NHK Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "Tatsuhiro Satou Resolve",
        "a_valentines_weeb": "NHK Marathon Vow",
        "a_pi_day": "Game Trial",
        "a_april_fools": "NHK Circle Devotion",
        "a_international_anime_day": "Session Pinnacle",
        "a_star_wars_day": "Functioning Chronicle",
        "a_summer_solstice": "Hikikomori Healed Calendar",
        "a_tanabata": "Life Focus",
        "a_friday_13th": "Misaki's Relic",
        "a_halloween_spirit": "Healed Vow",
        "a_thanksgiving_binge": "NHK Run",
        "a_christmas_special": "Welcome To The NHK Season",
        "a_new_years_eve": "Archive Pilgrimage",
        "a_birthday_watch": "Conspiracy Vow",
        "a_holiday_marathon": "Door Knocks Overture",
        "a_independence_day": "Fan Banner",
        "a_culture_day": "Room Vault Insignia",
        "a_spring_equinox": "NHK Marathon Decree",
        "a_earth_day": "Misaki's Record",
        "a_labor_day": "Outside World Seal",
        "a_winter_solstice": "Exits Pilgrimage",
        "a_anime_birthday": "NHK Marathon Pilgrimage",
        "a_every_holiday": "Room Vault Resolve",
        "a_consecutive_holidays": "Fan Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Trip Rank",
        "a_meta_collector": "Hikikomori Healed Hoard",
        "a_meta_category_starter": "Functioning Badge",
        "a_meta_tier_climber": "Fan Glyph",
        "a_meta_tier_max": "Door Knocked Writ",
        "a_meta_xp_earner": "Outside Trip Emblem",
        "a_meta_difficulty_easy": "Shut Mechanism",
        "a_meta_difficulty_hard": "Outside Writ",
        "a_meta_unlock_spree": "Satou Panel",
        "a_meta_completionist": "Shut Fan Fulfillment",
        "a_meta_diverse": "Outside Trophies Emblem",
        "a_meta_dominator": "NHK Marathon Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Chapter Outside",
        "m_chapter_counter": "Door Knocks Pinnacle",
        "m_chapter_titan": "Unresolved Issues Relic",
        "m_reading_hours": "Session Relic",
        "m_reading_time_lord": "Satou's Apartment Pinnacle Pinnacle",
        "m_manga_collector": "Welcome Ledger",
        "m_library_legend": "Outside Reliquary",
        "m_first_complete": "Door Knocks Triumph",
        "m_hundred_club": "NHK Marathon Network",
        "m_first_day": "Recovery Dawn",
        "m_first_rating": "NHK Circle Eye",
        "m_ten_thousand_pages": "Satou Gauge",
        "m_volume_collector": "Misaki's Storehouse",
        "m_year_explorer": "Marathon Quest",
        "m_century_reader": "Conspiracy Dominion",
        "m_five_hundred_ch": "Hikikomori Healed Ledger",
        "m_thousand_ch": "Welcome Life Testament",
        "m_reading_ten": "Misaki's Appraisal",
        "m_ptr_hoarder": "Misaki Index",
        "m_dropped_honesty": "Door Knocked Summit",
        "m_season_reader": "Door Treasury",
        "m_active_reader": "Welcome Life Trial",
        "m_five_thousand_ch": "NHK Legend",
        "m_ten_completed": "Hikikomori Resolution",
        "m_fifty_completed": "Room Vault Harvest",
        "m_five_hundred_completed": "Session Legacy",
        "m_mean_score_tracker": "NHK Circle Audit",
        "m_unique_authors": "NHK Marathon Reserve",
        "m_all_status": "Outside Trophies Testament",
        "m_first_favorite": "Outside World Cache",
        "m_favorites_collector": "Marathon Shelf",
        "m_days_spent_reading": "Life Decree",

        // ── MANGA BINGE ──
        "m_binge_reader": "Hikikomori Functioning Streak",
        "m_marathon_reader": "Outside Trip Rush",
        "m_weekend_reader": "NHK Circle Run",
        "m_non_stop_reading": "Outside Trip Gauntlet",
        "m_one_more_chapter": "Session Testament Testament",
        "m_speed_read": "Welcome Life Drive",
        "m_double_story": "Door Knocks Banner Banner",
        "m_triple_read": "Hikikomori Healed Record",
        "m_five_a_day": "Satou Insignia",
        "m_chapter_chain": "Outside Accord",
        "m_volume_binge": "NHK Circle Drive",
        "m_power_reader": "Hikikomori Healed Seal",
        "m_half_day_read": "Marathon Aegis",
        "m_full_day_read": "Life Aegis",
        "m_power_weekend": "Archive Streak",
        "m_binge_king": "Outside Trip Momentum",
        "m_no_sleep_read": "Healed Rush",
        "m_full_series_rush": "Session Cascade",
        "m_seven_day_challenge": "Functioning Warrant",
        "m_hundred_day_read": "Outside Relic",
        "m_volume_rush": "Welcome To The NHK Gauntlet",
        "m_series_sweep": "Functioning Trial",
        "m_genre_binge": "Outside Trophies Binge",
        "m_author_binge": "Outside Trip Surge",
        "m_chapter_counter_day": "Satou Ledger",
        "m_multi_series_binge": "Room Vault Charge",
        "m_midnight_binge": "Trip Tempest",
        "m_new_year_binge": "Unresolved Issues Passage",
        "m_forty_eight_hour": "Conspiracy Rally",
        "m_oneshot_binge": "Functioning Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Knocked Action",
        "m_genre_adventure": "Room Vault Adventure",
        "m_genre_comedy": "Welcome Life Comedy",
        "m_genre_drama": "Shut Fan Drama",
        "m_genre_fantasy": "Satou's Apartment Fantasy",
        "m_genre_horror": "Hikikomori Healed Horror",
        "m_genre_mystery": "NHK Marathon Mystery",
        "m_genre_romance": "Game Romance",
        "m_genre_scifi": "Shut Fan Sci-Fi",
        "m_genre_sol": "Door Knocks Slice",
        "m_genre_sports": "Welcome To The NHK Sports",
        "m_genre_supernatural": "Door Supernatural",
        "m_genre_thriller": "NHK Thriller",
        "m_genre_psychological": "Hikikomori Functioning Psychological",
        "m_genre_isekai": "Room Isekai",
        "m_genre_shounen": "Welcome Shounen",
        "m_genre_ecchi": "Hikikomori Functioning Ecchi",
        "m_genre_mahou_shoujo": "Misaki Magic Shoujo",
        "m_genre_mecha": "NHK Circle Mecha",
        "m_genre_music": "Game Music",
        "m_tag_isekai_new": "Misaki's Isekai New",
        "m_tag_harem": "Tatsuhiro Satou Harem",
        "m_tag_bl": "Door Bl",
        "m_tag_gl": "Life Gl",
        "m_tag_historical": "Door Knocked Historical",
        "m_tag_military": "Shut Fan Military",
        "m_tag_school": "Archive School",
        "m_tag_martial_arts": "NHK Martial Arts",
        "m_tag_vampire": "Healed Vampire",
        "m_tag_samurai": "Conspiracy Samurai",
        "m_tag_space": "Satou Space",
        "m_tag_parody": "Healed Parody",
        "m_tag_idol": "Tatsuhiro Satou Idol",
        "m_tag_post_apocalyptic": "Functioning Post Apocalyptic",
        "m_tag_cyberpunk": "Shut Fan Cyberpunk",
        "m_tag_shoujo": "Welcome Life Shoujo",
        "m_tag_survival": "Marathon Survival",
        "m_tag_cooking": "Game Cooking",
        "m_tag_medical": "Life Medical",
        "m_tag_villainess": "Outside World Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Archive",
        "m_mega_completionist": "Hikikomori Completion",
        "m_completion_rate_50": "Tatsuhiro Satou Return",
        "m_completion_rate_75": "Shut Fan Ascension",
        "m_completion_rate_90": "Trip Resolution",
        "m_no_drop": "Outside Trip Decree",
        "m_long_runner_complete": "Hikikomori Clear",
        "m_sequel_chain": "Outside World Seal Seal",
        "m_clean_list": "Unresolved Issues Relic Relic",
        "m_from_ptr": "Functioning Accord",
        "m_reread_master": "Conspiracy Trial",
        "m_oneshot_complete": "Hikikomori Functioning Ascension",
        "m_same_day_start_finish": "Unresolved Issues Crown",
        "m_revival": "Unresolved Issues Accord",
        "m_zero_to_hundred": "Room Banner",
        "m_five_genre_complete": "Door Knocked M Five Genre",
        "m_full_collection": "Door Knocks Proof",
        "m_batch_complete": "Marathon Testament Testament",
        "m_paused_to_done": "Life Standard Standard",
        "m_completion_spree": "Fan Triumph",
        "m_format_completionist": "Welcome To The NHK Testament",
        "m_catch_up": "NHK Chronicle",
        "m_multi_reread": "Shut Banner Banner",
        "m_dropped_recovery": "Satou's Apartment Conquest",
        "m_ten_perfect_scores": "Game Judgment",
        "m_complete_genre_span": "Hikikomori M Complete Genre Span",
        "m_monthly_completions": "Welcome Life Return",
        "m_yearly_completions": "Satou Epilogue",
        "m_rapid_complete": "Room Vault Finale",
        "m_author_complete": "Shut Fan Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Functioning Legacy",
        "m_mangaka_lover": "Misaki's Standard Standard",
        "m_rereader": "Outside World Relic",
        "m_triple_reread": "Life Testament Testament",
        "m_annual_reread": "Unresolved Issues Banner",
        "m_publisher_fan": "Room Vault Mark",
        "m_artist_fan": "Exits Insignia Insignia",
        "m_adaptation_compare": "Conspiracy Insignia",
        "m_source_material_fan": "Welcome Life Cache",
        "m_waiting_weekly": "Game Streak",
        "m_classic_reader": "Hikikomori Functioning Lantern",
        "m_saga_reader": "Door Crown",
        "m_genre_loyalty": "Satou's Apartment Loyalty",
        "m_decade_reader": "Misaki's Warrant",
        "m_ln_adaptation": "Outside Trip Mark Mark",
        "m_original_work": "Outside World Standard",
        "m_long_commitment": "Unresolved Issues Standard",
        "m_up_to_date": "Tatsuhiro Satou Warrant Warrant",
        "m_favorite_mangaka": "Room Vault Treasury",
        "m_complete_portfolio": "Knocked Triumph",
        "m_franchise_collector": "Recovery Archive",
        "m_serialization_follower": "Outside Handshake",
        "m_genre_master": "Tatsuhiro Satou Master",
        "m_multi_series_author": "Outside Trophies Insignia",
        "m_format_diversity": "Hikikomori Functioning Shelf",
        "m_year_dedication": "Welcome To The NHK Tenure",
        "m_ongoing_follower": "Outside World Fellowship",
        "m_genre_loyalty_50": "Life Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Archive Explorer",
        "m_publisher_hopper": "Hikikomori Record Record",
        "m_tag_explorer": "Hikikomori Healed Explorer",
        "m_decade_hopper": "Knocked Chronicle",
        "m_hidden_gem": "Conspiracy Mark",
        "m_popular_taste": "NHK Marathon Mantle",
        "m_retro_reader": "Hikikomori Healed Testament",
        "m_modern_reader": "Door Knocked Seal Seal",
        "m_cross_demographic": "Outside Crown",
        "m_underdog_fan": "NHK Circle Accord",
        "m_variety_week": "Shut Horizon",
        "m_manhwa_reader": "Shut Proof",
        "m_manhua_reader": "Shut Mantle",
        "m_classic_connoisseur": "Shut Glimpse",
        "m_award_winner": "Knocked Seal Seal",
        "m_niche_explorer": "Welcome To The NHK Horizon",
        "m_world_manga": "NHK Chronicle Chronicle",
        "m_cult_classic": "Hikikomori Functioning Map",
        "m_random_pick": "Welcome To The NHK Standard",
        "m_new_genre_month": "Room M New Genre Month",
        "m_year_completionist": "NHK Marathon Fulfillment",
        "m_unpopular_opinion": "Outside World Aegis Aegis",
        "m_top_rated_reader": "Trip Pinnacle Pinnacle",
        "m_source_variety": "Session Catalogue",
        "m_low_score_brave": "NHK Score",
        "m_short_manga_explorer": "Hikikomori Healed Compass",
        "m_long_manga_explorer": "Shut Fan Survey",
        "m_serialization_explorer": "Hikikomori Road",

        // ── MANGA TIME ──
        "m_night_owl": "Welcome To The NHK Accord",
        "m_early_bird": "Marathon Banner",
        "m_lunch_reader": "Game Relic",
        "m_commute_reader": "Room Vault Tenure",
        "m_four_am_club": "Outside Fellowship",
        "m_new_year_read": "Outside World Pact",
        "m_all_hours": "Door Knocked Accord Accord",
        "m_prime_time_reader": "Misaki's Banner",
        "m_workday_reader": "Unresolved Issues Accord Accord",
        "m_sunday_read": "Hikikomori Standard",
        "m_morning_routine": "Satou Discipline",
        "m_night_shift_reader": "Room Accord",
        "m_seasonal_premier_read": "Conspiracy Storehouse",
        "m_clock_collector": "Game Reserve",
        "m_late_night_horror": "Welcome Life Mark",
        "m_afternoon_reader": "Session Mantle Mantle",
        "m_golden_hour_reader": "Fan Observance",
        "m_dawn_reader": "Door Knocked Mantle",
        "m_twilight_reader": "NHK Marathon Decree Decree",
        "m_midnight_start": "Game Routine",
        "m_weekend_binge_hours": "Conspiracy Momentum",
        "m_late_night_regular": "NHK Marathon Accord",
        "m_sunrise_reader": "Healed Record Record",
        "m_every_day_of_week": "Welcome Life Seal",
        "m_monthly_hours": "Satou Vigil",
        "m_bedtime_reader": "Satou Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Shut Mantle Mantle",
        "m_webtoon_reader": "Exits Mark",
        "m_full_color": "Game Accord",
        "m_doujin_reader": "Life Record",
        "m_anthology_reader": "Outside Trip Accord",
        "m_adaptation_reader": "Hikikomori Functioning Banner",
        "m_longstrip_reader": "Welcome Life Trial Trial",
        "m_4koma_reader": "Room Vault Relic",
        "m_oneshot_reader": "Satou Mantle",
        "m_format_variety": "Outside Trophies Gallery",
        "m_light_novel_reader": "Life Insignia Insignia",
        "m_novel_reader": "Hikikomori Crown Crown",
        "m_visual_storyteller": "Conspiracy Testament",
        "m_colored_classic": "Tatsuhiro Satou Survey",
        "m_webcomic_fan": "Archive Pinnacle",
        "m_manga_to_anime": "Misaki Record",
        "m_seinen_reader": "Outside Trip Pinnacle",
        "m_josei_reader": "Door Pinnacle",
        "m_award_winning_art": "Door Relic",
        "m_debut_work": "Tatsuhiro Satou Dominion",
        "m_vertical_scroll": "NHK Marathon Crown Crown",
        "m_traditional_format": "Misaki's Hoard",
        "m_cross_media": "Welcome Life Accord",
        "m_spinoff_reader": "Shut Fan Accord",
        "m_remake_reader": "Knocked Insignia",
        "m_collaboration_reader": "Welcome To The NHK Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Door Knocked Focus",
        "m_mega_streak": "Hikikomori Routine",
        "m_weekly_warrior": "NHK Marathon Season",
        "m_monthly_reader": "NHK Marathon Discipline",
        "m_comeback": "Tatsuhiro Satou Standard",
        "m_weekend_streak": "Archive Fever",
        "m_no_zero_days": "Outside World Proof",
        "m_iron_will": "Session Ledger",
        "m_habit_formed": "Room Vault Crown",
        "m_consistent_pace": "Door Knocks Scrutiny",
        "m_year_long": "Misaki Observance",
        "m_double_streak": "NHK Resolve",
        "m_streak_recovery": "Door Knocks Resolve",
        "m_daily_minimum": "NHK Circle Focus",
        "m_winter_streak": "Welcome Life Observance",
        "m_summer_streak": "Satou Observance",
        "m_morning_streak": "Recovery Clock",
        "m_night_streak": "Session Discipline",
        "m_unbreakable": "Unresolved Issues Warrant Warrant",
        "m_eternal_flame": "Trip Record",
        "m_chapter_a_day": "Game Relic Relic",
        "m_genre_streak": "Welcome Life Streak",
        "m_completion_streak": "NHK Circle Return",
        "m_rating_streak": "Knocked Appraisal",
        "m_multi_ch_streak": "Room Tenure",
        "m_author_streak": "Session Calendar",
        "m_perfect_week_manga": "Satou Accord",
        "m_diverse_streak": "Session Streak",

        // ── MANGA SCORING ──
        "m_critic": "Game Scrutiny",
        "m_perfect_ten": "Trip Verdict",
        "m_harsh_critic": "Outside Scale",
        "m_fair_judge": "Satou's Apartment Eye",
        "m_generous_spirit": "Room Crown",
        "m_score_all": "Session Reckoning",
        "m_wide_range": "Door Knocks Ledger",
        "m_controversial": "Functioning Standard",
        "m_consistent_scorer": "Hikikomori Healed Grade",
        "m_score_sniper": "NHK Reckoning",
        "m_evolving_taste": "Hikikomori Trial Trial",
        "m_bell_curve": "Room Accord Accord",
        "m_picky_reader": "Knocked Relic",
        "m_100_rated": "Game Mark",
        "m_500_rated": "Hikikomori Functioning Proof",
        "m_mediocre_majority": "NHK Marathon Canon",
        "m_rating_spree": "Door Verdict",
        "m_score_variance": "Door Measure",
        "m_binge_rater": "Game Passage",
        "m_reread_rerate": "Satou Banner",
        "m_masterpiece_hunter": "Marathon Banner Banner",
        "m_contrarian": "Hikikomori Functioning Aegis",
        "m_optimist": "Marathon Accord",
        "m_score_distributor": "NHK Marathon Balance",
        "m_genre_critic": "Hikikomori Functioning Critic",
        "m_mean_above_8": "Tatsuhiro Satou Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Exits New Year",
        "m_valentines_read": "Room Vault Observance",
        "m_pi_day": "Satou Testament",
        "m_april_fools": "NHK Devotion",
        "m_international_manga_day": "NHK Marathon Proof",
        "m_free_comic_day": "Game Chronicle",
        "m_summer_solstice": "Marathon Focus",
        "m_tanabata": "Unresolved Issues Pilgrimage",
        "m_friday_13th": "Outside Trip Dominion",
        "m_halloween_read": "Door Knocked Calendar",
        "m_thanksgiving_binge": "Door Knocks Charge",
        "m_christmas_read": "Hikikomori Pact",
        "m_new_years_eve": "Welcome Life Pilgrimage",
        "m_birthday_read": "NHK Circle Birthday",
        "m_holiday_marathon": "Fan Rally",
        "m_independence_day": "Outside Trip Aegis Aegis",
        "m_culture_day": "Hikikomori Seal",
        "m_spring_equinox": "Room Banner Banner",
        "m_earth_day": "Hikikomori Healed Aegis",
        "m_labor_day": "Hikikomori Seal Seal",
        "m_winter_solstice": "Hikikomori Healed Focus",
        "m_manga_birthday": "Satou Ritual",
        "m_every_holiday_reader": "Hikikomori Watch",
        "m_consecutive_holidays": "Hikikomori Functioning Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Shut Fan Proof",
        "m_fibonacci": "Life Dominion",
        "m_palindrome_day": "Room Relic",
        "m_binary_day": "Welcome Life Proof",
        "m_full_moon_read": "Tatsuhiro Satou Crown",
        "m_leap_year_read": "Session Practice",
        "m_triple_seven": "Welcome To The NHK Trial",
        "m_thousand_complete": "Outside World Ascension",
        "m_nice": "Room Vault Seal",
        "m_power_level_chapters": "Tatsuhiro Satou Aegis",
        "m_answer_42": "Unresolved Issues Trial",
        "m_square_number": "Fan Standard",
        "m_prime_count": "Door Knocked Insignia Insignia",
        "m_matching_date": "Recovery Mantle",
        "m_century_chapter": "NHK Crown",
        "m_pi_chapters": "Misaki's Proof",
        "m_synchronicity": "Trip Emblem",
        "m_world_record": "Game Warrant",
        "m_genre_clash": "Conspiracy Clash",
        "m_time_traveler": "Outside Decree Decree",
        "m_double_digits": "Hikikomori Functioning Dominion Dominion",
        "m_one_two_three": "Life Warrant",
        "m_lucky_seven": "Fan Pinnacle",
        "m_exact_hundred_ch": "Room Vault Testament",
        "m_year_match_count": "Shut Routine",
        "m_chapter_match_date": "Hikikomori Healed Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Welcome To The NHK Index",
        "m_manhwa_format": "Marathon Gallery",
        "m_manhua_format": "Door Knocked Storehouse",
        "m_ln_format": "Outside Trip Index",
        "m_oneshot_format": "Room Index",
        "m_doujin_format": "Welcome Cabinet",
        "m_novel_format": "NHK Reserve",
        "m_format_master_manga": "NHK Marathon Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Knocked Link",
        "m_meta_collector": "NHK Reliquary",
        "m_meta_category_starter": "Hikikomori Healed Standard Standard",
        "m_meta_tier_climber": "Functioning Token",
        "m_meta_tier_max": "Misaki Token",
        "m_meta_xp_earner": "Conspiracy Anchor",
        "m_meta_difficulty_easy": "Exits Panel",
        "m_meta_difficulty_hard": "Welcome To The NHK Node",
        "m_meta_unlock_spree": "Misaki's Marker",
        "m_meta_completionist": "Trip Triumph",
        "m_meta_diverse": "Tatsuhiro Satou Anchor",
        "m_meta_dominator": "Marathon Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#010400",
        primary: "#348737",
        secondary: "#888888",
        accent: "#c8f0c0",
    },
    particleColor: "#50a850",
    backgroundDim: 0.35,
    backgroundBlur: 22,
    milestoneNames: {
  1: "Threadbare Generic Rank Spark",
  8: "Generic's Tarnished Omen",
  14: "Fractured Generic Rank",
  21: "Generic Rank Path",
  28: "Lowborn Legacy Myth",
  35: "Generic Rank Pulse",
  41: "Generic's Legacy Crest",
  48: "Humble Generic Mark",
  55: "Ragged Generic Rank Vow",
  61: "Generic's Faint Echo",
  68: "Lesser Generic Rank",
  75: "Generic Rank Zenith",
  81: "Doubtful Legacy Bloom",
  88: "Generic Rank Sigil",
  95: "Generic's Legacy Flame",
  102: "Really Cool Generic Spark",
  108: "Awakened Generic Rank Omen",
  115: "Generic's Resolute Seal",
  122: "Rising Generic Rank",
  128: "Generic Rank Myth",
  135: "Dauntless Legacy Pulse",
  142: "Generic Rank Crest",
  149: "Generic's Legacy Mark",
  155: "Fresh Generic Vow",
  162: "Valiant Generic Rank Echo",
  169: "Generic's Prime Crown",
  175: "Polished Generic Rank",
  182: "Generic Rank Bloom",
  189: "Stormlit Legacy Sigil",
  195: "Generic Rank Flame",
  202: "Generic's Legacy Spark",
  209: "Tempered Generic Omen",
  216: "Trusted Generic Rank Seal",
  222: "Generic's Steadfast Path",
  229: "Ironclad Generic Rank",
  236: "Veteran Legacy Pulse",
  242: "Core Legacy Crest",
  249: "Generic Rank Mark",
  256: "Generic's Legacy Vow",
  262: "Formidable Generic Echo",
  269: "Lucid Generic Rank Crown",
  276: "Generic's Ranked Zenith",
  283: "Fabled Generic Rank",
  289: "Grand Legacy Sigil",
  296: "Seasoned Legacy Flame",
  303: "Generic Rank Spark",
  309: "Generic's Legacy Omen",
  316: "Valorous Generic Seal",
  323: "Stalwart Generic Rank Path",
  330: "Generic's Commanding Myth",
  336: "Refined Generic Rank",
  343: "Unbroken Legacy Crest",
  350: "Blazing Legacy Mark",
  356: "Generic Rank Vow",
  363: "Generic's Legacy Echo",
  370: "Peerless Generic Crown",
  376: "Ardent Generic Rank Zenith",
  383: "Generic's Focused Bloom",
  390: "Vigilant Generic Rank",
  397: "Dominant Legacy Flame",
  403: "Elite Legacy Spark",
  410: "Generic Rank Omen",
  417: "Generic's Legacy Seal",
  423: "Sovereign Generic Path",
  430: "Regal Generic Rank Myth",
  437: "Generic's Crowned Pulse",
  444: "Mythborn Generic Rank",
  450: "Limitless Legacy Mark",
  457: "Radiant Legacy Vow",
  464: "Generic Rank Echo",
  470: "Generic's Legacy Crown",
  477: "Climactic Generic Zenith",
  484: "Epic Generic Rank Bloom",
  490: "Generic's Unreal Sigil",
  497: "Peak Generic Rank",
  504: "Supreme Legacy Spark",
  511: "Exalted Legacy Omen",
  517: "Generic Rank Seal",
  524: "Generic's Legacy Path",
  531: "Celestial Generic Myth",
  537: "Phantom Generic Rank Pulse",
  544: "Generic's Crimson Crest",
  551: "Silver Generic Rank",
  557: "Golden Legacy Vow",
  564: "Feral Legacy Echo",
  571: "Generic Rank Crown",
  578: "Generic's Legacy Zenith",
  584: "Dread Generic Bloom",
  591: "Luminous Generic Rank Sigil",
  598: "Generic's Thunderous Flame",
  604: "Ultraviolet Generic Rank",
  611: "Unleashed Legacy Omen",
  618: "Secret Legacy Seal",
  625: "Final Generic Path",
  631: "Generic's Legacy Myth",
  638: "Worldclass Generic Pulse",
  645: "Lawless Generic Rank Crest",
  651: "Generic's Chosen Mark",
  658: "Fearless Generic Rank",
  665: "Overdrive Legacy Echo",
  671: "Cinematic Legacy Crown",
  678: "Impossible Generic Zenith",
  685: "Generic's Legacy Bloom",
  692: "Canonized Generic Sigil",
  698: "Ascendant Generic Rank Flame",
  705: "Generic's Transfigured Spark",
  712: "Immortal Generic Rank",
  718: "Eclipsed Legacy Seal",
  725: "Astral Legacy Path",
  732: "Sublime Generic Myth",
  739: "Generic's Legacy Pulse",
  745: "Prismatic Generic Crest",
  752: "Abyssal Generic Rank Mark",
  759: "Generic's Unbound Vow",
  765: "Eternal Generic Rank",
  772: "Cosmic Legacy Crown",
  779: "Transcendent Legacy Zenith",
  785: "Perfected Generic Bloom",
  792: "Generic's Legacy Sigil",
  799: "Ultimate Generic Flame",
  806: "Mythic Generic Rank Spark",
  812: "Generic's Godlike Omen",
  819: "Canonical Generic Rank",
  826: "Reality-Bent Legacy Path",
  832: "Heavenly Legacy Myth",
  839: "Absolute Generic Pulse",
  846: "Untouchable Generic Crest",
  852: "Timeless Generic Mark",
  859: "Empyrean Generic Rank Vow",
  866: "Generic's Primordial Echo",
  873: "Omniscient Generic Rank",
  879: "Unfathomed Legacy Zenith",
  886: "Apocalyptic Legacy Bloom",
  893: "Seraphic Generic Sigil",
  899: "Omega Generic Flame",
  906: "Final Generic Spark",
  913: "Crowned Generic Rank Omen",
  920: "Generic's Mythic Seal",
  926: "Absolute Generic Rank",
  933: "Eternal Legacy Myth",
  940: "Cosmic Legacy Pulse",
  946: "Transcendent Generic Crest",
  953: "Perfected Generic Mark",
  960: "Definitive Generic Vow",
  966: "Ultimate Generic Rank Echo",
  973: "Generic's Infinite Crown",
  980: "Sovereign Generic Rank",
  987: "Celestial Legacy Bloom",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate Generic Rank"
},
}
