import { AnimeThemeConfig } from "./types"
import { GiWolfHowl, GiSnowflake1, GiMoonBats, GiCrystalBall, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiMountainRoad } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const wolfRainTheme: AnimeThemeConfig = {
    id: "wolf-rain",
    displayName: "Wolf's Rain",
    description: "In a world where wolves are thought to be extinct, a pack of wolves disguised as humans searches for Paradise — a legendary land promised at the end of the world.",
    fontFamily: "'Crimson Text', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Crimson+Text:ital,wght@0,400;0,600;1,400&display=swap",
    cssVars: {
        "--color-brand-200": "190 200 230",
        "--color-brand-300": "148 162 210",
        "--color-brand-400": "108 125 188",
        "--color-brand-500": "72 90 165",
        "--color-brand-600": "50 65 136",
        "--color-brand-700": "32 44 106",
        "--color-brand-800": "18 26 76",
        "--color-brand-900": "8 14 46",
        "--color-brand-950": "4 7 26",
        "--brand": "72 90 165",
        "--background": "#020204",
        "--paper": "#060710",
        "--color-gray-950": "2 2 4",
        "--color-gray-900": "6 7 12",
        "--color-gray-800": "12 14 24",
        "--color-gray-700": "22 24 40",
        "--color-gray-600": "36 38 64",
        "--color-gray-500": "58 62 100",
        "--color-gray-400": "90 96 140",
        "--color-gray-300": "128 134 172",
        "--color-gray-200": "164 170 198",
        "--color-gray-100": "198 202 220",
        "--color-gray-50": "230 232 240",
    },
    sidebarOverrides: {
        "home": { icon: GiWolfHowl, label: "Pack Den" },
        "schedule": { icon: GiAlarmClock, label: "Migration" },
        "manga": { icon: LuBookOpen, label: "Pack Lore" },
        "lists": { icon: GiMoonBats, label: "Pack Registry" },
        "discover": { icon: GiBullseye, label: "Paradise Hunt" },
        "torrent-list": { icon: GiSnowflake1, label: "Trail Cache" },
        "debrid": { icon: GiCrystalBall, label: "Moon Flower" },
        "unmatched": { icon: GiMountainRoad, label: "Lost Pack" },
        "enmasse": { icon: GiResize, label: "Pack Deploy" },
        "scan-summaries": { icon: TbReportSearch, label: "Pack Reports" },
        "auto-downloader": { icon: LuRss, label: "Wolf Howl" },
        "community": { icon: GiWolfHowl, label: "Wolf Pack" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Howl Alerts" },
        "achievements": { icon: GiTrophy, label: "Wolf Totems" },
        "milestones": { icon: LuFlag, label: "Wolf Goals" },
        "theme-manager": { icon: GiPalette, label: "Moon Colors" },
        "extensions": { icon: BiExtension, label: "Pack Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Pack Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Wolf Settings" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Howl",
        "a_episode_counter": "Lunar Flowers Mark",
        "a_episode_titan": "Wolf Sprint Relic",
        "a_hours_invested": "Pack Den Proof",
        "a_time_lord": "Pack Elder",
        "a_anime_collector": "Flower Cache",
        "a_library_legend": "Wolf Lore",
        "a_first_complete": "Paradise Found",
        "a_hundred_club": "Hundred Miles",
        "a_first_day": "Moon Flower Seal",
        "a_first_rating": "Wolf Sprint Appraisal",
        "a_ten_thousand_min": "Pack Registry Standard",
        "a_season_veteran": "Pack Registry Library",
        "a_year_explorer": "Wolf's Will Map",
        "a_century_watcher": "Wolf Critic Ledger",
        "a_five_hundred_eps": "Wolf's Rain Dominion",
        "a_thousand_eps": "Pack Marathon Record",
        "a_watching_ten": "Yoko Kanno Classic Acclaim",
        "a_ptw_hoarder": "Paradise Found Library",
        "a_dropped_honesty": "Yoko Kanno Classic Summit",
        "a_five_thousand_eps": "Bones Expert Warrant",
        "a_ten_completed": "Stray Pack Afterglow",
        "a_fifty_completed": "Night Journey Ascension",
        "a_five_hundred_completed": "Yoko Kanno Classic Clear",
        "a_mean_score_tracker": "Wolf Disguise Verdict",
        "a_unique_studios": "Pack Marathon Collection",
        "a_days_spent_watching": "Kanno Classic Dominion",
        "a_all_status": "Strict Review Testament",
        "a_first_favorite": "All Night Cabinet",
        "a_favorites_collector": "Wolf Totems Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Howl Alerts Drive",
        "a_marathon_runner": "Long Migration",
        "a_weekend_warrior": "Wolf Sprint Ordeal",
        "a_non_stop": "Long Migration Fever",
        "a_one_more_episode": "Wolf Expert Mantle",
        "a_speed_run": "Wolf Sprint",
        "a_double_feature": "Dawn Howl Crown",
        "a_triple_threat": "Moonlit Hunt Record",
        "a_five_a_day": "Pack Loss Accord",
        "a_back_to_back": "Cheza's Bloom Surge",
        "a_seasonal_binge": "Wolf Sprint Cascade",
        "a_cour_crusher": "Kanno Classic Ordeal",
        "a_half_day_watch": "Lunar Flowers Crown",
        "a_full_day_watch": "Wolf World Pinnacle",
        "a_power_weekend": "Moon Flower Run",
        "a_binge_king": "Pack Marathon",
        "a_no_sleep": "All-Night Journey",
        "a_entire_season": "Author Fan Library",
        "a_seven_day_challenge": "Wolf World Mark",
        "a_hundred_day_binge": "Moon Flower Surge",
        "a_genre_binge": "Hige's Moments Binge",
        "a_studio_binge": "Lunar Flowers Fever",
        "a_season_sweep": "Jagara's Terror Codex",
        "a_forty_eight_hour": "Pack Judge Overture",
        "a_ep_counter_day": "Stray Pack Aegis",
        "a_multi_series_binge": "Paradise Found Streak",
        "a_midnight_binge": "Wolf Expert Cascade",
        "a_new_year_binge": "Yoko Kanno Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Pack Battle",
        "a_genre_adventure": "Paradise Journey",
        "a_genre_comedy": "Hige's Moments",
        "a_genre_drama": "Pack Loss",
        "a_genre_fantasy": "Wolf World",
        "a_genre_horror": "Jagara's Terror",
        "a_genre_mystery": "Unbroken Hunt Mystery",
        "a_genre_romance": "Cheza's Bloom",
        "a_genre_scifi": "Lunar Flowers",
        "a_genre_sol": "Bones Expert Slice",
        "a_genre_sports": "Pack Judge Sports",
        "a_genre_supernatural": "Wolf Disguise",
        "a_genre_thriller": "Night Journey Thriller",
        "a_genre_mecha": "None Here",
        "a_genre_music": "Pack Registry Music",
        "a_genre_psychological": "Kiba's Obsession",
        "a_genre_ecchi": "Howl Alerts Ecchi",
        "a_genre_mahou_shoujo": "Moonlit Hunt Magic Shoujo",
        "a_tag_isekai": "Moon Art Isekai",
        "a_tag_harem": "Wolf Howl Harem",
        "a_tag_bl": "Pack Judge Bl",
        "a_tag_gl": "Wolf Expert Gl",
        "a_tag_historical": "Lost Pack Historical",
        "a_tag_military": "Wolf's Rain Military",
        "a_tag_school": "Paradise Found School",
        "a_tag_martial_arts": "Wolf World Martial Arts",
        "a_tag_vampire": "Moonlit Hunt Vampire",
        "a_tag_samurai": "Pack Marathon Samurai",
        "a_tag_space": "Wolf Pack Space",
        "a_tag_parody": "Pack Elder Parody",
        "a_tag_idol": "Pack Judge Idol",
        "a_tag_post_apocalyptic": "Paradise Gate Post Apocalyptic",
        "a_tag_cyberpunk": "Long Migration Cyberpunk",
        "a_tag_shounen": "Paradise Gate Shounen",
        "a_tag_seinen": "Decade Fan Seinen",
        "a_tag_shoujo": "Decade Fan Shoujo",
        "a_tag_josei": "Stray Pack Josei",
        "a_tag_survival": "Wolf Totems Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "Paradise Reached",
        "a_mega_completionist": "BONES Expert",
        "a_completion_rate_50": "Moonlit Hunt Return",
        "a_completion_rate_75": "Night Journey Crown",
        "a_completion_rate_90": "Stray Pack Resolution",
        "a_no_drop": "Unbroken Hunt Decree",
        "a_long_runner_complete": "Moon Flower Clear",
        "a_sequel_chain": "OVA Complete",
        "a_clean_list": "Jagara's Terror Relic",
        "a_from_ptw": "Pack Elder Index",
        "a_rewatch_master": "Wolf Disguise Return",
        "a_short_complete": "Paradise Hunt Endgame",
        "a_same_day_start_finish": "Trail Revisit Pinnacle",
        "a_revival": "Wolf Critic Insignia",
        "a_zero_to_hero": "Stray to Pack",
        "a_five_genre_complete": "Paradise Hunt A Five Genre",
        "a_full_franchise": "Paradise Found Chronicle",
        "a_batch_complete": "Wolf Sprint Crown",
        "a_paused_to_done": "Stray Pack Aegis Aegis",
        "a_completion_spree": "Pack Battle Triumph",
        "a_multi_rewatch": "Pack Battle Triumph Triumph",
        "a_dropped_recovery": "Lunar Flowers Conquest",
        "a_ten_perfect_scores": "Moon Flower Acclaim",
        "a_seasonal_clear": "Kanno Classic Codex",
        "a_complete_genre_span": "Wolf Lore A Complete Genre",
        "a_monthly_completions": "Wolf Disguise Afterglow",
        "a_yearly_completions": "Strict Review Epilogue",
        "a_rapid_complete": "Wolf World Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Kiba's Pack",
        "a_studio_devotee": "Unbroken Hunt Treasury",
        "a_rewatcher": "Paradise Revisit",
        "a_triple_rewatch": "Hige's Moments Coda",
        "a_annual_tradition": "Wolf World Proof",
        "a_director_fan": "Jagara's Terror Trial",
        "a_voice_actor_fan": "Lunar Flowers Crown Crown",
        "a_ost_lover": "Paradise Found Seal",
        "a_source_reader": "Wolf's Will Cabinet",
        "a_waiting_weekly": "Unbroken Hunt Clock",
        "a_childhood_revisit": "Kiba's Pack Seal",
        "a_saga_tracker": "Wolf Pack Standard",
        "a_genre_loyalty": "Bones Expert Loyalty",
        "a_decade_watcher": "Decade Fan",
        "a_adaptation_hunter": "Pack Elder Trial",
        "a_original_anime_fan": "Daily Hunt Testament",
        "a_long_commitment": "Wolf World Mark Mark",
        "a_perfect_attendance": "Yoko Kanno Classic Standard",
        "a_favorite_studio_5": "Paradise Gate Library",
        "a_complete_catalog": "Wolf Totems Seal",
        "a_franchise_collector": "Paradise Gate Archive",
        "a_airing_follower": "Kiba's Pack Signal",
        "a_genre_master": "Jagara's Terror Master",
        "a_staff_follower": "Paradise Gate Oath",
        "a_multi_season_fan": "Lost Pack Hoard",
        "a_format_diversity": "Moonlit Hunt Cache",
        "a_year_dedication": "Wolf Sprint Tenure",
        "a_season_dedication": "Wolf's Rain Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Hige's Moments Explorer",
        "a_studio_hopper": "Wolf Disguise Collection",
        "a_tag_explorer": "Wolf Sprint Explorer",
        "a_decade_hopper": "Paradise Found Chronicle Chronicle",
        "a_hidden_gem": "Hidden Path",
        "a_popular_taste": "Pack Judge Decree",
        "a_retro_appreciator": "Wolf Totems Aegis",
        "a_modern_viewer": "Trail Revisit Pinnacle Pinnacle",
        "a_cross_demographic": "Howl Alerts Pinnacle",
        "a_underdog_fan": "Wolf Lore Trial",
        "a_variety_week": "Paradise Gate Horizon",
        "a_foreign_cinema": "Wolf Expert Expedition",
        "a_classic_connoisseur": "2003 Fan",
        "a_every_season": "Kiba's Pack Archive",
        "a_award_winner": "Pack Registry Insignia",
        "a_niche_explorer": "Decade Fan Horizon",
        "a_global_anime": "Paradise Hunt Crown",
        "a_cult_classic": "Yoko Kanno Classic",
        "a_random_pick": "Pack Judge Decree Decree",
        "a_new_genre_month": "Yoko Kanno Classic A New",
        "a_seasonal_completionist": "Wolf Critic Summit",
        "a_unpopular_opinion": "All Night Standard",
        "a_top_rated_viewer": "Pack Loss Seal",
        "a_source_variety": "Kanno Classic Storehouse",
        "a_low_score_brave": "Long Migration Measure",
        "a_upcoming_watcher": "Pack Loss Seal Seal",
        "a_short_series_explorer": "Wolf Expert Expedition Expedition",
        "a_long_series_explorer": "Dawn Howl Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Moonlit Hunt",
        "a_early_bird": "Dawn Howl",
        "a_lunch_break": "Pack Lore Trial",
        "a_golden_hour": "Wolf Resolve Tenure",
        "a_four_am_club": "Pack Battle Gathering",
        "a_witching_hour": "Night Journey Tenure",
        "a_new_year_watch": "Wolf Sprint Season",
        "a_midnight_premiere": "Yoko Kanno Devotion",
        "a_all_hours": "Wolf Critic Seal",
        "a_dawn_warrior": "Pack Judge Aegis",
        "a_afternoon_delight": "Pack Den Proof Proof",
        "a_prime_time": "Pack Registry Insignia Insignia",
        "a_workday_watcher": "Howl Alerts Pinnacle Pinnacle",
        "a_sunday_marathon": "Moon Flower Momentum",
        "a_rainy_day": "Night Journey Relic",
        "a_morning_routine": "Lost Pack Promise",
        "a_night_shift": "Moonlit Hunt Aegis",
        "a_twilight_zone": "Author Fan Ledger",
        "a_seasonal_premier": "Unbroken Hunt Cabinet",
        "a_clock_collector": "Pack Battle Repository",
        "a_weekend_binge_hours": "Decade Fan Streak",
        "a_late_night_regular": "Strict Review Dominion",
        "a_sunrise_watcher": "Jagara's Terror Relic Relic",
        "a_holiday_watcher": "Pack Loss Pact",
        "a_every_day_of_week": "Cheza's Bloom Ledger",
        "a_monthly_hours": "Pack Judge Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Stray Pack Record",
        "a_party_host": "Moonlit Hunt Record Record",
        "a_social_butterfly": "Wolf's Will Company",
        "a_group_binge": "Pack Marathon Sprint",
        "a_party_regular": "Author Fan Chronicle",
        "a_sync_viewer": "Pack Battle Standard",
        "a_commentator": "Wolf Totems Record",
        "a_party_marathon": "Hige's Moments Vigil",
        "a_full_house": "Wolf's Rain Trial",
        "a_community_pillar": "Strict Review Alliance",
        "a_watch_party_streak": "Wolf Totems Vigil",
        "a_diverse_party": "Lost Pack Seal",
        "a_late_night_party": "Strict Review Testament Testament",
        "a_party_veteran": "Wolf's Rain Testament",
        "a_genre_party": "Wolf Expert Party",
        "a_weekly_party": "Pack Battle Calendar",
        "a_silent_viewer": "Daily Hunt Mantle",
        "a_recommendation_giver": "Decade Fan Network",
        "a_party_completionist": "Wolf Pack Coda",
        "a_social_scorer": "Jagara's Terror Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Dawn Howl Proof",
        "a_fibonacci": "Wolf Sprint Dominion",
        "a_palindrome_day": "Wolf Sprint Relic Relic",
        "a_binary_day": "Bones Expert Mark",
        "a_full_moon": "Kiba's Pack Insignia",
        "a_leap_year": "Paradise Hunt Devotion",
        "a_time_traveler": "Unbroken Hunt Record",
        "a_genre_clash": "Hige's Moments Clash",
        "a_triple_seven": "Wolf Sprint Testament",
        "a_thousand_complete": "Daily Hunt Epilogue",
        "a_pi_episodes": "Howl Alerts Crown",
        "a_synchronicity": "Wolf Lore Anchor",
        "a_world_record": "Lunar Flowers Warrant",
        "a_nice": "Pack Registry Chronicle",
        "a_power_level": "Daily Hunt Testament Testament",
        "a_answer_42": "Pack Judge Standard",
        "a_square_number": "Hige's Moments Decree",
        "a_prime_count": "Pack Registry Seal",
        "a_matching_date": "Wolf Lore Mantle",
        "a_century_episode": "Howl Alerts Mark",
        "a_double_digits": "Night Journey Testament",
        "a_one_two_three": "Paradise Hunt Crown Crown",
        "a_lucky_seven": "Wolf World Crown",
        "a_all_tens": "Long Migration Criterion",
        "a_exact_hundred_eps": "Wolf Pack Legend",
        "a_year_match_count": "Unbroken Hunt Yearlong",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Decade Fan Ledger",
        "a_movie_buff": "Lunar Flowers Mark Mark",
        "a_ova_hunter": "Wolf Pack Standard Standard",
        "a_ona_explorer": "Wolf Lore Secret",
        "a_special_watcher": "Night Journey Relic Relic",
        "a_short_king": "Wolf Howl Crown",
        "a_variety_pack": "Lunar Flowers Inquiry",
        "a_film_festival": "Pack Loss Chronicle",
        "a_music_video": "Lost Pack Chronicle",
        "a_tv_short": "Hige's Moments Record",
        "a_movie_marathon": "Hige's Moments Gauntlet",
        "a_double_length": "Dawn Howl Crown Crown",
        "a_anthology": "Moonlit Hunt Aegis Aegis",
        "a_mini_series": "All Night Decree",
        "a_theatrical": "Paradise Gate Accord",
        "a_format_master": "Pack Battle Vault",
        "a_long_movie": "Wolf Critic Insignia Insignia",
        "a_back_catalog": "Wolf Totems Standard",
        "a_cm_watcher": "Moon Art Aegis",
        "a_pv_collector": "Wolf Lore Storehouse",
        "a_format_balance": "Pack Battle Vault Vault",
        "a_episodic_master": "Moon Art Standard",
        "a_sequel_movie": "Paradise Hunt Pinnacle",
        "a_recap_watcher": "Pack Lore Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Hunt",
        "a_mega_streak": "Endless Migration",
        "a_weekly_warrior": "Wolf's Rain Season",
        "a_monthly_watcher": "Yoko Kanno Calendar",
        "a_comeback": "Wolf's Will Decree",
        "a_weekend_streak": "Long Migration Passage",
        "a_no_zero_days": "Bones Expert Warrant Warrant",
        "a_iron_will": "Wolf's Will",
        "a_habit_formed": "Cheza's Bloom Banner",
        "a_consistent_pace": "Dawn Howl Measure",
        "a_year_long": "Year of Howling",
        "a_double_streak": "Jagara's Terror Watch",
        "a_streak_recovery": "Daily Hunt Season",
        "a_daily_minimum": "Yoko Kanno Focus",
        "a_winter_streak": "Wolf Expert Watch",
        "a_summer_streak": "Night Journey Resolve",
        "a_morning_streak": "Wolf Totems Clock",
        "a_night_streak": "Cheza's Bloom Constancy",
        "a_unbreakable": "Wolf Howl Proof",
        "a_eternal_flame": "Wolf Disguise Standard",
        "a_completion_streak": "Wolf Pack Return",
        "a_rating_streak": "Wolf Sprint Balance",
        "a_multi_ep_streak": "Lunar Flowers Ritual",
        "a_genre_streak": "Wolf Sprint Streak",
        "a_studio_streak": "Wolf's Will Cabinet Cabinet",
        "a_perfect_week": "Wolf Lore Relic",

        // ── ANIME SCORING ──
        "a_critic": "Pack Judge",
        "a_perfect_ten": "Moon Flower",
        "a_harsh_critic": "Strict Review",
        "a_fair_judge": "Strict Review Balance",
        "a_generous_spirit": "Yoko Kanno Pinnacle",
        "a_score_all": "Pack Den Criterion",
        "a_wide_range": "Pack Registry Ledger",
        "a_controversial": "Wolf Totems Decree",
        "a_consistent_scorer": "Unbroken Hunt Verdict",
        "a_score_sniper": "Paradise Hunt Score",
        "a_evolving_taste": "Jagara's Terror Testament",
        "a_bell_curve": "Yoko Kanno Classic Insignia",
        "a_picky_watcher": "Daily Hunt Warrant",
        "a_100_rated": "Pack Battle Warrant",
        "a_500_rated": "Wolf Howl Pinnacle",
        "a_mediocre_majority": "Wolf Lore Canon",
        "a_rating_spree": "Wolf Totems Review",
        "a_score_variance": "Long Migration Score",
        "a_masterpiece_hunter": "Wolf Totems Banner",
        "a_contrarian": "Hige's Moments Record Record",
        "a_optimist": "Lost Pack Ledger",
        "a_score_distributor": "Pack Lore Appraisal",
        "a_genre_critic": "Dawn Howl Critic",
        "a_mean_above_8": "Wolf World Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Hunt",
        "a_valentines_weeb": "Paradise Gate Vow",
        "a_pi_day": "Strict Review Trial",
        "a_april_fools": "Paradise Hunt Devotion Devotion",
        "a_international_anime_day": "Wolf Critic Record",
        "a_star_wars_day": "Moon Flower Chronicle",
        "a_summer_solstice": "Bones Expert Calendar",
        "a_tanabata": "Trail Revisit Focus",
        "a_friday_13th": "Pack Lore Relic",
        "a_halloween_spirit": "Decade Fan Vow",
        "a_thanksgiving_binge": "Author Fan Run",
        "a_christmas_special": "Winter Migration",
        "a_new_years_eve": "Wolf World Pilgrimage",
        "a_birthday_watch": "Yoko Kanno Classic Vow",
        "a_holiday_marathon": "Pack Marathon Overture",
        "a_independence_day": "Wolf Disguise Banner",
        "a_culture_day": "Paradise Found Insignia",
        "a_spring_equinox": "Pack Marathon Decree",
        "a_earth_day": "Lunar Flowers Mantle",
        "a_labor_day": "Decade Fan Seal",
        "a_winter_solstice": "Howl Alerts Pilgrimage",
        "a_anime_birthday": "Lunar Flowers Pilgrimage",
        "a_every_holiday": "Pack Elder Resolve",
        "a_consecutive_holidays": "Night Journey Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Wolf's Will Rank",
        "a_meta_collector": "Paradise Found Hoard",
        "a_meta_category_starter": "Yoko Kanno Badge",
        "a_meta_tier_climber": "Paradise Found Glyph",
        "a_meta_tier_max": "Paradise Gate",
        "a_meta_xp_earner": "Pack Lore Emblem",
        "a_meta_difficulty_easy": "Strict Review Mechanism",
        "a_meta_difficulty_hard": "Pack Loss Writ",
        "a_meta_unlock_spree": "Wolf's Rain Panel",
        "a_meta_completionist": "Complete Pack",
        "a_meta_diverse": "Wolf Sprint Emblem",
        "a_meta_dominator": "Author Fan Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Trail",
        "m_chapter_counter": "Pack Battle Pinnacle",
        "m_chapter_titan": "Kanno Classic Relic",
        "m_reading_hours": "Pack Lore Relic Relic",
        "m_reading_time_lord": "Wolf Critic Record Record",
        "m_manga_collector": "Wolf's Rain Ledger",
        "m_library_legend": "Paradise Found Reliquary",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Miles",
        "m_first_day": "Paradise Gate Seal",
        "m_first_rating": "Pack Lore Eye",
        "m_ten_thousand_pages": "Paradise Gate Gauge",
        "m_volume_collector": "Daily Hunt Storehouse",
        "m_year_explorer": "Pack Judge Quest",
        "m_century_reader": "Wolf Expert Dominion",
        "m_five_hundred_ch": "Pack Registry Legend",
        "m_thousand_ch": "Jagara's Terror Legend",
        "m_reading_ten": "Wolf Expert Appraisal",
        "m_ptr_hoarder": "Jagara's Terror Index",
        "m_dropped_honesty": "Paradise Found Summit",
        "m_season_reader": "Wolf Totems Treasury",
        "m_active_reader": "Night Journey Trial",
        "m_five_thousand_ch": "Hige's Moments Standard",
        "m_ten_completed": "Hige's Moments Resolution",
        "m_fifty_completed": "Jagara's Terror Harvest",
        "m_five_hundred_completed": "Cheza's Bloom Legacy",
        "m_mean_score_tracker": "Unbroken Hunt Audit",
        "m_unique_authors": "Lunar Flowers Reserve",
        "m_all_status": "Night Journey Testament Testament",
        "m_first_favorite": "Wolf Pack Cache",
        "m_favorites_collector": "Wolf's Will Shelf",
        "m_days_spent_reading": "Howl Alerts Relic",

        // ── MANGA BINGE ──
        "m_binge_reader": "Yoko Kanno Classic Streak",
        "m_marathon_reader": "Strict Review Rush",
        "m_weekend_reader": "Kiba's Pack Run",
        "m_non_stop_reading": "Wolf Pack Gauntlet",
        "m_one_more_chapter": "Pack Lore Testament Testament",
        "m_speed_read": "Bones Expert Drive",
        "m_double_story": "Pack Marathon Banner",
        "m_triple_read": "Wolf Disguise Record",
        "m_five_a_day": "Lost Pack Insignia",
        "m_chapter_chain": "Paradise Found Accord",
        "m_volume_binge": "Long Migration Drive",
        "m_power_reader": "Moon Flower Seal Seal",
        "m_half_day_read": "Wolf's Will Aegis",
        "m_full_day_read": "Moon Art Aegis Aegis",
        "m_power_weekend": "Paradise Gate Streak",
        "m_binge_king": "Pack Marathon",
        "m_no_sleep_read": "Wolf Expert Rush",
        "m_full_series_rush": "Strict Review Cascade",
        "m_seven_day_challenge": "Trail Revisit Warrant",
        "m_hundred_day_read": "Wolf Sprint Legend",
        "m_volume_rush": "Stray Pack Gauntlet",
        "m_series_sweep": "Pack Elder Trial Trial",
        "m_genre_binge": "Moon Art Binge",
        "m_author_binge": "Kiba's Pack Surge",
        "m_chapter_counter_day": "Author Fan Ledger Ledger",
        "m_multi_series_binge": "Pack Registry Charge",
        "m_midnight_binge": "Jagara's Terror Tempest",
        "m_new_year_binge": "Lunar Flowers Passage",
        "m_forty_eight_hour": "Unbroken Hunt Rally",
        "m_oneshot_binge": "Bones Expert Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Combat Chapter",
        "m_genre_adventure": "Migration Chapter",
        "m_genre_comedy": "Wolf's Will Comedy",
        "m_genre_drama": "Pack Loss",
        "m_genre_fantasy": "Wolf Chapter",
        "m_genre_horror": "Dark Chapter",
        "m_genre_mystery": "Hige's Moments Mystery",
        "m_genre_romance": "Flower Chapter",
        "m_genre_scifi": "Moon Chapter",
        "m_genre_sol": "Pack Battle Slice",
        "m_genre_sports": "Stray Pack Sports",
        "m_genre_supernatural": "Spirit Chapter",
        "m_genre_thriller": "Wolf Lore Thriller",
        "m_genre_psychological": "Obsession",
        "m_genre_isekai": "Wolf's Rain Isekai",
        "m_genre_shounen": "Wolf Resolve Shounen",
        "m_genre_ecchi": "Dawn Howl Ecchi",
        "m_genre_mahou_shoujo": "Wolf's Will Magic Shoujo",
        "m_genre_mecha": "Daily Hunt Mecha",
        "m_genre_music": "Decade Fan Music",
        "m_tag_isekai_new": "Pack Lore Isekai New",
        "m_tag_harem": "Pack Den Harem",
        "m_tag_bl": "All Night Bl",
        "m_tag_gl": "Jagara's Terror Gl",
        "m_tag_historical": "Pack Registry Historical",
        "m_tag_military": "Wolf Resolve Military",
        "m_tag_school": "Paradise Gate School",
        "m_tag_martial_arts": "Pack Battle Martial Arts",
        "m_tag_vampire": "Stray Pack Vampire",
        "m_tag_samurai": "Moonlit Hunt Samurai",
        "m_tag_space": "All Night Space",
        "m_tag_parody": "Daily Hunt Parody",
        "m_tag_idol": "All Night Idol",
        "m_tag_post_apocalyptic": "Paradise Found Post Apocalyptic",
        "m_tag_cyberpunk": "Pack Den Cyberpunk",
        "m_tag_shoujo": "Pack Loss Shoujo",
        "m_tag_survival": "Wolf's Will Survival",
        "m_tag_cooking": "Yoko Kanno Classic Cooking",
        "m_tag_medical": "Night Journey Medical",
        "m_tag_villainess": "Kiba's Pack Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Journey",
        "m_mega_completionist": "Wolf Expert",
        "m_completion_rate_50": "All Night Return",
        "m_completion_rate_75": "Wolf Lore Ascension",
        "m_completion_rate_90": "Wolf Disguise Resolution",
        "m_no_drop": "Wolf Pack Decree",
        "m_long_runner_complete": "Author Fan Clear",
        "m_sequel_chain": "Decade Fan Seal Seal",
        "m_clean_list": "Kanno Classic Relic Relic",
        "m_from_ptr": "Pack Loss Watchlist",
        "m_reread_master": "Strict Review Trial Trial",
        "m_oneshot_complete": "Strict Review Ascension",
        "m_same_day_start_finish": "Wolf World Crown Crown",
        "m_revival": "Author Fan Accord",
        "m_zero_to_hundred": "Hige's Moments Banner",
        "m_five_genre_complete": "Bones Expert M Five Genre",
        "m_full_collection": "Wolf World Proof Proof",
        "m_batch_complete": "Unbroken Hunt Summit",
        "m_paused_to_done": "Wolf Disguise Standard Standard",
        "m_completion_spree": "Wolf Howl Triumph",
        "m_format_completionist": "Strict Review Completion",
        "m_catch_up": "Wolf Critic Chronicle",
        "m_multi_reread": "Wolf Pack Banner",
        "m_dropped_recovery": "Dawn Howl Conquest",
        "m_ten_perfect_scores": "Kiba's Pack Judgment",
        "m_complete_genre_span": "Wolf's Rain M Complete Genre",
        "m_monthly_completions": "Moon Art Return",
        "m_yearly_completions": "Wolf's Rain Epilogue",
        "m_rapid_complete": "Trail Revisit Finale",
        "m_author_complete": "Paradise Gate Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Wolf Reader",
        "m_mangaka_lover": "Author Fan",
        "m_rereader": "Trail Revisit",
        "m_triple_reread": "Wolf Sprint Testament Testament",
        "m_annual_reread": "Hige's Moments Banner Banner",
        "m_publisher_fan": "Wolf Howl Mark",
        "m_artist_fan": "Decade Fan Insignia",
        "m_adaptation_compare": "Yoko Kanno Classic Insignia Insignia",
        "m_source_material_fan": "Manga Version",
        "m_waiting_weekly": "Moonlit Hunt Streak",
        "m_classic_reader": "Daily Hunt Lantern",
        "m_saga_reader": "Paradise Found Decree",
        "m_genre_loyalty": "Dawn Howl Loyalty",
        "m_decade_reader": "Long Migration Warrant",
        "m_ln_adaptation": "Long Migration Mark",
        "m_original_work": "Stray Pack Standard",
        "m_long_commitment": "Dawn Howl Mark",
        "m_up_to_date": "Lunar Flowers Warrant Warrant",
        "m_favorite_mangaka": "Pack Judge Treasury",
        "m_complete_portfolio": "Wolf Howl Triumph Triumph",
        "m_franchise_collector": "Wolf Critic Archive",
        "m_serialization_follower": "Pack Judge Handshake",
        "m_genre_master": "Kanno Classic Master",
        "m_multi_series_author": "Paradise Found Insignia Insignia",
        "m_format_diversity": "Stray Pack Shelf",
        "m_year_dedication": "Wolf Expert Tenure",
        "m_ongoing_follower": "Long Migration Fellowship",
        "m_genre_loyalty_50": "Jagara's Terror Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Pack Marathon Explorer",
        "m_publisher_hopper": "Wolf Howl Mantle",
        "m_tag_explorer": "Pack Elder Explorer",
        "m_decade_hopper": "Pack Loss Chronicle Chronicle",
        "m_hidden_gem": "Hidden Volume",
        "m_popular_taste": "Unbroken Hunt Record Record",
        "m_retro_reader": "Unbroken Hunt Accord",
        "m_modern_reader": "Pack Registry Seal Seal",
        "m_cross_demographic": "Yoko Kanno Crown",
        "m_underdog_fan": "Unbroken Hunt Accord Accord",
        "m_variety_week": "Decade Fan Horizon Horizon",
        "m_manhwa_reader": "Paradise Hunt Proof",
        "m_manhua_reader": "Daily Hunt Mantle Mantle",
        "m_classic_connoisseur": "Cheza's Bloom Glimpse",
        "m_award_winner": "Wolf Expert Warrant",
        "m_niche_explorer": "Yoko Kanno Classic Horizon",
        "m_world_manga": "Wolf Critic Chronicle Chronicle",
        "m_cult_classic": "Classic Manga",
        "m_random_pick": "Unbroken Hunt Standard",
        "m_new_genre_month": "Wolf Critic M New Genre",
        "m_year_completionist": "Pack Battle Fulfillment",
        "m_unpopular_opinion": "Lunar Flowers Trial",
        "m_top_rated_reader": "Yoko Kanno Classic Record",
        "m_source_variety": "Daily Hunt Catalogue",
        "m_low_score_brave": "Pack Battle Score",
        "m_short_manga_explorer": "Pack Registry Compass",
        "m_long_manga_explorer": "Hige's Moments Survey",
        "m_serialization_explorer": "Wolf Lore Road",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "All Night Ledger",
        "m_commute_reader": "Night Journey Tenure Tenure",
        "m_four_am_club": "Wolf Howl Fellowship",
        "m_new_year_read": "Decade Fan Pact",
        "m_all_hours": "Pack Loss Accord Accord",
        "m_prime_time_reader": "Stray Pack Banner",
        "m_workday_reader": "Author Fan Accord Accord",
        "m_sunday_read": "All Night Standard Standard",
        "m_morning_routine": "Author Fan Discipline",
        "m_night_shift_reader": "Paradise Gate Accord Accord",
        "m_seasonal_premier_read": "Daily Hunt Seasonal",
        "m_clock_collector": "Howl Alerts Reserve",
        "m_late_night_horror": "Bones Expert Mark Mark",
        "m_afternoon_reader": "Wolf Expert Mantle Mantle",
        "m_golden_hour_reader": "Wolf Sprint Observance",
        "m_dawn_reader": "Pack Elder Mantle",
        "m_twilight_reader": "Long Migration Crown",
        "m_midnight_start": "Stray Pack Routine",
        "m_weekend_binge_hours": "Kiba's Pack Momentum",
        "m_late_night_regular": "All Night Accord",
        "m_sunrise_reader": "Pack Den Mantle",
        "m_every_day_of_week": "Daily Hunt Warrant Warrant",
        "m_monthly_hours": "Pack Marathon Vigil",
        "m_bedtime_reader": "Pack Battle Warrant Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Moon Art",
        "m_webtoon_reader": "Long Migration Mark Mark",
        "m_full_color": "Decade Fan Accord",
        "m_doujin_reader": "Wolf Disguise Record Record",
        "m_anthology_reader": "Kiba's Pack Accord",
        "m_adaptation_reader": "Unbroken Hunt Banner",
        "m_longstrip_reader": "Wolf Sprint Trial",
        "m_4koma_reader": "Moonlit Hunt Ledger",
        "m_oneshot_reader": "Wolf's Rain Mantle",
        "m_format_variety": "Wolf Howl Gallery",
        "m_light_novel_reader": "Pack Loss Insignia",
        "m_novel_reader": "Pack Battle Crown",
        "m_visual_storyteller": "Wolf Expert Testament",
        "m_colored_classic": "Wolf Totems Survey",
        "m_webcomic_fan": "Cheza's Bloom Insignia",
        "m_manga_to_anime": "Manga Adapted",
        "m_seinen_reader": "Dawn Howl Pinnacle",
        "m_josei_reader": "Pack Den Pinnacle",
        "m_award_winning_art": "Wolf Resolve Relic",
        "m_debut_work": "Wolf Resolve Dominion",
        "m_vertical_scroll": "Paradise Found Decree Decree",
        "m_traditional_format": "Yoko Kanno Classic Hoard",
        "m_cross_media": "Pack Registry Accord",
        "m_spinoff_reader": "Wolf Critic Accord",
        "m_remake_reader": "Strict Review Pinnacle",
        "m_collaboration_reader": "Cheza's Bloom Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Unbroken Hunt",
        "m_weekly_warrior": "Wolf Lore Season",
        "m_monthly_reader": "Lost Pack Discipline",
        "m_comeback": "Hige's Moments Standard Standard",
        "m_weekend_streak": "Pack Den Fever",
        "m_no_zero_days": "Paradise Hunt Proof Proof",
        "m_iron_will": "Wolf Resolve",
        "m_habit_formed": "Yoko Kanno Crown Crown",
        "m_consistent_pace": "Wolf World Scrutiny Scrutiny",
        "m_year_long": "Year Reading",
        "m_double_streak": "Wolf's Rain Resolve",
        "m_streak_recovery": "Kanno Classic Resolve",
        "m_daily_minimum": "Howl Alerts Focus",
        "m_winter_streak": "Wolf Sprint Observance Observance",
        "m_summer_streak": "Wolf Resolve Observance",
        "m_morning_streak": "Pack Marathon Clock",
        "m_night_streak": "Yoko Kanno Classic Discipline",
        "m_unbreakable": "Pack Den Warrant",
        "m_eternal_flame": "Wolf's Will Record",
        "m_chapter_a_day": "All Night Ledger Ledger",
        "m_genre_streak": "Pack Elder Streak",
        "m_completion_streak": "Unbroken Hunt Return",
        "m_rating_streak": "Pack Elder Appraisal",
        "m_multi_ch_streak": "Wolf Lore Tenure",
        "m_author_streak": "Howl Alerts Calendar",
        "m_perfect_week_manga": "Wolf Critic Accord Accord",
        "m_diverse_streak": "Wolf Pack Streak",

        // ── MANGA SCORING ──
        "m_critic": "Wolf Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_harsh_critic": "Pack Loss Scale",
        "m_fair_judge": "Pack Lore Eye Eye",
        "m_generous_spirit": "Kiba's Pack Decree",
        "m_score_all": "Long Migration Reckoning",
        "m_wide_range": "Lost Pack Ledger Ledger",
        "m_controversial": "Moon Art Standard Standard",
        "m_consistent_scorer": "Wolf Disguise Grade",
        "m_score_sniper": "Lunar Flowers Reckoning",
        "m_evolving_taste": "Wolf's Rain Trial Trial",
        "m_bell_curve": "Lost Pack Accord",
        "m_picky_reader": "Wolf Pack Ledger",
        "m_100_rated": "Lost Pack Standard",
        "m_500_rated": "Paradise Gate Aegis",
        "m_mediocre_majority": "Wolf's Rain Canon",
        "m_rating_spree": "Pack Marathon Verdict",
        "m_score_variance": "Pack Battle Measure",
        "m_binge_rater": "Howl Alerts Passage",
        "m_reread_rerate": "Wolf Totems Banner Banner",
        "m_masterpiece_hunter": "Moon Art Banner",
        "m_contrarian": "Unbroken Hunt Aegis",
        "m_optimist": "Pack Registry Accord Accord",
        "m_score_distributor": "Wolf Lore Balance",
        "m_genre_critic": "Howl Alerts Critic",
        "m_mean_above_8": "Pack Battle Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Wolf Expert Season",
        "m_valentines_read": "Pack Elder Observance",
        "m_pi_day": "Wolf's Rain Testament Testament",
        "m_april_fools": "Lunar Flowers Devotion",
        "m_international_manga_day": "Pack Loss Aegis",
        "m_free_comic_day": "Kiba's Pack Chronicle",
        "m_summer_solstice": "Trail Revisit Focus Focus",
        "m_tanabata": "Wolf World Tanabata",
        "m_friday_13th": "Strict Review Dominion Dominion",
        "m_halloween_read": "Bones Expert Halloween",
        "m_thanksgiving_binge": "Wolf Critic Charge",
        "m_christmas_read": "Author Fan Pact",
        "m_new_years_eve": "Trail Revisit Pilgrimage",
        "m_birthday_read": "Dawn Howl Focus",
        "m_holiday_marathon": "Pack Judge Rally",
        "m_independence_day": "Unbroken Hunt Aegis Aegis",
        "m_culture_day": "Paradise Gate Seal Seal",
        "m_spring_equinox": "Bones Expert Dominion",
        "m_earth_day": "Dawn Howl Trial",
        "m_labor_day": "Author Fan Seal",
        "m_winter_solstice": "Yoko Kanno Focus Focus",
        "m_manga_birthday": "Wolf World Ritual",
        "m_every_holiday_reader": "Kanno Classic Watch",
        "m_consecutive_holidays": "Strict Review Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Moon Flower Aegis",
        "m_fibonacci": "Night Journey Dominion",
        "m_palindrome_day": "Wolf's Rain Relic",
        "m_binary_day": "Yoko Kanno Proof",
        "m_full_moon_read": "Pack Den Crown",
        "m_leap_year_read": "Wolf Pack Practice",
        "m_triple_seven": "Pack Lore Trial Trial",
        "m_thousand_complete": "Pack Lore Ascension",
        "m_nice": "Paradise Found Seal Seal",
        "m_power_level_chapters": "Hige's Moments Aegis",
        "m_answer_42": "Pack Den Trial",
        "m_square_number": "Wolf's Will Standard",
        "m_prime_count": "Pack Lore Pinnacle",
        "m_matching_date": "Kanno Classic Mantle",
        "m_century_chapter": "Moon Flower Decree",
        "m_pi_chapters": "Dawn Howl Proof Proof",
        "m_synchronicity": "Pack Elder Emblem",
        "m_world_record": "Paradise Hunt Warrant",
        "m_genre_clash": "Stray Pack Clash",
        "m_time_traveler": "Wolf Disguise Decree",
        "m_double_digits": "Daily Hunt Dominion",
        "m_one_two_three": "Cheza's Bloom Banner Banner",
        "m_lucky_seven": "Yoko Kanno Classic Record Record",
        "m_exact_hundred_ch": "Night Journey Legend",
        "m_year_match_count": "Moonlit Hunt Routine",
        "m_chapter_match_date": "Yoko Kanno Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Daily Hunt Index",
        "m_manhwa_format": "Bones Expert Gallery",
        "m_manhua_format": "Wolf Sprint Storehouse",
        "m_ln_format": "Pack Lore Index",
        "m_oneshot_format": "Wolf's Rain Index",
        "m_doujin_format": "Pack Marathon Cabinet",
        "m_novel_format": "Lunar Flowers Reserve Reserve",
        "m_format_master_manga": "Pack Marathon Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Wolf Disguise Link",
        "m_meta_collector": "Paradise Gate Reliquary",
        "m_meta_category_starter": "Wolf Howl Standard",
        "m_meta_tier_climber": "Pack Registry Token",
        "m_meta_tier_max": "Paradise Complete",
        "m_meta_xp_earner": "Daily Hunt Anchor",
        "m_meta_difficulty_easy": "Pack Lore Panel",
        "m_meta_difficulty_hard": "Wolf Expert Node",
        "m_meta_unlock_spree": "Daily Hunt Marker",
        "m_meta_completionist": "Full Library",
        "m_meta_diverse": "Wolf's Rain Anchor",
        "m_meta_dominator": "Paradise Found Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#020204",
        primary: "#485aa5",
        secondary: "#324188",
        accent: "#c8e8f8",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/wolf-rain.jpg",
    particleColor: "#8090d8",
    backgroundDim: 0.4,
    backgroundBlur: 22,
    particleTypes: {
        snowflakes: { label: "Snowflakes", maxCount: 25, defaultEnabled: true, defaultIntensity: 60 },
        moon_flowers: { label: "Moon Flowers", maxCount: 10, defaultEnabled: true, defaultIntensity: 55 },
    },
    milestoneNames: {
  1: "Lone Starving Wolf",
  7: "City-Hunted Beast",
  14: "Masked Survival Drifter",
  21: "Packless Wanderer",
  27: "Urban Ghost Predator",
  34: "Instinct-Driven Fugitive",
  41: "Fragmented Pack Memory",
  47: "Disguised Canine Entity",
  54: "Survival Corridor Runner",
  61: "Cold City Stalker",
  68: "Feral Awareness Emergence",
  74: "Low Trust Packless Unit",
  81: "Myth-Sensing Wanderer",
  88: "Hunger-Driven Survivor",
  94: "Outcast of Civilization",

  101: "Pack Memory Fragment",
  108: "Companion-Seeking Entity",
  114: "Urban Survival Specialist",
  121: "Instinct-Coherent Form",
  128: "First Pack Contact",
  135: "Rusted Humanity Layer",
  141: "Myth Tracker Initiate",
  148: "Hidden Nature Carrier",
  155: "Cold Road Traveler",
  161: "Partial Pack Alignment",
  168: "Emotion-Resistant Hunter",
  175: "Shared Hunger Awareness",
  182: "Survival Bond Formation",
  188: "Nomadic Instinct Sync",
  195: "Rising Pack Consciousness",

  202: "Confirmed Pack Member",
  208: "Coordinated Hunter",
  215: "Myth Path Seeker",
  222: "Celestial Scent Tracker",
  228: "Urban Ruin Navigator",
  235: "Bond-Driven Fighter",
  242: "Shared Instinct Resonance",
  249: "Cold World Adapter",
  255: "Pack Stability Contributor",
  262: "Memory of Paradise Holder",
  269: "Fragmented Identity Holder",
  275: "Trust-Forming Entity",
  282: "Survival Strategy Wolf",
  289: "Myth Signal Receiver",
  296: "Rising Path Awareness",

  302: "Advanced Pack Member",
  309: "Coordinated Alpha-Adjacent",
  316: "Myth Direction Follower",
  322: "Instinct-Harmony Fighter",
  329: "Bond Reinforced Hunter",
  336: "Urban-to-Myth Transition Unit",
  342: "Shared Dream Carrier",
  349: "Pack Survival Anchor",
  356: "Emotional Instinct Fusion",
  363: "Pathway of Paradise Seeker",
  369: "Near Mythic Wanderer",
  376: "Identity Duality Form",
  383: "High Trust Pack Node",
  389: "Existence Direction Shift",
  396: "Rising Myth Walker",

  403: "Elite Pack Hunter",
  409: "Celestial Path Observer",
  416: "Myth Route Specialist",
  423: "Pack Stability Core",
  430: "Bond Absolute Fighter",
  436: "Ruined World Navigator",
  443: "Shared Destiny Carrier",
  450: "Instinct-Legend Hybrid",
  456: "Near Paradise Entity",
  463: "Myth-Reality Interface",
  470: "Pack Unity Anchor",
  477: "Transitional Wolf Form",
  483: "Truth Sensing Wanderer",
  490: "High Myth Awareness",
  497: "Legendary Pack Figure",

  503: "Alpha of the Lost Pack",
  510: "Myth Path Commander",
  517: "Celestial Destination Seeker",
  523: "Instinct-Calm Hybrid",
  530: "Reality Fracture Navigator",
  537: "Bond Absolute Guardian",
  544: "Dream of Paradise Carrier",
  550: "Myth Stability Anchor",
  557: "Near Transcendent Wolf",
  564: "Pack Myth Embodiment",
  570: "Truth Beyond Instinct",
  577: "Legend of Endless Night",
  584: "Paradise Threshold Walker",
  591: "Myth of Wolf’s Rain",
  597: "True Path Entity",

  604: "Instinct Awakening Surge",
  611: "Human Mask Dissolution",
  617: "Pack Memory Convergence",
  624: "Myth Signal Intensification",
  631: "Bond Overload State",
  637: "Paradise Illusion Drift",
  644: "Identity Boundary Collapse",
  651: "Shared Fate Synchronization",
  658: "Existence Direction Fracture",
  664: "Near Final Path Awareness",
  671: "Mythic Cycle Recognition",
  678: "Fully Realized Wanderer",
  684: "Absolute Pack Consciousness",
  691: "Myth of the Closed World",
  698: "True Wolf Essence",

  704: "Endless Road Awakening",
  711: "Instinct Purification Phase",
  718: "Myth Collapse Awareness",
  725: "Bond Finalization Event",
  731: "Paradise Search Dissolution",
  738: "World Boundary Recognition",
  745: "Shared Dream Breakdown",
  751: "Existence Loop Realization",
  758: "Final Journey Alignment",
  765: "Near Infinite Night State",
  772: "Last Path Decision",
  778: "End of Search Cycle",
  785: "World Without Paradise",
  792: "Silent Frozen Road",
  798: "Peak Existential Drift",

  805: "Apex Wolf Entity",
  812: "Beyond Human Illusion",
  818: "Absolute Instinct Form",
  825: "Myth Reality Anchor",
  832: "Pack Reality Engine",
  839: "Perfect Night Flow",
  845: "Infinite Wander State",
  852: "True Wolf Core",
  859: "Legend Beyond Paradise",
  865: "Myth of Endless Rain",
  872: "Absolute Pack Entity",
  879: "World Boundary Symbol",
  886: "Instinct Incarnate",
  892: "Near Omniversal Wanderer",
  899: "Perfect Myth Cycle",

  906: "Apex Instinct Form",
  912: "Beyond Destination Logic",
  919: "Final Wolf State",
  926: "Absolute Myth Entity",
  932: "Infinite Night Presence",
  939: "Reality of the Pack",
  946: "Perfect Survival Flow",
  953: "True Essence of Wander",
  959: "God of the Road",
  966: "End of Hunger",
  973: "End of Search",
  979: "Abyss of Silence",
  986: "Final Snowfall",
  993: "Nothing Left to Find",
  1000: "Wolf’s Rain"
}
}
