import { AnimeThemeConfig } from "./types"
import { GiLightningStorm, GiCrown, GiBookAura, GiStarFormation, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiSpellBook, GiHeartKey, GiMagicSwirl } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const zatchBellTheme: AnimeThemeConfig = {
    id: "zatch-bell",
    displayName: "Zatch Bell!",
    description: "Kiyo Takamine is paired with the amnesiac Zatch Bell, a mamodo child who shoots lightning from his mouth. Together they must fight other mamodo-human pairs to determine who will become the King of the Mamodo World.",
    fontFamily: "'Righteous', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Righteous&display=swap",
    cssVars: {
        "--color-brand-200": "255 235 140",
        "--color-brand-300": "252 210 62",
        "--color-brand-400": "240 178 6",
        "--color-brand-500": "212 146 0",
        "--color-brand-600": "170 112 0",
        "--color-brand-700": "128 80 0",
        "--color-brand-800": "86 50 0",
        "--color-brand-900": "46 24 0",
        "--color-brand-950": "18 8 0",
        "--brand": "212 146 0",
        "--background": "#060500",
        "--paper": "#120e00",
        "--color-gray-950": "6 5 0",
        "--color-gray-900": "14 11 0",
        "--color-gray-800": "26 20 2",
        "--color-gray-700": "44 34 6",
        "--color-gray-600": "70 56 14",
        "--color-gray-500": "112 92 32",
        "--color-gray-400": "162 140 65",
        "--color-gray-300": "208 185 100",
        "--color-gray-200": "238 218 145",
        "--color-gray-100": "250 240 188",
        "--color-gray-50": "255 252 228",
    },
    sidebarOverrides: {
        "home": { icon: GiSpellBook, label: "Spell Book" },
        "schedule": { icon: GiAlarmClock, label: "Battle Schedule" },
        "manga": { icon: LuBookOpen, label: "Mamodo Files" },
        "lists": { icon: GiFlowerEmblem, label: "Mamodo Registry" },
        "discover": { icon: GiBullseye, label: "New Rivals" },
        "torrent-list": { icon: GiLightningStorm, label: "Spell Cache" },
        "debrid": { icon: GiBookAura, label: "Spell Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Partners" },
        "enmasse": { icon: GiResize, label: "Team Spells" },
        "scan-summaries": { icon: TbReportSearch, label: "Battle Reports" },
        "auto-downloader": { icon: LuRss, label: "Mamodo Feed" },
        "community": { icon: GiMagicSwirl, label: "Partner Circle" },
        "achievements": { icon: GiTrophy, label: "King's Trophies" },
        "milestones": { icon: LuFlag, label: "King Milestones" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Mamodo Alerts" },
        "theme-manager": { icon: GiPalette, label: "Gold Palette" },
        "extensions": { icon: BiExtension, label: "Spell Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Spell Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Kiyo's Config" },
    },
    achievementNames: {
        "a_first_episode": "First Spell",
        "a_first_complete": "Battle Won",
        "a_hundred_club": "Hundred Spells",
        "a_time_lord": "Mamodo Elder",
        "a_anime_collector": "Spell Archive",
        "a_library_legend": "Spell Library",
        "a_binge_king": "Battle Marathon",
        "a_no_sleep": "All-Night Study",
        "a_marathon_runner": "Kiyo's Run",
        "a_speed_run": "Zaker Speed",
        "a_completionist": "Full Spell Book",
        "a_mega_completionist": "Mamodo King",
        "a_loyal_fan": "Loyal Partner",
        "a_rewatcher": "Replay Battle",
        "a_decade_watcher": "Decade Mamodo",
        "a_genre_action": "Mamodo Battle",
        "a_genre_adventure": "World Journey",
        "a_genre_comedy": "Zatch Comedy",
        "a_genre_drama": "Partner Drama",
        "a_genre_fantasy": "Mamodo World",
        "a_genre_horror": "None Here",
        "a_genre_romance": "None Here",
        "a_genre_scifi": "None Here",
        "a_genre_supernatural": "Mamodo Power",
        "a_genre_psychological": "Kiyo's Strategy",
        "a_genre_mecha": "None Here",
        "a_critic": "Spell Critic",
        "a_perfect_ten": "Perfect Zaker",
        "a_harsh_critic": "Kiyo's Standard",
        "a_daily_streak": "Daily Training",
        "a_mega_streak": "Lightning Streak",
        "a_year_long": "Year of Battles",
        "a_iron_will": "Zatch's Heart",
        "a_hidden_gem": "Hidden Spell",
        "a_cult_classic": "Zatch Classic",
        "a_classic_connoisseur": "2003 Fan",
        "a_new_years_resolution": "New Year Spell",
        "a_christmas_special": "Winter Battle",
        "a_meta_tier_max": "True King",
        "a_meta_completionist": "All Spells",
        "a_sequel_chain": "Battle Chain",
        "a_zero_to_hero": "Weak to King",
        "a_night_owl": "Night Study",
        "a_early_bird": "Dawn Training",
        "m_first_chapter": "First Zaker",
        "m_first_complete": "Arc Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Spell Binge",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Zatch Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "New Battle",
        "m_genre_action": "Battle Chapter",
        "m_genre_adventure": "Journey Chapter",
        "m_genre_romance": "None Here",
        "m_genre_fantasy": "Mamodo Chapter",
        "m_genre_horror": "None Here",
        "m_genre_drama": "Drama Chapter",
        "m_genre_scifi": "None Here",
        "m_genre_supernatural": "Power Chapter",
        "m_genre_psychological": "Strategy Chapter",
        "m_critic": "Kiyo's Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Lightning Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Iron Partner",
        "m_hidden_gem": "Hidden Spell",
        "m_cult_classic": "Classic Chapter",
        "m_mangaka_lover": "Raiku Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Zatch Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Mamodo Art",
        "m_manga_to_anime": "Adapted Battle",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060500",
        primary: "#d49200",
        secondary: "#aa7000",
        accent: "#4080f0",
    },
    particleColor: "#f0c020",
    backgroundDim: 0.26,
    backgroundBlur: 14,
    particleTypes: {
        lightning_bolts: { label: "Zaker Lightning", maxCount: 14, defaultEnabled: true, defaultIntensity: 52 },
        golden_sparks: { label: "Spell Sparks", maxCount: 12, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
    "7": "Novice Rank 1",
    "13": "Novice Level 2",
    "20": "Novice Tier 3",
    "27": "Novice Class 4",
    "33": "Novice Grade 5",
    "40": "Novice Position 6",
    "47": "Novice Status 7",
    "53": "Novice Role 8",
    "60": "Novice Title 9",
    "67": "Novice Authority 10",
    "73": "Beginner Rank 11",
    "80": "Beginner Level 12",
    "87": "Beginner Tier 13",
    "93": "Beginner Class 14",
    "100": "Beginner Grade 15",
    "107": "Beginner Position 16",
    "113": "Beginner Status 17",
    "120": "Beginner Role 18",
    "127": "Beginner Title 19",
    "133": "Student Authority 20",
    "140": "Student Rank 21",
    "147": "Student Level 22",
    "153": "Student Tier 23",
    "160": "Student Class 24",
    "167": "Student Grade 25",
    "173": "Student Position 26",
    "180": "Student Status 27",
    "187": "Student Role 28",
    "193": "Student Title 29",
    "200": "Learner Authority 30",
    "207": "Learner Rank 31",
    "213": "Learner Level 32",
    "220": "Learner Tier 33",
    "227": "Learner Class 34",
    "233": "Learner Grade 35",
    "240": "Learner Position 36",
    "247": "Learner Status 37",
    "253": "Learner Role 38",
    "260": "Adept Title 39",
    "267": "Adept Authority 40",
    "273": "Adept Rank 41",
    "280": "Adept Level 42",
    "287": "Adept Tier 43",
    "293": "Adept Class 44",
    "300": "Adept Grade 45",
    "307": "Adept Position 46",
    "313": "Adept Status 47",
    "320": "Expert Role 48",
    "327": "Expert Title 49",
    "333": "Expert Authority 50",
    "340": "Expert Rank 51",
    "347": "Expert Level 52",
    "353": "Expert Tier 53",
    "360": "Expert Class 54",
    "367": "Expert Grade 55",
    "373": "Expert Position 56",
    "380": "Expert Status 57",
    "387": "Master Role 58",
    "393": "Master Title 59",
    "400": "Master Authority 60",
    "407": "Master Rank 61",
    "413": "Master Level 62",
    "420": "Master Tier 63",
    "427": "Master Class 64",
    "433": "Master Grade 65",
    "440": "Master Position 66",
    "447": "Grandmaster Status 67",
    "453": "Grandmaster Role 68",
    "460": "Grandmaster Title 69",
    "467": "Grandmaster Authority 70",
    "473": "Grandmaster Rank 71",
    "480": "Grandmaster Level 72",
    "487": "Grandmaster Tier 73",
    "493": "Grandmaster Class 74",
    "500": "Grandmaster Grade 75",
    "507": "Sage Position 76",
    "513": "Sage Status 77",
    "520": "Sage Role 78",
    "527": "Sage Title 79",
    "533": "Sage Authority 80",
    "540": "Sage Rank 81",
    "547": "Sage Level 82",
    "553": "Sage Tier 83",
    "560": "Sage Class 84",
    "567": "Sage Grade 85",
    "573": "Legend Position 86",
    "580": "Legend Status 87",
    "587": "Legend Role 88",
    "593": "Legend Title 89",
    "600": "Legend Authority 90",
    "607": "Legend Rank 91",
    "613": "Legend Level 92",
    "620": "Legend Tier 93",
    "627": "Legend Class 94",
    "633": "Mythical Grade 95",
    "640": "Mythical Position 96",
    "647": "Mythical Status 97",
    "653": "Mythical Role 98",
    "660": "Mythical Title 99",
    "667": "Mythical Authority 100",
    "673": "Mythical Rank 101",
    "680": "Mythical Level 102",
    "687": "Mythical Tier 103",
    "693": "Mythical Class 104",
    "700": "Godly Grade 105",
    "707": "Godly Position 106",
    "713": "Godly Status 107",
    "720": "Godly Role 108",
    "727": "Godly Title 109",
    "733": "Godly Authority 110",
    "740": "Godly Rank 111",
    "747": "Godly Level 112",
    "753": "Godly Tier 113",
    "760": "Supreme Class 114",
    "767": "Supreme Grade 115",
    "773": "Supreme Position 116",
    "780": "Supreme Status 117",
    "787": "Supreme Role 118",
    "793": "Supreme Title 119",
    "800": "Supreme Authority 120",
    "807": "Supreme Rank 121",
    "813": "Supreme Level 122",
    "820": "Infinite Tier 123",
    "827": "Infinite Class 124",
    "833": "Infinite Grade 125",
    "840": "Infinite Position 126",
    "847": "Infinite Status 127",
    "853": "Infinite Role 128",
    "860": "Infinite Title 129",
    "867": "Infinite Authority 130",
    "873": "Infinite Rank 131",
    "880": "Infinite Level 132",
    "887": "Eternal Tier 133",
    "893": "Eternal Class 134",
    "900": "Eternal Grade 135",
    "907": "Eternal Position 136",
    "913": "Eternal Status 137",
    "920": "Eternal Role 138",
    "927": "Eternal Title 139",
    "933": "Eternal Authority 140",
    "940": "Eternal Rank 141",
    "947": "Transcendent Level 142",
    "953": "Transcendent Tier 143",
    "960": "Transcendent Class 144",
    "967": "Transcendent Grade 145",
    "973": "Transcendent Position 146",
    "980": "Transcendent Status 147",
    "987": "Transcendent Role 148",
    "993": "Transcendent Title 149",
    "1000": "Transcendent Authority 150"
},
}
