import { AnimeThemeConfig } from "./types"
import { GiLightningStorm, GiCrown, GiBookAura, GiStarFormation, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiSpellBook, GiHeartKey, GiMagicSwirl } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const zatchBellTheme: AnimeThemeConfig = {
    id: "zatch-bell",
    displayName: "Zatch Bell!",
    description: "Kiyo Takamine is paired with the amnesiac Zatch Bell, a mamodo child who shoots lightning from his mouth. Together they must fight other mamodo-human pairs to determine who will become the King of the Mamodo World.",
    fontFamily: "'Righteous', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Righteous&display=swap",
    cssVars: {
        "--color-brand-200": "255 235 140",
        "--color-brand-300": "252 210 62",
        "--color-brand-400": "240 178 6",
        "--color-brand-500": "212 146 0",
        "--color-brand-600": "170 112 0",
        "--color-brand-700": "128 80 0",
        "--color-brand-800": "86 50 0",
        "--color-brand-900": "46 24 0",
        "--color-brand-950": "18 8 0",
        "--brand": "212 146 0",
        "--background": "#060500",
        "--paper": "#120e00",
        "--color-gray-950": "6 5 0",
        "--color-gray-900": "14 11 0",
        "--color-gray-800": "26 20 2",
        "--color-gray-700": "44 34 6",
        "--color-gray-600": "70 56 14",
        "--color-gray-500": "112 92 32",
        "--color-gray-400": "162 140 65",
        "--color-gray-300": "208 185 100",
        "--color-gray-200": "238 218 145",
        "--color-gray-100": "250 240 188",
        "--color-gray-50": "255 252 228",
    },
    sidebarOverrides: {
        "home": { icon: GiSpellBook, label: "Spell Book" },
        "schedule": { icon: GiAlarmClock, label: "Battle Schedule" },
        "manga": { icon: LuBookOpen, label: "Mamodo Files" },
        "lists": { icon: GiFlowerEmblem, label: "Mamodo Registry" },
        "discover": { icon: GiBullseye, label: "New Rivals" },
        "torrent-list": { icon: GiLightningStorm, label: "Spell Cache" },
        "debrid": { icon: GiBookAura, label: "Spell Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Partners" },
        "enmasse": { icon: GiResize, label: "Team Spells" },
        "scan-summaries": { icon: TbReportSearch, label: "Battle Reports" },
        "auto-downloader": { icon: LuRss, label: "Mamodo Feed" },
        "community": { icon: GiMagicSwirl, label: "Partner Circle" },
        "achievements": { icon: GiTrophy, label: "King's Trophies" },
        "milestones": { icon: LuFlag, label: "King Milestones" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Mamodo Alerts" },
        "theme-manager": { icon: GiPalette, label: "Gold Palette" },
        "extensions": { icon: BiExtension, label: "Spell Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Spell Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Kiyo's Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Spell",
        "a_episode_counter": "Winter Battle Mark",
        "a_episode_titan": "Kiyo Takamine Relic",
        "a_hours_invested": "All Night Proof",
        "a_time_lord": "Mamodo Elder",
        "a_anime_collector": "Spell Archive",
        "a_library_legend": "Spell Library",
        "a_first_complete": "Battle Won",
        "a_hundred_club": "Hundred Spells",
        "a_first_day": "Battle Chain Seal",
        "a_first_rating": "Kiyo Takamine Appraisal",
        "a_ten_thousand_min": "World Journey Standard",
        "a_season_veteran": "World Journey Library",
        "a_year_explorer": "Spell Archive Map",
        "a_century_watcher": "Loyal Partner Ledger",
        "a_five_hundred_eps": "Hidden Spell Dominion",
        "a_thousand_eps": "Perfect Zaker Record",
        "a_watching_ten": "Raiku Fan Acclaim",
        "a_ptw_hoarder": "King's Trophies Library",
        "a_dropped_honesty": "Raiku Fan Summit",
        "a_five_thousand_eps": "Replay Battle Warrant",
        "a_ten_completed": "Spell Critic Afterglow",
        "a_fifty_completed": "Zatch's Heart Ascension",
        "a_five_hundred_completed": "Raiku Fan Clear",
        "a_mean_score_tracker": "Dawn Training Verdict",
        "a_unique_studios": "Perfect Zaker Collection",
        "a_days_spent_watching": "Mamodo Registry Dominion",
        "a_all_status": "Kiyo's Review Testament",
        "a_first_favorite": "Night Study Cabinet",
        "a_favorites_collector": "Iron Partner Shelf",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Zatch Expert Drive",
        "a_marathon_runner": "Kiyo's Run",
        "a_weekend_warrior": "Kiyo Takamine Ordeal",
        "a_non_stop": "Battle Marathon Fever",
        "a_one_more_episode": "Spell Library Mantle",
        "a_speed_run": "Zaker Speed",
        "a_double_feature": "Team Spells Crown",
        "a_triple_threat": "Decade Mamodo Record",
        "a_five_a_day": "Spell Vault Accord",
        "a_back_to_back": "Zatch Classic Surge",
        "a_seasonal_binge": "Kiyo Takamine Cascade",
        "a_cour_crusher": "Mamodo Registry Ordeal",
        "a_half_day_watch": "Winter Battle Crown",
        "a_full_day_watch": "Mamodo World Pinnacle",
        "a_power_weekend": "Battle Chain Run",
        "a_binge_king": "Battle Marathon",
        "a_no_sleep": "All-Night Study",
        "a_entire_season": "Zatch Comedy Library",
        "a_seven_day_challenge": "Mamodo World Mark",
        "a_hundred_day_binge": "Battle Chain Surge",
        "a_genre_binge": "Kiyo's Strategy Binge",
        "a_studio_binge": "Winter Battle Fever",
        "a_season_sweep": "Kiyo's Standard Codex",
        "a_forty_eight_hour": "Gold Palette Overture",
        "a_ep_counter_day": "Spell Critic Aegis",
        "a_multi_series_binge": "King's Trophies Streak",
        "a_midnight_binge": "Spell Library Cascade",
        "a_new_year_binge": "Mamodo Power Drive",

        // ── ANIME GENRES ──
        "a_genre_action": "Mamodo Battle",
        "a_genre_adventure": "World Journey",
        "a_genre_comedy": "Zatch Comedy",
        "a_genre_drama": "Partner Drama",
        "a_genre_fantasy": "Mamodo World",
        "a_genre_horror": "None Here",
        "a_genre_mystery": "Adapted Battle Mystery",
        "a_genre_romance": "None Here",
        "a_genre_scifi": "None Here",
        "a_genre_sol": "Replay Battle Slice",
        "a_genre_sports": "Gold Palette Sports",
        "a_genre_supernatural": "Mamodo Power",
        "a_genre_thriller": "Zatch's Heart Thriller",
        "a_genre_mecha": "None Here",
        "a_genre_music": "World Journey Music",
        "a_genre_psychological": "Kiyo's Strategy",
        "a_genre_ecchi": "Zatch Expert Ecchi",
        "a_genre_mahou_shoujo": "Decade Mamodo Magic Shoujo",
        "a_tag_isekai": "Zatch Bell Isekai",
        "a_tag_harem": "Kiyo's Run Harem",
        "a_tag_bl": "Gold Palette Bl",
        "a_tag_gl": "Spell Library Gl",
        "a_tag_historical": "Battle Won Historical",
        "a_tag_military": "Hidden Spell Military",
        "a_tag_school": "King's Trophies School",
        "a_tag_martial_arts": "Mamodo World Martial Arts",
        "a_tag_vampire": "Decade Mamodo Vampire",
        "a_tag_samurai": "Perfect Zaker Samurai",
        "a_tag_space": "All Spells Space",
        "a_tag_parody": "Zaker Speed Parody",
        "a_tag_idol": "Gold Palette Idol",
        "a_tag_post_apocalyptic": "Partner Circle Post Apocalyptic",
        "a_tag_cyberpunk": "Battle Marathon Cyberpunk",
        "a_tag_shounen": "Partner Circle Shounen",
        "a_tag_seinen": "Spell Binge Seinen",
        "a_tag_shoujo": "Spell Binge Shoujo",
        "a_tag_josei": "Spell Critic Josei",
        "a_tag_survival": "Iron Partner Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Spell Book",
        "a_mega_completionist": "Mamodo King",
        "a_completion_rate_50": "Decade Mamodo Return",
        "a_completion_rate_75": "Zatch's Heart Crown",
        "a_completion_rate_90": "Spell Critic Resolution",
        "a_no_drop": "Adapted Battle Decree",
        "a_long_runner_complete": "Battle Chain Clear",
        "a_sequel_chain": "Battle Chain",
        "a_clean_list": "Kiyo's Standard Relic",
        "a_from_ptw": "Zaker Speed Index",
        "a_rewatch_master": "Dawn Training Return",
        "a_short_complete": "Partner Drama Endgame",
        "a_same_day_start_finish": "Daily Training Pinnacle",
        "a_revival": "Loyal Partner Insignia",
        "a_zero_to_hero": "Weak to King",
        "a_five_genre_complete": "Partner Drama A Five Genre",
        "a_full_franchise": "King's Trophies Chronicle",
        "a_batch_complete": "Kiyo Takamine Crown",
        "a_paused_to_done": "Spell Critic Aegis Aegis",
        "a_completion_spree": "Mamodo Alerts Triumph",
        "a_multi_rewatch": "Mamodo Alerts Triumph Triumph",
        "a_dropped_recovery": "Winter Battle Conquest",
        "a_ten_perfect_scores": "Battle Chain Acclaim",
        "a_seasonal_clear": "Mamodo Registry Codex",
        "a_complete_genre_span": "Mamodo Art A Complete Genre",
        "a_monthly_completions": "Dawn Training Afterglow",
        "a_yearly_completions": "Kiyo's Review Epilogue",
        "a_rapid_complete": "Mamodo World Finale",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Partner",
        "a_studio_devotee": "Adapted Battle Treasury",
        "a_rewatcher": "Replay Battle",
        "a_triple_rewatch": "Kiyo's Strategy Coda",
        "a_annual_tradition": "Mamodo World Proof",
        "a_director_fan": "Kiyo's Standard Trial",
        "a_voice_actor_fan": "Winter Battle Crown Crown",
        "a_ost_lover": "King's Trophies Seal",
        "a_source_reader": "Spell Archive Cabinet",
        "a_waiting_weekly": "Adapted Battle Clock",
        "a_childhood_revisit": "Lost Partners Seal",
        "a_saga_tracker": "All Spells Standard",
        "a_genre_loyalty": "Replay Battle Loyalty",
        "a_decade_watcher": "Decade Mamodo",
        "a_adaptation_hunter": "Zaker Speed Trial",
        "a_original_anime_fan": "Mamodo Elder Testament",
        "a_long_commitment": "Mamodo World Mark Mark",
        "a_perfect_attendance": "Raiku Fan Standard",
        "a_favorite_studio_5": "Partner Circle Library",
        "a_complete_catalog": "Iron Partner Seal",
        "a_franchise_collector": "Partner Circle Archive",
        "a_airing_follower": "Lost Partners Signal",
        "a_genre_master": "Kiyo's Standard Master",
        "a_staff_follower": "Partner Circle Oath",
        "a_multi_season_fan": "Battle Won Hoard",
        "a_format_diversity": "Decade Mamodo Cache",
        "a_year_dedication": "Kiyo Takamine Tenure",
        "a_season_dedication": "Hidden Spell Codex",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Kiyo's Strategy Explorer",
        "a_studio_hopper": "Dawn Training Collection",
        "a_tag_explorer": "Kiyo Takamine Explorer",
        "a_decade_hopper": "King's Trophies Chronicle Chronicle",
        "a_hidden_gem": "Hidden Spell",
        "a_popular_taste": "Gold Palette Decree",
        "a_retro_appreciator": "Iron Partner Aegis",
        "a_modern_viewer": "Daily Training Pinnacle Pinnacle",
        "a_cross_demographic": "Zatch Expert Pinnacle",
        "a_underdog_fan": "Mamodo Art Trial",
        "a_variety_week": "Partner Circle Horizon",
        "a_foreign_cinema": "Spell Library Expedition",
        "a_classic_connoisseur": "2003 Fan",
        "a_every_season": "Lost Partners Archive",
        "a_award_winner": "World Journey Insignia",
        "a_niche_explorer": "Spell Binge Horizon",
        "a_global_anime": "Partner Drama Crown",
        "a_cult_classic": "Zatch Classic",
        "a_random_pick": "Gold Palette Decree Decree",
        "a_new_genre_month": "Raiku Fan A New Genre",
        "a_seasonal_completionist": "Loyal Partner Summit",
        "a_unpopular_opinion": "Night Study Standard",
        "a_top_rated_viewer": "Spell Vault Seal",
        "a_source_variety": "Mamodo Registry Storehouse",
        "a_low_score_brave": "Battle Marathon Measure",
        "a_upcoming_watcher": "Spell Vault Seal Seal",
        "a_short_series_explorer": "Spell Library Expedition Expedition",
        "a_long_series_explorer": "Team Spells Passage",

        // ── ANIME TIME ──
        "a_night_owl": "Night Study",
        "a_early_bird": "Dawn Training",
        "a_lunch_break": "Spell Book Trial",
        "a_golden_hour": "Mamodo Battle Tenure",
        "a_four_am_club": "Mamodo Alerts Gathering",
        "a_witching_hour": "Zatch's Heart Tenure",
        "a_new_year_watch": "Kiyo Takamine Season",
        "a_midnight_premiere": "Mamodo Power Devotion",
        "a_all_hours": "Loyal Partner Seal",
        "a_dawn_warrior": "Gold Palette Aegis",
        "a_afternoon_delight": "All Night Proof Proof",
        "a_prime_time": "World Journey Insignia Insignia",
        "a_workday_watcher": "Zatch Expert Pinnacle Pinnacle",
        "a_sunday_marathon": "Battle Chain Momentum",
        "a_rainy_day": "Zatch's Heart Relic",
        "a_morning_routine": "Battle Won Promise",
        "a_night_shift": "Decade Mamodo Aegis",
        "a_twilight_zone": "Zatch Comedy Ledger",
        "a_seasonal_premier": "Adapted Battle Cabinet",
        "a_clock_collector": "Mamodo Alerts Repository",
        "a_weekend_binge_hours": "Spell Binge Streak",
        "a_late_night_regular": "Kiyo's Review Dominion",
        "a_sunrise_watcher": "Kiyo's Standard Relic Relic",
        "a_holiday_watcher": "Spell Vault Pact",
        "a_every_day_of_week": "Zatch Classic Ledger",
        "a_monthly_hours": "Gold Palette Streak",

        // ── ANIME SOCIAL ──
        "a_first_party": "Spell Critic Record",
        "a_party_host": "Decade Mamodo Record Record",
        "a_social_butterfly": "Spell Archive Company",
        "a_group_binge": "Perfect Zaker Sprint",
        "a_party_regular": "Zatch Comedy Chronicle",
        "a_sync_viewer": "Mamodo Alerts Standard",
        "a_commentator": "Iron Partner Record",
        "a_party_marathon": "Kiyo's Strategy Vigil",
        "a_full_house": "Hidden Spell Trial",
        "a_community_pillar": "Kiyo's Review Alliance",
        "a_watch_party_streak": "Iron Partner Vigil",
        "a_diverse_party": "Battle Won Seal",
        "a_late_night_party": "Kiyo's Review Testament Testament",
        "a_party_veteran": "Hidden Spell Testament",
        "a_genre_party": "Spell Library Party",
        "a_weekly_party": "Mamodo Alerts Calendar",
        "a_silent_viewer": "Mamodo Elder Mantle",
        "a_recommendation_giver": "Spell Binge Network",
        "a_party_completionist": "All Spells Coda",
        "a_social_scorer": "Kiyo's Standard Balance",

        // ── ANIME SPECIAL ──
        "a_round_number": "Team Spells Proof",
        "a_fibonacci": "Kiyo Takamine Dominion",
        "a_palindrome_day": "Kiyo Takamine Relic Relic",
        "a_binary_day": "Replay Battle Mark",
        "a_full_moon": "Lost Partners Insignia",
        "a_leap_year": "Partner Drama Devotion",
        "a_time_traveler": "Adapted Battle Record",
        "a_genre_clash": "Kiyo's Strategy Clash",
        "a_triple_seven": "Kiyo Takamine Testament",
        "a_thousand_complete": "Mamodo Elder Epilogue",
        "a_pi_episodes": "Zatch Expert Crown",
        "a_synchronicity": "Mamodo Art Anchor",
        "a_world_record": "Winter Battle Warrant",
        "a_nice": "World Journey Chronicle",
        "a_power_level": "Mamodo Elder Testament Testament",
        "a_answer_42": "Gold Palette Standard",
        "a_square_number": "Kiyo's Strategy Decree",
        "a_prime_count": "World Journey Seal",
        "a_matching_date": "Mamodo Art Mantle",
        "a_century_episode": "Zatch Expert Mark",
        "a_double_digits": "Zatch's Heart Testament",
        "a_one_two_three": "Partner Drama Crown Crown",
        "a_lucky_seven": "Mamodo World Crown",
        "a_all_tens": "Battle Marathon Criterion",
        "a_exact_hundred_eps": "All Spells Legend",
        "a_year_match_count": "Adapted Battle Yearlong",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Spell Binge Ledger",
        "a_movie_buff": "Winter Battle Mark Mark",
        "a_ova_hunter": "All Spells Standard Standard",
        "a_ona_explorer": "Mamodo Art Secret",
        "a_special_watcher": "Zatch's Heart Relic Relic",
        "a_short_king": "Kiyo's Run Crown",
        "a_variety_pack": "Winter Battle Inquiry",
        "a_film_festival": "Spell Vault Chronicle",
        "a_music_video": "Battle Won Chronicle",
        "a_tv_short": "Kiyo's Strategy Record",
        "a_movie_marathon": "Kiyo's Strategy Gauntlet",
        "a_double_length": "Team Spells Crown Crown",
        "a_anthology": "Decade Mamodo Aegis Aegis",
        "a_mini_series": "Night Study Decree",
        "a_theatrical": "Partner Circle Accord",
        "a_format_master": "Mamodo Alerts Vault",
        "a_long_movie": "Loyal Partner Insignia Insignia",
        "a_back_catalog": "Iron Partner Standard",
        "a_cm_watcher": "Zatch Bell Aegis",
        "a_pv_collector": "Mamodo Art Storehouse",
        "a_format_balance": "Mamodo Alerts Vault Vault",
        "a_episodic_master": "Zatch Bell Standard",
        "a_sequel_movie": "Partner Drama Pinnacle",
        "a_recap_watcher": "Spell Book Testament",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Training",
        "a_mega_streak": "Lightning Streak",
        "a_weekly_warrior": "Hidden Spell Season",
        "a_monthly_watcher": "Mamodo Power Calendar",
        "a_comeback": "Spell Archive Decree",
        "a_weekend_streak": "Battle Marathon Passage",
        "a_no_zero_days": "Replay Battle Warrant Warrant",
        "a_iron_will": "Zatch's Heart",
        "a_habit_formed": "Zatch Classic Banner",
        "a_consistent_pace": "Team Spells Measure",
        "a_year_long": "Year of Battles",
        "a_double_streak": "Kiyo's Standard Watch",
        "a_streak_recovery": "Mamodo Elder Season",
        "a_daily_minimum": "Mamodo Power Focus",
        "a_winter_streak": "Spell Library Watch",
        "a_summer_streak": "Zatch's Heart Resolve",
        "a_morning_streak": "Iron Partner Clock",
        "a_night_streak": "Zatch Classic Constancy",
        "a_unbreakable": "Kiyo's Run Proof",
        "a_eternal_flame": "Dawn Training Standard",
        "a_completion_streak": "All Spells Return",
        "a_rating_streak": "Kiyo Takamine Balance",
        "a_multi_ep_streak": "Winter Battle Ritual",
        "a_genre_streak": "Kiyo Takamine Streak",
        "a_studio_streak": "Spell Archive Cabinet Cabinet",
        "a_perfect_week": "Mamodo Art Relic",

        // ── ANIME SCORING ──
        "a_critic": "Spell Critic",
        "a_perfect_ten": "Perfect Zaker",
        "a_harsh_critic": "Kiyo's Standard",
        "a_fair_judge": "Kiyo's Review Balance",
        "a_generous_spirit": "Mamodo Power Pinnacle",
        "a_score_all": "All Night Criterion",
        "a_wide_range": "World Journey Ledger",
        "a_controversial": "Iron Partner Decree",
        "a_consistent_scorer": "Adapted Battle Verdict",
        "a_score_sniper": "Partner Drama Score",
        "a_evolving_taste": "Kiyo's Standard Testament",
        "a_bell_curve": "Raiku Fan Insignia",
        "a_picky_watcher": "Mamodo Elder Warrant",
        "a_100_rated": "Mamodo Alerts Warrant",
        "a_500_rated": "Kiyo's Run Pinnacle",
        "a_mediocre_majority": "Mamodo Art Canon",
        "a_rating_spree": "Iron Partner Review",
        "a_score_variance": "Battle Marathon Score",
        "a_masterpiece_hunter": "Iron Partner Banner",
        "a_contrarian": "Kiyo's Strategy Record Record",
        "a_optimist": "Battle Won Ledger",
        "a_score_distributor": "Spell Book Appraisal",
        "a_genre_critic": "Team Spells Critic",
        "a_mean_above_8": "Mamodo World Scrutiny",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Spell",
        "a_valentines_weeb": "Partner Circle Vow",
        "a_pi_day": "Kiyo's Review Trial",
        "a_april_fools": "Partner Drama Devotion Devotion",
        "a_international_anime_day": "Loyal Partner Record",
        "a_star_wars_day": "Battle Chain Chronicle",
        "a_summer_solstice": "Replay Battle Calendar",
        "a_tanabata": "Daily Training Focus",
        "a_friday_13th": "Spell Book Relic",
        "a_halloween_spirit": "Spell Binge Vow",
        "a_thanksgiving_binge": "Zatch Comedy Run",
        "a_christmas_special": "Winter Battle",
        "a_new_years_eve": "Mamodo World Pilgrimage",
        "a_birthday_watch": "Raiku Fan Vow",
        "a_holiday_marathon": "Perfect Zaker Overture",
        "a_independence_day": "Dawn Training Banner",
        "a_culture_day": "King's Trophies Insignia",
        "a_spring_equinox": "Perfect Zaker Decree",
        "a_earth_day": "Winter Battle Mantle",
        "a_labor_day": "Spell Binge Seal",
        "a_winter_solstice": "Zatch Expert Pilgrimage",
        "a_anime_birthday": "Winter Battle Pilgrimage",
        "a_every_holiday": "Zaker Speed Resolve",
        "a_consecutive_holidays": "Zatch's Heart Season",

        // ── ANIME META ──
        "a_meta_first_unlock": "Spell Archive Rank",
        "a_meta_collector": "King's Trophies Hoard",
        "a_meta_category_starter": "Mamodo Power Badge",
        "a_meta_tier_climber": "King's Trophies Glyph",
        "a_meta_tier_max": "True King",
        "a_meta_xp_earner": "Spell Book Emblem",
        "a_meta_difficulty_easy": "Kiyo's Review Mechanism",
        "a_meta_difficulty_hard": "Spell Vault Writ",
        "a_meta_unlock_spree": "Hidden Spell Panel",
        "a_meta_completionist": "All Spells",
        "a_meta_diverse": "Kiyo Takamine Emblem",
        "a_meta_dominator": "Zatch Comedy Token",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Zaker",
        "m_chapter_counter": "Mamodo Alerts Pinnacle",
        "m_chapter_titan": "Mamodo Registry Relic",
        "m_reading_hours": "Spell Book Relic Relic",
        "m_reading_time_lord": "Loyal Partner Record Record",
        "m_manga_collector": "Hidden Spell Ledger",
        "m_library_legend": "King's Trophies Reliquary",
        "m_first_complete": "Arc Done",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "Partner Circle Seal",
        "m_first_rating": "Spell Book Eye",
        "m_ten_thousand_pages": "Partner Circle Gauge",
        "m_volume_collector": "Mamodo Elder Storehouse",
        "m_year_explorer": "Gold Palette Quest",
        "m_century_reader": "Spell Library Dominion",
        "m_five_hundred_ch": "World Journey Legend",
        "m_thousand_ch": "Kiyo's Standard Legend",
        "m_reading_ten": "Spell Library Appraisal",
        "m_ptr_hoarder": "Kiyo's Standard Index",
        "m_dropped_honesty": "King's Trophies Summit",
        "m_season_reader": "Iron Partner Treasury",
        "m_active_reader": "Zatch's Heart Trial",
        "m_five_thousand_ch": "Kiyo's Strategy Standard",
        "m_ten_completed": "Kiyo's Strategy Resolution",
        "m_fifty_completed": "Kiyo's Standard Harvest",
        "m_five_hundred_completed": "Zatch Classic Legacy",
        "m_mean_score_tracker": "Adapted Battle Audit",
        "m_unique_authors": "Winter Battle Reserve",
        "m_all_status": "Zatch's Heart Testament Testament",
        "m_first_favorite": "All Spells Cache",
        "m_favorites_collector": "Spell Archive Shelf",
        "m_days_spent_reading": "Zatch Expert Relic",

        // ── MANGA BINGE ──
        "m_binge_reader": "Raiku Fan Streak",
        "m_marathon_reader": "Kiyo's Review Rush",
        "m_weekend_reader": "Lost Partners Run",
        "m_non_stop_reading": "All Spells Gauntlet",
        "m_one_more_chapter": "Spell Book Testament Testament",
        "m_speed_read": "Replay Battle Drive",
        "m_double_story": "Perfect Zaker Banner",
        "m_triple_read": "Dawn Training Record",
        "m_five_a_day": "Battle Won Insignia",
        "m_chapter_chain": "King's Trophies Accord",
        "m_volume_binge": "Battle Marathon Drive",
        "m_power_reader": "Battle Chain Seal Seal",
        "m_half_day_read": "Spell Archive Aegis",
        "m_full_day_read": "Zatch Bell Aegis Aegis",
        "m_power_weekend": "Partner Circle Streak",
        "m_binge_king": "Spell Binge",
        "m_no_sleep_read": "Spell Library Rush",
        "m_full_series_rush": "Kiyo's Review Cascade",
        "m_seven_day_challenge": "Daily Training Warrant",
        "m_hundred_day_read": "Kiyo Takamine Legend",
        "m_volume_rush": "Spell Critic Gauntlet",
        "m_series_sweep": "Zaker Speed Trial Trial",
        "m_genre_binge": "Zatch Bell Binge",
        "m_author_binge": "Lost Partners Surge",
        "m_chapter_counter_day": "Zatch Comedy Ledger Ledger",
        "m_multi_series_binge": "World Journey Charge",
        "m_midnight_binge": "Kiyo's Standard Tempest",
        "m_new_year_binge": "Winter Battle Passage",
        "m_forty_eight_hour": "Adapted Battle Rally",
        "m_oneshot_binge": "Replay Battle Marathon",

        // ── MANGA GENRES ──
        "m_genre_action": "Battle Chapter",
        "m_genre_adventure": "Journey Chapter",
        "m_genre_comedy": "Spell Archive Comedy",
        "m_genre_drama": "Drama Chapter",
        "m_genre_fantasy": "Mamodo Chapter",
        "m_genre_horror": "None Here",
        "m_genre_mystery": "Kiyo's Strategy Mystery",
        "m_genre_romance": "None Here",
        "m_genre_scifi": "None Here",
        "m_genre_sol": "Mamodo Alerts Slice",
        "m_genre_sports": "Spell Critic Sports",
        "m_genre_supernatural": "Power Chapter",
        "m_genre_thriller": "Mamodo Art Thriller",
        "m_genre_psychological": "Strategy Chapter",
        "m_genre_isekai": "Hidden Spell Isekai",
        "m_genre_shounen": "Mamodo Battle Shounen",
        "m_genre_ecchi": "Team Spells Ecchi",
        "m_genre_mahou_shoujo": "Spell Archive Magic Shoujo",
        "m_genre_mecha": "Mamodo Elder Mecha",
        "m_genre_music": "Spell Binge Music",
        "m_tag_isekai_new": "Spell Book Isekai New",
        "m_tag_harem": "All Night Harem",
        "m_tag_bl": "Night Study Bl",
        "m_tag_gl": "Kiyo's Standard Gl",
        "m_tag_historical": "World Journey Historical",
        "m_tag_military": "Mamodo Battle Military",
        "m_tag_school": "Partner Circle School",
        "m_tag_martial_arts": "Mamodo Alerts Martial Arts",
        "m_tag_vampire": "Spell Critic Vampire",
        "m_tag_samurai": "Decade Mamodo Samurai",
        "m_tag_space": "Night Study Space",
        "m_tag_parody": "Mamodo Elder Parody",
        "m_tag_idol": "Night Study Idol",
        "m_tag_post_apocalyptic": "King's Trophies Post Apocalyptic",
        "m_tag_cyberpunk": "All Night Cyberpunk",
        "m_tag_shoujo": "Spell Vault Shoujo",
        "m_tag_survival": "Spell Archive Survival",
        "m_tag_cooking": "Raiku Fan Cooking",
        "m_tag_medical": "Zatch's Heart Medical",
        "m_tag_villainess": "Lost Partners Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Zatch Expert",
        "m_completion_rate_50": "Night Study Return",
        "m_completion_rate_75": "Mamodo Art Ascension",
        "m_completion_rate_90": "Dawn Training Resolution",
        "m_no_drop": "All Spells Decree",
        "m_long_runner_complete": "Zatch Comedy Clear",
        "m_sequel_chain": "Spell Binge Seal Seal",
        "m_clean_list": "Mamodo Registry Relic Relic",
        "m_from_ptr": "Spell Vault Watchlist",
        "m_reread_master": "Kiyo's Review Trial Trial",
        "m_oneshot_complete": "Kiyo's Review Ascension",
        "m_same_day_start_finish": "Mamodo World Crown Crown",
        "m_revival": "Zatch Comedy Accord",
        "m_zero_to_hundred": "Kiyo's Strategy Banner",
        "m_five_genre_complete": "Replay Battle M Five Genre",
        "m_full_collection": "Mamodo World Proof Proof",
        "m_batch_complete": "Adapted Battle Summit",
        "m_paused_to_done": "Dawn Training Standard Standard",
        "m_completion_spree": "Kiyo's Run Triumph",
        "m_format_completionist": "Kiyo's Review Completion",
        "m_catch_up": "Loyal Partner Chronicle",
        "m_multi_reread": "All Spells Banner",
        "m_dropped_recovery": "Team Spells Conquest",
        "m_ten_perfect_scores": "Lost Partners Judgment",
        "m_complete_genre_span": "Hidden Spell M Complete Genre",
        "m_monthly_completions": "Zatch Bell Return",
        "m_yearly_completions": "Hidden Spell Epilogue",
        "m_rapid_complete": "Daily Training Finale",
        "m_author_complete": "Partner Circle Clear",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Devoted Reader",
        "m_mangaka_lover": "Raiku Fan",
        "m_rereader": "New Battle",
        "m_triple_reread": "Kiyo Takamine Testament Testament",
        "m_annual_reread": "Kiyo's Strategy Banner Banner",
        "m_publisher_fan": "Kiyo's Run Mark",
        "m_artist_fan": "Spell Binge Insignia",
        "m_adaptation_compare": "Raiku Fan Insignia Insignia",
        "m_source_material_fan": "Manga First",
        "m_waiting_weekly": "Decade Mamodo Streak",
        "m_classic_reader": "Mamodo Elder Lantern",
        "m_saga_reader": "King's Trophies Decree",
        "m_genre_loyalty": "Team Spells Loyalty",
        "m_decade_reader": "Battle Marathon Warrant",
        "m_ln_adaptation": "Battle Marathon Mark",
        "m_original_work": "Spell Critic Standard",
        "m_long_commitment": "Team Spells Mark",
        "m_up_to_date": "Winter Battle Warrant Warrant",
        "m_favorite_mangaka": "Gold Palette Treasury",
        "m_complete_portfolio": "Kiyo's Run Triumph Triumph",
        "m_franchise_collector": "Loyal Partner Archive",
        "m_serialization_follower": "Gold Palette Handshake",
        "m_genre_master": "Mamodo Registry Master",
        "m_multi_series_author": "King's Trophies Insignia Insignia",
        "m_format_diversity": "Spell Critic Shelf",
        "m_year_dedication": "Spell Library Tenure",
        "m_ongoing_follower": "Battle Marathon Fellowship",
        "m_genre_loyalty_50": "Kiyo's Standard Loyalty 50",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Perfect Zaker Explorer",
        "m_publisher_hopper": "Kiyo's Run Mantle",
        "m_tag_explorer": "Zaker Speed Explorer",
        "m_decade_hopper": "Spell Vault Chronicle Chronicle",
        "m_hidden_gem": "Hidden Spell",
        "m_popular_taste": "Adapted Battle Record Record",
        "m_retro_reader": "Adapted Battle Accord",
        "m_modern_reader": "World Journey Seal Seal",
        "m_cross_demographic": "Mamodo Power Crown",
        "m_underdog_fan": "Adapted Battle Accord Accord",
        "m_variety_week": "Spell Binge Horizon Horizon",
        "m_manhwa_reader": "Partner Drama Proof",
        "m_manhua_reader": "Mamodo Elder Mantle Mantle",
        "m_classic_connoisseur": "Zatch Classic Glimpse",
        "m_award_winner": "Spell Library Warrant",
        "m_niche_explorer": "Raiku Fan Horizon",
        "m_world_manga": "Loyal Partner Chronicle Chronicle",
        "m_cult_classic": "Classic Chapter",
        "m_random_pick": "Adapted Battle Standard",
        "m_new_genre_month": "Loyal Partner M New Genre",
        "m_year_completionist": "Mamodo Alerts Fulfillment",
        "m_unpopular_opinion": "Winter Battle Trial",
        "m_top_rated_reader": "Raiku Fan Record",
        "m_source_variety": "Mamodo Elder Catalogue",
        "m_low_score_brave": "Mamodo Alerts Score",
        "m_short_manga_explorer": "World Journey Compass",
        "m_long_manga_explorer": "Kiyo's Strategy Survey",
        "m_serialization_explorer": "Mamodo Art Road",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Night Study Ledger",
        "m_commute_reader": "Zatch's Heart Tenure Tenure",
        "m_four_am_club": "Kiyo's Run Fellowship",
        "m_new_year_read": "Spell Binge Pact",
        "m_all_hours": "Spell Vault Accord Accord",
        "m_prime_time_reader": "Spell Critic Banner",
        "m_workday_reader": "Zatch Comedy Accord Accord",
        "m_sunday_read": "Night Study Standard Standard",
        "m_morning_routine": "Zatch Comedy Discipline",
        "m_night_shift_reader": "Partner Circle Accord Accord",
        "m_seasonal_premier_read": "Mamodo Elder Seasonal",
        "m_clock_collector": "Zatch Expert Reserve",
        "m_late_night_horror": "Replay Battle Mark Mark",
        "m_afternoon_reader": "Spell Library Mantle Mantle",
        "m_golden_hour_reader": "Kiyo Takamine Observance",
        "m_dawn_reader": "Zaker Speed Mantle",
        "m_twilight_reader": "Battle Marathon Crown",
        "m_midnight_start": "Spell Critic Routine",
        "m_weekend_binge_hours": "Lost Partners Momentum",
        "m_late_night_regular": "Night Study Accord",
        "m_sunrise_reader": "All Night Mantle",
        "m_every_day_of_week": "Mamodo Elder Warrant Warrant",
        "m_monthly_hours": "Perfect Zaker Vigil",
        "m_bedtime_reader": "Mamodo Alerts Warrant Warrant",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Mamodo Art",
        "m_webtoon_reader": "Battle Marathon Mark Mark",
        "m_full_color": "Spell Binge Accord",
        "m_doujin_reader": "Dawn Training Record Record",
        "m_anthology_reader": "Lost Partners Accord",
        "m_adaptation_reader": "Adapted Battle Banner",
        "m_longstrip_reader": "Kiyo Takamine Trial",
        "m_4koma_reader": "Decade Mamodo Ledger",
        "m_oneshot_reader": "Hidden Spell Mantle",
        "m_format_variety": "Kiyo's Run Gallery",
        "m_light_novel_reader": "Spell Vault Insignia",
        "m_novel_reader": "Mamodo Alerts Crown",
        "m_visual_storyteller": "Spell Library Testament",
        "m_colored_classic": "Iron Partner Survey",
        "m_webcomic_fan": "Zatch Classic Insignia",
        "m_manga_to_anime": "Adapted Battle",
        "m_seinen_reader": "Team Spells Pinnacle",
        "m_josei_reader": "All Night Pinnacle",
        "m_award_winning_art": "Mamodo Battle Relic",
        "m_debut_work": "Mamodo Battle Dominion",
        "m_vertical_scroll": "King's Trophies Decree Decree",
        "m_traditional_format": "Raiku Fan Hoard",
        "m_cross_media": "World Journey Accord",
        "m_spinoff_reader": "Loyal Partner Accord",
        "m_remake_reader": "Kiyo's Review Pinnacle",
        "m_collaboration_reader": "Zatch Classic Chronicle",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Lightning Streak",
        "m_weekly_warrior": "Mamodo Art Season",
        "m_monthly_reader": "Battle Won Discipline",
        "m_comeback": "Kiyo's Strategy Standard Standard",
        "m_weekend_streak": "All Night Fever",
        "m_no_zero_days": "Partner Drama Proof Proof",
        "m_iron_will": "Iron Partner",
        "m_habit_formed": "Mamodo Power Crown Crown",
        "m_consistent_pace": "Mamodo World Scrutiny Scrutiny",
        "m_year_long": "Year Reading",
        "m_double_streak": "Hidden Spell Resolve",
        "m_streak_recovery": "Mamodo Registry Resolve",
        "m_daily_minimum": "Zatch Expert Focus",
        "m_winter_streak": "Kiyo Takamine Observance Observance",
        "m_summer_streak": "Mamodo Battle Observance",
        "m_morning_streak": "Perfect Zaker Clock",
        "m_night_streak": "Raiku Fan Discipline",
        "m_unbreakable": "All Night Warrant",
        "m_eternal_flame": "Spell Archive Record",
        "m_chapter_a_day": "Night Study Ledger Ledger",
        "m_genre_streak": "Zaker Speed Streak",
        "m_completion_streak": "Adapted Battle Return",
        "m_rating_streak": "Zaker Speed Appraisal",
        "m_multi_ch_streak": "Mamodo Art Tenure",
        "m_author_streak": "Zatch Expert Calendar",
        "m_perfect_week_manga": "Loyal Partner Accord Accord",
        "m_diverse_streak": "All Spells Streak",

        // ── MANGA SCORING ──
        "m_critic": "Kiyo's Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_harsh_critic": "Spell Vault Scale",
        "m_fair_judge": "Spell Book Eye Eye",
        "m_generous_spirit": "Lost Partners Decree",
        "m_score_all": "Battle Marathon Reckoning",
        "m_wide_range": "Battle Won Ledger Ledger",
        "m_controversial": "Zatch Bell Standard Standard",
        "m_consistent_scorer": "Dawn Training Grade",
        "m_score_sniper": "Winter Battle Reckoning",
        "m_evolving_taste": "Hidden Spell Trial Trial",
        "m_bell_curve": "Battle Won Accord",
        "m_picky_reader": "All Spells Ledger",
        "m_100_rated": "Battle Won Standard",
        "m_500_rated": "Partner Circle Aegis",
        "m_mediocre_majority": "Hidden Spell Canon",
        "m_rating_spree": "Perfect Zaker Verdict",
        "m_score_variance": "Mamodo Alerts Measure",
        "m_binge_rater": "Zatch Expert Passage",
        "m_reread_rerate": "Iron Partner Banner Banner",
        "m_masterpiece_hunter": "Zatch Bell Banner",
        "m_contrarian": "Adapted Battle Aegis",
        "m_optimist": "World Journey Accord Accord",
        "m_score_distributor": "Mamodo Art Balance",
        "m_genre_critic": "Zatch Expert Critic",
        "m_mean_above_8": "Mamodo Alerts Score Score",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "Spell Library Season",
        "m_valentines_read": "Zaker Speed Observance",
        "m_pi_day": "Hidden Spell Testament Testament",
        "m_april_fools": "Winter Battle Devotion",
        "m_international_manga_day": "Spell Vault Aegis",
        "m_free_comic_day": "Lost Partners Chronicle",
        "m_summer_solstice": "Daily Training Focus Focus",
        "m_tanabata": "Mamodo World Tanabata",
        "m_friday_13th": "Kiyo's Review Dominion Dominion",
        "m_halloween_read": "Replay Battle Halloween",
        "m_thanksgiving_binge": "Loyal Partner Charge",
        "m_christmas_read": "Zatch Comedy Pact",
        "m_new_years_eve": "Daily Training Pilgrimage",
        "m_birthday_read": "Team Spells Focus",
        "m_holiday_marathon": "Gold Palette Rally",
        "m_independence_day": "Adapted Battle Aegis Aegis",
        "m_culture_day": "Partner Circle Seal Seal",
        "m_spring_equinox": "Replay Battle Dominion",
        "m_earth_day": "Team Spells Trial",
        "m_labor_day": "Zatch Comedy Seal",
        "m_winter_solstice": "Mamodo Power Focus Focus",
        "m_manga_birthday": "Mamodo World Ritual",
        "m_every_holiday_reader": "Mamodo Registry Watch",
        "m_consecutive_holidays": "Kiyo's Review Watch",

        // ── MANGA SPECIAL ──
        "m_round_number": "Battle Chain Aegis",
        "m_fibonacci": "Zatch's Heart Dominion",
        "m_palindrome_day": "Hidden Spell Relic",
        "m_binary_day": "Mamodo Power Proof",
        "m_full_moon_read": "All Night Crown",
        "m_leap_year_read": "All Spells Practice",
        "m_triple_seven": "Spell Book Trial Trial",
        "m_thousand_complete": "Spell Book Ascension",
        "m_nice": "King's Trophies Seal Seal",
        "m_power_level_chapters": "Kiyo's Strategy Aegis",
        "m_answer_42": "All Night Trial",
        "m_square_number": "Spell Archive Standard",
        "m_prime_count": "Spell Book Pinnacle",
        "m_matching_date": "Mamodo Registry Mantle",
        "m_century_chapter": "Battle Chain Decree",
        "m_pi_chapters": "Team Spells Proof Proof",
        "m_synchronicity": "Zaker Speed Emblem",
        "m_world_record": "Partner Drama Warrant",
        "m_genre_clash": "Spell Critic Clash",
        "m_time_traveler": "Dawn Training Decree",
        "m_double_digits": "Mamodo Elder Dominion",
        "m_one_two_three": "Zatch Classic Banner Banner",
        "m_lucky_seven": "Raiku Fan Record Record",
        "m_exact_hundred_ch": "Zatch's Heart Legend",
        "m_year_match_count": "Decade Mamodo Routine",
        "m_chapter_match_date": "Mamodo Power Pinnacle Pinnacle",

        // ── MANGA FORMATS ──
        "m_manga_format": "Mamodo Elder Index",
        "m_manhwa_format": "Replay Battle Gallery",
        "m_manhua_format": "Kiyo Takamine Storehouse",
        "m_ln_format": "Spell Book Index",
        "m_oneshot_format": "Hidden Spell Index",
        "m_doujin_format": "Perfect Zaker Cabinet",
        "m_novel_format": "Winter Battle Reserve Reserve",
        "m_format_master_manga": "Perfect Zaker Treasury",

        // ── MANGA META ──
        "m_meta_first_unlock": "Dawn Training Link",
        "m_meta_collector": "Partner Circle Reliquary",
        "m_meta_category_starter": "Kiyo's Run Standard",
        "m_meta_tier_climber": "World Journey Token",
        "m_meta_tier_max": "Zatch Complete",
        "m_meta_xp_earner": "Mamodo Elder Anchor",
        "m_meta_difficulty_easy": "Spell Book Panel",
        "m_meta_difficulty_hard": "Spell Library Node",
        "m_meta_unlock_spree": "Mamodo Elder Marker",
        "m_meta_completionist": "Full Library",
        "m_meta_diverse": "Hidden Spell Anchor",
        "m_meta_dominator": "King's Trophies Writ",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060500",
        primary: "#d49200",
        secondary: "#aa7000",
        accent: "#4080f0",
    },
    particleColor: "#f0c020",
    backgroundDim: 0.26,
    backgroundBlur: 14,
    particleTypes: {
        lightning_bolts: { label: "Zaker Lightning", maxCount: 14, defaultEnabled: true, defaultIntensity: 52 },
        golden_sparks: { label: "Spell Sparks", maxCount: 12, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
  1: "Threadbare Generic Rank Spark",
  8: "Generic's Tarnished Omen",
  14: "Fractured Generic Rank",
  21: "Generic Rank Path",
  28: "Lowborn Legacy Myth",
  35: "Generic Rank Pulse",
  41: "Generic's Legacy Crest",
  48: "Humble Generic Mark",
  55: "Ragged Generic Rank Vow",
  61: "Generic's Faint Echo",
  68: "Lesser Generic Rank",
  75: "Generic Rank Zenith",
  81: "Doubtful Legacy Bloom",
  88: "Generic Rank Sigil",
  95: "Generic's Legacy Flame",
  102: "Really Cool Generic Spark",
  108: "Awakened Generic Rank Omen",
  115: "Generic's Resolute Seal",
  122: "Rising Generic Rank",
  128: "Generic Rank Myth",
  135: "Dauntless Legacy Pulse",
  142: "Generic Rank Crest",
  149: "Generic's Legacy Mark",
  155: "Fresh Generic Vow",
  162: "Valiant Generic Rank Echo",
  169: "Generic's Prime Crown",
  175: "Polished Generic Rank",
  182: "Generic Rank Bloom",
  189: "Stormlit Legacy Sigil",
  195: "Generic Rank Flame",
  202: "Generic's Legacy Spark",
  209: "Tempered Generic Omen",
  216: "Trusted Generic Rank Seal",
  222: "Generic's Steadfast Path",
  229: "Ironclad Generic Rank",
  236: "Veteran Legacy Pulse",
  242: "Core Legacy Crest",
  249: "Generic Rank Mark",
  256: "Generic's Legacy Vow",
  262: "Formidable Generic Echo",
  269: "Lucid Generic Rank Crown",
  276: "Generic's Ranked Zenith",
  283: "Fabled Generic Rank",
  289: "Grand Legacy Sigil",
  296: "Seasoned Legacy Flame",
  303: "Generic Rank Spark",
  309: "Generic's Legacy Omen",
  316: "Valorous Generic Seal",
  323: "Stalwart Generic Rank Path",
  330: "Generic's Commanding Myth",
  336: "Refined Generic Rank",
  343: "Unbroken Legacy Crest",
  350: "Blazing Legacy Mark",
  356: "Generic Rank Vow",
  363: "Generic's Legacy Echo",
  370: "Peerless Generic Crown",
  376: "Ardent Generic Rank Zenith",
  383: "Generic's Focused Bloom",
  390: "Vigilant Generic Rank",
  397: "Dominant Legacy Flame",
  403: "Elite Legacy Spark",
  410: "Generic Rank Omen",
  417: "Generic's Legacy Seal",
  423: "Sovereign Generic Path",
  430: "Regal Generic Rank Myth",
  437: "Generic's Crowned Pulse",
  444: "Mythborn Generic Rank",
  450: "Limitless Legacy Mark",
  457: "Radiant Legacy Vow",
  464: "Generic Rank Echo",
  470: "Generic's Legacy Crown",
  477: "Climactic Generic Zenith",
  484: "Epic Generic Rank Bloom",
  490: "Generic's Unreal Sigil",
  497: "Peak Generic Rank",
  504: "Supreme Legacy Spark",
  511: "Exalted Legacy Omen",
  517: "Generic Rank Seal",
  524: "Generic's Legacy Path",
  531: "Celestial Generic Myth",
  537: "Phantom Generic Rank Pulse",
  544: "Generic's Crimson Crest",
  551: "Silver Generic Rank",
  557: "Golden Legacy Vow",
  564: "Feral Legacy Echo",
  571: "Generic Rank Crown",
  578: "Generic's Legacy Zenith",
  584: "Dread Generic Bloom",
  591: "Luminous Generic Rank Sigil",
  598: "Generic's Thunderous Flame",
  604: "Ultraviolet Generic Rank",
  611: "Unleashed Legacy Omen",
  618: "Secret Legacy Seal",
  625: "Final Generic Path",
  631: "Generic's Legacy Myth",
  638: "Worldclass Generic Pulse",
  645: "Lawless Generic Rank Crest",
  651: "Generic's Chosen Mark",
  658: "Fearless Generic Rank",
  665: "Overdrive Legacy Echo",
  671: "Cinematic Legacy Crown",
  678: "Impossible Generic Zenith",
  685: "Generic's Legacy Bloom",
  692: "Canonized Generic Sigil",
  698: "Ascendant Generic Rank Flame",
  705: "Generic's Transfigured Spark",
  712: "Immortal Generic Rank",
  718: "Eclipsed Legacy Seal",
  725: "Astral Legacy Path",
  732: "Sublime Generic Myth",
  739: "Generic's Legacy Pulse",
  745: "Prismatic Generic Crest",
  752: "Abyssal Generic Rank Mark",
  759: "Generic's Unbound Vow",
  765: "Eternal Generic Rank",
  772: "Cosmic Legacy Crown",
  779: "Transcendent Legacy Zenith",
  785: "Perfected Generic Bloom",
  792: "Generic's Legacy Sigil",
  799: "Ultimate Generic Flame",
  806: "Mythic Generic Rank Spark",
  812: "Generic's Godlike Omen",
  819: "Canonical Generic Rank",
  826: "Reality-Bent Legacy Path",
  832: "Heavenly Legacy Myth",
  839: "Absolute Generic Pulse",
  846: "Untouchable Generic Crest",
  852: "Timeless Generic Mark",
  859: "Empyrean Generic Rank Vow",
  866: "Generic's Primordial Echo",
  873: "Omniscient Generic Rank",
  879: "Unfathomed Legacy Zenith",
  886: "Apocalyptic Legacy Bloom",
  893: "Seraphic Generic Sigil",
  899: "Omega Generic Flame",
  906: "Final Generic Spark",
  913: "Crowned Generic Rank Omen",
  920: "Generic's Mythic Seal",
  926: "Absolute Generic Rank",
  933: "Eternal Legacy Myth",
  940: "Cosmic Legacy Pulse",
  946: "Transcendent Generic Crest",
  953: "Perfected Generic Mark",
  960: "Definitive Generic Vow",
  966: "Ultimate Generic Rank Echo",
  973: "Generic's Infinite Crown",
  980: "Sovereign Generic Rank",
  987: "Celestial Legacy Bloom",
  993: "Legendary Legacy Sigil",
  1000: "Ultimate Generic Rank"
},
}
