import { AnimeThemeConfig } from "./types"
import { GiCrossedSwords, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiCrystalBall, GiStarSwirl, GiRoad } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const bananaFishTheme: AnimeThemeConfig = {
    id: "banana-fish",
    displayName: "Banana Fish",
    description: "Ash Lynx is a beautiful, deadly street gang leader in New York caught up in a conspiracy around a mysterious drug called Banana Fish. His meeting with Japanese photographer Eiji changes everything.",
    cssVars: {
        "--color-brand-200": "220 200 170",
        "--color-brand-300": "195 162 112",
        "--color-brand-400": "165 120 62",
        "--color-brand-500": "132 82 25",
        "--color-brand-600": "98 52 8",
        "--color-brand-700": "68 28 2",
        "--color-brand-800": "42 12 0",
        "--color-brand-900": "20 4 0",
        "--color-brand-950": "8 1 0",
        "--brand": "132 82 25",
        "--background": "#050200",
        "--paper": "#0c0400",
        "--color-gray-950": "5 2 0",
        "--color-gray-900": "14 6 1",
        "--color-gray-800": "28 14 3",
        "--color-gray-700": "48 25 6",
        "--color-gray-600": "75 42 12",
        "--color-gray-500": "115 72 25",
        "--color-gray-400": "158 112 52",
        "--color-gray-300": "200 158 90",
        "--color-gray-200": "232 198 138",
        "--color-gray-100": "250 228 188",
        "--color-gray-50": "255 245 232",
    },
    sidebarOverrides: {
        "home": { icon: GiRoad, label: "New York Streets" },
        "schedule": { icon: GiAlarmClock, label: "Street Schedule" },
        "manga": { icon: LuBookOpen, label: "Case Files" },
        "lists": { icon: GiScrollUnfurled, label: "Crew List" },
        "discover": { icon: GiBullseye, label: "New Leads" },
        "torrent-list": { icon: GiCrossedSwords, label: "Weapon Cache" },
        "debrid": { icon: GiHeartKey, label: "Street Vault" },
        "unmatched": { icon: GiCrystalBall, label: "Unsolved Cases" },
        "enmasse": { icon: GiResize, label: "Gang War" },
        "scan-summaries": { icon: TbReportSearch, label: "Case Reports" },
        "auto-downloader": { icon: LuRss, label: "Street Feed" },
        "community": { icon: GiStarSwirl, label: "Banana Fish Circle" },
        "achievements": { icon: GiTrophyCup, label: "Street Trophies" },
        "milestones": { icon: LuFlag, label: "Survival Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Danger Alerts" },
        "theme-manager": { icon: GiPalette, label: "Noir Colors" },
        "extensions": { icon: BiExtension, label: "Street Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Street Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Ash Config" },
    },
    achievementNames: {
        "a_first_episode": "New York Streets",
        "a_first_complete": "First Lead",
        "a_hundred_club": "Hundred Street Days",
        "a_binge_king": "Banana Fish Marathon",
        "a_completionist": "Conspiracy Uncovered",
        "a_mega_completionist": "Banana Fish Complete",
        "a_loyal_fan": "Street Fan",
        "a_zero_to_hero": "Victim to Leader",
        "m_first_chapter": "First Page",
        "m_completionist": "Full Manga Archive",
    },
    musicUrl: "",
    previewColors: {
        bg: "#050200",
        primary: "#845219",
        secondary: "#506080",
        accent: "#e8d0a0",
    },
    particleColor: "#a07030",
    backgroundDim: 0.38,
    backgroundBlur: 22,
    milestoneNames: {
        1: "Street Survivor",
        5: "Gang Leader",
        15: "Conspiracy Aware",
        30: "Eiji's Protector",
        50: "Truth Seeker",
        75: "Final Confrontation",
        100: "Ash Lynx's Legacy",
    },
}
