import { AnimeThemeConfig } from "./types"
import { GiMagnifyingGlass, GiScrollUnfurled, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiSpellBook, GiCrystalBall, GiHeartKey, GiAnvilImpact } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const detectiveConanTheme: AnimeThemeConfig = {
    id: "detective-conan",
    displayName: "Detective Conan",
    description: "Shinichi Kudo, shrunken into a child, hunts the Black Organization as Conan Edogawa. Every mystery solved brings him closer to restoring his true identity.",
    cssVars: {
        "--color-brand-200": "185 205 240",
        "--color-brand-300": "130 165 220",
        "--color-brand-400": "78 120 195",
        "--color-brand-500": "40 85 165",
        "--color-brand-600": "22 62 130",
        "--color-brand-700": "12 42 95",
        "--color-brand-800": "5 24 62",
        "--color-brand-900": "2 12 38",
        "--color-brand-950": "0 4 18",
        "--brand": "40 85 165",
        "--background": "#00020e",
        "--paper": "#020414",
        "--color-gray-950": "0 2 14",
        "--color-gray-900": "3 6 25",
        "--color-gray-800": "8 14 44",
        "--color-gray-700": "16 26 68",
        "--color-gray-600": "28 48 100",
        "--color-gray-500": "48 78 138",
        "--color-gray-400": "85 118 175",
        "--color-gray-300": "125 158 210",
        "--color-gray-200": "170 195 232",
        "--color-gray-100": "210 225 248",
        "--color-gray-50": "238 244 254",
    },
    sidebarOverrides: {
        "home": { icon: GiMagnifyingGlass, label: "Detective Agency" },
        "schedule": { icon: GiAlarmClock, label: "Case Schedule" },
        "manga": { icon: LuBookOpen, label: "Case Files" },
        "lists": { icon: GiScrollUnfurled, label: "Suspect List" },
        "discover": { icon: GiBullseye, label: "New Leads" },
        "torrent-list": { icon: GiAnvilImpact, label: "Evidence Lock-Up" },
        "debrid": { icon: GiCrystalBall, label: "Hidden Clues" },
        "unmatched": { icon: GiHeartKey, label: "Cold Cases" },
        "enmasse": { icon: GiResize, label: "Mass Case" },
        "scan-summaries": { icon: TbReportSearch, label: "Case Reports" },
        "auto-downloader": { icon: LuRss, label: "New Case Alert" },
        "community": { icon: GiSpellBook, label: "Detective Circle" },
        "achievements": { icon: GiTrophyCup, label: "Case Trophies" },
        "milestones": { icon: LuFlag, label: "Investigation Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Case Alerts" },
        "theme-manager": { icon: GiPalette, label: "Detective Palette" },
        "extensions": { icon: BiExtension, label: "Gadget Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Police Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Wristwatch Config" },
    },
    achievementNames: {
        "a_first_episode": "First Case Solved",
        "a_first_complete": "Mystery Cracked",
        "a_hundred_club": "Hundred Cases",
        "a_time_lord": "Black Org. Veteran",
        "a_binge_king": "Case Marathon",
        "a_completionist": "All Cases Solved",
        "a_mega_completionist": "Conan Master",
        "a_loyal_fan": "Loyal Sleuth",
        "a_night_owl": "Late Night Case",
        "m_first_chapter": "First Clue",
        "m_completionist": "Full Case Archive",
    },
    musicUrl: "",
    previewColors: {
        bg: "#00020e",
        primary: "#2855a5",
        secondary: "#8c0000",
        accent: "#c8a000",
    },
    particleColor: "#4878c3",
    backgroundDim: 0.30,
    backgroundBlur: 18,
    milestoneNames: {
        1:   "Junior Detective",
        8:   "Detective Boys Member",
        14:  "Amateur Detective",
        21:  "High School Detective",
        28:  "Conan Edogawa",
        35:  "Detective of the East",
        41:  "Sleeping Kogoro-Level",
        48:  "Famous Detective",
        55:  "Detective of the West — Heiji",
        61:  "Known Detective — National",
        68:  "International Detective",
        75:  "FBI Operative",
        81:  "CIA Operative",
        88:  "MI6 Operative",
        95:  "PSB Agent",
        102: "NPA Detective",
        108: "Metropolitan Police",
        115: "Interpol Agent",
        122: "Organization — Detected",
        128: "Black Organization — Known",
        135: "Men in Black",
        142: "Organization Member — Met",
        149: "Gin — Encountered",
        155: "Vodka — Encountered",
        162: "Vermouth — Encountered",
        169: "Rum — Encountered",
        175: "Bourbon — Revealed",
        182: "Kir — Double Agent",
        189: "Haibara Ai — APTX 4869",
        195: "APTX 4869 — Shrunken",
        202: "APTX 4869 — Antidote",
        209: "Shinichi — Temporarily Restored",
        216: "Organization Spy — Uncovered",
        222: "Organization Mole — Revealed",
        229: "Zero — Rei Furuya",
        236: "Akai Shuichi — FBI",
        242: "Akai — Covert Op",
        249: "Mary Sera — Shrunk",
        256: "Masumi Sera — Sister",
        262: "Rum — Identity",
        269: "Rum — Revealed",
        276: "Boss — APTX 4869",
        283: "Anokata — Searched",
        289: "Anokata — Identity",
        296: "Karasuma Renya",
        303: "Boss — Confronted",
        309: "Organization — Exposed",
        316: "Organization — Arrested",
        323: "Organization — Dismantled",
        330: "Ran Mouri — Protected",
        336: "Ran — Not Told",
        343: "Ran — Suspects",
        350: "Ran — Knows?",
        356: "Ran — Told",
        363: "Shinichi — Revealed",
        370: "Kaito Kid — Rival",
        376: "Kaito Kid — Ally",
        383: "Kaito Kid — Secret Kept",
        390: "Kaito — Pandora Gem",
        397: "Hakuba Saguru",
        403: "Saguru — Abroad",
        410: "Deduction Show",
        417: "Locked Room — Solved",
        423: "Impossible Crime — Solved",
        430: "Cold Case — Reopened",
        437: "Cold Case — Solved",
        444: "Serial Killer — Caught",
        450: "Art Thief — Foiled",
        457: "Jewel Thief — Caught",
        464: "Spy — Uncovered",
        470: "Assassin — Stopped",
        477: "Poisoning Case — Solved",
        484: "Kidnapping — Resolved",
        490: "Hostage — Rescued",
        497: "Bomb — Defused",
        504: "Explosive — Found",
        511: "Train Crime — Solved",
        517: "Ship Crime — Solved",
        524: "Airplane Crime — Solved",
        531: "Island Crime — Solved",
        537: "Haunted House — Explained",
        544: "Onsen Crime — Solved",
        551: "School Festival Crime",
        557: "Sports Festival Crime",
        564: "Museum Crime — Solved",
        571: "Theater Crime — Solved",
        578: "Hospital Crime — Solved",
        584: "All Cases — Filed",
        591: "Detective — Never Wrong",
        598: "One Truth — Prevails",
        604: "Detective God",
        611: "One Truth — Always",
        618: "Never-Wrong Detective",
        625: "Conan — Shinichi Restored",
        631: "Shinichi — Home",
        638: "Ran — Reunited",
        645: "Organization — Gone",
        651: "APTX 4869 — Cured",
        658: "Shinichi Kudo — Real",
        665: "High School Detective — Final",
        671: "One Truth — Final",
        678: "Sleeping Kogoro — Replaced",
        685: "Detective of Japan",
        692: "World's Greatest Detective",
        698: "Kaito Kid — Ended",
        705: "Pandora Gem — Destroyed",
        712: "Magic Kaito — Complete",
        718: "Heiji — Partner",
        725: "FBI — Allied",
        732: "CIA — Allied",
        739: "Interpol — Allied",
        745: "All Agencies — Allied",
        752: "Organization Final Case",
        759: "Black Organization — Case Closed",
        765: "One Truth Prevails — Final",
        772: "Detektiv Conan Legend",
        779: "Shinichi's Return — Permanent",
        785: "Ran's Happiness",
        792: "Haibara's Cure",
        799: "Detective Boys — Grown",
        806: "Mouri Kogoro — Retired",
        812: "Conan — Real Identity Known",
        819: "Shinichi Kudo — Active",
        826: "Kudo — Legend",
        832: "Conan — Legend",
        839: "Detective — Legend",
        846: "Japan's Finest Detective",
        852: "World's Finest Detective",
        859: "Case Closed — 1000 Cases",
        866: "Truth — Always One",
        873: "Lie — Never Accepted",
        879: "Justice — Always Prevails",
        886: "Deduction God",
        893: "Truth God",
        899: "Justice God",
        906: "Detective Eternal",
        913: "One Truth — Eternal",
        920: "Shinichi Kudo — Eternal",
        926: "Conan Edogawa — Legend",
        933: "Case Closed — Complete",
        940: "Detective Boys — Heroes",
        946: "Ran — Always Waited",
        953: "Haibara — Peace",
        960: "Organization — Memory",
        966: "Gin — Arrested",
        973: "Vodka — Arrested",
        980: "Vermouth — Revealed",
        987: "Boss — Defeated",
        993: "One Truth Prevails",
        1000: "Shinichi Kudo",
    },
}
