import { AnimeThemeConfig } from "./types"
import { GiCookingPot, GiMeatCleaver, GiDungeonGate, GiSwordClash, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiMushroom, GiHeartKey, GiFireBowl } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const dungeonMeshiTheme: AnimeThemeConfig = {
    id: "dungeon-meshi",
    displayName: "Dungeon Meshi",
    description: "After his sister is devoured by a dragon deep in a dungeon, the adventurer Laios sets out to rescue her — with the ingenious plan to cook and eat the monsters they encounter along the way.",
    fontFamily: "'Noto Sans JP', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "248 222 148",
        "--color-brand-300": "238 195 88",
        "--color-brand-400": "218 162 30",
        "--color-brand-500": "188 130 0",
        "--color-brand-600": "150 100 0",
        "--color-brand-700": "110 70 0",
        "--color-brand-800": "72 44 0",
        "--color-brand-900": "40 22 0",
        "--color-brand-950": "18 8 0",
        "--brand": "188 130 0",
        "--background": "#050300",
        "--paper": "#120800",
        "--color-gray-950": "5 3 0",
        "--color-gray-900": "12 7 0",
        "--color-gray-800": "24 14 2",
        "--color-gray-700": "40 24 6",
        "--color-gray-600": "65 40 12",
        "--color-gray-500": "102 68 26",
        "--color-gray-400": "148 108 55",
        "--color-gray-300": "190 148 90",
        "--color-gray-200": "220 185 132",
        "--color-gray-100": "240 215 172",
        "--color-gray-50": "252 240 215",
    },
    sidebarOverrides: {
        "home": { icon: GiCookingPot, label: "Mess Hall" },
        "schedule": { icon: GiAlarmClock, label: "Dungeon Run" },
        "manga": { icon: LuBookOpen, label: "Recipes" },
        "lists": { icon: GiFlowerEmblem, label: "Monster Bestiary" },
        "discover": { icon: GiBullseye, label: "New Floors" },
        "torrent-list": { icon: GiMeatCleaver, label: "Supply Cache" },
        "debrid": { icon: GiDungeonGate, label: "Dungeon Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Party" },
        "enmasse": { icon: GiResize, label: "Dungeon Crew" },
        "scan-summaries": { icon: TbReportSearch, label: "Expedition Logs" },
        "auto-downloader": { icon: LuRss, label: "Monster Feed" },
        "community": { icon: GiMushroom, label: "Adventurer Guild" },
        "achievements": { icon: GiTrophy, label: "Dungeon Trophies" },
        "milestones": { icon: LuFlag, label: "Floor Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Guild Alerts" },
        "theme-manager": { icon: GiPalette, label: "Gold Palette" },
        "extensions": { icon: BiExtension, label: "Dungeon Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Party Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Laios's Config" },
    },
    achievementNames: {
        "a_first_episode": "First Bite",
        "a_first_complete": "Floor Cleared",
        "a_hundred_club": "Hundred Recipes",
        "a_time_lord": "Dungeon Elder",
        "a_anime_collector": "Recipe Archive",
        "a_library_legend": "Monster Library",
        "a_binge_king": "Feast Marathon",
        "a_no_sleep": "All-Night Cook",
        "a_marathon_runner": "Laios's Run",
        "a_speed_run": "Quick Cook",
        "a_completionist": "Full Feast",
        "a_mega_completionist": "Master Cook",
        "a_loyal_fan": "Loyal Companion",
        "a_rewatcher": "Second Serving",
        "a_decade_watcher": "Decade Cook",
        "a_genre_action": "Dungeon Fight",
        "a_genre_adventure": "Dungeon Dive",
        "a_genre_comedy": "Cooking Comedy",
        "a_genre_drama": "Dungeon Drama",
        "a_genre_fantasy": "Fantasy Dungeon",
        "a_genre_horror": "Cursed Floor",
        "a_genre_romance": "None Here",
        "a_genre_scifi": "None Here",
        "a_genre_supernatural": "Ancient Magic",
        "a_genre_psychological": "Dungeon Mind",
        "a_genre_mecha": "None Here",
        "a_critic": "Food Critic",
        "a_perfect_ten": "Perfect Dish",
        "a_harsh_critic": "Senshi Standard",
        "a_daily_streak": "Daily Cook",
        "a_mega_streak": "Endless Feast",
        "a_year_long": "Year of Feasts",
        "a_iron_will": "Dungeon Will",
        "a_hidden_gem": "Hidden Recipe",
        "a_cult_classic": "Dungeon Classic",
        "a_classic_connoisseur": "2024 Fan",
        "a_new_years_resolution": "New Year Feast",
        "a_christmas_special": "Winter Meal",
        "a_meta_tier_max": "True Delver",
        "a_meta_completionist": "All Floors",
        "a_sequel_chain": "Laios's Chain",
        "a_zero_to_hero": "Raw Ingredient",
        "a_night_owl": "Night Cook",
        "a_early_bird": "Dawn Prep",
        "m_first_chapter": "First Course",
        "m_first_complete": "Meal Complete",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Recipe Binge",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Meshi Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Re-serve",
        "m_genre_action": "Action Chapter",
        "m_genre_adventure": "Dungeon Chapter",
        "m_genre_romance": "None Here",
        "m_genre_fantasy": "Fantasy Chapter",
        "m_genre_horror": "Cursed Chapter",
        "m_genre_drama": "Drama Chapter",
        "m_genre_scifi": "None Here",
        "m_genre_supernatural": "Magic Chapter",
        "m_genre_psychological": "Deep Chapter",
        "m_critic": "Senshi's Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Dungeon Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Iron Chef",
        "m_hidden_gem": "Hidden Recipe",
        "m_cult_classic": "Dungeon Classic",
        "m_mangaka_lover": "Ryoko Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Meshi Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Dungeon Art",
        "m_manga_to_anime": "Adapted Feast",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#050300",
        primary: "#bc8200",
        secondary: "#966400",
        accent: "#50c890",
    },
    particleColor: "#d8a830",
    backgroundDim: 0.28,
    backgroundBlur: 14,
    particleTypes: {
        golden_sparks: { label: "Cooking Sparks", maxCount: 16, defaultEnabled: true, defaultIntensity: 50 },
        ember_wisps: { label: "Embers", maxCount: 12, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
        1:   "D-Rank Adventurer",
        8:   "C-Rank Adventurer",
        14:  "B-Rank Adventurer",
        21:  "A-Rank Adventurer",
        28:  "S-Rank Adventurer",
        35:  "Living Legend",
        41:  "Surface Dweller",
        48:  "Dungeon Diver",
        55:  "Novice Cook",
        61:  "Apprentice Cook",
        68:  "Journeyman Cook",
        75:  "Expert Cook",
        81:  "Monster Cuisine Master",
        88:  "Senshi's Pupil",
        95:  "Mid-Dungeon Survivor",
        102: "Deep Dungeon Survivor",
        108: "Golden City Survivor",
        115: "Canari Island Elder",
        122: "Slime — Cooked",
        128: "Giant Frog — Eaten",
        135: "Walking Mushroom — Eaten",
        142: "Scorpion Tail Fried",
        149: "Mandrake — Harvested",
        155: "Basilisk — Consumed",
        162: "Golem Stew",
        169: "Dragon Sashimi",
        175: "Undine Sashimi",
        182: "Kelpie Jerky",
        189: "Griffin — Cooked",
        195: "Red Dragon — Cooked",
        202: "Laios Party Member",
        209: "Falin's Brother — Searching",
        216: "Falin — Found",
        222: "Falin — Eaten By Dragon",
        229: "Falin — Resurrected",
        236: "Falin — Chimera",
        242: "Falin — Saved",
        249: "Chilchuck — Party Thief",
        256: "Marcille — Party Mage",
        262: "Senshi — Party Warrior",
        269: "Namari — Former Member",
        276: "Izutsumi — New Member",
        283: "Kabru — Rival",
        289: "Dungeon Master — Met",
        296: "Dungeon Master — Challenged",
        303: "Dungeon Master — Overthrown",
        309: "Winged Lion — Spoken To",
        316: "Winged Lion — Bound",
        323: "Winged Lion — Freed",
        330: "Canary — Mage Guild",
        336: "Mage Guild — Opposed",
        343: "Mage Guild — Defeated",
        350: "Thistle — Confronted",
        356: "Thistle — Defeated",
        363: "Island — Eaten",
        370: "Island — Eaten By Winged Lion",
        376: "Laios — Dungeon Master",
        383: "Laios — King",
        390: "Laios — Monster",
        397: "Laios — Accepted",
        403: "Cooking in Danger",
        410: "Eating Monsters — Art",
        417: "Food Source — Dungeon",
        423: "Ecosystem — Understood",
        430: "Dungeon Ecology",
        437: "Monster Biology — Studied",
        444: "Senshi's Dwarf Cooking",
        450: "Ancient Elf Cooking",
        457: "Halfling Cooking",
        464: "Human Cooking",
        470: "Tallman Cooking",
        477: "Lion Cooking",
        484: "All Races — Fed",
        490: "Dungeon Feast — Master",
        497: "Foraging — Expert",
        504: "Monster Harvesting — Expert",
        511: "Ingredient Knowledge — Full",
        517: "Magical Cooking — Active",
        524: "Enchanted Meal — Made",
        531: "Healing Meal — Made",
        537: "Reviving Meal — Made",
        544: "Dungeon Kitchen",
        551: "Dungeon Restaurant",
        557: "Monster Cuisine Menu",
        564: "Legendary Meal — Made",
        571: "Meal to Die For",
        578: "Meal Worth Living For",
        584: "Dungeon Food Chain",
        591: "Magical Food Chain",
        598: "Monster-Based Ecosystem",
        604: "Slime Ecology",
        611: "Dragon Ecology",
        618: "Dungeon Master's Kitchen",
        625: "Winged Lion's Meal",
        631: "Red Dragon — Defeated",
        638: "Red Dragon — Devoured",
        645: "Dragon — Cooked",
        651: "Dragon — Tasted",
        658: "Dragon Meal — Legendary",
        665: "Undead — Cooked",
        671: "Undead Feast",
        678: "Skeleton Stew",
        685: "Zombie Cuisine",
        692: "Living Armor — Ingredients",
        698: "Mimics — Harvested",
        705: "All Dungeon Monsters — Tasted",
        712: "Full Monster Menu",
        718: "Dungeon Cuisine Legend",
        725: "Senshi's Appreciation",
        732: "Falin's Recovery Meal",
        739: "Laios's Dream Meal",
        745: "Chilchuck's Comfort Food",
        752: "Marcille's Dessert",
        759: "Full Party — Fed",
        765: "All Dungeons — Explored",
        772: "All Floors — Cleared",
        779: "Golden City — Reached",
        785: "Dungeon Heart — Understood",
        792: "Monster Love — Understood",
        799: "Eating — Sacred",
        806: "Food — Sacred",
        812: "Hunger — Defeated",
        819: "Dungeon — Sustained By",
        826: "Master of the Dungeon",
        832: "King of the Dungeon",
        839: "Cook of the Dungeon",
        846:  "God of Dungeon Cuisine",
        852: "Monster Chef God",
        859: "Foraging God",
        866: "Dungeon God",
        873: "Laios — Monster King",
        879: "Falin — Free",
        886: "Senshi's Legacy — Honored",
        893: "Dungeon Cuisine — Eternal",
        899: "All Races — Fed Equally",
        906: "Monster Ecosystem — Balanced",
        913: "Delicious Dungeon — Complete",
        920: "Eating — Beyond Fear",
        926: "Monsters — Beyond Fear",
        933: "Dungeon — Beyond Fear",
        940: "Food — Life Source",
        946: "Dungeon — Life Source",
        953: "Monster — Life Source",
        960: "All Dungeons — Tasted",
        966: "Monster Cuisine — Eternal",
        973: "Dungeon Meshi God",
        980: "Food God",
        987: "Hunger God",
        993: "Ryoko Kui — Honored",
        1000: "Master of Monster Cuisine",
    },
}
