import { AnimeThemeConfig } from "./types"
import { GiCrossedSwords, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiCrystalBall, GiStarSwirl, GiHelmet } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const grimgarTheme: AnimeThemeConfig = {
    id: "grimgar",
    displayName: "Grimgar of Fantasy and Ash",
    description: "A group of strangers wake in the fantasy world of Grimgar with no memories. With no special powers or easy answers, they form a weak party and struggle to survive, learning the true cost of taking a life.",
    cssVars: {
        "--color-brand-200": "195 215 240",
        "--color-brand-300": "142 175 222",
        "--color-brand-400": "88 132 200",
        "--color-brand-500": "48 92 172",
        "--color-brand-600": "20 60 135",
        "--color-brand-700": "6 35 98",
        "--color-brand-800": "2 16 62",
        "--color-brand-900": "0 6 32",
        "--color-brand-950": "0 2 14",
        "--brand": "48 92 172",
        "--background": "#000206",
        "--paper": "#000410",
        "--color-gray-950": "0 2 6",
        "--color-gray-900": "2 6 16",
        "--color-gray-800": "4 12 32",
        "--color-gray-700": "8 22 52",
        "--color-gray-600": "14 38 82",
        "--color-gray-500": "24 62 118",
        "--color-gray-400": "45 98 155",
        "--color-gray-300": "78 140 192",
        "--color-gray-200": "120 178 222",
        "--color-gray-100": "172 212 242",
        "--color-gray-50": "220 238 255",
    },
    sidebarOverrides: {
        "home": { icon: GiHelmet, label: "Grimgar" },
        "schedule": { icon: GiAlarmClock, label: "Hunt Schedule" },
        "manga": { icon: LuBookOpen, label: "Party Log" },
        "lists": { icon: GiScrollUnfurled, label: "Party Roster" },
        "discover": { icon: GiBullseye, label: "New Quests" },
        "torrent-list": { icon: GiCrossedSwords, label: "Equipment Cache" },
        "debrid": { icon: GiHeartKey, label: "Party Vault" },
        "unmatched": { icon: GiCrystalBall, label: "Lost Files" },
        "enmasse": { icon: GiResize, label: "Raid Night" },
        "scan-summaries": { icon: TbReportSearch, label: "Hunt Reports" },
        "auto-downloader": { icon: LuRss, label: "Quest Feed" },
        "community": { icon: GiStarSwirl, label: "Grimgar Circle" },
        "achievements": { icon: GiTrophyCup, label: "Survival Trophies" },
        "milestones": { icon: LuFlag, label: "Survival Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Danger Alerts" },
        "theme-manager": { icon: GiPalette, label: "Ash Colors" },
        "extensions": { icon: BiExtension, label: "Party Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Party Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Party Config" },
    },
    achievementNames: {
        "a_first_episode": "Woke in Grimgar",
        "a_first_complete": "First Kill",
        "a_hundred_club": "Hundred Hunt Days",
        "a_binge_king": "Grimgar Marathon",
        "a_completionist": "Party Veteran",
        "a_mega_completionist": "Grimgar Survivor",
        "a_loyal_fan": "Grimgar Devotee",
        "a_zero_to_hero": "Weakling to Warrior",
        "m_first_chapter": "First Hunt",
        "m_completionist": "Full Grimgar Archive",
    },
    musicUrl: "",
    previewColors: {
        bg: "#000206",
        primary: "#305cac",
        secondary: "#885858",
        accent: "#c8d8f0",
    },
    particleColor: "#5080c8",
    backgroundDim: 0.38,
    backgroundBlur: 25,
    milestoneNames: {
        1: "Arrived in Grimgar",
        5: "First Goblin Down",
        15: "Party Formed",
        30: "Battle-Hardened",
        50: "Veteran Hunter",
        75: "Facing the Unknown",
        100: "Grimgar's Champion",
    },
}
