import { AnimeThemeConfig } from "./types"
import { GiFlowerEmblem, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiCrystalBall, GiStarSwirl, GiSpellBook } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const kamisamaKissTheme: AnimeThemeConfig = {
    id: "kamisama-kiss",
    displayName: "Kamisama Kiss",
    description: "Homeless high-schooler Nanami is accidentally made a land god by a stranger. She inherits his shrine and his reluctant fox familiar Tomoe — who is proud, powerful, and slowly, unavoidably falling for her.",
    cssVars: {
        "--color-brand-200": "255 218 175",
        "--color-brand-300": "252 178 108",
        "--color-brand-400": "240 132 45",
        "--color-brand-500": "212 88 8",
        "--color-brand-600": "168 52 0",
        "--color-brand-700": "120 26 0",
        "--color-brand-800": "76 10 0",
        "--color-brand-900": "38 3 0",
        "--color-brand-950": "16 1 0",
        "--brand": "212 88 8",
        "--background": "#060200",
        "--paper": "#0f0400",
        "--color-gray-950": "6 2 0",
        "--color-gray-900": "16 6 1",
        "--color-gray-800": "30 14 2",
        "--color-gray-700": "52 26 5",
        "--color-gray-600": "82 45 12",
        "--color-gray-500": "125 78 25",
        "--color-gray-400": "168 122 55",
        "--color-gray-300": "208 168 92",
        "--color-gray-200": "238 205 142",
        "--color-gray-100": "252 232 192",
        "--color-gray-50": "255 246 230",
    },
    sidebarOverrides: {
        "home": { icon: GiFlowerEmblem, label: "Mikage Shrine" },
        "schedule": { icon: GiAlarmClock, label: "Divine Schedule" },
        "manga": { icon: LuBookOpen, label: "Shrine Scrolls" },
        "lists": { icon: GiScrollUnfurled, label: "Familiar Registry" },
        "discover": { icon: GiBullseye, label: "New Yokai" },
        "torrent-list": { icon: GiCrystalBall, label: "Spirit Cache" },
        "debrid": { icon: GiHeartKey, label: "Divine Vault" },
        "unmatched": { icon: GiStarSwirl, label: "Lost Spirits" },
        "enmasse": { icon: GiResize, label: "Divine Gathering" },
        "scan-summaries": { icon: TbReportSearch, label: "Shrine Reports" },
        "auto-downloader": { icon: LuRss, label: "Spirit Feed" },
        "community": { icon: GiSpellBook, label: "Shrine Circle" },
        "achievements": { icon: GiTrophyCup, label: "Divine Trophies" },
        "milestones": { icon: LuFlag, label: "Divine Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Shrine Alerts" },
        "theme-manager": { icon: GiPalette, label: "Shrine Colors" },
        "extensions": { icon: BiExtension, label: "Fox Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Divine Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Nanami Config" },
    },
    achievementNames: {
        "a_first_episode": "Became a God",
        "a_first_complete": "First Miracle",
        "a_hundred_club": "Hundred Divine Days",
        "a_binge_king": "Kamisama Marathon",
        "a_completionist": "All Shrines Visited",
        "a_mega_completionist": "True God",
        "a_loyal_fan": "Shrine Devotee",
        "a_zero_to_hero": "Homeless to Divine",
        "m_first_chapter": "First Prayer",
        "m_completionist": "Full Shrine Archive",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060200",
        primary: "#d45808",
        secondary: "#5858a0",
        accent: "#f8d888",
    },
    particleColor: "#e08030",
    backgroundDim: 0.28,
    backgroundBlur: 20,
    milestoneNames: {
        1: "Accidental God",
        5: "Shrine Opened",
        15: "Tomoe Reluctant",
        30: "Divine Power",
        50: "Yokai Ambassador",
        75: "Fox Familiar's Trust",
        100: "True Land God",
    },
}
