import { AnimeThemeConfig } from "./types"
import { GiPokecog, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiSpellBook, GiScrollUnfurled, GiCrystalBall, GiRunningShoe, GiFireworkRocket } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const pokemonTheme: AnimeThemeConfig = {
    id: "pokemon",
    displayName: "PokÃ©mon",
    description: "Gotta catch 'em all! Ash and Pikachu travel across Kanto and beyond, battling Gym Leaders, foiling Team Rocket, and forging bonds with incredible creatures.",
    fontFamily: "'Fredoka One', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap",
    cssVars: {
        "--color-brand-200": "255 218 100",
        "--color-brand-300": "255 195 50",
        "--color-brand-400": "248 168 0",
        "--color-brand-500": "220 138 0",
        "--color-brand-600": "175 102 0",
        "--color-brand-700": "128 65 0",
        "--color-brand-800": "82 36 0",
        "--color-brand-900": "44 16 0",
        "--color-brand-950": "20 6 0",
        "--brand": "220 138 0",
        "--background": "#080400",
        "--paper": "#130800",
        "--color-gray-950": "8 4 0",
        "--color-gray-900": "18 9 0",
        "--color-gray-800": "36 18 2",
        "--color-gray-700": "58 32 5",
        "--color-gray-600": "88 55 15",
        "--color-gray-500": "130 88 32",
        "--color-gray-400": "175 130 60",
        "--color-gray-300": "215 175 100",
        "--color-gray-200": "240 210 145",
        "--color-gray-100": "252 235 192",
        "--color-gray-50": "255 248 228",
    },
    sidebarOverrides: {
        "home": { icon: GiRunningShoe, label: "Pallet Town" },
        "schedule": { icon: GiAlarmClock, label: "Gym Schedule" },
        "manga": { icon: LuBookOpen, label: "PokÃ©dex" },
        "lists": { icon: GiScrollUnfurled, label: "PokÃ©mon Roster" },
        "discover": { icon: GiBullseye, label: "Discover Routes" },
        "torrent-list": { icon: GiFireworkRocket, label: "Item Cache" },
        "debrid": { icon: GiCrystalBall, label: "Safari Vault" },
        "unmatched": { icon: GiSpellBook, label: "Unknown PokÃ©mon" },
        "enmasse": { icon: GiResize, label: "Mass Release" },
        "scan-summaries": { icon: TbReportSearch, label: "Battle Reports" },
        "auto-downloader": { icon: LuRss, label: "New PokÃ©mon Alert" },
        "community": { icon: GiTrophyCup, label: "Trainer Club" },
        "achievements": { icon: GiTrophyCup, label: "League Badges" },
        "milestones": { icon: LuFlag, label: "Journey Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Trainer Alerts" },
        "theme-manager": { icon: GiPalette, label: "Type Colors" },
        "extensions": { icon: BiExtension, label: "TM Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "PC Box Sync" },
        "settings": { icon: GiSettingsKnobs, label: "PC Config" },
    },
    achievementNames: {
        "a_first_episode": "First Catch",
        "a_first_complete": "Badge Earned",
        "a_hundred_club": "Hundred Caught",
        "a_time_lord": "PokÃ©mon Master",
        "a_binge_king": "PokÃ©mon Marathon",
        "a_completionist": "PokÃ©dex Complete",
        "a_mega_completionist": "Champion Trainer",
        "a_zero_to_hero": "Pallet Town to Champion",
        "a_loyal_fan": "Loyal Trainer",
        "a_night_owl": "Nighttime Encounter",
        "m_first_chapter": "First Chapter Read",
        "m_completionist": "Full PokÃ©dex Read",
        "m_loyal_reader": "Loyal Manga Trainer",
    },
    musicUrl: "",
    previewColors: {
        bg: "#080400",
        primary: "#dc8a00",
        secondary: "#cc0000",
        accent: "#3366cc",
    },
    particleColor: "#f8a800",
    backgroundDim: 0.25,
    backgroundBlur: 10,
    particleTypes: {
        sparkles: { label: "Sparkles", maxCount: 16, defaultEnabled: true, defaultIntensity: 55 },
        pokeflash: { label: "PokÃ© Flash", maxCount: 5, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
        1:   "New Trainer",
        8:   "Gym Challenger — Badge 1",
        14:  "Badge Collector — 2",
        21:  "Badge Collector — 3",
        28:  "Badge Collector — 4",
        35:  "Badge Collector — 5",
        41:  "Badge Collector — 6",
        48:  "Badge Collector — 7",
        55:  "Badge Collector — 8",
        61:  "Elite Four Challenger",
        68:  "Elite Four — Cleared",
        75:  "Regional Champion",
        81:  "Champion — Kanto",
        88:  "Champion — Johto",
        95:  "Champion — Hoenn",
        102: "Champion — Sinnoh",
        108: "Champion — Unova",
        115: "Champion — Kalos",
        122: "Champion — Alola",
        128: "Champion — Galar",
        135: "Champion — Paldea",
        142: "Master Class — World Coronation",
        149: "Ultra Class",
        155: "Super Class",
        162: "Normal Class",
        169: "World Coronation Champion",
        175: "World Champion",
        182: "Rookie Coordinator",
        189: "Coordinator",
        195: "Top Coordinator",
        202: "Grand Festival Champion",
        209: "Contest Master",
        216: "PokÃ©mon Ranger",
        222: "PokÃ©mon Ranger — Top",
        229: "Battle Frontier Brain",
        236: "Frontier Brain — Defeated",
        242: "PokÃ©mon Professor",
        249: "PokÃ©dex — Completed",
        256: "PokÃ©dex — National",
        262: "Living PokÃ©dex",
        269: "Shiny Hunter",
        276: "Shiny — Found",
        283: "Legendary — Caught",
        289: "Mythical — Caught",
        296: "Ultra Beast — Caught",
        303: "Paradox — Caught",
        309: "Titan — Defeated",
        316: "Path of Legends",
        323: "Starfall Street",
        330: "Victory Road",
        336: "Team Rocket — Defeated",
        343: "Team Magma — Defeated",
        350: "Team Aqua — Defeated",
        356: "Team Galactic — Defeated",
        363: "Team Plasma — Defeated",
        370: "Team Flare — Defeated",
        376: "Team Skull — Defeated",
        383: "Team Yell — Defeated",
        390: "Team Star — Defeated",
        397: "Team GO Rocket — Defeated",
        403: "Elite Four — All Versions",
        410: "All Champions — Defeated",
        417: "Ash Ketchum — Goal",
        423: "Ash — Alola Champion",
        430: "Ash — World Champion",
        437: "Goh — Legendary Caught",
        444: "Dawn — Grand Festival",
        450: "May — Grand Festival",
        457: "Brock — Doctor",
        464: "Misty — Gym Leader",
        470: "Serena — Kalos Queen",
        477: "Iris — Unova Champion",
        484: "Clemont — Inventor",
        490: "Lillie — Trainer",
        497: "Lana — Legendary Trial",
        504: "Kiawe — Fire Trial",
        511: "Mallow — Grass Trial",
        517: "Sophocles — Electric Trial",
        524: "Trial Captain",
        531: "Island Kahuna",
        537: "Grand Trial — Cleared",
        544: "Z-Crystal — Obtained",
        551: "Z-Move — Mastered",
        557: "Mega Evolution — Mastered",
        564: "Dynamax — Mastered",
        571: "Gigantamax — Mastered",
        578: "Terastallization — Mastered",
        584: "Synchro Evolution",
        591: "Alpha PokÃ©mon — Tamed",
        598: "Noble PokÃ©mon — Calmed",
        604: "Hisui Region — Explored",
        611: "PokÃ©mon Origins",
        618: "PokÃ©mon Origins — Understood",
        625: "Legendary Trio — Caught",
        631: "Legendary Quartet — Caught",
        638: "Legendary Duo — Caught",
        645: "Mascot Legendary — Caught",
        651: "Cover Legendary — Caught",
        658: "God PokÃ©mon — Seen",
        665: "Arceus — Encountered",
        671: "Arceus — Caught",
        678: "Dialga — Caught",
        685: "Palkia — Caught",
        692: "Giratina — Caught",
        698: "Rayquaza — Caught",
        705: "Mewtwo — Caught",
        712: "Mew — Found",
        718: "Celebi — Found",
        725: "Jirachi — Found",
        732: "Deoxys — Caught",
        739: "Darkrai — Caught",
        745: "Shaymin — Found",
        752: "Victini — Found",
        759: "Reshiram — Caught",
        765: "Zekrom — Caught",
        772: "Kyurem — Caught",
        779: "Xerneas — Caught",
        785: "Yveltal — Caught",
        792: "Zygarde — Caught",
        799: "Cosmog — Found",
        806: "Solgaleo — Caught",
        812: "Lunala — Caught",
        819: "Necrozma — Caught",
        826: "Eternatus — Caught",
        832: "Calyrex — Caught",
        839: "Miraidon — Caught",
        846: "Koraidon — Caught",
        852: "All Legendaries — Caught",
        859: "All Mythicals — Caught",
        866: "PokÃ©dex — All Forms",
        873: "National Champion — All Regions",
        879: "World Champion — Undefeated",
        886: "PokÃ©mon Master — Approached",
        893: "PokÃ©mon Master — Claimed",
        899: "Grand Champion",
        906: "PokÃ©mon God",
        913: "Legendary Trainer",
        920: "Champion of Champions",
        926: "All Regions — Champion",
        933: "World Tournament — Won",
        940: "PokÃ©mon — All Caught",
        946: "Shiny PokÃ©dex — Complete",
        953: "Perfect IV PokÃ©dex",
        960: "All Ribbons — Collected",
        966: "All Contest Ribbons",
        973: "Battle Frontier — Complete",
        980: "All Battle Facilities — Won",
        987: "PokÃ©mon World — Complete",
        993: "PokÃ©mon Master — All",
        1000: "World Champion",
    },
}
