import { AnimeThemeConfig } from "./types"
import { GiCrossedSwords, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiCrystalBall, GiStarSwirl, GiAnvilImpact } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const texhnolyzeTheme: AnimeThemeConfig = {
    id: "texhnolyze",
    displayName: "Texhnolyze",
    description: "In the underground city of Lux, fighter Ichise loses his arm and leg in a brutal punishment — then receives texhnolyze cybernetic replacements. He is drawn into a brutal war between factions in a dying city.",
    cssVars: {
        "--color-brand-200": "195 195 210",
        "--color-brand-300": "155 155 175",
        "--color-brand-400": "112 112 138",
        "--color-brand-500": "75 75 105",
        "--color-brand-600": "48 48 75",
        "--color-brand-700": "28 28 50",
        "--color-brand-800": "12 12 26",
        "--color-brand-900": "4 4 12",
        "--color-brand-950": "1 1 5",
        "--brand": "75 75 105",
        "--background": "#030303",
        "--paper": "#080809",
        "--color-gray-950": "3 3 3",
        "--color-gray-900": "9 9 10",
        "--color-gray-800": "18 18 22",
        "--color-gray-700": "32 32 40",
        "--color-gray-600": "52 52 65",
        "--color-gray-500": "80 80 100",
        "--color-gray-400": "118 118 142",
        "--color-gray-300": "162 162 185",
        "--color-gray-200": "200 200 218",
        "--color-gray-100": "230 230 240",
        "--color-gray-50": "248 248 252",
    },
    sidebarOverrides: {
        "home": { icon: GiCrossedSwords, label: "Lux Underground" },
        "schedule": { icon: GiAlarmClock, label: "War Schedule" },
        "manga": { icon: LuBookOpen, label: "Faction Files" },
        "lists": { icon: GiScrollUnfurled, label: "Faction Registry" },
        "discover": { icon: GiBullseye, label: "New Enemies" },
        "torrent-list": { icon: GiAnvilImpact, label: "Weapon Cache" },
        "debrid": { icon: GiHeartKey, label: "Underground Vault" },
        "unmatched": { icon: GiCrystalBall, label: "Unknown Faction" },
        "enmasse": { icon: GiResize, label: "Faction War" },
        "scan-summaries": { icon: TbReportSearch, label: "War Reports" },
        "auto-downloader": { icon: LuRss, label: "Faction Feed" },
        "community": { icon: GiStarSwirl, label: "Lux Circle" },
        "achievements": { icon: GiTrophyCup, label: "Survivor Trophies" },
        "milestones": { icon: LuFlag, label: "Survival Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Danger Alerts" },
        "theme-manager": { icon: GiPalette, label: "Steel Colors" },
        "extensions": { icon: BiExtension, label: "Cyber Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Underground Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Ichise Config" },
    },
    achievementNames: {
        "a_first_episode": "Texhnolyze Received",
        "a_first_complete": "First Battle",
        "a_hundred_club": "Hundred Underground Days",
        "a_binge_king": "Texhnolyze Marathon",
        "a_completionist": "Lux's Champion",
        "a_mega_completionist": "Underground Complete",
        "a_loyal_fan": "Underground Fan",
        "a_zero_to_hero": "Victim to Weapon",
        "m_first_chapter": "First Limb",
        "m_completionist": "Full Archive",
    },
    musicUrl: "",
    previewColors: {
        bg: "#030303",
        primary: "#4b4b69",
        secondary: "#882222",
        accent: "#c8c8e0",
    },
    particleColor: "#808090",
    backgroundDim: 0.45,
    backgroundBlur: 25,
    milestoneNames: {
        1: "Texhnolyze Received",
        5: "Lux Fighter",
        15: "Faction Pawn",
        30: "Lux's Weapon",
        50: "Key Player",
        75: "City's Fate",
        100: "Lux's End",
    },
}
