import { AnimeThemeConfig } from "./types"
import { GiImperialCrown, GiDragonHead, GiAncientSword, GiFlame, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiCastle } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const twelveKingdomsTheme: AnimeThemeConfig = {
    id: "twelve-kingdoms",
    displayName: "The Twelve Kingdoms",
    description: "Ordinary schoolgirl Yoko is suddenly transported to a mysterious world of twelve kingdoms where she must survive, grow, and eventually become a true ruler worthy of the throne.",
    fontFamily: "'Noto Serif JP', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "195 230 175",
        "--color-brand-300": "148 205 128",
        "--color-brand-400": "100 178 82",
        "--color-brand-500": "60 150 42",
        "--color-brand-600": "38 120 26",
        "--color-brand-700": "22 90 14",
        "--color-brand-800": "12 62 8",
        "--color-brand-900": "6 36 4",
        "--color-brand-950": "2 20 2",
        "--brand": "60 150 42",
        "--background": "#010601",
        "--paper": "#050e04",
        "--color-gray-950": "1 6 1",
        "--color-gray-900": "4 12 4",
        "--color-gray-800": "8 22 8",
        "--color-gray-700": "14 38 14",
        "--color-gray-600": "24 60 24",
        "--color-gray-500": "40 90 40",
        "--color-gray-400": "72 130 72",
        "--color-gray-300": "112 170 112",
        "--color-gray-200": "155 200 155",
        "--color-gray-100": "192 224 192",
        "--color-gray-50": "228 242 228",
    },
    sidebarOverrides: {
        "home": { icon: GiCastle, label: "Kingdom" },
        "schedule": { icon: GiAlarmClock, label: "Court Schedule" },
        "manga": { icon: LuBookOpen, label: "Kingdom Records" },
        "lists": { icon: GiImperialCrown, label: "Ruler Registry" },
        "discover": { icon: GiBullseye, label: "Kingdom Recon" },
        "torrent-list": { icon: GiAncientSword, label: "Army Cache" },
        "debrid": { icon: GiDragonHead, label: "Dragon Network" },
        "unmatched": { icon: GiFlame, label: "Unknown Realms" },
        "enmasse": { icon: GiResize, label: "Kingdom Deploy" },
        "scan-summaries": { icon: TbReportSearch, label: "Court Records" },
        "auto-downloader": { icon: LuRss, label: "Kingdom News" },
        "community": { icon: GiImperialCrown, label: "Twelve Kingdoms" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Court Bells" },
        "achievements": { icon: GiTrophy, label: "Ruler Titles" },
        "milestones": { icon: LuFlag, label: "Kingdom Goals" },
        "theme-manager": { icon: GiPalette, label: "Kingdom Colors" },
        "extensions": { icon: BiExtension, label: "Kingdom Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Kingdom Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Court Settings" },
    },
    achievementNames: {
        "a_first_episode": "Kirin Appears",
        "a_first_complete": "Kingdom Ruled",
        "a_hundred_club": "Hundred Reigns",
        "a_time_lord": "Eternal Ruler",
        "a_anime_collector": "Kingdom Cache",
        "a_library_legend": "Royal Archives",
        "a_binge_king": "Kingdom Marathon",
        "a_no_sleep": "All-Night Ruling",
        "a_marathon_runner": "Twelve Journey",
        "a_speed_run": "Fast Ascent",
        "a_completionist": "All Kingdoms",
        "a_mega_completionist": "Ono Master",
        "a_loyal_fan": "Yoko's Path",
        "a_rewatcher": "Kingdom Revisit",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Kingdom War",
        "a_genre_adventure": "Twelve Journey",
        "a_genre_comedy": "Youko's Struggles",
        "a_genre_drama": "Royal Drama",
        "a_genre_fantasy": "Twelve Kingdoms",
        "a_genre_horror": "Kingdom Terror",
        "a_genre_romance": "Youko's Heart",
        "a_genre_scifi": "Kirin Biology",
        "a_genre_supernatural": "Kirin Power",
        "a_genre_psychological": "Ruler's Burden",
        "a_genre_mecha": "None Here",
        "a_critic": "Kingdom Judge",
        "a_perfect_ten": "Perfect Reign",
        "a_harsh_critic": "Strict Ruler",
        "a_daily_streak": "Daily Ruling",
        "a_mega_streak": "Eternal Reign",
        "a_year_long": "Year of Kingdoms",
        "a_iron_will": "Youko's Will",
        "a_hidden_gem": "Hidden Kingdom",
        "a_cult_classic": "Ono Classic",
        "a_classic_connoisseur": "2002 Fan",
        "a_new_years_resolution": "New Year Reign",
        "a_christmas_special": "Winter Kingdom",
        "a_meta_tier_max": "Supreme Ruler",
        "a_meta_completionist": "All Kingdoms",
        "a_sequel_chain": "Ono Novels",
        "a_zero_to_hero": "Student to Ruler",
        "a_night_owl": "Night Court",
        "a_early_bird": "Dawn Ruling",
        "m_first_chapter": "First Realm",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Kingdom Marathon",
        "m_completionist": "Full Saga",
        "m_mega_completionist": "Kingdom Expert",
        "m_loyal_reader": "Royal Reader",
        "m_rereader": "Kingdom Revisit",
        "m_genre_action": "War Chapter",
        "m_genre_adventure": "Journey Chapter",
        "m_genre_romance": "Heart Chapter",
        "m_genre_fantasy": "Kingdom Chapter",
        "m_genre_horror": "Dark Chapter",
        "m_genre_drama": "Court Drama",
        "m_genre_scifi": "Kirin Chapter",
        "m_genre_supernatural": "Power Chapter",
        "m_genre_psychological": "Burden Chapter",
        "m_critic": "Kingdom Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Kingdom Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Ruler Resolve",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Classic Novel",
        "m_mangaka_lover": "Ono Fan",
        "m_source_material_fan": "Novel First",
        "m_meta_tier_max": "All Kingdoms",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Kingdom Art",
        "m_manga_to_anime": "Novel Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#010601",
        primary: "#3c962a",
        secondary: "#26781a",
        accent: "#c89030",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/twelve-kingdoms.jpg",
    particleColor: "#70d060",
    backgroundDim: 0.35,
    backgroundBlur: 18,
    particleTypes: {
        leaves: { label: "Kingdom Leaves", maxCount: 18, defaultEnabled: true, defaultIntensity: 55 },
        kirin_light: { label: "Kirin Light", maxCount: 10, defaultEnabled: true, defaultIntensity: 50 },
    },
    milestoneNames: {
        1: "Ordinary Student",
        5: "Youko",
        15: "Kirin's Chosen",
        30: "Kingdom Traveler",
        50: "Ascending Ruler",
        75: "Kingdom Ruler",
        100: "Blessed Sovereign",
    },
}
