import { AnimeThemeConfig } from "./types"
import { GiFlowerEmblem, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiCrystalBall, GiStarSwirl, GiSpellBook } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const wolfChildrenTheme: AnimeThemeConfig = {
    id: "wolf-children",
    displayName: "Wolf Children",
    description: "A college student falls in love with a wolf-man and bears two children — Ame and Yuki — who can transform between human and wolf form. After their father's death, she raises them alone in the mountains.",
    cssVars: {
        "--color-brand-200": "195 228 200",
        "--color-brand-300": "145 205 152",
        "--color-brand-400": "92 175 105",
        "--color-brand-500": "50 142 65",
        "--color-brand-600": "20 108 30",
        "--color-brand-700": "5 72 10",
        "--color-brand-800": "1 44 3",
        "--color-brand-900": "0 22 1",
        "--color-brand-950": "0 8 0",
        "--brand": "50 142 65",
        "--background": "#000400",
        "--paper": "#010a01",
        "--color-gray-950": "0 4 0",
        "--color-gray-900": "1 10 1",
        "--color-gray-800": "3 22 4",
        "--color-gray-700": "6 38 8",
        "--color-gray-600": "10 62 14",
        "--color-gray-500": "18 96 22",
        "--color-gray-400": "35 138 40",
        "--color-gray-300": "65 178 72",
        "--color-gray-200": "108 215 115",
        "--color-gray-100": "162 240 168",
        "--color-gray-50": "215 252 220",
    },
    sidebarOverrides: {
        "home": { icon: GiFlowerEmblem, label: "Mountain Home" },
        "schedule": { icon: GiAlarmClock, label: "Family Schedule" },
        "manga": { icon: LuBookOpen, label: "Family Journal" },
        "lists": { icon: GiScrollUnfurled, label: "Family List" },
        "discover": { icon: GiBullseye, label: "New Adventures" },
        "torrent-list": { icon: GiStarSwirl, label: "Nature Cache" },
        "debrid": { icon: GiHeartKey, label: "Family Vault" },
        "unmatched": { icon: GiCrystalBall, label: "Wild Unknown" },
        "enmasse": { icon: GiResize, label: "Village Life" },
        "scan-summaries": { icon: TbReportSearch, label: "Family Reports" },
        "auto-downloader": { icon: LuRss, label: "Nature Feed" },
        "community": { icon: GiSpellBook, label: "Wolf Circle" },
        "achievements": { icon: GiTrophyCup, label: "Family Trophies" },
        "milestones": { icon: LuFlag, label: "Growth Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Family Alerts" },
        "theme-manager": { icon: GiPalette, label: "Forest Colors" },
        "extensions": { icon: BiExtension, label: "Wolf Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Family Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Hana Config" },
    },
    achievementNames: {
        "a_first_episode": "Wolf Children Born",
        "a_first_complete": "First Year Survived",
        "a_hundred_club": "Hundred Mountain Days",
        "a_binge_king": "Wolf Children Marathon",
        "a_completionist": "Children Grown",
        "a_mega_completionist": "Mother's Journey",
        "a_loyal_fan": "Nature Fan",
        "a_zero_to_hero": "Alone to Complete",
        "m_first_chapter": "First Day",
        "m_completionist": "Full Archive",
    },
    musicUrl: "",
    previewColors: {
        bg: "#000400",
        primary: "#328e41",
        secondary: "#884028",
        accent: "#c8f0c0",
    },
    particleColor: "#50b058",
    backgroundDim: 0.25,
    backgroundBlur: 18,
    milestoneNames: {
        1: "Single Mother",
        5: "Mountain Move",
        15: "Village Accepted",
        30: "Children Growing",
        50: "Ame's Choice",
        75: "Yuki's Path",
        100: "Mother's Love",
    },
}
