import { AnimeThemeConfig } from "./types"
import { GiRunningShoe, GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled, GiHeartKey, GiCrystalBall, GiStarSwirl, GiRoad } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const yowamushiPedalTheme: AnimeThemeConfig = {
    id: "yowamushi-pedal",
    displayName: "Yowamushi Pedal",
    description: "Otaku Sakamichi Onoda commutes 45km to school on a mamachari to get to Akihabara. Discovered by cycling enthusiasts, he joins the road racing club and his incredible natural climbing ability astounds everyone.",
    cssVars: {
        "--color-brand-200": "175 210 255",
        "--color-brand-300": "115 172 248",
        "--color-brand-400": "62 130 235",
        "--color-brand-500": "22 90 208",
        "--color-brand-600": "6 58 168",
        "--color-brand-700": "1 34 122",
        "--color-brand-800": "0 16 76",
        "--color-brand-900": "0 6 40",
        "--color-brand-950": "0 2 18",
        "--brand": "22 90 208",
        "--background": "#000208",
        "--paper": "#000414",
        "--color-gray-950": "0 2 8",
        "--color-gray-900": "1 6 18",
        "--color-gray-800": "3 14 35",
        "--color-gray-700": "6 26 58",
        "--color-gray-600": "11 46 92",
        "--color-gray-500": "20 76 132",
        "--color-gray-400": "42 116 170",
        "--color-gray-300": "78 156 208",
        "--color-gray-200": "122 192 235",
        "--color-gray-100": "175 220 250",
        "--color-gray-50": "222 242 255",
    },
    sidebarOverrides: {
        "home": { icon: GiRoad, label: "Sohoku High" },
        "schedule": { icon: GiAlarmClock, label: "Race Schedule" },
        "manga": { icon: LuBookOpen, label: "Race Log" },
        "lists": { icon: GiScrollUnfurled, label: "Team Roster" },
        "discover": { icon: GiBullseye, label: "New Rivals" },
        "torrent-list": { icon: GiRunningShoe, label: "Gear Cache" },
        "debrid": { icon: GiHeartKey, label: "Club Vault" },
        "unmatched": { icon: GiCrystalBall, label: "Unknown Routes" },
        "enmasse": { icon: GiResize, label: "Inter-High" },
        "scan-summaries": { icon: TbReportSearch, label: "Race Reports" },
        "auto-downloader": { icon: LuRss, label: "Race Feed" },
        "community": { icon: GiStarSwirl, label: "Cycling Circle" },
        "achievements": { icon: GiTrophyCup, label: "Podium Trophies" },
        "milestones": { icon: LuFlag, label: "Summit Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Race Alerts" },
        "theme-manager": { icon: GiPalette, label: "Road Colors" },
        "extensions": { icon: BiExtension, label: "Bike Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Race Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Onoda Config" },
    },
    achievementNames: {
        "a_first_episode": "First Climb",
        "a_first_complete": "First Race Done",
        "a_hundred_club": "Hundred KM",
        "a_binge_king": "Yowapeda Marathon",
        "a_completionist": "Inter-High Complete",
        "a_mega_completionist": "King of the Mountain",
        "a_loyal_fan": "Pedalboard Fan",
        "a_zero_to_hero": "Otaku to Climber",
        "m_first_chapter": "First Gear",
        "m_completionist": "Full Race Archive",
    },
    musicUrl: "",
    previewColors: {
        bg: "#000208",
        primary: "#165ad0",
        secondary: "#cc3030",
        accent: "#a8d0f8",
    },
    particleColor: "#4088e0",
    backgroundDim: 0.28,
    backgroundBlur: 18,
    milestoneNames: {
        1: "Mamachari Rider",
        5: "Club Recruit",
        15: "Mountain Climber",
        30: "Inter-High Qualifier",
        50: "Team Ace",
        75: "Summit Champion",
        100: "King of the Mountain",
    },
}
